src/prefect/client/orchestration.py
src/prefect/client/schemas/objects.py
src/prefect/server/orchestration/core_policy.py
src/prefect/server/schemas/states.py
tests/server/api/test_flow_runs.py
tests/server/orchestration/test_core_policy.py
tests/workers/test_base_worker.py

closes: https://github.com/PrefectHQ/prefect/issues/10263 and https://github.com/PrefectHQ/prefect/issues/10263
This PR adds a new optional to field to `StateDetails` called `transition_id: UUID`. This is an optional field that the client can (and will by default) populate when calling `/set_state`. This PR also adds a new orchestration rule `PreventDuplicateTransitions`. This rule will reject the transition (returning the already set state) if the `transition_id` of the initial state and the proposed state are the same.
This allows us to make duplicate transitions aren't made, for example in the following scenario:
- Client makes a request to transition a flow run to `PENDING`
- Server accepts and commits the transition and returns a response
- Client never  fully receives the response …

prevent duplicate transitions

---

docs/concepts/tasks.md

This PR removes a warning about using task tag concurrency in subflows which I think no longer applies.
This was written two years ago. We made substantial improvements to our internal concurrency handling in the past year. And the following flow runs fine, even with some `sleep`s introduced to the task.
```
import asyncio
@task(tags=["limited"]) # This task will be limited to 2 concurrent runs
def add(x, y):
return x + y
@flow
async def my_async_subflow():
return add(1, 2)
@flow
async def async_parent_flow(n_subflows: int):
subflows = [my_async_subflow() for _ in range(n_subflows)]
await asyncio.gather(*subflows)
asyncio.run(async_parent_flow(n_subflows=1_000))
```
Let's see whether or not that Chesterton guy was onto something. …

Remove subflow task tag concurrency warning

---

docs/concepts/flows.md

This removes line from `Pausing a flow` docs saying you can `pause` from the UI, you're only able to _suspend_ from the UI, not pause.

Remove line from `Pausing a flow` docs saying you can `pause` from the UI

---

requirements-dev.txt

New versions of `pytest` and `moto` was just released that break our unit tests, temporarily pinning while we update the suite.
Related to #11750
Related to #11752

Temporarily pin `pytest` to < 8 and `moto` to < 5

---

src/prefect/server/services/scheduler.py
tests/server/services/test_scheduler.py

This updates the scheduler to only look at deployments that have active schedules when scheduling runs. 
OSS side of https://github.com/PrefectHQ/nebula/pull/6783

Only attempt to schedule runs for deployments that have active schedules

---

tests/utilities/test_importtools.py

This has been failing a lot recently, marking it as flaky for now.

Mark `test_import_object_from_script_with_relative_imports` as flaky

---

requirements-dev.txt
src/prefect/settings.py
src/prefect/workers/server.py
tests/runner/test_webserver.py

the `PREFECT_WORKER_WEBSERVER_HOST` and `...PORT` settings were erroneously deprecated in this [PR](https://github.com/PrefectHQ/prefect/pull/11476/files#diff-eb8a03a8ac41aec52fe38a471a96a468ffba04db74fb97149c65f9ee1efd2266R49) such the default host for the worker's webserver went from `0.0.0.0` to `localhost`

revert deprecation of worker webserver setting

---

docs/concepts/schedules.md

Interval schedules use an anchor date, which is a fixed point in time from which to compute intervals.  The use of **_from_** made it seem like a start date for the schedule.  This PR switches from to **_using_** to better fit the idea of an anchor date. 
Part of https://github.com/PrefectHQ/prefect/issues/11551

Clarify that interval schedules use an anchor not start date

---

RELEASE-NOTES.md

cutting an early patch release to get [this](https://github.com/PrefectHQ/prefect/pull/11758) fix out asap

prep `2.14.18`

---

tests/infrastructure/test_docker_container.py

This test is failing quite a bit even with the `flaky` decorator, this gives it 4 runs to pass.

Give `test_generate_work_pool_base_job_template` up to 4 runs to pass

---

src/prefect/input/run_input.py
tests/input/test_run_input.py

This adds a private `_description` field to `RunInput` and stores a provided description when saving the schema so the UI can grab it and display it in the resume modal.
Related to #11735
```
from prefect import flow, pause_flow_run
from prefect.input import RunInput
class TreeInput(RunInput):
kind: str
@flow
async def tree_flow():
await pause_flow_run(
wait_for_input=TreeInput.with_initial_data(
description="What kind of tree do you want to plant?"
)
)
```

Store description when saving a RunInput schema

---

src/prefect/client/subscriptions.py
src/prefect/server/api/task_runs.py
src/prefect/server/utilities/subscriptions.py

adds a retry queue for when tasks are submitted and there is no running `TaskServer`
empirically this solves the problem I described earlier:
- prefect server start
- run a TaskServer
- submit a task -> runs great :white-check-mark2:
- stop the TaskServer
- submit a task while no task server running
- start the TaskServer -> subscription created
- nothing gets picked up

Task subscription api retry queue

---

docs/guides/creating-interactive-workflows.md

Adds documentation for providing a description when pausing a flow run.
Related to #11735 

Add documentation on providing a description when pausing a flow run

---

src/prefect/engine.py
src/prefect/input/run_input.py
tests/input/test_run_input.py

This fixes the type hinting for automatic run inputs. Previously if you passed a `str` or anything else that wasn't a `RunInput` subclass into `pause_flow_run` or `receive_input` the type hint would come back as `Any`. This makes it so that those hints are accurate.
There is one caveat to this, if you pass in a pydantic model:
```python
class MyModel(pydantic.BaseModel):
name: str
value: str
...
input = await receive_input(MyModel).next()
```
`input` in this case will be hinted as a `MyModel` instance, which is _technically_ inaccurate. `input` will be a subclass of `RunInput` and `MyModel`. I chose to go this route rather than hinting that it was a generic `RunInput` class, but could be convinced that it makes sense the other way.
Closes #11792 
- If no issue exists and your change is …

Fix type hinting for automatic run inputs

---

src/prefect/server/api/task_runs.py
src/prefect/server/utilities/subscriptions.py
tests/server/api/test_task_run_subscriptions.py

Adds tests for autonomous task delivery over websockets, including restoring
scheduled tasks at initial startup.  These tests aim to cover all of the
behavior of the server-side socket and its protocol.
Note: the test suite here starts a "real" Prefect server concurrently with the
tests, because attemping to tests the websockets using `TestClient` resulted in
deadlocks and hangs.

Tests for autonomous task subscriptions

---

src/prefect/client/subscriptions.py
src/prefect/server/api/task_runs.py
src/prefect/task_server.py
tests/server/api/test_task_run_subscriptions.py
tests/test_autonomous_tasks.py

The goal here is for each subscriber to be able to filter to a subset of the
tasks they are interested in (i.e. which tasks a task server is serving).  This
required routing task runs into queues and monitoring multiple queues for
tasks.  This was a good opportunity to refactor some of the mechanics here to
capture the idea that a `TaskQueue` is really two queues (a "regular" queue and
a high-priority retry queue).  This led me down a path of tidying up the
implementation to remove globals and encapsulate more of the behavior.

Implementing task subscription filtering

---

scripts/install-with-latest-dependencies
setup.cfg

Suppresses a specific new `pluggy` warning causing flaky tests

---

requirements-dev.txt
tests/infrastructure/provisioners/test_ecs.py

As part of making our test suite a little better, this PR removes our pin on `moto<5` and updates our `test_ecs.py` tests to use the updated version coming in.

Remove our pin on moto and update tests

---

tests/test-projects/nested-project/explicit_relative.py
tests/test-projects/nested-project/implicit_relative.py
tests/test-projects/nested-project/shared_libs/bar.py
tests/test-projects/nested-project/shared_libs/foo.py
tests/test-projects/tree-project/imports/explicit_relative.py
tests/test-projects/tree-project/imports/implicit_relative.py
tests/test-projects/tree-project/shared_libs/bar.py
tests/test-projects/tree-project/shared_libs/foo.py
tests/utilities/test_importtools.py

Our `load_script_as_module` utility modifies the sys path to handle relative imports when loading scripts. This can cause issues when used concurrently. Some of the import tests flake because a relative import that should be a function instead is loaded as a module. This PR changes the names of those functions to avoid naming conflicts with other tests. This PR also adds additional assertions so we can get better information about where the conflict is coming from in the unlikely event it happens again.

Improve flaky import tests

---

src/prefect/server/api/task_runs.py
src/prefect/settings.py
tests/server/api/test_task_run_subscriptions.py

adds
```
PREFECT_TASK_SCHEDULING_MAX_SCHEDULED_QUEUE_SIZE
PREFECT_TASK_SCHEDULING_MAX_RETRY_QUEUE_SIZE
```
to govern max per-task-key queue sizes

[task scheduling] basic task run queue capacity settings

---

setup.cfg
tests/server/utilities/test_connection_leak_warnings.py

The tests here aren't intended to _fix_ the issue, just to make sure that we
are covering them with our warning filters.  This helps with reproducing the
issue locally.
Part of #11820

Trying to reproduce the connection leak issue that pluggy is warning about

---

requirements-dev.txt

Fixes #11836
Related to #11820

Being explicit that we need `pluggy>=1.4.0`

---

tests/_internal/concurrency/test_cancellation.py

Similar to previous work to remove timing dependencies, this test suite now
uses `completed` booleans to make the cancellation tests deterministic.

Making the internal concurrency cancellation tests deterministic

---

src/prefect/settings.py
ui/src/maps/featureFlag.ts
ui/src/types/flagResponse.ts
ui/src/utilities/permissions.ts

Adds a new setting to toggle on experimental work queue status flag. Toggling this flag on will enable a new incoming feature which will replace Work Queue Health metrics with a new Work Queue _Status_ similar to the recently introduced deployment statuses. More info to come soon 🙃 .

Add plumbing for toggling work queue status experimental flag.

---

tests/test_engine.py

Doing this in two flows ends up with 99% of the time a server side `CancelledError`, which we get from running the ephemeral api in process. The error we actually care about is `PausedRun` raised by the `suspendable_flow()`. The flake occurs the <1% of the time that `PausedRun` actually sneaks through first before the serve side error. 
To avoid this completely there is no reason the suspending function needs to be a flow so we just make it a plain function and catch our actual expected error.

de-flake suspend test

---

tests/server/models/test_orm.py

`estimated_run_time` is a server side calculation that uses `pendulum.now()` to estimate how much time has passed since the start of the run. We can't reliably say that `estimated_run_time` will _always_ be between 59-60 seconds here. This PR adds a little more tolerance to this test while keeping the spirit of what it is checking.

de-flake orm tests

---

.github/workflows/python-tests.yaml

to avoid these variety of errors uploading failure flags
```
With the provided path, there will be 1 file uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

more unique failure flag names

---

src/prefect/testing/utilities.py
tests/server/services/test_loop_service.py
tests/test_flows.py
tests/test_tasks.py

The windows test suite doesn't even run anymore, no reason to explicitly mark things there as flaky.

Remove `flaky_on_windows` helper

---

tests/cli/test_deploy.py
tests/deployment/test_base.py
tests/test-projects/flat-project/explicit_relative.py
tests/test-projects/flat-project/implicit_relative.py
tests/test-projects/flat-project/shared_libs.py

Further addresses flakiness in import tests. The `deploy` CLI tests change the working directory during the test setup. This PR updates those tests to use `tmpchdir` to ensure the working directory is changed back reliability to avoid interfering with the import object tests.

Improves reliability of import tests

---

tests/fixtures/docker.py

This PR updates our exception block to handle errors from `docker.errors`, It used to handle exceptions from  `docker.errors`, where `docker` was referring to an instance of a `DockerClient`, **NOT** the docker module. 
Closes #11855 

Use errors from docker.errors

---

tests/fixtures/docker.py
tests/test_flows.py

For all of these tests, we were depending on execution time to know if the
behavior was correct.  As with previous work, I'm replacing these with
deterministic assertions on a nonlocal `completed` variable.

Making test_flows.py deterministic

---

tests/test_engine.py

Removes `mark.flaky` decorators from engine suite and de-flakes corresponding tests.

De-flaky `tests/test_engine.py`

---

.github/workflows/python-tests.yaml

We've seen a lot of failures attempting to upload our built images to the GithubActions Cache API. This PR updates our build and upload step to ignore failures resulting from cache uploads. This should let the CI continue without using cached images. The idea here is its better for the CI run to continue without a cached image than it is to crash if we can't cache anymore. 
Reference PRs:
- New feature - https://github.com/moby/buildkit/pull/3430

ft: adds GH option to ignore cache upload failures

---

.github/workflows/python-tests.yaml

In order to get cycle times for PRs down to reasonable levels, we're temporarily
dropping the PostgreSQL 13 and pydantic v1 tests.  We may be able to bring these
back in the future, but for now we need to focus on stability and cycle times.
I am also removing an apparently dead branch around installing the lower bounds
of all requirements.  We have support for this, but we haven't had it in the
matrix for some time.  Removing it for clarity.

Reducing the dimensions of the unit test matrix

---

tests/cli/test_agent.py

I do not believe we need this file to use the flaky marker anymore because we resolved this issue in the comment in a prior PR.

Remove flaky marker from `tests/cli/test_agent.py`

---

tests/runner/test_runner.py

This test has been through three prior iterations and is still popping up as
a flake in test suites.  Removing it.

Removing unstable flow cancellation test

---

flows/client_context_lifespan.py
tests/client/test_prefect_client.py

These tests are not really unit tests and are too flaky given the amount of threads they open up. This type of coverage in the unit test suite is not worth the flakiness.

remove flaky client tests

---

flows/client_context_lifespan.py

we run these for every major version of prefect, so we only want our vendored fastapi after 2.13.0

fix context tests

---

setup.cfg

There are a bunch of different errors that seem to be coming from the case where "a test case is taking longer than our 60 second pytest timeout value". These errors don't seem to be contained to a single test and seem to happen when you cancel a function mid-execution. This PR bumps the timeout from 60 to 90 to see if the extra time helps these tests successfully pass by themselves.
Potential fix for 
- https://github.com/orgs/PrefectHQ/projects/123/views/1?pane=issue&itemId=52401111
- https://github.com/orgs/PrefectHQ/projects/123/views/1?pane=issue&itemId=52262606
- https://github.com/orgs/PrefectHQ/projects/123/views/1?pane=issue&itemId=52263841
- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) …

Adds longer timeout to help prevent flakes

---

tests/fixtures/database.py

retry loop during db teardown in global fixture `clear_db`

---

tests/server/models/test_block_documents.py

closes [#11896](https://github.com/PrefectHQ/prefect/issues/11896)
ran a bunch with `--flake-finder`

deflaky `test_read_block_documents_limit_offset`

---

tests/test_engine.py

Fixes a race condition in the tests where flow resume runs too quickly - after the pausing flow is paused but before the input schema is saved.
When a flow is paused, the client updates the status and _then_ the run input schema is saved. If the test's flow resumer picks up that the flow run is now paused _before_ the run input schema saves, then the test flakes and fails. This PR is to resolve that issue by having the flow resumer wait for the input schema to exist before resuming the flow run.

Fix flaky test_engine.py::TestBlockingPause tests

---

tests/_internal/concurrency/test_cancellation.py

Closes #11890 
For some reason, this test will sometimes get scheduled not on the `MainThread`. When that happens, the parameterization with `AlarmCancelScope` fails. This fix isolates the `AlarmCancelScope` test case to only enter its context if it is on the main thread. The parts of the test that don't depend on entering the context will still run.

Isolate alarm based thread test

---

.github/workflows/python-tests.yaml

I changed my mind on this, because if we don't see the checks fail, it may be
confusing to see a failure in DD that doesn't correspond with a failure on
`main`, and we should have enough confidence that our test suite will pass to
include an additional run of it.

We should actually fail checks of the DataDog visibility tests fail

---

src/prefect/server/database/configurations.py

We use this setting in Prefect Cloud to great effect, it ensures that a
connection is actually connected at the point of pool checkout.  This should
resolve the transient `connection is closed` errors and also improve the
stability of running Prefect servers and the ephemeral API with PostgreSQL.

Using `pool_pre_ping` to ensure that our PostgreSQL connections are connected

---

.github/workflows/python-tests.yaml

Higher than 6 doesn't gain us much, and can be slower in outlier cases

Test different maxprocesses values

---

tests/conftest.py
tests/utilities/test_importtools.py

The issue here was that the `cli/test_deploy.py` tests were also importing these `shared_lib` functions which got cached in `sys.modules`, but we weren't invalidating the cache during those tests. This makes the invalidation fixture a global autouse.

Invalidate `sys.modules` cache after each test

---

tests/cli/deployment/test_deployment_build.py

Remove a lot of stray files that are created during test running including `.prefectignore`, `.py` flow files and deployment `.yaml`s

remove stray file creation from tests

---

docker-compose.yml
setup.cfg
src/prefect/server/database/configurations.py
tests/cli/deployment/test_deployment_cli.py
tests/fixtures/database.py

This adds a tracking utility that observes all connections produced by our
engine's pools, allowing us to make assertions and clean them up at the end of
a test session.  This utility helps to avoid a `ResourceWarning` about
connections being cleaned up with `__del__` instead of being deliberately
closed, because it keeps a reference to all connections (open or closed) until
we can dispose of the engines and all the pooled connections deliberately.
The utility is only active during unit tests, when `TRACKER.active` is set, so
we shouldn't have concerns about memory use in long-running servers.
Fixes #11820

Tracking connections process-wide for test assertions

---

.github/workflows/python-tests.yaml

Now that we've removed `flaky` we should no longer recommend marking tests as flaky but instead to fix or remove them.

Update failing tests notification

---

src/prefect/events/utilities.py
src/prefect/events/worker.py
src/prefect/testing/fixtures.py
tests/concurrency/test_concurrency_asyncio.py
tests/concurrency/test_concurrency_sync.py
tests/events/conftest.py

We observed instances of tests timing out with `Failed: Timeout >90.0s` trying to get an instance of `EventsWorker` and starting it in the global loop thread. Before this pr, calling fixtures that had blocks in them (with `.save()`) would try and instantiate a null client.
There is definitely something up with calling `QueueService.instance` and it timing out, however it is very difficult to debug. For now we can at least cut down on places we're calling `.instance` in tests by short circuiting if we're not hooked up to cloud or not testing events explicitly. 
```
/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/asyncio/base_events.py:653: in run_until_complete
return future.result()
/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/pytest_asyncio/plugin.py:323: in …
```

don't get an instance if we don't need one

---

tests/server/models/test_block_schemas.py

A couple of the fields are lists in this test. The test can flake due to the order of what's in these lists. For our purposes it really doesn't matter so just compare the fields very explicitly.

fix ordering in `test_read_block_schema_with_union`

---

tests/infrastructure/test_docker_container.py

When running in parallel, it's possible that more than one test is trying to
create the `test-name` container (in the other test trying to test for name
collisions) and we'll end up with `test-name-1` here.  Giving it a fully unique
name sorts this out.

Fixing test flake in Docker container naming

---

requirements-client.txt
requirements.txt
src/prefect/_internal/concurrency/api.py
src/prefect/_internal/concurrency/calls.py
src/prefect/_internal/concurrency/threads.py
src/prefect/engine.py
tests/conftest.py
tests/test_engine.py
tests/test_task_server.py
tests/test_tasks.py

This is a new version of #9855 rebased onto [`main`](https://github.com/PrefectHQ/prefect/tree/main) now that the upstream issue in greenback (https://github.com/oremanj/greenback/issues/22) preventing this from working with ephemeral servers is resolved. This no longer requires ugly hacks like https://github.com/PrefectHQ/prefect/pull/9870 to avoid greenlet contamination. The following description is mostly copied from the old pull request. I have no idea if this would interact with or is relevant for new work regarding "autonomous" tasks e.g. https://github.com/PrefectHQ/prefect/pull/11779
-----
When feasible, task runs are now executed on the main thread instead of a worker thread. Previously, all task runs were run in a new worker thread. This should significantly improve performance …

Run tasks on the main thread

---

src/prefect/client/subscriptions.py
src/prefect/server/api/task_runs.py
src/prefect/server/utilities/subscriptions.py
tests/server/api/test_task_run_subscriptions.py
tests/software/test_conda.py

These had been disabled while we were looking for test flake culprits, but they
should be okay to run.

Bring back the task subscription API tests

---

.github/workflows/python-tests.yaml

We had been splitting off a set of tests we called the "services" tests, which
includes running some more invovled tests with the process and docker infra.
This only splits off 53 tests from the 8k test suite, so the overhead of a full
separate leg of the checks seems unnecessary.  We aren't skipping them for the
pydantic, sqlalchemy, and datadog tests, and they all seem to run just fine as
a unifed suite.

Run the full test suite in each leg of the matrix

---

tests/fixtures/database.py

If we see any more flakes with this, I'll just remove the inspection of
connections here, because we're "fixing" this by suppressing warnings around
these stray connections.

Actually close stray connections at test session shutdown

---

src/prefect/server/database/migrations/versions/postgresql/2024_01_22_120615_8cf4d4933848_create_deployment_schedule_and_add_.py
src/prefect/server/database/migrations/versions/sqlite/2024_01_22_120214_265eb1a2da4c_create_deployment_schedule_and_add_.py
src/prefect/server/models/deployments.py

In Cloud we noticed issues where the backfilled schedule was `'null'`, we've since removed these cases in Cloud, but need to replicate that change to this feature branch.
Related to https://github.com/PrefectHQ/nebula/issues/6706

Exclude schedules from backfill that have a value of `'null'`

---

src/prefect/client/subscriptions.py
src/prefect/engine.py
src/prefect/task_engine.py

following #11930 , we need to include `user_thread` in `submit_autonomous_task_to_engine`

update minimum viable flow run context to include `user_thread`

---

src/prefect/settings.py
tests/_internal/compatibility/test_experimental.py
tests/server/test_app.py

This PR changes the default value for our feature flag enabling `WorkQueue` status indicators in the UI. 
There is no need to enable work queue status via environment variables, just start the server:
```
❯ prefect server start
___ ___ ___ ___ ___ ___ _____
| _ \ _ \ __| __| __/ __|_   _|
|  _/   / _|| _|| _| (__  | |
|_| |_|_\___|_| |___\___| |_|
Configure Prefect to communicate with the server with:
prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api
View the API reference documentation at http://127.0.0.1:4200/docs
Check out the dashboard at http://127.0.0.1:4200
```
And enjoy the new status indicators:
For …

Enable work queue status in the UI by default

---

src/prefect/server/orchestration/core_policy.py
src/prefect/task_engine.py
src/prefect/task_server.py
tests/server/api/test_task_runs.py
tests/server/orchestration/test_core_policy.py

based on discussion, we should:
- have autonomous task runs go from `SCHEDULED` -> `PENDING` -> `RUNNING`
- prevent `PENDING` -> `PENDING` (using the existing `PreventPendingTransitions` rule) instead of `RUNNING` -> `RUNNING`

[task scheduling] add intermediate `Pending` state and update policy

---

docs/guides/settings.md

Improve language and formatting in Profiles and Configuration guide

---

.pre-commit-config.yaml
requirements-dev.txt

In their README, they recommend putting putting the linter with `--fix` first,
before the formatter.

Switching to the astral-sh pre-commit hook

---

docs/guides/creating-interactive-workflows.md

A blank code field was rendering toward the bottom of the page. 

Updates formatting for guide: creating-interactive-workflows.md

---

src/prefect/cli/work_queue.py
tests/cli/test_work_queues.py

This PR adds a CLI command to make it easy to read the runs off of a work queue:
```
❯ prefect work-queue read-runs --pool local-process-wp local-wq-2
Read 0 runs for work queue 'local-wq-2' in work pool local-process-wp: []
```
My main use case was simulating a worker/agent poll to a work queue to simulate work queue status events. The command was useful during testing and I can image it being useful to test other work queue status related things (i.e. automations, events). Note that running this command is equivalent to a worker polling a work queue and may lead to a temporary false positive where it looks like "something is polling for work" but it was just a one time command.  …

Add CLI command to read runs in WQ

---

docs/concepts/artifacts.md

This PR removes the following extraneous trailing quotation marks from the artifacts documentation page.
| **Section** | **Screenshot** |
| Creating link artifacts | <img width="1032" alt="image" src="https://github.com/PrefectHQ/prefect/assets/22418768/4384b01b-c379-4853-8133-e5d765cee41c"> |
| Creating Markdown artifacts | <img width="1029" alt="image" src="https://github.com/PrefectHQ/prefect/assets/22418768/93a3e47f-9b6c-4a0b-a4f5-08510c0162f6"> |
| Creating table artifacts | <img width="1042" alt="image" src="https://github.com/PrefectHQ/prefect/assets/22418768/f1cae02e-e134-457c-8eb0-9328c73b1ca9"> |
For documentation …

Remove extraneous trailing quotation marks in concepts/artifacts docs

---

tests/agent/test_agent_run_cancellation.py
tests/agent/test_agent_run_submission.py
tests/cli/test_deploy.py
tests/conftest.py
tests/fixtures/database.py
tests/server/api/test_work_queues.py
tests/server/models/test_filters.py
tests/test_flows.py
tests/workers/test_base_worker.py

Updates the `clear_db` fixture to clear the test DB **before** running a test to make it more intuitive for individual tests.
Excludes `test/agents` from DB clearing to slightly decrease the test running time and makes the changes necessary to get the tests to pass.

Update `clear_db` to clear the DB before running a test

---

src/prefect/server/api/deployments.py
tests/server/api/test_deployment_schedules.py

OSS side of https://github.com/PrefectHQ/nebula/pull/6982
Ensures that when we update schedules we also clear out any runs created by those schedules.

Remove scheduled flow runs when updating/removing schedules

---

src/prefect/utilities/dockerutils.py
tests/utilities/test_importtools.py

When deploying using a Docker image we get an unclear error in case Docker is not running on the local machine.
Added a more readable error Runtime Exception: `Docker is not running. please run docker and try again`

Adding a more readable error in case Docker not running 

---

src/prefect/client/subscriptions.py
src/prefect/task_server.py
tests/test_task_server.py

for task scheduling in cloud, it'd be helpful if we have a unique websocket client id to refer to a given `TaskServer` / consumer
so we add a client id property to `TaskServer` like `{socket.gethostname()}-{os.getpid()}` that reads settings from its `_client`

[task scheduling] send up client id if cloud

---

src/prefect/logging/filters.py
src/prefect/logging/loggers.py
tests/test_logging.py

On rare occasions, unexpected crashes in task runners can sometimes lead to log dumps that include all configurations, including the current API key. This PR adds a logging filter to prevent inadvertently logging the current Prefect API key.
Running this flow:
```python
from prefect.settings import PREFECT_API_KEY
def my_treacherous_flow():
print(PREFECT_API_KEY.value())
my_treacherous_flow()
```
will log this in the console:
and log this in the UI:

Add logging filter to prevent logging the current Prefect API key

---

src/prefect/cli/work_pool.py

While looking into work pool CLI, I realized I was trying to inspect a work pool in the wrong prefect profile. It would be nice to surface an error.
Current:
```bash
❯ prefect work-pool inspect <nonexistent-wp>
```
(no output)
With fix:
```bash
❯ prefect work-pool inspect <nonexistent-wp>
Work pool 'local-work' not found!
```

Surface work pool not found error

---

src/prefect/server/database/query_components.py
src/prefect/server/models/flow_runs.py
src/prefect/server/schemas/graph.py
src/prefect/settings.py
tests/server/api/test_flow_run_graph_v2.py

This PR introduces 2 new settings:
- `PREFECT_EXPERIMENTAL_ENABLE_ARTIFACTS_ON_FLOW_RUN_GRAPH` - an opt-in flag to enable new behavior as described below. NOTE: when this is OFF, the graph response still includes both the top-level artifacts key as well as on each node but their values are empty arrays and the underlying data fetching is skipped. 
- `PREFECT_API_MAX_FLOW_RUN_GRAPH_ARTIFACTS` - an `int` setting to allow a user to set an upper limit on the # of artifacts that can load into the graph. At the moment, the default is quite high but this gives a user the ability to tune it down if they were to run into issues.
This PR makes flow run artifact data available on the graph-v2 route to enable consumption by the flow run graph in the UI.
- If no issue exists and your change is not a …

Add artifact data to flow run graph API

---

docs/integrations/catalog/prefect-coiled.yaml

A small follow-up to https://github.com/PrefectHQ/prefect/pull/12098 that updates the link to the corresponding Coiled docs. 
xref https://github.com/PrefectHQ/prefect/pull/12098#issuecomment-1969912418

Update Coiled link on integrations page

---

src/prefect/deployments/deployments.py
tests/test_deployments.py

If we know that a Deployment has been initialized with `schedules=[]`, ignore any generated `schedule` field the API returns from `Deployment.load` because we know it's out of date.
This PR also makes our deprecation warnings for `schedule` and `is_schedule_paused` less aggressive, only setting them if a user initializes `Deployment` with one of those fields and not `schedules`.
fixes #12099 

Ignore "schedule" in `Deployment.build_from_flow` if it's out of date

---

src/prefect/cli/flow.py
src/prefect/client/orchestration.py
src/prefect/deployments/runner.py
src/prefect/flows.py
src/prefect/runner/runner.py
src/prefect/server/schemas/responses.py
tests/cli/deployment/test_deployment_cli.py
tests/runner/test_runner.py
tests/server/api/test_deployments.py
tests/test_flows.py

This updates `flow.serve` to support multiple schedules. The schedules can be given in many different forms:
```
schedules=[IntervalSchedule(...), CronSchedule(...), ...]
schedules=[{"schedule": IntervalSchedule(...), "active": False}]
schedules=[MinimalDeploymentSchedule(schedule=IntervalSchedule(...), active=False)]
```
You can also specify multiple `interval`, `cron`, and `rrule` schedules via shorthand:
```
cron=["* * * *", ...]
interval=(3600, 7200, ...)
rrule={"FREQ=DAILY", "FREQ=WEEKLY", ...}
```
Closes #12090 

Update `flow.serve` to support multiple schedules

---

tests/docker/test_image_builds.py

Fix a test flake where we can get a `500` from dockerhub while trying to build an image. I'm not super familiar with these tests but it seems like we already allow for a 429 as an acceptable response. 
https://github.com/PrefectHQ/prefect/actions/runs/8098803080/job/22133077817?pr=12113
```
E       AssertionError: Regex pattern did not match.
E        Regex: 'pull access denied|429'
E        Input: 'Head "https://registry-1.docker.io/v2/library/flibbity-gibbity-jabberty/manifests/never-nohow-whowouldmakethis-oh-the-humanity": received unexpected HTTP status: 500 Internal Server Error'
tests/docker/test_image_builds.py:138: AssertionError
```

allow 500s on docker test flake

---

src/prefect/server/orchestration/core_policy.py
src/prefect/server/services/late_runs.py
tests/fixtures/database.py
tests/server/orchestration/test_core_policy.py
tests/server/orchestration/test_rules.py
tests/server/services/test_late_runs.py

closes: https://github.com/PrefectHQ/prefect/issues/12116
oss version of: https://github.com/PrefectHQ/nebula/pull/4569
The MarkLateRuns service will grab late SCHEDULED runs in batches and then mark those runs as late. In the current implementation it is possible for a run that was SCHEDULED and needed to be marked late, to transition to PENDING while the service is working it's way through the batch.
This PR adds a new orchestration rule `EnsureOnlyScheduledFlowsMarkedLate`. It also adds a new orchestration policy to only be used by `MarkLateRuns` that enforces this rule.
**NOTE:**If there is a race condition and a run's state is being concurrently orchestrated we may still find this is possible. However, this will drastically reduce the window in which it is possible.

ensure only scheduled runs can be marked late

---

docs/concepts/schedules.md
src/prefect/cli/_prompts.py
src/prefect/cli/deploy.py
src/prefect/deployments/base.py
src/prefect/testing/cli.py
tests/cli/test_deploy.py

This adds support for multiple schedules to `prefect deploy`. It allows for the `prefect.yaml` to contain a `schedules` list, all schedules in that list will be added to that deployment when it's created/updated. Setting it to an empty list will result in all schedules being removed. It also allows you to interactively define multiple schedules.
Additionally you can specify multiple schedules via the command line:
`prefect deploy ... --cron '4 * * * *' --cron '1 * * * *' --rrule 'FREQ=DAILY'`
Lastly I opted to keep the behavior where passing `--anchor_date` or `--timezone` would update the existing schedule to use that timezone/anchor_date, but now it applies to both new and existing schedules for the deployment.
Closes #12092 
- If no issue exists and your change is not a small fix, …

Add support for multiple schedules to `prefect deploy`

---

src/prefect/cli/deployment.py
tests/cli/deployment/test_deployment_cli.py

Adds a `--replace` option to the `prefect deployment schedule create` command, so that `prefect deployment schedule create <options> --replace -y` works like the now-deprecated command `prefect deployment set-schedule`, replacing all current schedules with the new one.

Add a --replace option to "schedule create" command

---

src/prefect/server/api/server.py
src/prefect/server/api/task_runs.py
src/prefect/server/orchestration/core_policy.py
src/prefect/server/services/__init__.py
src/prefect/server/services/task_scheduling.py
src/prefect/server/task_queue.py
src/prefect/settings.py
tests/server/api/test_task_run_subscriptions.py
tests/test_autonomous_tasks.py

* Moves enqueuing to an orchestration rule when tasks enter `SCHEDULED`
* Adds a loop service that rescheduled timed out `PENDING` tasks
* Moves the enqueuing of scheduled tasks at startup to that loop service

Reliability improvements for autonomous task scheduling

---

src/prefect/logging/filters.py
tests/test_logging.py

closes #12139
`ObfuscateApiKeyFilter` as introduced by https://github.com/PrefectHQ/prefect/pull/12072 was assuming log record messages were strings, so when we attempted to remove a `PREFECT_API_KEY` from the message, we saw attribute errors like in the original issue.
this pr uses `visit_collection` to allow us to redact arbitrary collections recursively

Support obfuscation of more complex log record messages

---

docs/concepts/schedules.md
src/prefect/flows.py

Docstring params for flow.deploy and flow.serve now reference multiple parameters.
Removes redundant section in schedules doc and updates the docstring language on that page.

Update `flow.serve` and `flow.deploy` docstrings and docs for multiple schedules

---

docs/getting-started/installation.md

This PR removes mention of the SQLite version from the install docs. Closes #5197 
Context: 
- The minimum required version of SQLite in the docs is incorrect.
- We don't test against a matrix of sqlite libraries.
- It's not straightforward or efficient to install old sqlite libraries. 
- We have very few reported issues of problems with old versions of SQLite, as the Python versions that we support (3.8 and up) generally install with SQLite versions that work.

Remove outdated sqlite version info from install docs

---

.github/workflows/docker-images.yaml
.github/workflows/integration-tests.yaml

closes #12161
I don't see why we'd need to build images / do integration tests for changes outside of any of these paths, but let me know if there's some reason I'm missing

only do docker builds/intregration tests on changes to deps/src

---

src/prefect/server/database/query_components.py
src/prefect/server/schemas/graph.py
src/prefect/settings.py
tests/server/api/test_flow_run_graph_v2.py

This PR mimics #12105 in supporting upcoming enhancements to the flow run graph.
It adds 1 new experimental opt-in flag:
- `PREFECT_EXPERIMENTAL_ENABLE_STATES_ON_FLOW_RUN_GRAPH` - an opt-in flag to add flow run state data to the graph-v2 route's response. NOTE: when this is OFF, the graph response still includes the top-level states key but the value is stubbed out with an empty array and any additional query overhead is foregone.
| **OFF (default)** | **ON** |
| ![Screenshot 2024-03-01 at 11 27 29 AM](https://github.com/PrefectHQ/prefect/assets/22418768/f6a80b9b-2589-48a4-adc4-11b188d653c5) | ![Screenshot 2024-03-01 at 11 25 55 AM](https://github.com/PrefectHQ/prefect/assets/22418768/1c08f7c2-a14a-4930-9b9a-7d24b710ef79) |
- If no issue exists and your change is not a …

Add flow run state data to flow run graph API

---

src/prefect/engine.py
src/prefect/task_engine.py
src/prefect/tasks.py
tests/test_autonomous_tasks.py

closes #12155
allows calling tasks outside of a flow run using `__call__`, which does not engage with the `TaskServer` or server-side websocket endpoint, rather it blocks and returns the result (or the `state` if you pass `return_state=True`)

allow creating autonomous task runs via `__call__`

---

src/prefect/engine.py
src/prefect/task_engine.py
src/prefect/tasks.py
tests/test_autonomous_tasks.py

closes #12154
stacked on https://github.com/PrefectHQ/prefect/pull/12158/files
<hr>
this PR adds support for calling `.map` outside the context of a flow run (if flag is enabled)
- similar to the traditional `.map`, a task run is created for each parameter set accepted by `.map`'s signature (how you call `.map` has not changed)
- however, since autonomous `.submit` returns a `TaskRun` and (in the traditional case) `.map` is really just calling `.submit` for you under the hood for each parameter set, we follow the theme here. `.map` will return a `list[TaskRun]` according to the parameter sets we pull out of `.maps` args and kwargs (that logic hasnt changed either)
- the exeuction of the submitted runs are assumed to be handled by a running `TaskServer`
```python
async def …
```

[task scheduling] map autonomous task runs

---

requirements-client.txt
src/prefect/utilities/schema_tools/hydration.py
src/prefect/utilities/schema_tools/validation.py
tests/utilities/schema_tools/test_hydration.py
tests/utilities/schema_tools/test_validation.py

This PR ports the Hydration and Validation module `/schema_tools/` from Cloud to OSS. The files and tests were copied over entirely as is except for:
- removal of jinja support
- updating some type hints to be python 3.8 compatible

port schema tools to OSS

---

docs/api-ref/prefect/deployments/schedules.md
mkdocs.yml
src/prefect/deployments/deployments.py
src/prefect/deployments/runner.py
src/prefect/deployments/schedules.py
src/prefect/runner/runner.py
tests/deployment/test_schedules.py
tests/test_deployments.py

This adds 'shorthand' schedules support to `Deployment`, and specifically `Deployment.build_from_flow`, so now you can do:
```python
deployment = await Deployment.build_from_flow(
flow=my_flow,
name="The best flow in the world",
schedules=[
CronSchedule(cron="0 0 * * *"),
{"schedule": {"interval": datetime.timedelta(minutes=10)}},
],
)
```
Without needing `MinimalDeploymentSchedule`
Closes #12177 

Add schedules shorthand support to `Deployment.build_from_flow`

---

src/prefect/server/schemas/filters.py
tests/server/models/test_deployments.py
tests/server/models/test_filters.py

This updates the legacy `IsScheduleActive` filter to filter on the `paused` field, and creates a new filter to filter by `Deployment.paused`.
OSS side of https://github.com/PrefectHQ/nebula/pull/7139
Related to https://github.com/PrefectHQ/nebula/issues/6877

Create `DeploymentFilterPaused` and update legacy filter

---

ui/src/maps/featureFlag.ts
ui/src/pages/FlowRun.vue
ui/src/types/flagResponse.ts
ui/src/utilities/permissions.ts

This PR adds a new tab for a flow run's job variables.
> [!Note]
> This functionality is hidden behind an experimental setting as job variables at the flow run level are [still baking in the oven](https://github.com/PrefectHQ/prefect/pull/12185).
Closes #12207 

Expose flow run job vars on page

---

src/prefect/engine.py
src/prefect/flows.py
tests/test_flows.py

This PR adds an on_running state change hook to the list of existing hooks available for flows, this is particularly useful for maintenance tasks that may need to be performed on a flow just prior to it's execution that may need to be separated from the flow code itself.
It's worth noting that the behavior for this hook differs from others in that it's not running on a Terminal state change meaning that depending on the circumstances it's possible for these hooks to be triggered multiple times during the course of a run.
closes [`10446`](https://github.com/PrefectHQ/prefect/issues/10446)
```
import time 
import random
def on_running_function(flow, flow_run, state):
print(f"I am an on_running function! The flow is currently in state {state}")
@task
def …
```

Adds an on_running state change hook

---

src/prefect/events/schemas.py
tests/cli/test_deploy.py
tests/client/test_prefect_client.py
tests/events/test_event_schemas.py
tests/events/test_v1_triggers_deserialization.py

This backports the new `Trigger`s schema class hierarchy from Prefect Cloud,
with a unit test confirming that we are maintaining full backwards compatibility
with prior versions of `Trigger`.  This also allows clients to start specifying
Metric triggers in their deployments as well.

Updating client-side schemas for Triggers to reflect updates in Prefect Cloud

---

src/prefect/cli/cloud/__init__.py
tests/cli/test_cloud.py

Removes an ambiguous question in the `prefect cloud login` flow when a user has one or more profiles already authenticated to cloud.
Closes #10689 
The command had an ambiguous question that was meant to tell if the user wanted to authenticate with the current profile or switch profiles. Essentially, asking them a question so we can ask a question, here I'm just removing that question altogether and asking if they want to switch profiles immediately. This takes it from:
to:

Simplify already authenticated logic for `prefect cloud login`

---

src/prefect/engine.py

This updates the engine to send the `INFO` log about the fact that a flow run or task run is retrying to the API instead of ignoring it.
Closes #10569 

Send flow run and task run retry logs to API

---

src/prefect/server/api/task_runs.py
tests/server/api/test_task_run_subscriptions.py

We had a little bit of drift between Prefect and Prefect Cloud, mostly in how
error handling in the socket works.  This reconciles the changes.

Better parity between Prefect and Prefect Cloud for task scheduling protocol

---

src/prefect/server/database/migrations/versions/postgresql/2023_01_31_110543_f98ae6d8e2cc_work_queue_data_migration.py
src/prefect/server/database/migrations/versions/sqlite/2023_01_31_105442_1678f2fb8b33_work_queue_data_migration.py
tests/server/database/test_migrations.py

closes #11984 
edits an old data migration that was creating a `default-agent-pool` work pool by default, and associating work-queues with this work pool
as it was, this data migration had the misleading side-effect of seeming like a recommendation to new users of the open source server
if we find any work queues that have a `null` work pool, we keep the status quo and create the `default agent pool`, but in the empty case, we shouldn't find any such work queues, so we just do not create the `default agent pool` or do the downstream queue association

do not create `default-agent-pool` in empty state server

---

src/prefect/client/subscriptions.py
src/prefect/events/clients.py
tests/events/test_v1_triggers_deserialization.py

In Prefect Cloud, we're now giving better error messages when authentication
fails on a websocket connection, and this change has the clients show those
error reasons to the users in the exceptions thrown during
connection/reconnection.

Giving better client-side feedback on websocket authT/authZ issues

---

src/prefect/client/schemas/objects.py
src/prefect/client/schemas/responses.py
src/prefect/server/api/deployments.py
src/prefect/server/api/flow_runs.py
src/prefect/server/api/validation.py
src/prefect/server/database/migrations/MIGRATION-NOTES.md
src/prefect/server/database/migrations/versions/postgresql/2024_03_05_122228_121699507574_add_job_variables_column_to_flow_runs.py
src/prefect/server/database/migrations/versions/sqlite/2024_03_05_115258_342220764f0b_add_job_variables_column_to_flow_runs.py
src/prefect/server/database/orm_models.py
src/prefect/server/schemas/actions.py
src/prefect/server/schemas/core.py
src/prefect/server/schemas/responses.py
tests/server/api/test_deployments.py
tests/server/api/test_flow_runs.py
tests/server/api/test_infra_overrides.py
tests/server/models/test_flow_runs.py

This PR adds backend support for creating and validating flow-run level `job_variables` through the API. It also adds support and validation to updates to a flow-run's `job_variables` if that flow run is still in a scheduled state. Although the API inputs and responses will start including `job_variables`, the validation logic is behind the feature flag `PREFECT_EXPERIMENTAL_ENABLE_FLOW_RUN_INFRA_OVERRIDES`.
This is an example of the input schema on server-side `FlowRunCreate` objects:

Add backend support for creating and updating flow run `job_variables`

---

ui/package-lock.json
ui/package.json

I've checked around and found `dotenv` not used in any parts in `ui` module. I also ran `npm run build` to ensure no breakage and indeed, no breakage.

chore: remove unused `dotenv`

---

src/prefect/workers/base.py
tests/workers/test_process_worker.py

This PR adds the final functionality for propagating `job_variables` onto workers -- if the FF is enabled the worker will pull job_variables off the flow run object and combine those with the deployment's infra-overrides before using the result to build the run's final configuration.
Note: This PR depends on https://github.com/PrefectHQ/prefect/pull/12195

Workers use flow run overrides

---

src/prefect/deployments/deployments.py
src/prefect/deployments/schedules.py
tests/cli/deployment/test_deployment_build.py
tests/deployment/test_schedules.py
tests/test_deployments.py

The recent changes for enhanced scheduling broke the way the legacy `schedule` parameter worked for `build_from_flow`. This ensures that the legacy field is able to add and remove schedules, but in the case that both `schedule` and `schedules` are provided `schedules` will be the source of truth.
Closes #12255 

Fix support for legacy schedule in `build_from_flow`

---

requirements-client.txt

This pins `importlib-resources` to 6.1.x to fix the issue with our 3.8 tests failing to start because of an import error.
Related to #12265

Pin `importlib-resources` to 6.1.x

---

src/prefect/server/api/flow_runs.py
src/prefect/utilities/schema_tools/__init__.py
tests/server/api/test_flow_runs.py

This adds support for hydrating run input before comparing it against the resume schema.
OSS side of https://github.com/PrefectHQ/nebula/pull/7192

Hydrate run input when resuming a flow run

---

docs/guides/creating-interactive-workflows.md

Copying and pasting the examples in the docs produced errors because `get_run_logger` was not imported.

Docs: Add `get_run_logger` to imports in interactive workflow examples

---

src/prefect/cli/_types.py
src/prefect/cli/deployment.py
src/prefect/deployments/deployments.py
tests/cli/deployment/test_deployment_build.py
tests/cli/deployment/test_deployment_cli.py
tests/test_deployments.py

Adds a deprecation warning to the `Deployment` class along with the the deployment `build` and `apply` commands in lieu of `flow.deploy` and `prefect deploy`. Adds some logic to enable deprecation of specific commands in addition to full command groups.

Deprecate `Deployment` class and deployment `build` and `apply` commands

---

src/prefect/filesystems.py
tests/test_filesystems.py

Adds deprecation warnings to the `S3`, `GCS`, `Azure`, and `GitHub` blocks in the `filesystems` module. These blocks have implementations in Prefect integration packages that offer more functionality and a better user experience. These blocks will be removed from the core package to prevent confusion around blocks that appear to be duplicates.
Requires https://github.com/PrefectHQ/prefect-azure/pull/139

Deprecate storage blocks with implementations in Prefect integration packages

---

client/build_client.sh

This PR changes our prefect-client build process to include our artifacts module for creating and working with artifacts.
Closes #12315 
Users who install `prefect-client` will be able to do this now:
```python
from prefect.artifacts import create_markdown_artifact
```
- [-] This pull request includes tests or only affects documentation.

Keep artifacts file in prefect-client

---

.pre-commit-config.yaml
requirements-dev.txt
setup.cfg
src/prefect/_internal/concurrency/calls.py
src/prefect/client/subscriptions.py
src/prefect/events/related.py
src/prefect/server/database/configurations.py
src/prefect/task_server.py
src/prefect/utilities/callables.py
tests/_internal/concurrency/conftest.py
tests/runner/test_runner.py
tests/test_flows.py

Vermin is a utility for detecting which python version is supported for a given python file. This wires it up to our pre-commit and sets the config such that any file that doesn't pass at our minimum python version, 3.8, will get a pre-commit failure:
```
Check minimum Python version.............................................Failed
- hook id: vermin
- exit code: 1
tests/test_flows.py:1394::!2:3.9:builtin generic type annotation (list[..])
tests/test_flows.py:::!2:3.9:
:::!2:3.9:
```

Wire up vermin to pre-commit

---

src/prefect/server/database/interface.py
src/prefect/server/database/query_components.py
src/prefect/server/models/agents.py
src/prefect/server/models/artifacts.py
src/prefect/server/models/block_documents.py
src/prefect/server/models/block_schemas.py
src/prefect/server/models/block_types.py
src/prefect/server/models/concurrency_limits.py
src/prefect/server/models/csrf_token.py
src/prefect/server/models/deployments.py
src/prefect/server/models/flow_runs.py
src/prefect/server/models/flows.py
src/prefect/server/models/logs.py
src/prefect/server/models/saved_searches.py
src/prefect/server/models/task_runs.py
src/prefect/server/models/workers.py
tests/server/api/test_workers.py

This updates the typing on `db.insert` to be accurate as well as makes it a sync function as it does not do anything async.
Before:
After:

Fix `db.insert` typing

---

src/prefect/client/base.py
src/prefect/client/cloud.py
src/prefect/client/orchestration.py
src/prefect/client/schemas/objects.py
src/prefect/settings.py
tests/cli/test_worker.py
tests/client/test_base_client.py
tests/client/test_prefect_client.py
tests/test_deployments.py

Adds CSRF support to orchestration client.
When a request is made to a POST, PATCH, PUT, or DELETE endpoint the orchestration client will ensure that it has a valid token and attach the CSRF headers to the request. In the event that a request fails because of CSRF token validation the client will automatically retry after refreshing the CSRF token. 
This support is disabled when talking to Cloud, but is otherwise enabled by default as we need to assume that all prefect servers have CSRF enabled. In the event that a client is talking to an older server that does not have the CSRF token endpoint it will disable its csrf support after receiving a 404. 
If a user knows that they do not need CSRF support, due to an older server or one that has CSRF protection disabled they can set …

Add CSRF support to orchestration client

---

src/prefect/tasks.py
tests/test_autonomous_tasks.py

https://github.com/PrefectHQ/prefect/pull/12227 didn't quite cover everything we needed
because tasks would go through their `__init__` again at import time when submitting a task defined elsewhere, the `__module__` is not guaranteed to be the same between where the task is served and submitted. Therefore checking if `__main__` is in the module would only solve half the problem.
this PR updates the `task_key` of `Task` (when a `__qualname__` exists) to be a composite of the `__qualname__` (static, not relative to the importer) and a hash of the absolute path where the task is defined, which leaves the door open to referring to the tasks by string name, in arq-style.
note that this still works in interactive environments like `ipython`
```python
In [2]: from prefect import task
...: from …
```

refactor task key logic

---

.github/workflows/benchmarks.yaml
.github/workflows/docker-images.yaml
.github/workflows/python-tests.yaml

We had builds failing with:
```
ERROR: failed to solve: failed to compute cache key: blob sha256:3aa78131f5aa6760ebe0b219764d4ae523872584040fefe3ff754cb42c402ca0 not found
Error: buildx failed with: ERROR: failed to solve: failed to compute cache key: blob sha256:3aa78131f5aa6760ebe0b219764d4ae523872584040fefe3ff754cb42c402ca0 not found
```
-- https://github.com/PrefectHQ/prefect/actions/runs/8331581620/job/22799600345?pr=12342
Which appears to be a regression issue with buildkit 0.13 (https://github.com/moby/buildkit/pull/4771). 
This pins buildkit to 0.12.5.

Pin Buildkit to 0.12.5 to fix issue with test image build

---

src/prefect/client/base.py
src/prefect/server/api/csrf_token.py
tests/client/test_base_client.py
tests/server/api/test_csrf_token.py
tests/server/models/test_csrf_token.py

This PR has a couple UX enhancements for the CSRF endpoint:
1. When CSRF protection is disabled, the server will now respond with a `422` noting that CSRF protection is disabled. The client will look for this and turn off CSRF support in the event that it receives this response.
2. Expired tokens are deleted when creating new tokens.
Closes #12338 
Closes #12339 

Return 422 when CSRF is disabled and delete expired tokens

---

src/prefect/server/api/collections_data/views/aggregate-worker-metadata.json

ports changes for `cloud-run` worker from recent `prefect-gcp` release

Update `aggregate-worker-metadata` from `prefect-gcp` release

---

src/prefect/engine.py
src/prefect/task_server.py
tests/events/instrumentation/test_task_run_state_change_events.py

we were not correctly recording state changes with emitted events from
`None` -> `SCHEDULED` -> `PENDING` -> `RUNNING` -> `COMPLETED`
in particular, we need to handle the `SCHEDULED` and `PENDING` state changes differently, since historically tasks have gone from `NONE` -> `PENDING`

[background tasks] emit pending event

---

ui/src/pages/FlowRuns.vue

This PR adds the ability to select all flow runs in the current view on the flow runs page to more easily enable deleting multiple flow runs.
Note: Because the flow runs list is virtualized, when filtering for 200+ flow runs, selecting all will only select what's currently in view 
| | 📸 Screenshots |
| Select all | <img width="1080" alt="image" src="https://github.com/PrefectHQ/prefect/assets/22418768/f394f523-5e23-4d0e-93f0-aef086e02283"> |
| Deselect all | <img width="1081" alt="image" src="https://github.com/PrefectHQ/prefect/assets/22418768/ad56068b-bd0f-4d8c-90f1-1755faf15507"> |
For new functions …

Add a select all flow runs checkbox to the flow runs page.

---

src/prefect/_internal/pydantic/__init__.py
src/prefect/_internal/pydantic/_compat.py
src/prefect/settings.py
tests/_internal/pydantic/test_model_dump.py

this PR starts laying the groundwork for a more complete compat layer that we can begin adopting incrementally.
here we add only a `model_dump` function that can be used anywhere we use `some_model_instance.dict()` on a v1 `BaseModel` today.
it may be possible to reduce the surface area of changes that would stem from replacing every use of `.dict()` with a `model_dump(some_model_instance)` call by mirroring the v2 `BaseModel` interface on classes like `PrefectBaseModel`, but even that will require this initial layer (that we could call from some method like `PrefectBaseModel.model_dump` based on the switching logic inside `_compat`'s `model_dump`)

[pydantic v2] init compat layer

---

src/prefect/cli/cloud/__init__.py

Uvicorn just released `0.29.0` which fixes some issues it had with signal handlers, but it also causes `uvicorn.serve` to raise a `KeyboardInterrupt` when it's done serving. This ensures that we're handling `KeyboardInterrupt` exceptions coming from `.serve`.

Handle `KeyboardInterrupt` coming from `uvicorn.serve`

---

src/prefect/settings.py
tests/_internal/compatibility/test_experimental.py
tests/server/test_app.py

This PR enables artifacts and states on the flow run graph by default. 
The respective experimental settings will now be enabled by default providing an opt-out experience at the api level if a user were to run into issues in their environment. 
For example, by setting `PREFECT_EXPERIMENTAL_ENABLE_ARTIFACTS_ON_FLOW_RUN_GRAPH` to a falsey value, the server will skip fetching artifacts for all flow run graphs. Similarly so for `PREFECT_EXPERIMENTAL_ENABLE_STATES_ON_FLOW_RUN_GRAPH` but for flow run states.
As a user, if you'd like to just toggle either layer off while viewing the graph, the graph has built-in toggles to do just that! These flags are intended more as escape hatches server-side in the event that you run into performance issues loading the extra data required for the graph. 
- …

Render artifacts and states on the flow run graph by default.

---

src/prefect/server/api/middleware.py
ui/src/maps/csrfToken.ts
ui/src/maps/index.ts
ui/src/models/CsrfToken.ts
ui/src/pages/AppRouterView.vue
ui/src/services/csrfTokenApi.ts
ui/src/types/csrfTokenResponse.ts
ui/src/utilities/api.ts

This adds CSRF support to the UI. A CSRF token is retrieved when the app starts, and a background task is started to ensure that the token is refreshed before the token expires. The headers are attached to each request via an axios interceptor, this required adding a hook (https://github.com/PrefectHQ/prefect-ui-library/pull/2239) to prefect-ui-library so that the axios instance itself could be updated.
Closes #12347 

Implement CSRF support in the UI

---

setup.cfg
src/prefect/cli/cloud/__init__.py
src/prefect/cli/profile.py
src/prefect/client/base.py
tests/cli/test_profile.py
tests/client/test_base_client.py
tests/client/test_prefect_client.py
tests/conftest.py
tests/docker/test_image_builder_assertions.py
tests/docker/test_image_builds.py
tests/docker/test_image_parsing.py
tests/docker/test_registry_pushes.py
tests/engine/reliability/test_deadlocks.py
tests/fixtures/client.py
tests/fixtures/logging.py
tests/runner/test_runner.py
tests/server/orchestration/test_core_policy.py
tests/utilities/test_importtools.py

This reverts commit bc62ed9.
It also reverts a follow-up that tried to resolve new issues in CI seemingly related to 500 status retries: Attempt to fix agent/work queue test CI flakes (#12375).

Revert "Enhancement: Base client retry on 500 (#12084)"

---

.github/workflows/integration-tests.yaml
src/prefect/settings.py
src/prefect/testing/fixtures.py
tests/conftest.py

This updates the `PREFECT_SERVER_CSRF_PROTECTION_ENABLED` setting to be on by default. It also updates our main `conftest` to disable it in the test suite, just to avoid the noise of the extra requests where they're not important.

Turn CSRF protection on by default

---

src/prefect/cli/deploy.py
src/prefect/cli/deployment.py
tests/cli/test_agent.py
tests/cli/test_worker.py

fixes #12397
when we have some command like
```python
@deployment_app.command()
async def run(
...
job_variables: List[str] = typer.Option(
None,
...
),
```
[typer `0.10.x` now gives a `None` instead of an empty list](https://github.com/tiangolo/typer/releases/tag/0.10.0)
which had the effect of us trying to iterate over a `NoneType` thing that was previously a list
this PR just swaps those cases for `once_a_list or []` and/or updates `assert_called_with` cases to the right thing

handle new `typer.Option` behavior

---

src/prefect/server/api/server.py

This PR updates the UI server utilities to write the version of Prefect into the stored reference file in addition to the base path. This should invalidate the file when the version gets upgraded and cause the UI to be recreated. 
Resolves #12427

Bugfix: Upgrading should upgrade the UI as well

---

src/prefect/server/api/server.py
src/prefect/server/services/task_scheduling.py
src/prefect/utilities/asyncutils.py

to avoid deprecation warnings like
```python
logger.warn("The event loop shutdown callback was not properly registered. ")
File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/logging/__init__.py", line 1492, in warn
warnings.warn("The 'warn' method is deprecated, "
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```

move uses of `logger.warn` to `logger.warning`

---

docs/concepts/states.md
src/prefect/settings.py

This PR increases the default time after scheduled start time after which a flow run is marked Late from 5 seconds to 15 seconds.
We have found 5 seconds ends up causing contention between our `MarkLateRuns` service and workers/agents trying to mark runs as `Pending`.

Increase late runs after seconds setting default

---

ui/vite.config.ts

Since the ui code is open source theres no reason to not have source maps all the time. Will make the package slightly larger but will make debugging customer ui issues much easier.

UI: enable sourcemaps by default

---

requirements-client.txt

We've had several reports of issues with our `cloud login` command and some other random `CancelledError` in the vicinity of our uvicorn usage. Uvicorn currently has a couple open issues related to 0.29 and its new signal handling. This pins us to <0.29.0 until there is another release and then we can revisit.
Related to #12371

Pin uvicorn to < 0.29

---

src/prefect/server/schemas/responses.py
tests/workers/test_base_worker.py

we previously have used `@copy_model_fields` and `FieldFrom` to avoid duplicating `Field` definitions on our schemas, but with the move to pydantic 2 we have decided to stop this:
- current implementation is incompatible with pydantic 2
- it eats type information (that would allow us to pass mypy, all else being fine)
this PR is the first (quite small) step in removing our dependence on these type utils

remove `copy_model_fields` from response schemas

---

requirements-client.txt

We want to stay under .29 for now, it's causing some `CancelledError` issues, specifically with `cloud login`.
Reverts PrefectHQ/prefect#12477

Revert "Update uvicorn requirement from <0.29.0,>=0.14.0 to >=0.14.0,<0.30.0"

---

src/prefect/server/utilities/messaging/__init__.py
src/prefect/server/utilities/messaging/memory.py
src/prefect/settings.py
tests/server/conftest.py
tests/server/utilities/test_messaging.py

This introduces the abstract bases and the first in-memory implementation of
message publishers and consumers.  This generic base can form the foundation for
events, actions, and task run subscriptions.  The in-memory implementation is
based on distributing messages among `asyncio.Queue`s, and using an in-memory
`TTLCache` to keep track of duplicate messages.
The test suite here fully covers the in-memory implementation, but can stand
become a set of compatibility tests for any other implementations.  I have not
tried to address dynamically loading implementations from external collections,
but that could be addressed with minor adjustments to the `create_*` functions.
```
src/prefect/server/utilities/messaging/__init__.py           44      0      8      0   100% …
```

Message Publisher and Consumer abstractions, with in-memory implementation

---

src/prefect/testing/cli.py
tests/cli/test_artifact.py
tests/cli/test_deploy.py

This adds a new concept of `prompts_and_responses` to `invoke_and_assert`. `prompts_and_responses` let's you define the prompts you expect and the response that should be given, and includes support for navigating tables with up/down arrows. `invoke_and_assert` will grab all of the 'responses' and use those as input for the command, and then it will assert that all of the prompts are in the output, and in the expected order. It will also assert that the correct option is selected in the table. 
I've updated several tests with this new pattern, but wanted to get feedback before going further.

Add `prompts_and_responses` support to `invoke_and_assert`

---

src/prefect/server/api/__init__.py
src/prefect/server/api/events.py
src/prefect/server/api/server.py
src/prefect/server/events/messaging.py
src/prefect/server/utilities/messaging/__init__.py
src/prefect/settings.py
tests/events/client/test_cloud_events_subscriber.py
tests/events/server/conftest.py
tests/events/server/gateway/conftest.py
tests/events/server/gateway/test_gateway_in.py
tests/events/server/test_messaging.py

This adds the events HTTP and websocket endpoints to act as the inbound gateway
for events, matching the interface and behavior of Prefect Cloud (apart from
authentication).  Based on the current implementation using the default
in-memory topics and subscriptions will essentially act as a `/dev/null` for any
events sent to them.

Backporting `POST /api/events` and the `/api/events/in` Websocket

---

src/prefect/server/api/server.py
src/prefect/server/events/services/event_logger.py
src/prefect/settings.py

This enables an end-to-end test of event colleciton, from the API to
distribution to consumers.  It can be enabled at startup to print every event
received on the event bus.  I'm not including an additional test suite for this
service because it's not likely to stay with us long-term.

Adding a diagnostic service which consumes events and prints a summary of them

---

.github/workflows/python-tests.yaml

Trying to cache our docker images results in trying to build and export to the cache, which seems to takes all of the time.
This PR removes caching when trying to build images during our tests. When caching is working in a normal manner this seems to only save us around 10s total. For now lets remove caching entirely to avoid running into 15min image build times and we can revisit it.
Additionally we've exceed our GHA cache by 200GB (the limit is allegedly 10GB). Clearing this might provide a more reliable experience.
without it this step takes under 2 minutes:

stop trying to cache docker layers

---

src/prefect/settings.py
tests/conftest.py
tests/server/models/test_orm.py

Setting the test event loop to `loop.set_debug(True)` makes things way slower during our tests.
Removing this cuts the sqlite test suite by about 3 minutes and the postgres test suite by about 1 minute.

set loop debug off

---

src/prefect/client/schemas/actions.py
src/prefect/client/schemas/objects.py
src/prefect/client/schemas/responses.py

continuing #12475
we are no longer doing the `Mixin` because its complex and mypy gets angry, so we are now duplicating schemas
---
the `class SomeModel(ActionModel, SomeModelMixin):` strategy is seeming a bit complex, especially because mypy (we hope someday to pass its muster) does not let you override type annotations on base model, so even if you have a true intersection of `Field` objects that can live on the mixin, you can't really be safe with types (which sort of defeats the purpose of the this effort to remove `copy_model_fields`)
so, the plan is to just do the dead simplest thing, which is to duplicate the ORM and action schemas so we can be explicit on each with typing.
The claim is that even though this creates multiple places you need to update a schema if one changes:
- it …

revert mixin strategy and copy schemas to remove `copy_model_fields`

---

src/prefect/_internal/pydantic/utilities/model_dump.py
tests/_internal/pydantic/test_model_dump.py

with the flag off, we can still get `json_compatible` behavior
```python
In [1]: from datetime import datetime
In [2]: from prefect.pydantic import BaseModel
In [3]: class FooModel(BaseModel):
...:     d: datetime = datetime.now()
...:
In [4]: FooModel(x=42).model_dump(mode="json")
Out[4]: {'d': '2024-04-02T09:45:31.311534'}
```

support `mode="json"` when flag is off

---

requirements-client.txt

this install should not affect ongoing pydantic compatibility
short term:
- fix nebula compat
long term:
- v1 / v2 independent utils, for example `from_json` as an efficient version of `json.loads`

add `pydantic_core` to client deps

---

.github/workflows/python-tests.yaml
requirements-client.txt

We were depending on `pip` to install the _latest_ version of pydantic, but with
recent `uv` changes, it looks as if it favors the cached lower version.  This
adds an explicit additional install to the tests where we expect pydantic v2.

Making sure that we explicitly install pydantic v2 in CI where we intend to

---

tests/test_tasks.py

adds (not comprehensive but _some_) tests for proposed nested tasks
loosely covers:
- sync / async submission and result fetching + map
- caching
- `wait_for`
- `retries`

add init test coverage for nested tasks

---

requirements-client.txt

httpcore released an upstream fix for a bug that is common for our users, as long as this doesn't seem like too restrictive a lower bound, this should circumvent the problem without forcing manual upgrades for containerized runtimes
see https://github.com/PrefectHQ/prefect/issues/11660 and https://github.com/encode/httpcore/releases/tag/1.0.5

update `httpcore` dep

---

.github/CODEOWNERS

It's important that I keep the OSS and Prefect Cloud implementations in concert
with one another.  While we're in the process of porting it to
`PrefectHQ/prefect`, I'd like to see any proposed changes so I can relay them
to Cloud.

Add myself as a CODEOWNER for the events subsystem while it's being ported

---

setup.cfg
src/prefect/events/actions.py
src/prefect/events/schemas/automations.py
src/prefect/server/events/actions.py
src/prefect/server/events/schemas/automations.py
tests/events/server/actions/test_doing_nothing.py
tests/events/server/conftest.py
tests/events/server/schemas/test_automations.py

This introduces just the models, including the instance methods, but doesn't
add much in the way of new tests because most of this code is tested as part of
the triggers services.  I need the schema models available so I can build out
the ORM and CRUD APIs.
I debated whether to cut these instance methods for better coverage or to keep
them in and accept the coverage drop.  Keeping them in means less churn when we
do add the triggers system, so I'm good with that.

Introduces the server-side automations schema models

---

src/prefect/blocks/kubernetes.py
tests/blocks/test_kubernetes_block.py

This PR adds a deprecation I missed when deprecating classes related to agent deprecation.

Deprecate `KubernetesCusterConfig` block

---

src/prefect/cli/cloud/__init__.py

closes https://github.com/PrefectHQ/prefect/issues/12459
Same as https://github.com/PrefectHQ/prefect/pull/12562 but now hopefully correct with this pre-commit hook

Allow to authenticate even if authenticated already in non-interactive mode

---

src/prefect/server/orchestration/rules.py
tests/test_task_server.py

Right now we flood the orchestration database with artifacts representing "unpersisted" results. These are functionally useless and create more noise than is necessary, so we are removing them.
The only change this makes is that retried flows without persisted results have a _slightly_ different error message now - instead of saying "Unpersisted result" the message says "State data is missing", but the exception type is the same.

Stop creating artifacts for unpersisted results

---

src/prefect/engine.py
src/prefect/utilities/engine.py
src/prefect/utilities/visualization.py
tests/test_engine.py
tests/test_tasks.py

I'm working on refactoring the engine for simplicity and performance; as a part of this, I'm attempting to first simplify the structure of the file as much as possible without changing any behavior so that we can transparently review and isolate bigger changes whenever they happen.
This PR moves any functions that don't depend on sync/async conditional logic into their own file, reducing the surface area of the engine file by about 600 LOC.

Engine refactor part 1

---

src/prefect/client/base.py
tests/client/test_base_client.py

We've been sending the default `python-httpx/x.y.z` `User-Agent` header, but
we're missing out on an opportunity for better observability.  This change sets
a Prefect-specific `User-Agent` header for all HTTP requests.
Closes #12539

Giving the Prefect HTTP client an informative `User-Agent`

---

src/prefect/engine.py
tests/events/client/instrumentation/test_task_run_state_change_events.py
tests/test_background_tasks.py
tests/test_task_server.py
tests/test_tasks.py

fixes #12605 
also removes the somewhat arbitrary restriction that you must have the `PREFECT_EXPERIMENTAL_ENABLE_TASK_SCHEDULING` flag on to run a task outside of a flow

allow flows in standalone tasks

---

.github/workflows/python-tests.yaml

`uv==0.1.30` ([release](https://github.com/astral-sh/uv/releases/tag/0.1.30)) seems to break our dep installs in CI
[example](https://github.com/PrefectHQ/prefect/actions/runs/8620086419/job/23626392040?pr=12629)

pin `uv==0.1.29` for now

---

.github/workflows/python-tests.yaml

Reverts PrefectHQ/prefect#12630
https://github.com/astral-sh/uv/pull/2943 should fix https://github.com/astral-sh/uv/issues/2941, avoiding the need for any pin

Revert "pin `uv==0.1.29` for now"

---

src/prefect/events/clients.py
src/prefect/events/utilities.py
src/prefect/events/worker.py
src/prefect/testing/fixtures.py
tests/concurrency/test_concurrency_asyncio.py
tests/concurrency/test_concurrency_sync.py
tests/events/client/conftest.py
tests/events/client/test_cloud_events_client.py
tests/events/client/test_cloud_events_subscriber.py
tests/events/client/test_events_emit_event.py
tests/events/client/test_events_worker.py

Adds a `PrefectEventsClient` that enables event emission to OSS Prefect servers. The existing `PrefectCloudEventsClient` inherits from this new client because emitting events to Prefect Cloud requires authentication.
Note that this PR requires a long-running Prefect server. Emitting events via the ephemeral API will be handled in a subsequent PR.
Closes https://github.com/PrefectHQ/prefect/issues/12631
1. Update the following settings in your Prefect profile:
```
PREFECT_API_SERVICES_EVENT_LOGGER_ENABLED='True'
PREFECT_API_URL='http://localhost:4200/api'
PREFECT_EXPERIMENTAL_EVENTS='True'
```
2. Start a Prefect server:
```
prefect server start
```
3. Run the following code:
```
>>> from prefect.events import emit_event
>>>
>>> def some_function(name: str="kiki") -> None:
... …
```

Enable `EventsWorker` to emit events to Prefect servers

---

scripts/events-coverage
src/prefect/server/api/server.py
src/prefect/server/events/schemas/events.py
src/prefect/server/events/services/event_persister.py
src/prefect/settings.py
tests/conftest.py
tests/events/server/conftest.py
tests/fixtures/time.py
tests/server/events/services/test_event_persister.py

Adds an `EventPersister` service to store received events in the Prefect server's configured database. The service will write to the DB in batches with periodic flushes. The batch size and flush interval can be configured with the `PREFECT_API_SERVICES_EVENT_PERSISTER_BATCH_SIZE` and `PREFECT_API_SERVICES_EVENT_PERSISTER_FLUSH_INTERVAL` settings, respectively.

Add `EventPersister` service to store received events

---

src/prefect/_internal/compatibility/deprecated.py
tests/_internal/compatibility/test_deprecated.py

Pydantic uses a class's docstring for the "description" field in its generated JSON schema. If the subclass that includes this mixin does not specify a docstring, Pydantic will use the mixin's docstring where previously the schema would not have included a description. This mixin's description shouldn't appear in a schema, so if that case arises, we preserve the previous behavior.

Do not use the mixin docstring for the schema

---

src/prefect/server/events/storage/__init__.py

attempting to resolve
```console
ModuleNotFoundError: No module named 'prefect.server.events.storage'
```

Fix events storage import

---

.github/workflows/python-tests.yaml
src/prefect/server/events/storage/database.py
src/prefect/server/utilities/database.py

Updates `write_events` to check for existing events before inserting when using a SQLite database because SQLite doesn't support the `RETURNING` clause when used with SQLAlchemy 1.x.

Fix writing events for SQLite + SQLAlchemy<2

---

tests/server/utilities/test_database.py

This test was failing because it appeared that the `pytest` `monkeypatch` wasn't
being reverted before the teardown.  Using `mock` with explicit contexts here
makes sure that we're only monkeying with the version inside the test itself.

Fixing a flake with the SQLite version check test

---

src/prefect/client/base.py
src/prefect/server/api/clients.py
src/prefect/server/api/dependencies.py
src/prefect/server/api/deployments.py
src/prefect/server/api/flow_runs.py
src/prefect/server/events/actions.py
src/prefect/server/events/jinja_filters.py
src/prefect/server/schemas/responses.py
src/prefect/utilities/schema_tools/hydration.py
tests/conftest.py
tests/events/server/actions/test_infinite_loops.py
tests/events/server/actions/test_jinja_templated_action.py
tests/events/server/actions/test_running_deployment.py
tests/events/server/conftest.py
tests/fixtures/database.py
tests/fixtures/events.py
tests/server/utilities/test_database.py
tests/utilities/schema_tools/test_hydration.py

This brings the `run-deployment` action to parity with Prefect Cloud, which
required bringing quite a few additional things along.
First, we needed to bring the Jinja2 base `Action` and refresh the open-source
version of schema hydration to include Jinja2 support.  This will aid with
several upcoming `Action`s as well.
Second, we needed the support for `created_by`, which was stubbed in for OSS,
but had a fuller implementation in Prefect Cloud.  I've ported the automations
part of that to OSS.
I'm also removing a long-standing TODO to allow some configuration of whether
our custom client will always raise on HTTP errors or not.  The actions template
system expected to get raw responses (and test for 404s, etc).  Making this an
argument to the Prefect HTTP client allows us to change this …

Implementing the `run-deployment` automation action

---

src/prefect/blocks/abstract.py
src/prefect/blocks/notifications.py
src/prefect/logging/__init__.py
src/prefect/logging/loggers.py
src/prefect/server/events/actions.py
tests/events/server/actions/test_sending_notification.py
tests/fixtures/database.py
tests/test_logging.py

Building on the `JinjaTemplatedAction` in previous PRs, this ports the
`SendNotification` action and associated machinery.  During this process, I
introduced the ability for notification blocks to raise custom errors when they
fail, so that block subclasses can share more details when they fail.

Implements the `send-notification` action

---

src/prefect/server/events/schemas/automations.py
tests/events/server/actions/test_jinja_templated_action.py
tests/events/server/actions/test_running_deployment.py
tests/events/server/actions/test_sending_notification.py
tests/events/server/conftest.py

This matches a comparable change in Prefect Cloud, and it was always intended
that the `firing` would be required for any triggered action.  Prefect Cloud had
it as optional for temporary compatibility but that's been corrected now.

Making `TriggeredAction.firing` required

---

docker-compose.yml

Compose v2 doesn't require or use the `version` field, and now prints a warning
about it being obsolete:
https://docs.docker.com/compose/compose-file/04-version-and-name/

Remove `version` from `docker-compose.yml`, as it is now deprecated

---

src/prefect/exceptions.py
tests/test_exceptions.py

taking the following example
```python
from typing import Annotated
from pydantic import BaseModel, Field
NonNegativeInt = Annotated[int, Field(ge=0)]
class User(BaseModel):
name: str
age: NonNegativeInt
class FlowInput(BaseModel):
user: User
other_user: User
@flow
def process_input(flow_input: FlowInput):
pass
process_user(dict(user=dict(name="John", age=-1)))
```
previously surfaced validation errors would not display the field(s) that actually failed validation
```python
prefect.exceptions.ParameterTypeError: Flow run received invalid parameters:
- flow_input: Input should be greater than or equal to 0
- flow_input: Field required
```
this PR includes the whole `loc` part of the error, such that we can see which field(s) failed …

better flow validation error

---

docs/guides/variables.md
src/prefect/variables.py

```python
In [1]: from prefect import variables.Variable
Cell In[1], line 1
from prefect import variables.Variable
^
SyntaxError: invalid syntax
```

Fix import syntax in `variables.Variable` example

---

src/prefect/_internal/compatibility/deprecated.py
tests/_internal/compatibility/test_deprecated.py

When we use `DeprecatedInfraOverridesField`, we always want serialized forms of the object to exclude `job_variables`. Currently, if `exclude=None` when `dict()` is called, we will fail to exclude `job_variables`. This PR fixes that.

exclude job_variables when exclude=None

---

src/prefect/events/actions.py
src/prefect/server/events/actions.py
src/prefect/server/utilities/http.py
tests/events/server/actions/test_calling_webhook.py

Adds the `CallWebhook` action to use a invoke a configured Webhook block. This
also adds client-side schemata for all supported Action types on both OSS
and Prefect Cloud.

Implements the `call-webhook` action and adds all Action client-side schemata

---

src/prefect/server/api/clients.py
src/prefect/server/events/actions.py
src/prefect/server/utilities/http.py
tests/events/server/actions/test_cancelling_flow_run.py
tests/events/server/actions/test_changing_flow_run_state.py
tests/events/server/actions/test_suspending_flow_run.py

The two original actions (cancel and suspend) have converged into
specializations of the general purpose `change-flow-run-state` action and
represent a family of actions that work essentially the same.

Implements `change-flow-run-state`, `cancel-flow-run`, and `suspend-flow-run`

---

docs/tutorial/tasks.md

The `repo_info.py` script is missing an import statement to use `Optional` and had dtype typos that caused the script to fail.
Running:
Python: 3.11.8
Prefect: 2.16.9

Fix `typing` import and dtype typos in Tasks tutorial

---

src/prefect/server/events/actions.py
src/prefect/server/events/jinja_filters.py
tests/events/server/actions/test_actions_service.py
tests/events/server/actions/test_calling_webhook.py
tests/events/server/actions/test_cancelling_flow_run.py
tests/events/server/actions/test_changing_flow_run_state.py
tests/events/server/actions/test_pausing_resuming_automation.py
tests/events/server/actions/test_pausing_resuming_deployment.py
tests/events/server/actions/test_pausing_resuming_work_pool.py
tests/events/server/actions/test_pausing_resuming_work_queue.py
tests/events/server/actions/test_running_deployment.py
tests/events/server/actions/test_sending_notification.py
tests/events/server/actions/test_suspending_flow_run.py

While introducing automations to open-source, we want to be consistent with the
naming of events, since all orchestration domain concepts use events and labels
like `prefect.*`.  While automations started life in Prefect Cloud, they are
now going to be considered orchestration domain objects.  This will break a
conceptual compatibility for the near term: if you're triggering on
`prefect.automation.*` events in OSS, you'll need to change that to
`prefect-cloud.automation.*` in order to deploy that to Prefect Cloud.  We're
good with that tradeoff until we can get the concepts in Prefect Cloud renamed
as well.

Renaming `prefect-cloud.*` events and labels to `prefect.*`

---

docs/getting-started/installation.md

Python 3.12 has been GA for nearly 6 months and we have tested it and released Docker images against it for over 3 months without issue. I think it's worth removing the note in the docs install guide that support is experimental.

Remove disclaimer for Python 3.12 experimental support

---

flows/automation-assessments.py
flows/client_context_lifespan.py
flows/deployment_run.py
flows/deployment_storage.py
flows/flow_pauses.py
scripts/run-integration-flows.py
src/prefect/events/__init__.py
src/prefect/events/clients.py
src/prefect/server/api/events.py
tests/events/client/test_events_client.py
tests/events/client/test_events_subscriber.py
tests/events/server/gateway/test_gateway_out.py

This gives us two top-level functions that will choose the correct
implementation subclasses for event clients and subscribers, depending on
your `PREFECT_API_URL`.  This also parametrizes most of the tests to check all
four client types.
Note: this is also sprawling into an attempt to correct the integration tests,
which were silently exiting the process when they weren't compatible with the
current server version.

Adding helper functions for creating an events client or subscriber

---

docs/concepts/automations.md

Changes the Python composite trigger example to use a dictionary for each inner trigger to keep user-facing classes to a minimum and align with the other examples.

Clarify deployment trigger examples

---

flows/automation-assessments.py

Running this flow as part of Prefect Cloud's CI integration tests won't work
because we need additional components and infrastructure running.  We can
skip this test for Prefect Cloud because we already have another version of this
integration test running continually against our test environment.

Disable the automations integration flows for Prefect Cloud

---

RELEASE-NOTES.md

Release notes for 2.18.0

---

src/prefect/cli/deploy.py
src/prefect/deployments/deployments.py
src/prefect/deployments/runner.py
src/prefect/events/schemas/automations.py
src/prefect/events/schemas/deployment_triggers.py
src/prefect/flows.py
src/prefect/runner/runner.py
tests/events/client/test_deployment_trigger_schema.py
tests/test_deployments.py

The `Deployment*Trigger` classes help capture some additional information about
the automation to create (name, description, whether it's enabled, etc) or
about how to customize the `RunDeployment` action, which can be useful for
stored triggers in a `prefect.yaml`.  When serving flows dynamically or when we
don't need as much customization, we can also accept triggers from the "normal"
`Trigger` hierarchy.
This allows doing this:
```
from prefect.events import EventTrigger
@flow
def my_flow():
pass
my_flow.serve(name="my-server", triggers=[EventTrigger(expect={"some.event"})])
```
This also makes the `Deployment*Trigger` classes subclasses of their respective
`Trigger` types to avoid duplicating fields and validations.

Add support for using the "normal" Trigger classes for flow.serve and .deploy

---

.github/workflows/api-compatibility-tests.yaml
.gitmodules
scripts/generate_oss_openapi_schema.py
scripts/run-compatibility-tests

Our [`compat-tests`](https://github.com/PrefectHQ/compat-tests) have been
running with every Prefect Cloud CI build for some time now.  Here, we also
start running them with every `PrefectHQ/prefect` pull request as well.  This
will help to catch incompatibilities earlier and prevent the scenario where an
addition in OSS will cause the _next_ Prefect Cloud build to fail.
Part of PrefectHQ/compat-tests#16

Run `compat-tests` as part of CI

---

requirements-dev.txt
setup.cfg
src/prefect/_internal/schemas/fields.py
src/prefect/blocks/system.py
src/prefect/events/actions.py
src/prefect/events/clients.py
src/prefect/events/filters.py
src/prefect/events/instrument.py
src/prefect/events/related.py
src/prefect/events/utilities.py
src/prefect/events/worker.py
src/prefect/server/events/filters.py
src/prefect/server/utilities/schemas/fields.py
tests/server/utilities/test_schemas.py
tests/utilities/test_templating.py

We have a long-term goal to have the entire Prefect library pass mypy in strict
mode, and the journey of a thousand miles starts with a single step.  This
resets the `mypy` configuration we had and starts with a couple of modules we've
identified to tackle today.  This includes the client-side events code.
Probably the most controversial thing I'm doing here is making `DateTimeTZ` just
an alias to `DateTime` and then dynamically adding the appropriate `pydantic`
validator functions to it.  This allows us to avoid a giant swath of typing
errors where it looks like we're downcasting a `DateTime` to a `DateTimeTZ`.
This change has been in effect on Prefect Cloud for some time now, so I'm pretty
confident that it is a drop-in replacement for what we were doing before.

Preparing to introduce `mypy` checking, starting with client-side events

---

requirements-dev.txt
setup.cfg
src/prefect/blocks/core.py
src/prefect/blocks/notifications.py
src/prefect/cli/_types.py
src/prefect/cli/dev.py
src/prefect/cli/root.py
src/prefect/events/instrument.py
src/prefect/events/schemas/automations.py
src/prefect/events/schemas/deployment_triggers.py
src/prefect/events/schemas/events.py
tests/events/client/cli/test_automations.py
tests/events/client/instrumentation/test_task_run_state_change_events.py
tests/events/client/test_automations_server_compatibility.py
tests/events/client/test_deployment_trigger_schema.py
tests/events/client/test_events_emit_event.py
tests/events/client/test_events_worker.py
tests/events/client/test_resource_schema.py
tests/events/client/test_v1_triggers_deserialization.py
tests/fixtures/client.py

The original mypy file selector was excluding files in deeper directories.  This
simplifies it to just include the directories we're able to check types on.
I also took a pass through all the low-hanging fruit in `tests/events/client`,
but we'll need to do some more work on the fundamentals first.

`mypy` coverage for the rest of client-side events

---

.github/workflows/create-tags-for-changed-integrations.yaml
scripts/create_tags_for_changed_collections.py

this PR adds:
- a script that creates new GitHub tags for each changed collection given a current commit and previous tag
- a github action to trigger this script on published release of prefect core, or workflow dispatch
when we release prefect core or trigger via `workflow_dispatch`, we will:
- discover all modified collections
- fetch the latest tag for each such collection
- create and push a new tag for each such collection, a PATCH bump is assumed for now
tested [here](https://github.com/zzstoatzz/integration-monorepo/tags)
<details>
```python
» PREVIOUS_TAG=0.1.0 CURRENT_COMMIT=d811e10e7de8fba01f490aeb1a35c05f60a97dab python scripts/create_tags_for_changed_collections.py
[04/19/24 13:44:45] INFO     gh_util.client: AUTH: Using token from env vars `GITHUB_TOKEN` …
```

Create integration tags on published release

---

docs/api-ref/prefect/concurrency/common.md
mkdocs.yml

https://github.com/PrefectHQ/prefect/pull/12803 removed `prefect.concurrency.common`, but docs build is still looking for it

rm references to deleted concurrency module

---

src/prefect/engine.py
tests/test_tasks.py

fixing another improper assumption of having an attr (`flow` in this case) on `FlowRunContext` in a nested task outside of flow situation

Fix improper context access for nested async task outside of flow

---

scripts/generate-release-notes.py

Ensures we can retrieve the latest release commits from integrations repos. 
- Add `get_latest_and_previous_tags` fn to correctly fetch and handle tags from GitHub
- Add `clean_integrations_changelog` fn to cleanup the integrations changelog

Fix release notes integrations section generation

---

docs/concepts/schedules.md
docs/guides/using-the-client.md

users (that are not contributing server-side changes) should never have to import `server` schemas

remove bad/old import recommendations

---

src/prefect/client/orchestration.py
src/prefect/server/api/deployments.py
src/prefect/server/models/deployments.py
src/prefect/server/models/events.py
src/prefect/server/models/work_queues.py
src/prefect/server/orchestration/core_policy.py
src/prefect/server/orchestration/instrumentation_policies.py
src/prefect/server/services/late_runs.py
src/prefect/settings.py
tests/fixtures/events.py
tests/server/orchestration/test_flow_run_instrumentation_policies.py
tests/server/services/test_late_runs.py

This represents parity with Prefect Cloud for instrumenting flow run state
changes with events with an orchestration rule.  The events are emitted
synchronously during the request/response cycle.

Flow run state change events

---

Makefile
scripts/serve_docs

since serving the docs will require all integration libraries be installed (to build api refs from docstrings etc) this PR adds a script to handle that for us
`make docs` will:
- run `./scripts/serve_docs` if its executable, otherwise prompt the user to make it so and retry
- install all collection / core deps in a `uv` `venv` in a tmpdir
- start a hot-reloading `mkdocs serve` process
i tried messing with it to `open` the browser for you, but since
- `open` i dont think works for most linux
- `mkdocs serve` is blocking
- `mkdocs serve` gives you a link to the serve address anyways
it seemed more trouble than it was worth
___
this PR also introduces a `Makefile`, which @chrisguidry has mentioned we should do at some point

Add serve docs script

---

src/prefect/new_flow_engine.py
src/prefect/new_task_engine.py
tests/test_new_flow_engine.py
tests/test_new_task_engine.py

Adds flow run retries in the new flow engine. Also updates a couple of tests to use async flows and tasks so that they'll pass and refactors the flow run engine to look more like the task run engine.

Implement flow retries in new flow engine

---

src/prefect/utilities/schema_tools/validation.py

if a `definitions` value is falsy, we should not try to call `.values()` on it

update handling where definitions falsy

---

.github/workflows/prefect-client.yaml

previously was running on every `push` to `main`, which does not seem necessary at all

Avoid running the `prefect-client` build all the time

---

src/prefect/new_flow_engine.py
src/prefect/utilities/asyncutils.py
tests/utilities/test_asyncutils.py

One of my favorite things about the new engine (there are many) is that it eliminates the separate execution branches and logic for subflow runs. Now there is only a small amount of bookkeeping that has to be done. 
This PR stems from an odd behavior observed in the tests for https://github.com/PrefectHQ/prefect/pull/12889, in which a test that is currently passing on main started failing without clear catalyst. 
[This test](https://github.com/PrefectHQ/prefect/blob/ebb42b0fe328c8c3486344c43fb227d28563a483/tests/test_new_flow_engine.py#L568-L603) is currently passing on `main`, but is actually doing the right thing for the wrong reason. As written it is a synchronous flow and synchronous subflow, but if you switch both flows to async (on `main`) the test will fail. 
The test is supposed …

Fix subflow handling in new engine

---

src/prefect/server/api/workers.py

The workers API wasn't differentiating between previously ready and unready
work queues, it was just marking them _all_ ready and emitting their event.
This would cause work queues to emit a ready event every time they were polled.

Correcting an issue that would cause the `work-queue.ready` event to overfire

---

src/prefect/events/cli/automations.py
tests/events/client/cli/test_automations.py

- Previously, the `automation pause` and `resume` cmds accepted a single parameter `id_or_name`, which could be either an ID or a name. These functions have been refactored to separate these inputs into two distinct optional parameters: `name` and `id`, consistent with `automation delete`, `automation inspect`, etc.
- The logic in the `pause` and `resume` functions have been updated to ensure that either a name or an ID is provided.
- Added handling for cases where multiple automations are found when using the `name` parameter.
- The updated code includes more detailed comments and revised documentation strings that clarify the purpose and usage of each parameter and function.
```bash
❯ prefect automation pause --help
Usage: prefect automation pause [OPTIONS] [NAME] …
```

Update `automation pause` and `automation resume` to handle automations with same name

---

src/prefect/cli/block.py
tests/cli/test_block.py

Fix https://github.com/PrefectHQ/prefect/issues/6676
```bash
❯ prefect block inspect my-block
'my-block' is not valid. Slug must contain a '/', e.g. 'json/my-json-block'
```
```bash
❯ prefect block delete my-block
'my-block' is not valid. Slug must contain a '/', e.g. 'json/my-json-block'
```

Raise a better error when deleting and inspecting blocks

---

src/prefect/flows.py

This PR modifies the behavior of `flow.serve` to no longer require passing a name for the subsequently-created deployment, instead defaulting to the name of the flow. 
Example:
```py
@flow
def etl_flow():
pass
etl_flow.serve()
```
results in:
```
Your flow 'etl-flow' is being served and polling for scheduled runs!
To trigger a run for this flow, use the following command:
$ prefect deployment run 'etl-flow/etl-flow'
```

Enhancement: Make name optional when running `flow.serve`

---

src/prefect/cli/_types.py
src/prefect/cli/root.py

fixes bad interactive CLI detection that seems to have been introduced by https://github.com/PrefectHQ/prefect/pull/12800
leading to the following behavior (currently on `main`)
```python
» prefect cloud login
When not using an interactive terminal, you must supply a `--key` and `--workspace`.
```
even though
```python
In [1]: from rich.console import Console
In [2]: Console().is_interactive
Out[2]: True
```
which is the only thing that should matter with `PREFECT_CLI_PROMPT` unset

Revert console setup changes to fix interactivity

---

docs/concepts/automations.md
src/prefect/client/schemas/objects.py
src/prefect/server/api/clients.py
src/prefect/server/api/workers.py
src/prefect/server/database/migrations/versions/postgresql/2024_04_25_155240_8905262ec07f_worker_status_field.py
src/prefect/server/database/migrations/versions/sqlite/2024_04_25_155120_a8e62d4c72cf_worker_status_field.py
src/prefect/server/database/orm_models.py
src/prefect/server/events/actions.py
src/prefect/server/models/events.py
src/prefect/server/models/workers.py
src/prefect/server/schemas/__init__.py
src/prefect/server/schemas/actions.py
src/prefect/server/schemas/core.py
src/prefect/server/schemas/filters.py
src/prefect/server/schemas/internal.py
src/prefect/server/schemas/responses.py
src/prefect/server/services/foreman.py
src/prefect/settings.py
tests/server/api/test_workers.py
tests/server/database/test_queries.py
tests/server/models/test_workers.py
tests/server/services/test_foreman.py

This implements the work pool status events, using persisted information on
the work pool and workers to decide when to emit the events.
Inspecting the output from the `EventLogger` debugging service:
```
...start up a worker...
Event: f24dc1ee 2024-04-29T18:25:15.628018+00:00  ( -0.00) 
[prefect.work-pool.ready] prefect.work-pool.513c569d-0e93-4841-91d4-bc0d596e9163
Event: e5f4fa72 2024-04-29T18:25:15.700495+00:00  ( -0.00) 
[prefect.work-queue.ready] 
prefect.work-queue.64c0f2c6-bce3-41e4-a1cc-20a26a5bb581
Event: 14c047a8 2024-04-29T18:25:15.706885+00:00  ( -0.01) 
[prefect.deployment.ready] 
prefect.deployment.4f4e186c-b159-451c-9647-5fe638e434b5
...start up a second worker...
...kill first worker...
14:27:28.802 | INFO    | prefect.server.services.foreman - Marked 1 workers as …
```

Implementing work pool status events

---

src/integrations/prefect-databricks/prefect_databricks/flows.py
src/integrations/prefect-databricks/tests/test_flows.py

When a databricks notebook is submitted for execution, it kicks off a cascade of subflows; when this notebook fails, it's difficult to get at the logs and to find the URL of the notebook execution that was created without having to click through all those subflows. This updates the return of `jobs_runs_submit_and_wait_for_completion` with the full metadata output of the job so that it can bubble up to the parent flow that kicks off this works - this means, for example, the notebook URL can be logged at the very top.
```python
from prefect import flow, get_logger
from prefect_databricks import jobs_runs_submit_and_wait_for_completion
@flow
def my_flow():
logger = get_logger()
notebook_output, jobs_meta = jobs_runs_submit_and_wait_for_completion(...) …
```

Log full output of databricks job

---

tests/test_tasks.py

Updates `fails_with_new_engine` to fail when decorated tests pass unexpectedly. Also, removes decorators from tests that now pass with changes in https://github.com/PrefectHQ/prefect/pull/12889.

Fixes `fails_with_new_engine` to fail tests when they pass unexpectedly

---

src/prefect/new_flow_engine.py
src/prefect/new_task_engine.py
tests/test_new_flow_engine.py
tests/test_new_task_engine.py

The new engine currently doesn't handle args/kwargs because they are not "unwrapped" appropriately (they are passed to the underlying functions as literally `args=<args>` and `kwargs=<kwargs>`. This PR calls the appropriate utility to prepare them for the function call, and adds tests.
```python
@task
def f(**kwargs):
return kwargs
assert f(x=1, y=2) == {'x': 1, 'y': 2}
```

New engine: handle *args / **kwargs correctly

---

src/integrations/prefect-gcp/prefect_gcp/aiplatform.py
src/integrations/prefect-gcp/prefect_gcp/credentials.py
src/integrations/prefect-gcp/prefect_gcp/workers/vertex.py
src/integrations/prefect-gcp/tests/conftest.py
src/integrations/prefect-gcp/tests/test_aiplatform.py
src/integrations/prefect-gcp/tests/test_credentials.py
src/integrations/prefect-gcp/tests/test_vertex_worker.py

Closes #12875 
- Clarifies logging
- Changes confusing/delayed logs about job state changes to debug level
- Fixes blocking sync sleep causing slow job submission by switching to `JobServiceAsyncClient`
- Caches Vertex job service client for stable high volume concurrent job monitoring
While trying to test performance for concurrent job submission, I noticed that simultaneously submitted jobs were beginning very slowly. When submitting 3 jobs for example, the time between the flow run being picked up by the agent/worker and the job being created on Vertex for the third job was 10 seconds. This was due to the sync sleep during Vertex job state change polling not happening in its own thread. Switching to the `JobServiceAsyncClient`  eliminates the needs for thread management and uses async …

Vertex AI performance pass

---

src/prefect/server/events/services/event_persister.py
src/prefect/settings.py
tests/events/server/storage/test_event_persister.py

This setting, `PREFECT_EVENTS_RETENTION_PERIOD`, will be enforced periodically
by the event persister service as it is recording other events.  The setting
defaults to 7 days but can be set arbitrarily high.

Adding a retention policy for events

---

src/integrations/prefect-databricks/prefect_databricks/rest.py

We're testing a codebase with both pydantic v1 & v2 and we found the v1 versions failing with:
```
NameError: name 'V2BaseModel' is not defined
```
We observed this happen sometime after [0.2.3](https://pypi.org/project/prefect-databricks/0.2.3/).
I'm not sure what your test suite looks like and/if you test with both versions of Pydantic - so it's not clear to me how to add another unit test for this.

Fix pydantic v1 prefect-databricks

---

src/prefect/server/api/server.py
tests/server/test_app.py

This adds the value of `PREFECT_SERVER_CSRF_PROTECTION_ENABLED` to the UI settings so the UI can more intelligently turn on / off CSRF support.

Add `csrf_enabled` setting to UI settings

---

src/prefect/cli/flow_run.py
src/prefect/client/schemas/objects.py
tests/cli/test_flow_run.py

```bash
❯ prefect flow-runs ls --help
Usage: prefect flow-runs ls [OPTIONS]                                                                                                                                                                        
View recent flow runs or flow runs for specific flows.                                                                                                                                                       
Arguments:                                                                                                                                                                                                   
flow_name: Name of the flow …
```

Allow case-insensitive state and state type handling when listing flow runs via CLI

---

docs/concepts/work-pools.md
src/prefect/server/api/collections_data/views/aggregate-worker-metadata.json
src/prefect/workers/process.py

Closes #10842
Updates docs and server instance UI to refer to Process work pool instead of subprocess. 
Most places it already was Process (e.g. CLI, type in UI, most docs).

Standardize work pool name as Process

---

scripts/collections-manager

most of the code was related to managing the complexity of many github repos, which is no longer the case
similarly, bumping patch versions is all done via github tags, but we have GHAs for that now
because the idea of applying a function across all collections is so useful, I've reimplemented it here for the new setup
`scripts/functions/test.py`
```python
from pathlib import Path
def print_first_line_of_readme(repo: Path):
print((repo / "README.md").read_text().split("\n")[0])
```
```console
» ./scripts/collections-manager run-function scripts.functions.test:print_first_line_of_readme
```

update `collection-manager` for monorepo

---

src/prefect/server/database/migrations/versions/postgresql/2024_05_01_105401_b23c83a12cb4_add_catchup_fields_to_deploymentschedule.py
src/prefect/server/database/migrations/versions/sqlite/2024_05_01_103824_20fbd53b3cef_add_catchup_fields_to_deploymentschedule.py
src/prefect/server/database/orm_models.py

adds columns to the `ORMDeploymentSchedule`
```python
max_active_runs = sa.Column(sa.Integer, nullable=True)
max_scheduled_runs = sa.Column(sa.Integer, nullable=True)
catchup = sa.Column(sa.Boolean, nullable=False, default=False)
```
and adds the corresponding migrations

Add columns to ORM `DeploymentSchedule` and add migrations

---

src/prefect/events/schemas/events.py
src/prefect/server/events/filters.py
src/prefect/server/events/schemas/events.py
tests/events/client/test_resource_schema.py
tests/events/server/test_events_queries.py
tests/events/server/test_resource_schema.py

This supports several otherwise painful use cases for triggers, like being able
to match on any tag _except_ `prod`, or any flow _except_ ones starting with
`testing_`.
When there's a negative label, the resource MUST have the label, and it also
must not match the value.
Example:
```
{
"my-label": ["this*", "!this", "!this-either", "!this-never*"]
}
```
Would match resources with labels:
```
{"my-label": "this is fine"}
{"my-label": "this is great"}
```
But not these labels:
```
{"my-label": "this"}
{"my-label": "this-either"}
{"my-label": "this-never-could-match"}
{"my-label": "this-never-should-match"}
{"some-other-label": "because I don't have my-label"
```
Fixes #12776

Support for negative label values in `ResourceSpecification` and filters

---

RELEASE-NOTES.md

Some are mistakenly interpreting the current text in the release notes to mean that we have removed the `prefect deploy` wizard, when that is in fact not the case. We love the wizard and are merely streamlining and removing a long deprecated command group, command options and flags. 🧙

Clarify breaking changes in release notes

---

docs/concepts/automations.md
src/prefect/server/models/events.py
tests/server/api/test_workers.py
tests/server/services/test_foreman.py

This event was mis-named in both Prefect Cloud and in the Prefect port, and we
will be automatically migrating Prefect Cloud automations in order to rename
them there.

Renaming `prefect.work-pool.not_ready` to `prefect.work-pool.not-ready`

---

src/prefect/settings.py
src/prefect/utilities/asyncutils.py
tests/utilities/test_asyncutils.py

This PR adds a new experimental setting that, when set, _disables_ the `sync_compatible` interface. As we continue to build out the new engine we are confronting various issues with sync/async interfaces and this allows us to test.  The ultimate goal will be to remove this utility entirely, but this setting will help us do that safely.

Add new sync compat setting

---

ui/src/components/ContextSidebar.vue
ui/src/pages/FlowRun.vue

In an effort to reduce the top-level surface area of user entrypoints in the UI, this PR removes:
- the Artifacts nav item
- the Artifacts tab on the flow run page
The goal here is to reduce the # of forks at the highest level of the app. While artifacts can be created and exist outside the context of flows, they rarely are and so we want the UI to better reflect the relationship that artifacts do have - namely with flow runs and task runs. 
After these changes, artifacts are still available in the UI through the flow run graph on the flow run page. Their individual pages are also still available and exposed throughout the app but just not via top-level site navigations.

Chore/prune artifact UI entrypoints

---

src/prefect/client/orchestration.py
tests/client/test_prefect_client.py

When using the `update_deployment_schedule` method in the client, users should be able to pass in both an `active` argument and a `schedule` argument to have both updated.
fixes #13243 
```python
await prefect_client.update_deployment_schedule(
deployment.id,
deployment.schedules[0].id,
schedule=IntervalSchedule(interval=timedelta(minutes=15)),
active=False,
)
```

Allow both active and schedule params

---

src/prefect/client/base.py
src/prefect/client/orchestration.py
src/prefect/new_flow_engine.py
src/prefect/new_task_engine.py

A nested task test has been causing intermittent failures e.g. https://github.com/PrefectHQ/prefect/actions/runs/8972915998/job/24641970356. The failures appear related to SQLite contention.
Prefect API clients retry on certain API errors, including SQLite database locked errors, that indicate transient issues. The sync engine currently uses a Starlette TestClient for synchronous access to the ephemeral API. However, that TestClient doesn't have any of Prefect's retry logic. This PR replaces the raw TestClient with one that inherits our retry behavior.

Use Prefect-specific TestClient for sync calls

---

src/prefect/utilities/timeout.py

Small PR that skips opening the timeout context if no timeout is set. This has minor QOL benefits, including not trapping keyboard interrupts and manipulating signals (on sync branches)

[New engine] Skip timeout context if not needed

---

src/prefect/server/orchestration/core_policy.py
tests/server/orchestration/test_core_policy.py

Since `Resuming` is just a `Scheduled` state for flow runs that have been suspended, they have no associated infrastructure and should transition directly from `Cancelling` to `Cancelled`.

Add `Resuming` flow runs to `BypassCancellingFlowRunsWithNoInfra` orchestration policy

---

setup.py

With the addition of the `prefect-dask` codebase directly into `prefect`, I think it's worth considering adding support for `pip install prefect[dask]` as a convenience option for end-users. I have enabled this by modifying `setup.py`.

Add support for `pip install prefect[dask]`

---

src/prefect/blocks/notifications.py

Fixes `apprise` [tests](https://github.com/PrefectHQ/prefect/actions/runs/9063969160/job/24901105992) failing after release of [apprise 1.8.0](https://github.com/caronc/apprise/releases/tag/v1.8.0).

Fix `apprise 1.8.0` imports

---

src/prefect/client/orchestration.py
src/prefect/client/schemas/actions.py
src/prefect/new_task_engine.py
src/prefect/server/api/task_runs.py
src/prefect/server/schemas/actions.py
src/prefect/tasks.py
tests/server/api/test_task_runs.py
tests/test_new_task_engine.py

When working on the new task run engine, we identified an opportunity to remove our API as a bottleneck when submitting tasks to remote infrastructure, allowing the client to generate a UUID and provide that as the ID when creating a task run. Using a client-generated ID will enable us to submit to the task execution layer before creating a task run on the server while also allowing future enhancements where the client can track dependencies between runs.

Allow client-provided ID when creating a task run

---

.github/workflows/integration-tests.yaml

Ensure we test the latest release of `2.19.0` as well as prior versions.

Add 2.19 to compatibility tests

---

.github/workflows/python-tests.yaml
requirements-client.txt
requirements.txt

This also removes the extra CI checks for the 1.x series of those two libraries,
as well as enabling our experimental pydantic flag for all unit tests.

Pin the lower bounds of `pydantic` and `sqlalchemy` for 3.x line

---

src/prefect/context.py
src/prefect/filesystems.py
src/prefect/flows.py
src/prefect/results.py
src/prefect/serializers.py
src/prefect/settings.py

starts the process of replacing the pydantic conditional imports with just imports from the v1 backport of v2 since we will always have pydantic 2 on main

rm `not HAS_PYDANTIC_v2` branch of conditional imports from top level modules

---

src/integrations/prefect-gcp/prefect_gcp/workers/cloud_run_v2.py
src/integrations/prefect-gcp/tests/test_cloud_run_worker.py
src/prefect/exceptions.py

forgot to use v1 import in https://github.com/PrefectHQ/prefect/pull/13330
and fixes https://github.com/PrefectHQ/prefect/issues/13333, which was actually unrelated - although we did have a expected error mismatch where we are raising our own internal `ValidationError` from `schema_tools` but were expecting the one from `jsonschema` in the tests

use v1 validation error

---

ui/.vscode/settings.json
ui/src/components/AutomationActionTypeSelect.vue
ui/src/components/AutomationCard.vue
ui/src/components/AutomationTriggerJsonInput.vue
ui/src/components/AutomationTriggerTemplateSelect.vue
ui/src/components/AutomationWizard.vue
ui/src/components/AutomationWizardAction.vue
ui/src/components/AutomationWizardStepActions.vue
ui/src/components/AutomationWizardStepDetails.vue
ui/src/components/AutomationWizardStepTrigger.vue
ui/src/components/ContextSidebar.vue
ui/src/maps/automation.ts
ui/src/maps/featureFlag.ts
ui/src/maps/index.ts
ui/src/pages/Automation.vue
ui/src/pages/AutomationCreate.vue
ui/src/pages/AutomationEdit.vue
ui/src/pages/Automations.vue
ui/src/router/index.ts
ui/src/services/automationsApi.ts
ui/src/types/automation.ts
ui/src/types/automationCreate.ts
ui/src/types/automationCreateRequest.ts
ui/src/types/automationResponse.ts
ui/src/types/flagResponse.ts
ui/src/utilities/api.ts
ui/src/utilities/permissions.ts

Users can now manage their automations via the ui. Automations in Prefect enable you to configure [actions](https://docs.prefect.io/latest/concepts/automations/#actions) that Prefect executes automatically based on [trigger](https://docs.prefect.io/latest/concepts/automations/#triggers) conditions.
To enable set `PREFECT_EXPERIMENTAL_EVENTS=True` and `PREFECT_API_SERVICES_TRIGGERS_ENABLED=True` in your prefect profile. 
Read more about automations in the [prefect automation docs](https://docs.prefect.io/latest/concepts/automations/).
The following preconfigured trigger templates are available
- Deployment status
- Flow run state
- Work pool status
- Work queue status
The following actions are available
- Cancel a flow run
- Suspend a flow run
- Change a flow run's state
- Pause a …

Create and manage automations in the UI 

---

src/prefect/_internal/schemas/validators.py
src/prefect/client/schemas/actions.py
src/prefect/client/schemas/objects.py
src/prefect/flows.py
src/prefect/server/api/workers.py
src/prefect/server/schemas/actions.py
src/prefect/server/schemas/core.py
src/prefect/types/__init__.py
tests/server/api/test_work_queues.py
tests/server/api/test_workers.py
tests/server/models/test_concurrency_limits_v2.py
tests/server/models/test_workers.py
tests/server/schemas/test_core.py

There were a few sub-flavors of this, but I was most surprised that we allow
for `Deployments` to have empty string names.  I'll track that separate issue.
My aim here was for no behavioral changes except for the new normalized
validation message from Pydantic (and the 422s instead of 400s).

Migrating all uses of the banned characters validation to a self-validator

---

docs/integrations/prefect-dask/index.md
docs/integrations/prefect-ray/index.md

Match format of other integration libraries.

Update Ray integration docs

---

tests/cli/test_deploy.py
tests/conftest.py
tests/deployment/test_steps.py
tests/results/test_flow_results.py
tests/runner/test_runner.py
tests/test_flows.py
tests/test_new_task_engine.py
tests/test_tasks.py

We've had trouble in the past with tests inadvertently writing files to the
current working directory instead of isolated to a temporary directory.  It's
far too easy to introduce these, and they can be frustrating to track down.
This adds a module-level autouse fixture to alert us when a test suite had
dropped new files in the working tree.
Counterpart of #13380

Fixing stray files from the test suite, with a utility to notify us about them

---

.github/workflows/codeql-analysis.yml

This has been putting a little annotation icon on all our CI checks with the
message:
```
The setup-python-dependencies input is deprecated and no longer has any effect.
We recommend removing any references from your workflows.
See https://github.blog/changelog/2024-01-23-codeql-2-16-python-dependency-installation-disabled-new-queries-and-bug-fixes/
for more information.
```

Removes an unused/deprecated parameter from CodeQL checks

---

src/integrations/prefect-dbt/prefect_dbt/cli/commands.py
src/integrations/prefect-dbt/tests/cli/test_commands.py

Currently in prefect-dbt 0.4.3, unsuccessful dbt core runs will cause the Prefect task to fail. This changes the new, programmatically-invoked dbt tasks to match that behavior. Compares with #13405 

prefect-dbt - 2.x Cause unsuccessful dbt tasks to fail 

---

src/prefect/flows.py
src/prefect/tasks.py
src/prefect/testing/standard_test_suites/task_runners.py
tests/events/client/instrumentation/test_task_run_state_change_events.py
tests/events/client/test_events_related_from_context.py
tests/events/client/test_events_worker.py
tests/test_engine.py
tests/test_flows.py
tests/test_futures.py
tests/test_logging.py
tests/test_new_flow_engine.py
tests/test_tasks.py

Removes all uses of the `._run` interface; this interface simply hard-coded `return_state=True`, which IMO does not justify having more interface surface area to maintain even if it is private.

Remove private run methods

---

docs/concepts/automations.md

When using the example in the doc for an email notification automation:
| **Before** | **After** |
| <img width="816" alt="image" src="https://github.com/PrefectHQ/prefect/assets/22418768/460dfd5c-780f-4e5e-9b58-319ee6fedba6"> | <img width="811" alt="image" src="https://github.com/PrefectHQ/prefect/assets/22418768/0d7d483a-80b2-47fd-801f-ae6f1458a75e"> |
Notice that before, the related resources being rendered are actually all just the top-level resource.

Fix jinja template in automations doc.

---

src/prefect/client/orchestration.py
src/prefect/context.py
src/prefect/flows.py
src/prefect/new_flow_engine.py
src/prefect/new_futures.py
src/prefect/new_task_engine.py
src/prefect/new_task_runners.py
src/prefect/states.py
src/prefect/tasks.py
src/prefect/utilities/collections.py
src/prefect/utilities/engine.py
tests/client/test_prefect_client.py
tests/test_new_flow_engine.py
tests/test_new_futures.py
tests/test_new_task_runners.py
tests/test_tasks.py

This PR creates a new interface for task runners and prefect futures to work with the new engine. The new `ThreadPoolTaskRunner` is intended to replace the existing `ConcurrentTaskRunner`. The new `PrefectFuture` implementation is meant to serve as a wrapper for specific future implementations. More implementations will be added when we update the Dask and Ray task runners.
This PR turns on the logic to run the existing task tests through the new engine to ensure compatibility and expose differences. 
Two main differences are:
1. `.submit` on a task is always a sync call
2. `.result` and `.wait` on a `PrefectFuture` are always sync calls
Example of a flow submitting tasks to a `ThreadPoolTaskRunner` (should look familiar)
```python
from time import sleep …
```

[New Engine] Add new `ThreadPoolTaskRunner` and new `PrefectFuture` implementation

---

src/prefect/testing/utilities.py

The `server` submodule imports our models, schemas, services, and more. The `dependencies` module itself also imports a lot from `server`. I think it's better to defer this when we can. The imports that leaked due to that were leading to runtime errors in our tests from `events_persister`. See that PR for details: https://github.com/PrefectHQ/prefect/pull/13426

Defer import of `temporary_database_interface` in testing utilities

---

src/prefect/server/events/services/event_persister.py

Previously, the `asyncio.Event` was being initialized directly within the class constructor, which was leading to issues in tests, such as 
```bash
RuntimeError("There is no current event loop in thread \'AnyIO worker thread\'.")
```
where event loop wasn't available. 
This PR removes direct instantiation of `asyncio.Event` from the class constructor, and adds a property method `started_event` that initializes the `asyncio.Event` upon first access. It adds a setter method for `started_event` to allow controlled modification in the tests
This hopefully also reduces overhead during class instantiation, only creating the event when needed instead of upon import. This will hopefully prevent runtime errors when this module is imported as part of future tests as well.
<details>
<pre>
assert …

Lazily instantiate `asyncio.Event` in `EventPersister` for context safety

---

src/prefect/server/events/models/automations.py
src/prefect/server/models/agents.py
src/prefect/server/models/artifacts.py
src/prefect/server/models/block_documents.py
src/prefect/server/models/block_schemas.py
src/prefect/server/models/block_types.py
src/prefect/server/models/concurrency_limits.py
src/prefect/server/models/deployments.py
src/prefect/server/models/flow_run_notification_policies.py
src/prefect/server/models/flow_runs.py
src/prefect/server/models/flows.py
src/prefect/server/models/saved_searches.py
src/prefect/server/models/task_runs.py
src/prefect/server/models/variables.py
src/prefect/server/models/work_queues.py
src/prefect/server/models/workers.py
src/prefect/server/orchestration/rules.py
src/prefect/server/utilities/schemas/bases.py
tests/server/api/test_task_run_subscriptions.py

This replaces our previous uses of `.dict(shallow=True)`, where we want to
preserve nested `BaseModel` instances in fields.  Our ORM layer is able to
understand Pydantic columns, so we generally want to always work in terms of
base models with it.  Pydantic v1's `.dict` and v2's `.model_dump` both dump
recursively through the whole object graph, so we had previously introduced
an extension `shallow=True`.
We now know how fragile it can get if we're adding new `kwargs` to well-known
Pydantic methods, so our new approach is to add special-purpose methods for
Prefect-specific behavior.
```
class Engine(BaseModel):
cylinders: int
volume: float
class Car(BaseModel):
model: str
make: str
year: int
engine: Engine
```
`.model_dump(mode="python")`
```python
{
"model": "Liberty",
"make": "Jeep", …
```

Creating a Prefect `model_dump_for_orm` extension

---

src/prefect/cli/root.py

not sure why we had this turned off
when on, allows
```console
» prefect --install-completion
```
which gives

enable cli autocompletion

---

src/prefect/utilities/asyncutils.py
tests/test_tasks.py

This PR updates `sync_compatible` in the following ways:
- introduces a `force_sync` flag (this is useful in one known situation: our CLI commands)
- makes `sync_compatible` dispatch in a more transparent way; in particular, it dispatches based on whether the function is being run within an asynchronous _run context_ (instead of through implicit logic based on threads, etc.)
- handles nested `sync_compatible` calls through a `ContextVar`
When the new engine flag is set, this does introduce breaking changes - in particular, async calls outside of flow/tasks _must be awaited_.

Update sync compat in preparation for new engine

---

tests/deployment/test_flow_runs.py
tests/test_background_tasks.py

More test updates in preparation for switching to the new engine by default. Note that async functions called outside of flow/task run contexts _must_ be awaited in the new world.

More test prep

---

src/prefect/server/api/collections.py
src/prefect/server/api/collections_data/views/aggregate-worker-metadata.json
tests/cli/test_work_pool.py
tests/fixtures/collections_registry.py
tests/server/api/test_collections.py
tests/workers/test_utilities.py

Removes `prefect-agent` as a selectable work pool type. `PrefectAgent` has been removed for the 3.0 release, so this is no longer needed. The collection registry will still contain data for the `prefect-agent` work pool type until `PrefectAgent` is removed from the 2.x line.

Remove `prefect-agent` as a possible work pool type

---

src/prefect/client/orchestration.py
src/prefect/new_flow_engine.py
src/prefect/new_task_engine.py
src/prefect/new_task_runners.py
src/prefect/tasks.py
tests/fixtures/database.py
tests/test_tasks.py
tests/utilities/test_templating.py

Adds logging for run creation and completion to the new engine so that it feels familiar and homey.
Also adds support for logging prints to the new engine.
Also fixes some issues with task run naming.
For this flow:
```python
@flow(retries=3, log_prints=True)
def my_flow(foo: bool):
my_other_flow(42)
print("Hello, world!")
return slow_task.submit()
@flow
def my_other_flow(bar: int):
pass
@task(timeout_seconds=10, task_run_name="bloop")
def slow_task():
print("Sleeping...")
import time
time.sleep(1)
my_flow(foo=True)
```
Running will produce this output:
```
22:14:31.434 | INFO    | prefect.engine - Created flow run 'didactic-prawn' for flow 'my-flow'
22:14:31.437 | INFO    | prefect.engine - View at …
```

New engine logging

---

src/prefect/server/database/migrations/env.py
src/prefect/server/events/models/automations.py

We are frequently seeing a unit test issue regarding event loops that are closed. Randomly (but frequently), tests will fail reporting a RunTimeError("Event loop is closed.")  
After tracking down (at least one) source, it appears to be a race condition involving this SQLAlchemy hook. The loop is loaded before the hook is created, and by the time the hook is called the loop has been closed -- I believe this might be exacerbated by single-purpose loops being created for e.g. run_sync calls.
I explored a few solutions - mainly try/except with a fallback to asyncio.run, but ultimately using `run_sync` encapsulated them all and seems to work...? This is just a nasty race condition which something in the new engine code is exacerbating, probably the use of run sync to make scoped loops which …

Fix issue with event loops being closed

---

src/prefect/_internal/schemas/validators.py
src/prefect/server/schemas/schedules.py

The `default_anchor_date` validator wasn't getting called when no value was given to the schedule, so we just need a default factory to set the value on initialization. This also removes the `None` check from `default_anchor_date` as we don't expect, or want to handle, `IntervalSchedule(anchor_date=None)`.

Default `anchor_date` to `now`

---

requirements-dev.txt

A new version of `requests` was released a couple hours ago that broke compatibility with `docker-py`. Pinning while they get a hotfix together.
More details: https://github.com/docker/docker-py/issues/3256

Pin requests to <2.32.0

---

src/prefect/new_flow_engine.py
tests/test_flows.py

Adds support for missing hook types in new engine. Also fixes some tests related to flow run inputs. Only failing tests in `test_flows` should be for unsupported behavior in the new engine.

[New Engine] Add support for `on_crashed`, `on_cancellation`, and `on_running` hooks

---

tests/cli/test_flow_run.py

Fixes tests in `test_flow_run.py` file:
```bash
FAILED tests/cli/test_flow_run.py::TestFlowRunLogs::test_when_num_logs_smaller_than_page_size_then_no_pagination - pydantic_core._pydantic_core.ValidationError: 1 validation error for LogCreate
FAILED tests/cli/test_flow_run.py::TestFlowRunLogs::test_when_num_logs_greater_than_page_size_then_pagination - pydantic_core._pydantic_core.ValidationError: 1 validation error for LogCreate
FAILED tests/cli/test_flow_run.py::TestFlowRunLogs::test_when_num_logs_smaller_than_page_size_with_head_then_no_pagination - pydantic_core._pydantic_core.ValidationError: 1 validation error for LogCreate
FAILED tests/cli/test_flow_run.py::TestFlowRunLogs::test_when_num_logs_greater_than_page_size_with_head_then_pagination - …
```

Fix some tests in `tests/cli/test_flow_run.py`

---

src/prefect/server/schemas/filters.py

Add the ability to filter on `task_run.expected_start_time`.

Add filter on task_run.expected_start_time

---

tests/cli/deployment/test_deployment_cli.py

Should fix: 
```bash
ERROR tests/cli/deployment/test_deployment_cli.py::TestDeploymentSchedules::test_list_schedules - pydantic_core._pydantic_core.ValidationError: 4 validation errors for DeploymentCreate
ERROR tests/cli/deployment/test_deployment_cli.py::TestDeploymentSchedules::test_set_schedule_interval_without_anchor_date[commands0] - pydantic_core._pydantic_core.ValidationError: 4 validation errors for DeploymentCreate
ERROR tests/cli/deployment/test_deployment_cli.py::TestDeploymentSchedules::test_set_schedule_interval_without_anchor_date[commands1] - pydantic_core._pydantic_core.ValidationError: 4 validation errors for DeploymentCreate
ERROR tests/cli/deployment/test_deployment_cli.py::TestDeploymentSchedules::test_set_no_schedule[commands0] - …
```

Fix most `test_deployment_cli.py` tests

---

src/prefect/cli/_types.py
src/prefect/cli/variable.py
tests/cli/test_variable.py

This PR expands the `prefect variable ...` CLI to include a couple more commands.
- `prefect variable get` - to get the value of a variable
- `prefect variable set` - to set a variable (create or update, if you update you must pass `--overwrite`
- `prefect variable unset` - to delete a variable. This leaves the `delete` alias in place
- this pr fixes an issue with listing variables now that they are not always strings
```bash
➜ prefect variable set foo_bar_var '{"foo": "bar"}' --tag foo --tag bar
Set variable 'foo_bar_var'.
➜ prefect variable get foo_bar_var
{"foo": "bar"}
➜ prefect variable ls             
Variables                                  
┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┓
┃ Name        ┃ Value                    ┃ Created        ┃ …
```

variable cli updates

---

src/prefect/context.py
src/prefect/new_task_engine.py
src/prefect/tasks.py
src/prefect/utilities/engine.py
tests/test_context.py
tests/test_new_task_engine.py

When running tasks on remote infrastructure like Dask and Ray with the task engine, we lose some of the context surrounding the current task run. This makes it difficult to link the task run back to its parent run. This can also make it difficult to ensure the correct settings are propagated to the remote infrastructure.
This PR introduces two mirror utilities: `serialize_context` and `hydrated_context`. When used in conjunction, we can serialize the current context to a pickleable dictionary, send it to the remote infrastructure, and recreate it. This helps to make the task engine highly portable and helps us maintain consistent dependency tracking.
The task run engine has been updated to accept a `context` kwargs, which consumes the output of `serialize_context`.
Submit a task to Dask …

Add utilities to serialize context to a dictionary and hydrate context from a dictionary

---

src/prefect/engine.py
src/prefect/new_task_engine.py
src/prefect/tasks.py
tests/test_tasks.py

This PR exposes a new pattern for specifying state change hooks while preserving the current syntax; specifically, for tasks, it allows hooks to be specified as follows:
```python
@task
def my_task():
pass
@my_task.on_completion
def my_hook(t, tr, s):
pass
@my_task.on_failure
def my_other_hook(t, tr, s):
pass
```
This PR also removes the unnecessary constraint that prevents empty lists in hook specification.
Assuming this passes muster, I'll follow up by exposing this same pattern for flows as well.

Task Hook decorators

---

.github/workflows/integration-tests.yaml

Clone of https://github.com/PrefectHQ/prefect/pull/13322 for `2.x`

Add 2.19 to compatibility tests in `2.x`

---

src/prefect/server/api/deployments.py
src/prefect/server/api/flow_runs.py
src/prefect/server/api/ui/schemas.py
tests/server/api/test_deployments.py
tests/server/api/test_flow_runs.py
tests/utilities/schema_tools/test_hydration.py

closes: https://github.com/PrefectHQ/prefect/issues/13541
There was an update to how `HydrationContext` worked specifically for `actions` that got made in cloud but not in OSS. When actions got ported over to OSS, it brought 80% of that pr, but not the parts in the deployment/flow run api.
This PR updates `HydrationContext.build` to use the correct parameters in those endpoints. It also brings over a bunch of tests that would have caught this had I added them earlier.

fix hydration for workspace variables for `2.x`

---

src/prefect/results.py

More info here: https://docs.pydantic.dev/latest/concepts/serialization/#serializing-with-duck-typing
Fixes: `tests/results/test_persisted_result.py`
Before:
```bash
async def test_result_reference_create_uses_serializer(storage_block):
serializer = PickleSerializer(picklelib="pickle")
result = await PersistedResult.create(
"test",
storage_block_id=storage_block._block_document_id,
storage_block=storage_block,
storage_key_fn=DEFAULT_STORAGE_KEY_FN,
serializer=serializer,
)
assert result.serializer_type == serializer.type
contents = await storage_block.read_path(result.storage_key)
blob = PersistedResultBlob.parse_raw(contents)
>       assert blob.serializer == serializer
E       AssertionError: assert PickleSerializer(type='pickle', picklelib='cloudpickle', picklelib_version=None) == …
```

Use `serialize_as_any` when calling `model_dump_json` in `to_bytes` method of `PersistedResultBlob`

---

src/prefect/results.py
tests/utilities/test_callables.py

This PR updates the tests to use the `model_dump_for_openapi` method that we used to replace the `dict` method we had on the `ParameterSchema` class. It also adds `required` and `definitions` fields to the expected schema as they no longer default to `None`.
Fixes currently failing tests:
<details>
<pre>
_______________________________________________________________________ TestParseFlowDescriptionToSchema.test_flow_with_complex_args_docstring _______________________________________________________________________
self = <tests.utilities.test_callables.TestParseFlowDescriptionToSchema object at 0x125274490>
def test_flow_with_complex_args_docstring(self):
def f(x, y):
"""Function f.
Second line of docstring.
Args:
x: required argument x
y (str): required typed argument y
with second line …

Fix `test_callables` tests

---

requirements-dev.txt

Clone of https://github.com/PrefectHQ/prefect/pull/13474 for `2.x`

Pin requests to <2.32.0 for `2.x`

---

src/prefect/blocks/notifications.py

I saw notification block tests failing due to having `apprise<1.8.0` installed, and that made me realize that we probably want to try to support both import syntaxes.
If we are in favor of this I'd add to `2.x` as well.

Add `apprise` version compatibility for notification blocks

---

.github/workflows/integration-pacakge-tests.yaml
src/integrations/prefect-dask/prefect_dask/__init__.py
src/integrations/prefect-dask/prefect_dask/client.py
src/integrations/prefect-dask/tests/conftest.py
src/integrations/prefect-dask/tests/test_client.py
src/integrations/prefect-dask/tests/test_task_runners.py
src/integrations/prefect-dask/tests/test_utils.py
src/prefect/context.py
src/prefect/new_task_engine.py
src/prefect/utilities/engine.py

This PR adds a `PrefectDistributedClient` to `prefect-dask`. The client is a drop in replacement for the client from `distributed` for submitting work to a Dask cluster. This client will power the new task runner, but splitting out this client allows users to take advantage of Prefect features without changing their existing Dask code.
An example flow with tasks submitted to Dask via the `PrefectDistributedClient`
```python
from prefect.flows import flow
from prefect.tasks import task
from prefect_dask import PrefectDistributedClient
@task
def square(x):
return x**2
@task
def neg(x):
return -x
@task
def summation(args):
return sum(args)
@flow
def my_flow():
with PrefectDistributedClient() as client:
square_futures = client.map(square, range(10))
neg_futures = client.map(neg, …
```

Adds `PrefectDistributedClient` to `prefect-dask`

---

src/prefect/states.py
src/prefect/utilities/engine.py
tests/results/test_flow_results.py
tests/test_states.py

The is_state utility exists for backwards-compatible checks of historic server-defined State objects, and is no longer needed. 
Due to threading, calling this function accounts for 7% of new task engine overhead (!)

Remove is_state

---

src/prefect/new_flow_engine.py
src/prefect/new_task_engine.py
tests/test_flows.py

Part of performance profiling - these blocking calls add 20% overhead to the new engine.

Remove extra log flushes

---

tests/utilities/test_asyncutils.py

This PR adds more tests for #13573, specifically around dynamics involving nested calls.

Add tests for running coros

---

tests/events/client/instrumentation/test_task_run_state_change_events.py
tests/results/test_result_factory.py
tests/test_background_tasks.py

I noticed we had some tests with hardcoded paths (which is no good); some of those were fixed in #13572 and this PR fixes a few more.  This PR also adds subdirectories to a few tests to ensure some of the equality checks are actually checking for something interesting.

Fix up some tests

---

src/prefect/logging/handlers.py
src/prefect/new_flow_engine.py
src/prefect/new_task_engine.py
src/prefect/utilities/asyncutils.py

[git history got messed up on #13577]
This PR builds on #13573 to constructively revert #13568.
It adds "background task" capabilities to the `run_coro_from_sync` function, allowing it to fire-and-forget a coro to the worker thread. We then use this to performantly flush logs at the end of a run. Previously we _removed_ this flush because it was very expensive to do synchronously and we had no good way to do it in the background.
Note that there are a number of methods that are synchronous but attempt to detect an async loop and return awaitables, like `APILogWorker.aflush`. These are really hard to reason about and end up not being used (empiricalyl). This PR changes `aflush` to be a coroutine function, which you'd expect from its name.

Flush logs at the end of flows/tasks

---

src/integrations/prefect-dask/prefect_dask/client.py
src/integrations/prefect-dask/prefect_dask/task_runners.py
src/integrations/prefect-dask/tests/conftest.py
src/integrations/prefect-dask/tests/test_task_runners.py
src/integrations/prefect-dask/tests/test_utils.py
src/prefect/new_futures.py
src/prefect/new_task_runners.py
src/prefect/server/events/triggers.py

Updates the task runner to implement the new `TaskRunner` interface. The new task runner delegates most responsibilities to the `PrefectDistributedClient`, but the task runner handles wrapping and unwrapping `PrefectDaskFuture`s to ensure work is efficiently scheduled on a Dask cluster.

Update `DaskTaskRunner` for compatibility with the updated engine

---

tests/deployment/test_steps.py

Thanks to @chrisguidry's new test utility that errors on new file creation, I believe I've found the culprit of many of our file creation errors.

Chdir on test to prevent file writes

---

src/prefect/server/models/block_schemas.py
src/prefect/server/models/block_types.py

We were originally allowing this only for unit tests, but we also use this
path via block autoregistration at server startup.  Now that we're past the
hump on Pydantic v2, we can remove the more aggressive exception here and just
transparently convert the type.

Allow block registration to use client schemas for server model creation

---

src/prefect/_internal/schemas/bases.py
src/prefect/cli/_prompts.py
src/prefect/client/schemas/schedules.py
src/prefect/events/schemas/automations.py
src/prefect/server/events/schemas/automations.py
src/prefect/server/schemas/schedules.py
src/prefect/server/utilities/schemas/bases.py
src/prefect/settings.py
src/prefect/types/__init__.py
tests/events/server/storage/test_event_persister.py
tests/types/test_self_validating_types.py

As I was trying to reconcile the schemas between OSS and Cloud, I discovered
that there's a model configuration called `ser_json_timedelta` where we can
easily toggle the original behavior of serializing to floats.  No need for
custom types at all.

Replace our customized `Duration` types with plain `timedelta`s

---

requirements-client.txt

we currently use [pydantic's `Secret`](https://docs.pydantic.dev/latest/examples/secrets/#serialize-secretstr-and-secretbytes-as-plain-text) in `main` when it is only available after 2.7

pin `pydantic>=2.7` for `Secret`

---

src/prefect/cli/deploy.py
src/prefect/flows.py
src/prefect/utilities/callables.py
src/prefect/utilities/importtools.py
tests/test_flows.py
tests/utilities/test_callables.py
tests/utilities/test_importtools.py

This PR adds a new method of generating a parameter schema for a function so users and use `prefect deploy` when not all dependencies are available on the current machine.
Our current method of generating a parameter schema requires us to load the flow function itself and get the signature using the built-in `inspect` module. This causes issues when not all dependencies are present because loading the flow causes the entire module the flow is located in to be run and can result in Python raising an `ImportError`.
This PR updates this approach to allow a parameter schema given an entrypoint that points to a function with the new `parameter_schema_from_entrypoint` function. This new function will generate a `inspect.Signature` object and docstring dictionary from the source code directly …

Allow flow parameter schema generation when dependencies are missing

---

src/prefect/records/result_store.py
src/prefect/utilities/asyncutils.py
tests/utilities/test_asyncutils.py

In the spirit of minimizing breaking changes and also giving ourselves and users escape hatches, this PR updates `sync_compatible` in two ways:
- returns an awaitable if there is a running event loop, otherwise runs the function synchronously
- exposes a flag `_sync: bool` that allows the caller to override any magic and pick how they want the function run
**cc:** @jlowin @zzstoatzz

Add _sync flag to sync compatible fns

---

.github/workflows/python-tests.yaml
docker-compose.yml
tests/fixtures/docker.py

The issue with our docker tests seems to have been that all of the workers were trying to start the registry and all but the first one would be denied by docker itself. This led to the `registry` fixture throwing an exception and the tests relying on the fixture to fail.
This moves the management of the docker registry out of pytest and into actions/docker-compose.

Move docker registry lifecycle management out of pytest

---

tests/docker/contexts/tree-as-context/hello.txt
tests/docker/test_image_builds.py

If `test_can_use_working_tree_as_context` and `test_generate_dockerfile_with_no_requirements` were picked up by different workers it was possible for them to interact as they used the same `contexts` folder. This copies that folder to give `test_can_use_working_tree_as_context` its own.

Give `test_can_use_working_tree_as_context` its own contexts folder

---

src/prefect/task_server.py

Makes use of an `anyio` task group on the task server to background submission of received task runs so that they can be executed concurrently. Also used a `ThreadPoolExecutor` to run run tasks in a separate thread to avoid blocking execution. Async tasks are run in the primary thread via the task group.
A subsequent PR will add the ability to limit the number of tasks being executed for a given task server.
Closes #13595
Given this script:
```python
from prefect.task_server import serve
@task
def slow_task():
import time
time.sleep(5)
return 42
@task
def fast_task():
return 42
async def main():
slow_task.apply_async()
fast_task.apply_async()
fast_task.apply_async()
fast_task.apply_async()
await serve(slow_task, fast_task)
import asyncio …
```

Update task server to run recieved tasks concurrently

---

flows/automation-assessments.py

Cloud has its own version of the automations assessments, so we don't need to
run this one during Cloud's CI.  By convention, we use that 9.9.9 version as a
sentinel to indicate Cloud.

Disable the automations-assessment test for Prefect Cloud

---

src/prefect/runner/runner.py
tests/runner/test_runner.py

This PR adds exception handling to skip cancellation hooks if a Runner can't load the flow code. A similar fix has already been made for workers https://github.com/PrefectHQ/prefect/pull/12001/files.
Closes https://github.com/PrefectHQ/prefect/issues/12389.
Once merged I'll open a PR to 2.x.

Skip on cancellation hooks if runner cant load flow

---

.github/workflows/integration-package-tests.yaml
src/prefect/__init__.py

There are times when we make changes to `prefect` that we suspect may affect
the integrations packages, but we don't want to run the full integrations test
suites on _every_ `prefect` change.  This lets us add a `test-all-integrations` label to
a PR to opt in to running those tests.

Allows us to run integration package unit tests by adding a PR label

---

docs/3.0rc/api-ref/prefect/cli/task.mdx
src/prefect/cli/__init__.py
src/prefect/cli/task.py
tests/cli/test_task.py
tests/test-projects/tasks/household.py
tests/test-projects/tasks/space.py

This adds a `prefect task serve` CLI command that takes a list of entrypoints and starts a task server that will serve the tasks at those entrypoints.
Closes #12245

Add `prefect task serve` CLI command to start task server

---

src/prefect/flow_engine.py
src/prefect/task_engine.py
src/prefect/task_server.py
tests/test_task_server.py

Adds a `limit` argument to `TaskServer` to limit the number of concurrent runs for a given task server. Task servers will stop receiving runs from the sbuscription when the limit is reached. Once one or more active task runs completes, the server will begin pulling runs from the subscription again until the limit is reached. If `limit` is set to `None`, now limiting of concurrent runs is enforced.
Closes https://github.com/PrefectHQ/prefect/issues/12325
Given the following script:
```python
from prefect.task_server import serve
@task
def slow_task():
import time
time.sleep(5)
return 42
async def main():
for _ in range(10):
slow_task.apply_async()
await serve(slow_task, limit=2)
import asyncio
asyncio.run(main())
```
the received runs …

Add ability to limit concurrent runs for a task server

---

src/prefect/client/schemas/objects.py
src/prefect/server/orchestration/core_policy.py
src/prefect/server/schemas/states.py
src/prefect/server/services/task_scheduling.py
src/prefect/tasks.py
tests/server/orchestration/api/test_task_run_subscriptions.py
tests/test_background_tasks.py

This updates `apply_async` to mark task runs it creates as being `deferred`. It also updates the `EnqueueScheduledTasks` core policy to only enqueue tasks that are `deferred=True`. This keeps tasks that are executed in other ways from also being executed by the task server.
Closes #13674

Mark tasks as being `deferred` when using `apply_async`

---

src/prefect/cli/task.py
tests/cli/test_task.py

Following on from https://github.com/PrefectHQ/prefect/pull/13662 this exposes the `limit` in the CLI.

Expose `limit` in `prefect task serve`

---

tests/conftest.py
tests/results/test_flow_results.py
tests/results/test_task_results.py
tests/runner/test_storage.py

This PR fixes a number of test flakes related to stray file cleanup. 

Fix flaky 2.x CI tests

---

.github/workflows/codeql-analysis.yml
src/prefect/client/schemas/actions.py
src/prefect/server/api/task_runs.py
src/prefect/server/schemas/actions.py
tests/results/test_flow_results.py
tests/results/test_task_results.py
tests/runner/test_storage.py
tests/server/api/test_task_runs.py

Though we aren't using this client-side in 2.x, having support for it will allow
3.x clients to work with 2.x servers (as with Prefect Cloud)

Allowing clients to provide TaskRun ids

---

src/prefect/server/api/events.py

Should close a few code scanning alerts
- [Log Injection](https://github.com/PrefectHQ/prefect/security/code-scanning/2011)
- [Log Injection](https://github.com/PrefectHQ/prefect/security/code-scanning/2012)
- [Log Injection](https://github.com/PrefectHQ/prefect/security/code-scanning/2013)

Remove unnecessary debug log in events API

---

.github/workflows/integration-package-tests.yaml

Ideally we'd only run on changes to `.py` files, rather than docs changes, for example.

Run integrations package test workflow only on Python file changes

---

tests/test_settings.py

Since we changed the settings to warn on missing settings instead of raising these couple tests were failing.

Fix missing settings tests

---

tests/fixtures/docker.py

The docker tests [failed in main](https://github.com/PrefectHQ/prefect/actions/runs/9323639698/job/25667269799) with an error when trying to cleanup created containers:
```
tests/fixtures/docker.py:73: in cleanup_all_new_docker_objects
except docker.errors.NotFound:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <docker.client.DockerClient object at 0x7f8450f44d90>, name = 'errors'
def __getattr__(self, name):
s = [f"'DockerClient' object has no attribute '{name}'"]
if hasattr(APIClient, name):
s.append("In Docker SDK for Python 2.0, this method is now on the "
"object APIClient. See the low-level API section of the "
"documentation for more details.")
>       raise AttributeError(' '.join(s))
E       AttributeError: 'DockerClient' object has no …
```

Use `NotFound` exception from `docker.errors`

---

src/prefect/tasks.py
tests/test_background_tasks.py
tests/test_tasks.py

Adds a `deferred` kwarg to signify that mapped tasks should be executed on a task server. `deferred` can be used inside or outside of flows. Calling `Task.map` outside of flow without `deferred=True` will raise an error.
Closes #13722

Adds `deferred` kwarg to `Task.map` to executed mapped tasks on a task server

---

.github/workflows/integration-package-tests.yaml
src/integrations/prefect-redis/prefect_redis/__init__.py
src/integrations/prefect-redis/prefect_redis/filesystem.py
src/integrations/prefect-redis/tests/test_filesystem.py

@desertaxle I think this naming brings it inline with the others, thoughts?
Related to #12249

Rename `RedisFilesystem` to `RedisStorageContainer` to match naming semantics of other filesystem classes

---

src/prefect/server/api/server.py
src/prefect/server/models/deployments.py
src/prefect/server/services/loop_service.py
src/prefect/settings.py
tests/conftest.py

When running the prefect server (ephemeral or otherwise), there a number of known expected exceptions that a user will hit. 
This is particularly true with SQLite:
- A requirement of our existing server side orchestration is that 1 client is orchestrating 1 run at a time. Cloud has it's own implementation to enforce this. OSS Postgres locks the row.
- To improve sqlite transaction behavior we implemented the following: https://github.com/PrefectHQ/prefect/pull/9594, where we can conditionally and explicitly lock the DB for certain actions (if you want to understand the real WHY we need to do this, I'd really recommend looking at that pr and the code comments in it)
- These locked db errors are sent with a retryable status code by the server, with the expectation that the client will try …

conditionally log retryable errors

---

tests/conftest.py

I had the [Datadog tests fail](https://github.com/PrefectHQ/prefect/actions/runs/9386164402/job/25846053054) because there were `.coverage` files on the filesystem, this is expected as the datadog tests collect and report coverage. This PR ensures that these files are ignored for the purposes of checking for extraneous files.

Ignore `.coverage` files when checking for extraneous files

---

docs/mint.json

Changes CTA based on user feedback @danielhstahl @sarahmk125 

Update button text at top of page

---

src/prefect/client/orchestration.py
src/prefect/client/schemas/objects.py
src/prefect/events/clients.py
src/prefect/events/schemas/events.py
src/prefect/futures.py
src/prefect/task_runs.py
tests/events/client/instrumentation/test_task_run_state_change_events.py
tests/test_background_tasks.py
tests/test_futures.py
tests/test_task_runners.py
tests/test_task_runs.py
tests/test_task_server.py
tests/test_tasks.py

Flows like this still work (assuming you're running the appropriate task worker):
```python
from prefect.task_runners import PrefectTaskRunner
from tasks import square, neg, summation
@flow(task_runner=PrefectTaskRunner())
def example_flow():
A = square.map(range(10))
B = neg.map(A)
total = summation.submit(B)
return total.result()
result = example_flow()
print(result)
```

Updates `PrefectDistributedFuture` to use an event websocket to determine task completion

---

src/prefect/records/cache_policies.py
src/prefect/states.py
src/prefect/task_engine.py
src/prefect/tasks.py
src/prefect/transactions.py
tests/records/test_cache_policies.py
tests/results/test_task_results.py
tests/test_tasks.py
tests/test_transactions.py

This PR updates cache policies in the following ways:
- updates the signature on `compute_key` to be closer to the original `cache_key_fn` signature
- auto-converts `cache_key_fn`'s to `CacheKeyFnPolicy`'s for backwards compatibility
- adds an `overwrite` flag on transactions that can be used to ignore existing records; the engine currently matches this to the original `refresh_cache` functionality
**NOTE**: cache expirations are _not_ currently wired up; that will require some extensions to cache policies that will need to be handled separately
**cc:** @EmilRex (I won't keep doing this I promise haha - this just dovetails nicely with our conversations this week so wanted you to know when these milestones are complete)

Cache Policy Upgrades

---

src/prefect/task_engine.py
src/prefect/task_server.py
src/prefect/tasks.py
tests/fixtures/database.py

this PR
- stops allowing `serve` to accept a `task_runner` as `TaskServer` no longer expects one
- catches any `BaseExceptionGroup` that `TaskServer(...).start()` might throw
- removes db fixture section that [has flaked](https://github.com/PrefectHQ/prefect/actions/runs/9391770315/job/25868658763?pr=13821#step:9:2200) (@chrisguidry seems to have foretold this 🧙‍♂️ )

remove invalid kwarg and catch exception groups

---

src/integrations/prefect-aws/prefect_aws/s3.py
src/integrations/prefect-aws/tests/test_s3.py

The issue as written isn't particularly accurate. What's actually going on here is that `S3Bucket` has a default_factory for `credentials`, which is just `AwsCredentials`, when the code in the issue is doing `overwrite=True` that's causing it to overwrite the credentials assigned in the UI. That all makes sense, what _didn't_ make sense was the error that was being thrown.
The error in the issue was `TypeError: unhashable type: 'dict'`, so my goal here was to get a more useful `botocore.exceptions.NoCredentialsError` that would hint at the credentials being missing. That led me down a rabbit hole where there seems to be some incompatibility between pydantic and nested blocks with Union types. With `MinIOCredentials` as the first thing in the Union loading fails, but it fails in a way that …

Put `AwsCredentials` first to match default factory

---

tests/test_logging.py

This test flaked by asserting that the caplog tuples exactly match and have no other records. This PR changes the test to assert that the expected log is in the tuples and not that it's all of the tuples.
```
_________________________ test_without_disable_logger __________________________
[gw0] linux -- Python 3.11.9 /opt/hostedtoolcache/Python/3.11.9/x64/bin/python3
caplog = <_pytest.logging.LogCaptureFixture object at 0x7f3c90173990>
def test_without_disable_logger(caplog):
"""
Sanity test to double check whether caplog actually works
so can be more confident in the asserts in test_disable_logger.
"""
logger = logging.getLogger("griffe.agents.nodes")
def function_with_logging(logger):
assert not logger.disabled
logger.critical("it's enabled!")
return 42
function_with_logging(logger) …
```

Fix flaky `test_without_disable_logger` test.

---

tests/_internal/concurrency/test_waiters.py

This test flaked by having the time comparison be milliseconds over the 1 second window imposed in the test. This PR bumps that to a two second window to account for these small variations.
```
__________________ test_sync_waiter_timeout_in_worker_thread ___________________
[gw2] linux -- Python 3.10.14 /opt/hostedtoolcache/Python/3.10.14/x64/bin/python3
def test_sync_waiter_timeout_in_worker_thread():
"""
In this test, a timeout is raised due to a slow call that is occurring on the worker
thread.
"""
done_callback = Call.new(identity, 1)
with WorkerThread(run_once=True) as runner:
call = Call.new(sleep_repeatedly, 1)
waiter = SyncWaiter(call)
waiter.add_done_callback(done_callback)
call.set_timeout(0.1)
runner.submit(call)
t0 = time.time()
waiter.wait()
t1 = time.time()
with …
```

Fix flaky `test_sync_waiter_timeout_in_worker_thread` test

---

RELEASE-NOTES.md
docs/3.0rc/guides/deferred-tasks.mdx
docs/3.0rc/guides/index.mdx
src/prefect/cli/task.py
src/prefect/futures.py
src/prefect/server/task_queue.py
src/prefect/settings.py
src/prefect/task_runners.py
src/prefect/task_worker.py
src/prefect/tasks.py
tests/events/client/instrumentation/test_task_run_state_change_events.py
tests/test_background_tasks.py
tests/test_task_runners.py
tests/test_task_worker.py

this PR actualizes internal discussion around "worker" being the best word for what you get when you start a process to listen for / execute task runs
this is obviously a significant breaking change, but one i think we're aligned on

rename `TaskServer` to `TaskWorker`

---

.github/workflows/python-tests.yaml

We moved the lifecycle management of the docker registry for the docker tests out of pytest and into the action. We missed that the datadog suite was also running these tests and also needs the registry running.

Startup the docker registry when running datadog tests

---

.github/workflows/python-tests.yaml

Redis had a copy/pasted name from the docker registry, renaming it to keep it from conflicting when running the datadog tests. This also includes a change to ensure we're running the datadog tests when we change the action yaml.

Give `redis` a non-conflicting name in datadog tests

---

.github/workflows/python-tests.yaml

Fun fact, if you mess up a yaml GitHub doesn't count that as a failed check.

Fix syntax issue in `python-tests.yaml` action.

---

src/prefect/events/clients.py
src/prefect/server/api/server.py
src/prefect/utilities/asyncutils.py
tests/client/test_prefect_client.py

I'm trying to find the source of a performance issue and while this PR doesn't solve it, I did come across these two issues:
- the ephemeral events worker client doesn't create an ephemeral app, which means background services on the app are enabled. Now this doesn't matter in practice because the client is a low-level client that doesn't invoke the app lifespan, but if that changed it would have bad consequences. So I set the flag for using an ephemeral app (which will mean it can reuse the app from other clients without creating a new one).
- relatedly, ephemeral lifespans -- including creating/migrating the database and registering blocks -- are run multiple times, as the hooks are called whenever a new app is created. This is almost certainly unnecessary to do more than once per …

Ensure events-worker app is ephemeral; run ephemeral migrations only once

---

tests/conftest.py
tests/fixtures/events.py
tests/fixtures/logging.py

Tests are extremely noisy lately with two common errors:
- logs not being written due to files being closed
- events db records not being written due to the file being unavailable
(Note these usually don't seem to actually fail tests, but they show up in test failure outputs - see https://github.com/PrefectHQ/prefect/actions/runs/9391385621/job/25863415303. The same errors *do* sometimes show up as test failures but I'm not sure why yet)
I believe this is because the log/events workers have outstanding items to process when test directory is cleaned up. This PR makes the following changes:
- explicit fixtures to drain all logs and events workers
- a session fixture to delete the temp directory after the worker fixtures complete. In theory the hook implementation should have ensured that …

Ensure that workers drain before the test dir is deleted

---

src/prefect/client/subscriptions.py
src/prefect/task_worker.py
tests/test_task_worker.py

closes:https://github.com/PrefectHQ/prefect/issues/13847
Previously running a task worker against the ephemeral api would error with:
```
17:32:07.345 | INFO    | prefect.task_worker - Starting task worker...
17:32:07.345 | INFO    | prefect.task_worker - Subscribing to tasks: my_background_task-7c388d0bf59fa4394379971e841498bc
17:32:07.347 | ERROR   | prefect.task_worker - Task worker stopped with 1 exception:
'NoneType' object has no attribute 'replace'
```
As of this PR it errors in the following way:
```
17:44:36.607 | INFO    | prefect.task_worker - Starting task worker...
17:44:36.609 | ERROR   | prefect.task_worker - Task worker stopped with 1 exception:
PREFECT_API_URL must be set to use the task worker. Task workers are not compatible with ephemeral api.
```

raise helpful error when `task_worker` runs against ephemeral server

---

.github/workflows/integration-tests.yaml
flows/automation-assessments.py

One way that these automation tests could fail is if connecting to the websocket
to listen for the triggered event takes longer than it takes to emit the
events and trigger the automation.
By using an `asyncio.Event` to signal when the socket is connected, we can wait
for that signal before we proceed with the rest of the test.

Addressing a race condition with the automations integration tests

---

src/prefect/task_engine.py

closes #13864 - which outlines that retry logging is not so good in `main` right now in 3.x, this PR cleans it up a bit
```python
In [1]: from prefect import task
In [2]: @task(retries=5)
...: def terrible():
...:     raise ValueError
...:
In [3]: terrible()
11:34:05.523 | INFO    | prefect.engine - Created task run 'terrible-terrible' for task 'terrible'
11:34:06.132 | INFO    | Task run 'terrible-terrible' - Task run failed with exception ValueError() - Retry 1/5 will start immediately
11:34:06.512 | INFO    | Task run 'terrible-terrible' - Task run failed with exception ValueError() - Retry 2/5 will start immediately
11:34:06.830 | INFO    | Task run 'terrible-terrible' - Task run failed with exception ValueError() - Retry 3/5 will start immediately
11:34:07.153 | INFO    | Task run …
```

Add better task retry logging

---

src/prefect/server/api/events.py
src/prefect/server/api/task_runs.py
src/prefect/server/events/stream.py
src/prefect/server/utilities/subscriptions.py

The outward signs of this manifest as the Prefect server not stopping in
response to an interrupt after a websocket subscriber has connected once.  The
specific scenario that caused that was:
* Subscriber connects and start listening for events from the server
* The server opens a queue with the distributor and starts the loop to check for
new events, periodically yielding back control
* If no events ever arrive for that subscriber (due to a restrictive filter or
just an absence of events), the loop will just continue indefinitely _even if
the subscriber disconnects_
* This leads to there being an unfinished task on the event loop, preventing the
server from shutting itself down cleanly
The ideal solution here would be to send a `ping` message down the wire to the
client, but we don't …

Resolving an infinite loop distributing events to a websocket subscriber

---

src/prefect/server/events/models/automations.py
src/prefect/server/events/triggers.py

When porting automations from Prefect Cloud, the default is to begin a
transaction for every automations session.  This isn't strictly necessary in
most cases, and with SQLite, it exacerbates the `database is locked` issues.

Reduces the lockiness of automations database access

---

src/prefect/task_runners.py
tests/test_task_runners.py

Adds a `max_workers` arg to the `ThreadPoolTaskRunner` to allow users to control the number of concurrent task runs the task runner allows.
cc @kevingrismore 

Expose arg for max workers on `ThreadPoolTaskRunner`

---

docs/3.0rc/guides/deployment/developing-a-new-worker-type.mdx

updates `pydantic>2`-related job config syntax in the *Developing a New Worker Type* guide and adds a note about `pydantic<2`

Update `pydantic` syntax in docs

---

src/prefect/server/api/server.py
tests/client/test_prefect_client.py

Quick follow up to #13838 -- that PR prevented lifespan events (like db migrations) running once they had already been run once, but set the flag globally. That might be too heavy handed, as two different apps could each want their own lifecycle governance. In practice this is unlikely because while `create_app()` will allow multiple apps to be created, they all inherit the same settings; nonetheless this is probably a more permissive design.

Ensure lifespan runs for each app

---

src/prefect/flow_engine.py
src/prefect/task_engine.py
tests/test_tasks.py

This PR adds a useful help message in cases where tasks can't be started because their parent flow is already completed. 
New logged output will look something like this:
```
09:20:37.219 | ERROR   | Task run 'say_hello_3-6' - Task run was aborted: The enclosing flow must be running to begin task execution.
09:20:37.220 | ERROR   | Task run 'say_hello_3-6' - Finished in state Pending(). Please wait for all submitted tasks to complete before exiting your flow.
```
Closes https://github.com/PrefectHQ/prefect/issues/13832
For this script that doesn't wait for submitting tasks:
```python
@task
def say_hello_3(name):
return f"Hello {name}!"
@flow
def my_flow():
for i in range(10):
say_hello_3.submit(name=range(10))
my_flow()
```
New …

Add message for submitted tasks that are not waited

---

src/prefect/tasks.py

If I have task called `my_background_task`, when I run it inside of a flow, the task run's name is `my_background_task-0`. When I run it independently (via `.delay` or directly) it's name is `my_background_task-my_backg` as it tries to append the first 8 characters of the dynamic key. If the function name is > 8 chars, this suffix will always be the same. It seems better UX to just have the task run name

remove dynamic key from non-flow task run name

---

src/prefect/server/services/task_scheduling.py

Background tasks used to be the only tasks that existed without a flow run, but
that is no longer true.  The `TaskSchedulingTimeouts`, when it's looking for
stuck `PENDING` tasks would warn when it encountered one that hadn't previously
been `SCHEDULED`.  These tasks can just be quietly skipped here, without warning.

Remove stray warning about tasks that weren't originally `SCHEDULED`

---

src/integrations/prefect-aws/prefect_aws/ecs.py
src/integrations/prefect-azure/prefect_azure/container_instance.py
src/integrations/prefect-gcp/prefect_gcp/aiplatform.py
src/integrations/prefect-gcp/prefect_gcp/cloud_run.py
src/prefect/infrastructure/container.py
src/prefect/server/collection_blocks_data.json
src/prefect/server/models/block_registration.py

> [!Note]
> Seems like prefect-azure is incompatible w/ python 3.12 due to azureml-core retaining references to `pkg_resources`. That's what the remaining CI failures in integration tests are from. This PR only adds a deprecation warning to a block within that collection.
This PR:
- Updates 2.x collections registry block metadata from https://github.com/PrefectHQ/prefect-collection-registry/pull/395 - note that it's been a while since the metadata in this repo has been updated so some changes were required to handle the newer JSON structure from the aggregated block view in the collection-registry repository.
- Adds deprecation warnings to deprecated infrastructure block descriptions that were missing them in the UI
Closes #13287

Deprecation warnings on blocks

---

src/prefect/task_runners.py
tests/test_task_runners.py

Fixes issue with `ThreadPoolTaskRunner` concurrency by copying `max_workers` on task runner duplication. Now the `max_workers` setting is respected, and users can increase the amount of concurrent execution if desired.
Execute 100 tasks concurrently (this would execute in batches previously):
```python
from prefect.task_runners import ThreadPoolTaskRunner
@task
def sleepy_task(i):
import time
print(f"Sleepy task {i}")
time.sleep(10)
return i
@flow(task_runner=ThreadPoolTaskRunner(max_workers=100))
return sleepy_task.map(range(100))
test_flow()
```
For documentation …

Fix `ThreadPoolTaskRunner` concurrency by copying `max_workers` on duplication

---

src/prefect/input/__init__.py

These methods were only in `prefect.input.run_input` which doesn't match with everything else that's exposed at `prefect.input`.

Expose `receive_input` and `send_input` from `prefect.input`

---

src/prefect/workers/base.py
tests/workers/test_base_worker.py

When there's no `PREFECT_API_URL` set, calls to `get_client` will start the
ephemeral server transparently for the user.  This works amazingly well for
running single flows and tasks for demos and testing.  In the default
configuration, you can share a SQLite database across several Prefect processes,
like a server and a worker, and things will generally appear to work.
However, when we start to get into more advanced infrastructure like `Worker`
and `TaskWorker`, it doesn't make sense to run these ephemerally without a
Prefect server.  Event-driven workflows and background task scheduling require
a running server, and we should be explicit about that fact to avoid the
possibility for confusion (like events not being emitted, or automations not
running as expected).
Fixes #13876

Require a `PREFECT_API_URL` to start a worker

---

src/prefect/events/clients.py

Raise a more useful error when trying to stream with no `PREFECT_API_URL`

---

.github/workflows/api-compatibility-tests.yaml
.github/workflows/integration-package-tests.yaml
.github/workflows/static-analysis.yaml
README.md
docs/2.19.x/how-to-guides/development/ci-cd.mdx
docs/3.0rc/deploy/dynamic-infra/deploy-ci-cd.mdx
src/integrations/prefect-aws/pyproject.toml
src/integrations/prefect-azure/pyproject.toml
src/integrations/prefect-bitbucket/pyproject.toml
src/integrations/prefect-dask/pyproject.toml
src/integrations/prefect-databricks/pyproject.toml
src/integrations/prefect-dbt/pyproject.toml
src/integrations/prefect-docker/pyproject.toml
src/integrations/prefect-email/pyproject.toml
src/integrations/prefect-gcp/pyproject.toml
src/integrations/prefect-github/pyproject.toml
src/integrations/prefect-gitlab/pyproject.toml
src/integrations/prefect-kubernetes/pyproject.toml
src/integrations/prefect-ray/pyproject.toml
src/integrations/prefect-shell/pyproject.toml
src/integrations/prefect-slack/pyproject.toml
src/integrations/prefect-snowflake/pyproject.toml
src/integrations/prefect-sqlalchemy/pyproject.toml
src/prefect/workers/base.py

In a [prior change](https://github.com/PrefectHQ/prefect/pull/13942), we make it required that a worker have a `PREFECT_API_URL` set (with an exception for unit tests by looking at `PREFECT_TEST_MODE`).  We weren't setting `PREFECT_TEST_MODE` for the integrations package tests, so any ones that tested workers were failing.

Enabling `PREFECT_TEST_MODE` for integrations tests

---

src/prefect/records/result_store.py

resolves https://github.com/PrefectHQ/prefect/issues/13989
@desertaxle and I were discussing ^, and it looks like we might be running into a problem with remote `result_store` uses if we expect this `exists()` check to fire on every task run start.  If we don't catch every vendor-specific Exception, it seems like we might prevent those tasks from starting - this is something I observed with the `GcsBucket()` results store

fix(results-store): catch and handle any Exception from exists()

---

docs/integrations/integrations.mdx

Didn't like triple backticks inside triple backticks and fixes a typo.

Fix docs formatting in integrations page

---

requirements-client.txt

I've reported the issue upstream:
https://github.com/pydantic/pydantic-extra-types/issues/188

Avoiding `pydantic-extra-types==2.8.1` due to timezone bug

---

docs/script.js

Accidentally marked the load function as async so the return value was a promise and not the script node. Also adds an optional onload handler to the load script method so callers don't need to add the event listener themselves (this also avoids a potential race condition with the script load event firing before the event listener has been instantiated)

Chore: Docs script

---

src/prefect/flows.py
src/prefect/tasks.py
src/prefect/utilities/callables.py
tests/test_flows.py
tests/test_tasks.py

This PR adds support for decorating instance/class/static methods as @flows or @tasks.
Today, methods aren't supported because of how Prefect handles the implicit `self` argument; you'll get an error like `ParameterBindError: Error binding parameters for function 'instance_method': missing a required argument: 'self'.
Function 'instance_method' has signature 'self' but received args: () and kwargs: [].`.
This is because the function signature (used for validating parameters) demands an explicit `self` call arg that will never be supplied by the user.
The solution (for both flows and tasks) has two parts:
1. Implement the descriptor protocol on `Flows` and `Tasks` by adding a `__get__` method. When an instance method is accessed on its parent instance, the `__get__` method is called with …

Add support for instance/class/static methods

---

docs/3.0rc/develop/write-tasks/use-task-runners.mdx

I had this brought up by someone who found that their usage of SequentialTaskRunner was no longer working. I've changed the explanation and examples of task runners to explain how tasks are sequential by default, and concurrent by default, when using .submit().

Removed references to SequentialTaskRunner

---

src/prefect/flows.py
src/prefect/tasks.py
tests/test_flows.py
tests/test_tasks.py

Follow up from #13944. It's not obvious what order to stack decorators, but the `@task` or `@flow` decorator needs to go *under* [be applied before] the `@classmethod` or `@staticmethod`. This is because the classmethod/staticmethod  decorator outputs are not recognized as callable objects and therefore create errors in a lot of Prefect's attempts to set up the flow/task.
This PR adds a clear error message, as the one you get today is `TypeError: 'bar' must be callable` which is very confusing.
```python
class Foo:
@task
@classmethod
def bar(cls, x):
pass
@staticmethod
@task
def baz(x):
pass
```

Add helpful warning about decorator order

---

src/prefect/server/api/automations.py
tests/events/server/test_automations_api.py

This was originally in place as part of the feature flagging mechanism for
events and automations, but is probably too aggressive for 3.0.  Similarly to
managing deployments even if `PREFECT_API_SERVICES_SCHEDULER_ENABLED` is turned
off, we can allow people to turn off triggers but still manage automations.

Enable the automations API even when the triggers service is disabled

---

docs/2.19.x/concepts/flows.mdx
docs/3.0rc/develop/observe-workflows/logging.mdx
docs/3.0rc/develop/write-workflows/index.mdx
src/prefect/flows.py

closes #13955
note we keep one reference to it in the task runners page to let people know that its gone now (should they come looking for it)

Remove remaining references to `SequentialTaskRunner` in 3.x docs

---

src/integrations/prefect-bitbucket/prefect_bitbucket/repository.py
src/integrations/prefect-github/prefect_github/repository.py
src/integrations/prefect-gitlab/prefect_gitlab/repositories.py

Our Github, Gitlab, and Bitbucket integrations had a dependency on `distutils`,
which was deprecated in Python 3.10 and removed in Python 3.12.  We were only
using them for a recursive copy utility, which is readily available in `shutil`.

Removing dependencies on `distutils` in VCS integrations

---

src/prefect/task_engine.py

This INFO log includes the task run name, but task run names won't be finalized until upstream parameters are available, which happens in `setup_run_context()`. Therefore it prints the decorated function's name even if a custom name was provided.

Move log to after task run name is set

---

tests/fixtures/time.py
tests/test_task_engine.py

This introduces a new `advance_time` fixture that allows for arbitrarily
adjusting the return value of `pendulum.now` in tests.  It's similar to its
counterpart `frozen_time`, but the time will advance on its own with each call.
The function returned by the fixture allows advancing time by a specified amount
in tests.

Controls time in the task engine cache tests to avoid flakes

---

src/prefect/tasks.py
tests/test_tasks.py

This PR adds a warning when `cache_key_fn` and `cache_policy` are both provided to a task informing the user that `cache_key_fn` takes precedence.
It also adds a test recording that the cache is busted when the `result_storage_key` on a task changes. This will be true until we implement a transaction record store separate from result storage.
Related to https://github.com/PrefectHQ/prefect/issues/13800

Adds warning when `cache_key_fn` and `cache_policy` are both provided to a task

---

src/prefect/task_worker.py
tests/test_task_worker.py

This endpoint, at `http://127.0.0.1:4422/status` reports the current state of
the `TaskWorker`, including what its limiting parameters look like and which
task runs of each key are currently in-flight.  This is a rough-and-ready
monitoring endpoint that we can flesh out with more info and tests as we go, but
for now, we need it for load testing and reliability troubleshooting.

Adds a private status endpoint to `TaskWorker`

---

requirements-dev.txt

Dependabot wanted to bump this for us, but it would have left it as a `<`
requirement, as well as retaining this stray comment in the requirements file.
Here I just bump it to a `>=`, since it should be working now.

Bumping `pytest-xdist`

---

src/prefect/results.py
src/prefect/task_engine.py
src/prefect/tasks.py
src/prefect/transactions.py
tests/events/client/instrumentation/test_task_run_state_change_events.py
tests/fixtures/storage.py
tests/results/test_flow_results.py
tests/results/test_result_factory.py
tests/results/test_task_results.py
tests/test_background_tasks.py
tests/test_task_engine.py
tests/test_task_runners.py
tests/test_task_worker.py
tests/test_tasks.py
tests/test_transactions.py

To ensure we get idempotency for tasks out of the box, we need to ensure that tasks persist their results by default. With this PR, `persist_result` will default to `True` for all tasks. If `persist_result` is set to false, then the `cache_policy` will be ignored.
To facilitate writing results by default, we will attempt to load a default storage block matching the default storage block configured with `PREFECT_DEFAULT_RESULT_STORAGE_BLOCK`. If that block doesn't exist (defaults to `{hostname}-storage`), we will create and save that block for the user. That block will be reused for subsequent runs.
Closes https://github.com/PrefectHQ/prefect/issues/14087
- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) …

Turn on task persistence by default

---

src/prefect/task_runs.py

There is a very narrow gap here, but it's possible nonetheless, where an event
could sneak through in the time between checking for a previously completed
task run and when we start waiting for the event to arrive on the websocket.
This closes the gap so that we make one more check just before we start waiting,
after having established the `asyncio.Event` for completion.
Part of #14098

Closes another race condition in task waiting

---

.pre-commit-config.yaml
docs/3.0rc/api-ref/server/schema.json
src/prefect/server/services/task_scheduling.py
src/prefect/settings.py
tests/test_background_tasks.py

During my load testing, it became clear that this feature won't work as-is on
such a short timescale.  Because tasks remain `PENDING` until all of their
dependencies are resolved, it's possible that a long period of time may elapse
before those `PENDING` tasks can actually move on to `RUNNING`, and in a system
with deep dependencies, this can put the task workers in a position where they
can't keep up and are constantly getting redelivered tasks.
Rather than defaulting this to on, we should let the user opt-in to the behavior
for now, based on their workload.

Disables server-side `PENDING` task rescheduling by default

---

src/prefect/utilities/urls.py

This log shows up very frequently when developing interactively, even when I have my log level set to WARNING, which I expect will only show me information that requires action or impairs performance. However, when developing or testing flows interactively, it is expected that no URL is available for the UI.

Downgrade missing url log from warning to info

---

docs/3.0rc/develop/write-tasks/dask-and-ray.mdx
src/integrations/prefect-ray/prefect_ray/task_runners.py

resolves https://github.com/PrefectHQ/prefect/issues/14099

chore(docs): add RayTaskRunner doc example using runtime_env

---

docs/3.0rc/get-started/quickstart.mdx

- Ends all sentences proceeding code/command blocks with a colon.
- Minor clarifications/additions to the converting to a workflow section

quickstart-tweaks

---

docs/3.0rc/get-started/quickstart.mdx
src/prefect/records/result_store.py
src/prefect/results.py
src/prefect/states.py
src/prefect/task_engine.py
src/prefect/transactions.py
tests/client/test_base_client.py
tests/results/test_persisted_result.py
tests/test_flows.py
tests/test_tasks.py
tests/test_transactions.py

This PR adds the ability to defer result persistence; in a follow up PR this will allow us to persist only on commit without changing any observable behavior.

Add ability to defer result persistence

---

docs/3.0rc/get-started/install.mdx
docs/contribute/dev-contribute.mdx
docs/contribute/index.mdx
docs/mint.json

This PR:
- touches up the Contributing section of our docs
- changes the default to light mode (I don't think a documentation site should ever default to dark mode)

Make some updates to the contributing sections of the docs

---

src/prefect/server/api/events.py
src/prefect/server/models/logs.py

When using the ephemeral API, one will occasionally see a frightening traceback because events are being received after interpreter shutdown has begun, which is an error specific to 3.12.2. This was addressed for logs in https://github.com/PrefectHQ/prefect/pull/13831, and this PR adds the same behavior (plus a debug log) for events.

Silence runtime errors for ephemeral shutdown

---

src/prefect/concurrency/asyncio.py
src/prefect/concurrency/services.py
src/prefect/concurrency/sync.py
tests/concurrency/test_concurrency_asyncio.py
tests/concurrency/test_concurrency_slot_acquisition_service.py
tests/concurrency/test_concurrency_sync.py

this PR moves the `timeout_async` context down into the `acquire_slots` method of the `ConcurrencySlotAcquisitionService` to ensure its scoped correctly.
this has the bonus that we remove some duplication as `_acquire_concurrency_slots` is used by both the `sync` and `asyncio` versions of the `concurrency` context manager
---
if this looks good ill port it to 2.x

Move timeout context into slot acquisition service

---

src/integrations/prefect-dask/prefect_dask/task_runners.py
src/integrations/prefect-dask/tests/test_task_runners.py
src/integrations/prefect-ray/prefect_ray/task_runners.py
src/integrations/prefect-ray/tests/test_task_runners.py
src/prefect/futures.py
tests/test_futures.py

Adds a `__del__` method to the following `PrefectFuture` implementations:
- `PrefectConcurrentFuture`
- `PrefectDaskFuture`
- `PrefectRayFuture`
These futures will log a warning if they are garbage collection before resolving. The user will be directed to call either `.wait()` or `.result()` on the future for subsequent runs.
Notably, this allows us to log a warning when a `PrefectRayFuture` is not resolved, which we were not doing previously.
Closes https://github.com/PrefectHQ/prefect/issues/14018
A flow that existing without waiting for a future like this:
```python
from prefect_ray import RayTaskRunner
@task
def say_hello(name):
return f"Hello {name}!"
@flow(task_runner=RayTaskRunner)
def my_flow():
say_hello.submit("world") …
```

Log warning when a Concurrent, Dask, or Ray versions of `PrefectFuture` are garbage collection before resolution

---

.pre-commit-config.yaml
scripts/generate_mintlify_openapi_docs.py

I learned something new with `pre-commit`: when you use the default
`pass_filenames: true`, all of the affected files are split into chunks and sent
to many instances of your hook in parallel.  Running `mintlify-scrape` in
parallel is pretty flakey and has been giving people fits.  Since this hook
doesn't need the specific filenames, we can turn off that option so it will
just invoke the script once.
Additionally, I'm using a more robust way to install `mintlify-scrape` with
the `npx` command, which will install it to the right place in a way that
doesn't require installing it globally.

Makes the OpenAPI docs generation more robust

---

docs/3.0rc/develop/write-tasks/index.mdx

Note that some changes depend on #14164 
My goal here was to give a practical orientation to caching without mentioning transactions, as those will be more advanced

Updates caching docs to be all about the new style of caching

---

src/prefect/tasks.py

Updates `Task.serve` to be `sync_compatible` to align with `Flow.serve`.
Closes #13446 

Make `Task.serve` sync compatible

---

docs/integrations/prefect-aws/index.mdx
docs/integrations/prefect-azure/index.mdx
docs/integrations/prefect-bitbucket/index.mdx
docs/integrations/prefect-dask/index.mdx

Updates libraries through prefect-dask. Pausing for feedback, if there is any.
Part of  #14131

Update integration library install instructions to show Prefect 2 and Prefect 3

---

src/prefect/task_runners.py
tests/test_task_runners.py

This PR fixes deadlocks with the default `ThreadPoolTaskRunner` by setting the `max_workers` setting arbitrarily high by default. In rare occasions, this will lead to thread exhaustion, but the default worker count in the `ThreadPoolExecutor` has proven to be too low in cases with nested dependent runs.
Closes https://github.com/PrefectHQ/prefect/issues/14194

Prevent deadlocks with default `ThreadPoolTaskRunner` settings

---

src/prefect/results.py
src/prefect/states.py
tests/results/test_persisted_result.py
tests/results/test_state_result.py

With some recent changes to transactions, we are now emitting events slightly
before we write results to their storage backend.  While we should undertake a
fuller refactoring to uncouple transaction storage from individual results, we
can also get by with a few built-in graceful retries here.  This should smooth
over the issue with the race condition, as well as help with transient network
issues on remote filesystems.
Part of #14189

Retries retrieval of persisted results from storage

---

docs/3.0rc/api-ref/server/schema.json
src/prefect/server/database/query_components.py
src/prefect/settings.py
tests/_internal/compatibility/test_experimental.py
tests/server/orchestration/api/test_flow_run_graph_v2.py
tests/server/test_app.py

Removes `PREFECT_EXPERIMENTAL_ENABLE_ARTIFACTS_ON_FLOW_RUN_GRAPH` and `PREFECT_EXPERIMENTAL_ENABLE_STATES_ON_FLOW_RUN_GRAPH` which are both on by default now.
closes https://github.com/PrefectHQ/prefect/issues/14211
closes https://github.com/PrefectHQ/prefect/issues/14210

Remove default-on, flow run graph experimental flags.

---

docs/3.0rc/api-ref/server/schema.json
src/prefect/server/api/events.py
src/prefect/server/events/filters.py
src/prefect/settings.py
tests/events/server/gateway/test_gateway_out.py

During my load testing of `TaskWorker`, I was able to narrow down one source of
instability to missing events during a websocket reconnection.  I realized that
we were only partially backfilling events down the socket (limited to 1k) and
that under moderate volume it was totally possible to miss events.  Instead,
we will clamp the backfill to 15 minutes worth of time and send _all_ of the
matching events.
Part of #14098

Backfill _all_ of the preceding events, in smaller batches and a limited time

---

docs/3.0rc/api-ref/server/schema.json
src/prefect/results.py
src/prefect/settings.py
src/prefect/tasks.py
tests/results/test_flow_results.py
tests/results/test_result_factory.py
tests/test_flow_engine.py
tests/test_flows.py
tests/test_states.py
tests/test_tasks.py

Sets `PREFECT_RESULTS_PERSIST_BY_DEFAULT` to `True` by default

Update persistence setting to mirror internal logic

---

src/prefect/client/schemas/objects.py
src/prefect/states.py
src/prefect/task_engine.py
tests/test_task_engine.py

This PR fixes the situation in which the API rejects a `Running` state and returns a `Completed` state with a stale result reference - results should be _entirely_ handled by the transactional machinery.  This PR bandaids that situation with a try / except that we'll be able to remove once the API is less heavy-handed.

Add fix for bad result references from the API

---

src/integrations/prefect-sqlalchemy/prefect_sqlalchemy/database.py
src/integrations/prefect-sqlalchemy/tests/test_database.py

Closes #14232 
Returns a CursorResult object when using execute / executemany.

returning cursor result from ex/exmany

---

src/prefect/cli/deploy.py
tests/cli/test_deploy.py

This PR skips formatting block documents in a `prefect.yaml`'s `work_pool.job_variables`. The worker that picks up a flow run for the created deployment will handle that resolution.
Closes https://github.com/PrefectHQ/prefect/issues/14088

Fix bug where block documents are resolved in `job_variables` before saving server-side

---

src/prefect/engine.py
src/prefect/flow_engine.py
tests/test_flow_engine.py

This ensures that when we start a flow run that we pull the parameters from the flow function definition if no parameters are provided via the flow run or passed into the `run_flow` method itself.
This also changes the entrypoint in the engine to use `run_flow` instead of `run_flow_sync` and `run_flow_async`.
Closes #13273 

Get `parameters` from flow definition if none are given otherwise

---

src/prefect/logging/loggers.py
src/prefect/task_engine.py
src/prefect/transactions.py
tests/test_tasks.py

I noticed that errors in both rollback and commit hooks are completely swallowed, which makes it really hard to debug when they occur.  This PR adds logging for those errors.

Log transaction hook errors for better UX

---

src/prefect/flow_runs.py
src/prefect/results.py

There is a longstanding issue with pickling locally-defined Pydantic models that is suddenly biting a lot of users (including myself 😅 ) now that we are optimistically persisting results by default for the transactional layer. A user testing ControlFlow immediately ran into this last night. We can take steps in CF proactively because we know what the user is trying to do, but I'm not sure how heavy-handed we can be in Prefect proper. For example, I do not think we can automatically select a different serializer at this point. Instead, this PR adds an explanation to what is otherwise a very cryptic error (`TypeError: cannot pickle 'sqlite3.Connection' object`), which we reraise.

Add extra info to pydantic error to help users recover

---

src/integrations/prefect-docker/pyproject.toml
src/prefect/flows.py
tests/test_flows.py

We had previously pinned `requests` due to an upstream compatibility issue
between `docker` and `requests` (which should have been fixed by now).  Pinning
this dependency means that the security alerts about `requests` are listed as
ours.  We don't reference `requests` directly, so we can stop doing this for
now.
Note: I'm also addressing a set of circular imports around `prefect.flows` and `prefect.runner` in order for the Docker test suite to pass

Removes our declaration of a dependency on `requests` for `prefect-docker`

---

docs/assets/code.css

This PR updates codeblock styling to better match the branding of the docs. 
| Before | After |
|---|---|
| <img width="793" alt="Screenshot 2024-06-24 at 1 14 19 PM" src="https://github.com/PrefectHQ/prefect/assets/27291717/bee998a2-b7e1-47fb-90be-8d1dc8e95679"> | <img width="793" alt="Screenshot 2024-06-24 at 1 14 22 PM" src="https://github.com/PrefectHQ/prefect/assets/27291717/a717fcf5-2fbf-470f-aefc-d11156b085b2"> |
| <img width="793" alt="Screenshot 2024-06-24 at 1 14 01 PM" src="https://github.com/PrefectHQ/prefect/assets/27291717/eb9f633d-4fac-40ab-827c-e6686dfdec40"> | <img width="793" alt="Screenshot 2024-06-24 at 1 14 04 PM" src="https://github.com/PrefectHQ/prefect/assets/27291717/4e7be874-bf00-4667-ab87-79b38fa56408"> |
| <img width="793" alt="Screenshot 2024-06-24 at 1 15 …

Enhancement: Docs codeblock styling

---

.github/ISSUE_TEMPLATE/0_3x_bug_report.yaml
.github/ISSUE_TEMPLATE/1_2x_bug_report.yaml

Re: [this conversation](https://prefecthq.slack.com/archives/C0796KB678S/p1718976362315659), we would like to have a separate issue template for 3.x issues to help organize the GitHub project board/priorities.

Add `3.x`-specific issue template

---

mkdocs.yml

Attempting to get 3.x docs bar to show.

Remove announce dismiss in mkdocs.yml

---

src/prefect/flows.py
src/prefect/results.py
src/prefect/tasks.py
tests/results/test_result_factory.py
tests/test_flows.py
tests/test_tasks.py

Right now, users have to explicitly set `persist_result=True` in their task inits, _or_ set the global `PREFECT_RESULTS_PERSIST_BY_DEFAULT`.  This is overly conservative; when a user sets other settings such as cache key policies, they are clearly opting into result persistence so we can improve the DX here by making that inference on users' behalf.
In addition, this PR adds similar logic to flow init and allows settings configured at the flow level to become defaults for tasks if they are not otherwise set on the task.

Infer task result persistence from other settings

---

docs/3.0rc/api-ref/server/schema.json
src/prefect/filesystems.py
src/prefect/flows.py
src/prefect/results.py
src/prefect/settings.py
src/prefect/tasks.py
src/prefect/transactions.py
tests/events/client/instrumentation/test_task_run_state_change_events.py
tests/results/test_flow_results.py
tests/results/test_result_factory.py
tests/results/test_task_results.py
tests/test_background_tasks.py
tests/test_filesystems.py
tests/test_flows.py
tests/test_futures.py
tests/test_task_engine.py
tests/test_task_worker.py
tests/test_tasks.py
tests/test_transactions.py

This PR avoids the unnecessary persistence of blocks, specifically local storage blocks. There's essentially no reason to store a local storage block as absolute paths are all that's needed to read and write locally.
This PR makes default storage local-file based without block references.

Save absolute paths with no block IDs by default

---

docs/3.0rc/resources/upgrade-prefect-3.mdx

The link to the migration script in the upgrade doc was pointed at a commit, when it should probably just be pointed at main so the latest changes are there.

Point to `main` for migration script in upgrade doc

---

src/prefect/server/api/validation.py
tests/server/orchestration/api/test_validation.py

Code scanning alerts [2014](https://github.com/PrefectHQ/prefect/security/code-scanning/2014) and [2015](https://github.com/PrefectHQ/prefect/security/code-scanning/2015) point out that we're using a potentially user-provided value in a log message.
I also noticed that, becuase we aren't validating that the given block document
ID was a UUID, we were also passing a user-provided value through the models
layer.  Parsing the given string to a UUID resolves both issues.

Resolves two log injection security alerts

---

requirements-client.txt
src/prefect/cli/cloud/__init__.py
src/prefect/server/api/server.py

This is the 2.x side of https://github.com/PrefectHQ/prefect/pull/14361 
In this version we're manually setting `handle_signals=False` in the fastapi factory instead of changing the default value, keeping the, possibly, breaking change in the 3.x line.
Related to #14318

Allow uvicorn > 0.29.0 (2.x)

---

src/prefect/flows.py
tests/test_flows.py

This fixes an issue where splitting a dynamic flow name across multiple lines would result in an error when it was `eval`'ed.
Closes #14025

Handle multi-line dynamic flow names

---

docs/3.0rc/resources/upgrade-agents-to-workers.mdx
src/prefect/flows.py

the current version of the [guide has a section titled `flow.deploy`](https://docs-3.prefect.io/3.0rc/resources/upgrade-agents-to-workers#flow-deploy) and means to help people off `Deployment.build_from_flow`, but the first couple examples use `flow.serve`.
`flow.serve` is not a direct replacement for `Deployment.build_from_flow` because no one who was using the latter ever got a blocking process that serves their flow as a deployment. `flow.deploy` is the direct analogue and the subject of the section and seems like it should be used in the examples.
i keep a link to the main docs on `serve`

Add more direct recommendations to worker upgrade guide

---

docs/3.0rc/deploy/index.mdx
src/prefect/cli/deploy.py

closes https://github.com/PrefectHQ/prefect/issues/14422
this PR:
- adds small example use to Deployment Overview below existing docs on running a deployment from the CLI. includes some commonly needed kwargs
- updates `infra_overrides` references to `job_variables`
- removes incorrect `Deployment` field `trigger`
- adds one missing `Optional`

Refresh `Deployment` overview and add note on `run_deployment` sdk use

---

src/prefect/exceptions.py
tests/test_exceptions.py

closes #14406
handles the case where an `loc` item might be an `int`, when you are referring an index in a list input type
```python
File "/home/nmclean/.cache/pypoetry/virtualenvs/global-calculator-UYA1GDje-py3.11/lib/python3.11/site-packages/prefect/exceptions.py", line 181, in <listcomp>
bad_params = [f'{".".join(err["loc"])}: {err["msg"]}' for err in exc.errors()]
^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 1: expected str instance, int found
```

handle join edge case in `ParameterTypeError.from_validation_error`

---

src/integrations/prefect-aws/prefect_aws/s3.py
src/integrations/prefect-aws/tests/test_s3.py

This is the 2.x side of https://github.com/PrefectHQ/prefect/pull/13819, the issue here presented the same, but was _slightly_ different. Similar to the 3.x side, the crux of the problem is Pydantic + nested blocks with a Union. In this case though the issue was presenting as the `AwsClientParameters` being a `dict` on the credentials rather than an instance of the class. This adds a validator to check for this case and create an instance from the dict.
Closes #14147

Handle case where `AwsClientParameters` is a dict

---

docs/.vale.ini
docs/3.0rc/deploy/infrastructure-concepts/prefect-yaml.mdx
docs/3.0rc/deploy/infrastructure-concepts/work-pools.mdx
docs/3.0rc/deploy/infrastructure-examples/serverless.mdx
docs/3.0rc/develop/blocks.mdx
docs/3.0rc/develop/deferred-tasks.mdx
docs/3.0rc/develop/interact-with-data.mdx
docs/3.0rc/develop/pause-resume.mdx
docs/3.0rc/develop/write-tasks.mdx
docs/3.0rc/get-started/install.mdx
docs/3.0rc/get-started/quickstart.mdx
docs/3.0rc/manage/cloud/index.mdx
docs/3.0rc/manage/cloud/manage-users/manage-roles.mdx
docs/3.0rc/manage/cloud/workspaces.mdx
docs/3.0rc/resources/upgrade-agents-to-workers.mdx
docs/3.0rc/resources/upgrade-prefect-3.mdx
docs/contribute/styles-practices.mdx
docs/getting-started/installation.mdx
docs/integrations/prefect-azure/index.mdx
docs/integrations/prefect-dbt/index.mdx
docs/integrations/prefect-gcp/index.mdx

This PR brings the 3.0rc repo and other docs files to 0 errors and 53 warnings. Does not include the Server API docs.
From the docs folder, run with:
```vale --glob='!{*.mdx,*.js,*.json,*.png,*.jpg,*.css,*.yml,*.svg,3.0rc/api-ref/*.md}' ./3.0rc```
It runs quickly locally.

More docs style improvements from Vale

---

docs/3.0rc/develop/results.mdx
docs/mint.json

This PR puts the finishing touches on #14394 by:
- rearranging and better organizing the sections
- including more information on the categories of configuration for results
- documenting the new `PREFECT_DEFAULT_RESULT_STORAGE_BLOCK` setting (**cc:** @taylor-curran )

Finalize results doc

---

.github/workflows/label-check.yml

It would be useful to ensure we don't have uncategorized PRs, when it comes to release notes.

Ensure label on PRs for release notes

---

tests/test_tasks.py

This fixes the flaky `test_logs_message_when_submitted_tasks_end_in_pending` test. The original test was just queuing up 100 tasks that were no-ops, and sometimes those tasks were able to all complete before the flow fully exited. This version gives it a single, somewhat expensive, never ending, task that should never complete, allowing the flow to exit before the task finishes.
Closes #14225

Fix flaky `test_logs_message_when_submitted_tasks_end_in_pending` test

---

tests/test_task_engine.py

This gives a larger window for the call args to sleep in `test_async_task_respects_retry_delay_second`. On slower systems the amount of time we're going to sleep is going to be smaller, which seems to be causing this flake.

Fix flaky `test_async_task_respects_retry_delay_second` test

---

src/prefect/logging/loggers.py
src/prefect/server/api/server.py
tests/public/flows/test_previously_awaited_methods.py
tests/test_task_engine.py

this [PR](https://github.com/PrefectHQ/prefect/pull/14190) shuffled some imports and resulted in us not respecting the server log level (defaults to `WARNING`), and giving `INFO` regardless, which is much more verbose than the implicit default.
since we want to keep `__init__.py` clean, this PR moves the logging setup we need to `create_app` since that's where it seems we already do a bunch of similar ad-hoc setup

do logging setup in `create_app`

---

src/integrations/prefect-docker/prefect_docker/worker.py
src/integrations/prefect-docker/tests/test_worker.py

closes https://github.com/PrefectHQ/prefect/issues/14490
[this previous](https://github.com/PrefectHQ/prefect/pull/13697) PR introduced an incorrect `AfterValidator` for a self-validating `VolumeStr` which was `lambda v: ":" in v` which returns a `bool`, effectively casting all users' volumes `str->bool` after instantiation
this PR fixes this and adds some regression tests

Fix docker worker volumes

---

src/prefect/cli/server.py

closes https://github.com/PrefectHQ/prefect/issues/14476
previously, whether or not the dashboard was build only depended on `PREFECT_UI_ENABLED`, where that should be starting place that can be overridden or not by the `ui`/ `no-ui` flag on `prefect server start`
```bash
docker build . -t test
docker run -p 4200:4200 --rm test -- prefect server start --host 0.0.0.0 --ui # correctly builds dashboard
docker run -p 4200:4200 --rm test -- prefect server start --host 0.0.0.0 --no-ui # correctly skips dashboard
```

respect `--ui`/`--no-ui` flag on `prefect server start`

---

src/prefect/cli/deploy.py
src/prefect/flows.py
src/prefect/runner/server.py
tests/test_flows.py

This extends the work done in https://github.com/PrefectHQ/prefect/pull/13315 to also allow loading flows from an entrypoint when dependencies are missing.
Closes #14464

Allow loading flows from an entrypoint when dependencies are missing

---

docs/3.0rc/api-ref/rest-api/server/schema.json
src/prefect/runner/server.py
src/prefect/runner/submit.py
src/prefect/settings.py
tests/runner/test_submit.py
tests/runner/test_webserver.py

Removes the `PREFECT_EXPERIMENTAL_ENABLE_EXTRA_RUNNER_ENDPOINTS` flag and related code.
Closes #14212

Remove `PREFECT_EXPERIMENTAL_ENABLE_EXTRA_RUNNER_ENDPOINTS` flag

---

src/integrations/prefect-dbt/prefect_dbt/cloud/jobs.py
src/prefect/cli/_prompts.py
src/prefect/server/services/cancellation_cleanup.py
src/prefect/utilities/engine.py

Fix type check warnings reported by Pyre@Google, which were outdated after code modifications.
1. update the type hint of argument `run_id`  in function `_build_trigger_job_run_options` from `str` to `int`, since the `run_id` is used as an argument in `get_dbt_cloud_run_artifact.with_options` and should be `int` after the commit https://github.com/PrefectHQ/prefect/commit/839c3b02e007d14a2b7df6a01b208c724caffa4d
2. update the return value type of function `build_table` from `Table` to `Union[Table, Group]`, since it can return `Group` after commit https://github.com/PrefectHQ/prefect/commit/0429a61d5554233489a3cb6aefed3df9b11fd03c
3. update the return value type of function `_cancel_subflow` from `None` to `Optional[bool]`, since it can return `False` and `None` after commit …

Type hint Fix

---

.github/CODEOWNERS

Now that events are all cooked in 3.0, these can just be treated normally.  I
also noticed we had some legacy rules that are no-ops as well, so I removed
those too.

Removes the extra CODEOWNERS entry for events

---

docs/mint.json
docs/styles.css

Before (note the faint weird border inside the button): 
After:

Enhancement: Cloud CTA dark mode button

---

src/prefect/flows.py
src/prefect/runner/runner.py
src/prefect/utilities/asyncutils.py
tests/runner/test_runner.py
tests/runner/test_webserver.py
tests/test_flows.py

using `sync_compatible` on async functions causes a host of problems:
- cancellation upon sigterms is interrupted
- typing is screwed up
`serve` doesn't need all the baggage, since its only ever expected to be a blocking thing anyways, so we make `serve` sync, and consequently, make `Runner.start` non `sync_compatible` since its not really user-facing and would just cause the same "interrupted `KeyboardInterrupt`" problem as `serve` being `sync_compatible` originally
This is a breaking change, as `serve` must now be called as a sync function. I would argue that there is no practical reason to have `serve` be async for users, but curious for feedback on this (cc @desertaxle @cicdw)
- typing now looks like
- and deployments are successfully paused upon control-c

syncify `serve`

---

src/prefect/transactions.py
tests/test_tasks.py

This PR adds INFO logging around transaction rollback and commit hooks for identifying execution and completion of those hooks. Similar to logging around other registered hooks like `on_failure`.
Closes #14565 

Info logging around transaction hooks

---

docs/3.0rc/deploy/run-flows-in-local-processes.mdx

Fixes example code script title formatting.
Problematic formatting example:

Fix title formatting of code sample scripts in serve docs

---

src/prefect/futures.py
tests/test_futures.py

Adds a `wait`utility function that mirrors that of `concurrent.futures.wait`. 
Closes #14240
- [ x ] This pull request includes a label categorizing the change e.g. `maintenance`, `fix`, `feature`, `enhancement`, `docs`.
- [ x ] This pull request references any related issue by including "closes `<link to issue>`"
- [ x ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ x ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ x ] If this pull request adds functions or classes, it includes helpful docstrings.

Adds `wait` utility for `PrefectFutures`

---

src/prefect/server/database/migrations/versions/postgresql/2024_07_15_145240_7495a5013e7e_adding_scope_to_followers.py
src/prefect/server/database/migrations/versions/sqlite/2024_07_15_145350_354f1ede7e9f_adding_scope_to_followers.py
src/prefect/server/database/orm_models.py
src/prefect/server/events/ordering.py
src/prefect/server/events/triggers.py
tests/events/server/test_ordering.py
tests/events/server/triggers/test_basics.py
tests/events/server/triggers/test_regressions.py
tests/events/server/triggers/test_service.py

For the triggers system, we keep track of out-of-order messages and attempt to
replay them in causal order (where an event is processed after the event that
it declares it `follows`).  This change extracts this logic to a class and
separates the bookkeeping records so that multiple consumers can keep separate
track of events.
This is largely a port of the changes in Prefect Cloud that we made last week.
Closes #14577

Refactors event causal ordering to be reusable by multiple consumers

---

src/prefect/_internal/retries.py
src/prefect/deployments/steps/pull.py
tests/_internal/test_retries.py
tests/deployment/test_steps.py

this PR adds retries to `git_clone` to retry pulling code from github 
we discussed using `tenacity` internally and decided to avoid it for now, since we may want an opinionated retry primitive later, that we wouldn't necessarily want coupled to `tenacity`
instead, this PR implements an `_internal` `retry_async_fn` (explicitly for async functions 🙂) to accomplish what we need

retry `git_clone` pull step

---

src/prefect/client/schemas/objects.py
src/prefect/utilities/engine.py
tests/events/client/instrumentation/test_task_run_state_change_events.py

In advance of client-side task orchestration, this expands the data we include
on task run state change event payloads.  It includes the full current `TaskRun`
minus redundant info like `id` and `created/updated`.  The state details for
the two states are also included.
Closes #14582

Adds more detail to task run state change events, including the full task run

---

.github/workflows/docker-images.yaml

closes https://github.com/PrefectHQ/prefect/issues/14228
allows ad-hoc publishing of `3-latest` images via `workflow_dispatch`
this PR:
- adds the ability to publish `3-latest` tags (for each minor version and flavor) on `workflow_dispatch`

update docker image builds to publish `3-latest` images

---

src/prefect/context.py

When running tasks within a flow, the client will attempt to track data dependencies between tasks by associating the object ID of a task execution's return value with the state of the corresponding task run. Those values are stored in a dictionary on the `FlowRunContext` of the current flow run.
This behavior leads to excessive memory usage that scales as a function of the size of the task execution return values and the number of task executions in a flow. The state stored on the `FlowRunContext` contains a reference to the result of the task run, which holds a reference to the return value of the user's code (as long as `cache_result_in_memory` is enabled, which it is by default). These held references prevent the Python runtime from garbage-collecting task execution return values …

Fix excessive memory usage in flows with many tasks

---

src/prefect/flow_engine.py
tests/test_flows.py

This PR moves the `call_hooks` in the flow engine so that the hooks run within the flow run context, the fact this has not been the case has been a common sticking point in the past. With planned restrictions like https://github.com/PrefectHQ/prefect/pull/13688 (creating artifacts only in a flow run context), it would be nice to be able to create artifacts in an `on_completion` hook for example.
There is a consideration here about the injected kwargs (flow, flow_run, state), since this PR would make it trivially easy to get these things from `get_run_context` (many ways to do the same thing), open to feedback on this.
Intentionally did not do the task run engine in this PR as I figured I should wait for https://github.com/PrefectHQ/prefect/pull/14643 to land

Run flow hooks in flow run context

---

src/prefect/flow_engine.py
src/prefect/flows.py
src/prefect/runner/runner.py
tests/runner/test_runner.py
tests/runner/test_webserver.py
tests/test_flows.py

closes #14663 
This PR:
- Adds `use_placeholder_flow: bool` flag to `load_flow_from_entrypoint`
- Updates uses to `use_placeholder_flow=True` at deployment time and `False` at runtime
- Adds test for `use_placeholder_flow`
- moves the `Runner`'s capacity limiter to `__aenter__` for consistency with the other attrs that need to be created in an async context
Addresses misleading `SignatureMismatchError`s when flows run with missing dependencies. Allows immediate failure with `ScriptError` during runtime, while maintaining placeholder flows for deployment creation.
we now get an error like this on the worker if we cant load the flow
```python
prefect.exceptions.ScriptError: Script at 'src/demo_project/param_sig.py' encountered an exception: ModuleNotFoundError("No module named 'pandas'") …
```

Fix runtime load from entrypoint

---

src/prefect/utilities/asyncutils.py
tests/deployment/test_base.py
tests/test-projects/flows/uses_block.py
tests/test_flow_engine.py

This PR ensures that functions wrapped in `@sync_compatible` execute as expected in remote environments by setting `RUNNING_ASYNC_FLAG` to `False` when running a sync function in a worker thread. Flow scripts are loaded in a worker thread without an event loop, so updating the `RUNNING_ASYNC_FLAG` context variable will ensure those wrapped async functions execute as sync.
I noticed that a couple of threads are created when loading a flow script. The number of created threads could be reduced by creating a sync implementation of `load_flow_from_flow_run`, but we'd likely still need to call storage block methods and pull steps in a separate thread since they are async by default.
Closes https://github.com/PrefectHQ/prefect/issues/14625
- If no issue exists and your change is not a small …

Improve consistency of `sync_compatible` when running flows in remote environments

---

src/prefect/task_engine.py
tests/test_task_engine.py

Adds local orchestration for setting the `start_time` on the `TaskRun`.
Tasking over the responsibility from: https://github.com/PrefectHQ/prefect/blob/96140dee4aed2f13b3852deb63c5b76687fa42f1/src/prefect/server/orchestration/global_policy.py#L96-L108

add start time tracking

---

src/prefect/task_engine.py
tests/test_task_engine.py

This is the client-side version of the `SetRunState*` orchestration rules.  The
task run recorder in Cloud (and soon to be in OSS) covers the equivalent
server-side denormalizations for the database models.

Updates de-normalized state fields during client-side orchestration

---

src/prefect/task_engine.py
tests/test_task_engine.py

This also includes a small refactoring to more cleanly split client-side from
server-side orchestration in `TaskRunEngine.set_state`.

Predictively updates the run IDs on `State.state_details` client-side

---

src/prefect/task_engine.py
tests/test_task_engine.py

These two counters, the `flow_run_run_count` and the `run_count`, are mostly
used during retry handling, which should already be completely handled on the
client-side and may not be necessary to track for client-side orchestration.
We do, however, want to keep the server-orchestrated and client-orchestrated
behavior as similar as possible, so they are updated here for completeness.

Incrementing run counts during client-side task orchestration

---

src/prefect/task_engine.py
tests/test_task_engine.py

Adds the equivalent handling for setting the end time for terminal states during client side task run orchestration, which is part of the responsibilities of `SetEndTime`. Covers `COMPLETED`, 'FAILED` and `CRASHED`. `CANCELLED` is not something that is handled client side.
Note: I'm not implementing the first half of the rule because task runs shouldn't be leaving a terminal state
https://github.com/PrefectHQ/prefect/blob/7bea0f0e0fbc814c100ffc7f6acdc879e0adb9ff/src/prefect/server/orchestration/global_policy.py#L124-L150

set `end_time` during client-side task orchestration

---

src/prefect/task_engine.py
tests/test_task_engine.py

This PR implements the client-side task orchestration version of `IncrementRunTime`. I added a method `TaskEngine.record_terminal_state_timing` to encapsulate this.

client-side task orchestration - `IncrementRunTime`

---

src/prefect/task_engine.py
tests/test_task_engine.py

The logic of `SetExpectedStartTime` is already implemented here when we set this when creating the run for the first time. This pr is just adding tests for it.
https://github.com/PrefectHQ/prefect/blob/main/src/prefect/tasks.py#L909-910
Original rule:
https://github.com/PrefectHQ/prefect/blob/033cb35ef8d228805fb132f9463b9e361e940aa4/src/prefect/server/orchestration/global_policy.py#L226-L245

client-side task orchestration - `SetExpectedStartTime`

---

src/integrations/prefect-docker/prefect_docker/worker.py
src/integrations/prefect-docker/tests/test_worker.py

Picks up from https://github.com/PrefectHQ/prefect-docker/pull/85.
```python
import socket
def docker_flow():
print(socket.gethostname())
docker_flow.deploy(
name="docker-flow",
image="my_registry/dockerflow:latest",
work_pool_name="docker-dev",
job_variables={"container_create_kwargs": {"hostname": "custom_hostname"}},
)
```
```bash
13:29:40.161 | INFO    | prefect.flow_runs.worker - Completed submission of flow run '299d1d66-1f37-48f7-a454-90c1d0913ae4'
18:29:41.885 | INFO    | prefect.flow_runs.runner - Opening process...
18:29:43.211 | INFO    | Flow run 'positive-leopard' - Downloading flow code from storage at '.'
18:29:43.688 | INFO    | Flow run 'positive-leopard' - custom_hostname
18:29:43.834 | INFO    | …
```

Add `container_create_kwargs` to Docker worker

---

.github/workflows/copy-linked-issue-labels.yml

This new workflow will automatically label a PR with all the labels from any issues referenced within its description.
Action definition is from [here](https://github.com/michalvankodev/copy-issue-labels).
Random reference of #14658 and #14671 just to see if this workflow will run on this PR (random references won't work I'm now seeing - it will need to be an official link based on [special GitHub keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)).

Add workflow that auto populates labels based on linked issues

---

src/prefect/task_engine.py
tests/test_task_engine.py

When moving to a `Retrying()` state and using client side orchestration, make sure to update the run count. This lets us remove an `xfail` around an existing test

update task run counts on retry with client-side task orchestration

---

src/prefect/task_worker.py
src/prefect/tasks.py
tests/events/client/instrumentation/test_task_run_state_change_events.py
tests/test_background_tasks.py
tests/test_tasks.py

closes #13735 
this PR removes our reliance on the absolute path of the source file, which caused persistent cache misses due to source code being cloned to tmp dirs
the original issue was reported on a 2.x version - if this looks good I can backport this to `2.x`

Fix task key computation

---

setup.cfg

update setup.cfg to allow us to show users deprecation warnings without failing tests

silence `PrefectDeprecationWarning` in tests

---

src/prefect/flows.py

The current typing suggests input should be a list-of-list of schedules, but really should be a list of schedules. The 3 or 4 functions it passes it to expects `Optional[FlexibleScheduleList]`.

Fix typing of schedules argument in Flow.to_deployment

---

docs/3.0rc/api-ref/rest-api/server/schema.json
src/prefect/client/schemas/actions.py
src/prefect/server/api/deployments.py
src/prefect/server/schemas/actions.py
tests/server/orchestration/api/test_deployments.py

Exposes a flag for enforcing parameter validation (or not) on individual flow runs. This allows for overriding the default setting on the deployment.
Closes #9215

Expose enforce parameter schema flag on individual flow runs

---

src/prefect/server/api/deployments.py
src/prefect/server/schemas/actions.py
tests/server/api/test_deployments.py

This PR adds an `enforce_parameter_schema` flag to flow run creation that mirrors the logic for the setting on the deployment itself; this allows for users to toggle behavior when creating a given flow run (for experimentation, etc.). 
This is the 2.x lineage version of #9215, will open a corresponding 3.0 PR and begin work on the UI after this is approved and merged

Expose schema validation flag on deployment flow run create

---

src/prefect/server/events/schemas/events.py
src/prefect/server/services/task_run_recorder.py
tests/server/services/test_task_run_recorder.py

closes: https://github.com/PrefectHQ/prefect/issues/14648
Updates `TaskRunRecorder` from being a no-op service to actually processing `task-run` events that come through.
For every event we see we'll:
- insert or update the task run
- insert the task run state
- update the task run with the state data

let `TaskRunRecorder` process events into task runs/task run states

---

src/prefect/utilities/asyncutils.py
tests/utilities/test_asyncutils.py

This PR backports the `_sync` kwarg on `sync_compatible` decorated methods and functions.
There's a lot of conditional logic here so it may take some inspection to convince yourself that this won't affect current behavior.
Related to #14712

Backport _sync kwarg to 2.x

---

src/prefect/results.py

It looks like `_get_or_create_default_storage` is not invoked anywhere, so this PR removes it.

Remove unused function in results.py

---

src/prefect/task_engine.py
tests/test_task_engine.py

This PR:
- ensures we always pass a `Failed` state with the corresponding raised exception to `retry_condition_fn`'s, to preserve behavioral compatibility with 2.x
- supports asynchronous `retry_condition_fn`
Closes #14745

Always pass failed state to retry handlers and support async

---

docs/3.0rc/develop/write-flows.mdx
docs/3.0rc/resources/upgrade-prefect-3.mdx

adds docs about how final state of flow runs is determined, focusing on the contrast to prefect 2
related to #14470

Add migration docs about final flow run state

---

docs/3.0rc/api-ref/rest-api/server/schema.json
src/prefect/settings.py
src/prefect/utilities/asyncutils.py
tests/utilities/test_asyncutils.py

Removes two stale settings:
- `PREFECT_EXTRA_ENTRYPOINTS` 
- `PREFECT_EXPERIMENTAL_DISABLE_SYNC_COMPAT`

Remove stale settings

---

.github/workflows/python-tests.yaml

This job posted to an internal slack channel whenever tests were failing on main regularly; I'll be monitoring test failures closely on a daily basis and so this isn't needed anymore, and I want to keep the repo as tidy as possible.

Remove notify job

---

.github/release.yml

This PR updates the template for our auto-generated release notes within GitHub, and will replace our `generate-release-notes.py` script once tested.

Update github auto-release notes template

---

src/integrations/prefect-dbt/prefect_dbt/cli/configs/snowflake.py
src/integrations/prefect-dbt/tests/cli/configs/test_snowflake.py

Per [dbt documentation](https://docs.getdbt.com/docs/core/connect-data-platform/snowflake-setup#key-pair-authentication), 
> Starting from [dbt version 1.7](https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.7), dbt introduced the ability to specify a private_key directly as a string instead of a private_key_path.
This change makes sure that a `private_key`, if specified in the `SnowflakeConnector`, is included in the dbt profile. 
One hiccup is that the `private_key` in `SnowflakeCredentials` is a `Optional[SecretBytes]`, which, if left as-is, is written as a binary to `profiles.yml`—which is not supported by `dbt`. So, we deal with the edge-case by manually `decode`-ing `private_key` if it exists. 
```python
from prefect_dbt.cli import DbtCliProfile
from …
```

Add support for Snowflake private_key in prefect_dbt

---

src/prefect/events/clients.py
src/prefect/task_engine.py
src/prefect/task_worker.py
src/prefect/testing/fixtures.py
tests/test_task_worker.py

One the only places we set a task run's state external to the `TaskRunEngine` is inside of `TaskWorker` when we claim a run. This PR integrates our client side orchestration into `TaskWorker` and removes that api call, instead opting to just emit an event that run has moved to `PENDING`.
closes: https://github.com/PrefectHQ/prefect/issues/14717

remove `TaskWorker` set state api call

---

src/prefect/server/api/events.py
src/prefect/server/events/pipeline.py
tests/events/server/gateway/test_gateway_in.py

When receiving events via `ephemeral_request`, we previously wrote the events directly to the DB. This PR updates that to use the newly added `EventsPipeline` to make sure we're doing all the bookkeeping we want when an event reaches the api.

record events with ephemeral api

---

src/prefect/client/orchestration.py
src/prefect/client/utilities.py
src/prefect/context.py
src/prefect/flow_engine.py
src/prefect/task_engine.py
tests/test_flow_engine.py
tests/test_task_engine.py
tests/test_task_worker.py

This creates an `AsyncTaskRunEngine` and wires it up to run async tasks.
To reduce the code duplication I created a `BaseTaskRunEngine` that has all of the shared `sync` code, and then a `SyncTaskRunEngine` for sync tasks, and the new `AsyncTaskRunEngine` for async tasks.
Closes #14113

Create an AsyncTaskRunEngine and wire it up to run async tasks

---

src/prefect/blocks/notifications.py
tests/blocks/test_notifications.py

closes #14575 
This PR adds support for Microsoft Teams notifications using the new Power Automate (Workflows) system. This update is necessary due to the upcoming deprecation of the old Teams webhook system (see https://github.com/caronc/apprise/issues/1161).
This PR
- Updates `MicrosoftTeamsWebhook` notification block
- Updates tests to accommodate the new block
- Leverages Apprise's `NotifyWorkflows` for handling the new URL format
```python
from prefect.blocks.notifications import MicrosoftTeamsWebhook
teams_webhook = MicrosoftTeamsWebhook(
url="https://prod-XX.REGION.logic.azure.com:443/workflows/YOUR_WORKFLOW_ID/triggers/manual/paths/invoke?sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=YOUR_SIGNATURE"
)
teams_webhook.notify("meowdy!")
```
- i dont have Teams access at the moment, so I …

Microsoft Teams Webhook Support for Power Automate (Workflows)

---

src/prefect/task_engine.py
tests/test_task_engine.py

If there are no tags on the task, we don't need to use the concurrency context manager

only use concurrency when tasks have tags

---

docs/3.0rc/api-ref/rest-api/server/schema.json
requirements-client.txt
src/prefect/context.py
src/prefect/runner/runner.py
src/prefect/server/api/server.py
src/prefect/settings.py
src/prefect/task_worker.py
src/prefect/utilities/services.py
tests/utilities/test_services.py

This adds the `prometheus_client` library as a client-side dependency.  This
is a very lightweight (<500KB compiled) library with no transitive dependencies.
I'm choosing Prometheus here as it is the current standard for metrics from the
CNCF, and because its Python client library is very light and thus suitable for
inclusion on the client-side of Prefect.
There are two "sides" that expose a Prometheus metrics endpoint:
* The Prefect server will expose it from startup if `PREFECT_API_ENABLE_METRICS`
is on.  This endpoint is at `/api/metrics` (to avoid any potential collision
with future UI routes).
* The Prefect client SDK will expose these from any of the following points if
`PREFECT_CLIENT_ENABLE_METRICS` is on:
* Serving one or more flow via `serve(...)`
* Serving one or more tasks via …

Adds Prometheus metrics for API and client

---

benches/bench_import.py
src/prefect/events/clients.py

Following the addition of the `prometheus_client` in #14783, this adds counters
for measuring the performance of Prefect event emissions and subscription.
A note about unit tests: I don't traditionally add unit tests for
"leaf-level" instrumentation like this.  Leaf-level here means it is measuring
something about the system and doesn't form part of a measurement API (like if
there were middleware for measuring HTTP latency, for example). Unless it is
particularly complex to calculate, I generally skip extra unit tests and let the
standard test suite and coverage inform me if the instrumentation might be a
problem or not executed.

Adds metrics for client-side event emission and subscription

---

src/prefect/cli/profile.py
src/prefect/profiles.toml
src/prefect/settings.py
tests/cli/test_profile.py
tests/test_context.py
tests/test_settings.py

this PR adds a `populate-defaults` command to the `profiles` subgroup of the CLI to populate the `PREFECT_PROFILES_PATH` with a sane starting place that conveys best practices on how to use profiles.
- if the recommended template content already exists at `PREFECT_PROFILES_PATH`, no action is taken and we exit
- if a custom `profiles.toml` exists at `PREFECT_PROFILES_PATH` the user will be asked to confirm a backup and update to their existing file (if any profiles with the recommended names exist, they will be carried over untouched).
- if we havent exited, the content of `src/prefect/profiles.toml` will be written to `PREFECT_PROFILES_PATH`
this PR omits the `test` profile for now, see the comment below for why
```
[profiles.test]
PREFECT_API_DATABASE_CONNECTION_URL = …
```

add `prefect profiles populate-defaults` CLI command

---

src/prefect/blocks/notifications.py

3.8 doesn't support the nice `|=` dict merge

fix teams webhook block syntax for 3.8

---

future-docs/2.19.x/how-to-guides/work-pools/deploying-flows.mdx

Removes an extra backtick in the documentation on deploying flows.
Removes an extra backtick in the docs on deploying flows:
- ~~This pull request references any related issue by including "closes `<link to issue>`"~~
- ~~If this pull request adds new functionality, it includes unit tests that cover the changes~~
- ~~If this pull request removes docs files, it includes redirect settings in `mint.json`.~~
- ~~If this pull request adds functions or classes, it includes helpful docstrings.~~

Remove extra backtick in deployment docs

---

src/prefect/concurrency/asyncio.py
src/prefect/concurrency/sync.py
tests/concurrency/test_concurrency_asyncio.py
tests/concurrency/test_concurrency_sync.py

If a user calls `concurrency()` or `rate_limit()` and passes a None value or an empty collection, return early to avoid making unnecessary API requests.
Fixes #14786 

Return early from concurrency() and rate_limit() without limit names

---

src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/tests/test_worker.py

Removes await from `load_incluster_config` and refactors the way the config is mocked as not all config functions are not async.
closes #14799 
- [ x ] This pull request references any related issue by including "closes `<link to issue>`"
- [ x  ] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ x ] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ x ] If this pull request adds functions or classes, it includes helpful docstrings.

refactors how cluster_config is implemented

---

docs/3.0rc/manage/settings-and-profiles.mdx
src/prefect/cli/profile.py
src/prefect/context.py
src/prefect/profiles.toml
tests/cli/test_cloud.py
tests/cli/test_config.py
tests/cli/test_profile.py
tests/test_context.py
tests/test_settings.py

following up on some feedback that came in after https://github.com/PrefectHQ/prefect/pull/14749 was merged
this PR:
- removes `default` as the "default" profile, in favor of `ephemeral`
- shows changes to be made to the user before confirming the write to `PREFECT_PROFILES_PATH`
- updates some missed `orion` -> `server` variable names
- updates tests according to changes
---
- its prohibitively complex to intersperse toml with comments in a way that can be preserved between parses. there's a library [here](https://github.com/python-poetry/tomlkit) for that, but not sure its worth the squeeze
- [unfortunately](https://github.com/toml-lang/toml/issues/30#issuecomment-14003959) there is no concept of a `None / nil` in toml, and I'm not a huge fan of setting dummy "english" as values of real …

Follow up on `prefect profile populate-defaults`

---

src/integrations/prefect-gcp/prefect_gcp/workers/vertex.py
src/integrations/prefect-gcp/tests/test_vertex_worker.py

There's a mismatch between the Vertex AI job configuration and the expected shape of the Vertex AI API call for service accounts. This PR ensures that the provided service account name is correctly propagated.
2.x fix for https://github.com/PrefectHQ/prefect/issues/14742

Fix setting of service account on Vertex AI jobs

---

src/prefect/client/base.py
src/prefect/client/orchestration.py

after #14722, `PrefectHttpxSyncEphemeralClient` is no longer needed and was causing issues since it was indiscriminately being passed a `str` that was expected to be an app instance. This will fix errors when running sync tasks or flows against an ephemeral subprocess server.

Remove `PrefectHttpxSyncEphemeralClient`

---

docs/3.0rc/api-ref/rest-api/server/schema.json
src/prefect/server/api/flow_runs.py
src/prefect/server/api/server.py
tests/server/api/test_server.py
tests/server/orchestration/api/test_flow_runs.py

Renaming this endpoint to make it more generic the keep open the possibility of downloading flow run logs in other formats.

Rename the `/download-logs/csv` endpoint to `/logs/download`

---

src/prefect/cli/deploy.py
src/prefect/flows.py
src/prefect/utilities/callables.py
src/prefect/utilities/importtools.py
tests/cli/test_deploy.py
tests/test-projects/wrapped-flow-project/flow.py
tests/test-projects/wrapped-flow-project/missing_imports.py
tests/test-projects/wrapped-flow-project/utils.py
tests/test_flows.py

This PR alters how the client loads a flow from source code when dependencies are missing. Previously, the client would attempt to retrieve flow metadata from the @flow decorator and generate a parameter schema for the decorated function by traversing the abstract syntax tree (AST). This approach prevents the use of custom decorators that wrap the @flow decorator.
This PR instead adds a safe_load_flow_from_entrypoint function which is capable of loading the full flow after making modifications to the AST. safe_load_flow_from_entrypoint will use safe_load_namespace to avoid raising exceptions when dependencies are not present on the current machine when loading a flow. If the flow depends on types or objects from missing dependencies, the AST will be updated to remove the annotations, …

Add support for custom flow decorators to `prefect deploy`

---

src/prefect/events/clients.py

Several metrics were considered for optimizing the checkpointing process, including checkpoint frequency, memory usage, data loss risk, and overall system performance impact. After careful consideration, checkpoint overhead was chosen as the focus, specifically aiming to keep it at 1% of total processing time.
This metric was selected because it effectively balances performance and data safety while scaling well with varying event rates. It provides a consistent measure of efficiency that's easily quantifiable and adjustable. By focusing on overhead, memory usage is indirectly optimized and data loss risk is minimized through timely checkpoints. This approach also allows for clear performance budgeting, reserving 99% of system time for core operations.
The decision was informed by …

Optimize value of `checkpoint_every`

---

src/prefect/events/clients.py
src/prefect/events/utilities.py
tests/events/client/test_events_client.py
tests/events/client/test_events_subscriber.py

This PR updates `get_events_client` and `get_events_subscriber` to start a subprocess server when necessary and allowed. This enables users to use the events subscriber with an ephemeral server, which wasn't previously allowed.
Note that running a persistent server when emitting and consuming events is still recommended. Running the event producer and the event subscriber in different processes will result in two subprocess servers running with different in-memory event queues. In this case, the event subscriber will not receive events from the event producer.
Related to https://github.com/PrefectHQ/prefect/issues/14716

Allow starting an ephemeral server when emitting or subscribing to events

---

src/prefect/profiles.toml
src/prefect/server/api/server.py
src/prefect/server/database/alembic_commands.py
src/prefect/server/database/configurations.py
src/prefect/server/database/interface.py
tests/cli/test_profile.py
tests/server/api/test_server.py

This PR adds a `test` profile to the default set of profiles that uses an ephemeral server and an ephemeral DB by default. Using this profile in its default form will prevent data persistence and can be used to test functionality without persisting data in other environments. Users can update this profile to match their test environment (e.g. a local server or a dev Prefect Cloud workspace).
Related to https://github.com/PrefectHQ/prefect/issues/14716

Add `test` profile to default profiles

---

src/prefect/task_engine.py
tests/deployment/test_flow_runs.py

When using client side task run orchestration, make sure to link states to result when going to a new state. Currently this functionality is buried inside of `propose_state`. This elevates it into the client side orchestration portion of the `set_state` methods of the sync and async task engines.

Client side task run orchestration - link states to results

---

docs/3.0rc/resources/upgrade-prefect-3.mdx
requirements-client.txt
src/prefect/_internal/compatibility/deprecated.py
src/prefect/futures.py
src/prefect/tasks.py
src/prefect/utilities/asyncutils.py
tests/public/flows/test_previously_awaited_methods.py

after making `Task` methods (`submit` / `map`) and `PrefectFuture` methods (`result` / `wait`) sync during the engine rewrite, we later [used `wrapt`](https://github.com/PrefectHQ/prefect/pull/14197) to try and mitigate issues migrating from prefect 2 behavior (implicit dual sync/async via `sync_compatible`) by imbuing objects returned from these formerly async methods with an `__await__` method that we could use to log a warning, but permit the incorrect `await`.
There are several odd edge cases that have come up from returning a `wrapt.ObjectProxy`, most recently https://github.com/PrefectHQ/prefect/issues/14832, where `join` looks at `type` of the object instead of `isinstance` (`wrapt` correctly represents the object with `isinstance` but not `type`).
**This PR removes `wrapt` …

Remove `wrapt` and fail on incorrect `await` usage

---

src/prefect/flows.py

just an aesthetic / QoL thing, make the traceback cleaner when we simply Ctrl-C a `serve` process
<details>
<summary>Before</summary>
```python
» python repros/14779.py
Your flow 'foo' is being served and polling for scheduled runs!
To trigger a run for this flow, use the following command:
$ prefect deployment run 'foo/foo'
You can also run your flow via the Prefect UI: https://app.prefect.cloud/account/9b649228-0419-40e1-9e0d-44954b5c0ab6/workspace/e49488be-6d30-4980-94b2-a82a5edbb19c/deployments/deployment/ec27d398-ce67-4ca7-a7c4-b6bcdd4853c4
^C11:18:50.646 | INFO    | prefect.runner - Pausing all deployments...
11:18:50.823 | INFO    | prefect.runner - All deployments have been paused!
File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.fr …
```

Cleaner exit when Ctrl-C'ing `Flow.serve`

---

src/prefect/task_engine.py
src/prefect/tasks.py
src/prefect/utilities/engine.py
tests/events/client/instrumentation/test_task_run_state_change_events.py

Previously the only way a `task-run.Scheduled` event appears to be something like this:
- task run gets created via apply async
- worker gets the run, sets state to pending and emits `SCHEDULED` -> `PENDING` event
- worker would open the engine context and inside of the engine a `None` -> `SCHEDULED` event would be [emitted](https://github.com/PrefectHQ/prefect/blob/4a7424d9ced3477ec21839c2f41413bed9d3ef74/src/prefect/task_engine.py#L705-L710) 
This does not seem intentional and is certainly unintuitive. However I think we do want to keep `task-run.Scheduled` events as they are useful. This PR makes the following updates:
- Only emit an initial task run event in the engine if we're creating a new run (this is the classic `PENDING` event)
- Actually emit a `SCHEDULED` event inside of …

fix `task-run.Scheduled` event emission

---

.github/workflows/python-tests.yaml
tests/client/test_prefect_client.py
tests/test_import_interceptor.py

This PR fixes the client side pytest workflow to use the `--ignore` flag correctly. Since upgrading to `pytest>8`, only the `test/events/server` module has been running. An example of the current behavior can be seen [here](https://github.com/PrefectHQ/prefect/actions/runs/10253505240/job/28366270121).

Fix syntax for client test suite `pytest` command

---

src/prefect/server/api/server.py
src/prefect/testing/utilities.py
tests/testing/test_utilites.py

Adds a explicit drain of the `APILogWorker` before stopping the server started by the `prefect_test_harness` to ensure no connection errors are printed upon exit.
Closes https://github.com/PrefectHQ/prefect/issues/14845

Flush logs when exiting `prefect_test_harness` to avoid error logs

---

src/prefect/task_worker.py
src/prefect/testing/fixtures.py
tests/events/client/instrumentation/test_task_run_state_change_events.py

This PR updates `test_task_run_state_change_events.py` to pass with client side orchestration enabled. There are a couple of differences between the task runs contained in the event payload when client side orchestration is enabled vs disabled. 
With client side orchestration enabled, the engine's copy of the task run is updated directly _before_ we emit a task run event. This means the copy of the task run inside of the event payload will include updated fields like start time, run count, etc. Things that previously were not included until the engine re-read the task run from the server as part of it's main loop.

update task run event tests for client side orchestration

---

src/prefect/context.py
tests/test_context.py

This PR enables the submission and mapping of tasks from tasks that themselves were submitted to Ray or Dask. This is achieved by starting the task runner when hydrating a flow run context in a remote environment.
Closes https://github.com/PrefectHQ/prefect/issues/14788

Enable tasks to be submitted and mapped from tasks submitted to Dask or Ray

---

requirements-client.txt
requirements.txt

This PR moves the `exceptiongroup` dependency from `requirements.txt` to `requirements-client.txt` to ensure the `exceptiongroup` module is available when installing `prefect-client`. `exceptiongroup` is listed in `requirements-client.txt` on `main`, so I think this only affects `2.x` versions of `prefect-client`.
Closes #14870 

Move `exceptiongroup` to `requirements-client.txt`

---

src/integrations/prefect-dbt/prefect_dbt/cli/commands.py
src/integrations/prefect-dbt/tests/cli/test_commands.py

If the profiles directory is misspecified but overwrite_profiles is false, it will also raise this error.

prefect-dbt - Clarify missing profile error

---

src/prefect/cli/deploy.py
tests/cli/test_deploy.py

currently on `main`, providing a `null` for `schedules` (which you should be able to use to avoid the prompt specifically about schedules) in `prefect.yaml` raises the following unfriendly error
```python
File "/Users/nate/github.com/prefecthq/flows/.venv/lib/python3.12/site-packages/prefect/cli/deploy.py", line 424, in deploy
await _run_single_deploy(
...
File "/Users/nate/github.com/prefecthq/flows/.venv/lib/python3.12/site-packages/prefect/cli/deploy.py", line 1527, in _apply_cli_options_to_deploy_config
for schedule_config in deploy_config.get("schedules", []):
TypeError: 'NoneType' object is not iterable
```

Allow `schedules: null` in `prefect.yaml`

---

src/prefect/task_engine.py

I fixed a typo that had `say_hello.submit(name="Marvin)` instead of `say_hello.submit(name="Marvin")`.
Edit: I also fixed a `print` statement that was written in Python 2 format, not Python 3.

Typo fix: `say_hello.submit(name="Marvin)`

---

src/prefect/settings.py
tests/test_settings.py

This PR fixes errors raised when a database password contains a `$` character by using `safe_substitute` when templating. Templating will not occur when a `$` character is present in the password, which means that errors may still occur with settings like the following:
```bash
PREFECT_API_DATABASE_NAME="the-database"
PREFECT_API_DATABASE_CONNECTION_URL="postgresql+asyncpg://the-user:the-$password@localhost:5432/${PREFECT_API_DATABASE_NAME}"
```
Since this setup would fail without these changes, and the docs recommend setting `PREFECT_API_DATABASE_CONNECTION_URL` directly, I think this behavior is acceptable.
Closes https://github.com/PrefectHQ/prefect/issues/11067 …

Avoid raising errors on database passwords that contain a `$` character

---

docs/3.0rc/develop/task-runners.mdx

tweak the examples
- make it more obvious how to get the actual results out
- encourage use of `unmapped` in the flow definition as opposed to wrapping the parameter value provided at runtime, since otherwise I'd argue the `static_iterable` variable name is misleading (this is generally how I think we should recommend the use of `unmapped` anyways

tweak task runner docs

---

.github/CODEOWNERS

Without this, it appears that the CODEONWER hierarchy assumes more specific owners are required over and above global owners, so this adds @desertaxle @zzstoatzz and myself to those specific subgroups as well.

Ensure global codeowner reviews are accepted for specific files

---

src/prefect/task_engine.py
src/prefect/transactions.py

Currently we have two places that contain the logic for executing a transaction lifecycle hook. This PR consolidates that logic into the `Transaction` class.  Putting it on the class will be necessary to allow for users to reference stateful data in their hooks.

Consolidate where transaction hooks are run

---

src/prefect/transactions.py
tests/test_flows.py
tests/test_transactions.py

Right now, users must hard code any state that needs to be shared between a task and its transaction lifecycle hooks (`on_commit` and `on_rollback`).  This PR exposes a simple `get` / `set` mechanic for persisting arbitrary data to a task's transaction:
```python
from prefect.transactions import get_transaction
@task
def main_task(fpath: str):
with open(fpath, "w') as f:
f.write("hello")
get_transaction().set("fpath", fpath)
@main_task.on_rollback
def hook(txn):
fpath = txn.get("fpath")
os.unlink(fpath)
```
I explored more magical ways of exposing this interface as well, such as by auto-injecting data into hook keyword arguments, but I thought starting simple and seeing what patterns emerge was a safer plan of action.

Sharing state with transaction hooks

---

src/prefect/flows.py

This PR introduces a very small change to the logic in `prefect.flows.Flow.serialize_parameters` that will check to see if the parameter is a `PrefectFuture` or `State`, and if it is, it will automatically assume that it is not serializable.
I also fixed the grammar of a debug statement.
Previously, this was done by calling the following block of code:
https://github.com/PrefectHQ/prefect/blob/aad6693608aeb2dbe71dfcf8dde2e48a45e30942/src/prefect/flows.py#L614-L622
In the code above, `jsonable_encoder(value)` in turn calls `dict(PrefectFuture)` or `dict(State)`. That will correctly raise an exception and mark the `value` as unserializable. Nonetheless, I am proposing this PR as a way to address https://github.com/PrefectHQ/prefect/discussions/14881. It would be really convenient to allow …

Avoid `__getitem__` calls on a `PrefectFuture` or `State` in checking `Flow` parameter serialization

---

src/prefect/cli/server.py

closes https://github.com/PrefectHQ/prefect/issues/14906
we were checking truthyness of the function itself, which is not what we want

correctly call `is_interactive` function during server preflight check

---

src/prefect/transactions.py
tests/test_transactions.py

This PR allows users to provide default values for `transaction.get` in the case that a value wasn't set; this allows for code that is more graceful / easier to test in isolation without having to resort to `try/except` patterns.
Basic usage:
```python
with transaction() as txn:
assert txn.get("unknown", 42) == 42
```

Allow for defaults on txn.get

---

src/prefect/transactions.py
tests/test_transactions.py

This PR adds one line that ensures child/nested transactions inherit data from their parents, which they can then safely override.  The primary use case for such a thing is to allow for patterns such as:
```python
@flow 
def my_flow():
with transaction() as txn:
txn.set("global_state", value)
task_one()
task_two()
```
And now `task_one` and `task_two` can define commit/rollback hooks that look for `"global_state"` without having to individually set the value within their respective definitions.

Transactions should inherit data from their parents

---

src/prefect/blocks/core.py
src/prefect/cache_policies.py
tests/test_cache_policies.py

this PR handles an error (`OSError: could not get source code`) that occurs in `TaskSource(CachePolicy)` if you try to run a task in the native python repl
in that case or any other time we cannot `inspect.getsource`, we fall back to hashing the `__code__` object on `Task.fn`
<details>
<summary>repro on main</summary>
```python
>>> import prefect
>>> @prefect.task
... def f(): pass
...
>>> f()
22:40:56.454 | INFO    | Task run 'f' - Created task run 'f' for task 'f'
22:40:56.741 | ERROR   | Task run 'f' - Task run failed with exception: OSError('could not get source code') - Retries are exhausted
File "/Users/nate/github.com/prefecthq/prefect/src/prefect/task_engine.py", line 804, in run_context
yield self
File …
```

fallback `TaskSource` key computation if no source code

---

src/prefect/task_engine.py
src/prefect/tasks.py
tests/test_tasks.py

Updates the `test_task.py` test suite to be compatible with client side task run orchestration. This is the final test suite that needed updates in order to make the flag the default.

enable cstro in `test_tasks.py`

---

tests/test_flow_engine.py
tests/test_task_engine.py

Fixes flaky log tests by updating them to search for the expected record by message instead of assuming the expected log will always be the first record.
Closes https://github.com/PrefectHQ/prefect/issues/14892

Fix flaky log tests

---

src/prefect/workers/base.py
tests/workers/test_base_worker.py

Closes #11041 
This PR more gracefully merges flow run overrides with deployment overrides, specifically allowing for first-order deep merging of dictionaries.  The most prominent use case for this would be things like overriding one and only one environment variable on a per-run basis (e.g., a git branch) - it would be unreasonable to expect flow-run creators to maintain a duplicate copy of all the environment variables set on the deployment.
Note that this change will also affect any other dictionary field present on a deployment job variable.  If for some reason that is an issue, we can scope this change to environment variables only.

First order deep merge of flow run overrides with deployment overrides

---

src/prefect/cli/work_pool.py

Produce correct error message when work pool name doesn't exist
Currently when you run `prefect work-pool update ... my-work-pool` and the work pool doesn't exist you do not receive the correct message code.
The following is currently returned:
```bash
Work pool named {name!r} does not exist.
```
The expected result is:
```bash
Work pool named my-work-pool does not exist.
```

Fix error code when work pool name not found

---

docs/3.0rc/api-ref/rest-api/server/schema.json
src/prefect/server/schemas/filters.py
tests/server/models/test_logs.py

Allows clients to retrieve only flow run-level logs that pertain to a given flow run and not those of nested task runs.

Add is_null_ filter to logs filter endpoint

---

src/prefect/cli/block.py
tests/cli/test_block.py

updates the `prefect block register` command to more clearly show when we're not finding any blocks to register
updates some tests that were passing because they checked for this boilerplate but weren't actually registering blocks
previously
```
» prefect block register -m prefect
Successfully registered 0 blocks
┏━━━━━━━━━━━━━━━━━━━┓
┃ Registered Blocks ┃
┡━━━━━━━━━━━━━━━━━━━┩
└───────────────────┘
To configure the newly registered blocks, go to the Blocks page in the Prefect UI: http://127.0.0.1:4200/blocks/catalog
```
now
```
» prefect block register -m prefect
No blocks were registered from module 'prefect'.
Please make sure the module 'prefect' contains valid blocks.
```

clearer message upon no-op `prefect block register`

---

src/prefect/server/models/block_documents.py
src/prefect/server/schemas/core.py

`obfuscate` is just a more general form of `obfuscate_string` that will behave in the same way and paves the way for other secret block types being masked by the API

use `obfuscate` instead of `obfuscate_string`

---

src/prefect/tasks.py
src/prefect/utilities/engine.py
tests/events/client/instrumentation/test_task_run_state_change_events.py

Creating this PR to merge this change to main ahead of https://github.com/PrefectHQ/prefect/pull/14944, which was dependent on enabling client side orchestration by default

let dynamic key be more dynamic for client side task run orchestration

---

requirements-client.txt

It [appears](https://github.com/PrefectHQ/prefect/pull/14947) this is no longer necessary as the original issue was related to Python 3.8 - closes https://github.com/PrefectHQ/prefect/issues/12265

Remove importlib-resources as an explicit requirement

---

src/prefect/cli/work_pool.py
src/prefect/client/orchestration.py
tests/cli/test_work_pool.py
tests/client/test_prefect_client.py

closes https://github.com/PrefectHQ/prefect/issues/14961
allows "create or update" of work pool via a new `overwrite: bool` flag you may pass to `client.create_work_pool`
we `exclude` the fields `name` and `type` from the create action schema when calling `update_work_pool`, warning that we may not `overwrite` the `type` of a work pool once it's been created
---
makes a corresponding change to `prefect work-pool create`
```python
» prefect work-pool ls
Work Pools
┏━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Name  ┃ Type       ┃                                   ID ┃ Concurrency Limit ┃
┡━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ asdf  │ kubernetes │ 1ff6da22-f38b-4d29-b1a9-1e41bb6f5a1e │ None              │
│ …
```

allow overwrite in `create_work_pool`

---

src/prefect/_internal/concurrency/services.py
src/prefect/task_engine.py

Log a message while items are still draining out of the `QueueService`. This is particularly important for UX of client side task run orchestration. Consider this example:
```python
@task
def add_one(n):
return n + 1
@flow
def add_flow():
futures = [add_one.submit(i) for i in range(1000)]
for future in futures:
future.result()
if __name__ == '__main__':
add_flow()
```
1000 tasks will all finish at roughly the same time and generate 1000 events. The flow will finish and it will look like the process is hanging to the user. In reality we still need to churn through those 1000 events. This PR adds the following logging when the service begins to drain.
```
$ python add_flow.py
13:59:37.814 | INFO    | prefect.engine - Created flow run 'witty-aardwolf' for flow …
```

log message while events are still draining

---

src/prefect/events/clients.py
src/prefect/events/utilities.py
src/prefect/server/api/server.py
src/prefect/testing/fixtures.py
tests/conftest.py
tests/events/client/test_events_related_from_context.py
tests/test_logging.py
tests/test_task_runs.py

This PR disables the `TaskRunRecorder` service when running the hosted api during tests. This is consistent with our other services that are disabled during tests. While it was enabled it was leading to deadlocks during test setup, while it was trying to insert things from the last test, and the next test was trying to do it's setup.
It also introduces the `AssertingPrefectEventsClient`. This client both emits the event to the server (which is configured to do nothing with it but distribute it to connected websockets) AND stashes a copy of the event on the client. The existing `AssertingEventsClient` and `events_pipeline`, would _catch_ events from being sent to the server and then we would do things with them like run the `task_run_recorder` manually. 
This lets us satisfy tests around …

disable task run recorder in tests

---

src/prefect/context.py
src/prefect/records/base.py
src/prefect/records/memory.py
src/prefect/records/result_store.py
src/prefect/transactions.py
tests/records/test_memory.py
tests/test_transactions.py

This PR adds the ability to configure the isolation level for a transaction. The isolation level will default to `READ_COMMITTED`, and the available isolation level will be determined by the `RecordStore` implementation used with the transaction. The new `MemoryRecordStore` supports the `SERIALIZABLE` isolation level and is used to test the addition of locking logic to the `Transaction` class.
I also updated the `RecordStore` to have abstract methods to clarify which methods must be included in a `RecordStore` implementation and which are optional. I also updated the `ResultFactoryStore` to adhere to the updated interface.
Related to https://github.com/PrefectHQ/prefect/issues/14914 …

Add ability to configure isolation level for a transaction

---

docs/3.0rc/api-ref/rest-api/server/schema.json
src/integrations/prefect-redis/prefect_redis/records.py
src/integrations/prefect-redis/prefect_redis/redis.py
src/integrations/prefect-redis/pyproject.toml
src/integrations/prefect-redis/tests/conftest.py
src/integrations/prefect-redis/tests/test_records.py
src/integrations/prefect-redis/tests/test_tasks.py
src/prefect/context.py
src/prefect/records/base.py
src/prefect/records/memory.py
src/prefect/records/result_store.py
src/prefect/results.py
src/prefect/settings.py
src/prefect/transactions.py
tests/records/test_memory.py
tests/test_transactions.py

This PR introduces a `RecordStore` implementation that uses a Redis DB to store transaction records and handle locking. This implementation allows for serializable workflow transactions in a distributed environment. 
This PR introduces settings to configure the Redis server used for a `RedisRecordStore`. Ideally, I'd like to be able to house those settings in `prefect-redis`, but there isn't a mechanism for declaring settings in integrations packages. If moving these settings to `prefect-redis` sounds like a good idea, I can create an issue to allow loading settings from integrations packages and move the settings added in this PR.
Related to https://github.com/PrefectHQ/prefect/issues/14914 …

Add `RedisRecordStore`

---

docs/3.0rc/api-ref/rest-api/server/schema.json
src/prefect/server/database/migrations/versions/postgresql/2024_04_03_112409_aeea5ee6f070_automations_models.py
src/prefect/server/database/migrations/versions/sqlite/2024_04_03_111618_07ed05dfd4ec_automations_models.py
src/prefect/server/database/orm_models.py
src/prefect/server/events/actions.py
src/prefect/server/events/schemas/automations.py
src/prefect/server/events/triggers.py
tests/events/server/actions/test_calling_webhook.py
tests/events/server/schemas/test_automations.py

During some internal testing of Prefect, we noticed a surprising bug, where
we could not create server-side automations that included composite triggers.
This was due to Pydantic parsing the server-side `CompositeTrigger.triggers` as
_client-side_ `EventTrigger`s, which don't include some of the necessary
server-side implementation.
I was unable to reproduce the problem in a unit test (if this were happening
during unit tests, many tests would fail), but I was able to reproduce it in
a simple standalone script using the same test code.  This is hinting to
import ordering as part of the problem.
```
File "/home/chris/src/github.com/PrefectHQ/prefect/repro.py", line 92, in <module>
test_server_composite_triggers_validate_to_server_triggers()
File …
```

Ensures that server automations schemas are parsed with only server models

---

requirements-client.txt
src/prefect/blocks/core.py
src/prefect/utilities/callables.py

Updates our requirements and code to be compatible with `griffe 1.0`.
Closes #14975

Unbound griffe to 2.0

---

.github/labeler.yml

This PR adds two more auto-labeling rules:
- label any change to our `requirements*.txt` files with `upstream dependency`: this should help us audit changes for our [conda-forge feedstock](https://github.com/conda-forge/prefect-feedstock) (we routinely miss requirement updates over there)
- label any PR to `2.x` with `2.x` so we can quickly see the affected version lineage

Add a few more label rules to help keep things organized

---

requirements.txt

Given a few dependency issues that we've had, I think we should upper bound major version changes for packages that use semantic versioning. This will allow us to be more intentional about major version change support while accepting all minor versions along the way by default.
This PR will also serve as a test of #15000

Add some missing upper bounds to requirements

---

README.md

Fixes the markdown link to the Slack community, which should have a bracket instead of a curly brace.

README: fix link to Slack community

---

src/prefect/cli/deploy.py
tests/cli/test_deploy.py

Adds a `-cl` and `--concurrency-limit` to the CLI's `deploy` function in order to add concurrency limit field when creating deployments from the CLI.
Related: #14934 
Example:
```bash
prefect deploy hello.py:my_flow -n test-name -p test-pool --concurrency-limit 42
```

Adds concurrency limit options to `prefect deploy`  

---

src/prefect/runner/runner.py
src/prefect/utilities/processutils.py
tests/runner/test_runner.py

This PR ensures that the Python executable path used by the `Runner` when starting a flow run is quoted to avoid issues with spaces.I tested on a Windows setup via Parallels
Closes https://github.com/PrefectHQ/prefect/issues/15014

Ensure Python executable is quoted in runner command on Windows

---

.github/workflows/integration-tests.yaml
src/prefect/cli/server.py
tests/cli/test_start_server.py

Adds a `--background` (or `-b`) flag to `prefect server start` to allow running a server in a background process. A server started with `--background` can be stopped with `prefect server stop`.
When starting a background server, a `server.pid` file is written to the `PREFECT_HOME` directory with the process ID of the background server. This lets `prefect server stop` know which process to interrupt. Currently, only one background server can be started at a time. Allowing more simultaneous background servers will likely require an update to `prefect server stop`.
Closes https://github.com/PrefectHQ/prefect/issues/6989

Adds the ability to run a server in the background

---

src/prefect/blocks/core.py
tests/blocks/test_core.py

Closes #15009 
This PR proposes modification of `prefect.blocks.core.Block.register_type_and_schema()` to registers nested block types in its field annotations. Nested block types are searched only in Dict, List, Tuple and Union types.
Additionally `prefect.blocks.core._collect_secret_fields()` has been updated to collect secret fields in nested types as well as `prefect.blocks.core.schema_extra()` for block schemas. 
Small fix applied to `prefect.blocks.core._is_subclass()` to check if passed `cls` is parametrized type using `typing.get_origin()`. Without this, `inspect.isclass()` returns True for parametrized types for python<=3.11 and this results in `TypeError` raised by `issubclass()`.
This implementation also fixes any race conditions when registering Blocks with CLI, as shown in …

Add Block Type registration for its nested block types in field annotations

---

docs/3.0rc/api-ref/rest-api/server/concurrency-limits/decrement-concurrency-limits-v1.mdx
docs/3.0rc/api-ref/rest-api/server/concurrency-limits/increment-concurrency-limits-v1.mdx
docs/3.0rc/api-ref/rest-api/server/schema.json
docs/mint.json
src/prefect/server/api/concurrency_limits.py
tests/server/orchestration/api/test_concurrency_limits.py

In support of client-side task run orchestration, we need to expose these two
endpoints so that clients may acquire and release tag-based concurrency limits
for the task runs they are orchestrating.
The design of this API is intended to be closer to V2 concurrency terminology,
hence the `increment`/`decrement` paths and the `names` parameter.

Adds acquire/release endpoints for task run concurrency limits

---

docs/3.0rc/api-ref/rest-api/server/schema.json
src/integrations/prefect-redis/prefect_redis/records.py
src/integrations/prefect-redis/tests/test_records.py
src/prefect/settings.py

This PR removes the `PREFECT_RECORD_STORE_REDIS_` settings. After the exploration in https://github.com/PrefectHQ/prefect/pull/14987, I think that a more hierarchical structure for settings will be more ergonomic. The `RedisRecordStore` will be fully configurable via code and we'll introduce a more ergonomic way to configure defaults across environments once the settings mechanics can support it.

Remove Redis record store settings

---

docs/3.0rc/api-ref/rest-api/server/schema.json
src/prefect/client/orchestration.py
src/prefect/client/schemas/responses.py
src/prefect/concurrency/asyncio.py
src/prefect/concurrency/events.py
src/prefect/concurrency/services.py
src/prefect/concurrency/sync.py
src/prefect/server/api/clients.py
src/prefect/server/api/concurrency_limits_v2.py
src/prefect/server/events/actions.py
src/prefect/server/models/concurrency_limits_v2.py
src/prefect/server/schemas/actions.py
src/prefect/server/schemas/responses.py
tests/concurrency/test_acquire_concurrency_slots.py
tests/concurrency/test_concurrency_asyncio.py
tests/concurrency/test_concurrency_slot_acquisition_service.py
tests/concurrency/test_concurrency_sync.py
tests/concurrency/test_release_concurrency_slots.py
tests/events/server/actions/test_jinja_templated_action.py
tests/server/models/test_concurrency_limits_v2.py
tests/server/orchestration/api/test_concurrency_limits_v2.py
tests/test_task_engine.py

This reverts commit 4da5da207b126639998917cb1e246f7b15484405 in favor of a different approach.

Revert "Add optional "holder" semantics to global concurrency limits

---

src/prefect/_internal/schemas/bases.py
src/prefect/server/utilities/schemas/bases.py

Adding `defer_build=True` may have contributed to FastAPI server-specific test instability in Python 3.12. Here, we also set `experimental_defer_build_mode`, which the [Pydantic docs](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.defer_build) suggest is needed to use `defer_build=True` with FastAPI.

Test `experimental_defer_build_mode` with `defer_build=True`

---

src/prefect/results.py
src/prefect/testing/utilities.py
tests/results/test_flow_results.py
tests/results/test_persisted_result.py
tests/results/test_state_result.py
tests/test_flows.py

This PR is the next stage in the ongoing results refactor. This PR replaces `PersistedResultBlob` with `ResultRecord`. `ResultRecord` contains much of the same information that `PersistedResultBlob` had, but it is constructed such that separating the result from its metadata and then recombining it is easier. The `ResultRecord` also encapsulates serialization and deserialization so that other actors can directly interact with the result value.
The separation of result and metadata will allow users to opt in to persisting raw results which can be used apart from Prefect.

Replace `PersistedResultBlob` with `ResultRecord`

---

src/prefect/server/utilities/schemas/bases.py

Deferring model builds on the server side appear to cause issues when a server is restarted. Deferring builds of our server-side models doesn't affect import time, so this PR reverts the deferring of server-side builds.
Closes https://github.com/PrefectHQ/prefect/issues/15067

Revert change to defer building the server-side version of `PrefectBaseModel`

---

src/prefect/blocks/core.py
src/prefect/blocks/system.py
src/prefect/client/orchestration.py
src/prefect/client/schemas/objects.py
tests/blocks/test_system.py

this PR closes #14899 by allowing any `JSON` value (i.e. strings, lists, dictionaries) to be stored as a secret
<details>
<summary>examples</summary>
```python
In [2]: Secret.load('test').get()
Out[2]: [1, 2, 3]
In [3]: type(_)
Out[3]: list
```
```python
from pydantic import Secret as PydanticSecret
from prefect.blocks.system import Secret
Secret(value={"key": "value"}).save("secret-block", overwrite=True)
secret_block = Secret.load("secret-block")
assert secret_block.get() == {"key": "value"}
assert secret_block.value == PydanticSecret[dict]({"key": "value"})
```
</details>
---
this PR should _not_ change any behavior for current users of `Secret`, including [this outstanding issue](https://github.com/PrefectHQ/prefect/issues/6949) about stripping newlines

allow JSON values in `Secret` block

---

src/prefect/exceptions.py
src/prefect/results.py
src/prefect/states.py
src/prefect/task_engine.py
src/prefect/transactions.py
tests/results/test_state_result.py
tests/test_tasks.py

This PR updates the transaction context manager to log a warning when result serialization fails instead of a big traceback. This PR also avoids logging when the default rollback hook that updates the tasks state runs.
Very open to changing the verbiage of the warning message.
```
15:42:51.769 | WARNING | Task run 'create_db_and_cur-5c1' - Encountered an error while serializing result for transaction '159ef706744b2d7edd395d9458f3d2ec': Failed to serialize object of type 'tuple' with serializer 'pickle'. You can try a different serializer (e.g. result_serializer="json") or disabling persistence (persist_result=False) for this flow or task. Code execution will continue, but the transaction will not be committed.
``` …

Improve logging on result serialization errors

---

src/prefect/server/services/task_run_recorder.py
tests/server/services/test_task_run_recorder.py

This PR adds a periodic task to the `task-run-recorder` consumer to periodically process lost follower task run events where we never see an expected preceding event. This is similar to how these orphans are dealt with in the triggers service.

record task run followers

---

src/prefect/cli/dashboard.py
tests/cli/test_dashboard.py

though it still worked, we got an ugly trace in the terminal after `prefect dashboard open` when against an oss server since we raise `CloudUnauthorizedError` upon bad status calling `/me/workspaces`

Fix `CloudUnauthorized` case in `prefect dashboard open`

---

src/prefect/concurrency/asyncio.py
src/prefect/concurrency/sync.py

`create_if_missing=None` has no meaning in this context, so it should be `bool` not `Optional[bool]` and updates docstring

fix typing and docstring for `concurrency` ctx managers

---

src/prefect/main.py
src/prefect/utilities/dispatch.py

This PR updates `.model_rebuild` calls in `main.py` to explicitly pass namespace types. Version `2.9.0b1` of `pydantic` no longer implicitly loads the parent namespace when rebuilding models and this approach was suggested [here](https://github.com/pydantic/pydantic/pull/10113#issuecomment-2314573655). This update will ensure `prefect` doesn't break when version `2.9.0` of `pydantic` is released.
Closes https://github.com/PrefectHQ/prefect/issues/15112
Closes https://github.com/PrefectHQ/prefect/issues/15092

Update `model_rebuild` in `main.py` to explicitly pass namespace types

---

src/prefect/cli/server.py
tests/cli/test_start_server.py

This PR updates the `prefect server start` command to consider existing profiles when checking if the client is set up to communicate with the started server. If a profile with a matching `PREFECT_API_URL` exists, that profile will automatically be made active. 
In the default case, new users will automatically switch to the `local` profile when they start a local server for the first time.
If there are multiple valid profiles, the user is prompted to choose between them.
Users can skip all prompts with `prefect --no-prompt server start`.

Switch to profile with matching `PREFECT_API_URL` on server start

---

src/prefect/engine.py
tests/test_flows.py

backports #15109 
closes #15107

[2.x] ensure `on_failure` hook runs upon parameter validation error

---

ui/tailwind.config.ts

Make the import specific to the `src` and limits it to `.vue` files.

Fix tailwind warning about node_modules import 

---

docs/3.0rc/develop/manage-states.mdx
docs/3.0rc/develop/write-flows.mdx
docs/3.0rc/develop/write-tasks.mdx

to
- manage states (fix confusing / odd language describing return values / dont recommend returning futures directly)
- write flows (section on Custom named states, ie Skipped)
- write tasks (remove incorrect mintlify syntax)

some minor docs improvements

---

.github/workflows/docker-images.yaml

This PR makes the following updates, with an eye toward the post-3.0 future:
- stops building docker images with every merge to `main`
- instead, `prefect-dev` images are now populated with every _pre-release_, which for 3.0 occur automatically daily
- the goal would be after 3.0 is not a release candidate, we do automatic daily pre-releases which populates the `prefect-dev` images, and no longer do dev image building with every commit to `main`
Ultimately my hope is this reduces action failure noise and increases the stability / signal of using a `dev` image.

Updates docker image build logic

---

docs/3.0rc/resources/upgrade-to-prefect-3.mdx

on many systems the current recommendation fails like
```bash
» pip install prefect>=3.0.0rc1 --pre
zsh: 3.0.0rc1 not found
» uv pip install prefect>=3.0.0rc1 --pre                                                              1 ↵
zsh: 3.0.0rc1 not found
» pip install 'prefect>=3.0.0rc1' --pre                                                               1 ↵
... (success)
» uv pip install 'prefect>=3.0.0rc1' --pre
Audited 1 package in 18ms
```

fix install command

---

docs/contribute/styles-practices.mdx

rm poorly rendered line in contributing guide

---

docs/3.0rc/resources/upgrade-to-prefect-3.mdx

@cicdw spotted a vestigial reference to "three" items which were expanded into standalone sections of this doc.

Remove reference to "three" changes in upgrade doc

---

src/prefect/client/cloud.py
tests/client/test_cloud_client.py

This PR fixes an edge case in which a first-time user (with no profiles) calls `prefect cloud login`; previously, the lack of `PREFECT_API_URL` would cause a `TypeError` error from `re.search`.  This PR avoids the typing error.

Fixes init of cloud client when no profiles are set

---

docs/guides/global-concurrency-limits.md

Explain the Active Slots field on the edit form for global concurrency limits.
Fixes #13361 
Fixes OSS-5405

Add active slots to concurrency docs

---

docs/3.0rc/get-started/quickstart.mdx

- remove outdated logs in docs (as the current state may be superseded, leaving us in the same place later)
- rename flow in example to avoid shadowing the function name

rm old logs example and fix name

---

src/prefect/cli/profile.py
src/prefect/settings.py
tests/cli/test_profile.py

as in https://github.com/PrefectHQ/prefect/issues/15153, switching `default` -> `ephemeral` can create some confusing situations
there's no strong reason to be special casing any of the profiles anymore, better to document best practices

Rm "default" profile migration

---

src/prefect/client/orchestration.py

The async client has a slightly different call from the sync client for the `create_artifact` route and I observed a 422 go by related to a failure to create an artifact - I think this may be why.

Update sync artifact call to same as async

---

src/integrations/prefect-redis/tests/test_records.py
src/prefect/context.py
src/prefect/flow_engine.py
src/prefect/results.py
src/prefect/task_engine.py
src/prefect/task_worker.py
src/prefect/tasks.py
src/prefect/transactions.py
tests/records/test_filesystem.py
tests/records/test_memory.py
tests/results/test_result_factory.py
tests/results/test_state_result.py
tests/test_background_tasks.py
tests/test_context.py
tests/test_states.py
tests/test_task_engine.py
tests/test_tasks.py
tests/test_transactions.py

This PR refactors `ResultFactory` to no longer depend on flow and task run context. It builds off of what I learned working on #15155 and the feedback given there to decrease the complexity of `ResultFactory`. 
`ResultFactory` instances are created with a standard `__init__`, and the model handles the defaults directly. When a new `ResultFactory` is needed for a new context, the new context should copy the existing `ResultFactory` and make the needed changes on the copy. Some convenience methods, `update_for_flow` and `update_for_task`, have been added for use in the flow and task engines. 
I also added a `get_current_result_factory` utility method to make it easy to get the result factory for a given context. This should be useful when we add more methods to `ResultFactory` for …

Refactor `ResultFactory` to no longer be run context aware

---

src/integrations/prefect-databricks/prefect_databricks/flows.py
src/integrations/prefect-databricks/tests/test_flows.py

restores `job_submission_handler` to `prefect-databricks` pre-built flow `jobs_runs_submit_and_wait_for_completion`
3.x half of https://github.com/PrefectHQ/prefect/issues/15180

restore job submission handler in `jobs_runs_submit_and_wait_for_completion`

---

src/prefect/results.py
src/prefect/testing/utilities.py
tests/blocks/test_notifications.py
tests/results/test_persisted_result.py
tests/results/test_state_result.py

This PR is the next step in the results refactor and adds `read` and `write` methods to `ResultFactory` to move towards the `ResultFactory` (soon to be the `ResultStore`) being the source of truth for reading and writing results. `PersistedResult` has been updated to delegate reads and writes to a `ResultFactory`. I think we'll soon be able to remove `PersistedResult` from the critical path.

Add `read` and `write` methods to `ResultFactory`

---

src/prefect/variables.py
tests/test_variables.py

I'm just now seeing that the variables code is a bit all over the place (e.g., `as_object` for type dispatching, inheriting from a schema object instead of being a standalone class, etc.).
This PR attempts to get in a few minor breaking changes prior to 3.0 going GA for `Variable.get` and `Variable.set`; while it does feel a bit weird that `set -> Variable` and `get -> str`, I think it's justifiable as `set` is effectively `__init__ + create` and `get` is dictionary-semantics for value retrieval.  For users who want to load a full variable object we'll need to introduce `load/aload` methods but I'm comfortable waiting on those for another minor version release.

Touch up variable get and set

---

src/prefect/server/events/triggers.py

closes https://github.com/PrefectHQ/prefect/issues/15170
we should probably review access patterns to improve sqlite performance across the board, but this appears to avoid the errors described in the linked issue

retry on locked errors when getting lost followers

---

src/prefect/blocks/core.py
src/prefect/utilities/callables.py

Closes #15090 
Will backport to 2.x as well

Disable griffe logging entirely when used

---

src/prefect/variables.py

As a matter of best practice I don't think that user-facing objects should inherit from our schemas. This PR updates the  `Variable` class in accordance with this guideline.

Touch up variable class inheritance

---

src/prefect/tasks.py
tests/test_tasks.py

Fixes task key computation under an edge case.
Closes https://github.com/PrefectHQ/prefect/issues/15058
Will backport to 2.x as well

Fix task key comp

---

src/prefect/blocks/core.py
src/prefect/utilities/callables.py

[2.x] Disable griffe logging entirely when used

---

flows/worker.py

This test was disabled while we got the integrations package versions worked out
with `prefect>3`.  Now that `prefect-kubernetes` has 3.0 support, we can use
this test again.

Updates the worker integration tests for post-GA

---

docs/3.0/resources/upgrade-to-prefect-3.mdx

amends https://github.com/PrefectHQ/prefect/pull/15192 since `pip install 'prefect[aws]'` would no op with a 2.x version of prefect and prefect-aws installed

more correct upgrade recommendation

---

src/integrations/prefect-github/prefect_github/repository.py

backports https://github.com/PrefectHQ/prefect/pull/15143
actually closes https://github.com/PrefectHQ/prefect/issues/13180

backport windows quote fix

---

src/integrations/prefect-azure/tests/test_credentials.py

there were a couple failing `isinstance` asserts on objects from different places, and missing `assert` keywords which could have caused silent failures

fix `prefect-azure` tests

---

src/integrations/prefect-kubernetes/prefect_kubernetes/credentials.py
src/integrations/prefect-kubernetes/tests/test_credentials.py

closes https://github.com/PrefectHQ/prefect/issues/15204

prefect-kubernetes: add missing config loaders

---

src/prefect/cli/_prompts.py
tests/cli/test_deploy.py

this PR updates `prompt_select_from_table` to display a rolling window of options instead of all of them at once.
for example, consider a `prefect work-pool create --provision-infra` with cloud run and I have 50 gcp projects, the current setup wouldn't let me select the bottom of the list if it ran off-screen downwards
<details>
<summary>before</summary>
all shown together, but you can't arrow down past the bottom of the screen
</details>
<details>
<summary>after</summary>
select from a rolling window of options (temporarily obscured values)
https://github.com/user-attachments/assets/b7cb70bc-91fe-4a25-8970-de70b429c936
</details>

update `prompt_select_from_table` 

---

src/prefect/results.py
tests/results/test_result_store.py

This PR adds the ability to configure `metadata_storage` for a `ResultStore`. Specifying `metadata_storage` will cause the `ResultStore` to write result metadata separate from the result data. The `ResultStore` will continue to operate as it did before if `result_metadata` is not provided.
Related to https://github.com/PrefectHQ/prefect/issues/15208

Adds ability to write result metadata separate from data when using `ResultStore`

---

src/integrations/prefect-kubernetes/prefect_kubernetes/utilities.py
src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/tests/test_utilities.py
src/integrations/prefect-kubernetes/tests/test_worker.py

Closes #14954 
Swaps the request class on the async k8s base client for one that has TCP keepalive enabled after the client is built. Refer to https://github.com/aio-libs/aiohttp/issues/3904#issuecomment-759205696

Add `KeepAliveClientRequest` class for k8s async client

---

docs/3.0/deploy/infrastructure-examples/docker.mdx
docs/mint.json

Most links to the 2.x docs had `/latest/` in them, but not all. This PR adds redirect rules to mint.json to catch many of those cases. Tested locally, and the redirects resolve as expected. 
For example /concepts/tasks now resolves appropriately to /3.0/develop/write-tasks.

Add docs redirects to catch non-latest in slugs 

---

docs/3.0/api-ref/rest-api/server/schema.json
docs/3.0/develop/variables.mdx

adds note that `overwrite` exists as a kwarg in the SDK
also updates language on sync/async, because `Variable` methods are `sync_compatible` so how they're called is [dually contextual](https://github.com/PrefectHQ/prefect/pull/15233#discussion_r1744814829) but from a user perspective has nothing to do with a run context. the current docs make some incorrect statements that further confuse that status quo. `def` vs `async def` seems like the most direct way to convey this behavior
<details>
<summary>for example</summary>
```python
In [1]: from prefect import flow, task
In [2]: from prefect.variables import Variable
In [3]: @task
...: def t():
...:     print(Variable.get('answer'))
...:
...: @task
...: async def at():
...:     print(await Variable.get('answer'))
...:
...: @flow
...: def …
```

clarify variables docs

---

docs/3.0/api-ref/rest-api/server/schema.json
src/prefect/server/schemas/actions.py
src/prefect/server/schemas/core.py

This PR tweaks API schemas for the recently added `Deployment.concurrency_limit` field to narrow allowed values to exclude the literal value `0` as it's confusing how it intersects with `concurrency_limit=None` and disabling a deployment. 
> [!Important]
> This is technically a breaking api change and is also inconsistent with Work pool concurrency limits which similarly allow 0. 
> We want to do this while this feature is still rather new/in-development and to pre-empt confusion with disabling deployments. 
>
> Also worth noting that the UI will include client-side validation for this greater-than-0 behavior already
> 
> Happy to close this small PR though if we think this additional validation isn't worth it …

Deployment.concurrency_limit cannot be zero.

---

src/prefect/server/services/task_run_recorder.py
tests/server/services/test_task_run_recorder.py

The `task-run-recorder` consumer takes in task run events, converts them into task runs and task run states, and inserts them into the database. Previously we ensured that these inserts are forced to be done in order of the events occurring through the `CausalOrdering`. 
In practice, the only benefit is that if someone were to observe the actual task run state inserts, a `COMPLETED` row would never exist before a `RUNNING` row. Additionally as long as we are using a queue that is always ordered (currently the only option is an in memory queue), events will never come out of order. Additionally the final state of the task run will always be reported correctly.
This PR removes the ordering as there is no real benefit and it is likely adding unnecessary strain to the server.

Remove `CausalOrdering` from `task-run-recorder`

---

src/prefect/client/orchestration.py
src/prefect/context.py
tests/client/test_prefect_client.py

When entering a `SyncClientContext` or `AsyncClientContext` for the first time, check if the client and server are compatible. 
This PR defines compatibility as both the client and server must be on the same major version. The goal of this pr is specifically to flag incompatibility between `2.x` and `3.x` clients and servers (in both directions). I'm very open to changing this in anyway that makes it more useful and future proof for the direction of the package.

check api compatibility when entering a client context

---

src/prefect/server/events/messaging.py
src/prefect/server/events/services/event_persister.py
src/prefect/server/services/task_run_recorder.py
tests/server/services/test_task_run_recorder.py

This PR adds some extra debug level logging on:
- when we publish an event
- when the `events-persister` receives an event
- when the `task-run-recorder` receives an event
This should give us the full picture of tracking an event from client side emit through persistence.
Related to ongoing investigations in https://github.com/PrefectHQ/prefect/issues/15153

Add debug logging for server side event handling

---

src/integrations/prefect-docker/prefect_docker/deployments/steps.py
src/integrations/prefect-docker/tests/deployments/test_steps.py

related to #15258
backport of #15262

[2.x] add function name to `prefect-docker` cache key

---

.pre-commit-config.yaml
requirements-dev.txt
src/prefect/records/filesystem.py
tests/records/test_filesystem.py

Closes #15077 
Additionally:
- adds `uv` as a dev dependency
- enforces `pydantic>=2.9.0` in generating openAPI schema to avoid noisy commits

Fix test flake and add `uv` dev dependency

---

.github/workflows/helm-chart-release.yaml

Since we are no longer cutting releases of our `prefect-helm` charts packaged with `prefect 2`, we will only allow this repo to trigger a helm release on a 3.x version.
Supporting GHA workflow doc [here](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#startswith)
Relates to PLA-237

chore: only trigger helm release workflows on 3.x.x version releases

---

.github/workflows/labeler.yml

I noticed that the labeler job was failing on contributor PRs ([example here](https://github.com/PrefectHQ/prefect/actions/runs/10584311321/job/29328278417?pr=15070)).  I did some reading and found two things that needed fixing:
- we need to check out the repository so that the `labeler.yml` file could be found by the runner without an API call (it's not clear that this is critical but 🤷 )
- we need to use the `pull_request_target` event to enable write permissions back on the PR from forked PRs, which is safe in the context of a labeling job (see [documentation on `pull_request_target`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target))

Fix labeler job

---

docs/3.0/resources/upgrade-to-prefect-3.mdx

https://github.com/PrefectHQ/prefect/pull/14996 removed this section because the code example was distracting and detracted from the main point, which was to make sure these common errors are searchable and have concrete suggestions to resolve them
this PR reintroduces the section with the intent of being more clear about what to change / why this is happening

better common error section

---

src/prefect/blocks/notifications.py
src/prefect/blocks/webhook.py
src/prefect/utilities/urls.py
tests/blocks/test_notifications.py
tests/blocks/test_webhook.py
tests/utilities/test_urls.py

(I'm just the messenger here, all of the work here was actually done by @chrisguidry)
If a user is self-hosting a Prefect API that they expose to "external" users of any kind, it's possible for a malicious user to configure a notification URL that points to an internal API (e.g., an internal Cloud provider API), which could result in comprising information exposure. This PR adds an optional flag for users in this situation that will restrict notification URLs to only public IP addresses. Note that validation occurs at notification runtime because DNS records could be altered post-validation if it occurred prior to the webhook firing.

Notification security controls

---

src/prefect/concurrency/asyncio.py
src/prefect/concurrency/sync.py
src/prefect/concurrency/v1/asyncio.py
src/prefect/concurrency/v1/sync.py
tests/concurrency/test_concurrency_asyncio.py
tests/concurrency/test_concurrency_sync.py
tests/concurrency/v1/test_concurrency_sync.py
tests/test_task_engine.py

We have an `internal.concurrency.api` module that I suspect is ultimately not needed anymore given our sync/async plans and current design. 
I noticed we were relying on it while perusing the concurrency code, so this PR refactors that code to use `sync_compatible` instead - this is a pure refactor, no behavior changes or anything are expected.

Refactor some concurrency utilities to be sync_compatible

---

src/prefect/server/services/cancellation_cleanup.py

A user identified that this was a problematic expression to include in the OR as it risks returning massive numbers of subflow runs; this PR correctly moves the expression to the AND of the where clause, which will _hopefully_ close #15231

Move expensive filter to AND

---

.github/workflows/copy-linked-issue-labels.yml

This PR:
- doesn't port the labels "great writeup" or "good first issue" from referenced issues to the PR
- in addition to [GitHub's automatic linking through special keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), adds a few new linking words that will trigger the auto-labeling of a PR; these words are to support phrases like "related to", "as mentioned in", etc. which usually mean the issue labels will have meaning for the PR as well

Add some more nuance to labeler

---

src/prefect/client/orchestration.py
src/prefect/client/schemas/objects.py
src/prefect/context.py
src/prefect/flow_engine.py
src/prefect/main.py
src/prefect/records/filesystem.py
src/prefect/results.py
src/prefect/states.py
src/prefect/task_engine.py
src/prefect/testing/utilities.py
src/prefect/transactions.py
src/prefect/utilities/engine.py
tests/results/test_flow_results.py
tests/results/test_result_store.py
tests/results/test_task_results.py
tests/test_context.py
tests/test_locking.py
tests/test_states.py
tests/test_task_engine.py
tests/test_tasks.py
tests/test_transactions.py

This PR updates the `Transaction` used for a task run to use a `ResultStore` instead of a `RecordStore`. Once a top-level method of `ResultStore` configuration is exposed, users will be able to configure result persistence, metadata persistence, and locking for task runs by changing the storage blocks and lock manager given to a `ResultStore`.
As a result of these changes, a JSON representation of `ResultMetadata` is stored in the `data` column of the `task_run_state` table. This replaces the JSON representation of `PersistedResult` that was used before. This maintains the current functionality to retrieve a persisted result from a state. The existing mechanics are kept for backwards compatibility.
A couple of key API additions/changes to make this possible:
- `should_persist_result`
- …

Use `ResultStore` by default for task transactions

---

.github/workflows/integration-tests.yaml
.github/workflows/python-tests.yaml

Reduces 2.x test matrix due to brittle test failures; the reduction in scope is based on the fact that the overwhelming number of new installs for 2.20.* are on 3.11 with a large representation on 3.10 as well.
Note: I expect tests to fail until #15292 is merged which fixes issues from `pydantic>=2.9`

Reduce test matrix

---

docs/3.0/api-ref/rest-api/server/schema.json
src/prefect/settings.py

This PR updates `PREFECT_API_ENABLE_HTTP2` to disable HTTP2 by default, improving client throughput and stability.
To test the effect of HTTP2, we used a single client machine and an over-resourced Prefect Cloud environment.
When enabling HTTP2, we observe very high server side response times. `p50` around 2s and `p99` at our server side timeout of 9s.
Upon digging into the data, it appears the increased response times are due to the server waiting on the client to send the full request, overwhelming server side resources. The client machine (my laptop)'s CPU resources were also overwhelmed.
After disabling HTTP2, we observed higher throughput with faster response times. `p50` around 60ms and `p99` around 250ms. And the client machine (my laptop) did not need all of it's CPU resources to …

Disable HTTP2 by default

---

src/integrations/prefect-databricks/prefect_databricks/models/jobs.py

closes https://github.com/PrefectHQ/prefect/issues/15308
this appears to have been dropped when moving this integration into `prefecthq/prefect`
I don't see any harm in reintroducing this, just for consistency

reintroduce job model for `prefect-databricks`

---

docs/3.0/api-ref/rest-api/server/schema.json
src/prefect/_internal/compatibility/deprecated.py
src/prefect/client/orchestration.py
src/prefect/concurrency/asyncio.py
src/prefect/concurrency/services.py
src/prefect/concurrency/sync.py
src/prefect/server/api/concurrency_limits_v2.py
src/prefect/server/models/concurrency_limits_v2.py
tests/_internal/compatibility/test_deprecated.py
tests/concurrency/test_acquire_concurrency_slots.py
tests/concurrency/test_concurrency_asyncio.py
tests/concurrency/test_concurrency_sync.py
tests/concurrency/v1/test_increment_concurrency_limits.py
tests/runner/test_runner.py
tests/server/models/test_concurrency_limits_v2.py
tests/server/orchestration/api/test_concurrency_limits_v2.py
tests/test_logging.py
tests/test_settings.py
tests/workers/test_base_worker.py

This PR deprecates `create_if_missing` which causes an ill-posed problem: creating a limit _implicitly_ has no obvious default limit value.
Instead, the behavior we want is:
- taking concurrency from a limit name that doesn't exist in the backend should be functionally equivalent to taking concurrency from a limit name that has a limit of `None` or from a limit that is "inactive" and therefore - at this instant - might as well not exist, i.e., it allows execution without creating any new object in the backend (and we log a `WARNING` to alert users)
- for users who want stricter control, we have a new kwarg `strict: bool` that specifies whether to raise an error if the limit name doesn't exist in the backend; this defaults to `False` but can be set to `True`. Setting this to `True` is …

Concurrency limit UX enhancements: add `strict` mode

---

src/integrations/prefect-dbt/prefect_dbt/cli/commands.py

closes #15235 
the subclass' field is `working_dir`, not `working_directory`

Update `DbtCoreOperation` docstring

---

src/prefect/records/base.py
src/prefect/records/filesystem.py
src/prefect/records/memory.py
src/prefect/records/result_store.py
src/prefect/transactions.py
tests/records/deprecation.py
tests/test_transactions.py

This PR adds deprecation warnings to all released `RecordStore` implementations as they have been superseded by `ResultStore` and it's accompanying `LockManager` implementations.
This PR also updates the `transaction` context manager to use a `ResultStore` by default instead of a `ResultRecordStore`.
Related to https://github.com/PrefectHQ/prefect/issues/15208

Add deprecation warnings to all `RecordStore` implementations

---

docs/3.0/develop/transactions.mdx

Updates the list of states a transaction goes through to try to reflect code updates. Feel free to revise.
Makes the code example runnable and adds a little sleep so the user can see the transaction do its thing.
Adds an example of setting and getting key-value pairs within the transaction's rollback book and a task.

Update transactions docs 

---

tests/test_tasks.py

I used this functionality in some code and wanted to affirm that it's true -- because of the way instance methods are turned into task runs, the `self` param *SHOULD* be treated like any other argument (this is important for how params are passed around). That implies that it should also be available to any feature that uses task run parameters, like a string template for the task run name. This test proves that's true.

Add unit test for accessing `self` as normal arg when setting task run name

---

setup.cfg
src/prefect/client/schemas/actions.py
src/prefect/results.py
src/prefect/states.py
src/prefect/transactions.py
tests/blocks/test_core.py
tests/blocks/test_system.py
tests/cli/test_block.py
tests/cli/test_deploy.py
tests/concurrency/test_concurrency_asyncio.py
tests/fixtures/deprecation.py
tests/records/test_filesystem.py
tests/records/test_memory.py
tests/results/test_persisted_result.py
tests/results/test_result_store.py
tests/results/test_state_result.py
tests/server/models/test_concurrency_limits_v2.py
tests/server/orchestration/api/test_block_types.py
tests/server/orchestration/api/test_concurrency_limits_v2.py
tests/server/orchestration/test_core_policy.py
tests/test_states.py
tests/test_task_engine.py
tests/test_transactions.py
tests/utilities/test_templating.py
tests/utilities/test_urls.py

This PR adds deprecation warning to following because they have been superseded by new results mechanics:
- `ResultStore.create_result`
- `BaseResult`
- `PersistedResult`
This PR also updates our testing logic to fail whenever a `PrefectDeprecationWarning` is raised. A fixture `ignore_prefect_deprecation_warnings` can suppress failures until the deprecation period has passed. Once the deprecation period has passed, the warnings will cause test failures again, prompting us to remove the deprecated code.
Related to https://github.com/PrefectHQ/prefect/issues/15208

Add deprecation warnings to results classes and methods

---

src/prefect/task_engine.py
tests/test_task_engine.py

This PR uses the `task_run` object for tag lookups instead of the `task`; this ensures that any tags added at runtime (e.g., when using `with tags(...):` are taken into account in the concurrency limiter of the engine.
Closes #15345

Ensure all tags are used in concurrency limiter

---

src/prefect/logging/configuration.py
src/prefect/logging/logging.yml

Closes #12518 and related to #11727 and #7851 
This PR sets `propagate: false` on any extra loggers configured through `PREFECT_LOGGING_EXTRA_LOGGERS`. This means that log records sent through these loggers will _not_ propagate to the `root` logger and therefore _not_ be handled by the `PrefectConsoleLogger`.  They will instead be handled by whatever handlers were explicitly configured + the `api` handler (which is necessary for sending logs to the API).
Adding this field to the default `logging.yml` file means that users can now customize this behavior through a setting / environment variable:
```
PREFECT_LOGGING_LOGGERS_PREFECT_EXTRA_PROPAGATE=true/false
```
whereas previously they needed to generate their own `logging.yml` file from scratch.
My choice of `false` for this setting is …

Set propagate to false for extra loggers

---

src/prefect/transactions.py
tests/test_transactions.py

This PR enables child transactions to access parent stored values set after the child transaction opened. This behavior is achieved by having child transactions delegate `.get` calls to their parent if they don't have a stored value for the provided key. The value from the parent transaction is copied and stored on the child transaction to avoid accidental mutation.
These changes resolve the issue in https://github.com/PrefectHQ/prefect/issues/15309 where a value set on a parent was accessed in a rollback hook since the rollback hook gets the task's transaction. These changes also mean that we don't have to copy all stored values from parent to child, which should reduce memory usage in some scenarios.
Closes https://github.com/PrefectHQ/prefect/issues/15309
- If no issue exists and your …

Allow child transactions to access parent values set after child transaction opens

---

src/prefect/logging/logging.yml

2.x version of #15348 -- stops propagating extra logs through root logger by default

Dont propagate extra loggers through root logger

---

src/prefect/utilities/importtools.py
tests/utilities/test_importtools.py

`safe_load_namespace` had trouble loading implicitly relative import (e.g. `from constants import FOO`) because the current working directory wasn't included in the sys path when attempting to resolve imports. This PR fixes that.
Closes https://github.com/PrefectHQ/prefect/issues/15352

Fix resolution of implicit relative import when using `safe_load_namespace`

---

src/prefect/client/types/flexible_schedule_list.py

type checked value that was unquoted results in
```
File "/Users/nate/github.com/prefecthq/prefect/src/prefect/client/types/flexible_schedule_list.py", line 10, in <module>
Union[DeploymentScheduleCreate, dict[str, Any], "SCHEDULE_TYPES"]
^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'DeploymentScheduleCreate' is not defined
```

quote type checked value

---

src/prefect/server/events/triggers.py
tests/events/server/triggers/test_regressions.py

There is an edge case with simple recurring automations (those with an `expect`,
a `within`, no `after`, and no `for_each`).  When an event arrives with an
`occurred` time that is ahead of the `end` of the current window, we correctly
skip counting that event toward that window, and we correctly attribute the
event to the next future window.  However, we weren't testing if that new future
window would _meet its threshold_ given that event.  This would cause these
simple automations to occasionally fail to fire on schedule.
Here we make one recursive call to `evaluate` in this case where we're leaving
`evaluate` with a new bucket and a remaining `count` of events.  This ensures
that we'll immediately fire on the first event rather than relying one a steady
stream of matching events to fire …

Correctly handles recurring automations and future events

---

.github/workflows/helm-chart-release.yaml

As demonstrated on the most recent 2.X release, the [action](https://github.com/PrefectHQ/prefect/actions/runs/10837591865/job/30073865265) ran successfully. We don't want this. Moving the conditional to the correct level within the action.

fix: move the github conditional to the appropriate level

---

src/prefect/client/orchestration.py
src/prefect/runner/runner.py
src/prefect/workers/base.py
tests/fixtures/database.py
tests/runner/test_runner.py
tests/workers/test_base_worker.py

Closes #15338
This PR includes 2 important changes related to deployment concurrency limits
1. Fixes a bug wherein `deployment.concurrency_limit` was erroneously being used as the _# of slots to acquire_ rather than the _# of slots to be made available_. This made attempting to use limits >1 untenable.
2. Adds an explicit upsert_gcl within worker/runners before they attempt to acquire a concurrency slot for use in enforcing deployment concurrency limits. This fixes a regression caused by #15297 where GCL's backing deployment concurrency limits used to be implicitly created and updated by the concurrency helper. This also has a nice side-effect of maintaining data consistency between the `deployment.concurrency_limit` field and the underlying `concurrency_limit_v2.limit`. 
> [!Note]
> …

Fix deployment-concurrency-limiting-GCL lifecycle management

---

.pre-commit-config.yaml
docs/3.0/api-ref/rest-api/server/schema.json
src/prefect/blocks/core.py
src/prefect/server/database/interface.py
src/prefect/server/database/orm_models.py
src/prefect/server/database/query_components.py
src/prefect/server/models/block_documents.py
src/prefect/server/models/block_registration.py
src/prefect/server/models/block_schemas.py
src/prefect/server/models/block_types.py
src/prefect/server/models/csrf_token.py
src/prefect/server/models/deployments.py
src/prefect/server/models/flow_run_notification_policies.py
src/prefect/server/models/flow_run_states.py
src/prefect/server/models/flow_runs.py
src/prefect/server/models/logs.py
src/prefect/server/models/saved_searches.py
src/prefect/server/models/task_run_states.py
src/prefect/server/models/task_runs.py
src/prefect/server/models/task_workers.py
src/prefect/server/models/work_queues.py
src/prefect/server/models/workers.py
src/prefect/utilities/collections.py
tests/server/models/test_flow_runs.py
tests/test_tasks.py

This gets all of the files in `/models` to pass mypy checks.

Get `/models` passing mypy checks.

---

src/prefect/cache_policies.py
tests/test_cache_policies.py

Refactors `__add__` and `__sub__` on `CachePolicy` and its subclasses to remove `if isinstance(self, ...)` calls. Instead, `CachePolicy` subclasses implement new versions of `__add__` and `__sub__` so that logic is located on the appropriate classes.

Refactors `__add__` and `__sub__` on cache policies

---

src/prefect/utilities/asyncutils.py

This PR aims to improve the docs so that if a user is typing the return of a function that is decorated by `@sync_compatible` they are aware of its behaviour.
It is a quick fix for the issue:
Closes: https://github.com/PrefectHQ/prefect/issues/15275

Improve type hinting docs for sync_compatible

---

src/integrations/prefect-sqlalchemy/prefect_sqlalchemy/credentials.py

This pull request adds support for `Oracle` databases using the `oracledb` Python library in the Prefect `SQLAlchemy` integration, addressing issue #15278.
Overview of the proposed changes:
Added `Oracle` Support in Enums:
- Added `ORACLE_ORACLEDB` to the `SyncDriver` enum, enabling synchronous connections to `Oracle` databases using the `oracledb` driver.
- Added `ORACLE_ORACLEDB_ASYNC` to the `AsyncDriver` enum, enabling asynchronous connections to `Oracle` databases using the `oracledb` driver with `SQLAlchemy`'s async support.

feat: add oracledb support in prefect-sqlalchemy

---

src/integrations/prefect-ray/prefect_ray/task_runners.py

This PR updates `prefect-ray` to lazily import `ray` to avoid issues when starting up a Prefect server in a virtual environment where `prefect-ray` is installed.
Also makes a fix to check if `ray` is initialized in all cases when `__enter__` is called on the `RayTaskRunner` to fix test failures.
Closes https://github.com/PrefectHQ/prefect/issues/14955
Closes https://github.com/PrefectHQ/prefect/issues/15226

Lazy import `ray` to fix server startup issues

---

docs/3.0/api-ref/rest-api/server/schema.json
src/prefect/server/api/server.py
src/prefect/settings.py
tests/server/api/test_server.py

Adds the following settings to allow modification to the CORS configuration of a Prefect server:
- `PREFECT_SERVER_CORS_ALLOWED_ORIGINS`
- `PREFECT_SERVER_CORS_ALLOWED_METHODS`
- `PREFECT_SERVER_CORS_ALLOWED_HEADERS`
Closes https://github.com/PrefectHQ/prefect/issues/15074

Adds settings to control server CORS configuration

---

src/prefect/flows.py
tests/test_flows.py

this PR reorders the validation to catch invalid `fn` name fallbacks before attempting to create the flow in the API, and renames a `fn` set to an unnamed lambda (which currently falls back to `<lambda>`) to `unknown-lambda` to handle this case
---
besides disallowing `<` and `>` in names of `Flow` objects in the API, the `flow` decorator just works with lambdas (though granted its not recommended) and IMO we should either handle this case or explicitly not support lambdas (which we do already use for `fn` in the tests)
```python
» python -c "from prefect import flow; flow(log_prints=True)(lambda: print(42))()"
...
prefect.exceptions.PrefectHTTPStatusError: Client error '422 Unprocessable Entity' for url …
```

handle unnamed lambdas for consistency

---

src/prefect/deployments/runner.py
src/prefect/flows.py
tests/test_flows.py

backports https://github.com/PrefectHQ/prefect/pull/15393
related to https://github.com/PrefectHQ/prefect/issues/15380

[2.x] preserve `flow.name` with `RunnerDeployment.from_storage`

---

src/prefect/cache_policies.py
src/prefect/locking/filesystem.py
src/prefect/results.py
src/prefect/task_engine.py
src/prefect/transactions.py
tests/test_cache_policies.py
tests/test_tasks.py
tests/test_transactions.py

This PR adds the ability to specify a storage location for cache entries via a `CachePolicy`. The isolation level for the cache and locking mechanism are also configurable via a `CachePolicy`.
Cache task results based on the input and source code a task. Store those cache entries at `~/.prefect/cache`. Allow only one actor to access a cache entry at a time and store lock files to enforce that at `~.prefect/locks`.
```python
from prefect.cache_policies import INPUTS, TASK_SOURCE
from prefect.transactions import IsolationLevel
@task(
cache_policy=(INPUTS + TASK_SOURCE).configure(
key_storage="~/.prefect/cache",
lock_manager="~/.prefect/locks",
isolation_level=IsolationLevel.SERIALIZABLE,
)
)
def my_task(x):
return x
print(my_task(10))
``` …

Add `key_storage`, `isolation_level` and `lock_manager` configuration to cache policies

---

src/prefect/context.py
src/prefect/utilities/engine.py

Closes https://github.com/PrefectHQ/prefect/issues/15391
In https://github.com/PrefectHQ/prefect/pull/14651 we started tracking task run states with a `WeakValueDictionary` to avoid memory bloat in flow with many tasks. Using a `WeakValueDictionary` can lead task run states to be garbage collected too soon which remove the information necessary to consistently show data dependencies between tasks.
This PR goes back to using a `dict` to track task run states, but drops the return value from the user's code to avoid memory bloat. 
Using the following script, we can see that memory usage stays roughly consistent (or even improves a bit) before and after this change:
```python
from memory_profiler import profile
@task
def with_task():
return [{"abc": "123"} for …
```

Fix task linking

---

src/prefect/server/api/server.py

This is the same fix as https://github.com/PrefectHQ/prefect/pull/15103, but applied to the command used to start an ephemeral server.
I have verified the fix on a Windows 11 VM.
Closes https://github.com/PrefectHQ/prefect/issues/15414

Fix ephemeral server start command for Windows

---

src/integrations/prefect-gcp/prefect_gcp/models/cloud_run_v2.py
src/integrations/prefect-gcp/prefect_gcp/workers/cloud_run_v2.py
src/integrations/prefect-gcp/tests/test_cloud_run_worker_v2.py

This PR adds the ability to create environment variables from GCP secrets in cloud run v2 prefect workers. To do so a new attribute was added to cloud run job v2 workers configurations, `env_from_secrets` which allows for the referencing of GCP secrets in a cloud run job v2 worker template with the following structure.
```json
{
"job_configuration": {
"env_from_secrets": "{{ env_from_secrets }}"
},
"variables": {
"env_from_secrets": {
"title": "Secrets as Environment Variables",
"description": "Environment variables to set from GCP secrets when starting a flow run.",
"type": "object",
"additionalProperties": {
"type": "string"
}
}
}
}
```
Deployments can then set environment variables from secrets via job variables, e.g.
```json
"env_from_secrets": {
"ENV_VAR": {
"secret": "SECRET_NAME", …
```

Add environment variables from GCP secrets to cloud run job v2 workers

---

src/prefect/results.py
tests/results/test_task_results.py
tests/test_tasks.py

`ResultStore.from_task` mistakenly uses the `key_storage` from a cache policy to configure `result_storage` instead of `metadata_storage`. This PR rectifies that.

Fix bug where task cache storage is misconfigured

---

docs/3.0/develop/task-caching.mdx

The `IsolationLevel` imports were wrong. Now, they're right.

Fix incorrect imports in task caching example

---

src/prefect/events/clients.py

Fixes these new test errors that we've seen in CI:
```
>       with pytest.raises(Exception, match="Unable to authenticate"):
E       AssertionError: Regex pattern did not match.
E        Regex: 'Unable to authenticate'
E        Input: 'ConnectionClosed.reason is deprecated; use Protocol.close_reason or ConnectionClosed.rcvd.reason'
```

Fix use of deprecated field on `websockets.exceptions.ConnectionClosedError`

---

src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/tests/test_worker.py

In https://github.com/PrefectHQ/prefect/issues/15259, we are seeing the Kubernetes worker stop its watch early and mark flow runs as crashed because an exit code hasn't been populated yet. I'm not entirely sure why that's happening, but I think it's because we're being too granular in determining if a Kubernetes job is in a terminal state.
This PR updates the determination of when a Kubernetes job is finished by observing the job status conditions on incoming job events. This appears to be the recommended method of determining when a job is finished in the [Kubernetes docs](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1JobStatus.md).
Might address https://github.com/PrefectHQ/prefect/issues/15259

Use job status conditions to determine when a job is in a terminal state

---

src/prefect/flows.py
tests/blocks/test_block_reference.py

This PR fixes loading block references in async flows. For async flows it throws `ParameterTypeError` as the sync compatible `Block.load_from_ref` call does not runs the coroutine.
Related to no existing issue (or i could not find any) and i assumed that it might not need one.

Fix block reference load in async flow

---

docs/3.0/api-ref/rest-api/server/schema.json
src/prefect/server/schemas/filters.py
tests/server/schemas/test_filters.py

This'll help us better catch edge cases where a run should be included in a list because it ended within a certain window or outside of a certain window.

Enhancement: Add `end_time` to flow run filters

---

docs/3.0/develop/transactions.mdx

Adds an idempotency section to the 'Write transactions' docs. Explains how to use transaction keys to prevent duplicate execution and how to use lock managers to prevent race conditions in concurrent workflows.

Add 'Idempotency' section to transactions docs

---

src/prefect/_internal/retries.py

use the internal logger for this, so as not to confuse users
> Saw this in the logs, is this something to be concerned about?
WARNING | prefect.retries - Attempt 1 of function 'get_lost_followers' failed with OperationalError. Retrying in 0.87 seconds..

use internal logger for `get_lost_followers` retries
