PrefectHQ/prefect

- src/prefect/server/models/deployments.py
Fixes a typo for deployment_version in the generate schedules function 
> fix typo in deployment_version

- src/prefect/_internal/pydantic/utilities/field_validator.py
- tests/_internal/pydantic/test_field_validator.py
> Fix imports for experimental Pydantic V2 field decorator

- requirements-client.txt
> bump `jsonschema` lower bound

- src/prefect/flows.py
prevent clicking on partial links and getting 404s
> fix soft wrap in `.deploy`

- src/prefect/cli/server.py
- src/prefect/events/filters.py
- src/prefect/server/database/interface.py
- src/prefect/server/database/migrations/MIGRATION-NOTES.md
- src/prefect/server/database/migrations/versions/postgresql/2024_04_10_112019_a0b41bdff9b3_add_events_and_event_resources_tables.py
- src/prefect/server/database/migrations/versions/postgresql/2024_04_10_194742_15768c2ec702_add_events_and_event_resources_tables.py
- src/prefect/server/database/migrations/versions/sqlite/2024_04_10_104304_824e9edafa60_adds_events_tables.py
- src/prefect/server/database/orm_models.py
- src/prefect/server/events/filters.py
- src/prefect/server/events/schemas/events.py
- src/prefect/server/events/storage/database.py
- tests/events/storage/test_database.py
- Adds SQLite and Postgres migrations to add an `events` table and an `event_resources` table
- Adds `Event` and `EventResource` ORM models and wires them up with the `PrefectDBInterface`
- Adds `prefect.server.events.storage` module with basic functions `read_events` and `write_events`
- Basic functionality is validated with tests
- Adds the ability to generate where clauses for existing filter types
- Currently lacks test coverage. Tests will be added in a subsequent PR to prevent this PR from getting any bigger than it already is.
> Adds ORM models and migrations for events storage

- src/prefect/cli/cloud/__init__.py
Removes an extra `if` statement.
Closes #12663
> Remove duplicate CLI output when reauthorizing with `prefect cloud login`

- src/prefect/server/api/server.py
- src/prefect/server/events/services/actions.py
- src/prefect/server/events/services/triggers.py
- src/prefect/server/events/triggers.py
- src/prefect/settings.py
- tests/events/server/triggers/conftest.py
- tests/events/server/triggers/test_basics.py
- tests/events/server/triggers/test_flow_run_slas.py
- tests/events/server/triggers/test_regressions.py
- tests/events/server/triggers/test_service.py
This brings proactive triggers to the OSS Prefect server, with a simplified
execution model based on a `LoopService`.
> Proactive triggers

- docs/concepts/artifacts.md
Screenshot from preview build:
> Show how to retrieve an artifact in Python code in the Artifact concept docs

- RELEASE-NOTES.md
[RENDERED](https://github.com/PrefectHQ/prefect/blob/3c86d55a1f4317fb577deb81723ecab4c724058c/RELEASE-NOTES.md)
> Release notes for 2.17.0

- src/prefect/server/utilities/user_templates.py
Closes https://github.com/PrefectHQ/prefect/issues/12685
> Remove `opentelemetry` import

- RELEASE-NOTES.md
> 2.17.1 release notes

- docs/concepts/work-pools.md
Updates the only remaining mention of `deployment.yaml` in the docs (outside of block and agent-based section pages).
> Update example to `prefect.yaml` in  work-pools concepts page

- src/prefect/server/api/server.py
- src/prefect/server/events/actions.py
- src/prefect/server/events/services/actions.py
- tests/events/server/actions/test_actions_service.py
Adds the service that consumes actions messages and runs them.
> Actions service

- tests/runner/test_runner.py
When running `runner/test_runner.py` it would leave a `flows.py` in your cwd. This ensures that this file is removed if it exists, and attempts to not create it in the first place.
> Update `runner/test_runner.py` to not leave `flows.py` on filesystem

- docs/getting-started/quickstart.md
add hyphen to forever free in quickstart
> add hyphen

- docs/getting-started/quickstart.md
> remove duplicative resilient

- src/prefect/cli/cloud/__init__.py
closes https://github.com/PrefectHQ/prefect/issues/12665
> Allow returning to account selection in `prefect cloud login` and `workspace set`

- docs/getting-started/quickstart.md
> Fix typo in Quickstart

- src/prefect/server/events/counting.py
- src/prefect/server/events/filters.py
- src/prefect/server/events/schemas/events.py
- src/prefect/server/events/storage/__init__.py
- src/prefect/server/events/storage/database.py
- src/prefect/server/utilities/database.py
- tests/events/server/test_events_counts.py
- tests/events/server/test_events_queries.py
- tests/server/events/services/test_event_persister.py
- tests/server/utilities/test_database.py
Adds `query_events`, `query_next_page`, and `count_events` functions that will provide the functionality necessary to read events via the REST API.
> Add functions for querying and counting events

- src/prefect/server/api/events.py
- tests/server/api/test_events.py
Add API routes for reading and paging through events with a given filter and API routes for counting events for different time periods.
> Add `/events/filter` and `/events/count-by` route trees

- src/prefect/server/api/clients.py
- src/prefect/server/api/deployments.py
- src/prefect/server/events/actions.py
- tests/events/server/actions/test_pausing_resuming_deployment.py
- tests/events/server/actions/test_pausing_resuming_work_pool.py
- tests/events/server/actions/test_pausing_resuming_work_queue.py
This implements the pause/resume work pool/queue actions.
> Implementing the work pool and work queue actions

- docs/tutorial/work-pools.md
I might be mistaken but it seems to me like there was a trailing sentence at the end of this paragraph that didn't quite make sense. I've suggested a minor restructuring to hopefully improve legibility :)
> Fix minor restructure to improve legibility of `work pools` tutorial

- docs/getting-started/quickstart.md
Strip out some unnecessary detail in the connection section
> Simplify-api-connection

- docs/concepts/automations.md
> Add `.serve`, `.deploy`, and composite trigger examples to deployment triggers docs

- docs/tutorial/index.md
> Simplify-tutorial

- src/prefect/events/clients.py
- src/prefect/events/utilities.py
- src/prefect/events/worker.py
- src/prefect/server/api/dependencies.py
- src/prefect/server/api/events.py
- tests/events/client/test_cloud_events_client.py
- tests/events/client/test_events_worker.py
- tests/events/server/gateway/test_gateway_in.py
- tests/events/server/gateway/test_gateway_out.py
- tests/server/api/test_events.py
This PR adds a `PrefectEphemeralEventsClient` class to handle sending events to an ephemeral Prefect server via the `POST /api/events` endpoint. This PR also updates the `/api/events` endpoint to directly store events when running in ephemeral mode. This change allows us to capture and store task run events when running against and ephemeral server.
Look Ma! No server!
```python
from prefect.event import emit_event
emit_event(
event="casper.sent.event!",
resource={
"prefect.resource.id": "ghost.friendly",
"prefect.resource.name": "casper"
}
)
```
> Adds ability to emit events to an ephemeral Prefect server

- docs/getting-started/installation.md
Simplify installation page by removing unnecessary info, combining duplicative info, and reordering info
> simplify-installation

- src/prefect/utilities/dispatch.py
> rm stray print

- docs/contributing/overview.md
- docs/getting-started/installation.md
Condenses duplicative sections, adds section on `prefect-client`, and adds a toggle for a RHEL section.
Updates versions and standarizes terminal input formatting.
> Improve installation instructions 

- .github/workflows/integration-tests.yaml
- flows/automation-assessments.py
- src/prefect/cli/deploy.py
- src/prefect/deployments/deployments.py
- src/prefect/deployments/runner.py
> Update integration tests for 2.18.0

- src/prefect/client/utilities.py
This adds a `client_injector` decorator as an alternative to `inject_client` that always injects a client as the first argument to the function it's decorating. This gives better type hinting and gets us away from the pattern of `client: PrefectClient = None`.
> Create `client_injector` for better type hints

- docs/cloud/index.md
- docs/cloud/users/api-keys.md
- docs/cloud/users/service-accounts.md
- docs/cloud/users/sso.md
- docs/getting-started/quickstart.md
- docs/guides/deployment/push-work-pools.md
- docs/index.md
- docs/tutorial/index.md
Contains a bunch of docs improvements from feedback, including better differentiating Quickstart and Tutorial.
> Quickstart and other improvements 

- src/prefect/input/actions.py
- src/prefect/input/run_input.py
Updates the `input` module to pass mypy checks.
> Get `input` module passing mypy checks

- docs/guides/deployment/storage-guide.md
Removes mention of non-existent block fields.
Thanks @seanpwlms for raising!
> Update storage guide credentials blocks

- mkdocs.yml
The deployments->schedules page no longer exists.
> Remove link to removed API page

- .github/workflows/integration-package-release.yaml
Adds a workflow to publish a new version of an integration package when a tag is created for that package. Only triggers on tags like `prefect-azure-0.3.8` where the package name is followed by the version.
Will only publish to TestPyPI for now. Will update to real PyPI once we're sure the workflow is working correctly.
> Add release workflow for integrations packages

- .github/workflows/integration-package-release.yaml
> Fixes error in working directory for integration package release workflow steps

- .github/workflows/integration-package-release.yaml
Didn't declare the output on the first job correctly.
> Fix output passing between jobs in integration package release workflow

- src/prefect/new_task_engine.py
- tests/test_new_task_engine.py
Adds handling to detect crashed tasks and update their state to `CRASHED`. The `TaskRunEngine` context will catch raised `BaseException`s and report task runs as crashed.
Note: This is to the new engine branch and test failures are coming from the new flow run engine tests.
> Add task crash detection to new engine

- src/prefect/cli/_prompts.py
- tests/cli/test_deploy.py
Fixes #12834 
```bash
❯ prefect deploy
? Select a flow to deploy [Use arrows to move; enter to select; n to select none]
┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃    ┃ Flow Name                            ┃ Location                    ┃
┡━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ >  │ glass_tower                          │ glass_flow.py               │
└────┴──────────────────────────────────────┴─────────────────────────────┘
Enter a flow entrypoint manually
? Deployment name (default): 
? Would you like to configure schedules for this deployment? [y/n] (y): 
? What type of schedule would you like to use? [Use arrows to move; enter to select]
┏━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ …
```
> Fix using default interval schedule in `prefect deploy`

- .github/workflows/integration-tests.yaml
- .github/workflows/validate_worker_metadata.yaml
- docs/integrations/catalog/prefect-slack.yaml
- docs/integrations/prefect-slack/credentials.md
- docs/integrations/prefect-slack/index.md
- docs/integrations/prefect-slack/messages.md
- mkdocs.yml
- src/integrations/prefect-slack/README.md
- src/integrations/prefect-slack/prefect_slack/__init__.py
- src/integrations/prefect-slack/prefect_slack/credentials.py
- src/integrations/prefect-slack/prefect_slack/messages.py
- src/integrations/prefect-slack/pyproject.toml
- src/integrations/prefect-slack/tests/conftest.py
- src/integrations/prefect-slack/tests/test_credentials.py
- src/integrations/prefect-slack/tests/test_messages.py
- src/integrations/prefect-slack/tests/test_version.py
- migrates `prefect-slack`
- updates `integration-tests.yaml` to only run on changes to `src/prefect/**/*.py`
> Migrate `prefect-slack` to core

- .github/workflows/integration-package-release.yaml
Updates the integration release workflow to point to real PyPI and use the correct secret based on the package being released.
> Update integration release workflow to point to real PyPI

- .github/workflows/integration-package-release.yaml
The release workflow ran into issues with dynamically accessing the correct secret for a package. This PR switches to use [PyPI's Trusted Publisher](https://docs.pypi.org/trusted-publishers/using-a-publisher/) setup which allows us to securely publish without needing to manage a separate API key for each package.
> Update integrations release workflow to use trusted PyPI publisher

- docs/integrations/catalog/prefect-docker.yaml
- docs/integrations/prefect-docker/containers.md
- docs/integrations/prefect-docker/credentials.md
- docs/integrations/prefect-docker/host.md
- docs/integrations/prefect-docker/images.md
- docs/integrations/prefect-docker/index.md
- docs/integrations/prefect-docker/worker.md
- mkdocs.yml
- src/integrations/prefect-docker/README.md
- src/integrations/prefect-docker/prefect_docker/__init__.py
- src/integrations/prefect-docker/prefect_docker/containers.py
- src/integrations/prefect-docker/prefect_docker/credentials.py
- src/integrations/prefect-docker/prefect_docker/deployments/steps.py
- src/integrations/prefect-docker/prefect_docker/host.py
- src/integrations/prefect-docker/prefect_docker/images.py
- src/integrations/prefect-docker/prefect_docker/worker.py
- src/integrations/prefect-docker/pyproject.toml
- src/integrations/prefect-docker/tests/conftest.py
- src/integrations/prefect-docker/tests/deployments/test_steps.py
- src/integrations/prefect-docker/tests/test-project/flow.py
- src/integrations/prefect-docker/tests/test-project/requirements.txt
- src/integrations/prefect-docker/tests/test_containers.py
- src/integrations/prefect-docker/tests/test_credentials.py
- src/integrations/prefect-docker/tests/test_host.py
- src/integrations/prefect-docker/tests/test_images.py
- src/integrations/prefect-docker/tests/test_version.py
- src/integrations/prefect-docker/tests/test_worker.py
> Migrate `prefect-docker` to core `prefect` repository

- src/prefect/cli/deployment.py
Before: `Watching flow run ''fuzzy-nightingale''...`
After: `Watching flow run 'dark-frigatebird'...`
> Remove extra quotes in `prefect deployment run --watch`

- src/integrations/prefect-snowflake/prefect_snowflake/database.py
After creating a SnowflakeConnector block, the code snippet we provide in the UI has a trailing colon that leads to failure if copied verbatim. This PR removes the colon.
Screenshot:
> Update Snowflake Connector example in UI

- docs/integrations/prefect-azure/aci_worker.md
Missed an `&&`. Also, that command is never happy when I pass an env var to `--name` so just using a string instead.
> Fix `az acr create` command in ACI worker guide

- ui/src/maps/csrfToken.ts
- ui/src/models/CsrfToken.ts
- ui/src/types/csrfTokenResponse.ts
Noticed there was a type error in the mapper. The code looks correct but the response type was saying it was already a `Date`. Which I don't think is possible because json won't parse the ISO string.
> Fix types and lint

- scripts/collections-manager
> Add list collections cmd to `collection-manager`

- src/prefect/events/cli/automations.py
- tests/events/client/cli/test_automations.py
- Previously, the `automation inspect` cmd accepted a single parameter `id_or_name`, which could be either an ID or a name. The function has been overhauled to separate these inputs into two distinct optional parameters: `name` and `id`, consistent with `prefect automation delete` and other `prefect` command groups.
- The logic in the `inspect` function has been updated to ensure that either a name or an ID is provided
- Added handling for cases where multiple automations are found when using the name parameter.
- The updated code includes more detailed comments and revised documentation strings that clarify the purpose and usage of each parameter and function.
```bash
❯ prefect automation inspect
Please provide either a name or an id.
```
```bash
❯ prefect automation inspect --help …
```
> Update `prefect automation inspect`

- .pre-commit-config.yaml
- setup.cfg
- src/prefect/events/cli/automations.py
- src/prefect/events/clients.py
- src/prefect/events/filters.py
- src/prefect/events/schemas/automations.py
- src/prefect/events/schemas/deployment_triggers.py
- src/prefect/events/schemas/labelling.py
- src/prefect/input/run_input.py
- src/prefect/server/models/agents.py
This also includes configuration to actually run `mypy` on pre-commit for the files we've done.
> Get `models/agents.py` passing in `mypy`

- tests/test_tasks.py
Updates the task test to run through both the current engine and the new engine implementation. Any currently failing tests in `tests/test_tasks.py` are decorated with `@fails_with_new_engine`. The aim is to be able to use the existing tests to verify that we are covering existing functionality in the new implementation, and allow us to discover areas where we want to diverge from what's supported by the current engine.
If this is gucci, I can do the same for `tests/test_flows.py`.
> Update task tests to run through new engine

- src/integrations/prefect-slack/prefect_slack/credentials.py
- src/integrations/prefect-slack/prefect_slack/messages.py
- src/integrations/prefect-slack/tests/test_block_standards.py
- src/integrations/prefect-slack/tests/test_notification_block.py
> Update `prefect-slack` code to match most recent version released from `prefect-slack` repo

- .github/workflows/benchmarks.yaml
See the details of this vulnerability at https://huntr.com/bounties/58ef02f2-31cc-488d-a55f-84ab309aa2b2 (private link)
> Update benchmarks.yaml fix security vulnerability

- ui/src/maps/uiSettings.ts
- ui/src/services/csrfTokenApi.ts
- ui/src/services/uiSettings.ts
- ui/src/types/settingsResponse.ts
- ui/src/utilities/api.ts
Needs: https://github.com/PrefectHQ/prefect/pull/13168
Closes: https://github.com/PrefectHQ/prefect/issues/13150
> Fix csrf race condition that caused some pages to not render content when refreshing

- docs/integrations/prefect-snowflake/index.md
Fixes and standardizes formatting in prefect-snowflake index and updates contributing information.
After:
> Update Prefect Snowflake docs

- src/integrations/prefect-gcp/prefect_gcp/credentials.py
- src/integrations/prefect-gcp/tests/test_credentials.py
> Handle empty `service_account_info` for cached Vertex client

- src/integrations/prefect-aws/prefect_aws/workers/ecs_worker.py
- src/integrations/prefect-aws/tests/workers/test_ecs_worker.py
closes https://github.com/PrefectHQ/prefect/issues/13174
> [prefect-aws] Fix inclusion of commas in tag scrubbing

- src/prefect/server/database/migrations/versions/postgresql/2024_05_01_105401_b23c83a12cb4_add_catchup_fields_to_deploymentschedule.py
- src/prefect/server/database/migrations/versions/sqlite/2024_05_01_103824_20fbd53b3cef_add_catchup_fields_to_deploymentschedule.py
same as https://github.com/PrefectHQ/nebula/pull/7674
> add server default for non-nullable deployment schedule column

- docs/integrations/prefect-dbt/index.md
Updates language and formatting. Planning to update other integration index pages similarly, so please let me know if you have feedback.
This page will be further refined with @robfreedy's pending library changes.
Preview page:
https://deploy-preview-13187--prefect-docs-preview.netlify.app/integrations/prefect-dbt/
> Update prefect-dbt index page

- RELEASE-NOTES.md
[Preview](https://github.com/PrefectHQ/prefect/blob/release-notes-2.18.2/RELEASE-NOTES.md)
> Release notes 2.18.2

- RELEASE-NOTES.md
[Preview](https://github.com/PrefectHQ/prefect/blob/release-notes-2.18.3/RELEASE-NOTES.md)
> Release notes for 2.18.3

- tests/types/test_self_validating_types.py
- ui/package-lock.json
- ui/package.json
this probably should have happened when they came in, but this covers our constrained types (compat with pydantic v1 and 2 - we dont need conditional imports)
> add tests for self-validating types

- docs/guides/host.md
- Made content clearer
- Used active language when possible
- Made some structural changes
- Fixed typo
> Edit review of Hosting a Prefect server instance

- docs/getting-started/quickstart.md
- docs/guides/ci-cd.md
- docs/guides/deployment/storage-guide.md
- docs/guides/managed-execution.md
- docs/guides/prefect-deploy.md
- docs/tutorial/work-pools.md
Switch repositories for examples to prefecthq repos.
> Switch docs example repo links to prefecthq repos

- src/prefect/types/__init__.py
its not needed, and messes with the inferred type
> remove `dataclass` from custom constrained types

- ui/src/pages/FlowRun.vue
> Revert flow run artifacts tab removal.

- src/prefect/new_flow_engine.py
- tests/test_new_flow_engine.py
Adds crash reporting to the new flow run engine following the same pattern as the crash detection implemented for the new task run engine.
> [New Engine] Add crash detection for flow runs

- tests/test_artifacts.py
Uncomments a line from an Artifact test.
> Chore: uncomment line now that the uniqueness constraint is dropped

- docs/guides/secrets.md
> Expand discussion of resolution order for cloud-provider service auth in doc

- src/integrations/prefect-aws/tests/deployments/test_steps.py
- src/integrations/prefect-dask/tests/test_task_runners.py
- src/integrations/prefect-docker/tests/conftest.py
- src/integrations/prefect-docker/tests/deployments/test_steps.py
- src/integrations/prefect-ray/tests/test_task_runners.py
- src/prefect/__init__.py
- src/prefect/infrastructure/process.py
- src/prefect/logging/formatters.py
- src/prefect/runner/runner.py
- src/prefect/testing/utilities.py
- src/prefect/utilities/annotations.py
- src/prefect/workers/process.py
- tests/cli/test_deploy.py
- tests/conftest.py
- tests/deployment/test_base.py
- tests/server/services/test_loop_service.py
Python 3.7 is at EOL and we no longer run our tests with Python 3.7. 
I think this would be the final step to close this issue: https://github.com/PrefectHQ/prefect/issues/10156
> Remove conditional logic and checks for Python 3.7

- docs/guides/deployment/storage-guide.md
> Fix repo url typo in storage guide

- src/integrations/prefect-gcp/prefect_gcp/cloud_storage.py
- src/integrations/prefect-gcp/tests/test_cloud_storage.py
> Fix selecting correct files when using ignore file in `GcsBucket`'s `put_directory`

- setup.py
Following a community submission to add the `prefect[dask]` extra, we agreed
that this is a good direction and that we should at least cover the major
infrastructure integrations.
```bash
pip install prefect[gcp,kubernetes]
```
> Adding extras for our major infrastructure and distributed task integrations

- src/prefect/__init__.py
- src/prefect/flows.py
- src/prefect/runner/__init__.py
- src/prefect/runner/runner.py
Please see the internal discussion at:
https://prefecthq.slack.com/archives/C071DE98B7U/p1715183364979709?thread_ts=1715098891.527619&cid=C071DE98B7U for more details.
Part of closing #12274
> Move `serve` to `flows` submodule

- setup.py
```bash
pip install prefect[gcp,kubernetes,dbt,snowflake,slack]
```
> Adds the remaining integrations as `extra`s

- .github/workflows/integration-tests.yaml
- RELEASE-NOTES.md
[Preview](https://github.com/PrefectHQ/prefect/blob/release-notes-2.19.0/RELEASE-NOTES.md)
> Release notes 2.19.0

- docs/guides/docker.md
> Add Python 3.12 to list of Docker images in docs

- ui/src/components/AutomationTriggerTemplateSelect.vue
- ui/src/pages/Automations.vue
Shamefully forgot to push these two commits before merging #13293
> Add changes from PR review of 13293

- src/prefect/deployments/deployments.py
> Defer imports for type annotations in `deployments` module under`TYPE_CHECKING` guard

- setup.cfg
This PR sets `testpaths` to `tests` to enable running `pytest` at the root of the repo to run the `prefect` test suite. To run integrations test suites, developers can navigate to the corresponding directory and run `pytest` or run `pytest src/integrations/<package_name>`
> Set `testpaths` for `pytest` to avoid default conftest conflict

- setup.cfg
Equivalent of https://github.com/PrefectHQ/prefect/pull/13368 for 2.x
> Set `testpaths` for `pytest` to avoid default conftest conflict - 2.x

- src/integrations/prefect-dbt/pyproject.toml
The programmatic invocations used by `prefect-dbt` were introduced after the current minimum specified `dbt-core` in `pyproject.toml`
> prefect-dbt - update dbt-core dependency

- src/integrations/prefect-dbt/pyproject.toml
Applies prefect-dot dbt-core dependency bump from #13394 to 2.x
> Update prefect-dbt dbt-core dependency

- src/integrations/prefect-aws/pyproject.toml
- src/integrations/prefect-azure/pyproject.toml
- src/integrations/prefect-bitbucket/pyproject.toml
- src/integrations/prefect-dask/pyproject.toml
- src/integrations/prefect-databricks/pyproject.toml
- src/integrations/prefect-dbt/pyproject.toml
- src/integrations/prefect-docker/pyproject.toml
- src/integrations/prefect-email/pyproject.toml
- src/integrations/prefect-gcp/pyproject.toml
- src/integrations/prefect-gcp/tests/test_cloud_run_worker.py
- src/integrations/prefect-github/pyproject.toml
- src/integrations/prefect-gitlab/pyproject.toml
- src/integrations/prefect-kubernetes/pyproject.toml
- src/integrations/prefect-ray/pyproject.toml
- src/integrations/prefect-shell/pyproject.toml
- src/integrations/prefect-slack/pyproject.toml
- src/integrations/prefect-snowflake/pyproject.toml
- src/integrations/prefect-sqlalchemy/pyproject.toml
Pins the existing version of integrations packages until we can update them to work with Pydantic V2 and other breaking changes. Updates to accommodate breaking changes can be made on `main` and the `2.x` branch will house versions of the integrations libraries that are compatible with 2.x versions.
> Pin `prefect` version for integrations packages

- RELEASE-NOTES.md
> 2.19.1 Release Notes

- tests/runner/test_storage.py
Should resolve some test flakes involving the creation of files in the present working directory ([example](https://github.com/PrefectHQ/prefect/actions/runs/9116551484/job/25070314995?pr=13337)).
> Add autouse fixture to modify cwd

- src/prefect/new_task_engine.py
- src/prefect/new_task_runners.py
- src/prefect/tasks.py
- src/prefect/utilities/engine.py
- tests/test_new_task_runners.py
- tests/test_tasks.py
This PR adds the ability to map tasks with the new engine. The new `TaskRunner` interface has been updated to include `.map` method that underpins `Task.map`.
I added a `.map` method to use native mapping capabilities in other executors. The `ThreadPoolTaskRunner` simply calls `.submit` in a loop when `.map` is called because `ThreadPoolExecutor` is blocking, and we want to return a group of futures from a `Task.map` call.
> [New Engine] Add the ability to map tasks

- docs/concepts/automations.md
Port from https://github.com/PrefectHQ/prefect/pull/13421
> Fix jinja template in automations doc.

- ui/package-lock.json
- ui/package.json
> Chore: Bump @prefecthq/prefet-ui-library@2.10.5

- src/prefect/new_flow_engine.py
- src/prefect/testing/utilities.py
- src/prefect/utilities/asyncutils.py
- tests/cli/test_worker.py
- tests/fixtures/collections_registry.py
- tests/test_flows.py
- tests/test_tasks.py
- tests/workers/test_utilities.py
More progress on refactoring tests to prepare for all green when we switch to the new engine by default
> More test progress

- docs/integrations/prefect-ray/index.md
Updating main branch (already added to 2.x branch in #13384)
> Update Ray integration docs

- tests/cli/test_config.py
> Fix `tests/cli/test_config.py`

- src/prefect/logging/handlers.py
- src/prefect/server/database/migrations/env.py
- tests/test_flows.py
> Remove `@sync_compatible` from `apply_migrations`

- tests/test_tasks.py
Adds a filter by `flow_run_id` to solve flaky tests like these: https://github.com/PrefectHQ/prefect/actions/runs/9178599774/job/25238870506
> Adds `flow_run_id` filter to `read_logs` call to prevent test cross-talk

- src/prefect/blocks/core.py
When saving a block the `block_type_slug` was being included as part of the `data`. This ensures that the `include` and `exclude` have an effect as they're just ignored by the `model_serializer`.
> Only include `block_type_slug` when appropriate

- RELEASE-NOTES.md
- scripts/generate-release-notes.py
[Preview](https://github.com/PrefectHQ/prefect/blob/2.19.2-release-notes/RELEASE-NOTES.md#release-2192)
Merge into `2.x` branch
> 2.19.2 release notes

- docs/cloud/rate-limits.md
> adding note on artifact retention

- src/prefect/cli/work_pool.py
- src/prefect/client/schemas/objects.py
Closes #13590 
Provides a hyperlink to to the newly created work pool object.
```bash
❯ prefect work-pool create my-modal-push-pool
? What type of work pool infrastructure would you like to use? [Use arrows to move; enter to select]
┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃    ┃ Infrastructure Type                  ┃ Description …
```
> Provide URL in CLI output upon work pool creation

- src/integrations/prefect-bitbucket/prefect_bitbucket/credentials.py
- src/integrations/prefect-bitbucket/prefect_bitbucket/repository.py
- src/integrations/prefect-bitbucket/pyproject.toml
- src/integrations/prefect-bitbucket/tests/test_repository.py
> migrate `prefect-bitbucket` to pydantic v2

- requirements-client.txt
> Remove dependencies from previously vendored starlette

- src/integrations/prefect-databricks/prefect_databricks/credentials.py
- src/integrations/prefect-databricks/prefect_databricks/flows.py
- src/integrations/prefect-databricks/prefect_databricks/jobs.py
- src/integrations/prefect-databricks/prefect_databricks/models/jobs.py
- src/integrations/prefect-databricks/prefect_databricks/rest.py
- src/integrations/prefect-databricks/pyproject.toml
- src/integrations/prefect-databricks/tests/test_rest.py
i unfortunately had to make some changes to the autogenerated `pydantic` models
notably, all models with `__root__` became `RootModels`
> migrate `prefect-databricks` to pydantic 2

- src/prefect/server/api/deployments.py
- src/prefect/server/api/flow_runs.py
- src/prefect/server/api/task_runs.py
- src/prefect/server/schemas/actions.py
This corresponds with adjustments in PrefectHQ/compat-tests#23
> Correcting API schemas to maintain compatibility with Cloud

- .github/pull_request_template.md
- docs/script.js
> Cleanup for new docs

- ui/src/pages/Variables.vue
This PR makes the UI use the new variables UI by default.
> using new json variables ui

- src/prefect/cli/block.py
- tests/cli/test_block.py
I'd like to find the schema of a block type, given the slug.  currently `prefect block type inspect <slug>` shows some top-level metadata, like the type ID and description.  I think it makes sense to include the latest schema of the type, in a readable format
https://www.loom.com/share/b47cae0cacff4bf9907e2823ebcd60d9?sid=74f80ff0-c2dc-4598-b56b-aeb34549c1cd
> feat(cli): show latest blocks schema on `prefect block type inspect <slug>`

- setup.cfg
- src/prefect/runner/runner.py
- tests/runner/test_runner.py
Port of https://github.com/PrefectHQ/prefect/pull/13660 to `2.x`.
> Skip on cancellation hooks if runner cant load flow

- RELEASE-NOTES.md
> Add release notes for 2.19.3

- RELEASE-NOTES.md
> Update RELEASE-NOTES.md on 2.x branch

- src/prefect/tasks.py
- tests/test_tasks.py
Add a `Task.delay()` method similar to Celery's that allows users to avoid passing explicit `args=` and `kwargs=` arguments.
closes #13693 
> Add Task.delay()

- docs/future-content-for-mint-2.19x.json
- docs/mint.json
Removes 2.19.x from versions mint.json and saves content in a file for future use.
Main site builds fine locally.
> Remove 2.19.x draft content from live docs

- docs/integrations/prefect-docker/deployments/steps.md
Generated docs for deployment steps from the Docker integration were missing. This adds them back in.
> Add Docker deployment steps page to centralized integration docs

- src/integrations/prefect-dask/prefect_dask/task_runners.py
- src/integrations/prefect-ray/prefect_ray/task_runners.py
> Fix inheritance for Dask and Ray futures

- RELEASE-NOTES.md
Clarifying that you cannot submit tasks, updating pip install command
> removing submit mention from release notes

- RELEASE-NOTES.md
> Update release heading

- setup.cfg
Tested by tagging commit:
```
git tag 3.0.0rc1
```
And then running `prefect-version`:
```
prefect version
Version:             3.0.0rc1
API version:         0.8.4
Python version:      3.9.18
Git commit:          4d5ed94a
Built:               Fri, May 31, 2024 11:54 AM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         server
```
> Update versioneer regex for release candidates

- docs/3.0rc/getting-started/installation.mdx
Just updates to the install page.
> Install updates for docs

- .github/workflows/python-package.yaml
> Install wheel when releasing core package

- src/integrations/prefect-slack/pyproject.toml
> `prefect-slack` 0.3.0rc1

- .github/workflows/integration-package-release.yaml
> Fix integration package release pipeline for RC releases

- src/integrations/prefect-aws/pyproject.toml
- src/integrations/prefect-azure/pyproject.toml
- src/integrations/prefect-bitbucket/pyproject.toml
- src/integrations/prefect-dask/pyproject.toml
- src/integrations/prefect-databricks/pyproject.toml
- src/integrations/prefect-dbt/pyproject.toml
- src/integrations/prefect-docker/pyproject.toml
- src/integrations/prefect-email/pyproject.toml
- src/integrations/prefect-gcp/pyproject.toml
- src/integrations/prefect-github/pyproject.toml
- src/integrations/prefect-gitlab/pyproject.toml
- src/integrations/prefect-kubernetes/pyproject.toml
- src/integrations/prefect-ray/pyproject.toml
- src/integrations/prefect-shell/pyproject.toml
- src/integrations/prefect-snowflake/pyproject.toml
- src/integrations/prefect-sqlalchemy/pyproject.toml
> Update `prefect` version and `tag_regex` for integrations packages

- src/integrations/prefect-dbt/pyproject.toml
> Update `prefect-dbt` to depend on RC versions

- tests/results/test_flow_results.py
- tests/results/test_task_results.py
- tests/runner/test_storage.py
This is a direct copy of @zangell44 's PR (https://github.com/PrefectHQ/prefect/pull/13680) to do this for the 2.x line.
> Fix tests that leave files on the filesystem

- src/prefect/server/api/ui/flow_runs.py
- tests/server/orchestration/api/ui/test_flow_runs.py
Adds a new ui endpoint for getting task run counts by flow run ids in bulk
> Add endpoint for bulk task run counts for flow runs

- src/prefect/deployments/base.py
- src/prefect/flows.py
- src/prefect/utilities/callables.py
- tests/test_flows.py
Port of #13716 to `2.x` branch
> Fix `load_flow_argument_from_entrypoint` to work with async flows

- docs/3.0rc/guides/managed-execution.mdx
> removing beta disclaimer

- src/prefect/utilities/importtools.py
- tests/utilities/test_callables.py
- tests/utilities/test_importtools.py
Attempt to load assignments when safeloading a namespace. This allows us to use dynamically defined Pydantic models for flows deployed via `prefect deploy` like in the example below.
Closes https://github.com/PrefectHQ/prefect/issues/13710
```python
def test_handles_dynamically_created_models(tmp_path: Path):
source_code = dedent(
"""
from pydantic import BaseModel, create_model, Field
def get_model() -> BaseModel:
return create_model(
"MyModel",
param=(
int,
Field(
title="param",
default=1,
),
),
)
MyModel = get_model()
def f(
param: MyModel,
) -> None:
pass        
"""
)
tmp_path.joinpath("test.py").write_text(source_code)
schema = callables.parameter_schema_from_entrypoint(f"{tmp_path}/test.py:f")
assert schema.model_dump_for_openapi() == {
"title": "Parameters",
"type": "object", …
```
> Load assignments when safeloading a namespace

- .github/workflows/integration-package-tests.yaml
- src/integrations/prefect-redis/README.md
- src/integrations/prefect-redis/prefect_redis/__init__.py
- src/integrations/prefect-redis/prefect_redis/filesystem.py
- src/integrations/prefect-redis/tests/test_filesystem.py
Makes the `read_path` and `write_path` methods of `RedisStorageContainer` sync compatible.
Closes #12249
> Update `read_path` and `write_path` methods of `RedisStorageContainer` to be sync_compatible

- src/prefect/utilities/callables.py
- tests/utilities/test_callables.py
Port of fix in #13774 to `2.x` branch
> Add handling for positional only and keyword only arguments when parsing a function signature from source code

- RELEASE-NOTES.md
> 2.19.4 release notes

- src/prefect/task_engine.py
see https://github.com/PrefectHQ/prefect/pull/13785#discussion_r1626806911
> sync_compatible

- docs/2.19.x/how-to-guides/execution/managed-execution.mdx
- docs/3.0rc/develop/recover-from-failure.mdx
Fix a doc build from an admonition change and note managed execution not in beta.
> Fixes a doc build from an admonition change and note managed execution not in beta.

- docs/3.0rc/get-started/install.mdx
> Update version instruction install docs page

- src/prefect/task_runners.py
> chore: alias ConcurrentTaskRunner -> ThreadPoolTaskRunner

- src/prefect/server/api/flow_runs.py
- tests/server/orchestration/api/test_flow_runs.py
The `flow_runs/filter` endpoint allows for `limit`/`offset` pagination but it has the limitation of not returning any sort of total count for how many flow runs exist that match the filter provided. This makes doing any sort of pagination difficult because you also have to make a call to `flow_runs/count` to determine the number of flow runs. 
This new `flow_runs/paginate` endpoint returns a dictionary like
```json
{
"results": [...],
"limit": 200, // returns whatever limit was passed as part of the request or what default limit was used
"page": 1,
"pages": 10,
"count": 100,
}
```
> Add new flow runs pagination endpoint

- src/prefect/tasks.py
Closes https://github.com/PrefectHQ/prefect/issues/13833
> Remove outdated comment

- docs/3.0rc/cloud/self-host.mdx
- docs/3.0rc/get-started/install.mdx
This cleans up the get-started/install page 
- change title to "Install"
- page doesn't discuss configuration so I removed that text
- DB content goes on the self-hosted page (makes this page simpler and encourages "just use Cloud")
- remove esoteric content
- make the TOC cleaner and better targeted
- point to quickstart after this instead of the tutorial
I also removed the instructions for how to install SQLite entirely because:
- As mentioned in the text, SQLite is already commonly installed
- That information isn't specific to Prefect
- That information is already--and better--found elsewhere online
> Edit get-started/install page

- docs/script.js
Removes script tag as a second script tag appears to be automatically added by mintlify.
> Remove script tag

- .github/ISSUE_TEMPLATE/3_feature_enhancement.yaml
Adds `3.x` to the dropdown for the Feature Enhancement issue template.
> Add 3.x to Feature Enhancement issue template

- docs/3.0rc/get-started/index.mdx
- docs/3.0rc/get-started/quickstart.mdx
Polishes the Quickstart using previous feedback and to better fit the new IA.
Also made minor tweaks to the home page for clarity and to fix links for the new IA. 
> Quickstart 3.0rc polish

- docs/3.0rc/cloud/configure-client.mdx
- docs/3.0rc/cloud/connect-to-cloud/index.mdx
- docs/3.0rc/cloud/interact-with-api.mdx
- docs/3.0rc/cloud/manage-users/api-keys.mdx
- docs/3.0rc/cloud/manage-users/audit-logs.mdx
- docs/3.0rc/cloud/manage-users/configure-sso.mdx
- docs/3.0rc/cloud/manage-users/index.mdx
- docs/3.0rc/cloud/manage-users/manage-roles.mdx
- docs/3.0rc/cloud/manage-users/object-access-control-lists.mdx
- docs/3.0rc/cloud/manage-users/service-accounts.mdx
- docs/3.0rc/cloud/rate-limits.mdx
- docs/3.0rc/cloud/self-host.mdx
- docs/3.0rc/cloud/troubleshoot-cloud.mdx
- docs/mint.json
- Retitled pages
- Separated troubleshooting and tips into its own page
- Edited each page and general cleanup
> Cloud docs 3.0 overhaul

- docs/3.0rc/deploy/serve-workflows/add-schedules.mdx
Simplifies the schedules documentation
> schedule-simplification

- docs/3.0rc/resources/daemonize-processes.mdx
- docs/integrations/prefect-aws/ecs_guide.mdx
- docs/integrations/prefect-bitbucket/index.mdx
- docs/integrations/prefect-dask/index.mdx
- docs/integrations/prefect-dask/usage_guide.mdx
- docs/integrations/prefect-dbt/index.mdx
- docs/integrations/prefect-gcp/gcp-worker-guide.mdx
- docs/integrations/prefect-gcp/index.mdx
- docs/integrations/prefect-ray/index.mdx
- docs/integrations/prefect-snowflake/index.mdx
- docs/integrations/prefect-sqlalchemy/index.mdx
- src/integrations/prefect-databricks/prefect_databricks/models/jobs.py
Updates formatting for mintlify.
> Improves integrations docs formatting 

- src/integrations/prefect-databricks/prefect_databricks/flows.py
- src/integrations/prefect-databricks/tests/test_flows.py
3.x version of https://github.com/PrefectHQ/prefect/pull/13957
> restore flow to `prefect-databricks`

- docs/3.0rc/deploy/serve-workflows/deploy-a-flow.mdx
- docs/3.0rc/deploy/work-pools/control-runs.mdx
Added note to /control-runs per @discdiver's feedback.
Fixed a header in /deploy-a-flow to sentence case.
> added control runs note

- docs/3.0rc/get-started/quickstart.mdx
- docs/getting-started/installation.mdx
User would get 2.19.x docs if they followed the existing instructions on that page.
> Update Quickstart install instructions for 3.0

- src/prefect/utilities/importtools.py
- tests/utilities/test_importtools.py
Port of https://github.com/PrefectHQ/prefect/pull/13922 to `2.x` branch
> Prevent execution of code in `if __name__ == "__main__":` blocks when running `prefect deploy`

- src/prefect/client/schemas/actions.py
- tests/cli/test_global_concurrency_limit.py
`active` should be a `bool`, not a `NonNegativeInteger`
> fix typing on `GlobalConcurrencyLimitUpdate`

- RELEASE-NOTES.md
> Release Notes for 2.19.5

- docs/3.0rc/get-started/install.mdx
Just a few small tweaks to the install page
> Install tweaks

- docs/3.0rc/deploy/work-pools/control-runs.mdx
- docs/3.0rc/develop/write-workflows/pause-cancel-flows.mdx
Removes a couple of references to infrastructure blocks.
> Remove infra block references

- src/prefect/task_runs.py
- src/prefect/task_worker.py
> Bump `TaskRunWaiter` cache size and expiration time and pin task worker thread pool workers to passed `limit`

- docs/3.0rc/develop/write-tasks/index.mdx
- docs/3.0rc/develop/write-workflows/index.mdx
This is a precursor to some IA changes
> Update task and flow page titles from "Create" to "Write and run"

- docs/mint.json
@billpalombi pointed out there was an extra arrow in the button.
After:
> Remove extra arrow in top button

- src/prefect/flows.py
just found small nits during QA
> minor typing and logging improvements

- RELEASE-NOTES.md
[Rendered](https://github.com/PrefectHQ/prefect/blob/b5b7f20fee1dea85fa08f53cba65a2e5f31097e1/RELEASE-NOTES.md)
> `3.0.0rc3` release notes

- .github/pull_request_template.md
Update the PR template to make it more succinct now that SDK docs are auto-discovered.
> Update PR template to reflect docs process changes

- docs/3.0rc/deploy/dynamic-infra/push-runs-remote.mdx
- docs/3.0rc/develop/connect-third-party.mdx
- docs/3.0rc/develop/write-tasks/use-task-runners.mdx
- docs/3.0rc/manage/cloud/troubleshoot-cloud.mdx
- docs/3.0rc/resources/secrets.mdx
- docs/contribute/index.mdx
- docs/integrations/prefect-azure/index.mdx
- docs/integrations/prefect-gcp/index.mdx
> Update nearly 100 broken links

- docs/3.0rc/get-started/install.mdx
It makes the line overflow onto the next line
> remove-pricing-link

- .github/workflows/nightly-release.yaml
This PR adds a workflow to release a new 3.0 release candidate every night a 12am PST. The workflow will only create a release if there are changes to `.py` files or the Python requirements. The workflow will generate release notes and create a GitHub release (marked as a pre-release), triggering the existing publish workflows. These workflows will need to be manually approved for now. Once we have confidence in this workflow, we can deploy to a different GH environment to remove the need for manual approval.
> Add nightly release workflow for release candidates

- .github/workflows/nightly-release.yaml
The commands in the nightly release workflow need a full git history to work correctly.
> Fix error in nightly release workflow by fetching full git history

- .github/workflows/nightly-release.yaml
> Fix latest tag regex in nightly release workflow to work on Ubuntu

- .github/workflows/nightly-release.yaml
The [most recent](https://github.com/PrefectHQ/prefect/actions/runs/9578351811/job/26408420743) nightly release workflow run failed due to an unnecessary `git fetch` command that failed. This PR removes that command since we are already fetching the entire git history and adds files where changes would trigger a nightly release.
> Remove unnecessary `git fetch` and add more changes to trigger a nightly release

- src/prefect/flow_engine.py
- tests/test_flows.py
This PR fixes a bug where a flow would fail if a `PrefectFuture` was passed. The fix was to run parameter validation after all upstream dependencies were resolved.
Closes https://github.com/PrefectHQ/prefect/issues/14036
> Fixes passing `PrefectFuture`s to flows

- docs/integrations/prefect-kubernetes/index.mdx
- src/integrations/prefect-kubernetes/README.md
- src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
Updates imports of `KubernetesClusterConfig` to import from `prefect_kubernetes.credentials`
> Fixes `KubernetesClusterConfig` import in `prefect-kubernetes`

- src/prefect/records/result_store.py
- src/prefect/results.py
- src/prefect/states.py
- src/prefect/task_engine.py
- src/prefect/transactions.py
- tests/test_flows.py
- tests/test_tasks.py
- tests/test_transactions.py
Building on #14155, this PR actually defers result persistence until commit time.
Once approved, will merge to other branch and then merge all as one.
> Only persist a tasks result at commit time

- docs/3.0rc/develop/write-flows/index.mdx
Just perusing docs and making touch ups as I see them. This PR makes some modifications to the flows section, in particular I noticed there were two sections on "Parameters" so I merged their content.
> Touch up flows section of docs

- mkdocs.yml
> Update link in nav

- .github/workflows/nightly-release.yaml
The [most recent](https://github.com/PrefectHQ/prefect/actions/runs/9593789059/job/26454978638) nightly release workflow run failed with permissions issues. This PR updates the input to the changelog creation step and adds `pull-requests: read` permission to the workflow so release notes can be successfully generated.
This PR also updates the create release action because the previously used one is deprecated.
> Fix permissions issue in nightly release workflow

- docs/integrations/prefect-dbt/index.mdx
Documents new features introduced in 0.5.0 and reorganizes content for clarity.
> prefect-dbt - update integration docs

- docs/3.0rc/develop/control-workflows/cancel.mdx
- docs/3.0rc/develop/control-workflows/pause-resume.mdx
- docs/mint.json
Upon further consideration, I don't think these should be on the same page and maybe not even in the same section.
> Separate pause and cancel

- src/prefect/server/api/workers.py
- tests/server/api/test_workers.py
Port of #14082 and #14095 for 2.x
> Fix deployment & work queue statuses

- .github/workflows/docker-images.yaml
- .github/workflows/prefect-client-publish.yaml
- .github/workflows/python-package.yaml
This PR updates our core release workflows to use the `dev` GitHub environment when the triggering release was a prerelease. With this change, the nightly release candidates will not need approval before being published to PyPI. This PR also adds a check of the tag before publishing to `dev` to ensure the new version will be a prerelease in PyPI.
> Use `dev` GitHub environment for prereleases

- src/prefect/_internal/compatibility/migration.py
Friction encountered in https://github.com/PrefectHQ/nebula/issues/8001
> Suggest flow.deploy() to replace use of `Deployment` interface

- docs/integrations/prefect-dask/index.mdx
- docs/integrations/prefect-databricks/index.mdx
- docs/integrations/prefect-dbt/index.mdx
- docs/integrations/prefect-docker/index.mdx
- docs/integrations/prefect-email/index.mdx
- docs/integrations/prefect-gcp/index.mdx
- docs/integrations/prefect-github/index.mdx
- docs/integrations/prefect-gitlab/index.mdx
- docs/integrations/prefect-kubernetes/index.mdx
- docs/integrations/prefect-ray/index.mdx
- docs/integrations/prefect-shell/index.mdx
- docs/integrations/prefect-slack/index.mdx
- docs/integrations/prefect-snowflake/index.mdx
- docs/integrations/prefect-sqlalchemy/index.mdx
> Update install instructions for remaining integration libraries

- src/prefect/flows.py
- src/prefect/runner/storage.py
- tests/runner/test_storage.py
- tests/test_flows.py
Porting changes from this pr https://github.com/PrefectHQ/prefect/pull/13981 to 3.x
> Port LocalStorage implementation to main

- .github/workflows/docker-images.yaml
- .github/workflows/prefect-client-publish.yaml
- .github/workflows/python-package.yaml
Updates the workflows to publish `prefect`, `prefect-client`, and Docker images to use the new `pre-release` environment for prereleases. Also updates the PyPI publish workflows to use a trusted publisher instead of an API token in a secret.
> Update publish workflows to use `pre-release` environment

- src/integrations/prefect-dask/prefect_dask/task_runners.py
- src/integrations/prefect-ray/prefect_ray/task_runners.py
- src/prefect/futures.py
- src/prefect/task_runners.py
- src/prefect/tasks.py
This PR fixes typing for `.submit` and `.map` so that when you call `.result()` on a future, it will have the correct type hint.
Closes https://github.com/PrefectHQ/prefect/issues/14223
> Fix typing for `.submit` and `.map`

- src/prefect/results.py
- src/prefect/tasks.py
- tests/results/test_flow_results.py
- tests/results/test_result_factory.py
- tests/test_flow_engine.py
- tests/test_flows.py
- tests/test_states.py
- tests/test_tasks.py
> Tests for #14166

- docs/3.0rc/deploy/serve-flows/serve-a-flow.mdx
- docs/3.0rc/deploy/work-pools/managed-execution.mdx
- docs/3.0rc/deploy/work-pools/prefect-deploy.mdx
- docs/3.0rc/develop/blocks.mdx
- docs/3.0rc/develop/manage-states.mdx
- docs/3.0rc/develop/recover-from-failure.mdx
- docs/3.0rc/develop/write-flows.mdx
- docs/3.0rc/manage/interact-with-api.mdx
- docs/3.0rc/resources/cancel.mdx
Removes broken line highlighting syntax from code snippets in docs
> remove broken line highlights

- docs/2.19.x/cloud/overview.mdx
- docs/2.19.x/cloud/users/api-keys.mdx
- docs/2.19.x/cloud/users/audit-log.mdx
- docs/2.19.x/cloud/users/objective-level-access-control.mdx
- docs/2.19.x/cloud/users/overview.mdx
- docs/2.19.x/cloud/users/rbac.mdx
- docs/2.19.x/cloud/users/sso.mdx
- docs/2.19.x/cloud/users/teams.mdx
- docs/2.19.x/cloud/workspaces.mdx
- docs/2.19.x/concepts/automations.mdx
- docs/3.0rc/automate/events/automations-triggers.mdx
- docs/3.0rc/manage/cloud/index.mdx
- docs/3.0rc/manage/cloud/manage-users/api-keys.mdx
- docs/3.0rc/manage/cloud/manage-users/audit-logs.mdx
- docs/3.0rc/manage/cloud/manage-users/configure-sso.mdx
- docs/3.0rc/manage/cloud/manage-users/index.mdx
- docs/3.0rc/manage/cloud/manage-users/manage-roles.mdx
- docs/3.0rc/manage/cloud/manage-users/manage-teams.mdx
- docs/3.0rc/manage/cloud/manage-users/object-access-control-lists.mdx
- docs/3.0rc/manage/cloud/workspaces.mdx
Updates docs language on Cloud plan from Custom to Enterprise.
Closes #14243
> Update Cloud plan language

- src/prefect/_internal/integrations.py
- src/prefect/cli/_prompts.py
- src/prefect/cli/worker.py
- src/prefect/deployments/steps/core.py
- tests/_internal/test_integrations.py
- tests/cli/test_worker.py
- tests/deployment/test_steps.py
This PR updates places where we adhoc install an integration package to use an extra instead of the package name itself. This will ensure that the version of the integration package compatible with the current version of `prefect` will be installed. Previously, the non-RC versions of integration packages would be installed and cause errors due to incompatibility.
Closes https://github.com/PrefectHQ/prefect/issues/14123
> Use prefect extras when adhoc installing integrations

- docs/3.0rc/get-started/install.mdx
- docs/snippets/installation.mdx
- Adds just a few more words to the install snippet for consistency with other sections
- Moves ancillary info to the bottom of the page
> install-tweaks

- docs/3.0rc/get-started/quickstart.mdx
Just a few small tweaks to the quickstart
> quickstart-tweaks

- docs/3.0rc/develop/write-flows.mdx
A few additional modifications to the flows page and another attempt at clarifying how nested runs are recorded.
> Flows page clarifications

- RELEASE-NOTES.md
> 2.19.6 release notes

- src/prefect/blocks/core.py
- src/prefect/client/utilities.py
- src/prefect/utilities/asyncutils.py
Fix type hinting of `sync_compatible` decorated functions. Fixes #13856.
> Fix sync_compatible typing

- docs/3.0rc/develop/blocks.mdx
- docs/3.0rc/develop/write-tasks.mdx
> Update blocks section 

- src/prefect/server/api/collections.py
When loading collection view data from disk, we pass a user-provided string into a path without first checking the value. This PR adds a check to prevent inadvertent exposure of local files via the `/collections/views/` route.
Should resolve https://github.com/PrefectHQ/prefect/security/code-scanning/2010
> Adds check to ensure only know view paths can be passed

- docs/contribute/code-of-conduct.mdx
Minor tweaks to the code of conduct styling
> Code of conduct styling

- docs/integrations/integrations.mdx
Makes the integrations page wide
> Widen integration page

- docs/3.0rc/get-started/index.mdx
@djsauble you were right that "scale to zero" is a bit to esoteric. That card its too wordy anyway.
I think we can do without the community message and the callout at the bottom - both are at the top of the side bar.
Feel free to push back if you disagree.
> Simplify landing page

- docs/3.0rc/manage/cloud/rate-limits.mdx
I am making this change for aesthetic reasons - so the title fits in the sidebar without wrapping.
> Change metadata to data

- docs/contribute/index.mdx
- docs/integrations/integrations.mdx
Cleans up formatting for the contribute and integrations overview pages
> overview-page-formatting

- docs/3.0rc/develop/results.mdx
> Fix typo in results.mdx

- docs/3.0rc/develop/variables.mdx
Minor tweaks to the formatting for consistency.
> Fix variables formatting

- docs/3.0rc/deploy/dynamic-infra/push-runs-serverless.mdx
Not necessary to show this small screenshot.
> Remove unnecessary screen shot

- docs/3.0rc/get-started/index.mdx
- Shortens the description so it doesn't wrap
- Changes "React" to "Automate" to correspond to the nav
> Landing Page Tweaks

- README.md
- Removes screen shots
- Updates language to be more consistent with latest framing
> Upadte readme

- docs/3.0rc/develop/interact-with-data.mdx
- docs/3.0rc/manage/cloud/troubleshoot-cloud.mdx
> Improve formatting of output and update links

- docs/3.0rc/api-ref/index.mdx
- docs/3.0rc/api-ref/rest-api/index.mdx
- docs/3.0rc/automate/add-schedules.mdx
- docs/3.0rc/deploy/control-runs/workers.mdx
- docs/3.0rc/develop/logging.mdx
- docs/3.0rc/develop/task-caching.mdx
- docs/3.0rc/manage/cloud/connect-to-cloud.mdx
- docs/3.0rc/manage/cloud/manage-users/api-keys.mdx
- docs/3.0rc/manage/self-host.mdx
- docs/3.0rc/manage/settings-and-profiles.mdx
- docs/mint.json
- src/prefect/cli/config.py
This PR updates the configuration of profiles and settings and greatly compresses the content into a more streamlined and hopefully digestible form.
Additionally, this adds a `-y` flag for unsetting values from an active profile.
> Updates to configuring profiles and settings

- docs/3.0rc/manage/cloud/index.mdx
- docs/mkdocs/stylesheets/extra.css
> Update button in docs to Enterprise from Custom

- docs/3.0rc/automate/add-schedules.mdx
Reorganized and abbreviates content
> Simplify schedules page

- docs/3.0rc/manage/cloud/workspaces.mdx
> Update workspaces docs

- docs/3.0rc/api-ref/server/schema.json
- src/integrations/prefect-docker/tests/test_worker.py
- src/integrations/prefect-kubernetes/tests/test_worker.py
- src/prefect/cli/deployment.py
- src/prefect/settings.py
- tests/_internal/compatibility/test_experimental.py
- tests/conftest.py
- tests/server/test_app.py
> Remove experimental worker settings

- docs/3.0rc/manage/cloud/manage-users/audit-logs.mdx
Minimal edits to the audit logs page for clarity and ascetics.
> audit-logs-cleanup

- docs/index.md
> Update Prefect intro in 2.19.x docs

- mkdocs.yml
Update docs edit pencil icon link for 2.x docs to 2.x branch.
Closes #14374
> Update docs edit pencil icon link for 2.x docs

- docs/3.0rc/manage/cloud/index.mdx
- docs/3.0rc/manage/cloud/manage-users/api-keys.mdx
- docs/3.0rc/manage/cloud/manage-users/audit-logs.mdx
- docs/3.0rc/manage/cloud/manage-users/configure-sso.mdx
- docs/3.0rc/manage/cloud/manage-users/index.mdx
- docs/3.0rc/manage/cloud/manage-users/manage-roles.mdx
- docs/3.0rc/manage/cloud/manage-users/manage-teams.mdx
- docs/3.0rc/manage/cloud/manage-users/service-accounts.mdx
- docs/3.0rc/manage/cloud/workspaces.mdx
- docs/mint.json
Edits the titles in the manage accounts section
> Manage-users-title-cleanup

- src/prefect/results.py
- tests/results/test_persisted_result.py
- tests/results/test_state_result.py
- tests/results/test_unknown_results.py
- tests/results/test_unpersisted_result.py
This PR removes artifact fields from result schemas as they are not necessary.
> Remove unnecessary fields on result schemas

- docs/contribute/code-of-conduct.mdx
- docs/contribute/dev-contribute.mdx
Small tweaks to titles and spacing
> contribute-cleanup

- src/prefect/utilities/importtools.py
- tests/utilities/test_importtools.py
Updates `safe_load_namespace` to only walk the top level of source code when looking for classes, functions, and assignments.
Closes https://github.com/PrefectHQ/prefect/issues/14402
> Fixes bug where assignments inside functions are evaluated when running `prefect deploy`

- RELEASE-NOTES.md
> 2.19.7 Release Notes

- .github/workflows/surface-high-engagement-issues.yml
- scripts/surface_high_engagement_issues.py
It would be ideal to allow manually changing the input to the new issue workflow
> Allow input to issue workflow

- src/prefect/task_worker.py
- src/prefect/tasks.py
- tests/test_task_worker.py
- tests/test_tasks.py
> Emit task run urls when creating/submitting background tasks

- docs/3.0rc/resources/upgrade-prefect-3.mdx
Minor, mostly editorial, edits to the "upgrade to Prefect 3" doc, for consistency and clarity. 
Use active voice, avoid "we", avoid future tense.
> minor edits to "upgrade to Prefect 3" doc

- docs/3.0rc/develop/inputs.mdx
- future-docs/2.19.x/how-to-guides/development/interactive-workflows.mdx
Updates/corrects the import path for run_deployment in our code examples. 
> Update import path for for run_deployment in docs code examples

- docs/3.0rc/develop/deferred-tasks.mdx
Closes #14435 
Fixes import and minor formatting edits to the example.
> Update deferred tasks example

- docs/3.0rc/resources/upgrade-prefect-3.mdx
A user with a self-hosted server instance will need to upgrade their database to use Prefect 3. This isn't unique from other Prefect upgrades that require a database migration, but it's something that will affect all self-hosted users coming to 3 from 2.
> Update Prefect 3 upgrade page to include database migration

- src/prefect/cli/flow_run.py
> Fix error in `flow-run` CLI log printing and escape special characters

- src/prefect/_internal/compatibility/migration.py
> Clarify usage for migration utility

- docs/3.0rc/develop/inputs.mdx
> Update validator usage for pydantic 2 in `RunInput` examples

- .github/workflows/surface-high-engagement-issues.yml
- scripts/surface_high_engagement_issues.py
Attempt to debug [failing workflow](https://github.com/PrefectHQ/prefect/actions/runs/9717666029/job/26823818832) that passes locally
> Debug failing workflow

- src/prefect/_internal/compatibility/migration.py
- src/prefect/context.py
Add  `PrefectObjectRegistry` to list of removed classes for the migration to v3.
Closes #13162
> Add  `PrefectObjectRegistry` to list of removed classes

- docs/3.0rc/develop/artifacts.mdx
- docs/3.0rc/develop/blocks.mdx
- docs/3.0rc/develop/pause-resume.mdx
- docs/3.0rc/develop/test-workflows.mdx
- docs/3.0rc/develop/write-flows.mdx
- docs/3.0rc/manage/cloud/index.mdx
- docs/3.0rc/resources/cancel.mdx
- docs/3.0rc/resources/visualize-flow-structure.mdx
- docs/contribute/contribute-integrations.mdx
- docs/contribute/dev-contribute.mdx
> Rework contribute page and minor docs fixes for formatting consistency

- docs/3.0rc/resources/upgrade-prefect-3.mdx
Small refinements to upgrade guide language
> Simplify and refine upgrade guide language

- RELEASE-NOTES.md
- scripts/generate-release-notes.py
[Preview](https://github.com/PrefectHQ/prefect/blob/3.0.0rc10-release-notes/RELEASE-NOTES.md#release-300rc10)
> Release notes 3.0.0rc10

- RELEASE-NOTES.md
- scripts/generate-release-notes.py
I didn't realize Daniel had another handle!
> Fix latest release notes outside contributors section

- docs/3.0rc/automate/events/automations-triggers.mdx
- docs/3.0rc/deploy/infrastructure-concepts/customize.mdx
- docs/3.0rc/deploy/infrastructure-concepts/deploy-ci-cd.mdx
- docs/3.0rc/deploy/infrastructure-examples/kubernetes.mdx
- docs/3.0rc/deploy/infrastructure-examples/managed.mdx
- docs/3.0rc/develop/logging.mdx
- docs/3.0rc/develop/write-tasks.mdx
- docs/styles/CustomStyles/WordList.yml
> Update code examples to that reference Prefect v2 to v3 

- docs/3.0rc/automate/automate-overview.mdx
- docs/3.0rc/automate/events/automations-triggers.mdx
- docs/3.0rc/automate/events/events.mdx
- docs/3.0rc/automate/incidents.mdx
- docs/mint.json
Creates overview page for Automate.
Update automations and events for Prefect v3. 
> Adds overview page for Automate section and updates content for v3

- docs/3.0rc/get-started/quickstart.mdx
Changed `considering` to `consider` in line # 253
- Before: `Now considering reading:`
- After: `Now consider reading:`
> [docs] fixed a grammatical error in quickstart.mdx

- docs/3.0rc/automate/automate-overview.mdx
- docs/3.0rc/deploy/index.mdx
- docs/3.0rc/develop/develop-overview.mdx
- docs/3.0rc/manage/manage-overview.mdx
Makes each overview page simply display as "Overview" in the sidebar.
> Simplify Sidebar titles

- docs/guides/host.md
Closes #14506 
The intro paragraph renders in HTML as 
```
<p>After installing Prefect, you have:
- a Python SDK client that can communicate with <a href="https://app.prefect.cloud">Prefect Cloud</a>
- an <a href="/api-ref/">API server</a> instance backed by a database and a UI</p>
```
rather than the intended list due to a missing empty line prior to the list item
> Adding missing empty line to trigger list rendering in host.md

- docs/3.0rc/develop/write-flows.mdx
> Corrected "feild" typos in "Write and run flows" doc

- docs/3.0rc/get-started/index.mdx
> Update index.mdx so builds

- src/prefect/cli/server.py
> 2.x port of #14519

- docs/3.0rc/get-started/index.mdx
Modifies the descriptions in a couple of the cards to make them each no more than three lines.
> resolve hanging words

- docs/3.0rc/api-ref/index.mdx
- docs/3.0rc/api-ref/rest-api/index.mdx
- docs/3.0rc/automate/automate-overview.mdx
- docs/3.0rc/deploy/infrastructure-concepts/store-flow-code.mdx
- docs/3.0rc/deploy/infrastructure-concepts/work-pools.mdx
- docs/3.0rc/deploy/run-flows-in-local-processes.mdx
- docs/3.0rc/develop/artifacts.mdx
- docs/3.0rc/develop/blocks.mdx
- docs/3.0rc/develop/deferred-tasks.mdx
- docs/3.0rc/develop/inputs.mdx
- docs/3.0rc/develop/interact-with-data.mdx
- docs/3.0rc/develop/variables.mdx
- docs/3.0rc/develop/write-flows.mdx
- docs/3.0rc/get-started/install.mdx
- docs/3.0rc/get-started/quickstart.mdx
- docs/3.0rc/manage/cloud/connect-to-cloud.mdx
- docs/3.0rc/manage/cloud/index.mdx
- docs/3.0rc/manage/manage-overview.mdx
- docs/3.0rc/manage/self-host.mdx
- docs/3.0rc/manage/settings-and-profiles.mdx
- docs/3.0rc/resources/daemonize-processes.mdx
- docs/3.0rc/resources/secrets.mdx
- docs/3.0rc/resources/upgrade-prefect-3.mdx
- docs/integrations/prefect-kubernetes/index.mdx
- docs/styles/CustomStyles/WordList.yml
Improves consistency in the docs around Prefect server and Prefect Cloud.
Adds a few Vale rules for capitalization of the same terms.
Closes #14509
> Updates language around Prefect server and Cloud in the docs

- src/integrations/prefect-gcp/prefect_gcp/cloud_storage.py
- src/integrations/prefect-gcp/tests/test_cloud_storage.py
> port `get_directory` fix (#14432)

- docs/script.js
cc: @sarahmk125 
Snippet for docs.
> Adds reo to docs 

- src/prefect/cli/deploy.py
- src/prefect/flows.py
- src/prefect/runner/server.py
- tests/test_flows.py
This is the 2.x backport of https://github.com/PrefectHQ/prefect/pull/14530
Related to #14464
> Allow loading flows from an entrypoint when dependencies are missing (2.x)

- src/integrations/prefect-kubernetes/prefect_kubernetes/flows.py
- src/integrations/prefect-kubernetes/prefect_kubernetes/jobs.py
- src/integrations/prefect-kubernetes/tests/test_flows.py
closes https://github.com/PrefectHQ/prefect/issues/12993
> Added print_func for run_namespaced_job

- .github/workflows/benchmarks.yaml
- .github/workflows/codspeed-benchmarks.yaml
- benches/bench_cli.py
- benches/bench_flows.py
- benches/bench_import.py
- benches/bench_tasks.py
- requirements-dev.txt
Adds `pytest-codspeed` as a dev dependency and updates the benchmark workflow to add additional tracking and metrics to our benchmark tests.
The [Codspeed docs](https://docs.codspeed.io/) provide more info on what it offers.
> Add CodSpeed to add additional tracking and metrics to benchmarks

- RELEASE-NOTES.md
> Release notes for 2.19.8

- .github/workflows/create-tags-for-changed-integrations.yaml
looks like the GHA workflow is getting a 403 on the `create_repo_tag()` method, specifically
https://github.com/zzstoatzz/gh/blob/main/src/gh_util/functions.py#L739-L816
from what i can tell, there are two explicit calls to the GH API:
```
POST /tags
https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28#create-a-tag-object
POST /refs
https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#create-a-reference
```
we can try adding this permission explicitly to the ephemeral token, im not entirely sure what would have changed (other than defaults on the GH side) for us to have to make this change
https://github.com/PrefectHQ/prefect/actions/workflows/create-tags-for-changed-integrations.yaml …
> fix(collections): update workflow permissions for tag creation

- .github/workflows/weekly-release.yaml
Updates the release workflow to publish an RC version every Thursday at 2PM EST. The workflow is currently disabled, but I can enable it once the new cadence is agreed upon and this PR is merged.
Closes https://github.com/PrefectHQ/prefect/issues/14400
> Update release workflow to weekly

- .pre-commit-config.yaml
- src/prefect/concurrency/asyncio.py
- src/prefect/concurrency/events.py
- src/prefect/concurrency/services.py
- src/prefect/concurrency/sync.py
- src/prefect/server/database/orm_models.py
- src/prefect/server/models/agents.py
- src/prefect/server/models/artifacts.py
- src/prefect/server/models/flows.py
This is _mostly_ about `models/artifacts.py`, but it includes some other changes. Specifically changes to other mypy 'approved' files. `mypy` wasn't finding any issues in `artifacts.py`, this seems to be because we have `follow_imports = skip`, turning this to `normal` caused a lot of mypy errors in `artifacts` but elsewhere too. I've cleaned up a bunch of them, but leaving `follow_imports` as `skip` for now as it breaks pre-commit as it calls out ~1k issues.
> Update `models/artifacts.py` to pass mypy checks

- src/prefect/cli/worker.py
- src/prefect/workers/base.py
- src/prefect/workers/server.py
- tests/cli/test_worker.py
- tests/workers/test_base_worker.py
This PR refactors the `BaseWorker` to own starting polling loops instead of the CLI. This is in anticipation of removing cancellation from workers when removing the `PREFECT_EXPERIMENTAL_ENABLE_ENHANCED_CANCELLATION` setting. The `ProcessWorker` will need to keep its cancellation loop (because it doesn't start a `Runner` for flow runs), so this PR adds a `.start` method to handle loop creation, which the `ProcessWorker` will be able to implement to maintain a cancellation loop.
Related to https://github.com/PrefectHQ/prefect/issues/14208 and https://github.com/PrefectHQ/prefect/issues/14209
> Move loop creation into `BaseWorker` class

- scripts/create_tags_for_changed_collections.py
https://github.com/zzstoatzz/gh/blob/main/src/gh_util/functions.py#L778
https://github.com/PrefectHQ/prefect/actions/runs/9896652374/job/27344257392
> fix(collections): pass github actor tagger to `create_repo_tag` function

- src/prefect/_internal/concurrency/api.py
- src/prefect/flows.py
this will improve more after https://github.com/PrefectHQ/prefect/pull/14563 is merged
> improve typing in `from_source`

- requirements-client.txt
Bump anyio to resolve: https://security.snyk.io/vuln/SNYK-PYTHON-ANYIO-7361842
Closes PrefectHQ/devsecops#981
> bump anyio

- docs/3.0rc/develop/write-tasks.mdx
Re-adds retries to task docs. Updates text and style for 3.0 docs.
Addresses majority of  #14543
> Add retries to Write tasks page

- docs/3.0rc/api-ref/rest-api/index.mdx
- docs/3.0rc/develop/blocks.mdx
- docs/3.0rc/develop/results.mdx
- docs/3.0rc/develop/write-flows.mdx
- docs/3.0rc/get-started/index.mdx
- docs/3.0rc/manage/cloud/manage-users/manage-roles.mdx
- docs/3.0rc/manage/cloud/workspaces.mdx
- docs/3.0rc/manage/manage-overview.mdx
Codespell helped me find some typos in the docs. I'm going to look at turning it back on for docs. Right now it doesn't fire on docs page changes. 
> Fix spelling typos

- .github/workflows/weekly-release.yaml
The weekly RC release went out earlier than expected. This PR updates the cron string to account for UTC and updates the name of the created releases.
> Update cron string for weekly release and release name

- requirements-client.txt
- src/integrations/prefect-kubernetes/prefect_kubernetes/jobs.py
- src/prefect/client/schemas/objects.py
- src/prefect/context.py
- src/prefect/deployments/deployments.py
- src/prefect/engine.py
- src/prefect/workers/block.py
This PR adds deprecation warnings for anything we know is moving or being removed in Prefect 3.0.0, if one did not already exist.
Closes #14676 
> Removal 3 warnings

- docs/3.0rc/resources/upgrade-prefect-3.mdx
> Fix typo in upgrade guide regarding calling async tasks/flows from sync tasks/flows

- src/integrations/prefect-docker/prefect_docker/worker.py
- src/integrations/prefect-docker/tests/test_worker.py
Closes #12924 
2.x port of #14686 
> Add `container_create_kwargs` to Docker worker

- .github/workflows/copy-linked-issue-labels.yml
> Remove repo equality check

- .github/workflows/copy-linked-issue-labels.yml
I might have over-specified some things in the original workflow template. Trying to simplify to see if that gets it working.
Possibly fixes #14672
> Update issue labeling workflow

- .github/ISSUE_TEMPLATE/1_bug_report.yaml
Updates our bug issue template to be more streamlined and less noisy to look at.  Hopefully makes bug reports a bit easier for folks.
> Update bug issue template

- docs/3.0rc/develop/write-flows.mdx
Add missing imports to docs example flow so that the code works as is.
> Add missing imports to docs example

- .github/pull_request_template.md
This PR reduces the copy in our PR template and relies more heavily on our contribution guidelines link.
> Minimize PR template

- src/prefect/tasks.py
- tests/runner/test_runner.py
- tests/test_background_tasks.py
- tests/test_tasks.py
closes https://github.com/PrefectHQ/prefect/issues/13735
2.x backport of https://github.com/PrefectHQ/prefect/pull/14704
> fix task key comp for 2.x

- .github/workflows/npm_update_latest_prefect.yaml
label to use for this sort of thing changed so the workflow was failing.
> Fix broken npm package update github action

- docs/3.0rc/develop/results.mdx
Examples used the deprecated block type. Updated to use the integration's block and made some small tweaks for clarity.
> Update results docs examples

- .github/ISSUE_TEMPLATE/1_bug_report.yaml
- .github/ISSUE_TEMPLATE/2_feature_enhancement.yaml
A few minor updates to our issue templates, including the removal of posted checklists.
> Some more updates to issue templates

- .github/workflows/api-compatibility-tests.yaml
- tests/test_futures.py
Pauses API compatibility tests while we iterate on the RC
> Pause compat tests

- requirements.txt
- src/prefect/blocks/notifications.py
- tests/blocks/test_notifications.py
backport of https://github.com/PrefectHQ/prefect/pull/14771
> Backport teams notif update for `2.x`

- src/integrations/prefect-gcp/prefect_gcp/workers/vertex.py
- src/integrations/prefect-gcp/tests/test_vertex_worker.py
There's a mismatch between the Vertex AI job configuration and the expected shape of the Vertex AI API call for service accounts. This PR ensures that the provided service account name is correctly propegated.
Closes https://github.com/PrefectHQ/prefect/issues/14742
> Fix setting of service account on Vertex AI jobs

- docs/.vuepress/config.js
Related to https://github.com/PrefectHQ/prefect/issues/14467
> Chore: Update link to legacy docs

- tests/test_futures.py
Fixes issue where task runs don't take place in `test_as_completed_yields_correct_order_dist` leading to test timeouts.
Related:  #14241
> Waits for task runs in as completed test

- src/prefect/runner/storage.py
- tests/runner/test_storage.py
> Persist include-submodules flag when using GitStorage

- src/prefect/runner/storage.py
- tests/runner/test_storage.py
> Persist include-submodules flag

- tests/test_flow_engine.py
Adds our event processing to a fix a few tests with client side orchestration enabled. One test I've mark as xfailed since preventing tasks from running paused flows is not yet supported.
> ensure flow engine tests support client side task run orchestration

- src/prefect/cli/_types.py
and update some very hard to understand variables names because I couldn't easily read what was going on
> A couple minor typing fixes

- docs/3.0rc/resources/daemonize-processes.mdx
fixes a couple incorrect and confusing things in the daemonized process docs
> fix docs typos

- src/integrations/prefect-dbt/prefect_dbt/cli/commands.py
closes https://github.com/PrefectHQ/prefect/issues/14865
backport of https://github.com/PrefectHQ/prefect/pull/13853
> allow passing `stream_output` to dbt tasks

- .github/workflows/prefect-client.yaml
The error in #14870 should have been caught by the `prefect-client` smoke test workflow, but it wasn't. This PR adds a matrix to run the `prefect-client` build and smoke test across all supported Python versions.
> Smoke test `prefect-client` across all supported Python versions

- .github/CODEOWNERS
Adds @zzstoatzz and @desertaxle to 2.x codeowners and removes team references
> Update 2.x codeowners

- docs/3.0rc/get-started/quickstart.mdx
Update the Quickstart to address Tyree and Taylor's feedback that more explicitly suggesting where to go for other infrastructure options in the Next Steps would be helpful.
> Minor updates to Quickstart

- src/integrations/prefect-docker/prefect_docker/deployments/steps.py
- src/integrations/prefect-docker/tests/deployments/test_steps.py
closes https://github.com/PrefectHQ/prefect/issues/9921
backport of https://github.com/PrefectHQ/prefect/pull/13286
> Docker step caching 2.x

- src/prefect/runtime/flow_run.py
- tests/results/test_flow_results.py
closes https://github.com/PrefectHQ/prefect/issues/14886
> Make flow version available in `runtime`

- src/prefect/runtime/flow_run.py
- tests/results/test_flow_results.py
backport of https://github.com/PrefectHQ/prefect/pull/14897
> Flow version in runtime 2.x

- ui/package-lock.json
- ui/package.json
Resolves:  https://github.com/PrefectHQ/prefect/security/dependabot/77
> Chore: Bump axios to v1.7.4

- src/prefect/infrastructure/kubernetes.py
- tests/infrastructure/test_kubernetes_job.py
> Allow for null command when building k8s job

- src/prefect/workers/base.py
- tests/workers/test_base_worker.py
Closes #11041 for 3.0
See https://github.com/PrefectHQ/prefect/pull/14923 for discussion
> Deep merge env vars

- src/prefect/client/schemas/actions.py
for consistency with the main `objects.WorkQueue`
> add constrained types for select `WorkQueue` action fields

- docs/3.0rc/develop/write-tasks.mdx
- docs/3.0rc/get-started/quickstart.mdx
> Fixes two broken links in docs

- .github/workflows/integration-package-tests.yaml
- src/integrations/prefect-redis/LICENSE
- src/integrations/prefect-redis/MANIFEST.in
- src/integrations/prefect-redis/README.md
- src/integrations/prefect-redis/prefect_redis/__init__.py
- src/integrations/prefect-redis/prefect_redis/credentials.py
- src/integrations/prefect-redis/prefect_redis/redis.py
- src/integrations/prefect-redis/pyproject.toml
- src/integrations/prefect-redis/tests/test_tasks.py
Migrates the code for `prefect-redis` from its current repository into the core library with the rest of the integrations. This PR doesn't make any code changes, but subsequent PRs will migrate Redis functionality in the core library to `prefect-redis` and add a `RedisRecordStore` implementation.
Related to https://github.com/PrefectHQ/prefect/issues/14914
> Migrates `prefect-redis` to the core repository

- src/prefect/cli/work_pool.py
- src/prefect/client/orchestration.py
- tests/cli/test_work_pool.py
- tests/client/test_prefect_client.py
2.x backport of https://github.com/PrefectHQ/prefect/pull/14967
> Backport `--overwrite` for `create_work_pool`

- requirements.txt
There are duplicate `griffe` requirements in `requirements.txt` and `requirements-client.txt` when it is only needed in `requirements-client.txt`.
Addresses https://github.com/PrefectHQ/prefect/issues/14975
> Remove duplicate `griffe` requirement

- requirements-client.txt
- src/prefect/blocks/core.py
- src/prefect/utilities/callables.py
> Update griffe requirements and corresponding imports

- src/prefect/client/orchestration.py
- src/prefect/deployments/flow_runs.py
- src/prefect/server/api/server.py
- src/prefect/utilities/asyncutils.py
RIP - this PR removes some dead code and unused kwargs throughout the codebase. Should have no effect.
> Go through some known dead code and remove it

- requirements-dev.txt
- requirements.txt
- tests/results/test_flow_results.py
- tests/server/schemas/test_states.py
Requirements audit: the 2.x prequel to #15002
> Upper bound critical requirements

- src/prefect/deployments/templates/prefect.yaml
- tests/cli/test_deploy.py
Adds support for `prefect.yaml` files specifying `Deployment.concurrency_limit`.
Related: #14934 
> Adds `concurrency_limit` to `prefect.yaml`

- src/prefect/cli/server.py
- tests/cli/test_start_server.py
> Adds the ability to run a server in the background

- src/prefect/runner/runner.py
- tests/runner/test_runner.py
`3.0` version of https://github.com/PrefectHQ/prefect/pull/15015
> Ensure Python executable is quoted in runner command on Windows

- docs/3.0rc/api-ref/index.mdx
- docs/mint.json
Adds redirects to mint.json in preparation for switching docs.prefect.io to point to the Mintlify docs site for GA. 
This PR has no effect on URLs at the moment, it will only affect things once docs.prefect.io DNS records are updated. 
This PR covers the 250 most visited 2.x docs pages at docs.prefect.io.
Spot tested to check that they work as expected.
> Adds docs redirects 

- docs/2.x/get-started/index.mdx
- docs/mint.json
Tested locally and everything works as expected.
> Adds a 2.x version to the v3 docs with a page that directs visitors to docs-2.prefect.io

- src/prefect/blocks/core.py
- tests/blocks/test_core.py
`2.x` port of #15011 
@GalLadislav should be given credit in the release notes.
> Add Block Type registration for its nested block types in field annotations

- src/prefect/task_engine.py
This PR is the first part of a larger refactor to simplify results.  In particular this PR shifts the responsibility for result persistence to the engine + transaction by avoiding setting a transaction store if result persistence is disabled for a task. This will set the stage nicely for removing the `ResultFactory` and `UnpersistedResult` class entirely.
> Avoid result factories if persistence is turned off for a task

- src/prefect/states.py
This PR addresses [this comment](https://github.com/PrefectHQ/prefect/pull/15084#discussion_r1733183816) from a previous PR.
> Updates warning message when result persistence fails

- src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
- src/integrations/prefect-kubernetes/tests/test_worker.py
backports https://github.com/PrefectHQ/prefect/pull/14813
> backport `prefect-kubernetes` fix

- src/prefect/cli/server.py
Now that we're using `anyio.open_process` when starting the Prefect server, we don't need any extra quoting to work on Windows; `anyio.open_process` handles that. This PR removes the quoting to fix `prefect server start` on Windows. 
Closes https://github.com/PrefectHQ/prefect/issues/15101
> Fixes `prefect server start` for Windows machines

- docs/3.0rc/automate/add-schedules.mdx
fixing some code blocks formatting
> minor docs formatting fixes

- src/prefect/cli/server.py
> Fix `prefect server start` for Windows machines

- docs/3.0rc/develop/artifacts.mdx
Updates language to say that artifacts should be defined in the context of a flow or task - so user's don't get a deprecation warning. 
Also updates formatting, links, and wording to a bit for consistency and clarity and .
> Update artifacts doc page

- docs/3.0rc/get-started/quickstart.mdx
Updates some of the language in the quickstart without changing the core content.
> Update language in quickstart

- docs/3.0rc/develop/write-tasks.mdx
This PR moves a couple of sections around and removes a couple of sections that are more advanced concepts.
> Update write tasks page for clarity

- docs/contribute/dev-contribute.mdx
- docs/contribute/docs-contribute.mdx
- docs/contribute/index.mdx
- docs/contribute/styles-practices.mdx
- docs/mint.json
- docs/snippets/fork.mdx
Our contribution docs read awkwardly to me so I went through them and touched them up. I also separated out documentation contributions from code contributions.
> Go through contributing docs

- docs/3.0rc/deploy/infrastructure-concepts/work-pools.mdx
- docs/mint.json
This PR updates the work pools doc for flow and clarity. Most of the removed sections are housed in other places in the docs. The one exception is information about `flow.deploy`, which doesn't have a home right now. My plan is to create a separate page for python-based deployments in a subsequent PR.
> Update work pools doc for flow and clarity

- docs/3.0rc/manage/cloud/manage-users/secure-access-by-ip-address.mdx
- docs/mint.json
This PR adds a new page to the docs for Prefect Cloud IP Allowlisting. 
Related to #15087.
> Add a docs page for Prefect Cloud IP Allowlisting.

- docs/3.0rc/develop/logging.mdx
> Add note for remote logging

- docs/3.0rc/api-ref/rest-api/server/schema.json
- src/prefect/server/api/server.py
to address a possible race condition
```
RuntimeError: Timed out while attempting to connect to ephemeral Prefect API server
/usr/local/lib/python3.12/site-packages/prefect/client/orchestration.py, line 218, in get_client
```
> move ephemeral server port finding to `start`

- src/prefect/cli/cloud/ip_allowlist.py
This PR follows from #15087 and includes a small change to error handling around server responses to better surface server-side validation errors.
> Fix server-side validation errors in IP allowlist CLI being swallowed.

- docs/3.0rc/develop/manage-states.mdx
> Update minor style issues on manage-states.mdx

- docs/3.0rc/deploy/infrastructure-concepts/deploy-via-python.mdx
- docs/mint.json
This PR adds a docs page about deploying flows via the Python SDK. Documentation about deploying via Python was co-located with the work pools documentation but was removed in https://github.com/PrefectHQ/prefect/pull/15127.
> Adds docs page for deploying flows via Python

- docs/3.0rc/develop/task-caching.mdx
This PR updates docs to reflect cache policy `RUN_ID` renaming to `FLOW_RUN_ID`.
> Update FLOW_RUN_ID -> RUN_ID in docs

- docs/3.0rc/develop/task-runners.mdx
- src/prefect/futures.py
> Add docs link to future garbage collection message

- docs/3.0rc/develop/logging.mdx
- docs/mint.json
Rewrites a large part of the logging configuration doc for clarity.
> Rewrite logging config doc

- docs/3.0rc/develop/index.mdx
- docs/3.0rc/manage/cloud/index.mdx
- docs/3.0rc/resources/big-data.mdx
- docs/mint.json
> Updates redirects, removes broken links, and updates subsection index entries

- src/integrations/prefect-databricks/prefect_databricks/flows.py
- src/integrations/prefect-databricks/tests/test_flows.py
2.x version of https://github.com/PrefectHQ/prefect/pull/15182
closes https://github.com/PrefectHQ/prefect/issues/15180
> (2.x) restore job submission handler in `jobs_runs_submit_and_wait_for_completion`

- tests/blocks/test_notifications.py
Fixes tests related to the `apprise` version bump
> Fix tests for new `apprise` version

- src/prefect/variables.py
> 2.x variable return value fix

- docs/overrides/main.html
Updates the 2.x docs site header banner text for 3.0 GA. 
This change won't go live on the site without a docs release or a 2.x version release.
> Update docs header link and language for 3.0 GA

- .github/workflows/integration-package-release.yaml
The release pipeline for integration packages is specifically looking for `rc` in the tag. This PR fixes that.
> Fix release pipeline for integration packages

- docs/3.0/resources/upgrade-to-prefect-3.mdx
- docs/integrations/prefect-azure/index.mdx
- docs/integrations/prefect-dbt/index.mdx
- scripts/generate_sdk_docs.py
now that 3.x is default, we should not recommend `--pre`
> no longer recommend `--pre` flag in docs

- src/prefect/tasks.py
- tests/test_tasks.py
> Fix task key computation 

- docs/integrations/prefect-aws/index.mdx
- docs/integrations/prefect-azure/index.mdx
- docs/integrations/prefect-bitbucket/index.mdx
- docs/integrations/prefect-dask/index.mdx
- docs/integrations/prefect-databricks/index.mdx
- docs/integrations/prefect-dbt/index.mdx
- docs/integrations/prefect-docker/index.mdx
- docs/integrations/prefect-email/index.mdx
- docs/integrations/prefect-gcp/index.mdx
- docs/integrations/prefect-github/index.mdx
- docs/integrations/prefect-gitlab/index.mdx
- docs/integrations/prefect-kubernetes/index.mdx
- docs/integrations/prefect-ray/index.mdx
- docs/integrations/prefect-shell/index.mdx
- docs/integrations/prefect-slack/index.mdx
- docs/integrations/prefect-snowflake/index.mdx
- docs/integrations/prefect-sqlalchemy/index.mdx
Please let me know if you have any suggested changes. When we're set, I'll push updates for the other packages.
To merge when packages have been updated for GA.
> Update install instructions for prefect-azure for 3.0GA

- docs/3.0/manage/cloud/manage-users/secure-access-by-ip-address.mdx
This PR updates Prefect Cloud IP allowlisting docs to change some of the opening language.
> Update opening language of allowlisting docs.

- src/prefect/flows.py
- tests/test_flows.py
closes https://github.com/PrefectHQ/prefect/issues/15206
> remove duplicate `pull_code` instruction

- src/integrations/prefect-kubernetes/prefect_kubernetes/credentials.py
- src/integrations/prefect-kubernetes/tests/test_credentials.py
Ports the changes in #15209 to the `2.x` branch
> prefect-kubernetes: add missing config loaders

- .gitignore
- README.md
- docs/contributing/overview.md
- docs/getting-started/installation.md
- docs/integrations/prefect-aws/index.md
- docs/integrations/prefect-azure/index.md
- docs/integrations/prefect-bitbucket/index.md
- docs/integrations/prefect-dask/index.md
- docs/integrations/prefect-databricks/index.md
- docs/integrations/prefect-dbt/index.md
- docs/integrations/prefect-docker/index.md
- docs/integrations/prefect-email/index.md
- docs/integrations/prefect-gcp/index.md
- docs/integrations/prefect-github/index.md
- docs/integrations/prefect-gitlab/index.md
- docs/integrations/prefect-kubernetes/index.md
- docs/integrations/prefect-ray/index.md
- docs/integrations/prefect-shell/index.md
- docs/integrations/prefect-slack/index.md
- docs/integrations/prefect-snowflake/index.md
- docs/integrations/prefect-sqlalchemy/index.md
- docs/tutorial/index.md
> Update install instructions in 2.x docs

- src/integrations/prefect-kubernetes/prefect_kubernetes/utilities.py
- src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
- src/integrations/prefect-kubernetes/tests/test_utilities.py
- src/integrations/prefect-kubernetes/tests/test_worker.py
> Add `KeepAliveClientRequest` class for k8s async client 2.x

- docs/3.0/deploy/infrastructure-concepts/deploy-via-python.mdx
- docs/3.0/deploy/infrastructure-concepts/work-pools.mdx
- docs/3.0/deploy/infrastructure-examples/kubernetes.mdx
- docs/3.0/manage/cloud/index.mdx
A relative link in the docs needs a `/` at the start of it.
> Fixes a few broken links in the docs

- docs/3.0/deploy/infrastructure-concepts/prefect-yaml.mdx
- docs/3.0/deploy/infrastructure-examples/managed.mdx
This adds the missing quotation marks mentioned in #10420, fixes indentation for work pools, and makes yaml indentation more consistent. 
> Improve prefect.yaml docs

- tests/utilities/test_callables.py
> Fix test failures for `pydantic==2.9.0`

- src/prefect/results.py
small type fix found while looking for improved import strategies
> use `is not` for type comparison instead of `!=`

- .github/workflows/docker-images.yaml
Ports a change in https://github.com/PrefectHQ/prefect/pull/13932 to `2.x` branch to ensure we install the correct `prefect-kubernetes` version in the Kubernetes flavored Docker image.
> Use `kubernetes` extra when building Docker image

- .github/release.yml
Updates release notes template to include a dedicated Enhancements section - I thought the "New Features" title was a bit much for some of the improvements.
> Add dedicated enhancements section

- docs/3.0/develop/blocks.mdx
Rewrites the block page in our docs. Closes https://github.com/PrefectHQ/prefect/issues/14337
> Rewrite block page in docs

- .github/workflows/labeler.yml
3.0 analogue of #15113 - see description there
> Fix labeler job

- docs/3.0/resources/upgrade-to-prefect-3.mdx
follow up to https://github.com/PrefectHQ/prefect/pull/15271, missed another application of [suggestion](https://github.com/PrefectHQ/prefect/pull/15271#discussion_r1748086079)
> fix inconsistent word in upgrade guide

- docs/3.0/develop/blocks.mdx
- docs/integrations/use-integrations.mdx
- add note about extras in Use Integrations section
- reorder table in Pre-built Blocks section
> Update integrations docs

- ui/src/compositions/useCreateCan.ts
Removing the flag from projects now that its been enabled for a while without issue.
> Remove feature flag for nested task runs on the run graph

- src/prefect/settings.py
Ports https://github.com/PrefectHQ/prefect/pull/15311 to the `2.x` branch.
> Disable HTTP2 by default

- src/integrations/prefect-databricks/prefect_databricks/models/jobs.py
backport of https://github.com/PrefectHQ/prefect/pull/15313
related to https://github.com/PrefectHQ/prefect/issues/15308
> reintroduce job model for `prefect-databricks` in 2.x

- src/integrations/prefect-dbt/prefect_dbt/cli/commands.py
backports https://github.com/PrefectHQ/prefect/pull/15317
related to https://github.com/PrefectHQ/prefect/issues/15235
> Update `DbtCoreOperation` docstring 2.x

- docs/3.0/automate/events/automations-triggers.mdx
there aren't any good examples that I could find using `for_each` in the docs, so this PR adds one
> add `for_each` trigger example

- src/integrations/prefect-dask/prefect_dask/task_runners.py
- src/integrations/prefect-dask/tests/test_task_runners.py
In https://github.com/PrefectHQ/prefect/pull/14829 the context hydration process started initializing a task runner to enable submission of tasks from other tasks running in remote infrastructure. This lead to errors in local Dask setups because the hydration process would trigger another local cluster creation.
This PR fixes that issue by updating the `__enter__` method on the `DaskTaskRunner` to discover an existing cluster by inspecting the global `distributed` client available if running on a Dask worker.
Closes https://github.com/PrefectHQ/prefect/issues/15260
> Fix issue where `DaskTaskRunner` was attempting to create a duplicate cluster

- src/prefect/testing/utilities.py
- tests/testing/test_utilites.py
Closes https://github.com/PrefectHQ/prefect/issues/15075
Closes https://github.com/PrefectHQ/prefect/issues/15353
> Make `prefect_test_harness` startup timeout configurable

- docs/3.0/develop/logging.mdx
> Update logging.mdx to fix title display

- docs/integrations/prefect-dbt/index.mdx
> Fix broken image link and update formatting in prefect-dbt

- src/prefect/deployments/runner.py
- src/prefect/flows.py
- tests/test_flows.py
closes https://github.com/PrefectHQ/prefect/issues/15380
> preserve `flow.name` with `RunnerDeployment.from_storage`

- src/prefect/blocks/webhook.py
- tests/blocks/test_webhook.py
Closes #10885 -- This code allows for the insecure webhooks to be used.  Tests have been added to verify both functionality and that the insecure client is being used.
> Adding support for insecure webhooks

- docs/3.0/resources/upgrade-to-prefect-3.mdx
see https://prefect-community.slack.com/archives/C048ZHT5U3U/p1726774790546129
> add note on terminal unawaited coro

- src/prefect/cli/deploy.py
- tests/cli/test_deploy.py
Closes #15416.
Closes OSS-5635
This PR adds a `--collision-strategy` option to the `prefect deploy` CLI for configuring the behavior once a deployment's concurrency limit has been reached. 
> Add --collision-strategy to `prefect deploy` CLI.

- docs/3.0/automate/events/webhook-triggers.mdx
Adds documentation on securing webhooks with service accounts in Prefect Cloud.
> Add docs on securing webhooks with service accounts

- src/integrations/prefect-sqlalchemy/prefect_sqlalchemy/database.py
- src/integrations/prefect-sqlalchemy/tests/test_database.py
closes https://github.com/PrefectHQ/prefect/issues/15490
> Allow oracle connection urls

- src/prefect/cli/deploy.py
- tests/cli/test_deploy.py
closes https://github.com/PrefectHQ/prefect/issues/15471
> Don't prompt custom image build for managed pools in `prefect deploy`

- src/integrations/prefect-dbt/pyproject.toml
- src/integrations/prefect-dbt/tests/conftest.py
Removes an import for a no longer existing class in the `prefect-sqlalchemy` integration from the `prefect-dbt` integration.
Looks like this class was removed here: https://github.com/PrefectHQ/prefect/commit/3ffaeb99dcb40bbbd4b8c79b42aa4018d825702b and the current `pyproject.toml` pins the version of `prefect-sqlalchemy` to https://github.com/PrefectHQ/prefect/blob/main/src/integrations/prefect-dbt/pyproject.toml#L43 after when this was removed 
> Use `ConnectionComponents` components from `prefect-sqlalchemy` in `prefect-dbt`

- tests/test_states.py
The fix for the https://github.com/PrefectHQ/prefect/issues/14927 was included in https://github.com/PrefectHQ/prefect/pull/15264. This PR adds a test to prevent regression so we can close the issue.
Closes https://github.com/PrefectHQ/prefect/issues/14927
> Add regression test for arbitrary state data

- docs/3.0/deploy/index.mdx
- docs/3.0/resources/upgrade-to-prefect-3.mdx
- docs/3.0/resources/whats-new-prefect-3.mdx
Closes #15420
Also fixes a few other broken links.
> Deploy docs overview improvements

- src/prefect/flows.py
backports: https://github.com/PrefectHQ/prefect/pull/15528
> [2.x] Fix flow typing when passing return_state to a coroutine

- src/prefect/server/models/flow_runs.py
- tests/server/models/test_flow_runs.py
- tests/server/orchestration/api/test_flow_runs.py
@jeanluciano check this out. I can't get the tests to pass because of session wonkiness. 😅 But this should be what we need.
> [WIP] Decrement active limit when deleting a flow from a deployment with a concurrency limit

- src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
- src/integrations/prefect-kubernetes/tests/test_worker.py
- src/prefect/workers/base.py
closes https://github.com/PrefectHQ/prefect/issues/15450
tested [here](https://github.com/zzstoatzz/prefect-pack/blob/main/prefect.yaml#L53-L66)
> override `_coerce_env` for k8s worker

- docs/guides/migration-guide.md
Follow on to #15544 and replaces #15554
> Minor changes to Prefect 1.0 migration guide

- src/integrations/prefect-ray/prefect_ray/task_runners.py
- src/integrations/prefect-ray/tests/test_task_runners.py
This PR fixes an issue where Ray workers were crashing when using the `RayTaskRunner`. The `RayTaskRunner` was calling `ray.shutdown` every time it exited, which would kill the worker that a submitted task was running on. We have a `RayTaskRunner` running on the worker to allow task submission from other tasks, so now the task runner will only shutdown the Ray driver when **not** running on a Ray worker.
Closes https://github.com/PrefectHQ/prefect/issues/15539
> Avoid shutting down Ray driver when running on a Ray worker

- docs/3.0/get-started/index.mdx
Adjusts first docs example so that the Quickstart follows without confusion - based on user feedback.
Also makes the first example runnable as is against Cloud or server without needing to run a deployment and pass params.
> Update first docs example

- src/prefect/_internal/pydantic/v2_schema.py
- src/prefect/flows.py
- tests/test_flows.py
closes https://github.com/PrefectHQ/prefect/issues/15603
> [2.x] Fix validation of `pydantic.v1.SecretStr` in flow signature

- src/prefect/futures.py
utilities like `as_completed` were losing the info on what the type of the `PrefectFuture` was (i.e. `R`)
> avoid losing typing info in `PrefectFuture`

- ui/src/components/FlowStats.vue
> Chore: remove confusing filter from Flow page

- .github/ISSUE_TEMPLATE/2_feature_enhancement.yaml
add note to clarify that enhancement issues will only be considered for 3.x
> Add enhancement note

- src/prefect/utilities/dockerutils.py
- tests/utilities/test_dockerutils.py
closes https://github.com/PrefectHQ/prefect/issues/15637
> fix prefect version parsing error

- docs/3.0/manage/settings-and-profiles.mdx
follow on to https://github.com/PrefectHQ/prefect/pull/15644
> follow on suggestion: simplify phrasing

- docs/3.0/deploy/index.mdx
Adds vertexAI to list of work pools, fixes typo, improves intro.
> Minor updates to deploy overview

- .github/workflows/nightly-release.yaml
- .github/workflows/npm_update_latest_prefect.yaml
Relates to [PLA-389](https://linear.app/prefect/issue/PLA-389/create-variable-set-to-hold-all-of-marvin-pats-in-a-single-place-in)
> chore: update secret ref

- src/integrations/prefect-kubernetes/prefect_kubernetes/credentials.py
- src/integrations/prefect-kubernetes/prefect_kubernetes/jobs.py
- src/integrations/prefect-kubernetes/tests/test_jobs.py
backports https://github.com/PrefectHQ/prefect/pull/15655
> [2.x] await `load_kube_config`

- src/prefect/settings.py
- tests/test_settings.py
Profile version of https://github.com/PrefectHQ/prefect/pull/15657
> Add tests for specifying each setting via a profile

- src/prefect/runner/runner.py
> Fix bug that causes `Runner` to exit early

- docs/3.0/deploy/infrastructure-examples/docker.mdx
Adds a few minor notes to Docker page.
> Add a few notes to Docker docs page

- docs/3.0/deploy/infrastructure-examples/serverless.mdx
- docs/3.0/develop/inputs.mdx
Fix formatting on a number of docs tables. 
Find/replace suggests we should have them all updated now.
Addresses user feedback on table formatting.
> Improve table formatting in docs

- docs/3.0/deploy/infrastructure-concepts/prefect-yaml.mdx
- docs/3.0/deploy/infrastructure-concepts/store-flow-code.mdx
- docs/3.0/deploy/infrastructure-concepts/work-pools.mdx
- docs/3.0/deploy/infrastructure-concepts/workers.mdx
- docs/3.0/deploy/infrastructure-examples/serverless.mdx
- docs/3.0/resources/big-data.mdx
- docs/contribute/develop-a-new-worker-type.mdx
- docs/integrations/catalog/TEMPLATE.yaml
- docs/integrations/catalog/prefect-databricks.yaml
- docs/integrations/index.md
- docs/integrations/integrations.mdx
- docs/integrations/prefect-aws/ecs_guide.mdx
- docs/integrations/prefect-aws/index.mdx
- docs/integrations/prefect-azure/aci_worker.mdx
- docs/integrations/prefect-azure/index.mdx
- docs/integrations/prefect-bitbucket/index.mdx
- docs/integrations/prefect-dask/index.mdx
- docs/integrations/prefect-dbt/index.mdx
- docs/integrations/prefect-docker/index.mdx
- docs/integrations/prefect-gcp/gcp-worker-guide.mdx
- docs/integrations/prefect-gcp/index.mdx
- docs/integrations/prefect-snowflake/index.mdx
- docs/integrations/use-integrations.mdx
- index.md
Updates a number of links that were pointing to old GitHub Pages for integrations.
Also updates links in integrations to be robust to future docs version changes.
> Fix docs links for integrations

- flows/serve_a_flow.py
saw a couple timing related flakes in the integrations tests, e.g. https://github.com/PrefectHQ/prefect/pull/15719
> give more time for integration serve flow

- src/integrations/prefect-aws/prefect_aws/client_parameters.py
- src/integrations/prefect-aws/tests/test_client_parameters.py
Ports `prefect-aws` from #15574 to 2.x branch
> Ports #15574 to 2.x

- docs/3.0/deploy/infrastructure-concepts/prefect-yaml.mdx
- docs/3.0/deploy/infrastructure-concepts/store-flow-code.mdx
this example was still using `push: true`, which is now split into a distinct step
> updated docker push step in docs

- docs/integrations/prefect-azure/aci_worker.mdx
Now works with Prefect 3.
cc: @biancaines - TY!
> Update Docker image reference in aci_worker docs page

- flows/deploy.py
> Ignore errors when cleaning up after deploy integration test

- .github/workflows/markdown-tests.yaml
after chatting with @bunchesofdonald, we are just disabling this until https://github.com/PrefectHQ/prefect/issues/15781 is resolved during scheduled reliability work on friday
> disable automatic markdown tests

- .github/ISSUE_TEMPLATE/1_bug_report.yaml
The PR updates the bug issue template to be more explicit about the format of version information that is most useful. It also updates the template to direct submitters to open a GitHub discussion if they have a usage question.
> Update instructions on bug report issue template

- docs/integrations/prefect-databricks/index.mdx
> Fix typo in prefect-databricks

- src/prefect/workers/base.py
- tests/workers/test_base_worker.py
> Include env defaults from `variables.properties.env` in deep merge 2.x

- docs/3.0/resources/upgrade-to-prefect-3.mdx
> add schedule gotcha

- docs/3.0/api-ref/rest-api/server/schema.json
- src/prefect/cli/_prompts.py
- src/prefect/cli/deploy.py
- src/prefect/client/schemas/actions.py
- src/prefect/client/schemas/objects.py
- src/prefect/deployments/base.py
- src/prefect/deployments/schedules.py
- src/prefect/server/database/orm_models.py
- src/prefect/server/models/deployments.py
- src/prefect/server/schemas/actions.py
- src/prefect/server/schemas/core.py
- src/prefect/settings/models/root.py
- tests/cli/test_deploy.py
- tests/server/schemas/test_actions.py
- tests/test_settings.py
closes https://github.com/PrefectHQ/prefect/issues/15661
supersedes https://github.com/PrefectHQ/prefect/pull/15663
> remove `max_active_runs` and `catchup` fields

- requirements-client.txt
- requirements.txt
- setup.cfg
- src/prefect/blocks/notifications.py
- src/prefect/blocks/webhook.py
- src/prefect/utilities/urls.py
- tests/blocks/test_notifications.py
- tests/blocks/test_webhook.py
- tests/conftest.py
- tests/deployment/test_steps.py
- tests/utilities/test_urls.py
Backports https://github.com/PrefectHQ/prefect/pull/15272 to 2.x
> Backport security enhancement

- src/prefect/cli/block.py
unfortunately we don't always want this, so its not cut and dry to global find replace
> fix non `soft_wrap` link in `prefect block register`

- src/integrations/prefect-dbt/prefect_dbt/__init__.py
Closes https://github.com/PrefectHQ/prefect/issues/15879
> Add DbtCloudJob block to top level import

- src/integrations/prefect-dask/prefect_dask/task_runners.py
- src/integrations/prefect-dask/tests/test_task_runners.py
closes #15904 
updates `DaskTaskRunner` to respect `wait_for` and adds some tests
> fix `wait_for` for `DaskTaskRunner`

- .github/workflows/integration-tests.yaml
- old-sqlite.Dockerfile
- src/prefect/server/database/migrations/versions/sqlite/2022_04_23_114831_fd966d4ad99c_rename_block_to_blockbasis_and_.py
- src/prefect/server/database/migrations/versions/sqlite/2024_09_16_162719_4ad4658cbefe_add_deployment_to_global_concurrency_.py
related to  https://github.com/PrefectHQ/prefect/issues/15901 https://github.com/PrefectHQ/prefect/issues/15903
`UPDATE ... FROM` is [not supported in older versions](https://www.sqlite.org/lang_update.html) of sqlite
instead in this PR we use a subquery
---
i have reproduced this with the dockerfile in this PR, which we will using going forward to run integration tests against
> fix sqlite migration

- docs/3.0/manage/self-host.mdx
> Fix typo on self-host.mdx

- docs/3.0/deploy/infrastructure-concepts/workers.mdx
Fixes some small nits in the worker logging docs. 
> Fix some nits in the worker logging docs

- src/prefect/workers/base.py
Adds in a flow run log to the worker's log page if the worker logging experiment is enabled and we have a backend_id. 
> Add in a link to the worker logs page

- src/prefect/workers/base.py
late submission for reliabilty day: just a mypy nit noticed when catching up on some changes
> handle possible `None` value

- docs/3.0/develop/manage-states.mdx
fix imports and hook signature
> clarify state hook docs

- src/prefect/workers/base.py
With the change in URL for's parameters I committed in a swapped set of parameters for the Baseworker. I fixed the parameters and added in a try/except to make this log statement not bring down the worker if it didn't work.
> Fixes the arguments for the url generation in BaseWorker

- src/prefect/settings/sources.py
- tests/test_settings.py
Fixes a bug where profiles and toml files could override settings values set via environment variable. The root cause is that fields that have multiple `validation_alias` choices will have their own internal priority among those validation choices. This means that if a lower priority source (like a profile) used a higher priority alias than a higher priority source (like an environment variable) the lower priority source would win.
The fix proposed in this PR is to ensure that we are using the lowest priority validation aliases in the profile and toml file sources. This will take the `validation_alias` priority out of the equation when determining source priority.
Closes https://github.com/PrefectHQ/prefect/issues/15981
> Fix bugs in precedence of settings sources for settings with multiple validation aliases

- .github/release.yml
Categorizes docs as "Development & Tidiness" in release notes
> Categorize docs in release notes

- docs/3.0/deploy/infrastructure-concepts/customize.mdx
> Fix formatting for output file tree structure in customize.mdx

- README.md
Remove Discourse as we are sunsetting this.
> Remove Discourse from README

- docs/3.0/manage/cloud/connect-to-cloud.mdx
- docs/3.0/manage/cloud/manage-users/api-keys.mdx
> Improve instructions for connecting to Cloud

- src/prefect/workers/base.py
- tests/workers/test_base_worker.py
> Fix env var deep merge order on worker 2.x

- docs/v3/resources/upgrade-agents-to-workers.mdx
`prefect.storage.GitHub` is not a real class
> fix agents -> workers doc examples that reference non-existent code

- src/integrations/prefect-aws/pyproject.toml
follow on to https://github.com/PrefectHQ/prefect/pull/16053
> updated `async_dispatch` requires `prefect>=3.1.3`

- src/integrations/prefect-aws/prefect_aws/client_waiter.py
- src/integrations/prefect-aws/tests/test_client_waiter.py
related to https://github.com/PrefectHQ/prefect/issues/15008
> migrate `prefect_aws.client_waiter` off `sync_compatible`

- src/integrations/prefect-aws/prefect_aws/lambda_function.py
- src/integrations/prefect-aws/tests/test_lambda_function.py
> migrate `prefect_aws.lambda_function` off `sync_compatible`

- docs/mint.json
Docs break if click on settings page with self-referential redirect.
> Fix redirect

- src/prefect/server/models/deployments.py
As part of our investigation into the timeouts of both RecentDeploymentsScheduler and regular Scheduler services, we bumped into an [unexpectedly slow query](https://github.com/prefecthq/prefect/blob/2.x/src/prefect/server/models/deployments.py#L696-L707) in `_insert_scheduled_flow_runs` function in model/deployments.py:
```python
inserted_rows = (
sa.select(db.FlowRun.id)
.join(
db.FlowRunState,
db.FlowRun.id == db.FlowRunState.flow_run_id,
isouter=True,
)
.where(
db.FlowRun.id.in_([r["id"] for r in runs]),
db.FlowRunState.id.is_(None),
)
)
```
It was taking 30-60 seconds when the number of runs is > ~34. Deeper investigation revealed that Postgres used a query plan that included sequential scan of `flow_run_states` table and we have 110M rows there. Here's the plan for reference:
``` …
```
> Improve scheduled flows query

- CODE_OF_CONDUCT.md
related to https://github.com/PrefectHQ/prefect/issues/16103
we may want to make this an org level readme as mentioned by @olearycrew
> copy `CODE_OF_CONDUCT.md` to repo

- client/README.md
- docs/v3/resources/recipes.mdx
Removes some old discourse references that are no longer relevant with the sunsetting of Discourse
> Remove some stray discourse refs

- docs/v3/deploy/infrastructure-examples/docker.mdx
> update docker example flow

- ui-v2/src/components/concurrency/global-concurrency-limit-empty-state.test.tsx
- ui-v2/src/components/concurrency/global-concurrency-limit-empty-state.tsx
1. Adds `GlobalConcurrencyLimitEmptyState` which will be used when developing concurrency route
2. Adds simple test to ensure callback is being fired
Good exercise to develop using the re-usable UX components created in the previous PRs
> [UI v2] feat: Adds GlobalConcurrencyLimitEmptyState component to be used in concurrency route development

- src/prefect/_internal/concurrency/api.py
- src/prefect/client/schemas/objects.py
- src/prefect/context.py
- src/prefect/flow_engine.py
- src/prefect/flows.py
- src/prefect/task_runners.py
- src/prefect/tasks.py
- src/prefect/utilities/visualization.py
aw man, that type completeness check is a tough cookie
> make `flow` and `task` decorators pass strict typing

- src/prefect/logging/highlighters.py
> [typing] highlighters.py

- src/prefect/_internal/compatibility/migration.py
@zzstoatzz lmk if these PRs should be meatier
> [typing] Update migration.py

- ui-v2/src/components/concurrency/concurrency-page.tsx
- ui-v2/src/components/concurrency/concurrency-tabs.tsx
- ui-v2/src/components/flows/detail/index.tsx
- ui-v2/src/components/ui/docs-link.tsx
- ui-v2/src/components/ui/empty-state.stories.tsx
- ui-v2/src/components/ui/empty-state.tsx
- ui-v2/src/components/ui/icons/icons.stories.tsx
- ui-v2/src/hooks/use-is-overflowing.ts
Ran codemods based on upgrading to React19 (to be ready for migration): https://react.dev/blog/2024/04/25/react-19-upgrade-guide
Ran:
```
npx codemod@latest react/19/migration-recipe
npx types-react-codemod@latest preset-19 ./
```
> [UI v2] chore: Running react-19 codemods

- docs/v3/api-ref/rest-api/server/flow-runs/download-logs.mdx
- src/prefect/server/api/flow_runs.py
closes https://github.com/PrefectHQ/prefect/issues/16279
---
> fix typing and route in flow run logs download api ref

- tests/test_flows.py
closes https://github.com/PrefectHQ/prefect/issues/16258
> avoiding timing issue in flaky test

- docs/v3/tutorials/debug.mdx
- docs/v3/tutorials/platform.mdx
The operator tutorials require the use of a Prefect Cloud account with multiple workspaces, which free accounts do not support. This PR updates the verbiage in the operator tutorials to reflect this.
> Clarify that the operator tutorials are intended for paid accounts

- src/prefect/_internal/schemas/validators.py
- src/prefect/results.py
- src/prefect/serializers.py
This PR fixes typing errors in `prefect.serializers`.
Related to https://github.com/PrefectHQ/prefect/issues/16292
> [typing] `prefect.serializers`

- .github/workflows/time-docker-build.yaml
> only run docker build bench on push to main

- ui-v2/biome.json
- ui-v2/src/components/ui/json-input.tsx
- ui-v2/src/components/variables/variable-dialog/variable-dialog.tsx
- ui-v2/src/routeTree.gen.ts
- ui-v2/tests/variables/variables.test.tsx
Fixes the add/edit variable dialog not closing on submit and the tab order for the json input component. I also excluded `routeTree.gen.ts` from `biome` because it's a generated file and `biome` formatting it was driving me crazy.
> Fix closing and tab order issues for variables dialog

- src/prefect/tasks.py
- tests/test_tasks.py
> Early error on bad retry delay types

- docs/v3/deploy/infrastructure-concepts/work-pools.mdx
small nit from checking out our [llms.txt](https://docs.prefect.io/llms-full.txt) we get for free from mintlify
> update example output for `prefect work-pool inspect`

- src/prefect/cli/global_concurrency_limit.py
- tests/cli/test_global_concurrency_limit.py
same idea as https://github.com/PrefectHQ/prefect/pull/15653
```python
» prefect gcl delete task_throttle
Are you sure you want to delete global concurrency limit with name 'task_throttle'? [y/N]: y
Global concurrency limit 'task_throttle' not found.
```
```python
» prefect gcl delete task_throttle
Global concurrency limit 'task_throttle' not found.
```
> dont ask to confirm deletion of non-existent gcl

- docs/v3/develop/settings-ref.mdx
- schemas/settings.schema.json
- src/prefect/client/orchestration.py
- src/prefect/server/api/server.py
- src/prefect/settings/__init__.py
- src/prefect/settings/models/api.py
- src/prefect/settings/models/server/api.py
- tests/client/test_prefect_client.py
- tests/test_settings.py
- ui/src/App.vue
- ui/src/pages/AppRouterView.vue
- ui/src/pages/Unauthenticated.vue
- ui/src/router/index.ts
- ui/src/router/routes.ts
- ui/src/services/adminApi.ts
- ui/src/services/csrfTokenApi.ts
- ui/src/utilities/api.ts
Builds on #16408 
note the sidebar renders twice, and the basic token is stored in localstorage (not ideal). but works!
> Add basic auth UI

- src/prefect/cli/deploy.py
- tests/cli/test_deploy.py
closes https://github.com/PrefectHQ/prefect/issues/16409
> fix passing `enforce_parameter_schema` in `prefect deploy`

- ui-v2/src/components/ui/docs-link.stories.tsx
- ui-v2/src/components/ui/empty-state.stories.tsx
- ui-v2/src/components/ui/icons/icons.stories.tsx
- ui-v2/src/components/ui/typography/typography.stories.tsx
1. Removes unnecessary storybook story nesting. Helps remove unnecessary clicks
Before:
After: 
> [UI v2] chore: Removes unnecessary storybook story nesting

- src/prefect/agent.py
- src/prefect/deployments/deployments.py
- src/prefect/engine.py
- src/prefect/filesystems.py
- src/prefect/infrastructure/__init__.py
- src/prefect/infrastructure/base.py
- src/prefect/variables.py
- src/prefect/workers/block.py
- src/prefect/workers/cloud.py
> [typing] Annotate all getattr_migration callsites

- ui-v2/src/hooks/use-stepper.test.ts
- ui-v2/src/hooks/use-stepper.ts
1. Adds declarative hook `useStepper` to manage state for future UX that requires steps
2. Adds test for `useStepper` hook. 
Will most likely iterate on this hook as we start integrating this hook with UI
> [UI v2] feat: Adds useStepper hook to be used for automations creation wizard

- ui-v2/src/storybook/utils/index.ts
- ui-v2/src/storybook/utils/react-query-decorator.tsx
- ui-v2/src/storybook/utils/router-decorator.tsx
1. Adds storybook decorator so that we can create stories that uses `@tanstack/react-router` components
2. Adds storybook decorator so that we can create stories that has `@tanstack/react-query` components embedded. Comes with the devtool so that we can debug when developing with storybook
Comes from: https://gist.github.com/jaens/693bd767b0f18d6577265815f6831c7a
> [UI v2] feat: Adds router and react-query storybook decorator

- flows/load_flows_concurrently.py
see https://github.com/PrefectHQ/prefect/pull/16458#discussion_r1894519106
> address typing nits

- .github/dependabot.yml
Updates tags to use `ui-replatform` tag
Separate tanstack dependencies for router and query
> feat: Updating tags and groups for ui-v2 dependabot

- .github/pull_request_template.md
The current link in the PR template for contribution guidelines is outdates, this PR corrects it
- ~~[ ] This pull request references any related issue by including "closes `<link to issue>`~~
- ~~[ ] If this pull request adds new functionality, it includes unit tests that cover the changes~~
- ~~[ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.~~
- ~~[ ] If this pull request adds functions or classes, it includes helpful docstrings.~~
> fix: Correct link to contribution guidelines

- ui-v2/src/components/automations/automations-create/automations-create-header/automations-create-header.stories.tsx
- ui-v2/src/components/automations/automations-create/automations-create-header/automations-create-header.tsx
- ui-v2/src/components/automations/automations-empty-state/automations-empty-state.stories.tsx
- ui-v2/src/components/automations/automations-empty-state/automations-empty-state.tsx
- ui-v2/src/components/automations/automations-empty-state/index.ts
- ui-v2/src/components/automations/automations-header/automations-header.stories.tsx
- ui-v2/src/components/automations/automations-header/automations-header.tsx
- ui-v2/src/components/automations/automations-header/index.ts
- ui-v2/src/components/ui/docs-link.tsx
- ui-v2/src/components/ui/icons/constants.ts
- ui-v2/src/routeTree.gen.ts
- ui-v2/src/routes/automations/automation.$id.ts
- ui-v2/src/routes/automations/create.ts
- ui-v2/src/routes/automations/index.ts
1. Creates routes for `/automations`, `/automations/create`, and `/automations/automation/:id`
2. Adds automation empty state component
3. Adds automations header component
> [UI v2] feat: scaffolds automations route

- docs/integrations/prefect-snowflake/index.mdx
This PR simplifies, updates, and removes some redundant content for the `prefect-snowflake` docs
> Update snowflake integration docs

- ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-data-table/global-concurrency-limits-data-table.stories.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limit-header/task-run-concurrency-limit-header.stories.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-actions-menu/task-run-concurrency-limits-actions-menu.stories.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-data-table/task-run-concurrency-limits-data-table.stories.tsx
- ui-v2/src/components/deployments/data-table/data-table.stories.tsx
- ui-v2/src/storybook/utils/index.ts
- ui-v2/src/storybook/utils/toast-decorator.tsx
Replaces void function calls for `fn()` from storybook
https://github.com/user-attachments/assets/fc505e6c-8548-4ef3-aaf4-35395e5687aa
> [UI v2] feat: Adds toast decorator for storybook

- ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-create-or-edit-dialog/global-concurrency-limits-create-or-edit-dialog.stories.tsx
- ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-data-table/global-concurrency-limits-data-table.stories.tsx
- ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-delete-dialog/global-concurrency-limits-delete-dialog.stories.tsx
- ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-empty-state/global-concurrency-limits-empty-state.stories.tsx
- ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-header/global-concurrency-limits-header.stories.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limit-header/task-run-concurrency-limit-header.stories.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-actions-menu/task-run-concurrency-limits-actions-menu.stories.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-create-dialog/task-run-concurrency-limits-create-dialog.stories.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-data-table/task-run-concurrency-limits-data-table.stories.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-delete-dialog/task-run-concurrency-limits-delete-dialog.stories.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-empty-state/task-run-concurrency-limits-empty-state.stories.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-header/task-run-concurrency-limits-header.stories.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-reset-dialog/task-run-concurrency-limit-reset-dialog.stories.tsx
Updates stories to use `fn()` for logging actions
https://github.com/PrefectHQ/prefect/issues/15512
> [UI v2] chore: Use storybook fn() for handlers

- ui-v2/src/components/concurrency/concurrency-limits-tabs.tsx
- ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-create-or-edit-dialog/global-concurrency-limits-create-or-edit-dialog.tsx
- ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-data-table/actions-cell.tsx
- ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-data-table/global-concurrency-limits-data-table.tsx
- ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-delete-dialog/global-concurrency-limits-delete-dialog.tsx
- ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-empty-state/global-concurrency-limits-empty-state.tsx
- ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-header/global-concurrency-limits-header.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limit-active-task-runs/task-run-concurrency-limit-active-task-runs.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limit-details/task-run-concurrency-limit-details.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limit-header/nav-header.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limit-header/task-run-concurrency-limit-header.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limit-page/index.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limit-page/task-run-concurrency-limit-dialog.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limit-page/task-run-concurrency-limit-tab-navigation.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-actions-menu/task-run-concurrency-limits-actions-menu.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-create-dialog/task-run-concurrency-limits-create-dialog.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-data-table/active-task-runs-cell.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-data-table/tag-cell.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-data-table/task-run-concurrency-limits-data-table.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-delete-dialog/task-run-concurrency-limits-delete-dialog.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-empty-state/task-run-concurrency-limits-empty-state.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-header/task-run-concurrency-limits-header.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-reset-dialog/task-run-concurrency-limits-reset-dialog.tsx
- ui-v2/src/components/ui/docs-link.tsx
- ui-v2/src/components/ui/empty-state.tsx
- ui-v2/src/components/ui/icons/icon.tsx
- ui-v2/src/components/ui/run-card/run-card.tsx
- ui-v2/src/components/ui/typography/typography.tsx
Update `Prop` type names to be consistent with the component
> [UI v2] chore: Consistent and descriptive prop name

- src/integrations/prefect-redis/prefect_redis/blocks.py
- src/prefect/blocks/redis.py
> fix redis link

- docs/v3/get-started/index.mdx
code snippet is great/necessary for README, but want /home to be nav + description for now.
> Remove code snippet from docs homepage

- ui-v2/src/components/automations/automations-delete-dialog/automations-delete-dialog.stories.tsx
- ui-v2/src/components/automations/automations-delete-dialog/automations-delete-dialog.test.tsx
- ui-v2/src/components/automations/automations-delete-dialog/automations-delete-dialog.tsx
- ui-v2/src/components/automations/automations-delete-dialog/index.ts
Adds `AutomationsDeleteDialog`
> [UI v2] feat: Add AutomationsDeleteDialog

- docs/integrations/index.md
- docs/integrations/integrations.mdx
removing a bunch of integrations from our docs that are more or less unmaintained
> remove some integrations from docs

- docs/mint.json
- docs/v3/get-started/index.mdx
> docs intro

- ui-v2/src/components/automations/automations-wizard/automations-action-select/automations-action-select.stories.tsx
- ui-v2/src/components/automations/automations-wizard/automations-action-select/automations-action-select.test.tsx
- ui-v2/src/components/automations/automations-wizard/automations-action-select/automations-action-select.tsx
- ui-v2/src/components/automations/automations-wizard/automations-action-select/index.ts
Starts AutomationsActionSelect component. Will continuously add components for the additional field options based on the action type
https://github.com/user-attachments/assets/0d649156-9b67-4ac7-b17f-b54a61f385d1
> [UI v2] feat: Starts AutomationsActionSelect component

- docs/v3/get-started/index.mdx
> add main features to docs index

- ui-v2/.storybook/preview.ts
- ui-v2/package-lock.json
- ui-v2/package.json
- ui-v2/public/mockServiceWorker.js
- ui-v2/src/components/automations/automations-delete-dialog/automations-delete-dialog.stories.tsx
- ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-create-or-edit-dialog/global-concurrency-limits-create-or-edit-dialog.stories.tsx
- ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-delete-dialog/global-concurrency-limits-delete-dialog.stories.tsx
- ui-v2/src/components/ui/empty-state.stories.tsx
1. Adds `msw` addon for storybook. Re-uses our existing handlers
2. Adds `toastDecorator` to components that has mutation callbacks
https://github.com/user-attachments/assets/b8ca81fd-7ce7-4bc2-8455-c941d598adfc
> [UI v2] feat: Adds msw addon for storybook

- docs/mint.json
Clone of @thomas-te's https://github.com/PrefectHQ/prefect/pull/16622. Pre-commit was failing on that one and anothero attempt. Seems to be an issue with GitHub's inline editor changing the end of the file. Worked when pushed local work to a new branch.
> Update docs nav first links order 

- ui-v2/.storybook/main.ts
- ui-v2/package-lock.json
- ui-v2/package.json
Adds a11y addon to storybook. Encourages developers to be more conscious in accessibility when creating components.
https://github.com/user-attachments/assets/191a162b-0926-4a0e-b57f-00c74359faf5
> [Ui v2] feat: Adds a11y addon to storybook

- ui-v2/package-lock.json
- ui-v2/package.json
- ui-v2/src/components/ui/command.tsx
- ui-v2/src/components/ui/dialog.tsx
Adds command component from shadcn. To be used to make a combobox component
https://ui.shadcn.com/docs/components/combobox
https://github.com/user-attachments/assets/f384ab5e-cd66-48bb-b509-aef4260ca061
> [UI v2] feat: Adds command component used for combobox

- src/prefect/cli/deploy.py
- tests/cli/test_deploy.py
closes https://github.com/PrefectHQ/prefect/issues/16600
> handle setting `enforce_parameter_schema` in `prefect.yaml`

- src/prefect/logging/logging.yml
Proposing fixing comment in logging.yaml. 
logging.Filter requires the '()' key rather than 'class'
Reference https://github.com/python/cpython/blob/8f93dd8a8f237b277abad20d566df90c5cbd7f1e/Lib/logging/config.py#L732-L739
> Fix logging.yml comment

- src/prefect/blocks/__init__.py
- src/prefect/blocks/abstract.py
- src/prefect/blocks/core.py
- src/prefect/blocks/notifications.py
- src/prefect/blocks/redis.py
- src/prefect/blocks/system.py
- src/prefect/blocks/webhook.py
- src/prefect/client/schemas/objects.py
- src/prefect/testing/standard_test_suites/blocks.py
- src/prefect/utilities/templating.py
- tests/blocks/test_notifications.py
- tests/server/orchestration/api/test_block_types.py
Improves typing in `prefect.blocks` and brings total type completeness to ~87.95%.
Related to #16292
> Improve typing in `prefect.blocks`

- docs/v3/api-ref/rest-api/server/schema.json
- src/prefect/server/models/task_runs.py
- src/prefect/server/orchestration/core_policy.py
- src/prefect/server/orchestration/dependencies.py
- src/prefect/server/orchestration/global_policy.py
- src/prefect/server/orchestration/instrumentation_policies.py
- src/prefect/server/orchestration/policies.py
- src/prefect/server/orchestration/rules.py
- src/prefect/server/schemas/core.py
- tests/client/test_prefect_client.py
- tests/server/orchestration/test_rules.py
- ui-v2/src/api/prefect.ts
Related to #16292 
This PR increases type completeness by nearly 2%.
> Improve typing in prefect.server.orchestration

- src/prefect/engine.py
- src/prefect/flow_engine.py
Closes https://github.com/PrefectHQ/prefect/issues/15722
Closes https://github.com/PrefectHQ/prefect/issues/15444
and hopefully other cryptic errors related to flow loading and the engine.
> Log failures to load flow with flow run logger

- ui-v2/src/components/automations/automations-create-header/automations-create-header.tsx
- ui-v2/src/components/automations/automations-header/automations-header.tsx
- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limit-header/nav-header.tsx
- ui-v2/src/components/ui/run-card/run-card.tsx
Adds `<BreadcrumbItem>` fix  accessibility violation
**Before**
**After**
> [UI v2] fix: Fixes accessibility for breadcrumb lists

- ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limit-details/task-run-concurrency-limit-details.tsx
1. Fixes accessibility violation outputted by storybook.
2. Adds consistent spacing
**Before**
**After**
> [UI v2] fix: Fixes accessibility violations for limit details component

- src/prefect/blocks/notifications.py
Closes: https://github.com/PrefectHQ/prefect/issues/16335
> Fix `SendgridEmail` code example

- docs/v3/get-started/index.mdx
@discdiver [suggested](https://github.com/PrefectHQ/prefect/pull/16454#discussion_r1892855512) we not mention that the quickstart only takes five minutes.
> Remove promise that the quickstart only takes five minutes to complete

- ui-v2/src/components/automations/automations-wizard/action-step/action-change-flow-run-state-fields/action-change-flow-run-state-fields.tsx
- ui-v2/src/components/automations/automations-wizard/action-step/action-change-flow-run-state-fields/action-change-flow-run-state-name-field.tsx
- ui-v2/src/components/automations/automations-wizard/action-step/action-step.stories.tsx
- ui-v2/src/components/automations/automations-wizard/action-step/action-step.test.tsx
- ui-v2/src/components/automations/automations-wizard/action-step/action-step.tsx
- ui-v2/src/components/automations/automations-wizard/action-step/action-type-additional-fields.tsx
- ui-v2/src/components/automations/automations-wizard/action-step/action-type-schemas.ts
- ui-v2/src/components/automations/automations-wizard/action-step/automations-select-state-fields.tsx
- ui-v2/src/components/ui/combobox/combobox.tsx
- ui-v2/src/components/ui/combobox/comboxbox.stories.tsx
1. Restructures form schema for an automation action
2. Adds component for Additional actions when selecting an automation type action and tests
https://github.com/user-attachments/assets/cbac3ab8-32c1-43fa-b225-bc7751a1efd9
> [UI v2] feat: Adds additional fields for automations select step

- docs/v3/develop/manage-states.mdx
- docs/v3/tutorials/debug.mdx
Closes https://linear.app/prefect/issue/DOC-126/explain-flow-run-lifecycle-in-debug-a-data-pipeline-tutorial
> Add state transition table to 'Manage states' doc and link from the debug tutorial

- src/prefect/server/api/clients.py
- src/prefect/server/events/actions.py
- src/prefect/server/events/clients.py
- src/prefect/server/events/counting.py
- src/prefect/server/events/filters.py
- src/prefect/server/events/jinja_filters.py
- src/prefect/server/events/messaging.py
- src/prefect/server/events/ordering.py
- src/prefect/server/events/pipeline.py
- src/prefect/server/events/schemas/automations.py
- src/prefect/server/events/schemas/events.py
- src/prefect/server/events/storage/database.py
- src/prefect/server/events/stream.py
- src/prefect/server/events/triggers.py
- src/prefect/server/schemas/actions.py
- src/prefect/server/schemas/core.py
- ui-v2/src/api/prefect.ts
This PR brings the `prefect.server.events` module up to 100% type completion.
> Improve typing in server events - part deux

- src/prefect/_experimental/sla/objects.py
- src/prefect/_internal/concurrency/threads.py
- src/prefect/events/worker.py
- src/prefect/flows.py
- src/prefect/futures.py
- src/prefect/runner/runner.py
- src/prefect/settings/legacy.py
- src/prefect/settings/models/logging.py
- src/prefect/settings/models/server/database.py
- src/prefect/settings/profiles.py
- src/prefect/settings/sources.py
- src/prefect/task_runners.py
- src/prefect/task_runs.py
- src/prefect/tasks.py
I tried to get `prefect.flows` to 100% type completion, but it's too early for that. So here's 100% type completion in `prefect.settings` instead.
> Improve typing of `prefect.settings`

- docs/v3/tutorials/ml.mdx
- requirements-markdown-tests.txt
Fixes broken CI tests on main.
https://github.com/PrefectHQ/prefect/actions/runs/12792423178/job/35662842051?pr=16728#step:8:404
> [Docs] Use Python 3.9 syntax and don't test 3rd-party deps

- docs/integrations/prefect-gcp/gcp-worker-guide.mdx
Closes https://github.com/PrefectHQ/prefect/issues/16673
> Add correct probe config to gcloud example command

- ui-v2/src/components/automations/automations-header/automations-header.tsx
- ui-v2/src/components/automations/automations-page.tsx
- ui-v2/src/routes/automations/index.ts
Begins layout and logic for automations page
https://github.com/user-attachments/assets/59293a52-6432-41e6-8c21-9de23f6a2380
> [UI v2] feat: Begin to create automation page

- docs/overrides/main.html
- docs/robots.txt
> Create robots.txt and in-page instructions to avoid searching of docs v2 pages

- ui-v2/src/api/deployments/deployments.test.ts
- ui-v2/src/api/work-pools/index.ts
- ui-v2/src/api/work-pools/work-pools.test.ts
- ui-v2/src/api/work-pools/work-pools.ts
- ui-v2/src/mocks/create-fake-work-pool.ts
- ui-v2/src/mocks/index.ts
- ui-v2/src/routeTree.gen.ts
- ui-v2/src/routes/work-pools/index.tsx
- ui-v2/src/routes/work-pools/work-pool.$id.tsx
- ui-v2/tests/utils/handlers.ts
1. Adds queries for work pool APIs (filter and count)
2. Update routes for work-pools
> [UI v2] feat: Adds api hooks for work pools and updates routing

- ui-v2/package-lock.json
- ui-v2/package.json
- ui-v2/src/storybook/utils/mode-decorator.tsx
- ui-v2/src/storybook/utils/react-query-decorator.tsx
- ui-v2/src/storybook/utils/toast-decorator.tsx
1. Updates how storybook decorator typings should be handled from the React 19 Upgrade
From this thread: https://github.com/storybookjs/storybook/issues/29805#issuecomment-2589711027
> [UI v2] fix: Fix Storybook decorators typings

- ui-v2/src/api/work-queues/index.ts
- ui-v2/src/api/work-queues/work-queues.test.ts
- ui-v2/src/api/work-queues/work-queues.ts
- ui-v2/src/mocks/create-fake-work-queue.ts
- ui-v2/src/mocks/index.ts
- ui-v2/src/routeTree.gen.ts
- ui-v2/src/routes/work-pools/work-pool.$workPoolId.queue.$workQueueId.tsx
- ui-v2/src/routes/work-pools/work-pool.$workPoolId.tsx
- ui-v2/tests/utils/handlers.ts
1. Adds queries for work queues APIs (filter)
2. Update routes for work-queues
> [UI v2] feat: Adds api hooks for work queues and updates routing

- ui-v2/src/api/deployments/index.ts
- ui-v2/src/api/deployments/use-list-deployments-with-flows/index.ts
- ui-v2/src/api/deployments/use-list-deployments-with-flows/use-list-deployments-with-flows.ts
- ui-v2/src/components/automations/automations-wizard/actions-step/action-step.tsx
- ui-v2/src/components/automations/automations-wizard/actions-step/actions-step.stories.tsx
- ui-v2/src/components/automations/automations-wizard/actions-step/actions-step.test.tsx
- ui-v2/src/components/automations/automations-wizard/actions-step/automations-select-state-fields.tsx
- ui-v2/src/components/automations/automations-wizard/actions-step/deployments-select-state-fields.tsx
- ui-v2/src/components/automations/automations-wizard/actions-step/loading-select-state.tsx
- ui-v2/src/components/automations/automations-wizard/automation-wizard.stories.tsx
- ui-v2/src/components/ui/combobox/combobox.tsx
1. Adds automation select deployment options for wizard
https://github.com/user-attachments/assets/5febda15-607a-47c9-a853-e8bb41be1a57
> [UI v2] feat: Adds pause and resume deployment options for automation wizard

- docs/v3/tutorials/schedule.mdx
> Fix work pool types link in `Schedule a flow` tutorial

- ui-v2/src/api/work-queues/work-queues.ts
- ui-v2/src/components/automations/automations-wizard/actions-step/action-step.tsx
- ui-v2/src/components/automations/automations-wizard/actions-step/actions-step.stories.tsx
- ui-v2/src/components/automations/automations-wizard/actions-step/actions-step.test.tsx
- ui-v2/src/components/automations/automations-wizard/actions-step/select-work-queues-fields.tsx
- ui-v2/src/components/automations/automations-wizard/automation-wizard.stories.tsx
- ui-v2/src/components/ui/combobox/combobox.tsx
- ui-v2/src/mocks/create-fake-work-queue.ts
Adds work queue automation action option
https://github.com/user-attachments/assets/0d179977-c89e-4881-a8cb-fb7e2a235753
> [UI v2] feat: Adds select work queues automation action option

- ui-v2/src/components/automations/action-details/action-details.stories.tsx
- ui-v2/src/components/automations/action-details/action-details.tsx
- ui-v2/src/components/ui/state-badge/index.tsx
1. Updates Status badge UI component, so that it can be re-used for this automation type. (Should update this component to not expect a `State` schema, but UI props instead)
2. Adds action descriptions for `change-flow-run-state` type
> [UI v2] feat: Adds action description for change state of a flow

- docs/v3/get-started/index.mdx
https://github.com/PrefectHQ/prefect/pull/16814#discussion_r1927259845
> [Docs] Update awkward phrasing in mini-history of Prefect

- src/prefect/server/api/clients.py
- tests/server/api/test_clients.py
> Add auth string handling to server side client

- .github/dependabot.yml
Consolidates to just 2 groupings:
1. eslint
2. All remaining packages
> [UI v2] feat: Updates dependabot groupings for ui-v2

- ui-v2/src/api/automations/use-get-automation-action-resources/use-get-automation-action-resources.test.ts
- ui-v2/src/api/automations/use-get-automation-action-resources/use-get-automation-action-resources.ts
- ui-v2/src/api/block-documents/block-documents.ts
- ui-v2/src/api/deployments/index.ts
- ui-v2/src/api/work-pools/work-pools.ts
- ui-v2/src/api/work-queues/work-queues.ts
- ui-v2/src/components/automations/action-details/action-details.stories.tsx
- ui-v2/src/components/automations/action-details/action-details.tsx
- ui-v2/src/components/automations/automation-details-page.tsx
- ui-v2/src/components/automations/automation-details.tsx
- ui-v2/src/components/automations/automations-page.tsx
1. Integrates hook to join automation actions' data sources
2. Updates hook to only call APIs if there is a source to be combined
3. Hook now supports block document APIs
https://github.com/user-attachments/assets/959089fd-5234-4256-b043-f61740a600d2
> [UI v2] feat: Combines automation source endpoints to get action details

- ui-v2/src/hooks/use-local-storage.test.ts
- ui-v2/src/hooks/use-local-storage.ts
- ui-v2/tests/setup.ts
Adds `useLocalStorage` hook, to be used for synchronizing state with local storage.
This is needed for enabling dark mode feature in the react re-platform
https://github.com/PrefectHQ/prefect/issues/15512
> [UI v2] feat: Adds useLocalStorage hook

- src/prefect/results.py
- src/prefect/server/orchestration/core_policy.py
- src/prefect/states.py
- src/prefect/task_engine.py
- src/prefect/task_worker.py
- tests/fixtures/time.py
- tests/server/orchestration/test_core_policy.py
related to https://github.com/PrefectHQ/prefect/issues/16910
> more pendulum consolidation

- ui-v2/src/api/artifacts/artifacts.test.ts
- ui-v2/src/api/artifacts/index.ts
- ui-v2/src/mocks/create-fake-artifact.ts
- ui-v2/src/mocks/index.ts
- ui-v2/src/routeTree.gen.ts
- ui-v2/src/routes/artifacts/index.tsx
1. adds artifacts to api 
2. adds mock to create a fake artifact
3. adds stubbed route at `/artifacts`
> feat: artifacts api RQ and stub route

- docs/v3/get-started/quickstart.mdx
Submitting a few small recommendations after I ran through the quickstart today.
> fix(docs): small quickstart fixes

- .github/labeler.yml
This is labeling everything now - going to admin merge this
> Removes bad label syntax

- docs/v3/resources/upgrade-to-prefect-3.mdx
Closes https://github.com/PrefectHQ/prefect/issues/15477
> Add suggestion to pause schedules prior to upgrading

- ui-v2/src/hooks/use-toast.ts
Not changing any functionality. Just something I noticed when poking around.
> [UI v2] Simplify toast listeners

- docs/mint.json
This PR adds new redirects for `/reference` docs; we're using two entries so we can capture both root-level and any path-level refs.
Closes: PLA-958
> Chore: Add `/reference` redirects

- .github/CODEOWNERS
Updates CODEOWNERS file to include @devangrose and @pleek91 
> [UI v2] chore: Update CODEOWNERS for ui-v2

- ui-v2/src/components/deployments/data-table/data-table.test.tsx
- ui-v2/src/components/deployments/data-table/index.tsx
- ui-v2/src/components/ui/flow-run-activity-bar-graph/flow-run-activity-bar-graph.test.tsx
1. Wraps links around the deployment table's flow name and deployment
2. Updates test to be compatible with `@tanstack/router` dependency
https://github.com/user-attachments/assets/75f29185-177f-4c5f-8a7e-19445c814967
> [UI v2] feat: Adds links to deployment table for deployment details and flows

- ui-v2/src/api/deployments/deployments.test.ts
- ui-v2/src/api/deployments/index.ts
- ui-v2/src/routes/deployments/deployment.$id.tsx
1. Adds RQ hook for getting a deployment's details based on its `id`
2. Ensures loader based on QueryOptions from above for the deployment details page
> [UI v2] feat: Adds deployment details RQ hook

- ui-v2/src/routes/deployments/deployment.$id.tsx
Adds search params to deployment details route
> [UI v2] feat: Adds search params for the deployment details route

- ui-v2/src/components/deployments/deployment-details-header.tsx
- ui-v2/src/components/deployments/deployment-details-page.tsx
- ui-v2/src/components/deployments/deployment-details-tabs.tsx
- ui-v2/src/routes/deployments/deployment.$id.tsx
1. Scaffolds UX components for deployment details page. Will fill in UX components in future PRs
2. Adds in the Tab components and placeholders for the component view
https://github.com/user-attachments/assets/36d1bc0d-a7b6-4a75-9fce-5cf5fbccef2b
> [UI v2] feat: Scaffolds UX components for deployment details page

- ui-v2/src/api/flows/flows.test.ts
- ui-v2/src/api/flows/index.ts
Adds react query options for flow details API. Needed for the deployment details page
> [UI v2] feat: Adds react query options for flow details API

- ui-v2/package-lock.json
- ui-v2/package.json
- ui-v2/src/components/artifacts/artifacts-filter.test.tsx
- ui-v2/src/components/artifacts/artifacts-filter.tsx
- ui-v2/src/components/artifacts/artifacts-header.tsx
- ui-v2/src/components/artifacts/artifacts-page.tsx
- ui-v2/src/components/ui/icons/constants.ts
- ui-v2/src/components/ui/toggle-group.tsx
- ui-v2/src/components/ui/toggle.tsx
> [UI-v2] feat: add artifacts list view

- ui-v2/src/components/deployments/deployment-details-page.tsx
- ui-v2/src/components/deployments/deployment-details-tabs.tsx
- ui-v2/src/components/deployments/deployment-metadata.tsx
Adds deployment metadata side details
> [UI v2] feat: Adds deployment metadata

- docs/v3/api-ref/rest-api/server/schema.json
- src/prefect/server/schemas/actions.py
- tests/server/orchestration/api/test_deployments.py
- ui-v2/src/api/prefect.ts
Allows `pull_steps` to be updated on PATCH requests to update deployments
> Allow for pull step updates on deployments

- ui-v2/src/components/deployments/deployment-details-page.tsx
- ui-v2/src/components/deployments/deployment-triggers.tsx
- ui-v2/src/routes/automations/create.ts
Adds Triggers section in deployment details page
> [UI v2] feat: Adds Triggers section in deployment details page

- ui-v2/src/components/deployments/deployment-description.tsx
- ui-v2/src/components/deployments/deployment-details-page.tsx
- ui-v2/src/components/deployments/deployment-details-tabs.tsx
Adds Deployment description tab content with markdown support
https://github.com/user-attachments/assets/71f31832-56c4-4dff-82d6-6ca42159e3b7
> [UI v2] feat: Adds Deployment description tab content

- ui-v2/src/api/deployments/deployments.test.ts
- ui-v2/src/api/deployments/index.ts
- ui-v2/tests/utils/handlers.ts
Adds update deployment schedule hook. Needed for deployment page
> [UI v2] feat: Adds update deployment schedule hook

- docs/integrations/prefect-dbt/index.mdx
Especially looking for feedback on what good headers would be for differentiating versions while both old and new are temporarily available.
> Add `PrefectDbtRunner` docs

- docs/integrations/prefect-dbt/index.mdx
> Update `prefect-dbt` prerelease install command with `-U`

- src/prefect/server/database/query_components.py
- src/prefect/server/utilities/database.py
- src/prefect/server/utilities/schemas/bases.py
- src/prefect/states.py
- src/prefect/task_engine.py
- src/prefect/testing/fixtures.py
- src/prefect/types/_datetime.py
- src/prefect/utilities/dockerutils.py
- src/prefect/workers/base.py
- tests/cli/deployment/test_deployment_run.py
- tests/docker/test_registry_pushes.py
Related to https://github.com/PrefectHQ/prefect/issues/16910
> Migrate some `pendulum` usage to internal shim

- src/prefect/concurrency/asyncio.py
- src/prefect/concurrency/sync.py
- src/prefect/concurrency/v1/asyncio.py
- src/prefect/concurrency/v1/sync.py
> pendulum consolidation in `prefect.concurrency`

- ui-v2/package-lock.json
- ui-v2/package.json
- ui-v2/src/components/ui/cron-input/cron-input.stories.tsx
- ui-v2/src/components/ui/cron-input/cron-input.test.tsx
- ui-v2/src/components/ui/cron-input/cron-input.tsx
- ui-v2/src/components/ui/cron-input/index.ts
Adds `CronInput` component.
To be used for creating a schedule dialog
https://github.com/user-attachments/assets/28cc4ca8-b401-4c6e-90ce-a62a5fd8426a
> [UI v2] feat: Adds cron input component

- ui-v2/src/api/deployments/deployments.test.ts
- ui-v2/src/api/deployments/index.ts
- ui-v2/tests/utils/handlers.ts
Adds create deployment schedule mutation
> [UI v2] feat: Adds create deployment schedule mutation

- ui-v2/src/components/deployments/deployment-details-page.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-item.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedules.stories.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedules.tsx
- ui-v2/src/components/deployments/deployment-schedules/get-schedule-title.test.ts
- ui-v2/src/components/deployments/deployment-schedules/get-schedule-title.ts
- ui-v2/src/components/deployments/deployment-schedules/index.ts
- ui-v2/src/components/deployments/deployment-schedules/schedule-action-menu.test.tsx
- ui-v2/src/components/deployments/deployment-schedules/schedule-action-menu.tsx
- ui-v2/src/components/deployments/deployment-schedules/schedule-toggle-switch.test.tsx
- ui-v2/src/components/deployments/deployment-schedules/schedule-toggle-switch.tsx
- ui-v2/src/components/deployments/deployment-schedules/types.ts
- ui-v2/src/components/deployments/deployment-schedules/use-delete-schedule.ts
Adds deployment schedule list (except for adding end editing UX). Will do the UX for creating and editing a schedule in an upcoming PR
https://github.com/user-attachments/assets/36cabf9b-eadf-48b9-a0f9-a70beb94ad28
> [UI v2] feat: Adds deployment schedule list (except for adding end editing UX)

- ui-v2/src/components/ui/timezone-select/index.ts
- ui-v2/src/components/ui/timezone-select/timezone-select.stories.tsx
- ui-v2/src/components/ui/timezone-select/timezone-select.test.tsx
- ui-v2/src/components/ui/timezone-select/timezone-select.tsx
- ui-v2/tsconfig.app.json
Adds timezone select component. Used for deployment schedule UX
https://github.com/user-attachments/assets/73b7ff75-3aef-401b-a95d-9ef4686a636b
> [UI v2] feat: Adds timezone component

- ui-v2/src/components/deployments/deployment-details-page.tsx
- ui-v2/src/components/deployments/deployment-flow-link.tsx
- ui-v2/src/components/deployments/deployment-triggers.tsx
- ui-v2/src/routes/deployments/deployment.$id.tsx
Updates deployment details page route to load data for related automations **and** deployment details
> [UI v2] chore: Updates deployment details page route data loading

- .github/workflows/codspeed-benchmarks.yaml
- .github/workflows/python-tests.yaml
- .github/workflows/static-analysis.yaml
- pyproject.toml
> Fix tests in CI after migrating to `pyproject.toml` and `uv` project

- docs/integrations/prefect-aws/ecs_guide.mdx
Remove link until [Example repo issue](https://github.com/PrefectHQ/examples/issues/11) porting over ECS worker example is completed.
> Remove link in ECS Guide

- docs/integrations/prefect-gcp/index.mdx
Updates GCP integration docs to follow the format used for the AWS integration docs.
> Docs: Update GCP integration docs

- docs/mint.json
- this PR removes Github from the left sidebar (it's in the top navbar already)
- changes "Community" to "Join our Community"
> change docs sidebar items

- ui-v2/src/components/deployments/deployment-details-page.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-dialog/deployment-schedule-dialog.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-dialog/index.ts
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-dialog/rrule-schedule-form.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-item.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedules.tsx
- ui-v2/src/components/deployments/deployment-schedules/schedule-action-menu.test.tsx
- ui-v2/src/components/deployments/deployment-schedules/schedule-action-menu.tsx
- ui-v2/src/components/ui/timezone-select/timezone-select.tsx
Starts UX for adding and editing a deployment schedule. Future PRs will add and implement the forms for the different schedule types
https://github.com/user-attachments/assets/3b62566a-5210-4e0b-9eaf-94f0a15d451f
> [UI v2] feat: Start UX for adding and editing a deployment schedule

- docs/integrations/prefect-dbt/index.mdx
> Fix link to dbt programmatic invocation

- ui-v2/src/api/deployments/index.ts
- ui-v2/src/components/deployments/deployment-details-page.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-dialog/cron-schedule-form.test.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-dialog/cron-schedule-form.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-dialog/deployment-schedule-dialog.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-item.tsx
- ui-v2/src/components/deployments/deployment-schedules/get-schedule-title.test.ts
- ui-v2/src/components/deployments/deployment-schedules/get-schedule-title.ts
- ui-v2/src/components/deployments/deployment-schedules/schedule-action-menu.tsx
- ui-v2/src/components/deployments/deployment-schedules/schedule-toggle-switch.tsx
- ui-v2/src/components/deployments/deployment-schedules/types.ts
- ui-v2/src/components/deployments/deployment-schedules/use-delete-schedule.ts
Adds deployment schedule cron tab
https://github.com/user-attachments/assets/bdfc6d55-3ad6-4034-a38d-49e89a308bcb
> [UI v2] feat: Adds deployment schedule cron tab

- docs/integrations/prefect-aws/index.mdx
- docs/integrations/prefect-bitbucket/index.mdx
- docs/integrations/prefect-dask/index.mdx
- docs/integrations/prefect-databricks/index.mdx
- docs/integrations/prefect-dbt/index.mdx
- docs/integrations/prefect-docker/index.mdx
- docs/integrations/prefect-email/index.mdx
- docs/integrations/prefect-github/index.mdx
- docs/integrations/prefect-gitlab/index.mdx
- docs/integrations/prefect-kubernetes/index.mdx
- docs/integrations/prefect-ray/index.mdx
- docs/integrations/prefect-shell/index.mdx
- docs/integrations/prefect-slack/index.mdx
- docs/integrations/prefect-snowflake/index.mdx
- docs/integrations/prefect-sqlalchemy/index.mdx
This PR updates the integration docs to include links to the new reference.prefect.io domain
> Update SDK docs links

- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-dialog/cron-schedule-form.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-dialog/deployment-schedule-dialog.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-dialog/interval-schedule-form.test.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-dialog/interval-schedule-form.tsx
Adds deployment interval schedule form
https://github.com/user-attachments/assets/111ec3d4-56b8-4d12-a7f7-cad090422321
> [UI v2] feat: Adds deployment interval schedule form

- .github/workflows/python-package.yaml
see https://github.com/PrefectHQ/prefect/actions/runs/13398872086/job/37424551326
> add `uv run` for smoke test UI build

- pyproject.toml
> add `server/ui` to wheel

- ui-v2/src/components/flow-runs/data-table/data-table.stories.tsx
- ui-v2/src/components/flow-runs/data-table/data-table.tsx
- ui-v2/src/components/flow-runs/data-table/state-filter.tsx
1. Adds placements for flow run counter and filters
2. Will update flow run counter component to handled select and delete UX in a future PR
> [UI v2] feat: Adds total flow run counter to data table

- ui-v2/src/api/flow-runs/flow-runs.test.ts
- ui-v2/src/api/flow-runs/index.ts
- ui-v2/tests/utils/handlers.ts
Adds delete flow run mutation.
This is needed for the flow run data table
> [UI v2] feat: Adds delete flow run mutation

- src/prefect/deployments/runner.py
- tests/runner/test_runner.py
Closes https://github.com/PrefectHQ/prefect/issues/17182
> Fix update logic to account for pull_steps

- client/pyproject.toml
- pyproject.toml
should have been removed with #17165
> rm croniter dep

- ui-v2/src/api/task-runs/index.ts
- ui-v2/src/api/task-runs/task-runs.test.ts
Adds flow run task count query. Needed for flow run data table
> [UI v2] feat: Adds flow run task count query

- ui-v2/src/api/task-runs/index.ts
- ui-v2/src/api/task-runs/task-runs.test.ts
- ui-v2/src/components/flow-runs/data-table/data-table.stories.tsx
- ui-v2/src/components/flow-runs/data-table/data-table.test.tsx
- ui-v2/src/components/flow-runs/data-table/data-table.tsx
- ui-v2/src/components/flow-runs/data-table/run-name-search.tsx
- ui-v2/src/components/flow-runs/data-table/sort-filter.tsx
- ui-v2/src/components/flow-runs/data-table/state-filter.tsx
- ui-v2/src/components/flow-runs/data-table/tasks-cell.tsx
Adds search, sort, filtering, and pagination functionality to data table.
Next step is to integrate this UI component to a route with search params
Opting to not test too much on these feature on the data table component, because tests are already written per component. Trying to avoid redundant tests
https://github.com/user-attachments/assets/614f9f34-4790-4583-83ff-fa8de4968b3f
> [UI v2] feat: Adds search, sort, filtering, and pagination functionality to data table

- ui-v2/src/api/artifacts/use-get-artifacts-flow-task-runs/use-get-artifacts-flow-task-runs.ts
- ui-v2/src/api/flow-runs/flow-runs.test.ts
- ui-v2/src/api/flow-runs/index.ts
- ui-v2/src/components/deployments/data-table/cells.tsx
Adds flow runs paginate query
This query is needed for the deployment details upcoming tab
> [UI v2] feat: Adds flow runs paginate query

- docs/v3/deploy/infrastructure-concepts/deploy-ci-cd.mdx
related to https://github.com/PrefectHQ/prefect/issues/17204
> standardize names of step action slugs in docs

- ui-v2/src/api/flow-runs/index.ts
- ui-v2/src/api/flow-runs/use-paginate-flow-runs-with-flows/use-paginate-flow-runs-with-flows.ts
- ui-v2/src/components/deployments/deployment-details-page.tsx
- ui-v2/src/components/deployments/deployment-details-tabs.tsx
- ui-v2/src/components/deployments/deployment-details-upcoming-tab.tsx
- ui-v2/src/components/flow-runs/data-table/data-table-filters.tsx
- ui-v2/src/components/flow-runs/data-table/use-delete-flow-runs-dialog.ts
- ui-v2/src/routes/deployments/deployment.$id.tsx
Adds deployment details upcoming tab UX
https://github.com/user-attachments/assets/f4943e0c-6f7a-4f67-878e-66375f6d8c72
> [UI v2] feat: Adds deployment details upcoming tab UX

- src/integrations/prefect-aws/prefect_aws/experimental/bundles/types.py
follow up to https://github.com/PrefectHQ/prefect/pull/17201
this types.py file is no longer necessary
> remove unused experimental `bundles.types` file in `prefect-aws`

- src/prefect/cli/deploy.py
- src/prefect/utilities/templating.py
- tests/cli/test_deploy.py
- tests/utilities/test_templating.py
Closes https://github.com/PrefectHQ/prefect/issues/17204
> Add option to log warning when placeholder values is missing when templating

- docs/mint.json
> Remove broken link and add redirect for terraform provider

- ui-v2/src/api/flow-runs/use-filter-flow-runs-with-flows/index.ts
- ui-v2/src/api/flow-runs/use-filter-flow-runs-with-flows/use-filter-flow-runs-with-flows.test.ts
- ui-v2/src/api/flow-runs/use-filter-flow-runs-with-flows/use-filter-flow-runs-with-flows.ts
- ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-row-count.tsx
- ui-v2/src/components/flow-runs/flow-runs-list/types.ts
Adds query to join filtered flow runs with flow API.
This is needed for the Runs tab in the Deployment details page
> [UI v2] feat: Adds query to join filtered flow runs with flow API

- .github/workflows/integration-package-tests.yaml
- pyproject.toml
- src/integrations/prefect-aws/pyproject.toml
- src/integrations/prefect-azure/pyproject.toml
- src/integrations/prefect-bitbucket/pyproject.toml
- src/integrations/prefect-dask/pyproject.toml
- src/integrations/prefect-databricks/pyproject.toml
- src/integrations/prefect-dbt/pyproject.toml
- src/integrations/prefect-docker/pyproject.toml
- src/integrations/prefect-email/pyproject.toml
- src/integrations/prefect-gcp/pyproject.toml
- src/integrations/prefect-github/pyproject.toml
- src/integrations/prefect-gitlab/pyproject.toml
- src/integrations/prefect-kubernetes/pyproject.toml
- src/integrations/prefect-ray/pyproject.toml
- src/integrations/prefect-redis/pyproject.toml
- src/integrations/prefect-shell/pyproject.toml
- src/integrations/prefect-slack/pyproject.toml
- src/integrations/prefect-snowflake/pyproject.toml
- src/integrations/prefect-sqlalchemy/pyproject.toml
no more `dev` extra, all just `dependency-groups` which `uv sync` will install by default
> dev group for all integrations

- src/integrations/prefect-kubernetes/tests/experimental/test_decorator.py
> initial test coverage for kubernetes decorator

- ui-v2/src/api/deployments/deployments.test.ts
- ui-v2/src/api/deployments/index.ts
- ui-v2/src/api/flow-runs/index.ts
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-item.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-toggle.tsx
- ui-v2/src/components/deployments/deployment-schedules/deployment-schedules.tsx
- ui-v2/src/components/deployments/deployment-schedules/schedule-toggle-switch.tsx
- ui-v2/tests/utils/handlers.ts
1. Adds update deployment mutation
2. Adds pause/activate schedules switch
3. Updates schedule toggles to be disabled if deployment is paused
https://github.com/user-attachments/assets/0e24a853-727d-4e76-b323-5abd35f672c4
> [UI v2] feat: Adds toggle all schedules switch

- docs/integrations/prefect-dbt/index.mdx
> Fix dbt docs typo

- ui-v2/src/components/flow-runs/activity-chart/activity-chart.test.tsx
- ui-v2/src/components/flow-runs/activity-chart/activity-chart.tsx
- ui-v2/src/components/flow-runs/activity-chart/flowRunCell.test.tsx
- ui-v2/src/components/flow-runs/activity-chart/flowRunCell.tsx
- ui-v2/src/components/flow-runs/activity-chart/popover.test.tsx
- ui-v2/src/components/flow-runs/activity-chart/popover.tsx
- ui-v2/src/components/flows/detail/index.tsx
- ui-v2/src/components/flows/queries.tsx
- ui-v2/src/mocks/create-fake-flow-run.ts
Add activity graph and mini version. 
> [UI-v2] feat: add activity graph

- .pre-commit-config.yaml
- ui-v2/package-lock.json
- ui-v2/package.json
this reduces wait time on committing by only linting staged files
> [ui-v2] feat: only lint staged changes on pre-commit

- ui-v2/src/api/work-pools/index.ts
- ui-v2/src/api/work-pools/work-pools.test.ts
- ui-v2/src/api/work-pools/work-pools.ts
Adds API to retrieve a work pool details
This is needed for the flow details page
> [UI v2] feat: Adds API to retrieve a work pool details

- ui-v2/src/components/work-pools/work-pool-select/work-pool-select.test.tsx
- ui-v2/src/components/work-pools/work-queue-select/index.ts
- ui-v2/src/components/work-pools/work-queue-select/work-queue-select.stories.tsx
- ui-v2/src/components/work-pools/work-queue-select/work-queue-select.test.tsx
- ui-v2/src/components/work-pools/work-queue-select/work-queue-select.tsx
Adds Work Queues select component. This component is needed for the deployment edit and duplicate form
https://github.com/user-attachments/assets/049a0aae-aeda-4229-a52b-b5cce275e81d
> [UI v2] feat: Adds Work Queues select component

- docs/integrations/prefect-ray/index.mdx
Just a small change based on latest Ray info. ☺️
> docs(prefect-ray): change to Ray support for Python 3.13 is experimental

- ui-v2/package-lock.json
- ui-v2/package.json
Updating graphs package to latest.
> [ui-v2] Update graphs package

- ui-v2/package-lock.json
- ui-v2/package.json
- ui-v2/src/components/deployments/deployment-form/deployment-form.stories.tsx
- ui-v2/src/components/deployments/deployment-form/deployment-form.tsx
- ui-v2/src/components/deployments/deployment-form/limit-collision-strategy-select.tsx
- ui-v2/src/components/deployments/deployment-form/use-deployment-form.ts
- ui-v2/src/components/ui/markdown-input.tsx
- ui-v2/src/components/work-pools/work-queue-select/work-queue-select.stories.tsx
- ui-v2/src/routes/deployments/deployment_.$id.edit.tsx
Begins the deployment edit form page (skipping on the parameters section for now).
https://github.com/user-attachments/assets/b498ee91-f11e-4594-86bc-9a95985d16ba
> [UI v2] feate: Begins deployment edit / duplicate form

- ui-v2/src/components/deployments/deployment-form/deployment-form.tsx
- ui-v2/src/components/deployments/deployment-form/use-deployment-form.ts
- ui-v2/src/components/schemas/__snapshots__/schema-form.snapshot.test.tsx.snap
- ui-v2/src/components/schemas/hooks/useSchemaForm.ts
- ui-v2/src/components/schemas/index.ts
- ui-v2/src/components/schemas/readme.md
- ui-v2/src/components/schemas/schema-form-input-boolean.tsx
- ui-v2/src/components/schemas/utilities/validate.ts
Adds parameters form fields to deployment edit page
Uploading Screen Recording 2025-03-04 at 1.26.29 PM.mov…
> [UI v2] feat: Adds parameters form fields to deployment edit page

- ui-v2/package-lock.json
- ui-v2/package.json
> [ui-v2] Update graphs to 3.0.5

- src/prefect/cli/server.py
Closes https://github.com/PrefectHQ/prefect/issues/17378
> Print correct API URL when setting base path

- ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-item.tsx
Fixes deployment schedule item layout after shadcn update
> [UI v2] fix: Fixes deployment schedule item layout after shadcn update

- docs/v3/api-ref/rest-api/server/schema.json
- src/prefect/server/schemas/actions.py
- ui-v2/package-lock.json
- ui-v2/package.json
- ui-v2/src/api/flow-runs/index.ts
- ui-v2/src/api/prefect.ts
- ui-v2/src/components/deployments/create-flow-run-form/create-flow-run-form.stories.tsx
- ui-v2/src/components/deployments/create-flow-run-form/create-flow-run-form.tsx
- ui-v2/src/components/deployments/create-flow-run-form/flow-run-name-input.tsx
- ui-v2/src/components/deployments/create-flow-run-form/index.ts
- ui-v2/src/components/deployments/create-flow-run-form/use-create-flow-run-form.tsx
- ui-v2/src/components/deployments/custom-run-page.tsx
- ui-v2/src/components/deployments/data-table/cells.tsx
- ui-v2/src/components/deployments/deployment-action-header.tsx
- ui-v2/src/components/deployments/deployment-details-page.tsx
- ui-v2/src/components/deployments/deployment-duplicate-page.tsx
- ui-v2/src/components/deployments/deployment-edit-page.tsx
- ui-v2/src/components/deployments/deployment-form/use-deployment-form.ts
- ui-v2/src/components/deployments/deployment-links.tsx
- ui-v2/src/components/ui/accordion.tsx
- ui-v2/src/routes/deployments/deployment_.$id.duplicate.tsx
- ui-v2/src/routes/deployments/deployment_.$id.edit.tsx
- ui-v2/src/routes/deployments/deployment_.$id.run.tsx
1. Adds Accordion component
2. Moves deployment edit, duplicate, and run pages to its own page components.
3. Finishes custom run page form
https://github.com/user-attachments/assets/59081a78-04b3-4dde-94a7-f9cb9bd4666d
> [UI v2] feat: Adds deployment custom run page

- .github/dependabot.yml
- .gitignore
- .pre-commit-config.yaml
- ui-v2/src/api/zod/deployments/deployments.ts
- uv.lock
> commit `uv.lock`

- src/integrations/prefect-azure/pyproject.toml
- src/integrations/prefect-dbt/pyproject.toml
- src/integrations/prefect-gcp/pyproject.toml
Closes https://github.com/PrefectHQ/prefect/issues/17431
> Update optional dependencies in integration packages to use `[project.optional-dependencies]`

- README.md
> Fix pep8 in README.md

- docs/contribute/dev-contribute.mdx
- docs/mint.json
- docs/v3/api-ref/rest-api/server/index.mdx
- docs/v3/get-started/install.mdx
- docs/v3/manage/index.mdx
- docs/v3/manage/server/examples/cli.mdx
- docs/v3/manage/server/examples/docker.mdx
- docs/v3/manage/server/examples/helm.mdx
- docs/v3/manage/server/index.mdx
- docs/v3/tutorials/platform.mdx
Split out self-hosted server examples into separate pages, and migrate Helm tutorial to this new section.
> Create a new section for self-hosted server examples (CLI, Docker, Helm)

- src/integrations/prefect-kubernetes/integration_tests/src/prefect_kubernetes_integration_tests/test_crash_detection.py
- src/integrations/prefect-kubernetes/integration_tests/src/prefect_kubernetes_integration_tests/test_events.py
- src/integrations/prefect-kubernetes/integration_tests/src/prefect_kubernetes_integration_tests/test_eviction.py
- src/integrations/prefect-kubernetes/integration_tests/src/prefect_kubernetes_integration_tests/utils/k8s.py
- src/integrations/prefect-kubernetes/integration_tests/src/prefect_kubernetes_integration_tests/utils/prefect_core.py
- src/integrations/prefect-kubernetes/prefect_kubernetes/operator.py
- src/integrations/prefect-kubernetes/tests/test_operator.py
> Add integration tests for crash detection

- ui-v2/src/api/automations/use-get-automation-action-resources/use-get-automation-action-resources.ts
- ui-v2/src/api/block-documents/block-documents.test.ts
- ui-v2/src/api/block-documents/block-documents.ts
- ui-v2/src/api/block-documents/index.ts
- ui-v2/tests/utils/handlers.ts
Begins APIS for block documents list and count
> [UI v2] feat: Begins APIS for block documents list and count

- ui-v2/src/components/blocks/empty-state/empty-state.stories.tsx
- ui-v2/src/components/blocks/empty-state/empty-state.tsx
- ui-v2/src/components/blocks/empty-state/index.ts
- ui-v2/src/components/ui/docs-link/constants.ts
Adds Blocks Empty State component
https://github.com/user-attachments/assets/2713e374-9ae4-4eec-9792-8b5b8f4d24c9
> [UI v2] feat: Adds Blocks Empty State component

- ui-v2/src/api/block-documents/block-documents.test.ts
- ui-v2/src/api/block-documents/block-documents.ts
- ui-v2/src/api/block-documents/index.ts
- ui-v2/src/components/blocks/use-delete-block-document-confirmation-dialog.ts
- ui-v2/tests/utils/handlers.ts
1. Adds useDeleteBlock Mutation
2. Adds useDeleteBlockConfirmationDialog hook
This is needed for the block UI
> [UI v2] feat: Adds useDeleteBlockConfirmationDialog hook

- docs/v3/automate/add-schedules.mdx
- docs/v3/develop/runtime-context.mdx
- src/integrations/prefect-aws/tests/test_secrets_manager.py
- src/integrations/prefect-docker/prefect_docker/deployments/steps.py
- src/integrations/prefect-docker/tests/deployments/test_steps.py
- src/integrations/prefect-kubernetes/tests/test_worker.py
> rm pendulum from integrations

- docs/mint.json
- docs/v3/api-ref/rest-api/server/schema.json
- docs/v3/api-ref/rest-api/server/task-runs/paginate-task-runs.mdx
- src/prefect/server/api/task_runs.py
- src/prefect/server/schemas/responses.py
- tests/server/orchestration/api/test_task_runs.py
- ui-v2/src/api/prefect.ts
- ui/src/pages/Runs.vue
closes https://github.com/PrefectHQ/prefect/issues/17286
Fixes an issue where the UI was expecting a route that didn't exist. Also updates the client-side implementations of the `usePaginatedTaskRuns` route
> Bugfix: Paginated task runs route + client-side fix

- docs/integrations/prefect-aws/ecs_guide.mdx
Links to the updated ECS worker Terraform module.
Closes https://github.com/PrefectHQ/prefect/issues/17522
Related to https://linear.app/prefect/issue/PLA-1072/create-opinionated-terraform-module-that-deploys-an-aws-ecs-cluster
> chore(docs): link to new ECS worker Terraform module

- src/integrations/prefect-databricks/prefect_databricks/models/jobs.py
- src/integrations/prefect-gcp/prefect_gcp/workers/cloud_run_v2.py
see https://github.com/PrefectHQ/prefect/pull/12656#issuecomment-2734972476
> update `Field` `examples` kwargs for gcp and databricks

- pyproject.toml
- src/prefect/server/services/telemetry.py
- tests/server/services/test_service_subsets.py
Adds back the telemetry service to _all_ servers (when enabled) not just long-standing servers.
> Adds back telemetry service to all servers when enabled

- docs/v3/api-ref/rest-api/server/schema.json
- src/prefect/client/schemas/actions.py
- src/prefect/client/schemas/objects.py
- src/prefect/server/database/_migrations/MIGRATION-NOTES.md
- src/prefect/server/database/_migrations/versions/postgresql/2025_03_19_143502_b5f5644500d2_add_storage_configuration_to_work_pool.py
- src/prefect/server/database/_migrations/versions/sqlite/2025_03_19_134138_40f679df41e9_.py
- src/prefect/server/database/_migrations/versions/sqlite/2025_03_19_142603_3457c6ca2360_add_storage_configuration_to_work_pool.py
- src/prefect/server/database/orm_models.py
- src/prefect/server/schemas/actions.py
- src/prefect/server/schemas/core.py
- tests/client/test_prefect_client.py
- tests/server/models/test_workers.py
- ui-v2/src/api/prefect.ts
> schema changes for work pool storage config

- src/prefect/docker/docker_image.py
closes [#17534](https://github.com/PrefectHQ/prefect/issues/17534)
> #fix: fix docker build with context arg when already set

- src/integrations/prefect-gcp/prefect_gcp/workers/cloud_run_v2.py
Closes https://github.com/PrefectHQ/prefect/issues/17511
Increasing Cloud Run Job timeout maximum to 7 days, to match their new parameters.
> increase cloud run worker timeout

- src/integrations/prefect-azure/prefect_azure/container_instance.py
- src/integrations/prefect-azure/prefect_azure/workers/container_instance.py
- src/integrations/prefect-azure/pyproject.toml
- src/integrations/prefect-azure/tests/test_aci_worker.py
> Add `prefect-docker`'s `DockerRegistryCredentials` as accepted type for ACI job configuration's `image_registry`

- src/prefect/server/api/collections_data/views/aggregate-worker-metadata.json
Updating the base job template for the ACI worker to go along with changes in #17543
> Update ACI worker base job template with current docker registry block

- src/prefect/results.py
> Account for `_resolve_path` returning `None`

- docs/v3/deploy/infrastructure-examples/managed.mdx
Removes the section on plan limits for managed execution as the information was out of date.  I would prefer to limit the places we need to update plan info to the Cloud UI and website so that we don't make mistakes or forget to update the docs. 
> Update docs on managed execution limits

- .github/workflows/python-tests.yaml
- src/prefect/server/api/server.py
- src/prefect/settings.py
- src/prefect/testing/fixtures.py
- tests/server/api/test_server.py
This is a backport to the 2.x line to address https://nvd.nist.gov/vuln/detail/CVE-2024-8183
> Adds settings to control server CORS configuration

- pyrightconfig-ci.json
- src/prefect/_internal/concurrency/services.py
- src/prefect/locking/memory.py
- src/prefect/logging/__init__.py
- src/prefect/logging/configuration.py
- src/prefect/logging/formatters.py
- src/prefect/logging/handlers.py
- tests/fixtures/logging.py
- tests/test_logging.py
Ths PR gets a couple more modules passing `pyright` checks.
> Various typing improvments

- ui-v2/src/api/block-types/block-types.test.ts
- ui-v2/src/api/block-types/block-types.ts
- ui-v2/src/api/block-types/index.ts
- ui-v2/src/mocks/create-fake-block-type.ts
- ui-v2/src/mocks/index.ts
- ui-v2/tests/utils/handlers.ts
Starts RQ queries for block_types list. This is needed for replatforming `/blocks`
> [UI v2] feat: Starts RQ queries for block_types list

- .github/workflows/proxy-test.yaml
see https://github.com/PrefectHQ/prefect/actions/runs/14044941628/job/39323535446
> fix proxy test

- .github/workflows/nightly-release.yaml
> Includes the .github workflows in the nightly release detection

- .github/workflows/docker-images.yaml
> Chooses the right Dockerfile for building `prefect-client`

- .github/workflows/nightly-release.yaml
- .github/workflows/prefect-client-publish.yaml
> Uses the right format for prefect-client pre-release tags

- docs/v3/automate/add-schedules.mdx
The docs include a syntax error in the code example for using schedules.  This updates it to make it so you can copy the code example and have it work. 
> Fix syntax in schedules example

- src/prefect/utilities/collections.py
- tests/utilities/test_collections.py
> remove extra getattr calls in `visit_collection` for `pydantic` objects

- src/prefect/events/utilities.py
Closes https://github.com/PrefectHQ/prefect/issues/17630
> Handle all `emit_event` errors and log them

- src/integrations/prefect-dbt/prefect_dbt/cloud/jobs.py
- src/integrations/prefect-dbt/tests/cloud/test_jobs.py
> handle `targeted_retries=0` in `run_dbt_cloud_job`

- src/prefect/client/base.py
- tests/client/test_base_client.py
This PR adds logic to bypass incrementing the retry counter if a special response header is returned, specifically 
```
"Prefect-Maintenance": "true"
```
This supports scenarios when it might be beneficial to give the Prefect server control to make client-side retries more tolerant of variable windows of downtime, such as maintenance-related operations.  
> chore(prefect-client): allow indefinite retries during maintenance

- ui-v2/src/components/ui/calendar.tsx
- ui-v2/src/components/ui/date-time-picker/date-time-picker.stories.tsx
- ui-v2/src/components/ui/date-time-picker/date-time-picker.test.tsx
- ui-v2/src/components/ui/date-time-picker/date-time-picker.tsx
fixes test that was failing on main
> fix date picker test

- ui-v2/.gitignore
- ui-v2/src/api/logs/index.ts
- ui-v2/src/api/logs/logs.test.ts
Adds initial query build and query key factory for `/logs`.
> Add query builder for log filtering

- src/integrations/prefect-dbt/prefect_dbt/cli/configs/snowflake.py
- src/integrations/prefect-dbt/tests/cli/configs/test_snowflake.py
Closes #17229
2.x port of https://github.com/PrefectHQ/prefect/pull/14767
> Port dbt snowflake config private key fix to 2.x

- ui-v2/src/components/flows/columns.tsx
Fixes margin in flow tables select columns
> fix: Fixes margin in flow tables select columns

- ui-v2/src/api/work-pools/work-pools.ts
Fast follow from #17419, check I modified there wasn't quite right.
> Bugfix: Nullish coalesce the work pools count

- ui-v2/src/api/flow-runs/flow-runs.test.ts
- ui-v2/src/api/flow-runs/index.ts
precursor to https://github.com/PrefectHQ/prefect/pull/17704 to reduce the diff in that PR
this PR adds only the changes to `src/api/flow-runs` needed to change flow run state from the dialogue
> api layer changes for flow run state dialogue

- ui-v2/src/components/blocks/block-document-data-table/block-document-data-table.stories.tsx
- ui-v2/src/components/blocks/block-document-data-table/block-document-data-table.tsx
- ui-v2/src/components/blocks/blocks-page.tsx
- ui-v2/src/components/blocks/blocks-row-count/blocks-row-count.test.tsx
- ui-v2/src/components/blocks/blocks-row-count/blocks-row-count.tsx
- ui-v2/src/components/blocks/blocks-row-count/index.ts
- ui-v2/src/components/blocks/use-delete-block-document-confirmation-dialog.ts
- ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-row-count.tsx
- ui-v2/src/routes/blocks/index.tsx
1. Adds row count and delete component for blocks page
2. Updates deletion dialog logic to occur in the row count component.
3. Removes unnecessary comments from previous PR
4. Updates to use query for all blocks count
https://github.com/user-attachments/assets/1e97935d-c29f-483c-abc2-73f8bf31fe95
> feat: Adds row count and delete component to blocks page

- ui-v2/src/api/block-documents/block-documents.ts
- ui-v2/src/components/blocks/blocks-page-header.tsx
- ui-v2/src/components/blocks/blocks-page.tsx
- ui-v2/src/routes/blocks/index.tsx
1. Adds search feature for blocks table
2. Simplifies search parameter to be flatter.
3. Moves queries in the routes page
https://github.com/user-attachments/assets/daeb328a-d518-43d3-80bf-90bc80893575
> feat: Adds search feature for blocks page

- ui-v2/src/components/blocks/block-types-multi-select/block-types-multi-select.stories.tsx
- ui-v2/src/components/blocks/block-types-multi-select/block-types-multi-select.tsx
- ui-v2/src/components/blocks/blocks-page.tsx
- ui-v2/src/routes/blocks/index.tsx
1. Updates block type multiselect to use an Array data structure for simplicity. Additionally, updates component to return the slug field, rather than the id
2. Adds block type filtering UX
https://github.com/user-attachments/assets/d20a8154-ec2c-490a-9662-084e9056d0b0
> [UI v2] feat: Adds block type filtering to blocks page

- src/integrations/prefect-dask/prefect_dask/task_runners.py
- src/integrations/prefect-dask/tests/test_task_runners.py
closes https://github.com/PrefectHQ/prefect/issues/17734
> `prefect-dask`: fix string `cluster_class` instantiation

- ui-v2/src/api/flow-runs/index.ts
- ui-v2/src/api/logs/index.ts
- ui-v2/src/api/task-runs/index.ts
- ui-v2/src/api/task-runs/task-runs.test.ts
- ui-v2/src/components/task-runs/task-run-details-page.tsx
- ui-v2/src/components/task-runs/task-run-details-page/index.tsx
- ui-v2/src/components/task-runs/task-run-details-page/task-run-details-page.test.tsx
- ui-v2/src/components/task-runs/task-run-details/task-run-details.test.tsx
- ui-v2/src/components/task-runs/task-run-details/task-run-details.tsx
- ui-v2/src/components/task-runs/task-run-logs/index.tsx
- ui-v2/src/components/task-runs/task-run-logs/task-run-logs.test.tsx
- ui-v2/src/components/ui/run-logs/index.tsx
- ui-v2/src/components/ui/state-badge/index.tsx
- ui-v2/src/mocks/create-fake-flow-run.ts
- ui-v2/src/mocks/create-fake-state.ts
- ui-v2/src/mocks/create-fake-task-run.ts
- ui-v2/src/routes/runs/task-run.$id.tsx
Adds most of the task run details page. The component uses the infinite and virtualized log view to give a "real-time" view of logs. The page also polls the API as long as the task is in a `RUNNING` state.
https://github.com/user-attachments/assets/0ef2f831-dc1b-48b9-bc86-12fe80eea28c
> [UI v2] Task run details page

- ui-v2/src/api/task-runs/index.ts
- ui-v2/src/api/task-runs/task-runs.test.ts
preparing for https://github.com/PrefectHQ/prefect/pull/17704
> add task run state mutation

- ui-v2/src/components/blocks/block-document-data-table/block-document-data-table.tsx
- ui-v2/src/components/blocks/blocks-page.tsx
- ui-v2/src/routes/blocks/index.tsx
Adds pagination to blocks table
https://github.com/user-attachments/assets/2bcd68dd-30af-44bc-ba57-92cb4c8725a1
> [UI-v2] feat: Adds pagination to blocks table

- ui-v2/package-lock.json
- ui-v2/package.json
- ui-v2/src/components/block-type-logo/block-type-logo.stories.tsx
- ui-v2/src/components/block-type-logo/block-type-logo.tsx
- ui-v2/src/components/blocks/block-document-data-table/block-document-cell.tsx
- ui-v2/src/components/blocks/block-type-page/block-type-page.stories.tsx
- ui-v2/src/components/blocks/block-type-page/block-type-page.tsx
- ui-v2/src/components/blocks/block-type-page/index.ts
- ui-v2/src/components/deployments/deployment-description.tsx
- ui-v2/src/components/ui/python-input.tsx
- ui-v2/src/mocks/create-fake-block-type.ts
- ui-v2/src/mocks/index.ts
- ui-v2/src/routeTree.gen.ts
- ui-v2/src/routes/blocks/catalog_.$slug.create.tsx
1. Adds block type details page
2. Adds python input component using codemirror python extension
3. Consolidates block type logos with a new `BlockTypeLogo` component
4. Updates markup components to not have a reduced width
5. Adds block type slug create route
https://github.com/user-attachments/assets/8119768e-d015-4dd7-b308-b670327bebbf
> [UI v2] feat: Adds block type page component

- ui-v2/src/components/blocks/blocks-catalog-page/index.ts
- ui-v2/src/components/blocks/blocks-page.tsx
- ui-v2/src/routeTree.gen.ts
- ui-v2/src/routes/blocks/catalog.tsx
- ui-v2/src/routes/blocks/catalog_.$slug_.create.tsx
1. Adds button in Blocks page to lead to the catalog page
2. Integrates BlocksCatalogPage to route with search
https://github.com/user-attachments/assets/36ff1676-04d9-4a54-a47a-0d3b7087dc51
> [UI v2] feat: Integrates BlocksCatalogPage to route with search

- ui-v2/src/api/block-documents/block-documents.test.ts
- ui-v2/src/api/block-documents/block-documents.ts
- ui-v2/src/api/block-documents/index.ts
Adds RQ query to get block document by id. This is needed for the block document details page
> [UI v2] feat: Adds RQ query to get block document by id

- ui-v2/src/components/blocks/block-document-action-menu/block-document-action-menu.tsx
- ui-v2/src/components/blocks/block-document-details-page/block-document-details-page-header.tsx
- ui-v2/src/components/blocks/block-document-details-page/block-document-details-page.tsx
- ui-v2/src/components/blocks/block-document-details-page/block-document-schema-properties.tsx
- ui-v2/src/components/blocks/block-document-details-page/block-type-details.tsx
- ui-v2/src/components/blocks/block-type-page/block-type-page.tsx
- ui-v2/src/components/blocks/blocks-row-count/blocks-row-count.tsx
- ui-v2/src/components/blocks/python-example-snippet.tsx
- ui-v2/src/routeTree.gen.ts
- ui-v2/src/routes/blocks/block.$id.tsx
- ui-v2/src/routes/blocks/block_.$id.edit.tsx
1. Scaffolds BlockDocumentDetailsPage
2. Updates ActionMenu to direct to `/edit` page
https://github.com/user-attachments/assets/ac53bf93-8046-4530-94b2-f484ddc43326
> [UI v2] feat: Scaffolds block document details page

- ui-v2/src/api/block-schemas/block-schemas.test.ts
- ui-v2/src/api/block-schemas/block-schemas.ts
- ui-v2/src/api/block-schemas/index.ts
- ui-v2/src/mocks/create-fake-block-schema.ts
- ui-v2/src/mocks/index.ts
- ui-v2/tests/utils/handlers.ts
1. Starts RQ queries for `block_schemas`. This is needed for creating and editing a new block
> [UI v2] feat: Adds block_schemas RQ queries

- ui-v2/src/api/block-documents/block-documents.test.ts
- ui-v2/src/api/block-documents/block-documents.ts
- ui-v2/src/api/block-documents/index.ts
- ui-v2/tests/utils/handlers.ts
Adds mutation to update a block document
> Add update block document mutation

- src/prefect/telemetry/instrumentation.py
- tests/telemetry/test_instrumentation.py
closes https://github.com/PrefectHQ/prefect/issues/17823
> use platform independent method in telemetry instrumentation

- docs/docs.json
- docs/v3/automate/add-schedules.mdx
- docs/v3/deploy/index.mdx
- docs/v3/deploy/infrastructure-concepts/deploy-via-python.mdx
- docs/v3/deploy/infrastructure-concepts/store-flow-code.mdx
- docs/v3/deploy/infrastructure-examples/docker.mdx
- docs/v3/deploy/run-flows-in-local-processes.mdx
- docs/v3/develop/cancel.mdx
- docs/v3/develop/write-flows.mdx
- src/prefect/flows.py
- tests/typesafety/test_flows.yml
improves the clarity of the remote code storage page as well as general updates to replace "work pool-based deployments" with more descriptive language, like "deployments associated with a work pool" or "deployments with dynamic dispatch of infrastructure per flow run"
[preview build](https://prefect-bd373955-storage-option-docs.mintlify.app/v3/deploy/infrastructure-concepts/store-flow-code)
---
This pull request involves multiple changes to the documentation, primarily focusing on updating terminology and improving clarity regarding deployment methods and infrastructure concepts. The most important changes are grouped by theme below:
* Updated references to "work pool-based deployments" to "deployments with dynamic infrastructure" across various documentation files to align with new …
> update deployment and remote code storage docs

- src/prefect/cli/work_pool.py
- tests/cli/test_work_pool.py
This PR expands the work pool storage configuration CLI to include Azure Blob Storage.
Example:
```
~/d/P/prefect ❯❯❯ uv run prefect work-pool storage configure azure-blob-storage olympic \
--container my-container \
--azure-blob-storage-credentials-block-name my-azure-blob-storage-creds
Configured Azure Blob Storage for work pool 'olympic'
~/d/P/prefect ❯❯❯ uv run prefect work-pool storage inspect olympic
╭───────────────────── Storage Configuration for olympic ─────────────────────╮
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
│ ┃ Setting                                   ┃ Value                       ┃ │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
│ │ type                                      │ Azure Blob Storage …
```
> Add CLI to configure Azure Blob Storage for a work pool

- docs/integrations/prefect-slack/index.mdx
> update sync/async example in `prefect-slack`

- docs/integrations/prefect-dbt/index.mdx
Removes some outdated references from the dbt integration docs in preparation for revisiting those concepts.
> Clean up dbt integration docs

- src/prefect/cache_policies.py
hmm im not actually sure why that error popped up on that PR i linked
see https://github.com/PrefectHQ/prefect/actions/runs/14506792219/job/40698042377
> fix pyright errors

- docs/conftest.py
- docs/docs.json
- docs/v3/deploy/run-flows-on-hetergeneous-infrastructure.mdx
- docs/v3/deploy/submit-flows-directly-to-dynamic-infrastructure.mdx
> Add initial documentation for submitting workflows directly to dynamic infrastructure

- src/prefect/deployments/steps/pull.py
- src/prefect/runner/storage.py
- tests/deployment/test_steps.py
- tests/runner/test_storage.py
Closes #17904
If a `commit_sha` is provided to the step or is present on a `GitRepository`, that commit will be checked out after the pull/clone happens.
> Allow providing a commit sha to the `git_clone` pull step

- src/integrations/prefect-snowflake/prefect_snowflake/credentials.py
- src/integrations/prefect-snowflake/tests/test_credentials.py
closes #17883 
This pull request improves the handling of PEM certificate parsing and adds a regression test to ensure encrypted private keys are processed correctly. The most important changes include refining the regex for PEM certificates, enhancing error handling in `_compose_pem`, and introducing a new test for encrypted private key parsing.
* Updated `_SIMPLE_PEM_CERTIFICATE_REGEX` to handle multiline PEM certificate bodies more robustly by using a non-greedy match for the body section (`[\s\S]+?`) instead of `[^-]+`.
* Refined `_compose_pem` to strip leading/trailing whitespace from the decoded private key before matching and simplified the body processing logic. Added error handling for `UnicodeDecodeError` to raise a more descriptive `InvalidPemFormat` exception when decoding …
> fix regex for snowflake private keys

- src/prefect/_internal/schemas/validators.py
- src/prefect/server/schemas/actions.py
- tests/server/orchestration/api/test_variables.py
Closes: https://github.com/PrefectHQ/prefect/issues/17865
> Chore: Update variable name validator to allow hyphens

- src/prefect/cli/work_pool.py
- tests/cli/test_work_pool.py
Fixes an issue with GCS work pool storage raised in https://github.com/PrefectHQ/prefect/issues/17194#issuecomment-2855750764.
> Fix generated work pool storage config for GCS

- docs/docs.json
- docs/v3/how-to-guides/workflows/form-building.mdx
Moves a tutorial with no content changes
> Move a tutorial to a how-to

- docs/docs.json
- docs/v3/advanced/interactive.mdx
- docs/v3/advanced/transactions.mdx
- **Move transactions docs to Advanced**
- **Move write interactive workflows guide to Advanced**
> Move transactions and interactive workflows guides

- docs/docs.json
- docs/v3/concepts/cancel-workflows.mdx
- docs/v3/how-to-guides/workflows/write-and-run.mdx
Seems like there should be a cancel how-to guide, but the current docs were *very* concept. We should probably create a more how-to oriented guide for cancellation.
I also wasn't sure where to put info about timeouts. Didn't seem large enough to be its own guide, so I put it in "How to write and run a workflow", but I'm game to move it somewhere else.
> Move cancel workflows docs to concepts

- docs/v3/advanced/interactive.mdx
> remove counterproductive admoninition

- src/integrations/prefect-ray/prefect_ray/task_runners.py
- src/prefect/task_engine.py
- tests/test_tasks.py
- demote ray task runner log to DEBUG
- more accurate log when a task _without retries_ fails
> minor log cleanup

- src/prefect/_internal/concurrency/calls.py
- tests/_internal/concurrency/test_calls.py
closes https://github.com/PrefectHQ/prefect/issues/18080
> fix `AttributeError` after args/kwargs deletion

- src/integrations/prefect-redis/prefect_redis/messaging.py
- src/prefect/server/events/schemas/automations.py
- src/prefect/server/events/services/actions.py
- src/prefect/server/events/services/event_logger.py
- src/prefect/server/events/services/event_persister.py
- src/prefect/server/events/services/triggers.py
- src/prefect/server/events/triggers.py
- src/prefect/server/services/task_run_recorder.py
- src/prefect/server/utilities/messaging/_consumer_names.py
- src/prefect/server/utilities/messaging/memory.py
this is the first in a series of PRs related to https://github.com/PrefectHQ/prefect/discussions/18150
this PR creates a central util for making unique consumer names to avoid distribution weirdness in multi-server setups
> multi-server setup fixes pt1

- src/prefect/task_runners.py
closes https://github.com/PrefectHQ/prefect/issues/18144
> add thread local context note

- src/integrations/prefect-docker/prefect_docker/worker.py
- src/integrations/prefect-docker/tests/test_worker.py
> merge duplicate `extra_hosts` kwarg

- docs/docs.json
- docs/v3/how-to-guides/index.mdx
Adds how-to overview page for faster navigation
> Add how-to page overview

- src/prefect/_internal/schemas/validators.py
- src/prefect/client/schemas/objects.py
- src/prefect/server/schemas/core.py
- tests/test_tasks.py
closes https://github.com/PrefectHQ/prefect/issues/18199
> fix fractional value handling in retry delay policy

- src/prefect/events/clients.py
> Adds missing increments for events client metrics

- src/prefect/tasks.py
- tests/typesafety/test_tasks.yml
closes https://github.com/PrefectHQ/prefect/issues/18140
> fix async retry fn typing

- tests/server/orchestration/api/test_variables.py
Implements comprehensive test coverage for the variable duplication feature with test cases covering basic variable cloning, name conflict validation, original data preservation, multiple copy creation, chain duplication scenarios, and proper handling of JSON and null values during duplication.
Related PR: [UI implementation](https://github.com/PrefectHQ/prefect-ui-library/pull/3048)
Co-author-by: Tiago Bernardo @tiagogb1 <tiago.gomes.bernardo@tecnico.ulisboa.pt>
> Add tests for UI variable duplication enhancement

- docs/integrations/prefect-bitbucket/sdk.mdx
- docs/integrations/prefect-dask/sdk.mdx
- docs/integrations/prefect-databricks/sdk.mdx
Fixes incorrect URL references to SDK packages.
> Fix incorrect links to SDK

- docs/v3/concepts/server.mdx
- src/prefect/server/database/_migrations/versions/postgresql/2025_04_04_092158_7a73514ca2d6_add_ix_events__event_related_occurred_.py
closes https://github.com/PrefectHQ/prefect/issues/18263
> add note about long migrations with big tables

- src/prefect/futures.py
- tests/test_futures.py
closes #18278
the bug seemed to be about eventual consistency between the event system and the API
When a task completes:
1. The worker emits a completion event
2. `TaskRunWaiter` receives the event and returns from `wait_for_task_run()`
3. `wait_async()` then reads the task run state from the API
4. Due to eventual consistency, the API might still show the task as `Running`
5. So `_final_state` is not set, causing `result_async()` to timeout
1. In `wait_async()`: Don't cache non-final states after waiting
2. In `result_async()`: If `_final_state` is not set after `wait_async()`, make one 
additional attempt to read the state directly from the API
3. This handles the eventual consistency without arbitrary retries or delays
> fix `TimeoutError` in `result_async` when accessing results from `delay`

- src/integrations/prefect-snowflake/prefect_snowflake/database.py
- src/integrations/prefect-snowflake/tests/conftest.py
- src/integrations/prefect-snowflake/tests/test_database.py
Closes https://github.com/PrefectHQ/prefect/issues/18239
This pull request enhances the handling of Snowflake connections in the `prefect-snowflake` integration by improving connection reuse logic and adding tests to ensure proper functionality. The most important changes include updating the connection reuse condition, mocking connection closure in tests, and adding new test cases for multiple connection calls.
* [`src/integrations/prefect-snowflake/prefect_snowflake/database.py`](diffhunk://#diff-281c3008f93f32c1f2beffcfb69f35564230d262ada7c0141ec06542e625c036L144-R144): Updated the `get_connection` method to check if the existing connection is closed before reusing it. This ensures that only active connections are reused.
* [`src/integrations/prefect-snowflake/tests/conftest.py`](diffhu …
> Fix for issue 18239

- docs/docs.json
- docs/v3/how-to-guides/self-hosted/server-cli.mdx
- docs/v3/how-to-guides/self-hosted/server-docker.mdx
"self-host prefect with the cli" was awkward
> improve self-host guide name

- src/prefect/client/cloud.py
- src/prefect/client/orchestration/__init__.py
- src/prefect/serializers.py
- src/prefect/server/database/configurations.py
- src/prefect/server/utilities/database.py
supersedes https://github.com/PrefectHQ/prefect/pull/18136
type adapters are expensive to create. i considered a global type adapter cache but decided to punt on that for now to be safe
> serialization performance improvements

- src/prefect/server/utilities/user_templates.py
- tests/events/server/actions/test_jinja_templated_action.py
backport of https://github.com/PrefectHQ/prefect/pull/18232
> backport jinja max range fix

- docs/v3/api-ref/rest-api/server/schema.json
- docs/v3/api-ref/settings-ref.mdx
- schemas/settings.schema.json
- ui-v2/src/api/prefect.ts
some pre-push hooks did not run because they were not installed locally - this PR just runs the pre-push hooks so it doesn't pollute other PRs
I'll follow up in a separate PR with instructions on installing them to the OSS contributing guide (edit: https://github.com/PrefectHQ/prefect/pull/18332)
> run pre-push hooks

- ui/src/components/ApiStatusToast.vue
- ui/src/services/apiStatus.ts
- ui/src/services/csrfTokenApi.ts
- ui/src/utilities/api.ts
This PR adds a new axios interceptor that we can use to show helpful messages on configuration or managed opportunities. The toast is dismissible and that dismissal will be respected until the page is refreshed.
> Enhancement: Add an axios middleware for intercepting errors 

- src/integrations/prefect-aws/pyproject.toml
- src/integrations/prefect-dask/pyproject.toml
- src/integrations/prefect-ray/pyproject.toml
closes https://github.com/PrefectHQ/prefect/issues/18381
> update pins on core

- docs/docs.json
- docs/v3/advanced/worker-healthchecks.mdx
> Adds Worker healthcheck advanced guide

- docs/v3/how-to-guides/deployments/create-schedules.mdx
Closes https://github.com/PrefectHQ/prefect/issues/17503
> Add section of examples on schedule CLI

- docs/docs.json
- docs/v3/how-to-guides/self-hosted/server-windows.mdx
> Add how to guide for running prefect server on windows

- src/prefect/server/api/artifacts.py
- src/prefect/server/api/block_schemas.py
- src/prefect/server/api/block_types.py
- src/prefect/server/api/concurrency_limits.py
- src/prefect/server/api/deployments.py
- src/prefect/server/api/flow_run_states.py
- src/prefect/server/api/flow_runs.py
- src/prefect/server/api/flows.py
- src/prefect/server/api/saved_searches.py
- src/prefect/server/api/task_run_states.py
- src/prefect/server/api/task_runs.py
- src/prefect/server/api/ui/task_runs.py
- src/prefect/server/api/work_queues.py
- tests/server/orchestration/api/test_flow_runs.py
Closes https://github.com/PrefectHQ/prefect/issues/6542
> Use UUID path converter in all places

- tests/cli/test_flow.py
- tests/cli/test_flow_run.py
These changes fix the failing tests introduced by https://github.com/PrefectHQ/prefect/pull/18450
> Fix failing unit tests

- docs/v3/get-started/github-quickstart.mdx
- docs/v3/get-started/quickstart.mdx
Adds a quickstart that can be visited from the "Connect Github" button in the UI dashboard's empty state, but is hidden in the docs nav.
> New quickstart

- tests/_internal/test_websockets.py
Adds a test to ensure that custom headers work with the `websocket_connect` utility function to prevent regression like the one found in https://github.com/PrefectHQ/prefect/issues/18477
> Update test to connect to websocket with custom headers

- .github/CODEOWNERS
> Update dbt integration codeowners

- .github/workflows/static-analysis.yaml
follow up to https://github.com/PrefectHQ/prefect/pull/18504
https://github.com/pre-commit/pre-commit.com/blob/main/sections/advanced.md#temporarily-disabling-hooks
> skip no-commit-to-branch check on merge to main

- docs/docs.json
> Chore: update docs logo link from prefect.io => docs.prefect.io

- docs/v3/concepts/states.mdx
adds missing state entries to the states docs table
> add more states to docs

- docs/v3/get-started/github-quickstart.mdx
> Add detail and options to the GitHub Quickstart

- pyrightconfig-ci.json
- src/integrations/prefect-docker/prefect_docker/deployments/steps.py
- src/prefect/_internal/installation.py
- src/prefect/cli/_prompts.py
- src/prefect/cli/worker.py
- src/prefect/deployments/steps/core.py
- src/prefect/infrastructure/provisioners/coiled.py
- src/prefect/infrastructure/provisioners/ecs.py
- src/prefect/infrastructure/provisioners/modal.py
- src/prefect/utilities/dockerutils.py
- tests/_internal/test_installation.py
- tests/cli/test_worker.py
- tests/deployment/test_steps.py
- tests/docker/test_image_builds.py
- tests/infrastructure/provisioners/test_ecs.py
- tests/infrastructure/provisioners/test_modal.py
- tests/test_infrastructure_bound_flow.py
Closes https://github.com/PrefectHQ/prefect/issues/18598
> Update ad hoc installations to use `uv` if available

- src/prefect/concurrency/_leases.py
> check future is if cancelled.

- src/prefect/_internal/compatibility/migration.py
Fix the upgrade guide URL in the migration module
> Fix the upgrade guide URL

- docs/v3/how-to-guides/deployments/create-schedules.mdx
> note about `to_deployment`

- docs/v3/release-notes/oss/version-3-4.mdx
> prepare 3.4.12: 20k magic in the air

- docs/integrations/use-integrations.mdx
Minor docs update to fix broken link.
> Update use-integrations.mdx to reflect removal of setup.py

- docs/integrations/use-integrations.mdx
> Fix typos in "Use integrations" documentation

- src/integrations/prefect-redis/prefect_redis/messaging.py
- src/integrations/prefect-redis/tests/test_messaging.py
follow up https://github.com/PrefectHQ/prefect/pull/18642
> only delete groups that start with `ephemeral`

- docs/integrations/prefect-aws/ecs/iam/secrets/secrets-manager/secret-policy.json
- docs/integrations/prefect-aws/ecs/iam/secrets/ssm-parameter-store/secret-policy.json
- docs/integrations/prefect-aws/ecs/iam/task-definition.json
- docs/integrations/prefect-aws/ecs/iam/trust-policy.json
- docs/integrations/prefect-aws/ecs/iam/worker-policy.json
- docs/integrations/prefect-aws/ecs_guide.mdx
* Mintlify the shit out of the ECS Worker guide.
* Adds steps to rectify missing IAM permissions that caused the worker to be unable to _actually_ run flows.
Resolves #16385 
> Overhaul ECS Worker Guide

- .github/workflows/integration-package-release.yaml
Should fix this failure https://github.com/PrefectHQ/prefect/actions/runs/17250643133/job/48951822896
> Fix CloudFormation template generation during `prefect-aws` release

- src/prefect/client/orchestration/_artifacts/client.py
- tests/client/test_prefect_client.py
This PR adds artifact created and updated events to the prefect client.
Closes ENG-2671
> Add artifact created and updated events

- ui-v2/eslint.config.js
- ui-v2/src/components/ui/calendar.tsx
- ui-v2/src/components/ui/date-range-picker/date-range-picker.stories.tsx
- ui-v2/src/components/ui/date-range-picker/date-range-picker.test.tsx
- ui-v2/src/components/ui/date-range-picker/date-range-picker.tsx
- ui-v2/src/components/ui/date-range-picker/index.ts
Adds a reusable DateRangePicker built on react-day-picker, following existing DateTimePicker patterns. 
Related to #15512
> [UI v2] Add `DateRangePicker` component

- src/integrations/prefect-dbt/prefect_dbt/core/runner.py
- src/integrations/prefect-dbt/prefect_dbt/utilities.py
- src/integrations/prefect-dbt/tests/test_utilities.py
Closes #18980
This PR fixes a breaking change introduced in prefect-dbt 0.7.7 where dbt commands with positional arguments (like `debug`) would fail with "No such option: --profiles-dir" errors.
PR #18952 changed how kwargs are passed to dbt by converting them to CLI args via `kwargs_to_args()`. However, this introduced two issues:
1. **Lost positional arguments**: The `_parse_args_to_flag_groups()` function only captured flag arguments (`--flag value`) but dropped positional arguments like the dbt command name (`debug`)
2. **Invalid flags for commands**: Some kwargs like `target_path` were being passed to all dbt commands, but commands like `debug` don't accept `--target-path`, causing "No such option" errors
1. **Preserve positional arguments** in `utilities.py`:
- Modified …
> Fix dbt kwargs handling to preserve positional args and validate command flags

- src/prefect/server/events/ordering/memory.py
- tests/events/server/test_in_memory_ordering.py
Replaces manual timestamp-based event tracking with `TTLCache` in memory-based `CausalOrdering` to prevent unbounded memory growth.
- Use `TTLCache[UUID, bool]` instead of `dict[UUID, datetime]` for `_seen_events`
- Auto-expires after 30 minutes, max 10k entries
- Remove O(n) `_cleanup_seen_events()` method
- Update test to verify TTLCache behavior
- Automatic memory management with TTL-based expiration
- Bounded memory usage (max 10k entries)
- Better performance (no O(n) scans per event)
- Consistency with database-based implementation
Related to #18605
> Use TTLCache for memory-based CausalOrdering to prevent memory leaks

- docs/v3/release-notes/index.mdx
> docs: link to available integrations release notes
