docs/3.0/develop/global-concurrency-limits.mdx

This PR tweaks global concurrency limits docs to account for recent changes from #15297 .
| **Before** | **After** |
| <img width="1280" alt="image" src="https://github.com/user-attachments/assets/8cb628d8-f084-4344-ab13-94ba20b7fc1f"> | <img width="1279" alt="image" src="https://github.com/user-attachments/assets/f777e7bf-a315-4fc4-b274-4d7a4db2294b"> |

Update global concurrency limits docs for removed create_if_missing behavior

---

docs/mint.json

Link to prefect.io from the logo in the top left of the docs.
We didn't have a link to the site.
Now clicking on the logo behaves as one would expect.
Looking at the first five libraries I thought of in the orchestration space, the logos on their docs sites all link to their primary non-docs websites. 
cc: @seanpwlms - thank you for raising!

Docs Prefect logo link to prefect.io

---

docs/3.0/deploy/index.mdx
docs/3.0/deploy/infrastructure-concepts/prefect-yaml.mdx

This PR updates docs to include deployment concurrency limit fields.
Closes OSS-5617

Docs for deployment concurrency limits

---

docs/3.0/develop/transactions.mdx
src/prefect/transactions.py

This PR updates `write_on_commit` to default to `True` on the `transaction` context manager. 
Previously, it defaulted to the value of `PREFECT_RESULTS_PERSIST_BY_DEFAULT` outside of a task or flow, which defaults to `False`. In most cases, user-defined transactions must explicitly set `write_on_commit` to `True`. 
This behavior feels unintuitive, so this PR changes that. This change doesn't affect task transactions since they explicitly provide a value for `write_on_commit` based on the context in which they are run.

Update `transaction` context manager to default `write_on_commit` to `True`

---

src/prefect/cli/cloud/__init__.py
src/prefect/client/cloud.py
tests/client/test_cloud_client.py

this PR adds a cloud client method to read the current workspace. it also deprecates `prefect cloud open` in favor of the more general `prefect dashboard open`
---
copilot summary
* [`src/prefect/cli/cloud/__init__.py`](diffhunk://#diff-7a5d84ab59363d3aaed9feb4cd5415cf97129147328588935c36047d897b0eaeL560-R565): Deprecated the `prefect cloud open` command and added a deprecation message suggesting the use of `prefect dashboard open` instead.
* [`src/prefect/cli/cloud/__init__.py`](diffhunk://#diff-7a5d84ab59363d3aaed9feb4cd5415cf97129147328588935c36047d897b0eaeR578-L576): Updated the `open` function to use an asynchronous context manager for retrieving the current workspace.
* [`src/prefect/client/cloud.py`](diffhunk://#diff-5a511ac64f00b69748c693dfcb62f815958978fea3a9abe42e0698d298f55d13R1 …

add `get_current_workspace` cloud client method

---

docs/3.0/develop/task-caching.mdx

Updates example to better show the difference in behavior when tasks use a cache policy with a  `READ_COMMITTED` isolation level vs `SERIALIZABLE`.

Update cache isolation example to show different behavior between isolation levels

---

src/prefect/results.py
tests/test_tasks.py

This PR fixes errors raised when a task is run in a `SERIALIZABLE` transaction without a lock manager specified within a task's cache policy.
There's a larger question of how much of the `store` a child transaction should inherit from its parent. I think the most intuitive approach might be to have a child transaction use the parent's `store` if it isn't given one, but this change would still be necessary in that case since the task engine provides a `ResultStore` to each task's transaction.
Closes https://github.com/PrefectHQ/prefect/issues/15503

Update tasks to inherit the lock manager from a parent transaction if present

---

.github/workflows/nightly-release.yaml

I forgot to set `next_tag` in `$GITHUB_OUTPUT` to make it available in the last step. This PR fixes that.

Fix bug in nightly release workflow

---

.github/workflows/markdown-tests.yaml
.github/workflows/nightly-release.yaml
requirements-markdown-tests.txt
setup.py

This PR fixes the name for created releases in GitHub to use the next tag. This PR also removes the `markdown-tests` extra because I saw this error when trying to publish to PyPI:
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
Can't have direct dependency: pytest-markdown-docs@                    
git+https://github.com/PrefectHQ/pytest-markdown-docs@mdx-comment-suppo
rt ; extra == "markdown-tests". See                                    
https://packaging.python.org/specifications/core-metadata for more     
information.    
```
I think once we are using a published version of `pytest-markdown-docs`, we can add that extra back, but I removed it for now to unblock publishing to PyPI.

Fix dev nightly release errors

---

src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/pyproject.toml
src/integrations/prefect-kubernetes/tests/test_worker.py

This PR updates the Kubernetes worker to avoid marking a flow run as crashed if the container within the flow is still running when the job watch exits. This won't address the root cause of issues like https://github.com/PrefectHQ/prefect/issues/15259, but it will prevent flow runs from errantly being marked as crashed. 
This PR also improves the error logging when the job watch encounters an exception. In its current state, we can't see what error is causing the job watch to stop.

Avoid crashing flows when Kubernetes job watch exits but the container is still running

---

src/integrations/prefect-sqlalchemy/prefect_sqlalchemy/credentials.py

closes  https://github.com/PrefectHQ/prefect/issues/15511

Make database parameter optional in ConnectionComponents  #15511

---

src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/tests/test_worker.py

ensure list can be used with `env` in `KubernetesWorkerJobConfiguration`

---

.github/workflows/docker-images.yaml

Fixes the error from [this job](https://github.com/PrefectHQ/prefect/actions/runs/11116907648) when attempting to publish Docker images for a nightly build.
This was the error:
```
Error: Tag refs/tags/3.0.4.dev1 does not match prerelease version pattern.
```
This check matches the one on the Publish Python Package workflow

Fix check to prerelease tag to allow nightly builds to publish Docker images

---

.github/workflows/nightly-release.yaml

Fixes the release name to include the correct version tag. Also updates the format to match other releases. Release names will now look like `3.0.5.dev2: Nightly Development Release`.

Update format for nightly dev release names

---

.github/workflows/prefect-client-publish.yaml
.github/workflows/prefect-client.yaml
docs/guides/migration-guide.md

This PR fixes an issue that's been bugging me about 2.x releases: when released, the publish `prefect-client` job runs a _reusable_ workflow that has a matrix strategy in it. Because of that + the fact that the caller specifies a single artifact name output, the job errors out and I have to manually rerun it 4 times to get through that workflow.
This PR semi-hacks the matrix strategy so that the calling workflow can pass a single python version, hopefully avoiding that headache in the future. 
Closes https://github.com/PrefectHQ/prefect/issues/15053

Fix client release action for 2.x

---

.codespellrc
src/prefect/client/orchestration.py
src/prefect/exceptions.py
src/prefect/utilities/text.py
tests/client/test_prefect_client.py
tests/utilities/test_text.py

closes https://github.com/PrefectHQ/prefect/issues/15571
uses `difflib` to get fuzzy string matching
```python
ObjectNotFound: Deployment 'hello/hello-moo-deng' not found; did you mean 'hello/hello'?
```
---
this might be over-wraught, but I do think it will be helpful. very open to suggestions

helpful message on 404 with deployment by name

---

src/prefect/cache_policies.py
tests/test_cache_policies.py

In some cases, `inspect.getsource` can raise `OSError("source not available")`, in addition to `OSError("could not find source")` (see: https://github.com/python/cpython/blob/3.12/Lib/inspect.py#L1088 and https://github.com/python/cpython/blob/3.12/Lib/inspect.py#L1096)
It seems appropriate to handle both instances of `OSError` with the same fallback. This commit simply expands the fallback handler to also check for `source not available` errors.
Closes https://github.com/PrefectHQ/prefect/issues/15384

Changed `TaskSource` key computation to handle `OSError("source not available")`

---

.github/workflows/benchmarks.yaml
.github/workflows/codspeed-benchmarks.yaml
benches/conftest.py
docs/3.0/api-ref/rest-api/server/schema.json
setup.cfg
src/prefect/context.py
src/prefect/settings.py
tests/conftest.py
tests/results/test_result_fetch.py
tests/server/api/test_server.py
tests/test_context.py
tests/test_settings.py

closes https://github.com/PrefectHQ/prefect/issues/11777
this PR is a follow-on to #15412 that defines a custom settings source for prefect profiles
other important changes/implications:
- enables support for overriding settings from a `.env` file
- stops using `use_profile` in `root_settings_context`
- skips some chronically flaky tests that I will need to come back and figure out
```console
» prefect config view
🚀 you are connected to:
https://app.prefect.cloud/account/{acct}/workspace/{ws}
PREFECT_PROFILE='pong'
PREFECT_API_KEY='********' (from profile)
PREFECT_API_URL='https://api.prefect.cloud/api/accounts/{acct}/workspaces/{ws}' (from profile)
» python -c "from prefect.settings import Settings; print(Settings().logging_level)"
INFO
» prefect config set PREFECT_LOGGING_LEVEL=CRITICAL …
```

Allow specifying settings overrides in a `.env`

---

docs/3.0/develop/global-concurrency-limits.mdx

Awaiting task submissions in the async code examples throws an error with Prefect 3.0. ie:
TypeError: object PrefectConcurrentFuture can't be used in 'await' expression
Updating the examples so that `await` is no longer included before submitting a task allows them to complete successfully.

Update global-concurrency-limits.mdx - Remove `await` for task submissions

---

src/prefect/results.py
tests/results/test_base_result.py

related to https://github.com/PrefectHQ/prefect/issues/15585

fail correctly if `lookup_type` throws a `KeyError` in `BaseResult.__new__`

---

src/integrations/prefect-aws/prefect_aws/client_parameters.py
src/integrations/prefect-aws/tests/test_client_parameters.py

update `AwsClientParameters` validation for `verify`

---

src/prefect/transactions.py
tests/test_transactions.py

In the [_Access data in transactions_ example](https://docs.prefect.io/3.0/develop/transactions#access-data-within-transactions), the rollback hook of a task that completes attempts to get a value not available in its stored values, but fails to determine its parent transaction. When completing the child transaction, the reference to the transaction context variable is dropped, so the transaction errors when determining its parent. 
This PR fixes the error by falling back to the current transaction when the stored token for the transaction context variable has already been cleared. The example code runs as expected with this change.
Closes https://github.com/PrefectHQ/prefect/issues/15593

Fix issue where transaction parent look up fails in rollback hooks

---

src/prefect/settings.py
tests/test_settings.py

Fixes a bug where settings fail to load when there is no file at the path specified via `PREFECT_PROFILES_PATH`. Also adds handling if the profiles file is not valid TOML.

Fix errors loading settings when profiles file can't be read

---

src/prefect/flows.py
tests/test_flows.py

closes https://github.com/PrefectHQ/prefect/issues/15610
see upstream issue https://github.com/pydantic/pydantic/issues/10575

Fix flow run parameters literally named `keys`

---

src/prefect/settings.py
tests/test_settings.py

this PR forgets field defaults "set" in the model after validator, so that `exclude_unset` gives us the actually "set" fields
> [!IMPORTANT]
> We should _NOT_ be accessing / modifying / or otherwise relying upon any dunder attr like `__pydantic_fields_set__`, but in this case we need to as a consequence of the workaround for https://github.com/pydantic/pydantic/issues/9789

unset default dependent settings assigned posthoc

---

src/prefect/client/schemas/objects.py
src/prefect/deployments/flow_runs.py

closes https://github.com/PrefectHQ/prefect/issues/15591
Rebuilt `StateCreate` model to resolve runtime errors during deployment execution caused by incomplete model definitions / circular import woes

rebuild `StateCreate` model

---

docs/3.0/manage/settings-and-profiles.mdx
src/prefect/cli/config.py
src/prefect/settings.py

this PR
- tweaks the docs to reflect recent setting changes (removes suggestion that `default` is special bc its not)
- shows new source in `prefect config view` i.e. `(from .env file)`
- fixes small bug to create intermediate file structure if no existing `profiles.toml`

settings docs updates and a minor fix

---

src/prefect/task_engine.py
src/prefect/task_runners.py

closes https://github.com/PrefectHQ/prefect/issues/15627

make task creation and submission logs `DEBUG`

---

docs/3.0/develop/global-concurrency-limits.mdx
docs/3.0/develop/task-run-limits.mdx
docs/3.0/develop/task-runners.mdx

- Adds note and links for other ways to limit concurrency.
- Adds a note on what the  `max_workers` param does in task runner example.
- Minor formatting updates for style consistency.
cc: @kevingrismore - following up on your note from PACC re: `max_workers`

Clarify a few items in the docs

---

src/prefect/flows.py

follow on to https://github.com/PrefectHQ/prefect/issues/15610.
the upstream [issue](https://github.com/pydantic/pydantic/issues/10575) I opened in pydantic is actually due to an existing cpython behavior described [here](https://github.com/python/cpython/issues/116938)
see [recommendation](https://github.com/pydantic/pydantic/issues/10575#issuecomment-2401545677) from pydantic

use safer, recommended workaround for #15611

---

src/prefect/client/orchestration.py

Backport typing overload of `get_client` so mypy can properly resolve the return type.
This was fixed in 3.x but not backported. Relevant issue: https://github.com/PrefectHQ/prefect/issues/14104

Add type overload for get_client

---

src/prefect/server/api/server.py

closes https://github.com/PrefectHQ/prefect/issues/15597
open to suggestions on these exact log messages
```python
In [1]: from prefect import flow
In [2]: @flow
...: def f(): pass
In [3]: f()
16:16:42.932 | INFO    | prefect - Starting ephemeral server on http://127.0.0.1:8095 - see https://docs.prefect.io/3.0/manage/self-host#self-host-a-prefect-server for more information on running a dedicated Prefect server.
16:16:45.015 | INFO    | prefect.engine - Created flow run 'khaki-wildcat' for flow 'f'
16:16:45.066 | INFO    | Flow run 'khaki-wildcat' - Finished in state Completed()
In [4]: exit
16:16:48.660 | INFO    | prefect - Stopping ephemeral server on http://127.0.0.1:8095
```

link to docs on starting ephemeral server

---

docs/contribute/develop-a-new-worker-type.mdx

remove note from 3.x docs about using `pydantic<2`

---

docs/3.0/manage/settings-and-profiles.mdx

The profile is named "ephemeral" in the code example, but we call it "default" directly above the example.

Update reference to name of profile in example

---

src/prefect/cli/work_pool.py
tests/_internal/concurrency/test_waiters.py
tests/cli/test_work_pool.py

```python
» prefect work-pool delete asdf
Are you sure you want to delete work pool with name 'asdf'? [y/N]: y
Deleted work pool 'asdf'
» prefect work-pool delete asdf
Are you sure you want to delete work pool with name 'asdf'? [y/N]: y
None
```
```python
» pool delete asdf
Are you sure you want to delete work pool with name 'asdf'? [y/N]: y
Deleted work pool 'asdf'
» pool delete asdf
Work pool 'asdf' does not exist.
```
---
also skips [this](https://github.com/PrefectHQ/prefect/issues/15654) chronic flake

dont ask to confirm non-existent deployment

---

src/integrations/prefect-kubernetes/prefect_kubernetes/credentials.py
src/integrations/prefect-kubernetes/prefect_kubernetes/jobs.py
src/integrations/prefect-kubernetes/tests/test_jobs.py

introduced by https://github.com/PrefectHQ/prefect/pull/13910, we fail to await the async method, silently skipping to load the config from the local kube-config
also adds a default factory for `KubernetesCredentials` since in many cases you just want the default behavior from it anyways

correctly await `config.load_kube_config`

---

tests/test_settings.py

Adds a parameterized test configuring every supported setting to verify the value propagates correctly. This test should give a good signal if any of the settings break while working on regrouping settings.
If this looks like a good structure for these tests, I can add similar tests to verify profile loading for every setting.

Add tests to verify all settings via environment variables

---

client/setup.py
setup.cfg
src/prefect/_version.py
src/prefect/utilities/dockerutils.py
tests/test_versioneer.py
tests/utilities/test_dockerutils.py
versioneer.py

This PR updates the version rendering in our vendored version of `versioneer` to ignore uncommitted changes. These updates will prevent `versioneer` from including `.dirty` suffix in the `prefect-client` version due to file changes we make during CI for packaging. These changes shouldn't affect the core package or development because `_version,py` is left unchanged. I included a couple of tests covering the changes to prevent regression if/when we upgrade `versioneer`.

Update `versioneer.py` to ignore uncommited changes

---

docs/3.0/develop/logging.mdx

Documents a newer work around for [this Discourse article](https://discourse.prefect.io/t/how-to-stream-prefect-logs-to-a-file/1963).

Docs note about accessing flow run logs

---

.github/workflows/python-tests.yaml
src/prefect/runner/runner.py
src/prefect/task_worker.py

Fixes test failures I was seeing in https://github.com/PrefectHQ/prefect/pull/15682. This is likely caused by the `TaskWorker` creating a task group in `__init__` (which is a `sync` context) instead of `__aenter__` (which is an `async` context).

Ensure `TaskWorker` creates a `anyio.TaskGroup` in an `async` context

---

src/prefect/server/models/deployments.py
tests/server/models/test_deployments.py

Previously, creating, updating or deleting deployments would delete any flow run associated with that deployment in a `Scheduled` state, including runs that were `AwaitingRetry`.
Only scheduled flow runs that haven't had a chance to run should be deleted.

Do not delete flow runs awaiting retry on deployment changes

---

src/prefect/context.py
src/prefect/settings.py
tests/test_context.py
tests/test_settings.py

This PR makes sure the `PREFECT_HOME` directory exists. Previously, directory creation was handled in the `__enter__` method of `SettingsContext`. The logic has now been moved to `root_settings_context`
this got past the test suite because the test we used to check that home was created used `temporary_settings`, which will enter a `SettingsContext`. we circumvented `use_profile` in https://github.com/PrefectHQ/prefect/pull/15565, meaning that in more normal use we don't enter a context and ensure `PREFECT_HOME` in all necessary cases
```bash
docker build -t test .
docker run --rm test -- prefect server start --host 0.0.0.0
```
or just
```
» PREFECT_HOME=/tmp/foo prefect server start&
[1] 93881
π prefect 3.12.5 ። ~/github.com/prefecthq/prefect create-home-with-settings …
```

create `PREFECT_HOME` in `root_settings_context`

---

.github/workflows/python-tests.yaml
src/prefect/cli/config.py
src/prefect/settings.py
src/prefect/utilities/collections.py
tests/cli/test_config.py
tests/test_context.py
tests/test_settings.py
tests/utilities/test_collections.py

Reintroduces changes first introduced in https://github.com/PrefectHQ/prefect/pull/15580 with fixes to ensure nested models are included when calling `.to_environment_variables()`.
See comments below for where this PR differs from #15580.

Add `APISettings` setting group

---

.github/workflows/integration-tests.yaml
flows/flow_retries.py
flows/serve_a_flow.py
flows/task_results.py
scripts/run-integration-flows.py
src/prefect/flows.py
src/prefect/runner/runner.py

- fixes a bug with `Runner.start` that used the wrong task group
- makes sure that integration tests actually fail in CI if one of them exits with a bad code
- removes integration tests against 2.x servers, since we explicitly don't support that client / server mismatch
- first of a slew of PRs to add coverage to our integration tests suite

fix bug where `.serve` exits early and add integration test

---

docs/3.0/deploy/infrastructure-concepts/customize.mdx

this page of docs has a slightly jargon-y title, and overriding configuration for deployments is a very common question

more accessible wording for job variable overrides docs

---

flows/automation-assessments.py

https://github.com/PrefectHQ/prefect/pull/15691 started to raise error codes out of the client compatibility tests. We should just nicely skip here instead of raising `NotImplementedError`

fix automation-assement.py

---

tests/server/models/deprecated/test_work_queues.py

Fixes a test that started failing on 3.9:
```
FAILED tests/server/models/deprecated/test_work_queues.py::TestUpdateWorkQueue::test_update_work_queue - pydantic_core._pydantic_core.ValidationError: 1 validation error for WorkQueue
updated
Error extracting attribute: MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/20/xd2s) [type=get_attribute_error, input_value=WorkQueue(id=ad3757a9-9c58-4adc-b355-9ffef3e1b730), input_type=WorkQueue]
For further information visit https://errors.pydantic.dev/2.9/v/get_attribute_error
```
Something about the update and then read wasn't working, so I added `populate_existing=True` for this one test.

Fix failing work queue test

---

src/integrations/prefect-dbt/prefect_dbt/cli/commands.py
src/integrations/prefect-dbt/tests/cli/test_commands.py

This is a minor fix for prefect-dbt integration. For dbt commands that are multipart such as `dbt source freshness`, `trigger_dbt_cli_command` function did not separate the individual command parts into list of arguments, causing the following error:
`DbtUsageException("No such command 'source freshness'.")`

prefect-dbt - fix dbt cli argument list for multipart commands

---

.github/workflows/python-tests.yaml

We've been seeing the test suite hanging and timing out. I've traced these hanging tests to the task runner and runner tests. These tests don't hang when run by themselves, so this PR creates a separate entry in the testing matrix so task runner, runner, and worker tests. This appears to eliminate the test suite hanging that we've seen.

Split out runner and worker tests to avoid hanging test suite

---

.github/workflows/python-tests.yaml

Contributors submitting PRs from a fork see tests fail due to Docker authentication failures. This PR updates the `python-tests` workflow only to perform Docker auth from a branch.

Only authenticate with Docker when running on a branch

---

flows/task_results.py

`0.3` is not always enough time for this propagate through with eventual consistency.

give more time for state to integration flow to finish

---

.github/workflows/python-tests.yaml

PR https://github.com/PrefectHQ/prefect/pull/15708 attempts to bypass the Docker Login step in the Python tests workflow, which is currently failing on PRs originating from forks, e.g. this one https://github.com/PrefectHQ/prefect/pull/15687 . The conditional doesn't seem to work correctly as the test failures reoccur even after the fix is applied. I'm not extremely familiar with GitHub Actions, but it seems that the `github.repository` context variable holds the base repository name, rather than the head repository, meaning that the check always passes and docker login is always attempted.
This PR changes the comparison to be explicitly against the head repository as recorded on the pull request event - this should correctly hold the fork name, leading to a bypass of the login step for …

Fix origin repo check that bypasses Docker Login on PRs originating from forks.

---

flows/serve_a_flow.py

because we're using scheduling and a runner poll frequency, we're still hitting some timing issues in the integration test even though its working as expected - this PR makes the test a bit more lenient wrt timing

de-flake serve integration test

---

src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/pyproject.toml
src/integrations/prefect-kubernetes/tests/test_worker.py

This PR replicates this https://github.com/PrefectHQ/prefect/pull/15525 Only difference is that this is created for main branch and for Prefect V3.
- https://github.com/PrefectHQ/prefect/pull/15525

Avoid crashing flows when job watch exits but conatiner is still running

---

docs/integrations/prefect-kubernetes/index.mdx
src/integrations/prefect-kubernetes/prefect_kubernetes/jobs.py
src/integrations/prefect-kubernetes/tests/conftest.py
src/integrations/prefect-kubernetes/tests/test_flows.py

fixes an issue where the `controller-uid` was being selected off the job status instead of the freshly retrieved `Job` object. the fact that that we were looking in the wrong place meant that the pod logs were not returned from `run_namespaced_job`
as discussed with @mitchnielsen, the injected label should always be present at the job's `spec.template.metadata.labels`, so we now look there, and fail if we cannot find it

Capture pod logs for `run_namespaced_job`

---

src/prefect/settings.py
tests/test_settings.py

fixes a bug with the default value of `PREFECT_UI_API_URL`

add `/api` to `PREFECT_UI_API_URL` in default case

---

src/integrations/prefect-kubernetes/prefect_kubernetes/events.py
src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/tests/test_worker.py

Closes #15622
This is a workaround for an issue in `kubernetes_asyncio` in which a 5 minute request timeout is the default behavior. There is an [open PR](https://github.com/tomplus/kubernetes_asyncio/pull/337) to resolve there that seems like it'll be released in December at the earliest. In the meantime, we can override the 5 minute timeout by passing a `ClientTimeout` into `_request_timeout` on our watches.
This enables `timeout_seconds` to once again do its job of enforcing timeouts on watches.
After starting a flow run with a CPU request that was impossible to schedule on my cluster and a 20 minute timeout `pod_watch_timeout_seconds`:
```
23:44:49.737 | INFO    | prefect.flow_runs.worker - Completed submission of flow run 'd957920d-ef3d-4c26-a148-a287d037e0d8'
00:04:49.626 | ERROR …
```

Add `_request_timeout` to Kubernetes watches

---

src/prefect/runner/server.py
tests/runner/test_runner.py

Running a worker in k8s as a pod. We needed a /health entry point.
I notices the following feature:
flow_function.serve(name=snapshot_flow.name, webserver=True)
When tested It fails to create the uvicorn server. The log_level in uvicorn is case-sensitive (lower) and prefect works with upper.
Full comment and explanation in the code.
- [V] This pull request references any related issue by including "closes `<link to issue>`"
- [V] If this pull request adds new functionality, it includes unit tests that cover the changes
- [ V] If this pull request removes docs files, it includes redirect settings in `mint.json`.
- [ V] If this pull request adds …

fix(runner.server): Pass lowercase log level to uvicorn server

---

src/prefect/settings.py
src/prefect/task_runners.py
tests/test_settings.py
tests/test_task_runners.py

Added prefect setting `THREAD_POOL_TASK_RUNNER_MAX_WORKERS` to configure the `max_workers` parameter in `ThreadPoolTaskRunner`. The default value is `None`.

Thread pool task runner max worker configurable via environment variable

---

Dockerfile

Older versions of Python are packaged with `setuptools` versions that contain known vulnerabilities. `prefect` doesn't need `setuptools` to run after it is packaged, so this PR updates our `Dockerfile` to remove `setuptools` after `prefect` is packaged and installed.
I also updated the `pip` pin while I was in there.

Remove `setuptools` and update `pip` pin in Docker build

---

flows/deploy.py
src/prefect/futures.py
src/prefect/tasks.py

this PR fixes the type errors that arise during normal usage of `Task.map` by forgoing the using the `ParamSpec`, since it seems generally not possible to fully capture the user function signature and also see the correct downstream types
also conveys that `wait_for` must be an `Iterable[T | PrefectFuture[T]] | None`
the concession is that we say `*args: Any`, so we lose the user defined arguments
but I would argue that not being forced to `type ignore` or `cast` downstream everywhere is actually better than the IDE telling you the arguments of the function you already wrote
<details>
<summary>example</summary>
```python
from prefect import flow, task, unmapped
@task
def my_task(x: int) -> int:
return x * 2
@task
async def my_async_task(x: int) -> int:
return x * 3
@task
def …
```

fix map typing

---

docs/3.0/deploy/infrastructure-examples/kubernetes.mdx

it wasn't super clear that the guide assumed the reader sets the namespace to "prefect"

clear up namespace selection in k8s guide

---

src/prefect/__init__.py
tests/test_exceptions.py

raise AttributeError instead of ModuleNotFoundError in `__getattr__` in `prefect/__init__.py` (issue https://github.com/PrefectHQ/prefect/issues/15739) 

fix wrong exception in lazy import __getattr__

---

src/prefect/workers/base.py
tests/workers/test_base_worker.py

The deep merge for `env` from the deployment->work pool only worked if the env vars were written directly into the template. This copies down the defaults to include them in the deep merge as well.

Include env defaults from `variables.properties.env` in deep merge

---

src/integrations/prefect-dbt/prefect_dbt/cli/commands.py
src/integrations/prefect-dbt/tests/cli/test_commands.py

Closes #15647
This PR wraps each of the `run_dbt_` functions with `sync_compatible`. Not sure if that's a desirable fix, so open to suggestions.
Currently, the functions never execute (at least when called from a sync context):
```py
from dbt.cli.main import dbtRunner
@task
async def trigger_dbt_cli_command():
dbtRunner().invoke(["debug"])
@flow
def main():
trigger_dbt_cli_command()
main()
```
```
11:32:09.538 | INFO    | prefect.engine - Created flow run 'spectral-marmoset' for flow 'main'
11:32:09.539 | INFO    | prefect.engine - View at http://127.0.0.1:4200/runs/flow-run/ea66fd5c-f10d-415c-a181-0e347a83c217
11:32:09.589 | INFO    | Flow run 'spectral-marmoset' - Finished in state Completed()
```
Adding `@sync_compatible` to …

Wraps run_dbt_ function in sync_compatible

---

src/integrations/prefect-kubernetes/prefect_kubernetes/events.py
src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/tests/test_worker.py

Add _request_timeout to Kubernetes watches 2.x

---

src/prefect/task_engine.py
src/prefect/tasks.py
src/prefect/utilities/engine.py
tests/public/flows/test_flow_with_mapped_tasks.py

<details>
<summary>MRE i was using</summary>
```python
from random import uniform
from time import sleep
from typing import Any
from prefect.runtime import task_run
def generate_task_run_name(parameters: dict[str, Any]) -> str:
"""previously we got parameters here from prefect.runtime.task_run.parameters, but as discussed below the values are not guaranteed to be resolved"""
return f'{task_run.task_name} - input["val"]:  {parameters["input"]["val"]}'
@task(log_prints=True)
def pre_task() -> bool:
return True
@task(log_prints=True, task_run_name=generate_task_run_name)
def task_1(input: dict[str, Any]) -> dict[str, Any]:
input_val = input["val"]
input["val"] = input_val + 1
print(f'task_1 - input["val"]:  {input_val}, output:  {input}')
sleep(uniform(1, 5)) …
```

Fix custom task run name rendering

---

src/prefect/cli/deploy.py

another example of where we should use `soft_wrap` to avoid line breaks from making invalid links

Soft wrap deployment link

---

src/prefect/events/schemas/automations.py
src/prefect/events/schemas/deployment_triggers.py

on `main`, an example like this will complain about missing fields even though the schema has defaults the user doesn't need to pass
```python
from prefect.events import DeploymentEventTrigger
DeploymentEventTrigger(expect={"weeeeeee"})
```
it seems to be because pydantic needs `default=` in the `Field` definitions to recognize the default value as "not required" by the constructor of the instance
---
this might be a bug related to multiple-inheritance to report to pydantic but for now, this is a QoL improvement

fix phantom missing fields for triggers schemas

---

requirements-client.txt

with new settings sources, we need `pydantic-settings > 2.2.1`
<details>
```bash
find_err() {
local package=$1
local command=$2
local start_version=$3
local reverse=$4
versions=($(pip index versions "$package" | rg -o '\d+\.\d+\.\d+' | sort -V -u))
if [[ "$reverse" == "reverse" ]]; then
versions=($(echo "${versions[@]}" | tr ' ' '\n' | sort -rV -u))
fi
echo "📦 Testing $package versions starting from $start_version"
echo "🔍 Command: $command"
echo "-------------------------------------------"
local start=false
local last_working_version=""
for version in "${versions[@]}"; do
if [[ "$version" == "$start_version" || "$start" == true ]]; then
start=true
printf "Testing v%-10s" "$version"
if output=$(uv run --with "$package==$version" python -c "$command" 2>&1); then
echo " ✅" …
```

require `pydantic-settings>2.2.1`

---

setup.cfg
src/prefect/_internal/schemas/bases.py
src/prefect/client/cloud.py
src/prefect/client/orchestration.py
src/prefect/flows.py
src/prefect/logging/logging.yml
src/prefect/server/database/configurations.py
src/prefect/server/utilities/schemas/bases.py
src/prefect/settings/base.py
src/prefect/settings/legacy.py
src/prefect/settings/models/api.py
src/prefect/settings/models/internal.py
src/prefect/settings/models/root.py
src/prefect/settings/models/server/api.py
src/prefect/settings/models/server/database.py
src/prefect/settings/models/server/deployments.py
src/prefect/settings/models/server/root.py
src/prefect/settings/models/server/ui.py
src/prefect/settings/models/tasks.py
src/prefect/settings/models/testing.py
src/prefect/settings/models/worker.py
src/prefect/settings/sources.py
tests/client/test_cloud_client.py
tests/client/test_prefect_client.py
tests/server/utilities/test_schemas.py
tests/test_settings.py

Creates final settings models for workers, tasks, testing, internal, and UI settings.
This PR updates the serializer for `PrefectBaseSettings` to ensure that fields that have been set on child models after object creation are included when dumping the model with `exclude_unset=True`.

Create worker, tasks, testing, and UI settings models

---

src/prefect/client/orchestration.py
tests/server/orchestration/api/test_workers.py

This PR fixes a misnamed filter parameter for the `/workers/filter` client call.

Fix worker filter param

---

.github/workflows/markdown-tests.yaml
requirements-markdown-tests.txt

This updates `requirements-markdown-tests.txt` to use the newly released version of `pytest-markdown-docs` that supports MDX comments, which we need for our tests to be compatible with Mintlify. It also renables the markdown tests action.
Closes https://github.com/PrefectHQ/prefect/issues/15781

Use released version of `pytest-markdown-docs`

---

docs/3.0/develop/write-tasks.mdx

I noticed the link to task settings was broken because the section title was different than the link. This PR fixes it by updating the link.  

Fix documentation link to task settings

---

.github/workflows/nightly-release.yaml

The nightly release workflow has continued to released dev versions for `3.0.11` even though `3.0.11` has been released. It should be releasing `3.0.12` dev version now. The sorting for the latest version was considering dev versions newer than release versions, so this PR updates the `latest_tag` one-liner to modify the tags to sort correctly and then revert the change after sorting.

Fix sorting of tags to determine nightly release version

---

src/prefect/cli/shell.py
tests/cli/test_shell.py

closes https://github.com/PrefectHQ/prefect/issues/15816

pass through kwargs for `run_shell_process`

---

schemas/settings.schema.json
src/prefect/settings/models/experiments.py
src/prefect/settings/models/root.py

This adds in an Experiments model to the Settings class to store all experimental feature settings 

Add in a settings.experiments module

---

docs/3.0/develop/settings-and-profiles.mdx

This PR updates the 'Configure settings and profiles' doc to include `prefect.toml` support. I beefed up the intro a little bit to establish what settings enable and how to get started with them. I included a list of supported setting sources and the order they are used to resolve settings values. I also included information about where each setting source is best used.
Very open to feedback about the overall structure and recommendation in addition to the specific wording used.
Closes https://github.com/PrefectHQ/prefect/issues/10697

Update 'Configure settings and profiles' documentation to include `prefect.toml` support

---

docs/3.0/develop/settings-ref.mdx
schemas/settings.schema.json
src/prefect/client/orchestration.py
src/prefect/settings/models/experiments.py
src/prefect/settings/models/worker.py
src/prefect/workers/base.py
tests/test_settings.py
tests/workers/test_base_worker.py

Add in the optional ability for a worker to get it's ID from the server using the heartbeat mechanism. This should only be enabled if `PREFECT_EXPERIMENTAL_WORKER_LOGGING_API_ENABLED` is set. This PR doesn't do any logging atm, just set the ground work for future PRs. 

Adds in the ability for the client to get a remote_id from the server

---

src/prefect/server/database/configurations.py

The [original issue](https://github.com/MagicStack/asyncpg/issues/530) that led to turning off `jit` when using a Postgres DB has been closed. This PR removes the explicit turning off of the `jit` setting to resolve issues with environments that don't support this setting.
Closes https://github.com/PrefectHQ/prefect/issues/14602
Closes https://github.com/PrefectHQ/prefect/issues/10903

Remove `jit="off"` setting for Postgres DBs

---

src/prefect/cache_policies.py
src/prefect/task_engine.py
src/prefect/utilities/hashing.py
tests/test_task_engine.py

Closes #15861 
This PR encourages `CachePolicy.compute_key` to raise exceptions on failure that can be handled by the engine; specifically, if any inputs are not serializable, instead of silently ignoring that policy by returning `None` we log the error and explicitly state that caching will not be performed. This is most important when using compound cache key policies and now ensures universal behavior across various policy configurations.

Dont cache on any key computation errors and log for visibility

---

src/prefect/client/schemas/actions.py

This PR adds in `worker_id` to the LogCreate schema. Ended up being a lot smaller then i thought it would be.

Adds in the worker_id to the LogCreate schema

---

src/prefect/server/orchestration/core_policy.py

Closes https://github.com/PrefectHQ/prefect/issues/13794
Note:
- this issue is already resolve for 3.x
- an analogous fix for the Cloud backend will go out soon

Allow for empty list retry delays

---

src/prefect/logging/logging.yml

The default `logging.yml` was missing handlers for the `fastapi` and `uvicorn` loggers. This PR adds a `console` handler for each, so logs are printed to the console as expected. These loggers also have `propagate` set to `false` to prevent duplicate logging.
Closes https://github.com/PrefectHQ/prefect/issues/15775

Fix logging for FastAPI and Uvicorn

---

src/prefect/client/schemas/objects.py
tests/deployment/test_flow_runs.py

Closes https://github.com/PrefectHQ/prefect/issues/15694
This may be controversial, but this PR explicitly patches the ability to load states from a 2.x API that have "unpersisted" results associated with them. This arises primarily when mixing Prefect versions across clients, specifically when triggering 2.x deployments from 3.x flows (see issue).  
As users upgrade, I think this is a reasonable thing to support that doesn't lose any information (since the result is unpersisted), and I believe the logic for checking that we're in the situation is specific enough so as to avoid other failure modes (if you actually have a real result you care about, it will be persisted somewhere else using one of our classes/types).

Allow for unpersisted 2.x result payloads in states

---

docs/3.0/develop/settings-ref.mdx
schemas/settings.schema.json
src/integrations/prefect-dask/tests/conftest.py
src/integrations/prefect-ray/tests/conftest.py
src/integrations/prefect-sqlalchemy/tests/conftest.py
src/prefect/client/schemas/objects.py
src/prefect/settings/models/experiments.py
src/prefect/settings/models/root.py
src/prefect/states.py
tests/conftest.py
tests/results/test_result_fetch.py
tests/test_settings.py

This PR takes care of two settings on the root model that shouldn't be there long term:
- `experimental_warn` is moved to `experiments.warn`
- `async_fetch_state_result` is removed and the default behavior for fetching results is updated to match this setting being enabled. The corresponding `fetch` kwargs are also deprecated so we can eventually clean all that up.

Moves `experimental_warn` setting to `experiments` model and removes `async_fetch_state_result`

---

src/prefect/states.py

I honestly am not sure if this is a fix or not, but I have a suspicion this could be the issue with https://github.com/PrefectHQ/prefect/issues/15893

Dont reuse exc name in nested exception handling

---

.github/workflows/python-tests.yaml

The 3.12 tests were running slow, so this PR sets `COVERAGE_CORE` for Python 3.12 tests. I learned about this setting in https://github.com/nedbat/coveragepy/issues/1665. The 3.12 test run significantly faster now and have gone from the slowest to the fastest:

Set `COVERAGE_CORE=sysmon` to speed up test on 3.12

---

src/prefect/logging/handlers.py
src/prefect/logging/loggers.py
src/prefect/logging/logging.yml
src/prefect/server/schemas/actions.py
src/prefect/workers/base.py
tests/test_logging.py
tests/workers/test_base_worker.py

Adds the ability for a worker to send logs to the Prefect Cloud endpoint with the relevant attributes set for Cloud to ingest the worker logs into clickhouse. 

Add in WorkerAPILogger and related functionality

---

src/prefect/settings/models/logging.py
src/prefect/types/__init__.py
tests/test_settings.py

setting `extra_loggers` to a normal python list failed, since we tried to `split()` in an `AfterValidator`, this switches us to use the same handling as we do for client extra retry codes i.e. either `list,of,things` or `['list', 'of', 'things']` to support `.env` as well as native types (found this when using controlflow)

fix extra loggers parsing

---

src/prefect/cli/config.py
tests/cli/test_config.py

This PR fixes `prefect config view` for .env file settings with added tests.

Fix `prefect config view` not showing .env file settings

---

src/prefect/server/database/query_components.py
tests/server/orchestration/api/test_flow_run_graph_v2.py

closes https://github.com/PrefectHQ/prefect/issues/15933
When checking if task runs are nested task runs, if the parent function contains multiple arguments, we'll end up with multiple edges (because there are two parents). 
Normally when constructing edges this is the behavior we want. However when generating our list of encapsulating ids (parents that have a nested task run), this shows up as two of the same parent, which is unexpected for that field. This PR ensures we deduplicates the encapsulating_ids field.

fix flow run graph endpoint for nested task runs

---

src/prefect/logging/handlers.py
src/prefect/workers/base.py
tests/test_logging.py
tests/workers/test_base_worker.py

Expanding on our work to emit worker logs, this PR includes the worker ID when a worker emits logs on behalf of a flow run. We do this so that we can show these logs, which are very often about infrastructure, alongside other infra-related worker logs on the new worker page.

Include worker ID with worker-originated flow run logs

---

src/prefect/workers/base.py
tests/workers/test_base_worker.py

Small fix: when we send worker metadata and normalize the way our collections and `distributions()` report package names, expect the integration to use underscores and the distribution to use dashes.

Fix the direction of our integration string replacement

---

src/prefect/workers/base.py

We used the `workpool.id` rather then `workpool.name` in generating the link to the workpool which isn't the proper routing used in the url.

Fixes the worker url slug

---

src/integrations/prefect-slack/prefect_slack/credentials.py
src/integrations/prefect-slack/pyproject.toml
src/integrations/prefect-slack/tests/test_credentials.py

related to https://github.com/PrefectHQ/prefect/issues/15008
first of many PRs to define explicit sync / async interfaces where we previously had `@sync_compatible`
```python
In [1]: from prefect_slack import SlackWebhook
In [2]: s = SlackWebhook(url="https://hooks.slack.com/services/xxx/xxx/xxx")
In [3]: s.notify("oi")
In [4]: await s.notify_async("oi")
In [5]: await s.notify("oi")
```

adopt `async_dispatch` for slack collection

---

src/prefect/client/orchestration.py
tests/client/test_prefect_client.py
tests/workers/test_base_worker.py

The JSON key for worker metadata is actually just "metadata." 🤦 

Fix the key for worker metadata: it's is just "metadata"

---

docs/3.0/deploy/index.mdx
docs/3.0/get-started/quickstart.mdx

* On Quickstart-page, to explain the concept of deployment in Prefect, link to the general Deployment-page  instead of a specific page about Deployment in Docker.
* On the general Deployment-page, remove an unexpected link to a Docker deployment section. Linking to the Docker deployment section is done in a later section on the same page already, where it is more appropriate.

Fix documentation link to deployment concept

---

src/prefect/settings/base.py
tests/test_settings.py

This PR fixes conversion of Settings to environment variables for settings of type set/list. For example `PREFECT_LOGGING_EXTRA_LOGGERS` values can be supplied as string with values separated by delimiter. The conversion back to env. var. value is done by simple `str()`, which returns different value ("foo,bar" != "['foo','bar']"). 
Solution: 
Applied value to environment variable value conversion function in `PrefectBaseSettings.to_environment_variables` to convert list/set/tuple values.
Note:
`PREFECT_LOGGING_EXTRA_LOGGERS` is set to be of type list and if validated by `validate_set_T_from_delim_string` the original order is lost. Currently, there is no need for OrderedSet (i assume) other than in tests for easier value assertion. But there is also no need for …

Fix formatting of `list` and `set` settings values when marshaling to environment variables

---

src/prefect/settings/base.py
src/prefect/settings/sources.py
tests/test_settings.py

This PR subclasses `DotEnvSettingsSource` to ensure environment variables in `.env` files not prefixed with `PREFECT_` are not loaded when retrieving the configured settings. 
Closes https://github.com/PrefectHQ/prefect/issues/15943

Ensure `.env` files load only Prefect environment variables

---

src/integrations/prefect-aws/pyproject.toml
src/integrations/prefect-azure/pyproject.toml
src/integrations/prefect-bitbucket/pyproject.toml
src/integrations/prefect-dask/pyproject.toml
src/integrations/prefect-databricks/pyproject.toml
src/integrations/prefect-dbt/pyproject.toml
src/integrations/prefect-docker/pyproject.toml
src/integrations/prefect-email/pyproject.toml
src/integrations/prefect-gcp/pyproject.toml
src/integrations/prefect-github/pyproject.toml
src/integrations/prefect-gitlab/pyproject.toml
src/integrations/prefect-kubernetes/pyproject.toml
src/integrations/prefect-ray/pyproject.toml
src/integrations/prefect-redis/pyproject.toml
src/integrations/prefect-shell/pyproject.toml
src/integrations/prefect-shell/tests/test_commands.py
src/integrations/prefect-slack/pyproject.toml
src/integrations/prefect-snowflake/pyproject.toml
src/integrations/prefect-sqlalchemy/pyproject.toml

newer versions of `pytest` require us to set this, this avoids the warning that tells us this

update `asyncio_default_fixture_loop_scope` in all collections

---

src/prefect/states.py
tests/results/test_task_results.py

This PR adjusts the logic for failed state persistence to avoid using task's `result_storage_key`; if `result_storage_key` is used, it can cause future runs to incorrectly load the exception as cached data.
Closes https://github.com/PrefectHQ/prefect/issues/15658

Persist failed data at random locations

---

flows/worker.py
src/prefect/events/filters.py
src/prefect/workers/base.py
tests/workers/test_base_worker.py

closes https://github.com/PrefectHQ/prefect/issues/15999

make sure workers emit stop events

---

.github/workflows/test-windows-unc.yaml
scripts/test_unc_paths.py
src/prefect/utilities/filesystem.py

closes https://github.com/PrefectHQ/prefect/issues/15971
I'm happy to remove this new CI job I used to repro, but it wont run unless we change the filesystem utils anyways

handle UNC paths for windows

---

src/integrations/prefect-redis/prefect_redis/blocks.py
src/integrations/prefect-redis/prefect_redis/locking.py

It seems async wasn't being correctly used and pretty obvious errors were being thrown within async tasks
```python
redis_block = RedisDatabase.load("mein")
s3_block = S3Bucket.load("stuff")
task_cached = partial(
task,
cache_policy=(INPUTS).configure(
isolation_level=IsolationLevel.READ_COMMITTED,
lock_manager=RedisLockManager(
**{
k: v
for k, v in redis_block.as_connection_params().items()
if not k.startswith("_")
}
),
key_storage=redis_block,  # Keys are stored in Redis for fast access
),
log_prints=True,  # print() statements will be logged
persist_result=True,
result_storage=s3_block,  # S3 as data sink
cache_result_in_memory=False,  # Do not cache results in memory (they can also be huge)
result_serializer="json",
cache_expiration=timedelta(
minutes=1
),  # Default cache expiration, …
```

fix: `prefect_redis` use of `async`

---

src/prefect/workers/base.py
tests/workers/test_base_worker.py

Fixes a bug where workers aborting a flow run submission doesn't release the concurrency slot that was claimed. I've based this on what has been done in the runner as this issue doesn't seem to exist over there https://github.com/PrefectHQ/prefect/blob/8758666101ce96d4f7ce098563a41ea81db8d5ef/src/prefect/runner/runner.py#L963. I've had a quick look at putting together a test case for this but I might need a hand here. Cheers.
Closes https://github.com/PrefectHQ/prefect/issues/15952

fix worker not releasing limit slot on failed propose pending state

---

ui-v2/src/components/ui/json-input.tsx
ui-v2/src/components/variables/add-variable-dialog.tsx
ui-v2/tests/variables/mocks.tsx
ui-v2/tests/variables/variables.test.tsx

@aaazzam discovered that the tab order was messed up on the `AddVariableDialog` component. I tracked the issue down to the `CodeMirror` component, but I don't know why it messed it up. 
Fortunately, `@uiw/react-codemirror` has a `useCodeMirror` hook that gives us more control over component creation. I used `useCodeMirror` to create a `JsonInput` component that doesn't have the same tab order foibles.
`AddVarialbeDialog` is now an upstanding citizen:

[UI v2] Fix tab order in variable create dialog

---

ui-v2/src/components/ui/button/button.tsx
ui-v2/src/components/ui/data-table.tsx
ui-v2/src/components/ui/input.tsx
ui-v2/src/components/ui/tags-input.tsx
ui-v2/src/components/variables/data-table/cells.tsx
ui-v2/src/components/variables/data-table/data-table.tsx
ui-v2/src/components/variables/data-table/search.tsx
ui-v2/src/components/variables/page.tsx
ui-v2/src/hooks/use-debounce.ts
ui-v2/src/routes/variables.tsx
ui-v2/tests/variables/mocks.tsx
ui-v2/tests/variables/variables.test.tsx

This PR finishes up the variables table by adding filtering, page size selection, and sorting to the table. This PR also refactors the `TagsInput` component slightly to fit into the table filtering layout a little better.
Here are some of the changes in action:

[UI v2] Variables table - part 2

---

docs/3.0/manage/self-host.mdx

The [self-hosting page](https://docs.prefect.io/3.0/manage/self-host) opens with a series of advanced installation notes that may not be relevant to most users, but seem like part of the critical path because of their location on the page (e.g. you see a section called "Use a self-signed SSL certificate" before you get to step 1 of "Self-host a Prefect server").
This PR moves them to the end of the page, which is appropriate for their content and likelihood of applicability to all users.

Move installation notes to bottom of self-host doc

---

src/prefect/blocks/notifications.py
tests/blocks/test_notifications.py

`apprise`'s new default `MAP` action for OpsGenie is a no-op (no notification is sent). To create an OpsGenie alert we need to include the `new` action type. As is, this is backwards compatible with older `apprise` versions, but if we bumped the minimum requirement for `apprise` to `1.9.0` we could either import and use `OpsgenieAlertAction.NEW` or maybe even support `action` as a block field instead of just sending a string.

Add `new` action to `OpsGenieWebhook` for `apprise==1.9.0` compatibility

---

src/integrations/prefect-slack/prefect_slack/credentials.py
src/prefect/_internal/compatibility/async_dispatch.py
tests/_internal/compatibility/test_async_dispatch.py

because of binding issues with the property-based method of "forcing" sync or async, here we concede and switch to `_sync` even though this means [we can't get perfect typing](https://peps.python.org/pep-0612/#concatenating-keyword-parameters)

refactor `async_dispatch` to enable forcing behavior for instance methods

---

src/prefect/workers/base.py
tests/workers/test_base_worker.py

Changes merge order so overlapping keys select deployment env vars over work pool env vars.

Fix env var deep merge order on worker

---

src/prefect/cache_policies.py
src/prefect/exceptions.py
src/prefect/utilities/hashing.py
tests/test_tasks.py
tests/utilities/test_hashing.py

closes https://github.com/PrefectHQ/prefect/issues/16042
in cases where a user attempts to pass an unhashable object to a task and we fail to compute a cache key, we should at least raise a helpful error.
I could be convinced that we should somehow attempt to change the items we hash for the key automatically, but I didn't want to start with magic

helpful error on unhashable parameters

---

docs/mint.json
scripts/generate_settings_ref.py

- Redirects /3.0/ to /v3/. 
- Reduces redirect chains for /latest/.
- Updates setting reference generation script to use `v3` path.

Update docs redirects and settings reference path

---

src/integrations/prefect-aws/prefect_aws/batch.py
src/integrations/prefect-aws/pyproject.toml
src/integrations/prefect-aws/tests/test_batch.py
src/prefect/_internal/compatibility/async_dispatch.py

related to #15008
migrates `prefect_aws.batch` tasks to explicit sync / async via `async_dispatch`
also updates `async_dispatch` to allow dispatching async task objects
will continue with `prefect_aws` after this PR

migrate `prefect_aws.batch` off `sync_compatible`

---

src/prefect/server/utilities/messaging/memory.py
tests/server/services/test_task_run_recorder.py
tests/server/utilities/test_messaging.py

In https://github.com/PrefectHQ/prefect/issues/15607, users are seeing the task run recorder get stuck in an infinite loop when trying to insert a task run state update with the same task run ID and timestamp as another task run state update, but with a different ID. This PR doesn't solve the underlying problem (which appears to be a race condition in the client-side code), but it does add a dead-letter queue to the `Subscription` class to avoid messages being retried ad-infinitum. By default, messages will attempt to be processed 3 times before being removed from the subscription's queue.
Closes https://github.com/PrefectHQ/prefect/issues/15607

Adds a dead-letter queue to memory subscriptions to avoid infinite loops

---

docs/v3/develop/results.mdx

Fixes a few remaining 3.0 links left over from https://github.com/PrefectHQ/prefect/pull/15923. These are all in-page links, so I just removed the absolute part of the path.
- ~If no issue exists and your change is not a small fix, please [create an issue]~(https://github.com/PrefectHQ/prefect/issues/new/choose) first.

Remove last remaining links to /docs/3.0

---

docs/v3/api-ref/rest-api/server/schema.json
src/prefect/_internal/schemas/bases.py
src/prefect/server/utilities/schemas/bases.py
tests/events/server/test_events_api.py

related to https://github.com/pydantic/pydantic/issues/10912
---
pydantic 2.10 broke us because of
- `get_default` (as used in `PrefectBaseModel.reset_fields`) now conditionally requires a new kwarg
- something about comparing instances of `AnyHttpUrl` i haven't grokked yet (only broke a couple events tests)

fix pydantic 2.10 compat

---

src/prefect/deployments/runner.py
src/prefect/types/__init__.py

closes https://github.com/PrefectHQ/prefect/issues/16074

omit empty tags in `RunnerDeployment`

---

docs/v3/api-ref/rest-api/server/schema.json
src/prefect/client/schemas/filters.py
src/prefect/server/api/flow_runs.py
src/prefect/server/schemas/filters.py
tests/client/test_prefect_client.py

closes https://github.com/PrefectHQ/prefect/issues/16070
will merge after a corresponding change in prefect cloud

allow filtering by flow run tags via `any_`

---

requirements-client.txt
src/prefect/_internal/schemas/bases.py
src/prefect/server/utilities/schemas/bases.py

revert changes to `reset_fields` from https://github.com/PrefectHQ/prefect/pull/16076 given fix in https://github.com/pydantic/pydantic/pull/10909 and disallows `2.10.0` (open to leaving the workaround in and closing this PR for more permissive resolutions but if we can avoid an extra `model_dump()` why not)

revert `pydantic==2.10.0` workaround given upstream fix

---

src/prefect/flow_engine.py
tests/test_flow_engine.py

This PR creates a `BaseFlowRunEngine` similar to `BaseTaskRunEngine` to enable fully asynchronous flow runs. The PR also copies the existing `FlowRunEngine` to `AsyncFlowRunEngine`, which will eventually be the async implementation. Both classes are identical right now, and this PR gets the larger structure in place so the diffs in subsequent PRs will be easier to read.
Related to https://github.com/PrefectHQ/prefect/issues/15415

Create `BaseFlowRunEngine` and `AsyncFlowRunEngine` shell

---

ui-v2/src/components/ui/button/button.tsx
ui-v2/src/components/variables/data-table/cells.tsx
ui-v2/src/components/variables/data-table/data-table.tsx
ui-v2/src/components/variables/hooks.ts
ui-v2/src/components/variables/page.tsx
ui-v2/src/components/variables/variable-dialog.tsx
ui-v2/tests/mocks/handlers.ts
ui-v2/tests/variables/variables.test.tsx

This PR adds the ability to edit existing variables. It repurposes the existing variable dialog to handle edits. Here's what it looks like:
https://github.com/user-attachments/assets/e18aec2a-4393-4ad1-96df-81ae48ee2505
This PR also starts to experiment with colocating hooks for common operations. Since this is the last major piece of functionality for variables, I'll review and refactor some parts to simplify the organization and increase reusability. Colocating hooks and query keys will be a part of that refactor.
Related to #15512

[UI v2] Edit variables

---

docs/integrations/integrations.mdx

Our docs provider, Mintlify, automatically binds a click event to images to enable a modal zoom. The noZoom attribute prevents this click handler from being bound.
More info here - https://mintlify.com/docs/image-embeds\#disable-image-zoom

added noZoom tag to integration images

---

src/prefect/flows.py
tests/test_flows.py

closes #16105
the checks for `has_v1_model` and `has_v2_model` used by `Flow.validate_parameters` did not consider the possibility of using `GenericAlias`

2.x generic alias handling in `validate_parameters`

---

src/integrations/prefect-aws/prefect_aws/s3.py
src/integrations/prefect-aws/tests/test_s3.py

related to #15008 
adds explicit async methods to all public tasks and methods in `prefect_aws.s3` and removes use of `sync_compatable`
<details>
<summary>old notes</summary>
i intentionally did not do the `S3Bucket` methods here, since there's an open question I want to discuss with @desertaxle
on S3Bucket
```python
async def get_directory()
```
is not actually async at all, not even a sending sync stuff to a worker thread
the established pattern would say we do
```python
async def aget_directory(self):
@async_dispatch(aget_directory)
def get_directory(self):
```
that seems like it was duplicate a lot for not a very compelling reason
but because stopped supporting async in sync we might need to do this
</details>
also renamed tasks in backword compat fashion per [this …

migrate `prefect_aws.s3` async tasks to `async_dispatch`

---

src/prefect/server/api/server.py
src/prefect/server/services/telemetry.py

I noticed that all services, including the scheduler, etc. were running in a background process on a loop anytime an ephemeral server was started. This hogs resources and is not intended behavior - we were not using the `ephemeral` flag on `create_app` as we should have.
This PR uses an env var to signal to the application when it should run in ephemeral mode.

Stop running all services in ephemeral app

---

src/prefect/cli/cloud/__init__.py
tests/cli/cloud/test_cloud.py

This PR adds a check to avoid raising an error when listing workspaces without a current workspace. It also adds some test coverage to the `prefect cloud workspace ls` command that was missing.
Closes https://github.com/PrefectHQ/prefect/issues/16098

Fix error when listing workspaces without an active workspace

---

ui-v2/package-lock.json
ui-v2/package.json
ui-v2/src/app.tsx
ui-v2/tests/setup.ts

This PR adds the `@tanstack/query` devtools. This tool is only visible during `development` build environments and helps developers visualize query keys and its state. This tool is useful when debugging cached state and visualizing redundant query keys
https://github.com/user-attachments/assets/70362ac1-fb60-4603-a5fe-df04525cc847

[UI v2] feat: Adds tanstack query dev tools for development mode

---

ui-v2/src/hooks/variables.ts

This PR wraps `queryKey` and `queryFn` objects using the `queryOptions` API.
Opting to use the `queryOptions` wrapper due to its Typescript benefits (see attachment).
Additionally, all tanstack router + query uses `queryOptions` in their latest documentation examples
Overall, by using the `queryOptions` wrapper, our codebase knows what the expected return type is based on the `query keys` provided in the `queryClient`
And a good blog read: https://tkdodo.eu/blog/the-query-options-api
(Without the wrapper, TS assumes `any` type that is associated with the provided `queryKey`. With the wrapper, TS magically 🧙 knows what the expected type is for this cache)
https://github.com/user-attachments/assets/5fae4841-19c9-4765-b974-dc5b22c9ce6f
- …

[UI v2] feat: Use queryOptions API to define queries

---

ui-v2/src/components/variables/data-table/cells.tsx
ui-v2/src/components/variables/variable-dialog/variable-dialog.tsx
ui-v2/src/hooks/variables.ts
ui-v2/tests/mocks/handlers.ts

This PR handles all UX related mutation callbacks to be handled on the UX layer.
`useMutation` is divided into 2 separate  concerns: 1️⃣ Data, 2️⃣ UX.
Upon success on the data layer, **it is not guaranteed that the UX related callbacks will be invoked**.
This is why after calling a defined `useMutation`, there are callback options to pass, in which all UX related callbacks should be handled there.
Here is a good article of how `useMutation` is architected with seperation of concerns: 
https://tkdodo.eu/blog/mastering-mutations-in-react-query#some-callbacks-might-not-fire
Overall, `useMutation` _should_ be designed with 2 considerations:
1️⃣ When initially creating a `mutation`,  handle all data / cache related callbacks here
2️⃣ When …

[UI v2] feat: Have UX related mutation callbacks be handled in the UX layer

---

src/prefect/server/models/deployments.py

This PR ports the excellent contribution from @ashtuchkin in #16121 to `main` to improve the performance of the scheduler query for newly inserted rows.

Improve scheduled flows query

---

ui-v2/src/hooks/variables.ts

Simplifies invalidating all queries for `['variables']`.
Looking at the code, it looks like we want to invalidate **all** queries starting with `'variables'` as the key.
The simplest way of doing it is just passing `queryKey: variableKeys.all`, or `queryKey: ['variables']`. You don't need to iterate through all queries and evaluate each one for this case
React Query's query key matching is simple. It will match query keys on how specific the key sequence is being passed.
eg: 
Passing`['variables']`, will invalidate all query keys starting with `'variables'`.
Passing `['variables',  'filtered-count]`, will only invalidate all queries that matches up to this sequence, such as `['variables', 'filter-count', 'foo']` `['variables', …

[UI v2] feat: simplfies invalidating all variable queries

---

docs/v3/develop/big-data.mdx
docs/v3/develop/task-caching.mdx
docs/v3/develop/write-tasks.mdx

this has come up a lot, adds two examples of how to handle unserializable task inputs that you still want to compute a cache key for

Add caching doc section on unserializable inputs

---

ui-v2/src/components/variables/data-table/cells.tsx
ui-v2/src/hooks/variables.ts

As noted by @devinvillarosa  in https://github.com/PrefectHQ/prefect/pull/16140, the delete variable mutation should be located in the variables hooks module to take advantage of the centralized query key factory and increase reusability. This PR does that.
Related to #15512

[UI v2] Move delete variable mutation to variable hooks module

---

ui-v2/src/components/flows/data-table.tsx
ui-v2/src/hooks/use-set.test.ts
ui-v2/src/hooks/use-set.ts

1. Adds a custom hook `useSet`. This custom hook is a declarative way of keeping state for "selected" types. Most likely in the app we will need to keep state of selected IDs for a list. This hook can be used for convenience and uniqueness for the selected items in a declarative way.
2. Adds an example test on how to test hooks only using `renderHook`. I haven't seen an example of this in the codebase yet
3. Attempts to replace the imperative way of keeping track of selected tags from `useState` to `useSet` as en example.
⚠️ I haven't been able to run this locally, and cannot validate if this replacement works. I can revert this change if needed …

[UI v2] feat: Introducing declarative useSet custom hook and replacing selected tags state for this hook

---

ui-v2/eslint.config.js
ui-v2/package-lock.json
ui-v2/package.json
ui-v2/src/hooks/variables.ts

1. Adds tanstack query eslint rule which ensures variables being passed into `queryFn` are also `queryKey` dependencies. Details here: https://tanstack.com/query/v5/docs/eslint/eslint-plugin-query
2. Updates docs for useMutation from previous PR https://github.com/PrefectHQ/prefect/pull/16141
Followup from https://github.com/PrefectHQ/prefect/pull/16155

[UI v2] dev: Adds tanstack query eslint rules and updates docs for variable mutations

---

flows/client_context_lifespan.py
flows/worker.py
requirements-dev.txt
scripts/run-integration-flows.py
src/prefect/workers/base.py
tests/blocks/test_notifications.py
tests/cli/cloud/test_cloud.py
tests/cli/test_profile.py
tests/cli/test_worker.py
tests/client/test_cloud_client.py
tests/client/test_prefect_client.py
tests/conftest.py
tests/deployment/test_flow_runs.py
tests/fixtures/collections_registry.py
tests/server/orchestration/api/test_collections.py
tests/server/services/test_telemetry.py

This PR updates `respx.mock` calls to include `using="httpx"` to mock at the `httpx` level instead of the `httpcore` level. This mitigates `respx` not being compatible with `httpx==0.28.0`.

Workaround `respx` incompatibility with `httpx==0.28.0`

---

.github/workflows/markdown-tests.yaml
flows/client_context_lifespan.py
requirements-dev.txt
scripts/run-integration-flows.py
src/prefect/client/orchestration.py
src/prefect/client/schemas/actions.py
src/prefect/workers/base.py
tests/blocks/test_notifications.py
tests/cli/cloud/test_cloud.py
tests/cli/test_profile.py
tests/cli/test_worker.py
tests/client/test_cloud_client.py
tests/client/test_prefect_client.py
tests/conftest.py
tests/deployment/test_flow_runs.py
tests/fixtures/collections_registry.py
tests/server/orchestration/api/test_collections.py
tests/server/services/test_telemetry.py

closes https://github.com/PrefectHQ/prefect/issues/16148
- uses the fork of `respx` with the [fix](https://github.com/lundberg/respx/pull/278) until the main version is released
- also updates the markdown tests setup to actually use the working version of `prefect` instead overwriting it
---
relatedly, https://github.com/PrefectHQ/prefect/pull/16168 fixes httpx issues with tests and an issue with the worker's cloud client context when adding flow run labels

fix ssl verify and update tests

---

src/integrations/prefect-aws/prefect_aws/secrets_manager.py
src/integrations/prefect-aws/tests/test_secrets_manager.py

related to https://github.com/PrefectHQ/prefect/issues/15008
this finishes off `prefect_aws`

migrate `prefect_aws.secrets_manager` off `sync_compatible`

---

src/prefect/task_engine.py
tests/test_task_engine.py

closes #16100 , related to #15607 and for some users in #15153.
This PR tries to fix an issue on Windows machines where setting task state from Pending to Running by TaskEngine causes the Running state to be ignored due to the same timestamp. This issue also created infinite loop on Prefect Server resulted from "duplicate key constrain violation" prior to v3.1.4. For the latest version it only causes the task to remain in Pending state until new state is set.
More information is in #16100, but the main issue i see in Windows having resolution of ~15ms for timestamps.
Solution:
Adding check to TaskEngine.set_status for the duplicit timestamp and adding 1us if is equal. I do not like that solution but it should not affect Linux clients, and for Windows clients there is probably no easy way …

Fix setting task states with duplicate timestamps

---

src/prefect/runtime/flow_run.py
tests/runtime/test_flow_run.py

```python
In [1]: from prefect import flow
In [2]: import prefect.runtime
In [3]: @flow(log_prints=True)
...: def f(): print(prefect.runtime.flow_run.job_variables)
In [4]: f()
17:55:23.174 | INFO    | prefect.engine - Created flow run 'true-panda' for flow 'f'
17:55:23.423 | INFO    | Flow run 'true-panda' - {}
17:55:23.548 | INFO    | Flow run 'true-panda' - Finished in state Completed()
```

expose `job_variables` in `runtime.flow_run`

---

src/prefect/docker/__init__.py
tests/docker/test_public_api.py

closes https://github.com/PrefectHQ/prefect/issues/16171
---
Fix `unittest.assertWarns()` compatibility with module `__getattr__` handling in `prefect.docker.__init__`
issue arises bc unittest's `assertWarns` uses `getattr()` with a default value to safely check for `__warningregistry__` on modules
https://github.com/python/cpython/blob/e546876d83e1cc3f761e1eeca57f8a4533d06d00/Lib/unittest/case.py#L290-L294
Our `__getattr__` implementation was raising `ImportError`, preventing Python from handling the default value case, so this PR changes it to raise `AttributeError` to follow attribute lookup protocol (like the other dynamic imports we have)

fix `__getattr__` conflict in `prefect.docker.__init__`

---

ui-v2/src/hooks/variables.test.tsx
ui-v2/src/hooks/variables.ts

⚠️ This PR is an exercise and has some lessons learned when going doing this. Additionally, this PR may be used as a good reference if we need an example on how to write tests for our react query modules
This PR goes over the exercise of what it may look like adding tests that focuses on our react query modules.
This test covers the integration between how data is fetched, stored, mutated, and fetched again when using `@tanstack/query` for server data management. 
The main test is to ensure our query keys are being properly invalidated and re-fetching data from the server. This should help build confidence when building query modules for different data sources without being dependent on building and testing with UI
A good blog on how to write tests for react query: …

[UI v2] exercise: Adds test for variables hook that focuses on react query and query caching and invalidation

---

ui-v2/src/components/ui/docs-link.stories.tsx
ui-v2/src/components/ui/docs-link.tsx
ui-v2/src/components/variables/empty-state.tsx

1. Create a re-usable `DocsLink` component that can be re-used throughout the app.
2. Replace Docs link in variables page in favor for new `DocsLink` component
https://github.com/user-attachments/assets/59553b4c-37c9-48de-a224-8802bd270c59

[UI v2] feat: Adding DocsLink reusable component

---

docs/v3/api-ref/rest-api/server/schema.json
src/prefect/blocks/core.py
src/prefect/context.py
tests/blocks/test_core.py
tests/test_context.py

Context serialization is dropping storage block attributes due to the typing of `result_storage` on the `ResultStore` class. Adding `serialize_as_any` will ensure all necessary result storage information is sent to remote execution infrastructure like Dask and Ray.
Closes https://github.com/PrefectHQ/prefect/issues/15783
Closes #16009

Fix result store serialization to include all necessary attributes

---

ui-v2/.gitignore
ui-v2/src/components/ui/empty-state.stories.tsx
ui-v2/src/components/ui/empty-state.tsx
ui-v2/src/components/variables/empty-state.tsx

Looking at the upcoming concurrency page, there can be some generic components that can be re-used. One of them being `EmptyState`. This PR:
1. Adds a generic `EmptyState` composite component. This components manages the styling and pieces needed to create an Empty State
2. Replaces variables EmptyState to use this generic `EmptyState`

[UI v2] feat: Adding generic empty-state component, and replaced variables empty-state for it

---

ui-v2/src/components/ui/state-badge/index.tsx
ui-v2/src/components/ui/state-badge/state-badge.stories.tsx
ui-v2/src/components/ui/state-badge/state-badge.test.tsx

This PR includes three small improvements: 
1. Use `cva()` on state-based styles for `StateBadge` to get Tailwind [IntelliSense](https://cva.style/docs/getting-started/installation#intellisense). 
2. Make the Storybook story a "Catalog" of all states. 
3. Simplify the Storybook hierarchy via [single-story hoisting](https://storybook.js.org/docs/writing-stories/naming-components-and-hierarchy#single-story-hoisting). 
Please let me know if only some of the above are interested, and I will revert the other changes. 

[UI v2] Use cva() on StateBadge

---

ui-v2/src/components/concurrency/task-run-concurrency-limit-empty-state.test.tsx
ui-v2/src/components/concurrency/task-run-concurrency-limit-empty-state.tsx
ui-v2/src/components/ui/docs-link.tsx

1. Adds EmptyState for Task Run Concurrency Limits
2. Adds simple tests for component callback
3. Adds docs entry

[UI v2] feat: Adds EmptyState for Task Run Concurrency Limits

---

.github/workflows/static-analysis.yaml

This PR adds a type completeness check to the Static Analysis workflow. The check uses `pyright` to calculate a type completeness score and ensures that a PR will not decrease the type completeness score by comparing the generated score to the score generated on the base branch. 
Contributors will be able to see the output in the summary of the Static Analysis workflow:
Inspired by discussion in https://github.com/PrefectHQ/prefect/discussions/16167

Add type completeness check to CI

---

src/integrations/prefect-azure/pyproject.toml
src/integrations/prefect-docker/pyproject.toml
src/integrations/prefect-gcp/pyproject.toml
src/integrations/prefect-kubernetes/pyproject.toml

for collections that offer a worker
related to https://github.com/PrefectHQ/prefect/issues/16188
but its still not totally clear how the error in that issue arose. it seems like there might have been some python pathing issue where (somehow) the `3.0.11` version was used instead of the `3.1.1` version (that has the `Integration` schema) that was installed on top, but seems to not be a bug on our side

bump required minor versions of core

---

src/prefect/blocks/abstract.py
src/prefect/blocks/core.py
src/prefect/concurrency/asyncio.py
src/prefect/concurrency/sync.py
tests/concurrency/test_acquire_concurrency_slots.py
tests/concurrency/test_concurrency_asyncio.py
tests/concurrency/test_concurrency_sync.py
tests/concurrency/test_release_concurrency_slots.py
tests/concurrency/v1/test_increment_concurrency_limits.py

and migrates private concurrency context managers' helpers off `sync_compatible` 
cc @aaazzam

update typing in `blocks.abstract` and `concurrency`

---

ui-v2/src/hooks/global-concurrency-limits.test.tsx
ui-v2/src/hooks/global-concurrency-limits.ts

Building the query data store for `global concurrency limits` entity
This PR just focuses on the Query Key architecture for `global concurrency limits`. A follow up PR will address the mutations
1. Defines QueryKey architecture that will manage `global concurrency limits` data entity
2. Exports `useQuery` wrappers to be used in the UI

[UI v2] feat: Adds global concurrency limit query definitions

---

src/prefect/client/base.py
src/prefect/client/cloud.py
src/prefect/client/collections.py
src/prefect/client/subscriptions.py
src/prefect/client/utilities.py
src/prefect/utilities/asyncutils.py
src/prefect/utilities/math.py

strict type client modules

---

src/prefect/server/database/_migrations/MIGRATION-NOTES.md
src/prefect/server/database/_migrations/env.py
src/prefect/server/database/_migrations/versions/postgresql/2024_12_04_165333_5d03c01be85e_sync_orm_models_and_migrations.py
src/prefect/server/database/_migrations/versions/sqlite/2024_12_04_144924_a49711513ad4_sync_orm_models_and_migrations.py
src/prefect/server/database/orm_models.py

As I was looking into low-hanging fruit to improve prefect's type completeness, I ran into several issues with the ORM model definitions. Over time the migrations and the models have diverged somewhat, for various reasons, and this commit brings them back together again.
With this commit, you can run `prefect server database revision --autogenerate` in a clean checkout and alembic will generate empty migration steps. At the same time, the ORM models accurately reflect what is in the database.
- Update the alembic `include_object` hook to support per-dialect filtering for indexes, and to avoid enum-to-varchar conversions for existing columns in SQLite.
- Add indexes added by manual migrations into their respective ORM models, with dialect-specific information where needed.
- Keep index …

Bring ORM models and Alembic migrations in sync

---

setup.cfg
src/prefect/server/database/orm_models.py

Consistently use `Mapped[...]` and `mapped_column()` to define all column and relationship types. The responsibility for flagging a column as nullable is up to the type annotation, using `Optional`.
The module now passes pyright typechecks in strict mode.
Note that the database schema hasn't changed; running `prefect server database revision --autogenerate` results in an empty migration step.

Use SQLAlchemy 2.0 style for ORM models, make typing complete

---

ui-v2/src/hooks/global-concurrency-limits.test.tsx
ui-v2/src/hooks/global-concurrency-limits.ts
ui-v2/tests/mocks/handlers.ts

Building the  mutations `global concurrency limits`queries
This PR just focuses on the mutations for `global concurrency limits` queries.
1. Defines Mutations for `global concurrency limits`
2. Updates `msw` handlers for generic `global concurrency limits`  API mocks
Follow up to https://github.com/PrefectHQ/prefect/pull/16220

[UI v2] feat: Adding mutations for global concurrency limit

---

ui-v2/src/components/ui/typography.stories.tsx
ui-v2/src/components/ui/typography.tsx

When rebuilding UI pages, the typography can get confusing with the abundance of options provided with Tailwind.
This PR:
1. Introduces a simple Typography component to help simplify text when re-writing the platform. We can add stricter styling to each variant as we move forward, but this should help bring some consistency. Additionally this should help provide semantic HTML
2. Adds story to Typography component story

[UI v2] feat: Simplifies typography by introducing a simple typography component

---

ui-v2/src/components/concurrency/concurrency-constants.ts
ui-v2/src/components/concurrency/concurrency-page.tsx
ui-v2/src/components/concurrency/concurrency-tabs.tsx
ui-v2/src/components/concurrency/global-concurrency-view/global-concurrency-limit-empty-state.test.tsx
ui-v2/src/components/concurrency/global-concurrency-view/global-concurrency-limit-empty-state.tsx
ui-v2/src/components/concurrency/global-concurrency-view/global-concurrency-limits-header.tsx
ui-v2/src/components/concurrency/global-concurrency-view/index.tsx
ui-v2/src/components/concurrency/task-run-concurrenct-view/index.tsx
ui-v2/src/components/concurrency/task-run-concurrenct-view/task-run-concurrency-limit-empty-state.test.tsx
ui-v2/src/components/concurrency/task-run-concurrenct-view/task-run-concurrency-limit-empty-state.tsx
ui-v2/src/components/layouts/MainLayout.tsx
ui-v2/src/components/variables/layout.tsx
ui-v2/src/routes/concurrency-limits.tsx

Adds basic page layout for concurrency page
1. Create page layout component and place in some re-usable component fillers
Todos when doing this exercise:
1. Create a re-usable component for the tab navigation
2. Integrate routing url options to handle tab state 
https://github.com/user-attachments/assets/019ee798-a327-4792-895b-1876a3fd8b63

[UI v2] feat: Starts page layout for concurrency page

---

docs/v3/develop/blocks.mdx

The docs were unclear to me on why the built-in blocks didn't show up in the UI. See this [slack thread](https://prefect-community.slack.com/archives/C04DZJC94DC/p1733490977608259).

Include info about registering built-in blocks

---

.github/workflows/static-analysis.yaml
.pre-commit-config.yaml
ui-v2/.husky/pre-commit
ui-v2/biome.json
ui-v2/package-lock.json
ui-v2/package.json
ui-v2/src/api/prefect.ts

I previously set up the `ui-v2` directory to run pre-commit hooks for formatting and linting via `husky`, but it turns out you can only have `pre-commit` or `husky` hooks installed locally at a given time. This PR moves all the UI v2 hooks to `pre-commit` and adds a new hook to ensure the generated client code for the UI is kept in sync with the API.

Move UI pre-commit hooks from `husky` to `pre-commit`

---

ui-v2/src/components/concurrency/concurrency-constants.ts
ui-v2/src/components/concurrency/concurrency-page.tsx
ui-v2/src/components/concurrency/concurrency-tabs.tsx
ui-v2/src/components/concurrency/global-concurrency-view/index.tsx
ui-v2/src/hooks/global-concurrency-limits.ts
ui-v2/src/routes/concurrency-limits.tsx

This PR focuses on passing data from react query cache and url state into the route component, which will be consumed by the page component
1. Add a `useSuspenseQuery` wrapper.
2. Adds search validator and loader to route and UX component
https://github.com/user-attachments/assets/94a003f2-e758-47e5-9989-af9402ee15f9

[UI v2] feat: Loads data and url state to concurrency limit route for UX to consume

---

src/prefect/workers/base.py
tests/workers/test_base_worker.py

This adds work pool id/name to the labels the worker gives a flow-run when it submits.

Add work-pool id/name to labels donated by worker to flow run

---

src/prefect/telemetry/bootstrap.py

This gives failures that result from enabling telemetry friendly error messages, rather than just exploding.

Raise informative errors when failing to bootstrap telemetry

---

ui-v2/package-lock.json
ui-v2/package.json
ui-v2/src/components/concurrency/concurrency-tabs.tsx
ui-v2/src/components/concurrency/global-concurrency-view/create-or-edit-limit-dialog/index.tsx
ui-v2/src/components/concurrency/global-concurrency-view/create-or-edit-limit-dialog/use-create-or-edit-limit-form.ts
ui-v2/src/components/concurrency/global-concurrency-view/index.tsx
ui-v2/src/components/ui/switch.tsx

1. Adds Switch component using `cli`
2. Adds Creating or Editing a global concurrent limit using hook logic. (Only manually tested creation)
3. Adds UI for creating a new global concurrent limit
Will add tests when testing for the entire page functionality. Similar to `variables.test.tsx`. I think our hook tests in `hooks/global-concurrent-limits.test.tsx` is suffice for now for confidence

[UI v2] Adds Create or edit dialog for concurrency limit

---

ui-v2/src/components/concurrency/global-concurrency-view/data-table/data-table.tsx
ui-v2/src/components/concurrency/global-concurrency-view/data-table/index.ts
ui-v2/src/components/concurrency/global-concurrency-view/index.tsx
ui-v2/src/routes/concurrency-limits.tsx

1. Adds a `hidePagination` option to `DataTable` for tables that do not support pagination features
2. Adds basic table for global concurrency limit. Will do active toggle in a separate PR, and action list on another one

[UI v2] feat: Adding basic table for global concurrency limit

---

src/prefect/_internal/schemas/validators.py
src/prefect/client/__init__.py
src/prefect/client/base.py
src/prefect/client/cloud.py
src/prefect/client/orchestration.py
src/prefect/client/schemas/__init__.py
src/prefect/client/schemas/actions.py
src/prefect/client/schemas/objects.py
src/prefect/client/schemas/responses.py
src/prefect/client/schemas/schedules.py
src/prefect/client/subscriptions.py
src/prefect/client/utilities.py
src/prefect/main.py

Code now passes pyright checking in strict mode.

[typing] prefect.client

---

src/prefect/client/utilities.py

`TypeIs` should only be used if the negative result excludes the narrowed type.
Also see https://github.com/PrefectHQ/prefect/pull/16265#discussion_r1874713679

[typing] Use correct type narrowing construct

---

docs/v3/tutorials/debug.mdx

https://github.com/PrefectHQ/prefect/pull/16225 breaks the markdown tests everywhere because we run them with 3.9 and `T | None` is introduced in 3.10

3.9 compat for `debug.mdx` tutorial

---

ui-v2/src/hooks/deployments/deployments.test.tsx
ui-v2/src/hooks/deployments/index.ts

This PR adds a `usePaginateDeployments` hook and a `useCountDeployments` hook. Both will be use to provide data to the deployments table view.

[UI v2] Add hooks for paginating and counting deployments

---

ui-v2/src/components/deployments/empty-state/empty-state.stories.tsx
ui-v2/src/components/deployments/empty-state/index.tsx
ui-v2/src/components/deployments/header.tsx
ui-v2/src/components/ui/docs-link.tsx
ui-v2/src/components/ui/icons/constants.ts
ui-v2/src/routes/deployments.tsx

This PR adds an empty state for the deployments page, matching the existing empty state as closely as possible while using `react-lucide` icons.
Here's what it looks like:

[UI v2] Create empty state for deployments page

---

docs/v3/tutorials/debug.mdx
docs/v3/tutorials/platform.mdx

A few CLI commands in the tutorials use incorrect syntax.

Fix bad workspace commands in the tutorials

---

.github/workflows/static-analysis.yaml
scripts/pyright_diff.py
src/prefect/logging/loggers.py

This PR improves the type completeness check by providing information about new type hinting errors.
This should help contributors see where type hinting needs to be improved to keep type completeness trending in the right direction.

Include more helpful output in type completeness check

---

flows/client_context_lifespan.py
scripts/run-integration-flows.py
src/prefect/client/orchestration.py
tests/blocks/test_notifications.py
tests/cli/test_cloud.py
tests/cli/test_profile.py
tests/cli/test_worker.py
tests/client/test_cloud_client.py
tests/client/test_prefect_client.py
tests/conftest.py
tests/fixtures/collections_registry.py
tests/infrastructure/test_kubernetes_job.py
tests/server/api/test_collections.py
tests/server/services/test_telemetry.py
tests/test_deployments.py
tests/workers/test_utilities.py

backports #16149 for 2.x lineage
updates a bunch of cli tests w.r.t `respx`

backport #16149

---

src/prefect/_internal/compatibility/async_dispatch.py
src/prefect/blocks/core.py
src/prefect/cli/_prompts.py
src/prefect/cli/deploy.py
src/prefect/client/orchestration.py
src/prefect/client/utilities.py
src/prefect/deployments/steps/pull.py
src/prefect/results.py
src/prefect/testing/utilities.py
tests/_internal/compatibility/test_async_dispatch.py
tests/blocks/test_core.py

This PR improves type hinting on `Block.load` by removing the `@sync_compatible` decorator and using `@async_dispatch` instead.
I had to update `@async_dispatch` to handle class methods and update the dispatch behavior in tasks and flows to match the behavior provided by `@sync_compatible`.
Also, `@inject_client` might be a thorn in our side because it makes wrapped functions async. To handle that in this PR, I removed `@inject_client` from `Block.load` and moved the client retrieval inside the method. There's a weird split where sometimes we can use the sync client, and other times we have to use the async client, but we can clean that up once we remove `@async_dispatch`.
Related to https://github.com/PrefectHQ/prefect/issues/16292

Add `Block.aload` method and remove `@sync_compatible` from `Block.load`

---

.github/dependabot.yml
.github/release.yml

Updates release notes for tidiness that I've been manually doing; for PRs that only touch docs files, let's not add `development` so that they get categorized as Documentation updates.
Also specifically excludes dependabot updates to UI dependencies as these don't affect user environments at all.

Update release notes for tidiness

---

.github/labeler.yml
.github/release.yml

Small update to make release notes compilation easier.

Exclude UI v2 PRs from the release notes auto-generation

---

src/prefect/_internal/retries.py
src/prefect/deployments/steps/core.py
src/prefect/deployments/steps/pull.py
tests/_internal/test_retries.py
tests/deployment/test_steps.py

related to #15008 and https://github.com/PrefectHQ/prefect/issues/16292

remove `sync_compatible` from `git_clone`

---

src/prefect/client/orchestration.py
src/prefect/variables.py
tests/test_variables.py

remove `sync_compatible` in `prefect.variables` and replace it with `async_dispatch`

remove `sync_compatible` from `prefect.variables`

---

docs/mint.json

I noticed an error when building the docs locally:
```
% mintlify dev
⠹ Preparing local Mintlify instance...
...
⠧ Preparing local Mintlify instance...⚠️   "v3/automate/incidents" is defined in the mint.json navigation but the file does not exist.
```
This seems to be because the incidents page was removed from the docs but left in the nav.

Remove missing page from the nav

---

.github/workflows/static-analysis.yaml

Looks like PRs from forks are failing when switching back to the current branch (example: https://github.com/PrefectHQ/prefect/actions/runs/12291713039/job/34300966606?pr=16328). Now that the script to diff `pyright` failures is on `main`, this step shouldn't be necessary any longer.

Fix type analysis check for PRs from forks

---

.dockerignore
.github/workflows/time-docker-build.yaml
Dockerfile

there's still work to be done here, since i'm not sure what caused the dramatically inflated runtime of the `Docker images` job, but now at least we can relatively quantify all changes to the `Dockerfile`
inspired by https://github.com/PrefectHQ/prefect/pull/16327 (see https://github.com/PrefectHQ/prefect/actions/runs/12284945352?pr=16348)

improve `Dockerfile` build time and add CI to catch future slow downs

---

.github/workflows/time-docker-build.yaml
docs/v3/tutorials/pipelines.mdx

makes a couple updates to the `Build a data pipeline` tutorial
- existing use of `.submit()`/ `.result()` is bit more verbose and I would rather recommend using sequential `.map` calls in cases where the io actually takes a while, bc in this example the second loop blocks at each `result()` call `for` each item, instead of resolving futures concurrently like `.map(list[T]).result()`. i also think its easier to read / reason about
<details>
<summary>for example</summary>
```python
import time
from typing import Any
@task
def slow_api_call(item: str) -> dict[str, Any]:
"""Simulate a slow API call that takes 1 second"""
time.sleep(1)  # Simulate network delay
return {"item": item, "data": f"data for {item}"}
@task
def slow_processing(data: dict[str, Any]) -> …
```

update tutorial for clarity

---

src/prefect/flow_engine.py
src/prefect/task_engine.py
src/prefect/telemetry/instrumentation.py
src/prefect/telemetry/processors.py
src/prefect/telemetry/run_telemetry.py
tests/telemetry/test_instrumentation.py

This updates the RunTelemetry class to pull the traceparent from the runs labels. A traceparent can be added to these labels by server-side code. For instance if a run is Late when we transition to Late the server will start a span and store the traceparent in the flow run's labels. This way when the flow run is later picked up by a worker this "Late" span becomes the root span for the trace.
Related to CLOUD-732

Pick up trace context from run labels

---

.github/workflows/python-tests.yaml
flows/docker_deploy.py
scripts/entrypoint.sh

once images are out with the next release, runtime installs via `EXTRA_PIP_PACKAGES` should be faster for free via `uv`
and adds an integration test to make sure it plays nicely python paths during standard usage
```
» docker run -p 4200:4200 -e EXTRA_PIP_PACKAGES=pandas --rm uv-test -- prefect server start --host 0.0.0.0
+uv pip install pandas
Using Python 3.9.21 environment at: /usr/local
Resolved 6 packages in 229ms
Prepared 2 packages in 1.48s
Installed 2 packages in 22ms
+ numpy==2.0.2
+ pandas==2.2.3
___ ___ ___ ___ ___ ___ _____
| _ \ _ \ __| __| __/ __|_   _|
|  _/   / _|| _|| _| (__  | |
|_| |_|_\___|_| |___\___| |_|
Configure Prefect to communicate with the server with:
prefect config set PREFECT_API_URL=http://0.0.0.0:4200/api
View the API reference documentation at …
```

update `entrypoint.sh` to use `uv` for `EXTRA_PIP_PACKAGES`

---

src/prefect/tasks.py
tests/test_tasks.py

the original issue was about 2.x, so we should backport #16369
related to https://github.com/PrefectHQ/prefect/issues/16357

backport retry delay type fix

---

src/prefect/server/api/run_history.py
src/prefect/server/api/ui/task_runs.py
src/prefect/server/database/configurations.py
src/prefect/server/database/interface.py
src/prefect/server/database/orm_models.py
src/prefect/server/database/query_components.py
src/prefect/server/events/counting.py
src/prefect/server/events/filters.py
src/prefect/server/models/concurrency_limits_v2.py
src/prefect/server/models/deployments.py
src/prefect/server/schemas/filters.py
src/prefect/server/utilities/database.py
tests/server/utilities/test_database.py

This is a complete refactor of this module.
- Move functions into the `sqlalchemy.func` namespace so they don't need to be imported everywhere
- Re-use SQLAlchemy's Postgresql JSONB operators by providing SQLite equivalents
- Provide a new function that calculates the difference between timestamps as seconds.
This removes the need for many separate PostgreSQL vs SQLite queries.
Related to #16292

[typing] prefect.server.utilities.database

---

src/prefect/client/subscriptions.py

While I was moving things around my original [PR](https://github.com/PrefectHQ/prefect/pull/16326), I accidentally kept one instance of `websockets.connect` which we need to replace with our new `websocket_connect` utility so that `Subscriptions` can respect proxy settings.

Use `websocket_connect` utility in `Subscriptions`

---

src/prefect/server/database/dependencies.py
src/prefect/server/events/ordering.py
src/prefect/server/services/foreman.py
src/prefect/server/utilities/schemas/__init__.py
src/prefect/server/utilities/schemas/bases.py
tests/server/database/test_dependencies.py
tests/server/services/test_foreman.py
tests/server/utilities/test_schemas.py

The decorator now returns a custom descriptor object instead of a wrapper function. The descriptor can then keep the `self` and database interface objects separate without having to reverse the normal argument order.

Refactor db_injector decorator

---

docs/v3/develop/settings-ref.mdx
schemas/settings.schema.json
src/prefect/runner/runner.py
src/prefect/settings/models/runner.py
tests/runner/test_runner.py
tests/test_settings.py

This PR enhances the `Runner` by sending heartbeat events for flow runs it is managing with an eye toward creating automations that can update flow run state in the absence of heartbeats.

Enhance `Runner` to send heartbeat events for flow runs

---

docs/v3/develop/settings-ref.mdx
schemas/settings.schema.json
src/prefect/client/orchestration.py
src/prefect/server/api/server.py
src/prefect/settings/__init__.py
src/prefect/settings/models/api.py
src/prefect/settings/models/server/api.py
tests/client/test_prefect_client.py
tests/test_settings.py

Adds basic auth to both the server and the client; still needs tests and QA.
Start a protected server:
```
PREFECT_SERVER_API_AUTH_STRING="admin:admin" prefect server start
```
Run a flow:
```
PREFECT_API_AUTH_STRING="admin:admin" python -c "from prefect import flow; flow(lambda: None)()"
```
Closes https://github.com/PrefectHQ/prefect/issues/15711

Add working implementation of basic auth to server and client

---

src/integrations/prefect-redis/prefect_redis/client.py
src/integrations/prefect-redis/tests/test_client.py
src/prefect/settings/base.py

in support of https://github.com/PrefectHQ/prefect/pull/16415 and https://github.com/PrefectHQ/prefect/pull/16416

add async redis client utils to `prefect-redis`

---

docs/v3/automate/events/automations-triggers.mdx

This PR adds an example of how to add an automation to mark zombie flow runs as crashed. I had trouble finding a good place to put this, so I'm open to putting this somewhere else.

Add an example for creating an automation to mark zombie flow runs as crashed

---

src/prefect/_internal/concurrency/services.py
src/prefect/telemetry/instrumentation.py
src/prefect/telemetry/services.py
tests/telemetry/test_instrumentation.py

Due to the way the OpenTelemetry OTLP Span and Log exporters work they can block execution of flows/tasks if the otel collectors they're sending data to are down. This moves their handling into QueueServices so that we unblock the main thread and flows/tasks can run normally.
Closes CLOUD-872

Wrap OTLPLogExporter and OTLPSpanExporter in a QueueService to pull them out of the main thread

---

docs/v3/api-ref/rest-api/server/schema.json
src/prefect/client/schemas/objects.py
src/prefect/flow_engine.py
src/prefect/server/schemas/states.py
src/prefect/states.py
src/prefect/task_engine.py
src/prefect/utilities/engine.py
tests/telemetry/test_run_telemetry.py
ui-v2/src/api/prefect.ts

As part of our ongoing initiative to emit high quality OpenTelemetry
traces from Prefect, this adds a span link for each parameter back to
the flow or task that produced it.  Like all of our input tracing, this
is able to connect upstream runs to downstream runs if the parameter is
passed as a `PrefectFuture`.  The links mention the parameter's name and
the type of the result that will be used as the final parameter when
invoking the flow/task function.
Closes CLOUD-697
Closes CLOUD-739

Adds a link to the span that each parameter came from

---

src/prefect/client/cloud.py
src/prefect/workers/base.py
tests/workers/test_base_worker.py

This updates the worker to use the orchestration client for updating labels and removes the method from the CloudClient.
Closes CLOUD-859

Update worker to use orchestration client for updating labels

---

src/prefect/client/schemas/objects.py
src/prefect/server/database/sql/postgres/get-runs-from-worker-queues.sql.jinja
src/prefect/server/database/sql/sqlite/get-runs-from-worker-queues.sql.jinja
src/prefect/server/orchestration/core_policy.py
src/prefect/server/schemas/core.py
tests/blocks/test_notifications.py
tests/server/database/test_queries.py
tests/server/orchestration/test_core_policy.py
tests/workers/test_base_worker.py

Ports fix in https://github.com/PrefectHQ/prefect/pull/15482 to the `2.x` line.
Closes https://github.com/PrefectHQ/prefect/issues/12509

Prevent workers from running flow runs scheduled for in process retry

---

docs/v3/get-started/index.mdx

Closes https://linear.app/prefect/issue/DOC-106/update-the-overview-page-to-include-references-to-the-new-tutorials
Now that we've deployed the first set of data engineer and platform engineer tutorials, let's add them to the overview page to encourage people to dive into the use cases that matter the most to them.

Add tutorials to the overview page of the docs

---

.github/workflows/python-tests.yaml
src/prefect/client/orchestration.py
tests/client/test_prefect_client.py

Closes #16307 in Prefect 2.x. Original PR: #16308

Backport: deleting flows in python client prefect 2.0

---

src/prefect/runner/runner.py
src/prefect/workers/base.py

This should help improve the experience when infrastructure submission fails with an opaque "could not be submitted: exit code 1"

Log exceptions when run submission fails in both the runner and worker

---

src/prefect/client/utilities.py

The decorator can't accept a regular callable (it uses `await` when calling the wrapped function), and has so far never been used on anything but coroutines.
References #16292 and #16341.

[typing] Remove overload from inject_client

---

src/prefect/exceptions.py
src/prefect/flows.py

- removed `FlowScriptError.rich_user_traceback()`; it has not been in use since January 2022 (see 1b0e69b19084843598158ac09946eaa0d0d622c9).
References #16292

[typing] prefect.exceptions

---

.github/workflows/python-tests.yaml
requirements-dev.txt
setup.cfg
src/prefect/flows.py
tests/test_flows.py
tests/typesafety/test_flows.yml

This makes the `flow.from_source()` callable available to the type checker.
A new tests/typesafety suite provides coverage for the type annotations here.
Related: #16292

Refactor prefect.flow decorator

---

docs/v3/api-ref/rest-api/server/schema.json
src/prefect/client/schemas/objects.py
src/prefect/server/schemas/states.py
src/prefect/states.py
src/prefect/utilities/engine.py
ui-v2/src/api/prefect.ts

In a prior change, we added the `trace_id` and `span_id` as separate
fields to the `StateDetails`.  However, because `trace_id` is a 128-bit
integer, we could get inconsistencies and errors serializing that to and
from JSON.  For example, browsers usually only support 53-bit integers
in JSON, which means these trace IDs become floating point values.  In
`orjson`, it strictly validates that integers are at most 64-bit and
raises an error if not.
Because of these compatibility issues, we're going to change this to
the more standard abstraction of the string-based `traceparent`, which
encodes the trace and span IDs along with additional flags.

Transitions to using `traceparent` instead of separate IDs

---

src/prefect/filesystems.py
src/prefect/results.py
tests/results/test_state_result.py

closes https://github.com/PrefectHQ/prefect/issues/16428
another issue related to #15008 
this is a bit of compatibility code required due to the fact that `async_dispatch` is aware of run contexts, and that all blocks are not yet migrated off sync_compatible (and users may subclass these methods without adding the compat decorators) - this can be simplified/removed once all block implementations behave the same way (though we'd still have to handle the possibility of user subclasses)

use correct async method on storage blocks

---

flows/load_flows_concurrently.py
src/prefect/deployments/runner.py
src/prefect/flows.py
src/prefect/utilities/importtools.py
tests/utilities/test_importtools.py

closes #16452 
as observed in the linked issue
> Sometimes it completes, but other times it errors with `KeyError: __prefect_loader__` as shown below.
we had a race condition where we'd use the  same hardcoded `__prefect_loader__` in `load_script_from_module`, causing issues when you use `from_source` concurrently

make `from_source` safe to use concurrently

---

src/prefect/__init__.py

- Provide more typing details for version info and the local module spec.
- A module `__getattr__` is never called for globals, so the `_slots` structure was redundant.
- Minimise what code is run in the `try: ... except:` block.
- For Python 3.10 and up, include more context in the AttributeError.
References #16292

[typing] clean up prefect __init__.py

---

src/prefect/futures.py

related to #16292
updates typing of wait and `DoneAndNotDoneFutures`

[typing] update `prefect.futures`

---

requirements-dev.txt
src/prefect/artifacts.py
src/prefect/automations.py
src/prefect/context.py
src/prefect/locking/filesystem.py
src/prefect/locking/memory.py
src/prefect/locking/protocol.py
src/prefect/plugins.py
src/prefect/telemetry/processors.py
src/prefect/telemetry/services.py
src/prefect/workers/__init__.py
tests/test_plugins.py
tests/typesafety/test_automations.yml
tests/typesafety/test_flows.yml

A few more modules to pass strict typing checks.
References #16292

[typing] misc prefect modules

---

docs/v3/deploy/index.mdx

fix broken link
[old link](https://docs-3.prefect.io/v3/develop/write-flows#serve-a-flow) (points to non-existent header)
[new link](https://docs-3.prefect.io/v3/deploy/run-flows-in-local-processes#serve-a-flow)

fix link to `serve` docs

---

.github/dependabot.yml

Adds dependabot groupings for `/ui-v2`. [Using grouping method](https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/). Using groupings due to most grouped dependencies _should_ be upgraded together. This should signal us when we can upgrade to React 19 with our dependencies

[UI v2] feat: Adds dependabot groupings for ui-v2

---

.github/workflows/python-tests.yaml

This PR ensures that the `exclude` entry for the client tests with SQLite matches the matrix entry. Previously, client tests were running with SQLite when we only need them to run against PostgreSQL (which is faster).

Ensure client tests don't run with SQLite

---

client/client_flow.py
src/prefect/_internal/concurrency/services.py
src/prefect/concurrency/_asyncio.py
src/prefect/concurrency/_events.py
src/prefect/concurrency/asyncio.py
src/prefect/concurrency/context.py
src/prefect/concurrency/services.py
src/prefect/concurrency/sync.py
src/prefect/concurrency/v1/_asyncio.py
src/prefect/concurrency/v1/_events.py
src/prefect/concurrency/v1/asyncio.py
src/prefect/concurrency/v1/context.py
src/prefect/concurrency/v1/services.py
src/prefect/concurrency/v1/sync.py
src/prefect/context.py
src/prefect/task_engine.py
tests/concurrency/test_acquire_concurrency_slots.py
tests/concurrency/test_concurrency_asyncio.py
tests/concurrency/test_concurrency_slot_acquisition_service.py
tests/concurrency/test_release_concurrency_slots.py
tests/concurrency/v1/test_concurrency_asyncio.py
tests/concurrency/v1/test_concurrency_limit_acquisition_service.py
tests/concurrency/v1/test_concurrency_sync.py
tests/concurrency/v1/test_decrement_concurrency_slots.py
tests/concurrency/v1/test_increment_concurrency_limits.py
tests/test_task_engine.py

[typing] prefect.concurrency

---

src/integrations/prefect-snowflake/prefect_snowflake/database.py
src/integrations/prefect-snowflake/tests/test_database.py

closes #16110 
The `fetch_all` method was failing with `TypeError: 'NoneType' object is not an iterator` because it was trying to fetch results before executing the query. This fix ensures the query is executed on the cursor before attempting to fetch results.

Fix `TypeError` in `SnowflakeConnector.fetch_all`

---

ui-v2/src/components/deployments/data-table/cells.tsx
ui-v2/src/components/deployments/data-table/data-table.stories.tsx
ui-v2/src/components/deployments/data-table/data-table.test.tsx
ui-v2/src/components/deployments/data-table/index.tsx
ui-v2/src/components/ui/status-badge/index.tsx
ui-v2/src/components/ui/status-badge/status-badge.stories.tsx
ui-v2/src/components/ui/status-badge/status-badge.test.tsx
ui-v2/src/hooks/deployments/index.ts

This PR introduces the `DeploymentsDataTable` component. Not all columns are implemented as part of this PR (https://github.com/PrefectHQ/prefect/pull/16284 needs to be merged to add the activity column), and the table hasn't been wired up to a hook yet, but the interface for the component should be pretty set.
I added a `StatusBadge` component also to support the 'Status' column in the table.
Here's what it looks like so far:

`DeploymentsDataTable` - Part 1

---

src/prefect/flow_engine.py
tests/test_flows.py

closes https://github.com/PrefectHQ/prefect/issues/16513
to log the correct name, we have to defer this info log until after we resolve the custom name
I changed `Created` to `Beginning` since we now "create" the flow run much earlier than we log this message, and I wanted to keep the log accurate - open to alternate wordings
---
```python
In [1]: from prefect import flow
In [2]: @flow(flow_run_name='foo')
...: def f(): pass
In [3]:
In [3]: f()
13:10:12.057 | INFO    | prefect.engine - Created flow run 'poised-griffin' for flow 'f'
13:10:12.556 | INFO    | Flow run 'foo' - Finished in state Completed()
```
note `Created flow run 'poised-griffin' for flow 'f'`
```python
In [1]: from prefect import flow
In [2]: @flow(flow_run_name='foo')
...: def f(): pass
In [3]: f()
13:09:35.053 | INFO …
```

log rendered custom `flow_run_name`

---

ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limit-header/nav-header.tsx
ui-v2/src/components/ui/breadcrumb.tsx
ui-v2/src/components/ui/run-card/run-card.tsx

1. Updates `BreadcrumbLink` to be usable with `tanstack router`.
2. Update Breadcrumb components to use `BreadcrumbLink` instead of a nested `Link` component
https://tanstack.com/router/latest/docs/framework/react/guide/custom-link

[UI v2] feat: Have Breadcrumb link be connected with tanstack router

---

ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-data-table/actions-cell.tsx
ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-data-table/active-cell.tsx
ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-actions-menu/task-run-concurrency-limits-actions-menu.tsx
ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-data-table/tag-cell.tsx
ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-delete-dialog/task-run-concurrency-limits-delete-dialog.tsx

After the schema for concurrency limits got fixed such that `id` is expected, cleans out the falsey checks for type checking

[UI v2] chore: Clean out id field type check after schema got fixed

---

src/prefect/task_engine.py
src/prefect/tasks.py

adds an overload to make the type checker handle `wait_for` when calling tasks directly, pyright complains on main
also makes various `Dict` -> `dict` changes and adds a private alias to make the overloads as shown by IDE easier to grok
```python
@task
def double(x: int) -> int:
return x * 2
@task
def cast_to_float(x: int) -> float:
return float(x)
@flow
def flow_with_task() -> float:
result = double(1)
other_result = cast_to_float(2, wait_for=[result])
state = cast_to_float(3, wait_for=[other_result], return_state=True)
last_value = cast_to_float(4, wait_for=[state.result()], return_state=False)
return last_value
```

fix overloads for `wait_for` and `return_state` in  `Task.__call__`

---

src/prefect/events/clients.py
tests/utilities/test_proxy.py

In https://github.com/PrefectHQ/prefect/pull/16326 the team added support for HTTP_PROXY & HTTPS_PROXY for the websocket connection used by the agent to submit events (such as task runs).
However in some environments these proxies are necessary to route connection for the flow itself running (i.e. to connect to external in an air gapped environment).
Having the events routed through the proxy might mean they cannot reach the server.
This PR adds basic support for the NO_PROXY variable for the websocket connection, allowing to ignore the proxy for the server connection.
- ~~[ ] If this pull request removes docs files, it includes redirect settings …

feat: Add support for NO_PROXY for websocket connections

---

src/integrations/prefect-snowflake/prefect_snowflake/database.py
src/integrations/prefect-snowflake/tests/test_database.py

Fixes #15712
The `fetch_one` and `fetch_many` methods were being used incorrectly internally, causing both:
- trying to call `.strip()` on a cursor
- `TypeError: 'NoneType' object is not an iterator`
Here we follow the pattern established in #16511 by ensuring synchronous fetch methods use synchronous execution.
Changes:
- Update `fetch_one` and `fetch_many` to use `cursor.execute()` directly instead of async execution
- Fix parameter name from `parameters` to `params` to match Snowflake's API
The fix ensures the cursor's result iterator is properly initialized before fetch operations.
```python
from prefect_snowflake import SnowflakeConnector
@task
def fetch_data(block_name: str) -> list[tuple[str]]:
all_rows: list[tuple[str]] = []
with …
```

fix `fetch_one` and `fetch_many` in `prefect-snowflake`

---

src/prefect/deployments/runner.py
tests/runner/test_runner.py

closes #16551
though I wouldn't recommend deployment names like `..foo`, we do not explicitly disallow those characters, so we should handle this cleanly

avoid `Path` interpreting `.` in deployment names as the beginning of a file extension

---

src/prefect/client/orchestration/__init__.py
src/prefect/client/orchestration/_variables/client.py

Related to #16472, this PR continues the optimization pattern established for Artifacts, though with a smaller impact since Variables is one of our lighter primitives. The memory footprint reduction is negligible in this case, but the PR:
* Refactors the client's Variable CRUD methods into a standalone module
* Uses ForwardRefs for heavy imports, moving them into the call itself
While the memory impact is minimal for Variables specifically, applying this pattern consistently across all primitives will help us reach our optimization targets in #16472. The refactoring maintains full feature parity while improving the module's organization and type safety.
fun fact: our previous async client didn't have a create method, while our sync one didn't have a read_variables method

Refactor Variable CRUD methods in client

---

src/prefect/client/orchestration/__init__.py
src/prefect/client/orchestration/_logs/client.py

Related to #16472, this PR continues the optimization pattern established for Artifacts. Like the previous PRs, it:
* Refactors the client's Log CR methods into a standalone module
* Uses ForwardRefs for heavy imports, moving them into the call itself

Refactor Log CRUD methods in client

---

src/prefect/client/orchestration/__init__.py
src/prefect/client/orchestration/_concurrency_limits/client.py

Related to https://github.com/PrefectHQ/prefect/issues/16472, this PR continues the optimization pattern established for Artifacts. Like the previous PRs, it:
- Refactors the client's ConcurrencyLimit CRUD methods into a standalone module
- Uses ForwardRefs for heavy imports, moving them into the call itself

Refactor ConcurrencyLimit CRUD methods in client 

---

ui-v2/src/components/automations/automations-header/automations-header.tsx
ui-v2/src/components/concurrency/concurrency-limits-page.tsx
ui-v2/src/components/concurrency/concurrency-limits-tabs.tsx
ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-header/global-concurrency-limits-header.test.tsx
ui-v2/src/components/concurrency/global-concurrency-limits/global-concurrency-limits-header/global-concurrency-limits-header.tsx
ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-header/task-run-concurrency-limits-header.tsx
ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limits-header/task-run-conrrency-limits-header.test.tsx

1. Updates Concurrency Title to use `Breadcrumb` component (to be consistent with `Variables` and `Deployments` page).
2. Updates nav button to **not** span across the entire page.
https://github.com/user-attachments/assets/7e57aab7-788c-4dfc-bc17-6fbe56f8bc73

[UI v2] fix: Create consistent concurrency limit nav title

---

src/prefect/tasks.py

closes https://github.com/PrefectHQ/prefect/issues/16502
an example like this will complain on `main` about the return value of the task being `None` if `cache_policy=NONE`. the same being true for any kwarg of the task decorator
this PR fixes the typing - its possible the third overload is now not necessary, but we can remove this later as needed
```python
import asyncio
from prefect.cache_policies import NONE
@task(cache_policy=NONE)
def a_task() -> int:
return 1
@flow
def a_flow() -> int:
return a_task()
@task(cache_policy=NONE)
async def an_async_task() -> int:
return 1
@flow
async def an_async_flow() -> int:
return await an_async_task()
a_flow()
asyncio.run(an_async_flow())
```

fix task overload for decorator kwargs

---

src/prefect/client/orchestration/__init__.py
src/prefect/client/orchestration/_deployments/client.py
tests/client/test_prefect_client.py

Related to https://github.com/PrefectHQ/prefect/issues/16472, this PR continues the optimization pattern established for Deployments. Like the previous PRs, it:
- Refactors the client's Deployments CRUD methods into a standalone module
- Uses ForwardRefs for heavy imports, moving them into the call itself

Refactor Deployment CRUD methods in client

---

ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limit-page/index.tsx
ui-v2/src/hooks/task-run-concurrency-limits.test.tsx
ui-v2/src/hooks/task-run-concurrency-limits.ts

Renames deferred promise variable from `activeTaskRuns` to `activeTaskRunsPromise`.
Makes it clearer when using this object

[UI v2] feat: Give deferred promise a better variable name

---

src/prefect/client/orchestration/_deployments/client.py
src/prefect/client/orchestration/_logs/client.py
src/prefect/client/schemas/__init__.py
src/prefect/states.py

In refactoring the Prefect client, two "heavy" refs slipped by:
- prefect.states.Scheduled which imports all its friends and inflates memory
- prefect.client.schemas.sorting enums. Enums suck here, because you have to import them in order to set defaults, but since our imports are a little wonky to begin with, you end up importing _every model_ just to set a default. So the one place this is used (which is inconsistent with other methods anyway) in `logs`, the sort is now optional and the default logic is moved inside the body of the function.

cleanup a few refs

---

ui-v2/src/hooks/automations.test.ts
ui-v2/src/hooks/automations.ts
ui-v2/tests/utils/handlers.ts

Adds mutations for automations

[UI v2] feat: Adds automations mutations

---

ui-v2/src/api/automations/automations.test.ts
ui-v2/src/api/automations/automations.ts
ui-v2/src/components/automations/automation-enable-toggle/automation-enable-toggle.stories.tsx
ui-v2/src/components/automations/automation-enable-toggle/automation-enable-toggle.test.tsx
ui-v2/src/components/automations/automation-enable-toggle/automation-enable-toggle.tsx
ui-v2/src/components/automations/automation-enable-toggle/index.ts

Adds automation enable toggle component
https://github.com/PrefectHQ/prefect/issues/15512

[UI v2] feat: Adds AutomationEnableToggle component

---

src/prefect/filesystems.py
src/prefect/flow_engine.py
src/prefect/workers/process.py
tests/test_flows.py

closes https://github.com/PrefectHQ/prefect/issues/16427
(https://github.com/PrefectHQ/prefect/issues/16436 is not closed by this, as this is a separate issue)

consolidate hook calling in flow engine

---

ui-v2/src/api/flow-runs/flow-runs.test.ts
ui-v2/src/api/flow-runs/index.ts
ui-v2/src/api/flows/index.ts
ui-v2/src/components/deployments/data-table/cells.tsx
ui-v2/src/components/deployments/data-table/data-table.stories.tsx
ui-v2/src/components/deployments/data-table/data-table.test.tsx
ui-v2/src/components/deployments/data-table/index.tsx
ui-v2/src/components/ui/flow-run-acitivity-bar-graph/context.tsx
ui-v2/src/components/ui/flow-run-acitivity-bar-graph/flow-run-activity-bar-graph.stories.tsx
ui-v2/src/components/ui/flow-run-acitivity-bar-graph/index.tsx
ui-v2/src/components/ui/flow-run-acitivity-bar-graph/utils.test.ts
ui-v2/src/components/ui/flow-run-acitivity-bar-graph/utils.ts
ui-v2/src/mocks/create-fake-flow-run.ts
ui-v2/tests/utils/handlers.ts

This PR integrated the flow run activity bar graph into the deployments table.
Here's what it looks like in action:
https://github.com/user-attachments/assets/6a0ecd1c-a7bf-4d29-8036-ab22605ffd06
A couple of noteworthy things:
- I introduced a context that wraps the deployments table to ensure only one graph displays a tooltip at a time.
- The query for the flow runs lives in a table cell because the number of flow runs to query for is determined by the cell size.

Add flow run activity bar graph to deployments table

---

.github/workflows/benchmarks.yaml
.github/workflows/codspeed-benchmarks.yaml
.github/workflows/markdown-tests.yaml
.github/workflows/python-tests.yaml
tests/cli/test_prompts.py
tests/telemetry/test_instrumentation.py

This PR tweaks our testing setup to optimize our runner usage. I removed coverage collection because it added overhead to our test suite and provided little value. If we want to gather coverage, we can create an on-demand job to gather coverage data when needed. I also split up the test suite between jobs more effectively and updated all jobs to use the default Ubuntu runners. With these changes we get roughly the same speed at a fraction of the cost.

Tune CI for efficiency

---

src/prefect/server/models/events.py
tests/server/orchestration/test_flow_run_instrumentation_policies.py

When generating the related resources for flow run state change events. Make sure to include the work pool type as well.

Add work pool type to related resource 

---

tests/client/test_prefect_client.py
tests/test_flows.py

In investigating https://github.com/PrefectHQ/prefect/issues/11233, which I don't think is a problem for 3.x, I noticed we didn't appear to have test coverage for this scenario. This PR adds two tests.

Add some tests for failure hooks and retries

---

src/prefect/cli/server.py
tests/cli/test_start_server.py

In #16644, we were able to get the standalone Prefect server we run in
`prefect server start` from 400MB to 343MB.  By running `uvicorn`
directly in the parent process, we further reduce that to **266MB**.  I
measured this using the same process as before, using a `cgroup` with
no swap to constrain the memory until I found the minimum.
There are two main changes here:
1. Making `prefect server start` a synchronous command in both the
background and the foreground cases.  This helps to simplify the
handling of signals and removes the need for `anyio` or piping the
streams of a child process manually.
2. Splitting the paths between background and foreground servers.  In
the case of the background server, we run the subprocess as usual and
then exit leaving it running.  In the case of the …

Reduces the memory requirement of a standalone Prefect server again

---

docs/v3/develop/task-caching.mdx
docs/v3/develop/write-tasks.mdx
src/prefect/cache_policies.py
src/prefect/task_worker.py
src/prefect/tasks.py
tests/test_tasks.py
ui-v2/src/api/prefect.ts

We've seen multiple get users get confused about the `NONE` cache policy, thinking that passing the Python `None` is sufficient to engage this policy. To avoid this confusion, this PR proposes renaming `NONE` to `NO_CACHE` to be explicit, updates docs accordingly, and keeps `NONE` around to avoid any breaking changes.
**cc:** @gabcoyne

Proposal: NONE to NO_CACHE

---

src/prefect/runner/runner.py

Based on [this comment](https://github.com/PrefectHQ/prefect/issues/16515#issuecomment-2579750302)

Update runner docstring for clarity of their universality

---

src/integrations/prefect-ray/prefect_ray/task_runners.py
src/integrations/prefect-ray/tests/test_task_runners.py
src/prefect/context.py
src/prefect/task_runners.py
src/prefect/telemetry/services.py

fixes `EngineContext` rebuild error, which when occurring was causing this downstream error, as the pydantic error could not be serialized
```
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
traceback: Traceback (most recent call last):
File "/Users/nate/Library/Caches/uv/archive-v0/9aF8mmPcr6WgOvDDdAgDC/lib/python3.12/site-packages/ray/exceptions.py", line 51, in from_ray_exception
return pickle.loads(ray_exception.serialized_exception)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PydanticErrorMixin.__init__() missing 1 required keyword-only argument: 'code'
```
and assorted typing improvements

call `FlowRunContext.model_rebuild()` in `hydrate_context`

---

src/prefect/settings/base.py
src/prefect/settings/models/root.py
tests/test_settings.py

In some cases, the connection URL is set to a plain string instead of a `SecretStr`, which causes serialization to fail when serializing to a JSON-compatible form. This fixes that.
Closes https://github.com/PrefectHQ/prefect/issues/16657

Fix connection string handling when individual components are provided via settings

---

ui-v2/.storybook/preview-body.html
ui-v2/.storybook/preview.ts
ui-v2/src/storybook/utils/index.ts
ui-v2/src/storybook/utils/mode-decorator.tsx

Adds a dark mode storybook decorator, and applies it to all stories.
Although dark mode does not seem to be a priority, it will help developers be more conscious about it when developing components
https://github.com/user-attachments/assets/427975e3-1ee0-4330-8b56-f5417ebeeec7

[UI v2] experiment: Adds dark mode decorator for all stories

---

requirements-client.txt

Tests fail for me locally with various validation errors under pydantic 2.7.1, but not if I upgrade to 2.9, e.g.,
```
E       pydantic_core._pydantic_core.ValidationError: 1 validation error for ServerEventsSettings
E       prefect_api_events_related_resource_cache_ttl
E         Input should be a valid timedelta, "day" identifier in duration not correctly formatted [type=time_delta_parsing, input_value='0:06:00', input_type=str]
E           For further information visit https://errors.pydantic.dev/2.7/v/time_delta_parsing
../../miniconda3/envs/prefect/lib/python3.10/site-packages/pydantic_settings/main.py:167: ValidationError
FAILED tests/test_settings.py::TestSettingValues::test_set_via_env_var[PREFECT_API_EVENTS_RELATED_RESOURCE_CACHE_TTL] - pydantic_core._pydantic_core.ValidationError: …
```

Bump lower bound on pydantic to 2.9

---

src/prefect/server/services/loop_service.py

I've been investigating our DB connection / performance issues which has led me to looking at how and when we create engines and connection pools; in my investigations I realized that this db interface was unused, and [the commit that removed its use](https://github.com/PrefectHQ/prefect/commit/6e360f4485157f219d4938c452859976d21fe267) appears to have kept the kwarg around out of oversight, not with any specific intent.
I figured the more of these imports we can remove, the better. I'll probably have some more slight refactors of the DB engine at various points as I continue to look into it.

Remove DB interface from `_on_start`

---

src/prefect/utilities/engine.py
tests/telemetry/test_run_telemetry.py

In our OpenTelemetry instrumentation, we were assuming that if we were
resolving a future before running a task, it must be a parameter.  This
isn't true in the case where a future is used in `wait_for`, where the
context's `parameter_name` won't be set.
Fixes #16708

Handles the instrumentation case where a future is only used to wait_for

---

src/prefect/cli/server.py
src/prefect/server/api/server.py

This PR enhances the `prefect server start` command to allow for:
```
prefect server start --no-services
```
Which starts only the webserver and the "services" necessary for event processing (which aren't actual loop services).
I realized that `prefect server start` creates a _single_ connection pool to the database that is shared across both the webserver and all running loop services; this seems problematic to me in high scale / high traffic situations - those connection pools have fundamentally different properties (timeout configuration, pool configuration, etc.). 
The eventual idea is to recommend pairing this new flag with a new CLI command `prefect services start` that starts _only_ the background loop services. This allows users to easily decouple these two components of the …

Allow servers to start with no background services

---

src/prefect/results.py

Related to https://github.com/PrefectHQ/prefect/issues/16292
Gets rid of a couple of `@sync_compatible`s too, so related to https://github.com/PrefectHQ/prefect/issues/15008

Improve typing in `prefect.results`

---

docs/mint.json

The next page after the quickstart was 'Install Prefect', which is redundant since the reader has already installed Prefect by virtue of going through the Quickstart.
I've moved the **Quickstart** immediately before the **Schedule a flow** tutorial in the nav, so that the progression makes more sense.

Move quickstart to immediately before the 'schedule a flow' tutorial in the docs

---

load_testing/run-server.sh
src/prefect/cli/server.py
src/prefect/server/events/services/triggers.py
src/prefect/server/services/loop_service.py
src/prefect/testing/cli.py
tests/cli/test_server_services.py
tests/cli/test_start_server.py
tests/test_logging.py

wondering if maybe should be `experimental` as I think we may want to add some logging config and maybe update the signature of things  - feedback?
- `start`: start all loop services in the foreground
- `--background` start them in the background
- `ls`: list all known loop services and whether they are enabled
- `stop`: stop any running loop services
both `start` and `stop` should be idempotent
in order to ensure the `--background` option can be managed by a single process, I created a hidden `manager` command under `services` (which does not show up in `--help`). open to other suggestions
<details>
<summary>demo usage</summary>
```
» prefect server services start
Starting services... Press CTRL+C to stop
23:16:55.600 | INFO    | prefect.cli.server - Started service: CancellationCleanup …
```

add `prefect server services` CLI commands

---

ui-v2/src/components/automations/automations-wizard/actions-step/action-step.tsx
ui-v2/src/components/automations/automations-wizard/actions-step/action-type-select.tsx
ui-v2/src/components/automations/automations-wizard/actions-step/actions-step.stories.tsx
ui-v2/src/components/automations/automations-wizard/actions-step/actions-step.test.tsx
ui-v2/src/components/automations/automations-wizard/actions-step/actions-step.tsx
ui-v2/src/components/automations/automations-wizard/actions-step/automations-select-state-fields.tsx
ui-v2/src/components/automations/automations-wizard/actions-step/change-flow-run-fields.tsx
ui-v2/src/components/automations/automations-wizard/automation-schema.ts
ui-v2/src/components/automations/automations-wizard/automation-wizard.stories.tsx
ui-v2/src/components/automations/automations-wizard/automation-wizard.tsx
ui-v2/src/components/automations/automations-wizard/details-step/details-step.stories.tsx
ui-v2/src/components/automations/automations-wizard/details-step/details-step.test.tsx
ui-v2/src/components/automations/automations-wizard/details-step/details-step.tsx

1. Updates Automation wizard schema to include `actions`, `name`, and `description`.
2. Elevates the `Form` container and state to a higher level.
3. Updates tests to now be wrapped with a `Form` container
https://github.com/user-attachments/assets/2a4d927d-9822-4006-8632-515937ac66e5

[UI v2] feat: Updates automation wizard action steps to be part of the automation wizard

---

ui-v2/src/api/deployments/use-list-deployments-with-flows/index.ts
ui-v2/src/api/deployments/use-list-deployments-with-flows/use-list-deployments-with-flows.test.ts
ui-v2/src/api/deployments/use-list-deployments-with-flows/use-list-deployments-with-flows.ts
ui-v2/src/api/flows/index.ts
ui-v2/src/components/deployments/data-table/data-table.stories.tsx
ui-v2/src/mocks/create-fake-deployment.ts
ui-v2/src/mocks/index.ts

1. Updates `createFakeDeployment` to only return the deployment object (with override options).
2. Adds `useListDeploymentsWithFlows` hook to join the flow and deployments query data together

[UI v2] feat: Adds hook to join deployment and flow data

---

src/prefect/client/utilities.py
src/prefect/input/actions.py
src/prefect/input/run_input.py

Related to #16292 
This one was a bit more involved because I needed to rearrange some class hierarchy to ensure all parameter types and return values where fully known.

Raise type completeness on `prefect.inputs` to 100%

---

src/integrations/prefect-gcp/prefect_gcp/workers/cloud_run.py
src/integrations/prefect-gcp/prefect_gcp/workers/cloud_run_v2.py
src/integrations/prefect-gcp/prefect_gcp/workers/vertex.py
src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/prefect/utilities/_deprecated.py
src/prefect/utilities/pydantic.py
tests/utilities/test_pydantic.py

Our `JsonPatch` subclass is harshing our type completeness vibes. We don't use it internally any longer, so this PR deprecates it and moves it to a `_deprecated` module so `pyright` will ignore it during type completeness checks. Our `JsonPatch` subclass will remain available for import, but doing so will raise a `DeprecationWarning`.

Deprecate custom `JsonPatch` implementation

---

README.md

This adds some more docs links from our README to help direct folks to our docs as well as keeping out "get started right now" nature of the README.

Add some more tips and docs links

---

src/prefect/infrastructure/provisioners/__init__.py
src/prefect/infrastructure/provisioners/coiled.py
tests/infrastructure/provisioners/test_coiled.py

This adds a provisioner for the Coiled push work pool, so you can do this:
```bash
prefect work-pool create "my-coiled-pool" --type coiled:push --provision-infra
```
It's nearly identical to the Modal push work pool provisioner, substituting coiled for modal throughout.
We'll plan to handle docs as follow up PR.

Add provisioner for Coiled push work pools

---

src/prefect/infrastructure/provisioners/coiled.py

Fixes type completeness failures on `main`.

Add type hints to `CoiledPushProvisioner`

---

ui-v2/src/components/automations/automation-page/automation-page.tsx
ui-v2/src/components/automations/automation-page/index.ts
ui-v2/src/components/automations/automation-page/nav-header.tsx
ui-v2/src/components/automations/use-delete-automation-confirmation-dialog.ts
ui-v2/src/routeTree.gen.ts
ui-v2/src/routes/automations/automation.$id.tsx

1. Creates `useDeleteAutomationConfirmationDialog`. This will most likely be reused in `/automations` view as well.
2. Starts the Route and component for the Automation details page. Will push future PRs to handle the logic for triggers and actions.
https://github.com/user-attachments/assets/98f154bf-04c4-4de3-93d9-7418101ca705

[UI v2] feat: Starts automation details page

---

src/prefect/_internal/concurrency/services.py
tests/_internal/concurrency/test_services.py

As @jakekaplan and I were debugging a different issue, we realized that
the implementation of `QueueServiceBase.instance` would return an
instance of the wrong type if there were two subclasses that both used
the same `args` (including the empty `args`).  Luckily, the subclasses
of `QueueService` we have so far seem to avoid this by overriding
`instance` or by using different `args`, but this leaves a trap for
folks implementing services in the future.

Ensures that `QueueService` instances are unique within types

---

docs/v3/deploy/infrastructure-examples/managed.mdx

this PR publishes our outbound ip addresses, so users can whitelist addresses when running work in managed execution
other saas tools publish these addresses in their documentation, such as:
https://clickhouse.com/docs/en/manage/security/cloud-endpoints-api
https://docs.lightstep.com/docs/data-security-in-lightstep#the-cloud-observability-microsatellites-or-opentelemetry-collectors-and-the-saas-platform

docs: publish static outbound ip address for managed execution

---

docs/v3/develop/settings-ref.mdx
schemas/settings.schema.json
src/prefect/server/database/configurations.py
src/prefect/settings/models/server/database.py
tests/test_settings.py

This moves the new and unreleased `app_name` field I added recently to a dedicated new section of settings for connect args. I didn't want to add more logic yet as I want to be mindful of changes to settings, but ultimately I think this is the place to put the new fields suggested in https://github.com/PrefectHQ/prefect/pull/16374 and there are a few top-level settings within `[database]` that could be deprecated and moved here (`connection_timeout` and `timeout` for example).

Move app name setting to new nested settings object

---

ui-v2/src/api/deployments/use-list-deployments-with-flows/use-list-deployments-with-flows.ts
ui-v2/src/components/automations/action-details/action-details.stories.tsx
ui-v2/src/components/automations/action-details/action-details.tsx
ui-v2/src/components/automations/action-details/index.ts
ui-v2/src/components/automations/automation-page/automation-page.tsx

1. Begins writing components for the UX on what an action does. First starting with the simple actions and actions that are inferred
2. Writes a storybook to help display the different UX based on the action
3. Adds improvement to remove redundant ids when joining deployments and flows
Will add tests once things are more complete (and compoennt pattern is proven)
https://github.com/user-attachments/assets/9a2a4cca-1106-4923-93f3-cb87ae8d23e4

[UI v2] feat: Begins logic for creating UX based on an action type

---

src/prefect/cli/deploy.py

begins improving typing in `prefect.cli.deploy` to make it easier for an eventual refactor

typing `cli.deploy`

---

src/prefect/cli/server.py

https://github.com/PrefectHQ/prefect/pull/16651 introduced a regression where `PREFECT_SERVER_LOGGING_LEVEL` was not respected when starting a server via `prefect server start`, we need to pass the `log_level` to `uvicorn`
[original report](https://prefect-community.slack.com/archives/CL09KU1K7/p1737051883805439)

respect `PREFECT_SERVER_LOGGING_LEVEL` in `prefect server start`

---

src/prefect/cli/dashboard.py
src/prefect/cli/deploy.py
tests/cli/test_dashboard.py

if cloud is down (like it was for maintenance) then `prefect dashboard open` hangs as it tries to find your workspace, but you're using OSS this shouldn't matter and it should exit early
stacked on https://github.com/PrefectHQ/prefect/pull/16767

don't make extra calls to cloud in `prefect dashboard open`

---

src/prefect/logging/configuration.py
tests/test_logging.py

Each logger defined in 'PREFECT_LOGGING_EXTRA_LOGGERS' now has their level set according to the 'prefect.extra' level. Previously, this only occurred when their level was NOTSET.
Additionally, avoid configuring the logger 'level' and 'propagate' values while iterating over 'extra_config.handlers'
closes https://github.com/PrefectHQ/prefect/issues/15370

Fix configuring loggers found in 'PREFECT_LOGGING_EXTRA_LOGGERS'

---

docs/integrations/prefect-aws/index.mdx
docs/v3/develop/blocks.mdx

This more explicitly documents how to create the various `prefect-aws` blocks, adds more examples, reorganizes a few things, and updates some language.

Update prefect-aws docs

---

src/prefect/cache_policies.py
tests/test_cache_policies.py
tests/test_tasks.py

Ensure multiple `Inputs` cache policies are consolidated when used in a `CompoundCachePolicy`

---

src/prefect/client/orchestration/_deployments/client.py
src/prefect/flows.py
src/prefect/logging/loggers.py
src/prefect/runner/runner.py

This PR fixes all typing errors for the `Runner`. I want to refactor the `Runner` a bit and starting out with no red squiggles will make that easier.

Fix all typing errors in `prefect.runner.runner`

---

ui-v2/src/components/automations/action-details/action-details.tsx
ui-v2/src/components/ui/flow-run-activity-bar-graph/index.tsx
ui-v2/src/components/ui/run-card/run-card.tsx
ui-v2/src/components/ui/state-badge/index.tsx
ui-v2/src/components/ui/state-badge/state-badge.stories.tsx
ui-v2/src/components/ui/state-badge/state-badge.test.tsx

Updates props for `StateBadge` component to only look for the UI components

[UI v2] feat: Updates StateBadge components props to be detached from State schema

---

flows/automation-assessments.py
src/prefect/events/filters.py
src/prefect/types/__init__.py
src/prefect/types/_datetime.py

moving use of `pendulum` into `prefect.types` so we can switch off, taking up the torch from #16609 , which bit off more than I intended
Would also like to gather feedback about the strategy to replicating the top level utils (outside `DateTime`, `Date` etc) from `pendulum` like `pendulum.parse`
my initial thoughts are that we:
- pick sane but bespoke names (easy to mass replace later)
- keep them all in a private module `prefect.types._datetime`
- eventually implement the same API, improving it as needed before putting it in `prefect.types` proper

start incremental `pendulum` consolidation

---

src/prefect/client/orchestration/_automations/client.py
tests/test_automations.py

In #16822, a user shared that a refactor in #16579 to address the memory footprint of the client omitted an import of `UUID` in the `find_automation` method of the client, a bug that was missed to incomplete test coverage.
This PR closes #16822 and adds the missing test. We should inspect more broadly about whether there are more holes in our test coverage of the client.

Add missing function body import in client.find_automation

---

src/prefect/_experimental/lineage.py
tests/experimental/test_lineage.py

Emits all the necessary events to connect one external lineage resource to another with a flow as the facilitator.
`upstream`->`(flow)`->`downstream`
Example usage:
```python
upstream_resources = [
{
"prefect.resource.id": "api://interesting.data.source/cool",
"prefect.resource.role": "api",
}
]
downstream_resources = [
{
"prefect.resource.id": "snowflake://my-database/my-schema/my-table",
"prefect.resource.role": "table",
}
]
@flow
async def test_flow():
await emit_external_resource_lineage(
upstream_resources=upstream_resources,
downstream_resources=downstream_resources,
)
```

Add experimental function for connecting external lineage resources

---

.github/workflows/docker-images.yaml
.github/workflows/time-docker-build.yaml
Dockerfile

In the interest of helping folks looking to horizontally scale out
Prefect, we want to include `prefect-redis` in the base image.  This is
unusual for a Prefect integration, but we feel that including the
Redis implementation of messaging and caching will enable folks to make
a simpler transition to running the server and services separately.
Since `redis` is already a dependency of Prefect, this will add very
minimal heft to the image (<1MB).

Adds `prefect-redis` to the Prefect image

---

docs/v3/get-started/index.mdx

Closes https://linear.app/prefect/issue/DOC-136/mini-history-of-prefect-new-sub-section
Preview: https://prefect-bd373955-add_timeline_to_introduction_doc.mintlify.app/v3/get-started/index#mini-history-of-prefect

Add mini-history of Prefect to the introduction page of the docs

---

ui-v2/src/api/deployments/deployments.test.ts
ui-v2/src/api/deployments/index.ts
ui-v2/tests/utils/handlers.ts

Needed to cal the /filter endpoint for deployments in the automations page.
This PR re-organizes the hierarchy of `deployments` query keys to add another layer for `lists`

[UI v2] feat: Adds deployments filter query

---

src/prefect/server/services/task_run_recorder.py

related to https://github.com/PrefectHQ/prefect/issues/16299
in the `TaskRunRecorder` we call `record_task_run_event` which performs
- an insert of the task run where the state timestamp is newer
- an insert of the task run state
- an update of the task run where the timestamp is non-existent or older than the current state's timestamp
`record_task_run_event` wraps these statements in a transaction, but these operations should be idempotent. In the interest of speeding up the many writes that may occur when running task-heavy flows, this PR removes `begin_transaction=True`

No transaction in `TaskRunRecorder`

---

src/integrations/prefect-redis/prefect_redis/messaging.py
src/integrations/prefect-redis/tests/test_messaging.py
src/prefect/server/events/clients.py
src/prefect/server/utilities/messaging/__init__.py
src/prefect/server/utilities/messaging/memory.py
tests/server/utilities/test_messaging.py

There was a small gap where the base `EventPublisher` wasn't calling
`__aenter__` on the underlying messaging `Publisher` implementation.
I wanted to add compatibility tests to make sure this was true in both
the memory and redis implementations, and firm up the interface.
Prior to the fix, trying to use the Redis messaging system lead to this error:
```
server-7bf457464-kwmhn prefect-server     async with PrefectServerEventsClient() as events:
server-7bf457464-kwmhn prefect-server                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
server-7bf457464-kwmhn prefect-server   File "/usr/local/lib/python3.12/site-packages/prefect/server/events/clients.py", line 223, in __aexit__
server-7bf457464-kwmhn prefect-server     await self._publisher.__aexit__(exc_type, exc_val, exc_tb)
server-7bf457464-kwmhn …
```

Ensures that the Redis messaging implementation works with event clients

---

load_testing/run-server.sh
load_testing/track_cnx.py

after https://github.com/PrefectHQ/prefect/pull/16651, wrapping `create_app` as the telemetry entrypoint for the server no longer worked, since it would not run the services, so this PR updates the entrypoint used by the local telemetry harness
also adds a script to view / inspect the state of active db connections

Fix script to run server with local telemetry

---

src/prefect/server/models/concurrency_limits.py

@zzstoatzz observed an excessive amount of pointless DB queries looking for old-style concurrency limits by tag, filtering on `WHERE concurrency_limit.tag in (NULL)`.
I did some digging and found the following sequence:
- subflow runs create "dummy" task runs that reflect their state in the parent flow run
- these are created through the standard `create_task_run` API logic, which invokes the old orchestration policies
- the standard orchestration policies include [this line](https://github.com/PrefectHQ/prefect/blob/131136b419df6fe32bfc39d8e8664523719f8768/src/prefect/server/orchestration/core_policy.py#L324) which looks up any relevant concurrency limits
That lookup is _not_ gated by `tags` being non-empty, so the query is actually made even though we know it will return an empty list. …

Stop making useless query

---

src/prefect/flow_engine.py
tests/test_flow_engine.py

This PR adds a `context` attribute to the `BaseFlowRunEngine` so that context can be transported between different engine instances to may not be running in the same process or on the same machine. The engine is updated to use `hydrated_context` to create a full context from the provided object. This matches the same pattern used in the task run engine.

Add the ability to pass context into the flow run engine

---

src/prefect/cache_policies.py
tests/test_cache_policies.py

This PR implements @a14e's suggested bug fix as discussed [here](https://github.com/PrefectHQ/prefect/issues/16773#issuecomment-2605390190).
In particular, cache policies which do not already rely on run inputs should _not_ implicitly begin relying on run inputs just because the subtraction operator was used.

Fix subtraction logic on non-input cache policies

---

src/prefect/_experimental/lineage.py
tests/experimental/test_lineage.py

This PR updates the experimental external lineage interface introduced in #16820 to allow passing an event name; this name will be recorded only for the direct connection between lineage resources. It also fixes a bug where context resources weren't being registered as lineage resources in the global namespace.
cc @kevingrismore 

[Experimental] Enhancement: Lineage interface event names and context resource registration

---

ui-v2/src/api/automations/use-get-automation-action-resources/index.ts
ui-v2/src/api/automations/use-get-automation-action-resources/use-get-automation-action-resources.test.ts
ui-v2/src/api/automations/use-get-automation-action-resources/use-get-automation-action-resources.ts

Adds `useGetAutomationActionResources` hook.
This hook is to enables the UX to join data between an automation's action and its source.
Used to fulfill UX such as:

[UI v2] feat: Adds hook to combine sources from an automation action

---

src/integrations/prefect-aws/prefect_aws/batch.py
src/integrations/prefect-aws/prefect_aws/client_waiter.py
src/integrations/prefect-aws/prefect_aws/s3.py

`@async_dispatch` wasn't dispatching correctly and causing failures in the `prefect_aws` test suite. We started checking the parent run to determine if a function should be dispatched to async or not for compatibility with `@sync_compatible` behavior. Since `@task` was on top of `@async_dispatch`, the functions were always considered to be running in a sync task. This PR swaps the order of decorators.

Fix async dispatch for `prefect_aws` tasks

---

src/integrations/prefect-dbt/prefect_dbt/cli/configs/base.py
src/integrations/prefect-dbt/prefect_dbt/cli/credentials.py
src/integrations/prefect-dbt/tests/cli/test_commands.py
src/integrations/prefect-dbt/tests/cli/test_credentials.py
src/prefect/blocks/core.py

<details>
<summary>does not load nested blocks</summary>
```python
from typing import Union
from pydantic import Field
from prefect.blocks.core import Block
class ChildBlockX(Block):
x: int = Field(default=1)
class ChildBlockY(Block):
y: int = Field(default=2)
class ParentBlock(Block):
child: Union[ChildBlockX, ChildBlockY] = Field(default=...)
ParentBlock(
child=ChildBlockX(x=42),
).save("parent-x", overwrite=True)
ParentBlock(
child=ChildBlockY(y=42),
).save("parent-y", overwrite=True)
print(ParentBlock.load("parent-x"))
print(ParentBlock.load("parent-y"))
```
```
» python sandbox/nested_block_save.py
ParentBlock(child=ChildBlockX(x=42))
ParentBlock(child=ChildBlockY()) # why is this empty?
```
</details>
<details>
<summary>example that appears to</summary>
```python
from typing import …
```

add `Discriminator` for `dbt` target config union

---

src/integrations/prefect-dbt/prefect_dbt/__init__.py
src/integrations/prefect-dbt/prefect_dbt/cli/configs/base.py
src/integrations/prefect-dbt/prefect_dbt/cli/credentials.py
src/integrations/prefect-dbt/prefect_dbt/core/__init__.py
src/integrations/prefect-dbt/prefect_dbt/core/settings.py
src/integrations/prefect-dbt/tests/cli/test_commands.py
src/integrations/prefect-dbt/tests/cli/test_credentials.py
src/integrations/prefect-dbt/tests/core/test_settings.py
src/prefect/blocks/core.py

This introduces `PrefectDbtSettings`, which automatically detects a common set of `DBT_`-prefixed env vars upon instantiation. Intended for use with `PrefectDbtRunner`.

Add `PrefectDbtSettings` to `prefect-dbt`

---

src/integrations/prefect-snowflake/prefect_snowflake/database.py
src/integrations/prefect-snowflake/tests/test_database.py

This PR updates `SnowflakeConnector` to handle setting `schema_` with different keys. This update helps the block handle cases where the data was dumped without using the serialization alias, which was seen in https://github.com/PrefectHQ/prefect/pull/16834.

Add additional `validation_alias` to `SnowflakeConnector`

---

ui-v2/src/components/automations/action-details/action-details.tsx
ui-v2/src/components/automations/automation-details.tsx
ui-v2/src/components/deployments/data-table/index.tsx
ui-v2/src/components/ui/schedule-badge/index.tsx
ui-v2/src/components/ui/state-badge/index.tsx
ui-v2/src/components/ui/status-badge/index.tsx
ui-v2/src/components/variables/data-table/data-table.tsx
ui-v2/src/mocks/create-fake-state.ts
ui-v2/src/utils/index.ts
ui-v2/src/utils/utils.test.ts
ui-v2/src/utils/utils.ts

When doing the UI replatforming, there's a few string utililties that can be re-used via a function:
`pluralize` and `capitalize`
CC @devangrose

[UI v2] feat: Adds basic string utils that can be re-used throughout the app

---

src/prefect/cli/deploy.py
src/prefect/client/schemas/actions.py
src/prefect/deployments/base.py
tests/cli/test_deploy.py
tests/client/schemas/test_schedules.py

closes https://github.com/PrefectHQ/prefect/issues/16826
this PR constructs schedules later so we can template in step outputs, tests are updated as the user is prompted after work pool info for a given deployment (which changes the expected outputs of all the interactive tests)
consider an example like this
```python
- entrypoint: repros/16826/main.py:scheduled_flow
name: schedule-active-flag-repro
work_pool:
name: local
build:
- prefect.deployments.steps.run_shell_script:
id: get-schedule-isactive
script: sh repros/16826/get-schedule-isactive.sh
stream_output: false
schedules:
- cron: "*/5 * * * *"
timezone: "America/Chicago"
active: "{{ get-schedule-isactive.stdout }}"
```
where that bash is just doing
```python
#!/bin/sh
echo "false" 
```
historically, this would not work, as schedule …

allow templating `schedules` in `prefect.yaml`

---

.github/CODEOWNERS

Adds @devinvillarosa as a `ui-v2` codeowner.

Update `ui-v2` codeowners

---

.github/CODEOWNERS

this PR is a changing of the guard on /docs. 
an immense gratitude to @discdiver for carrying docs on his shoulders for so long. 
excited to take on that burden with @daniel-prefect , @kevingrismore  and @seanpwlms

Update CODEOWNERS for /docs

---

src/prefect/flow_engine.py

Small follow up to https://github.com/PrefectHQ/prefect/pull/16802

Fixes typing of `run_flow_in_subprocess`

---

src/prefect/artifacts.py
tests/fixtures/api.py
tests/test_artifacts.py

Related to https://github.com/PrefectHQ/prefect/issues/15008
I also addressed the `pyright` errors in `tests/test_artifacts.py`, which is why the diff is a bit messy.

Remove `@sync_compatible` from `prefect.artifacts`

---

src/prefect/blocks/notifications.py
tests/blocks/test_notifications.py

Apprise supports this but we need to surface the configuration part and pass it on. Keeping default to insecure connection to not break compatibility, but perhaps worth reconsidering.
-  I think this is small enough of a fix?

Add support for secure Mattermost notifications

---

ui-v2/src/components/automations/automation-details-page.tsx
ui-v2/src/components/automations/automation-details.tsx
ui-v2/src/components/automations/automation-enable-toggle/automation-enable-toggle.stories.tsx
ui-v2/src/components/automations/automation-enable-toggle/automation-enable-toggle.test.tsx
ui-v2/src/components/automations/automation-enable-toggle/automation-enable-toggle.tsx
ui-v2/src/components/automations/automations-page.tsx
ui-v2/tests/utils/handlers.ts

Renames prop `data` to be more explicit to `automation`

[UI v2] chore: rename automation props from data to automation

---

src/prefect/cli/_prompts.py
tests/cli/test_prompts.py

closes #16882 
excludes `**/site-packages/**` using `filter_files`

Exclude `site-packages` from scanned dirs in `prefect deploy`

---

src/prefect/__main__.py

Added __main__ module to prefect package to be able to use prefect cli with `python -m prefect ...` approach.

Allow CLI to be invoked with `python -m prefect`

---

src/prefect/tasks.py
tests/typesafety/test_flows.yml
tests/typesafety/test_tasks.yml

This PR removes a duplicate overload for `Task.__call__` and adds one to handle basic calls.
Here's the new overload, because the diff kinda obscures it:
```python
@overload
def __call__(
self: "Task[P, R]",
*args: P.args,
**kwargs: P.kwargs,
) -> R:
...
```
I added some type safety tests to prevent future regression.
Closes https://github.com/PrefectHQ/prefect/issues/16856

Add missing overload for `Task.__call__`

---

src/prefect/_experimental/lineage.py
tests/experimental/test_lineage.py

All upstream, downstream, and direct lineage events will now include any tags in the Prefect context as related resources so we can filter lineage resources by tag in the UI.

[Experimental] Include tags as related resources on lineage events

---

src/prefect/server/api/server.py
src/prefect/server/events/services/actions.py
src/prefect/server/events/services/event_logger.py
src/prefect/server/events/services/event_persister.py
src/prefect/server/events/services/triggers.py
src/prefect/server/services/base.py
src/prefect/server/services/loop_service.py

We have two kinds of background services in the Prefect server: loop
services that run a task periodically, and consumer services that react
to messages on a message bus.  I'd like to unify their treatment in a
series of PRs with a few goals:
- That we can run the consumer-style services along with the loop
services in the background service process we start with `prefect
server services`
- That we can either opt-in or opt-out of running services in either
the API or the background services process
- That we can take the next step in refactoring services following the
really cool discovery logic that @zzstoatzz added to the CLI:
- A service knows which setting enables itself
- There is one routine for finding the relevant services to start or
stop for a given process
- The starting and …

Introduces a `Service` base class to cover loop and other services

---

src/prefect/deployments/runner.py
src/prefect/flows.py
src/prefect/testing/utilities.py
tests/conftest.py
tests/fixtures/database.py
tests/runner/test_runner.py
tests/test_flows.py

Introduces new explicitly async methods to use `async_dispatch` instead of `sync_compatible`.
Related to https://github.com/PrefectHQ/prefect/issues/15008

Add `Flow.ato_deployment`, `Flow.afrom_source`, and `Runner.afrom_storage`

---

src/prefect/server/events/services/event_persister.py
tests/events/server/storage/test_event_persister.py

Proposed fix for issue https://github.com/PrefectHQ/prefect/issues/16906
Before, events itself were deleted according to the event retention period, but the corresponding event resources would accumulate and block database disk space. This PR adds event resources to the same lifecycle logic as events.
From what I understand, it is safe to delete old event resources the same way as old events. However this assumption is something that someone with more insight than me should challenge - if this PR is merged, the next update of Prefect deletes potentially millions of old event resources in line with the event retention policy.
closes https://github.com/PrefectHQ/prefect/issues/16906

Add event resources to the event cleanup cycle

---

src/prefect/server/orchestration/core_policy.py
tests/server/orchestration/api/test_task_runs.py

This is the OSS side of https://github.com/PrefectHQ/nebula/pull/9069. In Cloud we had an issue where a task run caused a 500 error because the cache key was too long. This adds some validation to the CacheInsertion policy to reject these task runs rather than let them cause the 500.
Related to CLOUD-900

Reject task run state change if the cache key is too large

---

src/prefect/client/schemas/objects.py
src/prefect/events/utilities.py

`emit_event` can be used in OSS, so the current message is needlessly skewed towards cloud
related to #16910

fix `emit_event` docstring

---

.github/workflows/integration-package-tests.yaml
src/integrations/prefect-dask/tests/conftest.py
src/integrations/prefect-dask/tests/test_client.py
src/integrations/prefect-dask/tests/test_task_runners.py

`prefect-dask` tests are failing on `main`. This PR fixes that by removing unnecessary fixtures like the scoped event loop and `use_hosted_api_server` (`prefect_test_harness` takes care of that), reusing Dask clusters where possible, and updating two tests to run with only a single task runner because they aren't dependent on the task runner configuration.

Fix `prefect-dask` test suite

---

src/prefect/utilities/importtools.py

I searched the codebase and couldn't find any use of this function, which is our only use of `runpy` outside of tests. Removing for tidiness.
Closes https://github.com/PrefectHQ/prefect/issues/7869

Remove unused function

---

src/integrations/prefect-dbt/prefect_dbt/cli/commands.py
src/integrations/prefect-dbt/tests/cli/test_commands.py
src/integrations/prefect-dbt/tests/conftest.py

closes https://github.com/PrefectHQ/prefect/issues/16924
https://github.com/PrefectHQ/prefect/pull/16877 removed `sync_compatible` from artifact methods / top-level utils

fix `create_markdown_artifact` usage in `prefect-dbt`

---

docs/v3/develop/task-caching.mdx
src/prefect/cache_policies.py

related to #16925 
update docs and docstring

add notes on `TASK_SOURCE` behavior

---

src/integrations/prefect-dbt/prefect_dbt/core/profiles.py
src/integrations/prefect-dbt/tests/core/test_profiles.py
src/prefect/utilities/templating.py

This module includes utilities for locating and loading dbt profiles from YAML. It also enables the resolution of block and variable references when the `PrefectDbtRunner` executes dbt commands by writing the resolved file to a temporary directory.
```yaml
test:
outputs:
dev:
type: duckdb
path: dev.duckdb
threads: 1
prod:
type: duckdb
path: prod.duckdb
threads: 4
password: "{{ prefect.blocks.secret.my-password }}"
target: "{{ prefect.variables.dbt_target }}"
```
At the moment, all block references resolve to calls to dbt's `env_var()` since blocks can contain secrets, and block values are stored as env vars. Variables are resolved directly to text.
```yaml
test:
outputs:
dev:
type: duckdb
path: dev.duckdb
threads: 1
prod:
type: duckdb
path: prod.duckdb
threads: 4
password: "{{ …
```

Add dbt profiles utilities

---

src/prefect/cli/server.py
src/prefect/server/api/server.py
src/prefect/server/events/services/actions.py
src/prefect/server/events/services/event_logger.py
src/prefect/server/events/services/event_persister.py
src/prefect/server/events/services/triggers.py
src/prefect/server/events/stream.py
src/prefect/server/services/base.py
src/prefect/server/services/task_run_recorder.py

In the final step of the plan to unify how services are handled (
after #16898 and #16913), we tie everything together by having both the
API lifespan in `prefect server start` and the CLI `prefect server
services start` use the same service running logic.
At this point, when adding a new service, we should just need to add a
new subclass, implement its settings class, and then make sure its
module is represented in `server/services/base.py`.

Unifies background service running between the web server and CLI

---

src/prefect/cli/profile.py
tests/cli/test_profile.py

Closes https://github.com/PrefectHQ/prefect/issues/15643

Add fix for creating profile with default name conflict

---

ui-v2/src/components/settings/server-settings.tsx
ui-v2/src/components/ui/json-input.tsx

1, Adds server settings UI by re-using `JsonInput` component.
2. Adds prop to `JsonInput` component to exclude line numbers
https://github.com/user-attachments/assets/bf765ded-ab51-4203-8708-0cbcc9822908

[UI v2] feat: Adds Server Settings component

---

ui-v2/src/components/settings/theme-switch.tsx

Adds dark mode switch to the settings page.
In a different PR, will update the server settings section to work better with dark mode
https://github.com/user-attachments/assets/8fda446e-186d-4a08-ad3b-95ccacf72299

 [UI v2] feat: Adds Server Settings component

---

src/prefect/client/schemas/schedules.py

anticipating updates to schedules schemas, this PR removes direct `pendulum` use per #16910

rm `pendulum` use in `schedules.py`

---

src/prefect/server/database/_migrations/MIGRATION-NOTES.md
src/prefect/server/database/_migrations/versions/postgresql/2025_02_03_125146_c163acd7e8e3_add_parameters_column_to_deployment_.py
src/prefect/server/database/_migrations/versions/sqlite/2025_02_03_125228_67f886da208e_add_parameters_column_to_deployment_.py
src/prefect/server/database/orm_models.py

First step towards supporting per-schedule parameter overrides.

Add database migration that adds parameter fields to deployment schedules

---

.github/CODEOWNERS

As we saw on https://github.com/PrefectHQ/prefect/pull/16921, changes to settings incur a huge review cost in the form of tagging tons of people (unnecessarily). 
CODEOWNERS files take into account the last line referencing a file for review requests, so you can effectively "reset" individual files as needed. This PR uses that pattern for settings related file changes that don't need doc-team review.

Add file exclusion to codeowners

---

.github/CODEOWNERS
.github/labeler.yml

I noticed that [this PR](https://github.com/PrefectHQ/prefect/pull/16947) was not properly tagged; also following up on #16957 this PR also adjusts our labeler to avoid the `ui-replatform` label and auto-review tags when we only touch settings.

Update a few more small things for labeler and review tags

---

src/prefect/cli/server.py
tests/cli/test_start_server.py

closes #16950
adds an exception case to give a better error message when a bad `host` is provided to `prefect server start`

fix handling for bad `host` with `prefect server start`

---

.github/labeler.yml
src/prefect/_internal/schemas/bases.py
src/prefect/server/utilities/schemas/bases.py
tests/server/utilities/test_schemas.py

This is making test-writing harder and prevents us from making server changes independently of client changes easily. (ref: #16951 )

Remove switching logic within settings config

---

.github/workflows/python-tests.yaml

I don't think this is being used anywhere and it is friction to getting to test failures because the artifact name creation is many-to-one.

Remove failure flag

---

src/prefect/cli/deploy.py
src/prefect/client/schemas/actions.py
src/prefect/client/schemas/objects.py
tests/cli/test_deploy.py

Allows per-schedule parameter overrides to be defined in a `prefect.yaml` like so:
```yaml
schedules:
- cron: '* * * * *'
timezone: America/Chicago
parameters:
do_something: true
person:
name: Marvin
age: 7
```

Allow definition of per-schedule parameter overrides via `prefect.yaml`

---

docs/v3/resources/upgrade-to-prefect-3.mdx
src/prefect/task_engine.py
tests/test_task_engine.py
tests/test_tasks.py

Closes https://github.com/PrefectHQ/prefect/issues/16848

Target `wait` warning to more specific circumstances

---

.pre-commit-config.yaml

I routinely run into a situation where my UI pre-commit hooks fail, and in doing so they also update `package-lock.json`; this PR ensures that all UI-related pre-commit hooks use `nvm` which prevents this sort of thing from happening.

Use nvm in pre-commit hooks

---

src/prefect/client/orchestration/_deployments/client.py
src/prefect/client/orchestration/base.py

I noticed that our clients no longer use [the dedicated `send(...)` methods](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/client/base.py#L529) that we built to help with flaky API performance. This PR re-engages that logic. 
[As stated in the `httpx` docs](https://www.python-httpx.org/api/), calling `client.request` is
> Equivalent to:
> 
> ```
> request = client.build_request(...)
> response = client.send(request, ...)
> ```
This also resolves an undetected bug in which `PREFECT_CLIENT_RETRY_EXTRA_CODES` was not being used.

Use retry logic of underlying prefect client properly

---

docs/mint.json
docs/v3/api-ref/index.mdx

This PR adds additional valid redirects to the docs including `/latest/reference` and `/v3/reference`.  These should capture all available valid paths that someone may hit for v3 docs.  We are now redirecting these requests to the `/api-ref` endpoint rather than reference.prefect.io.
I have also updated the `Prefect Python SDK` linkout to use a valid prefect domain of reference.prefect.io
Closes: PLA-958

chore: Add additional `reference` redirects

---

docs/v3/api-ref/rest-api/server/schema.json
src/prefect/server/api/deployments.py
src/prefect/server/database/_migrations/versions/postgresql/2025_02_05_152418_a03d00b8e275_add_slug_column_to_deployment_schedule.py
src/prefect/server/database/_migrations/versions/sqlite/2025_02_05_152431_07ecde74d74d_add_slug_column_to_deployment_schedule.py
src/prefect/server/database/orm_models.py
src/prefect/server/models/deployments.py
src/prefect/server/schemas/actions.py
src/prefect/server/schemas/core.py
tests/server/database/test_migrations.py
tests/server/orchestration/api/test_deployment_schedules.py
ui-v2/src/api/prefect.ts

This PR adds a new `slug` column to `deployment_schedules` that is a user-friendly, unique identifier for the schedule. This field is also used for populating `created_by` on scheduled flow runs, falling back to the schedule type if not present. The `created_by` field is already displayed in the UI if present.
Closes https://github.com/PrefectHQ/prefect/issues/13210

Add slugs to schedules and populate created_by

---

.github/labeler.yml

Adding the top level `all:` key should make the any/all syntax work properly now and avoid the spurious `docs` and `ui-replatform` labels on PRs that update settings and the API.

Fix labeler to remove unnecessary labels

---

.github/CODEOWNERS

My last few PRs have touched this file and it's spamming lots of people for unnecessary reviews.

Remove full team from schema json updates

---

ui-v2/src/components/ui/app-sidebar.tsx
ui-v2/src/routeTree.gen.ts
ui-v2/src/routes/notifications.tsx
ui-v2/tests/app.test.tsx

`/notifications` is deprecated in favor for `/automations`.
Deprecating route from `ui-v2` efforts

[UI v2] chore: Deprecates notifications route from react webapp

---

docs/v3/automate/add-schedules.mdx
docs/v3/deploy/infrastructure-concepts/deploy-via-python.mdx
docs/v3/resources/upgrade-to-prefect-3.mdx

follow on to https://github.com/PrefectHQ/prefect/pull/16963 and https://github.com/PrefectHQ/prefect/pull/16965

add docs on per-schedule parameters

---

ui-v2/package.json

Adds npm script `validate:types` (same script name from `/ui`) to only validate typescript.
We currently don't have an npm script that does it. We _do_ have `npm run build` which does type checking **and** builds the app.
Adding this command, because before pushing and opening a PR, I would like to validate types on my client. My IDE doesn't always catch all errors

[UI v2] feat: Adds npm script to check only typescript types

---

ui-v2/src/components/deployments/data-table/index.tsx
ui-v2/src/components/deployments/use-delete-deployment-confirmation-dialog.ts

Moves logic for deleting deployment confirmation dialog to a re-usable hook.
This re-usable hook will be used in the deployment details page for its own action menu.

[UI v2] feat: Moves delete deployment confirmation dialog logic to a re-usable hook

---

ui-v2/src/components/deployments/deployment-details-page.tsx
ui-v2/src/components/deployments/deployment-flow-link.tsx

Adds deployment flow link
https://github.com/user-attachments/assets/fad4315b-ecbd-40cc-81b7-20dcafe7598a

[UI v2] feat: Adds deployment flow link

---

src/integrations/prefect-docker/prefect_docker/types.py
src/integrations/prefect-docker/prefect_docker/worker.py
src/integrations/prefect-docker/tests/test_worker.py

closes #17017 
adds ability to specify anonymous volumes in a docker work pool

support anonymous volumes in `docker` work pool

---

src/prefect/engine.py
src/prefect/flow_engine.py

Two things:
- our exception types have no repr/str of value; `f"{Pause()}"` prints an empty string, so I removed this from the log
- we log "unexpected exception" when catching exceptions that are more expected than unexpected; we have special handling for these exception types so shouldn't say they were unexpected
Closes https://github.com/PrefectHQ/prefect/issues/16915

Remove some log noise in pause and abort handling

---

docs/v3/api-ref/rest-api/server/schema.json
src/prefect/server/api/deployments.py
src/prefect/server/schemas/actions.py
tests/server/orchestration/api/test_deployments.py
ui-v2/src/api/prefect.ts

In preparation for improving the deployment experience with respect to schedules, this PR allows for deployments to update the parameter openAPI schema and adjusts the server-side validation and testes accordingly.

Allow for updating a deployment's parameter openapi schema

---

src/prefect/cli/deploy.py
src/prefect/client/schemas/actions.py
src/prefect/client/schemas/objects.py
src/prefect/schedules.py
tests/cli/test_deploy.py
tests/runner/test_runner.py
tests/test_flows.py

Allows the setting of schedule slugs via a `prefect.yaml file`:
```yaml
schedules:
- cron: "* * * * *"
slug: "my-important-schedule"
```
or via the Python SDK:
```python
from prefect.schedules import Cron
@flow
def say_hello(name: str = "Marvin"):
print(f"Hello, {name}")
say_hello.serve("frequently", schedule=Cron("* * * * *", slug="my-important-schedule")
```

Update deployment SDK to use slugs

---

src/integrations/prefect-dbt/pyproject.toml

https://github.com/PrefectHQ/prefect/pull/16877 removed sync_compatible from `prefect.artifacts` which required https://github.com/PrefectHQ/prefect/pull/16926. 
but when using older versions of core (as is the case here https://github.com/PrefectHQ/prefect/issues/17006) the new explicit async artifact methods don't exist yet
so this PR updates the pin in `prefect-dbt` to require sufficiently new `prefect`
closes #17006

pin core above `3.1.15` for `prefect-dbt`

---

ui-v2/src/components/deployments/deployment-action-menu/deployment-action-menu.stories.tsx
ui-v2/src/components/deployments/deployment-action-menu/deployment-action-menu.test.tsx
ui-v2/src/components/deployments/deployment-action-menu/deployment-action-menu.tsx
ui-v2/src/components/deployments/deployment-action-menu/index.ts
ui-v2/src/components/deployments/deployment-details-page.tsx
ui-v2/src/routeTree.gen.ts
ui-v2/src/routes/deployments/deployment_.$id.duplicate.tsx
ui-v2/src/routes/deployments/deployment_.$id.edit.tsx

Adds Deployment Action Menu component
https://github.com/user-attachments/assets/08793c5e-1991-4093-8e93-c1245be7f0df

 [UI v2] feat: Adds Deployment Action Menu component

---

ui-v2/src/api/flow-runs/flow-runs.test.ts
ui-v2/src/api/flow-runs/index.ts

Adds createDeploymentFlowRun mutation. This is needed for the deployment quick run button

[UI v2] feat: Adds createDeploymentFlowRun mutation

---

src/integrations/prefect-dbt/prefect_dbt/__init__.py
src/integrations/prefect-dbt/prefect_dbt/cli/__init__.py
src/integrations/prefect-dbt/prefect_dbt/core/__init__.py
src/integrations/prefect-dbt/prefect_dbt/core/runner.py
src/integrations/prefect-dbt/pyproject.toml
src/integrations/prefect-dbt/tests/core/test_runner.py
src/integrations/prefect-dbt/tests/dbt_configs/profiles.yml
src/integrations/prefect-dbt/tests/test_imports.py

This is a new primary interface for dbt Core.
Example usage:
```python
from prefect_dbt import PrefectDbtRunner, PrefectDbtSettings
@flow
def run_dbt():
runner = PrefectDbtRunner(
settings=PrefectDbtSettings(project_dir="test", profiles_dir="examples/run_dbt")
)
runner.invoke(["run"])
run_dbt()
```
As this will be replacing the functionality of everything in `prefect_dbt.cli`, any imports from that path will raise the following warning:
```
"prefect_dbt.cli is deprecated and will be removed in a future release. Please use prefect_dbt.core instead."
```
The [previous implementation](https://github.com/PrefectHQ/prefect/blob/main/src/integrations/prefect-dbt/prefect_dbt/cli/commands.py#L178) assumed the presence of a Prefect run logger, …

Add `PrefectDbtRunner`

---

flows/schedule_statefulness.py

adds integration test simulating simple use of `.serve` with named/unnamed schedules

named deployment schedule integration test

---

.github/workflows/docker-images.yaml
.github/workflows/time-docker-build.yaml
Dockerfile

Docker builds have been running offensively long when running `npm ci`. This wasn't shown in our Docker build benchmark because we were only building for `amd64` and `arm64` was causing the issue. I belive the issue is because some of the `npm` dependeices (namely `esbuilt`) rely on C binaries that need to be recompiles for `arm64`.
This PR updates the Docker build benchmark workflow to perform a multi-platform build to get a more accurate read of build performance. It also updates the Dockerfile to only run the UI build step for the current build platform. Since the UI build step produces static HTML, JS, and CSS files, it is not platform-dependent. The result of this change is a ~90% reduction in build time.

Use newer `npm` version in Docker UI build

---

ui-v2/src/components/deployments/deployment-details-page.tsx
ui-v2/src/components/deployments/run-flow-button/index.ts
ui-v2/src/components/deployments/run-flow-button/run-flow-button.stories.tsx
ui-v2/src/components/deployments/run-flow-button/run-flow-button.test.tsx
ui-v2/src/components/deployments/run-flow-button/run-flow-button.tsx
ui-v2/src/routeTree.gen.ts
ui-v2/src/routes/deployments/deployment_.$id.run.tsx

Adds flow run button to deployment details page
https://github.com/user-attachments/assets/383f2d58-cfa7-4844-8b51-b611645455e7

[UI v2] feat: Adds flow run button to deployment details page

---

ui-v2/src/components/ui/toggle/index.ts
ui-v2/src/components/ui/toggle/styles.ts
ui-v2/src/components/ui/toggle/toggle.tsx

Exporting this would give an eslint warning (which shows up in all UI related PRs).
Separating the variants into another file for now and exporting it through an `index.ts` file 
If needed, we can move `toggleVariant` as its own file and import/export it from there

[UI v2] chore: Removes toggleVariants as an export

---

ui-v2/src/components/deployments/deployment-details-tabs.tsx
ui-v2/src/components/deployments/deployment-parameters-table/deployment-parameters-table.stories.tsx
ui-v2/src/components/deployments/deployment-parameters-table/deployment-parameters-table.test.tsx
ui-v2/src/components/deployments/deployment-parameters-table/deployment-parameters-table.tsx
ui-v2/src/components/deployments/deployment-parameters-table/index.ts

Adds deployment parameter table
https://github.com/user-attachments/assets/cb203ca1-69f0-401d-870e-33d50826890f

[UI v2] feat: Adds deployment parameter table

---

src/prefect/settings/sources.py
tests/test_settings.py

closes https://github.com/PrefectHQ/prefect/issues/17068

infer `PREFECT_PROFILES_PATH` from `PREFECT_HOME`

---

src/prefect/cli/deploy.py
tests/cli/test_deploy.py

Fixes a bug where `prefect deploy` will wipe the parameter schema for a deployment.

Fix bug where a flow's parameter schema is not included in deployment create/update requests when using `prefect deploy`

---

src/prefect/flows.py
tests/test_flows.py

In https://github.com/PrefectHQ/prefect/pull/17024 I only partially updated `load_flow`. This PR updates the other half of the branching logic under `load_flow_from_flow_run` to handle non flow functions (which to be honest is what I meant to update in the first place).

Add missing `load_function_and_convert_to_flow`

---

src/integrations/prefect-snowflake/pyproject.toml

Updates `snowflake-connector-python` minimum to be above the End-of-Support version as of May 1, 2025. Snowflake's recommended version is `3.13.2`, so we could also bump it to that. 

prefect-snowflake - Bump snowflake dependency

---

src/prefect/server/models/deployments.py
tests/server/orchestration/api/test_deployments.py

This PR ensures that we default to `active=True` when schedules are recreated via a call to the `POST /deployments` endpoint. This preserves the behavior exhibited prior to the introduction of deployment schedule slugs.

Fix bug where schedules without a slug or active raise a 500

---

src/prefect/client/orchestration/__init__.py
src/prefect/client/schemas/schedules.py

related to https://github.com/PrefectHQ/prefect/issues/16910

pendulum consolidation in `prefect.client`

---

src/prefect/server/database/orm_models.py
src/prefect/server/services/cancellation_cleanup.py
src/prefect/server/services/foreman.py
src/prefect/server/services/late_runs.py
src/prefect/server/services/pause_expirations.py
src/prefect/server/services/scheduler.py
src/prefect/server/services/task_run_recorder.py
src/prefect/server/services/telemetry.py

Related to https://github.com/PrefectHQ/prefect/issues/16910

Consolidate `pendulum` usage in `prefect.server.services`

---

src/prefect/deployments/flow_runs.py
src/prefect/docker/docker_image.py
src/prefect/events/clients.py
src/prefect/events/related.py
src/prefect/locking/filesystem.py
src/prefect/logging/handlers.py
src/prefect/runtime/flow_run.py
src/prefect/types/_datetime.py
src/prefect/utilities/dockerutils.py
tests/runtime/test_flow_run.py

related to #16910 
- deployments/flow_runs.py
- docker/docker_image.py
- events/{clients.py related.py}
- locking/filesystem.py
- logging/handlers.py
- runtime/flow_run.py

pendulum consolidation in several modules

---

ui-v2/src/api/deployments/deployments.test.ts
ui-v2/src/api/deployments/index.ts
ui-v2/tests/utils/handlers.ts

Adds `useDeleteDeploymentSchedule` mutation

[UI v2] feat: Adds useDeleteDeploymentSchedule hook

---

src/prefect/_result_records.py
src/prefect/client/orchestration/__init__.py
src/prefect/server/models/deployments.py
tests/server/services/test_scheduler.py

closes #17115 
using the [MRE](https://github.com/PrefectHQ/prefect/issues/17115#issue-2848846007) in the linked issue
also [defers fixing `get_client` overloads](https://github.com/PrefectHQ/prefect/issues/17124) and type errors in `_result_records` that have started failing on `main`

update idempotency key for scheduled runs to disambiguate schedules

---

ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-dialog/cron-schedule-form.test.tsx
ui-v2/src/components/deployments/deployment-schedules/deployment-schedule-dialog/interval-schedule-form.test.tsx
ui-v2/src/components/flow-runs/data-table/run-name-search.tsx
ui-v2/src/components/flow-runs/data-table/sort-filter.test.tsx
ui-v2/src/components/flow-runs/data-table/sort-filter.tsx
ui-v2/src/components/flow-runs/data-table/state-filter.stories.tsx
ui-v2/src/components/flow-runs/data-table/state-filter.test.tsx
ui-v2/src/components/flow-runs/data-table/state-filter.tsx
ui-v2/src/components/ui/state-badge/index.tsx

Adds filtering components to be used for the flow run data table
https://github.com/user-attachments/assets/264ab0b2-e35b-4522-b047-d426ac28c3c5

[UI v2] feat: Adds flow run data table filter components

---

tests/blocks/test_system.py
tests/cli/deployment/test_deployment_run.py
tests/cli/test_artifact.py
tests/cli/test_deploy.py
tests/cli/test_version.py
tests/conftest.py
tests/test_flows.py
tests/test_logging.py

related to #16910
first PR to remove `pendulum` from `tests`.  i tried and failed once to use broad find/replace, and I got got

consolidate use of `pendulum` in `tests/`: part 1

---

tests/conftest.py

accidentally introduced a static analysis [failure](https://github.com/PrefectHQ/prefect/actions/runs/13397421077/job/37419835054), this fixes it

fix static analysis error

---

client/pyproject.toml

This change ensures the version of `prefect-client` matches the version of `prefect` when building `prefect-client`.

Ignore VCS changes in `prefect-client` version determiniation

---

ui-v2/src/api/flow-runs/index.ts
ui-v2/src/components/flow-runs/data-table/data-table.stories.tsx
ui-v2/src/components/flow-runs/data-table/data-table.tsx
ui-v2/src/components/flow-runs/data-table/deployment-cell.tsx
ui-v2/src/components/flow-runs/data-table/name-cell.tsx

Starts flow runs data table with basic columns. Will incrementally add columns based on original [vue component ](https://github.com/PrefectHQ/prefect-ui-library/blob/main/src/components/FlowRunListItem.vue).
Will also incrementally add server-side filters

[UI v2] feat: Start flow runs data table UX

---

ui-v2/src/components/flow-runs/data-table/data-table.tsx
ui-v2/src/components/flow-runs/data-table/duration-cell.tsx
ui-v2/src/components/flow-runs/data-table/start-time-cell.tsx

1. Adds StartTimeCell to the flow-run data table
2. Updates duration cell to have the same hover effect as `StartTimeCell`
https://github.com/user-attachments/assets/72c074a1-ff87-46b3-8021-5ea436fa2b17

[UI v2] feat: Adds StartTimeCell to flow run data table

---

pyrightconfig-ci.json
src/prefect/_internal/schemas/validators.py
src/prefect/_vendor/croniter/__init__.py
src/prefect/_vendor/croniter/croniter.py
src/prefect/server/schemas/schedules.py

closes #17164 (i think we could create a separate issue for tracking the implementation of a replacement)
removes `croniter` as a dependency given [impending removal of support](https://github.com/corpusops/croniter?tab=readme-ov-file#disclaimer---abandonedunmaintained-code--do-not-use) and adds `src/prefect/_vendor` to the `ignore` section of the `pyright` config

vendor croniter

---

.github/workflows/api-compatibility-tests.yaml
.github/workflows/benchmarks.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/codspeed-benchmarks.yaml
.github/workflows/integration-tests.yaml
.github/workflows/markdown-tests.yaml
.github/workflows/proxy-test.yaml
.github/workflows/python-tests.yaml

the old `paths` had not yet been updated per https://github.com/PrefectHQ/prefect/pull/17116
tldr: `pyproject.toml` should now be used to trigger checks rather than `requirements*.txt`

fix paths in GHAs

---

src/prefect/_experimental/bundles.py
src/prefect/runner/runner.py
tests/runner/test_runner.py

This PR uses the utilities introduced in #17178 to outfit the `Runner` class to kick off and monitor the execution of a bundle. The `Runner` can handle cancellation and crash detection for flow runs initiated via bundle the same as if execution was kicked off by a normally scheduled run.
The `execute_bundle` method duplicates some logic because I want to move the `Runner` control flow towards one where we kick off subprocess via `multiprocessing` rather than `subprocess`. I think that flow is substantially easier to understand and should be possible with the `run_flow_in_subprocess` utility in a later PR.

Add bundle execution capabilities to `Runner`

---

src/integrations/prefect-dask/prefect_dask/task_runners.py
src/integrations/prefect-dask/pyproject.toml
src/integrations/prefect-dask/tests/test_task_runners.py

Prefect 1's `DaskExecutor` had a `performance_report_path` arg that made it straightforward to save out the Dask performance report from a flow run. This PR restores that behavior for `prefect-dask`'s `DaskTaskRunner`.
The only slightly weird thing I ran into was that the `distributed.get_client()` helper does not pick up the task runner's client (` ValueError: No global client found and no address provided`), so I had to add a call to `as_current` to register as the global client...not sure whether it was a deliberate choice to not have our PrefectDaskClient show up as the Dask default (possibly related to #12971?), if it's important to preserve that then I'm not totally sure how else to get `performance_report` to pick up the correct client.

Add performance_report_path arg to DaskTaskRunner

---

ui-v2/src/components/flow-runs/data-table/data-table.stories.tsx
ui-v2/src/components/flow-runs/data-table/data-table.test.tsx
ui-v2/src/components/flow-runs/data-table/data-table.tsx
ui-v2/src/components/flow-runs/data-table/deployment-cell.tsx
ui-v2/src/components/flow-runs/data-table/name-cell.tsx
ui-v2/src/components/flow-runs/data-table/use-delete-flow-runs-dialog.ts

Integrates flow run row deletion to data table
https://github.com/user-attachments/assets/1c667c08-0623-4a97-8a70-7824e980d1ae

[UI v2] feat: Integrate flow run row deletion to data table

---

pyproject.toml

Closes https://github.com/PrefectHQ/prefect/issues/17197

Removes `client` extras and moves them to top level dependencies

---

src/prefect/server/services/cancellation_cleanup.py
tests/server/services/test_cancellation_cleanup.py

closes https://github.com/PrefectHQ/prefect/issues/17080

try improved `cancelled_flow_query `

---

ui-v2/src/components/deployments/deployment-metadata.tsx

Fixed deployment details tags not appearing when tags is empty

[UI v2] fix: Fixed deployment details tags not appearing when tags is empty

---

ui-v2/src/api/flow-runs/use-paginate-flow-runs-with-flows/index.ts
ui-v2/src/api/flow-runs/use-paginate-flow-runs-with-flows/use-paginate-flow-runs-with-flows.test.ts
ui-v2/src/api/flow-runs/use-paginate-flow-runs-with-flows/use-paginate-flow-runs-with-flows.ts

[UI v2] feat: adds query to join flow runs with parent flow
This query is needed for a basic flow runs table (until the APIs get updated to include both `flow_id` and `flow_name`)

[UI v2] feat: adds query to join flow runs with parent flow

---

docs/v3/manage/self-host.mdx
src/prefect/client/orchestration/__init__.py
tests/client/test_prefect_client.py

Clients generally need to be the same version as the server or earlier to accommodate adding new fields to the REST API. This PR adds a warning to the client to alert users if their client is a newer version than the server they are running against and provides the version the user needs to upgrade their server to.
Here's what the warning looks like:
```python
>>> from prefect import flow
>>> @flow
... def my_flow():
...     print("Hello world!")
... 
>>> my_flow()
21:32:29.962 | WARNING | prefect.client - Your Prefect server is running an older version of Prefect than your client which may result in unexpected behavior. Please upgrade your Prefect server from version 3.2.3 to version 3.2.6 or higher.
21:32:30.035 | INFO    | Flow run 'daffodil-jackdaw' - Beginning flow run …
```

Add warning of potential client/server incompatibilities

---

src/prefect/logging/configuration.py
src/prefect/settings/base.py
tests/test_logging.py
tests/test_settings.py

closes #17152
adds a new (default False) flag to `to_environment_variables` to dump alias keys
also adds type hints for all test cases in `test_logging`

respect aliases when loading custom `logging.yaml`

---

src/prefect/server/database/query_components.py

Closes #17231 
This PR sets the `cache_ok` flag to `True` for our custom `UUIDList` type in the sqlalchemy layer of the server. From the SA docs:
> If the TypeDecorator is not guaranteed to produce the same bind/result behavior and SQL generation every time, this flag should be set to False; otherwise if the class produces the same behavior each time, it may be set to True. See TypeDecorator.cache_ok for further notes on how this works.
I'm still reading a little bit but this class should be fully deterministic, including preserving the order in which values are given, so this should be a strict improvement AFAIK.

Set `cache_ok` flag to true for UUIDList

---

src/prefect/server/services/base.py
tests/server/services/test_service_subsets.py

In the prior work on this (PrefectHQ/prefect#16913) we needed to
maintain an explicit set of modules from which to discover services, and
I missed the modules that include the `EventPersister` and the
`EventLogger` (a debugging-only service).  This meant that under most
circumstances, because the `event_persister` module wasn't imported, we
wouldn't run it in either API or background processes.
Here I'm adding a test that confirms the exact subsets of services we
should run, just to avoid any quiet failures like this.

Brings back `EventPersister` in discovery of background services

---

ui-v2/src/components/deployments/deployment-details-upcoming-tab.tsx
ui-v2/src/components/flow-runs/flow-runs-list/flow-run-card.tsx
ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-filters.tsx
ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-filters/run-name-search.tsx
ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-filters/sort-filter.constants.ts
ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-filters/sort-filter.test.tsx
ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-filters/sort-filter.tsx
ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-filters/state-filter.stories.tsx
ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-filters/state-filter.test.tsx
ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-filters/state-filter.tsx
ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-filters/state-filters.constants.ts
ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-list.stories.tsx
ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-list.tsx
ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-pagination.tsx
ui-v2/src/components/flow-runs/flow-runs-list/flow-runs-row-count.tsx
ui-v2/src/components/flow-runs/flow-runs-list/index.ts
ui-v2/src/components/flow-runs/flow-runs-list/types.ts
ui-v2/src/components/flow-runs/flow-runs-list/use-delete-flow-runs-dialog.ts

Start transition flow runs list form data table to cards
After discussion to use a card UX instead, this PR starts the transition to use cards. Future PRs will slowly build up the cards.
This PR copies over pagination features over from the data table UX
https://github.com/user-attachments/assets/d1216c5b-f2bc-43d5-b5a2-063be39e22ce

[UI v2] feat: Start transition flow runs list form data table to cards

---

src/prefect/_waiters.py
src/prefect/flow_runs.py
src/prefect/futures.py
tests/test_flow_runs.py
tests/test_futures.py
tests/test_waiters.py

This PR adds a `PrefectFuture` implementation for tracking flow run execution that works similarly to the `PrefectDistributedFuture` for task runs. To support the operation of the new `PrefectFlowRunFuture`, this PR also adds a `FlowRunWaiter` to monitor the execution of flow runs via events.
To make the inheritance hierarchy of `PrefectFuture` make a little more sense, I also added a  `PrefectTaskRunFuture` class to hold some of the implementations that were on `PrefectFuture` so that `PrefectFuture` can be purely an interface and not a Frankenstein class. The implementations on `PrefectFutrue` have been deprecated and should be removed in a later release. This should only affect users that might be subclassing `PrefectFuture`.
This new future type will be used to track flow runs …

Add `PrefectFuture` implementation for flow runs

---

pyproject.toml
src/prefect/_experimental/bundles.py
tests/experimental/test_bundles.py
tests/runner/test_runner.py

This PR adds `dependencies` to a serialized flow bundle. Dependencies are gathered via `uv pip freeze` and then installed via `uv pip install` before executing the bundle in a subprocess. Because this functionality depends on `uv`, this PR also adds `uv` as a dependency.
Related to #17194

Add handling to propagate dependencies for submitted flow runs

---

src/integrations/prefect-kubernetes/prefect_kubernetes/__init__.py

This PR adds `KubernetesClusterConfig` to the top-level `__init__.py` of `prefect-kubernetes` to ensure it gets pick up by the package entrypoint.

Expose `KubernetesClusterConfig` at the top level of `prefect-kubernetes`

---

ui-v2/src/components/deployments/deployment-details-runs-tab.tsx
ui-v2/src/components/deployments/deployment-details-tabs.tsx

Adds Next run section to run 
https://github.com/user-attachments/assets/37f2a0d3-2409-409b-acda-19362466dd18

[UI v2] feat: Adds Next run section to run tab

---

src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/tests/test_worker.py
src/prefect/_experimental/bundles.py
src/prefect/workers/base.py
tests/experimental/test_bundles.py
tests/workers/test_base_worker.py
tests/workers/test_process_worker.py

This PR adds an experimental `.submit` method to the `KubernetesWorker` class to allow a flow to be submitted to a Kubernetes cluster. The updates to the work pool API haven't been made yet, so the steps for bundle upload and execution are stored within the work pool's `env` field on the base job template.
Here's an example:
```python
import asyncio
import json
import os
from prefect_kubernetes import KubernetesWorker
UPLOAD_STEP = {
"prefect_aws.experimental.bundles.upload": {
"requires": "prefect-aws==0.5.5",
"bucket": "storage-blocks-test-bucket",
"aws_credentials_block_name": "my-creds",
}
}
EXECUTE_STEP = {
"prefect_aws.experimental.bundles.execute": {
"requires": "prefect-aws==0.5.5",
"bucket": "storage-blocks-test-bucket",
"aws_credentials_block_name": …
```

Add `KuberenetesWorker.submit` for ad-hoc submission to a Kubernetes work pool

---

ui-v2/src/components/ui/alert-dialog.tsx

Missed re-updating `AlertDialog` to fix the dialog animation bug that occured when upgrading to tailwind 4
https://github.com/user-attachments/assets/49353207-39bd-4715-85ad-35ae14d2483c

[UI v2] feat: Re-adds Alert Dialog to get updated shadcn version for tailwind 4 upgrade

---

ui-v2/src/components/deployments/data-table/cells.tsx
ui-v2/src/components/deployments/data-table/data-table.stories.tsx
ui-v2/src/components/deployments/data-table/data-table.test.tsx
ui-v2/src/components/deployments/data-table/index.tsx
ui-v2/src/components/deployments/run-flow-button/run-flow-button.tsx
ui-v2/src/components/deployments/use-quick-run.tsx
ui-v2/src/routes/deployments/index.tsx

1. Consolidates the ability to create a quick run through a re-usable hook
2. Updates `edit`, `duplicate`, and `custom run` options to be links instead.
https://github.com/user-attachments/assets/8d056c5f-42c6-4876-80e3-c5f247f45f2f

[UI v2] feat: Completes action items in deployments data table

---

src/prefect/_experimental/bundles.py
tests/experimental/test_bundles.py

I was running into issues with the `@kubernetes` decorator because `prefect-kubernetes` wasn't available during unpickling. Turns out `subprocess.check_call` won't propagate the current environment variables for you, so the dependencies scooped up using `uv pip freeze` were being installed in the wrong virtual environment. This PR fixes that and I've verified the fix by running it against this branch.

Fix dependency installation for flow submission

---

ui-v2/src/components/work-pools/work-pool-select/index.ts
ui-v2/src/components/work-pools/work-pool-select/work-pool-select.stories.tsx
ui-v2/src/components/work-pools/work-pool-select/work-pool-select.test.tsx
ui-v2/src/components/work-pools/work-pool-select/work-pool-select.tsx

Adds `WorkPoolSelect` component.
This component is used for selecting a Deployment's workpool when editing or duplicating
https://github.com/user-attachments/assets/be286832-54d7-4091-a9b1-729642885798

[UI v2] feat: Adds work-pool-select component

---

src/prefect/cli/cloud/__init__.py
tests/cli/cloud/test_cloud.py

closes #17284 
https://github.com/user-attachments/assets/7a906894-6812-4f74-8f6b-714a7f89af0c
also makes that whole test suite pass pylance strict

fix go back to acct for `prefect cloud login` and `prefect cloud workspace set`

---

ui-v2/src/api/work-queues/index.ts
ui-v2/src/api/work-queues/work-queues.test.ts
ui-v2/src/api/work-queues/work-queues.ts

1. Re-arranges filtering query keys to accommodate filtering by work pool name
2. Adds API to filter work queues, given a work pool name

[UI v2] feat: Adds filter API by for work queues by work pool name

---

ui-v2/src/components/deployments/deployment-details-page.tsx
ui-v2/src/components/flows/flow-link.tsx
ui-v2/src/components/ui/status-badge/index.tsx
ui-v2/src/components/work-pools/work-pool-link.tsx
ui-v2/src/components/work-pools/work-queue-link.tsx
ui-v2/src/routes/deployments/deployment.$id.tsx

Updates deployment details page to have associated work pools and work queues links
https://github.com/user-attachments/assets/2fff416b-4421-4171-a3dd-4ab2173a3e04

[UI v2] feat: Updates deployment details page to have associated work pools and work queues links

---

src/prefect/flows.py
src/prefect/runner/runner.py
src/prefect/server/schemas/actions.py
src/prefect/telemetry/instrumentation.py
src/prefect/workers/base.py
src/prefect/workers/process.py
tests/runner/test_runner.py
tests/workers/test_process_worker.py

This PR updates the `ProcessWorker` to use a `Runner` for flow run execution. This brings the `ProcessWorker` in line with other worker types and allows the `ProcessWorker` to adopt some of the `Runner` enhancements like flow run heartbeats and improved `on_cancellation` and `on_crashed` hook running.
The `ProcessWorker` using a `Runner` also allows the `Runner` to handle cancellation, so the cancellation code and accompanying tests have been removed as part of this PR.
Closes https://github.com/PrefectHQ/prefect/issues/17259
Closes https://github.com/PrefectHQ/prefect/issues/16515
Closes https://github.com/PrefectHQ/prefect/issues/16436

Updates `ProcessWorker` to delegate flow run execution to a `Runner`

---

src/prefect/server/models/deployments.py
tests/server/orchestration/api/test_deployments.py

Closes https://github.com/PrefectHQ/prefect/issues/17227

Refresh session when deleting schedules off a deployment

---

src/prefect/cli/deployment.py
src/prefect/flow_runs.py
tests/test_flow_runs.py

Sort of a precursor to #17228; the current implementation polls for state changes (and logs on each poll, even when the state has not changed). As a half step towards also streaming other events / logs, I wanted to start by just swapping the polling for an event subscriber. The result is almost the same except for de-duping the repeated logs from the same state.
I went back and forth on whether to remove the `poll_interval`/`watch_interval` argument or warn that it's deprecated or just have it do nothing, I'm not sure if you have a specific policy on little CLI changes like that but either seems fine to me.
Before:
```
Creating flow run for deployment 'hello-flow/hello-flow'...
Created flow run 'belligerent-lobster'.
└── UUID: 322266a2-b2df-488f-9d84-6db32230c8a7
└── Parameters: {}
└── …
```

Subscribe to state changes in wait_for_flow_run

---

src/prefect/cli/profile.py
src/prefect/settings/profiles.py
tests/cli/test_profile.py

this was checking for a cloud url first and causing and inappropriate errors
if you happened to switch from a non-cloud profile, it wouldn't throw 🫠 
```python
(venv) engineer in project/fix-pathing λ prefect profile use clean     
⠋ Checking API connectivity...
No Prefect server specified using profile 'clean' - the API will run in ephemeral mode.
(venv) engineer in project/fix-pathing λ prefect profile use dev_server
⠸ Checking API connectivity...
Error authenticating with Prefect Cloud using profile 'dev_server'
```

fix `profile use` switching

---

docs/v3/api-ref/rest-api/server/schema.json
src/prefect/server/api/artifacts.py
src/prefect/server/api/automations.py
src/prefect/server/api/block_capabilities.py
src/prefect/server/api/block_documents.py
src/prefect/server/api/block_schemas.py
src/prefect/server/api/block_types.py
src/prefect/server/api/concurrency_limits.py
src/prefect/server/api/concurrency_limits_v2.py
src/prefect/server/api/deployments.py
src/prefect/server/api/events.py
src/prefect/server/api/flow_run_notification_policies.py
src/prefect/server/api/flow_run_states.py
src/prefect/server/api/flow_runs.py
src/prefect/server/api/flows.py
src/prefect/server/api/logs.py
src/prefect/server/api/task_run_states.py
src/prefect/server/api/task_runs.py
src/prefect/server/api/task_workers.py
src/prefect/server/api/variables.py
src/prefect/server/api/work_queues.py
src/prefect/server/api/workers.py
ui-v2/src/api/prefect.ts

Links from the API docs to the related documentation pages. This helps identify which features each API route represents.
Related to https://linear.app/prefect/issue/PLA-987/add-links-to-documentation-from-the-oss-api-docs

chore(API docs): link to related docs pages

---

ui-v2/biome.json

npm formats these files itself which conflicts with biome. So ignoring these files from biome's formatting.

[ui-v2] Ignore package files in biome formatting

---

src/prefect/_experimental/bundles.py

Adds a fallback to the system `uv` if the Python interface isn't available, which applies to the Conda distribution of `uv`.

Fallback to system `uv` if Python interface isn't available

---

.github/workflows/markdown-tests.yaml
src/integrations/prefect-gcp/prefect_gcp/workers/vertex.py

This appears to be the source of the markdown test failures on `main`. Removing this example because `google-cloud-aiplatform` isn't guaranteed to be installed with a `prefect-gcp` installation.

Remove extra example from Vertex AI worker

---

pyproject.toml
src/prefect/runner/runner.py
src/prefect/workers/process.py
tests/runner/test_runner.py

This PR updates the `Runner` to allow for no limiting of flow runs and updates the `ProcessWorker` to take advantage of this change.

Lift limit on `Runner` used by `ProcessWorker`

---

docs/v3/api-ref/rest-api/server/schema.json
pyproject.toml
src/prefect/server/api/deployments.py
src/prefect/server/api/work_queues.py
src/prefect/server/api/workers.py
src/prefect/server/models/deployments.py
src/prefect/server/models/work_queues.py
ui-v2/src/api/prefect.ts

removes `db_injector` from functions that the deployments endpoints was giving to `BackgroundTasks`
not exactly sure what the offending interaction was, but we want to remove `db_injector` across the board anyways
---
the large diff comes from correctly typing the endpoints with optionals

fix 3.9 specific flakes

---

src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py

We are seeing this issue in production:
```
19:51:49.451 | INFO    | prefect.flow_runs.worker - Job 'testing-pool-94wq5': Pod 'testing-pool-94wq5-n8mbn' has started.
19:51:49.452 | INFO    | prefect.flow_runs.worker - Job 'testing-pool-94wq5': Pod has status 'Pending'.
19:51:49.458 | INFO    | prefect.flow_runs.worker - Job 'testing-pool-94wq5': Pod 'testing-pool-94wq5-n8mbn' has started.
19:51:49.459 | INFO    | prefect.flow_runs.worker - Job 'testing-pool-94wq5': Pod has status 'Failed'.
19:51:50.458 | ERROR   | prefect.flow_runs.worker - Job 'testing-pool-94wq5': Job reached backoff limit.
19:51:50.467 | ERROR   | prefect.flow_runs.worker - An error occurred while monitoring flow run '29ed2ed6-6c92-4c9c-95af-1eba0a35c5c8'. The flow run will not be marked as failed, but an issue may …
```

Check if status.container_status[0] is not None

---

src/integrations/prefect-kubernetes/pyproject.toml

```python
» uv run --with prefect==3.2.7 --with prefect-kubernetes python -c "import prefect_kubernetes"
File "<string>", line 1, in <module>
File "/Users/nate/Library/Caches/uv/archive-v0/nBzMLbYy8B3yWNDaG_Rwg/lib/python3.12/site-packages/prefect_kubernetes/__init__.py", line 8, in <module>
from prefect_kubernetes.worker import KubernetesWorker  # noqa F401
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/nate/Library/Caches/uv/archive-v0/nBzMLbYy8B3yWNDaG_Rwg/lib/python3.12/site-packages/prefect_kubernetes/worker.py", line 156, in <module>
from prefect.futures import PrefectFlowRunFuture
ImportError: cannot import name 'PrefectFlowRunFuture' from 'prefect.futures' (/Users/nate/Library/Caches/uv/archive-v0/nBzMLbYy8B3yWNDaG_Rwg/lib/pyt …
```

bump `prefect-kubernetes`'s dependency on `prefect`

---

src/prefect/server/api/server.py

On startup prefect copies over files from the ui into the ui direcctory. If for any reason the ui files were not writeable, the whole setup will fail. This PR ensures that the copied files are writeable To give a bit more context, I am currently packaging Prefect for nixos. Nix having a little bit of a strict build system, makes sure that the built package has only read-only files. this is to ensure the build is deterministic.
I understand that this might appear as a detail related to nix build system only. I can patch the source when building the nix package, but I thought I would try to contribute the patch. No hard feelings if you are not interested in this patch. Thank you for developping prefect!
closes https://github.com/PrefectHQ/prefect/issues/17337
- If no issue exists and your …

feat: ensure ui files are writeable

---

src/prefect/flows.py
tests/runner/test_runner.py

motivated by the example in #17348 (not directly related to that issue)
in order to avoid 404ing later, we must explicitly set the `work_pool_name` to `None`

warn if `RunnerDeployment` with a `work_pool_name` given to `serve`

---

src/prefect/workers/base.py
tests/workers/test_base_worker.py

I also removed a method from the worker - I personally find the pattern of encapsulating every possible mini-subroutine as a function increases complexity of a codebase.
Closes https://github.com/PrefectHQ/prefect/issues/16213

Cancel runs if the deployment was deleted

---

docs/integrations/prefect-aws/ecs_guide.mdx

Helm isn't relevant in the ECS guide, because the workers will be created using the AWS CLI instead of the Helm `prefect-worker` chart, which is used in Kubernetes.
We'll expand on this with an ECS Terraform example as part of:
- https://github.com/PrefectHQ/examples/issues/11
- https://linear.app/prefect/issue/PLA-1072

chore(docs): remove Helm reference on ECS page

---

src/prefect/events/clients.py
tests/events/client/test_events_client.py

It looks like our events client didn't respect the `PREFECT_API_SSL_CERT_FILE` setting, so this PR adds in the necessary logic

Respect custom cert files in events client

---

ui-v2/src/api/deployments/deployments.test.ts
ui-v2/src/api/deployments/index.ts
ui-v2/src/components/deployments/deployment-form/deployment-form.stories.tsx
ui-v2/src/components/deployments/deployment-form/deployment-form.tsx
ui-v2/src/components/deployments/deployment-form/index.ts
ui-v2/src/components/deployments/deployment-form/use-deployment-form.ts
ui-v2/src/components/deployments/deployment-parameters-table/deployment-parameters-table.tsx
ui-v2/src/routes/deployments/deployment_.$id.duplicate.tsx
ui-v2/src/routes/deployments/deployment_.$id.edit.tsx

Adds deployment duplicate page
1. Adds create deployment API
2. Updates `DeploymentForm` and `useDeploymentForm` to include a `duplicate` mode.
3. Update name field to be a form field, but disabled if it is in `edit` mode
4. Updates `useDeploymentForm` to support editing or duplicating a deployment
https://github.com/user-attachments/assets/399e5ff8-5904-4f71-a682-6391bd27eae6

[UI v2] feat: Adds deployment duplicate page

---

src/prefect/cli/flow_run.py
src/prefect/runner/runner.py
tests/cli/test_flow_run.py
tests/runner/test_runner.py

This PR adds the ability to reschedule flow runs when the `Runner` receives a SIGTERM. This should handle some cases where infrastructure providers will interrupt work while it's still running due to scale-down. 
This opt-in feature can be enabled by setting the environment variable `PREFECT_FLOW_RUN_EXECUTE_SIGTERM_BEHAVIOR` to `reschedule`. Note, this should NOT be used with a `backoffLimit` in Kubernetes (or equivalent in other infrastructure providers) as it will result in duplicate flow runs. It should be safe to use with the default Kubernetes work pool configuration where the `backoffLimit` defaults to `0`.

Add sigterm handling for `prefect flow-run execute`

---

src/integrations/prefect-gcp/prefect_gcp/workers/vertex.py
src/integrations/prefect-gcp/tests/test_vertex_worker.py

Adding two variables to the Vertex AI Worker:  `enable_web_access` and `enable_dashboard_access` which are useful for debugging jobs, these parameters are available today in Vertex AI [CustomJobSpec](https://cloud.google.com/python/docs/reference/aiplatform/latest/google.cloud.aiplatform_v1.types.CustomJobSpec) and closing the loop on [issue #5495](https://github.com/PrefectHQ/prefect/issues/5495). In addition, cleaned up the scheduling parameters logic to make it more readable.
The `VertexAIWorker` in `vertex.py` already allows [passing additional arguments into CustomJobSpec](https://github.com/PrefectHQ/prefect/blob/af502b4497663b65418e2891ea3baf384c338c73/src/integrations/prefect-gcp/prefect_gcp/workers/vertex.py#L520) in the provided job_spec, if they should explicitly defined as …

Add debugging variables to Vertex AI Worker

---

src/prefect/deployments/flow_runs.py

Closes https://github.com/PrefectHQ/prefect/issues/17391
Verified locally:
```python
~/d/P/prefect ❯❯❯ python                             (.venv) fix-over-eager-import ✭ ✱ ◼
Python 3.12.5 (main, Aug 14 2024, 04:32:18) [Clang 18.1.8 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from opentelemetry.instrumentation.utils import is_instrumentation_enabled
ModuleNotFoundError: No module named 'opentelemetry.instrumentation'
>>> from prefect.deployments.flow_runs import run_deployment
>>>
```

Add handling for extra install in `prefect.deployments.flow_runs`

---

src/prefect/client/schemas/actions.py
src/prefect/deployments/runner.py
src/prefect/utilities/annotations.py
tests/runner/test_runner.py
tests/utilities/test_annotations.py

closes #11073
this PR adds a `freeze` annotation type as described in the linked PR. adding a parameterized type (e.g. `freeze[str]`) is not necessary
```python
from prefect.utilities.annotations import freeze
def test_freeze(value: str) -> str:
print(f"value: {value}, type: {type(value)}")
assert isinstance(value, str)
return value
test_freeze.serve(parameters={"value": freeze[str]("test")})
```

add `freeze` annotation

---

src/integrations/prefect-kubernetes/prefect_kubernetes/settings.py
src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/tests/test_worker.py

I'm looking to incorporate the ability to give a secret for the Kubernetes worker to pass down to created jobs into the Kubernetes worker Helm chart, but the value for the secret is currently hard coded. This PR adds a setting to allow customization of the key within the secret for the API key.
Related to https://github.com/PrefectHQ/prefect/issues/17093

Allow specifying the key for an existing Kubernetes worker API key secret

---

docs/v3/api-ref/rest-api/server/schema.json
scripts/generate_oss_openapi_schema.py
src/prefect/server/schemas/actions.py
ui-v2/package.json
ui-v2/src/api/prefect.ts
ui-v2/src/components/deployments/deployment-form/use-deployment-form.ts

Adds `additionalProperties: True` to both properties so that the generated typescript types are not `Record<string, never>`

[ui-v2] Fix types for `parameters` and `job_variables` on `DeploymentCreate`

---

src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/tests/test_worker.py

This PR adds Prefect labels to job pods created for flow runs. This allows us to efficiently watch pods by querying for pods with the `prefect.io/flow-run-id` label.

Add Prefect labels to flow run pods

---

src/prefect/cli/deploy.py

Templating allows one to parametrize deploy commands and so a prompt to harden a specific templated value is never useful
closes https://github.com/PrefectHQ/prefect/issues/17409

Remove unnecessary prompt condition

---

src/prefect/flows.py
tests/test_flows.py
uv.lock

closes #17434
related to #15008
this behavior occurs because `async_dispatch` behaves differently in flow run contexts. I'm not sure that checking for a flow run context directly would be better, either way this will have to be refactored when we have explicit sync/async interfaces for everything + no compat interface

fix improper `await` of `RunnerDeployment`

---

src/prefect/logging/loggers.py
tests/test_logging.py

There was a mismatch between the name of the run loggers and what `disable_run_logger` and its accompanying test were using. This PR fixes the naming and adds additional test coverage.
Closes https://github.com/PrefectHQ/prefect/issues/17442

Fix `disable_run_logger` context manager

---

src/prefect/flows.py
tests/test_flows.py
uv.lock

closes #17446 
fixes condition that was too broadly treating strings containing dots (like semantic versions) as file extensions and stripping them

Fix `serve` deployment name truncation

---

src/prefect/task_engine.py
src/prefect/tasks.py

in preparation for solving #17388
`wait_for` is going to be tricky because we can't put it in the signature of anything that takes `P.args` and `P.kwargs` without it breaking type safety in the same way `submit` and `map` are currently broken

add overloads for `run_task`

---

.github/workflows/k8s-integration-tests.yaml
src/integrations/prefect-kubernetes/integration_tests/pyproject.toml
src/integrations/prefect-kubernetes/integration_tests/src/prefect_kubernetes_integration_tests/conftest.py
src/integrations/prefect-kubernetes/integration_tests/src/prefect_kubernetes_integration_tests/test_events.py
src/integrations/prefect-kubernetes/integration_tests/src/prefect_kubernetes_integration_tests/test_eviction.py
src/integrations/prefect-kubernetes/integration_tests/src/prefect_kubernetes_integration_tests/utils/prefect_core.py

Updates Kubernetes integration test to run in parallel. To support parallel execution, each xdist worker will use its own work pool.

Allow Kubernetes integration tests to run in parallel

---

src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/tests/test_worker.py

Fixes a scenario where the pod is deleted before the container status is available, but the flow run has been rescheduled. Previously, this would incorrectly report the flow run as crashed, but now it will correctly return a 0 exit code. This issue manifested as a flake in the Kubernetes worker integration tests.

Fix race condition in Kubernetes worker

---

docs/mint.json
docs/v3/deploy/infrastructure-concepts/work-pools.mdx
docs/v3/deploy/infrastructure-examples/modal.mdx
docs/v3/deploy/infrastructure-examples/serverless.mdx
docs/v3/get-started/index.mdx

Let's move the Modal tutorial to the same section as the other dynamic infra examples (for example, Coiled).

[Docs] Move Modal tutorial to the Dynamic infrastructure examples section

---

docs/mint.json

I forgot to remove the old entries in the tutorials section, and I missed a redirect for the Helm tutorial too. This fixes both issues.

[Docs] Remove dangling tutorial references

---

.gitignore

There's a `prefect.yaml` file in `.gitignore` which causes the base `prefect.yaml` to not be included in the sdist. This PR explicitly includes the base `prefect.yaml` to make sure it's included in the sdist and wheel.
Closes https://github.com/PrefectHQ/prefect/issues/17377

Ensure base `prefect.yaml` template is included in built package

---

src/integrations/prefect-kubernetes/integration_tests/src/prefect_kubernetes_integration_tests/test_eviction.py
src/integrations/prefect-kubernetes/integration_tests/src/prefect_kubernetes_integration_tests/utils/k8s.py
src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py

This PR adds additional event checks to ensure the operator correctly emits events in eviction scenarios.
This PR also adds handling for a race condition where the worker might mark a flow run as crashed if the pod disappears too soon. To handle that, the worker will check if the flow run has been rescheduled before saying that it should be marked as crashed. This fixes a flake we've been seeing in the integration tests.

Adds checks for events in eviction tests and and handling for race condition

---

ui-v2/src/api/flows/flows.test.ts
ui-v2/src/api/flows/index.ts
ui-v2/src/components/flows/cells.tsx
ui-v2/src/components/flows/columns.tsx
ui-v2/src/components/flows/data-table.tsx
ui-v2/src/components/flows/flows-page-header.tsx
ui-v2/src/components/flows/flows-page.tsx
ui-v2/src/components/flows/table-count-header.tsx
ui-v2/src/components/ui/docs-link/constants.ts
ui-v2/src/routes/flows/index.tsx

finished up flows page and aligned its styling to be closer to existing OSS implementation

[UI-v2] feat: finish flows page

---

ui-v2/src/components/artifacts/artifact/artifact-detail-page.test.tsx
ui-v2/src/components/artifacts/artifact/detail-table.tsx

This PR adds the correct table components for the artifact table component. This PR also updates the test to use `screen` queries instead of render based on the updated [docs](https://testing-library.com/docs/queries/about/)
Was getting an error in tests and console saying:
```
stderr | src/components/artifacts/artifact/artifact-detail-page.test.tsx > ArtifactDetailPage > renders artifact detail for table with data
In HTML, <th> cannot be a child of <thead>.
This will cause a hydration error.
...
<SafeFragment fallback={null}>
<SafeFragment getResetKey={function getResetKey} errorComponent={function ErrorComponent} ...>
<SafeFragment fallback={function fallback}>
<MatchInnerImpl matchId="__root__">
<component>
<ArtifactDetailPage artifact={{id:"3cf11a...", ...}}>
<div> …
```

[UI v2] fix: Fixes Artifacts table hydration warnings

---

src/prefect/server/schemas/responses.py
tests/server/orchestration/api/test_task_runs.py

updates https://github.com/PrefectHQ/prefect/pull/17407 typing in new tests and removes (seemingly) unnecessary override of `model_validate`

small updates to #17407

---

ui-v2/src/components/blocks/block-document-action-menu/block-document-action-menu.stories.tsx
ui-v2/src/components/blocks/block-document-action-menu/block-document-action-menu.test.tsx
ui-v2/src/components/blocks/block-document-action-menu/block-document-action-menu.tsx
ui-v2/src/components/blocks/block-document-action-menu/index.ts

Adds BlockDocumentActionMenu component.
This component is used for the `/blocks` and `/blocks/block/$id` routes
https://github.com/user-attachments/assets/19f7ea42-581b-4316-a4d6-dcff18478888

[UI v2] feat: Adds BlockDocumentActionMenu component

---

src/prefect/flow_engine.py
src/prefect/flow_runs.py

Closes https://github.com/PrefectHQ/prefect/issues/17264
The log _itself_ is pure INFO, regardless of the state that the run is ending it; whether or not a problem occurred should be logged accordingly at other places of the engine.

Only log at INFO level for final state

---

src/integrations/prefect-kubernetes/integration_tests/src/prefect_kubernetes_integration_tests/test_filtering.py
src/integrations/prefect-kubernetes/prefect_kubernetes/observer.py
src/integrations/prefect-kubernetes/prefect_kubernetes/settings.py
src/integrations/prefect-kubernetes/tests/test_settings.py
src/integrations/prefect-kubernetes/tests/test_worker.py

Add a `KubernetesObserverSettings` object to allow configuration of the namespaces the observer watches and additional labels to filter on.
The namespaces the observer watches can be set with the `PREFECT_INTEGRATIONS_KUBERNETES_OBSERVER_NAMESPACES` environment variable like this:
```bash
export PREFECT_INTEGRATIONS_KUBERNETES_OBSERVER_NAMESPACES="default,another-one"
```
and additional labels to filter on can be set like this:
```bash
export PREFECT_INTEGRATIONS_KUBERNETES_OBSERVER_ADDITIONAL_LABEL_FILTERS="prefect.io/deployment-id=not-a-real-deployment-id,prefect.io/deployment-id=also-not-a-real-deployment-id"
```
Both these settings can be used to assign observers to specific domains if multiple observers are running in the same cluster.

Add settings to control observer behavior

---

docs/v3/develop/settings-ref.mdx
schemas/settings.schema.json
src/prefect/settings/models/tasks.py
src/prefect/tasks.py
tests/test_settings.py
tests/test_tasks.py

Adds a new setting that, when enabled, will set the default cache policy on tasks to `NO_CACHE`. Note that this _can_ be overwritten by explicitly providing a cache policy or cache key function so this is **not** equivalent to a full disabling of caching behavior.
Closes https://github.com/PrefectHQ/prefect/issues/17369

Adds new setting `PREFECT_TASKS_DEFAULT_NO_CACHE` to not cache by default

---

src/prefect/results.py
src/prefect/transactions.py
tests/test_transactions.py

Fix flow transaction idempotency by replacing `NullFileSystem` with `None` in the `transaction` ctx manager. This ensures `transaction.is_committed()` correctly detects previously committed files, even when a flow's `ResultStore` uses `NullFileSystem` for metadata storage.

avoid inheriting `NullFilesystem` for transaction metadata storage

---

src/prefect/workers/base.py

Closes #17536 
When workers try to submit a scheduled flow run if its corresponding deployment somehow got deleted, workers will mark the flow run as cancelled.
However, the current implementation is getting an error leading to failure in marking the flow run as canceled. This then leads to to crashed worker in an **infinite loop**.

fix(flow-run): ensure state is consistent when cancelling

---

flows/multiprocessing_flow.py
src/prefect/deployments/runner.py
src/prefect/utilities/importtools.py
tests/runner/test_runner.py
tests/utilities/test_importtools.py

This PR attempts to close various issues related to the `__prefect_loader_` module mechanic by not using random module names but instead using the file name itself, while also preserving the `sys.path` and `sys.module` manipulations. This ensures that these paths and objects loaded from the file can be more robustly pickled and unpickled.
Closes https://github.com/PrefectHQ/prefect/issues/9329 
Closes https://github.com/PrefectHQ/prefect/issues/5984
Closes https://github.com/PrefectHQ/prefect/issues/17150
Closes https://github.com/PrefectHQ/prefect/issues/9542
Closes https://github.com/PrefectHQ/prefect/issues/6762
Closes https://github.com/PrefectHQ/prefect/issues/17449
I am not sure if I am backtracking on other issues with this change, so want to be mindful of looking into that before …

Don't pop the loader module

---

docs/v3/api-ref/rest-api/server/schema.json
src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/tests/test_worker.py
src/prefect/client/orchestration/_flow_runs/client.py
src/prefect/client/schemas/actions.py
src/prefect/server/api/flow_runs.py
src/prefect/server/schemas/actions.py
tests/server/orchestration/api/test_flow_runs.py
ui-v2/src/api/prefect.ts

This PR adds work_pool_name, work_queue_name, and job_variables fields to the create flow run endpoint.
The client is also updated to use the API updates when submitting ad-hoc flow run to remote infrastructure via a worker. The worker will use the base job template from an existing work pool when spinning up infra, so defining the work pool/queue will mark those flow runs as having run in that work pool. The job variables will store the custom command necessary to execute the submitted flow runs. Neither change is strictly necessary, but they enable infrastructure-level retries for submitted flow runs.
Related to #17194

Persist work pool and job variables for submitted ad-hoc flow runs

---

src/prefect/server/models/flow_runs.py
tests/server/orchestration/api/test_flow_run_graph_v2.py

I ran into this when trying to reproduce another issue - it seems like something changed in the UI that began sending naive strings instead of timezone-aware strings? Either way this makes the known problematic endpoint more robust to inputs.
Closes #16487
Closes https://github.com/PrefectHQ/prefect/issues/17225

Convert strings to timezone-aware datetimes in the flow run graph API

---

src/prefect/cli/work_pool.py
tests/cli/test_work_pool.py

This PR adds an experimental CLI to configure storage for a work pool. Currently, only AWS S3 is supported and the CLI will only configure bundle storage for ad-hoc flow submission. If this works well, both those aspects can be expanded in later PRs.
Example:
```
❯❯❯ prefect work-pool storage configure s3 olympic \
--bucket storage-blocks-test-bucket \
--aws-credentials-block-name my-creds
Configured S3 storage for work pool 'olympic'
❯❯❯ prefect work-pool storage inspect olympic                                                                                  
╭───────────── Storage Configuration for olympic ─────────────╮
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
│ ┃ Setting                    ┃ Value                      ┃ │
│ …
```

Add experimental CLI for configuring work pool storage

---

src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/tests/test_worker.py

closes https://github.com/PrefectHQ/prefect/issues/17406
opted for handling this in the k8s worker directly instead of the base worker because this seems specific to the k8s worker
---
while mulling over https://github.com/PrefectHQ/prefect/pull/17512#discussion_r2001882300, I'm thinking that there might be some `RootModel`-ish stuff we want to do on `BaseJobConfiguration` to standardize initialization, validation and mutation of `self.env` since it would be on every subclass, but in the interest of this fix I think that could be in another PR.

fix kubernetes job variables merge logic

---

src/integrations/prefect-docker/prefect_docker/worker.py
src/integrations/prefect-docker/tests/test_worker.py

We are running prefect open source, executing a growing number of containers on a Linux host.
We started occasionally seeing the create_container() command timing out with the python docker clients default timeout of 60 seconds.
While this is it's own problem which we are tackling, short term we did not find any way of bumping the timeout within docker or prefect.
This PR adds basic integration to allow controlling the timeout via the standard `DOCKER_CLIENT_TIMEOUT` variable.
closes https://github.com/PrefectHQ/prefect/issues/17553
- ~~[ ] If this pull request removes docs files, it includes redirect settings in `mint.json`.~~
- ~~[ ] If this …

fix: Pass DOCKER_CLIENT_TIMEOUT to the worker docker client

---

src/integrations/prefect-aws/prefect_aws/experimental/bundles/execute.py
src/integrations/prefect-aws/prefect_aws/experimental/bundles/upload.py
src/integrations/prefect-kubernetes/prefect_kubernetes/experimental/decorators.py
src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/tests/experimental/test_decorator.py
src/integrations/prefect-kubernetes/tests/test_worker.py
src/prefect/_experimental/bundles.py
src/prefect/workers/base.py

This PR improves the error messages produced when an ad-hoc flow submitted to remote infrastructure fails. The main improvements come from:
- Ensuring exceptions don't get wrapped in an exception group by `anyio`
- Updating bundle steps to print nice error messages to `stderr` on failure
With this PR, you'll get an error message like this is the bundle upload to S3 fails:
`
RuntimeError: Failed to upload bundle to S3 (S3UploadFailedError): Failed to upload 013aa438-9aa5-4a55-a6d5-eedef0eebbf2 to storage-blocks-test-bucket/013aa438-9aa5-4a55-a6d5-eedef0eebbf2: An error occurred (InvalidToken) when calling the PutObject operation: The provided token is malformed or otherwise invalid.
`
Related to #17194

Improve ad-hoc infrastructure submission error handling

---

src/integrations/prefect-aws/prefect_aws/workers/ecs_worker.py
src/integrations/prefect-aws/tests/workers/test_ecs_worker.py

When a task definition arn is included in an ECS work pool's job variables, any value that would be used to construct a task definition is ignored since a task definition doesn't need to be constructed. Updates a warning log that calls this out more explicitly.
Sample logs
```bash
19:02:28.089 | WARNING | prefect.flow_runs.worker - Skipping task definition construction since a task definition ARN is provided.
19:02:28.091 | WARNING | prefect.flow_runs.worker - The following job variable references in the task definition template will be ignored: cpu, execution_role_arn, memory, image, container_name, family
```

Log ignored template variables when a task definition arn is supplied to the ECS worker

---

pyproject.toml

closes #17579 
see https://github.com/python/typing_extensions/releases/tag/4.10.0

bump `typing-extensions` lower bound

---

docs/v3/deploy/infrastructure-examples/modal.mdx

not sure if this was always here or was changed at some point but it should be `prefect cloud login`

fix: cli login command in modal docs

---

src/integrations/prefect-docker/prefect_docker/deployments/steps.py
src/integrations/prefect-docker/tests/deployments/test_steps.py
tests/cli/test_deploy.py

closes https://github.com/PrefectHQ/prefect/issues/17604
focusing on type annotations, cache improvements, and the handling of Docker image namespaces. Additionally, new tests have been added to ensure these changes work as expected.
* Added type annotations to functions and variables in `src/integrations/prefect-docker/prefect_docker/deployments/steps.py` to improve code clarity and type checking. [[1]](diffhunk://#diff-3f40bcfdb088269ff630005eab5d7b9f51ebf44937ac6317c65517c1b14b497fR26-R55) [[2]](diffhunk://#diff-3f40bcfdb088269ff630005eab5d7b9f51ebf44937ac6317c65517c1b14b497fL88-R104) [[3]](diffhunk://#diff-3f40bcfdb088269ff630005eab5d7b9f51ebf44937ac6317c65517c1b14b497fL120-R129)
* Updated `STEP_OUTPUT_CACHE` to use a more specific type annotation for better type safety.
* Introduced …

respect default namespace for docker `prefect.yaml` steps

---

.github/workflows/static-analysis.yaml
pyproject.toml
src/prefect/cache_policies.py
tests/test_cache_policies.py
uv.lock

This PR introduces a new pattern for the `Inputs` cache policy: all inputs to the task are first checked against a dictionary of types. This dictionary optionally contains "stabilizing transformations" of the input type that ensure `cloudpickle` produces the same byte string on repeated invocations (which doesn't always happen for certain unordered objects).
If this pattern becomes valuable in other ways, we may consider exposing a `type_handler` interface to users that allows them to register their own custom type handling logic, but for now the interface remains private.
Closes https://github.com/PrefectHQ/prefect/issues/17547

Stable cache keys for pandas

---

src/prefect/workers/base.py

Fixes #17627 
The issue is occurring in the way kwargs are being passed.
1. In `mark_flow_run_as_cancelled()`, we set `state_updates.setdefault("type", StateType.CANCELLED)`
2. Then we call `Cancelled(**state_updates)`
3. Inside `Cancelled()`, we call `_traced(cls, type=StateType.CANCELLED, **kwargs)`
4. The problem is that `kwargs` already contains "type" from `state_updates`, and we're also explicitly passing `type=StateType.CANCELLED`
This causes a duplicate key situation. When Python expands `**kwargs` in the function call, it would result in something like:
```python
_traced(cls, type=StateType.CANCELLED, type=state_updates["type"], ...)
```
Having the type parameter twice is causing the `KeyError`. …

Fix `mark_flow_run_as_cancelled` in worker still gets error

---

src/prefect/tasks.py
tests/test_task_engine.py

related to https://github.com/PrefectHQ/prefect/issues/17637

explicitly disallow async rollback hooks until supported

---

docs/docs.json

Reintroduces `settings-ref` location change from #17590 - the change in #17591 reverted the location and was causing redirects to the documentation's intro page.

fix broken link in docs for settings ref

---

docs/v3/api-ref/rest-api/server/schema.json
src/integrations/prefect-aws/prefect_aws/deployments/steps.py
src/integrations/prefect-dask/prefect_dask/task_runners.py
src/integrations/prefect-gcp/prefect_gcp/deployments/steps.py
src/integrations/prefect-ray/prefect_ray/task_runners.py
src/prefect/cli/deploy.py
src/prefect/client/orchestration/_concurrency_limits/client.py
src/prefect/client/schemas/objects.py
src/prefect/concurrency/_asyncio.py
src/prefect/concurrency/asyncio.py
src/prefect/concurrency/services.py
src/prefect/concurrency/sync.py
src/prefect/flow_engine.py
src/prefect/futures.py
src/prefect/server/api/concurrency_limits_v2.py
src/prefect/server/models/concurrency_limits_v2.py
src/prefect/states.py
src/prefect/utilities/dockerutils.py
src/prefect/utilities/engine.py
tests/cli/test_deploy.py
tests/concurrency/test_acquire_concurrency_slots.py
tests/concurrency/test_concurrency_asyncio.py
tests/concurrency/test_concurrency_slot_acquisition_service.py
tests/concurrency/test_concurrency_sync.py
tests/concurrency/v1/test_increment_concurrency_limits.py
tests/results/test_result_fetch.py
tests/server/models/test_concurrency_limits_v2.py
tests/server/orchestration/api/test_concurrency_limits_v2.py
ui-v2/src/api/prefect.ts

In preparation for the upcoming 3.3.0 release this PR removes
- The `fetch` parameter from `State.result`. To maintain similar behavior, a `State.aresult` method has been added and `State.result` has been decorated with `@async_compatible`.
- The `create_if_missing` parameter from `concurrency` and `aconcurrency`. The corresponding field in the concurrency v2 API is still present but deprecated and will not be respected.
- The `-v/--variable` flag from the `prefect deploy` CLI.
- Several old deployment step names and types from `prefect-aws` and `prefect-gcp`.

Remove code past its marked deprecation date

---

docs/integrations/prefect-gcp/index.mdx

fixes a redirect to the getting started guide happening due to a faulty link

docs(gcp): fix google cloud run worker guide link

---

src/prefect/server/api/server.py

The self hosted version requires ui files copied over to be writeable not only readable, this was a small omission in changing the file permissions in the original PR. The writeable comes from the use of rmtree.
small omission in the original PR https://github.com/PrefectHQ/prefect/pull/17336
closes #17645 

fix: ui files permissions for self-hosted

---

src/integrations/prefect-dask/prefect_dask/task_runners.py
src/integrations/prefect-dask/pyproject.toml
src/integrations/prefect-dask/tests/test_task_runners.py

This PR adds a `client` property to `DaskTaskRunner` that will perform any necessary connection logic when called for the first time. This will prevent unnecessary creation of Dask clients for tasks submitted to a Dask cluster.
Closes https://github.com/PrefectHQ/prefect/issues/17618

Update `DaskTaskRunner` to lazily load the Dask client

---

src/prefect/_internal/concurrency/calls.py

It seems that in rare circumstances we trigger an unhandled edge case (at least in tests, example [here](https://github.com/PrefectHQ/prefect/actions/runs/14145853194/job/39633057783?pr=17644)).
In an effort to hopefully make tests more resilient, this PR adds handling for this edge case.

Add logic to handle cancel_scope None

---

client/client_flow.py
client/pyproject.toml
src/prefect/_internal/compatibility/deprecated.py
src/prefect/types/_datetime.py
tests/_internal/compatibility/test_deprecated.py

this behavior from `dateparser` that we support will be removed in python 3.15 according to the warning I suppress here

temporarily allow `str` or `datetime` for `generate_deprecation_message`

---

docs/v3/api-ref/rest-api/server/schema.json
src/integrations/prefect-dbt/prefect_dbt/cli/configs/base.py
src/prefect/_internal/schemas/bases.py
src/prefect/blocks/core.py
src/prefect/client/schemas/objects.py
src/prefect/events/filters.py
src/prefect/server/events/filters.py
src/prefect/server/utilities/schemas/bases.py
src/prefect/settings/base.py

pydantic 2.11 started throwing all these deprecation warnings about `self.model_fields`

update `self.model_fields` -> `type(self).model_fields`

---

src/prefect/schedules.py
tests/test_schedules.py

This update also matches the default for other schedule models and matches the docstrings in `prefect.schedules`.
Closes https://github.com/PrefectHQ/prefect/issues/17672

Update `Cron` `day_or` default to match `croniter` default

---

src/prefect/client/schemas/objects.py
src/prefect/client/schemas/responses.py
src/prefect/events/related.py
src/prefect/runner/runner.py
tests/events/client/instrumentation/test_events_workers_instrumentation.py
tests/runner/test_runner.py

If the server provides the new versioning fields on `Deployment`, use
them when emitting events in the context of a flow run or runner.

Includes `Deployment` versioning info in flow run execution event

---

docs/docs.json
docs/v3/api-ref/rest-api/server/schema.json
docs/v3/api-ref/rest-api/server/task-runs/read-task-run-1.mdx
docs/v3/api-ref/rest-api/server/task-runs/read-task-run-with-flow-run-name.mdx
src/prefect/server/api/ui/task_runs.py
src/prefect/server/models/task_runs.py
src/prefect/server/schemas/__init__.py
src/prefect/server/schemas/ui.py
tests/conftest.py
tests/fixtures/database.py
tests/server/orchestration/api/test_artifacts.py
tests/server/orchestration/api/ui/test_task_runs.py
tests/server/orchestration/test_flow_run_instrumentation_policies.py
ui-v2/src/api/prefect.ts

Adds a `/ui/task_runs/$id` route to include the name of the corresponding flow run when retrieving details about a task run. This will reduce the number of calls the UI needs to make when displaying task run details.

Add UI-specific route for task run details

---

.pre-commit-config.yaml
ui-v2/package-lock.json
ui-v2/package.json
ui-v2/src/api/logs/index.ts
ui-v2/src/components/task-runs/task-run-logs/index.tsx
ui-v2/src/components/task-runs/task-run-logs/task-run-logs.stories.tsx
ui-v2/src/components/task-runs/task-run-logs/task-run-logs.test.tsx
ui-v2/src/components/ui/run-logs/index.tsx
ui-v2/src/components/ui/run-logs/run-logs.stories.tsx
ui-v2/src/components/ui/run-logs/run-logs.test.tsx

This PR adds virtualization to the `RunsLogs` component via [`@tanstack/react-virtual`](http://tanstack.com/virtual/latest/docs/introduction), which ensures responsible memory usage for runs with lots of flow. I also added an `onBottomReached` callback for `RunLogs` which is used to query for more logs if they are available.
I removed the UI lint pre-commit hook because it's just too darn slow. We'll still lint in CI, but commits should be faster now.

Add virtualization to `RunLogs` component

---

ui-v2/src/components/task-runs/task-run-logs/task-run-logs.test.tsx

https://github.com/PrefectHQ/prefect/pull/17688 seems to have broken a test
The test "displays logs with default filter (all levels)" appeared to be failing because it tried to verify the presence of all log messages in the DOM simultaneously. However, since the component uses virtualization, only a subset of logs are rendered at any time.
This PR updates the test to:
1. Verify at least one log is rendered in the DOM
2. Verify the underlying data contains logs of all levels

fix task run logs test

---

docs/v3/api-ref/rest-api/server/schema.json
src/prefect/server/api/flow_runs.py
tests/server/orchestration/api/test_flow_run_graph_v2.py

Closes https://github.com/PrefectHQ/prefect/issues/17729

Include timezone in default `since` value for flow run graph v2 endpoint

---

ui-v2/src/api/task-runs/index.ts
ui-v2/src/api/task-runs/task-runs.test.ts
ui-v2/src/components/task-runs/task-run-details-page/index.tsx
ui-v2/src/components/task-runs/task-run-details-page/task-run-details-page.test.tsx
ui-v2/tests/utils/handlers.ts

- Add an action menu to the task run details page
- Add a delete action to the action menu
- Add a copy ID action to the action menu
https://github.com/user-attachments/assets/3e2778c7-050a-40b7-8a69-eebfd8d04b11

[UI v2] Add actions to task run details page

---

ui-v2/src/components/task-runs/task-run-details-page/index.tsx
ui-v2/src/components/task-runs/task-run-details-page/task-run-details-page.test.tsx
ui-v2/src/mocks/mock-json-input.tsx
ui-v2/src/mocks/mock-use-debounce.ts
ui-v2/tests/variables/variables.test.tsx

I also moved the `JsonInput` and `use-debounce` mocks for easier reuse.

Add task inputs display to task run details page

---

ui-v2/src/components/automations/use-delete-automation-confirmation-dialog.ts
ui-v2/src/components/blocks/blocks-row-count/blocks-row-count.test.tsx
ui-v2/src/components/blocks/use-delete-block-document-confirmation-dialog.ts
ui-v2/src/components/concurrency/task-run-concurrency-limits/task-run-concurrency-limit-page/task-run-concurrency-limit-dialog.tsx
ui-v2/src/components/deployments/use-delete-deployment-confirmation-dialog.ts

At some point `getRouteApi` was updated to work with a route that is relative to the path being passed.
This broke the `useNavigate` mechanism because these re-usable hooks are referencing an incorrect relative path.
Update `useNavigate` to **not** use `getRouteApi`, and default to use absolute pathing

[UI v2] fix: Fixed navigation upon deletions

---

src/prefect/runner/runner.py

According to the implementation of self._runs_task_group.start the return type might be an `anyio.abc.Process` or an `Exception`, as defined in [execute_flow_run](https://github.com/PrefectHQ/prefect/blob/990e781d79dd40250b7324619186988c39b546b9/src/prefect/runner/runner.py#L591), closes #17621

Fix readiness_result type to match expected Process type

---

ui-v2/package-lock.json
ui-v2/package.json
ui-v2/src/components/artifacts/artifact/artifact-raw-data-display.stories.tsx
ui-v2/src/components/artifacts/artifact/artifact-raw-data-display.test.tsx
ui-v2/src/components/artifacts/artifact/artifact-raw-data-display.tsx

Removes `react-code-blocks` and replaces its use with Code Mirror to resolve this security issue: https://github.com/PrefectHQ/prefect/security/dependabot/94.

Remove `react-code-blocks` dependency

---

.pre-commit-config.yaml

if you run the pre-commits locally with 3.12 for example, it will pass and then fail in CI

avoid unexpected pre-commit diffs from local to CI

---

src/integrations/prefect-gcp/prefect_gcp/deployments/steps.py
src/integrations/prefect-gcp/prefect_gcp/experimental/bundles/__init__.py
src/integrations/prefect-gcp/prefect_gcp/experimental/bundles/execute.py
src/integrations/prefect-gcp/prefect_gcp/experimental/bundles/upload.py
src/integrations/prefect-gcp/tests/conftest.py
src/integrations/prefect-gcp/tests/experimental/bundles/test_execute.py
src/integrations/prefect-gcp/tests/experimental/bundles/test_upload.py

Adds bundle upload and execution steps for Google Cloud Storage. Similar to the S3 versions, these can be executed via a CLI command and will be used in work pool storage configuration.

Add GCS bundle upload and execute steps

---

docs/v3/api-ref/settings-ref.mdx
schemas/settings.schema.json
src/prefect/server/services/scheduler.py
src/prefect/settings/models/server/services.py
tests/server/services/test_scheduler.py
tests/test_settings.py

closes #17696 
Here we add a specific setting for `RecentDeploymentsScheduler`'s loop interval while recognizing that both this and the PREFECT_LOGGING_* settings that don't necessarily need to be defined on the settings object, and rather can be derived from existing loop services and the `logging.yml` file respectively.
so we could potentially refactor (many) existing explicit loop service interval settings to be dynamic while remaining first class settings

allow configuring `RecentDeploymentScheduler` loop interval

---

src/prefect/runner/server.py
src/prefect/runner/submit.py
tests/runner/test_runner.py
tests/runner/test_submit.py
tests/runner/test_webserver.py

related to https://github.com/PrefectHQ/prefect/issues/15733
these were (unfortunately) added to the public API because experimental flags were removed. the outcomes are better reached via background tasks or using `run_deployment` in conjunction with `.serve` / `.deploy`
In addition, there are security issues with the runner webserver, as anyone with network access could bypass RBAC and create runs.
all "public" methods in the following modules will be slated for removal in October 2025:
- `prefect.runner.submit`
- `prefect.runner.server`
---
> "I was using the runner webserver, what should I use instead?"
- background tasks
- [docs](https://docs.prefect.io/v3/develop/deferred-tasks)
- [example](https://github.com/PrefectHQ/examples/tree/main/apps/background-tasks)
- `serve` many flows …

deprecate runner webserver machinery

---

pyproject.toml

Some deployment platforms like Railway won't copy `.git` folder within build context, hence it is impossible for `versioningit` to determine a version without first fetching the repo's tags
```
RuntimeError: Error getting the version from source `versioningit`: NotSdistError: /opt/prefect does not contain a PKG-INFO file
versioningit could not find a version for the project in /opt/prefect!
You may be installing from a shallow clone, in which case you need to unshallow it first.
Alternatively, you may be installing from a Git archive, which is not supported by default.  Install from a git+https://... URL instead.
```
More context in this [Discord thread](https://discord.com/channels/713503345364697088/1359959718386339840/1359959718386339840)

chore: tool.versioningit.default-version

---

docs/docs.json
docs/v3/deploy/static-infrastructure-examples/background-tasks.mdx
docs/v3/develop/deferred-tasks.mdx

revamps concept doc for background tasks and adds a static infra example guide based on https://github.com/PrefectHQ/examples/pull/20, which I should merge first so that I can link it from here (instead of the PR)
note i am intentionally using `marvin` as a means of illustrating
- dealing with dependencies in similar setups
- dealing with injecting an application critical env var (`OPENAI_API_KEY`)

update background tasks docs and add guide

---

src/prefect/events/clients.py
src/prefect/server/utilities/subscriptions.py
tests/events/client/test_events_client.py

closes https://github.com/PrefectHQ/prefect/issues/17687
Addresses an issue where `PREFECT_SERVER_API_AUTH_STRING` did not enforce authentication for the WebSocket event stream (`/events/out`). Clients (e.g., `prefect events stream`) could connect without a valid `PREFECT_API_AUTH_STRING`.
**notable changes**
1.  **Server (`accept_prefect_socket`):** Verifies the received WebSocket auth `token` against `PREFECT_SERVER_API_AUTH_STRING` (if set), rejecting invalid/missing tokens. Includes associated logging.
2.  **Client (`PrefectEventSubscriber`):** Reads `PREFECT_API_AUTH_STRING` and correctly sends it as the `token` for self-hosted connections.
3.  **Test (`test_events_subscriber_auth_string`):** Added test using the `puppeteer` fixture to verify client behavior (token sending) and …

respect auth for websockets

---

src/integrations/prefect-azure/prefect_azure/credentials.py
src/integrations/prefect-azure/prefect_azure/experimental/bundles/__init__.py
src/integrations/prefect-azure/prefect_azure/experimental/bundles/execute.py
src/integrations/prefect-azure/prefect_azure/experimental/bundles/upload.py
src/integrations/prefect-azure/tests/experimental/bundles/test_execute.py
src/integrations/prefect-azure/tests/experimental/bundles/test_upload.py

Adds bundle upload and execution steps for Azure blob storage. Similar to the S3 versions, these can be executed via a CLI command and will be used in work pool storage configuration. One unique aspect of these steps is that they require a credentials block name since Azure always requires an account URL.

Add experimental bundle steps for Azure Blob Storage

---

src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/prefect/workers/base.py
tests/workers/test_base_worker.py

Adding the `.submit` method to `BaseWorker` class will allow all workers to offer ad-hoc flow submission. Once this change is released, the `.submit` method can be removed from the `KubernetesWorker`.

Add `.submit` method to `BaseWorker`

---

.pre-commit-config.yaml
scripts/run_precommit_generation_scripts.py

the pre-commit was using `uv run -p 3.9 ...` for 3 consecutive pre-commit hooks, which would
- use the invoking user's venv iff it was a 3.9 venv
- otherwise destroy the existing venv and create a new 3.9 one
so if you had a 3.13 venv and then ran pre-commits, after running them you have 3.9
the solution here is `--isolated`, but doing that 3 times consecutively is annoyingly slow, so this PR consolidates the scripts (that use the same deps) into the same hook and makes sure it doesnt interact with the user's venv

Avoid clobbering dev venv

---

src/integrations/prefect-gcp/prefect_gcp/workers/vertex.py
src/integrations/prefect-gcp/tests/test_vertex_worker.py

Handles cases where `Scheduling` job variable is `None`.

Fix null `Scheduling` case in Vertex worker

---

src/integrations/prefect-kubernetes/prefect_kubernetes/experimental/decorators.py
src/prefect/_experimental/bundles.py
src/prefect/flows.py
src/prefect/runner/runner.py
src/prefect/workers/base.py
src/prefect/workers/process.py
tests/test_infrastructure_bound_flow.py

The PR adds the `InfrastructureBoundFlow` class, first explored in `prefect-kubernetes`, to `prefect` to support binding flows to infrastructure. Calls of `InfrastructureBoundFlow` will spin up infrastructure and submit the flow using the configured worker provided when the `InfrastructureBoundFlow` was created. The `bind_flow_to_infrastructure` can create an `InfrastructureBoundFlow` from a flow, work pool name, and worker class.
This PR also updates `ProcessWorker` to support testing `InfrastructureBoundFlow`. The `ProcessWorker` doesn't persist bundles for submitted flows because they can be passed to a subprocess.
Example usage:
```python
from prefect.filesystems import LocalFileSystem
from prefect.flows import bind_flow_to_infrastructure, flow
from prefect.workers.process import …
```

Add `InfrastructureBoundFlow` class and `bind_flow_to_infrastructure` function

---

src/prefect/cli/work_pool.py
tests/cli/test_work_pool.py

This PR expands the work pool storage configuration CLI to include GCS.
Example:
```
~/d/P/prefect ❯❯❯ uv run prefect work-pool storage configure gcs olympic \
--bucket storage-blocks-test-bucket \
--gcp-credentials-block-name my-gcp-creds
Configured GCS storage for work pool 'olympic'
~/d/P/prefect ❯❯❯ uv run prefect work-pool storage inspect olympic
╭─────────── Storage Configuration for olympic ───────────╮
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ │
│ ┃ Setting                ┃ Value                      ┃ │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩ │
│ │ type                   │ GCS                        │ │
│ │ bucket                 │ storage-blocks-test-bucket │ │
│ │ requires               │ prefect-gcs                │ │
│ │ …
```

Add CLI to configure GCS storage for a work pool

---

src/prefect/runner/runner.py

`shlex.split` removes the double-quotes we need to ensure that Python paths with spaces work on Windows. This carves out a case for Windows that I've tested on a Windows VM.
Closes https://github.com/PrefectHQ/prefect/issues/17820

Fixes `Runner` command handling for Windows

---

docs/v3/develop/blocks.mdx

custom blocks page was linking to `prefecthq/prefect-aws` which is archived

fix link to archived repo

---

src/prefect/cli/_prompts.py
src/prefect/cli/task.py
src/prefect/concurrency/context.py
src/prefect/context.py
src/prefect/utilities/_ast.py
uv.lock

picks up `find_flow_functions_in_file` from `_prompts` and moves it to `prefect.utilities._ast`
i want to add module-based `task` discovery to `prefect task serve` so I figured I'd first back this out so I can reuse it

move decorated function discovery out of the cli

---

src/prefect/server/events/triggers.py
tests/events/server/triggers/test_composite_triggers.py

Just like an event trigger, a composite trigger _may_ have a triggering
event that caused it to fire (like when all of its component triggers
are Reactive event triggers, a pretty common case).  Here, we propagate
that triggering event up through the firings so that folks can access
it from templates.  More importantly, this allows actions to make
inferences from the triggering event (like being able to infer a
deployment from it for the `PauseDeployment` action, for example).
closes https://github.com/PrefectHQ/prefect/issues/16399

Propagates the currently triggering event (if any) for composite triggers

---

src/prefect/cli/task.py
tests/cli/test_task.py

This pull request enhances the `task serve` command in the Prefect CLI by introducing support for importing tasks from Python modules in addition to entrypoints.
* Added support for specifying tasks via the `--module` option, allowing users to import tasks directly from Python modules. A new helper function `_import_tasks_from_module` was introduced to handle module imports. [[1]](diffhunk://#diff-f3f9a30115e3340d1216e6704ad41d055c231121f8634b2ac3ed791a994c9423L1-R48) [[2]](diffhunk://#diff-f3f9a30115e3340d1216e6704ad41d055c231121f8634b2ac3ed791a994c9423L53-R107)
* Updated the `serve` command to enforce mutual exclusivity between `entrypoints` and `--module` options, with appropriate error messages when both are provided.
* Added tests to validate mutual exclusivity between `entrypoints` …

serve all tasks in a module

---

docs/v3/develop/settings-and-profiles.mdx
docs/v3/manage/server/index.mdx

This PR adds
- a sample **tested** nginx configuration to self-host a Prefect server (see the [journey](https://github.com/ColinMaudry/prefect_ynh/issues/2) here)
- a note about how the Prefect API key setting takes precedence over the Prefect client authentication string when the Prefect client sets up the connection with the API
- It's a small fix

docs: Nginx sample config + note about client API key/auth string precedence

---

src/prefect/events/clients.py

* Prefect Worker logs a warning on reconnection to server and `PREFECT_DEBUG_MODE` is passed as `exc_info`.
* However, it is not boolean, by prefect setting, hence `.value()` should be called on this object, so I assume it is a typo/bug indeed.
* Currently when using JSON logs formatter, the warning is failed to render with an exception
```
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'prefect.settings.legacy.Setting'>
```

Fix warning on reconnect

---

docs/v3/api-ref/rest-api/server/schema.json
src/prefect/server/api/deployments.py
src/prefect/server/models/deployments.py
src/prefect/server/schemas/actions.py
src/prefect/server/schemas/core.py
tests/server/models/test_deployments.py
tests/server/orchestration/api/test_deployments.py
tests/server/schemas/test_actions.py
ui-v2/src/api/prefect.ts
ui-v2/src/components/deployments/deployment-form/deployment-form.tsx
ui-v2/src/components/deployments/deployment-form/use-deployment-form.ts
ui-v2/src/components/global-concurrency-limit/global-concurrency-limit-select/global-concurrency-limit-select.tsx
ui-v2/src/components/global-concurrency-limit/global-concurrency-limit-select/index.ts

This PR adds the `global_concurrency_limit_id` to the create and update route for deployments so that new and existing deployments can take advantage of the functionality to limit their work. 
closes #17803

Add global concurrency id to the create and update route for deployments

---

src/prefect/workers/base.py
tests/workers/test_base_worker.py

This PR updates `BaseWorker.submit` to link a submitted flow to its parent flow on submission. The methodology was borrowed from the flow run engine, so I included a couple of pieces (like tags) that were previously missing.

Link submitted flows to their parent flow

---

src/integrations/prefect-docker/prefect_docker/experimental/__init__.py
src/integrations/prefect-docker/prefect_docker/experimental/decorators.py
src/integrations/prefect-docker/prefect_docker/worker.py
src/integrations/prefect-docker/pyproject.toml
src/integrations/prefect-docker/tests/experimental/test_decorators.py
src/integrations/prefect-docker/tests/test_worker.py
src/prefect/_experimental/bundles/__init__.py
src/prefect/_experimental/bundles/execute.py
src/prefect/runner/runner.py
uv.lock

This PR adds a `@docker` decorator to bind a flow to run in a Docker container. This decorator is slightly different from the others introduced because it can operate without storage configured on the work pool. If the work pool doesn't have storage configured, then the flow bundle will be persisted to a temporary directory and a volume mount will be added to the created container so the bundle will be available for execution.
Here's what the usage looks like:
```python
from prefect_docker.experimental import docker
from prefect.filesystems import LocalFileSystem
result_storage = LocalFileSystem(basepath="/tmp/results")
result_storage.save("result-storage", overwrite=True)
@docker(
work_pool="in-ground",
image="prefecthq/prefect:local", …
```

Add `@docker` decorator

---

src/prefect/flows.py
tests/test_infrastructure_bound_flow.py

This PR adds a `submit` method to infrastructure-bound flows to dispatch their execution to remote infrastructure. Calling `submit` on an infrastructure-bound flow will return a future that can be used to track the execution of the submitted flow. 
Ideally, this would be the non-blocking alternative to calling an infrastructure-bound flow, but workers will block on exit if they are monitoring a flow run. I think we'll need to give workers the option to opt out of watching flow runs to make `submit` non-blocking.
Closes https://github.com/PrefectHQ/prefect/issues/6689

Add `submit` method to infrastructure bound flows

---

docs/v3/api-ref/rest-api/server/schema.json
src/prefect/_versioning.py
src/prefect/cli/deploy.py
src/prefect/server/models/deployments.py
src/prefect/server/schemas/actions.py
tests/test_versioning.py
ui-v2/src/api/prefect.ts

* We were making the classic `.rstrip` mistake of thinking it took a
string to replace, when it really takes string full of characters to
replace.  Here we parse it with `urlparse` and are more deliberate
about removing the trailing `.git`
* We were using the `GITHUB_REF` (like `refs/heads/main`) instead of the
friendlier `GITHUB_REF_NAME` (like `main`)
* We were printing the `repr` of the `VersionInfo` out during deploy,
but that's extra noise we don't need
* We're now inferring the version even if a `version_type` isn't
provided, which should make this more seamless for users.  If
`version` is explicitly passed, we'll use that directly

Polishes the experience with inferring versioning

---

src/prefect/flows.py
tests/test_flows.py
tests/test_infrastructure_bound_flow.py

Because `InfrastructureBoundFlow` subclasses `Flow` and `with_options` explicitly returns a `Flow` instance, we need a `with_options` implementation that handles the additional fields that `InfrastructureBoundFlow` exposes. This PR adds `with_options` to `InfrastructureBoundFlow` and allows users to update the `job_variables` associated with an `InfrastructureBoundFlow`.

Add `with_options` implementation to `InfrastructureBoundFlow`

---

src/prefect/cli/task_run.py
tests/cli/test_task_run.py

- Fixes an error where filtering task runs by state type would fail
- Adds tests for the `task-run logs` CLI
Closes #17902

Fix errors in `task-run ls` CLI

---

src/prefect/_internal/concurrency/threads.py

I've seen this test flake a lot, e.g., https://github.com/PrefectHQ/prefect/actions/runs/14669582788/job/41172805597
It crossed my mind that it _might_ be because the future finishes before the done callback is added to it that ensures proper shutdown. This PR changes the order of the logic to account for this race condition.

Add done callback prior to submitting

---

.github/workflows/prefect-client.yaml
client/client_deploy.py
client/client_flow.py
src/prefect/_experimental/bundles/execute.py

In https://github.com/PrefectHQ/prefect/pull/17878 I accidentally added `typer` into the path used to execute scheduled flow runs via the `Runner` class. This breaks `prefect flow-run execute` in the `prefect-client` Docker images because `typer` isn't installed with `prefect-client`.
I swapped out `typer` for `argv` to resolve the errors and added an additional check to the `prefect-client` smoke test workflow to guard against similar mistakes in the future.
Example failure before fix was added: https://github.com/PrefectHQ/prefect/actions/runs/14687032191/job/41217026252?pr=17920

Add smoke test for remote execution via `prefect-client`

---

docs/v3/deploy/index.mdx
src/prefect/_versioning.py
src/prefect/cli/deploy.py
tests/cli/deploy/test_deploy_versioning.py
tests/test_versioning.py

Adds vcs version types for Gitlab, Bitbucket, and Azure Devops.
Also adds the `commit_sha` and `message` fields to all `vcs` version types. The `message` field is the first line of the commit message.
Uses the `--version` from the CLI deploy or the `version` in a YAML deployment definition as the `version` field on `VersionInfo` if it's supplied, and uses the `message` as the `version` field otherwise.

Add vcs version types for Gitlab, Bitbucket, and Azure Devops

---

src/prefect/flow_runs.py
tests/test_flow_runs.py

closes https://github.com/PrefectHQ/prefect/issues/17929
we are subscribing to all flow run events, which makes sense
```
event_filter = EventFilter(
event=EventNameFilter(prefix=["prefect.flow-run"]),
resource=EventResourceFilter(id=[f"prefect.flow-run.{flow_run_id}"]),
)
```
but we were assuming that the only type of flow run events would be state changes, which is not true at this point
```
state_type = StateType(event.resource["prefect.state-type"])
```

handle heartbeat event in `wait_for_flow_run`

---

src/prefect/client/orchestration/_deployments/client.py
src/prefect/client/schemas/actions.py
tests/client/test_prefect_client.py

closes https://github.com/PrefectHQ/prefect/issues/17887
the sync and async versions of the client method are the only place this schema is used, and this should not impact any other cases (besides the problematic one currently giving unexpected results)
This pull request introduces enhancements to parameter handling in the `DeploymentFlowRunCreate` model and adds a corresponding test to ensure proper functionality. The most notable changes include adding a `model_validator` to convert Pydantic `BaseModel` parameters into plain JSON data and a new test case to validate this behavior.
* Added a `model_validator` method `convert_parameters_to_plain_data` in the `DeploymentFlowRunCreate` class to ensure that any `BaseModel` instances in the `parameters` field are converted to plain JSON data …

add `parameters` validator to `DeploymentCreateFlowRun`

---

src/prefect/blocks/core.py

the case is always true since a dict with any keys will be truthy

remove unnecessary walrus

---

ui-v2/src/api/block-documents/block-documents.test.ts
ui-v2/src/api/block-documents/block-documents.ts
ui-v2/src/api/block-documents/index.ts

Adds RQ mutation to create a block document with tests

[UI v2] feat: Adds create block document rq mutation

---

.github/workflows/integration-tests.yaml
.github/workflows/prefect-client.yaml

This PR adds a job that runs compatibility tests against `prefect-client`. This seems like the lowest lift way to add coverage to `prefect-client` and avoid accidental breakage.

Run integration tests against `prefect-client`

---

docs/v3/api-ref/rest-api/server/schema.json
docs/v3/deploy/submit-flows-directly-to-dynamic-infrastructure.mdx
src/prefect/blocks/core.py
src/prefect/cli/work_pool.py
src/prefect/client/schemas/objects.py
src/prefect/server/api/workers.py
src/prefect/server/schemas/core.py
src/prefect/workers/base.py
tests/cli/test_work_pool.py
tests/client/test_prefect_client.py
tests/server/orchestration/api/test_workers.py
tests/workers/test_base_worker.py
ui-v2/src/api/prefect.ts

This PR updates a work pool's storage configuration to include a default storage block to use for result storage. This improves the ergonomics when submitting flow runs directly to dynamic infrastructure because users won't need to provide their own result storage if they don't want to. Results are stored in the same storage location as bundles for execution, but under a `results` folder.
This PR also updates error handling for missing Block class definitions to direct users to install the necessary Prefect integration when possible. This is often a tripping point for users when using result storage.

Add default result storage for work pools

---

src/prefect/runner/runner.py
src/prefect/workers/base.py

These two logs are logged with every loop which can get noisy. Proposal to downgrade them both to `DEBUG` level.

Downgrade log to debug level

---

src/prefect/events/clients.py
src/prefect/runner/_observers.py
src/prefect/runner/runner.py

This PR refactors the `Runner` to use a websocket connection to receive cancellation messages. This eliminates the need to poll for cancellation (which makes the server and DB happy) while also allowing the `Runner` to respond to cancellation requests faster.

Refactor `Runner` to receive cancellation signals via websocket

---

flows/task_worker.py
src/prefect/client/orchestration/__init__.py
src/prefect/client/subscriptions.py
src/prefect/tasks.py
tests/test_task_worker.py

closes https://github.com/PrefectHQ/prefect/issues/17971
the client subscription code should have been updated in https://github.com/PrefectHQ/prefect/pull/17741 but it wasn't, so we were indiscriminately trying to use `PREFECT_API_KEY`

use correct secret in websocket subscription

---

src/prefect/flows.py
tests/test_flows.py

Classmethod flows were losing their cls inheritance structure when copied with .with_options(), causing them to default to the base class implementation. This was particularly evident when subclassing (e.g., ChildProcessor.process would incorrectly use BaseProcessor.get_multiplier).
The fix ensures proper context preservation by:
1. Creating deep copies of the function for each bound flow
2. Maintaining independent __prefect_self__ references
3. Preserving all function attributes during copying
Added test cases verify:
- Classmethod inheritance is maintained after .with_options()
- Instance methods retain their proper self context
- Multiple bound flows don't interfere with each other
Closes https://github.com/PrefectHQ/prefect/issues/17354
- If no issue exists and your change is not a …

Add test covering `.with_options` when used with a `classmethod` flow

---

src/prefect/utilities/dockerutils.py
tests/docker/test_image_parsing.py

Adds detection and parsing for Docker image strings containing digests.

Parse docker image strings with digests

---

src/prefect/events/clients.py
src/prefect/runner/runner.py
tests/runner/test_runner.py

Giving the runner a long-lived `EventsClient` allows us to customize the rate events are emitted. Using a client with a low checkpoint should prevent heartbeat events from piling up client-side.
Closes https://github.com/PrefectHQ/prefect/issues/17958

Update `Runner` to use a long-lived `EventsClient`

---

justfile
src/prefect/server/database/_migrations/versions/postgresql/2025_05_04_193249_1c9bb7f78263_add_scope_leader_idx_to_.py
src/prefect/server/database/_migrations/versions/sqlite/2025_05_04_193544_3c841a1800a1_add_scope_leader_idx_to_.py
src/prefect/server/database/orm_models.py

adds a  **Composite index on `automation_event_follower(scope, leader_event_id)`**
* `orm_models.py` declares `ix_ae_follower_scope_leader`.
* Alembic migrations for **Postgres** and **SQLite** create / drop the index.
no runtime code paths changed in this PR
---
* The API hits
```sql
SELECT follower
FROM automation_event_follower
WHERE scope=$1 AND leader_event_id=$2
```
on **every** event to maintain causal ordering.
* When the table is empty (typical) that query devolves to a seq-scan and ends up taking the _second most_ `total_ms` 
* The composite index converts it to an index-only hit (sub-ms)
---
* **Problem**: a multi-pod Prefect setup  will need the “skip-the-query”
hints to be **global**, not per-process (I tried a TTL cache for kicks and it works on the single server setup and …

add aef index

---

docs/v3/api-ref/rest-api/server/schema.json
src/prefect/_internal/schemas/validators.py
src/prefect/client/schemas/actions.py
src/prefect/client/schemas/objects.py
src/prefect/server/schemas/actions.py
src/prefect/server/schemas/core.py
src/prefect/types/__init__.py
src/prefect/types/names.py
tests/server/orchestration/api/test_variables.py
ui-v2/src/api/prefect.ts

strict refactor, deleting as much as possible from the internal validators module and moving it into `types` in cases where we only are checking some `re.Pattern`, which allows us to just define these once for use in client/server schemas and avoid extra encapsulation like we had in the internal validators module
moves naming related types into a new `prefect.types.names`
to merge after https://github.com/PrefectHQ/prefect/pull/17995, which doesn't attempt the consolidation im going for here
<details>
This pull request introduces several updates to improve schema validation, simplify code, and enhance maintainability. Key changes include replacing custom validators with type annotations, updating JSON schema definitions, and replacing default list initializations with `lambda` functions …

organize types

---

src/prefect/server/schemas/filters.py
tests/server/models/test_flow_runs.py
tests/server/schemas/test_filters.py

This PR fixes an issue where scheduled runs weren't returned when using `start_time` filters by coalescing `start_time` and `expected_start_time` fields. This matches the behavior JS clients are expecting.

Bugfix: Coalesce flow run start times with expected start times

---

.github/workflows/k8s-integration-tests.yaml
src/integrations/prefect-aws/prefect_aws/workers/ecs_worker.py
src/integrations/prefect-aws/tests/workers/test_ecs_worker.py
src/integrations/prefect-docker/prefect_docker/worker.py
src/integrations/prefect-docker/tests/test_worker.py
src/integrations/prefect-gcp/prefect_gcp/workers/vertex.py
src/integrations/prefect-gcp/tests/test_vertex_worker.py
src/integrations/prefect-kubernetes/prefect_kubernetes/worker.py
src/integrations/prefect-kubernetes/tests/test_worker.py
src/prefect/workers/base.py
tests/workers/test_base_worker.py

The `initiate_run` method is a new method used to create infrastructure for a flow run, but not watch the created infrastructure or wait for the flow run to complete.
`initiate_run` will be used (if implemented) within `.submit` to allow `flow.submit` to be a non-blocking way to submit runs to remote infrastructure.
This PR also implements `initiate_run` for the following workers:
- Kubernetes
- ECS
- Vertex AI
- Docker
This PR doesn't implement `initiate_run` for the Cloud Run or Azure Container Instances workers because those workers both have clean-up steps after a run has completed. A non-blocking approach will need to remove the clean-up requirement and will be addressed in another PR.

Allow `flow.sumbit` to be non-blocking for some infrastructure types

---

client/pyproject.toml
pyproject.toml
src/prefect/_internal/schemas/bases.py
src/prefect/_internal/uuid7.py
src/prefect/client/schemas/objects.py
src/prefect/events/schemas/events.py
src/prefect/server/api/workers.py
src/prefect/server/events/actions.py
src/prefect/server/events/schemas/automations.py
src/prefect/server/models/deployments.py
src/prefect/server/models/events.py
src/prefect/server/models/workers.py
src/prefect/server/schemas/core.py
src/prefect/server/schemas/states.py
src/prefect/server/utilities/schemas/__init__.py
src/prefect/server/utilities/schemas/bases.py
src/prefect/task_runners.py
src/prefect/tasks.py
src/prefect/types/__init__.py
uv.lock

[UUIDv7](https://uuid7.com/) is a UUID generation mechanism that
guarantees that UUIDs are both random/unique, but also sequential in
time.  This makes them ideal for storing any time-oriented rows in
databases, since they'll have great data locality.
We've made this change to Prefect Cloud, and have seen some significant
improvements in write throughput, overall I/O, and in page cache hit
ratios.

Uses UUIDv7 for the IDs of time-oriented objects

---

ui/src/pages/Runs.vue

This PR fixes an issue where the flow run scatterplot query wasn't respecting pages because the endpoint works on an offset model instead of a paginated one. It also moves the pager to the top of the list and bumps the default number of items from 10 => 100. This means users will be able to paginate through the scatterplot and runs list at the same time, like so:
https://github.com/user-attachments/assets/a145edfd-f371-4786-8775-9f236eb0c547

Bugfix: Scatterplot pagination

---

src/integrations/prefect-kubernetes/prefect_kubernetes/observer.py

This change disables `kopf` scanning for the `prefect-kubernetes` observer to avoid logging errors when the observer runs without the necessary permissions to discover namespaces and CRDs. That discovery isn't necessary for the observer to function, but it does log annoying errors.
Here's an exerpt from the setting docstring:
> If disabled or if enabled but the permission is not granted, then only the specific namespaces will be served, with namespace patterns ignored; and only the resources detected at startup will be served, with added CRDs or CRD versions being ignored, and the deleted CRDs causing failures.
> 
> The default mode is good enough for most cases, unless the strict (non-dynamic) mode is intended -- to prevent the warnings in the logs.
Closes …

Disable `kopf` scanning for `prefect-kubernetes` observer

---

.pre-commit-config.yaml

These hooks take a while to run and are unnecessary on every commit. This change means they only run before pushing to a remote branch.
Note that contributors will need to run `pre-commit install` again to install the pre-push hooks.

Move generation hooks to pre-push

---

src/integrations/prefect-redis/prefect_redis/locking.py
src/integrations/prefect-redis/tests/test_locking.py

resolves #18017 where unpicklable `_thread.lock` in `RedisLockManager` caused issues when used with Ray/Dask
this PR:
- updates `__init__`: Now calls a new `self._init_clients()` method to instantiate `self.client` and `self.async_client` immediately
- adds `_init_clients()`: private method containing the client instantiation logic
- adds `__getstate__`: pickle only connection parameters (host, port, etc.), excluding live clients and `_locks`.
- adds `__setstate__`: after restoring state, now calls `self._init_clients()` to ensure fresh client connections are established, resets `self._locks = {}`.

make `RedisLockManager` picklable for ray/dask compat

---

src/prefect/_internal/compatibility/blocks.py
src/prefect/results.py
src/prefect/task_worker.py
src/prefect/tasks.py
tests/test_background_tasks.py
tests/test_tasks.py

- moves `read_parameters` and `store_parameters` out of `results.py` and into `task_worker.py` as functions, deprecating the methods on `ResultStore`
- moves block method compat code into `_internal` module (was already private)
- updates error message upon 403 when connecting to subscription per https://github.com/PrefectHQ/prefect/pull/17975

Task worker hygiene

---

src/prefect/settings/models/tasks.py
src/prefect/types/__init__.py
tests/test_settings.py

uses a similar idea to `validate_set_T_from_delim_string` but its an unhashable `list` (order matters for retry delays), maybe there's some more general function to write for all these `BeforeValidator`s, but this seemed fine for now
motivated by https://github.com/PrefectHQ/prefect/pull/18041

fix parsing for `PREFECT_TASK_DEFAULT_RETRY_DELAY_SECONDS`

---

client/pyproject.toml
pyproject.toml
src/prefect/_internal/uuid7.py
tests/_internal/test_uuid.py
uv.lock

This PR vendors the UUIDv7 implementation from `uuid7` to unblock Conda releases. Parts that we don't need are left out and I've made some modifications to improve the typing.

Vendor `uuid7` implementation

---

.github/workflows/prefect-client.yaml
client/client_deploy.py
scripts/wait-for-server.py

Removes the dependency on Prefect Cloud and allows these tests to run successfully from a forked repository.

Run `prefect-client` smoke tests against local server

---

.github/workflows/integration-tests.yaml

The client compability tests have been failing because of a missing `uv run`.

Fix error in setup for client compatibility tests

---

src/prefect/runner/runner.py
tests/runner/test_runner.py

This PR removes some code for `Runner` cancellation that is no longer necessary, but lead to the incorrect `Runner` cancelling a flow run when multiple instances are running for the same deployment or if multiple process workers are running in the same work pool.
Closes https://github.com/PrefectHQ/prefect/issues/18106

Fix bug where the runner would try to cancel a flow run that was not running

---

src/prefect/serializers.py
tests/test_serializers.py

Addresses an issue where `io.StringIO`/`BytesIO` objects passed as task parameters were consumed before task execution, appearing empty to user code. This was a regression from Prefect 2.
**Cause:**
The `prefect_json_object_encoder` (used by `JSONSerializer` for logging/events) inadvertently read `io.IOBase` objects during its serialization process.
**Solution:**
`prefect_json_object_encoder` now explicitly checks for `io.IOBase` instances. Instead of reading them, it returns a standardized dictionary placeholder (e.g., `{"__class__": "...", "data": "<Prefect IOStream Placeholder...>"}`). This keeps the stream unread for the task.
<details>
from slack
```python
from io import StringIO
import prefect
from prefect import flow, task, get_run_logger
@task
def main_task(stream):
logger = …
```

avoid unexpected buffer consumption in pydantic encoder

---

docs/docs.json
docs/v3/how-to-guides/workflows/test-workflows.mdx

Stacked on https://github.com/PrefectHQ/prefect/pull/18123
This pull request updates the documentation for testing workflows in Prefect, reorganizing and improving the content for clarity and accessibility. The most important changes involve restructuring the file, adding new sections, and refining the language to better guide users.
* **File renamed and retitled:** The file `docs/v3/develop/test-workflows.mdx` was renamed to `docs/v3/how-to-guides/workflows/test-workflows.mdx` and retitled from "Test workflows" to "How to test workflows" to align with the "How-to guides" structure. A new `sidebarTitle` was also added for better navigation.
* **New section added:** A section titled "Isolate tests with an ephemeral backend" was introduced, explaining how to use a temporary local SQLite …

Move test workflows to how-to guide

---

src/prefect/server/api/clients.py
tests/server/api/test_clients.py

To help keep system coupling lower, the automations subsystem uses an
in-memory client to make API calls to perform orchestration actions.
This client was aware of Prefect API auth, but not of CSRF protection.
Closes #18045

Enables CSRF protection support on internal server requests

---

src/integrations/prefect-redis/prefect_redis/messaging.py
src/integrations/prefect-redis/tests/test_messaging.py

related to https://github.com/PrefectHQ/prefect/discussions/18150
adds settings objects local to the redis Publisher and Consumer messaging implementations so that env vars can fully control behavior
```python
» PREFECT_REDIS_MESSAGING_CONSUMER_TRIM_EVERY=30 PREFECT_REDIS_MESSAGING_PUBLISHER_BATCH_SIZE=42 ipython
#[1]
from prefect_redis.messaging import RedisMessagingConsumerSettings, RedisMessagingPublisherSettings
#[2]
RedisMessagingConsumerSettings().trim_every, RedisMessagingPublisherSettings().batch_size
Out[2]: (datetime.timedelta(seconds=30), 42)
```

add redis publisher/consumer settings

---

.pre-commit-config.yaml
Dockerfile
pyproject.toml

newer versions of `uv` add a `upload_time` field to all entries which causes a large diff.
this PR adds a bound so that devs don't accidentally cause churn by using a earlier uv version
see https://github.com/dependabot/dependabot-core/issues/12127

lower bound pin uv

---

src/integrations/prefect-kubernetes/prefect_kubernetes/observer.py
src/integrations/prefect-kubernetes/tests/test_observer.py

closes https://github.com/PrefectHQ/prefect/issues/18225
this PR makes 2 changes
- we restrict the `/events/filter` call to only look at things after the k8s event that triggers the handler
- we use the k8s event timestamp as the `occurred` of the prefect event

use kopf event for `occurred` in forwarded prefect events

---

docs/robots.txt

I want `docs-2.prefect.io` to be removed from search results, and it seems that in the past we had both:
- [a meta tag for noindex and nofollow](https://github.com/PrefectHQ/prefect/blob/2.x/docs/overrides/main.html#L4)
- [a `robots.txt` file instructing agents to not explore the site](https://github.com/PrefectHQ/prefect/blob/2.x/docs/robots.txt) 
Having both is an anti-pattern: the `robots.txt` file prevents bots from discovering the meta tag (and `robots.txt` doesn't prevent indexing due to cross-linking from other sites)! And the meta tag is [the recommended most robust way to delist a site](https://support.google.com/webmasters/answer/9689846?sjid=5781052515740160538-NC#make_permanent).
So with all that, this PR removes `robots.txt`.

Remove robots.txt file

---

src/integrations/prefect-gcp/prefect_gcp/cloud_storage.py
src/integrations/prefect-gcp/tests/test_cloud_storage.py

closes https://github.com/PrefectHQ/prefect/issues/18227

Early return bucket path to avoid duplicated prefix in GCS bucket

---

src/prefect/task_engine.py
tests/test_task_engine.py

This updates the task run engine to retry tasks that explicitly return a failed state. Consider this flow/task:
```python
from prefect import flow, task, get_run_logger
from prefect.states import Failed
RUNS = 0
def condition(task, task_run, state):
try:
state.result()
except Exception:
return "please_retry" in state.message
@task(retries=1, retry_condition_fn=condition)
def task_a():
global RUNS
RUNS += 1
logger.info("Inside task_a")
if RUNS < 2:
return Failed(message="please_retry")
else:
return "success"
@flow()
def generic_flow():
task_a()
generic_flow()
```
`task_a` will now be retried:
```
11:59:39.997 | INFO    | Flow run 'misty-shrew' - Beginning flow run 'misty-shrew' for flow 'generic-flow'
11:59:40.006 | INFO    | Flow run …
```

Attempt retries  when task returns a failed state

---

src/prefect/settings/profiles.py
tests/test_settings.py

closes https://github.com/PrefectHQ/prefect/issues/18258
**Problem:**
`prefect config set` was not validating field constraints for nested settings, allowing invalid values to be saved:
```bash
$ prefect config set PREFECT_RUNNER_HEARTBEAT_FREQUENCY=5
Set 'PREFECT_RUNNER_HEARTBEAT_FREQUENCY' to '5'.  # ❌ Should have failed (5 < 30)
$ prefect config view
ValidationError: Input should be greater than or equal to 30
```
**Root Cause:**
`Profile.validate_settings()` was manually traversing nested models, losing pydantic field constraints like `ge=30` in the process.
**Solution:**
Updated the validation to use the same robust approach as `Settings.copy_with_update()`:
1. Build proper nested dict structure using setting accessors
2. Validate against the full `Settings` model to preserve all …

fix `config` validation for nested and constrained settings

---

src/prefect/server/api/templates.py

Closes https://github.com/PrefectHQ/prefect/issues/17189
Supersedes https://github.com/PrefectHQ/prefect/pull/18259
It appears the UI is [still using the route with the `/automations` prefix](https://github.com/PrefectHQ/prefect-ui-library/blob/6564988eed300fd01df33b60e922e64ec7601bb5/src/services/WorkspaceAutomationsApi.ts#L36) so until that is updated we need to support both endpoints.

Add automations prefix to validate route

---

.dockerignore

notably, running `docker build` locally would scoop any .venv files from integrations, which would drastically increase build time and footprint

omit nested venv from docker builds

---

src/prefect/assets/core.py
src/prefect/types/__init__.py
src/prefect/types/names.py
tests/test_assets.py

This PR keeps `Asset.key` a little more restricted by adding:
- a list of characters you can't include
- enforcing a maximum length of 512 characters

Enforce asset key characters + length

---

docs/docs.json

Use redirect on Prefect website to access the invite page.
Replace Community Inviter link for Slack Community. `prefect.io/slack` is a 301 redirect to the Slack invite page and managed inside the website repo.

Update Slack footer link

---

src/integrations/prefect-dbt/prefect_dbt/core/_tracker.py
src/integrations/prefect-dbt/prefect_dbt/core/runner.py
src/integrations/prefect-dbt/tests/core/test_runner.py
src/integrations/prefect-dbt/tests/core/test_settings.py
src/integrations/prefect-dbt/tests/core/test_tracker.py

Closes #18430
This PR makes a number of improvements and fixes to `prefect-dbt` intended for inclusion in `prefect-dbt==0.7.2`:
- Fixes resolution of templated Prefect blocks and Prefect variables in `profiles.yml`
- Fixes a logging race condition, ensuring all logs about a node are associated with their corresponding Prefect task run
- Prevents skipped nodes from getting task runs so skipped nodes don't give a false impression that they ran, and don't create or update assets. Includes children of nodes whose tests fail if using or retrying the `build` command

Resolve dbt profiles and other improvements

---

src/integrations/prefect-bitbucket/prefect_bitbucket/credentials.py
src/integrations/prefect-bitbucket/prefect_bitbucket/repository.py
src/integrations/prefect-bitbucket/tests/test_credentials.py
src/integrations/prefect-bitbucket/tests/test_repository.py

This pull request improves the functionality and flexibility of the BitBucketCredentials block within the Prefect Bitbucket integration by addressing real-world authentication scenarios involving special characters and longer usernames.
**1. Expanded Username Validation**
•Updated the username field to allow special characters commonly used in Bitbucket usernames (such as @, ., _, +, and -).
•Enables use of email addresses and other valid Bitbucket username formats.
**2. Increased Username Length Limit**
•Raised the character limit from 30 to 100, supporting long email-based usernames.
**3. Secure Git URL Construction**
•Properly escapes special characters in username and token using urllib.parse.quote.
•Ensures safe and valid Git URLs for cloning private repositories.
•Added and updated …

Enhance BitBucket Credentials Block: Support Special Characters in Username and Escape Git URL Credentials

---

src/integrations/prefect-aws/prefect_aws/workers/ecs_worker.py
src/integrations/prefect-aws/tests/workers/test_ecs_worker.py

There are a couple of places in the ECS worker where we assume that a deployment ID is present. Flows submitted via the `@ecs` decorator don't have an assoicated deployment, which causes errors in caching, family name generation and log prefix generation. These changes adjust the implementation to use the flow ID as a fallback when there is no associated deployment.

Fix errors in ECS worker related to ad hoc submission

---

docs/v3/api-ref/cli/artifact.mdx
docs/v3/api-ref/cli/automation.mdx
docs/v3/api-ref/cli/automations.mdx
docs/v3/api-ref/cli/concurrency-limit.mdx
docs/v3/api-ref/cli/concurrency-limits.mdx
docs/v3/api-ref/cli/deployment.mdx
docs/v3/api-ref/cli/deployments.mdx
docs/v3/api-ref/cli/dev.mdx
docs/v3/api-ref/cli/flow-run.mdx
docs/v3/api-ref/cli/flow-runs.mdx
docs/v3/api-ref/cli/gcl.mdx
docs/v3/api-ref/cli/global-concurrency-limit.mdx
docs/v3/api-ref/cli/profile.mdx
docs/v3/api-ref/cli/profiles.mdx
docs/v3/api-ref/cli/task-run.mdx
docs/v3/api-ref/cli/task-runs.mdx
docs/v3/api-ref/cli/task.mdx
docs/v3/api-ref/cli/variable.mdx
docs/v3/api-ref/cli/work-pool.mdx
docs/v3/api-ref/cli/work-queue.mdx
docs/v3/api-ref/cli/work-queues.mdx
docs/v3/how-to-guides/automations/creating-automations.mdx
src/prefect/events/cli/automations.py
tests/events/client/cli/test_automations.py

This PR adds a `prefect automation create` command to the CLI, allowing users to create automations programmatically from YAML/JSON files or JSON strings. The command supports creating single or multiple automations at once.
closes #18451
- Added `create` command to `src/prefect/events/cli/automations.py`
- Uses explicit `--from-file`/`-f` and `--from-json`/`-j` flags for input
- Auto-detects file format based on extension (.yaml, .yml, .json)
- **Supports multiple automations** via `automations:` key or JSON array
- **No rollback behavior** - continues processing all automations and reports both successes and failures
- Uses existing `AutomationCore` schema validation and `client.create_automation()` method
```bash
prefect automation create --from-file automation.yaml
prefect automation …
```

add `prefect automation create` command

---

docs/v3/advanced/api-client.mdx
docs/v3/advanced/security-settings.mdx
docs/v3/api-ref/settings-ref.mdx
scripts/generate_settings_ref.py
src/prefect/_internal/websockets.py
src/prefect/client/base.py
src/prefect/settings/models/client.py
tests/_internal/test_websockets.py
tests/client/test_base_client.py
tests/test_settings.py

Adds a new setting for configuring custom client headers, including documentation.
Closes https://github.com/PrefectHQ/prefect/issues/18435

Add setting for configuring custom headers

---

src/prefect/server/models/events.py
src/prefect/utilities/engine.py
tests/events/client/instrumentation/test_task_run_state_change_events.py
tests/server/orchestration/test_flow_run_instrumentation_policies.py

This should make it much easier to create automations that stop triggering after a certain number of run retries.
For example:
```json
{
"type": "event",
"match": {
"prefect.resource.id": [
"prefect.flow-run.*"
],
"prefect.run-count": [
"1"
]
},
"match_related": {
"prefect.resource.id": [
"prefect.deployment.*"
]
},
"after": [],
"expect": [
"prefect.flow-run.Failed"
],
"for_each": [],
"posture": "Reactive",
"threshold": 1,
"within": 0
}
```
In english, "When any flow run of any deployment fails its first run, do {action}".

Include run count in state change events

---

src/prefect/server/orchestration/core_policy.py
tests/server/orchestration/test_core_policy.py

When initiating a manual retry from the UI after a flow has already performed in-process retries, the flow run will be stuck in `AwaitingRetry` because the retry type will remain set to `in_process`, which will cause the flow run to not be sent to workers. The `HandleFlowTerminalStateTransitions` orchestration policy is supposed to clear the retry type, but the UI forces the state transition, so that orchestration policy isn't run.
These changes fix the bug by clearing the retry type on exhausted retries in the `RetryFailedFlows` orchestration policy.
Closes https://github.com/PrefectHQ/prefect/issues/17913

Update `RetryFailedFlows` orchestration policy to clear retry type on exhausted retries

---

integration-tests/test_schedule_statefulness.py
integration-tests/test_serve_a_flow.py

This PR follows up https://github.com/PrefectHQ/prefect/pull/18468 to attempt to deflake the schedule statefullness integration test. With these changes, the script will verify the expected schedule operation has taken place before stopping the serve process.

Improve reliability of integration tests

---

src/integrations/prefect-dbt/prefect_dbt/utilities.py
src/integrations/prefect-dbt/tests/test_utilities.py

Closes #18475
Now that asset keys have an extensive restricted character list, we need to remove those characters from asset keys build from dbt relation names.

Remove restricted characters from dbt asset keys

---

.pre-commit-config.yaml

I accidentally commit to `main` every once in a while, so this adds some guardrails via `pre-commit`.

Add `no-commit-to-branch` hook to prevent accidental commits to main

---

docs/v3/how-to-guides/deployments/run-deployments.mdx
src/prefect/cli/deployment.py
tests/cli/deployment/test_deployment_cli.py

This PR adds support for specifying a custom name for a flow run using the --flow-run-name flag when running a deployment via the CLI.
- Added --flow-run-name option to set a static flow run name via CLI.
- Validates and passes the static name to the backend during flow run creation.
- Updated CLI command logic and documentation to reflect static name support.
- Added tests to verify correct behavior with static custom names.
Example Usage
```bash
prefect deployment run my-flow/my-deployment --flow-run-name "custom-run-name"
```
The templating logic has been tested with various scenarios, including:
- Verified CLI behavior with and without --flow-run-name
- Ensured flow run names are applied correctly when specified
- Confirmed appropriate fallback and error messaging when flow run name …

Added support for setting flow run name in deployment CLI

---

docs/docs.json
docs/v3/api-ref/rest-api/server/concurrency-limits-v2/bulk-increment-active-slots-with-lease.mdx
docs/v3/api-ref/rest-api/server/schema.json
src/prefect/server/api/concurrency_limits_v2.py
src/prefect/server/concurrency/lease_storage/memory.py
src/prefect/server/utilities/leasing.py
tests/server/orchestration/api/test_concurrency_limits_v2.py
ui-v2/src/api/prefect.ts

This PR adds a `/v2/concurrency-limits/increment-with-lease` endpoint that increments the specified concurrency limits and returns a lease ID for a lease valid for the provided duration. A lease renewal endpoint will be added in a subsequent PR.

Add endpoint for acquiring concurrency slots with a lease

---

docs/docs.json
docs/v3/api-ref/rest-api/server/concurrency-limits-v2/renew-concurrency-lease.mdx
docs/v3/api-ref/rest-api/server/schema.json
docs/v3/api-ref/settings-ref.mdx
schemas/settings.schema.json
src/prefect/server/api/concurrency_limits_v2.py
src/prefect/server/concurrency/lease_storage/__init__.py
src/prefect/server/concurrency/lease_storage/filesystem.py
src/prefect/server/concurrency/lease_storage/memory.py
src/prefect/server/services/repossessor.py
src/prefect/server/utilities/leasing.py
src/prefect/settings/models/server/concurrency.py
src/prefect/settings/models/server/root.py
tests/server/concurrency/test_filesystem_lease_storage.py
tests/server/concurrency/test_memory_lease_storage.py
tests/server/orchestration/api/test_concurrency_limits_v2.py
tests/test_settings.py
ui-v2/src/api/prefect.ts

This PR adds a `/v2/concurrency-limits/renew` endpoint to enable the exertion of concurrency limit leases to prevent the repossessor service from freeing slots in the associated concurrency limits.
This PR also adds a filesystem-based `ConcurrencyLeaseStorage` implementation to aid in testing, along with the settings mechanics to enable switching between different `ConcurrencyLeaseStorage` implementations.
Related to https://github.com/PrefectHQ/prefect/issues/17415

Add concurrency lease renewal endpoint

---

src/prefect/_experimental/bundles/__init__.py
src/prefect/flows.py
src/prefect/workers/base.py
tests/test_infrastructure_bound_flow.py

This PR adds a `.submit_to_work_pool` method to `InfrastructureBoundFlow`, which can be used to create a flow run for an `InfrastructureBoundFlow`, but will not spin up a local worker for submission. This new method is helpful if you want to dynamically configure job variables and run portions on your workflow on remote infrastructure **and** you have one or more workers already for the work pools you're submitting to. This can also help you consolidate permission grants (e.g. `ecs:RunTask`) to your workers while retaining the benefits of ad-hoc flow submission.
On the surface, it works pretty much the same as `.submit`:
```python
from prefect_kubernetes.experimental import kubernetes
@kubernetes(work_pool="olympic")
@flow
def my_flow(name: str):
return f"Hello, …
```

Allow infrastructure bound flows to be dispatched to existing workers

---

src/prefect/assets/core.py
tests/test_assets.py

Enforce max description length of 2500 character for an Asset.

Enforce max asset description length

---

docs/integrations/prefect-aws/ecs_guide.mdx

this guide could use a more holistic overhaul, but in the immediate term this PR aims to clarify that you can deploy an ECS worker with either OSS or cloud

add note about `PREFECT_API_KEY` in ecs guide

---

docs/v3/api-ref/rest-api/server/schema.json
src/prefect/server/api/concurrency_limits_v2.py
src/prefect/server/concurrency/lease_storage/filesystem.py
src/prefect/server/services/repossessor.py
src/prefect/server/utilities/leasing.py
tests/server/orchestration/api/test_concurrency_limits_v2.py
ui-v2/src/api/prefect.ts

This PR updates the concurrency limit lease implementation to track when leases are created, and use that timestamp to populate `occupancy_seconds` when decrementing concurrency limit slots. With this change, clients will not need to provide `occupancy_seconds` when decrementing concurrency limit slots via a lease.
Related to https://github.com/PrefectHQ/prefect/issues/17415

Track concurrency limit lease creation time and use it to calculate occupancy seconds

---

src/integrations/prefect-gcp/prefect_gcp/cloud_storage.py

Closes #18559
this PR improves the performance of `GcsBucket.put_directory()` by implementing concurrent uploads and client reuse
<details>
- **Before**: Created a new GCS client for each file upload
- **After**: Create a single client and reuse it for all uploads
- **Before**: Files uploaded sequentially, one at a time
- **After**: Files uploaded concurrently with up to 8 parallel uploads
- Collect all file paths first, then batch the upload operations
- Use `asyncio.gather()` with a semaphore to control concurrency
Testing with real GCS buckets shows dramatic improvements:
- **Before**: 32.3 seconds (0.81s per file)
- **After**: 1.6 seconds (0.04s per file)
- **Speedup**: 20x faster ⚡
- **Before**: 249 seconds (4.2 minutes)
- **After**: 8.2 seconds
- **Speedup**: 30x faster 🚀
- …

Improve performance of uploads to GCP bucket

---

src/integrations/prefect-dbt/prefect_dbt/core/runner.py
src/integrations/prefect-dbt/tests/core/test_runner.py

The `PrefectDbtRunner` needs to look in the right part of the dbt manifest to determine whether an upstream node is a `SourceDefinition`, then skip certain operations like trying to collect compiled code if it is one.

Handle dbt source types and source manifest references

---

src/prefect/server/events/models/automations.py

For maximum performance from the API servers, we might want to delegate triggers/actions processing exclusively to background services. In that case, we will disable the triggers service on the API servers. But this will prevent automations change notifications to reach the background services.
Allow this by removing this old check.
Related to #18150

fix: allow automations notify when triggers service is disabled

---

docs/styles.css

Code blocks and links that were last children accidentally had their bottom borders disabled
Before:
After:

fixed styling of certain code blocks and links in docs

---

src/prefect/locking/memory.py
src/prefect/results.py
src/prefect/transactions.py
tests/test_transactions.py

These changes fix an error where running nested transactions across asyncio tasks caused an error when releasing a transactions lock. The default holder string contains the ID of the current task, so mixing tasks would result in mismatched holders on lock acquisition and release.
The fix is to generate a unique holder for each transaction, which is used to acquire and release the lock, and held for the duration of the transaction.
Closes https://github.com/PrefectHQ/prefect/issues/18600

Fixes async locking error by generating unique holder for each transaction

---

docs/v3/concepts/task-runners.mdx

* Fix the link to `ThreadPoolTaskRunner` docs

Fix link for ThreadPoolTaskRunner in Task Runners doc

---

docs/v3/api-ref/settings-ref.mdx
schemas/settings.schema.json
src/prefect/server/events/ordering/__init__.py
src/prefect/settings/models/server/events.py
tests/test_settings.py

These changes will allow users to configure their server to use the a Redis causal ordering implementation for HA setups.

Add setting to customize which causal ordering implementation to use

---

docs/v3/concepts/rate-limits.mdx

These changes update the rate limits and metadata retention docs to reflect the tiers added since these docs were last updated. I also removed redundant information and improved to overall flow.

Update rate limit and metadata retention docs

---

docs/v3/advanced/self-hosted.mdx

Add docs for additional ENVs that can be set for Redis authentication and SSL/TLS.
From discussion #18678

Add blurb for Redis auth

---

src/integrations/prefect-redis/pyproject.toml

Ensures that the `ConcurrencyLeaseStorage` protocol is available in the installed version of `prefect`

Bump minimum `prefect` version in `prefect-redis`

---

src/prefect/_experimental/bundles/__init__.py
tests/experimental/test_bundles.py

This PR updates bundle creation to exclude dependencies that were installed from a local wheel or code. These can't be installed in the execution environment, so we'll exclude them and warn that the user needs to ensure that the dependencies are available in the execution environment.

Update bundle creation to exclude dependencies installed from a local file path

---

docs/v3/api-ref/settings-ref.mdx

TIL mintlify reads anything between `$ .. $` as [inline math](https://mintlify.com/docs/text#inline-math), which caused the `profiles_path` description to render as LaTeX. Here's a quick fix for it!

docs: fix profiles_path rendering in settings ref

---

.github/workflows/integration-package-release.yaml

Will fix https://github.com/PrefectHQ/prefect/actions/runs/17250943676/job/48952780475. You need AWS credentials to validate a CloudFormation template.

Skip validating generated CloudFormation templates

---

docs/v3/release-notes/integrations/prefect-aws.mdx
src/integrations/prefect-aws/prefect_aws/observers/ecs.py

`mypy_boto3_sqs` isn't current behind an `if TYPE_CHECKING` guard, which is causing issues with the release that just went out.

Hotfix release 0.5.15 for `prefect-aws`

---

docs/v3/api-ref/python/prefect-server-events-triggers.mdx
src/prefect/server/events/triggers.py
tests/events/server/triggers/test_regressions.py

This PR adds handling for a specific timing scenario where the same event triggers both the start of a monitoring period and sets up an expectation for the next event (like tracking heartbeats to detect if a system crashes). When the system reaches the time limit for expecting the next event, it resets by clearing the current tracking data and starting fresh with the latest event.
I was moving over a fix from Cloud to make sure the triggering event was propagated in this special case. However I noticed this special handling was missing from OSS. I have included both changes in this PR.

Special case for proactive automation

---

src/prefect/utilities/services.py
src/prefect/workers/base.py
src/prefect/workers/process.py

Starts the metrics server (assuming `PREFECT_CLIENT_ENABLE_METRICS=True`) on workers.

Enable metrics server on workers

---

pyproject.toml
src/prefect/filesystems.py
tests/test_filesystems.py

This PR fixs #10694 and ensures that both `RemoteFileSystem` blocks using SMB protocol and `SMB` blocks works when creating new directories. 
This pull request addresses a bug in SMB path handling in the `write_path` method and adds a targeted test to prevent regressions. The main focus is on ensuring that SMB UNC paths are constructed correctly, avoiding duplication of the host in the path, which previously caused connection errors.
**Bug fix for SMB path handling:**
* Updated `write_path` in `prefect/filesystems.py` to strip the SMB host from the directory path when the base path starts with `smb://`, ensuring that the UNC path passed to …

More robust `write_path` method in `RemoteFileSystem` to handle SMB UNC paths. 

---

docs/v3/api-ref/python/prefect-context.mdx
src/prefect/context.py
tests/test_task_worker.py

This PR fixes a serialization error that occurs when calling `task.delay()` from within another task that was itself called with `.delay()`, when tasks are defined in separate modules.
- Fixes `TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'` error
- Applies same fix pattern used for FlowRunContext to TaskRunContext
- Removes global `serialize_as_any=True` and applies it only to result_store
Issue reported by a user in Slack where nested `task.delay()` calls would fail with `MockValSer` serialization errors when tasks were defined in separate module files.
- Modified `TaskRunContext.serialize()` in `src/prefect/context.py` to handle serialization correctly
- Added comprehensive unit tests that reproduce and verify the fix

Fix nested `.delay()` serialization issue

---

src/integrations/prefect-redis/prefect_redis/ordering.py

This log is often empty and makes it hard to find other logs.

Removes followers log from Redis `CausalOrdering` implementation

---

src/integrations/prefect-aws/prefect_aws/workers/ecs_worker.py
src/integrations/prefect-aws/tests/workers/test_ecs_worker.py

- Add custom capacity provider support: `ECSWorker` now accepts user-defined `capacityProviderStrategy` in the `task_run_request`.
- `launchType` now defaults only when neither `launchType` nor `capacityProviderStrategy` are provided. Special case: `FARGATE_SPOT` still requires both.
- Validation updates: Move the CloudWatch logs `executionRoleArn` check up so we can return early.
- Tests: Add coverage for capacity provider strategy with a provided launchType (verifies the warning and removal of launchType from the run request).
Relates to #13030 but needs support from Prefect employees to update the push worker.
Local test result successfully placing a task in a cluster with no active container instances in which the task is `PROVISIONING`:
- If no issue exists and your change is not a …

Support custom capacity provider

---

docs/docs.json

Fixes the 404 issue on docs.prefect.io/latest paths.
Our docs were returning 404s for all  paths due to recent changes to Mintlify's 404 behavior that no longer automatically redirects.
Per Mintlify support, adding `redirect: true` to docs.json restores the redirect behavior for the /latest path.
- Mintlify docs: https://www.mintlify.com/docs/settings#param-redirect

fix: add redirect setting to docs.json to fix /latest path 404s

---

ui-v2/src/components/flow-runs/flow-run-tags-select.test.tsx
ui-v2/src/components/flow-runs/flow-run-tags-select.tsx
ui-v2/src/components/ui/combobox/combobox.tsx
ui-v2/src/routes/dashboard.tsx

Summary
- Migrates dashboard filters to React
Technical details
- Dashboard search params are validated with zod and kept flat:
- `rangeType`, `seconds`, `start`, `end`, `aroundDate`, `aroundQuantity`, `aroundUnit`, `period`
- Normalized `from`/`to` always present for downstream queries.
- URL cleanup uses a typed `omitKeys` to avoid any-casts.
- Default date window set to last 24 hours on first load.
- Tag suggestions are sourced from `/flow_runs/paginate` (recent page) via react-query.
Related to #15512

[UI v2] Add dashboard filters

---

src/integrations/prefect-dbt/prefect_dbt/core/runner.py
src/integrations/prefect-dbt/prefect_dbt/utilities.py
src/integrations/prefect-dbt/tests/core/test_runner.py
src/integrations/prefect-dbt/tests/test_utilities.py

Closes #17555
The dbt SDK's `dbtRunner().invoke()` method only accepts global flags as kwargs, so for safety, we'll convert all kwargs to args. Kwargs that are duplicates of args are thrown away.

Handle dbt kwargs as args

---

src/prefect/_internal/compatibility/starlette.py
src/prefect/client/base.py
src/prefect/server/api/automations.py
src/prefect/server/api/concurrency_limits_v2.py
src/prefect/server/api/csrf_token.py
src/prefect/server/api/dependencies.py
src/prefect/server/api/deployments.py
src/prefect/server/api/events.py
src/prefect/server/api/flow_runs.py
src/prefect/server/api/server.py
src/prefect/server/api/task_runs.py
src/prefect/server/api/ui/schemas.py
src/prefect/server/api/ui/task_runs.py
src/prefect/server/api/validation.py
tests/cli/cloud/test_ip_allowlist.py
tests/client/test_base_client.py
tests/server/api/test_pagination.py
tests/server/api/test_server.py
tests/server/orchestration/api/test_block_documents.py
tests/server/orchestration/api/test_block_types.py
tests/server/orchestration/api/test_flow_runs.py
tests/server/orchestration/api/test_task_runs.py
tests/server/orchestration/api/test_work_queues.py
tests/server/orchestration/api/test_workers.py

This PR adds a compatibility wrapper for starlette status codes to handle the breaking changes introduced in starlette 0.48.0, which renamed several HTTP status codes per RFC 9110.
Instead of bumping the minimum starlette version requirement to 0.48.0, we're creating a compatibility layer that allows us to support both old and new versions.
- Created `src/prefect/_internal/compatibility/starlette.py` with a `status` object that:
- Maps old status code names to new ones automatically
- Falls back gracefully for older starlette versions  
- Prevents deprecation warnings
- Updated all imports throughout the codebase to use our compatibility layer instead of importing directly from starlette/fastapi
The main renamed codes handled are:
- `HTTP_422_UNPROCESSABLE_ENTITY` -> …

Add starlette status code compatibility layer

---

.github/workflows/auto-generate-docs.yaml

Trying to get to the bottom of why the auto-generation of docs is deleting so many files. This will need to be merged to `main` before we can run it manually, but it'll give us a good way to test changes to the workflow.

Add `workflow_dispatch` trigger to docs auto-generation workflow for testing

---

src/prefect/client/orchestration/_concurrency_limits/client.py
src/prefect/client/schemas/objects.py
src/prefect/concurrency/_asyncio.py
src/prefect/concurrency/asyncio.py
src/prefect/concurrency/sync.py
src/prefect/task_engine.py
tests/concurrency/test_concurrency_asyncio.py
tests/concurrency/test_concurrency_sync.py
tests/test_task_engine.py

This PR updates the task engine to use the GCL versions of the `concurrency` context managers. Note that this will require a server upgrade that migrates all tag-based concurrency limits to GCLs, along with a client upgrade. 
Using GCLs for tag-based concurrency will allow this method of concurrency limiting to use leasing, which will eliminate zombie slots for tag-based concurrency limits.
Related to #17415

Update task engine to use GCLs to limit task concurrency

---

src/prefect/settings/base.py
tests/test_settings.py

Closes #19028
- Override `PrefectBaseSettings._settings_warn_unused_config_keys` so Prefect’s TOML sources satisfy pydantic-settings 2.11’s unused-config check without renaming our public config keys
- Add a regression test covering the warning suppression when Prefect sources are configured
- If future pydantic builds remove that helper entirely, their own constructor stops invoking it; our override detects the missing base method and no-ops, so behaviour naturally follows whatever upstream replaces it with, and we could remove this static method as it would be dead code
<details>
```python
#!/usr/bin/env python
"""
Minimal reproduction for issue #19028
pydantic-settings==2.11 breaks Prefect logging setup
Looking at the user's traceback more carefully, it seems the issue is that
when …
```

Fix pydantic-settings 2.11+ compatibility warnings

---

src/integrations/prefect-kubernetes/prefect_kubernetes/observer.py

allows configuration of logging level per [typical `logging.yaml`](https://docs.python.org/3/library/logging.config.html)

remove log level set in kubernetes observer

---

.github/workflows/static-analysis.yaml
src/prefect/runner/runner.py
src/prefect/utilities/callables.py
src/prefect/workers/process.py
tests/runner/test_runner.py

This PR updates the `Runner` class to maintain a dictionary of flow instances for deployments that have been registered with the `Runner`. This enables flows like the following to be successfully served and run:
```python
import time
class MyClass:
def __init__(self):
self.sleep_time = 60
def my_method(self, override_sleep_time: int | None = None):
sleep_time = override_sleep_time or self.sleep_time
print(f"Sleeping for {sleep_time} seconds")
time.sleep(sleep_time)
print("Done sleeping")
my_class = MyClass()
my_class.my_method.serve(name="served-from-instance")
```

Allow serving instance methods
