PrefectHQ/prefect

changes/pr3717.yaml
src/prefect/environments/storage/docker.py
tests/environments/storage/test_docker_storage.py

Fixes bug introduced in #3693 where an error is raised due to `None` values during docker storage build output parsing.
- Adds a default for `output` as an empty string instead of `None`
- Changes output parsing to a static method (does not use `self`)
- Adds test coverage for output parsing
Bugfix
This PR:

Fix docker storage bug when output is `None`

---

changes/pr3726.yaml
src/prefect/tasks/gcp/bigquery.py

Fix unused location parameters in bigquery tasks.
Changed to use location parameters when calling `load_table_from_uri` method and `load_table_from_file` method.
Location parameters in bigquery tasks are ignored.
This PR:

Fix using location parameter

---

changes/pr3725.yaml
src/prefect/tasks/jupyter/jupyter.py
tests/tasks/jupyter/sample_notebook.ipynb
tests/tasks/jupyter/test_jupyter.py

ExecuteNotebook task now takes an optional `exporter` argument that (when provided) is used to export the notebook.
Fixes #3687
The ExecuteNotebook task now takes an optional `exporter` argument that (when provided) is used to export the notebook.
This allows for custom exporters to any format, and not just html or json. In addition, it allows for an html-export with non-default HTMLExporter arguments.
This PR:

Allow custom exporter for ExecuteNotebook task 

---

changes/pr3724.yaml
src/prefect/tasks/gcp/bigquery.py

Fix issue #3657 
After remove `_client` and `_completion_lock`, the LoadJob object is pickleable.
```python
import cloudpickle
from google.cloud import bigquery
client = bigquery.Client()
table_ref = client.dataset('dataset').table('table')
job_config = bigquery.LoadJobConfig(
source_format=bigquery.SourceFormat.CSV,
)
with open('data.csv', 'rb') as f:
load_job = client.load_table_from_file(
f,
table_ref,
job_config=job_config,
)
load_job.result()
load_job._client = None
load_job._completion_lock
cloudpickle.dumps(load_job)
```
Override unpickleable attributes with None before return from the run method.
This PR:

Fix PicklingError in BigQueryLoadFile and BigQueryLoadGoogleCloudStorage #3657

---

docs/core/development/documentation.md
docs/generate_docs.py
docs/outline.toml
docs/test_generate_docs.py

Previously any non `_`-prefixed method in a class was documented as part
of the api docs. For things like agents (which are more an application
than a class), there were several non-public methods that aren't
`_`-prefixed. Having these in the api docs led some users to be
confused, thinking they could call those internal methods directly.
We now add a way to specify a set of methods to document, and apply this
to the agent api docs to only document the `start` methods.

Hide private methods in api docs

---

changes/pr3632.yaml
src/prefect/client/client.py
src/prefect/utilities/graphql.py
tests/client/test_client.py
tests/utilities/test_graphql.py

Displays the content of GraphQL error responses. Builds on #3615 
It looks like when Apollo sends a 400 response it always attaches some error information in the response.text section as a json blob. This json is a list of errors that include messages of what is actually wrong which is really helpful for determining what went wrong with your query.
- Adds GraphQL error response text parsing and formatting
- Adds GraphQL error check and display to Client._send_request
Error messages are hidden without entering a debugger
This PR:
```
ClientError: 400 Client Error: Bad Request for url: https://api-dev.prefect.io/graphql
The following error messages were provided by the GraphQL server:
GRAPHQL_VALIDATION_FAILED: Cannot query field "flow_run" on type "flow". Did you
mean "flow_runs", …
```

Display graphql error messages on failure

---

changes/pr3741.yaml
src/prefect/engine/result_handlers/gcs_result_handler.py
src/prefect/engine/results/gcs_result.py
tests/engine/results/test_gcs_result.py

Fix deprecated method.
Replace deprecated [download_as_string](https://googleapis.dev/python/storage/latest/blobs.html#google.cloud.storage.blob.Blob.download_as_string) method with download_as_bytes method.
This PR:

Replace deprecated download_as_string method with download_as_bytes method

---

changes/pr3732.yaml
src/prefect/tasks/gcp/storage.py
tests/tasks/gcp/test_gcs_copy.py
tests/tasks/gcp/test_gcs_upload_download.py

Support timeout option for GCS operations.
I used `request_timeout` as a parameter name instead of `timeout` since Task class already used it.
Add `request_timeout` parameter to these task classes.
- `prefect.tasks.gcp.storage.GCSBaseTask`
- `prefect.tasks.gcp.storage.GCSDownload`
- `prefect.tasks.gcp.storage.GCSUpload`
- `prefect.tasks.gcp.storage.GCSCopy`
Uploading or downloading large file may exceeds default timeout (60s).
This PR:

Support timeout option in GCS tasks

---

changes/issue3306.yaml
src/prefect/environments/execution/dask/k8s.py
src/prefect/tasks/gcp/bigquery.py
src/prefect/tasks/jupyter/__init__.py

- Added from on each raised exception in:
- `src/prefect/environments/execution/dask`.
- `src/prefect/tasks/gcp`.
- `src/prefect/tasks/jupyter`.
- Changes based on #3306 for the aforementioned sub-modules.
- Improves stack trace when debugging errors by using clearer language.
This PR:

Explicit exception chaining for gcp and jupyter tasks and dask execution

---

changes/pr3746.yaml
src/prefect/agent/docker/agent.py
src/prefect/agent/ecs/agent.py
src/prefect/agent/kubernetes/agent.py
tests/agent/test_docker_agent.py
tests/agent/test_ecs_agent.py
tests/agent/test_k8s_agent.py

For flow runs deployed by the k8s, ECS, and docker agent, we now add the
image used by the flow run to the environment as
`PREFECT__CONTEXT__IMAGE`. This lets users access the flow-run image
inside the flow run as `prefect.context.image`.
This can be used when creating a `DaskExecutor` to ensure the dask
cluster uses the same image as the flow runner (where the dask client
lives). For example:
```python
import prefect
from dask_cloudprovider.aws import FargateCluster
from prefect.engine.executors import DaskExecutor
executor = DaskExecutor(
cluster_class=lambda: FargateCluster(image=prefect.context.image),
adapt_kwargs={"maximum": 10},
)
```

Add `image` to `prefect.context` for flow runs

---

changes/pr3748.yaml
src/prefect/utilities/agent.py
tests/utilities/test_agent.py

When deploying Flows built off, e.g., the master branch of Prefect, the default image logic pointed to an image that doesn't exist.  This PR falls back to the nearest tag, as determined by versioneer, for the default image to use.
Fixes edge case
This PR:

Fix agent default image when using a non tagged commit

---

changes/issue3618.yaml
src/prefect/engine/state.py
tests/engine/test_state.py

A flow like the following would fail in cases where `b` attempts to load the result from the upstream.
```python
@task
def a():
return None
@task
def b(foo):
print(foo)
result = LocalResult(
location="{flow_name}/"
"{scheduled_start_time:%d-%m_%H-%M-%S}/"
"{task_full_name}-{task_run_id}.prefect_result",
)
```
In a normal run when a task returns `None` a result isn't written and the location is also set to `None`. In the state `load_results` function it sees that the location is None and then also attempts to use the original default (unformatted) location from the upstream state's result. 
Removes the getattr for the default result location because there shouldn't be a case where the result doesn't already have a location serialized if needed.
Closes #3618
This PR:
cc @cicdw

Fix state attempting to read result from absent upstream result

---

changes/pr3750.yaml
docs/orchestration/flow_config/run_configs.md
docs/outline.toml
src/prefect/agent/agent.py
src/prefect/agent/docker/agent.py
src/prefect/agent/ecs/agent.py
src/prefect/agent/kubernetes/agent.py
src/prefect/agent/local/agent.py
src/prefect/client/client.py
src/prefect/core/flow.py
src/prefect/run_configs/__init__.py
src/prefect/run_configs/base.py
src/prefect/run_configs/kubernetes.py
src/prefect/serialization/run_config.py
src/prefect/utilities/agent.py
tests/agent/test_docker_agent.py
tests/agent/test_ecs_agent.py
tests/agent/test_k8s_agent.py
tests/agent/test_local_agent.py
tests/client/test_client.py
tests/core/test_flow.py
tests/run_configs/test_universal.py
tests/serialization/test_run_configs.py
tests/utilities/test_agent.py

This adds support for flows with no `environment` AND no `run_config`.
Currently all flow's have an environment created by default. If a user explicitly sets a `run_config` on a flow, the new `run_config` based configuration is used, otherwise the default `environment` is used.
In 0.14.0 we plan to remove the default `environment`, so flow's will by default have `run_config=None, environment=None`. This change adds support for that, without removing the default (yet).
The new logic is now:
- If a flow has a run-config configured, use that. Agents check that the run-config set on the flow matches the type they support.
- If a flow has no environment, the agent will create the default `RunConfig` for that agent type. This means that a flow registered with no `run_config` configured on it is …

Support for flows with `flow.environment = None`

---

changes/issue3343.yaml
docs/core/idioms/file-based.md
docs/orchestration/execution/storage_options.md
docs/orchestration/flow_config/storage.md
docs/outline.toml
setup.py
src/prefect/agent/local/agent.py
src/prefect/environments/storage/__init__.py
src/prefect/environments/storage/bitbucket.py
src/prefect/serialization/storage.py
src/prefect/utilities/git.py
tests/agent/test_local_agent.py
tests/environments/storage/test_bitbucket_storage.py
tests/serialization/test_storage.py
tests/utilities/test_git.py

Add support for Bitbucket as a file-based storage option alongside GitHub and GitLab.
Uses atlassian-python-api package ([https://github.com/atlassian-api/atlassian-python-api]) to allow Bitbucket to be used as a storage option.
Implementation is identical to GitLab but includes additional argument necessary for Bitbucket:
- 'project' : Bitbucket organizes repositories into Projects and each repo requires an associated project
Bitbucket is a popular Git distribution and support has been requested (Issue #3343).
This PR:

Add Bitbucket storage

---

changes/codecommit.yaml
changes/pr3733.yaml
docs/orchestration/execution/storage_options.md
docs/orchestration/flow_config/storage.md
docs/outline.toml
src/prefect/environments/storage/__init__.py
src/prefect/environments/storage/codecommit.py
src/prefect/serialization/storage.py
tests/agent/test_local_agent.py
tests/environments/storage/test_codecommit_storage.py

Adds the ability to use AWS CodeCommit as a storage option
An additional storage option has been added, which builds on the AWS functionality of the S3 storage option
Enables AWS CodeCommit users to incorporate git storage into flows
This PR:

Add AWS CodeCommit storage option

---

docs/.vuepress/config.js
docs/orchestration/flow_config/executors.md
docs/orchestration/flow_config/overview.md
docs/orchestration/flow_config/run_configs.md

- Adds a new page to the docs on configuring an executor for a flow, and the various options available
- Fixes a few broken links in the run-config docs

Add docs section on executor configuration for a flow

---

changes/issue3747.yaml
src/prefect/agent/kubernetes/agent.py
tests/agent/test_k8s_agent.py

Related to some of the points outlined in #3747 
This adds a step to the k8s agent's `manage_jobs` to report on failed jobs and container errors. Previously if there were a container errors the flow run would stay in a running state until it was picked back up by lazarus and repeated multiple times. Now if there are container errors causing to pod failure it will be reported. Also the container status is reported as a log in this case.
Example:
Open to enhancements that would make this particular action more beneficial / any other information we can expose.
Adds a step to the k8s agent's `manage_jobs` to report on failed jobs and container errors.
More efforts to remove any black boxes in flow deployment!
This PR:

Surface pod failures and container errors in jobs deployed with the Kubernetes Agent

---

changes/pr3764.yaml
src/prefect/environments/storage/github.py

Fixes a UX bug where the docs stated the `ref` field on GitHub storage would default to `master` but that wasn't happening.
Defaults the `GitHub` storage ref to `master`, as stated in the doc string. 
The docs state this string is optional and will default to `master`, which is the default GitHub branch - this wasn't performing as expected. 
This PR:

Set master as the default github storage ref

---

changes/pr3770.yaml
requirements.txt
src/prefect/engine/executors/dask.py
tests/engine/executors/test_executors.py

Previously when running with a `DaskExecutor` connected to an external
dask cluster (one with an `address` passed in), a temporary
`distributed.Variable` was used to check if the task's flow-run was
still active. Before each prefect task started, it would check this
variable to determine if it should actually run. This helped provide a
stronger cancellation mechanism than distributed currently provides
(tasks submitted to distributed can be cancelled only if they haven't
arrived at a worker yet).
This worked well for many workloads, but ran into corner cases on
clusters experiencing high load:
- Distributed's comms can have some flaky behavior under high load,
leading to periodic connection errors. These can be remedied by
bumping the connection timeout, but not all users know to do that. …

More robust cancellation on Dask

---

changes/pr3761.yaml
src/prefect/configuration.py
tests/core/test_task.py
tests/test_configuration.py

If the default task timeout is set in the config, it is parsed into a `timedelta`, but the task initializer enforces that the type is an `int`
- Removes type casting of config task timeout values
Bugfix
This PR:

Update config parsing to not convert timeouts to timedelta

---

changes/pr3753.yaml
docs/outline.toml
examples/task_library/great_expectations/great_expectations_flow.py
src/prefect/tasks/great_expectations/__init__.py
src/prefect/tasks/great_expectations/checkpoints.py
tests/tasks/great_expectations/test_great_expectations_validation.py

This is a continuation of #3766 because I was having issues pushing to the remote branch. Original PR content:
Some tweaks to the RunGreatExpectationsCheckpoint task (including renaming...) to clarify the types of parameters that can be used to run validation. See discussion for context: https://github.com/PrefectHQ/prefect/discussions/3558
**This is untested, I just wanted to propose the change and discuss!**
I think there was some confusion around the use of "checkpoint"! A checkpoint is basically just a pre-configured "bundle" of batch_kwargs + suite name, so it can be used instead of those pairs to run validation. It looks like it was confused with a "validation_operator", which is basically just a pointer to some actions that happen after validation (by default: store the results, …

Make RunGreatExpectationsCheckpoint task accept different parameters (extends #3766)

---

examples/task_library/great_expectations/great_expectations_flow.py
src/prefect/tasks/great_expectations/__init__.py
src/prefect/tasks/great_expectations/checkpoints.py
tests/tasks/great_expectations/test_great_expectations_validation.py

Some tweaks to the RunGreatExpectationsCheckpoint task (including renaming...) to clarify the types of parameters that can be used to run validation. See discussion for context: https://github.com/PrefectHQ/prefect/discussions/3558
**This is untested, I just wanted to propose the change and discuss!**
I think there was some confusion around the use of "checkpoint"! A checkpoint is basically just a pre-configured "bundle" of batch_kwargs + suite name, so it can be used instead of those pairs to run validation. It looks like it was confused with a "validation_operator", which is basically just a pointer to some actions that happen after validation (by default: store the results, render data docs). I made some tweaks to reflect this better in the code:
- Renamed the task to …

Make RunGreatExpectationsCheckpoint task accept different parameters

---

docs/orchestration/server/deploy-local.md

Minor documentation change
Shows the correct path to the config file
Important because if your config file is in the wrong location, the server won't pick it up. And you might have to clear data from your browser before if will pick it up from the correct location in the future if you do it wrong the first time.
This PR:
(No checkboxes needed for this documentation change)

Update path to config file in docs

---

changes/pr3778.yaml
src/prefect/agent/kubernetes/agent.py
src/prefect/cli/agent.py
src/prefect/run_configs/kubernetes.py
src/prefect/serialization/run_config.py
tests/agent/test_k8s_agent.py
tests/cli/test_agent.py
tests/run_configs/test_kubernetes.py
tests/serialization/test_run_configs.py

- Adds `service_account_name`/`image_pull_secrets` to `KubernetesRun` run-configs.
- Adds kubernetes agent CLI `--service-account-name`/`--image-pull-secrets` flags for configuring the same values at the agent level
This makes it easier to configure these common options without requiring the user write a job template to replace the default.
This PR:

Add `service_account_name`/`image_pull_secrets`

---

docs/generate_docs.py

Currently in some of the API docs when rendering defaults with the class's `repr` it will cause it to not render due to the use of `<` and `>`. 
Current:
With fix:

Replace characters in API doc build that cause rendering issues

---

src/prefect/cli/auth.py

Adds a small note to auth login error messages about providing USER scoped tokens

Clarify use of USER tokens in auth login CLI command

---

changes/pr3800.yaml
changes/prlbl.yaml
src/prefect/agent/local/agent.py
src/prefect/cli/agent.py
src/prefect/storage/azure.py
src/prefect/storage/gcs.py
src/prefect/storage/github.py
src/prefect/storage/gitlab.py
src/prefect/storage/s3.py
src/prefect/storage/webhook.py
tests/agent/test_local_agent.py
tests/cli/test_agent.py
tests/environments/execution/test_dask_cloud_provider.py
tests/storage/test_webhook_storage.py

`0.14.0`: Removes the default labels on all storage options that had them and on the local agent. This does not, however, remove the hostname label on the local storage and local agent.
- Removed setting of default labels on storage objects and the local agent
- Removed `storage_labels` boolean kwarg from local agent
- Removed `--storage-labels` option from agent `start` CLI command
This has been a slightly confusing safety net that is no longer necessary now that all storage options can be used with all agents.
This PR:

Remove default labels on storage types and local agent

---

.circleci/config.yml
Dockerfile
changes/pr3804.yaml
codecov.yml
docs/core/getting_started/installation.md
docs/orchestration/execution/storage_options.md
setup.py
src/prefect/client/client.py
src/prefect/storage/docker.py
src/prefect/utilities/agent.py
tests/agent/test_docker_agent.py
tests/agent/test_ecs_agent.py
tests/agent/test_k8s_agent.py
tests/client/test_client.py
tests/storage/test_docker_storage.py
tests/utilities/test_agent.py

With `0.14.0` approaching we have the opportunity to better package dependencies in our base image. This PR makes various updates to some CI steps (including tests and image builds). It also updates places where the previous `all_extras` image was being used.
**Note**: We should cut a release candidate of `0.14.0` to ensure that the image building jobs function properly.
- Adds CI job for only testing the task library
- Ignores testing the task library in the 3.6-9 jobs
- Removes building the `all_extras` Docker image
- Adds a build of the `core` image that only contains the prefect core base dependencies
- Adds all orchestration extras to the standard `prefect/prefect` image
- Docker storage now installs all orchestration dependencies
- Deployed flows now default to using the …

Refactor dependencies included in Docker images

---

changes/pr3805.yaml
src/prefect/agent/kubernetes/agent.py
src/prefect/agent/kubernetes/job_template.yaml
tests/agent/test_k8s_agent.py

- Drops `command` from default k8s job template. We now pass in the
`prefect execute flow-run` command as a list (rather than a string),
making it compose better with existing entrypoints.
- Drops `restartPolicy` from default template, setting it
programmatically instead (default is `Never`).
Prefect now makes no assumptions about the default template, the user
can fill it in how they see fit. This makes it easier for the user to
customize a k8s deployment.
Fixes #3787.
This PR:

Simplify default k8s job template

---

changes/pr3806.yaml
src/prefect/core/flow.py
src/prefect/utilities/diagnostics.py
src/prefect/utilities/storage.py
tests/client/test_client.py
tests/core/test_flow.py
tests/utilities/test_diagnostics.py

Previously all flows had a `flow.environment` field created by default.
This has now been removed - use of the legacy `Environment` based
configuration is now opt-in only. Users who weren't setting
`flow.environment` explicitly before should transition automatically to
using the new `flow.run_config` based configuration without any changes
on their part.
This PR:

Remove default creation of `flow.environment`

---

changes/pr3808.yaml
src/prefect/core/flow.py
tests/core/test_flow.py

Adds a warning when registering a flow that is using the legacy
`flow.environment` based configuration but also sets a `flow.executor`
(which will thus be ignored at runtime).
This PR:

Add warning if mixing `environment` and `executor` config

---

changes/pr3811.yaml
src/prefect/environments/execution/__init__.py
src/prefect/environments/execution/base.py
src/prefect/environments/execution/dask/cloud_provider.py
src/prefect/environments/execution/dask/k8s.py
src/prefect/environments/execution/fargate/fargate_task.py
src/prefect/environments/execution/k8s/job.py
src/prefect/environments/execution/local.py
tests/environments/execution/__init__.py
tests/environments/execution/test_base_environment.py
tests/environments/execution/test_dask_cloud_provider.py
tests/environments/execution/test_dask_k8s_environment.py
tests/environments/execution/test_fargate_task_environment.py
tests/environments/execution/test_k8s_job_environment.py
tests/environments/execution/test_local_environment.py

Adds a warning on init to all `Environment` classes, and updates the
docstrings appropriately.
This PR:

Add deprecation warning to environments

---

changes/pr3812.yaml
setup.cfg
src/prefect/agent/fargate/agent.py
src/prefect/cli/agent.py
tests/agent/test_fargate_agent.py
tests/cli/test_agent.py
tests/environments/execution/__init__.py
tests/environments/execution/test_base_environment.py
tests/environments/execution/test_dask_cloud_provider.py
tests/environments/execution/test_dask_k8s_environment.py
tests/environments/execution/test_fargate_task_environment.py
tests/environments/execution/test_k8s_job_environment.py
tests/environments/execution/test_local_environment.py

Adds a deprecation warning to programmatic use of `FargateAgent`, and a
warning message to CLI usage of `prefect agent fargate start`/`prefect
agent start fargate`. Docs have been updated as well.
Also changes how we silence expected warnings in tests to be more
thorough.
This PR:

Deprecate the Fargate Agent

---

changes/pr3814.yaml
src/prefect/agent/kubernetes/agent.py

Previously the k8s agent was customized using environment variables that
don't really match with how prefect config works. For new
`KubernetesRun` configured deployments, all agent-level options have
CLI flags for configuring that are preferred. To make the upgrade
process easier for users, we continue accepting the old envvar style
options in the case the CLI flags weren't specified.
This PR:

Accept old envvar config uniformly in k8s agent

---

src/prefect/serialization/environment.py
tests/serialization/test_environments.py

The class was removed, but we still need deserialization not to error. Follow up for #3821.

Re-add support for deserializing `RemoteDaskEnvironment`

---

changes/pr3829.yaml
src/prefect/tasks/great_expectations/checkpoints.py

Hi. I wanted to receive artifact reports for my GreatExpectations validation even if the validation fails. 
Solution is to simply move the creation of markdown artifact in RunGreatExpectationsValidation up so it is created even when success check fails and thus returns with state FAIL.
Creates the artifact even if validation fails (which I think is important).
This PR:
- [ x] adds a change file in the `changes/` directory (if appropriate)

Move creation of markdown artifact in RunGreatExpectationsValidation up so it is created even when validation fails

---

src/prefect/cli/register.py
tests/cli/test_register.py

Updates the `prefect register flow` command to pass labels to the register call. Currently calling w/o any run config or environment would error because the UniversalRun isn't added until later. Simply passing in the labels this way fixes that and achieves the same behavior as before. (also updates a test)
No changes entry necessary since this was brought about due to a change in master

Properly pass labels to register call in CLI command

---

src/prefect/cli/execute.py

In the case where there is no run config on a flow object and the flow is stored using file-based storage then the execute command will previously error. This is due to the fact that the run config needs to be loaded off of the backend metadata (just like storage is) in order to retrieve the `UniversalRun` default.
No changes entry necessary since this was brought about due to a change in master

Load run config from backend on execute

---

src/prefect/serialization/flow.py

Call `parameters()` to fetch flow parameters.
It's better to call `parameters()` to fetch parameters of a flow, so user can inherit Flow class and rewrite parameters method.
For me, my flow contains a huge number of parameters, since Parameter is a Task, it takes 20s ~ 30s to run these tasks to fetch parameters.
So I create a new Parameter class (just a namedtuple) and a subclass of Flow, rewrite the `parameters` method, a subclass of FunctionTask to fetch parameters directly from `context['parameters']`.
It works fine, except I can't register to the server, because the flow serialize with `get_parameters` and it fetch parameters without calling `parameters()`
This PR:

Fetch flow parameters by calling parameters()

---

docs/.vuepress/config.js
docs/orchestration/execution/custom_environment.md
docs/orchestration/execution/dask_cloud_provider_environment.md
docs/orchestration/execution/dask_k8s_environment.md
docs/orchestration/execution/fargate_task_environment.md
docs/orchestration/execution/k8s_job_environment.md
docs/orchestration/execution/local_environment.md
docs/orchestration/execution/overview.md
docs/orchestration/execution/storage_options.md
docs/orchestration/flow_config/upgrade.md

Adds a docs section on upgrading from `flow.environment` based config to
using `flow.run_config` instead. Includes short examples for each
existing environment.

Add docs section on upgrading to 0.14.0

---

Dockerfile
changes/pr3839.yaml
docs/orchestration/agents/local.md

Without an init process like `tini`, long running Prefect jobs can
sometimes end up creating lots of zombie processes. Adding an init
process to reap these fixes this. This is a problem in containerized
instances only, non-containerized systems already have an init process
running and aren't affected.
This PR:

Add `tini` to the dockerfile

---

changes/pr3840.yaml
src/prefect/agent/kubernetes/agent.py
src/prefect/agent/kubernetes/deployment.yaml
src/prefect/cli/agent.py
tests/agent/test_k8s_agent.py
tests/cli/test_agent.py

The Kubernetes resource manager was officially deprecated in `0.13.5` and all of its functionality (plus more) now exists inside the agent process. This PR removes the kwargs for setting the resource manager on the k8s agent install command however it does not fully remove the resource manager code as to not yet break any existing deployments that may be using it.
Remove option to enable deprecated resource manager in `prefect agent kubernetes install` command.
First step in removing this deprecated code.
This PR:

Remove references to deprecated resource manager in install agent CLI command

---

changes/issue3846.yaml
src/prefect/engine/results/azure_result.py
tests/engine/results/test_azure_result.py

Closes #3846 
Fix the Azure result read function that was not previously decoding blob contents as bytes.
Fix functionality
This PR:

Fix Azure result byte decoding

---

changes/pr3850.yaml
src/prefect/tasks/prefect/flow_run.py

Fix StartFlowRun in Prefect Cloud
Pass `as_user=False` when [using `client.get_cloud_url` in `StartFlowRun`](https://github.com/PrefectHQ/prefect/blob/8ada99fa7e8cfad12cf793f62b57926d3bf071bf/src/prefect/tasks/prefect/flow_run.py#L172).
I'm not sure if this works locally (ie: local flow -> Cloud flow) or if we need more logic - hoping you all will have a quicker gut instinct. 😁 Related, any pointers on how to test this (or how the existing tests pass)?
I'm traveling the next few days and will try to turn things around, but also alright if others take over.
`StartFlowRun` would fail when running in Prefect Cloud.
This PR:

Fix StartFlowRun in Prefect Cloud

---

changes/pr3857.yaml
src/prefect/utilities/aws.py
tests/utilities/test_aws.py

Using the AWS utility to get a boto3 client like this
```python
get_boto_client(
resource="not a real resource",
credentials={"ACCESS_KEY": "true_key", "SECRET_ACCESS_KEY": "true_secret"},
aws_access_key_id="id",
aws_secret_access_key="secret",
aws_session_token="session",
)
```
will currently fail due to the kwargs `.pop` not being called because it is only popped if no other credentials have been provided. Thus it was causing the issue where the variables to initialze the client could be passed in twice, leading to an error.
```
File "/......./prefect/utilities/aws.py", line 55, in get_boto_client
return boto3.client(
TypeError: boto3.client() got multiple values for keyword argument 'aws_access_key_id'
```
Issue originally raised in slack thread …

Fix duplicate provided kwargs in aws utility

---

changes/pr3869.yaml
src/prefect/core/flow.py
src/prefect/tasks/core/resource_manager.py
tests/tasks/core/test_resource_manager.py

This makes the `setup` method optional for resource managers, allowing
creation of resource managers that only run a cleanup action on exit
from a block. This produces a slightly nicer graph in these cases, since
the `setup` task isn't needed.
Fixes #3841.
This PR:

Make `setup` method optional for resource managers

---

changes/issue3870.yaml
src/prefect/engine/results/gcs_result.py
src/prefect/storage/gcs.py
src/prefect/tasks/gcp/storage.py
src/prefect/utilities/filesystems.py
tests/storage/test_gcs_storage.py

Use `download_as_string` if `download_as_bytes` isn't available.
Fixes #3870.
This PR:

Support GCS versions < 1.31.0

---

changes/pr3884.yaml
src/prefect/agent/kubernetes/agent.py
tests/agent/test_k8s_agent.py

Previously these were inserted at the wrong level in the k8s agent.
Updates code and tests appropriately.
This PR:

Fixup imagePullSecrets/serviceAccountName in k8s agent

---

changes/pr3885.yaml
src/prefect/utilities/filesystems.py
tests/utilities/test_filesystems.py

Previously this would erroneously pass in the file key with a leading `/`, leading to api errors. I could have sworn we QA'd this against a real deployment months ago and it worked, but apparently not. I've tested this against a real S3 bucket and can confirm things are working appropriately.
Fixes #3876.
This PR:

Fixup read_bytes_from_path on s3

---

changes/pr3892.yaml
src/prefect/tasks/prefect/flow_run.py
tests/tasks/prefect/test_flow_run.py

- Adds `idempotency_key` as a kwarg to `StartFlowRun` constructor for
parity with its use in `run`.
- Changes the default `idempotency_key` to use `task_run_id` instead of
`flow_run_id`. The previous default would lead to only a single flow
run being created if multiple `StartFlowRun` tasks were created for
the same flow without relying on mapping.
This PR:

Fix `StartFlowRun` idempotency_key

---

changes/pr3893.yaml
src/prefect/agent/docker/agent.py
tests/agent/test_docker_agent.py

Adds the following labels to all flows deployed by the docker agent.
This is useful tools that monitor docker deployments by label.
- `io.prefect.flow-name`: the full flow name
- `io.prefect.flow-id`: the full flow id
- `io.prefect.flow-run-id`: the full flow run id
See https://docs.docker.com/config/labels-custom-metadata/ for more
information on docker labels.
Fixes #3819.
This PR:

Add container labels to docker agent

---

docs/orchestration/concepts/flows.md
docs/orchestration/execution/storage_options.md
docs/orchestration/flow_config/storage.md
docs/orchestration/server/deploy-local.md

- Remove docs on automatic storage labels, these are no longer relevant
- Remove note on `version_group_id` being deprecated
- Fix link in server docs

Assorted docs cleanups

---

.gitignore

This PR proposes adding some rules to .gitignore to prevent sensitive information like passwords and access keys from being checked into source control.
I've added common extensions for key material, plus the specific files that the AWS CLI docs encourage people to create: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html.
This PR will make it harder for contributors to accidentally expose sensitive information by checking it into source control. I think it's unlikely that such changes would make it past pull request review, but even showing up in a PR diff is still problematic.
I didn't add a changelog entry since this is just administrative stuff for this repo and won't impact users.

add credentials to .gitignore

---

changes/pr3903.yaml
src/prefect/agent/agent.py
src/prefect/client/client.py
src/prefect/tasks/prefect/flow_run.py
src/prefect/utilities/agent.py
tests/agent/test_docker_agent.py
tests/agent/test_ecs_agent.py
tests/agent/test_k8s_agent.py
tests/agent/test_local_agent.py
tests/client/test_client.py
tests/tasks/prefect/test_flow_run.py
tests/utilities/test_agent.py

This adds support for per-flow-run `run_config`. This shouldn't be merged until upstream support is finished (server PR is https://github.com/PrefectHQ/server/pull/166).
From a core interface perspective, there's only 2 user-facing changes
- Addition of `run_config` parameter in `Client.create_flow_run`
- Addition of `run_config` parameter in `StartFlowRun` task
Part of #3858.
This PR:

Per flow run run config

---

changes/pr3916.yaml
src/prefect/utilities/aws.py
tests/utilities/test_aws.py

Allow the usage of `profile_name` on the `get_boto_client` method.
This PR aims to allow users to define a `profile_name` to be used on the boto3 sessions.
The `profile_name` could be used to access different secrets or AWS resources based on profiles.
```python
AWSSecretsManager(
secret='prefect/dummy',
boto_kwargs={
'use_session': True,
'profile_name': 'MyAwsProfile',
'region_name': 'us-east-1'
}
)
```
The current code doesn't allow to specify profile names when working with AWS. This could allow using different profiles on different flows.
This PR:

:key: - Allow the usage of a profile_name on get_boto_client

---

changes/pr3918.yaml
src/prefect/__main__.py
src/prefect/agent/local/agent.py
src/prefect/engine/cloud/flow_runner.py
tests/agent/test_local_agent.py
tests/engine/cloud/test_cloud_flow_runner.py

Updates all `prefect ...` commands run by the agents/flow runners to
execute using a full python executable path. This lets prefect run
without having the `prefect` CLI on path.
Also makes `prefect` an executable module, so users can do
`path/to/python -m prefect ...` instead of `prefect ...` and things
should just work.
Fixes #3779.

Support running without prefect on path

---

changes/pr3920.yaml
src/prefect/utilities/tasks.py
tests/utilities/test_tasks.py

Fixes accidental cycle creation in `apply_map` in cases where a `case`
statement is mapped over a task that isn't used elsewhere in the
sub-flow beforehand. This was due to the args to `apply_map` not being
added to the subflow before the mapped function is called, causing the
logic in the `case` statement to automatically add erroneous edges to
these tasks.
Fixes #3890.

Fix cycle creation in apply_map

---

changes/pr3923.yaml
src/prefect/storage/local.py
tests/storage/test_local_storage.py

Changes the default storage path for `Local` storage to `~/.prefect/flows/{flow_name}/{timestamp}` from `~/.prefect/flows/{flow_name}.prefect`. This makes it possible to have multiple active local flows with the same name using the default storage scheme, and better matches the other storage classes.
Also includes a few small test cleanups in the 2nd commit.
Fixes #3900.

Add timestamp to default local storage path

---

changes/pr3924.yaml
src/prefect/utilities/context.py
tests/test_context.py

This fixes a bug in the contextmanager for `prefect.context` where
exiting the context would overwrite any values set in
`prefect.config.context` with their original config values (ignoring any
explicit values passed in at runtime). This was due to two things:
- The `Context` constructor being implicitly called when stashing a
temporary context away in the `contextmanager`. This is fixed by
avoiding creating temporary `Context` objects (which is also more
efficient).
- Values set on `prefect.config.context` being prioritized over values
explicitly set when creating `prefect.context`. This logic ordering is
fixed in the constructor.
New tests are added that would have caught this bug.
Fixes #3828.
This PR:

Fix bug in `prefect.context`

---

changes/pr3933.yaml
src/prefect/cli/docker-compose.yml

When `prefect server start` is given a custom graphql host port `--graphql-port 4303`, the apollo service hangs forever because the health check fails. This is because the docker-compose file sets `GRAPHQL_SERVICE_PORT` to `GRAPHQL_HOST_PORT` when it should be just be the hardcoded internal port of `4201` 
- Hardcodes `GRAPHQL_SERVICE_PORT` to `4201` in `docker-compose.yaml`
Fixes bug where the apollo service hangs when the graphql host port is changed.
See also https://github.com/PrefectHQ/server/pull/172
This PR:

Fix docker-compose with custom graphql host port

---

docs/core/faq.md

Fixes the wrong link at https://docs.prefect.io/core/faq.html#do-you-have-an-integration-for-service-x, that should link to https://docs.prefect.io/core/task_library/overview.html
The wrong link at https://docs.prefect.io/core/faq.html#do-you-have-an-integration-for-service-x to task overview.
Well I wouldn't call it "important", but it's nice when links work correctly
This PR:

fix wrong link in docs FAQ

---

changes/pr3941.yaml
src/prefect/agent/kubernetes/agent.py
tests/agent/test_k8s_agent.py

Sometimes certain scenarios could lead to a failed pod being reported by the Kubernetes agent but it is unable to retrieve any container statuses. This would lead to an error like this:
```
File "/usr/local/lib/python3.7/site-packages/prefect/agent/kubernetes/agent.py", line 357, in heartbeat
self.manage_jobs()
File "/usr/local/lib/python3.7/site-packages/prefect/agent/kubernetes/agent.py", line 265, in manage_jobs
for status in pod.status.container_statuses:
TypeError: 'NoneType' object is not iterable
```
Avoids attempting to use container statuses if none are found when reporting failed pods.
Error handling
This PR:
cc @TylerWanner

Handle empty container statuses when reporting failed pods in Kubernetes agent

---

changes/pr3940.yaml
src/prefect/core/flow.py
src/prefect/storage/_healthcheck.py
src/prefect/storage/azure.py
src/prefect/storage/docker.py
src/prefect/storage/gcs.py
src/prefect/storage/local.py
src/prefect/storage/s3.py
src/prefect/storage/webhook.py
src/prefect/utilities/storage.py
tests/storage/test_docker_healthcheck.py
tests/storage/test_gcs_storage.py
tests/storage/test_s3_storage.py
tests/utilities/test_storage.py

Currently flows are stored using `cloudpickle` by default. While
flexible, the error messages produced on failure can be opaque
(especially for new users). Since `pickle` makes the internal
datastructures part of the public api, changes in core library versions
can lead to subtle errors - it's hard for us to provide better error
messages without knowing these version differences exist.
This commit changes the storage representation to include extra metadata
(currently only version info), which allows for generating better error
messages. We currently encode the versions for things likely to lead to
pickling errors:
- `prefect`
- `python`
- `cloudpickle`
If the flow fails to load, version differences between the build and
execution environments are checked and added to the error message to …

Better error messages on failure to load flow

---

changes/pr3953.yaml
src/prefect/artifacts.py

Currently when running with Prefect Cloud, there's a rare race condition
that may occur when creating a task run artifact against a mapped task,
leading to errors. For now, we catch this error and retry a few times
with a fixed delay in between attempts.
No test added (hard to test, temporary fix), but I've confirmed this fix
works locally.
This PR:

Avoid race condition when creation task run artifacts

---

docs/orchestration/flow_config/storage.md
src/prefect/storage/azure.py
src/prefect/storage/gcs.py
src/prefect/storage/s3.py
src/prefect/storage/webhook.py

- Remove lingering notes about default storage labels
- Clarify descriptions of where flows are stored by default for each backend.
Fixes #3948.

Storage doc fixups

---

changes/pr3954.yaml
src/prefect/agent/kubernetes/agent.py
tests/agent/test_k8s_agent.py

Other agents propagate their labels to their flow runs via the
`PREFECT__CLOUD__AGENT__LABELS` environment variable, but the k8s agent
had dropped that in the run-config refactor. We re-add that environment
variable here.
This PR:

Add agent labels to k8s flow runs

---

changes/pr3959.yaml
src/prefect/client/client.py

In anticipation of some possible API changes, best to have this in place.
Adds 429 as a retry status code in the client.
Future proofing.
This PR:

Add 429 as a retry status code on the client

---

changes/pr3964.yaml
src/prefect/engine/result/base.py
src/prefect/engine/task_runner.py
tests/engine/result/test_base.py

The `TaskRunner` does different things dependent on if a task's result
type has a `write` method implemented. Previously this would check for
`NotImplementedError`, which would shadow any actual
`NotImplementedError` raised when writing a result (e.g. in the
serializer). We now use a custom `ResultNotImplementedError` to handle
this control flow, avoiding the issue.
Fixes #3962.
This PR:

Use custom `NotImplementedError` in results

---

docs/orchestration/tutorial/next-steps.md

Fix links in "Conclusion and Next Steps" page of Orchestration & API docs, including "concurrency limits" and "Flow Configuration" mentioned in #3960 .
1. Change the link of "concurrency limits" to https://docs.prefect.io/orchestration/concepts/task-concurrency-limiting.html
2. Change the link of "Flow Configuration" to https://docs.prefect.io/orchestration/flow_config/overview.html
No more 404 error returns in documentation!
This PR:

Fix links in "Conclusion and Next Steps" page

---

changes/pr-3715.yaml
docs/outline.toml
src/prefect/tasks/kubernetes/__init__.py
src/prefect/tasks/kubernetes/job.py
src/prefect/tasks/kubernetes/pod.py
tests/tasks/kubernetes/test_job.py
tests/tasks/kubernetes/test_pod.py

This PR opens a watch on `read_namespaced_pod_log` such that the logging output of the created job is forwarded to prefect. No more black box ⬛!
Replaces the polling for status on a job, to a watch to forward the logging from the job.
Gives insight in what the job is doing.
This PR:

Stream log output from Kubernetes RunNamespacedJob

---

docs/core/concepts/notifications.md

Small addition to the notifications page to show how to use a secret in a state_handler
There was previously no example and the standard PrefectSecret task didn't work in my state handler
This PR:

update slack state handler example to use a secret

---

changes/pr3968.yaml
src/prefect/tasks/gcp/storage.py

use chunk_size when creating blobs and set default chunk size on base class initialization
GCP storage task for upload and download
Allows Prefect to work better on large files without timing out. GCS has a 60-second timeout so if you are unable to complete file transfer in the allotted time, you'll get a socket timeout.
[Google Storage Source](https://github.com/googleapis/python-storage/blob/5b4568e7af1cb59f116301ce572cc1a2f8a57521/google/cloud/storage/blob.py#L144)
Example in other libraries
[leanplum](https://github.com/mozilla/leanplum-data-export/pull/18/files)
This PR:

GCS chunking

---

changes/pr3969.yaml
src/prefect/cli/execute.py
src/prefect/environments/execution/base.py
src/prefect/storage/__init__.py
src/prefect/storage/azure.py
src/prefect/storage/base.py
src/prefect/storage/bitbucket.py
src/prefect/storage/codecommit.py
src/prefect/storage/docker.py
src/prefect/storage/gcs.py
src/prefect/storage/github.py
src/prefect/storage/gitlab.py
src/prefect/storage/local.py
src/prefect/storage/s3.py
src/prefect/storage/webhook.py
tests/environments/execution/test_local_environment.py
tests/serialization/test_storage.py
tests/storage/test_azure_storage.py
tests/storage/test_bitbucket_storage.py
tests/storage/test_codecommit_storage.py
tests/storage/test_docker_storage.py
tests/storage/test_gcs_storage.py
tests/storage/test_github_storage.py
tests/storage/test_gitlab_storage.py
tests/storage/test_local_storage.py
tests/storage/test_s3_storage.py
tests/storage/test_webhook_storage.py

We previously added support for storing multiple flows in a single
script file, but in practice that would fail since which flow was
retrieved was non-deterministic (the first flow found would be used).
This fixes this to always load and return the correct flow.
To accomplish this (and clean up some storage internals), the signature
for the `get_flow` method has been changed to accept the *flow name*
rather than the *flow location*. A location may host more than one flow,
but a flow name is always unique within a `Storage` object. Since the
`get_flow` method isn't user facing this change should be fine.
Fixes #3961.
This PR:

Better support multiple flows per file in Storage

---

changes/pr3975.yaml
src/prefect/utilities/tasks.py
tests/utilities/test_tasks.py

A regression was added in #3920 which prevented using `apply_map` inside
a `resource_manager` or `case` block for non-trivial patterns. This
fixes that regression, and expands the test suite to catch issues with
this going forward.
Fixes #3973.
This PR:

Fix use of apply_map in resource_manager/case block

---

changes/pr3977.yaml
src/prefect/engine/flow_runner.py
tests/engine/test_flow_runner.py

When restarting a flow, we now always rerun secret tasks, since they're
never cached.
Fixes #3926.
This PR:

Rerun secret tasks on flow restart

---

.circleci/config.yml

This check is not a necessary part of this CI step and can be removed. It was adapted from the PyPi release step but is not needed for pinning doc builds.

Remove master branch check in cloud run CI step

---

changes/pr3978.yaml
src/prefect/tasks/gcp/storage.py
tests/tasks/gcp/test_gcs_upload_download.py

Added a case when data uploaded is neither string nor bytes in `prefect.tasks.gcp.storage.GCSUpload`, raising an explicit `ValuError` in that case.
Solving issue #3974 
Create an `else` case when determining the data type in `prefect.tasks.gcp.storage.GCSUpload`, raising a `ValueError` if type is neither string nor bytes.
Created an associated test in `tests/tasks/gcp/storage/test_gcs_upload_and_download.py`: I have created a `TestRunTimeValidation` object with this test a single function, took the naming from `test_gcs_copy.py` in the same folder.
GCSUpload is at the moment failing silently when data uploaded is neither string nor bytes.
With this PR it will explicitely fail.
This PR:

Raise error when invalid data type is uploaded with GCSUpload

---

changes/pr3995.yaml
src/prefect/storage/s3.py
tests/storage/test_s3_storage.py

We now log the `ETag`, `LastModified` timestamp, and `VersionId` (if
present) for flows downloaded from S3 storage. This makes it easier to
track what version of a flow is run.
Also cleans up the S3 storage tests to make better use of fixtures, and
remove duplicate tests.
This PR:

Improve logs from s3 storage

---

changes/pr3989.yaml
src/prefect/executors/dask.py
src/prefect/utilities/logging.py
tests/conftest.py
tests/engine/cloud/test_cloud_flow_runner.py
tests/engine/test_flow_runner.py
tests/utilities/test_logging.py

This does several things, with the goal of making our logging more
robust:
- Changes the implementation of `CloudHandler` to use a single (lazily
started) background thread, rather than a thread per handler. This
makes it cheaper to register `CloudHandler` handlers for custom
loggers.
- Better ensures that all logs are flushed to cloud on process exit
- Pre-checks all log messages for a max length (logging a warning if
that length is exceeded, and truncating the offending log). This
provides better user-facing warnings, rather than relying on an error
message from cloud.
- Batches log messages to cloud by a max size, preventing a huge amount
of logs from being sent in a single batch. With this and the above,
only network/intermitent errors should result in logs failing to
upload.
- In the …

Refactor logging

---

src/prefect/tasks/databricks/databricks_submitjob.py

Resolves #4000 by ensuring that the `databricks_conn_secret` and `json` arguments are used if they are passed to the run method instead of the instantiator, and update documentation.
- Change documentation to refer to `databricks_conn_secret`, not `databricks_conn_string`.
- Update code examples to show `PrefectSecret` being passed to the instantiated task, not the instantiator. This avoids triggering the `UserWarning` that happens when passing `PrefectSecret` directly to a task subclass.
- Modify implementation to update the corresponding attribute if `databricks_conn_secret` is passed to the run method. This fixes the `TypeError` bug.
- Modify implementation to update the corresponding attribute if `json` is passed to the run method. Previously it was ignored.
The existing databricks …

Databricks Fixes

---

changes/pr4003.yaml
src/prefect/client/secrets.py
tests/client/test_secrets.py

From a user question in Slack, I noticed that when running against Server we were still querying the API for secrets despite secrets not being a part of the Server API.  The traceback was huge and possibly misleading for users.  This PR simplifies the error message.
Raise more straightforward error message when a secret is missing when running against Server / locally.
Better UX.
This PR:

Better secret error message

---

changes/pr4006.yaml
src/prefect/agent/kubernetes/agent.py
tests/agent/test_k8s_agent.py

The resource management loop in the Kubernetes agent has the potential to error if it attempts to set the state for a missing flow run. This can happen in the case where a job is started, the user deletes the flow run, then the agent attempts to clean up the job (when the job is in a state where the agent marks the flow run as failed). To avoid this we handle the case where a `ClientError` is raised by the call to the client and the loop continues with its resource management cycle.
Handles `ClientError`s when calling the `set_flow_run_state` mutation in the Kubernetes agent resource management loop
Avoids a possible edge case
This PR:

Handle missing flow runs in k8s agent resource management

---

changes/pr3998.yaml
src/prefect/serialization/storage.py
src/prefect/storage/github.py
tests/serialization/test_storage.py
tests/storage/test_base_storage.py
tests/storage/test_github_storage.py

- Default `ref` is now `None` (instead of `"master"`). This defaults to
using the default branch for the repo, allowing for alternate default
branch names than `"master"`.
- Makes `path` a required parameter for `GitHub` storage. This was
always implicitly required (things would break if it was missing), but
the code and serializers still allowed for it.
- Adds improved log messages when failing to load a flow from `GitHub`
storage
- Adds more information to the github storage logs, including the commit
sha for the code that's loaded in all cases. This makes it easier to
determine the exact source used when running a flow.
- Improved test coverage
This PR:

A few changes to GitHub storage

---

changes/pr4008.yaml
src/prefect/tasks/prefect/flow_run.py
tests/tasks/prefect/test_flow_run.py

Some users have been confused when passing `Parameter` instances through
`parameters` in the constructor of `StartFlowRun` (these should instead
be passed to `StartFlowRun.__call__`). We raise a better error at flow
construction now.
This PR:

Better error for passing Tasks to `StartFlowRun` parameters

---

changes/pr4011.yaml
src/prefect/core/task.py
tests/core/test_task.py

This adds a warning for user defined tasks if they accidentally shadow
an attribute used by the default `Task.__init__`. We do this with
attributes instead of parameters, since users may want to override the
defaults for Task parameters for their specific subclass.
For example:
```python
from prefect import Task
class MyTask(Task):
def __init__(self, **kwargs):
self.target = "oops"
super().__init__(**kwargs)
MyTask()
```
raises the following warning:
```
/Users/jcristharif/Code/prefect/src/prefect/core/task.py:331:
UserWarning: `MyTask` sets a `target` attribute, which will be
overwritten by `prefect.Task`. Please rename this attribute to avoid
this issue.
```
Fixes #3950.
This PR:

Warn if user shadows attributes in Task class

---

Dockerfile
changes/pr4013.yaml
entrypoint.sh

This adds support for a `EXTRA_PIP_PACKAGES` environment variable in our
official `prefect` docker images. This takes a space delimited list of
packages to pass to `pip install` on image startup, allowing for easier
runtime installation of extra packages. For production deployments users
should still build images with their required dependencies, but for
development this can make things a bit easier. The official dask images
also support this, so there's some precedence here.
Also extends our default entrypoint to drop the user into a shell if no
CMD is specified (with a header explaining what the image is). We've had
a few users confused with what the prefect image was for (mostly
assuming it would start prefect server automatically), so hopefully this
helps remove this confusion.
This …

Support `EXTRA_PIP_PACKAGES` in docker image

---

changes/issue3972.yaml
src/prefect/agent/agent.py

On start Agents register themselves with the backend API. An exception handling step was added in to support the case where _old_ versions of the server did not contain the routes for agent registration. This had the potential to skip agent registration on new versions where the server was not yet started. Process being this: agent starts, can't register, keeps trying to connect to server, server starts up, agent begins and is in an unregistered state. Now that agent registration has existed for quite a few releases, this check can be removed.
Closes #3972

Fix Agent registration possibly skipping on server connection issues

---

docs/orchestration/concepts/tokens.md

The [Tokens doc](https://docs.prefect.io/orchestration/concepts/tokens.html#cli) illustrates that the way we generate a RUNNER token with the CLI is to add a `-r` option, but now it's `-s` option (I guess `s` stands for **scope**?).
Change the option for generating RUNNER scope token from `-r` to `-s`, so the command becomes:
```bash
$ prefect auth create-token -n my-runner-token -s RUNNER
```
The command can be executed successfully now.
This PR:

Docs issue: Fix option for generating a RUNNER scope token

---

changes/pr4021.yaml
src/prefect/cli/run.py
tests/cli/test_run.py

This PR adds the option to provide a flow ID to the `prefect run flow` CLI command.

Add option to provide flow ID when calling run flow CLI command

---

changes/pr3925.yaml
changes/pr3981.yaml
src/prefect/tasks/aws/s3.py
tests/tasks/aws/test_s3.py

Create a boto3 session during `tasks.aws.S3Upload` and `tasks.aws.S3Download` to ensure the task is executed in a thread-safe way. Provides a workaround for #3925.
~~The only change is the addition of one argument to the `run()` method for each of the two tasks, with the value of this argument being passed to `get_boto_client()`. The default value is `False`, which makes the task use the exact same behaviour from before this PR to avoid backwards compatibility issues. If `True`, a boto3 session is created before the boto3 client is created, requiring slightly more overhead but ensuring thread-safe execution.~~
After discussion with code owners, updated the logic so that the only change is to always pass `use_session = True` to `get_boto_client()`.
This PR makes the `S3Upload` and …

Use boto3 session in S3Upload and S3Download tasks

---

changes/issue4031.yaml
src/prefect/engine/task_runner.py
tests/engine/test_task_runner.py

The most prominent use case for pausing a task run is using a `manual_only` trigger, which results in a task run in a `Paused` state that waits for someone to manually place it back into a `Resume` state.  However, the [`pause_task` utility](https://docs.prefect.io/api/latest/utilities/tasks.html#functions) and the `Paused` state itself allow for users to specify a start time for the task run to automatically resume.  This means that the task run never transitions through a `Resume` state, which is how we normally detect whether to skip paused signals. 
This PR adjusts our task run initialization logic to account for `Paused` states with current start times so that they can be properly resumed.
Places `resume=True` into context if the current task run state is `Paused` and if the …

Fix issue with fixed-duration paused states not resuming properly

---

changes/3986_docker_networks.yaml
src/prefect/agent/agent.py
src/prefect/agent/docker/agent.py
src/prefect/cli/agent.py
tests/agent/test_docker_agent.py
tests/cli/test_agent.py

Allow Docker Agent to connect to multiple Docker networks (https://github.com/PrefectHQ/prefect/issues/3986).
- `prefect agent docker start` allows connecting to multiple networks, e.g. `--network network1 --network network2`.
- `prefect agent docker start --network <network-name>` assigns `<network-name>` to `networks` argument instead of `network`.
- `DockerAgent` has new `networks` argument, the `network` argument is set to deprecated.
A Docker container started by a Docker Agent might want to connect to multiple docker networks (e.g. in my use case a Kafka network, a database network, and the prefect network). This was previously not possible, this PR makes this possible.
This PR:

Allow Docker Agent to connect container to multiple Docker networks

---

docs/orchestration/flow_config/storage.md

Add a note to the Storage docs mentioning how to override the `LocalStorage` default of adding the hostname as a label. I've seen questions about this multiple times in the Slack channel, most recently today ( https://prefect-community.slack.com/archives/CL09KU1K7/p1612442778238000 )
Just adding this sentence and example to the "Automatic Labels" tip:
```
This behavior can be overridden by passing `add_default_labels = False` to the constructor:
\```python
flow = Flow("local-flow", storage=Local(add_default_labels = False))
\```
```
Hopefully saving people the time and effort of asking and answering this question again in Slack :)
This PR:
~~- [ ] updates docstrings for any …

Add note on add_default_labels to Storage docs

---

changes/4041_docker_healthcheck.yaml
src/prefect/cli/docker-compose.yml

Add [healthchecks](https://github.com/compose-spec/compose-spec/blob/master/spec.md#healthcheck) to docker-compose of Prefect server.
Add healthchecks to the following services:
- postgres (Based on [`pg_isready` utility](https://www.postgresql.org/docs/9.4/app-pg-isready.html) )
- hasura (Based on [`/healthz` endpoint](https://hasura.io/docs/1.0/graphql/core/api-reference/health.html) )
- apollo (Based on apollo graphql endpoint)
Startup dependent services only when dependencies are healthy.
- Monitor the health of the different server components.
- Force restart of unhealthy server components.
- Ability for downstream services to wait on server components.
For example: I have a deployment where I'm spinning up the prefect server along with any agents. I can have the agents in Docker …

Docker healthchecks for prefect server

---

changes/pr4061.yaml
src/prefect/cli/create.py
src/prefect/cli/register.py
tests/cli/test_create.py
tests/cli/test_register.py

This PR adds two new options to the CLI:
- `--detect-changes` when calling `prefect register flow` that uses the flow's serialized hash as the idempotency key when registering (allowing the flow version to not be bumped if the flow has not changed)
- `--skip-if-exists` when calling `prefect create project` to safely query for the project by name and skip if it has already been created
cc @cicdw 
This comes out of a direct request from some users that would make their CI/CD flow building and registration process smoother!
This PR:

Minor CLI enhancements

---

docs/core/idioms/parallel.md
src/prefect/executors/dask.py

- Add note on using `if __name__ == "__main__"` block to `DaskExecutor`
example.
- Remove some references to non-best practice
- Include links to new executors docs
Fixes #3908.

Cleanup parallelism idiom

---

changes/pr4073.yaml
docs/orchestration/flow_config/storage.md
docs/outline.toml
src/prefect/serialization/storage.py
src/prefect/storage/__init__.py
src/prefect/storage/base.py
src/prefect/storage/bitbucket.py
src/prefect/storage/codecommit.py
src/prefect/storage/github.py
src/prefect/storage/gitlab.py
src/prefect/storage/local.py
src/prefect/storage/module.py
src/prefect/utilities/storage.py
tests/serialization/test_storage.py
tests/storage/test_module.py
tests/utilities/test_storage.py

Adds a new `Module` storage class, for referencing flows importable from an installed python module. This was previously doable as part of `Local` storage (but kind of hidden). We move it out to its own storage class to better surface this feature, and because it works fine whether run locally or not (e.g. works in a docker container, an ECS task, etc...).
Also does some general storage cleanups.
This PR:

Module storage

---

changes/pr4089.yaml
src/prefect/executors/dask.py
tests/executors/test_executors.py

The latest release of Dask (`2021.02.0`) fails when using the
multiprocessing scheduler with prefect. This patches around the issue
until it's resolved upstream.
Fixes #4086.

Fix multiprocessing with dask 2021.02.0

---

changes/issue4091.yaml
src/prefect/engine/task_runner.py
src/prefect/utilities/exceptions.py
src/prefect/utilities/executors.py
tests/core/test_flow.py
tests/engine/test_flow_runner.py
tests/engine/test_task_runner.py
tests/utilities/test_executors.py

Raises custom timeout exception to prevent obscuring timeout errors raised by user code.
Closes #4091
This PR:

More targeted timeout handling

---

changes/pr4077.yaml
src/prefect/agent/kubernetes/deployment.yaml

These were extremely low, and there's not a good reason to have them
(IMO). If a user wants to ensure the agent doesn't exceed a limit they
can add one themself (or add a request), but we shouldn't assume any by
default.
Fixes #3942.

Drop default resource limits on k8s agent

---

tests/executors/test_executors.py

This test passes fine locally, but has started behaving oddly on
circleci. No code changes seem relevant, so I'm marking it as a flaky
test for now. Not sure what's going on.

Skip interrupt test for LocalDaskExecutor("processes")

---

docs/core/idioms/idioms.md
docs/core/idioms/script-based.md
docs/orchestration/execution/storage_options.md
docs/orchestration/flow_config/storage.md
docs/orchestration/tutorial/overview.md

Expands the storage docs a bit:
- Standardizes use of `script based` flow storage, instead of `file based`. The kwarg is named `stored_as_script`, and not all backends refer to things as "files", so I think this makes more sense.
- Adds section to storage docs clarifying the difference between pickle and script based flow storage, and why you might pick one or the other.
- Adds section to the docs on choosing a storage class.
- A few small typo fixers.

A few additions to the storage docs

---

src/prefect/agent/agent.py

This was broken in 0.14.7. Previously we had accidentally relied
distributed implicitly setting a global `AnyThreadEventLoop` policy on
import, but in 0.14.7 we dropped all unnecessary imports (so this
implicit global change didn't happen). Our tests still passed though,
since `distributed` is imported as part of the test suite.
This bug caused all health checks to fail in the agent, since the event
loop wouldn't properly start. I don't have a good test for this (global
state makes testing tricky), but have verified locally that this fixes
the issue.

Ensure agent health-check thread has an active event loop

---

changes/pr4115.yaml
src/prefect/engine/results/s3_result.py
src/prefect/storage/codecommit.py
src/prefect/storage/s3.py
src/prefect/tasks/aws/s3.py
src/prefect/utilities/aws.py
tests/agent/test_ecs_agent.py
tests/agent/test_fargate_agent.py
tests/engine/results/test_s3_result.py
tests/storage/test_codecommit_storage.py
tests/storage/test_s3_storage.py
tests/tasks/aws/__init__.py
tests/tasks/aws/conftest.py
tests/tasks/aws/test_batch.py
tests/tasks/aws/test_client_waiter.py
tests/tasks/aws/test_lambda.py
tests/tasks/aws/test_s3.py
tests/tasks/aws/test_secrets_manager.py
tests/tasks/aws/test_step_function.py
tests/utilities/test_aws.py

Prefect relies on `boto3` for aws integration. Previously we were relying on creating a new session for parallel requests to avoid thread-safety issues - this worked, but was expensive (creating a new session is an order of magnitude slower). This was compounded by some faulty logic in the `S3Result` code that looked like it was supposed to result in shared boto3 clients, but in practice didn't.
Turns out boto3 clients are thread safe to use, the thread-safety issues only apply to instantiation (or if you're using the higher-level `boto3.resource` clients). We now use a single lock around boto3 client creation, and have a shared weakref cache of clients, allowing use across threads. This results in significantly fewer boto3 clients being created (possibly only one session per process), …

Reduce number of boto3 clients created

---

changes/task-increase-client-timeout.yaml
src/prefect/client/client.py
src/prefect/config.toml

Resolves #4118 
Increases prefect client HTTP timeout from 15 seconds to 60 seconds
Flow registration is failing for large flows that takes more than 15 seconds to upload
This PR:

Increase Prefect Client HTTP Request Timeout

---

changes/pr4150.yaml
src/prefect/engine/serializers.py
tests/engine/test_serializers.py

Not all users have them installed and it breaks the import of core if they are imported at the top level.
If a user does not have a compression library required by the new `CompressedSerializer` (#4063) then `prefect` cannot be imported without exceptions. To resolve this, we 
Instead of importing all the libraries at module load, we import the library requested for compression as needed.
This reduces assumptions about the user's python environment.
This PR:

Dynamically load compression libraries for serializers

---

docs/core/advanced_tutorials/advanced-mapping.md

The sample code from the X-Files tutorial raises `OperationalError('unable to open database file')` when attempting to insert the episode scripts into the database using the code from the tutorial:
`final = insert_episode.map(ep_script, upstream_tasks=[unmapped(db)])`
I believe `ep_script` is passed as the first positional argument (`db` to `SQLiteScript` [docs](https://docs.prefect.io/api/latest/tasks/sqlite.html#sqlitescript)) and should have been passed as the `script` kwarg (`.map(script=ep_script, ...`). I've attached a full working example at the bottom
Changes one line for the tutorial snippets to work
I spent some time really confused why the sample code wasn't working, so this change (however small) would have saved me some head-scratching! 😄 
This PR:
Full traceback when running …

Fix X-Files SQLiteScript insert code

---

changes/pr4160.yaml
src/prefect/cli/agent.py
tests/cli/test_agent.py

Fixes a bug in the agent cli code, where environment variables passed to
`--env` couldn't have `=` in the values.
Fixes #4138.
This PR:

Support agent --env with equals in value

---

changes/pr4182.yaml
src/prefect/utilities/storage.py
tests/utilities/test_storage.py

When loading a flow from a source file, if the file doesn't contain the
expected flow we now raise a better error message.

Better error message when failing to find flow in file

---

changes/pr4189.yaml
src/prefect/core/flow.py
tests/core/test_flow.py

Previously generating a slug for a new task was an O(n) operation where
all existing tasks were inspected to determine the next slug to use for
the new task. Besides being mildly expensive, this wasn't robust to
tasks changing name after being added to a flow, leading to duplicate
slugs. We now track auto-generated slugs in a private member on the flow
class, and explicitly handle clashes.
Note that this is still technically O(n) (since we check for a clash in
`slugs.values()`, which is a linear search). But the operation takes
place entirely within the Python C-api, so is generally fast for the
size of `n` we typically deal with.
Fixes #4185.

Make slug generation more robust

---

src/prefect/core/task.py
tests/core/test_task_operators.py

Use the parent task name + key for the `GetItem` task returned by indexing.
First pass at fixing #3789 with just task + key naming (didn't try `NamedTuple`)
`GetItem` tasks are noisy and hard to follow in the UI schematic, this makes them a bit easier to work with.
This PR:

Improve indexed task naming

---

changes/pr4195.yaml
src/prefect/storage/s3.py
tests/storage/test_s3_storage.py

The initialization of storage.s3 initialize as well the S3Result property for S3. however the client_options dict is not passed to the result boto3_kwargs. 
Pass the property to the S3Result as below
```
result = S3Result(bucket=bucket, boto3_kwargs=client_options)
```
This is important to ensure the storage and the result are initialized with the same param when calling S3
This PR:

Pass S3 client option from storage to result

---

changes/pr4194.yaml
src/prefect/serialization/storage.py
src/prefect/storage/github.py
tests/serialization/test_storage.py
tests/storage/test_github_storage.py

Adds support for custom Github domains in Github storage
Adds the base_url parameter in in Github storage for the pygithub library, that adds support for custom Github REST api endpoints
Adds support for custom Github domain in Github storage.
This PR:

Add base_url parameter for Github storage

---

changes/pr4176.yaml
docs/outline.toml
src/prefect/cli/agent.py
src/prefect/cli/server.py
src/prefect/utilities/cli.py
src/prefect/utilities/compatibility.py
tests/cli/test_server.py

Instead of starting the server, provide the configured file for a user to spin it up themselves.
`prefect server config` writes a configure docker-compose yaml to standard output using `docker-compose config` to resolve environment variables. It takes all the same (non pull/start) options as `prefect server start`
- Adds `config` to `prefect server` CLI
- Refactors docker-compose file and environment generation
- Warns on collisions between the current environment and CLI commands
Closes https://github.com/PrefectHQ/prefect/issues/4151
This PR:

Add `prefect server config` command to output a compose file

---

changes/pr4206.yaml
src/prefect/core/task.py
tests/core/test_task.py

Previously setting `nout` on a task would forward the `nout` to both
normal task call outputs (which we want) and mapped task outputs (which
we don't). This led some users to assume that calling `task.map` would
result in a tuple of lists of results, when the actual output is a list
of tuples.
This PR fixes this to stop propagating the `nout` field on `task.map`
calls, so the improper usage will error instead of implicitly passing.

Don't forward nout in mapped tasks

---

changes/pr4209.yaml
src/prefect/core/flow.py

A simple fix swapping a lambda function by partial. This will help keep the Flow more pickle-friendly.
Setting of `_slug_counters` using `partial` instead of `lambda`
This is a simple fix, but will help users that rely on using `pickle` and `prefect.Flow`

fix: make slug_counters use partial instead of lambda

---

changes/pr4126.yaml
src/prefect/cli/docker-compose.yml

Upgrade hasura to 1.3.3
Keep hasura up to data
This PR:
- [-] adds new tests (if appropriate)
- [-] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

Upgrade hasura to 1.3.3

---

changes/pr4211.yaml
docs/orchestration/agents/ecs.md
src/prefect/agent/ecs/agent.py
src/prefect/run_configs/ecs.py
tests/agent/test_ecs_agent.py
tests/run_configs/test_ecs.py

- Move `command` and `environment` for the `flow` container to be set at ECS task run time rather than as part of the task definition. This makes it simpler to provide a `task_definition_arn`, as prefect can set more of the required parameters for you.
- Improve our docs a bit on what's required for a custom task definition.

A few ECS agent cleanups

---

changes/pr4232.yaml
src/prefect/agent/docker/agent.py
src/prefect/cli/agent.py
tests/agent/test_docker_agent.py
tests/cli/test_agent.py

Adds an option to configure a timeout for docker api requests to the
docker agent.
Fixes #4220.

Add `--docker-client-timeout` to docker agent

---

changes/pr4235.yaml
src/prefect/core/task.py
tests/core/test_task.py

This PR fixes a bug (https://github.com/PrefectHQ/prefect/issues/4234) where task signatures could not be generated for subclasses of `Task` where `.run` includes `**kwargs`.
This PR changes `prefect.core.Task.__signature__` to fix the bug by correctly accounting for parameter kind and order when modifying the task instance's call signature.
`task` is a core piece of prefect's functionality, and fixing this bug is necessary for it to work as documented.
This PR:

Test and bugfix for variadic keyword-only task signature

---

changes/issue3306.yaml
src/prefect/environments/execution/k8s/job.py

- Added from on each raised exception in:
- src/prefect/environments/execution/k8s.
- Changes based on #3306 for the aforementioned sub-modules.
- Improves stack trace when debugging errors by using clearer language.
This PR:

Use from chain exceptions in k8s enviroment

---

src/prefect/engine/serializers.py
src/prefect/tasks/airtable/__init__.py
src/prefect/tasks/aws/batch.py
src/prefect/tasks/aws/client_waiter.py
src/prefect/tasks/azure/__init__.py
src/prefect/tasks/azureml/__init__.py
src/prefect/tasks/dbt/__init__.py
src/prefect/tasks/dropbox/__init__.py
src/prefect/tasks/gcp/bigquery.py
src/prefect/tasks/great_expectations/__init__.py
src/prefect/tasks/gsheets/__init__.py
src/prefect/tasks/kubernetes/__init__.py
src/prefect/tasks/postgres/__init__.py
src/prefect/tasks/redis/__init__.py
src/prefect/tasks/rss/__init__.py
src/prefect/tasks/snowflake/__init__.py
src/prefect/tasks/sql_server/__init__.py
src/prefect/tasks/templates/jinja2.py

Adds explicit exception chaining so that exception stack traces are a bit easier to comprehend in these places
- src/prefect/engine/serializers.py
- src/prefect/tasks/airtable/__init__.py
- src/prefect/tasks/aws/batch.py
- src/prefect/tasks/aws/client_waiter.py
- src/prefect/tasks/azure/__init__.py
- src/prefect/tasks/azureml/__init__.py
- src/prefect/tasks/dbt/__init__.py
- src/prefect/tasks/dropbox/__init__.py
- src/prefect/tasks/gcp/bigquery.py
- src/prefect/tasks/great_expectations/__init__.py
- src/prefect/tasks/gsheets/__init__.py
- src/prefect/tasks/kubernetes/__init__.py
- src/prefect/tasks/postgres/__init__.py
- src/prefect/tasks/redis/__init__.py
- src/prefect/tasks/rss/__init__.py
- src/prefect/tasks/snowflake/__init__.py
- src/prefect/tasks/sql_server/__init__.py
- …

fixing raise-missing-from in remaining places

---

changes/pr4266.yaml
src/prefect/cli/run.py
tests/cli/test_run.py

Support setting flow run labels from cli
[Slack context](https://prefect-community.slack.com/archives/CL09KU1K7/p1616010761095000)
Adds a `--label` flag to `prefect run flow`.
Allows labels to be set via the CLI or in code wrapping the CLI in order to tail logs.
This PR:

Support setting flow run labels from cli

---

changes/pr4259.yaml
src/prefect/client/client.py
src/prefect/engine/cloud/flow_runner.py
tests/engine/cloud/test_cloud_flows.py

Improves the error message for the case where serialized flow task slugs cannot be found in the flow loaded from storage.
- Adds `storage` to `FlowRunInfoResult`
- Adds a special note if a "path" is attached to the storage
- Clarifies general message for task slug mismatches
Improves likelihood that a user can self-resolve this exception
This PR:

Improve message when task slugs are missing

---

changes/pr4270.yaml
src/prefect/agent/ecs/agent.py
src/prefect/agent/kubernetes/agent.py
src/prefect/utilities/agent.py
tests/agent/test_ecs_agent.py
tests/agent/test_k8s_agent.py
tests/utilities/test_agent.py

Previously we always overrode the `image` used at runtime for the K8s
and ECS agents, which prevented setting a default image to use on the
agent. This PR fixes that, allowing agent side defaults to be set
(through `--job-template` on the k8s agent and `--task-definition` on
the ECS agent).
Fixes #4269 , fixes #4128.
This PR:

Support setting `image` in agent-side templates

---

changes/pr4256.yaml
docs/core/idioms/script-based.md
docs/orchestration/concepts/flows.md
docs/outline.toml
src/prefect/cli/register.py
src/prefect/storage/_healthcheck.py
src/prefect/storage/base.py
tests/cli/test_register.py
tests/client/test_client.py

This PR deprecates the previous `prefect register flow` CLI in favor of a new `prefect register` CLI with lots more functionality.
Features:
- Allows registering multiple flows in a single call. Flows can be specified by `--path` (path to a file or directory containing flows) or by `--module` (an importable python module containing flows). Both options can be specified multiple times in a single call for more flexibility.
- A `--name` flag can be used to subselect flows to only register flows with a specific name (or names). If unspecified, all flows found are registered.
- By default, a flow will only be re-registered if it is *structurally different* than the existing version. This means that small edits to the source of tasks won't require re-registration, and the CLI will …

New flow registration CLI

---

changes/pr4282.yaml
docs/outline.toml
src/prefect/cli/__init__.py
src/prefect/cli/build_register.py
src/prefect/cli/register.py
src/prefect/utilities/filesystems.py
tests/cli/test_build_register.py
tests/cli/test_register.py
tests/utilities/test_filesystems.py

This PR:
- Adds a new `prefect build` CLI command for building flows and creating/updating a `.json` file containing their representations.
- Adds a `--json` flag to `prefect register` for registering flows from a `.json` file. Note that this file may be local, or hosted elsewhere (currently only `https`/`http`, `s3`, and `gcs` are supported).
Combined, these let users build flows once and host the `json` results somewhere for later registration into one or more projects.
For example, you might build your flows as part of CI (and host the output `flows.json` file on github pages as part of your docs). Users can then register flows from your repo as:
```
$ prefect register --json https://username.github.io/your-project/flows.json --project their-project-name
```
With pre-built flows, the …

Add support to CLI for pre-building flows

---

changes/pr4287.yaml
src/prefect/engine/flow_runner.py
tests/engine/test_flow_runner.py

When adding default fields to context during a flow run, several check
if there's an existing value and only override if it doesn't already
exist (e.g. `"date"`). However, this would only work if the context was
passed explicitly to `.run(context=context)`, rather than being part of
the implicit global context (since that wasn't added until the very
end). This PR fixes that bug.
Fixes #4276.

Respect global context in flow runner

---

changes/issue4265.yaml
src/prefect/tasks/jupyter/jupyter.py
tests/tasks/jupyter/sample_notebook.ipynb
tests/tasks/jupyter/test_jupyter.py

This is a response to [#4265](https://github.com/PrefectHQ/prefect/issues/4265), which was raised on Slack. The user wanted to capture Jupyter notebook cell outputs in the Prefect logs.
There are two things needed to get this to work. One is to pass the `log_output` bool into `papermill`'s execute_notebook function. By default this is False. It needs to be True. For consistency with the previous implementation, I kept the default asFalse, though I feel there might be benefits in making it True.
The second thing is to get the `papermill` logger and change the level to `INFO` or `DEBUG`. By default, it is at `WARN` so it does not log cell outputs. I think we should not do this change on the task side. Instead, Prefect users should use the (extra …

Improving logging of Jupyter task to capture cell output

---

changes/pr4298.yaml
src/prefect/tasks/snowflake/snowflake.py
tests/tasks/snowflake/test_snowflake.py

This is to fix this [issue](https://github.com/PrefectHQ/prefect/issues/3744) about Snowflake output not being pickleable. This is because the original code just returned the cursor.
I spun up a free trial for Snowflake and tested this change with the default databases. I then used `cloudpickle` to make sure results are serializable. This is hard to reflect in the unit tests.
I added the `fetchall` call, and then I added a new unit test that ensures the Task has the `fetchall` call.
This PR:

Fixing Snowflake Query Task

---

changes/pr4296.yaml
src/prefect/engine/cloud/task_runner.py
tests/engine/cloud/test_cloud_flow_runner.py
tests/engine/cloud/test_cloud_flows.py
tests/engine/cloud/test_cloud_task_runner.py

Generally, we pre-load task run information when the flow run starts. The only time we load task run information when the task itself starts is for dynamic tasks. However, in certain fast-moving situations, the flow may actually begin running before all task-level detail is available. This PR modifies the task run info logic to ALWAYS load when the task run starts.
With this in place, we could further improve performance by completely eliminating the initial batch task run load, but I'm not including that here.
This PR:

Always load latest task run info prior to running task

---

changes/pr4309.yaml
src/prefect/tasks/databricks/databricks_submitjob.py
tests/tasks/databricks/test_databricks.py

`DatabricksRunNow.run` was not properly overriding task attributes, which resulted in unexpected job json objects being generated for the Databricks API calls.
* Fixes task attribute override behavior when calling `DatabricksRunNow.run`.
* Improves `test_databricks.py` to allow mocked responses from Databricks API.
* Implement tests for `DatabricksRunNow.run` and generated job json object for Databricks API calls.
Using the `DatabricksRunNow` task resulted in some unexpected behavior when attempting to override task attributes during `DatabricksRunNow.run`. The issues are best demonstrated with this simple test (which currently fails):
```python
def test_run_with_attribute_overrides():
task_template = DatabricksRunNow(
databricks_conn_secret={
"host": "https://cloud.databricks.com", …
```

Fix `DatabricksRunNow` task attribute override behavior

---

changes/pr4295.yaml
src/prefect/engine/flow_runner.py
tests/engine/test_flow_runner.py

Previously, if you overrode `date` in the context for a flow, the dependent variables such as `tomorrow` and `today` would still be based on `pendulum.now()` making it hard for a user to do a simple override and see expected context changes. This will attempt to parse `date` if set to determine the "now" `DateTime` to be used to set the dependent variables. If unparsable, a warning will be displayed.
Dependent variables are automatically updated if `date` is set and is parsable as a `DateTime`.
Improves usability for testing / backfilled schedules.
This PR:

Use custom `date` in context to determine dependent context vars

---

changes/pr4321.yaml
src/prefect/executors/dask.py
tests/executors/test_executors.py

Adds the following logs:
- Scheduler address used when connecting to an existing cluster
- Callable used when creating a new cluster
- Dashboard address used for new cluster (if available)
We cannot log the dashboard address for an existing cluster, as this
can't be determined from the client.

Expand logs in `DaskExecutor`

---

changes/pr4307.yaml
docs/outline.toml
src/prefect/tasks/kubernetes/__init__.py
src/prefect/tasks/kubernetes/secrets.py
src/prefect/utilities/kubernetes.py
tests/tasks/kubernetes/test_secrets.py

This is a new task that allows us to extract Kubernetes Secret and transform it into a Prefect secret.
The idea is to have another secret store from the one which already exists. Prefect, env var or AWSvault.
This PR adds a new task KubernetesSecret that inherit from SecretBase
This PR allows users who are using Prefect Server to centralize all their secret on a Kubernetes Secret object
This PR:

Add new task KubernetesSecret

---

changes/pr4332.yaml
src/prefect/cli/build_register.py
tests/cli/test_build_register.py

When using `prefect register`/`prefect build` we now support flows that
import files from other files in the same directory. Note that this does
_not_ ensure that these flows will run successfully (as the presence of
these "helper scripts" would have to be ensured by the storage/runtime
environment). All this does is ensure that running `prefect register
--path path/to/flow.py` has the same `sys.path` as `python
path/to/flow.py` would have.
We also move to using `runpy` to properly setup some other metadata
values in the script's namespace (e.g. `__file__`).
Reported on slack: https://prefect-community.slack.com/archives/CL09KU1K7/p1617276925312300?thread_ts=1617160663.217800&cid=CL09KU1K7
This PR:

Support local directory imports in flow scripts from CLI

---

changes/pr4322.yaml
src/prefect/tasks/shell.py
tests/tasks/test_shell.py

There are certain circumstances under which we'd like to be able to stream the output of a `ShellTask` (or its child classes) without having to set the global logging level to `DEBUG`; for example, the process launched by `ShellTask` sometimes streams valuable output that a user might like to capture and stream using the base Prefect logger. Currently, this is not possible. This change gives the user more control in that they can change the log level from one `ShellTask` to the next within a given flow.
Fixes #3865.
Add ability to stream ShellTask logs with custom log level
- Changes the default behavior of `ShellTask.stream_output`, which will default to using a log level of `INFO` when enabled.
- Changes the type of `ShellTask.stream_output` to be a `Union[bool, int, str]`. This will …

Add ability to stream ShellTask logs with custom log level

---

changes/pr4334.yaml
src/prefect/utilities/logging.py
tests/utilities/test_logging.py

When writing logs to prefect cloud, we batch uploads into batches by a
time period (defaults to 5 seconds). On shutdown, the intent was to
break out of this write-then-sleep loop and write all the remaining logs
before closing.  Unfortunately this accidentally relied on the shutdown
signal interrupting the sleeping thread, leading to a slower shutdown
process on some platforms. When running on dask, the worker process must
shutdown in 3 seconds before a kill signal is sent, and since 3 < 5,
some logs could be lost. We now use a `threading.Event` instead of
sleeping, ensuring that the write-then-sleep loop breaks early on
shutdown and all logs are written.
Issue reported on slack here: https://prefect-community.slack.com/archives/CL09KU1K7/p1616957545069800

Speedup flushing of cloud logs on shutdown

---

changes/pr4325.yaml
src/prefect/agent/ecs/agent.py
tests/agent/test_ecs_agent.py

- Always set `requiresCompatibilities` in the task definition. This
isn't strictly required, but without it ECS won't provide good error
messages when a task definition is invalid.
- Set `executionRoleArn` on the task definition as well as at runtime.
Fargate requires an execution role ARN be set on the task definition
for any task that uses ECR, even if the execution role ARN would be
provided at runtime. We still provide it at runtime to support users
who provide their own pre-registered task definition and may want to
override the setting at runtime.
Fixes #4243.
This PR:

A couple ECS fixups for fargate

---

changes/pr4350.yaml
requirements.txt

Dask dropped support for Python 3.6 in their latest release. This PR pins upper `dask` and `distributed` versions to allow requirements to build in Python3.6 environments.
This PR:

Pin dask upper version limits

---

changes/pr4347.yaml
src/prefect/core/flow.py

Speed up `flow.validate()` call. For a Flow with 1,000 tasks and 10,000 edges, `flow.validate()` call time drops from ~32 seconds to ~5 seconds. 
This PR stores calls to `Flow.all_upstream_edges` and `Flow.all_downstream_edges` as a variable when sorting flow tasks, and moves minor logic into `Flow._sorted_tasks` instead of relying other Flow methods.
By doing so, we avoid repeated cache validation calls which check that all tasks, edges, and reference tasks on the flow model remain the same as prior calls. https://github.com/PrefectHQ/prefect/blob/master/src/prefect/core/flow.py#L67
These validation calls become very expensive as flow size increases.
I also played around with the idea of some object level property to ignore cache validation, but it seemed like there were too many edge …

Speed up flow validation logic

---

changes/issue4318.yaml
src/prefect/serialization/storage.py
src/prefect/storage/bitbucket.py
tests/serialization/test_storage.py
tests/storage/test_bitbucket_storage.py

Added support for Bitbucket cloud into Bitbucket storage class
Added three class variables to Bitbucket class (workspace, cloud_username_secret, cloud_app_password_secret). When constructed with a workspace the class will switch to using the bitbucket cloud client; without it the behaviour for bitbucket server remains unchanged.
The retry adapter is not required and could be removed. Our Bitbucket cloud API gets a lot of requests and the limit is 5000 per hour.
A lot of people and businesses will be using Bitbucket cloud and not hosting their own bitbucket servers. 
This PR:

Add bitbucket cloud

---

changes/pr4368.yaml
src/prefect/core/task.py
tests/core/test_flow.py

When a task subclass is declared in the `with Flow..` context we instantiate a `Task()` object to check the reserved attributes. Unfortunately, this adds a `Task` to the `unused_task_tracker` set that will never be removed which will give users false warnings that they have task objects in their flow that are not called.
- Disable the unused task tracker during reserved attribute retrieval
Fixes incorrect warning
This PR:

Fix incorrect unused task tracking

---

changes/pr4373.yaml
src/prefect/cli/build_register.py
tests/cli/test_build_register.py

Explains to users who may not understand why their flow is being skipped during `prefect register` that skipping is okay with a couple small display changes.
e.g. https://prefect-community.slack.com/archives/CL09KU1K7/p1617827979177100
- Adds metadata note to `--help` message
- Adds note after each `Skipped` message
- Improves experience for non-power users / people unfamiliar with idempotency keys
This PR:

Improve messaging when a flow is skipped during registration

---

changes/pr4374.yaml
src/prefect/core/task.py
tests/core/test_task.py
tests/utilities/test_tasks.py

Flow context cannot be inferred if a task is called outside of the `with Flow()` block. This PR aims to help users quickly determine which task in a large script is causing this error.
e.g.
```
>>> from prefect import Flow, task
>>> @task
... def foo():
...    pass
... 
>>> foo()
File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect-core/lib/python3.8/site-packages/prefect/core/task.py", line 621, in __call__
new.bind(
File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect-core/lib/python3.8/site-packages/prefect/core/task.py", line 674, in bind
raise ValueError(
ValueError: Could not infer an active Flow context while creating edge to <Task: foo>. This often means you called a task outside a `with Flow(...)` …
```

Display a more helpful error when flow context cannot be inferred

---

changes/pr4384.yaml
src/prefect/utilities/executors.py
tests/utilities/test_executors.py

A couple error cases in the `run_with_multiprocess_timeout` typically used by the `TaskRunner` when running a threaded dask scheduler were not captured and logged which could lead to opaque failures of the timeout handler. This PR adds logging and error capturing to try to improve introspection during failure cases.
- Pickling errors are captured, logged, and returned so the user gets a clear description of result requirements while using this timeout handler. Previously, this would result in a `TimeoutError` because the queue would be empty.
- `Queue.put` errors are logged and re-raised. They cannot be returned to the main process because the queue is how we pass exceptions up. Logging with a traceback is our best way to improve this edge-case right now.
Several users have encountered …

Add error handling to timeouts that fail during result pickling or passing

---

changes/pr4351.yaml
src/prefect/agent/kubernetes/agent.py
src/prefect/cli/agent.py
tests/agent/test_k8s_agent.py
tests/cli/test_agent.py

Sometimes non-deterministic failures can happen in a flow that are hard to track down (e.g. memory issues) when running on k8s. When investigating these incidents it would be nice if k8s held onto the resources so one could dig deeper into them before they are deleted. The k8s agent's resource management is currently a bit greedy and it would be nice to disable the cleanup step when necessary. That way in testing/debugging scenarios an Agent can be spun up, perform normally, but one would get to interact with the resources before manually deleting them.
This adds a new flag to the Kubernetes agent `delete_finished_jobs` that when set to `False` will explicitly disable the job deletion. It can also be set via the `DELETE_FINISHED_JOBS` environment variable or the `--disable-job-deletion` …

Add option to disable the deletion of finished jobs in the Kubernetes agent

---

changes/pr4397.yaml
src/prefect/tasks/shell.py
tests/tasks/test_shell.py

The `ShellTask` does not work on win32 because it does not look for executables in the path by default. This sets `Popen(..., shell=True)` when using win32 which inspects the path for the given executable.
You still need `bash` installed and on your `PATH` for this to work by default. Other shells should work without issue as well, but `cmd.exe` does not seem to support running a script.
Closes #1984 https://github.com/PrefectHQ/prefect/issues/4393
This PR:

Fix `ShellTask` on win32

---

changes/pr4396.yaml
docs/orchestration/server/deploy-local.md
docs/orchestration/server/overview.md
src/prefect/cli/docker-compose.yml

Lowers the required docker-compose version to 1.18.0 and cleans up some of the work done in #4041 
- Lowers version of the compose-file from 3.7 to 3.5
- Drops `condition` from healthchecks (not recommended, support dropped in newer compose versions)
- Cleans up comments in compose file
- Adds minimum docker-compose version to docs
- Adds helm chart link to docs for using server
- Increases healthcheck intervals to reduce load from healthchecks
- Helps direct users to the best way to get docker running
- Both clarifies and expands the supported docker-compose versions
This PR:

Cleanup docker-compose for `prefect server start`

---

changes/pr4409.yaml
docs/core/concepts/flows.md
src/prefect/core/flow.py
src/prefect/engine/flow_runner.py
tests/core/test_flow.py

This PR allows the flow runner to pass a set of reference task states instead of all task states.
When running against Cloud or Server, `task_states` is not populated. Until we implement some sort of deferred task result retrieval in place, passing reference task states seems reasonable.
This PR:

Pass reference states to terminal handler

---

changes/pr4217.yaml
tests/conftest.py
tests/core/test_flow.py
tests/engine/test_flow_runner.py

Originally created in an attempt to replicate a user's issue on Linux. The issue could not reproduced but additional executor coverage is nice and we've been seeing a lot of use of `LocalDaskExecutor` with timeouts lately.
- Adds `threaded_local` executor fixture
- Uses executor fixture in relevant timeout tests
This PR:

Add threaded local dask executor to timeout tests

---

changes/pr4417.yaml
src/prefect/agent/ecs/agent.py
tests/agent/test_ecs_agent.py

The `botocore.Config` object does not load pre-existing settings so if a user tries to override this setting via environment variable, we will override them (which is not the intended behavior). Passing the variables via CLI is tricky because botocore expects a bunch of different types (ie we can't just take a (str, str) tuple of key value settings for to pass to `botocore_config`). This is the only setting we set a default for so this is an acceptable workaround for now. Users with more complex use-cases can start their agent via a custom python script rather than using the CLI. Note that this will likely not respect settings in an aws config file.
- Do not force the retry mode to be 'standard' if it is set already via environment variable
This PR:

Check for AWS_RETRY_MODE variable before setting default in `ECSAgent`

---

docs/orchestration/agents/kubernetes.md

TL;DR: The `-f` argument in `kubectl apply` has to be beside the `-` argument, without it you get an error that looks like:
```
$ prefect agent kubernetes install -t "<TOKEN>" --rbac -n "<namespace>" | kubectl create -f --namespace="<namespace>" -
error: Unexpected args: [-]
See 'kubectl create -h' for help and examples
```
Updates `docs/orchestration/agents/kubernetes.md` to show the correct ordering of arguments
Currently the Prefect provided instructions on applying the Prefect Agent configuration to Kubernetes clusters is broken.
This PR:

Fix ordering of kubectl apply arguments

---

changes/pr4424.yaml
docs/orchestration/server/deploy-local.md
src/prefect/cli/server.py
tests/cli/test_server.py

This PR adds support for external Postgres databases with `prefect server start`.
- Adds a new flag `--external-postgres`, which if True removes `postgres` from the docker compose file
- Adds a new flat `--postgres-url`, which takes in a connection string and removes `postgres` from the docker compose file
If this flag is passed, Hasura will use `config.server.database.connection_url` to connect to Postgres.
Example usage
In `.prefect/config.toml`
```
[server.database]
connection_url = "postgres://<username>:<password>@hostname:<port>/<dbname> "
```
From the command line
`prefect server start --external-postgres`
OR just from the command line
`prefect server start --postgres-url postgres://<username>:<password>@hostname:<port>/<dbname>`
Addresses …

Add external postgres support

---

changes/pr4435.yaml
src/prefect/core/flow.py
tests/core/test_flow.py

Fixes https://github.com/PrefectHQ/prefect/issues/4437, which caused a flow and its copies to refer to the same `slugs` dictionary.
Copies the `slugs` dictionary as part of calling `Flow.copy()`.
Not copying the `slugs` dictionary means that the dictionary can be modified by adding tasks to either the original flow or its copy, leading to `slugs` that are not in sync with the tasks in the flow.
This PR:

Fixed bug from Flow.copy() not copying the slugs dictionary

---

changes/pr4414.yaml
src/prefect/tasks/postgres/postgres.py

There are plenty of ways of doing this: 
* We could add other cursors like the MySQL task does and get column names through the results (DictCursor and NamedTupleCursor store field name values).
* Doing an extra query in order to fetch those values
I tried to keep it simple and use the `cursor` object that we've already have. I**f this change is out of scope** for the task, I think we should add different cursors support so the user can handle this without the need of extra querying,
It adds a boolean flag to the `PostgresFetch` task.
If it's set to `True` the task fetches column names through the already created cursor and merge it with the result set.
Defaults to `False` to avoid breaking anything already built with the current behavior.
It's a pretty common need when fetching data. …

Add column names to PostgresFetch

---

changes/pr4440.yaml
tests/core/test_flow.py
tests/storage/test_github_storage.py
tests/tasks/aws/test_s3.py

We construct some `GithubExceptions` in tests which have been changed in the newest PyGithub release to require `headers` to be passed per https://github.com/PyGithub/PyGithub/pull/1887
Passes fake `headers` to the test exceptions
Tests will not pass in CI using the newest PyGithub
This PR:

Fix compatibility with PyGithub >= 1.55

---

changes/pr4452.yaml
setup.py

`dask_kubernetes` now requires `kubernetes >= 12` but we limited it to roughly `< 11` which causes errors
- Increases the upper limit for `kubernetes` from 11 to 13
Closes https://github.com/PrefectHQ/prefect/issues/4451
This PR:

Upgrade `kubernetes` package requirement upper limit

---

changes/pr4458.yaml
src/prefect/tasks/prefect/flow_run.py

The link artifact produced by StartFlowRun is very handy for navigating from parent to child flow, but a log message (like what `prefect run flow` produces) would still be nice: you can see it right away when following the logs from the command line, and when the parent task is running outside cloud there's no artifact at all. cc @madkinsz @cicdw

Print link to flow run in StartFlowRun

---

changes/pr4482.yaml
src/prefect/tasks/gcp/storage.py
tests/tasks/gcp/test_gcs_upload_download.py

This PR enables GCSUpload to accept `io.BytesIO`. This allows more rich usage, e.g. making working with in memory buffers easier.
This PR enables GCSUpload to accept `io.BytesIO`.
This allows more rich usage, e.g. making working with in memory buffers easier.
This PR:

feat(GCSUpload): allow passing in BytesIO

---

changes/pr4468.yaml
src/prefect/cli/build_register.py
src/prefect/utilities/importtools.py
tests/cli/test_build_register.py

Currently `prefect register --module my_module` does not allow you to pass a full import path to a single flow. This PR modifies the logic slightly to allow `prefect register --module my_module.flow` to import a single flow from a module.
- Allows a full import path to a flow within a module to be passed
- Fixes bug in `import_object` when passed a module with no `.`
This allows me to:
- Create an example like `prefect register --project default --module prefect.hello_world`
- Disambiguate flows by full path rather than `--module` and `--name` pairing (which is still valid)
- Run a single flow given an import path e.g. `prefect run --module prefect.hello_world.flow --watch` (I use these functions in #4463)
This PR:

Allow `prefect build/register --module` to accept full import path to flow

---

docs/.vuepress/config.js
docs/orchestration/concepts/cloud_hooks.md

We removed the cloud hooks docs page when we added automations but we have not yet actually deprecated cloud hooks so should still have docs for them!  
Add back the cloud hooks docs page. 
Users are asking for the cloud hooks docs page: https://prefect-community.slack.com/archives/CL09KU1K7/p1619703330298800
This PR:

Add back cloud hooks docs page

---

changes/pr4419.yaml
src/prefect/tasks/gcp/bigquery.py

…_from_uri
Fixes logging of error when exception is thrown during BigQuery load_table_from_uri. Currently another exception is thrown due invalid handling.
This PR:

Fix BigQuery: logging errors if exception is thrown during load_table_from_uri

---

changes/pr4462.yaml
docs/orchestration/flow_config/run_configs.md
src/prefect/agent/kubernetes/agent.py
src/prefect/run_configs/kubernetes.py
src/prefect/serialization/__init__.py
src/prefect/serialization/run_config.py
tests/agent/test_k8s_agent.py
tests/run_configs/test_kubernetes.py
tests/serialization/test_run_configs.py

Adds an `image_pull_policy` to `KubernetesRun` config object
- Adds an `image_pull_policy` kwarg to `KubernetesRun` config object
- Adds imagePullPolicy to job template if `image_pull_policy` is `Always`, `Never` or `IfNotPresent`
This is a common gotcha for Kubernetes jobs, and is a result of the discussion on #4445 
Closes #4445 
This PR:

Add `image_pull_policy` option to `KubernetesRun` config

---

changes/pr4485.yaml
src/prefect/agent/docker/agent.py
tests/agent/test_docker_agent.py

Currently, `DockerAgent` container names are UUIDs (the default). It'd be nice to set the container names to the flow run name. However, container names must be unique so we must check for collisions to avoid blocking flow run execution. It seems like a rare case that there will be a collision (since we auto-remove containers) so we add a simple index `-{i}` to the end of the name if we encounter one.
- Sets the container name during creation by a `DockerAgent`
Improves usability / interaction with flow run containers.
This PR:

Set flow docker container names to flow run names

---

changes/pr4513.yaml
src/prefect/utilities/importtools.py
tests/utilities/test_importtools.py

For sub modules that are not attributes of the top-level module (ie `prefect.hello_world` is not imported in the `prefect` `__init__.py`), `import_object` will not attempt to load the submodule and instead throw an attribute error.
This will certainly cause issues in `prefect register --module my_module.sub_module`
- Updates `import_object` to be more robust
This PR:

Fix `import_object` handling of submodules that are not attributes

---

.circleci/config.yml

This job just breaks because the token is out of date and it's contrived to use a flow for it.

Remove the netlify pin flow from CI

---

requirements.txt

Pins `click` < 8.0. There's a dependency issue with `dask-distributed` here https://github.com/dask/distributed/issues/4812.
Dask executors using the Prefect image will not work if the newest version of `click` is installed.
This PR:

Add upper version click pin

---

changes/pr4524.yaml
src/prefect/agent/agent.py

Users are easily confused about whether or not their agent has actually respected the config arg since the UI does not display it. Here, we display it
- Adds a "registering" INFO log to `_register_agent` that includes the config id if set
Displaying the id that we are using at startup is useful for displaying that we have met their expectation
This PR:

Display the agent config id on agent startup if set

---

changes/pr4523.yaml
src/prefect/storage/docker.py
tests/storage/test_docker_storage.py

This base image is used when a user is not using a tagged Prefect version and was erroring on build. `pynacl` requires `make` which is apparently not installed in this image.
- Installs `make` during slim python base image builds
- Fixes a blocking `DockerStorage` error; likely mostly encountered by developers
This PR:

Fix `DockerStorage` building with python slim image

---

src/prefect/backend/flow.py
src/prefect/backend/flow_run.py
src/prefect/backend/task_run.py
tests/backend/test_task_run.py

Previously, `FlowRunView` supplied a `iter_mapped_task_runs` but it doesn't really make sense to have it there since the whole point of iterating is that your mapped results are too big to cache. The new workflow looks like...
```python
flow_run = FlowRunView.from_flow_run_id("...")
task_run = flow_run.get_task_run(my_mapped_task)
task_run.result  # [1,2,3,4,5]
for child in task_run.iter_mapped():
print(child.result)
```
- Removes `FlowRunView` mapped task iteration
- Adds `TaskRunView.iter_mapped()`
- Fixes `FlowView` repr missing newline
- Adds `map_index` kwarg to `TaskRunView.from_task_slug`
A better API
This PR:

Move mapped task interation from `FlowRunView` to `TaskRunView`

---

src/prefect/backend/task_run.py
tests/backend/test_task_run.py

Per discussion at #4530, updating this from a property to a method.

Rename `TaskRunView.result` to `TaskRunView.get_result()`

---

src/prefect/agent/agent.py
tests/agent/test_agent.py

Adds some comments explaining the query that is used during metadata retrieval and clarifies the filtering used for retries and duplicate submission prevention.  
- `_get_ready_flow_runs` returns a `Set[str]` of flow run ids instead of calling `_get_flow_run_metadata` directly
- `_get_flow_run_metadata` is called separately after `_get_ready_flow_runs` which will be useful for #4532 in which we may want to skip metadata queries
Clarifies confusing behavior; refactors a little to make #4532 simpler
This PR:
- ~[ ] adds a change file in the `changes/` directory (if appropriate)~ not user facing

Cleanup `Agent._get_flow_run_metadata`

---

changes/pr4457.yaml
src/prefect/tasks/notifications/email_task.py

This PR adds a new option to the `EmailTask`, allowing to send attachments with the email.
The email task now always creates a multipart-message. The user of the task can optionally pass a list of files that should be sent as attachment with the email. The files are looked up in the local filesystem and attached to the multipart-message.
Sending attachments with emails is a very common thing to do. A concrete use-case would be to extract and transform some data and then send the resulting data (as csv, Excel, etc.) via email.
This PR:

feat(email_task): sending attachments with emails

---

changes/pr4544.yaml
src/prefect/agent/kubernetes/agent.py

It looks like the event timestamp can be null per https://prefect-community.slack.com/archives/CL09KU1K7/p1621293779234300 while streaming event logs from K8s
- Events with null timestamps are ignored
Fixes bug
This PR:

Handle events with missing timestamps in K8s agent

---

.circleci/config.yml
src/prefect/cli/server.py
test-requirements.txt
tests/cli/test_server.py
tests/core/test_flow.py
tests/executors/test_executors.py
tests/utilities/test_edges.py

Improves test times in CI from 4m 20s to 1m 30s for a ~3x speedup by using `pytest-xdist` to parallelize execution.
- Identifies and reduces brittleness of some tests that are not robust to running in parallel
- Upgrades pytest/xdist
- Adds multiprocesss test execution to CI
- Fixes (hopefully) frequently brittle timeout test
Faster CI = Faster feedback
- Do we want a makefile or something instead of repeating the pytest args repeatedly? It'd be nice for local development too
- Appveyor is still slow, ought to replace it soon anyway
- Netlify builds block merge; is that necessary? We're not publishing `master` docs anyway so can we just make sure it passes before a release manually?

Enable parallel pytest runs with xdist

---

changes/pr4568.yaml
src/prefect/agent/agent.py
tests/agent/test_agent.py

Fixes bug where agents use `FlowRun.scheduled_start_time` instead of `FlowRun.state/serialized_state.start_time`. 
For Scheduled Runs, the "Start Now" functionality does not work because agents are waiting until the FlowRun's originally scheduled start time to execute. See issue originally filed in Cloud here https://github.com/PrefectHQ/cloud/issues/3410
This PR:

Fix bug where agents use scheduled_start_time instead of state.start_time

---

src/prefect/backend/flow_run.py

This simplifies this function and since task slugs are not actually generated unless the flow run has been serialized, it's not particularly useful.

Drop task object slug inference from `get_task_run`

---

changes/pr4561.yaml
docs/outline.toml
setup.py
src/prefect/tasks/gcp/__init__.py
src/prefect/tasks/gcp/secretmanager.py
tests/tasks/gcp/__init__.py
tests/tasks/gcp/test_secretmanager.py

Added a task to pull a secret from [Google Cloud Platform's Secret Manager](https://cloud.google.com/secret-manager).
(Used the [AWS Secrets Manager task](https://github.com/PrefectHQ/prefect/blob/0ef255107b7b3b00165772b29e675536368a1e03/src/prefect/tasks/aws/secrets_manager.py) as example).
- Adds a new task to optional extra `gcp` (`prefect.tasks.gcp.secretmanager.GCPSecret`).
This allows more seamless interaction with the Google Cloud Platform and brings the `gcp` extra just a little bit more inline with the `aws` one.
This PR:

Task Library: Add Google Cloud Platform Secret Manager

---

CHANGELOG.md
changes/pr4341.yaml
changes/pr4457.yaml
changes/pr4487.yaml
changes/pr4513.yaml
changes/pr4523.yaml
changes/pr4524.yaml
changes/pr4544.yaml
changes/pr4547.yaml
changes/pr4561.yaml
changes/pr4568.yaml
docs/.vuepress/config.js

Released on May 25, 2021.
- Refactor `Agent` base class for readability - [#4341](https://github.com/PrefectHQ/prefect/pull/4341)
- Display the agent config id on agent startup if set - [#4524](https://github.com/PrefectHQ/prefect/pull/4524)
- Add debug logs during agent auth verification - [#4547](https://github.com/PrefectHQ/prefect/pull/4547)
- Sending logs to Cloud can be globally disabled via config in addition to the agent flag - [#4487](https://github.com/PrefectHQ/prefect/pull/4487)
- Enable sending attachments with emails in the `EmailTask` - [#4457](https://github.com/PrefectHQ/prefect/pull/4457)
- Add Google Cloud Platform `GCPSecret` task - [#4561](https://github.com/PrefectHQ/prefect/pull/4561)
- Fix `import_object` handling of submodules that are not attributes - …

Release 0.14.20

---

src/prefect/cli/run.py
tests/cli/test_run.py

`prefect run ... --param name=hello` would fail before since strings need quotes. A simple try/repeat pattern gives us a automatic quoting for inputs like this without adding it to things like integers.
Usability of `--param` and `--context`
This PR:

`prefect run`: Add automatic quoting for JSON inputs

---

changes/pr4587.yaml
src/prefect/engine/results/local_result.py

It's possible for the result directory to be created between the `exists` check and creation. Noticed this during a CI failure.

Fix possible race condition in `LocalResult` directory creation

---

docs/core/getting_started/why-not-airflow.md

Update the page _Why Not Airflow?_ to talk about the UI repository on GitHub.
This PR updates the language to talk about the new (2020) UI repository.
The page _Why Not Airflow?_ is the #1 Google hit for the query "airflow vs prefect," but the section on Prefect's UI claims that the UI is only available in Prefect Cloud. 
This PR:
- Updates docs only

Tell people about the UI repository on GitHub

---

changes/pr4584.yaml
src/prefect/storage/docker.py

`forcerm=True` effectively disables the docker caching mechanism, which is quite useful when building images locally using `prefect register --watch`. With this change docker builds are now cached, massively reducing build and push times.
Remove `forcerm=True` from the docker build command.
Slow builds suck.
This PR:

Remove forcerm=True from DockerStorage

---

src/prefect/agent/local/agent.py
src/prefect/backend/flow_run.py
src/prefect/cli/run.py
src/prefect/tasks/prefect/flow_run.py
tests/backend/test_flow_run.py

It seems clunky to pass a callable so instead I'm yielding log objects and the consumer can do as they wish with them without a callback
- `watch_flow_run` has a 12hr timeout; makes sense and prevents a test from hanging forever
- Adds a test for `watch_flow_run`
- `watch_flow_run` is of type `Iterator[FlowRunLog]` instead of taking a `Callable[[FlowRunLog], None]` and returning a `FlowRunView`
This PR:

Run Flow API: Update `watch_flow_run` to be an iterator

---

changes/pr4593.yaml
src/prefect/cli/build_register.py
tests/cli/test_build_register.py

- Fixes bug where relative path was used instead of absolute path when auto-creating `Local` storage
- Fixes bug where `flow.storage.labels` weren't being mirrored to the `run_config`/`environment` labels. This only affected local storage flows (no hostname label applied).
Fixes #4572
This PR:

A few register CLI fixes

---

src/prefect/tasks/mysql/mysql.py

This PR introduces changes that address two issues #3845 and #4377. This should enable the mysql tasks to be configured completely from just the `run` method via secrets/params and also allows `ssl` options to be configured when creating a mysql connection.
- update all init args to be keyword args
- update all run args to have all the same keyword args as __init__ and overrided via the `defaults_from_attrs` decorator
- support passing a `ssl` keyword argument with a dict to configure ssl when connecting
- Allows Parameters and Secrets to be used for this task, which makes this task better support prefect features
- Allows ssl options to be configured so MySQL DB's with TLS >= 1.2 can be connected to with these tasks.
This PR:

Support all arguments in MySQL Tasks' run methods and support SSL configuration

---

changes/pr4602.yaml
src/prefect/executors/dask.py

dask >= 2021.04.0 adds task submission batching in the multiprocessing case
to offset performance concerns from switching to a concurrent.Futures based
process pool. Since we are using our own pool to handle cancellation robustly,
we do not gain anything from the batched submission and the default task
submission batch size of 6 makes users think their flows will not run in
parallel. When/if we switch to using the new futures based multiprocessing in
dask, we should remove this to retain performance
- Sets `chunksize=1` for the process based `LocalDaskExecutor`
Closes https://github.com/PrefectHQ/prefect/issues/4537
This PR:
- ~[ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs …

Fix small-flow parallelism issues with multiprocess `LocalDaskExecutor`

---

changes/pr4605.yaml
src/prefect/engine/runner.py
src/prefect/engine/state.py
tests/engine/test_state.py

While using the `DaskExecutor`, if a task fails with an exception that cannot be pickled by `cloudpickle`, Dask will fail to send the failure back to the flow runner as the `Failed` state containing the exception as a result cannot be pickled. This PR adds more robust handling to `State` pickling to handle exception pickle failures.
- Adds `State.__getstate__` which will cast unpickable exception results to a string with helpful information
Prefect should be able to report task failure cleanly
This PR:

Cleanly handle unpicklable exceptions in tasks

---

docs/orchestration/concepts/flow_runs.md

Updates the documentation to replace an out of date command `prefect run server/cloud` with the new `prefect run flow`.

docs: update `prefect run` reference

---

.github/workflows/test_windows.yml
test-requirements.txt

Encountering things like `ValueError: signal only works in main thread of the main interpreter` intermittently on Windows. Likely introduced by timeouts or parallelism or both together. Investigating a fix...
Re-ran this job 3x and didn't see any failures; hopefully this resolves flakeyness

Remove timeouts from CI windows tests

---

docs/orchestration/flow-runs/inspection.md
docs/orchestration/flow-runs/task-runs.md
docs/outline.toml
src/prefect/backend/flow.py
src/prefect/backend/flow_run.py
src/prefect/backend/task_run.py
src/prefect/tasks/prefect/flow_run.py
tests/backend/test_task_run.py
tests/tasks/prefect/test_flow_run.py

Finalizing `FlowRunView`, `FlowView`, and `TaskRunView` interfaces
- Add experimental warnings
- Adds labels to `FlowRunView` repr
- Convert properties to methods if they hit the API
- Add check for current flow run id to `get_task_run_result`
- Cleanup flow run task docstrings
- Add error for custom result types which we cannot support yet (discovered via https://github.com/PrefectHQ/prefect/issues/4636)

Run Flow API: Cleanup view object interfaces

---

changes/task_timeout_as_int_or_timedelta.yaml
src/prefect/core/task.py
tests/core/test_task.py

Besides the original seconds `int`, the Task timeout parameter can also be a `timedelta` object.
- Task timeout parameter from `int` type to `Union[int, timedelta]` type.
- `Task.timeout` is still an `int`, `Task.__init__` converts the `timedelta` to seconds.
- Does not break changes, and sub-second timeouts are still not supported.
Consistency with other Task parameters such as `retry_delay` which do take a `timedelta` object.
This PR:

Task timeout as either int or timedelta

---

changes/startflowrun_wait_interval_parameter.yaml
src/prefect/tasks/prefect/flow_run.py
tests/tasks/prefect/test_flow_run.py

Add `waiting_interval` parameter to `StartFlowRun` to define the polling interval when waiting for the flow run to finish.
- `waiting_interval` parameter added to `StartFlowRun` initializer.
- Adds a unit test for `StartFlowRun(wait=True).run()`
The [default (and fixed) 10 seconds wait](https://github.com/PrefectHQ/prefect/blob/1867f205405e1f68b828ce9dcf00bbd4969903bc/src/prefect/tasks/prefect/flow_run.py#L198) has been slowing down my flow unit tests with flows depending on `StartFlowRun` Tasks. By making this a variable parameter I can speed up my unit tests significantly. There might be other cases where we want to speed up the waiting polling frequency.
This PR:

Add waiting_interval parameter to StartFlowRun

---

changes/pr4657.yaml
src/prefect/agent/agent.py
src/prefect/engine/runner.py
src/prefect/engine/task_runner.py
tests/agent/test_agent.py
tests/engine/cloud/test_cloud_task_runner.py
tests/engine/test_task_runner.py

`get_task_run_state` calls `task.run(...)`. This method is wrapped with `call_state_handlers` which will turn an exception into an `Failed(f"Unexpected error: {repr(exc)}")` state. I want to try to reserve "Unexpected" errors for errors that _we_ do not expect to occur rather than errors in user code. I've added a new exception -> `Failed` state trap in `get_task_run_state` that more clearly states the source of the error and logs the stack trace.
- Adds `Exception` -> `Failed` handling directly in `get_task_run_state`
- Adds `exc_info` to show a stack trace for unexpected exceptions in `call_state_handlers`
We should strive never to hide stack traces from the logs & have consistent error messaging.
This PR:
- ~[ ] updates docstrings for any new functions or function arguments, including …

Ensure stack traces are included in logs during task run exceptions

---

changes/pr4655.yaml
src/prefect/backend/kv_store.py
tests/backend/test_kv_store.py

This PR adds a check for the size of value in a kv pair before sending to Cloud.
- Adds a check for value size
- Adds tests for value over 10 KB limit
- Adds test cases for setting json-like objects
This limit is also enforced by the API, but handling it on the client side makes debugging easier.
This PR:

Add client side check for value size

---

changes/pr4644.yaml
src/prefect/core/flow.py
tests/core/test_flow.py

Adds optional parameter to the `core.flow.update` method to preserve the reference tasks from the provided flow when updating the current flow with a provided flow.
`update` method has an optional `merge_reference_tasks` parameter to add reference tasks from the provided flow to the updated flow.
When stitching flows together sometimes it is desirable to not lose the reference tasks set on the two sub-flows.
This PR:

Add merge reference tasks option in flow update

---

CHANGELOG.md
changes/pr4539.yaml
changes/pr4608.yaml
changes/pr4644.yaml
changes/pr4655.yaml
changes/pr4657.yaml
changes/startflowrun_wait_interval_parameter.yaml
changes/task_timeout_as_int_or_timedelta.yaml

Released on June 15, 2021.
- Use `functools.update_wrapper` for `FunctionTask` - [#4608](https://github.com/PrefectHQ/prefect/pull/4608)
- Optionally retain reference tasks when updating two flows - [#4644](https://github.com/PrefectHQ/prefect/pull/4644)
- Add client side check for key value size - [#4655](https://github.com/PrefectHQ/prefect/pull/4655)
- Ensure stack traces are included in logs during task run exceptions - [#4657](https://github.com/PrefectHQ/prefect/pull/4657)
- Add `poll_interval` parameter to `StartFlowRun` to define the polling interval when waiting for the flow run to finish - [#4641](https://github.com/PrefectHQ/prefect/pull/4641)
- Task timeout can be timedelta as well as integer in seconds - [#4619](https://github.com/PrefectHQ/prefect/pull/4619)
- Add ssh …

Release 0.14.22

---

changes/pr4665.yaml
src/prefect/utilities/git.py

This PR fixes an issue with `Git` storage on Windows where the `dulwich` library was still accessing repo files, causing temporary directory cleanup to fail.
See related dulwich thread here https://github.com/dulwich/dulwich/issues/584
`Git` storage needs to work on Windows.
This PR:

Fix git storage on windows

---

examples/tutorial/aircraftlib/opensky.py

Change opensky api request timeout to 300 seconds.
I tried to run the tutorial code, but the timeout window of only 10 seconds was far too low.
I tried to run the request manually and got the following request time in seconds:
Setting this timeout to 300 will help to not break the code when facing low quality internet problems.

Increase opensky request timeout to 5m

---

changes/pr4683.yaml
src/prefect/agent/docker/agent.py
src/prefect/agent/ecs/agent.py
src/prefect/agent/kubernetes/agent.py
src/prefect/agent/local/agent.py
src/prefect/client/client.py
tests/agent/test_docker_agent.py
tests/agent/test_ecs_agent.py
tests/agent/test_k8s_agent.py
tests/agent/test_local_agent.py

This provides backwards compatibility when running an agent authenticated with a 0.15.0 API key that deploys flow runs running in containers that require token based authentication
- All agents set `PREFECT__CLOUD__AUTH_TOKEN` to `PREFECT__CLOUD__API_KEY` if an auth token is not available.
- The `Client` will not warn if it receives an API key and an API token but they are identical
Backwards compatibility for flow runs
This PR:

Pass API keys as tokens as well when creating flow run environments

---

docs/orchestration/concepts/api.md
src/prefect/backend/tenant.py
src/prefect/cli/auth.py
src/prefect/client/client.py
tests/agent/test_docker_agent.py
tests/agent/test_ecs_agent.py
tests/agent/test_k8s_agent.py
tests/agent/test_local_agent.py
tests/backend/test_tenant.py
tests/cli/test_auth.py
tests/cli/test_create.py
tests/client/test_client.py
tests/client/test_client_auth_compat.py

Previously, if using an API key `Client.tenant_id` would return `None` if a tenant had not been explicitly set. The backend will infer the default tenant for us and there's no reason to query for it. However, `Client.tenant_id` is used by the agent during registration (why it's not just inferred from authentication, I'm not sure -- cc @cicdw). Unfortunately this means that #4676 broke launching agents with API keys. This behavior was generally confusing anyway as it required `client.tenant_id or client.get_auth_tenant()` if you wanted to _for sure_ get the current tenant id without always querying the backend so I think this is probably worth doing.
- The `tenant_id` property now retrieves the default tenant for the key and sets `_tenant_id` for API keys on first use
- Saving auth to disk …

Always retrieve the tenant id in the Client

---

changes/pr4695.yaml
src/prefect/engine/flow_runner.py
tests/core/test_flow.py

If a flow is loaded from an older version of Prefect, it may not have a `terminal_state_handler` attribute and the check in the `FlowRunner` will result in a failed flow like so
```
INFO     prefect.FlowRunner:flow_runner.py:710 Flow run SUCCESS: all reference tasks succeeded
ERROR    prefect.FlowRunner:runner.py:66 Unexpected error: AttributeError("'Flow' object has no attribute 'terminal_state_handler'")
File "/Users/mz/prefect/core/src/prefect/engine/runner.py", line 48, in inner
new_state = method(self, state, *args, **kwargs)
File "/Users/mz/prefect/core/src/prefect/engine/flow_runner.py", line 669, in get_flow_run_state
state = self.determine_final_state(
File "/Users/mz/prefect/core/src/prefect/engine/flow_runner.py", line 720, in …
```

Fix backwards compatibility for flows without a `terminal_state_handler`

---

changes/pr4669.yaml
src/prefect/tasks/sendgrid/sendgrid.py
tests/tasks/sendgrid/test_sendgrid.py

Change SendGrid SendEmail task to just use the given secret _value_, instead of manually using the secret name to get the secret value.
Remove use of hardcoded `SENDGRID_API_KEY` secret.
This change then outsources the `get`ting of the secret's value.
This change allows more flexibility with how the key is given to the Task.
Previously, "Prefect-native" secrets had to be used.
This change allows getting the secret value manually in a flow, e.g. a secret saved in GCP Secret Manager, or AWS Secrets Manger. It also allows more flexibility, since the user can now save the actual secret value as a JSON blob (they just need to convert the value to a string before using this Task).
This PR:

SendGrid.SendEmail task - use Secret value

---

src/prefect/hello_world.py
tests/tasks/docker/test_images.py

Now that the `prefect run` changes are in `master`
Includes a fix to a flakey docker test

Add `prefect run` example to `hello_world` module docstring

---

changes/pr4693.yaml
src/prefect/agent/kubernetes/agent.py
tests/agent/test_k8s_agent.py

Follow-up to https://github.com/PrefectHQ/prefect/pull/4544 which dropped events with null timestamps which now accounts for events missing timestamp attributes _entirely_
- Uses `getattr` to check for the attribute
- Logs these events so we can see what's going on

Fix missing event timestamp attribute errors in K8s agent

---

docs/orchestration/ui/interactive-api.md

I replaced the broken link to the Hasura docs. (It was 404ing before.) Also added a bit more of a description to let people know that there are many more ways to query available described in the hasura docs.
Replaced a broken link to the Hasura docs and made it a bit more descriptive so people would understand that following the link would explain the many options for querying they have. 
A broken link and a single sentence in the documentation.
I'm new to graphQL and using prefect for work. It wasn't super clear where I was supposed to go to read how to build more complex queries. (ie. the options available to query) I actually was reading the docs, clicked on that broken link, thought eh whatever, and spent hours just trying to look around for where I was actually supposed to find …

Replaced broken link to Hasura docs

---

changes/pr4708.yaml
src/prefect/backend/task_run.py
tests/backend/test_task_run.py

If a result is not set, it can be set to the `Result` base class which we detect as a "Custom" result type. This PR detects the case where there's actually no result type or location at all and raises an informative error.
After further investigation, I found there is a `NoResultType` class and mapped parents always have a `Result` base class and no location -- adding handling for those cases as well.
This PR:

Raise a better exception when a task run result type is not set

---

changes/pr4715.yaml
src/prefect/agent/local/agent.py
tests/agent/test_local_agent.py

If a flow process fails, we want to show the return code value for some transparency into what went wrong.

Display return code on local agent flow process failure

---

src/prefect/cli/run.py
tests/cli/test_run.py

This is a silly thing I did with the agentless branch merge that makes it show an unexpected state when not watching a flow run.
```
mz@mz-test-instance:~$ prefect run --name "hello-world"
Looking up flow metadata... Done
Creating run for flow 'hello-world'... Done
└── Name: bronze-whale
└── UUID: c8234085-a220-414e-97d9-39f8784ed24f
└── Labels: ['mz-test-instance']
└── Parameters: {}
└── Context: {}
└── URL: http://localhost:8080/default/flow-run/c8234085-a220-414e-97d9-39f8784ed24f
Flow run is in unexpected state: <Scheduled: "Flow run scheduled.">
```

If not watching/executing, exit without trying to display final state

---

src/prefect/agent/docker/agent.py

Until something like https://github.com/docker/cli/issues/2290 is done, Docker on Linux treats "host.docker.internal" differently than on OSX/Win32 so users encounter connection issues as in https://github.com/PrefectHQ/server/issues/25
Per https://github.com/moby/moby/pull/40007 we add an extra host mapping with a "magic" string that is resolved to the correct host IP. This reimplements the workaround that was removed in https://github.com/PrefectHQ/prefect/pull/4446 but relies on docker to determine the host ip which we were doing ourselves before (leading to exceptions in edge-cases).

Add "host.docker.internal" mapping for linux compatibility

---

changes/pr4709.yaml
src/prefect/cli/run.py
tests/cli/test_run.py

When watching, executing, or locally executing a flow, we will return an non-zero exit code if the flow run is not successful. This means in something like CI it would actually mark the step as failed.
This PR:

Exit with non-zero status on flow run failure when watched

---

changes/pr4744.yaml
src/prefect/engine/task_runner.py
tests/engine/test_task_runner.py

If a user wants to customize the state message but still end successfully, they can do
```python
raise prefect.engine.signals.SUCCESS("My custom message", result=<data>)
```
but because state signals bypass checkpointing logic, this task result is not stored in the provided `Result` location.
- Removes a signal re-raise that was a workaround while waiting for #4664 
- `SUCCESS` signals are treated like a successful task run instead of falling through
- Allows setting custom state messages while returning data
- Makes task run result checkpointing more consistent
This PR:

Checkpoint task results when `SUCCESS` is raised

---

changes/pr4751.yaml
src/prefect/cli/agent.py
tests/cli/test_agent.py

When starting an agent, `--key` can be provided. This sets a temporary config so the agent client will load the value. We were not falling back to the default though so if `--key` as not provided and it was set in the config or env it would be ignored.
Users can workaround by providing `--key` when starting the agent, using `prefect auth login`, or passing the key as an `PREFECT__CLOUD__AUTH_TOKEN`
- Fixes this by falling back to the default if `--key` or `--tenant-id` are not provided
Fixes bug where agents cannot be started with env based auth
This PR:

Fix loading of `PREFECT__CLOUD__API_KEY` environment variable when starting agents

---

changes/pr4758.yaml
src/prefect/client/client.py
tests/client/test_client.py

When using tokens for authentication, we have a few routes that call `get_cloud_url` with an explicit `as_user=False` because they are expected to be called from flow runs with a RUNNER (vs USER) scoped token. When using an agent with a RUNNER scoped token, a tenant id is not set by `_init_tenant` and is `None` during tenant slug lookup required for generating a cloud url.
Supersedes https://github.com/PrefectHQ/prefect/pull/4755 -- this will throw a better error if no tenants are returned.
Unlike https://github.com/PrefectHQ/prefect/pull/4753, this keeps the `as_user` interface for compatibility. We can remove it once API tokens are removed in the next major version.
- Returns the first tenant id if none is set and `as_user` is `False`
Resolves a bug where `slack_notifier` and …

Fix tenant slug retrieval when using auth tokens

---

changes/pr4759.yaml
src/prefect/client/client.py
tests/client/test_client_auth_compat.py

When an agent is spawned with a token `prefect agent local start -t <RUNNER_TOKEN>` on a machine that has auth saved with `prefect auth login -t <USER_TOKEN>`, it can result in broken authentication. When a tenant id is loaded from disk, the `Client` attempts to log in to the tenant. On failure, it will log out which clears auth information from disk. A non-user scoped token will _always_ fail to log in even though it is authenticated for other operations. Before 0.15.0, the agent used a different api server url than the default `Client` which would prevent this from clearing the user's login information. Now that the api server url is consistent, the agent can actually log out the user by clearing the `active_tenant_id` from disk.
Now, on failure to login, we will check that the token is …

Fix bug where an agent using token auth could clear the tenant from disk

---

docs/core/tutorial/02-etl-flow.md

Task Library" towards the bottom of the page leads to https://docs.prefect.io/core/task_library/ which gives a 404 error. 
issue can be seen here #4679
the link should be https://docs.prefect.io/core/task_library/overview.html.
The PR is important as it fixes a 404 link
This PR:

fix Docs - Task Library Not Found 

---

test-requirements.txt
tests/backend/test_execution.py
tests/core/test_flow.py
tests/executors/test_executors.py

It is now consuming an unacceptable amount of time to re-run CI due to a few tests that always succeed on re-run. I'd rather fix the tests than auto-rerun them but that isn't entirely feasible at the moment and some tests are flaky by nature. At the very least, this will indicate to us which tests need additional attention when we have more throughput.

Install flaky to auto-rerun known/marked flaky tests

---

requirements.txt
setup.cfg
tests/core/test_flow.py

Gets tests working again
- Pins the version of `requests`
the requests dependency shift to charset_normalizer is responsible for the new failures in graphql tests in Core https://docs.python-requests.org/en/latest/community/updates/#id1
charset_normalizer causes encoding an empty json string and subsequently decoding using requests to fail and raise the warning
tests/utilities/test_graphql.py::TestFormatGraphQLResponseError::test_empty_error_does_not_throw_exception
tests/utilities/test_graphql.py::TestFormatGraphQLResponseError::test_displays_query_and_variables
/usr/local/lib/python3.8/site-packages/charset_normalizer/api.py:95: UserWarning: Trying to detect encoding from a tiny portion of (2) byte(s).
warn('Trying to detect encoding from a tiny portion of ({}) byte(s).'.format(length)) …

Pin requests version

---

changes/pr4767.yaml
docs/orchestration/flow_config/storage.md
src/prefect/utilities/storage.py
tests/utilities/test_storage.py

This PR adds support and documentation for loading external files using `Git` storage.
- When extracting a flow from a file, pass the file path as `__file__`
- Document `Git` storage use case where additional files are loaded
Closes #4754 
This PR:

Git storage extra files

---

changes/issue4773.yaml
src/prefect/agent/docker/agent.py
src/prefect/run_configs/docker.py
src/prefect/serialization/run_config.py
tests/agent/test_docker_agent.py
tests/run_configs/test_docker.py

This PR allows to pass runtime commands to the Docker Agent via a host_config dictionary in the DockerRun config.
The DockerRun config allows for an additional argument which is the host_config. The Docker agent
adds the provided host_config to the default host_config, overwriting any defaults.
This PR will allow for more flexibility in how Prefect Flows are deployed with Docker.
This PR:
- [ x] adds a change file in the `changes/` directory (if appropriate)

Docker run host config

---

changes/pr4752.yaml
src/prefect/cli/build_register.py

Enables toggling schedule activation upon CLI flow registering. Useful for CI and development
Related issue: https://github.com/PrefectHQ/prefect/issues/4531
1. New CLI option `--schedule/--no-schedule` for the `register` command. Defaults to `--schedule`.
2. This option is passed down util it reaches `register_serialized_flow` and adds a new `input` called `et_schedule_active` to GraphQL request.
This will help with some CI use cases.
This PR:

Expose schedule activation from `prefect register` CLI

---

CHANGELOG.md
changes/pr4736.yaml
changes/pr4761.yaml
changes/pr4792.yaml
docs/.vuepress/config.js

- Allow CLI registration of flows without starting their schedule `prefect register --no-schedule` - [#4752](https://github.com/PrefectHQ/prefect/pull/4752)
- Add `host_config` to `DockerRun` to expose deeper settings for Docker flow runs - [#4733](https://github.com/PrefectHQ/prefect/issues/4773)
- Enable loading additional repository files with `Git` storage - [#4767](https://github.com/PrefectHQ/prefect/pull/4767)
- Update flow run heartbeats to be robust to exceptions - [#4736](https://github.com/PrefectHQ/prefect/pull/4736)
- Allow `prefect build/register` paths to contain globs for recursion - [#4761](https://github.com/PrefectHQ/prefect/pull/4761)
- Fix duplicate task runs in `FlowRunView.get_all_task_runs` - [#4774](https://github.com/PrefectHQ/prefect/pull/4774)
- Fix zombie …

Release 0.15.2

---

CHANGELOG.md

~The docs appear to have not built from #4794 so this is an empty commit to ask netlify to rebuild them so I can update the site~
The docs built, netlify was just slow. This just fixes a PR tag in the changelog.

Fixup changelog entry

---

changes/ge_task.yaml
src/prefect/tasks/great_expectations/checkpoints.py
tests/tasks/great_expectations/test_great_expectations_validation.py

Added support for passing evaluation parameters as an argument to the `RunGreatExpectationsValidation` task.
Makes it easy to calculate evaluation parameters on the fly, obtain from Prefect `Parameter`s, or anywhere else. Example with [KV Store](https://docs.prefect.io/orchestration/concepts/kv_store.html#ui):
```python
from prefect.tasks.great_expectations import RunGreatExpectationsValidation
from prefect.backend import get_key_value
prev_run_row_count= get_key_value(key="prev_run_row_count")
great_expectations_task = RunGreatExpectationsValidation()
great_expectations_task.run(
batch_kwargs=batch_kwargs,
expectation_suite_name=expectation_suite_name,
evaluation_parameters=dict(prev_run_row_count=prev_run_row_count)
)
```
This PR:

Add evaluation parameters to `RunGreatExpectationsValidation`

---

changes/pr4802.yaml
src/prefect/cli/run.py
tests/cli/test_run.py

When using a param like `--param foo=0xxx`, the JSON package throws an error noting that there's "Extra data" after the numeric character which does not match our auto-quoting exception check.
- Parameters with a leading numeric character are quoted for the user
Fixes auto-quoting expectations
This PR:

Fix auto-quoting for strings that begin with numeric characters

---

changes/pr4801.yaml
src/prefect/tasks/prefect/flow_run.py
tests/tasks/prefect/test_flow_run.py

When retrieving URLs from tasks using auth tokens (vs API keys) we need to specify that we are not using a USER scoped token or it will lack permissions to find the default tenant.
Passes `as_user=False` when retrieving a flow run URL
Closes #4799 
This PR:

Fix `create_flow_run` compatibility with auth tokens

---

src/prefect/engine/result/base.py
tests/engine/result/test_base.py

Removes result validation references, this logic was never implemented.
It's confusing to have these unused methods/properties on `Result`
This PR:

Remove results validators

---

tests/tasks/test_shell.py

- `test_shell_logs_non_zero_exit` fails with exit code 1 in my env
- no fixed rules for parsing nonzero codes, checking for 2 is brittle
`test_shell_logs_non_zero_exit` fails because the `ShellTask` fails with exit code 1, instead of 2. After some digging, it looks like M1 Macs ship with an older version of `bash` that consistently returns a different error code than Intel-Macs when trying to `ls` a nonexistent directory.
Moreover, since the test is only looking to see that `ShellTask` can return a useful output, as opposed to checking that the error is tied to a specific shell implementation and there is no convention on how to parse nonzero exit codes, I think we should simply remove the error code check from the test.
In `tests/tasks/test_shell.py::test_shell_logs_non_zero_exit` parse …

Do not look for a specific error code

---

changes/pr4855.yaml
src/prefect/tasks/dropbox/__init__.py

Fixes a typo with `ImportError` for the dropbox module (previously `ImportErro`)
Fixes a typo with `ImportError` for the dropbox tasks (previously `ImportErro`)
Could cause errors when importing the dropbox module since `ImportErro` is unrecognized
This PR:

Fix importerror typo in dropbox module

---

docs/core/concepts/tasks.md

Add a couple of pieces of info to the docs to answer a question from a client.
Adds a tip to the the tasks.md docs file, clarifying that task retries don't create new task runs.
Helping to keep docs helpful for customers. Thanks!
This PR:
- [ X] adds new tests (if appropriate)
- [ X] adds a change file in the `changes/` directory (if appropriate)
- [ X] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

Clarifying task retry in docs

---

changes/pr4871.yml
src/prefect/engine/signals.py

I am just changing two lines with the ENDRUN docstring. Multiple users have gotten the expectation that it would shut down the entire Flow because of the way it is currently written. I also just added a use case to use this to avoid task retries.
This PR:

Updating ENDRUN Docstring

---

changes/pr4876.yaml
src/prefect/agent/kubernetes/agent.py
src/prefect/agent/local/agent.py
src/prefect/cli/agent.py
tests/agent/test_k8s_agent.py
tests/cli/test_agent.py

Users are trying to set the `agent-config-id` for installed agents so they can use SLAs
- Adds the `--agent-config-id` CLI option
Easier to install SLAs w/ kubernetes agents
This PR:

Add `--agent-config-id` to `prefect agent <kubernetes|local> install

---

changes/pr4874.yaml
src/prefect/executors/dask.py

Described in #4874 - the tl;dr is that it would be handy to allow subclasses of the `DaskExecutor` to handle scheduler messages in their own way.
This refactors the current `_watch_dask_events` loop to call `_on_scheduler_message`, where it can be overriden
Watching scheduler events seems non-trivial, making it easily extensible is very handy to some use-cases. 
This PR:

Add a _on_scheduler_message callback to the DaskExecutor. Closes #4874

---

changes/pr4800.yaml
src/prefect/agent/docker/agent.py
tests/agent/test_docker_agent.py

Supersedes #4800 
A `bind` was not being generated in the `host_spec` for named volumes. Consequently, the volumes were attached but not available from inside the container as expected. This PR adds proper `bind` specs for named volumes.
- `bind` clauses are generated for named volumes
Fixes a bug on win32/unix where named volumes were not available in the flow container
`prefect agent docker start --volume my_named_volume:/tmp`
This PR:

Fix binding of named volumes to flow containers with Docker agent

---

src/prefect/storage/gitlab.py

Current gitlab storage is broken for any repository paths containing forward slash. The structure is common in gitlab since repositories can belong to projects. [The function used for URL quoting](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote)(`urllib.parse.quote_plus`) defaults to escaping all characters. The PR mirrors behavior of a similar function `urllib.parse.quote` by setting safe character to `/`
Sets default value for `urllib.parse.quote_plus` `safe` to `/`since originally it escapes all special characters
Allow for repo paths to contain forward slashes which are common in gitlab projects and repositories structure.
Minor fix 
This PR:

Fix default safe char for gitlab storage repo path

---

changes/pr4870.yaml
docs/orchestration/flow_config/storage.md
src/prefect/serialization/storage.py
src/prefect/storage/git.py
tests/storage/test_git_storage.py

This PR allows users to pass a secret name containing the exact clone url for `Git` storage.
Resolves #4850. I suspect there will be other cases where providers don't use standard syntax for cloning and this logic should cover those cases.
This PR:

Allow custom clone urls with `Git` storage

---

src/prefect/utilities/logging.py

Extend warning in case of log writing issues for better understanding of the current log pressure.
Extends the _write_logs exception handler to contain more information.
Helps to better understand the current tried to send log size (pending_length) and the current log pressure in case of log sending issues like:
```
.../prefect/lib/python3.9/site-packages/prefect/utilities/logging.py:124: 
UserWarning: Failed to write logs with error: 
HTTPError('413 Client Error: Request Entity Too Large for 
url: https://api.prefect.io/graphql')
warnings.warn(f"Failed to write logs with error: {exc!r}")
```
This PR:

Extend warning in case of log writing issues

---

docs/orchestration/flow_config/storage.md

The keyword arg is not `path` but `flow_path` for  the Git storage class, see [here](https://docs.prefect.io/api/latest/storage.html#git)
A small fix of the docs, correcting a wrong example.

Correct flow_path keyword arg for Git storage

---

.circleci/config.yml
Dockerfile

Noticed these images don't exist but Prefect has supported 3.9 for almost a year so it seems about time 🙂

Build Docker image for Python 3.9

---

changes/pr4821.yaml
src/prefect/cli/docker-compose.yml
src/prefect/cli/server.py
src/prefect/config.toml

By default docker-compose services listen to all host interfaces, meaning all machines in the connected networks have direct access to services exposing a port.
This commit sets the binding IP to localhost by default to mitigate this security issue.
* Limited services exposing ports to localhost in `prefect server` cli
* Add `--expose` flag to `prefect server` cli to make the Core server and UI listen to all interfaces
This is quite important as it fixes a security issue when working with a local environment.

[cli] Prevent server access from the outside

---

changes/pr4771.yml
src/prefect/tasks/aws/batch.py

Log boto exception in aws.BatchSubmit when submit_job fails
Logged the exception that is caught when calling boto.client.submit_job in order to improve debugging when batch submit fails.
Added additional logging to aws.BatchSubmit task [here](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/aws/batch.py#L94) 
Save developers time when debugging batch submit failuer
- No tests or dockstrings were added as they were not necessary / applicable for the PR
This PR:
- [ x] adds a change file in the `changes/` directory (if appropriate)

Log boto exception in AWS BatchSubmit task

---

changes/pr4903.yaml
src/prefect/serialization/schedule.py
src/prefect/serialization/state.py
src/prefect/serialization/storage.py

https://github.com/PrefectHQ/prefect/issues/4540
`serialization` was erroneously using the kwarg `key` to
marshmallow.fields.Dict, this should be `keys`. Marshmallow was seeing
this as `additional_metadata`, so showing a deprecation warning.
Fixes uses of `marshmallow.fields.Dict` to use `keys` correctly as a kwarg
rather than `key`. 
(See https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html#marshmallow.fields.Dict).
Fixes uses of `marshmallow.fields.Dict` to use `keys` correctly as a kwarg
rather than `key`.
Fixes a warning raised by prefect. Our test flow has errors raised on warnings, so we had to
explicitly ignore this error throughout our test runs.
This PR:

Fix marshmallow metadata kwarg deprecation warning

---

changes/pr4907.yaml
src/prefect/tasks/mysql/mysql.py
tests/tasks/mysql/test_mysql.py

This PR introduces a fix to a bug introduced in #4545 that is highlighted by issue #4885: Runtime arguments were ignored over task init arguments.
A task such as
```python
password_from_secret = "MySecretPassword"
task = MySQLFetch()
task.run(user="admin", host="localhost", port="3302", password=password_from_secret)
```
would fail because `pmysql.connect` would be called with `self.password` which would be `None` in this scenario.
A task such as
```python
password_from_secret = "MySecretPassword"
task = MySQLExecute(user="admin", host="localhost", port="3302", password="password")
task.run(password=password_from_secret)
```
would also fail if only `password_from_secret` contains the correct password because `pymysql.connect` would be called with `self.password` which would be …

Fix MySQL tasks that never use runtime arguments

---

src/prefect/agent/docker/agent.py
tests/agent/test_docker_agent.py

Quick fix that will need some real testing on linux systems; we may want to warn if we cannot set the value. Alternatively, we could just expose the host-config on the docker agent CLI and allow a user to override this field.

Only set `host-gateway` if docker version is compatible

---

changes/pr4917.yaml
src/prefect/backend/execution.py
tests/backend/test_execution.py

Includes the local environment in agentless flow runs by default. This was previously not available as I did not want to expose the entire local environment to flow runs--it seemed like a security risk. 
Alternatively, we could allow opt-in for a list of environment variables or encourage users to pass thing via prefect local secrets.
Users frequently store environment variables that their flows needs on the machine their flow runs on
This PR:

Pass existing environment variables to agentless flow runs

---

docs/core/concepts/mapping.md

Prefect already provides a built-in functionality to filter the output
of mapped tasks that should be used in downstream tasks. This commit
adds a paragraph with an example.
Update Mapping documentation with an example of filtering mapped tasks output.
Update `docs/core/concepts/mapping.md
This could save someone else some time when building flows with mapped tasks.
This PR:

Add output filtering example to Mapping docs

---

changes/pr4914.yaml
src/prefect/client/client.py
tests/client/test_client.py
tests/client/test_client_auth_compat.py

Patch `client.py` to properly retrieve the `api_server` from the prefect context. 
Add a missing `self` for api_server
This bug caused downstream issues when spawning dask workers on a kubernetes cluster. The api_server was reset to the cloud api instead of the one provided in the context. 
This PR:

Patch client.py to properly retrieve the api_server from the prefect context.

---

changes/pr4928.yaml
src/prefect/cli/run.py
tests/cli/test_run.py

Exposes the `idempotency_key` flow run setting with `prefect run --idempotency-key <key>`
Requested by user, CLI/client feature parity
This PR:

Add `--idempotency-key` to `prefect run`

---

changes/pr4436.yaml
src/prefect/tasks/exasol/exasol.py
tests/tasks/exasol/test_exasol.py

Prefect Secret support for Exasol tasks
- Prefect Secret support for Exasol Tasks
- Pass the name of a Prefect Secret for dsn string, user or password. ** To discuss**: should we make it possible to pass the secrets even at runtime?
- Removes deprecated constructor parameters user and password ([deprecated since 0.14.13](https://github.com/PrefectHQ/prefect/pull/4268#pullrequestreview-615513989))
- Unittests
- `ExasolExecute` doesn't return the `ExaConnection` object anymore, because it's not serializable. **To discuss**: we could maybe return the executed statement or the execution time??
As it's best pratice to use Prefect Secret it should be supported directly. It makes it easier for use because it's not neccessary to introduce Prefect Secret tasks to the flow.
This PR:

Prefect Secret support for Exasol tasks

---

src/prefect/cli/server.py

Adds missing docstring for API docs page for `prefect server start --expose`

Add `--expose` to API docs

---

changes/pr4968.yaml
src/prefect/tasks/postgres/postgres.py

This fixes a bug in PostgresFetch where TypeError is raised when fetch = "one" (default) and col_names = True.
As the psycopg cursor.fetchone() method returns a Tuple[Any] and not a List[Tuple[Any]] as cursor.fetchall and cursor.fetchmany the concatenation of tuple and list fails. This puts the single tuple row into a list when col_names is true.
Fixes a bug, "one" is the default fetch argument but I don't think it's used that often and less so in conjunction with headers and therefore not discovered yet.
This PR:

Fix PostgresFetch with headers for one row

---

changes/pr4970.yaml
src/prefect/utilities/tasks.py
tests/utilities/test_tasks.py

Given the following flow
```python
from prefect import Flow, apply_map, task
@task
def do_something_one(item):
return item + 1
@task
def do_something_two(item, item_one):
return item + item_one
@task
def do_something_three(item_combination):
return item_combination[0] + item_combination[1]
def apply_map_one_two(item):
result_one = do_something_one(item)
result_two = do_something_two(item, result_one)
return (result_one, result_two)
def apply_map_three(item):
return do_something_three(item)
with Flow("test flow") as flow:
l = [1, 2, 3]
results = apply_map(apply_map_one_two, l)
results_results = apply_map(apply_map_three, results)
```
We were creating this graph which adds an edge in the _wrong_ direction from `Tuple` to `do_something_one`
This flow now has a cycle and will not execute. The …

Fix bug where `apply_map` could create cyclic flows

---

docs/orchestration/recipes/multi_flow_storage.md

The links for the tutorials for `ETL` and `Map Reduce` on the top of the page are broken. 
This PR changes both the `ETL` and the `Map Reduce`. The former seems to have been put in the `advanced tutorials` page, and the latter was updated to the `reduce` part of the `mapping` concept page.
This PR aims at enabling users to click the links in the `Multi Flow Storage` example and not receive a `404 Page Not Found` error.
This PR:

Fix broken `ETL` and `Map Reduce` urls of the `Multi Flow Storage` doc page

---

changes/pr4971.yaml
src/prefect/core/task.py
tests/core/test_task.py
tests/engine/test_task_runner.py

Allow `max_retries` to be set at the task level to 0, overriding config setting
This PR resolves https://github.com/PrefectHQ/prefect/issues/4880
The below code now executes correctly when `max_retries` and `retry_delay` is already specified at the config level.
```
@task(max_retries=0, retry_delay=None)
def my_task():
...
```
This PR is important because it can be useful to have a single specific task not retry and it matches what the parameters intended.
This PR:

Allow max_retries=0 override at task level

---

docs/core/getting_started/install.md

I'm not sure which style applies, but the `$` in some of the CLI commands means that you cannot paste as-is. This PR removes the `$`. The other approach is to modify the copy and paste script to strip any leading `^$\s?`.
This PR:

Remove $ from code examples for copy and paste

---

docs/core/tutorial/07-next-steps.md

It looks like the links for "Task Looping" and "Signalling" are broken here: https://docs.prefect.io/core/tutorial/07-next-steps.html#advanced-control-structures. I made some semi-educated guesses about where these should point, but please let me know if this should be changed. Thanks!

Fix broken doc links

---

CHANGELOG.md
changes/pr4436.yaml
changes/pr4924.yaml
changes/pr4943.yaml
changes/pr4955.yaml
changes/pr4968.yaml
changes/pr4970.yaml
changes/pr4971.yaml
docs/.vuepress/config.js

- Improve setting the Azure storage connection string - [#4955](https://github.com/PrefectHQ/prefect/pull/4955)
- Allow disabling retries for a task with `max_retries=0` when retries are globally configured - [#4971](https://github.com/PrefectHQ/prefect/pull/4971)
- Allow Exasol Tasks to handle Prefect Secrets directly - [#4436](https://github.com/PrefectHQ/prefect/pull/4436)
- Adding [Census](https://www.getcensus.com/) Syncs to the task library - [#4935](https://github.com/PrefectHQ/prefect/pull/4935)
- Fix bug where `LocalDaskExecutor` did not respond to a `PrefectSignal` - [#4924](https://github.com/PrefectHQ/prefect/pull/4924)
- Fix `PostgresFetch` with headers for one row - [#4968](https://github.com/PrefectHQ/prefect/pull/4968)
- Fix bug where `apply_map` could create acyclic flows …

Release 0.15.6

---

changes/pr4981.yaml
src/prefect/tasks/database/sqlite.py
tests/tasks/test_sqlite.py

This allows for query parameterization when running queries against a SQLite database using the `SQLiteQuery` task. Currently if users want to include variables in a query string they'll have to do manual string formatting / escaping which is error-prone and in some cases dangerous. Adding this capability also aligns the API with that of other database tasks such as `PostgresExecute`.
Side comment, but since other database engines are in their own directories (e.g., `postgres`, `mysql`), should this directory be called `sqlite` instead of `database`?
Adds an optional `data` argument to the `SQLiteQuery` task.
More API consistency and helps end users avoid certain types of errors.
This PR:

Add data parameter to SQLiteQuery

---

changes/pr4996.yaml
src/prefect/utilities/tasks.py
tests/utilities/test_tasks.py

Adds `flatten` support to `apply_map`.
`flatten` edge annotations were missing in the implementation of `apply_map` . Now, an edges flatten property is derived via the same way its mapped property is derived, and all instances of `flow.add_edge` in `apply_map` use this flattened edge indicator. 
Flattening nested structures before mapping over is a widespread use case. Complex mapping pipelines that necessitate `apply_map` should be able to benefit from `flatten` as well. 
Old behavior silently disregards the flatten edge annotation, therefore I think this is strictly an enhancement, and hope it doesn't make any breaking changes.
- I will add tests soon, and then make this an actual PR.
- Admittedly, I don't fully understand the `apply_map` implementation. I just put flatten bool values …

Add flatten support to apply_map

---

changes/pr 5019.yaml
docs/core/advanced_tutorials/advanced-mapping.md
docs/core/advanced_tutorials/calculator.md
docs/core/advanced_tutorials/dask-cluster.md
docs/core/advanced_tutorials/using-results.md
docs/core/concepts/results.md
docs/core/concepts/states.md
docs/core/faq.md
docs/core/idioms/task-results.md
docs/orchestration/agents/local.md
docs/orchestration/agents/overview.md
docs/orchestration/concepts/flows.md
docs/orchestration/execution/storage_options.md
docs/orchestration/flow-runs/creation.md
docs/orchestration/flow-runs/overview.md
src/prefect/client/secrets.py

- Removing redundant text
- Removing the broken link from ResultHandler which doesn't exist
Just fixing some documentation typos.

Typos in the documentation

---

docs/orchestration/tutorial/overview.md

The installation instructions link in the overview is broken.
It points to: https://docs.prefect.io/core/getting_started/installation.html, but should be https://docs.prefect.io/core/getting_started/install.html
Documentation points to working link: https://docs.prefect.io/core/getting_started/install.html
Documentation
This PR:

Fix broken link in documentation

---

changes/pr5103.yaml
src/prefect/storage/azure.py
tests/backend/test_execution.py
tests/storage/test_azure_storage.py

Azure storage will fail if a blob already exists, however if setting a blob name manually you generally want to overwrite the existing blob instead of failing. This PR adds that option.
- `overwrite: bool = False` is added to the `Azure` storage config
Allows `blob_name` use in non-trivial cases.
Closes #4618 
This PR:

Allow `Azure` storage to overwrite existing blobs

---

changes/pr5066.yaml
src/prefect/agent/kubernetes/agent.py
src/prefect/config.toml
src/prefect/utilities/kubernetes.py
tests/agent/test_k8s_agent.py
tests/utilities/test_kubernetes.py

In some environments, the [kubernetes agent fails to deploy flows (and also on other tasks involving the kubernetes API server) due to the server closing the connection after some time being idle.
[This has been observed when running the kubernetes cluster within the Azure Kubernetes Service](https://prefect-community.slack.com/archives/C014Z8DPDSR/p1631240218210500) (but possibly others too). The firewall / loadbalancer closes idle connections after 4 minutes. The urllib3 connection pool used by the kubernetes client library then tries to connect to the server which results in a ReadTimeoutError. Thus the flow deployment is stuck in the submitted state and is only rescued by the Lazarus agent after 15 minutes.
This PR introduces keep-alive messages so that the connection will be kept …

Fixed ReadTimeoutErrors for kubernetes client after connection reset by keep-alive connections

---

docs/.vuepress/styles/index.styl

Increase vertical padding on code blocks in the [docs](https://docs.prefect.io/) from `1.25rem` to `1.5rem` to stop a scroll bar from appearing.
Before:
After:
Not very important.
This PR:

Add padding to code blocks to remove scroll bar

---

changes/pr5084.yaml
setup.py

Remove constraint on bigquery dependency that it must be below version 2.0.
My project is now using a newer (2.x) version of Biquery and is incompatible with the constraints in prefect's setup.py if I want the GCP extra.
No APIs need to be changed according to the migration guide since we are not using any removed/deprecated items. 
https://googleapis.dev/python/bigquery/latest/UPGRADING.html
Other users probably have encountered this issue or will likely encounter it. The 2.x google bigquery library has been out since September 2020. https://pypi.org/project/google-cloud-bigquery/#history 
This PR:

update bigquery dependency to support version 2.0

---

docs/core/concepts/secrets.md

Based on https://github.com/PrefectHQ/prefect/blob/57dbb113114603a743bec2fc407307336a9f2385/src/prefect/storage/github.py#L159-L166, it seems to me that Default Secrets can only come from locally configured settings, not from Cloud Secrets. This updates the documentation to reflect that.
Clarify where Default Secrets can come from, to try to avoid confusion
This PR:

Add clarification about default secrets

---

docs/core/getting_started/install.md
docs/orchestration/flow-runs/inspection.md
docs/orchestration/flow-runs/task-runs.md
docs/orchestration/getting-started/install.md
docs/outline.toml
src/prefect/backend/flow.py
src/prefect/backend/flow_run.py
src/prefect/backend/task_run.py
src/prefect/backend/tenant.py

_This merges into #5113_
Removes experimental labels from
- Backend views
- Python 3.9
- Artifacts

Remove experimental warnings

---

changes/pr5116.yaml
src/prefect/backend/flow.py
tests/backend/test_flow.py
tests/cli/test_run.py

Because the backend can manipulate the serialized flow for optimization reasons (#4930) and the `FlowView` eagerly deserialized the data, we encountered full breaking changes everywhere a `FlowView` was used (https://github.com/PrefectHQ/server/pull/309, https://github.com/PrefectHQ/prefect/issues/4957). Here, the `FlowView` only deserializes the flow when requested and allows some bad data. A disclaimer has been added to the docstring.
- Adds `FlowView.flow` property instead of deserializing at init time
`FlowView` is used in things like the CLI and shouldn't break entirely because the serialized flow doesn't load correctly.
This PR:

Update the `FlowView` to be more robust to serialized flow changes in the backend

---

changes/pr5117.yaml
docs/.vuepress/config.js
docs/outline.toml
src/prefect/__init__.py
src/prefect/artifacts.py
src/prefect/backend/__init__.py
src/prefect/backend/artifacts.py
src/prefect/tasks/great_expectations/checkpoints.py
src/prefect/tasks/prefect/flow_run.py
tests/artifacts/test_artifacts.py
tests/backend/test_artifacts.py
tests/tasks/prefect/test_flow_run.py

With the introduction of `prefect.backend` in `0.15.0`, there was an intention to move the existing `artifacts` API there. This matches the location of other backend-only specific features like the kv-store.
- Adds warnings to old artifact functions
- Moves artifact functions to new module
- Adds `_artifact` suffix where needed to artifact create/update functions
The old artifacts location can be removed in #5113 
This PR:

Move artifacts functions to `prefect.backend.artifacts`

---

src/prefect/tasks/prefect/flow_run.py
tests/tasks/prefect/test_flow_run.py

Pretty self-explanatory...it's present on `StartFlowRun` but not the new `create_flow_run`.
Also copied over the `create_link_artifact` call because why not?
cc @madkinsz

Add idempotency_key to create_flow_run task

---

src/prefect/tasks/prefect/flow_run.py
tests/tasks/prefect/test_flow_run.py

Artifact creation was added to `create_flow_run` in #5125 but when users map over this task it will create _many_ artifacts which is not particularly helpful. I'd rather encourage users to create artifacts in a subsequent task. We could consider adding this later with a toggle, but I'd rather lean minimal.
`wait_for_flow_run` does not reflect the final state of the child flow run like `StartFlowRun(wait=True)` does. Here, we add this functionality with an opt-in `raise_final_state` bool. This was noted in #5095 and will unblock that work.
- Remove artifact creation from `create_flow_run`
- Add `raise_final_state` bool to `wait_for_flow_run`
Additional feature parity for new child flow run tasks
This PR:
- ![ ] adds a change file in the `changes/` directory (if appropriate)~ Will add …

Add `raise_final_state` bool to `wait_for_flow_run`

---

CHANGELOG.md
src/prefect/agent/kubernetes/agent.py
src/prefect/utilities/kubernetes.py
tests/agent/test_k8s_agent.py
tests/executors/test_executors.py

Fixes breaking change introduced by https://github.com/PrefectHQ/prefect/pull/5066 where kubernetes agents will fail to initialize if the `KUBERNETES_API_KEY` secret does not exist.
The error looks like
```
File "/usr/local/lib/python3.7/site-packages/prefect/agent/kubernetes/agent.py", line 142, in __init__
self.batch_client = get_kubernetes_client("job")
File "/usr/local/lib/python3.7/site-packages/prefect/utilities/kubernetes.py", line 62, in get_kubernetes_client
kubernetes_api_key = Secret(kubernetes_api_key_secret).get()
File "/usr/local/lib/python3.7/site-packages/prefect/client/secrets.py", line 169, in get
) from None
ValueError: Local Secret "KUBERNETES_API_KEY" was not found.
```
This PR restores the previous behavior where kubernetes agents do not attempt to use secrets while …

Fix missing secret while using kubernetes agent

---

docs/.vuepress/config.js

This hotfix release fixes an issue where the kubernetes agent would attempt to load a secret value and fail if it was not present.
See [the PR](https://github.com/PrefectHQ/prefect/pull/5131) for details.

Release 0.15.9

---

changes/issue5110.yml
docs/core/about_prefect/why-not-airflow.md
src/prefect/agent/local/agent.py
src/prefect/run_configs/ecs.py

- added examples in ECSRun to show when custom IAM roles must be provided and when those can be skipped
- clarified that all roles must be passed using a full ARN
- fixed confusing docs about versioning and local agent
Related to #5110

Documentation fixes: ECSRun ambiguities in IAM roles in the ECSRun docstring

---

changes/pr5138.yaml
src/prefect/backend/flow_run.py
tests/backend/test_flow_run.py

`watch_flow_run` uses `FlowRunView.get_logs` to stream logs from the flow run. Since `get_logs` only would retrieve logs _before_ `FlowRunView.updated_at`, the logs would not stream until the flow run object changed in the backend (ie, the state changed). Instead, we'd like to stream logs as they are written. We resolve this by adding an optional `end_time` parameter to `get_logs` and `watch_flow_run` always sends `pendulum.now()`.
Note: `FlowRunView.get_logs` used `updated_at` by default still because we want the logs to be _scoped_ to the view.
- Adds `FlowRunView.get_logs` tests
- Adds `end_time` to `get_logs`
- Uses `end_time=pendulum.now()` in `watch_flow_run`
Resolves a bad UX.
This PR:

Add `end_time` to `FlowRunView.get_logs`

---

changes/issue5130.yml
src/prefect/agent/docker/agent.py
src/prefect/run_configs/docker.py
src/prefect/serialization/run_config.py
tests/agent/test_docker_agent.py
tests/run_configs/test_docker.py
tests/serialization/test_run_configs.py

Expose container ports when using Prefect's DockerRun. 
closes #5130 
`ports` (optional) argument in `DockerRun` run_config, which the are list of ports used to expose container ports.  
This PR:

Expose ports in docker run

---

src/prefect/storage/bitbucket.py

This is a simple PR to stop a `DeprecationWarning`
```
Using 'method_whitelist' with Retry is deprecated and will be removed in v2.0. Use 'allowed_methods' instead
``` 
Use `allowed_methods` instead of `method_whitelist` in the Retry object
This will ensure compatibility with future versions 
These points are all pretty much n/a
This PR:

Use allowed_methods in Retry as method_whitelist is depreciated 

---

changes/issue4540.yaml
src/prefect/serialization/schedule.py

This change fixes a deprecation warning that had been previously taken care of by PR #4903. It seems after that PR was merged some code using marshmallow's fields.Dict class was added that used the deprecated keyword argument `key` again. This just switches that over to use `keys` instead. The marshmallow deprecation itself was [made in marshmallow 3.10](https://github.com/marshmallow-code/marshmallow/blob/dev/CHANGELOG.rst#3100-2020-12-19) and you can see the issue in https://github.com/marshmallow-code/marshmallow/issues/1350.
There are no new tests with this because the code change is so small. Nothing has changed which existing tests would not cover.
For more information see #4903
This should resolve #4540
When using `marshmallow.fields.Dict` use `keys` as a kwarg rather than `key`. …

Resolve marshmallow deprecation warning

---

CHANGELOG.md
src/prefect/agent/docker/agent.py
tests/agent/test_docker_agent.py

The API URL used by the agent can be unconnectable from within a spawned flow run container when using Prefect Server. Currently, we replace `localhost` with `host.docker.internal` to fix this. However, this is brittle in some cases which we've been patching (e.g. #4714, #4809, #2433)
With the change to limit exposure of the API by default in #4821, when `--expose` is not used on server startup, it is not connectable even with `host.docker.internal`. In #5156, I documented adding the `prefect-server` network to the run containers to allow them to connect, but this does not work on Linux. This PR replaces `host.docker.internal` with `apollo` if the `prefect-server` network is detected so that the internal network is used. This allows running an agent and server side-by-side without the …

Allow override of Prefect API url in docker runs and improve inference

---

docs/orchestration/concepts/api.md

Corrects the graphql query docs to use `flow_runs` in place of `flow_run`
Change gql query to fetch flow in https://docs.prefect.io/orchestration/concepts/api.html#queries
```diff
- flow_run(order_by: { start_time: desc }, limit: 1) {
+ flow_runs(order_by: { start_time: desc }, limit: 1) {
```
As stated in #4922 Previous docs used `flow_run` which would not work
This PR:
~~- [ ] adds new tests (if appropriate)~~ 

docs(gql): use flow_runs instead of flow_run

---

changes/pr5220.yaml
docs/core/examples/overview.md
docs/generate_docs.py
docs/test_generate_docs.py

The examples we have in [this docs](https://docs.prefect.io/orchestration/tutorial/next-steps.html#examples) page don't work as reported in [this discussion](https://github.com/PrefectHQ/prefect/discussions/5215). 
Trying to run these vie the UI raises:
`Failed to load and execute Flow's environment: ValueError('Flow is not contained in this Storage')`
There are three Flows there and all of their storage look like the following. The important part is that `flows` is empty. When the Flow Run is triggered, there is no Flow to search for in the storage.
```
"storage": {"access_token_secret": null, "path": "examples/parameters.py", "ref": "d44b72a950ebda9f7bc6a9712fc71e2e9c680d25", "flows": {}, "repo": "PrefectHQ/prefect", "base_url": null, "secrets": [], "__version__": …
```

Fixing Serialized Flow Examples in Docs

---

src/prefect/utilities/executors.py
tests/utilities/test_executors.py

A user was running into an indeterminate issue with the multiprocess based handler. While investigating, I added some useful logs and discovered what `queue.empty()` is not reliable and the stdlib documentation recommends not using it at all. Additionally, joining a process before we've retrieved data from a queue can cause deadlocks. Previously, we even sent a SIGTERM to the process before retrieving the data.
- Adds pickling/unpickling debug logs
- Uses `queue.get(block=True, timeout=timeout)` instead of `process.join(timeout)`

Improve multiprocess based timeout handler

---

changes/pr5001.yaml
src/prefect/agent/kubernetes/agent.py
src/prefect/utilities/compatibility.py
tests/agent/test_k8s_agent.py

Allowing imagePullSecrets in Kubernetes agent to be unset in job YAML when it is unused.  This patch fixes compatibility issues with releases of Kubernetes before (v1.19.13, v1.20.9, v1.21.3) because it triggers this bug https://github.com/kubernetes/kubernetes/pull/103133 which manifests issues such as this https://github.com/kubernetes/autoscaler/issues/4353 
Very minor tweak that allows what appears to be intended to be possible which is to unset the imagePullSecrets key entirely if this value is unset or empty.  The supporting code in this file has certain code paths to `del` this key which would never be possible without this adjustment (lines 581 and 896 of `agent/kubernetes/agent.py`)
Fixes an issue with cluster-autoscaler and Kubernetes releases prior to v1.19.13, v1.20.9, v1.21.3 …

Kubernetes agent job YAML allowing imagePullSecrets to be unset as code intended

---

changes/pr5288.yaml
docs/core/idioms/flow-to-flow.md

The current code example in Flow of Flows is broken. It calls the task twice like this:
```python
with Flow("parent-flow", schedule=weekday_schedule) as flow:
flow_a = create_flow_run(flow_name="A", project_name="examples")
wait_for_flow_a = wait_for_flow_run(flow_a, raise_final_state=True)
flow_b = create_flow_run(flow_name="B", project_name="examples")
wait_for_flow_b = wait_for_flow_run(flow_b, raise_final_state=True)
b = wait_for_flow_b(upstream_tasks=[wait_for_flow_a])
```
But the task is meant to be only called once.
I fixed the code examples for Functional API.
I am also removing Imperative API versions because they are not Imperative to begin with and are pretty close to the Functional API.
This is a widely news documentation page and paradigm for Prefect users.
This PR:

Fixing flow of flows code

---

docs/orchestration/flow-runs/creation.md

Update the docs for Idempotency to indicate non-expiry of idempotency keys.
This PR updates the docs for Idempotency to indicate the non-expiry of idempotency keys, updating the previous stale docs for the same as discussed in #4976 
Closes #4976 
This PR:
- ~~[ ] adds new tests (if appropriate)~~
- ~~[ ] adds a change file in the `changes/` directory (if appropriate)~~
- ~~[ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)~~

docs: update idempotency docs to indicate no expiry

---

docs/orchestration/flow-runs/inspection.md

adds an example of `flow_run.get_logs()`
Example was missing, had to look in the source/object for the call
This PR:

add flow_run.get_logs() example

---

changes/pr5237.yaml
src/prefect/utilities/notifications/notifications.py
tests/utilities/notifications/test_notifications.py

Add `proxies` argument to `slack_notifier`.
`prefect.utilities.notifications.slack_notifier` now passes a new optional `proxies` argument to `requests.port` to send requests to the Slack webhook through proxies.
- Allows to send Slack notifications through proxies when required.
- Resolve #5236 
This PR:

Add proxies argument to slack_notifier

---

docs/orchestration/getting-started/basic-core-flow.md
docs/orchestration/getting-started/registering-and-running-a-flow.md

Fixes issue in https://github.com/PrefectHQ/prefect/issues/5098
Orchestration Getting Started tutorial starts by demonstrating in a REPL and is missing the explicit instructions to save the flow as a file, but the file is used in later steps.
Adds example of running from a file in https://docs.prefect.io/orchestration/getting-started/basic-core-flow.html
Adds reference to previously saved file, and updates terminal output to reflect 0.15.10 output in https://docs.prefect.io/orchestration/getting-started/registering-and-running-a-flow.html
Responds to user confusion about where the file to run was created.
This PR:
~~- [ ] updates docstrings for any new functions or function …

Docs - run a flow explanation missing step to save as a file

---

docs/.vuepress/config.js
docs/orchestration/concepts/api_keys.md
docs/orchestration/execution/custom_environment.md
docs/orchestration/execution/dask_cloud_provider_environment.md
docs/orchestration/execution/dask_k8s_environment.md
docs/orchestration/execution/fargate_task_environment.md
docs/orchestration/execution/k8s_job_environment.md
docs/orchestration/execution/local_environment.md
docs/orchestration/execution/overview.md
docs/orchestration/execution/storage_options.md
src/prefect/storage/gitlab.py

note this PR merges into a 1.0.0 release candidate branch instead of master
Documentation edits to reflect deprecations in 1.0.0rc
Reflects the following changes with deprecation PR noted.
[1.0.0] Drop client handling of authentication tokens #5140
https://github.com/PrefectHQ/prefect/pull/5140
Added warning for legacy token usage and additional notes on from the PR:
status CLI command
Configuration for containers
Affects https://docs.prefect.io/orchestration/concepts/api_keys.html#using-api-keys
Retain legacy environment docs, but update note that environments are no longer supported #5072
https://github.com/PrefectHQ/prefect/pull/5072
Revised warning to note that environments are deprecated and links to current RunConfig documentation.
Remove docs.prefect.io domain from API doc links. …

Docs changes to address 1.0.0rc deprecations (revised)

---

.circleci/config.yml

Adds build and publish of docker images for the `1.0.0rc` branch (not yet created). A copy of the publishing of development artifacts for `master`.

Add build of release candidate docker image

---

.circleci/config.yml

This appears necessary for `1.0rc` branch development artifacts to build.

Add release candidate builds to `master` config

---

CHANGELOG.md
changes/issue5172.yaml
changes/pr5001.yaml
changes/pr5190.yaml
changes/pr5194.yaml
changes/pr5220.yaml
changes/pr5232.yaml
changes/pr5233.yaml
changes/pr5237.yaml
changes/pr5288.yaml
docs/.vuepress/config.js

- Allow passing kwargs to `Merge` task constructor via `merge()` function - [#5233](https://github.com/PrefectHQ/prefect/pull/5233)
- Allow passing proxies to `slack_notifier` - [#5237](https://github.com/PrefectHQ/prefect/pull/5237)
- Update `RunGreatExpectationsValidation` task to work with latest version of `great_expectations` - [#5172](https://github.com/PrefectHQ/prefect/issues/5172)
- Allow unsetting kubernetes `imagePullSecrets` with an empty string - [#5001](https://github.com/PrefectHQ/prefect/pull/5001)
- Improve agent handling of kubernetes jobs for flow runs that have been deleted - [#5190](https://github.com/PrefectHQ/prefect/pull/5190)
- Remove `beta1` from kubernetes agent template - [#5194](https://github.com/PrefectHQ/prefect/pull/5194)
- Documentation improvements - …

Release 0.15.11

---

src/prefect/storage/docker.py
tests/storage/test_docker_storage.py

`Docker` storage needs special handling to detect release candidate versioning and use the proper base image tag

Add release candidate support to `Docker` storage

---

src/prefect/utilities/settings.py

Small fix to allow setup HOST and PORT via env vars
Added missed `class Config` for class APISettings
Currently you can not change HOST/PORT for web UI 
This PR:

Allow to setup HOST and PORT via env vars

---

docs/tutorials/dask-task-runner.md
docs/tutorials/execution.md

Fix error in example in `docs/tutorials/execution.md`:
```
TypeError: too many positional arguments
```

Orion: Fix docs execution example

---

src/prefect/orion/api/saved_searches.py
src/prefect/orion/models/saved_searches.py
tests/orion/api/test_saved_searches.py
tests/orion/models/test_saved_searches.py

Fix typo "SavedSearchs" -> "SavedSearches" (missing "e").

Orion: Fix typo SavedSearchs

---

docs/core/getting_started/install.md

Addresses [this suggestion](https://github.com/PrefectHQ/prefect/issues/3453#issuecomment-1003677122)

Remove Python 3.9 warning from install guide

---

changes/pr5292.yaml
src/prefect/client/client.py
tests/client/test_client.py

This allow more network errors to happen on unstable  networks or when the graphql service is temporarily unavailable

Robust communication on server or cloud instances

---

changes/pr5231.yaml
src/prefect/tasks/aws/step_function.py
tests/tasks/aws/test_step_function.py

Allow the StepActivate task to accept arguments in the `run` method.
- Allow arguments to be passed to the `run` method.
- Fix the assertion to check which arguments were passed to the `start_execution` boto call. `called_method.assert_called_once_with` was passing regardless of which arguments it was checking against.
AWS requires step functions to have a unique name for every execution. Only prefect's `run` method allows for arguments to be dynamic.
This PR:

StepActivate task now accepts run args

---

changes/pr5310.yaml
src/prefect/backend/flow.py
src/prefect/backend/flow_run.py
tests/backend/test_flow.py
tests/backend/test_flow_run.py

If the `Flow/FlowRun.run_config` is null then the `Flow` and `FlowView` will fail to deserialize it.
- Only deserialize run configs if they exist
Fixes a bug in the `prefect run` CLI when a flow is registered with an `Environment`.
This PR:

Fix bug where null `run_config` fields cause deserialization errors in backend views

---

changes/pr5314.yaml
src/prefect/tasks/airbyte/airbyte.py
tests/tasks/airbyte/test_airbyte.py

Currently an exception is thrown within the health check function when trying to trigger a connection in Airbyte.
The non-existing key from the response used for the health check is replaced by a valid, existing key.
Without the change it is not possible to execute an AirbyteTask successfully, because this will always lead to a KeyError: 'db'.
This PR:

Fix response key in airbyte task health check

---

docs/core/development/contributing.md

The docs listed `server` as a possible heading for a changelog file, but this contradicts the linter. 
The section list in the docs has been changed to match [the list in the linter](https://github.com/PrefectHQ/prefect/blob/master/update_changelog.py#L10).
Guidelines without this change can lead you to write a PR that doesn't pass in CI.
This PR:

Remove "server" changelog heading from contribution docs

---

src/prefect/backend/flow_run.py

When a flow run errors with this RuntimeError, the message did not display the actual flow run state, but literally the variables in curly braces.
This PR marks a string as format string.
It allows Prefect encountering this error to get more insight into the flow run state and why the error could have happened.
This PR:

Fix format string not interpolated in error message

---

docs/orchestration/ui/team-settings.md

Fixes incorrect link from ["roles"](https://docs.prefect.io/orchestration/ui/team-settings.html#switching-teams) to discussion of RBAC roles. 
Preview [Team Settings](https://deploy-preview-5334--prefect-docs.netlify.app/orchestration/ui/team-settings.html)
Closes https://github.com/PrefectHQ/prefect/issues/5331
- team-settings.md - replace with link to /orchestration/rbac/overview.html
Returns a 404 for the URL https://docs.prefect.io/orchestration/concepts/roles.html, which is a nonexistent page.
This PR:

Docs: Fix link from Team Settings to RBAC roles

---

changes/pr5335.yml
src/prefect/cli/docker-compose.yml

Proper Apple Silicon support was added to `hasura/graphql` engine in [v2.1.0](https://github.com/hasura/graphql-engine/releases/tag/v2.1.0). This brings it into the Server.
Just the version of the `hasura/graphql` image in the server's composefile from 2.0.9 to 2.1.1
This should mean the prefect server can start up on M1 Macs without them needing [8GB of RAM](https://github.com/hasura/graphql-engine/issues/6337#issuecomment-969300069)!
This PR:
- ~~adds new tests (if appropriate)~~
- ~~updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)~~

Bump hasura image version to 2.1.1 to fix M1 support

---

changes/pr5362.yml
src/prefect/tasks/airbyte/airbyte.py

Airbyte task currently checks for the job status here:
https://github.com/PrefectHQ/prefect/blob/01705d38b9819a8e38d2696ee56999bc7a3faf89/src/prefect/tasks/airbyte/airbyte.py#L271
However, when the job status is failed, it only logs the error rather than raising an exception:
https://github.com/PrefectHQ/prefect/blob/01705d38b9819a8e38d2696ee56999bc7a3faf89/src/prefect/tasks/airbyte/airbyte.py#L280
Raising an exception to mark the task run as Failed.
Fixes a bug flagged by a community user in [this Slack thread](https://prefect-community.slack.com/archives/CL09KU1K7/p1643021910053100).
This PR:
- [] adds new tests (if appropriate)
- [] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)

Raise an error when Airbyte sync job fails to mark the task run as Failed

---

setup.py

Relaxes upper bound constraints on our extra requirements. These can unnecessarily limit installations.
Matches the changes to primary requirements in #5356
Opened #5359 and #5358 to fix constraints that are actually needed.
Opened #5360 to note some task library tests that are not running correctly.

Drop upper bounds from extra requirements 

---

changes/pr5355.yaml
src/prefect/cli/auth.py
tests/cli/test_auth.py

This fixes a bug where the cached tenant id could be loaded when a new key is used which would result in unauthorized errors if the new key was not compatible with the old tenant

Explicitly unset the tenant id during `prefect auth login`

---

changes/pr5316.yaml
src/prefect/utilities/logging.py
tests/utilities/test_logging.py

This builds on the work in https://github.com/PrefectHQ/prefect/pull/4902 and logging in Orion to adjust the calculations for logging payload limits.
Since we remove an item from the queue to place it in the batch, the pending limit could exceed the batch limit by the size of a single log. When batching logs, we enforce a limit as `MAX_BATCH_LOG_SIZE - MAX_LOG_SIZE` to ensure we never exceed the `MAX_BATCH_LOG_SIZE`. If `MAX_LOG_SIZE` is greater than `MAX_BATCH_LOG_SIZE`, we will batch with `MAX_LOG_SIZE` instead.
Here, we also use `sys.getsizeof(log)` to check sizes instead of `len(log.message)`. This accounts for the overhead of the additional log fields without special calculations. `sys.getsizeof(dict(...))` should always exceed `len(json.dumps(dict(...)))` due to the overhead of a …

Enforce logging limits by size instead of message length

---

changes/pr5390.yaml
src/prefect/backend/kv_store.py
src/prefect/engine/state.py
src/prefect/utilities/executors.py
src/prefect/utilities/logging.py
tests/utilities/test_logging.py

Closes https://github.com/PrefectHQ/prefect/issues/5389 by including defaults for usage of `sys.getsizeof` which will otherwise throw a `TypeError` when using PyPy.
Fixes a related issue where `sys.getsizeof` would underestimate the size of log messages. This was a regression introduced in #5316. This improves test coverage to address that case and introduces realistic log size calculations.

Fix usage of `sys.getsizeof`

---

changes/issue5358.yaml
setup.py
src/prefect/tasks/spacy/spacy_tasks.py
tests/tasks/spacy/test_spacy_tasks.py

This PR addresses https://github.com/PrefectHQ/prefect/issues/5358 by making `SpacyNLP` task compatible with spacy version >= 3.0
- The error was thrown by `spacy.load`. As per the [docs for spacy.load](https://spacy.io/api/top-level#spacy.load), the argument name is now `config`, making `component_cfg` invalid. Therefore, `config` is now used
- To maintain backward compatibility, both spacy <3 and >=3 are supported. 
- A new `exclude` param is added to `SpacyNLP` task
This will help remove the upper bound constraints on `spacy` in requirements
This PR:

SpacyNLP task v3 compatibility

---

tests/tasks/great_expectations/v2_api/checkpoints/.ge_store_backend_id
tests/tasks/great_expectations/v2_api/expectations/.ge_store_backend_id
tests/tasks/great_expectations/v2_api/great_expectations.yml
tests/tasks/great_expectations/v3_api/expectations/.ge_store_backend_id
tests/tasks/great_expectations/v3_api/great_expectations.yml

This removes usage stats information from the sample fixtures to prevent inaccurate records from being sent.
See above.
See above.
I don't believe any of these would be necessary for this PR.
This PR:

remove usage stats information

---

setup.py

There's a version conflict for the version of `azure-core` required by `azure-storage-blob` and `azureml-sdk`. Specifying a lower bound of the `azure-core` version should fix the intermittent failures that we've been seeing in the task library tests.
This PR:

Adds lower version pin for azure-core to fix intermittent pipeline failures

---

changes/pr5437.yaml
src/prefect/tasks/azure/blobstorage.py
tests/tasks/azure/test_blobstorage.py

Adds overwrite flag to BlobStorageUpload task as requested in #5235 
Adds an overwrite flag to the BlobStorageUpload task that will allow overwriting of existing blobs.
Closes #5235 
This PR:

Add overwrite flag to BlobStorageUpload task

---

changes/issue5451.yaml
src/prefect/tasks/aws/secrets_manager.py
tests/tasks/aws/test_secrets_manager.py

Fixes the AWS secrets manager to return non key-value secrets as strings instead of erroring out.
Adds a try clause to the AWS secrets manager to allow for parsing non key-value type secrets.
Solves issue #5451 
Currently the AWS secrets manager errors out on parsing a non key value pair secret value. 
I.e A secret storing just "token" would fail to parse. 
This PR fixes this issue.
This PR:

Fix AWS secret manager not parsing `plaintext` secrets.

---

changes/pr5472.yaml
src/prefect/core/flow.py
tests/core/test_flow.py

This feature request introduces a new orientation to plot graphviz graphs.
If you need to save or display this figure in a doc or any other page, you should have the option to plot it in two different orientations.
This PR adds a new argument into `visualize()` function to change the image orientation.
This can be important to give the option to users to plot using a different orientation instead of saving it to `.dot` and change it manually. It is good for notebooks also.
This PR:

Add the ability to plot graphs horizontally.

---

changes/pr_5476.yaml
src/prefect/cli/docker-compose.yml

- Run hasura container with `init`
- Run the `hasura` service with `init: true` flag in compose file
- Change compose file version to 3.7 to use the `init` flag (not available in lower versions)
Reaps the zombie processes generated by the hasura service : solves https://github.com/PrefectHQ/server/issues/335 (I might be wrong but I think this should be done in this repo although the issue is in the server repo)

Run hasura service with init

---

src/prefect/tasks/prefect/flow_run.py

API documentation regarding StartFlowRun parameter `project_name` did not match what the code does.
Removes any mention of difference between Cloud & Core Server in the documentation of the `project_name` parameter of StartFlowRun (init & run).
Doc should match what the code does.
This PR:

fix StartFlowRun doc

---

tests/executors/test_executors.py

This test fails intermittently on Windows

Add flaky test mark to `test_executor_logs_worker_events`

---

changes/pr5490.yaml
entrypoint.sh

When starting the container, it shows a welcome message with a broken URL https://docs.prefect.io/core/getting_started/installation.html#docker:
This PR fixes the URL

Fix the broken URL in the entrypoint.sh

---

changes/pr_5499.yaml
src/prefect/tasks/files/operations.py
tests/tasks/files/test_operations.py

Fixes bug in `Glob` task where string paths are not handled correctly. Work originally performed in #5264 by @pgierz. Builds upon the original work by adding test coverage.
This PR:

Fixes `Glob` task to correctly accept a `str` for `path`

---

docs/orchestration/concepts/artifacts.md

Removes beta tag from the [Artifacts](https://deploy-preview-5506--prefect-docs.netlify.app/orchestration/concepts/artifacts.html) concept doc page.
Closes #5482
- /orchestration/concepts/artifacts.html
No longer beta with 1.0 release.
This PR:

Docs: Remove beta tag from Artifacts

---

src/prefect/engine/task_runner.py
tests/core/test_task.py

Fix a task failure when `self` is used as a task argument
`self` is popped from the formatting dictionary used to populate result strings. This should not be included because it means that we get `result.exists(self="foo", self="bar")`, which is an error.
Currently there is a crash whenever any method is used directly as a function. For example, in the below code note how the task's function *is* `Path.is_absolute` which is a method that we are using like a function, and which therefore needs a `self` argument:
```python
from pathlib import Path
seconds_task = task(Path.is_absolute, target="{{task_slug}}_{{map_index}}", result=LocalResult())
initial = Path("foo")
with Flow("test") as flow:
seconds_task(initial)
flow.run()
```
This PR:

Add workaround for self kwarg

---

changes/pr5514.yaml
src/prefect/tasks/kubernetes/job.py

This PR addresses the issue where pod logs aren't getting property
logged in RunNamespacedJob.
Because Context is thread-local, it isn't set properly in the threads
spawned by a ThreadPoolExecutor, and therefore the logs aren't sent
by the CloudHandler. Fix this by adding a thread initializer which
updates the thread's Context with a copy of the main thread's Context.
Without this fix, no output from pods is captured.
This PR:

fix pod logging in RunNamespacedJob

---

docs/core/concepts/schedules.md

Spacing in these examples looks a little weird in the docs: https://docs.prefect.io/core/concepts/schedules.html#clocks

Fix spacing in examples

---

changes/pr5443.yaml
src/prefect/tasks/prefect/flow_run.py
tests/tasks/prefect/test_flow_run.py

Task in local `flow.run` calls do not have unique task run ids when mapped. Since `create_flow_run` uses the `task_run_id` as the default idempotency key, mapped calls in local runs will only result in a single flow run. To resolve this, we can include the `map_index` in the default idempotency key.
Note that when running with a backend, each task run (mapped or not) has a distinct UUID.
Appends the `map_index` to the default idempotency key if present in the context.
Extends test coverage for local runs, run names, and idempotency keys.
Mapping with `create_flow_run` in `flow.run()` does not work as intended otherwise.
This PR:

Include the `map_index` in the default `create_flow_run` idempotency key 

---

docs/api/0.15.13/run_configs.md
src/prefect/run_configs/kubernetes.py

Adding a little documentation from a Slack Conversation.
I need to add a Kubernetes label to the Pod, so adding that as an example.
- Updates API docs for 0.15.13 to include an example of specifying a custom `job_template` as a `dict`.
I had a question in Slack that I thought would be in docs
This PR:

Update docs for custom Kubernetes Container JobSpec

---

docs/core/concepts/tasks.md

Renamed runtime to when you create them so that meaning is more clear
Renamed to something more friendly which user can understand
Docs
This PR:

Changed task.md

---

changes/pr4356.yaml
src/prefect/agent/ecs/agent.py
tests/agent/test_ecs_agent.py

PR to add the ability to  use capacity providers in ECS Agent and ECSRun when set in run_task_kwargs 
- Updates the way ECSAgent set's the launchType and default network configuration when a capacity provider is passed in via run-task-kwargs. 
- Deletes launchType in ECSAgent run_config (opts) in merge_run_task_kwargs if capacityProvider is found in ECSRun's run_config (opts2) and vice versa
Being able to use capacity providers in ECS enables the use of Fargate Spot and ASG's. 
Found in Issues:
#4356 and #5210 
This PR:

Adds ability to use ECS Capacity Provider in ECS Agent and ECS Run

---

src/prefect/context.py

Fixing a single quote in the documentation because it somehow annoyed me more than it should.
A single quote for the documentation of tags.
It kinda isn't. Just... cleaning up.
This PR:

single quote doc fix

---

changes/pr5554.yaml
src/prefect/backend/flow_run.py
tests/backend/test_flow_run.py

There is a slight timeframe in which an initialized flow run does not have a serialized state. During this time a backend FlowRunView object cannot be initiated.
With this change, `FlowRunView` instances can be initialized when `serialized_state` value is None. A default state of `Pending` is used to fill the null value instead, with a short message describing that the flow run state is not yet initialized.
`wait_for_flow_run` task could fail, even though child flow executes correctly. See issue #5552 
This PR:

Use pending state when flow run state is missing

---

src/prefect/agent/kubernetes/agent.py
tests/agent/test_k8s_agent.py

Currently this warning message errors out:
```
File "/usr/local/lib/python3.7/site-packages/prefect/agent/kubernetes/agent.py", line 413, in heartbeat
[2022-03-18 18:46:14,083] ERROR - agent | Error while managing existing k8s jobs
File "/usr/local/lib/python3.7/site-packages/prefect/agent/kubernetes/agent.py", line 190, in manage_jobs
flow_run_state = self.client.get_flow_run_state(flow_run_id)
File "/usr/local/lib/python3.7/site-packages/prefect/client/client.py", line 1340, in get_flow_run_state
raise ObjectNotFoundError(f"Flow run {flow_run_id!r} not found.")
prefect.exceptions.ObjectNotFoundError: Flow run 'ef8eeec4-4a0d-482a-8821-669be7bdc1a4' not found.
During handling of the above exception, another exception …
```

Fix warning for non-existent job in kubernetes agent

---

docs/concepts/tasks.md

This is a simple fix in the documentation. Replaced an underscore with a dash to show users the proper command.
In the docs concurrency_limit -> concurrency-limit
Helps new users avoid speedbumps when trying out orion. It also fixes this issue https://github.com/PrefectHQ/prefect/issues/5583
This PR:
This PR does none of these.

Changed doc for command concurrency_limit -> concurrency-limit

---

src/prefect/executors/dask.py
tests/executors/test_executors.py
tests/tasks/prefect/test_flow_run.py

Adds sleep before running Dask cluster scale in test to allow Dask event listener to start up.

Fix Dask CI failures

---

changes/pr5588.yaml
src/prefect/core/flow.py
tests/core/test_flow.py
tests/core/test_task.py
tests/engine/test_task_runner.py

Implements #5556 -> Raise informative error when `flow.run()` is called within a flow context.
Found a check in `flow.register()` that uses `hasattr` instead of `'flow' in prefect.context`. Opted to use that for consistency. 
This PR:

Raise error if flow.run called within Flow ctx

---

.github/ISSUE_TEMPLATE/3. orion.md

To reflect that Orion is no longer in technical preview but instead in a beta stage.
Not sure if the title prefix should stay "Orion: " - there may be some automations that rely on it

Change the issue type to Prefect 2.0

---

docs/core/idioms/script-based.md
docs/orchestration/execution/storage_options.md
docs/orchestration/flow_config/storage.md

Revise storage documentation to correctly indicate that git-based storage is read only.
Closes [#5589](https://github.com/PrefectHQ/prefect/issues/5589)
- Flow configuration > [Storage](https://deploy-preview-5616--prefect-docs.netlify.app/orchestration/flow_config/storage.html)
- Prefect Idioms > [Using script based flow storage](https://deploy-preview-5616--prefect-docs.netlify.app/core/idioms/script-based.html)
- Legacy Environments > [Storage](https://deploy-preview-5616--prefect-docs.netlify.app/orchestration/execution/storage_options.html)
Fixes incorrect statement that git-based storage supports both uploading and retrieving flow definitions.
Fixes minor language and formatting issues.
This PR:
~~- [ ] adds a change file in the `changes/` …

Docs: revisions to git-based storage descriptions

---

changes/pr5631.yaml
src/prefect/executors/dask.py
tests/executors/test_executors.py

Adds a `watch_worker_events` toggle to the `DaskExecutor`. When disabled, we will not subscribe to the Dask worker events which are normally logged when workers are added or removed from the connected cluster.
This toggle is disabled by default when `adapt_kwargs` is used to resolve issues where Dask clusters fail to scale correctly as only a single subcriber is allowed at once and Prefect replaces the clusters handler. Otherwise, it is enabled by default for backwards compatibility. Users may override the default behavior by setting `True` or `False` explicitly. 
Closes #5549.

Add `watch_worker_events` toggle to `DaskExecutor`

---

changes/pr5674.yml
src/prefect/core/task.py
tests/engine/test_task_runner.py

Add pipe support for EdgeAnnotation.
Handle `EdgeAnnotation` in `pipe` to return `Task` instead of `EdgeAnnotation` for subsequent chaining.
Fixes #5665
This PR:

Add pipe support for EdgeAnnotation.

---

changes/pr5662.yaml
src/prefect/core/flow.py
tests/core/test_flow.py

See: https://github.com/PrefectHQ/prefect/issues/5656
In short, this PR fixes an issue where a mapped lambda, e.g. `task(lambda x: x + 1).map([1, 2, 3])`, causes `graphviz.Digraph.render` (called by `Flow.visualize`) to generate DOT syntax with the label unquoted, e.g. `[label=<lambda> <map>]`, because it assumes that a string enclosed in angle brackets should contain valid HTML; and the resulting syntax is incorrect, so the `dot` command correctly rejects it, leading to an error.
Quick way to check whether the changes in PR fix the issue or not:
```python
with Flow('test') as flow:
xs = task(lambda x: x + 1).map([1, 2, 3])
flow.visualize()
```
...after this PR, that does not result in an error.
In Flow.visualize, we now wrap node labels with …

Fix flow visualization when tasks are mapped lambdas (#5656)

---

src/prefect/flow_runners.py
tests/test_flow_runners.py

Hey :wave:, this PR is related to #5578, and adds the ability in Prefect 2.0 to specify a service account when creating a KubernetesFlowRunner. I'm currently running this fork of 2.0b3 on our EKS cluster and it's the last thing that was needed to start with Prefect 2.0 as our orchestrator. Feel free to close/change, just putting it in the universe.
- adds a `service_account` attribute to `KubernetesFlowRunner`, with updated docstrings
- adds a test that it creates the correct Kubernetes job spec when specifying a service account
- while I was at it, added a test for the namespace argument, so should be a net positive in coverage
In many/most production Kubernetes clusters, service accounts are useful in granting access to out-of-cluster resources like databases, storage, secrets, etc. …

Adding service_account option to KuberentesFlowRunner

---

docs/tutorials/testing.md

Autouse fixtures don't need to be imported
Slight simplification of the pytest example in the testing section
Not terribly important, but may give best practices for folks who don't know `pytest` too well
This PR:

Docs: Simplify pytest example

---

.github/workflows/test_windows.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

changes/pr0000.yaml
src/prefect/tasks/databricks/models.py

Added an additional missing Parameter from the Databricks API for `policy_id`
Adjusted the `autoscale` parameter to accept none/optional since it's an optional value in Databricks API
[https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsCreate](https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsCreate)
adding a policy id is critical to Databricks tasks and making autoscale not required is the right thing to do
This PR:

add policy_id to NewCluster; autoscale is optional

---

changes/pr5716.yaml
src/prefect/cli/run.py
tests/cli/test_run.py

Fix error that arises when a (legitimate) equals sign is in a parameter value
How keys and values are parsed in a CLI parameter
In our use-case, we use [SMILES](https://en.wikipedia.org/wiki/Simplified_molecular-input_line-entry_system) strings 
to represent molecules. In this specification, an equals sign can represent a certain kind of bond. 
As is, passing a value with an equals sign causes an error
```
Invalid parameter option 'r-group-pattern='C=C'. Expected format 'key=value'.
```
This represents a huge problem for us and there is no easy obvious workaround.
This fixes that by only splitting on the first instance of an equals sign, where the parameter key and value are split.
I've checked that this works as expected included a test 
This PR:

Fix error when = is present in parameter value

---

changes/pr5705.yml
src/prefect/utilities/filesystems.py
tests/utilities/test_filesystems.py

Currently, doing something like:
```
prefect kubernetes agent start --job-template gs://blah/template.yml
```
as seen [here](https://docs.prefect.io/orchestration/agents/kubernetes.html#custom-job-template) will result in:
```
Unsupported file scheme gs://blah/template.yml
```
This is because our `if` condition looks for `gcs` as the scheme instead of `gs`. However, the convention is actually `gs`.
It adds support for both `gs` and `gcs` and adds a corresponding test.
There is no intuitive error if somebody uses the `gs` convention for Google Cloud Storage paths as opposed to `gcs`.
This PR:

Adding fs handling for gs scheme

---

changes/issue5076.yaml
src/prefect/tasks/dbt/dbt_cloud_utils.py

This fixes an issue where calling DbtCloudRunJob with nested inputs for the optional parameter `additional_args`, the DBT API returns a 400 response "Bad Request".
See [#5706](https://github.com/PrefectHQ/prefect/issues/5706) for more details.
This fixes the way that `additional_args` are passed to the [DBT Trigger Job Run API](https://docs.getdbt.com/dbt-cloud/api-v2#operation/triggerRun), using `json=` instead of `data=` to correct pass nested parameters.
This fix allows for calling the DbtCloudRunJob task with the `steps_override` nested argument (Array of string type) in `additional_args`.  
This PR:

Fix DbtCloudRunJob task failing with nested input for additional_args

---

docs/index.md

So far, there is no single mention of Orion on the main docs page. Therefore, new users, who are just getting started with Prefect, may not even find out about Prefect 2.0.
This PR adds info about Prefect 1.0, Prefect 2.0, and Cloud 2.0 including links to the relevant blog posts, Cloud 2.0 signup page, and Orion documentation.

Mention Prefect 2.0 on the main documentation page

---

src/prefect/client/client.py

Sometimes, the backend returns task run information before the
state has been populated in the database. This results in a null
state payload which throws an exception on deserialization.
Generally, it is safe to treat these null states as `Pending`.

Add handling for null states to `get_task_run_info`

---

changes/pr5748.yaml
src/prefect/agent/docker/agent.py
src/prefect/executors/dask.py
tests/agent/test_docker_agent.py

This brings our behavior in-line with the Docker CLI which will
change the network mode on created containers to 'host' or 'none'
respectively if the special network names 'host' or 'none' are used.
These networks appear to be immutably defined by Docker.
'host' networking is still not expected to work on non-Linux systems,
see the Docker documentation for more information.
Closes https://github.com/PrefectHQ/prefect/issues/4840
Closes https://github.com/PrefectHQ/prefect/issues/2638

Add inference of Docker network mode for 'host' and 'none' networks

---

docs/contributing/overview.md

Change directory into prefect repository to allow copy paste install for contributing.
Previously, developers were unable to copy all commands and run, due to missing change directory.
Contribution documentation
When reading the wiki, developers will likely copy paste all commands to have a simplified paste and install process. Currently, this does not work as the install checkout and subsequent commands are not in the prefect repo
This PR:
- [x ] adds a change file in the `changes/` directory (if appropriate)

Change Directory into Prefect to Streamline Copy Paste

---

src/prefect/cli/templates/kubernetes-dev.yaml

When creating a kubernetes manifest, the previous template did not include the no-ui option. This resulted
in the container crashing on load, as it does not have npm, which gets run as part of the UI standup process.
To overcome this, we launch orion without the UI in kube dev
Fixes kubernetes dev manifest to not launch UI
Containers will fail on start
https://github.com/PrefectHQ/prefect/issues/5751
This PR:
- [x ] adds a change file in the `changes/` directory (if appropriate)

Add No Ui Flag to Kubernetes Dev

---

changes/pr5727.yaml
changes/pr5728.yaml
src/prefect/tasks/databricks/databricks_submitjob.py

Use `BaseModel.json()` instead of `BaseModel.dict()` in order to appropriately convert `List[AccessControlRequest]` to JSON.
The `AccessControlRequest` model uses a `__root__` attribute, which does not lend itself well to using `BaseModel.dict()` when converting to JSON. We need to use `BaseModel.json()`.
Example with `dict()`:
```
{'__root__': {'user_name': 'test@email.com',
'permission_level': <CanManage.CAN_MANAGE: 'CAN_MANAGE'>}}
```
Example with `json()`: 
```
'{"user_name": "test@email.com", "permission_level": "CAN_MANAGE"}'
```
`access_control_list` is not passed correctly to Databricks for the `DatabricksSubmitMultitaskRun` API unless this is fixed.
This PR:

use json() instead of dict()

---

changes/pr5724.yaml
src/prefect/tasks/great_expectations/checkpoints.py
tests/tasks/great_expectations/.gitignore
tests/tasks/great_expectations/test_great_expectations_validation.py

Addresses defect documented in #5570.
Replaces a `RunIdentifier` supplied as a `dict` with the actual class, which serializes correctly. Unfortunately, `great-expectations` does not make it easy on anyone trying to leverage their API, as many key classes serialize to *look* like instances of `dict`, e.g.:
```python
>>> from great_expectations.core import RunIdentifier
>>> run_identifier = RunIdentifier("foo")
>>> str(run_identifier)
'{\n  "run_time": "2022-04-27T23:09:25.216846+00:00",\n  "run_name": "foo"\n}'
```
Serialization is currently broken for both `LocalResult` and `S3Result` (that I've tested). This means the following functionality *does not work*:
* Running `prefect[ge]` in the `LocalAgent`, since `LocalResult` is implied in that context, and there is no (obvious) way to …

Fix defect in serialization of GE results in LocalResult

---

.circleci/config.yml
.github/workflows/test_windows.yml
changes/pr5770.yaml
dev-requirements.txt
docs/core/development/tests.md
docs/orchestration/flow_config/docker.md
setup.py

This PR adds support for Python 3.10
I had a look at those Python 3.9 PRs:
https://github.com/PrefectHQ/prefect/pull/3441
https://github.com/PrefectHQ/prefect/pull/4896
Changes setup.py and CI to inlcude Python 3.10
Python 3.10 is the latest stable version of Python so it would be great to include it :)
This PR:

Add Python 3.10 support

---

changes/pr5785.yaml
src/prefect/serialization/flow.py
tests/serialization/test_flows.py

As the parameter is used repeatedly multiple times the upstream and downstream slug can be same. Add `key` which can be used as additional field for sorting to ensure deterministic order for serialized output and also during register.
Add `edge.key` as additional parameter for sorting. Use empty string when `None` so that `TypeError` is not raised.
Closes https://github.com/PrefectHQ/prefect/issues/5776
The below test command for 100 runs will fail on randomly without patch.
```
pytest --count=100 -s -x tests/serialization/test_flows.py -k test_serialize_flow_sorts_by_key
```
This PR:

Sort by key when upstream and downstream slug are same for deterministic order.

---

changes/pr5795.yaml
src/prefect/tasks/prefect/flow_run.py

Artifact creation is not always necessary and may cause issues when used with mapped tasks.
Adds a bool flag
Discussion on [Slack](https://linen.prefect.io/t/419667/We-are-seeing-errors-when-trying-to-register-artifacts-in-ou)
This PR:

Make artifacts optional in `StartFlowRun`

---

changes/pr5778.yaml
src/prefect/tasks/databricks/models.py

Adds an optional arg `data_security_mode` to Databricks cluster configuration.
I am creating a Databricks cluster policy via Terraform and specifying a default `data_security_mode` in there ([docs](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster)), from which I get a `policy_id` arg that I am supplying to the Databricks API. However, I want the option to be able to override that from the Prefect/Databricks API. This PR will allow for that.
Without this PR, I cannot override `data_security_mode` on a per-user basis.
This PR:

add data_security_mode

---

docs/api/0.14.22/cli/agent.md
docs/api/0.15.13/cli/agent.md
src/prefect/cli/agent.py

https://docs.prefect.io/api/latest/cli/agent.html#kubernetes
https://docs.prefect.io/api/latest/cli/agent.html#kubernetes-install
In the above mentioned links the documentation fix was supposed to be 
To change 
`Generate a supervisord.conf file for a Local agent`  to `Generate a deployment.yml file for a Kubernetes Agent`
This documentation fix will now show correct instructions under kubernetes cli install options

Modified changes under Kubernetes CLI options docs

---

changes/pr5797.yaml
src/prefect/cli/server.py

Add flag `--hide-welcome` to avoid printing the ascii welcome message
It should close #5619 
Add the possibility to prevent ASCII welcome message
Minor importance
This PR:

feat: add flag to hide welcome message

---

docs/core/advanced_tutorials/slack-notifications.md

Adds a deprecation notice for the [Slack Notifications tutorial](https://deploy-preview-5786--prefect-docs.netlify.app/core/advanced_tutorials/slack-notifications.html), which is out of date and also slightly dodgy with the "secret URL" business.
Rather than removing the tutorial entirely, added a deprecation notice at the top of the page with links to more current solutions.
Deprecation notice gives us a chance to redirect users who may have bookmarked this page, be following from a third party link, or find via search. If there's a true issue with removing, this gives users a chance to create an issue or raise a concern.
Better experience for users who want to use Slack notifications.
This PR:
~~- [ ] adds a change file in the `changes/` …

Docs: deprecation notice for Slack webhook tutorial

---

changes/pr5789.yaml
src/prefect/core/task.py
tests/core/test_flow.py

Validate positional-only arguments in task signature before bind to raise `TypeError` instead of exception during task run
Provide better error message to positional only arguments
Closes https://github.com/PrefectHQ/prefect/issues/5522 with better error message
This PR:

Validate positional-only arguments in task signature.

---

src/prefect/orion/api/server.py

Windows defaults to the mimetype text/plain for .js files, leading to the Orion UI loading a blank page, with the following in the JavaScript console:
"Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec."
This can be mitigated by changing the mimetype in the Windows registry, but that seems a bit invasive for such a minor fix.
This PR overrides the mime type for .js files if os.name == "nt", allowing the UI to load.
While it's still not possible to develop the UI on Windows (all the commands in dev that run `subprocess.check_output(['npm', ...])` fail due to not checking the path by default), this at least allows the final product to run on a …

Allow Orion UI to run on Windows

---

changes/pr5824.yaml
changes/pr5825.yaml
src/prefect/client/client.py
tests/client/test_client.py

This PR allows the prefect client to retry for HTTP targets. The reasoning leading up to this change can be found on https://github.com/PrefectHQ/prefect/pull/5600
This change mounts the HTTPAdapter containing retry to logic to HTTP prefixes alongside HTTPS prefixes. Session mounts are keyed by prefix, this change did not cause any ill-effects in testing.
Communications taking place internal to a cluster or in other configurations that use HTTP by default do not get the retry logic that applies to all Prefect Client communications. This includes state updates. For example, if a single state update is missed in Kubernetes executions, the entire flow fails. This PR corrects that by applying the retry logic to all HTTP communication.
This PR:

Allow prefect client to retry for HTTP targets

---

Dockerfile

Required to build grpcio on Python 3.10 slim which failed during the release of 1.2.2.
We'll need to publish the 1.2.2 image for 3.10 manually.

Add libffi-dev to the Dockerfile

---

changes/issue5860.yaml
src/prefect/storage/docker.py
tests/storage/test_docker_storage.py

Docker storage currently produces a pip install statement simply listing the dependencies as entered. For more complex dependency definitions, such as those with square brackets and various version constraints, the Docker build fails. This fixes the issue.
Addresses #5860 
This PR just quotes the Python dependencies in the resulting Dockerfile's `RUN` directive.
Users can't automatically build Docker storage for flows that use complex Python dependency definitions.
This PR:

Fix Docker builds for complex Python dependencies

---

src/prefect/tasks/airbyte/airbyte.py

As Airbyte does not always return a "schedule" key, this PR implements a soft-fail when the key is not present. As you can see, the fix is pretty simple.
This fixes the following stacktrace I've been having:
```
File "/usr/local/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
value = prefect.utilities.executors.run_task_with_timeout(
File "/usr/local/lib/python3.8/site-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
return task.run(*args, **kwargs)  # type: ignore
File "/usr/local/lib/python3.8/site-packages/prefect/utilities/tasks.py", line 456, in method
return run_method(self, *args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/prefect/tasks/airbyte/airbyte.py", line …
```

Airbyte does not return a 'schedule' key anymore for 'no schedule'

---

src/prefect/tasks/snowflake/__init__.py

Importing SnowflakeQuery fails when Prefect was not installed with the "snowflake" extra but with wrong exception.
Fix missing 'as err' so the right exceptions is raised instead of python's syntax exception
This PR:

fix raising error in __init__.py for snowflake task

---

changes/PR5957.yaml
src/prefect/schedules/clocks.py
tests/schedules/test_clocks.py

We thought we had identified all the weird DST issues with croniter, but a user recently stumbled across a new one. A simplified demo:
```python
import pendulum
from croniter import croniter
from datetime import datetime
cron = croniter('0 0 * * 0', pendulum.datetime(2022, 8, 21, tz='America/Santiago'))
for i in range(10):
print(cron.next(datetime))
```
Which results in
```
2022-08-28 00:00:00-04:00
2022-09-03 23:00:00-04:00
2022-09-03 23:00:00-04:00
2022-09-03 23:00:00-04:00
2022-09-03 23:00:00-04:00
2022-09-03 23:00:00-04:00
2022-09-03 23:00:00-04:00
2022-09-03 23:00:00-04:00
2022-09-03 23:00:00-04:00
2022-09-03 23:00:00-04:00
```
To avoid this (and others potentially lurking), this adds a check to see if we're stuck in a date loop when evaluating cron. If so, we exit the loop by …

Avoid croniter infinite loop

---

changes/pr5948.yaml
changes/pr5949.yaml
src/prefect/tasks/databricks/models.py
tests/tasks/databricks/test_databricks.py

Allows for extra arguments to the `NewCluster` model in the Databricks task library.
Fourth time's the charm! Replaces #5930, #5943, and #5948.
The PR allows extra arguments in `NewCluster` to pass through pydantic validation. Notably, only the `NewCluster` model is affected and only entirely new fields are allowed. The change does not apply to any parent or child models.
This change will allow users to supply newly introduced Databricks cluster arguments without needing to wait for a Prefect release that includes them. The change was suggested by @desertaxle in #5903.
This PR:

Allow extra arguments to Databricks NewCluster

---

changes/pr5903.yaml
src/prefect/tasks/databricks/models.py

Related to data_security_mode (added https://github.com/PrefectHQ/prefect/pull/5778), single_user_name is an arg supported in newer versions of the Cluster API https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster.
Adds an optional key to Databricks NewCluster.
When creating Databricks cluster with security_mode=SINGLE_USER, the single_user_name must be supplied.
This PR:

Add single_user_name to Databricks NewCluster

---

src/prefect/serialization/storage.py

Follow-up to https://github.com/PrefectHQ/prefect/pull/5033 updating the marshmallow `GitSchema` schema to match the changes to the `Git` storage object.
Closes #4882

Allow the repo to be null in serialized `Git` storage schema

---

src/prefect/client/client.py
src/prefect/config.toml

When a 429 rate limit response is encountered, the client retries+backs off repeatedly until the response succeeds or some maximum number of failures is reached. The original configuration from #4852 starts out by sleeping for between [180, 190] seconds, then [180, 200], etc, up to [180, 820].
For a typical (for us 🙂) case where a 429 occurs because of a high volume of task runs all starting at once, retrying every single task in 3 minutes is not a very good idea, as it almost guarantees that the exact same rate limit will be hit again, and probably again and again until the window gets wide enough to spread out the requests over several minutes at which point they will hopefully succeed.
Adds a `config.cloud.rate_limiting` variable where the default parameters can be overridden, to allow …

Make 429 rate limit backoff configurable

---

src/prefect/tasks/dbt/dbt.py

When creating a DbtShellTask with `return_all=True` the return type of `run` is `List[str]` but this is not reflected in the return type.
This PR updates the return type to match the [return type of `run`](https://github.com/PrefectHQ/prefect/blob/de5bdcf/src/prefect/tasks/shell.py#L93) in the super class (ShellTask).
Signed-off-by: Oliver Mannion <125105+tekumara@users.noreply.github.com>

fix: match DbtShellTask.run return type to ShellTask.run

---

changes/issue5907.yaml
src/prefect/tasks/aws/s3.py

Currently only `S3Upload` and `S3Download` support the `boto_kwargs` parameter. This PR adds support for `S3List`.
Allows to provide boto keyword arguments to the initializer of `S3List`. 
The `boto_kwargs` parameter should be provided for all S3 classes to allow e.g. changing of the `endpoint_url`.
This PR:

add boto_kwargs to S3List

---

src/prefect/engine/results/s3_result.py

When pickling an `S3Result` with an old version of Prefect and unpickling with a new version, the new attribute will be missing.
See https://prefect-community.slack.com/archives/CL09KU1K7/p1657211370977639

Fix pickle errors when using mismatched versions of Prefect and S3Result

---

changes/pr5979.yaml
src/prefect/tasks/kubernetes/pod.py
tests/tasks/kubernetes/test_pod.py

Adds container parameter to ReadNamespacedPodLogs
Without this parameter we can't target a specific container within the pod, for example an initContainer.
Because I can't target an `initContainer` logs without this.
This PR:

Adds container parameter to ReadNamespacedPodLogs

---

docs/tutorials/deployments.md
src/prefect/cli/deployment.py

`prefect deployment execute` is a convenience command used to try and run deployments without an active agent. This command is now very sensitive to the base directory from which which it's called, which only causes confusion and I think we should remove it.

Remove deployment execute

---

src/prefect/orion/utilities/database.py
tests/orion/utilities/test_database.py

PostgreSQL [explicitly does not support these values](https://www.postgresql.org/docs/current/datatype-json.html#JSON-TYPE-MAPPING-TABLE), and while SQLite supports saving and reading full JSON documents containing these values, any attempt to parse them in SQLite (like to use them with JSON operators) will fail.
This change follows the Javascript convention, which is to coerce these values to `null`, which should have good standards compatibility with the frontend and other non-Python clients.  The JSON spec does not comment on what to do with these values, but [MDN says they are prohibited](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON#numbers).
This was observed in our Prefect Cloud 2.0 environment: https://github.com/PrefectHQ/nebula/issues/1157 …

Coerce any floating point extrema (`NaN`, `-Infinity`, `Infinity`) in JSON objects to `None` for the DB

---

docs/index.md

To expand on why Prefect is air traffic control for the modern data stack

Add hyperlink on air traffic control in index.md

---

.gitignore
src/prefect/cli/deployment.py
src/prefect/deployments.py

This PR ensures that schedules set via API / UI on a deployment are preserved when building deployments from the CLI.  This behavior mirrors the current behavior with deployment `description`.

Preserve schedules set via the API in building deployments

---

docs/orchestration/flow_config/docker.md

Updates docker tags for release of Prefect 2
- Updates the tag listing for Prefect 1 in docker.md to denote that it's for 1.x
- Adds the docker tags for Prefect 2.
This PR:

Add Prefect 2 tags to docker.md

---

netlify.toml

Provide a redirect to migration guide. There are some incorrect URLs floating around.

Docs: Redirect for migration guide

---

docs/tutorials/deployments.md
docs/ui/cloud-getting-started.md

Fixes some formatting (missing div) in deployments tutorial.
Clarifies API URL use in Cloud quickstart.

Docs: Minor fixes for deployment and cloud tutorials

---

src/prefect/orion/services/flow_run_notifications.py
src/prefect/orion/services/scheduler.py

The comments in the code tell the story in detail, but because this loop-service
handles Exceptions internally, it may sometimes handle transient DB errors that
require a rollback before proceeding with more work.
Part of PrefectHQ/nebula#1220

Head off possible `PendingRollbackError`s from the `scheduler` and `flow-run-notifications` `LoopService`s.

---

docs/api-ref/prefect/utilities/annotations.md
mkdocs.yml
src/prefect/__init__.py
src/prefect/engine.py
src/prefect/utilities/annotations.py
tests/test_tasks.py
tests/utilities/test_annotations.py

In Issue #6106 it was called out that we didn't have an equivelant for `unmapped` from prefect 1. This adds support for `unmapped` to `Task.map` as it exists in Prefect 1.

Add support for unmapped values to Task.map

---

docs/concepts/deployments.md
docs/tutorials/deployments.md
src/prefect/cli/deployment.py

A common request we immediately received was for unique deployment YAML names (to better anticipate multi-flow deployments) and an optional output flag to customize the name. 
The students at PACC in San Jose all universally requested this today so it would be cool to have them get such a tight turnaround on their feedback (if possible / reasonable)!

Introduce output flag on deployment build and update default yaml name

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_enhancement.yaml
.github/pull_request_template.md

This pull request creates new templates for PRs and Issues. It is **heavily** inspired by the SQLAlchemy templates. I'll be working with @anna-geller to figure out wording and links on the bug report text.
I'm not certain if there's a way to preview the YAML results beforehand, so any input there would be helpful. I also don't know which tags we want to add as defaults to our issues. 
Seeking feedback on whether anything feels too verbose, hostile, or like we're asking too much. 
[Previous 1.x Pull Request Template](https://github.com/PrefectHQ/prefect/blob/1.x/.github/PULL_REQUEST_TEMPLATE.md)
[Previous 1.x Bug Report Template](https://github.com/PrefectHQ/prefect/blob/1.x/.github/ISSUE_TEMPLATE/1.%20bug_report.md)
[Previous 1.x Feature Enhancement …

Add PR, Issue, and New Feature templates

---

src/prefect/infrastructure/kubernetes.py
src/prefect/utilities/pydantic.py
tests/utilities/test_pydantic.py

In issue #6079 we found that the `customizations` OpenAPI schema was being output as `string` and this caused the UI to display the field as a simple text input.
This PR changes the schema to be an `array` with `object` children. This makes sense because JSON Patch is an array of JSON objects. This also sets the `format` to `rfc6902` so that further validation can be performed per the RFC spec. The schema for JSON Patch is now:
```
"customizations": {
"title": "Customizations",
"type": "array",
"format": "rfc6902",
"items": {
"type": "object",
"additionalProperties": {
"type": "string"
}
}
}
```

Set `format` of JsonPatch schema to `rfc6902`

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_enhancement.yaml

This PR 
1. Makes the `error` field optional for bug reports, because there are many situations where a bug may occur without an error output. 
2. Adds a required Prefect Version dropdown menu, with `1.x` and `2.x` as options, to the Enhancements template. This should help improve triage while limiting submitter overhead. 
I manually checked the Previews provided by github when clicking on each of the files. QA testers can see the same preview by going to each of the template files on the github website. 
- Please include tests. One-line fixes without tests will not be …

Update templates to make error optional and add a version field for enhancements

---

src/prefect/context.py
src/prefect/orion/api/deployments.py
src/prefect/orion/api/flow_runs.py
src/prefect/orion/api/run_history.py
src/prefect/orion/api/task_runs.py
src/prefect/orion/api/ui/flow_runs.py
src/prefect/orion/api/work_queues.py
src/prefect/orion/schemas/core.py
src/prefect/orion/schemas/filters.py
src/prefect/orion/schemas/responses.py
src/prefect/orion/schemas/schedules.py
src/prefect/orion/schemas/states.py
src/prefect/orion/utilities/schemas.py
tests/orion/utilities/test_schemas.py

This PR introduces a new Pydantic-validated type `DateTimeTZ` that always converts its input to a Pendulum timezone-aware datetime. 
This is a drop-in replacement for anywhere we currently type inputs as `datetime.datetime` or `pendulum.DateTime`, following up from https://github.com/PrefectHQ/orion/pull/2469, in which care was taken to ensure that models were serialized with tz-aware datetimes. 
Note that it actually **doesn't** work to type a field as `pendulum.DateTime`; pydantic will not coerce native or timezone-naive datetimes to Pendulum types. This new type achieves this with a custom pydantic validator, which means that all API-facing inputs will be guaranteed to be timezone-aware. The class is defined [here](https://github.com/PrefectHQ/prefect/pull/6142/files#diff-95fcbac7a05664 …

Add type that enforces timezone-aware datetimes

---

src/prefect/infrastructure/__init__.py

Adds the `__all__` attribute to `infrastructure/__init__.py` to denote which modules are public. Fixes issue #6144 
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the feature that …

Add list of public modules to infrastructure/__init__.py

---

src/prefect/cli/agent.py
src/prefect/utilities/collections.py
src/prefect/utilities/services.py
tests/utilities/test_services.py

This takes the approach of remembering the recent track record for a service,
so that momentary blips won't cause it to exit prematurely, but an ongoing
series of problems that might indicate a deeper issue (network, server, or cloud
outage) will.
Big thanks to @anticorrelator for help with the statistical underpinning here, it turned out very simple.  Math is real!
(none yet, this is a draft)
- Please reference the related issue by including "closes …

Makes the agent's inner loop more robust in the face of environmental failures

---

.github/labeler.yml
.github/workflows/labeler.yml

Followup from #6138. This combines @cicdw and @madkinsz suggestions by reusing our existing* labeler action to apply the `v1` label anytime a PR is opened in this branch.
Going forward, all PRs that use the 1.x branch as a base should have the `v1` label applied for easy triage.
\*the action doesn't already exist in _this_ branch, natch

Add labeler

---

src/prefect/cli/cloud.py

Empty profile names will produce an invalid `profiles.toml` file, causing errors later on. This PR makes it so we'll simply fail if an empty profile name is provided.

Fail login on invalid profile name

---

src/prefect/cli/profile.py
tests/cli/test_profile.py

Closes https://github.com/PrefectHQ/prefect/issues/6110 by changing the active profile in the profiles file if it is the one that was renamed. Includes a warning if you've renamed an active profile set by environment variable.

Switch the name of the active profile on rename if in use

---

changes/pr5819.yaml
docs/orchestration/agents/kubernetes.md
src/prefect/agent/kubernetes/agent.py
tests/agent/test_k8s_agent.py

This allows custom job name prefix using the job template passed to the KubernetesAgent.
The current code in `KubernetesAgent.generate_job_spec` forces a job name prefix of `prefect-job`. This change  means that the job template's `metadata.name` (if it exists) will be used as the job name prefix. If not, it will fall back to `prefect-job`
This PR allows users to name jobs so that they may be more easily identifiable.
This PR:

Allow custom job name from passed job template

---

.circleci/config.yml

Release 1.3.0 failed due to branch checks in CircleCI https://github.com/PrefectHQ/prefect/runs/7637395822 expecting `master`.

Fix Docker image builds for 1.x branch

---

requirements.txt

This was necessary for ray which has been moved out of the core library
cc @ahuang11 may need to be added to `prefect-ray`
@Sahiler  this should be updated in conda-forge as well

Remove pickle5 requirement

---

.circleci/config.yml

Attempts to fix our CircleCI commit check now that the default branch is "main." Previously, we cloned the repo and tested if a commit was in the "master" branch. Now, we need to check if the commit is in the "1.x" branch, but because that isn't the default branch, we need to create it locally before we check the commit.
Fixes #6190 
I manually ran the git commands in our CircleCI config locally until I could reproduce the error (I had to clone a fresh copy of `prefect`, which finally reproduced the issue). Then I ran the command `git branch 1.x origin/1.x` and verified that the error did not occur.
- If no issue exists, …

Create a local 1.x branch before we check if the commit exists in it

---

orion-ui/src/pages/Deployment.vue

Parameters don't work for deprecated deployments. So hiding the tab altogether.

UI: Hide the parameters tab on deprecated deployments

---

orion-ui/package-lock.json
orion-ui/package.json
orion-ui/src/App.vue
orion-ui/src/pages/BlocksCatalogView.vue
orion-ui/src/router/index.ts
orion-ui/src/router/routes.ts

Adds a page for viewing block types. This is useful because there are long descriptions and code examples that are not visible when viewing the list of block types. 
Implementation for https://github.com/PrefectHQ/orion-design/pull/443

Feature: Block type page

---

src/prefect/filesystems.py

- Adds `ignore_files` on Azure block
- Skips upload if a file is a directory rather than file, otherwise Azure upload gets stuck
- created a block
- created a deployment with Azure and Process

Fix: Add ignore_files and skip upload if dir

---

src/prefect/infrastructure/kubernetes.py
tests/infrastructure/test_kubernetes_job.py

Previously, we were not sanitizing the key at all and there was no test coverage for this.
Here, I separate handling of keys and values and sanitize both. Additionally, there's now a fallback if the slugified content is empty to the original content which will let Kubernetes throw an informative error about the bad label.
- Consider throwing a local error when slugification results in empty content
- Add checks/enforcement of starting and ending with alphanumeric characters

 Improve sanitization of labels for Kubernetes Jobs

---

src/prefect/orion/orchestration/rules.py
tests/orion/orchestration/test_rules.py

Add error handling to the state validation step.
We have observed intermittent and hard to reproduce database consistency errors where the validated state does not exist (when we believe it should). While at first we believed a race condition might be to blame, @madkinsz showed via a test that we could artificially recreate the error by invoking an exception during the state validation step. 
Here, on any failure to validate a proposed state, we will attempt to validate again a single time. If both attempts fail, we will abort the transition with an informative error. I don't believe it's desirable to defer the decision to retry the transition to the client, as this adds a significant amount of overhead to a failure we know exists on the backend.
We've both added tests to ensure the …

Handle database errors during state transition validation

---

src/prefect/cli/deployment.py
tests/cli/test_deployment_build.py

The manifest only flag should not cause any file uploads to occur and should only generate the flow's JSON manifest.  There was a missing `raise` that preventing the CLI from short circuiting in the right place.
Tests + confirmed locally.
- Please …

Fix manifest only flag

---

src/prefect/client.py
tests/test_client.py

Closes https://github.com/PrefectHQ/prefect/issues/6214
These are already supported by the API but were excluded from the client implementation.

Add flow run name and tag support to `create_flow_run_from_deployment`

---

src/prefect/client.py
tests/test_client.py

The Orion response in `read_flow_by_name` was being parsed as a `Deployment` instead of a `Flow` and that was causing a pydantic validation error. This updates the client to parse it with as `Flow`. Closes #6197 
- Created a unit test.
- Manually verified that I could retrieve a flow by name.

Use `Flow` schema in `read_flow_by_name` instead of `Deployment`

---

src/prefect/orion/utilities/schemas.py

The `PrefectBaseModel.subclass` method (and the underlying `pydantic_subclass` function) say they take _instances_ of `BaseModel` but they actually take _types_ derived from `BaseModel`.
- Please make sure that your QA steps are both thorough and …

Use the correct type annotations for PrefectBaseModel.subclass()

---

src/prefect/blocks/core.py
src/prefect/orion/models/block_schemas.py
tests/orion/models/test_block_schemas.py

Adds the ability to embed `BaseModel` subclasses as fields within blocks. This fixes an issue with the `ImagePullPolicy` field on the `KubernetesJob` block not being saved in the block schema. To resolve, non-block definitions in the generated OpenAPI spec are saved in the `fields` column, while definitions for fields that are block continue to be stored in the `block_schema_references` table.
Note that an update to the blocks UI is still needed for `ImagePullPolicy` to render correctly. I've spoken with @pleek91 and should be addressed in an upcoming block UI refactor.
Closes https://github.com/PrefectHQ/prefect/issues/6163
The code snippet referenced in https://github.com/PrefectHQ/prefect/issues/6163 now runs successfully.
- Please …

Adds support for `BaseModel` fields in blocks

---

src/prefect/__init__.py
src/prefect/context.py
tests/test_context.py

If a flow is called from a different thread than Prefect is imported from, the root settings context is missing. This is because the root settings context is accessed via context variable which is by definition thread independent. Additionally, if the flow was called from a different event loop than the one the module was imported from, the settings context would be missing. To address this, we no longer rely on the context variable. If the context variable does not detect any settings, we return a global variable where we have stashed a `SettingsContext` instance. We initialize this once on module import and it is accessible by all threads and event loops.
Initially, I thought we should just cache the settings context per thread or event loop and reinitialize it where necessary. See …

Fix missing global settings by caching object instead of relying on contextvars

---

requirements.txt

readchar released a new version, that finally fixes support for arrow-keys on windows. As this featrue is usefull to this project I recomend requiring that version.

bump readchar to >=3.0.6

---

src/prefect/engine.py

This log is confusing, particularly for the default task runner. Startup of the task runner is only significant if it takes a long time, e.g. the Dask task runner creating a cluster. However, those task runners should provide additional logs indicating the slow operation. The utility of this log is retained for users that enable a debug level log allowing us to determine where an issue occurs.

Change log level to DEBUG for starting task runner

---

.github/ISSUE_TEMPLATE/1_general_bug_report.yaml
.github/ISSUE_TEMPLATE/2_ui_bug_report.yaml
.github/ISSUE_TEMPLATE/3_feature_enhancement.yaml

We already have a `needs:` category and this label is otherwise verbose.
Existing labels can be updated after merge.

Update `status:needs-triage` to `status:triage`

---

src/prefect/cli/flow_run.py
tests/cli/test_flow_run.py

Adds a `--state` parameter to `prefect flow-run ls` to filter flow runs by the name of the state. Closes #6065 
- Unittests and manual verification
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with …

Add support for filtering on state name to `prefect flow-run ls`

---

src/prefect/engine.py
src/prefect/infrastructure/docker.py
tests/infrastructure/test_docker_container.py

- Adds a `DockerRegistry` block with a `login` capability.
- Adds an `image_registry` setting to the `DockerContainer` infrastructure block allowing login to a registry before image pull.
Addresses https://github.com/PrefectHQ/prefect/issues/6230 — I do not think it is fair to close this since a separate implementation with ECR token refresh support will be required.

Add `DockerRegistry` block for `DockerContainer` to pull images from registries with authentication

---

docs/tutorials/deployments.md

The example of running `prefect deployment inspect` contained single quotes around the deployment name.
However, these quotes are encoded as %27 in the GET request to the API, which in returns a 404.
>"GET /deployments/name/%27leonardo_dicapriflow/leo-deployment%27 HTTP/1.1" 404 Not Found
Removing the quotes solves this issue. I'm running prefect on windows, could the behavior differ using another OS?

Fixed example for prefect deployment inspect

---

src/prefect/cli/_types.py
src/prefect/cli/block.py
src/prefect/cli/cloud.py
src/prefect/cli/concurrency_limit.py
src/prefect/cli/deployment.py
src/prefect/cli/flow.py
src/prefect/cli/flow_run.py
src/prefect/cli/profile.py
src/prefect/cli/work_queue.py
tests/cli/test_typer_utils.py

In this PR we further extend our `Typer` wrappers to add the ability to add pluralized versions of our subcommands to our CLI. This implementation creates hidden (e.g. our documentation and help menus will only list the "singular" subcommands) alternate commands that we can specify when adding a subcomand to a `Typer` object via the `add_typer` method.
@cicdw suggested that we might want to consider a simple default pluralization scheme for each subcommand. This would reduce the maintenance overhead. One benefit to explicitly specifying pluralizations: in this PR I've purposefully omitted pluralizations for specific subcommands that make no sense, though I think that decision should ultimately be a product one.
Another interesting point is we could use the ability to explicitly specify …

Pluralize CLI commands

---

src/prefect/orion/api/block_schemas.py
src/prefect/orion/models/block_schemas.py
tests/orion/api/test_block_schemas.py
tests/orion/models/test_block_schemas.py

Makes block schema creation idempotent. If a block schema with the checksum calculated during creation already exists, then the existing block schema is returned instead of returning an error. This is to account for issues identified in #6265  caused by differences in block schema checksum calculation between the Python client and Orion server.
- Updated and added tests to verify that block schema creation called multiple times returns the same block schema and does not cause errors.
- Tested locally with an Orion server running code from main and a Python client running 2.0.3 with mismatched checksum calculation logic.
- If …

Makes block schema creation idempotent

---

orion-ui/src/pages/FlowRunCreate.vue

This PR updates the `FlowRunCreate` page component `createFlowRun` logic to reflect the run being created.
Closes: #6355
Create a run that starts in the future
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody …

Bugfix: Fix issue where flow run toast notification always showed "now"

---

src/prefect/infrastructure/docker.py

Follow up to #6303 
- Adds a base class. This will allow the ECR registry at https://github.com/PrefectHQ/prefect-aws/pull/68 to inherit shared logic and configuration
- Updates `login` to be async. Block methods should be async first.

Add base class and async compatibility to DockerRegistry

---

src/prefect/orion/api/deployments.py
src/prefect/orion/api/work_queues.py
src/prefect/orion/database/migrations/MIGRATION-NOTES.md
src/prefect/orion/database/migrations/versions/postgresql/2022_08_07_134410_77eb737fc759_add_work_queue_name_to_runs.py
src/prefect/orion/database/migrations/versions/sqlite/2022_08_07_134138_575634b7acd4_add_work_queue_name_to_runs.py
src/prefect/orion/database/orm_models.py
src/prefect/orion/models/deployments.py
src/prefect/orion/models/work_queues.py
src/prefect/orion/schemas/actions.py
src/prefect/orion/schemas/core.py
src/prefect/orion/schemas/filters.py
tests/fixtures/database.py
tests/orion/api/test_deployments.py
tests/orion/api/test_work_queues.py
tests/orion/models/deprecated/test_work_queues.py
tests/orion/models/test_deployments.py
tests/orion/models/test_work_queues.py

Implements the backend changes described in the [raft design doc](https://www.notion.so/prefect/Improving-Run-Work-Queue-Affinity-5a61f9ef96e6495d8605a43327591311), namely:
- work queues operate strictly by name, not by matching tags. Deployments (and flow runs) are explicitly linked to a single work queue
- as a convenience, work queues are automatically created whenever deployments (or agents) reference them. This means users do not need to interact with work queues explicitly unless they want to use work-queue specific features like pausing and concurrency
- backwards-compatibility is maintained. If `work_queue.filter is not None`, it is considered a "legacy" work queue and uses tag-based matching. Conversely, if `work_queue.filter is None` then it is a "new" work queue and tag …

Backend changes for work queues operating on name, not tags

---

src/prefect/deployments.py

If not run in a worker thread, the user's code is executed in an "async" context which means that any methods decorated by `sync_compatible` will return a coroutine. However, top-level code in a script is always intended to be run in a "sync" context, so the user can never `await` the coroutines and code that works without a deployment will break while using a deployment.
_Needs QA and unit test_
- Please reference the related issue by including …

Load flows for deployments in a worker thread

---

src/prefect/cli/profile.py

Minor change - there was an extra "f" before the database was printed, maybe from an old f-string declaration.

Remove extra "f" in CLI message

---

src/prefect/cli/deployment.py
src/prefect/deployments.py
src/prefect/orion/schemas/schedules.py

This PR:
- fixes issues with `main` that were caused by a bad merge resolution (sorry everyone!)
- extends the `deployment build` CLI to support 3 schedule types: cron, interval and rrule
Tested by specifying three different schedules for a deployment locally, over specifying multiple schedules, and not specifying any schedule at all.  That's how I discovered the issues with `main` :D 
- Please reference the related issue by including "closes `<link …

Add support for specifying schedules via deployment CLI

---

src/prefect/cli/work_queue.py
tests/cli/test_work_queues.py
tests/fixtures/database.py
tests/orion/api/test_work_queues.py

Recent changes to work queues have advanced work queue names as the primary user-facing identifier, instead of UUIDs. This aligns with work-queues being more lightweight, automatically generated objects. This PR updates the `prefect work-queue` CLI with similar behavior. It now accepts either an ID or a name for operating on work queues, which is a significant UX improvement:
Old:
```console
prefect work-queue set-concurrency-limit 45362125-0a31-4897-b8a4-9319264f2713 5
prefect work-queue inspect 45362125-0a31-4897-b8a4-9319264f2713
```
New:
```console
prefect work-queue set-concurrency-limit my-queue 5
prefect work-queue inspect my-queue
```
Note this change is not breaking (old commands still work). This PR also adds tests for both the name and ID versions of this subcommand

Update work-queue CLI to accept both IDs and names

---

src/prefect/utilities/processutils.py

Previously, this utility would call blocking writes to stderr and stdout directly. This appears to introduce the possibility of race conditions and blocked event loops when many processes are run concurrently. Since we use these utilities to launch flows in parallel processes from the agent, it is important that they are robust to concurrency. `wrap_file` _may_ not be thread safe, but this is still an improvement from where we were. There is not a clear suggested pattern for this, see extensive discussion at https://github.com/python-trio/trio/issues/174.
Attempts to address https://github.com/PrefectHQ/prefect/issues/6335
I wrote a recursive subprocess test
```python
from prefect.utilities.processutils import run_process
import anyio
import sys
async def main(count):
if count <= 0: …
```

Improve robustness of subprocess text streaming

---

.github/CODEOWNERS

Tiny housekeeping so @tpdorsey is auto-suggested as the reviewer for changes to the mkdocs config

Add mkdocs top level files to codeowners

---

RELEASE-NOTES.md
src/prefect/cli/deployment.py
src/prefect/deployments.py
tests/cli/test_deployment_build.py
tests/cli/test_deployment_cli.py
tests/test_deployments.py

- Adds a default work queue ("default") to client-side Deployments (no server-side changes)
- Adds helpful messages after `apply`-ing a deployment to start a work queue OR that no work queue was provided
cc @anna-geller 
- Please make sure that your …

Add helpful defaults and messages when creating deployments

---

src/prefect/utilities/callables.py
tests/test_engine.py

Fixes an issue in `2.1.0`. Initial Slack thread here https://prefecthq.slack.com/archives/C03RMGZ62DN/p1660823154255309
Repro
```python
from prefect import get_run_logger
@task
def say_hi(user_name: str):
logger.info("Hello from Prefect 2.0, %s!", user_name)
@flow
def hello(user: str = "Marvin"):
say_hi(user)
```
```
prefect deployment build flows/hello.py:hello --name process -q prod -t project \
-o deploy/process.yaml -ib process/prod -v GITHUB_SHA
prefect deployment apply deploy/process.yaml
prefect deployment run hello/process
```
Error output:
```
13:44:57.911 | ERROR   | Flow run 'gray-wombat' - Validation of flow parameters failed with error: SignatureMismatchError("Function expects parameters ['user'] but was provided with …
```

Don't raise an error if default args are missing on a flow

---

src/prefect/logging/loggers.py
tests/test_logging.py

Throw a type error instead of falling through to a "no context available" error if `get_run_logger` is called with an invalid context type. This should help narrow the cause of errors like the following where we can see the function is called with a value.
```python
File "/root/venv/lib/python3.8/site-packages/prefect_dask/task_runners.py", line 236, in wait
return await future.result(timeout=timeout)
File "/root/venv/lib/python3.8/site-packages/distributed/client.py", line 294, in _result
raise exc.with_traceback(tb)
File "/root/venv/lib/python3.8/site-packages/prefect/engine.py", line 959, in begin_task_run
get_run_logger(flow_run_context).debug(
File "/root/venv/lib/python3.8/site-packages/prefect/logging/loggers.py", line 91, in get_run_logger
raise …
```

Add error message if `get_run_logger` receives context of unknown type

---

src/prefect/agent.py
src/prefect/client.py
src/prefect/engine.py
src/prefect/orion/orchestration/core_policy.py
src/prefect/orion/schemas/states.py
src/prefect/testing/fixtures.py
tests/test_agent.py
tests/test_client.py
tests/test_engine.py

This method is performing more engine logic and does not map to a single API route. It makes increasing sense for this logic to take place in the engine alongside other client-side orchestration logic. This change should reduce circular imports while addressing result persistence and tracking during state proposal.
Since some of our tests relied on the `client` module importing its own copy of `sleep`, I've encountered a lot of issues moving this function. In an attempted to save us from this problem in the future, I've updated the mock sleep pattern.
Updated unit tests
- If no issue exists, please create a bug report issue …

Move `propose_state` from `OrionClient` to `engine`

---

src/prefect/client.py
src/prefect/orion/schemas/actions.py
tests/test_client.py

This will facilitate updating orchestration rules discovered from flow-level annotations for deployment flow runs.
Related to #6485 
See usage in https://github.com/PrefectHQ/prefect/pull/6489
- Please make sure that your QA steps are both thorough …

Add `empirical_policy` to flow run update route

---

src/prefect/orion/orchestration/core_policy.py
src/prefect/orion/schemas/core.py

This allows us to tell if these values were provided _explicitly_ on the run or if they can be updated with values discovered at runtime.
Related to #6485 
See usage in https://github.com/PrefectHQ/prefect/pull/6489
- Please make sure that your QA …

Update flow run policy retry settings to be nullable

---

src/prefect/engine.py
src/prefect/testing/fixtures.py
tests/test_engine.py

Retries are configured on ad-hoc flow runs during flow run creation. When flow runs are created for deployments, settings are copied from the deployment to the flow run. However, deployments do not have any concept of flow run orchestration policies yet. Instead of introducing retries to deployments now, we will update the flow run with any discovered orchestration settings at runtime. In the future, the deployment may override these discovered settings by setting values on flow run creation. With the changes in #6488 we should not need to change this code for that behavior to take effect :)
Requires #6486 and #6488
Closes #6485 
- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary …

Update deployment flow run retry settings with runtime values

---

docs/concepts/blocks.md

It was hard to find how to add it to Cloud blocks, plus registering is not just for new block types, so I moved it to its own heading.
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge …

Move registering blocks to its own heading

---

changes/6412.yml
src/prefect/tasks/databricks/databricks_submitjob.py
tests/tasks/databricks/test_submit_multirun.py
tests/tasks/databricks/test_submit_run.py

Fixes https://github.com/PrefectHQ/prefect/issues/6411
Create a two tasks flow creating two instances of DatabricksSubmitMultitaskRun
```
with Flow('my-flow) as flow:
task_1 = DatabricksSubmitMultitaskRun()
task 2 = DatabricksSubmitMultitaskRun()
```
from the log you should see that the two run id are different
- If no issue exists, …

Using Python object id as idempotency token for DatabricksSubmitMultitaskRun

---

src/prefect/cli/root.py
tests/cli/test_version.py

Previously, "hosted" was displayed for self-hosted and Prefect Cloud offerings. This will help us distinguish user backends during issue triage.
```
$ prefect --profile bar version 
Version:             2.1.1+24.gd7ba087cf.dirty
API version:         0.8.0
Python version:      3.8.3
Git commit:          d7ba087c
Built:               Mon, Aug 22, 2022 10:50 AM
OS/Arch:             darwin/x86_64
Profile:             bar
Server type:         cloud
```
- …

Add "cloud" to `prefect version` server type display

---

orion-ui/src/pages/WorkQueue.vue

because the watcher that triggers the persistent deprecated toast watches all of `workqueue`, any change (like pausing) will create additional toast messages. The fix was just to narrow the scope of what is watched
before: 
https://user-images.githubusercontent.com/6098901/186240647-58c9f4c0-4a8b-4a1f-af6d-d94a95d48c89.mov
after:
https://user-images.githubusercontent.com/6098901/186240671-fae75650-f0b5-44af-9793-08b012afd193.mov
you might notice that "work queue active/paused" toasts are stacked on top, that is a separate bug logged [here](https://github.com/PrefectHQ/orion-design/issues/527)

BugFix: duplicating work queue deprecated toast message

---

src/prefect/cli/deployment.py
src/prefect/deployments.py
src/prefect/filesystems.py
tests/cli/test_deployment_cli.py
tests/test_filesystems.py

This PR exposes the ability for users to specify relative subpaths when working with remote storage for deployments; in particular users can now do one of the following mutually exclusive things:
- provide a `--path` that specifies a relative path within remote storage to upload to / retrieve from
- specify such path with syntactic sugar of the form `--storage-block s3/dev/subdirectory/path` 
Closes https://github.com/PrefectHQ/prefect/issues/6320
Tested locally, still need to do more extensive QA before we can merge.
- Please make sure that your QA steps are both …

Relative paths

---

src/prefect/cli/agent.py

Minor change to display prefect version running on agents; accessing this information quickly and efficiently has come up a few times when debugging (**cc:** @dylanbhughes )

Agent version display

---

scripts/generate-lower-bounds.py
tests/scripts/test_generate_lower_bounds.py

Fixes bug found in https://github.com/PrefectHQ/prefect/pull/6540 where `generate-lower-bounds.py` fails to retain prerelease labels.
If `aiosqlite` is modified to be `a0`, you can see the generated requirements retain the label
```
❯ ./scripts/generate-lower-bounds.py requirements.txt                         
aiofiles==0.7.0
aiohttp==3.8.1
aiosqlite==0.17.0a0
```
Unit test coverage was added for edge cases and other prerelease labels.
- Please …

Add support for prereleases to `generate-lower-bounds`

---

src/prefect/agent.py
src/prefect/cli/deployment.py
src/prefect/deployments.py
tests/test_deployments.py

This PR tidies up some issues with blocks related to deployments:
- stops redundantly saving storage blocks as anonymous blocks
- stops saving default infra blocks on agents as anonymous blocks
- exposes a `--skip-upload` flag on `build` to avoid remote storage uploads (related to https://github.com/PrefectHQ/prefect/issues/6376 but does not take it that far yet)
Example usage:
```
prefect deployment build ./flows/example.py:main --name "Example" -sb s3/dev --skip-upload
prefect deployment apply main-deployment.yaml
```

Storage upload updates

---

src/prefect/deployments.py
tests/cli/test_deployment_cli.py
tests/test_deployments.py

This PR resolves a critical issue with Deployments defined via Python; specifically, the `entrypoint` should _always_ be relative to `remote_storage.basepath / path` and was incorrectly being set as an absolute path on the local machine, resulting in failed deployment runs.
Closes #6482 
Closes #6463 
Closes #6469 

Resolve issue with python-based deployments having incorrect entrypoints

---

src/prefect/orion/schemas/states.py

Mypy complains that calls like `state.is_completed()` are untyped in a typed context. 
This PR should fix that.
Closes #6562 

Add type hints to state predicates

---

docs/concepts/database.md

Prefect Orion requires functionality from the pg_trgm extension when using PostgreSQL. This extension is installed and enabled by default in many cases (like when using the Postgres Docker image), but it is not _always_ available. For example, in Postgres packages included in the package repositories of many Linux distros, the extension is not enabled by default; you must install postgres-contrib and then run a Postgres command to add the extension. 
I worry that mentioning this in the docs adds friction, but in my experience it's common for engineers to run Postgres in Docker on their dev machines even though their production environment uses distro-installed Postgres. They figure that it is Postgres on Linux either way, so if it works in dev it should work in production, but this isn't …

Update database docs for postgres

---

src/prefect/utilities/asyncutils.py
tests/utilities/test_asyncutils.py

Attempts to resolve a common confusion around `sync_compatible` calls. You cannot call a `sync_compatible` method from a synchronous function that was called by an asynchronous function. For example:
```python
async def foo():
bar()
def bar():
foobar()
@sync_compatible
async def foobar():
pass
run_async_in_new_loop(foo)
```
The proper pattern is
```python
async def foo():
await run_sync_in_worker_thread(bar)
def bar():
foobar()
@sync_compatible
async def foobar():
pass
run_async_in_new_loop(foo)
```
There is likely a small performance hit from peaking at the frame of the caller to see if it is an async function. We attempt to minimize this by retrieving at a single frame instead of the full stack.
Instead of throwing an error, we could support execution of this case by creating a _new_ …

Add error when sync compatible methods are used incorrectly

---

src/prefect/cli/deployment.py
src/prefect/deployments.py
src/prefect/docker.py
tests/test_deployments.py

This PR makes some adjustments to deployment uploads to remote storage:
- calling `deployment.upload_to_storage` no longer adjusts attributes of the deployment object other than storage
- exposes `skip_upload` flag on `Deployment.build_from_flow` for feature parity with the CLI
- exposes new `upload` flags on both the `deployment.apply` method as well as the `apply` CLI
The `--skip-upload` / `--upload` combo addresses #6376 in a non-breaking way.
```
prefect deployment build ./flows/example.py:main -n "demo" -sb s3/dev --skip-upload
prefect deployment apply main-deployment.yaml --upload
```

Deployment upload flags

---

.github/workflows/release.yaml

This should improve the runtime of our release process by using cached image
layers between runs.  Note, though, that the biggest benefits here come from
optimizing the order of the Dockerfile to maximize layer reuse.  This is
something we can work on over time.
Reference for the cache directives: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache

Use Github Action's cache for image layer caches.

---

src/prefect/tasks.py

After running into `prefect.exceptions.MappingLengthMismatch` when I passed a `str` arg to `Task.map` and it was treated as an iterable, I wasn't sure that `unmapped` was implemented yet - there was no example I could find of unmapped being used on an arg passed to `Task.map`
```python
from prefect import unmapped
@task
def my_task(n, static_str):
print(f'{n} - {static_str}')
@flow
def my_flow():
my_task.map([1, 2, 3], unmapped("Hello!"))
```

add unmapped example to `Task.map` docstring

---

src/prefect/infrastructure/kubernetes.py
tests/infrastructure/test_kubernetes_job.py

Kubernetes uses `command` and `args` where Docker uses `entrypoint` and `command` respectively. By setting the infrastructure command in the `command` field of a Kubernetes container, we bypass any entrypoint configured on the container. By default, we should respect container entrypoints. This is particularly relevant for the Prefect base image which uses the entrypoint to install extra packages.
Closes #6551 
This may be a breaking change in some specific cases, i.e. the user is using a container that has an invalid entrypoint or an entrypoint that should be bypassed.
```python
from prefect.infrastructure import KubernetesJob
job = KubernetesJob(
command=["pip", "show", "s3fs"],
env={"EXTRA_PIP_PACKAGES": "s3fs"},
)
await job.run()
```
```
+pip install s3fs
Collecting s3fs
Downloading …
```

Update Kubernetes Job to use `args` instead of `command`

---

setup.py
src/prefect/tasks/sodaspark/__init__.py
src/prefect/tasks/sodasql/__init__.py

Fixes the task library tasks by removing the soda sql tasks from the `task_library_ci`. `soda-sql` and `soda-spark` have  very restrictive dependency pins and have been deprecated. I added a deprecation warning reflecting that. We have no records of use for the soda tasks, so I don't expect issues from these changes.
- If no issue …

Fixs 1.x task library tests

---

src/prefect/tasks.py
src/prefect/utilities/collections.py
tests/test_tasks.py
tests/utilities/test_collections.py

Updates our `isiterable` check to treat `str` and `bytes` as non-iterable types. Our usage of `isiterable` is to detect if a parameter should be mapped over or not. These objects are singletons that happen to be iterable and should not require an explicit `unmapped` during mapped calls. Passing a string to a mapped call and expecting it to be treated as a constant is a very common pattern.
I've also updated the `Task.map` documentation to clarify this while simplifying and fixing some examples.
I noticed this in https://github.com/PrefectHQ/prefect/pull/6579.
```python
@task
def display(prefix, item):
print(prefix, item)
@flow
def my_flow():
display.map("Check it out: ", [1, 2, 3])
my_flow()
``` …

Update iterable detection to exclude strings and bytes

---

changes/6572.yaml
src/prefect/backend/flow_run.py
tests/backend/test_flow_run.py

Closes bug reported in https://prefecthq.slack.com/archives/C028BPL85C3/p1661452093250219 where if all of the task runs are cached an error is thrown when retrieving cache runs
```python
File "/usr/local/lib/python3.9/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
value = prefect.utilities.executors.run_task_with_timeout(
File "/usr/local/lib/python3.9/site-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
return task.run(*args, **kwargs)  # type: ignore
File "/redacted.py", line 122, in redacted
tasks = view.get_all_task_runs()
File "/usr/local/lib/python3.9/site-packages/prefect/backend/flow_run.py", line 739, in get_all_task_runs
task_run_data = TaskRunView._query_for_task_runs(
File …
```

Fix `FlowRunView` task run queries when all task runs are cached

---

.github/workflows/labeler.yml

See brief discussion at https://prefecthq.slack.com/archives/CH84XHRB4/p1661455833761669
The labeler does not have permissions to run on external contexts since it requires GitHub credentials.

Update labeler to work for external contributions

---

src/prefect/blocks/core.py
src/prefect/cli/deployment.py
src/prefect/deployments.py
src/prefect/exceptions.py
src/prefect/filesystems.py
tests/test_deployments.py
tests/test_filesystems.py

This PR wires up `GitHub` remote storage so that it can be used with deployments seamlessly.   Specifically, users can now specify:
- a remote repository (currently required to be public, but we will expand support for private repos)
- a reference branch or tag of that repository
- and an optional subdirectory of that repository to use as a workflow deployment project structure
Closes #6585 
We can actually illustrate this rather nicely off the current branch `github-deployments` that this PR is based on! 
Start by navigating to `tests/test-projects/nested-project` ([see its file structure here](https://github.com/PrefectHQ/prefect/tree/main/tests/test-projects/nested-project)).  We begin by creating a `GitHub` remote storage block:
```python
from prefect.filesystems import GitHub
g = …
```

GitHub-based deployments

---

README.md

This PR modifies the badges to use our brand colors using the flags at the bottom of [this page](https://shields.io/).

Update badge colors

---

RELEASE-NOTES.md
src/prefect/filesystems.py
src/prefect/utilities/filesystem.py
tests/test-projects/flat-project/.prefectignore
tests/test-projects/tree-project/.prefectignore
tests/test_filesystems.py

This makes a couple adjustments to `RemoteFileSystem.put_directory`:
- Updates `put_directory` to use `local_path` when generating the list of files to copy.
- Updates the way the remote file name is created to use `pathlib` for better cross-OS support.
This example will create a memory-based RemoteFileSystem, copy in files from a path and then use `fsspec` to list the stored files.
```python
import anyio
import functools
import sys
from prefect.filesystems import RemoteFileSystem
fs = RemoteFileSystem(basepath="memory://root")
partial = functools.partial(fs.put_directory, sys.argv[1])
anyio.run(partial)
print(fs.filesystem.glob("/root/**"))
```
I tested this both on the Mac and in Windows via Parallels.
Closes #6603 
Closes #6580 
Closes #6276

Ensure RemoteFileSystem.put_directory handles local_path and windows file structure

---

tests/orion/database/test_migrations.py
tests/test_engine.py

Marks flaky test as flaky to improve test failure signal.  Example failure here: https://github.com/PrefectHQ/prefect/runs/8102902087?check_suite_focus=true

Mark test as flaky

---

.github/ISSUE_TEMPLATE/3_feature_enhancement.yaml

Every time I open an enhancement request I want to explain how things currently work and what's wrong with that before proposing a solution. If users do not have a clear story of the current behavior, a feature request does not make much sense. Currently, our issue template prompts for your proposed change _then_ prompts for current behavior. This pull request swaps the order of these fields. This should make issues easier to read and write.

Swap order of "current" and "proposed" behavior in enhancement issue template

---

docs/concepts/logs.md

Example for task logging has unused "name" argument that is obviously meant for naming the task.

Correct name argument for task logging example

---

src/prefect/orion/database/dependencies.py
src/prefect/orion/database/interface.py
tests/orion/database/test_dependencies.py

Currently, the database permits dependency injection in a variety of ways -- the ORM config, customizable queries, and the database's own configuration. One thing that can't be changed is the parent interface itself, which is always an `OrionDBInterface`.  
The `OrionDBInterface` re-exposes many of its component attributes as properties or methods, which provides convenient access (e.g. `db.json_arr_agg` instead of `db.queries.json_arr_agg`, a more difficult-to-discover access point. However, this means that if dependency injection is used to add a new query, it can not be accessed in the same way. By allowing the `OrionDBInterface` class itself to be injected, developers adding new queries and properties specific to their use case can  modify the parent interface as well.
- If no issue …

Allow the DB interface class to be modified

---

src/prefect/infrastructure/base.py
src/prefect/infrastructure/docker.py
src/prefect/infrastructure/kubernetes.py
src/prefect/infrastructure/process.py
tests/infrastructure/test_docker_container.py
tests/infrastructure/test_kubernetes_job.py
tests/infrastructure/test_process.py

This is particularly helpful for testing infrastructure, but is also relevant for the many cases in which a user may want to run commands in infrastructure from sync flows or tasks.
Previously the following would not run the process as it returned a coroutine
```python
from prefect.infrastructure import Process
@flow
def foo():
process = Process(command=["echo", "hello!"])
process.run()
foo()
```

Add sync compatibility to `run` for all infrastructure types

---

src/prefect/infrastructure/docker.py

Addresses confusion in https://github.com/PrefectHQ/prefect/issues/6652#issuecomment-1233243902
Previously, the default logs would make it appear as though multiple containers had been created for a single run.
```python
import anyio
from prefect.infrastructure import DockerContainer
from prefect.logging.configuration import setup_logging
setup_logging()
container = DockerContainer(command=["echo", "hello!"], name="test")
anyio.run(container.run)
anyio.run(container.run)
```
```
13:27:32.455 | INFO    | prefect.infrastructure.docker-container - Creating Docker container 'foo'...
13:27:32.765 | INFO    | prefect.infrastructure.docker-container - Docker container 'foo' has status 'exited'
hello!
13:27:32.799 | INFO    | prefect.infrastructure.docker-container - Creating Docker container …
```

Update Docker container name collision log to `INFO` level for clarity

---

.gitignore
src/prefect/orion/api/block_documents.py
src/prefect/orion/database/configurations.py
src/prefect/orion/database/query_components.py
src/prefect/orion/models/block_documents.py
src/prefect/orion/schemas/filters.py
tests/orion/api/test_block_documents.py
tests/orion/api/test_flow_runs.py
tests/orion/models/test_block_documents.py

Closes https://github.com/PrefectHQ/nebula/issues/1492
@zangell44 noticed that block document queries are starting to take longer and longer in Prefect Cloud, even when querying for a nonexistent block document ID (see attached issue for detail, internal repo so re-summarizing here). Query complexity exploded into the hundreds of thousands, the culprit being an odd `seq scan` of the block document table, even though a block document ID was being provided.
When we looked closely, we identified that the blame lies with [this join condition](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/orion/models/block_documents.py#L148-L153):
```python
sa.or_(
db.BlockDocument.id == block_document_id,
recursive_block_document_references_cte.c.parent_block_document_id.is_not(
None
),
)
``` …

Refactor block documents queries for speed ⚡️

---

setup.cfg
src/prefect/infrastructure/docker.py
tests/infrastructure/test_docker_container.py

Closes https://github.com/PrefectHQ/prefect/issues/6648
If a container was removed while streaming logs, we threw an exception instead of returning the correct result. This  pull request updates our container watching implementation to repeatedly yield the latest container metadata it has seen so a wrapper can catch any `NotFound` errors and still produce a `DockerContainerResult`.
I imagine there are some edge cases here where we end up with a version of the container metadata that does not contain the exit code, but we can tackle those in a later as they'd require more redesign of how we stream logs. For example, the call to `wait()` could be fully decoupled from the log streaming calls  by running them in separate worker threads.
As described in the linked issue, the following would …

Update Docker container runs to be robust to container removal

---

src/prefect/orion/utilities/schemas.py
tests/orion/utilities/test_schemas.py

The `PrefectBaseModel` configures behavior when extra fields are provided to models as "forbid" or "ignore" depending on if we are in test mode. However, it just checked the truthiness of `os.getenv` which meant that if the variable was present with any non-empty value it would be treated as `True`. When we pass settings through from the main process to child processes or containers, we may want to set the variable to `"False"` which was then wrongly treated as `True`.
This pull request updates the parsing of the variable to check for truth-like values. I explored using `pydantic.parse_obj_as(bool, ...)` but its parsing was a bit more strict than I thought necessary. We want to avoid crashing here since it's on module import.
Previously the following would fail:
```
❯ …
```

Fix parsing of `PREFECT_TEST_MODE` in `PrefectBaseModel`

---

src/prefect/cli/block.py

- Clarifies the that the `prefect block register` command is related to types
- Updates description of `prefect block register` to display nicely during summary
- Updates the `prefect block type` subcommand to have the correct docstring
- Suggests available block types on missing create
- Updates capitalization to match our standard styling
Before
```
❯ prefect block
Usage: prefect block [OPTIONS] COMMAND [ARGS]...                                                     
Commands for working with blocks.                                                                    
╭─ Options ──────────────────────────────────────────────────────────────────────────────────────────╮
│ --help          Show this message and exit.                                                        │ …
```

Update block CLI to match standard styling

---

src/prefect/filesystems.py

In #6620 we adjusted the way that `RemoteFileSystem.put_directory` handled paths to have better cross-OS support, but at the same time introduced a bug where if files where being ignored by `.prefectignore` we were comparing the `included_files` in POSIX format rather than Windows format and this caused any subdirectories to be ignored. This fixes that bug.
Closes #6678 
No real way to give an example, I tested this in Windows via Parallels by:
- Copying the `tree-project`, adding a flow to it and building a deployment from it. This initially showed it copying 4 files, but after this fix it shows the correct 12 files.
- I verified that the unittests added in #6620 were in fact failing in Windows as well. They pass with this change.
Output of successful `deployment build`:
``` …
```

Fix handling of .prefectignore paths in Windows

---

src/prefect/infrastructure/docker.py

The parameters in the docstring got moved around but the second line for `auto_remove` wasn't moved up, this fixes it.
Closes #6441 

Fix `auto_remove` docstring for DockerContainer

---

src/prefect/orion/models/deployments.py
tests/orion/models/test_block_schemas.py
tests/orion/models/test_deployments.py

This PR ensures that the Parameter OpenAPI schema is updated with each deployment creation; previously this update was not occurring, leading to the UI not displaying the correct information.
Closes https://github.com/PrefectHQ/prefect/issues/6563
Take a flow defined as:
```python
@flow 
def my_flow(old: str):
pass
```
and create a basic deployment for it (CLI or Python, doesn't matter).  Add an override for `old` in the UI.
Then update the flow:
```python
@flow 
def my_flow(old: str, new: bool = False):
pass
```
and re-create a basic deployment for it.  Visit the UI - on `main`, the `new` parameter would not be displayed, but on this branch it will be.

Adds test for parameter openapi schema

---

.github/workflows/stale.yml

This enables the [stale action](https://github.com/actions/stale), but sets it in debug mode so that we can look at the changes it would make if it were fully enabled. This way we can change the settings around till we're happy.
To see the debug output we'll have to set the `ACTIONS_STEP_DEBUG` secret in the repo to `true`.

Enable stale action to handle aging issues and pull requests

---

src/prefect/orion/database/configurations.py
src/prefect/orion/database/query_components.py
src/prefect/orion/utilities/database.py
tests/orion/utilities/test_database.py

In https://github.com/PrefectHQ/prefect/pull/6645 we found a bizarre edge case where SQLite passed parameters to the compiled query in the wrong order. This happened at the lowest level of the DBApi -- even `compile()`-ing the statement in SqlAlchemy rendered everything correctly. We were unable to identify the source of the issue (something with nested CTEs and subqueries, presumably) and resolved it with a SQLite-specific code branch that materialized a heavily-parameterized query rather than leaving it as a CTE.
To resolve this properly, this PR changes the SQLite `paramstyle` from `qmark` to `named`. This has the effect of changing 
```
SELECT *
FROM my_table
WHERE x = ? and y = ?
```
to 
```
SELECT *
FROM my_table
WHERE x = :x and y = :y
```
This removes any ambiguity with how …

Use `named` paramstyle for sqlite

---

src/prefect/filesystems.py
tests/test_client.py
tests/test_filesystems.py

When running a deployment within a Docker image that has a non-empty working directory, GitHub storage would fail because `git clone` errors out if the directory is non-empty.  This PR adjusts the logic to `git clone` into a temporary directory (that will always be empty) and then recursively copy all files over into the present working directory.  This code path is the same as if a user had specified a subdirectory of their repository, so a nice side effect is a unified code path.
QA'ed live with @discdiver @WillRaphaelson and @khuyentran1401 

Fix issue with github storage running in non-empty directories

---

src/prefect/deployments.py
tests/utilities/test_services.py

I believe this may resolve the weird bug @znicholasbrown is seeing by avoiding a redundant load.  My theory is that objects loaded with our utility have non-standard attributes making this code path brittle.
I unfortunately don't have time to write a test for this right now, so if anyone else wants to take over this PR or I can follow up later (assuming it closes the issue).

Only load flow if necessary

---

src/prefect/orion/database/interface.py

Minor simplification -- AFAICT these arguments are not optional and in fact `provide_database_interface` errors if any of them are not provided. However, the possibility that they are `None` really upsets mypy in other codebases.

Remove default arguments; components are not optional

---

src/prefect/blocks/core.py
tests/blocks/test_core.py
tests/infrastructure/test_submission.py

This pull request allows model fields to be defined as generic or base block types which means that a model can consume a block without enumerating all known types. This is essential for allowing models to be configured with blocks that are defined outside the core library.
For example, this should allow us to change the `Deployment.infrastructure` field to be `Infrastructure` instead of `Union[Process, DockerContainer, KubernetesJob]`.
This is implemented by adding `block_type_slug` to the `dict()` and `json()` outputs of a block. This field is not included in the block document. During class instantiation, a hook in `__new__` will determine if the block type slug is present and look up a type in the registry. If the block type slug is not present, `__new__` is called normally. This …

Update blocks to dispatch instance creation using slugs

---

src/prefect/engine.py
tests/test_engine.py

Abort signals from the API were being incorrectly treated as crashes. Consequently, a flow run would be forced into a crashed state while running somewhere else.
Closes https://github.com/PrefectHQ/prefect/issues/6725
Create a deployment with a short interval schedule and multiple agents with high prefetch seconds. Multiple agents will attempt to start the flow runs, resulting in some of them aborting. These should not be marked as crashes.

Update crash detection to ignore abort signals

---

netlify.toml

Currently every PR opened from a fork results in a Netlify notification asking to approve the deploy preview; because many of our open source PRs are documentation related, it is convenient to see these builds often.  Right now, we have sensitive environment variables for interacting with our MkDocs insiders repo so we don't want to use those for "untrusted" builds. 
This PR attempts to change our Netlify build command so that it first attempts to install our Insiders package, but if that fails it falls back to a standard MkDocs build (which should work).  We can then turn builds on for unknown authors that don't set sensitive environment variables.  This should hopefully let us see useful deploy previews at the cost of not knowing if our insider builds are failing (this should be readily …

Make Netlify deploy previews resilient on forks

---

orion-ui/src/pages/FlowRun.vue

This PR adds `FlowRunStartTime` component to the meta well on the flowRun page. [Non-breaking changes were made to `FlowRunStartTime` component in orion-design](https://github.com/PrefectHQ/orion-design/pull/557) that will enhance the look of this page and will add the ability to see how late scheduled runs are/were. This PR can be merged right away, and the changes will get applied once the version of orion-design is released and updated in this repo.
Closes https://github.com/PrefectHQ/prefect/issues/6210
Discussion for the solution for this ticket can be found [here](https://prefecthq.slack.com/archives/CJN6L95L7/p1662574917612919)

Add FlowRunStartTime to flowRun meta well

---

src/prefect/agent.py
tests/test_agent.py

~Builds on the simple change in #6453 — this can supersede that pull request entirely if desired.~
Requires #6610 as it uses the agent test refactor there.
Running infrastructure is a two step process:
- Submission: infrastructure is created for the flow run
- Monitoring: the infrastructure is watched for success/failure
AnyIO's `TaskStatus` is used to report the completion of submission
allowing a caller to use `task_group.start` to await submission without
blocking on monitoring. If an error occurs during submission, the
agent captures it and marks the flow run as failed. However, if an
error occured during monitoring, the agent does not capture this
exception. Instead, it is raised in the agent's task group which
can cause the agent and any other concurrent tasks to fail.
A single flow …

Update agent to prevent crash when infrastructure errors after submission

---

docs/orchestration/flow-runs/task-runs.md
src/prefect/backend/task_run.py
tests/backend/test_task_run.py

Addresses issue where task run results cannot be retrieved because stale views are being used by adding `TaskRunView.get_latest()` which retrieves the most recent metadata for a task run while preserving cached results.
See https://prefecthq.slack.com/archives/C028BPL85C3/p1662655107790269 (internal)

Add `get_latest` to `TaskRunView`

---

src/prefect/blocks/core.py
tests/blocks/test_core.py

Closes https://github.com/PrefectHQ/prefect-dbt/issues/54
Previously, when users tried saving a block with a field that was aliased in code, it would not save the aliased field.
A block that fits the description:
https://github.com/PrefectHQ/prefect-dbt/blob/main/prefect_dbt/cli/configs/base.py#L84
Another block:
https://github.com/PrefectHQ/prefect-snowflake/blob/main/prefect_snowflake/database.py#L43
This PR fixes this issue by properly setting `by_alias` in their respective places.
Modified example from the issue above:
```
from prefect_dbt.cli.configs.base import TargetConfigs
@flow
myconfig = TargetConfigs(schema="abc", type="snowflake")
myconfig.save("testconfiguration", True)
loaded_myconfig = myconfig.load("testconfiguration")
return …
```

Fix saving blocks' fields with aliases

---

.github/workflows/stale.yml

The stale action has been running for a few days now. It only has 30 operations it can do, but the [logs](https://github.com/PrefectHQ/prefect/runs/8262229857?check_suite_focus=true) show it doing what I'd expect.Alternatively we could look at increasing the number of operations it's allowed to perform and let it be in debug mode for longer. But I think it's configured pretty well as it is and it's unable to do a lot of damage with only 30 operation per-day.

Disable debug mode on stale action

---

src/prefect/engine.py
tests/test_tasks.py

Preserves relationships between a mapped task and its parameters if that parameter is a future, closes https://github.com/PrefectHQ/prefect/issues/6686.
```python
from prefect import task, flow, get_run_logger
@task
def log_task(x: int):
logger.info(x)
@task
def flat_numbers() -> list[int]:
return [0, 1, 2, 3, 4]
@flow
x = flat_numbers.submit()
log_task.map(x)
```
Will now correctly produce this graph:

Preserve task dependencies to futures passed as parameters in `.map`

---

src/prefect/context.py
src/prefect/engine.py
tests/test_tasks.py

Updates task run contexts to include the latest metadata as we've done previously with flow run contexts. This does not only apply to retries: now normal task runs will receive an object with a `Running` state rather than a `Pending` state.
Closes #6786 
```python
from prefect.context import get_run_context
@task(retries=3)
def flaky_function():
ctx = get_run_context()
print("Start time:", ctx.start_time)
print("Run count:", ctx.task_run.run_count)
print("State name", ctx.task_run.state_name)
print("---")
raise ValueError()
@flow
flaky_function()
return True
```
```
Start time: 2022-09-12T16:11:34.626822+00:00
Run count: 1
State name Running
---
Start time: 2022-09-12T16:11:34.659258+00:00
Run count: 2
State name Retrying
---
Start time: …
```

Update task run orchestration to include latest metadata in context

---

src/prefect/agent.py
src/prefect/context.py
src/prefect/infrastructure/base.py
src/prefect/infrastructure/docker.py
src/prefect/infrastructure/kubernetes.py
src/prefect/infrastructure/process.py
src/prefect/task_runners.py

closes https://github.com/PrefectHQ/prefect/issues/6753

Used anyio.abc full namespace instead of from imports

---

.github/workflows/stale.yml

The `stale` action was using `Stale` as the label instead of the correct `status:stale`. This adjusts the action to use the right one.

Update stale action to use `status:stale` for labeling stale issues

---

src/prefect/cli/deployment.py
src/prefect/deployments.py
tests/test_deployments.py

Updates deployment `infrastructure` field type to the `Infrastructure` base class instead of enumerating all types. This is required for the upcoming infrastructure blocks in collections e.g. `ECSTask` and `CloudRunJob`.
#6622 should allow us to do this without any issues.
```python
from prefect_aws.ecs import ECSTask
Deployment(name="foo", infrastructure=ECSTask(...))
```

Update `Deployment.infrastructure` to accept types outside of the core library

---

scripts/generate-release-notes.py

It turns out `match[0]` is the full match string and you need to start at `1` for groups.
Fixes entry generation from
`- * Task runner documentation fixes and clarifications by @tpdorsey in https://github.com/PrefectHQ/prefect/pull/6733 — tpdorsey`
to
`- Task runner documentation fixes and clarifications — https://github.com/PrefectHQ/prefect/pull/6733`

Fix substitution in release notes generation

---

src/prefect/client/client.py

Each client "creates" a new logger which includes attaching handlers. Since Python loggers are singletons behind the scenes, this results in attaching duplicate handlers to the logger. Messages will then be duplicated per number of clients. Since task runs each have their own client, this can result in many log messages.
To resolve this, we define `logger` as a class variable instead of instance variable. The logger will be created once at import-time.
Closes https://github.com/PrefectHQ/prefect/issues/6831

Use a singleton diagnostics logger for `Client`

---

src/prefect/orion/utilities/names.py
tests/orion/api/test_block_documents.py
tests/orion/utilities/test_names.py

As a convenience, the API can send the last few characters of secrets to the UI. This has raised questions about whether the UI is receiving the entire secret and obfuscating it in the client (for clarity: it does not). In the future, we intend to make this behavior configurable (as some find it to be a useful convenience) but this PR disables it by default to avoid introducing unintended concern.
Closes #6707

Hide secret tails by default

---

src/prefect/orion/api/flow_runs.py
src/prefect/orion/schemas/actions.py
src/prefect/orion/schemas/core.py
src/prefect/orion/schemas/states.py
src/prefect/orion/utilities/schemas.py
tests/orion/api/test_flow_runs.py
tests/orion/api/test_logs.py
tests/orion/api/test_task_runs.py
tests/orion/models/deprecated/test_work_queues.py
tests/orion/models/test_logs.py
tests/orion/utilities/test_schemas.py

Pulls the `copy_model_fields` utility from  https://github.com/PrefectHQ/nebula/commit/9874ae454ce6fa64ad22291fb906584be937b617 and uses it for our actions models instead of the `pydantic_subclass` utility. This means action types no longer violate the Liskov substitution principle in which we were claiming they were subclasses of the parent type but we were excluding fields. We no longer use the subclass utility and it could be removed but I think it may be useful still.
I discovered several cases of undesirable and confusing behavior from the old pattern. I've done my best to match the old behavior but in some cases it was wrong and needed to be changed. This includes one "breaking" change to the set state routes for flow runs and task runs: Previously, these routes would raise a 422 if …

Use `copy_model_fields` utility for action schemas

---

tests/blocks/test_block_standards.py
tests/blocks/test_checksum_consistency.py

Restricts blocks used in suite tests to only the blocks in the prefect module. This way, any blocks that are installed in the same virtual environment will not cause failures in the prefect test suite.

Restricts blocks in suite tests to only blocks in prefect module

---

src/prefect/orion/api/server.py
src/prefect/settings.py
tests/cli/test_block.py
tests/conftest.py
tests/fixtures/client.py
tests/fixtures/database.py
tests/fixtures/storage.py
tests/orion/models/test_block_types.py

Adds the setting `PREFECT_ORION_BLOCKS_REGISTER_ON_START` which is used to determine if blocks should be registered as a server startup step. This may also solve issues being worked on in #6841.
This setting defaults to `True`, but I could see the argument for defaulting it to `False` and then setting it to `True` during `prefect orion start`. This would be a significant improvement to ephemeral client performance, but #6841 could accomplish something similar without changing the default.
Automatic registration of blocks was creating integrity errors during our test seeding process as we seed type models that happened to match a block type that was used in another fixture and auto-registered when a client was started. Previously, we implemented a workaround for this but additional issues …

Add toggle for block registration on application start

---

.github/workflows/windows-tests.yaml

These were copied from the normal Python tests workflow but aren't actually used.

Drop unused workflow steps from Windows GHA workflow

---

.github/workflows/python-tests.yaml
.github/workflows/release.yaml

Conda flavored Docker images are taking 8+ minutes to build compared to the base image build of 2 minutes. The build time is dominated by ~7 minutes of uploading image layers to a cache. Here, we disable the caching as it cannot possible be worth the runtime.

Drop cache upload for Conda flavor Docker images

---

src/prefect/cli/cloud.py
src/prefect/client/__init__.py
src/prefect/client/base.py
src/prefect/client/cloud.py
src/prefect/client/orion.py
src/prefect/deployments.py
src/prefect/engine.py
src/prefect/futures.py
src/prefect/packaging/file.py
src/prefect/packaging/orion.py
src/prefect/results.py
src/prefect/states.py
tests/cli/test_cloud.py
tests/client/test_base_client.py
tests/client/test_orion_client.py

In preparation for client-side schemas, introduces a `prefect.client` namespace.
- Moves `CloudClient` from `prefect.cli.cloud` to `prefect.client.cloud`
- Moves `PrefectHttpxClient`, `PrefectResponse`, and similar to `prefect.client.base`
- Moves `OrionClient` to `prefect.client.orion`
Imports of `prefect.client.get_client` and `prefect.client.OrionClient` are backwards compatible. Other objects previously in the module are not available without specifying `prefect.client.base` or `prefect.client.orion`.
No changes in behavior have been made.
```
client
├── __init__.py
├── base.py
├── cloud.py
└── orion.py
``` …

Refactor client into new namespaces

---

docs/concepts/tasks.md

This PR provides a small fix for the first example of the [`.map()`](https://docs.prefect.io/concepts/tasks/#map) function in the `Task` concepts. In the original example, the parameter `n` got mixed up with `nums`, such that `nums` is not defined.
Running the example raises a `NameError`:
```python
File "python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
result = context.run(func, *args)
File "<stdin>", line 3, in print_nums
NameError: name 'nums' is not defined
```

Fix incorrect parameter name in `.map()` example

---

src/prefect/engine.py
src/prefect/orion/orchestration/core_policy.py
tests/orion/api/test_flow_runs.py
tests/orion/api/test_task_runs.py
tests/orion/orchestration/test_core_policy.py

Here we add a simple orchestration rule preventing redundant transitions. Among other things, this will prevent multiple Agents from orchestrating an active run in competing and inconsistent ways.

Prevent redundant transitions

---

src/prefect/agent/docker/agent.py
src/prefect/agent/ecs/agent.py
src/prefect/agent/kubernetes/agent.py
src/prefect/agent/local/agent.py
src/prefect/agent/vertex/agent.py
tests/agent/test_docker_agent.py
tests/agent/test_ecs_agent.py
tests/agent/test_k8s_agent.py
tests/agent/test_local_agent.py
tests/agent/test_vertex_agent.py

The `PREFECT__CLOUD__SEND_FLOW_RUN_LOGS` environment variables is ignored when explicitly set. This change avoids overwriting it with a default value when set.
Closes #5521

Respect PREFECT__CLOUD__SEND_FLOW_RUN_LOGS

---

src/prefect/agent.py
tests/test_agent.py

Handles infrastructure errors before the agent submit a flow.
Closes #6894

Handles infrastructure errors before the agent submit a flow

---

.github/pull_request_template.md
.github/release.yml

Added the `deprecation` label to the release generation workflow. Also updated the pull request template. It no longer seems feasible to list all possible categorization labels.
See example in #6900

Add `deprecation` label

---

src/prefect/client/orion.py
src/prefect/client/schemas.py
src/prefect/context.py
src/prefect/engine.py
src/prefect/futures.py
src/prefect/orion/api/flow_runs.py
src/prefect/orion/api/task_runs.py
src/prefect/orion/models/flow_runs.py
src/prefect/orion/models/task_runs.py
src/prefect/orion/orchestration/__init__.py
src/prefect/orion/orchestration/rules.py
src/prefect/orion/schemas/responses.py
src/prefect/orion/schemas/states.py
src/prefect/states.py
src/prefect/testing/standard_test_suites/task_runners.py
tests/client/test_orion_client.py
tests/orion/api/test_flow_runs.py
tests/orion/api/test_task_runs.py
tests/orion/orchestration/test_rules.py
tests/orion/schemas/test_states.py
tests/test_flows.py
tests/test_futures.py
tests/test_states.py
tests/test_tasks.py

- Adds `prefect.client.schemas` with:
- `State`: extends server-side schema to include result retrieval
- `FlowRun`: uses client-side state type for field
- `TaskRun`: uses client-side state type for field
- `OrchestrationResult`: uses client-side state type for field
- Add `cls` argument to `prefect.orion.schemas.states` state type utilities for reuse client-side
- Removes `result` from server-side `State` type
- Updates the `OrionClient` to parse API responses as client types
- Moves `OrchestrationResult` to `schemas.responses` to fix circular imports

Introduce `prefect.client.schemas` and client-side state type

---

requirements.txt
src/prefect/serializers.py
tests/test-projects/import-project/my_module/flow.py
tests/test-projects/import-project/my_module/utils.py
tests/test_serializers.py

This prepares `prefect.serializers` for use with results.
- Copies base serializer model from `prefect.packaging`
- This model has support for dispatch so we will be able to dump/load subclasses from JSON
- Copies `PickleSerializer` from `prefect.packaging.serializers` and adds tests
- Adds `JSONSerializer` with support for:
- Alternative JSON libraries (e.g. `orjson`)
- Pydantic JSON encoders by default, extending support to include `Set`, `UUID`, etc.
- User-specified JSON object encoders for custom types`
Future work:
- Deprecation of data document serializers (#6900)
- Removal of packaging serializers …

Add `JSONSerializer` and `PickleSerializer` to `prefect.serializers`

---

docs/concepts/filesystems.md

The Azure filesystem block accepts `bucket_path`, not `basepath` ([source here](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/filesystems.py#L581-L585)). This PR updates the example in the relevant docs section.

Updates Azure filesystem basepath to bucket_path in docs

---

src/prefect/flows.py

Updates the `Flow.with_options` docstring to include `retries` and `retry_delay_seconds`.

Adds retries and retry_delay_seconds to flow.with_options doc

---

docs/concepts/tasks.md
docs/tutorials/flow-task-config.md

This is a documentation change only, fixing instances of the `peristed` typo to `persisted`.

Fix typos, peristed -> persisted

---

src/prefect/client/orion.py
tests/client/test_orion_client.py

Changed the name of the 'filter' property to 'logs', because it was not picked up by the api. 
This pull request closes #6883. 

Fix bug where `OrionClient.read_logs` filter was ignored

---

src/prefect/client/base.py
tests/client/test_base_client.py

Like 429, it is common for a 503 to include a Retry-After header. This retry mechanism will be useful for the client to retry failed requests the server has designated as retryable.
Related to #6748 

Add client retries on 503 response

---

RELEASE-NOTES.md

Add the Teams notification block to the release notes PR.

Add new Teams notification block to the release notes

---

src/prefect/blocks/kubernetes.py
src/prefect/blocks/notifications.py

When upgrading to prefect 2.4.1, this error is spawned multiple times when running a flow:
```
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
```
This is somehow due to the types of some attributes in blocks classes docstring. Maybe a dependency update caused this ?

Remove types in blocks docstring attributes to avoid annotation parsing error

---

src/prefect/blocks/core.py
src/prefect/client/orion.py
tests/blocks/test_core.py
tests/client/test_orion_client.py

Got a report of failures saving blocks from the Slack community. Blocks could be saved outside of flows, but not within flows. Root cause seems to be that `inject_client` was working when creating a new client, but not when retrieving an existing one for functions that had a default value of `None` due to `setdefault` behavior. This change pops `client` from `kwargs` in all scenarios to allow `setdefault` to do it's thing.
Closes https://github.com/PrefectHQ/prefect/issues/6940

Fixes `inject_client` in scenarios where the `client` kwarg is passed `None`

---

src/prefect/cli/cloud.py
tests/cli/test_cloud.py

We've seen some users trying to log in to Cloud 2 with Cloud 1 API key. It would be great to direct them to the right Cloud URL.

Warn if user tries to login with API key from Cloud 1

---

src/prefect/flows.py
tests/test_flows.py

This was missed somehow
```python
@flow
def foo():
pass
bar = foo.with_options(retries=3, retry_delay_seconds=20)
assert bar.retries == 3
@flow(retries=3, retry_delay_seconds=20)
def foo():
pass
bar = foo.with_options()
assert bar.retries == 3
```

Update `Flow.with_options` to actually pass retry settings to new object

---

src/prefect/task_runners.py

Improves performance of the concurrent task runner by using events instead of spinlocks to wait for results where feasible. I believe this only doesn't apply to use of async tasks from sync flows. If performance is a major concern in that case, users should be using sync or async consistently. This follows a pattern established in `PrefectFuture.wait`.
Closes https://github.com/PrefectHQ/prefect/issues/6468
Supersedes #6239 
In #6468 the concurrent task runner was demonstrated to be 7233% slower when performing synchronous IO. Replicated here, the concurrent task runner is 16% faster when performing synchronous IO. I did not attempt to reproduce the original slow download as my internet is not as fast as theirs and  their example would take a theoretical 3 hours to download on my machine. …

Improve concurrent task runner performance

---

src/prefect/logging/loggers.py
tests/test_logging.py

Closes https://github.com/PrefectHQ/prefect/issues/6977
Note changing exception types is generally a breaking change. However, `MissingContextError` inherits from `RuntimeError` so this is backwards compatible.
```python
try:
except MissingContextError:
```

Raise a `MissingContextError` when `get_run_logger` is called outside a run context

---

docs/ui/cloud-getting-started.md

Just a small fix. 😃
After running previous step `prefect deployment build ./basic_flow.py:basic_flow -n test-deployment -q test`, the file got generated is `basic_flow-deployment.yaml` instead of `deployment.yaml`.
BTW, I love Prefect, so neat!

Fix deployment file name in the tutorial

---

.github/workflows/integration-tests.yaml

Requires #6987 
Enables tests for 2.0 and 2.1 but disables checks in some cases where a new client is paired with an old server. New servers are always expected to support old clients, but new clients may attempt to _use_ functionality that an old server does not support. In this case, the server _should_ error to indicate that the requested functionality is not supported.
Closes #6978 
On most versions, we still run all the tests https://github.com/PrefectHQ/prefect/actions/runs/3137761832/jobs/5096309392
For those that explicit note incompatibility, we will skip the old server tests https://github.com/PrefectHQ/prefect/actions/runs/3137780810/jobs/5096352330 …

Disable new client / old server tests for some versions

---

docs/concepts/results.md
mkdocs.yml

In preparation for results configuration documentation, beings to cover the basics of using results!
Preview at https://deploy-preview-6992--prefect-orion.netlify.app/concepts/results/
This is pretty example heavy and could benefit from some highlighted lines.
Part of #6908

Add results concept to documentation

---

src/prefect/orion/api/block_types.py
src/prefect/orion/models/block_registration.py
tests/cli/test_block.py
tests/orion/api/test_block_types.py
tests/orion/models/test_block_registration.py

Ensuring that all system blocks are protected was previously the responsibility of destructive routes. This was happening too often, causing slowdowns in some cases. Here we move block protection to auto-registration so this update should happen much less frequently.

Move block protection to be called with auto-registration

---

RELEASE-NOTES.md

- Warn if user tries to login with API key from Cloud 1 — https://github.com/PrefectHQ/prefect/pull/6958
- Improve concurrent task runner performance — https://github.com/PrefectHQ/prefect/pull/6948
- Raise a `MissingContextError` when `get_run_logger` is called outside a run context — https://github.com/PrefectHQ/prefect/pull/6980
- Adding caching to API configuration lookups to improve performance — https://github.com/PrefectHQ/prefect/pull/6959
- Move `quote` to `prefect.utilities.annotations` — https://github.com/PrefectHQ/prefect/pull/6993
- Add state filters and sort-by to the work-queue, flow and deployment pages — https://github.com/PrefectHQ/prefect/pull/6985
- Fix login to private Docker registries — https://github.com/PrefectHQ/prefect/pull/6889
- Update `Flow.with_options` to …

Cut release notes for 2.4.3

---

RELEASE-NOTES.md
src/prefect/settings.py

Fixes bug noted in #7020 where memoization can cause block schemas to be unregisterable.

Hotfix: Disable block memoization

---

.github/workflows/integration-tests.yaml
RELEASE-NOTES.md
src/prefect/orion/api/block_types.py
src/prefect/settings.py

Follow-up to #7022 disabling block protection entirely. With block protection enabled, as in 2.4.3 and 2.4.4, client and server versions cannot be mismatched unless you are on a version before 2.4.0. Disabling block protection restores the ability for a client and server to have different version tags.

Hotfix: Disable block protection

---

.github/workflows/integration-tests.yaml

Updates compatibility tests following #7026 — it should now include 2.4.5 as well as the relevant 2.4.x versions that we had issues with.

Add 2.4 to the compatibility checks to capture the latest release

---

src/prefect/utilities/asyncutils.py
tests/utilities/test_asyncutils.py

While investigating https://github.com/PrefectHQ/prefect-dask/pull/33 two issues were found with `sync_compatible`.
1. It does not recognize async functions wrapped by sync decorators
2. Async generators are not detected as async by `iscoroutinefn` / `is_async_fn`
These were fixed by:
1. Updating `sync_compatible` to call `is_async_fn`
2. Updating `is_async_fn` to unwrap functions
3. Adding `is_async_gen_fn` to detect async generators
I briefly explored adding support to `sync_compatible` for async generators. I'm not actually sure it's possible. I've done some minor refactoring to allow us to do so in the future, but for now we will not allow it. The error message is clearer now, at least.
```python
async def foo():
yield True
async def bar():
return True
is_async_fn(foo)  # False …
```

Update `sync_compatible` handling of wrapped async functions and generators

---

src/prefect/infrastructure/docker.py
tests/infrastructure/test_docker_container.py

Summary:
- Adds test coverage for streaming logs in `DockerContainer._watch_container`
- removes  extra check of `self.stream_output`

add tests for streaming logs in `_watch_container`

---

src/prefect/filesystems.py
tests/test_filesystems.py

`Deployment().upload_to_storage()` returns the number of files uploaded (obtained from the relevant storage/filesystem `put_directory()`).  It caught me off-guard in that it seems to upload more files than I have in my folder.
I found, for example, for the [test `tree-project`](https://github.com/PrefectHQ/prefect/tree/3a3a22b06b769a247602e195d0bd5644a14a5d25/tests/test-projects/tree-project), it returns `7` files uploaded.
That is because it also counts the folders.
**Important**: This PR changes the behavior of the file counter to only count the files, and not the folders as well.

Change Storage `put_directory` to only count the number of files uploaded

---

docs/concepts/results.md
src/prefect/context.py
src/prefect/engine.py
src/prefect/flows.py
src/prefect/results.py
src/prefect/settings.py
src/prefect/tasks.py
src/prefect/utilities/annotations.py
src/prefect/utilities/pydantic.py
tests/client/test_orion_client.py
tests/results/test_flow_results.py
tests/results/test_task_results.py
tests/test_context.py
tests/test_engine.py
tests/test_logging.py
tests/utilities/test_pydantic.py

Changes:
- Extensive documentation of user experience for configuration of results; see [the preview](https://deploy-preview-7004--prefect-orion.netlify.app/concepts/results/#persisting-results)
- Adds `result_serializer`, `persist_result`, `result_storage` to `Flow` and `Task` interfaces
- Adds `ResultFactory` utility to determine the result settings to be used
- Adds `ResultFactory` to flow and task run contexts
- Insantiates and passes result factories in the engine
This does not:
- Implement result types or creation in the factory
- Replace existing result mechanisms
See documentation for examples. …

Add configuration of results

---

docs/contributing/overview.md

Drops 'git checkout orion' from steps

Fix contributing dev setup instructions

---

src/prefect/blocks/core.py
src/prefect/blocks/notifications.py
src/prefect/logging/loggers.py
tests/blocks/test_core.py
tests/test_logging.py

Disables griffe logs by adding a `disable_logger` context manager.
Also cleans up `disable_run_logger` by using `disable_logger`.
Closes https://github.com/PrefectHQ/prefect/issues/6947.
Closes https://github.com/PrefectHQ/prefect/issues/6960.
Without this PR:
```python
class A(Block):
"""
Without disable logger, this spawns griffe warnings.
Args:
string (str): This should spawn a warning
"""
```
results in:
```
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
Failed to parse annotation from 'Name' node: 'NoneType' object has no attribute 'resolve'
```
With this PR, those logs are suppressed.
- If no issue exists and your change is not a small fix, please …

Suppresses griffe logs

---

src/prefect/infrastructure/process.py
tests/infrastructure/test_process.py

We've had a couple of users ask what an exit code means and why their process is failing, e.g. https://prefect-community.slack.com/archives/CL09KU1K7/p1664981372214759
While you are able to just google exit codes, many users do not understand this and it can be hard to find relevant information. This pull request adds the scaffolding for including a help message on failure for specific exit codes. It uses this to add a help messages for OOM related exit codes. 
> 11:41:11.245 | INFO    | prefect.infrastructure.process - Opening process...
> 11:41:11.245 | DEBUG   | prefect.infrastructure.process - Process running command: noop in /var/folders/q9/1myqgwxn2r3fvkvf6jy3npcm0000gn/T/tmpex6pr53dprefect
> 11:41:11.246 | ERROR   | prefect.infrastructure.process - Process 0 exited with status …

Add OOM warning for `Process` exit code log

---

src/prefect/utilities/asyncutils.py
tests/utilities/test_asyncutils.py

Removes the check for a call pattern like: async -> sync -> sync_compatible
This check was added in https://github.com/PrefectHQ/prefect/pull/6565 which includes a bit more context on the issue it attempted to solve.
This check could only peek at the immediately caller and is not robust to use of decorators and such. It was introduced in an attempt to help prevent improper usage of async code, but it's caused more difficulties than it has fixed and sometimes we actually _want_ to perform this behavior as in #7071.
Separately, we still must address cases where we are incorrectly calling code that expects to be synchronous. For example, whenever we execute a top-level script it _never_ expects to be asynchronous and its not possible for the user to await calls. If we execute such code …

Remove the "sync caller" check from `sync_compatible`

---

docs/concepts/results.md
flows/hello_tasks.py
src/prefect/client/schemas.py
src/prefect/deprecated/data_documents.py
src/prefect/engine.py
src/prefect/futures.py
src/prefect/orion/schemas/states.py
src/prefect/settings.py
src/prefect/states.py
src/prefect/testing/standard_test_suites/task_runners.py
src/prefect/utilities/asyncutils.py
tests/conftest.py
tests/deprecated/test_data_documents.py
tests/results/test_result_fetch.py
tests/test_engine.py
tests/test_flows.py
tests/test_logging.py
tests/test_tasks.py
tests/utilities/test_asyncutils.py

Supersedes https://github.com/PrefectHQ/prefect/pull/6926; includes backwards compatibility.
`State.result()` needs async support for automatic retrieval of results that have been persisted. For our synchronous users, we can change the method to be `async` and just use the `sync_compatible `decorator and they will see no change in behavior but we will be able to make async calls. For our asynchronous users, this would be a breaking change since they would need to await the call. To avoid making a breaking change, we will _not_ make asynchronous calls if the user calls `State.result()` from an async context unless they opt-in. If they opt-in, we will return the coroutine for them to await. If they do not opt-in (or explicitly opt-out), we will display a warning:
> State.result() was called …

Add async support to `State.result()`

---

src/prefect/client/orion.py
tests/client/test_orion_client.py

Adds support to pass idempotency keys through on flow run creation for deployments. The API already supports this.

Add idempotency key support to `OrionClient.create_flow_run_from_deployment`

---

tests/test_deployments.py

@anticorrelator and I have not determined the root cause yet, but this ephemeral API test fails if it has a timeout with either "Event loop closed" errors or some SQLite driver complaints.
Setting the `timeout` to `0` looks like it fixes the flake and the timeout doesn't matter for the test. This also removes an unneeded CLI call from the deployment fixture.

Fix flaky deployment run test

---

src/prefect/deployments.py
tests/test_deployments.py

#5968
Allow setting custom flow run names when creating a flow run with `run_deployment`

Expose setting custom flow run names

---

orion-ui/package-lock.json
orion-ui/package.json
orion-ui/src/pages/FlowRuns.vue

This PR adds the ability to perform multiple delete on flow runs on flowRuns, Flow, Deployment, and WorkQueue pages

Add multi-delete to flowRuns, Flow, Deployment and WorkQueue pages

---

orion-ui/src/pages/WorkQueue.vue

**Problem:** when we exceed the concurrency limit, in the "Upcoming runs" tab we see ‘No upcoming runs’, and it can be confusing. The reason there are no upcoming runs is that the number of runs in the `Running` or `Pending` state is equal to the concurrency limit and is blocking the queue of runs. 
**Solution:** add a button to the "Upcoming runs" tab that will be displayed only when the queue line I clogged by `Running` or `Pending`, and that when clicked will take us to the "Runs" tab with `Running` or `Pending` state filter applied

Add 'Show Active Runs' button to WorkQueue page

---

.github/workflows/stale.yml

Adds `status:accepted` to the Stale action's exempt label list.

Exempt `status:accepted` labels from being marked as stale

---

tests/test_serializers.py
tests/test_tasks.py

This PR adds test coverage for bytes serialization for our `serializers` module and test coverage for correct cache utilization for Prefect blocks that have bytes attributes. 
The tests include simple and complex byte strings, multiple encodings, and objects with byte attributes. 
The tests were originally written as part of an investigation into issue with bytes using the `JSONSerializer` mentioned in pull request https://github.com/PrefectHQ/prefect/pull/7048 , but the issue was not able to be reproduced. 

Add test coverage for bytes serialization and caching

---

src/prefect/client/orion.py
tests/client/test_orion_client.py
tests/orion/models/test_flow_runs.py

The `create_flow_run_from_deployment` function was missing some documentation on supported functionality, as described in https://github.com/PrefectHQ/prefect/issues/5968
It already accepts a custom flow run name, so here we:
- document the params `name`, `tags`, and `idempotency_key`
- Add some more tests using different idempotency keys
The tag behavior is verified at the API's create_flow_run_from_deployment() function.
~(I couldn't figure out how to generate the API reference from docstrings)~
Pasted from Deploy Preview
- but possibly that Github issue remains open for other discussions
- Documents recent idempotency_key addition https://github.com/PrefectHQ/prefect/pull/7074

Improve create_flow_run_from_deployment docs, tests on idempotency_key

---

.github/workflows/integration-tests.yaml
docs/concepts/results.md
src/prefect/agent.py
src/prefect/client/orion.py
src/prefect/client/schemas.py
src/prefect/deployments.py
src/prefect/engine.py
src/prefect/exceptions.py
src/prefect/flows.py
src/prefect/futures.py
src/prefect/orion/schemas/states.py
src/prefect/results.py
src/prefect/serializers.py
src/prefect/states.py
src/prefect/task_runners.py
src/prefect/utilities/pydantic.py
tests/cli/test_flow_run.py
tests/client/test_orion_client.py
tests/orion/database/test_queries.py
tests/results/test_result_factory.py
tests/test_agent.py
tests/test_engine.py
tests/test_flows.py
tests/test_states.py

Hooks everything up! Everywhere in the engine where we were creating `DataDocument` types, we are now creating  new result types. 
The largest changes here are dealing with cases where we previously would pickle exceptions and attach them to states. We do this all over the place — sometimes where we do not have access to the user's result settings. To support those cases, I've refactored failed/crashed results to allow generation of an exception from a string. This means we do not need to actually serialize an exception to report a failure, e.g. when an agent fails to submit a flow run.
Unlike the other pull requests in #6908 this one is a little sprawling — at some point everything's got to switch over and little edge cases need to be addressed. I think this makes this a good candidate …

Update engine to use new results

---

src/prefect/client/orion.py

Provides a more detailed breakdown of the exceptions thrown by `read_work_queue_by_name`

docs: provide a more detailed exception section

---

src/prefect/exceptions.py
src/prefect/results.py
src/prefect/states.py
src/prefect/testing/utilities.py
tests/conftest.py
tests/results/test_flow_results.py
tests/results/test_result_factory.py
tests/results/test_task_results.py
tests/test_flows.py

- Abstract `PersistedResult._read_blob` for testing persisted results
- Consolidate result testing utilities into `prefect.testing.utilities`
- Add pytest assertion rewrites for testing utilities
- Add flow and test result coverage
- Add `MissingResult` exception instead of `ValueError` when data is null

Additional test coverage for results

---

src/prefect/__init__.py
src/prefect/engine.py
src/prefect/utilities/annotations.py
tests/test_flows.py
tests/test_tasks.py

Closes https://github.com/PrefectHQ/prefect/issues/7098
```python
@task
def fails():
raise ValueError("Fail task!")
@task
def bar(y):
return y
@flow
f = fails.submit()
b = bar.submit(allow_failure(f))
assert isinstance(b.result(), ValueError)
b = bar.submit(1, wait_for=[allow_failure(f)])
assert b.result() == 1
```

Add `allow_failure` annotation to allow failed runs to be passed downstream

---

docs/concepts/results.md
docs/concepts/tasks.md
src/prefect/context.py
src/prefect/engine.py
tests/test_context.py
tests/test_engine.py

Previously this was left untouched even though it no longer used (since #7094), now it has been purged.

Remove old result handling from the engine and documentation

---

src/prefect/orion/api/block_documents.py
src/prefect/orion/models/block_documents.py

On PostgreSQL, relying on the `IntegrityError` to indicate a constraint violation does work, but leads to a lot of noise in the PostgreSQL logs.  Also, tracing libraries see these spans as errors, even though they are normal ops.
This is a backported fix from Prefect Cloud: PrefectHQ/nebula#2165

Proactively look for duplicate blocks instead of relying on `IntegrityError`.

---

src/prefect/orion/api/logs.py
src/prefect/orion/models/logs.py

When saving very large numbers of logs, it's possible to overwhelm a PostgreSQL instance by having a single extremely large transaction open.  Instead, we should commit as we go.
Part of PrefectHQ/nebula#2192

Save log batches in individual transactions.

---

src/prefect/client/orion.py
src/prefect/orion/api/run_history.py
src/prefect/orion/api/ui/flow_runs.py
src/prefect/orion/database/migrations/versions/postgresql/2022_10_12_102048_22b7cb02e593_add_state_timestamp.py
src/prefect/orion/database/migrations/versions/sqlite/2022_10_12_102048_22b7cb02e593_add_state_timestamp.py
src/prefect/orion/database/orm_models.py
src/prefect/orion/orchestration/global_policy.py
tests/orion/api/test_run_history.py
tests/orion/orchestration/test_global_policy.py

This PR adds `state_timestamp` to the `flow_run` and `task_run` tables. This denormalization will speed up run history queries, which now do not need to join to the `flow_run_state` and `task_run_state` tables.
See https://github.com/PrefectHQ/nebula/issues/2110
n/a

History query refactor

---

src/prefect/settings.py

Following https://github.com/PrefectHQ/prefect/pull/7067 the settings added in #6908 have improper docstrings.

Update results settings to match new docstring format

---

requirements-dev.txt

We require >7 or ` AttributeError: module 'pytest' has no attribute 'Config'` will be raised

Update pytest requirement

---

src/prefect/cli/deployment.py
src/prefect/orion/services/flow_run_notifications.py

Failure notification URL currently has a format:
https://app.prefect.cloud/account/c5276cbb-62a2-4501-b64a-74d3d900d781/workspace/aaeffa0e-13fa-460e-a1f9-79b53c05ab36/flow-run/bc43a65c-b03b-4aca-9724-9ce362a40959
It should be:
https://app.prefect.cloud/account/c5276cbb-62a2-4501-b64a-74d3d900d781/workspace/aaeffa0e-13fa-460e-a1f9-79b53c05ab36/flow-runs/flow-run/bc43a65c-b03b-4aca-9724-9ce362a40959
The `flow-runs/` is missing. The same is true for URL added with this PR https://github.com/PrefectHQ/prefect/pull/7018 

Fix broken flow run URLs for notifications and creating runs from CLI

---

docs/concepts/schedules.md

I noticed that the page link had a typo, small fix to correctly link to the rrule section of the scheduling page in the docs.
See incorrect link here in the docs https://docs.prefect.io/concepts/schedules/?h=sched#schedule-types

Fix RRule link in Schedules documentation

---

src/prefect/results.py
tests/results/test_flow_results.py
tests/results/test_task_results.py

Pydantic was incorrectly parsing some user return values as the `BaseResult` type (which should never be insantiated) causing the incorrect type to be returned when `result()` is called. Users can workaround this before release by enabling result persistence. Luckily, this was easy to fix by making `BaseResult` uninstantiable.
```python
@task()
def my_task():
return []
@flow()
def my_flow():
result = my_task()
print(result)
```
In 2.5 `results == []`
In 2.6 `results is None`
With fix `results == []`
This applies to `{}` and to flows as well.

Fix bug where return values could be incorrectly parsed as `BaseResult`

---

docs/concepts/results.md
src/prefect/serializers.py
tests/results/test_flow_results.py
tests/results/test_task_results.py
tests/test_serializers.py

Adds ` CompressedSerializer` similar to the one in v1 which lets you use arbitrary (defaults to lzma) compression libraries to compress the bytes returned by an arbitrary serializer.
[Documentation preview](https://deploy-preview-7164--prefect-orion.netlify.app/concepts/results/#compressing-results)
```python
@flow(result_serializer="compressed/json")
...
@flow(result_serializer="compressed/pickle")
...
@flow(result_serializer=CompressedSerializer(compressionlib="zlib", serializer="pickle"))
...
```

Add `CompressedSerializer` for compression of other result serializers

---

src/prefect/orion/orchestration/rules.py
tests/orion/orchestration/test_rules.py

This PR adds logic to guard against calling `after_transition` if orchestration encountered an error.
This applies in cases where, for example, we could encountered in error trying to secure concurrency slots in `before_transition` because of a connectivity issue with the database. Often exceptions of this sort will impact our ability to communicate with the database further, resulting in mishandled errors.
Closes https://github.com/PrefectHQ/nebula/issues/1041

Guard calling after_transition when exception encountered

---

src/prefect/client/orion.py
src/prefect/orion/api/deployments.py
src/prefect/orion/database/migrations/versions/postgresql/2022_10_14_172612_ad4b1b4d1e9d_index_deployment_created.py
src/prefect/orion/database/migrations/versions/sqlite/2022_10_14_172612_ad4b1b4d1e9d_index_deployment_created.py
src/prefect/orion/database/orm_models.py
src/prefect/orion/models/deployments.py
src/prefect/orion/schemas/sorting.py
tests/orion/api/test_deployments.py

Add DeploymentSort to `/deployments/filter` to allow sorting deployments in the same way that flows are currently sorted.

Allow deployments to be sorted in the api

---

orion-ui/src/pages/FlowRun.vue

This PR removes a space between sub and flow per documentation standards
> Task run, flow run, and subflow are the current usage in the docs

UI: fix naming of subflow runs tab on flow run page

---

src/prefect/orion/schemas/schedules.py
tests/orion/schemas/test_schedules.py

`RRuleSchedule` cannot currently handle compound RRules, `dateutil`'s parser will sometimes return a complex `rruleset` object instead of an `rrule` when parsing an RRule string. I'm adding handling for `rrulesets`.
I could really use someone with some experience with working with schedules to give this a careful once-over to make sure I haven't missed/changed anything critical. I tried to add some tests that ensure that we can properly roundtrip a schedule using the `from_rrule` and `to_rrule` methods, but because of all the inconsistencies in naming timezones across the various timezone parsing libraries, this has proven to be difficult.

Improve rrule backend parsing

---

src/prefect/orion/schemas/states.py
src/prefect/states.py
tests/results/test_flow_results.py

Fixes a backwards compatibility edge-case where an `isinstance` check in `return_value_to_state` did not include server-side state schemas.
Did not work prior to change, flow ended in `Completed` state and treated returned value as a result:
```python
from prefect.orion.schemas.states import Cancelled
@flow
def foo():
return Cancelled()
```
The above works now and displays deprecation warnings.
Did work prior to change:
```python
from prefect.states import Cancelled
@flow
def foo():
return Cancelled()
```

Add backwards compatibility for return of server-states from flows and tasks

---

docs/concepts/results.md
src/prefect/engine.py
src/prefect/flows.py
src/prefect/results.py
src/prefect/tasks.py
tests/results/test_flow_results.py
tests/results/test_persisted_result.py
tests/results/test_result_factory.py
tests/results/test_task_results.py
tests/test_engine.py

Adds a `cache_result_in_memory` option to flows and tasks to drop a result from memory instead of holding it. You _can_ use this while disabling persistence which is the equivalent of saying "I shall not use this result downstream". By default, using it will enable persistence.
See the examples in the [documentation](https://deploy-preview-7174--prefect-orion.netlify.app/concepts/results/#caching-of-results-in-memory)

Add option to drop task or flow return values from memory

---

src/prefect/tasks.py
tests/test_flows.py
tests/test_tasks.py

This one has bitten me once again. We'll need to be careful about test coverage for this in the future.
The bug:
```python
@task
def foo():
pass
bar = foo.with_options()
bar = foo.with_options(cache_result_in_memory=True)
```
After this fix, `with_options` works as intended.

Fix handling of `cache_result_in_memory` in `Task.with_options`

---

.github/workflows/integration-tests.yaml
flows/flow_results.py
flows/task_results.py
scripts/run-integration-flows.py

The client tests are being skipped e.g. https://github.com/PrefectHQ/prefect/actions/runs/3268773790/jobs/5375567361
This led to a bad release in 2.6.2 and was definitely my fault as I added it incorrectly. I want to generate the matrix dynamically at some point, perhaps that point is soon as it would guard against this.
https://github.com/PrefectHQ/prefect/actions/runs/3276226541/jobs/5392036236

Fixes integration tests for 2.6 to include the current client

---

orion-ui/src/pages/Deployment.vue

renames "overview" tab to more limited "description"
uses simpler `useTabs` utility to control visibility
on small screen, details still gets added to tabset but now in first position (like it is in nebula)
closes https://github.com/PrefectHQ/orion-design/issues/450
after:

UI: updated deployment tabs

---

src/prefect/deployments.py
tests/test_deployments.py

I know #6932 is still waiting on product feedback but I went ahead and added the feature anyway. Please accept/reject according to the product team feedback.
Adds `load_existing` to `Deployment.build_from_flow`, toggling the load existing settings behavior
Fixes #6932 
```py
Deployment.build_from_flow(
flow,
name=f"{deployment_name}-{infrastructure}",
path="some/path"
).apply()
Deployment.build_from_flow(
flow,
name=f"{deployment_name}-{infrastructure}",
load_existing=False,
).apply()
```

Add toggle to load existing deployment values

---

docs/concepts/results.md
src/prefect/results.py
src/prefect/settings.py
tests/results/test_result_factory.py

Adds a global setting to change the default value for persistence e.g. when opt-in/out is not provided and a feature is not used.
Simplified version of #7161 
To enable persistence of all flow, task, and subflow results by default:
```
$ prefect config set PREFECT_RESULTS_PERSIST_BY_DEFAULT=true
```

Add `PREFECT_RESULTS_PERSIST_BY_DEFAULT` to globally toggle the result persistence default

---

src/prefect/tasks.py
tests/test_tasks.py

Fixes #7241 
```py
def test_task_run_from_callable_object(self):
class Foo:
message = "hello"
def __call__(self, prefix: str, suffix: str) -> Any:
return prefix + self.message + suffix
obj = Foo()
foo = Task(fn=obj)
@flow
def bar():
return foo("a", suffix="b")
assert bar() == "ahellob"
```

Handle __name__ for callable objects

---

orion-ui/vite.config.ts

vite.config.ts had some linting warnings and was also still referencing miter-design which we haven't used in a long time

UI: Clean up the vite config

---

src/prefect/settings.py
tests/conftest.py

Will help with issues like #7190
Increases the default database query timeout from 1s -> 5s
Keeps a 1s timeout during tests so we can keep an eye on slow queries.
- ~[ ] This pull request includes tests or only affects documentation.~

Increase default database timeout to 5 seconds

---

src/prefect/infrastructure/kubernetes.py
tests/blocks/checksums.json
tests/infrastructure/test_kubernetes_job.py

Closes #7245
Only sets a default value for `image` and `namespace` if they are not provided in the given manifest. This allows users to provide a manifest that contains these preset.
Given `job.yaml`:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
generateName: prefect-job-d41d8cd98f00b204e9800998ecf8427e
labels: {}
namespace: my-namespace
spec:
template:
spec:
completions: 1
containers:
- env: []
image: my-image
name: prefect-job
parallelism: 1
restartPolicy: Never
```
The image and namespace should be respected by this block:
```python
job = KubernetesJob(job=KubernetesJob.from_file("job.yaml"))
print(job.preview())
```
However, we overwrite `namespace` and `image` with Prefect's default values. This pull request updates this to respect the values in the job manifest if they exist.
- …

Allow image/namespace fields to be loaded from Kubernetes job manifest

---

.github/workflows/integration-tests.yaml

`set-output` used in the integration-test github action is deprecated and should be replaced by piping to `$GITHUB_OUTPUT`
See: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
From 01.06.2023 all github actions still using set-output will fail.

Replace deprecated set-output command in the integration-test

---

src/prefect/cli/deployment.py
tests/cli/test_deployment_cli.py

closes #7202
Adds timezone handling to `prefect deployment build` to bring its behavior more in line with `prefect deployment set-schedule`. Also improves handling of anchor dates for interval schedules and explicit timezone overrides for RRule schedules.

Add timezone param to deployment build

---

src/prefect/agent.py
src/prefect/cli/agent.py
src/prefect/client/orion.py
tests/test_agent.py

Fixes #7221 
```
prefect agent start -m "q1-" -m "q2-"
```

Add support for multiple work queue prefixes

---

docs/getting-started/installation.md
setup.cfg
src/prefect/client/orion.py
tests/client/test_orion_client.py

We were overriding the `transport` on our Orion connections in order to set the number of retries.  When doing this, we would need to include all of the logic for how to discover if the user has proxies configured in their environment. Instead, just set the retries _after_ the fact.
Fixes PrefectHQ/nebula#2356
Fixes #7204
See the background thread in the [Prefect Community Slack](https://linen.prefect.io/t/2930204/Hi-I-m-having-some-issues-with-accessing-prefect-2-0-cloud-f) for more information.

Restores proxy-awareness for the Orion client for remote Orion servers.

---

src/prefect/infrastructure/kubernetes.py
tests/infrastructure/test_kubernetes_job.py

Currently, K8s Jobs have names that look like `f"{job_object.name}{alnum5}"` or `f"{flow_run.name}{alnum5}"`, where `alnum5` is generated by K8s.
I believe this looks ugly and the common approach is to have `Job.metadata.generateName` end with a dash ([1](https://github.com/kubernetes/kubernetes/issues/44501), [2](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/)).
This change makes Job names look nicer (e.g. ` f"{job_object.name}-{alnum5}"`).
Before: ![generateName_before](https://i.imgur.com/elXw7jj.png)
After: ![generateName_after](https://i.imgur.com/O7JFR3j.png)

Append "-" to non-random part of K8s job name

---

orion-ui/tests/notifications.spec.ts

The "can delete notification" integration test has been flakey lately. I tried fixing it but don't have enough time to figure it out. So I'm removing it since a flakey test isn't a useful test.

UI: Remove flakey integration test

---

orion-ui/package-lock.json
orion-ui/package.json

[This PR](https://github.com/PrefectHQ/orion-design/pull/730) introduces an overload to all date-fns functions that make them aware of users timezone preference. Once that is merged, this PR removes `date-fns` in favor of these orion-design methods

UI: removed date-fns

---

.github/workflows/republish-images.yaml

To fix the failed release at https://github.com/PrefectHQ/prefect/actions/runs/3339913815/jobs/5529508862 by running the publish workflow with the fix in #7355

Add workflow to republish images for 2.6.5

---

src/prefect/utilities/processutils.py
tests/utilities/test_processutils.py

This updates `processutils.open_process` to check that the command being passed to it is a list and raise an error if it is not. This is important because we've passed strings to it on a couple occasions, which works on a unix machine, but breaks on a windows machine. This should hopefully save us a few compatibility bugs down the line. 
Related PR: https://github.com/PrefectHQ/prefect/pull/7372
The PR also moves the tests for `run_process` under their own class.
```python
async def open_process(command: List[str], **kwargs):
...
if not isinstance(command, list):
raise TypeError(
"The command passed to open process must be a list. You passed the command"
f"'{command}', which is type '{type(command)}'."
)
...
``` …

Discussion: Check that command is a list when passed to `open_process`

---

src/prefect/exceptions.py
src/prefect/orion/orchestration/core_policy.py
tests/orion/orchestration/test_core_policy.py

If a flow run is deleted while its tasks are being orchestrated, we should raise more informative errors.

Handle missing flow runs

---

docs/concepts/task-runners.md

This is a very simple merge request that resolves a typo in the concepts/task-runner docs which confused me when I was trying to follow the docs.
The code example shown used to be:
```python
@task
def my_task(name):
return "I'm a task!"
@flow
def my_flow():
future = my_task()
result = future.result(raise_on_failure=False)
if future.get_state().is_failed():
...
else:
...
```
What confused me is the call to `my_task`:
- `my_task.__call__` expects a `name` argument but we don't pass it anything 
- invoking `my_task.__call__` should not return a future but instead should execute the underlying python function. 

docs: fix typo in concepts/task-runner.md document

---

src/prefect/cli/work_queue.py
src/prefect/client/orion.py
src/prefect/orion/api/work_queues.py
src/prefect/orion/database/migrations/MIGRATION-NOTES.md
src/prefect/orion/database/migrations/versions/postgresql/2022_10_31_161719_41e5ed9e1034_.py
src/prefect/orion/models/work_queues.py
src/prefect/orion/schemas/filters.py
tests/client/test_orion_client.py
tests/orion/api/test_work_queues.py
tests/orion/models/test_work_queues.py

Adds support to the `work_queues/filter` route in the Orion API to filter Work Queues based on the name. The filter can perform `startswith_` queries that enable finding work queues with a matching prefix, as well as the standard `all_` query.
Closes #7205 

Allow filtering of Work Queues via the API based on name prefix

---

src/prefect/orion/services/scheduler.py
src/prefect/settings.py
tests/orion/api/test_deployments.py
tests/orion/models/test_deployments.py
tests/orion/services/test_scheduler.py

This PR makes a few changes to reduce the burden of scheduling flow runs on the orion database:
- Schedule the next 20 runs instead of 100 by default
- COMMIT scheduled runs in batches instead of batching multiple INSERTs in a single COMMIT
Part of https://github.com/PrefectHQ/nebula/issues/2503

Scheduler stability fixes
