src/prefect/deployments.py

Adds missing import statement for `ObjectAlreadyExists` exception class to the `prefect.deployments` module. Closes #7359 .

Add import for ObjectAlreadyExists exception in deployments module

---

.pre-commit-config.yaml
src/prefect/deployments.py

Bumps pre-commit tools versions. Fixes pre-commit failures on `main`.
See `./scripts/precommit-verisons.py` for updating verisons outside precommit.

Update pre-commit tools

---

requirements.txt

Removes aiohttp from requirements

---

src/prefect/utilities/collections.py
tests/utilities/test_collections.py

`visit_collection` treats all iterators as lists which does not work for `io.BaseIO` types, coercing them to an empty list. This means users could not pass IO objects between tasks. This pull request does not attempt to traverse IO types, making use of (and extending) our `isiterator` utility.
```python
import io
@task
def string_to_io():
return io.StringIO("hello prefect")
@task
def consume(string_io):
print(type(string_io))
return string_io.read()
@flow
def test():
str_io = string_to_io()
r = consume(str_io)
print(r)
test()
```

Fix `visit_collection` handling of IO objects

---

src/prefect/orion/database/migrations/versions/postgresql/2022_11_05_180555_54c1876c68ae_add_index_for_scheduled_deployments.py
src/prefect/orion/database/migrations/versions/sqlite/2022_11_05_180619_a0284438370e_add_index_for_scheduled_deployments.py
src/prefect/orion/models/deployments.py
src/prefect/orion/services/scheduler.py
tests/orion/services/test_scheduler.py

Follow up to #7433 (and builds on it).
If #7433 is merged, the scheduler will begin scheduling the _smallest_ number of runs that satisfy certain minimum criteria (a minimum number of runs and a minimum duration to schedule into the future). This has the major effect of reducing the number of runs the scheduler attempts to insert, which is important because the scheduler runs on a relatively tight loop and relies on idempotency to allow it to eagerly attempt to create redundant runs.
However, the fact that the scheduler is constantly trying to create runs that already exist is, itself, a larger source of potential performance problems. Even if every single deployment had just been scheduled and nothing had changed, on its next loop the scheduler will revisit every single deployment and …

Improve scheduler selectivity for performance

---

src/prefect/cli/agent.py
src/prefect/testing/cli.py
src/prefect/utilities/services.py
tests/cli/test_agent.py

The agent CLI is woefully untested and this is particularly useful for testing. I can see other cases where a user would want to run a single iteration of the agent as well, like a lambda.
Required for testing in #7498
```
❯ prefect agent start --run-once -q test
Starting v2.6.7+2.gb79491988 agent with ephemeral API...
___ ___ ___ ___ ___ ___ _____     _   ___ ___ _  _ _____
| _ \ _ \ __| __| __/ __|_   _|   /_\ / __| __| \| |_   _|
|  _/   / _|| _|| _| (__  | |    / _ \ (_ | _|| .` | | |
|_| |_|_\___|_| |___\___| |_|   /_/ \_\___|___|_|\_| |_|
Agent started! Looking for work from queue(s): test...
Agent stopped!
```

Add `--run-once` to `prefect agent start` CLI

---

docs/concepts/work-queues.md
requirements.txt
src/prefect/cli/agent.py
src/prefect/testing/utilities.py
src/prefect/utilities/compat.py
tests/cli/test_agent.py

Adds `--prefetch-seconds` to the CLI, this was previously available only in the `OrionAgent` interface or by changing a setting.
The [documentation](https://deploy-preview-7498--prefect-orion.netlify.app/concepts/work-queues/#configuring-prefetch) should be a good overview of the use-case.
Includes a `prefect.testing.utilities.MagicMock` backport for Python 3.7 with async method support to resolve [3.7-specific CI failures](https://github.com/PrefectHQ/prefect/actions/runs/3447020891/jobs/5752588235).
Includes a minimum typer version bump to a fix a bug where lists were parsed as tuples.
`prefect agent start --prefetch-seconds 60 -q test`

Expose `prefetch-seconds` in `prefect agent` CLI

---

docs/tutorials/docker.md

This PR just fixes a small typo in the docker tutorial in the docs

Fix typo in Docker tutorial

---

docs/concepts/blocks.md
netlify.toml

Reorganizing the collections catalog broke a previous URL to the collections. Fixing link in Blocks docs and adding a redirect to handle any user bookmarks.

Fix linking to Collections catalog

---

src/prefect/context.py

Add a docstring to override the imported pydantic docstring. Formatting of the imported docstring was not interpreted correctly by mkdocstrings.
[Preview](https://deploy-preview-7539--prefect-orion.netlify.app/api-ref/prefect/context/#prefect.context.ContextModel.copy)

Provide docstring for ContextModel.copy

---

orion-ui/package-lock.json
orion-ui/package.json
orion-ui/src/pages/FlowRun.vue
orion-ui/src/pages/TaskRun.vue

The issue came from this https://github.com/PrefectHQ/orion-design/pull/786 and here we switch WorkspaceFlowRun and WorkspaceTaskRun to pass ids as a prop instead full object to be able to refresh subscriptions on after change

Update props on TaskRun and FlowRun pages

---

docs/overrides/partials/tabs.html
docs/stylesheets/extra.css

Fixes positioning of "Go to Prefect Cloud" link in docs header.
This was floating right properly, but somewhere along the way it moved back to the left. I think this is a CSS difference between Material for Mkdocs and Insiders. 
Anyway minor adjustment to get it right-justified with Insiders builds again.

Fix positioning of Prefect Cloud link

---

.github/workflows/stale.yml

This makes several small changes to the stale action:
- Disables PR stale-ing. When debug / analytics were turned on a lot of operations were spent (over half) checking PRs and given the relatively small set of PRs it's likely not a great use of those operations.
- Sets `ascending` to `true`. If I'm reading the docs correctly this should result in in looking at old issues first.
- Doubles the number of operations it can perform, default is 30, this gives it 60.
- Updates messaging.

Make stale action more likely to close issues

---

src/prefect/logging/handlers.py
src/prefect/testing/cli.py
tests/cli/test_block.py
tests/test_logging.py

The logging handler added in #6101 did not include the proper formatting and consequently dropped tracebacks from `logger.exception(...)`. This pull request:
- Fixes the bug, restoring tracebacks
- Disables word-wrapping/cropping at the same time because log output should not be wrapped
- Restores usage of stderr for logs instead of stdout

Fix `PrefectConsoleHandler` bug where log tracebacks were excluded

---

src/prefect/__init__.py
src/prefect/logging/configuration.py
src/prefect/logging/handlers.py
tests/conftest.py
tests/test_engine.py
tests/test_logging.py

Closes #5850, https://github.com/PrefectHQ/prefect-dask/issues/10, https://github.com/PrefectHQ/prefect-dask/issues/40
Related #6872 
Previously, `setup_logging` was deferred until the a flow or task run started. A global variable was used to detect if it had been called already; if so, we'd exit so subsequent calls had no affect. Now, subsequent calls will trigger an "incremental" update. See the [standard library logging documentation](https://docs.python.org/3/library/logging.config.html#incremental-configuration) for details on incremental configuration.
This allows us to call `setup_logging` on import of Prefect. This is very convenient as there are other edge-cases where we want logging to be configured:
- CLI commands
- Uvicorn starting the server
- Dask workers
- Tests
We had to …

Update logging setup to support incremental configuration

---

requirements.txt
src/prefect/cli/cloud.py
src/prefect/cli/root.py
src/prefect/client/cloud.py
src/prefect/client/schemas.py
src/prefect/settings.py
src/prefect/utilities/compat.py
tests/cli/test_cloud.py
tests/cli/test_profile.py

Merges into #7332. Requires a UI `/authorize` route. Authored with @znicholasbrown.
Adds login via the web browser to `prefect cloud login`, allowing you to login without creating an API key first.
This is a result of the UI workshop during TDP in which we were attempting to improve the user experience during onboarding. The user is prompted to create a workspace, then prompted to use the workspace from the CLI before they have logged in with an API key. Instead of adding more steps to the UI onboarding experience, we can improve the user experience by making it very easy to authenticate the CLI.
This works by spinning up a little API server from the CLI then opening the user's web browser to a dedicated UI page. When the user authorizes the login, the browser will send a new API key to …

Add login with a browser to `prefect cloud login`

---

orion-ui/src/styles/style.css

This PR removes the inter font import. This font is already bundled in an upstream dependency and should be applied accordingly. 
Closes: https://github.com/PrefectHQ/prefect/issues/7582

Bugfix: Remove inter import blocking UI loads in airgapped environments

---

src/prefect/exceptions.py
src/prefect/orion/orchestration/core_policy.py
tests/orion/api/test_task_runs.py
tests/orion/orchestration/test_core_policy.py

If a flow run is not found when orchestrating a task run, ensure we return a 404. Previously, `MissingFlowRunError` was unhandled, resulting in a 500 error.
Closes https://github.com/PrefectHQ/nebula/issues/2685
```
async def test_set_task_run_state_returns_404_on_missing_flow_run(
self, task_run, client, session
):
await models.flow_runs.delete_flow_run(
session=session, flow_run_id=task_run.flow_run_id
)
await session.commit()
response = await client.post(
f"/task_runs/{task_run.id}/set_state",
json=dict(state=dict(type="RUNNING", name="Test State")),
)
assert response.status_code == status.HTTP_404_NOT_FOUND
```

Return 404 on missing flow run

---

src/prefect/logging/formatters.py
src/prefect/logging/logging.yml
tests/conftest.py
tests/test_logging.py

Previously, flow run and task run loggers required their own formatters and did not propagate to the `prefect` logger. We did this to allow customization of formatting for flow and task run logs. However, this makes it difficult to change the behavior of Prefect's loggers since you need to adjust multiple handlers. We can accomplish this same feature with a single formatter that has support for flow and task run formats.
Now, since there are not separate formatters for flow and task runs, you can change the format with a single setting e.g. to use JSON logging
```
PREFECT_LOGGING_HANDLERS_CONSOLE_FORMATTER="json" python example.py
```

Add `PrefectFormatter` to reduce logging configuration duplication

---

src/prefect/orion/services/flow_run_notifications.py

Curious for comment on this change -- currently we're using a single session to load and send every queued notification. This means that if anything happens to the session (due to misconfigured block or something), all subsequent notifications won't get sent because the session is rolled back. Notifications themselves do *not* use the session to send, so it's only the _loading_ of the notifications that presents a surface area for errors. This PR avoids this potentially long-lived session and opens a new session for each notification.

Use new session to send each notification

---

RELEASE-NOTES.md
src/prefect/cli/agent.py
src/prefect/utilities/math.py
src/prefect/utilities/services.py
tests/utilities/test_math.py
tests/utilities/test_services.py

Jitters agent loop intervals. This change modifies the agent loop sleep time so it is drawn from a clamped Poisson distribution. The average sleep time is approximately the same as it was before, only now it's allowed to vary within 30% of the old value (5 seconds). In setups that use many agents, it's possible for agents to enter race conditions that cascade into correlated errors. By adding jitter to the agent loops, multi-agent setups can be more distributed in time, guarding against these failure modes.

Add jitter to the agent core loop

---

src/prefect/engine.py
tests/test_flows.py

Closes https://github.com/PrefectHQ/prefect/issues/7494
cc @zhen0 
Sends final state logs to the API. Previously, these were logged locally but not sent to the API. Some logs will still not be sent to the API; for example, logs indicating that the API rejected a proposed state.

Include final state logs in logs sent to API

---

src/prefect/engine.py
src/prefect/flows.py
src/prefect/settings.py
tests/test_engine.py
tests/test_flows.py
tests/test_log_prints.py

this PR updates `create_and_begin_flow_run` to use `should_log_prints` in a similar way to how its currently used by `begin_flow_run`, where the result of `should_log_prints` decides:
- whether to enter `patch_print` before calling `orchestrate_flow_run`
-  what `log_prints` setting should be passed to `orchestrate_flow_run`
and adds test coverage checking task and subflow (and subsubflow) inheritance of this setting, and checking the ability for tasks or subflows to opt out of their parent's `log_prints` setting by defining their own `log_prints` setting

use `should_log_prints` in `create_and_begin_subflow_run` and add `test_log_prints.py`

---

src/prefect/cli/cloud.py
tests/cli/test_cloud.py

If the `PREFECT_API_URL` does not contain a valid workspace but the `PREFECT_API_KEY` is set during `prefect cloud login` re-authentication will fail during display of the current workspace.
Encountered in https://prefecthq.slack.com/archives/C029PBS5JVB/p1669233780065449

Prompt workspace selection if API key is set but API URL is not set

---

benches/__main__.py

We were not reraising the subprocess exit code so CI always succeeded unless it deadlocked.

Fix benchmarks exit codes

---

src/prefect/states.py
tests/test_states.py

While looking at how we're handling `Cancelled` states returned by tasks I noticed that there was a bug in `StateGroup` that caused `all_final` to return the opposite of what it should. This fixes that up and adds tests for the class as a whole.
Closes #7677

Fix bug in `StateGroup` that caused `all_final` to be wrong

---

src/prefect/engine.py
tests/test_engine.py

Fixes a bug in the pausing code that will result in a too-long initial poll when the timeout is large.

Bugfix: pauses will not sleep longer than the polling interval

---

src/prefect/states.py
tests/test_flows.py
tests/test_states.py

In issue #6789 it was called out that returning a `Cancelled` state from a task resulted in an exception. This updates the handling in `return_value_to_state` to set the final state of a flow to `Cancelled` if any subflow/task returns a `Cancelled` state. Examples:
This shows a flow that will run a task 10 times and get 5 Cancelled states and 5 Completed states. The final state of the flow will be `Cancelled`.
```python
from prefect.orion.schemas.states import Cancelled
@task
def process(n):
if n % 2 == 0:
return Cancelled(message="I want to skip this")
else:
return n
@flow
def my_flow():
for n in range(10):
process(n)
```
Which has the final state of `Cancelled('5/10 states cancelled.')`
The same is true about subflows:
```python
from prefect import flow, …
```

Make the final state of a flow `Cancelled` when any task finishes in a `Cancelled` state

---

docs/concepts/logs.md
src/prefect/context.py
src/prefect/engine.py
src/prefect/flows.py
src/prefect/logging/loggers.py
src/prefect/settings.py
src/prefect/tasks.py
tests/test_engine.py
tests/test_flows.py
tests/test_log_prints.py
tests/test_logging.py

Addresses the much requested `log_stdout` feature from v1 in v2 by adding a `log_prints` option. It is very hard for us to log standard output from _within_ the run as we have no way to tell where the bytes are coming from (i.e. you cannot disable capturing per task or flow). We can, however, patch the builtin `print` method, allowing us to identify the flow or task run the message comes from. 
This pull request introduces temporary patching of `print` to accomplish logging of prints from within tasks or flows. This will also apply to any functions within the scope of a task or a flow e.g. if they call into another library. If a flow or task run context is not present, we will just `print` as normal.
There are options at the flow, task, and settings level. Defaults for children (subflows …

Add `log_prints` option to redirect print to logs

---

orion-ui/package-lock.json
orion-ui/package.json
orion-ui/src/pages/FlowRun.vue

This PR utilizes a utility `getSchemaValuesWithDefaultsJson` created for this use case in orion-design to merge flowRun parameters (overrides) and deployment defaults that the flowRun was triggered with and display them in flowRuns parameters tab
Closes https://github.com/PrefectHQ/prefect/issues/7526

Display all parameter values a flow run was triggered with in the UI (defaults and overrides)

---

src/prefect/results.py
tests/results/test_persisted_result.py
tests/results/test_task_results.py

Alternative to https://github.com/PrefectHQ/prefect/pull/7625
Closes #7624 
Result caching can be disabled on creation, but if you retrieve the result downstream it will be cached on the state. There's not a great way for a user to release this cached object and it's not an intuitive result for the feature. Here, we stash the cache setting on creation. If caching was disabled at creation time, we do not cache the result on future retrievals. This setting will only be stashed locally and will not be persisted on later retrievals of the state.
Unlike  https://github.com/PrefectHQ/prefect/pull/7625, if a task enables caching in a flow that disables caching, the result will continue to cached as intended. …

Disable cache on result retrieval if disabled on creation

---

src/prefect/agent.py
tests/test_agent.py

Adds reporting for crashed flow runs to the agent when the infrastructure status code is non-zero.
Agent logs:
```
15:31:34.018 | ERROR   | prefect.infrastructure.process - Process 'chirpy-bison' exited with status code: 2
15:31:34.018 | INFO | prefect.agent - Reporting flow run '568261ef-049c-40a1-a562-05dcbc3d6306' as crashed due to non-zero status code.
```

Add agent reporting of crashed flow run infrastructure

---

src/prefect/deprecated/data_documents.py
src/prefect/exceptions.py
src/prefect/states.py
tests/test_flows.py
tests/test_states.py

As a follow-on to #7694 this causes getting the result of a `Cancelled` state to raise `CancelledRun`. This brings it in line with `Failed` and `Crashed` states.
```python
from prefect.orion.schemas.states import Cancelled
@flow
def my_flow():
return Cancelled(message="I want to skip this")
state = my_flow()
state.result()
```
Which results in this traceback:
```
13:33:08.615 | INFO    | prefect.engine - Created flow run 'polite-sidewinder' for flow 'my-flow'
13:33:08.721 | ERROR   | Flow run 'polite-sidewinder' - Finished in state Cancelled('I want to skip this')
File "/Users/chrispickett/src/flows/issue_6789.py", line 10, in <module>
state = my_flow()
File "/Users/chrispickett/src/prefect/src/prefect/flows.py", line 442, in …
```

Raise `CancelledRun` when retrieving a Cancelled state's Result

---

src/prefect/cli/deployment.py

This uses a worker thread for the `import_object` call so sync-compatible calls made in the flow definition can send calls to the event loop properly

Fix support for sync-compatible calls in `deployment build`

---

src/prefect/agent.py
src/prefect/cli/agent.py
tests/cli/test_agent.py
tests/test_agent.py

Added a --limit option on 'prefect agent start' to limit the number of flow runs an agent will start simultaneously.
`prefect agent start -l 4`
`prefect agent start --limit 4`

Agent: Add limit to control number of concurrent flow runs

---

tests/test_flows.py

See example failure at https://github.com/PrefectHQ/prefect/actions/runs/3589607088/jobs/6042201822 — if the runner is slow it is possible to timeout

Bump timeout in flaky test

---

src/prefect/settings.py

5s is aggressive and can increase load on agent infrastructure.

Increase default agent query interval to 10s

---

src/prefect/states.py

This helps with clarity where we are generating exceptions for states without attached data

 Add default messages to state exceptions

---

src/prefect/orion/schemas/states.py
tests/orion/schemas/test_states.py

```python
state = Failed(message=None, name="Test")
print(state)
```
Previously: `Test(, type=FAILED)`
Now: `Test(type=FAILED)`

Fix state display bug when state message is empty

---

docs/concepts/logs.md

adds a little detail on the implementation of `log_prints` with respect to the patching of `print`

add detail on `log_prints` patching

---

.github/workflows/release.yaml

I'm going to turn off merge commits because people are not squashing pull requests consistently per our standards. Previously when we turned of merge commits, it broke this workflow. This should fix that :)

Use rebase on docs deploy instead of creating a merge commit

---

docs/concepts/tasks.md

This PR includes a small fix in docs.
Reading and running [Concepts/Tasks#caching docs](https://docs.prefect.io/concepts/tasks/#caching), I got an error due to a missing `task_run` field in the example code so I would make a fix for it.
see also https://github.com/PrefectHQ/prefect/commit/4158a84eaecf0a62d9f9128b3f74f035c6de3a26

Docs: Fix docs typo in concepts tasks

---

src/prefect/engine/results/s3_result.py
src/prefect/storage/s3.py
src/prefect/tasks/aws/s3.py
tests/tasks/aws/test_s3.py

Brings S3Upload into line with similar functionality in S3 Storage, and Result
closes [7466](https://github.com/PrefectHQ/prefect/issues/7466)
Enables you to pass options like server-side encryption to the upload
```
task = S3Upload(bucket="my_bucket", upload_options={'ServerSideEncryption': 'AES256'})
```

Add upload_options to S3Upload

---

src/prefect/orion/api/server.py

Very minor change -- currently the `/health` endpoint shows up as the only element of the `default` category in the API docs; this moves it to the `root` category along with `/hello`.

Move /health to root router

---

src/prefect/infrastructure/process.py
tests/infrastructure/test_process.py

This updates the `Process.kill` method. Instead of sleeping for the full `grace_seconds` and then attempting a kill, it sleeps for 1 second `grace_seconds` times. This allows it to check if the process still exists and do an early return when possible.
Closes #7734 
https://user-images.githubusercontent.com/354286/205357158-9f4ec671-0a08-401f-a397-804075befb51.mov

Monitor process after kill and return early when possible

---

src/prefect/orion/orchestration/core_policy.py
tests/agent/test_agent_run_submission.py
tests/orion/orchestration/test_core_policy.py

Currently, the orchestrator blocks transition from SCHEDULED -> ANY until the scheduled start time is reached. Here, the scope is reduced to -> RUNNING and transitions to PENDING are allowed so that runs can be presubmitted to infrastructure.
Closes https://github.com/PrefectHQ/prefect/issues/7584

Update orchestration rule to wait for scheduled time to only apply to transition to running

---

src/prefect/__init__.py
src/prefect/plugins.py
src/prefect/settings.py
tests/test_plugins.py

A potential fix for https://github.com/PrefectHQ/prefect/issues/7177
Uses a mechanism similar to our collections loading to allow users to define a list of modules to load on Prefect import via a setting.
Specifying a module that cannot be loaded
```
❯ PREFECT_EXTRA_ENTRYPOINTS=foo python -c "import prefect"
Warning! Failed to load extra entrypoint 'foo': ModuleNotFoundError: No module named 'foo'
```
Define `foo.py`
```python
print("Hi from foo!")
def test():
print("Hi from a method in foo!")
```
Specifying a module loads it
```
❯ PREFECT_EXTRA_ENTRYPOINTS=foo python -c "import prefect"
Hi from foo!
```
Specifying a callable for contained side-effects
```
❯ PREFECT_EXTRA_ENTRYPOINTS=foo:test python -c "import prefect"
Hi from foo!
Hi from a method in foo!
```
- If no issue exists and …

Add extra entrypoints setting for user module injection

---

docs/concepts/tasks.md
src/prefect/infrastructure/kubernetes.py
tests/infrastructure/test_kubernetes_job.py

Co-authored with @peytonrunyan 
Closes https://github.com/PrefectHQ/prefect/issues/7739
Converts Kubernetes job PIDs from `{cluster_name}:{job_name}` to `{cluster_uid}:{namespace}:{job_name}`. Cluster names can be arbitrarily set in the Kubernetes config and are not a reliable unique identifier. Additionally, the config does not exist when using an in-cluster agent or in cases like #7739. We generate a stable cluster UID from the `kube-system` namespace UID as described in https://github.com/kubernetes/kubernetes/issues/44954 — which tracks the lack of a Kubernetes API for retrieving a cluster identifier. I attempted to use the job UID instead of the job name because it is guaranteed to be unique across namespaces. However, there is not a clear way to look up a job by its UID later …

Use cluster uid and namespace instead of cluster "name" for Kubernetes job identifiers

---

docs/concepts/deployments.md

There are two commits in this PR. 
The first one is to indent the `Create a deployment` section under `Create a deployment on the CLI`. Without this fix, there are two `Create a deployment with CLI` sections at the same level. 
The second one is to add creating a flow run from deployment with Prefect client to the Concepts page. This closes #7680

Docs: Add create a flow run from deployment with Prefect client to Concepts

---

orion-ui/src/App.vue

This PR fixes a long-standing bug where views like Radar that are full screen used a min-content height on screen sizes under the lg breakpoint.
Before:
After:

Bugfix: Fullscreen layouts on screens < `lg` should take up all the available space

---

src/prefect/client/orion.py
src/prefect/settings.py

We've seen enough folks having trouble with HTTP/2 connectivity, and we want to give them the option to disable it if they are experiencing difficulty with it with their workloads and environments.

Introducing the `PREFECT_API_ENABLE_HTTP2` setting to give users a choice

---

tests/orion/api/test_run_history.py

Comparison of Pydantic models and dictionaries works but can lead to very confusing output from pytest

Update run history tests to compare dicts instead of models

---

src/prefect/orion/orchestration/core_policy.py
tests/orion/orchestration/test_core_policy.py

Closes https://github.com/PrefectHQ/prefect/issues/7752.
Massive shoutout to @anticorrelator for the help.
Task concurrency slots are released according to `ReleaseTaskConcurrencySlots` which is currently a child class of `BaseOrchestrationRule`. Orchestration rules have `before_transition`, `after_transition`, and `cleanup` methods. The `cleanup` method is fired instead of the `after_transition` method if, at any point in the series of calls in the orchestration rules, a transition is rejected. `ReleaseTaskConcurrencySlots` releases the concurrency slot in the `after_transition` method.
This was causing a problem when retrying tasks, because a retry rejects a proposed final state and sets the state to `SCHEDULED` instead. This meant that `ReleaseTaskConcurrencySlots` was not able to …

Release task concurrency slots when transition is rejected as long as the task is not in a running state

---

docs/concepts/logs.md
src/prefect/logging/handlers.py
src/prefect/settings.py
tests/test_logging.py

Sometimes, strings that contain brackets  [  ]  aren't being logged correctly because rich interprets them as styles. This adds a setting to allow toggling and defaults it to False:
"Whether to interpret strings wrapped in square brackets as a style.
This allows styles to be conveniently added to log messages, e.g.
`[red]This is a red message.[/red]`. However, the downside is,
if enabled, strings that contain square brackets may be inaccurately
interpreted and lead to incomplete output, e.g.
`DROP TABLE [dbo].[SomeTable];"` results in `DROP TABLE .[SomeTable];`."
Originally from [here](https://prefect-community.slack.com/archives/CL09KU1K7/p1670455860648239)
```
from prefect import flow, task, get_run_logger
@task
def execute_sql(sql: str): …
```

Add setting to toggle interpreting square brackets as style

---

src/prefect/client/orion.py
src/prefect/infrastructure/docker.py
src/prefect/orion/schemas/filters.py
src/prefect/orion/schemas/sorting.py

I used [Tuna](https://github.com/nschloe/tuna) to profile import times and noticed a few easy wins:
- eager imports of `sqlalchemy` in `schemas/filters.py`
- eager import of `docker` in `docker.py` (this looks like an accident; it's lazily loaded a couple lines later)
- eager imports of the entire ephemeral server in `client/orion.py`
I deferred these imports and reduced import times by roughly 25-30%. For anyone using Prefect only for workflow development or as a client, these aren't needed (obviously working on or with the server would require them)
One other low-hanging fruit is the eager import of `apprise` in `blocks/notifications.py`. Unfortunately an Apprise class is used as a base class in the file, so deferring the import isn't possible. It would be straightforward to simply not …

Defer imports for performance

---

src/prefect/exceptions.py
src/prefect/orion/api/flow_runs.py
src/prefect/orion/api/task_runs.py
src/prefect/orion/exceptions.py
src/prefect/orion/orchestration/rules.py
tests/orion/orchestration/test_rules.py

Co-authored with @anticorrelator 
Previously a REJECT response required a new state which was then always written to the database. Here, the `OrchestrationRule.reject_transition` utility is updated to accept `state=None`. When this is used, the REJECT orchestration response will contain the current state of the run and a new state will not be appended to the run's states. This allows REJECT semantics to be used to prevent transition to a proposed state without providing an explicit alternative. This is useful when a client is proposing a state with the assumption that they are in a different starting state than the orchestrator has.
Required for #7738 
- If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect/issues/new/choose) …

Allow `reject_transition` to use current state

---

src/prefect/orion/api/server.py

Introduced in #7738 — clearly not intentional and not a big deal except the service was not disabled per #7846 so the late runs service is running during tests which causes test failures.

Fix bug where pause expiration and late run services settings were swapped

---

docs/ui/notifications.md
src/prefect/blocks/notifications.py
tests/blocks/test_notifications.py

The PR adds Opsgenie notification block feature, based on [Apprise documentation for Opsgenie](https://github.com/caronc/apprise/wiki/Notify_opsgenie)
Create the block URL from the Prefect UI:
Use the block:
```
from prefect.blocks.notifications import OpsgenieWebhook
opsgenie_webhook_block = OpsgenieWebhook.load("block-name")
opsgenie_webhook_block.notify("Hello from Prefect!")
```

Add Opsgenie notification block

---

tests/test_engine.py

See failure in https://github.com/PrefectHQ/prefect/actions/runs/3651682236/jobs/6169194536

Mark `test_first_polling_is_smaller_than_the_timeout` as flaky

---

.github/workflows/integration-tests.yaml

2.6 integration tests are failing due to a bad httpcore release in the image: https://github.com/PrefectHQ/prefect/actions/runs/3678823904/jobs/6222542729
I've resolved this by upgrading the httpcore package on container startup.
Fixed run at https://github.com/PrefectHQ/prefect/actions/runs/3678881759/jobs/6222672158

Fix integration tests with v2.6 client images

---

src/prefect/_internal/compatibility/experimental.py
src/prefect/utilities/callables.py
tests/_internal/compatibility/test_experimental.py

Extends #7819 to mark parameters in callables as experimental
```python
from prefect._internal.compatibility.experimental import experimental_parameter
@experimental_parameter("y", group="example", when=lambda y: y is not None)
def foo(x, y = None):
return x + 1 + (y or 0)
foo(1)       # No warning
foo(1, 2)    # Warning
foo(1, y=3)  # Warning
```

Add `experimental_parameter` utility

---

src/prefect/_internal/compatibility/experimental.py
tests/_internal/compatibility/test_experimental.py

For consistency in the API surface for these, the "feature" blurb comes first then the "group" is specified as a kwarg.

Update experimental utilities to require kwarg for group

---

src/prefect/_internal/concurrency/event_loop.py
src/prefect/_internal/concurrency/primitives.py
tests/_internal/concurrency/test_primitives.py

In preparation for changes in engine behavior, adds async but threadsafe `Event` and `Future` concurrency primitives. We may add other primitives like `Lock` in the future.
Note these implementations are specific to asyncio.

Add thread-safe async primitives `Event` and `Future`

---

netlify.toml

attempting to fix the docsite build failure - my hunch is that the subshell will prompt for a password without this prefix (bc the git client assumes this is a username/password authentication) + hang/fail

fixup: set `oauth` prefix to git clone string

---

src/prefect/engine.py
src/prefect/exceptions.py
tests/test_engine.py

Follow-up to #7738 
- Creates a separate `Pause(PrefectSignal)` instead of `PausedRun(BaseException)` for signalling exit on pause. This is inline with our plans for `Cancel` and our other state-exception types.
- Uses `propose_state` in `pause_flow_run` so all orchestration result types are handled.
I've attempted to avoid stylistic changes. I have not changed `resume_flow_run`, but we may want to in a separate PR.

Refactor `pause_flow_run` for consistency with engine state handling

---

src/prefect/orion/__init__.py
src/prefect/orion/orchestration/__init__.py

- `orion.models` can indirectly cause circular imports

Fix circular imports in the `orchestration` module

---

docs/stylesheets/extra.css
docs/ui/audit-log.md
docs/ui/automations.md
docs/ui/cloud-getting-started.md
docs/ui/cloud.md
docs/ui/organizations.md
docs/ui/roles.md
docs/ui/service-accounts.md
docs/ui/sso.md
docs/ui/workspaces.md
mkdocs.insiders.yml
mkdocs.yml

Styling changes to increase visibility of Prefect Cloud features.
- Add cloud icon next to Cloud-specific topics in left nav
- Move all Cloud topics up one level so they're not hidden
- Add a cloud admonition type
- Icons are compatible with dark theme

Add cloud icons and admonitions

---

docs/concepts/results.md

Small spelling fix: `retreived` -> `retrieved`

Correct spelling in Results page

---

docs/collections/usage.md

Example highlighting usage of `with_options` that can be referenced by all collection readme's to clarify that collection task / flow settings can be customized

add `with_options` example to collections usage docs

---

src/prefect/_internal/concurrency/event_loop.py
src/prefect/_internal/concurrency/primitives.py
src/prefect/_internal/concurrency/workers.py
tests/_internal/concurrency/test_workers.py

Follow-up to #7865
Adds a worker pool class for submitting synchronous functions to run in background workers. This will eventually replace our usage of anyio's worker threads, giving us greater control over concurrent work and improved debugging.
Workers will be extended in the near future to support sending asynchronous calls back from workers to the event loop thread and sending asynchronous calls to workers running event loops.
This implementation is inspired largely by the [CPython `ThreadPoolExecutor`](https://github.com/python/cpython/blob/main/Lib/concurrent/futures/thread.py) implementation. Handling for several weird edge cases (mostly related to garbage collection) is replicated here. This implementation will diverge further as we capitalize on asynchronous support.
```python …
```

Add `WorkerThreadPool` for running synchronous work in threads

---

src/prefect/filesystems.py
tests/test_filesystems.py

Closes https://github.com/PrefectHQ/prefect/issues/7853
The `--path` argument for deployments wasn't being used to modify the `LocalFileSystem.basepath` when calling the `put_directory` method.
This PR updates the logic of `LFS._resolve_path` and updates `LFS.put_directory` to use the `_resolve_path` method to fix the bug. This makes the implementation comparable to the implementation in the `RemoteFileSystem`.
A little bit of refactoring also happened in filesystem tests (see last commit) to remove some clunky temporary directory setup.
```python
fs = LocalFileSystem(basepath="~/my/dog")
fs._resolve_path("skip")
Out[14]: PosixPath('/Users/peytonrunyan/my/dog/skip')
``` …

Fix path argument for LocalFileSystem block

---

src/prefect/orion/database/migrations/MIGRATION-NOTES.md
src/prefect/orion/database/migrations/versions/postgresql/2022_12_06_164028_9326a6aee18b_add_cancelling_to_state_type_enum.py
src/prefect/orion/database/query_components.py
src/prefect/orion/orchestration/core_policy.py
src/prefect/orion/schemas/states.py
tests/orion/models/test_work_queues.py
tests/orion/orchestration/test_core_policy.py

The MVP for cancellation used a `CANCELLED` state with a name of `Cancelling` for the agent to decide which flows need to be cancelled. The main issue with this is that concurrency slots are immediately released when that transition happens even though the tasks/flows are still technically running. There is also some general 'ick' factor in using a state name for an important operation like cancellation.
This introduces a `CANCELLING` state type and sets it up so that it maintains / occupies concurrency limit slots, both for tag-based task usage as well as work queues. 
Related to #7735 

Create a `CANCELLING` state type

---

docs/concepts/flows.md

Adds a new "Pause a flow run" section to Flows documentation documenting flow run pause and resume.

Add documentation for pausing flow runs

---

src/prefect/infrastructure/kubernetes.py

Add missing type hint for `job_watch_timeout_seconds` on `KubernetesJob` - closes #7911 

add missing Optional type hint for `job_watch_timeout_seconds`

---

src/prefect/cli/deployment.py
src/prefect/flows.py
tests/cli/deployment/test_deployment_build.py
tests/test_flows.py

Closes https://github.com/PrefectHQ/prefect/issues/7918
The `select_flows` function was checking to see if flow names found in a module matched a desired function name. This was causing problems in two cases:
1. the flow function had underscores, which were converted to dashes in the flow name
2. the flow had a custom name, which would not relate to the underlying function
This is now addressed by checking the underlying function name. 
The parameter `flow_name` in `select_flows` is now also sanitized to make sure that any dashes are converted to underscores, so that it will match the underlying flow function name.  

Fix bug where flows with names that do not match the function name cannot not be loaded

---

src/prefect/_internal/concurrency/event_loop.py
src/prefect/_internal/concurrency/primitives.py
tests/_internal/concurrency/test_primitives.py
tests/_internal/concurrency/test_workers.py

Follow-up to #7865 — extends https://github.com/PrefectHQ/prefect/pull/7875 
I attempted to simplify the `Event` implementation by inheriting from `asyncio.Event`, but it turns out there is significant variation in how they handle binding to event loops across our supported Python versions. I went with a backport of the latest CPython implementation and cleaned up our comments covering the differences.
We no longer bind an event to a single loop at startup. Instead, each `wait()` call creates a future bound to the current event loop. Then, during `set()` calls, we will notify each waiter. This is nearly verbatim the implementation from CPython, with thread safety added in.
The primary motivation for revisiting the `Event` implementation was a hard to find deadlock that occurred when two …

Improve `Event` implementation consistency and fix deadlock

---

src/prefect/.prefectignore

vcs directories tend to be relatively big and make deployment slow, so they should be ignored by default. Added `.git` and `.hg` here as those are the ones I use.
Right now every deployment of a repository would also upload it's version control history although that's generally not needed or expected. This makes uploads quite a bit faster & cheaper.
I'm not aware of any already existing issue I could link here and it's a small fix.
Deploy a flow e.g. with to observe the time difference and also check the storage to see there is less data saved:
```
time prefect deployment build foobar.py:foobar --name dev -ib kubernetes-job/foobar-dev -sb gcs/foobar-dev -q kubernetes -a
``` …

Ignore vcs directories git, hg (mercurial) in .prefectignore

---

src/prefect/orion/api/workers.py
tests/orion/api/test_workers.py

@marichka-offen encountered the following error when developing the workers UI:
@marichka-offen was able to determine that the get worker pool queue endpoint was using the wrong model. This PR updates the endpoint to use the correct model and adds a test for coverage.

Fixes read worker pool queue endpoint

---

src/prefect/cli/flow_run.py
tests/cli/test_flow_run.py

Usage: prefect flow-run logs <flow-run-id>
closes #7814
This PR attempts to resolve issue #7814 .
It adds a new `logs` command to the `flow-runs` command in the CLI.
Usage is as follows:
```
prefect flow-run logs <flow-run-id>
```
The CLI responds as follows:
```
2022-12-23T14:44:16.847706+00:00  | INFO  | Finished in state Completed()
```
This is my first PR here. Waiting for your review and opinions :)
Ohad

feature: get flow run logs from CLI

---

src/prefect/utilities/callables.py
tests/utilities/test_callables.py

enables fix for #7508
Postgres JSONB doesn't preserve dictionary order which makes it currently impossible to display flow parameters in the UI in the order of definition in the flow function when using a postgres db.
This PR adds a position key to each parameter which could be used by the frontend to reconstruct the original order. This requires changes in the frontend.
simple_flow.py:
```
@flow()
def simple_flow(foo, bar, foo_bar):
pass
```
```
$ prefect deployment build simple_flow.py:simple_flow --name simple_flow --apply
Found flow 'simple-flow'
Deployment YAML created at 'simple_flow-deployment.yaml'.
Deployment storage None does not have upload capabilities; no files uploaded.  Pass --skip-upload to suppress this warning.
Deployment …
```

Add position key to parameter openapi schema properties

---

src/prefect/engine.py
tests/test_flows.py

Closes #7903
In `orchestrate_flow_run` the timeout context was created before resolving the inputs `resolve_inputs`. By creating the timeout context, the deadline is already calculated ([source](https://github.com/agronholm/anyio/blob/0cbb84bfadd9078c5dad63bab43907ed0dd555a1/src/anyio/_core/_tasks.py#L112-L114)). This seems incorrect. You would expect that the subflow's timeout begins counting down only after starting the subflow, not the moment of creation.
See added test for example flow (or the referenced issue). Before 929068e, the test will fail. 
<details>
<summary>Output of test without patch 929068e</summary>
```
pytest tests/test_flows.py::TestFlowTimeouts::test_subflow_timeout_waits_until_execution_starts -s …
```

Fix bug where flow timeouts started before waiting for upstreams

---

src/prefect/infrastructure/kubernetes.py
tests/infrastructure/test_kubernetes_job.py

As reported in https://prefecthq.slack.com/archives/C02J2QEHXAR/p1672429355523049?thread_ts=1672429297.984519&cid=C02J2QEHXAR — this path was incorrect.
```python
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.10/site-packages/prefect/agent.py", line 257, in _submit_run_and_capture_errors
result = await infrastructure.run(task_status=task_status)
File "/usr/local/lib/python3.10/site-packages/prefect/infrastructure/kubernetes.py", line 249, in run
return await run_sync_in_worker_thread(self._watch_job, job_name)
File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 68, in run_sync_in_worker_thread
return await anyio.to_thread.run_sync(call, cancellable=True)
File …
```

Fix captured Kubernetes error type in `get_job`

---

.github/codeql-config.yml

Ignores another type of cyclic import warning e.g. https://github.com/PrefectHQ/prefect/security/code-scanning/1578

Add another cyclic import to CodeQL exclusions

---

src/prefect/cli/cloud.py
tests/cli/test_cloud.py

Previously when running `prefect cloud login` without any workspaces existing, an `IndexError` would occur. This pr adds messaging when that occurs to indicate to the user that no workspaces exist and directs them to create one.
Closes: https://github.com/PrefectHQ/prefect/issues/7952
When logging in when no workspaces exist:

update `prefect cloud login` when no workspaces exist

---

.github/dependabot.yml

This was removed when we moved the default branch to `main`.
I have not enabled npm scanning since it is only used for legacy documentation, the security alerts are always false positives, and the requirements should stay frozen for consistent builds.

Add Python dependency scanning for the 1.x branch

---

orion-ui/src/App.vue
orion-ui/src/pages/AppRouterView.vue

We were already doing this for the main page views. This just moves everything inside the suspense so we can user permissions (which are async) inside the context sidebar
@znicholasbrown I'd like you to review this specifically to make sure I didn't mess up the scrolling fix css you added.

Refactor App.vue so everything is contained in a suspense wrapper

---

.github/workflows/python-tests.yaml
requirements.txt

[SQLAlchmey 1.4.46](https://docs.sqlalchemy.org/en/20/changelog/changelog_14.html#change-1.4.46) introduced a uber-warning which raises when a 2.0 deprecated API is used. This warning is causing all of our tests to fail because the warning raises during DB migration. This PR caps the SQLAlchemy version below 2.0 so that we can migrate to SQLAlchemy 2.0 when we are ready and adds the `SQLALCHEMY_SILENCE_UBER_WARNING` to python tests to unblock CI.

Caps SQLAlchemy version below 2.0 and silences uber-warning

---

requirements.txt

This release introduced a breaking change that was reverted in 0.23.3 (https://github.com/encode/httpx/pull/2540)
See #8032

Skip httpx version 0.23.2

---

.github/workflows/python-tests.yaml
setup.cfg

Moves `SQLALCHEMY_SILENCE_UBER_WARNING` to setup.cfg so that it disables warnings on local test runs as well as in CI.

Moves `SQLALCHEMY_SILENCE_UBER_WARNING` to setup.cfg

---

src/prefect/client/schemas.py
src/prefect/orion/api/deployments.py
src/prefect/orion/api/flow_runs.py
src/prefect/orion/api/work_queues.py
src/prefect/orion/database/orm_models.py
src/prefect/orion/models/flow_runs.py
src/prefect/orion/schemas/responses.py
tests/client/test_orion_client.py
tests/orion/api/test_flow_runs.py
tests/orion/api/test_work_queues.py
tests/orion/models/test_flow_runs.py

Introduces a `FlowRunResponse` model to replace a `worker_pool_queue_id` with the `worker_pool_name` and `worker_pool_queue_name` for the flow run. This update is for use in the UI and also to better align with the worker pool routes that operate with names instead of IDs. I'm not sure if this is the optimal implementation, so please let me know if there is a better way to approach this. I intend to implement a similar pattern for the deployments routes.

Include worker pool name and worker pool queue name in flow run API responses

---

orion-ui/package-lock.json
orion-ui/package.json

Reverts to a previous version of vue-compositions to resolve a bug with flow run filters. This has no user facing impact. 

Revert to 1.1.2 for vue compositions and update orion-design to 1.1.53

---

src/prefect/results.py
tests/test_states.py

Without this change, you can see an extra client is created during result factory creation
```
12:22:42.162 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////Users/mz/.prefect/orion.db
Stack (most recent call last):
File "/Users/mz/dev/prefect/example.py", line 16, in <module>
anyio.run(test_flow)
File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70, in run
return asynclib.run(func, *args, **backend_options)
File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292, in run
return native_run(wrapper(), debug=debug)
File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/pytho …
```

Avoid creating an extra client instance during result factory creation

---

src/prefect/deployments.py
tests/test_deployments.py

User reports that: `prefect deployment build sky-pipe/flows/test_flow.py:test_flow -n testaroo -q sky-pipe --skip-upload -a -ib "cloud-run-job/test"` does not work in prefect_gcp==0.2.2, a version that introduces `SecretDict` inside `GcpCredentials`.
However, during my testing, I found this works, with plain blocks.
```
from prefect_gcp import GcpCredentials
from prefect_gcp.cloud_run import CloudRunJob
job = CloudRunJob(image="myimage", region="region", credentials=GcpCredentials.load("gcp-credentials"))
job.json()
```
The reason it works with blocks is because `Block` class has special handling; it does not work in a `Deployment` because `Deployment` inherits from `BaseModel` and not `Block`,  
```
class Config:
extra = "allow"
json_encoders = {SecretDict: lambda v: v.dict()}
```
So …

SecretDict is not JSONSerializable in Deployment

---

orion-ui/src/components/ContextSidebar.vue

This PR adds the correct icon to TaskRunConcurrency page in context sidebar

Fix TaskRunConcurrency page icon in context sidebar

---

src/prefect/deployments.py

Adds additional logs to clarify behavior when a flow run is preparing for execution. Otherwise, users are confused when the flow run hangs while downloading content from storage and we have no insight into where the issue is occurring.
See https://prefect-community.slack.com/archives/CL09KU1K7/p1672951028821839
```
15:46:32.797 | INFO    | prefect.agent - Submitting flow run 'efc73470-4d4c-49a1-89b3-fb1cdfa7f608'
15:46:32.856 | INFO    | prefect.infrastructure.process - Opening process 'copper-numbat'...
15:46:32.857 | DEBUG   | prefect.infrastructure.process - Process 'copper-numbat' running command: /opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/bin/python -m prefect.engine in /var/folders/q9/1myqgwxn2r3fvkvf6jy3npcm0000gn/T/tmpgtxvmo22prefect
15:46:32.885 | INFO    | …
```

Add logs deployment flow code load

---

src/prefect/utilities/collections.py
tests/utilities/test_collections.py

Closes #8082 by adding a `hasattr` check on the fields of the Pydantic object
The following code now runs without error.
```python
from pydantic import BaseModel, Extra
class Something(BaseModel, extra=Extra.allow):
a: int
@flow(name="main")
def main_flow() -> Something:
o1 = Something(a=1, b=2)
o2 = o1.copy(exclude={"b"})
return o2
main_flow()
```

Check for missing Pydantic extra fields in `visit_collection`

---

src/prefect/_internal/compatibility/experimental.py
tests/_internal/compatibility/test_experimental.py

Add an `experimental_field` decorator for use with Pydantic models. The decorator allows the user to define a field to warn on and will raise a warning if the correct conditions are met when the model is instantiated. I also wanted to allow the warning to raise whenever the specified value is set, but I didn't find a way to get that working.
```python
from pydantic import BaseModel
from prefect._internal.compatibility.experimental import experimental_field
@experimental_field(
"value",
group="test",
help="This is just a test, don't worry.",
)
class Foo(BaseModel):
value: int
Foo(value=1) # raises experimental warning
```

Adds `experimental_field` decorator

---

tests/client/test_orion_client.py

Modify disable ssl setting tests to allow any for headers and timeout

---

docs/concepts/work-queues.md

Added documentation about the --match flag in agent configuration to work-queues.md. 
Preview here: https://deploy-preview-7768--prefect-orion.netlify.app/concepts/work-queues
Closes https://github.com/PrefectHQ/prefect/issues/7511

Add --match flag to work queues documentation

---

RELEASE-NOTES.md
docs/overrides/main.html

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.7.6/RELEASE-NOTES.md#release-277)
Using this in the highlight:

Add release notes for 2.7.7

---

src/prefect/orion/schemas/actions.py
tests/orion/schemas/test_actions.py

Ports changes in #8110 and adds support for `worker_pool_name` and `worker_pool_queue_name` to make rename safe for older clients.

Makes rename safe for deployments API

---

src/prefect/orion/models/workers.py
tests/orion/models/test_filters.py
tests/orion/models/test_workers.py

Supersedes #8108 
Renames the default worker pool queue to a slugified, one word `default`

Rename default work pool queue

---

tests/orion/models/test_flow_runs.py

Follow up to #7951 - improves test coverage by checking that dependencies match the initial task runs for all relevant fields.  

Enhancement: Update test coverage for task run dependencies utility

---

src/prefect/engine.py

Related to https://prefect-community.slack.com/archives/CL09KU1K7/p1673031232195399
```
Task run '8775d5ff-1614-4df3-83bd-dc3b3fc4bb0f' received abort during orchestration: The enclosing flow must be running to begin task execution. Task run is in PENDING state
```

Add logs when task run receives abort signal and is in non-final state

---

orion-ui/package-lock.json
orion-ui/package.json
orion-ui/src/pages/FlowRun.vue

Bumps the `orion-design` dependency to `1.1.59` to include the latest code for the `FlowRunTimeline`. Adds the timeline to the flow run page.

bump orion-design, release flow run timeline

---

docs/concepts/tasks.md

Adds documentation for https://github.com/PrefectHQ/prefect/pull/7856
Preview at https://deploy-preview-8156--prefect-orion.netlify.app/concepts/tasks/#refreshing-the-cache

Add documentation for cache refreshes

---

src/prefect/client/base.py
tests/client/test_base_client.py

I think this is similar to a retry on `ReadError`, but I'm not sure of the additional implications of retrying here.
Crash reported:
```
Crash detected! Execution was interrupted by an unexpected exception: Traceback (most recent call last):
File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 924, in write
n = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
The above exception was the direct cause of the following exception:
File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
yield
File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 51, in write
await self._stream.send(item=buffer)
File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", …
```

Add `httpx.WriteError` to client retryable exceptions

---

tests/software/test_conda.py

Example failure at https://github.com/PrefectHQ/prefect/actions/runs/3896185368/jobs/6652407578
Closes #8148

Fix detection of conda installation in test

---

tests/_internal/concurrency/test_primitives.py

Unfortunately this deadlock does occur frequently in CI

Skip flaky test `test_dependent_events_in_two_loops_do_not_deadlock`

---

RELEASE-NOTES.md
docs/overrides/main.html

Replaces https://github.com/PrefectHQ/prefect/pull/8155
[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.7.8/RELEASE-NOTES.md#release-278)

Add release notes for 2.7.8

---

tests/infrastructure/test_process.py

Example failure at https://github.com/PrefectHQ/prefect/actions/runs/3905183643/jobs/6671882248

Mark `test_process_streams_stderr` as flaky on Python 3.11

---

src/prefect/orion/api/deployments.py
src/prefect/orion/api/workers.py
src/prefect/orion/models/deployments.py
tests/orion/api/test_deployments.py
tests/orion/models/test_deployments.py

Adds the ability to create a work pool queue during deployment creation and update. If the work pool exists, but the work pool queue does not, the queue will be created under the specified work pool. If the work pool does not exist, a 404 error is returned and no work pool queue is created.

Allow deployment creation and update to create work pool queues

---

src/prefect/orion/schemas/core.py
tests/orion/schemas/test_core.py

closes: https://github.com/PrefectHQ/nebula/issues/3190
It is currently possible to get a block to create a `BlockDocumentReference` where the `parent_block_document_id` and `reference_block_document_id` are the same. This will lead to an infinite loop when trying to query the database for blocks using `WITH RECURSIVE ...` which looks to extract nested blocks. This pr will guard against this self referential loop from occurring. 
Note: There currently is not an MRE for actually getting into this state using the block interface. Once that exists, more changes and better validation might need to be added. Until then this ensures that the server cannot get into an undesired state.
```bash
>>> same_id = uuid4()
>>> BlockDocumentReference(parent_block_document_id=same_id, …
```

Stop blocks from referencing themselves

---

tests/client/test_orion_client.py

In an attempt to reproduce the issue at https://github.com/PrefectHQ/prefect/issues/8186 I added a check that the work queue name is populated on the returned flow run.

Add work queue name coverage to `test_create_flow_run_from_deployment`

---

docs/stylesheets/extra.css

Adds two new custom admonitions for calling out links to Discourse topics or blog/article/other content.
- "discourse" admonition uses a Discourse icon and is meant to call out a link to related content on Prefect Discourse.
- "blog" admonition uses a generalized book icon and may be used to call out any external content.
```
!!! discourse "Learn more about Secrets blocks"
See Prefect Discourse topic [Pass ENV vars from Kubernetes to Job](https://discourse.prefect.io/t/pass-env-vars-from-kubernetes-agent-to-job/2218) for more information about using Secrets with Kubernetes Jobs.
!!! blog "Learn more about building modular dataflow applications"
See the article [Modular Data Stack — Build a Data Platform with Prefect, dbt and Snowflake](https://www.prefect.io/guide/community-posts/modular-d …
```

Add new "discourse" and "blog" admonition types

---

src/prefect/cli/root.py

In  some cases, an external library can change the default event loop policy (see https://github.com/PrefectHQ/prefect/issues/8206). This pull request adds update of the event loop policy to the CLI entrypoint. This is ideal because it is
1. Before any event loop is created
2. Always in a context where we are in full control of the process — this will not change the policy for any user code

Fix CLI ability to spawn subprocesses on Windows

---

docs/orchestration/faq/upgrade_environments.md

I fixed dead links in /prefect/blob/1.x/docs/orchestration/faq/upgrade_environments.md
Preview of the corrected page: https://github.com/manic-miner/prefect/blob/2a8f88d2276d9678f2dafd9f320a0cec494bda5b/docs/orchestration/faq/upgrade_environments.md
Two links [here](https://github.com/manic-miner/prefect/blob/2a8f88d2276d9678f2dafd9f320a0cec494bda5b/docs/orchestration/faq/upgrade_environments.md#fargatetaskenvironment) that mention Fargate Agent and point at docs/orchestration/agents/fargate.md 
couldn't be fixed because the file doesn't exist.

Fix broken links in RunConfig FAQ

---

src/prefect/orion/database/query_components.py

closes: https://github.com/PrefectHQ/prefect/issues/7568
This PR fixes the postgres query for the `FlowRunNotifications` service. Previously the the service would pull multiple items off of the notifications queue when `LIMIT 1` is specified. This [message thread on the postgres forum](https://www.postgresql.org/message-id/1134.1553619797%40sss.pgh.pa.us) best explains why in detail. 
The short version is calling the subquery when called with `LIMIT 1` leads to some "unspecified" behavior by the postgres optimizer. By pulling the subquery out into a `WITH` statement, postgres can no longer "optimize" the subquery and 1 row will always be returned.
This solution is preferable to https://github.com/PrefectHQ/prefect/pull/8198 because the `LIMIT` can be variable in this query. In that …

fix flow run notifications query

---

src/prefect/cli/templates/kubernetes-agent.yaml
tests/cli/test_kubernetes_manifest.py

Relates to #8120; Defines the required cluster permissions to enable the Prefect agent to query the `kube-system` namespace to retrieve a UUID

chore: add k8s kube-system permissions to prefect agent template

---

orion-ui/src/components/ContextSidebar.vue
orion-ui/src/pages/WorkPool.vue
src/prefect/agent.py
src/prefect/cli/agent.py
src/prefect/cli/deployment.py
src/prefect/client/orion.py
src/prefect/orion/api/workers.py
src/prefect/orion/schemas/actions.py

A few tweaks to:
- hide some warnings
- update some console output
- fix a deployment creation error
- simplify run-gathering logic for work pools
- renames 'Workers' UI sidebar header
- removes Workers tab from Work Pool page

Tweaks to agents <-> work pools

---

orion-ui/src/components/ContextSidebar.vue
orion-ui/src/pages/WorkPool.vue
src/prefect/agent.py
src/prefect/cli/agent.py
src/prefect/cli/deployment.py
src/prefect/client/orion.py
src/prefect/orion/api/workers.py
src/prefect/orion/models/workers.py
src/prefect/orion/schemas/actions.py
src/prefect/orion/schemas/filters.py
tests/agent/test_agent_run_submission.py
tests/cli/test_agent.py

Adds the option to specify a work pool when starting an agent. The normally functionality is left untouched. 
The following functionality is added:
- If a work pool is specified with a queue or a queue prefix, the agent will poll for runs from the matching queues under the specified work pool.
- If only a work pool is provided, the agent will poll for runs from all queues in that work pool.
Start an agent to poll from a specific queues in a work pool:
```bash
prefect agent start --pool test-pool --queue test-queue-1 --queue test-queue-2
```
Start an agent to poll from a queues in a work pool:
```bash
prefect agent start --pool test-pool
```

Makes agents work pool aware

---

setup.py

Today we only use `url` parameter. This PR add relevant project links to `setup.py` as well. 
Today:
After this change:

Add `project_urls` to `setup.py`

---

.github/workflows/python-tests.yaml
requirements.txt
src/prefect/testing/standard_test_suites/task_runners.py
tests/conftest.py
tests/test_flows.py

Following #8125 we can consolidate the Postgres and SQLite tests into a single matrix for maintainability :)
This also creates an avenue for splitting tests further for speedups (as we have recently done in Cloud)

Update Python tests to use a single test matrix for both databases

---

docs/concepts/infrastructure.md

Adds some missing KubernetesJob options to the Infrastructure docs.

Update KubernetesJob options

---

src/prefect/infrastructure/kubernetes.py

The OCI spec calls refers to the fully-qualified image path (optional registry, tags, digest, etc) as an "image reference", so we can do the same here.
---
References:
* https://kubernetes.io/docs/concepts/containers/images/#image-names
* https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
In doing research for this, it seems that the name "image reference" isn't very well-defined. I think the example should help illustrate what users should put here, and in particular that they may need to include a tag, if they're not using `latest`

Add a hint to the Kubernetes block description for imageref

---

.github/workflows/python-tests.yaml
setup.cfg

The environment variable in `setup.cfg` does not appear to work although it is present in pytest's environment — perhaps it needs to be set when SQLAlchemy is loaded. We can use typical warning ignore patterns instead of their variable.

Use standard warning handling for SQLAlchemy 2.0

---

src/prefect/orion/schemas/actions.py
tests/orion/api/test_deployments.py
tests/orion/models/test_deployments.py
tests/orion/schemas/test_actions.py

`work_pool_queue_name` name was removed in lieu of `work_queue_name` which caused issues with 2.7.8 clients that don't have logic to filter out unset fields. This PR add compatibility with 2.7.8 client by filtering out `work_pool_queue_name` if it is included in a deployments API request.

Fixes server compatibility for deployments API

---

.github/workflows/docker-builds.yaml

Some touch-ups following the first production release:
- Updates workflow names
- Skips development tags on releases — the prod account does not have write access to the dev repo and it's a double push for the given commit anyway
- Skips tagging using `if` rather than `enable=...` when relevant — to avoid warnings about unused tags

Minor updates to the Docker image build workflow

---

src/prefect/_internal/compatibility/experimental.py
src/prefect/orion/utilities/schemas.py
tests/_internal/compatibility/test_experimental.py

Marks fields as experimental if `experimental_field` decorator is used and also adds the corresponding `group_name`. Those fields are then excluded from dictionaries generated from a `PrefectBaseModel` to avoid sending experimental fields to the API unless specifically enabled.

Adds ability to exclude experimental fields in API calls

---

src/prefect/engine.py

Supersedes #8287 
The task run name isn't very user friendly by default and since we're showing task run names in lots of places we'd like the default to be focused on human readability. The task key will still be available in details. This will allow us to improve readability of task runs in the UI without short-term patches that would complicate design once we allow users to set their own task run names.

Update default task run name to exclude hash of task key

---

.pre-commit-config.yaml

Our CI jobs have begun failing (some examples [here](https://github.com/PrefectHQ/prefect/actions/runs/4033934953/jobs/6934769167) and [here](https://github.com/PrefectHQ/prefect/actions/runs/4038476869/jobs/6942500294)), and also this issue is reproducible locally.  After doing some sleuthing, the issue is resolved by upgrading `isort`.

[maintenance] Update isort to fix errors in CI

---

docs/ui/roles.md

Adds permissions details regarding blocks secrets to Roles documentation.
[Preview](https://deploy-preview-8309--prefect-orion.netlify.app/ui/roles/)

Add role permissions regarding block secrets

---

setup.py

i have an application pinned to this branch, and started seeing some build failures:
```
'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
```
`v66.0.0` of setuptools was released earlier in the month, with a breaking change on dropping support for non-conforming version expressions for PEP 440
https://setuptools.pypa.io/en/latest/history.html#id9
checking the setuptools version loaded into the subprocess during pip install, im seeing v67
```
#10 17.31   Installing build dependencies: started
#10 17.31   Running command pip subprocess to install build dependencies
#10 18.53   Collecting setuptools>=40.8.0
#10 18.82     Downloading setuptools-67.0.0-py3-none-any.whl (1.1 MB)
#10 19.17 …
```

fixup: kubernetes package version to conform to v66 of setuptools

---

tests/cli/deployment/test_deployment_run.py

Currently, some unit tests are failing [here](https://github.com/PrefectHQ/prefect/actions/runs/4056871191/jobs/6981912109#step:13:462). This will add a fix for them.
Because of how we parse start time dates with `dateparser`, we always prefer dates from the future. One of the start times was `1-31-23`, which is no longer the future, so the expected start time was off as the actual start time in the tests became `1-31-2123` instead of `1-31-2023`.
```python
start_time_parsed = dateparser.parse(
start_time_raw,
settings={
"TO_TIMEZONE": "UTC",
"RETURN_AS_TIMEZONE_AWARE": False,
"PREFER_DATES_FROM": "future",
"RELATIVE_BASE": datetime.fromtimestamp(now.timestamp()),
},
)
```
There's probably a more long-term fix for this but this should resolve the problem for now.
- If no issue exists and …

Fix tests for scheduled flow runs CLI `--start-at` option

---

docs/stylesheets/extra.css
docs/ui/cloud-quickstart.md
docs/ui/cloud.md

Adds a getting started video to the Prefect Cloud Quickstart page.
Moves around a few other bits to emphasize getting started content.
[Preview](https://deploy-preview-8336--prefect-orion.netlify.app/ui/cloud-quickstart/)

Add getting started tutorial video to Prefect Cloud Quickstart

---

src/prefect/orion/api/workers.py
tests/orion/api/test_workers.py

Adds logic to the get scheduled flow runs endpoint so that work queues that are polled for work from that endpoint have their `last_polled` timestamp updated. If any work queues are specified when polling this endpoint, only the `last_polled` timestamp of those work queues will updated. If an entire work pool is being polled, all the work queues in the work pool will have their `last_polled` timestamp updated.

Enables updates to work queue `last_polled` time when polling work pools

---

src/prefect/agent.py
tests/agent/test_agent_run_cancellation.py

Agents were not properly updating `Cancelling` runs to a `Cancelled` state after cancellation logic has fired. This update fixes that.

Fix cancellation bug

---

requirements.txt
src/prefect/events/__init__.py
src/prefect/events/clients.py
src/prefect/events/schemas.py
tests/events/conftest.py
tests/events/test_cloud_events_client.py
tests/events/test_event_schemas.py
tests/events/test_resource_schemas.py
tests/events/test_utility_events_clients.py

This includes the client-side schema for Prefect Cloud events, as well as the
initial set of client implementations.  The primary client streams events over
WebSockets to Prefect Cloud, including reliable delivery through unreliable
network connections.  Prefect Cloud limits connections to ~30 seconds, so we
need to have highly reliable handling of disconnects.  This implementation has
been tested emperically at high rates (several hundreds of events per second)
and tested with Prefect Cloud for accuracy in their delivery.
Also included are the `NullEventsClient` which will be the default for non-Cloud
users and an `AssertingEventsClient` that will assist in future unit testing of
event emission from various Prefect components.
```
async with PrefectCloudEventsClient(API_URL, API_KEY) as …
```

Introduces the Prefect Cloud Events schema and clients.

---

src/prefect/infrastructure/kubernetes.py
tests/infrastructure/test_kubernetes_job.py

Closes https://github.com/PrefectHQ/prefect/issues/8345
The issue is a good summary of the details here, but briefly:
1. We should not pass `timeout_seconds` to K8s unless it is set, they use the presence of the kwarg to determine if retries should be enabled.
2. We should not exit early if the watch exits unless a timeout is given

Fix Kubernetes job watch exit when no timeout given

---

.github/workflows/integration-tests.yaml

Fixes wrong variable name used in #7861

Fix environment variable name for 2.6 integration tests

---

src/prefect/orion/models/work_queues.py
src/prefect/orion/schemas/actions.py
src/prefect/orion/schemas/core.py

Adds default value for priority to prevent new agents from breaking with old servers to address the issue raised [here](https://github.com/PrefectHQ/prefect/pull/8350#issuecomment-1413481071).

Adds default value for priority on `WorkQueue` core schema

---

orion-ui/src/pages/WorkPoolQueue.vue

Uses the recentFlowRunFilter instead of runFilter to match the date filter that's applied on work pools and the empty state message. 

BugFix: Use recentFlowRunFilter instead of flowRunFilter

---

src/prefect/orion/models/work_queues.py
tests/orion/models/test_work_queues.py

If the default work pool doesn't exist, then it's possible to get a conflict when creating a work queue named default. The default work pool is created, which creates a queue name default at the same time. This PR adds handling for that case.

Resolves conflict when default work pool doesn't exist

---

orion-ui/src/pages/Flow.vue

This PR makes a simple adjustment to display Runs before Deployments on an individual flow page.  This tab typically will have more interesting activity, and run creation is a simpler activity than deployment creation - displaying the tabs in this way implicitly emphasizes that more.

Swap order of runs and deployments on flow page

---

src/prefect/cli/profile.py
tests/cli/test_profile.py

If you store the following two profiles in `~/.prefect/profiles.toml`:
```yaml
active = "one"
[profiles.one]
PREFECT_ORION_DATABASE_CONNECTION_URL = "one"
[profiles.two]
PREFECT_ORION_DATABASE_CONNECTION_URL = "two"
```
and then run the following CLI:
```
prefect profile use two
```
you will find the following misleading output:
```
No Prefect Orion instance specified using profile 'two'. 
Flow run metadata will be stored at the locally configured database: one
```
This is because the output messages were created prior to the profile switch.  In addition, I believe we should disambiguate between the API and the persistent DB layer where possible, as this separation is key for certain use cases.  
This PR updates the CLI message as can be seen in the example below.
With the same profile …

Clearer output CLI message when switching profiles

---

src/prefect/cli/work_pool.py
tests/cli/test_work_pool.py

Users can't meaningfully interact with work pool types at this time; therefore, we should remove references of `type` especially from all creation logic to avoid confusing users or misleading them into thinking there are options for the value here.

Remove type requirement when creating a work pool via CLI

---

.github/workflows/integration-tests.yaml
flows/agent.py
scripts/run-integration-flows.py

Adds an integration test that creates a deployment, creates a flow run, and starts an agent.
Intended to test cases like https://github.com/PrefectHQ/prefect/pull/8373
```
❯ python flows/agent.py
11:44:05.976 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////Users/mz/.prefect/orion.db
11:44:06.049 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////Users/mz/.prefect/orion.db
11:44:06.106 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////Users/mz/.prefect/orion.db
11:44:06.215 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////Users/mz/.prefect/orion.db
Starting v2.7.10+46.gb3dcf538f2 agent with ephemeral API... …
```

Add coverage for flow run with agent to integration test

---

orion-ui/src/pages/Deployment.vue

Currently the first tab a user sees (if they are on a larger screen) on the deployments page is the description. However, not everyone uses a description. This PR tries out showing the runs tab first instead. Complement to https://github.com/PrefectHQ/nebula-ui/pull/2282

Switch deployment tabs

---

docs/concepts/flows.md
docs/concepts/tasks.md
docs/tutorials/flow-task-config.md
src/prefect/client/orion.py
src/prefect/engine.py
src/prefect/flows.py
src/prefect/orion/api/task_runs.py
src/prefect/orion/models/task_runs.py
src/prefect/orion/schemas/actions.py
src/prefect/tasks.py
tests/test_engine.py
tests/test_flows.py
tests/test_tasks.py

This PR introduces the ability to name your flow and task runs using a dynamic template; names are provided as strings to the respective decorator.  These strings can optionally include references to keyword arguments of the task / flow as the example below demonstrates.  Run names do not need to be unique.
Note that Cloud will need to be updated for this to be compatible, as I had to introduce a new API route and action model.
Closes https://github.com/PrefectHQ/prefect/issues/7463
Closes https://github.com/PrefectHQ/prefect/issues/7579
```python
import pendulum
@task(task_run_name="{greeting}-{name}")
def my_task(name, greeting="hi"):
print(f"{greeting} {name}!")
@flow(flow_run_name="{date:%A}-run")
def my_flow(date):
return my_task(name="chris") …
```

Name your runs

---

docs/concepts/deployments.md

The [Deployment page](https://docs.prefect.io/concepts/deployments/?h=deploy#deployment-build-options) of the Concepts docs do not describe the options for including parameter overrides in the `prefect deployment build` command. I've added `--param` and `--params` to the table, with the descriptions copied from the `prefect.cli.deployment` docs, with minor changes for formatting.
Screenshot of the rendered markdown in the proposed change:
This closes #7510

Updated "deployment build options" in Deployment Concepts to include --param and --params

---

src/prefect/orion/database/migrations/versions/postgresql/2023_01_26_045501_2882cd2df464_create_migration_index.py
src/prefect/orion/database/migrations/versions/sqlite/2023_01_12_000043_f92143d30c25_create_migration_index.py

Thanks to @hateyouinfinity for the excellent bug report.
Addresses the bug raised in https://github.com/PrefectHQ/prefect/issues/8417.
Our artifact migration improperly marked too many states to copy over to the artifact table, causing table bloat and, at times, migrations that might not end. We've implemented the changes suggested in #8417.
Users that have already made it past this migration should don't need to change anything, this change makes it so that users who have not yet upgraded are less likely to need to run a too-large migration.

Properly limit artifact migration to states that have non-null data

---

RELEASE-NOTES.md
src/prefect/cli/work_queue.py
tests/cli/test_work_queues.py

Closes https://github.com/PrefectHQ/prefect/issues/8426
The `prefect work-queue ls` command was using a route to lookup work pools associated with with each of the work queues. This doesn't work without enabling a flag. This wasn't caught by my tests because I was using a fixture that auto-enabled the flag. This is no longer the case. 
Updated video of the changes:
https://www.loom.com/share/c697692aa93e4c2f90c185f23e160fed
Note, it shows two default queues because I have a default-agent-pool and a separate pool with a default queue. I could see this potentially causing confusion. 

Fix error when using `prefect work-queue ls` without enabling work pools

---

src/prefect/blocks/__init__.py
src/prefect/blocks/webhook.py
src/prefect/orion/models/block_registration.py
tests/blocks/test_webhook.py
tests/orion/models/test_block_registration.py

This PR adds a new `Webhook` block type. 
The block allows customizing webhook url, method, and headers. Any payload sent must be explicitly provided at the time of firing.
```
my_webhook = Webhook(
method="POST", url="http://yahoo.com", headers={"authorization": "password"}
)
await my_webhook.call(payload={"example": "json payload"})
```

Add generic webhook block

---

src/prefect/orion/api/server.py
tests/orion/api/test_server.py

Adding an info route that returns the Orion version will be generally useful to maintain client compatibility in the future.

Add Orion info route

---

orion-ui/src/pages/FlowRun.vue

^`FlowRunLogs` component coming from the component library has a much more aggressive poll interval than this component; this was leading to a mismatch in page state

Enhancement: Increase polling interval on flow runs to match logs

---

src/prefect/_internal/compatibility/deprecated.py
src/prefect/settings.py
tests/_internal/compatibility/test_deprecated.py
tests/test_settings.py

Similar to our "experimental" utilities, this adds tooling for marking functions, parameters, fields, and settings as deprecated.
Additional work will be done to facilitate automatic renames of items that are _moved_ rather than _removed_.
```python
from prefect._internal.compatibility.deprecated import deprecated_callable
@deprecated_callable(start_date="Feb 2023", help="Use 'foo' instead.")
def my_function():
pass
my_function()
```
```
example.py:9: PrefectDeprecationWarning: __main__.my_function has been deprecated. 
It will not be available after Aug 2023. Use 'foo' instead.
my_function()
```
```python
from prefect._internal.compatibility.deprecated import deprecated_parameter
@deprecated_parameter(
name="y",
start_date="Feb 2023",
help="Use 'x' instead or provide a smaller value.", …
```

Add utilities for deprecation

---

src/prefect/logging/loggers.py

Some of the code paths return `PrefectLogAdapter`, so updated the main `get_run_logger()` return type to include `logging.LoggerAdapter`.

Update return type for get_run_logger

---

src/prefect/cli/deployment.py
src/prefect/client/orion.py
src/prefect/orion/api/workers.py
src/prefect/settings.py
tests/_internal/compatibility/test_experimental.py
tests/agent/test_agent_run_submission.py
tests/cli/deployment/test_deployment_build.py
tests/cli/deployment/test_deployment_cli.py
tests/cli/test_work_pool.py
tests/cli/test_work_queues.py
tests/client/test_orion_client.py
tests/conftest.py
tests/experimental/cli/test_worker.py
tests/experimental/workers/test_base_worker.py
tests/experimental/workers/test_process_worker.py
tests/orion/api/test_deployments.py
tests/orion/api/test_flow_runs.py
tests/orion/api/test_workers.py
tests/orion/models/test_deployments.py
tests/orion/test_app.py

Removes `/experimental` prefix from `work_pools` routes. Also enables `PREFECT_EXPERIMENTAL_ENABLE_WORK_POOLS` and turns off warnings.

Removes experimental guards around work pools

---

src/prefect/cli/concurrency_limit.py
src/prefect/client/orion.py
src/prefect/orion/api/concurrency_limits.py
src/prefect/orion/models/concurrency_limits.py
tests/client/test_orion_client.py
tests/orion/api/test_concurrency_limits.py
tests/orion/models/test_concurrency_limits.py

Partially addresses zombie concurrency limit slot issues documented in #5995
Here we add a simple CLI utility to reset the active slots on a concurrency limit. Sometimes, task runs might never reach a terminal state due to infrastructure crashes. In these cases the runs may never release concurrency limit slots they have acquired. By resetting a concurrency limit a user can purge all existing runs from holding a concurrency limit slot.
WIP: Still need to add client/CLI tests, but it might be nice to get some QA to see if this feels right @EmilRex 

Dezombify concurrency limits

---

src/prefect/logging/handlers.py
tests/test_logging.py

Issue #8397 reported that they had trouble sending large logs. The `OrionHandler` has some logic for ensuring that it only sends logs below certain size. _However_ it was using `getsizeof` which doesn't return the full size of a dict and was always returning `360` bytes no matter how much data was contained in the log. This updates the logic to use `len(json.dumps(log).encode())` which should more accurately represent the size of the log with respect to how the API will receive it.
Closes #8397  

Use the len of the JSON representation when determining log size

---

src/prefect/client/base.py
tests/client/test_base_client.py

Somehow, this was removed. I noticed this a while ago in a user report and was confused.
```
File "/Users/mz/dev/prefect/src/prefect/client/base.py", line 130, in raise_for_status
raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '422 Unprocessable Entity' for url 'http://127.0.0.1:4200/api/flow_runs/filter'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['body', 'flow_runs', 'state', 'type', 'any_', 0], 'msg': "value is not a valid enumeration member; permitted: 'SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED'", 'type': 'type_error.enum', 'ctx': {'enum_values': ['SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', …
```

Restore Prefect wrapper that shows details on HTTP errors

---

src/prefect/agent.py
tests/agent/test_agent_run_submission.py

Agents were not respecting work queue priority when pulling from multiple queues because the runs were being sorted by `scheduled_start_time`. This PR makes a change to only sort flow runs in the case when no work pool is provided. Otherwise, the order sent by the API is used, which is pre-sorted by priority.

Updates agent logic to respect work queue priority

---

.github/workflows/benchmarks.yaml
.github/workflows/integration-tests.yaml
README.md
docs/concepts/database.md
docs/concepts/logs.md
docs/concepts/schedules.md
docs/contributing/overview.md
docs/faq.md
docs/getting-started/installation.md
docs/getting-started/overview.md
docs/index.md
docs/tutorials/deployments.md
docs/tutorials/docker.md
docs/tutorials/first-steps.md
docs/tutorials/orchestration.md
docs/ui/cloud-local-environment.md
docs/ui/overview.md
src/prefect/cli/__init__.py
src/prefect/cli/_types.py
src/prefect/cli/server.py
src/prefect/settings.py
tests/cli/test_server.py

Part of #8454 
Adds a duplicate command group `prefect server` that does everything `prefect orion` does and adds deprecation notices to all of the `prefect orion` commands. The deprecation notices are implemented in the `PrefectTyper` class to deprecate command groups in the future. The `orion` command is hidden from the `prefect --help` menu. The Typer builtin `deprecated` functionality isn't good enough for me, I tried doing that first and it was harder and less coherent with the rest of our interface.
```
❯ prefect orion start       
WARNING: The 'prefect orion' command group has been deprecated. It will not be available after Aug 2023. Use 'prefect server' instead.
___ ___ ___ ___ ___ ___ _____ 
| _ \ _ \ __| __| __/ __|_   _| 
|  _/   / _|| _|| _| (__  | |  
|_| |_|_\___|_| …
```

Rename `prefect orion` CLI to `prefect server`

---

docs/concepts/work-pools.md
docs/ui/work-pools.md

There are a few broken links in the new work pools documentation.

Fix work pools documentation links

---

orion-ui/index.html
orion-ui/src/compositions/usePageTitle.ts
orion-ui/src/pages/Settings.vue
orion-ui/src/router/index.ts
orion-ui/src/utilities/api.ts

This PR switches to using Prefect Server in the following places in UI:
- Rename web app tabs
- Rename the default web app title
- Rename setting label
- Rename the failsafe title in the router
- Rename the web app name in the "Can't connect" message

Update web app name in UI

---

docs/tutorials/deployments.md

Fix wrong code highlight in config example of deployment. (https://docs.prefect.io/tutorials/deployments/#configure-the-deployment)
Current:
After:
Signed-off-by: Rui Li <me@lirui.org>

Fix code highlight in deployment configuration example

---

.github/workflows/python-tests.yaml
docker-compose.yml
docs/concepts/database.md
docs/concepts/settings.md
docs/faq.md
docs/getting-started/installation.md
docs/tutorials/orchestration.md
src/prefect/settings.py
src/prefect/testing/utilities.py

If `PREFECT_API_DATABASE_CONNECTION_URL` is set, nothing changes here.
Otherwise, the default value is now a SQLite database called `prefect.db`. For backwards compatibility, if the `orion.db` file exists and `prefect.db` does not, we will use that as the default instead. 
No warnings are displayed here, users can keep using the old database name. I'm very hesitant to move the database for the user as it could be in-use.

Update default database to be `prefect.db` instead of `orion.db`

---

ui/src/pages/FlowRunCreate.vue

because `useRouteQueryParam` was giving `{}` for a default value, it was always choosing query params over the deployment params
also was able to remove a seemingly unnecessary type casting

fixed default values on parameters map

---

src/prefect/_internal/concurrency/runtime.py
tests/_internal/concurrency/test_runtime.py

When we called `await self.context.run(self.fn, *self.args, **self.kwargs)` the coroutine would be _created_ within the context but not _run_ within the context. Instead, we must create a new _async task_ with the desired context. This is a little slower, but we need context variables to propagate.

Fix runtime bug where async context vars were not propagated

---

tests/_internal/concurrency/test_primitives.py

Enables the test that was flaking and solves the issue which was actually just a mistake in the test itself not the implementation.
Verified with flake-finder in https://github.com/PrefectHQ/prefect/pull/8515

Fix test bug where `two` did not wait for creation of `event_one`

---

docs/api-ref/overview.md
docs/ui/rate-limits.md
mkdocs.yml

Add a new Prefect Cloud API Rate Limits page documenting API route rate limits.
Also adds a note to the API reference overview page linking to rate limit docs.
[Prefect Cloud API Rate Limits](https://deploy-preview-8529--prefect-docs.netlify.app/ui/rate-limits/)
[API Reference](https://deploy-preview-8529--prefect-docs.netlify.app/api-ref/overview/)

Document Prefect Cloud API rate limits

---

ui/src/pages/FlowRuns.vue

FlowRun count on flowRun dashboard doesn't have background in prefect server
Was:
Now:
Closes https://github.com/PrefectHQ/prefect-ui-library/issues/1155

Add background to FlowRun count on flowRun dashboard

---

src/prefect/cli/deployment.py
tests/cli/deployment/test_deployment_build.py
tests/cli/deployment/test_deployment_cli.py

Setting the `anchor_date` when setting a schedule via the CLI was not working. This fix enables the `anchor_date` to be correctly parsed when passed in alongside the `--interval` arg.
```bash
prefect deployment set-schedule flows/my_flow --interval "1800" --anchor-date "2040-01-01"
```
Results in error:
```
File "/Users/bean/code/prefect/src/prefect/cli/_utilities.py", line 41, in wrapper
return fn(*args, **kwargs)
File "/Users/bean/code/prefect/src/prefect/utilities/asyncutils.py", line 230, in coroutine_wrapper
return run_async_in_new_loop(async_fn, *args, **kwargs)
File "/Users/bean/code/prefect/src/prefect/utilities/asyncutils.py", line 181, in run_async_in_new_loop
return anyio.run(partial(__fn, *args, **kwargs))
File …
```

Fix ability to use anchor date when setting an interval schedule with the `prefect set-schedule` command

---

src/prefect/cli/deployment.py
tests/cli/deployment/test_deployment_cli.py

This enhancement:
1. Allows support for either a valid RRule string or dictionary (we currently only support the latter).
2. Handles each type of schedule more explicitly and checks for and returns clearer error messages sooner to the user, which builds slightly off of interval handling adjustments here: https://github.com/PrefectHQ/prefect/pull/8524. 
Currently, when using `prefect deployment set-schedule` to add or update a schedule on a deployment, you must pass in a JSON string to the `--rrule` option, like so: 
```python
prefect deployment set-schedule 'flow-name/deployment-name' \
--rrule '{"rrule": "DTSTART;TZID=America/Chicago:20221027T124000\nRRULE:FREQ=DAILY", \
"timezone": "America/Chicago"}'
```
One user describes their pain point around this here: …

Add ability to pass in RRule string to `--rrule` option in `prefect set-schedule` command

---

RELEASE-NOTES.md

Adds 2.8.1 release notes section describing orion rename.
[Preview](https://github.com/PrefectHQ/prefect/blob/2.8.1-release-notes/RELEASE-NOTES.md)

Add release notes for 2.8.1

---

src/prefect/client/orchestration.py
src/prefect/engine.py
src/prefect/settings.py
src/prefect/testing/fixtures.py
tests/cli/test_version.py
tests/client/test_orion_client.py
tests/events/test_cloud_events_client.py

This adds an `events` method to `PrefectClient` that will initialize and enter the context of an EventClient. The type of event client depends on the `server_type` being used by the PrefectClient. Only `cloud` will get a 'working' EventClient, all others will get a NullEventClient that is a no-op. Also added to `PrefectClient` is a `disconnect_events` method that will ensure that the events client context is exited and that the PrefectClient no longer maintains a reference to the EventsClient. The engine also calls `disconnect_events` whenever we're exiting orchestration of a task/flow so that we ensure that any open connections to Cloud's websocket endpoint are closed. …

Hook events client into PrefectClient and ensure that its torn-down when needed.

---

src/prefect/__init__.py
tests/test_plugins.py

This PR re-enables plugin loading in `__init__.py__`.
With prefect 2.8.1, trying to run a flow using an `AzureContainerInstanceJob` block (or any other infrastructure block from a collection) results in an error message like `Submission failed. KeyError: “No class found for dispatch key ‘azure-container-instance-job’ in registry for type ‘Block’`. 
1. Install Prefect 2.8.1.
2. Try to run a deployed flow using ACI, ECS, or a Cloud Run Job.
3. Verify that you see a `KeyError` like the one shown above.
4. Install the `re-enable-plugin-loading` branch. 
5. Try to run the flow from step 2 again. 
6. Verify that it now runs as expected and does raise a `KeyError`. 
* Tested a flow deployed to Azure blob storage using `AzureContainerInstanceJob` 
* It failed with a `KeyError` on 2.8.1. 
* It …

Enable plugin loading in `prefect` module init

---

src/prefect/tasks.py

This incorrectly suggested a list of awaitables was returned instead of an awaitable that returns a list.
Prompted by https://prefect-community.slack.com/archives/C03D12VV4NN/p1676981132883279

Fix `Task.map` type hint for async tasks

---

src/prefect/engine.py
src/prefect/utilities/collections.py
tests/utilities/test_collections.py

Adds a `StopVisiting` signal that can be raised in a visit function to prevent further recursion then adds usage of it to input parameter resolution. Previously, we would recurse into objects and just not modify them if they were quoted. Quoting is much more useful if we avoid traversing the object though.

Update `quote` handling in input resolution to skip descending into the quoted expression

---

src/prefect/_internal/concurrency/from_async.py
src/prefect/_internal/concurrency/from_sync.py
tests/_internal/concurrency/test_api.py

In practice, we do not actually care if it is the main thread we just want to be able to pass work to the supervisor.

Update `call_soon_in_main_thread` to `call_soon_in_supervising_thread`

---

src/prefect/infrastructure/kubernetes.py
tests/infrastructure/test_kubernetes_job.py

Closes https://github.com/PrefectHQ/prefect/issues/8563
See discussion in issue for details. The Kubernetes job timeout was only being started _after_ streaming logs which meant that timeout was not applying to the full runtime of the job. Now if the timeout is exceeded while streaming logs, we will stop streaming logs and exit. We will also correctly enforce the timeout if we stream logs for some period of time then begin watching for job completion.

Fix Kubernetes job watch timeout when streaming logs

---

netlify.toml

Redirect from old Cloud Getting Started URL to new Cloud Quickstart tutorial
[/ui/cloud-getting-started/](https://deploy-preview-8622--prefect-docs.netlify.app/ui/cloud-getting-started/) should now redirect to /ui/cloud-quickstart/

Redirect from old Cloud Getting Started page

---

docs/concepts/deployments.md
docs/concepts/work-pools.md

Removes outdated notes about changes to agents and deployments from beta releases. 
Also adds `--pool` to deployment example and fixes errors, missing items in deployments and agents options tables.
Previews:
- [Deployments](https://deploy-preview-8630--prefect-docs.netlify.app/concepts/deployments/)
- [Agents & Work Pools](https://deploy-preview-8630--prefect-docs.netlify.app/concepts/work-pools/)

Remove beta notes regarding agents and deployments

---

src/prefect/_internal/concurrency/from_async.py
src/prefect/_internal/concurrency/from_sync.py
src/prefect/_internal/concurrency/supervisors.py

This allows the supervisor to track the thread the supervised future is executing on, which is essential for cancellation handling. This also has the benefit of clarifying the supervisor interface and reducing the responsibilities of users of the supervisor.

Refactor supervisors to manage submission

---

src/prefect/_internal/concurrency/from_async.py
src/prefect/_internal/concurrency/from_sync.py
src/prefect/_internal/concurrency/supervisors.py
tests/_internal/concurrency/test_supervisors.py

```python
import concurrent.futures
import threading
import pytest
from prefect._internal.concurrency.supervisors import AsyncSupervisor, SyncSupervisor
def fake_submit_fn(__fn, *args, **kwargs):
future = concurrent.futures.Future()
future.set_result(__fn(*args, **kwargs))
return future
def fake_fn(*args, **kwargs):
pass
supervisor = SyncSupervisor(submit_fn=fake_submit_fn)
print(repr(supervisor))
supervisor.submit(fake_fn, 1, 2)
print(repr(supervisor))
```
```
<SyncSupervisor submit_fn='fake_submit_fn', owner='MainThread'>
<SyncSupervisor submit_fn='fake_submit_fn', submitted='fake_fn', owner='MainThread'>
vs previously
<SyncSupervisor(id=140242493845264, owner=8633447104)>
<SyncSupervisor(id=140242493845264, owner=8633447104)>
```

Improve supervisor repr for debugging

---

src/prefect/_internal/concurrency/supervisors.py
src/prefect/_internal/concurrency/timeouts.py
tests/_internal/concurrency/test_supervisors.py
tests/_internal/concurrency/test_timeouts.py

Adds timeout handling to supervisors.
Supervisors can be created with a `timeout`. The timeout will start when the future submitted to the supervisor begins running. The timeout will be enforced for both synchronous and asynchronous work that the future represents. The timeout will also be enforced on work sent _back_ to the supervising thread by the supervised call, ensuring that the supervising thread never waits for a result longer than the timeout.
Timeouts are implemented in three ways:
- Asynchronous cancel scopes (async only)
- Alarm signal (main thread only — can notably interrupt sys calls)
- Watcher threads
```python
import concurrent.futures
import time
from prefect._internal.concurrency.supervisors import SyncSupervisor
def slow_worker():
for _ in range(100):
time.sleep(0.1) …
```

Add timeout support to supervisors

---

src/prefect/server/database/orm_models.py
src/prefect/server/models/flow_runs.py

Following best practice for performance, this PR changes SQLA lazy-loads from "joined" to "selectin". Joined loads _can_ be better, especially for many-to-one relationships, but they rewrite the query in ways that can have performance implications for Prefect's typical use patterns. Selectin shows significant performances gains. See also https://github.com/PrefectHQ/nebula/pull/3840 and https://github.com/PrefectHQ/nebula/pull/3842.

Change lazy loads from joined to selectin

---

src/prefect/cli/deployment.py
src/prefect/deployments.py
tests/cli/deployment/test_deployment_build.py
tests/test_deployments.py

Closes #7956
Exposed the `--description` flag for the `deployment build` CLI command. 
The behavior previously was to default to the description for the flow this deployment corresponds to.
Previously you'd run the `deployment build` command as:
```bash
deployment build fake-path.py:fn -n <deployment_name> -o <output-file-name>.yaml
```
And it would take the description from the flow defined in `fake-path.py`. 
Now, you can pass it:
```bash
deployment build fake-path.py:fn -n <deployment_name> -d <deployment-description> -o <output-file-name>.yaml
```
And you'll be able to explicitly set the description for the deployment.

Add description flag to prefect deployment build CLI command

---

netlify.toml

Adds Content-Security-Policy, Permissions-Policy, and other browser security features for https://docs.prefect.io

Add security headers for docs

---

src/prefect/cli/deployment.py
src/prefect/deployments.py

https://github.com/PrefectHQ/prefect/pull/8603 accidentally broke loading of an existing description from the server by always providing the description kwarg.

Fix loading of existing deployment descriptions from the server

---

src/prefect/server/orchestration/rules.py
tests/server/orchestration/test_rules.py

This PR improve task run-level results tracking by adding the task runs parent flow run id to the orchestration artifact. 
Also adds a bit of test coverage for result <> run tracking since I couldn't find that anywhere.

Enhancement: Track flow run id when generating task run results

---

tests/infrastructure/test_kubernetes_job.py

Closes https://github.com/PrefectHQ/prefect/issues/8677; reproduced with flake-finder at 50 iterations locally. The initial sleep can be significantly less than 1 on a slow run.

Increase tolerance for `test_watch_timeout_is_restarted_until_job_is_complete`

---

src/prefect/infrastructure/kubernetes.py

The normal clock should not be used as it could change during drift correction or daylight-savings time. May help with https://github.com/PrefectHQ/prefect/issues/8677

Use a monotonic clock for Kubernetes job watch timeout deadline calculation

---

src/prefect/blocks/abstract.py
src/prefect/blocks/core.py
src/prefect/blocks/notifications.py
src/prefect/events/clients.py
src/prefect/events/instrument.py
src/prefect/events/worker.py
tests/events/conftest.py
tests/events/test_block_events_instrumentation.py
tests/events/test_events_instrument.py
tests/events/test_events_worker.py

This adds basic support for sending events when a methods on a block are called. It's supported via decorators that decorate each method of a class and use the `EventsWorker` to emit events when one of those methods are called. The class itself supplies the main `kind` as well as the bulk of the resource and related resources.
Related to #8672 
```python
from pydantic import SecretStr
from prefect.blocks.system import Secret
secret = Secret(value=SecretStr("I'm hidden!"))
await secret.save("top-secret", overwrite=True)
secret = await Secret.load("top-secret")
secret.get()
```
Would result in three events being emitted, one for each method call to the
Secret block:
```
Event(
occurred=...,
event='prefect.block.secret.save.called',
resource=Resource(__root__={'prefect.resource.id': …
```

Add basic event instrumentation to blocks

---

netlify.toml

Chore: Don't use a path for mkdocs package CSP

---

src/prefect/_internal/concurrency/api.py
src/prefect/_internal/concurrency/supervisors.py
tests/_internal/concurrency/test_supervisors.py

All changes are internal to the `supervisors` module.
- Combine `WorkItem` and `Call` classes
- Update `Call.__call__` to use `Call.run` behind the scenes
- Improve `Call.run` handling of async

Consolidate `WorkItem` and `Call` classes

---

src/prefect/events/worker.py
tests/events/test_events_worker.py

When connecting to Cloud's events API via the events worker the events client was getting a 400, this turned out to be because the worker was using the `PREFECT_CLOUD_API_URL` instead of the `PREFECT_API_URL`.

Use `PREFECT_API_URL` when initializing events client

---

ui/src/pages/ConcurrencyLimit.vue
ui/src/pages/Deployment.vue
ui/src/pages/TaskRun.vue

Updates the Deployment and ConcurrencyLimit pages to use the new `useTabs` composition return value properly instead of trying to map on an object. 
Resolves: #8712

Bugfix: Deployment and ConcurrencyLimit pages tabs

---

src/prefect/cli/cloud.py

Otherwise, when I attempted to use the `prefect cloud login` CLI command it would not let me move forward.
`ENTER` on my machine actually sent `CR` then `CTRL_M`; no idea what's up with that maybe it's a readchar bug?
```
❯ pip show readchar          
Name: readchar
Version: 4.0.3
```

Add carriage return to `prompt_select_from_list`

---

src/prefect/_internal/concurrency/timeouts.py
tests/_internal/concurrency/test_timeouts.py

Adds a `chain` method to `CancelContexts` allowing cancelled marks to be propagated upstream. This will be required for adding a `cancelled` attribute to `Call` objects in supervisors since they can be cancelled by multiple implementations (sync / async); this is, in turn, required for only reporting cancellations caused by us as flow run timeouts in #8702.

Add chaining to cancel contexts

---

src/prefect/blocks/core.py
src/prefect/events/instrument.py
tests/events/test_block_events_instrumentation.py
tests/events/test_events_instrument.py

While testing out the block events we found that while the `name` of the block document was nicely human-readable it didn't provide an easy way to hook back into the API to get the block document itself. This updates the block events to emit the document id as the resource id and include the name as a label.

Update block event resource IDs to use block-document id instead of name.

---

src/prefect/_internal/concurrency/calls.py
src/prefect/_internal/concurrency/timeouts.py
src/prefect/_internal/concurrency/waiters.py
tests/_internal/concurrency/test_timeouts.py
tests/_internal/concurrency/test_waiters.py

Uses chaining introduced in #8719 to add cancellation reporting to calls
- Adds `CancelContext.mark_completed()` to avoid reporting completed items as cancelled in chains
- Adds lock to `CancelContext` to avoid completed/cancelled race conditions
- Updates `CancelContext.cancelled` to be a method instead of a property since it takes a lock
- Adds `Call.cancelled()` and `Call.cancel_context` to track cancellation of calls
- Adds reporting of cancelled callbacks to `Waiter`
All this is to allow us to determine if a call was cancelled due to exceeding its timeout, which will allow us to report flows as `TimedOut` correctly in #8702 
```python
import time
from prefect._internal.concurrency.calls import Call
call = Call.new(time.sleep, 5)
call.set_timeout(1)
call.run()
print(call.cancelled()) …
```

Add cancellation reporting to calls and waiters

---

src/prefect/cli/deployment.py
tests/cli/deployment/test_deployment_build.py
tests/cli/deployment/test_deployment_cli.py
tests/fixtures/database.py

Updates suggested command output when applying a deployment to prompt the user to start a worker. If a deployment is assigned to a work pool whose type is not `prefect-agent`, then the `prefect worker start -p {deployment_work_pool_name}` command is displayed with an extra suggestion to the user to enable the experimental setting for the workers group to make sure that the worker CLI is accessible.
Applying a deployment associated with a `prefect-agent` work pool
```bash
> prefect deployment apply print_my_env-deployment.yaml
Successfully loaded 'test-env-flow'
Deployment 'print-my-env/test-env-flow' successfully created with id 'ef341f28-2d41-4084-8666-75e1c43ffe32'.
...
To execute flow runs from this deployment, start an agent that pulls work from the 'default-agent-pool' work pool:
$ …
```

Adds worker command output when applying deployments with a work pool

---

src/prefect/_internal/concurrency/timeouts.py
tests/_internal/concurrency/test_timeouts.py
tests/_internal/concurrency/test_waiters.py

After much annoyance adjusting tests that used subsecond timeouts, I figured out how to make float values work with alarm based timeouts.
See https://docs.python.org/3/library/signal.html#signal.ITIMER_REAL and https://docs.python.org/3/library/signal.html#signal.setitimer

Add support for float timeouts using alarms

---

tests/server/database/test_migrations.py

- Skip backfill test on SQLite (takes ~60s vs ~6s on Postgres)
- Add service test mark to database migration test to run in separate job (takes ~60s)

Improve CI time for migration tests

---

docs/tutorials/storage.md

Was `-p` should have been `-q`.
It seems that the docs haven't been updated since work pools were introduced.

Corrected typo in Storage.md

---

requirements.txt

This appears to have a breaking change and we can try to avoid releasing it to our users https://github.com/PrefectHQ/prefect/issues/8710

Ignore fsspec `2023.3.0` during requirements installation

---

src/prefect/cli/flow_run.py

fixed the message which now reads ```Cancel a flow run by ID```
Closes #8740 

Fix `prefect flow-run cancel` help

---

tests/cli/test_start_server.py

Similar to #8745 these tests are slow and can be run on another job for an overall speed increase.

Run uvicorn signal forwarding tests in service test suite

---

src/prefect/results.py
src/prefect/states.py
tests/results/test_flow_results.py
tests/results/test_task_results.py
tests/results/test_unpersisted_result.py
tests/test_flows.py
tests/test_states.py

Previously, when results were not persisted no artifact would be sent to the API unless the return value was `None`. This can cause confusing behavior i.e. the presence of a return value of the task or flow can affect restart behavior. It also leads to a less than ideal experience with the upcoming result and artifact display in the UI. In general, result persistence needed to be enabled to see any information about the results in the UI; unless your task or flow returned `None`, then we'd show a result in the UI. This behavior made it challenging to set expectations about what user action was required to see results in the UI.
Here, instead of leaning on `LiteralResult(None)` to distinguish between unpersisted results and null return values, we introduce an `UnpersistedResult` class. …

Add artifacts for unpersisted results

---

src/prefect/server/database/alembic.ini
src/prefect/server/database/migrations/env.py
tests/server/database/test_migrations.py

Test was timing out but the error is obscured  because of bad interaction between what this test is doing, it failing and flaky
---
`test_orion_full_migration_works_with_data_in_db` was failing in CI more often then not with an error similar to:
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table flow_run has no column named work_queue_id
[SQL: INSERT INTO flow_run (id, created, updated, name, state_type, state_name, state_timestamp, run_count, 
expected_start_time, next_scheduled_start_time, start_time, end_time, total_run_time, deployment_id, work_queue_name,
flow_version, parameters, idempotency_key, context, empirical_policy, tags, created_by, infrastructure_pid, auto_scheduled,
flow_id, infrastructure_document_id, parent_task_run_id, state_id, work_queue_id) VALUES …
```

fix `test_orion_full_migration_works_with_data_in_db`

---

src/prefect/server/database/configurations.py

Duplicate of https://github.com/PrefectHQ/prefect/pull/8803 authored by @jakekaplan — based on `main` instead of #8702 
We've seen timeouts in tests running against Postgres servers and massive slowdowns when running Postgres 14 vs 13. 
A possible cause is https://lightrun.com/answers/magicstack-asyncpg-slow-introspection-when-using-multiple-custom-types-in-a-query
We've confirmed that JIT is enabled in 13 by default as well as 14 so it would probably need to be a specific change to JIT behavior in 14.

Disable Postgres JIT

---

src/prefect/testing/fixtures.py
tests/cli/test_version.py
tests/client/test_orion_client.py
tests/engine/reliability/test_deadlocks.py
tests/infrastructure/test_base.py
tests/infrastructure/test_docker_container.py
tests/infrastructure/test_kubernetes_job.py
tests/test_deployments.py

Renames to exclude `orion` and uses `unused_tcp_port` fixture to find a free port.
A factory is used (https://pytest-asyncio.readthedocs.io/en/latest/reference/fixtures.html#unused-tcp-port-factory) since we're using a session scoped fixture.

Cleanup fixture for hosted API server

---

src/prefect/results.py
tests/results/test_unpersisted_result.py

This PR changes how we stringify unpersisted result types by calling `str` instead of `repr` in the description and adding backticks (`). This creates a markdown-enabled string and removes the single quotes that python automatically wraps the type with otherwise.
**Before:**
**After:**

Enhancement: Call `str` instead of `repr` on UnpersistedResult descriptions

---

src/prefect/server/orchestration/core_policy.py
tests/server/api/test_task_runs.py
tests/server/orchestration/test_core_policy.py

Some users choose to run Dask workers on ephemeral infrastructure like EC2 spot instances, as reported in https://github.com/PrefectHQ/prefect/issues/8602. Sometimes, this infrastructure disappears without giving Prefect the opportunity to gracefully handle the shutdown - instead, Dask itself will [retry the task](https://github.com/dask/distributed/blob/main/distributed/distributed.yaml#L12).
The abrupt shutdown, combined with Dask retrying the task without giving Prefect an opportunity to gracefully terminate the task, leave the task in a RUNNING state, causing an error when retrying: `This run cannot transition to the RUNNING state from the RUNNING state. Task run is in RUNNING state`.
The issue also appears to happen when running Ray on spot instances: …

Remove `PreventRedundantTransitions` rule from core task orchestration policy

---

tests/events/test_events_worker.py

This fixes the `test_controls_client_and_thread_lifecycle` test. I think the test had an artifact from an older version of the code and was emitting `None` which now means that the worker should shut down, but then we're asserting that it's alive which is, unsurprisingly, failing. I ran this version in a loop 25 times and didn't see it fail, but was able to reproduce the failure every ~5th iteration before the fix.
Closes #8764 

Fix flaky `test_controls_client_and_thread_lifecycle` test

---

src/prefect/experimental/workers/base.py
src/prefect/server/schemas/core.py
src/prefect/utilities/templating.py
tests/experimental/workers/test_base_worker.py
tests/experimental/workers/test_process_worker.py
tests/server/api/test_workers.py
tests/server/schemas/test_core.py
tests/utilities/test_templating.py

Updates to the worker base job template templating logic to allow for placeholders to be placed into nested values within a JSON structure. Previously, attempts to create a work pool with a nested placeholder would fail validation. Once a work pool was created with a base job template that had a nested placeholder, the placeholders nested within dictionaries and lists would not be correctly replaced. This PR updates the placeholder replacement process to recursively walk a job configuration and replace all discovered placeholders.
Also adds functionality to resolve block document references within the variables supplied to populate a job configuration.
This PR supports the complexity of the default base job template for the kubernetes worker.
For a worker job configuration class with a …

Update to worker base job template logic for nested placeholders

---

src/prefect/server/models/block_documents.py
tests/server/models/test_block_documents.py

Fixes a bug where a block document's secret values would be lost if the block document's data was updated with `merege_existing_data=False`. This behavior was seen in the UI since the UI sends back an obfuscated value for a secret if its value has not changed.

Fixes saving block document secrets that have not been modified

---

src/prefect/cli/dev.py

Running `prefect dev start` on `main` leads to the following error: 
```bash
❯ prefect dev start
Running: uvicorn --factory prefect.server.api.server:create_app --host 127.0.0.1 --port 4200 --log-level debug
Installing npm packages...
Creating hot-reloading agent process...
File "/Users/bean/code-oss/prefect/src/prefect/cli/_utilities.py", line 41, in wrapper
return fn(*args, **kwargs)
File "/Users/bean/code-oss/prefect/src/prefect/utilities/asyncutils.py", line 260, in coroutine_wrapper
return call()
File "/Users/bean/code-oss/prefect/src/prefect/_internal/concurrency/calls.py", line 245, in __call__
return self.result()
File "/Users/bean/code-oss/prefect/src/prefect/_internal/concurrency/calls.py", line 173, in result
return …
```

Fix `prefect dev start`

---

requirements.txt
setup.cfg
src/prefect/cli/cloud.py
src/prefect/server/api/server.py
tests/client/test_orion_client.py

Replace the usage of deprecated arguments `on_startup` and `on_shutdown` with `lifespan` in the FastAPI constructor 
Closes #8786 

Update to use lifespan context manager as parameter in FastApi

---

src/prefect/client/base.py
src/prefect/settings.py
src/prefect/utilities/math.py
tests/client/test_base_client.py

Adds jitter to the Prefect base client when retrying requests.
Uses a Poisson interval with a shifted average for responses with "Retry-After" headers to ensure we never retry sooner than requested. Otherwise, we use a Poisson interval with an average matching our previous exponential back-off. A setting is added to control the amount of jitter (can be disabled with a value of 0) which defaults to +/- 20%.

Add jitter to Prefect client request retries

---

src/prefect/engine.py
src/prefect/utilities/callables.py
tests/test_tasks.py

Prompted by https://prefect-community.slack.com/archives/CL09KU1K7/p1673994869243719
Currently, if you have a task with variadic keyword arguments (i.e. `**kwargs`) it cannot be used with mapping: a mapping length mismatch error will be raised. This occurs because when we cast the call arguments and keyword arguments to _parameters_, we capture the variadic options in a "kwargs" key. 
To resolve this, we need to expand the parameter key (i.e. "kwargs") during length checks. This pull request adds utilities to explode and collapse variadic parameters which are used during mapping to ensure that we are performing length checks on the actual arguments that would be passed to the function.
Instead of checking the lengths of `{'x': [1, 2], 'kwargs': {}}` we check `{'x': [1, 2]}` and  instead …

Add support for variadic keyword arguments to `Task.map`

---

src/prefect/server/schemas/actions.py
tests/server/api/test_artifacts.py

OSS implementation of: https://github.com/PrefectHQ/nebula/pull/4002
Users specify the key field when creating an artifact but we only want to allow lowercase key values.
Also see: https://github.com/PrefectHQ/nebula/pull/3971#issuecomment-1458876332

Enforce lowercase artifact `key` field

---

src/prefect/settings.py
tests/_internal/compatibility/test_experimental.py
tests/events/test_events_worker.py
tests/server/test_app.py

This turns the events client experimental flag on by default.
Closes #8869

Enable events client experimental flag by default

---

src/prefect/engine.py
tests/test_engine.py

closes: https://github.com/PrefectHQ/prefect/issues/8825
Previously `propose_state` made a recursive call to itself when it received a `SetStateStatus.WAIT` as response. In extreme cases where a flow ran with a lot of tasks and a very low concurrency limit, the server could instruct a task to keep waiting and making new recursive `propose_state` calls until the maximum recursion depth is exceeded.
This pr moves the recursive call into a loop instead.

remove recursion from `propose_state`

---

src/prefect/server/database/migrations/MIGRATION-NOTES.md
src/prefect/server/database/migrations/versions/postgresql/2023_03_20_175243_aa84ac237ce8_remove_artifact_uq.py
src/prefect/server/database/migrations/versions/sqlite/2023_03_20_153925_1d7441c031d0_remove_uq_from_artifact_table.py
src/prefect/server/database/orm_models.py
tests/server/api/test_artifacts.py

OSS implementation of: https://github.com/PrefectHQ/nebula/pull/3971
Since we want to be able to have multiple artifacts with a single key, we need to remove the unique constraint from the artifact table.

Allow multiple artifacts to have the same key

---

flows/flow_pauses.py
src/prefect/engine.py

The client was not being injected into these methods correctly which caused it to be pulled from the context when it should not have been. An integration test for this feature has been added.
Closes https://github.com/PrefectHQ/prefect/issues/8878

Fix flow run pauses

---

tests/public/tasks/test_task_timeouts.py

This assertion was still < 1s instead of the variable sleep time constant which caused it to flake in CI

Fix sleep time assertion

---

src/prefect/_internal/concurrency/threads.py

Fixes race condition where thread.start() would return but not set the thread as started until a bit later. See 'https://github.com/PrefectHQ/prefect/actions/runs/4494685885/jobs/7907472976?pr=8882'

Fix race condition in worker thread start

---

src/prefect/engine.py
tests/engine/reliability/test_deadlocks.py

Updates the two major engine methods `collect_task_run_inputs`  and `resolve_inputs` to avoid creating worker threads. Instead, we run `visit_collection` without performing blocking calls! In `collect_task_run_inputs`, we now just collect futures then wait for them to be submitted after the collection has been traversed. For `resolve_inputs`, we're actually mutating the collections so this requires two traversals of the inputs so we can first collect all states and futures then resolve them asynchronously before updating the value in the collection.
Task run scaling which was previously bounded by the AnyIO worker thread limit (~250 https://github.com/PrefectHQ/prefect/pull/7961) which caused the engine to easily deadlock when we were doing too much synchronous work. In #8702, we moved …

Update task input resolution to avoid spawning worker threads

---

docs/concepts/index.md

Not upset to get shot down on this change, it's just been mildly annoying for a while so I figured I'd throw it out there.

disambiguate reference to "Blocks"

---

docs/concepts/results.md
src/prefect/results.py
src/prefect/tasks.py
tests/results/test_persisted_result.py
tests/results/test_task_results.py
tests/test_tasks.py

Closes https://github.com/PrefectHQ/prefect/issues/8894
New documentation at https://deploy-preview-8924--prefect-docs.netlify.app/concepts/results/#result-storage-key
Only allows static keys at this time. A follow-up can add support for templating keys with task run parameters by default. An additional follow-up can add support for providing a callable directly instead of a string.
Could also be accomplished by #8580 but I think that's a bit too low level to do first.
```python
from prefect.serializers import JSONSerializer
@task(persist_result=True, result_storage_key="foo.json")
def hello_world():
return "hello world"
@flow(result_serializer=JSONSerializer())
def my_flow():
hello_world()
my_flow()
```
```
❯ cat ~/.prefect/storage/foo.json | jq
{ …
```

Add support for custom static task storage keys

---

src/prefect/runtime/flow_run.py
tests/runtime/test_flow_run.py

Extends #8947 
Closes https://github.com/PrefectHQ/prefect/issues/8941
```python
import prefect.runtime
@flow(name="test")
def my_flow():
print(prefect.runtime.flow_run.flow_name)
my_flow()
```
```
11:48:33.097 | INFO    | prefect.engine - Created flow run 'shrewd-chihuahua' for flow 'test'
test
11:48:33.202 | INFO    | Flow run 'shrewd-chihuahua' - Finished in state Completed()
```

Add flow name support to `prefect.runtime.flow_run`

---

docs/concepts/work-pools.md

fix for missing ``` in work-pools.md, that was messing up the display.
This was before:
This is after (screenshot taken from VSCode preview):

docs: fix missing ``` in work-pools.md

---

src/prefect/runtime/flow_run.py
tests/runtime/test_flow_run.py

The flow run id can be retrieved from the task run object in a task run context if a flow run context is not available. This is important for runtime information to be accessible when running tasks on distributed workers and will ensure storage keys in https://github.com/PrefectHQ/prefect/pull/8949 are formatted correctly in that case.

Add retrieval of flow run id in `prefect.runtime.flow_run` from task run contexts

---

docs/concepts/results.md
src/prefect/__init__.py
src/prefect/context.py
src/prefect/engine.py
src/prefect/results.py
src/prefect/runtime/__init__.py
src/prefect/runtime/task_run.py
tests/results/test_task_results.py
tests/runtime/test_task_run.py
tests/test_context.py

Extends #8924 
Closes https://github.com/PrefectHQ/prefect/issues/8239
Adds dynamic task storage keys with formatting from parameters and the `prefect.runtime` modules. Instead of explicitly passing format variables through to the result factory, it adds a `prefect.runtime.task_run` module to pull from and adjusts the scope of the task run context so that it is available during result creation 
Read the docs https://deploy-preview-8949--prefect-docs.netlify.app/concepts/results/#result-storage-key or this example:
```python
from prefect.serializers import JSONSerializer
@task(
persist_result=True,
result_storage_key="{flow_run.flow_name}__hello-{parameters[name]}.json",
)
def hello_world(name: str = "world"):
return f"hello {name}" …
```

Add formatting of task storage keys and `prefect.runtime.task_run` module

---

.github/workflows/docker-images.yaml
Dockerfile

Explores adding additional image flavors for major deployment providers to our Docker image publishing step. Here, we add a `kubernetes` flavor image with `prefect-kubernetes` installed.

Add publish of Kubernetes flavored Docker images with `prefect-kubernetes`

---

src/prefect/cli/__init__.py
src/prefect/client/orchestration.py
src/prefect/experimental/cli/artifact.py
tests/client/test_orion_client.py
tests/experimental/cli/test_artifact.py

Adds initial artifact CLI with command `ls`.
Create an artifact:
```python
from prefect.experimental.artifacts import create_markdown_artifact
@flow
def my_flow():
create_markdown_artifact(
key="my-first-artifact",
markdown="## my markdown",
description="This is my most important artifact",
)
my_flow()
```
Then run:
```bash
prefect config set PREFECT_EXPERIMENTAL_ENABLE_ARTIFACTS=True
prefect artifact ls
```

Adds experimental artifacts `prefect artifact ls` command

---

src/prefect/server/api/server.py
tests/server/api/test_server.py

Return a 503 error if the sqlite db is locked due to other connections accessing it. This will let the client retry with exponential backoff so the connections will all eventually resolve instead of erroring and returning 500s

Retry on sqlite operational errors

---

docs/stylesheets/extra.css
mkdocs.yml

This PR includes two minor changes to prepare for docs versioning:
- Makes a CSS selector more specific so we can hide the site title as intended without _also_ hiding the version selection box.
- Adds two `mike` configuration options to `mkdocs.yml`.
Neither of these changes impact the current non-versioned docs. They still build and display as expected. The changes only make a difference when `mike` is used to build versioned docs.
Before: 
Expected: Version selector. Actual: No version selector. 😢 
After:
Expected: Version selector. Actual: Version selector! 😃 
Also after, as a result of the config changes:
Canonical links will point to the latest docs, avoiding penalties for duplicate content and keeping duplicate copies of docs pages out of search results. 
- If no issue exists and …

Update docs CSS and config for versioning compatibility

---

.github/ISSUE_TEMPLATE/5_docs_ticket.yaml

Inspired by Ryan P to create a new Issues template specific to docs edits/changes.
following same .yaml template for the existing 4 templates...
e.g.
- type: textarea
attributes:
label: Paste the relevant docs section URL here
description: If the issue applies to more than one section, please choose a representative example and paste that URL
validations:
required: true
-->

docs: adding .yaml template for efficient creation of docs Issues

---

.github/workflows/stale.yml

- Enable stale pull requests after 60 days
- Bump stale bot operations to 500/hr; previously this was 60/hr to avoid reaching our GitHub API request limit but that actually appears to be 15,000/hr so we should be safe with this and I want to work through the backlog

Enable stale pull requests and increase ops/hr

---

docs/concepts/filesystems.md

This PR updates the filesystem docs to clarify when EXTRA_PIP_PACKAGES works and when it does not.

Adding clarity to Filesystem package dependencies

---

docs/stylesheets/extra.css
mkdocs.insiders.yml

As @thomas-te pointed out in #8945, code blocks in the docs don't have a 'copy to clipboard' button. This is a valuable feature because it would let users quickly copy code samples from the docs to test and use for themselves.
This PR enables a clipboard copy button for all code blocks in the documentation.
Closes #8945.
**Before:** Hover over code box, no copy button forthcoming 😭 
**After:** Hover over code box and summon a copy button from the ether 🪄 
**Also After:** Click on the button, and a success message appears! It's more prominent when it first appears, but it fades away quickly, so by the time I grabbed a screenshot the message was well on its way to vanishing.
- Attempted to run docs locally using `mkdocs serve -f ./mkdocs.insiders.yml`
- Was annoyed at Mkdocs Insiders social …

Add copy to clipboard button in documentation code blocks

---

src/prefect/engine.py
src/prefect/tasks.py
tests/test_tasks.py

Closes https://github.com/PrefectHQ/prefect/issues/9020
Previously we treated iterable defaults as mapped parameters. However, default values should never be mapped over and should always be treated as `unmapped`. 
```python
@task
def add_some(x, y=[1, 4]):
return x + sum(y)
@flow
def my_flow():
numbers = [1, 2, 3]
return add_some.map(numbers)
```
Example previous failure:
```
prefect.exceptions.MappingLengthMismatch: Received iterable parameters with different lengths.
Parameters for map must all be the same length. Got lengths: {'x': 3, 'y': 2}
```

Fix bug where iterable defaults were treated as mapped parameters

---

src/prefect/_internal/concurrency/services.py
tests/_internal/concurrency/test_services.py

Adds a queue service class that runs on the global event loop. A queue service runs on a loop handling items as they are received. Items can be sent from any thread. The service can be "drained" which will ensure all remaining items are handled.
This will be used for the event and logs workers and we also hope to use this to implement a singleton client instance that runs on the global loop.
```python
from prefect._internal.concurrency.services import QueueService, drain_on_exit
class ExampleService(QueueService[int]):
async def _handle(self, item: int):
print(hex(id(self)), item)
with drain_on_exit(ExampleService):
ExampleService.instance().send(1)
ExampleService.instance().send(2)
ExampleService.instance().send(3)
ExampleService.instance().send(4)
```
```
0x1004e2610 …
```

Add internal `QueueService` abstract class

---

src/prefect/utilities/templating.py
tests/utilities/test_templating.py

Adds the ability to reference block documents in worker base job templates and project config files with a dot-delimited syntax. When templating, the referenced block document will be retrieved, and the placeholder will be replaced by the data contained in the block document and any nested block documents. Block document placeholders must be used by themselves because they perform a full replacement in the template.
Closes #9036 
Use an arbitrary block in a template:
```python
class ArbitraryBlock(Block):
a: int
b: str
await ArbitraryBlock(a=1, b="hello").save(name="arbitrary-block")
template = {"key": "{{ prefect.blocks.arbitraryblock.arbitrary-block }}"}
result = await resolve_block_document_references(template)
assert result == {"key": { "a": 1, "b": "hello" }}
```
- If no issue exists …

Adds human-friendly way to reference block documents

---

src/prefect/cli/work_pool.py
tests/cli/test_work_pool.py

Adds the ability to specify a type when creating a work pool via the CLI. A work pool also needs a base job template in order to allow the configuration of flow runs, so we attempt to find a default base job template based on the type provided by the user.
To determine the base job template for the new work pool, first we look for the corresponding worker type in the client-side type registry. If the worker type is not found, then we look in the collection registry worker metadata for the work type. If the worker type still isn't found, then the command exits with an error and we print the available types for the user.
Create a Kubernetes work pool:
```bash
> prefect work-pool create --type kubernetes olympic
Created work pool 'olympic'.
```
Create a work pool with an unknown type: …

Add `--type` option to create work-pool CLI

---

tests/test_logging.py

Adds 4 new tests around the `PREFECT_LOGGING_ORION_WHEN_MISSING_FLOW` setting to ensure that:
1. a default setting of `warn` does not raise
2. a setting of `warn` does not raise
3. a setting of `ignore` does not raise or warn
4. a setting of `error` does not warn
Intended to test cases like:
```bash
❯ PREFECT_LOGGING_EXTRA_LOGGERS="my-logger" python example.py    
File "/Users/mz/dev/prefect/src/prefect/logging/handlers.py", line 279, in emit
self.get_worker(profile).enqueue(self.prepare(record, profile.settings))
File "/Users/mz/dev/prefect/src/prefect/logging/handlers.py", line 323, in prepare
raise MissingContextError(
prefect.exceptions.MissingContextError: Logger 'my-logger' attempted to send logs to Orion without a flow run id. The Orion log …
```

Add test coverage for logging outside flow run

---

src/prefect/_internal/concurrency/services.py
tests/_internal/concurrency/test_services.py

In preparation for moving the log worker to run on the global event loop, introduces a batched queue service so we can send logs in batches even when they're emitted one at a time.

Add `BatchedQueueService` abstract class

---

tests/events/test_events_instrument.py

Example flake failure at 'https://github.com/PrefectHQ/prefect/actions/runs/4610329356/jobs/8148679070?pr=8930'

Fix instrument test assertions to run after a client is present

---

src/prefect/engine.py
tests/test_tasks.py

Closes https://github.com/PrefectHQ/prefect/issues/7763
Mapped tasks were being executed asynchronously even when using the SequentialTaskRunner. This was because inside of the `begin_task_map` function we get a list of partial `get_task_call_return_value` functions, which are async, and then we call ` return await gather(*task_runs)`.
My solution sidesteps this by doing a check right before we call gather to see if the runner is sequential, and if so, executes the coroutines without the gather. 

Fix sequential execution with mapped tasks using the SequentialTaskRunner

---

src/prefect/_internal/concurrency/services.py
src/prefect/engine.py
src/prefect/logging/handlers.py
tests/test_logging.py

Uses the abstraction introduced in #9045 to reimplement the log worker and update it to run on the global event loop.
Drops a great deal of worker management complexity as well as handling of retries (we rely on retries in the client layer instead).

Update log worker to run on the global event loop

---

src/prefect/cli/project.py
src/prefect/cli/root.py
src/prefect/deployments.py
src/prefect/projects/steps/core.py
src/prefect/utilities/templating.py
tests/projects/test_steps.py
tests/utilities/test_templating.py

Allows the use of block document placeholders in project steps. For blocks that have a `value` field, `resolve_block_document_references` will unpack and return the value stored in `value` to make `JSON` and `Secret` blocks more readily usable.
I had to make `run_step` an `async` function to add a call to `resolve_block_document_references`, but I don't expect that to cause any issues.

Enables use of block document placeholders in steps

---

src/prefect/settings.py

The current default is a bit aggressive for the cost of the query the agent makes. Increases the default prefetch interval to match.

Update default agent query interval from 10s to 15s

---

src/prefect/engine.py
src/prefect/testing/fixtures.py
tests/test_engine.py

Caching applies per API URL reducing the number of redundant API healthchecks we make. Only applies to explicit checks in the engine, this is not applied at the client level.

Add a 10 minute cache to API healthchecks

---

src/prefect/task_runners.py

Similar to https://github.com/PrefectHQ/prefect/pull/9072 removes spin-locks from the concurrent task runner which should improve stability and performance.

Update concurrent task runner to use efficient wait patterns

---

src/prefect/_internal/concurrency/event_loop.py
src/prefect/futures.py

Supersedes #9070 
Closes https://github.com/PrefectHQ/prefect/issues/8986
May resolve https://github.com/PrefectHQ/prefect/issues/8982
Removes use of a spin-lock for cross-event loop waits in favor of nice future-based scheduling :) should be a significant performance improvement for some task submission cases and may resolve submission deadlocks.

Avoid using spin locks while waiting for task submission

---

src/prefect/engine.py
tests/test_tasks.py

Resolves issue raised at https://prefect-community.slack.com/archives/CL09KU1K7/p1680714278761869?thread_ts=1680713049.940769&cid=CL09KU1K7
Quoted items are detected as iterables because annotations inherit from tuple but they should only be treated as iterable if the item within the quote is iterable.
```
@task
def add_together(x, y):
return x + y
@flow
def my_flow():
return add_together.map(quote(1), [1, 2, 3])
```
Previously this would complain about mismatched iterable lengths: 1 vs 3. Now, it correctly infers that `quote(1)` is not an iterable. Additionally, we solve the case where the quoted item is iterable.

Fix detection of iterables within `quote` annotations while mapping

---

src/prefect/projects/recipes/docker-git/prefect.yaml
src/prefect/projects/recipes/git/prefect.yaml
src/prefect/projects/steps/pull.py

Enables pulling a project from private repositories. Should work with the major SCM services.
Usage:
```yaml
pull:
- prefect.projects.steps.git_clone_project:
repository: https://github.com/PrefectHQ/hello-projects.git
branch: main
access_token: "{{ prefect.blocks.secret.github-access-token }}"
```
Note usage of block document placeholders reqiures #9081 

Add `access_token` to `git_clone_project` step for private repository support

---

src/prefect/filesystems.py
tests/test_filesystems.py

`LocalFileSystem.write_path` and `RemoteFileSystem.write_path` return the path written to as a string.
closes https://github.com/PrefectHQ/prefect/issues/8964
```py
from prefect.filesystems import LocalFileSystem
dst = LocalFileSystem.write_path("./test.txt", b"data")
print(f"Wrote some data to '{dst}'")
```
- [ x ] This pull request references any related issue by including "closes `<link to issue>`"

local and remote filesystems return path on write

---

src/prefect/cli/root.py

Right now if a user submits work to a `prefect-agent` typed work pool, it runs the risk of running in a half-broken state depending on what version of Prefect that agent is running.
To avoid confusion, this PR enforces that deployments built from projects can only be submitted to non-agent typed work pools.

Fail on prefect-agent typed work pools

---

src/prefect/projects/base.py
src/prefect/projects/recipes/docker/prefect.yaml

This PR resolves an issue on `main` where initializing a `docker` recipe from within a git repo produces errors (due to using the full repo name as the project name).
This simplifies things to always rely on the directory name along instead of mixing and matching git-semantics with filesystem semantics.

Resolves issue with initializing a docker recipe within a git repo

---

src/prefect/cli/root.py
tests/cli/test_project.py

`client.read_work_pool` expects the work pool name

add name to read work pool call

---

scripts/run-integration-flows.py
src/prefect/__init__.py
src/prefect/cli/dev.py
src/prefect/cli/project.py
tests/cli/test_project.py
tests/projects/test_base.py
tests/test_filesystems.py
tests/utilities/test_importtools.py

To clarify that this path is not available in production installs (i.e. non-editable) to avoid future problems like https://github.com/PrefectHQ/prefect/pull/9132 — this has bit me before as well.

Rename `__root_path__` to `__development_base_path__`

---

src/prefect/_internal/concurrency/services.py
src/prefect/events/related.py
src/prefect/events/schemas.py
src/prefect/events/worker.py
src/prefect/utilities/context.py
tests/_internal/concurrency/test_services.py
tests/events/test_event_schemas.py
tests/events/test_events_related_from_context.py
tests/events/test_events_worker.py

This changes the EventWorker to implicitly add flow run and flow objects from the run context as related objects when emitting events. This allows for events, such as block instrumentation events, to automatically get the correct related resources without needing to get this information directly.
Closes #9127 

Include flow run and flow as related resources when emitting events via the events worker

---

src/prefect/server/services/cancellation_cleanup.py

Attempts to resolve https://github.com/PrefectHQ/prefect/issues/9120 by zealously opening and closing sessions and avoiding transactions for reads.

Use new sessions and transactions for each query during `CancellationCleanup`

---

src/prefect/projects/steps/pull.py

Displays git output during clones which is helpful for debugging when this fails or for monitoring progress
e.g.
```
In [1]: from prefect.projects.steps.pull import git_clone_project
In [2]: git_clone_project("prefecthq/prefect")
fatal: repository 'prefecthq/prefect' does not exist
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
Cell In[2], line 1
----> 1 git_clone_project("prefecthq/prefect")
File ~/dev/prefect/src/prefect/projects/steps/pull.py:38, in git_clone_project(repository, branch, access_token)
35 # Limit git history
36 cmd += ["--depth", "1"]
---> 38 subprocess.check_call(
39     cmd, shell=sys.platform == "win32", stderr=sys.stderr, stdout=sys.stdout
40 )
41 directory = …
```

Stream `git` output during `git_clone_project`

---

src/prefect/cli/project.py
src/prefect/cli/root.py
src/prefect/projects/base.py
src/prefect/projects/templates/deployment.yaml
tests/projects/test_base.py

Similar to #9145 this PR updates recipe defaults to guide users to healthy deployments as quickly as possible.  In this case, anytime a user uses a docker-based recipe, we default to using a job variable that references the `image_name` output of `build_docker_image`.
Running `prefect project init --recipe docker` now produces the following work pool section:
```yaml
work_pool:
job_variables:
image: '{{ image_name }}'
name: null
work_queue_name: null
```

Update deployment defaults with project init

---

docs/api-ref/prefect/projects/base.md
docs/api-ref/prefect/projects/steps/core.md
docs/api-ref/prefect/projects/steps/pull.md
docs/concepts/projects.md
mkdocs.yml
src/prefect/projects/base.py
src/prefect/projects/steps/core.py
src/prefect/projects/steps/pull.py

- exposes projects within our API reference documentation
- expands step documentation

Expands upon project step documentation

---

docs/concepts/projects.md

kind of nitpicky, but i found it slightly odd that the third step began with "lastly"
also noticed:
- `.prefect` was not represented as hidden directory like it is [here](https://docs.prefect.io/latest/tutorials/projects/#projects)
- push and pull steps seemed to be swapped in template example

small project doc fixes

---

src/prefect/cli/root.py
src/prefect/projects/templates/deployment.yaml
tests/cli/test_project.py

Updates `prefect deploy` behavior to pull `flow_name` and `entrypoint` to pull from `deployment.yaml` if not specified via the CLI. Previously, `prefect deploy` would exit with an error if `flow_name` or `entrypoint` were not passed, but one of them was defined in `deployment.yaml`.
With a `deployment.yaml` with `name`, `entrypoint`, and `work_pool.name` configured:
```yaml
name: test-deployment
version: null
tags: []
description: null
schedule: null
flow_name: null
entrypoint: flows/hello.py:flow
parameters: {}
work_pool:
name: my-pool
work_queue_name: null
job_variables: {}
```
A deployment can be created by running `prefect deploy` with no arguments or options. …

Update `prefect deploy` to pull `flow_name` and `entrypoint` from deployment.yaml if specified

---

docs/concepts/runtime-context.md
src/prefect/runtime/deployment.py
src/prefect/runtime/flow_run.py
src/prefect/runtime/task_run.py
tests/runtime/test_deployment.py
tests/runtime/test_flow_run.py
tests/runtime/test_task_run.py

This PR introduces a mechanism for mocking / manually setting runtime attributes via environment variable.  This was requested by a user looking to test their code and provide explicit known values for the attributes.
To do this, a user only needs to set an appropriately prefixed environment variable, e.g., `PREFECT__RUNTIME__TASK_RUN__NEW_KEY="foobar"` and now `prefect.runtime.task_run.new_key` evaluates to `"foobar"`.

Mock runtime via environment variable

---

src/prefect/engine.py

closes: https://github.com/PrefectHQ/prefect/issues/8611
Changing the logging formatter for task runs in https://github.com/PrefectHQ/prefect/blob/2.8.2/src/prefect/logging/logging.yml#L20 to:
```
task_run_fmt: "%(asctime)s.%(msecs)03d | %(levelname)-7s | Flow run %(flow_run_name)r - Task run %(task_run_name)r - %(message)s"
```
```python
from prefect import flow, get_run_logger, task
from prefect.context import get_run_context
@task
def say_hello_world() -> None:
logger.info("Hello World")
@flow(name="hello-world")
def main_flow() -> None:
flow_context = get_run_context()
logger.info(f"Running flow at {flow_context.start_time}")
say_hello_world()
main_flow()
```
Logs Before:
```
13:36:41.000 | INFO    | …
```

add flow run to task run logging

---

src/prefect/server/database/migrations/env.py
src/prefect/server/database/migrations/script.py.mako

closes: https://github.com/PrefectHQ/prefect/issues/8060
Automatically adds `PRAGMA` statements for sqlite migrations to the migration template. This is referenced in the docs to include for sqlite migrations. This removes the manual step so they're added automatically if connected to a sqlite db.
Example:
```
prefect server database revision -m test
```
```python
...
def upgrade():
op.execute("PRAGMA foreign_keys=OFF")
pass
op.execute("PRAGMA foreign_keys=ON")
def downgrade():
op.execute("PRAGMA foreign_keys=OFF")
pass
op.execute("PRAGMA foreign_keys=ON")
```
```python
...
def upgrade():
pass
def downgrade():
pass
```

Add pragma statements automatically if sqlite

---

docs/concepts/projects.md
docs/tutorials/projects.md
src/prefect/cli/project.py
src/prefect/projects/base.py
src/prefect/projects/recipes/docker-gcs/prefect.yaml
src/prefect/projects/recipes/docker-git/prefect.yaml
src/prefect/projects/recipes/docker-s3/prefect.yaml
src/prefect/projects/recipes/docker/prefect.yaml
src/prefect/projects/recipes/gcs/prefect.yaml
src/prefect/projects/recipes/s3/prefect.yaml
tests/cli/test_project.py

This PR introduces a new interactive experience for recipes - all recipes now ship with `required_inputs` that, if not provided, are prompted for whenever initializing that recipe.  These interactive prompts can be avoided by passing the required fields with the new `--field` flag on `project init`.  Documentation has also been updated to reflect this.
produces:
```yaml
name: hello-projects
prefect-version: 2.10.2+20.gd7df0187c
build:
- prefect_docker.projects.steps.build_docker_image:
requires: prefect-docker>0.1.0
image_name: my-image
tag: my-tag
dockerfile: auto
push: null
pull:
- prefect.projects.steps.set_working_directory:
directory: /opt/prefect/hello-projects
``` …

Improved recipe initialization UX

---

src/prefect/logging/handlers.py

Closes https://github.com/PrefectHQ/prefect/issues/9172

Fix bug where log worker only sent logs to API on flush rather than on an interval

---

src/prefect/cli/worker.py

Fixes CLI arguments in `prefect worker start`. Currently `work_queues` and `worker_type` are both assigned to `-t` / `--type`.

Fixes worker start CLI args

---

docs/stylesheets/extra.css

We use badges in the docs to provide visual cues for things we want readers to notice. For example, we might use an Enterprise badge to incate a feature that is only available for Enterprise accounts, like so: <picture><img height="40" align="middle" src="https://user-images.githubusercontent.com/228762/231633408-4e293837-e919-42a9-b114-2ef3218a747e.png"></img></picture>
This generally works well, but unfortunately, Mkdocs' table of contents generator is picking up heading badges and inserting them in the table of contents, resulting in unintended badge proliferation:
 
<table align="center"><tr><td><div align="center"><img width="219" alt="Screenshot 2023-04-12 at 11 32 35 PM" src="https://user-images.githubusercontent.com/228762/231642147-e5728f86-968b-41a0-9a50-31b163358a8c.png"></div> …

Update badge styling in docs

---

src/prefect/events/schemas.py
src/prefect/events/utilities.py
src/prefect/workers/base.py
tests/events/instrumentation/test_events_workers_instrumentation.py
tests/events/test_event_schemas.py
tests/events/test_events_emit_event.py

This adds a `prefect.worker.executed-flow-run` event to workers. It's fired when the flow-run completes and the worker is done monitoring it. It's almost identical to the `submitted-flow-run` event except that it adds infrastructure related labels to the flow-run resource.
```
{
...
"event": "prefect.worker.executed-flow-run",
"related": [
{
"prefect.resource.id": "prefect.deployment.7cdd9672-dcaa-4bda-8a4f-c16ce079bcc7",
"prefect.resource.name": "happy_little_tree",
"prefect.resource.role": "deployment"
},
{
"prefect.resource.id": "prefect.flow.9dc1c2a4-4e85-4ebc-8a34-144d9633f8bf",
"prefect.resource.name": "happy",
"prefect.resource.role": "flow"
},
{
"prefect.resource.id": "prefect.flow-run.5ff2f394-1da2-449a-b066-b96e6fc4d17c",
"prefect.resource.name": "glorious-manatee", …
```

Add worker.executed-flow-run event

---

docs/index.md

> there's a [broken link here](https://docs.prefect.io/latest/) - when i click the anchor text in "try the [tutorial](https://docs.prefect.io/tutorial/index/) where you'll create a full data project" i get a 404.
fixes broken link and makes minor wording change

fix broken link

---

src/prefect/cli/worker.py
src/prefect/workers/base.py
tests/events/instrumentation/test_events_workers_instrumentation.py

This adds events to the worker's lifecycle. It emits an event when the worker starts and another when the worker is stopped.
**Started event**
```json
{
...
"event": "prefect.worker.started",
"related": [
{
"prefect.resource.id": "prefect.work-pool.cd90d075-aade-4931-97d4-2af6fcb2fd4d",
"prefect.resource.name": "process-pool",
"prefect.resource.role": "work-pool"
}
],
"resource": {
"prefect.version": "2.10.4+4.ge73265d55b",
"prefect.resource.id": "prefect.worker.process.my-worker",
"prefect.worker-type": "process",
"prefect.resource.name": "my-worker"
},
}
```
**Stopped event**
```json
{
...
"event": "prefect.worker.stopped",
"related": [
{
"prefect.resource.id": "prefect.work-pool.cd90d075-aade-4931-97d4-2af6fcb2fd4d",
"prefect.resource.name": "process-pool",
"prefect.resource.role": …
```

Emit worker lifecycle events.

---

docs/ui/task-concurrency.md

The task run concurrency UI docs include a warning that you must use the CLI or Python client to delete a task run concurrency limit. This is no longer true; deletion via the UI works now, too.
This PR removes the warning from the docs. 
Current docs:
Current UI:

Remove outdated warning from task run concurrency UI docs

---

src/prefect/workers/base.py
src/prefect/workers/process.py
tests/workers/test_base_worker.py
tests/workers/test_process_worker.py

Updates `BaseWorker` to pass `configuration` to `kill_infrastructure` calls which allow worker implementations to retrieve the credentials needed to tear down created infrastructure for flow runs.
This update doesn't affect the `ProcessWorker` since it doesn't rely on a configuration object, but other worker implementations in Prefect integration packages will need pin their `prefect` dependency to the version where this change is implemented. Note that no other workers have implemented flow run cancellation yet.

Add `configuration` to `kill_infrastructure` signature

---

src/prefect/utilities/services.py
tests/utilities/test_services.py

Fixes bug where the agent hangs when only one of its critical service loops fails.
We've been observing this for a while, but it was not clear what the cause was. It turns out we just _returned_ from this function on error because we assumed it was being used in a context where that would result in an exit. Since the agent now checks for cancelled runs in addition to scheduled runs in separate loops, if one loop failed the agent could continue running without reporting the failure. This almost definitely patches the same bug for workers.
Loosely related to some behavior in #7442 e.g. https://github.com/PrefectHQ/prefect/issues/7442#issuecomment-1515306301
cc @jawnsy who first reported this behavior
Closes #9052

Update `critical_service_loop` to throw a runtime error on failure

---

src/prefect/workers/base.py
tests/events/instrumentation/test_events_workers_instrumentation.py

This fixes the broken `test_worker_emits_cancelled_event` test. It also adds some extra resources to the event now that the `configuration` is available when cancelling flow runs.

Fix broken worker events test and include related from configuration

---

.github/workflows/python-tests.yaml
src/prefect/software/pip.py
src/prefect/utilities/compat.py
tests/software/test_pip.py

Upgrades from the deprecated `pkg_resources` to `importlib_metadata` for Python 3.11+ compatibility.
Resolves issues inferring if modules are editable for pip 23.1+ compatibility.
Closes https://github.com/PrefectHQ/prefect/issues/9242

Fix pip requirement inference compatibility with Python 3.11+ and pip 23.1+

---

src/prefect/client/base.py

Otherwise you cannot see why the request failed.

Add status code to base client log on retry

---

src/prefect/server/schemas/actions.py
tests/server/schemas/test_actions.py

Ensure that if under the `variables` schema of `Workpool.base_job_template`, if there is a required field that has a default, the required-ness of the field is ignored because we can expect the field to be populated via the default

add variables fixes

---

RELEASE-NOTES.md

The comparison in the Release Notes is missing in a few places.

Add comparison where missing in Release Notes

---

ui/src/pages/FlowRun.vue

Changes the v-if on the flow run page parameters tab to see if there's a retrieved flow run rather than deployment.  This brings the OSS flow run page into parity with the cloud flow run page by allowing users to see the parameters used by a locally kicked off flow run as well as those used by a deployment run. 

Check on the existence of flow run instead of deployment for deciding whether to show the params tab

---

docs/concepts/flows.md
docs/concepts/tasks.md
docs/tutorials/flow-task-config.md
src/prefect/engine.py
src/prefect/flows.py
src/prefect/tasks.py
tests/test_flows.py
tests/test_tasks.py

Currently flow_run_name and task_run_name settings only accept template strings to generate new name. This PR enhances this feature by accept a function that expects input parameters dict and returns a string. This should ideally allow injecting flow run context and task run context too.
```python
import datetime
def generate_flow_run_name(params):
date = datetime.datetime.utcnow()
name = "anon" if "name" not in params else str(params["name"])
return f"{name}-on-{date:%A}"
@flow(flow_run_name=generate_flow_run_name)
def my_flow(name: str):
pass
my_flow(name="marvin")
```
```python
import datetime
def generate_task_name(params):
name = "anon" if "name" not in params else params["name"]
date = datetime.datetime.utcnow()
return …
```

Accept functions to flow_run_name and task_run_name settings

---

src/prefect/workers/base.py
tests/workers/test_base_worker.py

Workers create multiple client contexts during normal operation. Each worker creates a client context which should be reused during the lifespan of the worker. 
This PR adds a `inject_client` decorator to `from_template_and_values` on the `BaseConfiguration` class and updates the `BaseWorker` to pass its client into `from_template_and_values` to prevent recreating a client context. A test has also be added to verify that only one client context is created.
Closes #9301 

Ensure workers only create one client while running

---

src/prefect/cli/flow_run.py
tests/cli/test_flow_run.py

When using the CLI to retrieve flow run logs, if the `num_logs` to return was >= `LOGS_DEFAULT_PAGE_SIZE`, the limit wasn't being recalculated correctly in the loop. Instead, all logs were being returned if the specified `num_logs` was 200+. With this fix, specifying 205 logs, for example, should return 205 logs.

Fix `flow-run logs` limit

---

src/prefect/futures.py

Ensures that futures retrieve results from the same event loop as the task runner is managed in. Otherwise, mixed event loops can cause bugs — i.e. the Dask client does not detect that it is being used in asynchronous context because the event loops do not match.
Closes https://github.com/PrefectHQ/prefect-dask/issues/91

Fix `future.result()` and `future.wait()` calls from async contexts

---

docs/concepts/settings.md
mkdocs.insiders.yml
netlify.toml

* Remove fallback to mkdocs, which was obscuring the failure in mkdocs material insiders due to the social plugin receiving a list of strings instead of string
* Change Profiles and Configuration title to a string instead of list
Resolves: #9304

Fix social cards

---

src/prefect/_internal/concurrency/event_loop.py
src/prefect/_internal/concurrency/services.py

Fixes race conditions where items may not be fully sent before the service is drained.
Example flake at https://github.com/PrefectHQ/prefect/actions/runs/4789808505/jobs/8518118439?pr=9316

Update `QueueService.send` to wait for the item to be placed in the queue before returning

---

src/prefect/server/api/flows.py
src/prefect/server/models/flows.py
tests/server/api/test_flows.py

OSS implementation of https://github.com/PrefectHQ/nebula/pull/4439
Add work pool filtering to `/flows/filter`. This allows for extra filtering on the work pool on the related deployment of a flow if exists.
Example usage:
```
res = await client.post(
"/flows/filter", 
json={'work_pools': {'id': {'any_': ['4794ea7b-14a0-4ea3-9b1a-22ae07329a3d']},
'name': None,
'operator': 'and_',
'type': None}}
)
```
This is implemented similarly to how flows can be filtered by task runs if they exist for the flow.

filter flows by work pool

---

src/prefect/server/orchestration/core_policy.py
src/prefect/server/orchestration/rules.py
tests/fixtures/database.py
tests/server/api/test_flow_runs.py
tests/server/orchestration/test_core_policy.py
tests/test_flows.py

Closes https://github.com/PrefectHQ/prefect/issues/9012
Closes https://github.com/PrefectHQ/prefect/issues/9292
Previously, transitions out of terminal states were allowed in very specific cases:
- A task run could move from a failed/crashed/cancelled state to running if the flow run was retrying
- A flow run could move to a scheduled (awaiting retry) state
Now, we allow transitions out of terminal states unless the run is completed _and_ has a persisted result. 
This enables the following behaviors:
- A task run that fails and is orchestrated again will run instead of aborting
- A task run that completes but does not persist its result will run again on flow run retry
- A flow run may be rescheduled without using the "awaiting retry" name
- A flow run that fails and is orchestrated again …

Update orchestration rules to allow transitions from terminal states

---

src/prefect/futures.py
tests/test_futures.py

Follow-up to #9316 for these utilities.
Note this breaks usage with generators — which is also broken in `resolve_inputs`. We can fix it by doing a `return_data` traversal on the first pass but then we're doing two copies of the data structures 😮‍💨 which isn't a trade-off I'm willing to make at this point.

Update `resolve_futures_to_data` and `resolve_futures_to_states` to wait for futures in the correct event loop

---

src/prefect/exceptions.py
src/prefect/states.py
tests/results/test_state_result.py
tests/test_tasks.py

Improves clarity during the broad set of failure modes related to `MissingResult`
```python
from prefect.states import Pending
Pending().result()
```
```
File "/Users/mz/dev/prefect/example.py", line 3, in <module>
Pending().result()
File "/Users/mz/dev/prefect/src/prefect/client/schemas.py", line 107, in result
return get_state_result(self, raise_on_failure=raise_on_failure, fetch=fetch)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/mz/dev/prefect/src/prefect/states.py", line 71, in get_state_result
return _get_state_result(state, raise_on_failure=raise_on_failure)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/mz/dev/prefect/src/prefect/utilities/asyncutils.py", line 260, in …
```

Raise `UnfinishedRun` instead of `MissingResult` when state is not final

---

src/prefect/_internal/concurrency/threads.py
tests/_internal/concurrency/test_threads.py

`EventLoopThread.start` was not safe to calls from multiple threads.
Reported in https://github.com/PrefectHQ/prefect/issues/9296

Fix race condition in event loop thread start

---

benches/bench_flows.py
src/prefect/engine.py
src/prefect/task_runners.py
src/prefect/testing/standard_test_suites/task_runners.py
tests/test_engine.py
tests/test_flows.py

Allows concurrent execution of the same flow, avoiding the "task runner is already started" issue by creating a new instance for each run. Avoids introducing new types or patterns — task runner implementations will need to implement the `duplicate` method if they take options. We use this instead of `copy` to avoid including any runtime state.
Closes https://github.com/PrefectHQ/prefect/issues/7319
Closes https://github.com/PrefectHQ/prefect/issues/8307
On release, Dask/Ray will ignore options passed to the task runner until their implementations are released:
Dask implementation https://github.com/PrefectHQ/prefect-dask/pull/93
Ray implementation https://github.com/PrefectHQ/prefect-ray/pull/83
We could make this an abstract method if we'd rather they just crashed and burned.
Concurrent …

Duplicate task runner instances before usage in engine

---

src/prefect/logging/loggers.py
tests/test_logging.py

Closes https://github.com/PrefectHQ/prefect/issues/9251
"bye" is not captured
```python
import sys
import io
def example():
print("hi")
print("hi", file=None)
print("hi", file=sys.stdout)
print("hi", file=sys.stderr)
print("bye", file=io.StringIO())
example()
```

Update `log_prints` to ignore prints where a custom `file` is used

---

src/prefect/logging/handlers.py

The docstring for `close` indicates that it is important for subclasses to call the parent method.
Related to https://github.com/PrefectHQ/prefect/issues/9345

Ensure `close()` is called on the base handler during `APILogHandler` shutdown

---

src/prefect/workers/base.py
tests/events/instrumentation/test_events_workers_instrumentation.py

When I was building out the events for the library-based workers I ran into an issue, at least in testing, where the deployment/flow could be `None` and that caused `config._related_resources` to raise an exception. This is the fix I applied in the libraries, just pulling it up so we can pull it out of those libraries at some point.

Update `BaseJobConfiguration._related_resources` to handle the case where objects are `None`.

---

src/prefect/_internal/concurrency/services.py
tests/_internal/concurrency/test_services.py

Closes https://github.com/PrefectHQ/prefect/issues/9396
Reverts #9318 
This appears to have introduced a deadlock when the event loop is blocked waiting for the logging lock.

Revert change where `QueueService.send` blocked until the item was enqueued

---

src/prefect/engine.py
src/prefect/flows.py
tests/test_engine.py
tests/test_flows.py

Closes #9348 
Closes #8688 
Adds the ability to execute arbitrary code when a flow enters a `CRASHED` state.
```python
def crash_hook(flow, flow_run, state):
print("Better call Marvin.. \U0001F641")
@flow(on_crashed=[crash_hook])
def my_flow():
raise SystemExit(1)
if __name__ == '__main__':
my_flow()
```
```bash
13:27:40.114 | INFO    | prefect.engine - Created flow run 'thundering-narwhal' for flow 'my-flow'
13:27:41.303 | ERROR   | Flow run 'thundering-narwhal' - Crash detected! Execution was aborted by Python system exit call.
13:27:41.360 | INFO    | Flow run 'thundering-narwhal' - Running hook 'crash_hook' in response to entering state 'Crashed'
Better call Marvin.. 🙁
13:27:41.361 | INFO    | Flow run 'thundering-narwhal' - Hook …
```

Add `on_crashed` flow run state change hook

---

src/prefect/server/models/work_queues.py
tests/server/api/test_work_queues.py

Updates work queue status to use work queue ID for gathering late flow runs instead of work queue name. Queues that shared the same name but were in different work pools would both show as unhealthy if one of them was unhealthy.
Closes #9433 
Closes #9324 

Fix work queues showing as unhealthy when a work queue with the same name is unhealthy

---

src/prefect/_internal/concurrency/services.py
src/prefect/_internal/concurrency/timeouts.py
tests/_internal/concurrency/test_services.py
tests/events/instrumentation/test_events_workers_instrumentation.py

Better implementation of #9318
Effectively reverts https://github.com/PrefectHQ/prefect/pull/9398
Fixes race conditions seen in work like https://github.com/PrefectHQ/prefect/pull/9354
- Adds a lock that is taken on `drain_all` to ensure it captures all of the instances
- Change from an `asyncio.Queue` with calls to put items into it scheduled on the event loop to a `queue.Queue` with calls to retrieve items from it run in worker threads. This ensures the item enters the queue before `send` returns without risking deadlock at the cost of creating a worker thread on each retrieval from the queue.

Fix send/drain race conditions in queue services

---

requirements.txt
src/prefect/filesystems.py

Multiple users have had storage issues that all appear to have the same root cause: fsspec behavior changes across versions depending on whether or not the `from_path` has a trailing slash.
This PR ensures the existence of a trailing slash (always a forward slash due to remote systems following POSIX path schemas) and closes:
- https://github.com/PrefectHQ/prefect/issues/9262
- https://github.com/PrefectHQ/prefect/issues/8710

Ensure trailing slash in remote filesystems

---

src/prefect/server/orchestration/core_policy.py
tests/server/orchestration/test_core_policy.py

Closes https://github.com/PrefectHQ/prefect/issues/7116
The `PreventRedundantTransitions` rule which was previously intended to prevent backwards transitions is now updated to allow most transitions. Now it **only prevents transitions to PENDING states** to prevent race conditions during duplicate submissions of runs and cancellation.
Before a run is submitted to its execution environment, it should be placed in a PENDING state. If two workers attempt to submit the same run, one of them should encounter a PENDING -> PENDING transition and abort orchestration of the run. 
Similarly, if the execution environment starts quickly the run may be in a RUNNING state when the second worker attempts the PENDING transition. We deny these state changes as well to prevent duplicate submission. If a …

Update orchestration rules to allow additional flow run state transitions

---

src/prefect/deployments.py

Touching the `.prefectignore` file modifies it even if the file already exists which breaks some read-only CI environments. This change simply performs an existence check before touching the file.
Closes #9332

Only touch the ignorefile if it doesn't exist

---

.github/ISSUE_TEMPLATE/1_general_bug_report.yaml

We have an extremely low success rate for users including the full version information when opening an issue introducing additional cycles as we attempt to determine if they are using Cloud or what Python version or OS they are using.

For real, please provide the output of the version command

---

src/prefect/_internal/concurrency/services.py

This reduces the overhead of spawning a new thread on each `queue.get()` call and allows us to set the worker thread as a daemon resolving a deadlock on interpreter exit.
Closes https://github.com/PrefectHQ/prefect/issues/9459

Update `QueueService` to use a dedicated worker thread

---

setup.cfg
src/prefect/__init__.py

```python
import prefect
```
```
example.py:1: FutureWarning: Prefect will drop support for Python 3.7 when it reaches end-of-life on 27 Jun 2023. 
To use new versions of Prefect after that date, you will need to upgrade to Python 3.8+.
import prefect
```

Add future warning for Python 3.7 EOL

---

docs/concepts/flows.md

adds a usage example for `on_failure`

add `on_failure` example to docs

---

docs/concepts/tasks.md
src/prefect/flows.py
src/prefect/settings.py
src/prefect/tasks.py
tests/test_engine.py
tests/test_flows.py
tests/test_tasks.py

This PR exposes 4 new global settings that can be set: 
PREFECT_FLOW_DEFAULT_RETRIES,
PREFECT_FLOW_DEFAULT_RETRY_DELAY_SECONDS,
PREFECT_TASK_DEFAULT_RETRIES,
PREFECT_TASK_DEFAULT_RETRY_DELAY_SECONDS
These values do not overwrite retry or retry delay seconds that are set on the flow/task level. These values will be used if the flow/task does not have a retry/retry delay seconds value set. The default for all of these is 0.
This would solve: https://github.com/PrefectHQ/prefect/issues/9520.
```
prefect config set PREFECT_FLOW_DEFAULT_RETRIES=2
prefect config set PREFECT_TASK_DEFAULT_RETRIES=2
prefect config set PREFECT_FLOW_DEFAULT_RETRY_DELAY_SECONDS = [1, 10, 100]
prefect config set PREFECT_TASK_DEFAULT_RETRY_DELAY_SECONDS = [1, 10, 100]
```
If retries/retry delay seconds are not set, …

Global flow and task retries and retry delay seconds

---

src/prefect/_internal/concurrency/api.py
src/prefect/engine.py
src/prefect/states.py
tests/public/flows/test_flow_crashes.py
tests/test_engine.py

Closes https://github.com/PrefectHQ/prefect/issues/9403
When we moved the engine to a dedicated thread, we lost the ability to register signal handlers. Here we add signal handler registration to the main thread before entering the engine which is important for crash detection of SIGTERM and consequently reports of cancellation.
I implemented this by adding support for context managers to the concurrency API because async flow calls return a coroutine and we need to enter the contexts inside that coroutine or it'll exit before it actually runs.
```
12:34:14.097 | DEBUG   | prefect.profiles - Using profile 'default'
12:34:14.576 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////Users/mz/.prefect/prefect.db
12:34:14.744 | INFO    | prefect.engine …
```

Fix bug where SIGTERM was not properly captured as a flow run crash

---

src/prefect/engine.py

Sometimes `retrieve_flow_then_begin_flow_run` can exit without orchestrating the flow run which means that logs are not flushed and can be missing but they are generally useful for debugging the failure so let's flush those things!

Flush logs before exiting deployed flow run processes

---

src/prefect/client/orchestration.py
tests/client/test_orion_client.py

I noticed that when using the `create_work_queue` method in the python client that the work queue would get created but without any of the parameters that were set to non-default values. I guess this was an oversight or rebase issue when the params were [first added here](https://github.com/PrefectHQ/prefect/commit/839cc3e#diff-ed60480b777e77bdeeced26ed733ea8d0da54e3da5a6dce53054258a1625b004R696).
This PR just builds the API request from the object that I assume should have been used all along and adds a test to check the extra params were used.
```python
async with get_client() as prefect_client:
await prefect_client.create_work_queue(
name="my-queue",
concurrency_limit=1,
)
``` …

Correctly pass optional parameters to API in create_work_queue

---

src/prefect/engine.py
tests/public/flows/test_flow_crashes.py

Follow-up to #9498 that adds the same context management to the engine entrypoint for deployed flow runs.

Fix bug where `SIGTERM` as not reported as a flow run crash for deployed runs

---

benches/bench_cli.py

Example
```
❯ python benches benches/bench_cli.py                                         
=========================================================================================================== test session starts ============================================================================================================
platform darwin -- Python 3.11.2, pytest-7.3.1, pluggy-1.0.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=1 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/mz/dev/prefect
configfile: setup.cfg
plugins: env-0.8.1, asyncio-0.21.0, flaky-3.7.0, timeout-2.1.0, flakefinder-1.1.0, xdist-3.2.1, respx-0.20.1, cov-4.0.0, anyio-3.6.2, benchmark-4.0.0, lazy-fixture-0.6.3
asyncio: …
```

Add benchmarks for CLI commands

---

benches/bench_import.py

Example
```
❯ python benches benches/bench_import.py        
=========================================================================================================== test session starts ============================================================================================================
platform darwin -- Python 3.11.2, pytest-7.3.1, pluggy-1.0.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=1 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/mz/dev/prefect
configfile: setup.cfg
plugins: env-0.8.1, asyncio-0.21.0, flaky-3.7.0, timeout-2.1.0, flakefinder-1.1.0, xdist-3.2.1, respx-0.20.1, cov-4.0.0, anyio-3.6.2, benchmark-4.0.0, lazy-fixture-0.6.3
asyncio: mode=Mode.AUTO
timeout: 60.0s …
```

Add benchmarks for `import prefect`

---

docs/concepts/tasks.md

as pointed out by @abrookins , the current example doesn't really make sense / illustrate the utility of retries
also adding placeholder function `def` for task decorator config examples

better retry example + tweaks

---

tests/server/api/test_run_history.py
tests/server/api/test_work_queues.py

The test_run_history module overrides the default `clear_db` fixture so that data hangs around for all tests in the module. The data isn't cleared, which can cause bleed over into other tests that work with work queues and work pools. This PR updates the custom `clear_db` fixture to clear data in the DB after all tests in the module are complete.
Closes #9538 
Closes #9537 

Ensure test DB is cleared at the end of run history tests

---

docs/concepts/deployments.md

Users can specify a work pool when building a deployment from a flow yet this is not represented in the docs. This PR adds `work_pool_name` to the examples in the deployment page.

Add `work_pool_name` to `Deployment.build_from_flow` in docs

---

src/prefect/cli/root.py

When using the ephemeral app, database migrations are run during a `prefect version` call. There's no reason to be running migrations when retrieving version information and it has caused a corrupted database in https://github.com/PrefectHQ/prefect/issues/9493
Closes https://github.com/PrefectHQ/prefect/issues/9493

Update `prefect version` command to avoid creating the database if it does not exist

---

src/prefect/cli/deployment.py

After the changes in #9577 and #9571 this is one of the larger remaining CLI startup costs
```
----------------------------------------- benchmark 'bench_import_prefect': 2 tests -----------------------------------------
Name (time in ms)                           Mean             StdDev                 Min                 Max            Rounds
-----------------------------------------------------------------------------------------------------------------------------
bench_import_prefect (NOW)              594.2356 (1.0)      46.2595 (1.73)     555.3874 (1.0)      670.8452 (1.0)           5
bench_import_prefect (0017_0ac7dea)     646.7460 (1.09)     26.6990 (1.0)      624.5832 (1.12)     683.3596 (1.02)          5
--------------------------------------------------------------------------- …
```

Defer import of `dateparser` to speed up CLI startup

---

src/prefect/__init__.py
src/prefect/agent.py
src/prefect/blocks/core.py
src/prefect/engine.py
tests/blocks/test_core.py
tests/test_plugins.py

Removes `prefect.plugins.load_prefect_collections()` from the main `__init__` to improve performance of `import prefect` and the CLI. Instead, we call this at places where we need to ensure that collections have been loaded such as before:
- Executing a deployed flow run
- Loading a saved block
Otherwise as the number of installed collections grows, so does the time of running any CLI command. In cases where multiple Cloud provider packages are installed, this can be greater than 5s.
On my machine, with `prefect-dask`, `prefect-aws`, and `prefect-docker` I see major improvements:
```
------------------------------------- benchmark 'bench_import_prefect': 2 tests --------------------------------------
Name (time in s)                          Mean            StdDev               Min …
```

Defer loading of prefect collections until necessary

---

src/prefect/blocks/core.py
src/prefect/cli/deployment.py
src/prefect/deployments.py

Follow-up to #9571 ensuring that some additional cases where we rely on dispatch go through the code path that loads collections

Add `Block.get_block_class_from_key` and replace external uses of `lookup_type`

---

docs/concepts/infrastructure.md

links previously just went to top of correct page, not the correct markdown header

fix links to infra blocks

---

ui/package-lock.json
ui/package.json

Fixes a bug where if you changed the Date Range filter on the flow runs page that new date range wouldn't be reflected on the page until you changed one of the other filters or the 30s polling interval happened. This was fixed upstream in the vue-compositions library

Date Range filter not responsive on flow runs page

---

src/prefect/client/orchestration.py
src/prefect/server/api/server.py
tests/client/test_orion_client.py
tests/server/api/test_server.py

While working on #9632 we noticed that the database error was being raised client-side.
@jakekaplan and I discovered that FastAPI treats [exception handlers that capture `Exception` as `ServerErrorMiddleware` instead of `ExceptionMiddleware`](https://github.com/tiangolo/fastapi/blob/8cc967a7605d3883bd04ceb5d25cc94ae079612f/fastapi/applications.py#L163-L164). The key difference here is that [`ServerErrorMiddleware` will always raise an encountered exception after returning the response](https://github.com/encode/starlette/blob/d3a11205ed35f8e5a58a711db0ff59c86fa7bb31/starlette/middleware/errors.py#L184). When using an ephemeral server, this causes server-side exceptions to be raised client-side breaking all of our response error code handling. To work around this, we can either insert our …

Fix bug where ephemeral server raised exceptions client-side

---

src/prefect/server/api/server.py
src/prefect/server/orchestration/core_policy.py
src/prefect/server/orchestration/rules.py
tests/server/api/test_server.py
tests/server/orchestration/test_rules.py

Requires https://github.com/PrefectHQ/prefect/pull/9637
Required for https://github.com/PrefectHQ/prefect/pull/9594
Previously, if a BUSY was encountered during orchestration the rules context would eat the exception so it would never be raised. A client would receive an ABORT signal. Now, we send a 503 instead.

Allow client retries when server SQLite database is busy

---

src/prefect/server/api/server.py
tests/server/api/test_server.py

Extends https://github.com/PrefectHQ/prefect/pull/9632 to include all of the retryable database exceptions that we use in Cloud.
This improves resilience for all open source server users.

Allow client retries when database errors are encountered

---

src/prefect/events/related.py
src/prefect/server/schemas/responses.py
tests/events/test_events_related_from_context.py

Step one of moving task run state change events to the client is to ensure that all of the related resources that cloud was attaching are now being attached via the related from context mechanism. This adds `deployment`, `work-queue`, and `work-pool` as resources as well as any tags they may have. 
Closes #9599 

Attach deployment, work-queue, and work-pool as related resources to emitted events.

---

src/prefect/events/clients.py
tests/events/test_cloud_events_client.py

As described in #9662 when prefect is configured with a `PREFECT_API_URL` that has a trailing slash the URL the Cloud events client uses to connect to the websocket endpoint is incorrect and the connection fails with a 403. This updates the cloud events client to correctly handle this by stripping trailing slashes before building the full URL.
Closes #9662 

Remove trailing slashes when building events/in websocket url

---

.github/workflows/python-tests.yaml
docs/concepts/infrastructure.md
docs/contributing/testing-flow-runners.md.old
scripts/build-all-dev-images
src/prefect/docker.py

Previously, if you were using a non-release version of Prefect we'd generate the special tag `prefect:dev-pythonX.X` to use a local image. This image should never be available on DockerHub so you'd need to build your local development image as needed.
However, this can be confusing and since we're publishing images on merge to `main` we can do a bit better! Now we generate the tag `prefect-dev:sha-XXXXX-pythonX.X` so you'll get an image that matches the most recent commit for your local version. If your commit is not available, you'll need to build an image for it or specify a different image than the default.

Improve default Prefect image tag when using development versions

---

src/prefect/cli/_types.py

Deprecation warnings should be printed to stderr instead of stdout so commands can be piped without breaking.

Display CLI deprecation warnings to STDERR instead of STDOUT

---

src/prefect/variables.py

closes: https://github.com/PrefectHQ/prefect/issues/9660
Fixes an issue where `variables.get` was incorrectly using `from_sync` to make a client call from an async context as well as scheduling it in the loop thread. This was only an issue when the variable was retrieved at the module level (like in the example below), where loading the flow code (which also was scheduled in a different thread) and the variable call itself would block each other.
```python
from prefect import flow, variables
bar = variables.get("foo")
@flow
def main():
print(bar)
main()
```
Previously this would appear to hang after downloading the flow code:
```python
Agent started! Looking for work from queue(s): default...
17:48:44.688 | INFO    | prefect.agent - Submitting flow run …
```

fix variables

---

src/prefect/cli/config.py
tests/cli/test_config.py

Changing `PREFECT_HOME` or `PREFECT_PROFILES_PATH` via the config will result in a new config path that would not be respected — very confusing for a user.
```
❯ prefect config set PREFECT_HOME="test"        
Setting 'PREFECT_HOME' cannot be changed with this command. Use an environment variable instead.
```

Guard against changing the profile path from `prefect config set`

---

src/prefect/agent.py
src/prefect/client/orchestration.py
src/prefect/workers/base.py
tests/client/test_orion_client.py
tests/workers/test_base_worker.py

Right now if a user deletes a deployment associated with a new work pool, workers trying to cancel its runs will error out with a 404.  This PR updates workers to handle this situation gracefully and mark the flow run as failed.

Handle deleted deployments gracefully

---

src/prefect/server/schemas/actions.py
tests/server/api/test_variables.py

closes: https://github.com/PrefectHQ/prefect/issues/9709
When calling `PATCH - .../api/variables/{id}` `Variables.value` can't be updated to more than 255 characters. That is the correct max length for `Variables.name`, but `Variables.value` should be max length of 5000.
The update would return a 422 before saying the max length was 255. Now this will correctly update up to 5000 characters.
```python
from prefect.client.orchestration import get_client
import asyncio
async def main():
async with get_client() as client:
res = await client._client.post(f"/variables/", json={"name": "foo", "value": "bar"})
assert res.status_code == 201
res = await client._client.patch(f"/variables/name/foo", json={"value": "b" * 257})
assert res.status_code == 422
print(res.json())
asyncio.run(main())
```
- …

fix variable max value update

---

src/prefect/cli/worker.py
src/prefect/workers/base.py
tests/events/instrumentation/test_events_workers_instrumentation.py

relates to https://github.com/PrefectHQ/platform/issues/3841
this PR adds:
* a `prefect.worker.poll.flow-run` event, to be dispatched when grabbing flow runs
* a `prefect.worker.poll.cancelled-flow-run` event (similar)

feat: add worker `poll.*` events

---

src/prefect/server/api/root.py
src/prefect/server/database/interface.py
tests/server/api/test_root.py

relates to https://github.com/PrefectHQ/prefect-helm/issues/132
relates to https://github.com/PrefectHQ/prefect/issues/8940
the idea is that we can continue using `GET /api/health` (or `GET /api/hello`) as a liveness check, and this new `GET /api/ready` endpoint as a readiness check, which probes to see if the database is connect-able

feat: add an /api/ready check to prefect server

---

docs/cloud/rate-limits.md

Adding /set_state and /flows to endpoint rate limits in documentation for Prefect Cloud.

Update rate limit docs to include /set_state and /flows endpoint for Prefect Cloud

---

docs/concepts/artifacts.md
src/prefect/artifacts.py
tests/test_artifacts.py

We're able to render table artifacts in the UI where the input is a `list[list]`, and we should allow it.
```python
@task
def my_table_task():
create_table_artifact(
key="sales-data-table",
table=[
["Region", "Revenue"],
["North America", 500000],
["Europe", 250000],
["Asia", 150000],
["South America", 75000],
["Africa", 25000],
],
description="## Sales by Region",
)
```

Allow table artifacts as list of lists

---

src/prefect/workers/base.py

Ensures submission failures are properly visibile in the UI logs page

Use flow run logger to report traceback for failed submissions

---

src/prefect/client/cloud.py

closes https://github.com/PrefectHQ/prefect/issues/9723

Use PrefectHttpxClient in cloud communication

---

tests/events/instrumentation/test_events_workers_instrumentation.py

After adding `poll.*` events from #9702, this uncovered that some of our event test assertions expected consistent ordering, when they are not - this led to some test flakiness
Here, we'll use `len()` checks instead, to assert the count of events we'd expect.  In some cases, we'll still use positional identifiers to check single-member sub-lists, but I think this is OK

fix: use counts for worker events instrumentation tests

---

src/prefect/engine.py

Closes https://github.com/PrefectHQ/prefect/issues/8627
```python
@flow
def child():
pass
@flow
def test():
child()
test()
```
```
12:25:49.851 | INFO    | prefect.engine - Created flow run 'dandelion-cuscus' for flow 'test'
12:25:49.855 | INFO    | Flow run 'dandelion-cuscus' - View at https://app.prefect.cloud/account/26718ef2-7196-45ed-b646-cefb69f8c14f/workspace/a987dfec-2197-4b8c-96d8-1439fa90dce8/flow-runs/flow-run/c2dabf64-d466-4ef3-bbcd-554bcff7ad5a
12:25:51.458 | INFO    | Flow run 'dandelion-cuscus' - Created subflow run 'daft-manul' for flow 'child'
12:25:51.459 | INFO    | Flow run 'daft-manul' - View at https://app.prefect.cloud/account/26718ef2-7196-45ed-b646-cefb69f8c14f/workspace/a987dfec-2197-4b8c-96d8-1439fa90dce8/flow-runs/flo …
```

Display URL to flow run on creation

---

src/prefect/client/base.py
src/prefect/settings.py
tests/client/test_base_client.py

Allows users to increase retry counts if they would rather have a slow run than a failed run

Add `PREFECT_CLIENT_MAX_RETRIES` for configuration of maximum HTTP request retries

---

src/prefect/utilities/asyncutils.py

It seems like it's possible for `EVENT_LOOP_GC_REFS` to be garbage collected earlier than `add_event_loop_shutdown_callback` expects. As a result, you can get the following error (as seen in [this issue](https://github.com/PrefectHQ/prefect/issues/7709#issuecomment-1560021109)):
```
Exception ignored in: <async_generator object add_event_loop_shutdown_callback.<locals>.on_shutdown at 0x16fe264c0>
File "/Users/ryanmorshead/.mambaforge/envs/***/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 326, in on_shutdown
AttributeError: 'NoneType' object has no attribute 'pop'
Exception ignored in: <async_generator object add_event_loop_shutdown_callback.<locals>.on_shutdown at 0x28fcfb640>
File …
```

Fix bug where event loop shutdown hooks could fail due to early garbage collection

---

src/prefect/events/related.py
tests/events/test_events_related_from_context.py

This adds the current task run from the TaskRunContext (if it exists) to emitted events. It also changes the logic a bit to grab the flow run from the flow-run context if it exists rather than always asking the API.
Closes #9758

Add task-run as a related object to emitted events

---

.gitignore
benches/conftest.py
src/prefect/engine.py
src/prefect/events/utilities.py
src/prefect/events/worker.py
src/prefect/utilities/text.py
tests/events/instrumentation/test_task_run_state_change_events.py
tests/events/test_events_emit_event.py
tests/events/test_events_related_from_context.py
tests/events/test_events_worker.py
tests/results/test_flow_results.py

This updates the engine to emit an event when a task run changes states. 
Closes #9651 
-->

Emit task run state change events when orchestrating a task run

---

docs/concepts/variables.md

This PR only affects documentation.  Here is the current example in [concepts/variables](https://docs.prefect.io/latest/concepts/variables/):
```python
answer = variables.get('not_the_answer')
print(answer)
answer = variables.get('not_the_answer', default='42')
print(answer)
```
The first comment should be: `#without a default value`.

Fix default value comment in docs/concepts/variables

---

docs/concepts/task-runners.md

As you can see [in the doc](https://docs.prefect.io/latest/concepts/task-runners/#running-tasks-on-ray), speaking about *Ray's support for Python 3.11*, the link is not properly formatted and there is even a wrong URL in the middle.

The link to Ray page was not properly formatted

---

src/prefect/server/api/server.py
tests/server/api/test_server.py

Follow-up to https://github.com/PrefectHQ/prefect/pull/8454

Deprecate `create_orion_api` in favor of `create_api_app`

---

src/prefect/workers/process.py

extra comma made the multiline string a tuple and therefore was failing against registry json schema validation

fix process worker `documentation_url`

---

docs/overrides/main.html

We previously had announcement text, which is not visible on the page but appears in the generated HTML and thus would appear in search engines indexes.

Remove outdated announcement

---

src/prefect/engine.py
src/prefect/logging/handlers.py
src/prefect/logging/loggers.py
tests/test_flows.py
tests/test_logging.py
tests/test_tasks.py

Follow-up to https://github.com/PrefectHQ/prefect/pull/8454
```python
from prefect import flow, get_run_logger
@flow
def test():
get_run_logger().info("Hello world!", extra={"send_to_orion": False})
test()
```
```
13:16:40.132 | INFO    | prefect.engine - Created flow run 'premium-jackdaw' for flow 'test'
/Users/mz/dev/prefect/example.py:6: PrefectDeprecationWarning: The "send_to_orion" option has been deprecated. It will not be available after Nov 2023. Use "send_to_api" instead.
get_run_logger().info("Hello world!", extra={"send_to_orion": False})
13:16:40.202 | INFO    | Flow run 'premium-jackdaw' - Hello world!
13:16:40.219 | INFO    | Flow run 'premium-jackdaw' - Finished in state Completed()
```

Deprecate "send_to_orion" logging option in favor of "send_to_api"

---

src/prefect/server/models/work_queues.py
src/prefect/server/models/workers.py
tests/server/api/test_work_queues.py
tests/server/api/test_workers.py
tests/server/models/test_workers.py

Work queue priorities are currently kept in sequential order. If there are 3 queues with priorities 1 and 2, and the user set one of their priorities to be 20, it is actually set to 3 before the queue is written to the DB. From a user perspective it looks like we aren't respecting their specified priority.
With this PR users can set any value and it is respected. If the user sets a priority that conflicts with the priority of another queue, then existing queue priorities are incremented to ensure all their values are unique.
Ports functionality from https://github.com/PrefectHQ/nebula/pull/3778
Closes #9794 

Respect priority passed when creating a work queue

---

flows/deployment_storage.py
src/prefect/context.py
src/prefect/infrastructure/container.py
src/prefect/projects/base.py
src/prefect/server/api/server.py
src/prefect/settings.py
src/prefect/utilities/filesystem.py
tests/cli/test_deploy.py
tests/projects/test_base.py

When creating ~/.prefect and other files, use restrictive (user-only) permissions to improve privacy on shared systems.
---
I tested this by removing my `~/.prefect` directory and running `prefect server`:
```
$ ls -al ~ | grep "prefect"
drwx------    5 jawnsy staff  160 May 30 13:06 .prefect
drwxr-xr-x    8 jawnsy staff  256 May 27 14:07 .prefect.bak
-rw-------    1 jawnsy staff  31K May 17 10:38 .psql_history-prefect_cloud
$ ls -al ~/.prefect
total 836K
drwx------    4 jawnsy staff  128 May 30 13:06 .
drwxr-x---+ 165 jawnsy staff 5.2K May 30 13:06 ..
-rw-------    1 jawnsy staff   93 May 30 13:06 memo_store.toml
-rw-------    1 jawnsy staff …
```

Create files and directories with user-scoped permissions

---

src/prefect/cli/_prompts.py
src/prefect/cli/_utilities.py
src/prefect/cli/deploy.py
src/prefect/cli/root.py
src/prefect/cli/work_pool.py
tests/cli/test_deploy.py

Adds interactive prompts for adding a schedule to a deployment when running `prefect deploy`. When running `prefect deploy` without a schedule specified via the CLI or `deployment.yaml`, the user is asked if they want to assign a schedule to the new deployment. If the user accepts they will see options for **Interval**, **Cron**, and **RRule** schedules. After selecting a schedule type, the user will be prompted to enter the details specific to their deployment. Inputs for schedule details are validated on input and the user is re-prompted if an invalid value is supplied.
This PR also adds a `--ci` flag to `prefect deploy`. The `--ci` flag is intended for CI/CD use cases where interactive prompts are unnecessary. This allows deployments to be created without a schedule without triggering …

Add interactive schedule prompting to `prefect deploy`

---

docs/api-ref/prefect/projects/steps/utility.md
docs/concepts/projects.md
mkdocs.yml
src/prefect/cli/deploy.py
src/prefect/projects/steps/__init__.py
src/prefect/projects/steps/core.py
src/prefect/projects/steps/utility.py
src/prefect/utilities/collections.py
src/prefect/utilities/processutils.py
src/prefect/utilities/templating.py
tests/projects/test_steps.py
tests/utilities/test_collections.py
tests/utilities/test_templating.py

Adds a deployment lifecycle step that allows users to run shell commands as part of their deployment process. The step captures the stdout and stderr of the commands that are run so that they can be used as inputs to later steps.
This PR updates `utilities.processutils.stream_text` to accept multiple sinks for stdout and std error to support capturing process output while streaming the output back to stdout and stderr.
Closes #9783
To make the `run_shell_script` step more useful, this PR also implements passing outputs to downstream steps in the same action. To avoid overwriting outputs of upstream tasks, users can now add an `id` to each step and use it to reference step outputs in downstream steps. See the YAML snippet below for an example of this functionality.
Closes #9346
Retrieve …

Add `run_shell_script` step

---

mkdocs.yml

Adds a feedback widget to bottom of docs pages. 
Goal is to help provide information so we can improve docs where the need is greatest.
Closes #6687. 
Clicking on the sad face gives you a link to create an issue with the docs change template.
See the [preview Netlify site](https://deploy-preview-9836--prefect-docs-preview.netlify.app/) or Loom [video demo](https://www.loom.com/share/96f179e7b2294d45871798bf603ecf32). 

Add feedback widget for docs

---

docs/cloud/webhooks.md
mkdocs.yml

This includes information on the API and example usage of Prefect Cloud webhooks
as of the initial release.  The section on how to use the Prefect CLI to set up
webhooks is stubbed in as a placeholder until that work is completed.
Note: this feature is currently disabled on Prefect Cloud until it is generally
available.  Using these APIs will return a 418 error until GA.
The examples are embedded within the documentation

Documentation for Prefect Cloud's webhooks

---

src/prefect/events/instrument.py

It'd be nice to be able to pass through `payload` with `emit_instance_method_called_event` in situations where I don't want the whole class to be instrumented (the `_events_exclude_methods` outnumber the methods I actually want to instrument, so `@instrument_method_calls_on_class_instances` didn't feel ideal)
I could also just use `emit_event` here if that seems more sensible, just thought I would try and leverage what already exists
```python
class Bot(MarvinBaseModel, LoggerMixin):
...
async def say(
self, *args, response_format=None, on_token_callback: Callable = None, **kwargs
) -> BotResponse:
...
bot_response = await self._say(
messages=messages, on_token_callback=on_token_callback
)
emit_instance_method_called_event(
self,
"say",
successful=True,
payload={
"user_message": …
```

allow passing `payload` to `emit_instance_method_called_event`

---

src/prefect/client/schemas/schedules.py
src/prefect/server/schemas/schedules.py
tests/server/schemas/test_schedules.py

We discovered that `RRULE` schedules that didn't include their own embedded
`DTSTART` were prone to producing a ton of extraneous schedules.  Each time
you asked one of these `RRULE` schedules to generate dates, it used the current
time as the anchor, so some types of rules would produce duplicates over and
over again because they weren't idempotent.
Adding a fixed `DTSTART` (which is only used if the rule doesn't have an
embedded one) makes sure that we always produce a stable set of dates/times no
matter when we ask.

Provide a default `DTSTART` to anchor `RRULE` schedules

---

src/prefect/client/cloud.py

our Prefect Cloud http client wraps the httpx.AsyncClient, so the `get()` method just proxied to the AsyncClient's `get()` method and threw a Cloud-specific exception on 401/403s
here, im defining a base `request()` method, so we can use it for more method types for an upcoming set of `prefect cloud` CLI commands, and invoking it from the existing `get()` method
relates to https://github.com/PrefectHQ/nebula/issues/4817

chore: add httpx request method to CloudClient

---

src/prefect/client/orchestration.py
src/prefect/client/utilities.py
tests/client/test_prefect_client.py

Previously, we pulled clients from the flow and task run contexts for `inject_client`. We stopped doing this once clients could span multiple threads during the engine event loop work (ref https://github.com/PrefectHQ/prefect/pull/8702/commits/a7033b0a8903ace51413ed3a3f92942f65a81401). However, this means that we've been instantiating more clients e.g. when creating results. We can safely allow `inject_client` to pull a client from the context if they share a common event loop.

Re-enable the retrieval of existing clients from flow and task run contexts when safe

---

src/prefect/cli/deployment.py
src/prefect/client/orchestration.py
src/prefect/deployments.py
src/prefect/events/actions.py
src/prefect/events/schemas.py
tests/client/test_prefect_client.py
tests/events/test_event_schemas.py
tests/fixtures/client.py
tests/test_deployments.py

This adds support for users defining triggers as part of their deployment specification. The spec for the triggers is an abbreviated form of the full Automation specification and results in an implicit `RunDeployment` action for the deployment that they're creating. It uses a wipe and create mechanism to ensure that duplicate automations are not created. 
Closes #9883 
```
name: my-deployment
...
triggers:
- enabled: true
match:
prefect.resource.id: prefect.flow-run.*
expect:
- prefect.flow-run.Completed
match_related:
prefect.resource.id: prefect.flow.<uuid>
prefect.resource.role: flow
parameters:
fast: true
```

Create automations when applying deployments that have trigger specifications

---

src/prefect/_internal/concurrency/calls.py
tests/server/services/test_flow_run_notifications.py

Instead of "timeout of None" we just won't display that text if there is no timeout.

Improve timeout display message for calls

---

src/prefect/cli/root.py
src/prefect/settings.py
tests/cli/test_root.py

Closes https://github.com/PrefectHQ/prefect/issues/9876
Adds a `--prompt`/--no-prompt` option as well as a `PREFECT_CLI_PROMPT` setting to disable interaction.
Due to limitations with typer (and for consistency with our other "global" flags), this must be specified _before_ the command group. For example:
```
❯ prefect --no-prompt cloud login
When not using an interactive terminal, you must supply a `--key` and `--workspace`.
```
Similarly, the setting can be used
```
❯ PREFECT_CLI_PROMPT=0 prefect cloud login                   
When not using an interactive terminal, you must supply a `--key` and `--workspace`.
```
Prompting can also be forced _on_ in cases where we do not detect a tty. …

Add `prefect --prompt/--no-prompt` to force toggle interactive CLI sessions

---

src/prefect/cli/deploy.py
tests/cli/test_deploy.py

This PR adds a deprecation warning when using `deploy` with a flow name by `--flow/-f`.
It is the first step towards removal of ability to deploy via flow name, which will occur when deployment ux leaves beta. See the draft PR for that at https://github.com/PrefectHQ/prefect/pull/9881.
```bash
❯ prefect deploy -f my-deployment
08:17:37.571 | DEBUG   | prefect.profiles - Using profile 'local_sqlite'
08:17:38.802 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////Users/bean/.prefect/prefect.db
The `prefect deploy --flow/-f` command has been deprecated. It will not be available after Jun 2023. 
Use `prefect deploy` to specify an entrypoint instead.
? Would you like to schedule when this flow runs? [y/n] (y): 
```
- If no issue exists and your …

Deprecate project deployment via `—flow/-f`

---

src/prefect/client/orchestration.py
src/prefect/client/schemas/objects.py
src/prefect/server/api/work_queues.py
src/prefect/server/api/workers.py
src/prefect/server/models/work_queues.py
src/prefect/server/models/workers.py
src/prefect/server/schemas/responses.py
tests/server/api/test_work_queues.py
tests/server/api/test_workers.py

Work pools can only be retrieved via their name, so if reading work queues directly, like in https://github.com/PrefectHQ/prefect-ui-library/pull/1428, an extra call is required to determine the name of the work pool that a work queue resides in. This PR adds `work_pool_name` to the response for work queue API routes to make it easier to get work pool information when starting with a work queue.

Add `work_pool_name` to work queue API responses

---

src/prefect/server/api/server.py

If application startup fails before services are created, the `services` item is missing from the application state and another exception is added to the traceback
```python
File "/opt/homebrew/Caskroom/miniforge/base/envs/prefect_env/lib/python3.10/site-packages/prefect/server/api/server.py", line 520, in lifespan
await stop_services()
File "/opt/homebrew/Caskroom/miniforge/base/envs/prefect_env/lib/python3.10/site-packages/prefect/server/api/server.py", line 502, in stop_services
if app.state.services:
File "/opt/homebrew/Caskroom/miniforge/base/envs/prefect_env/lib/python3.10/site-packages/starlette/datastructures.py", line 705, in __getattr__
raise AttributeError(message.format(self.__class__.__name__, key))
AttributeError: 'State' object has no attribute 'services'
```
This is …

Fix bug where attribute error raised on service shutdown when the app startup fails

---

docs/cloud/users/index.md

Adds user profile information to the Cloud Users landing page in docs, including what screens are behind the Profile page. This adds a direct link to the Profile page, which some users have a hard time finding.
- [x ] This pull request references any related issue by including "closes `<link to issue>`"
- [x ] This pull request includes tests or only affects documentation.
- [no permission, but should be docs ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.

Add additional user profile info to docs

---

src/prefect/server/api/server.py
tests/server/api/test_server.py

closes: https://github.com/PrefectHQ/prefect/issues/9923
SQLite transaction behavior was improved in https://github.com/PrefectHQ/prefect/pull/9594. A consequence of this is that in order to guarantee the expected behavior, the database must be locked for certain operations. In order to respect this without erroring, the API will send a 503 to tell the client to retry later if the database is locked.
The original pr covered the main locked cases, where a `SQLITE_BUSY` or `SQLITE_BUSY_SNAPSHOT` was being raised by sqlite and attached as the original exception when `sqlalchemy` would raise `sqlalchemy.exc.OperationalError`.
There appears more cases involving concurrent access where `sqlite3` will raise `sqlite3.OperationalError("database is locked")` with no attached original exception. I …

make more sqlite locking retryable

---

src/prefect/cli/project.py
tests/cli/test_project.py

- Deprecates `prefect project init`
- Deprecates `prefect project recipe ls`
- Deprecates `prefect project clone`
There will be a follow-up PR to deprecate the `projects` module and rename the `git_clone_project` step.
`prefect project init`
```bash
❯ prefect project
16:03:11.382 | DEBUG   | prefect.profiles - Using profile 'local_sqlite'
Usage: prefect project [OPTIONS] COMMAND [ARGS]...                                                                                                           
Deprecated. Use `prefect init` instead.                                                                                                                      
╭─ Options ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── …
```

Deprecate `prefect project` CLI command group

---

src/prefect/cli/deploy.py
tests/cli/test_deploy.py

Fixes an error where `prefect deploy` would fail when a `.prefect` folder is not present in the current directory or any parent directory. We relied on `register_flow` to return a flow object, but it would raise a `FileNotFoundError` if it couldn't find a `.prefect` folder. Deploying via flow name is deprecated, so we are catching that `FileNotFoundError` to remove the requirement to have a `.prefect` folder. We need to make sure that we load the flow object when catching this exception to continue deployment.
Closes #9971

Fix error in `prefect deploy` when `.prefect` folder is absent

---

src/prefect/cli/project.py
tests/cli/test_project.py

Closes #9962 
Fix bug where `recipe` variable reassigned in loop
cc @discdiver 

Fix exception raised in `prefect init` command when no recipe is selected

---

requirements.txt
src/prefect/cli/deploy.py
src/prefect/deployments/base.py
tests/cli/test_deploy.py

This PR adds a prompt at the end of the interactive `prefect deploy` UX asking users if they want to save their deployment configuration for later use. If the user accepts, the CLI saves the inputs to the interactive CLI in the `prefect.yaml` file in the current working directory. If a `prefect.yaml` file does not exist, one is created in the current working directory with the user inputs and any generated `pull` steps. Users will be prompted to save only for new deployment configurations.
Closes #9858 
[`prefect deploy` save prompt demo - Watch Video](https://www.loom.com/share/0a1ae32ad3c04085ba65e45b3e77d0e6)

Add prompt to save inputs to interactive `prefect deploy` command

---

src/prefect/cli/deploy.py
tests/cli/test_deploy.py

Switches the input for the deployments git_clone pull step created by the cli wizard to access_token rather than token.  Using the cli I was getting the following error in my runs: `TypeError: git_clone() got an unexpected keyword argument 'token'`

Switch token to access_token in cli wizard

---

src/prefect/client/schemas/schedules.py

If the error message does not appear to be a valid IANA tzdata timezone specifier, then we return an "Invalid timezone" error, but do not provide any hints to resolve.
This change updates the error message and documentation string to indicate that the timezone is to be specified in IANA tzdata format, such as America/New_York.
Closes: #10006
```
>>> from prefect.client.schemas.schedules import CronSchedule
>>> CronSchedule(cron="0 0 * * *", timezone="PST")
File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CronSchedule
timezone
Invalid timezone: "PST" (specify in IANA tzdata format, for example, America/New_York) (type=value_error)
``` …

Add hint to "Invalid timezone" error message

---

src/prefect/cli/_prompts.py
src/prefect/cli/deploy.py
src/prefect/deployments/base.py
tests/cli/test_deploy.py
tests/deployment/test_base.py
tests/test-projects/import-project/my_module/flow.py
tests/test-projects/nested-project/implicit_relative.py

This PR adds prompts to `prefect deploy` when run without a flow entrypoint. The CLI will recursively scan the current working directory and any sub-directories for flow functions and present the user with a list of discovered flow to choose from. The selected flow will be the one deployed.
If a user does not see the flow they want to deploy, they will have the option to select none of the flows and manually enter a flow entrypoint.
If no flows are discovered, the user is prompted to enter a flow entrypoint. The entrypoint prompt will validate that a flow can be loaded from the entrypoint before proceeding.
Closes #9909 
Example of a list of flows presented to a user:
Example of entry point validation:
[`prefect deploy` run without an entrypoint - Watch …

Add prompt to `prefect deploy` to allow user to select from list of discovered flows

---

src/prefect/cli/_prompts.py
src/prefect/deployments/base.py
src/prefect/utilities/filesystem.py
tests/deployment/test_base.py

Adds an `asyncio.semaphore` for use across invocations of `_find_flow_functions_in_file` for cases where many files are being scanned for flows. Previously, users would encounter an `OSError` saying that too many files were open. This PR also adds a spinner to display while scanning for flows to show the CLI is working while scanning large directories.

Limit the number of files opened concurrently by `prefect deploy`

---

src/prefect/client/cloud.py
src/prefect/client/orchestration.py
src/prefect/settings.py
tests/client/test_base_client.py
tests/client/test_cloud_client.py
tests/client/test_prefect_client.py
tests/conftest.py

This is a first pass at the following issue:
closes https://github.com/PrefectHQ/prefect/issues/9773
This was the suggested course of action (see comment from @zanieb):
-- https://github.com/PrefectHQ/prefect/issues/9773#issuecomment-1568779492
**PS. I'm not familiar with the prefect codebase, just grabbed a few random issues tagged with `good first issue`, so review with extreme caution :)**

Issue 9773: Default HTTPX  follow_redirects to true

---

src/prefect/cli/deploy.py
src/prefect/testing/utilities.py
src/prefect/utilities/templating.py
tests/cli/test_deploy.py
tests/utilities/test_templating.py

Step chaining is not working in the `pull` action, because non-block placeholders are wiped out before saving a deployment's `pull` steps. This PR updates templating for `pull` steps to not remove unset placeholders.
Closes https://github.com/PrefectHQ/prefect/issues/10052

Fix pull step saving by preserving placeholders with missing values

---

docs/tutorial/flows.md

`retries=3, retry_delay_seconds=5` should be @flow's parameter instead of the `get_repo_info` function.

fix: demo usage about @flow parameter.

---

src/prefect/_internal/schemas/transformations.py
src/prefect/engine.py
src/prefect/settings.py
src/prefect/testing/utilities.py
src/prefect/utilities/importtools.py

I was reading the docs and noticed some example sections rendering like this:
for docstrings that use doctest format.  I noticed a mixture of markdown and doctest format, but I only altered the existing occurrence of doctest format with 'Example' instead of 'Examples'.  I only noticed this because I've done the same thing on some of my projects that use `mkdocstrings`.

docs: rename 'Example' to 'Examples' in code blocks

---

src/prefect/utilities/filesystem.py
tests/utilities/test_filesystem.py

Prefect 2.10.17 added a Unix only import in `utilities/filesystem.py` that breaks when running Prefect server or an agent on Windows. 
Credit to @grenzi for suggesting a solution to this; this PR only differs from their PR #10055 in calling `getmaxstdio` without adding a dependency on `pywin32`.
This PR calls a function in the Windows Universal C runtime to perform the same check on Windows, and scopes the `resource` module import to ensure it won't run on Windows. Using `ctypes` in this instance should be safe, as Microsoft is unlikely to remove the Universal C runtime DLL from Windows given how many of their own applications depend on it.
See https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/getmaxstdio for more detail.
Closes #10054
Closes #10058
Although this PR adds a …

Fix windows file limit check

---

.github/workflows/codeql-analysis.yml
.github/workflows/python-tests.yaml
.github/workflows/static-analysis.yaml
.github/workflows/ui-tests.yml

Our previous GitHub concurrency settings were cancelling pending executions on push events, rather than queuing them as expected.
This updates our settings so that each run uses a different concurrency group on push events.

Update build concurrency settings

---

docs/concepts/deployments-ux.md

Adds two additional pull step examples using a run_shell_script, and an arbitrary function call.
- [x ] This pull request includes tests or only affects documentation.
- [x ] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`, `docs`.

Add custom pull step examples with variables

---

src/prefect/workers/base.py
tests/workers/test_base_worker.py

Adds call to `resolve_variables` when preparing a flow run configuration for a worker. This will resolve any Prefect variables that are present in either the `base_job_template` for a worker or the `infra_overrides` defined on the deployment.
Closes https://github.com/PrefectHQ/prefect/issues/10071
The reproduction outlined in the linked issue now correctly prints the value of the configured variable.
A deploy config like the following will use the underlying value of the Prefect variable rather than the placeholder itself:
```yaml
deployments:
- name: foo
entrypoint: flow.py:main
work_pool:
name: foo-process
job_variables:
env:
FOO: "{{ prefect.variables.foo }}"
``` …

Allows use of Prefect variables in `job_variables` section of deploy config in `prefect.yaml`

---

src/prefect/utilities/callables.py
tests/utilities/test_callables.py

Closes https://github.com/PrefectHQ/prefect/issues/10066
Adds a default value to fix the issue of KeyError exception being raised if a mapped task accepts `**kwargs` but does not use them.

Add default option to new_parameters.pop in `explode_variadic_parameter` used to handle `**kwargs` in task mapping

---

src/prefect/cli/deploy.py
tests/cli/test_deploy.py

DESCRIPTION OF THE PULL REQUEST:
Changes have been made in two files: 'test_deploy.py' and 'deploy.py'. Since code deployment through flow names is no longer possible and has been deprecated, the 'prefect deploy --help' command needs to be updated accordingly. Additionally, the 'ValueError' in the 'deploy.py' file has been modified to match the same error in the 'test_deploy.py' file, ensuring consistency and maintaining the integrity of the tests.
Fixes:#9984

Improve language around `prefect deploy` to not recommend creating a deployment by flow name

---

ui/src/maps/featureFlag.ts
ui/src/pages/Dashboard.vue
ui/src/types/flagResponse.ts

Adds the ui for the experimental dashboard that has flow run, task run, and work pool information. This will become the default view once it is no longer experimental.

Experimental Dashboard UI

---

docs/concepts/deployments-ux.md

With the new `credentials` field available in the `git_clone` step, we'll want to ensure our documentation shows how to do this in the variety of possible ways (`GitHubCredentials` block, `Secret` block, etc.)
Part of closing #9918

Update `git_clone` documentation with examples of using `credentials` field

---

src/prefect/deployments/deployments.py

The documentation for `prefect.deployments.Deployment` currently has no mention of `work_pool_name`. This small PR adds this to the docstring.
Documentation change only.

Update to `Deployment` docstring

---

src/prefect/deployments/base.py

Currently when we've got a conflicting entrypoint we see the following message:
This PR aims to improve the message by making the difference in current working directory obvious:

Improve `prefect deploy` error message

---

src/prefect/deployments/base.py

We should remove the dead end from this error message by providing the workaround documented in this Discourse article.
https://discourse.prefect.io/t/after-changing-the-location-of-my-flow-file-i-get-an-error-when-trying-to-run-prefect-deploy-conflicting-entry-found-for-flow-with-name/3188

Add another improvement to `prefect deploy` message

---

docs/concepts/deployments-ux.md
src/prefect/cli/deploy.py
tests/cli/test_deploy.py
tests/deployment/test_base.py
tests/test-projects/flows/hello.py

In the following `prefect.yaml`:
```bash
deployments:
- name: "default"
entrypoint: "flows/hello.py:hello"
- name: "default"
entrypoint: "flows/hello.py:hello_parallel"
```
Running `prefect deploy -n default` currently deploys both flows. It would be ideal to prompt the user on which flow to deploy if in interactive mode, and at least allow users to deploy by `flow-name/deployment-name`. This PR does both.
Regardless of whether a user opts to use the wizard or not, this PR adds support for deploying a deployment prefixed with the flow name. This way users do not need to resort to workarounds like [prefixing their flow name **inside** of their deployment name](https://github.com/PrefectHQ/prefect/issues/9913#issuecomment-1593604049). 
```bash
❯ prefect deploy -n log-flow/default
? Your …
```

Support deploying by name with multiple deployments with the same name during `prefect deploy`

---

src/prefect/settings.py
tests/_internal/compatibility/test_experimental.py
tests/server/test_app.py

In advance of releasing the feature, this sets the default for `WORKSPACE_DASHBOARD` to `True`.

Turn workspace dashboard flag on by default

---

src/prefect/deployments/base.py

If a user forgets use `-n` when running the `prefect deploy` command, e.g. `prefect deploy default` when they mean to run `prefect deploy -n default`, they will be prompted to use the wizard to select a deployment; then they will receive an error because the second positional argument is entrypoint, not deployment name. This PR is a stopgap, improving the error messaging to guide users who mistakenly forget to use `-n`.

Enhance `prefect deploy nonexistent-entrypoint` `ValueError` with possible solution

---

docs/concepts/settings.md

The Profiles & Configuration docs make reference to a command, `get` that doesn't exist. Removing these references closes #10186 

Remove references to `profile get`

---

src/prefect/cli/work_pool.py
src/prefect/server/api/workers.py
tests/cli/test_work_pool.py
tests/server/api/test_workers.py

Currently it is possible for users to create work pools with empty string names; this is a problem for a number of reasons, one of which is that these work pools cannot be deleted due to this creating invalid path specs for the delete route.  This PR adds validation to both the OSS server as well as the CLI for protecting against users getting into this situation.
Closes https://github.com/PrefectHQ/prefect/issues/10193
We raise 422 for other name-validation failures, but I don't think that is correct; 422 should be for unprocessable entities, meaning payloads with unknown or missing fields, not for payloads with "bad" values.  For that situation we should raise 400.  I didn't change the other status codes here because that would _technically_ be a breaking change, but wanted to call it …

Work pool name validation

---

ui/src/pages/Dashboard.vue

Adds the missing interval to the dashboard so that it refreshes automatically every 30 seconds.

BugFix: Dashboard not refreshing automatically

---

src/prefect/futures.py
tests/test_futures.py

Make `resolve_futures_to_data` function raise on failure by default (#9361)

---

tests/cli/test_deploy.py

I keep seeing this test fail on essentially every PR; every other test in this repository uses the `project_dir` fixture to ensure a stable path, so I'm taking an educated guess that this is causing the `FileNotFoundError`s we're seeing non-deterministically.  Time will tell.

Add project_dir fixture to brittle test

---

src/prefect/_internal/schemas/bases.py
tests/fixtures/client.py
tests/test_deployments.py

The function `orjson_dumps_extra_compatible` was created for dumping a value to JSON using orjson, the purpose is to allow for more complex keys (from the [documentation](https://github.com/PrefectHQ/prefect/blob/4c8d8e4fe055cec7fa07da80cc21ff08e32f03f6/src/prefect/_internal/schemas/serializers.py#L15)):
> 1) non-string keys: this is helpful for situations like pandas dataframes,
which can result in non-string keys 
Using it to solve the bug in question, seems fitting. 
closes #10216

Use orjson_dumps_extra_compatible when serializing in `build_from_flow` (#10216) 

---

src/prefect/runtime/flow_run.py

Noticed we had some undocumented runtime values for flow runs, this PR adds them to our docs.

Add undocumented runtime parameters

---

ui/src/pages/FlowRuns.vue

Re-implements the infinite scroll for flow runs on the flow runs page and adds the missing polling interval.

Fix flow runs page not polling for new runs and not loading more flow runs when scrolling

---

.github/workflows/python-tests.yaml

Our `main` branch is _never_ healthy due to these job cancellations; increasing timeout to 60 minutes as a bandaid.

Increase timeout to an hour to prevent cancellation failures on main

---

src/prefect/settings.py

Right now we are creating / touching the default database file when _loading_ the current Prefect settings (the `touch` logic lived within the logic for determining the default value of `PREFECT_API_DATABASE_CONNECTION_URL`) which is not an appropriate place to create this file.
I tested locally and this file _is_ still created when this line is removed (I'm guessing by sqlite internals).
Closes #9840 

Dont create DB default during settings load

---

src/prefect/deployments/base.py

~./prefect should be ~/.prefect in duplicate deploy error message. Bug found by Raoul B. at PACC.
- [n/a] This pull request references any related issue by including "closes `<link to issue>`"

Fix incorrect path in error message

---

src/prefect/filesystems.py
tests/test_filesystems.py

Closes https://github.com/PrefectHQ/prefect/issues/10254
When a `LocalFileSystem` was specified with a `basepath`, `get_directory` would fail when provided with a relative `from_path`. In addition, no checks were performed to ensure `from_path` was within the `basepath`. Both of these issues are addressed by using `LocalFileSystem._resolve_path`, as is done in `RemoteFileSystem.get_directory`.
A test was added for using `get_directory` with a relative `from_path`. In addition, two tests relied on the missing check above, so were fixed:
* `test_dir_contents_copied_correctly_with_get_directory`
* `test_get_directory_empty_local_path_uses_cwd`
``` python
fs = LocalFileSystem(basepath="path/with/subdirectory")
fs.get_directory(from_path="subdirectory") # Previously failed
```
- If no issue …

Fix LocalFileSystem.get_directory with basepath behaviour 

---

src/prefect/client/orchestration.py
src/prefect/client/schemas/actions.py
src/prefect/deployments/deployments.py
src/prefect/server/api/deployments.py
src/prefect/server/api/workers.py
src/prefect/server/schemas/actions.py
tests/cli/test_start_agent.py
tests/server/api/test_deployments.py

This PR exposes a `work_queue_name` field when creating a flow run for a deployment that allows users to override the queue setting on the deployment on a per-run basis.  If the queue name does not already exist, one is created within the work pool set for the deployment.
Closes #10257 
Closes #10261 
I will also work on exposing this field within the UI as a next step.

Allow setting a work queue per flow run

---

src/prefect/client/orchestration.py
src/prefect/client/schemas/responses.py
src/prefect/concurrency.py

This creates the general use `concurrency` context manager. I'm calling this a `proof-of-concept` because I'm currently unable to write useful tests as the API portion of this only exists in Cloud and that API is still in flux. Tests will be added after the API portion is ported.
```python
import sys
import asyncio
import random
from prefect.concurrency import concurrency
from prefect.blocks.system import String
trees = ["🌲", "🌴", "🌳"]
@task
async def get_random_tree() -> str:
with concurrency("trees"):
await asyncio.sleep(1)
return random.choice(trees)
@flow
async def happy(num_trees: int):
futures = []
for _ in range(num_trees):
futures.append(await get_random_tree.submit())
for future in futures:
tree = await future.result()
print("Here's a happy little …
```

Build out a proof-of-concept concurrency context manager.

---

src/prefect/client/orchestration.py
src/prefect/concurrency.py

This implements the `rate_limit` form of concurrency limits where there is no explicit decrement and a slot decay is used instead. Much like the `concurrency` context manager this PR includes no tests and will be 'codified' when the API is ported to OSS.
```python
import asyncio
import datetime
from prefect.concurrency import rate_limit
def resource_hog():
rate_limit("hog")
print(datetime.datetime.now())
async def main():
await asyncio.gather(*[resource_hog() for _ in range(3)])
asyncio.run(main())
```

Implement `rate_limit` function to block execution while acquiring slots

---

src/prefect/engine.py
src/prefect/exceptions.py
src/prefect/states.py
tests/test_engine.py

Currently you cannot pause task runs; this was originally designed this way because task runs cannot be individually resumed.  However, if a user explicitly puts a task run into a Paused state, the flow run should pause likewise using the same settings, and now the flow run can resume as intended.
This PR allows task runs to explicitly return `Paused` states, and the flow run will behave as expected.
Closes https://github.com/PrefectHQ/prefect/issues/8442
```python
from prefect.states import Paused
@task
def pause_sometimes(pause):
import random
if random.random() > 0.5:
return Paused()
@flow 
def pause_flow():
pause_sometimes()
return 42
```
If you execute this using your favorite method, you'll find that half the time the task run will enter a Paused …

Pause task runs

---

docs/guides/index.md

Update index.md to point to ECS worker guide and not agent/infra block guide

Point to ECS worker guide and not agent/infra block guide

---

src/prefect/cli/deploy.py
tests/cli/test_deploy.py

Skip build docker image prompt when a deployment has explicitly set the `build` step to `null` in `prefect.yaml`. See the attached issue for an example. Previously if `build` was set to `null`, users would still see prompts to build a docker image on every interactive `prefect deploy` run for that deployment. This change allows users to configure deployments without running a build step and without needing to opt out of the prompt every time.

Update `prefect deploy` to skip building docker image prompt if `build` key explicitly set to null in `prefect.yaml`

---

.github/workflows/stale.yml

Issues which keep the `status:triage` label for over 60 days with no activity are marked as stale. Since these issues await action from our team, they should not be marked as stale. 
Currently, issues needing product feedback are not being moved out of `status:triage` in time before they are marked as stale and closed. This PR excludes them from a hasty fate to a stale status.

Exempt issues needing product feedback from being prematurely marked as stale

---

.github/workflows/issue-bot.yaml
.github/workflows/stale.yml

This PR updates our bot rules to be:
- mark PRs with no activity stale after 14 days
- close PRs with no activity after 14 days (marking the PR as "stale" counts as activity)
- never auto-close an issue

Update to bot workflows

---

docs/concepts/agents.md
docs/concepts/deployments-block-based.md
docs/concepts/infrastructure.md
docs/guides/index.md
docs/guides/upgrade-guide-agents-to-workers.md
mkdocs.yml

The agents Agents -> Workers upgrade guide belongs in the guide section. We can link to it from wherever we'd like. I've added links to the top of the agents, infrastructure, and block based deployment pages.

Move and reference Agents -> Workers upgrade guide

---

.github/ISSUE_TEMPLATE/1_general_bug_report.yaml
.github/ISSUE_TEMPLATE/2_ui_bug_report.yaml
.github/ISSUE_TEMPLATE/3_feature_enhancement.yaml
.github/ISSUE_TEMPLATE/4_docs_change.yaml
.github/ISSUE_TEMPLATE/5_maintenance_ticket.yaml

Our issue templates can't reference the non-existent `status:triage` label. This PR updates the auto-label for issues to `needs:triage`.

Update issue templates

---

setup.cfg
src/prefect/cli/config.py
src/prefect/settings.py

When users misconfigure their `PREFECT_API_URL`,  we should try to let them know as soon as possible.
With this PR, when a `PREFECT_API_URL` is misconfigured, running profile CLI commands such as `prefect profile ls`, `prefect profile use <profile-name>`, and `prefect config set <profile-name>` will generate a warning.

Warn users with misconfigured `PREFECT_API_URL`

---

src/prefect/server/models/task_runs.py
src/prefect/server/schemas/filters.py

We have observed poor performance of the Prefect Server in responding to the `/task_runs/filter` endpoint, and have seen mention in the Prefect Slack of other users reporting similar findings.
The code supporting `/task_runs/filter` is general enough to be able to allow filtering on lots of different criteria. For any filter criteria provided, the query generates a `WHERE EXISTS` clause based on that filter criteria.
But the main use case for this endpoint is to simply fetch the task runs for a particular `flow_run_id`. In our workload (and I suspect in many other users') this represents 99%+ of the invocations of this endpoint. However, the `WHERE EXISTS` DB query generated for this use case is much less efficient than it needs to be.
Specifically, when the endpoint is asked to simply …

Optimize the query generated by the /task_runs endpoint

---

src/prefect/blocks/notifications.py
tests/blocks/test_notifications.py

Adds a DiscordWebhook notification block using the AbstractAppriseNotificationBlock
Closes #8727
```
In [1]: from prefect.blocks.notifications import DiscordWebhook
In [2]: discord_webhook_block = DiscordWebhook.load("discord-prefect")
In [3]: discord_webhook_block.notify("Hello from Prefect!!")
```

add discord notification block

---

src/prefect/server/models/task_runs.py
src/prefect/server/schemas/filters.py

We got an [awesome community contribution to optimize the task runs filter](https://github.com/PrefectHQ/prefect/pull/10422)
endpoint, but it needed a couple of safety guards:
* We should make sure that the ID filter is only making positive matches on
ID (with `any_`) and not negative matches
* We should support multiple flow run IDs with an `IN` clause

Adding some safety checks to a prior optimization on task runs

---

src/prefect/cli/deploy.py

with the `project` command group deprecated, we should direct the user to `prefect init` for more for information around flow storage / `prefect.yaml` setup

update wizard recommendation when no `pull` step selected

---

docs/overrides/partials/integrations/analytics/custom.html

Switch from searchParams.append to searchParams.set to fix duplicate deviceIds getting added to URLs.

Fix duplicate Amplitude deviceId

---

docs/concepts/deployments.md

As described in the linked issue, our documentation refers to `flow_name` as a deprecated but still valid option for use in deployments, when in reality, it is no longer usable and should be removed from our documentation. 
[Preview](https://deploy-preview-10477--prefect-docs-preview.netlify.app/concepts/deployments/#deployment-fields)

Remove references to `flow_name` from deployments documentation

---

src/prefect/cli/worker.py
tests/cli/test_worker.py

DESCRIPTION OF THE PULL REQUEST:
Currently in Prefect, if a user pauses a work-pool using the CLI command, the user can start the worker for polling on the paused work-pool. This way, the user will get confused about why the worker is not polling from the work-pool. The change I have made is to add a CLI message to inform the user that the work-pool is paused.
I have implemented a logic to check if the worker is paused or not. If it is paused, a message is displayed indicating that the work-pool is paused, and the worker execution is aborted. Therefore, the user must resume the work-pool before starting with the polling. I have tested this modification on the Prefect agent so far
Fixes: #10308 
https://github.com/PrefectHQ/prefect/assets/121633121/9e0d39b9-fdc2-4f12-ae77-248d363d9636
- If …

Show cli message for the paused work-pool 

---

src/prefect/flows.py
tests/test_flows.py

Despite raising an error when we run a flow locally, it would be nicer to validate the name on the Flow object.
```python
from prefect import flow, runtime
import datetime
def get_flow_run_name():
date = datetime.datetime.now().isoformat()
return f"{runtime.deployment.name}-{date}"
@flow(log_prints=True, name=get_flow_run_name)  # mistake here, should be get_flow_run_name()
def hi_named_flow(name:str="world"):
print(f"Hi {name}")
```
```bash
❯ python flow_10023.py
13:52:48.270 | DEBUG   | prefect.profiles - Using profile 'cloud'
File "flow_10023.py", line 10, in <module>
def hi_named_flow(name:str="world"):
File "/Users/bean/prefect-demo/38pyvenv/lib/python3.8/site-packages/prefect/flows.py", line 821, in flow
Flow(
File …
```

Improve validation for `Flow.name`

---

.github/workflows/python-tests.yaml

previously this notification was sent anytime any CI failed on main, which was needlessly noisy
this PR implements a threshold with github artifacts (its surprisingly annoying to share data across matrixed jobs)
I've set `FAILURE_THRESHOLD: 3` on the `env` of the notification job - let me know if a different value is more appropriate

threshold for notifying about failing tests on main

---

mkdocs.yml

Not sure what happened but #10545 reverted some changes to `mkdocs.yml` that this PR brings back

Bring back mkdocs title changes

---

src/prefect/deployments/deployments.py
tests/test_deployments.py

Updates `run_deployment` to pull the flow run ID and dynamic key from the task run context when the flow run context is not available. This occurs when the task is run on a remote task runner like Dask or Ray. With this change, subflows for deployments run in a task will show up in the flow run timeline.
Closes https://github.com/PrefectHQ/prefect/issues/9135
Before:
After:

Fix subflow linking when using `run_deployment` with Dask and Ray task runners

---

src/prefect/cli/flow.py

Using this kwarg introduced a non-backwards compatible version issue with the `typer` library, so avoiding its use for now.

Dont use default factory for version compatibility

---

ui/src/pages/Deployment.vue

Fixes an issue where viewing a deployment on a larger screen would cause no tab to be displayed.

Deployment page showing a blank tab on desktop

---

src/prefect/runner.py
tests/test_runner.py

- Adds missing example to `serve` docstring
- Update runner to log when pausing schedules for deployments
- Fixes misformatted example in `Runner.start()` docstring

Add `serve` example and logs for schedule pausing

---

ui/src/pages/WorkPool.vue
ui/src/pages/WorkPoolQueue.vue

Fixes an issue where names with spaces in them would cause the command to not be valid and not run.

Always use quote for work pool and work queue names in cli commands

---

ui/src/pages/AppRouterView.vue

This PR updates the overall UI layout and how it scrolls in order to enable sticky headers to function properly and trigger the intersection observer required to apply the proper styles when stuck. It also fixes the fullscreen flow run graph.

fix layout so sticky headers work

---

src/prefect/_internal/concurrency/services.py
src/prefect/logging/handlers.py
tests/_internal/concurrency/test_services.py

Closes https://github.com/PrefectHQ/prefect/issues/10456
Full tracebacks for Batched/QueueServices startup/item-processing failures will only be logged if the log level is set to `DEBUG`. Otherwise, the output only contains the log message. The hope is this will make it easier to understand where errors are coming from while still allowing access to detailed information. 
Log line for an item processing failure at `DEBUG`:
```
16:39:35.649 | WARNING | GlobalEventLoopThread | prefect._internal.concurrency - Service 'ExceptionOnHandleService' failed to process item 1
File "/Users/uriel/Projects/github.com/PrefectHQ/prefect/src/prefect/_internal/concurrency/services.py", line 151, in _main_loop
await self._handle(item)
File …
```

Reduce logging noise on QueueServices startup failures and item processing failures

---

netlify.toml
src/prefect/runner.py
src/prefect/settings.py
tests/test_runner.py

This new setting:
- sets a default limit for the number of processes a runner will submit in parallel (so by default you can't crash one)
- uses a setting to configure that limit via environment variable
I decided not to expose any new kwargs on `serve` yet until we know how we want users to think of the runners that `serve` spawns.
**cc:** @EmilRex 

Expose a setting for configuring a process limit on served flows

---

.github/workflows/python-tests.yaml

I noticed that a dependabot PR failed to run the test suite because our
"isinternal" check to see if the user is a PrefectHQ organization member was
including the `[bot]` suffix and causing an error from cURL.  This check is
used to decide whether the PR is run on our faster internal machines, which we
would want for dependabot, so we'll shortcut the API call and just treat them
as internal.
https://github.com/PrefectHQ/prefect/actions/runs/6078894220/job/16490683120?pr=10622

When dependabot makes a PR, treat it as an internal user

---

tests/test_filesystems.py

In this new version of `fsspec`, there's been [some adjustments to how globs are
processed][1], which has the side-effect of returning the base directory when
doing a glob like `/some-dir/**` (this also includes `/some-dir`).
[1]: https://github.com/fsspec/filesystem_spec/commit/c3b4bc36a8c2fa1b98429f5cd963ea0b4d04ad11

Accounting for a change in how `fsspec==2023.9.0` handles globs

---

docs/concepts/flows.md
src/prefect/flows.py
src/prefect/settings.py
tests/utilities/test_visualization.py

- Removes experimental decorator from `flow.visualize()`
- Disables visualize experimental setting to silence experimental warning
Closes https://github.com/PrefectHQ/prefect/issues/10628

Remove experimental status from `flow.visualize()`

---

docs/guides/index.md
mkdocs.yml
netlify.toml

Closes #10617 
Docker guide links now work and match nav.
Preview:  https://deploy-preview-10624--prefect-docs-preview.netlify.app/guides/

Fix broken link to docker guide with redirect and harmonize naming

---

src/prefect/settings.py

Removes deprecated logging settings:
- `PREFECT_LOGGING_TO_API_ENABLED`
- `PREFECT_LOGGING_TO_API_BATCH_INTERVAL`
- `PREFECT_LOGGING_TO_API_BATCH_SIZE`
- `PREFECT_LOGGING_TO_API_MAX_LOG_SIZE`
- `PREFECT_LOGGING_TO_API_WHEN_MISSING_FLOW`

Remove deprecated `ORION` logging settings

---

src/prefect/cli/server.py
tests/cli/test_server.py

**Note: The base branch for this PR is not main, it is remove-deprecated-orion-refs.**
Removes deprecated `prefect orion` command group in favor of `prefect server`.
```bash
❯ prefect orion start
Usage: prefect [OPTIONS] COMMAND [ARGS]...
Try 'prefect --help' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ No such command 'orion'.                                                                                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
``` …

Remove deprecated `prefect orion` CLI

---

src/prefect/server/utilities/server.py

Remove deprecated `OrionRouter` and `OrionAPIRoute`

---

src/prefect/server/api/server.py

Remove deprecated `create_orion_api`

---

src/prefect/logging/handlers.py

Remove deprecated `OrionHandler` and  `OrionLogWorker`

---

src/prefect/cli/kubernetes.py

Remove deprecated `kubernetes manifest orion` command

---

src/prefect/cli/worker.py
src/prefect/client/orchestration.py
src/prefect/client/schemas/objects.py
src/prefect/server/api/workers.py
src/prefect/server/database/migrations/MIGRATION-NOTES.md
src/prefect/server/database/migrations/versions/postgresql/2023_09_06_085747_50f8c182c3ca_.py
src/prefect/server/database/migrations/versions/sqlite/2023_09_06_084729_c2d001b7dd06_.py
src/prefect/server/database/orm_models.py
src/prefect/server/models/workers.py
src/prefect/server/schemas/__init__.py
src/prefect/server/schemas/core.py
src/prefect/server/schemas/responses.py
src/prefect/server/schemas/statuses.py
src/prefect/workers/base.py
tests/cli/test_worker.py
tests/server/api/test_workers.py
tests/workers/test_base_worker.py

This PR adds status to both work pools and workers. Work pool and worker status will be displayed in the UI to help users debug when work isn't being executed as expected.
Workers have two statuses: `ONLINE` and `OFFLINE`. A worker is online if it sends regular heartbeat messages to the Prefect API. If a worker has missed three heartbeats, it will be considered offline. In the default case, a worker would be considered offline a maximum of 90 seconds after it stopped sending heartbeats.
Work pools have three statuses: `READY`, `NOT_READY`, and `PAUSED`. A work pool is considered ready if it has at least one online worker sending heartbeats to the work pool. If a work pool has no online workers, it is considered not ready to execute work. If a work pool is paused, it will have a paused …

Add status to work pools and workers

---

docs/guides/deployment/kubernetes.md

Currently, the indentation shows the ` ```json ... ` part of formatting as text.
https://docs.prefect.io/latest/guides/deployment/kubernetes/

Chore: Fix AKS docs JSON section

---

src/prefect/client/orchestration.py
src/prefect/results.py
tests/results/test_result_factory.py
tests/test_states.py

New `LocalFilesystem` block documents were being created and saved on every flow run, which led to unbounded DB table growth.
This PR changes the behavior of our `ResultFactory` so that it will not create a remote storage block for flows (and tasks) unless features that require persistence are enabled (flow retries, task caching, `persist_results=True`, etc). This will cut down on DB table growth __unless__ the user is actually asking for features that require it. 
This PR has been improved by adding defensive checks to <LOUDLY> let us know where storage block ids set to `None` can cause problems. See https://github.com/PrefectHQ/prefect/pull/10649#discussion_r1319157753
Resolves #10358 and resolves #9950
Repeated runs for this flow will not create any entries in the DB's `block_document` …

Don't create unpersisted blocks remotely

---

docs/concepts/agents.md

Improves formatting of bash output in code blocks on concepts/agents page. 
Makes other minor improvements to the page (including removing mention of work-queue where it doesn't make sense).
- [ n/a] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

`no-copy` output code block in docs agents concept page

---

tests/client/test_base_client.py

With the latest realse of `httpx==0.25.0`, the documentation url for response codes has changed: https://github.com/encode/httpx/blob/master/CHANGELOG.md#0250-11th-sep-2023
This breaks a test as it makes the str version of an exception slightly longer, and the value we are checking for is truncated. 
```
<ExceptionInfo PrefectHTTPStatusError("Client error '400 Bad Request' for url 'fake.url/fake/route'\nResponse: {'extra_info': [{'mess...: 'a test error message'}]}\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400") tblen=5>
```
This fixes it by using `str(exc.exconly())` to get the full string.

fix base client test

---

src/prefect/flows.py
tests/test_flows.py
tests/test_tasks.py

When we parse a function using the `flow` decorator and later when we try to run it using some input, we do some `pydantic`-based validation to ensure that the arguments provided match with what the decorated function expects as input. The validation introspects the function signature to understand what needs validating and how to validate it. When dealing with builtins or `BaseModels` as type hints, `pydantic` knows how to perform validation. The problem comes from using _plain_ Python classes as type hints because `pydantic` can't do deep validation on _plain_ classes so it will raise an error `RuntimeError: no validator found for <class 'ase.atoms.Atoms'>`
This PR changes the validation config to include `arbitrary_types_allowed` which will change the type of validation  `pydantic` …

Allow Python classes as flow/task type hints

---

src/prefect/server/schemas/filters.py
tests/server/api/test_flows.py

This adds an `is_null` filter for deployments to the flows/filter route to be able to read flows that have associated deployments or have no associated deployments.
Closes #10715 
To get all flows that have at least one associated deployment:
```
{
"flows": {"deployment": { "is_null_": false}}
}
```
To get all flows that do not have any associated deployments:
```
{
"flows": {"deployment": { "is_null_": true}}
}
```

Add an `is_null` filter for Deployments to flows/filter

---

docs/guides/deployment/push-work-pools.md

Currently, if I type "push" into the search bar in the docs, "Push Work to Serverless Computing Infrastructure" is the top result; but once I type "push work", the result disappears, leading to decreased visibility.

Add `push work pools` tag to push work pools guide to raise visibility

---

src/prefect/cli/deploy.py

This PR has no user-facing change but refactors `_pick_deploy_configs` which encapsulates how we determine which deploy configs to deploy. The helper function has grown to the point that I felt refactoring it an important first step in increasing readability before further development/improvements in `_pick_deploy_configs`.
There are no test changes. 
A few helper functions have been added:
- `_handle_pick_deploy_with_name`
- `_find_matching_deploy_config`
- `_log_missing_deployment_names`
- `_handle_pick_deploy_without_name`
If these helper function names are ambiguous, I'd always appreciate more name suggestions.

Refactor deployment config selection in `prefect deploy`

---

docs/concepts/deployments-block-based.md
docs/concepts/deployments.md

All styles of deployment have a boost of 2; I think we should allow `/concepts/deployments.md` and `/guides/prefect-deploy.md` to keep the boost whilst we could it from this page along with the `prefect.yaml` tag. But, welcome to differing thoughts! 
Current search results order in documentation:
When discussing the two approaches to deployments on the deployments concept page, link to our guide to raise its visibility:
**[Related community question that this stems from](https://prefect-community.slack.com/archives/CM28LL405/p1694769482045889)**

Remove boost from block-based deployments page in documentation, improve visibility of `prefect deploy`

---

src/prefect/server/database/migrations/MIGRATION-NOTES.md
src/prefect/server/database/migrations/versions/postgresql/2023_09_21_130125_4e9a6f93eb6c_make_slot_decay_per_second_not_nullable.py
src/prefect/server/database/migrations/versions/sqlite/2023_09_21_121806_8167af8df781_make_slot_decay_per_second_not_nullable.py
src/prefect/server/database/orm_models.py

This updates the `slot_decay_per_second` column on the global concurrency limit table to not allow null values. Having null values causes validation errors when retrieving concurrency limits from the API. 
Related to #10779 

Make `slot_decay_per_second` not nullable

---

src/prefect/cli/work_pool.py
tests/cli/base-job-templates/process-worker.json
tests/cli/test_work_pool.py

This adds a --base-job-template feature when creating work pools, rather than using the default base job template.
Related to #9576

Add ability to create work pools with a base template

---

src/prefect/client/orchestration.py
tests/client/test_prefect_client.py

If a work pool is missing, the server will return a 404, and we propagate the exception. This change returns a friendlier ObjectNotFound exception, similar to other client code.

Return ObjectNotFound from update_work_pool

---

src/prefect/cli/work_pool.py
tests/cli/test_work_pool.py

This adds a command that allows several work pool properties to be updated, including the base job template, concurrency limit, description, or combinations thereof.
Related to #9576

Add command for updating work pools

---

src/prefect/cli/worker.py
src/prefect/workers/base.py
tests/cli/test_worker.py

On "prefect worker start", allow users to pass in the base job template instead of using the default.
Related to #9576

Configure base job template during worker startup

---

src/prefect/client/schemas/filters.py
src/prefect/server/schemas/filters.py
tests/server/api/test_flow_runs.py

Adds a filter where, given the ID of a flow run, it filters all the direct
subflows of that flow (not recursive).

Flow run filter for fetching the (first-level) subflows of a given flow

---

src/prefect/client/orchestration.py
src/prefect/client/schemas/responses.py
src/prefect/runner.py
src/prefect/server/api/deployments.py
src/prefect/server/schemas/filters.py
tests/server/api/test_deployments.py

Adds a new route for retrieving the scheduled flow runs for a set of deployments. This moves the filters used by runners server-side and will be used to track deployments that are actively being polled by a runner. Updates `Runner` class to use the new route. Status tracking for deployments will be added in a later PR.

Adds `/deployments/get_scheduled_flow_runs` endpoint

---

docs/guides/prefect-deploy.md

This PR updates the example `git_clone` step to make some clarifications:
- `stream_output` is default `true`. I think we shouldn't suggest setting it to `false` through our example.
- add comments so that users do not think that `id` is a field that is automatically set.
[Relevant community thread](https://prefect-community.slack.com/archives/CL09KU1K7/p1695682647749099?thread_ts=1695675921.948819&cid=CL09KU1K7)

Update `git_clone` deployment step example in documentation

---

src/prefect/deployments/steps/utility.py
tests/deployment/test_steps.py

Previously `pip_install_requirements` would silently fail. This would lead to `ModuleNotFound` errors in user flows.
This pr updates it to raise a `RuntimeError` similar to the other utility steps to indicate that something has happened
closes: https://github.com/PrefectHQ/prefect/issues/10822
Example:
```
18:24:17.652 | ERROR   | Flow run 'truthful-pronghorn' - Flow could not be retrieved from deployment.
File "/Users/jakekaplan/PycharmProjects/prefect/src/prefect/deployments/steps/core.py", line 124, in run_steps
step_output = await run_step(step, upstream_outputs)
File "/Users/jakekaplan/PycharmProjects/prefect/src/prefect/deployments/steps/core.py", line 95, in run_step
result = await from_async.call_soon_in_new_thread(
File …
```

raise `RuntimeError` if `pip_install_requirements` fails

---

docs/guides/index.md

We currently provide 2 links to the [prefect deploy guide](https://docs.prefect.io/latest/guides/prefect-deploy/) in our [deployments concept page](https://docs.prefect.io/latest/concepts/deployments/) but we don't include it in [our guides index](https://docs.prefect.io/latest/guides/) (the guides landing page). This PR adds the guide to the index.

Add `prefect deploy` guide to guide index for visibility 

---

.github/codeql-config.yml
.github/workflows/codeql-analysis.yml

We now use `ruff` for our quality checks, which are run via `pre-commit` for
developers locally and also during CI.  The CodeQL security checks are a
valuable signal, but they are often lost in the noise of regular linting.  Here
we downshift our use of CodeQL to the `security-extended` suite.

Use only the security suite from CodeQL

---

src/prefect/server/api/collections.py
tests/server/api/test_collections.py

CodeQL identified a partial server-side request forgery with a pretty limited
blast radius.  It could be exploited to cause a bunch of 404s at Github in a
very specific repo, but not likely any further harm than that.  Using a fixed
list of known views prevents us from even attempting the request for unknown
views.

Use a fixed list of known registry views rather than using the user's input

---

ui/package-lock.json
ui/package.json

This PR brings in a fix for a minor issue where the custom flow run filter option is erroneously tagged as (default).
Upstream fix - https://github.com/PrefectHQ/prefect-ui-library/pull/1786

Fix: Bump prefect-ui-library to 2.0.16

---

tests/server/api/test_flow_runs.py

We had an incident where we caused a large number of 404s because we changed the
`read_flow_run` route to use the specifier `{id:uuid}`. This specifier expects
UUIDs to have dashes, but the `PREFECT__FLOW_RUN_ID` variable is produced with
`flow_run.id.hex` and will be a 32-character hex string without dashes.
This test makes it explicit that we're supporting that unexpected format so we
don't accidentally break this again.
Related to #10851

Adding explicit tests for the format of the `PREFECT__FLOW_RUN_ID` env var

---

netlify.toml

Good to regularly push the pinned mkdocs-material insiders version to keep it updated.
This update affects docs preview builds only.
The preview doc
s build ok with the new pin:
https://deploy-preview-10859--prefect-docs-preview.netlify.app

Update pinned mkdocs-material insiders version in netlify.toml

---

src/prefect/agent.py
src/prefect/client/orchestration.py
tests/agent/test_agent_queue_selection.py
tests/agent/test_agent_run_submission.py
tests/cli/test_start_agent.py

Resolves https://github.com/PrefectHQ/prefect/issues/10743
From the issue:
> When you start an agent listening to only a queue (e.g. prefect agent start -q default) it polls for flow runs across all work pools of all types (as opposed to only the prefect-agent type)
This PR updates the agent's behavior so that it will poll for flow runs in `prefect-agent` type WorkPools if no WorkPool is explicitly passed to the agent. This will should help prevent the agent from accidentally picking up work meant for other agents.

By default, agents only query WorkQueues in `prefect-agent` typed WorkPools

---

src/prefect/utilities/collections.py
tests/utilities/test_collections.py

When executing a `task` that takes an instance of a `pydantic.BaseModel`, we construct a copy of the input instance and  lose track of which attributes were explicitly set. This is evident when running `.json(exclude_unset=True)` on the instance from inside the task. This change copies information on which fields were explicitly set from the input instance and onto the copy that we create and return. 
When a model is parsed by a task as input, the value passed is a reconstructed instance that loses some info from the original instance:
```python
from typing import Optional
from pydantic import BaseModel
class User(BaseModel):
"""Pydantic model for the User."""
email: Optional[str]
firstName: Optional[str]
lastName: Optional[str]
@task()
def t(u: User): …
```

Preserve set attribute information in tasks during execution

---

.github/workflows/python-tests.yaml

I'm choosing to run a smaller subset of actions here, just to keep things from
ballooning:
```
Python 3.8      sqlite          service tests
x               x
Python 3.11     postgres 14
```
Eventually, we'll flip this so that `pydantic>2` is the default for all test
suites, and we'll preserve a small subset like this for `pydantic<2`.

Creating CI actions for pydantic v2

---

docs/guides/global-concurrency-limits.md

This adds a paragraph calling out the primary difference between concurrency and rate limits and adds a section to the end with common use cases for the rate limit and concurrency managers along with code examples.

Add more info about rate limits and include use cases for global concurrency

---

scripts/collections-manager

There are occasions where we need to make bulk updates across all of our collections (currently ~30 repos now), such as dependency bumps, adapting to an upstream change, or to re-apply changes from the collections template.
In these cases, it can help to have a tool that operates over each repo in a uniform way.  This script is a starting point with shortcuts for those kinds of tasks, and should be pretty easy to extend to other use cases.
Note that this script is currently opinionated about a couple things that may not be true for everyone on the team:
* That you follow the `GOPATH` style of code repos on your local machine: `~/src/<site>/<owner>/<repo>`, like `~/src/github.com/PrefectHQ/prefect`
* That you use `pyenv` to manage multiple python versions and virtual environments for local …

Introducing a tool to help with bulk tasks over Prefect-maintained collections

---

setup.cfg
src/prefect/_internal/pydantic/v2_validated_func.py
src/prefect/flows.py
tests/test_engine.py
tests/test_flows.py

This PR brings us one step closer to allowing users to use pydantic V2 in their Flows. This PR fixes an edge case where a user with a flow/task that uses a pydantic V2 model as input fails validation. The reason validation fails is because our function + call arg validator (`pydantic.v1.decorator.ValidatedFunction`) returns a V1 model which fails to pass validation. Instead, when we detect that we're running with pydantic V2, we use a custom implementation of `ValidatedFunction` which returns a V2 model and passes validation. 
**NOTE** While running testes with pydantic V2 tests, `pytest` will fail a lot of tests due to `pydantic.warnings.PydanticDeprecatedSince20`.

Use custom ValidationFunction for pydantic v2

---

.github/workflows/python-tests.yaml
tests/cli/test_agent.py
tests/cli/test_cloud.py
tests/cli/test_server.py
tests/cli/test_worker.py
tests/docker/test_image_builds.py
tests/server/models/test_orm.py

- Mark several tests that have caused failures in the main branch recently as "flaky," so that pytest will rerun them.
- Update our Slack notification to use a more visible channel and notify on any failure.

Mark more flaky tests

---

scripts/collections-manager

This automates the process of releasing all of the collections repos en masse,
including major, minor, or patch version bumps.  The script skips repos with
no changes on `main` since the last release.
```
$ ./scripts/collections-manager bump-versions minor
Note: there is an intentional delay between each repo to avoid exceeding Github's rate limit for creating releases
prefect-snowflake v0.26.1 -> v0.27.0
https://github.com/PrefectHQ/prefect-snowflake/releases/tag/v0.27.0
prefect-databricks v0.1.6 -> v0.2.0
https://github.com/PrefectHQ/prefect-databricks/releases/tag/v0.2.0
prefect-great-expectations v0.1.0 -> v0.2.0
https://github.com/PrefectHQ/prefect-great-expectations/releases/tag/v0.2.0
prefect-hex v0.1.1 -> v0.2.0
https://github.com/PrefectHQ/prefect-hex/releases/tag/v0.2.0
...
```

Adding a bulk release script for collections

---

docs/guides/logs.md

docs: fix typo in logs guide

---

tests/workers/test_process_worker.py

per the notification in #engineering-review, this test flaked on merge to main, so we mark it as flaky

mark `test_process_kill_no_matching_pid` as flaky

---

src/prefect/agent.py
src/prefect/infrastructure/base.py
src/prefect/runner/runner.py
src/prefect/settings.py
src/prefect/workers/base.py
src/prefect/workers/process.py
tests/agent/test_agent_run_cancellation.py
tests/fixtures/database.py
tests/infrastructure/test_base.py
tests/workers/test_base_worker.py

Adds the ability to use a one-off runner to provide more consistent and reliable flow run cancellations. Enabling the `PREFECT_EXPERIMENTAL_ENABLE_ENHANCED_CANCELLATION` setting on a worker will change the default command the worker provided to infrastructure when starting a flow run from `python -m prefect.engine` to `prefect flow-run execute`. 
The new(ish) `prefect flow-run execute` command will spin up a runner to handle the execution of a flow run, and the runner will listen for cancellation requests for that flow run only. Cancellation will be more consistent with a runner because the runner only needs to kill a single process to ensure cancellation. Once that single process completes or is killed, the runner will stop, and the infrastructure will terminate. Also, the flow run can …

Add experimental enhanced cancellation

---

src/prefect/cli/deploy.py
tests/cli/test_deploy.py
tests/workers/test_process_worker.py

closes #10939
This PR adds a condition to check for a global pull step (instead of just an explicit `pull` step on the specific deployment config) before prompting the user to select remote storage for the flow
the tests are updated to remove responses to the cases where the prompt is no longer present
see example on [issue](https://github.com/PrefectHQ/prefect/issues/10939) 

`prefect deploy`: don't prompt remote storage if global pull step

---

requirements.txt

This updates our `requirements.txt` to remove the pin keeping users from updating to `pydantic>2`. This will let users install newer versions of `pydantic` without error from their dependency tracking tools.
```console
❯ pip install -e . 
....
❯ pip show pydantic
Name: pydantic
Version: 2.4.2
Summary: Data validation using Python type hints
Home-page:
Author:
Author-email: Samuel Colvin <s@muelcolvin.com>, Eric Jolibois <em.jolibois@gmail.com>, Hasan Ramezani <hasan.r67@gmail.com>, Adrian Garcia Badaracco <1755071+adriangb@users.noreply.github.com>, Terrence Dorsey <terry@pydantic.dev>, David Montague <david@pydantic.dev>
License:
Location: /Users/uriel/.pyenv/versions/3.8.17/envs/prefect-38/lib/python3.8/site-packages
Requires: annotated-types, pydantic-core, typing-extensions …
```

Removes pin locking `pydantic` <2

---

requirements.txt

Closes #10954 
It fixes an issue with rez package manager when installing prefect dependencies as 
a package need to declare its requirements with the same name as the pip package https://pypi.org/project/ruamel.yaml/

fix requirements.txt : renamed ruamel-yaml to ruamel.yaml

---

src/prefect/flows.py
tests/test_flows.py

load_flow_from_entrypoint("C:\\Users\\maitl\\AppData\\Local\\Temp\\tmp78go90gn\\MAD.Data.SurveyMonkey-main\\mad_data_surveymonkey.dw.surveys_detail.ingest.py:ingest_surveys_detail")
So I can use Flow.from_source during development on my Windows machine.

fix: support Windows paths in load_flow_from_entrypoint

---

src/prefect/flows.py

We have seen a few edge cases popping up where we're trying to use the
pydantic v2 validator to validate v1 models as flow function arguments.  This
leads to the opaque error:
```
TypeError: BaseModel.validate() takes 2 positional arguments but 3 were given
```
Examples:
* https://github.com/PrefectHQ/prefect-airbyte/issues/61
* https://github.com/PrefectHQ/prefect-kubernetes/actions/runs/6628004996/job/18004160832?pr=92
The issue here is that we were trying to use our custom v2 port of the v1
`ValidatedFunction`, without inspecting the types of models involved.  Here, we
are looking at the types of the passed arguments, validating that they aren't
mixing v1 and v2 models, and then choosing the right validation implementation
from there.

Refining how we validate flow parameters under Pydantic 1 versus 2

---

src/prefect/engine.py
src/prefect/runner/runner.py
src/prefect/settings.py
tests/runner/test_runner.py
tests/test_flows.py

`on_cancellation` hooks do not run when submitted tasks are still running because we wait for submitted tasks to complete, preventing the engine's crash detection from activating before the flow's process or infrastructure is killed. A runner can be used to observe a flow run, which makes it well-positioned to handle running `on_cancellation` and `on_crashed` hooks.
This PR introduces settings that allow a runner to turn off the engine's handling of `on_cancellation` and `on_crashed` hooks, allowing the runner to execute those hooks when present. The engine's behavior is maintained when a runner is not present, and the engine remains responsible for the `on_completion` and `on_failure` hooks.
Note: users will need to enable enhanced cancellation to use this fix. The fix will be available …

Moves responsibility for running 'on_cancellation` and `on_crashed` flow hooks to runner when present

---

src/prefect/server/services/cancellation_cleanup.py
tests/server/services/test_cancellation_cleanup.py

Currently, the cancellation cleanup service marks all subflow runs of cancelled flow runs as CANCELLED. This prevents runners, workers, and agents from tearing down infrastructure if the subflow run was created from a deployment via run_deployment because they poll for CANCELLING states to know when to tear down the supporting infrastructure. This can cause the subflow run to keep running until the next attempt at a state transition.
This PR updates the cancellation cleanup service to mark subflow runs created from a deployment as CANCELLING to enable cascading cancellation to tear down provisioned infrastructure.
Closes https://github.com/PrefectHQ/prefect/issues/10947 …

Update cancellation cleanup service to allow for infrastructure teardown

---

src/prefect/runner/storage.py
tests/runner/test_storage.py

Fixes bug introduced when unifying `git_clone` and `GitRepository` implementations where `password` would not be accepted in the `credentials` dictionary provided to `git_clone`. Added a regression with description for future reference.
Closes https://github.com/PrefectHQ/prefect/issues/11051

Allow `password` to be provided in `credentials` for `GitRespository`

---

requirements-dev.txt

This version of `pytest-asyncio` started emitting a new warning (which fails
our tests because we treat warnings as errors).  It looks like this may have
been premature on the maintainer's part:
This release deprecated event loop overrides, but didn't provide adequate
replacement functionality for all relevant use cases. As such, the release
was yanked from PyPI.
https://github.com/pytest-dev/pytest-asyncio/releases/tag/v0.22.0
I'm going to avoid that particular release and we can revisit once they have
given clearer guidance on how to update your test suite.

Avoid yanked `pytest-asyncio==0.22.0`

---

setup.cfg
src/prefect/_internal/pydantic/annotations/pendulum.py
src/prefect/_internal/pydantic/schemas.py
src/prefect/_internal/pydantic/v2_schema.py
src/prefect/cli/deployment.py
src/prefect/utilities/callables.py
tests/utilities/test_callables.py

Closes #10965
This is an addition to our pydantic v2 parameter schema generation logic. When we parse a flow function we attempt to generate a schema for it. Our schema generation logic is entirely pydantic v1 based. Now that we've lifted our restriction on pydantic v2, it's possible for flow function signatures to make use of pydantic v2-based models. The error was coming from using v1-schema generation on a v2 model. 
~Note that with this fix the schema that is generated will drop the default with a warning:~ This is no longer an issue with the new implementation!

fix: handle v2 models in func signatures

---

src/prefect/testing/standard_test_suites/task_runners.py

This PR is a fix for our downstream collections -- in those collections we subclass the `TaskRunnerStandardTestSuite` and inherit a default suite of tests. One of those inherited tests is `test_sync_task_timeout` which fails consistently on Windows environments because we don't support cancellation due to timeouts on Windows. The marker added here just skips the test on Windows CI runs.
An example of failing tests can be seen [here](https://github.com/PrefectHQ/prefect-dask/actions/runs/6710486682/job/18266164487).

Skips unsupported Windows tests

---

src/prefect/engine.py
src/prefect/server/api/flow_runs.py
src/prefect/settings.py
src/prefect/utilities/annotations.py
tests/test_engine.py

When you apply a `@task` decorator to a function prefect will introspect the parameters you pass so it can track dependencies (like task A's result got passed to task B). This is what we want to show for most cases, but it's a big performance hit when the data you're passing is a really large collection like a `dataframe` or large `dict`, and we try to visit everything inside of it.
`quote()` is an escape utility which tells prefect to ignore introspecting this thing. However this utility is not well known or well documented and this case frequently comes up as there are many data heavy users passing dataframes around.
This pr introduces a helpful warning if task run parameter introspection takes longer than `PREFECT_TASK_INTROSPECTION_WARN_THRESHOLD`, instructing the user to try …

Warn if task parameter introspection takes a long time

---

src/prefect/server/database/query_components.py
tests/server/api/test_flow_run_graph_v2.py

During testing, we uncovered 500 errors for some calls for `graph-v2`, and it
was due to `NULL` `start_time` values coming back from the query. This is
because we should be using expected_start_time when a task/flow hasn't
actually started yet.

Use `expected_start_time` in Graph v2 for unstarted runs

---

src/prefect/deployments/runner.py
src/prefect/flows.py
tests/runner/test_runner.py
tests/test_flows.py

Adds a `build` kwargs to `deploy` and `flow.deploy` that allows users to opt-out of building an image via `flow.deploy` and `deploy`. The provided image will be associated with the specified deployments and will be pulled at flow execution time. This gives the user the power and responsibility to build their Docker images via a separate process.
```python
from time import sleep
def tired_flow():
print("🥱 Im so tired...")
sleep(1)
for i in range(30):
print("😴")
sleep(6)
tired_flow.deploy(
name="test-s3-remote",
work_pool_name="olympic",
image="desertaxle/tired-flow:dev",
build=False,
)
``` …

Add option to skip building a Docker image with `flow.deploy`

---

docs/guides/global-concurrency-limits.md

addressing #11081
(if im understanding the existing doc correctly) This PR adds a `!!!tip` to mitigate conflation of general "tasks" in common concurrency lingo with Prefect proper noun "Task".

docs: add clarifying comment on use of `task`

---

src/prefect/server/database/query_components.py
src/prefect/server/schemas/graph.py
tests/server/api/test_flow_run_graph_v2.py

* Excludes `PENDING` tasks, as it is ambiguous whether they will be subflow runs
* Removes `state_name` from the API, as it isn't needed by the UI

Flow run graph v2 polish

---

src/prefect/flows.py

`work_pool` in docstring example should be `work_pool_name`

Fix docstring for `flow.deploy` method example

---

client/client_flow.py

When we run CI on external PRs (such as dependabot automatic updates), the workflow does not have access to the repository secrets and fails while running an integration test workflow. It's still helpful to run as much of the build as possible without failing on integration flows that require secrets to work against a remote API. This PR changes the integration flow to detect when it should not run (in GHA and no secret availabl). In these cases, the integration test step will just verify `prefect-client`'s imports work correctly.

Allow minimal prefect-client CI validation on external PRs

---

src/prefect/deployments/runner.py
tests/runner/test_runner.py

The `DeploymentImage` class currently appends tags even if one is provided implicitly through the name; this PR adds the convenience of providing a `name:tag` formatted name and we "do the right thing".
```python
image = DeploymentImage(name="my-repo/my-image:my-tag") # works
```

Improved tag handling on DeploymentImage

---

src/prefect/deployments/runner.py
src/prefect/flows.py
tests/runner/test_runner.py

Closes https://github.com/PrefectHQ/prefect/issues/11096
```python
from prefect import deploy
def local_flow():
print("I'm a locally defined flow!")
local_flow.deploy(
name="test-remote-flow-deploy",
work_pool_name="my-cloud-run-push-work-pool",
image="serinabeana/dev:latest",
job_variables={"image_pull_policy": "Never"},
)
deploy(
flow.from_source(
source="https://github.com/desertaxle/demo.git",
entrypoint="flow.py:my_flow",
).to_deployment(
name="test-deploy-remote-flow",
),
work_pool_name="my-cloud-run-push-work-pool",
)
deploy(
local_flow.to_deployment("my-deployment"),
flow.from_source(
source="https://github.com/desertaxle/demo.git",
entrypoint="flow.py:my_flow",
).to_deployment( …
```

Allow `image` passed into `deploy` to be optional if loading flow from storage

---

src/prefect/cli/deploy.py
src/prefect/cli/worker.py
src/prefect/deployments/runner.py
src/prefect/flows.py

Similar to push work pools, for managed pools we want to avoid printing any help text suggesting users can/should start their own worker for the pool.

Dont print worker start command for managed pool

---

tests/cli/test_server.py
tests/test_flows.py
tests/workers/test_process_worker.py

Removes flaky test cases. See #11124 and #11123.

Remove flaky tests

---

src/prefect/server/database/query_components.py
tests/server/api/test_flow_run_graph_v2.py

Cached tasks have an `expected_start_time`, but because they aren't actually run, they
have `NULL` `start_time` and `end_time`.  Cached tasks appear as `COMPLETED`, so we can
detect those and use their `expected_start_time` in place of both times, reflecting that
they are "zero duration" tasks.  The UI will correctly hold those to a minimum width and
drop them in the right spot on the layout.

Handle Cached tasks on graph-v2

---

src/prefect/server/database/query_components.py
tests/server/api/test_flow_run_graph_v2.py

There can be a brief period of time when a flow/task run has been created but does not
yet have a `start_time` or even an `expected_start_time`.  This is causing a pydantic
`ValidationError` when trying to read the graph.  We can safely ignore these
cases, as they can't be plotted on the graph visualization anyway, and the runs they
represent will "pop in" as soon as they have a valid time.

Exclude any flow/task run with a `NULL` `start_time` from Graph v2

---

src/prefect/runner/runner.py
src/prefect/utilities/processutils.py

```python
import time
def slow_flow(sleep: int = 60):
time.sleep(sleep)
slow_flow.serve(name="my_flow")
```
```bash
13:32:35.707 | DEBUG    | prefect.runner - Querying for flow runs scheduled before 2023-11-08T21:32:45.707395+00:00
13:32:35.730 | INFO    | prefect.flow_runs.runner - Runner 'my_flow' submitting flow run '26ee9497-7421-43de-9df1-712c42704086'
13:32:35.864 | INFO    | prefect.flow_runs.runner - Opening process...
13:32:35.872 | INFO    | prefect.flow_runs.runner - Completed submission of flow run '26ee9497-7421-43de-9df1-712c42704086'
<frozen runpy>:128: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result …
```

Add `SIGTERM` handling to runner to gracefully handle timeouts

---

src/prefect/server/database/query_components.py
tests/server/api/test_flow_run_graph_v2.py

We're seeing a very small error rate of trying to set `Graph.start_time` to
`None` when reading a flow run graph, and it is due to unstarted flow runs
briefly having no `start_time` (just like we fixed with task runs).  This
affects the whole `Graph`, not the `Node`s, but the idea is the same: use the
`expected_start_time` if there's no `start_time`.

Use an unstarted flow run's expected start time for the Graph start time

---

docs/guides/index.md
mkdocs.yml

i was confused to find `Webhooks` in `Execution` - while webhooks to run a deployment is a common use case, it seems webhooks are generally a part of `Development` against prefect cloud, rather than a facet of execution explicitly

docs: move `Webhooks` to `Development`

---

.github/workflows/python-tests.yaml

Originates from #11149 
As we've had issues opened lately related to Pydantic V2, I would advocate for testing against all our Python versions (3.8, 3.9, 3.10, 3.11) instead of just (3.8 and 3.11).

Run tests with Pydantic V2 installed for all Python versions we support

---

src/prefect/_internal/concurrency/calls.py

We use an internal object called a `Call` to capture the function,
`args/kwargs`, and some contextual information about function calls that are
potentially crossing concurrency boundaries.  These objects are used to track
calls and make their results available in a sync/async agnostic way.
When a user task is run, it is ultimately done so with a `Call` created by
`begin_task_run` that captures the task arguments.  That `Call` seems to still
be referenced by the event loop between flow runs, and if large objects were
passed as arguments, the garbage collector can't free them.  This change breaks
that reference cycle so that after the function of a `Call` has been invoked in
the right concurrency context, the `args` and `kwargs` are set to `None`, as
they can't be used meaningfully anymore …

Forgetting the `args/kwargs` to a Prefect `Call` after they are used

---

src/prefect/deployments/steps/core.py
tests/deployment/test_steps.py

- Adds formatting to handle libraries with `-` in the name, but the corresponding module uses a `_` (e.g. `prefect-aws`)
- Raises warning, but doesn't fail when requirements installation fails. Steps can succeed if the necessary requirements are available, but installation fails. The warning can help with debugging if a step run fails.
Closes https://github.com/PrefectHQ/prefect/issues/11091

Fix bug where check for required packages fails incorrectly

---

src/prefect/settings.py
src/prefect/workers/server.py

adds settings to allow configuration of worker webserver:
```python
PREFECT_WORKER_WEBSERVER_HOST = Setting(str, default="0.0.0.0")
"""
The host address the worker's webserver should bind to.
"""
PREFECT_WORKER_WEBSERVER_PORT = Setting(int, default=8080)
"""
The port the worker's webserver should bind to.
"""
```
closes #11158

add settings for worker webserver host and port

---

src/prefect/events/related.py

This PR makes the way we're finding the `flow_run_id` more resilient by doing deeper inspection on objects. This removes an assumption that the `{flow_run,task_run}_contexts` are fully populated.

Safely retrieve `flow_run_id` in `EventsWorker`

---

src/prefect/cli/deploy.py
src/prefect/cli/work_pool.py
src/prefect/deployments/runner.py
src/prefect/flows.py
src/prefect/settings.py
tests/cli/test_deploy.py
tests/cli/test_work_pool.py
tests/runner/test_runner.py

Adds a new setting `PREFECT_DEFAULT_WORK_POOL_NAME` which controls the work pool that a flow will be deployed to if a work pool name is not explicitly given. This change is only client-side and will not persist between different machines.
When creating a work pool, users can add a `--set-as-default` flag to automatically update their current profile to point to the new work pool as the default.
Create a work pool and set it as the default:
```bash
prefect work-pool create --type process --set-as-default inflatable
```
Deploy a flow to the default work pool:
```python
flow.from_source(
source="https://github.com/desertaxle/demo.git",
entrypoint="flow.py:my_flow",
).deploy(
name="to-default-work-pool",
)
```
- If no issue exists and your …

Add client-side setting for default work pool

---

src/prefect/logging/handlers.py

This removes an assumption that emitted log records have a uuid-like `flow_run_id` by dropping the value before it creates the log structure. This should give us more flexibility in deciding how to handle missing ids while still shipping logs.  

fix: Allow logs to handle un-uuid-like `flow_run_id`s

---

src/prefect/client/schemas/filters.py
src/prefect/server/database/migrations/versions/postgresql/2023_11_20_084708_9c493c02ca6d_add_trgm_index_to_block_document_name.py
src/prefect/server/database/migrations/versions/sqlite/2023_11_20_084708_9c493c02ca6d_add_trgm_index_to_block_document_name.py
src/prefect/server/schemas/filters.py
tests/server/api/test_block_documents.py

This PR adds fuzzy name matching for block documents as part of pagination work @pleek91 is doing.

Add LIKE filtering for block document names

---

src/prefect/server/database/migrations/versions/sqlite/2023_10_30_103720_22ef3915ccd8_index_and_backfill_block_type_name.py

This PR fixes a SQLite migration for backfilling `block_document.block_type_name`. The previous migration required SQLite functionality not supported by our minimum version.
Closes https://github.com/PrefectHQ/prefect/issues/11104

Fix sqlite block type name backfill

---

ui/package-lock.json
ui/package.json
ui/src/pages/Blocks.vue

Adds pagination to the block documents page in the ui and replaces the browser side filtering and sorting with api filtering and sorting.
Needs: https://github.com/PrefectHQ/prefect-ui-library/pull/1876

Add pagination to blocks in the ui

---

docs/guides/testing.md

I've begun unit testing my flows, and used the [current guide](https://docs.prefect.io/latest/guides/testing/#unit-testing-tasks) to help me on my way. I use logging in my task and was unable to properly test it as I was running into:
```
RuntimeError: There is no active flow or task run context.
```
I then ran across [this solution](https://discourse.prefect.io/t/unit-testing-best-practices-for-prefect-flows-subflows-and-tasks/1070/10) - so I'm adding it to the docs to help the next person.

docs: add hint for disabling logger in unit testing

---

requirements-dev.txt
tests/fixtures/client.py

Looks like `pytest-xdist` 3.5.0 changed how scopes are scheduled: https://github.com/pytest-dev/pytest-xdist/pull/778. This seems to cause some tests to flake.
Maintenance issue created here: https://github.com/PrefectHQ/prefect/issues/11231

Flaky test investigation

---

client/build_client.sh
client/client_flow.py

This PR changes the `prefect-client` build process to include the `concurrency` module. My understanding is that this is a way to control how much work is happening at once via a central state (prefect DB), which I think makes it a good candidate for bringing over into the more client-oriented `prefect-client`. 
closes #11202

ft: Include concurrency controls in `prefect-client`

---

src/prefect/client/cloud.py
tests/client/test_cloud_client.py

Updates `read_worker_metadata` method on `CloudClient` to use new workspace scoped route to read available work pool types and their metadata.

Use new route to read work pool types when connected to Prefect Cloud

---

.github/workflows/python-package.yaml

to avoid future erroneous release tags (like `v2.14.6` instead of `2.14.6`), we should fail the PyPI build/publish CI early

[ci] check tag format in release ci

---

src/prefect/deployments/steps/core.py
tests/deployment/test_steps.py

closes #11243
spreads `packages` into `check_call` to avoid this error
```python
subprocess.CalledProcessError: Command '['/bin/python', '-m', 'pip', 'install', 'prefect-aws==0.4.2,mysecondpackage==0.0.1']' returned non-zero exit status 1.
```
cc @desertaxle - just making sure I'm not misunderstanding the intent of #11111 

[deploy ux] fix install when `requires` more than one package

---

.github/workflows/python-package.yaml

This PR adds an escape hatch to allow the `Publish Python package` workflow to run in isolation from a specific commit SHA (or generally, any valid `ref` as accepted by `actions/checkout@v4`)
In particular, this is motivated by a [failure in the `Publish Python package` workflow upon creation of the `2.14.7`](https://github.com/PrefectHQ/prefect/actions/runs/7023267856) where all other release-triggered CI completed successfully (docker images, docs etc) but the publish to PyPI did not.
Note: we've verified that the docker images do in fact contain the correct version of the code, which is correctly versioned as `2.14.7`, its just PyPI that doesn't have 2.14.7 …

[ci] allow adhoc release from certain commit

---

.github/workflows/python-package.yaml

the tag check as is checks the `ref`, which must be `main` if supplying a `commit` to build from in the new `workflow_dispatch`
therefore, to get 2.14.7 properly published on PyPI we will **temporarily** remove the tag check and add it back once this is released
cc @zhen0

temporarily remove tag check to allow release from 2.14.7 tag

---

docs/guides/managed-execution.md

Guide for managed execution. Intentionally unlinked during alpha.
navigate to guides/managed-execution/

Managed execution guide

---

requirements-dev.txt

`pytest-asyncio` introduced a change in 0.23.0 to prevent overriding the event loop in tests. We override the event loop to use async fixtures with `session` and `module` scopes. The solution for event loop scoping doesn't account for fixtures, so we'll need to cap `pytest-asyncio` for now. See https://github.com/pytest-dev/pytest-asyncio/issues/706 for more details.

Cap `pytest-asyncio`

---

src/prefect/cli/_types.py
src/prefect/cli/work_pool.py
src/prefect/infrastructure/provisioners/cloud_run.py
src/prefect/infrastructure/provisioners/container_instance.py
tests/cli/test_typer_utils.py
tests/cli/test_work_pool.py

This PR introduces the functionality to provision infrastructure for an existing work pool through a `prefect work-pool provision-infra` subcommand in the Prefect CLI. 
```bash
❯ prefect work-pool provision-infra my-work-pool
13:22:32.560 | DEBUG   | prefect.profiles - Using profile 'cloud'
13:22:32.640 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/abc/workspaces/xyz/
13:22:32.851 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/abc/workspaces/xyz/
? Please select which Azure subscription to use: [Use arrows to move; enter to select]
┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃    ┃ Name                 ┃ Subscription ID                      ┃ …
```

Add ability to provision infrastructure for an existing work pool

---

src/prefect/server/database/migrations/MIGRATION-NOTES.md
src/prefect/server/database/migrations/versions/postgresql/2023_12_07_121416_7c453555d3a5_make_flowruninput_flow_run_id_a_foreign_.py
src/prefect/server/database/migrations/versions/sqlite/2023_12_07_121624_35659cc49969_make_flowruninput_flow_run_id_a_foreign_.py
src/prefect/server/database/orm_models.py

Makes `FlowRunInput.flow_run_id` a foreign key to `flow_run.id` and deletes on cascade.
Closes #11351

Make `FlowRunInput.flow_run_id` a foreign key to `flow_run.id`

---

src/prefect/_internal/pydantic/v2_schema.py
src/prefect/client/orchestration.py
src/prefect/client/schemas/objects.py
src/prefect/engine.py
src/prefect/input/__init__.py
src/prefect/input/actions.py
src/prefect/input/run_input.py
src/prefect/server/schemas/states.py
src/prefect/settings.py
tests/input/test_actions.py
tests/input/test_run_input.py
tests/test_engine.py

This integrates flow run input into pause/suspend allowing a flow run to pause or suspend and receive structured and validated input, it does this by:
- Creating `RunInput` a sub-classable pydantic model that a user can subclass and add their own fields and validation.
- Adding `wait_for_input` to `pause_flow_run` and `suspend_flow_run`. When either method is provided a subclass of `RunInput` it will pause/suspend,'save` and the schema of the class to the flow run input API. When resuming it will then try to grab a response from the flow run input API and instantiate the class with that data.
Closes #11339 
```python
import random
from prefect import flow, get_run_logger, pause_flow_run
from prefect.input import RunInput
class UserGuess(RunInput):
guess: int
@flow
async def …
```

Integrate flow run input and schema/response mechanics into pause/suspend

---

src/prefect/deployments/runner.py
src/prefect/flows.py
src/prefect/runner/runner.py
tests/runner/test_runner.py
tests/test_flows.py

Adds `is_schedule_active` arg to allow users to create a deployment with the schedule paused or pause/resume the schedule of an existing deployment. The `RunnerDeployment` class already supported `is_schedule_active`, but it was not exposed in the user-facing API.
Create a deployment with a paused schedule:
```python
def local_flow():
print("I'm a locally defined flow!")
local_flow.deploy(
name="test-flow-deploy",
work_pool_name="olympic",
image="desertaxle/test-local-flow-deploy:dev",
interval=3600,
is_schedule_active=False,
)
```

Adds support for `is_schedule_active` to `flow.deploy` and `flow.serve`

---

src/prefect/infrastructure/provisioners/cloud_run.py
tests/infrastructure/provisioners/test_cloud_run.py

co-authored with @desertaxle 
This PR enhances the `CloudRunPushProvisioner` class by adding functionality for users to provide custom names for resources during the infrastructure provisioning process. It introduces interactive user prompts for naming service accounts and GCP credential blocks.
```bash
❯ prefect work-pool create my-work-pool --type cloud-run:push --provision-infra
? Please select which GCP project to use [Use arrows to move; enter to select]
┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┓
┃   ┃ Name             ┃ Project ID         ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━┩
│ > │ My First Project │ project-boa-404417 │
└───┴──────────────────┴────────────────────┘
╭───────────────────────────────────────────────────────────────────────────────────────────────────────── …
```

Add ability to provision resources with user provided names in Cloud Run push pool provisioner

---

ui/package-lock.json
ui/package.json
ui/src/pages/Dashboard.vue

Implements a new date range select on the dashboard. Now users can select both past and future relative date ranges like "Past 1 week" or "Next 1 hour" but users can also select specific date and time ranges. Previously the dashboard was limited to viewing the last 8 hours, 24 hours, or 1 week. 
| Before | After |
|--------|--------|
| <img width="1054" alt="image" src="https://github.com/PrefectHQ/prefect/assets/6200442/db88c7c3-eaea-4d85-a6ed-83f9218bda1f"> | <img width="1048" alt="image" src="https://github.com/PrefectHQ/prefect/assets/6200442/94c99646-de24-434f-85ca-b672cdfb4299"> |

Allow users to select relative and fixed date ranges to filter the dashboard

---

src/prefect/server/orchestration/core_policy.py
tests/fixtures/database.py
tests/server/orchestration/test_core_policy.py

Recent work on fixing a pause/resume bug with tasks introduced a new bug in which we reused the ID of an existing state while constructing a new state record. Oops.

Construct a pause state without reusing the state ID

---

src/prefect/runner/server.py
src/prefect/settings.py
tests/runner/test_webserver.py

to avoid any breaking edge cases in the upcoming release associated with building the webserver (e.g. perhaps very complicated flow run parameters that we would fail to inject into the runner webserver schema), this PR adds a default `False` setting to enable the experimental webserver endpoints
like all settings, this setting can be toggled by setting the env var or with the CLI:
```
prefect config set PREFECT_EXPERIMENTAL_ENABLE_EXTRA_RUNNER_ENDPOINTS=True
```
the name is up for debate 🙂 my idea was to use this flag to gate all experimental routers we may throw on the runner webserver in coming weeks

add setting for experimental runner endpoints

---

src/prefect/engine.py
tests/test_engine.py

Updates the default `pause_flow_run` and `suspend_flow_run` from 5m (300s) to 1 hour (3600s). 
Closes #11413 

Update default pause/suspend timeout to be 1 hour

---

src/prefect/input/run_input.py
tests/input/test_run_input.py

This removes the `title` and `description` fields from the `RunInput` model.
Related to #11339

Remove title/description from `RunInput` model

---

docs/api-ref/prefect/input/actions.md
docs/api-ref/prefect/input/run_input.md
docs/concepts/flows.md
docs/guides/creating-human-in-the-loop-workflows.md
docs/guides/index.md
docs/guides/receiving-input-when-paused.md
mkdocs.yml

This adds `wait_for_input` documentation to the existing pause/resume documentation and creates a guide that goes more in-depth.
Closes #11401 

Documentation for `wait_for_input`

---

ui/.vscode/settings.json
ui/package-lock.json
ui/package.json
ui/src/pages/FlowRuns.vue

Building on the updates to the dashboard we've updated the flow runs page to support relative time spans like "Past 7 days". This means its much easier to quickly look at what's happing right now (e.g. "Past 1 hour") or see whats coming up next (e.g. "Next 15 minutes").
You can also save date ranges when saving flow run filters. So creating a view to see the past 6 hours of runs for a specific work pool is now possible.

Allow users to select relative time spans and save date range to saved filters on the flow runs page

---

src/prefect/cli/deploy.py
tests/cli/test_deploy.py

Closes https://github.com/PrefectHQ/prefect/issues/11189, where the `work_pool_name` in `prefect.yaml` was being used during `prefect deploy` prior to when we read the value from the environment variable.
This PR modifies the `deploy_config` resolution process to apply environment variables parsing to all configuration elements earlier, including `work_pool_name`.

Resolve `work_pool` env vars during `prefect deploy`

---

docs/concepts/tasks.md

Reverts PrefectHQ/prefect#11490
This won't make it into today's release after all because we need to ensure compatibility with Prefect Cloud.

Revert "Add documentation on conditional retries"

---

docs/tutorial/tasks.md

Documentation fix: On the Tasks page of the tutorial, the defined method is named `get_repo_info()`, but the call from the main function was incorrectly spelled `repo_info()`.
N/A

Fix method name typo in Tasks tutorial

---

src/prefect/server/services/loop_service.py
src/prefect/utilities/processutils.py

This helps address #10895
The flaky tests on main leading to: `ValueError: signal only works in main thread of the main interpreter` are getting out of hand. This PR attempts to fix that by only attempting to registering signal on main thread.

Don't attempt to register signals in non-main thread

---

src/prefect/cli/work_queue.py
src/prefect/client/orchestration.py

```bash
❯ prefect work-queue inspect d9181a64-c098-4e13-ad51-6d63141cd8fc
WorkQueue(
id='d91...',
created=DateTime(2023, 2, 2, 17, 39, 58, 692020, tzinfo=Timezone('+00:00')),
updated=DateTime(2023, 12, 14, 14, 20, 58, 185706, tzinfo=Timezone('+00:00')),
name='default',
work_pool_name='default-agent-pool',
work_pool_id='f8110b4f-f0db-4f10-b615-79081d6afc97',
last_polled=DateTime(2023, 12, 14, 14, 19, 35, 193143, tzinfo=Timezone('+00:00'))
)
WorkQueueStatusDetail(
healthy=False,
last_polled=DateTime(2023, 12, 14, 14, 19, 35, 193143, tzinfo=Timezone('+00:00')),
health_check_policy=WorkQueueHealthPolicy()
)
```

Display work queue status details via CLI

---

tests/public/flows/test_flow_crashes.py
tests/test_flows.py

Should close #10895 
We missed a spot where we're using the `mock_sigterm_handler` fixture in our tests and we sometimes face intermittent failures resulting in the `ValueError: signal only works in main thread of the main interpreter` we've been seeing lately. 

Check if we're on the main thread when using mock sigterm handler in tests

---

src/prefect/runner/server.py
src/prefect/runner/utils.py
tests/runner/test_webserver.py

This PR adds filtering to limit the flows the runner is aware of to only those flows available in the deployment's import namespace. This PR also includes logging on flow schema changes -- this is useful to detect when a runner has pulled new code that is different than the code available when the webserver was built.

Filter available subflows in the generic runner subflow endpoint

---

docs/concepts/deployments.md

There's no reference to `prefect.yaml` so ideally it wouldn't come up when searching for `prefect.yaml` in the docs.

Remove `prefect.yaml` tag from page where unmentioned

---

src/prefect/runner/runner.py
src/prefect/settings.py
tests/runner/test_runner.py

This PR includes a setting for starting the webserver process in the runner. This will enable the server to be started by setting mechanics instead of needing to be activated by a kwarg.

Add setting for starting the webserver

---

src/prefect/runner/submit.py
src/prefect/settings.py
src/prefect/workers/server.py
tests/runner/test_webserver.py

```console
(bleeding-prefect) pad-2 :: github.com/PrefectHQ/prefect ‹ft/runner-runs-flows*›
» prefect config set PREFECT_WORKER_WEBSERVER_HOST=localhost
Set 'PREFECT_WORKER_WEBSERVER_HOST' to 'localhost'.
Setting 'PREFECT_WORKER_WEBSERVER_HOST' has been deprecated. It will not be available after Jul 2024. Use `PREFECT_RUNNER_SERVER_HOST` instead.
Updated profile 'pong'.
» prefect config set PREFECT_WORKER_WEBSERVER_PORT=8080
Set 'PREFECT_WORKER_WEBSERVER_PORT' to '8080'.
Setting 'PREFECT_WORKER_WEBSERVER_PORT' has been deprecated. It will not be available after Jul 2024. Use `PREFECT_RUNNER_SERVER_PORT` instead.
Updated profile 'pong'.
```

feature flag and deprecate dupe webserver settings

---

.gitignore

This PR adds `src/prefect/server/api/collections_data/views/aggregate-worker-metadata.json` to the `.gitignore file`. This change is intended to prevent the dynamically generated worker metadata from affecting the repository's clean state, ensuring that our versioning remains consistent and unmarked by 'dirty' flags.
During our build and deployment process in `python-package.yaml`, `aggregate-worker-metadata.json` is dynamically generated and downloaded (we intend to change this soon). This file's changes caused the build to be marked as 'dirty'.
More details in Slack: https://prefecthq.slack.com/archives/C03PSCZLNKG/p1704406599187539?thread_ts=1704381666.821209&cid=C03PSCZLNKG …

Add `aggregate-worker-metadata.json` to `.gitignore`

---

.github/workflows/python-package.yaml
src/prefect/server/api/collections_data/views/aggregate-worker-metadata.json

This PR is the first step to change the way we incorporate the latest worker metadata into each release. Here we remove it from being downloaded prior to building the package. We fix typos in the json. Prior to the next `prefect` release (2.14.14), @zzstoatzz plans to write a script to generate a PR to the `prefect` repo whenever the metadata changes.

Remove worker metadata download from build/publish workflow, fix typos in worker metadata

---

src/prefect/_internal/pydantic/v2_schema.py
src/prefect/client/orchestration.py
src/prefect/client/schemas/objects.py
src/prefect/context.py
src/prefect/input/__init__.py
src/prefect/input/actions.py
src/prefect/input/run_input.py
src/prefect/server/api/flow_runs.py
src/prefect/server/database/migrations/MIGRATION-NOTES.md
src/prefect/server/database/migrations/versions/postgresql/2024_01_05_101034_6b63c51c31b4_add_sender_to_flowruninput.py
src/prefect/server/database/migrations/versions/sqlite/2024_01_05_101041_c63a0a6dc787_add_sender_to_flowruninput.py
src/prefect/server/database/orm_models.py
src/prefect/server/models/flow_run_input.py
src/prefect/server/schemas/core.py
tests/input/test_actions.py
tests/input/test_run_input.py
tests/server/api/test_flow_runs.py
tests/server/models/test_flow_run_input.py

This enables flow runs to receive and send input from/to external sources.
Closes https://github.com/PrefectHQ/nebula/issues/6425
This example implements a simple `mapreduce` set of flows. A main `mapreduce` flow delegates the mapping/reducing logic to other long-running flows. These flows wait to receive input, process it, and then respond to that input with their computed values.
First there is a `common` set of `RunInput` classes, referenced from `common.py`:
```python
from prefect.input import RunInput
class Values(RunInput):
values: list[int]
class Summed(RunInput):
value: int
```
Then a flow that receives `Values` inputs and transforms the provided list of ints by multiplying each by 2. It then responds to the incoming `Values` input with the newly mapped `Values`:
```python
from …
```

Enable flow runs to receive typed input from external sources

---

src/prefect/runner/__init__.py
src/prefect/runner/runner.py
src/prefect/runner/server.py
src/prefect/runner/submit.py
src/prefect/settings.py
tests/runner/test_runner.py
tests/runner/test_submit.py

adds `PREFECT_RUNNER_SERVER_ENABLE_BLOCKING_FAILOVER` and corresponding handling in `submit_to_runner`

failover setting and init test coverage

---

src/prefect/runner/submit.py
tests/runner/test_submit.py

Added a bunch of tests to verify behavior for `_submit_flow_to_runner` running flows in a sync fashion (not in the webserver). Along the way I found a small bug in how we were detecting whether to return a list of UUIDs or a single UUID - so I updated the logic to make it clearer how we make that decision.

ft: add more tests for submissions

---

.github/pull_request_template.md

Python SDK modules are not always updated in the docs because stub files and navigation for mkdocs were often not added. Sometimes docstrings were not added.  Users pointed out that some docs were missing.
This PR adds checkboxes to make folks aware of that expectation with importable Python code.
- [] This pull request includes tests or only affects documentation.

Add PR checkbox for docstrings and Python SDK doc files

---

docs/concepts/blocks.md
src/prefect/blocks/core.py
tests/blocks/test_core.py

previously, we forced callers of `save` to pass `name` even if they were trying to save a block that was `.load`ed from the DB
this PR updates `save` to infer `name` from `self._block_document_name` if `name` is not explicitly passed to `save`
```python
async def test_save_block_with_name_inferred_from_loaded_document(NewBlock):
new_block = NewBlock(a="foo", b="bar")
with pytest.raises(
ValueError,
match="You're attempting to save a block document without a name.",
):
await new_block.save()
await new_block.save("new-block")
new_python_instance = await NewBlock.load("new-block")
new_python_instance.a = "baz"
await new_python_instance.save(overwrite=True)
loaded_new_block = await NewBlock.load("new-block")
assert loaded_new_block.a == "baz"
assert loaded_new_block.b == "bar"
```
- If no …

allow saving previously saved blocks without passing `name`

---

docs/concepts/schedules.md
src/prefect/cli/_prompts.py
src/prefect/cli/deploy.py
src/prefect/deployments/base.py
tests/cli/test_deploy.py
tests/input/test_run_input.py

This adds support for an `active` property on the `schedule` definition of a deployment in `prefect.yaml`. It also adds support to the interactive CLI.
Closes #11334 
Closes https://github.com/PrefectHQ/nebula/issues/5838

Support defining if a schedule is active or not via `prefect.yaml`

---

src/prefect/cli/deploy.py
src/prefect/deployments/base.py
tests/cli/test_deploy.py

Closes #10618 
This PR adds a new flag `--prefect-file` to the `prefect deploy` command to support custom prefect file names and locations during deployment. Note that while the file can now be located anywhere, the `prefect deploy` command **must** be run from the project root and the contents of the file (e.g. entrypoints) **must** be relative to the project root.  
In addition to supporting loading configuration from a custom prefect file, these changes also allow a user to save their changes to the target file when they're prompted to do so during deployment.
```shell
❯ prefect deploy --prefect-file ../prefect2.yaml --all
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Deploying out-of-this-dir-prefect …
```

ft: support reading and writing  custom prefect.yaml files

---

docs/concepts/deployments.md
docs/concepts/flows.md
src/prefect/deployments/deployments.py
tests/_internal/concurrency/test_cancellation.py
tests/test_deployments.py

Allow the user to specify when calling `run_deployment` whether or not they want the flow run to run as a subflow.

Make subflows optional with run_deployment

---

src/prefect/context.py

classes decorated with`PrefectObjectRegistry`'s `register_instances` (like `Flow`) had obfuscated methods / typing, which is most relevant with `my_flow.deploy`, `my_flow.from_source`, `my_flow.to_deployment` etc, but also `flow`/`task` `with_options` and similar methods
this should make it easier to grok what is needed to deploy a flow minimally without being reliant on docs

fix IDE support for `PrefectObjectRegistry.register_instances` decorated classes

---

src/prefect/deployments/steps/utility.py
tests/cli/test_deploy.py

This PR focuses on handling errors more effectively during the execution of `run_shell_script` in deployment steps. Instead of silently allowing deployment steps to continue during `prefect deploy`, we raise on error here. 

Raise `StepExecutionError` on non-zero `run_shell_script` return code during `prefect deploy`

---

ui/package-lock.json
ui/package.json

Prepping for a release - bumping prefect-ui-library from 2.4.21 -> 2.4.25 🤖

Bump prefect-ui-library to 2.4.25.

---

src/prefect/utilities/callables.py
tests/test_flows_compat.py

This is a direct follow-up to PR #11578, which closed issue #7502. This PR closes #11605. CC @chrisguidry.
When a class is behind an `if TYPE_CHECKING` block, as noted in #7502, the string cannot be evaluated, and the `Flow` can no longer be instantiated.
```python
from __future__ import annotations
from typing import TYPE_CHECKING
if TYPE_CHECKING:
class Test2:
pass
@flow
def foo(x: Test2):
return
assert foo
```
This is because there is no way for `inspection.signature(fn, eval_str=True)` to evaluate the parameter in such a case because `TYPE_CHECKING` is `False` in most real-world cases.
In hindsight, I realized it is probably just simpler to catch the exception and have the parameter be `Any`. Prefect can't find it, and Prefect won't care (at least until Python …

Safer handling of class-based type hints with `from __future__ import annotations`

---

src/prefect/server/api/server.py

Fixes an issue where setting `UI_SERVE_BASE` to an empty string or `/` lead to incorrectly replaced asset urls like `//asset.js` instead of `/asset.js`

Bugfix: Missing `UI_SERVE_BASE_URL` lead to incorrect asset urls

---

docs/concepts/tasks.md

I think this documentation may not work. As in, for any other exception it just gets raised after the last except. `return True`, which is what the documentation says should happen in that case, never gets called. 
Here's some example code to show it:
```python
try:
raise NotImplementedError()
except KeyError:
print("Got caught")
quit()
print("Did get through")
```
Output: `NotImplementedError`
but the documentation here makes it seem like `Did get through` should be printed. 
I think this fixes it!

Fix tasks.md -> retry handler

---

src/prefect/flows.py
src/prefect/runner/storage.py

`GitRepository` does not accept an `access_token` kwarg, rather it seems to accept `credentials: GitCredentials | Block | dict | None`

fix docstring example for `from_source`

---

README.md

Maybe obvious and a minor thing, but as a first-time user, I started the server, then realized I needed to run the Python file first

specify to run the Python file in the README before starting server (and fix typo)

---

flows/concurrent_subflows.py

Currently, testing the `concurrent_subflow.py` flow in integrations tests will fail against client version `2.11.5`. The [fix for concurrent subflows](https://github.com/PrefectHQ/prefect/pull/10533) that added the concurrent subflow flow in the first place was not released until `2.12.0`; so we should test only again versions at equivalent or greater.
I think the reason why we haven't had more regular failures on `main` due to this is because the issue itself (the one the fix is based on) did not always occur and also I'm guessing because there is an element of randomness in our concurrent subflow test. We began to see this failure more regularly in December. …

Fix intermittent integrations test failure when testing compatibility with 2.11

---

src/prefect/server/api/server.py
src/prefect/settings.py

Fixes an issue documented in #11640 where running `prefect server start` with a user that didn't have write permissions to the package subdirectory would cause the command to fail. 
This exposes a setting, `PREFECT_UI_STATIC_DIRECTORY`, that `prefect server start` will attempt to write to instead, allowing the directory to be created/properly permissioned ahead of time. We also no longer remove the root directory when the setting has changed (or on first run) and only overwrite its contents.
Resolves: #11640

Bugifx: Adjust UI serving to work with a static directory

---

src/prefect/runner/server.py
src/prefect/runner/submit.py
tests/runner/test_submit.py
tests/runner/test_webserver.py

returning `flow_run` from `submit_to_runner` makes better use of the fact that the webserver endpoint already asks the API for a `FlowRun` when we create it and hand it off to the `Runner`

return flow run and update tests

---

docs/guides/host.md
src/prefect/cli/server.py
src/prefect/server/database/alembic_commands.py
src/prefect/server/database/interface.py
tests/server/database/test_alembic_commands.py
tests/server/database/test_migrations.py

Running `prefect server database downgrade` without an explicit target revision defaults to "base" which basically drops the database. While there is a confirmation step here, it'd be nice if the default were less destructive in general as dropping a database is a pretty unfortunate booboo. 
Aside from safety, this new default behavior should be familiar to folks from the flask ecosystem working with tooling like flask-migrate. This default is also just a little more convenient when developing with in-flight migrations. 
```sh
prefect server database downgrade
prefect server database downgrade -r base
```
For new …

Make `server database downgrade` default revision less destructive

---

docs/concepts/flows.md

Some users are running the from_source example that uses a fake repository and are confused when it doesn't run.

Add runnable example of flow.from_source()_flows.md
