PrefectHQ/prefect

.github/workflows/codeql-analysis.yml

* Run static code analysis in pull requests whenever code changes, and upload reports to CodeQL
* Add a schedule to run the scans weekly on Sunday at 20:30 UTC
* Cancel in-progress scans for pull requests, and serialize scans on main branch
* Do not install Python dependencies prior to scan

chore: update CodeQL settings

---

src/prefect/infrastructure/docker.py
tests/infrastructure/test_docker_container.py

This PR adds the `kill` method for Docker containers as part of #7666

Add kill docker method

---

RELEASE-NOTES.md

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.7.0/RELEASE-NOTES.md#release-270)

Add release notes for 2.7.0

---

src/prefect/infrastructure/kubernetes.py
tests/infrastructure/test_kubernetes_job.py

Fix cluster config not found

---

orion-ui/package-lock.json
orion-ui/package.json
orion-ui/src/pages/FlowRun.vue

Bump orion-design to 1.1.23, prefect-design to 1.1.33 and update Cancel button to proper implementation

---

orion-ui/package-lock.json
orion-ui/package.json
orion-ui/src/pages/Deployments.vue
orion-ui/src/pages/FlowRuns.vue
orion-ui/src/pages/Flows.vue

This clean-up PR is a maintenance PR to make sure the multi-delete from orion-design doesn't break anything

Bump orion-design to 1.1.30 and fix breaking change in multi delete

---

docs/concepts/tasks.md
docs/faq.md

Add `wait_for` to the `Tasks` section under `Concepts` and add a link to this section on the FAQ page.

Move wait_for examples to Tasks documentation

---

orion-ui/src/components/ContextSidebar.vue
orion-ui/src/pages/ConcurrencyLimits.vue
orion-ui/src/router/index.ts

Shows task run concurrency limits and adds the ability to add a task run concurrency limit from the UI

Add a task run concurrency limits page

---

docs/concepts/logs.md

Resolves incorrect statement pointed out by a user: https://prefect-community.slack.com/archives/CL09KU1K7/p1670509705787889?thread_ts=1670480537.109379&cid=CL09KU1K7

Remove incorrect statement regarding CLI access to logs

---

RELEASE-NOTES.md

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.7.1/RELEASE-NOTES.md)

Add release notes for 2.7.1

---

src/prefect/_internal/compatibility/experimental.py
src/prefect/settings.py
tests/_internal/compatibility/test_experimental.py

Adds utilities for marking features as experimental. In brief:
- Use of experimental features will display a warning unless disabled.
- Experimental features can require explicit opt-in or usage will raise an error.
- Adding a new experimental group requires adding a setting to toggle warnings. If the group requires explicit opt-in, another setting must be added.
Regarding the module structure: I intend to begin moving internal code into an `_internal` module so we can be very explicit about what our user-facing API is. This `compatibility` namespace will house a `deprecated` module for upcoming deprecation related utilities and a `backports` module for the code currently in `prefect.utilities.compat`.
```python
from prefect._internal.compatibility.experimental import experimental …
```

Add experimental utilities

---

tests/fixtures/database.py

Running migrations is expensive with a time of ~5s. Test databases are always isolated and deleted at the end of the test session so there's no reason to run downgrades during test session teardown. When running a single test, this cuts test suite runtime in half.
```
❯ pytest tests/test_flows.py::TestFlow::test_initializes --durations 5 --no-cov
```
main:
```
4.08s setup    tests/test_flows.py::TestFlow::test_initializes
3.87s teardown tests/test_flows.py::TestFlow::test_initializes
```
this branch: 
```
4.08s setup    tests/test_flows.py::TestFlow::test_initializes
0.03s teardown tests/test_flows.py::TestFlow::test_initializes
```

Remove down-migrations from database setup fixture

---

src/prefect/agent.py
tests/agent/test_agent_run_submission.py

Closes https://github.com/PrefectHQ/prefect/issues/7841
Agent concurrency limits added in #7361 did not handle a case where the API denied the transition to PENDING causing a concurrency slot to be permanently consumed for flow runs that encountered this orchestration instruction.
This adds the missing token release and adds test coverage.

Fix bug where agent concurrency slots may not be released

---

docs/stylesheets/extra.css

Adds a new "Beta" badge, based on styling used in the Cloud UI.
Updates the "Experimental" badge to use similar styling.

Adds CSS for a Beta badge

---

.github/codeql-config.yml

chore: add exclusions for noisy CodeQL rules

---

docs/collections/usage.md
docs/recipes/recipes.md

Hopefully including these three words:
1. tutorial
2. recipes
3. example
can help with visibility when users search for this.

Mention recipes and tutorials under Recipes and Collections pages

---

orion-ui/.eslintrc.js
orion-ui/package-lock.json
orion-ui/package.json
orion-ui/src/main.ts
orion-ui/src/pages/ConcurrencyLimits.vue
orion-ui/src/pages/FlowRun.vue
orion-ui/src/pages/FlowRunRadar.vue
orion-ui/src/pages/WorkQueue.vue
orion-ui/src/utilities/meta.ts

updated to latest [@prefecthq/eslint-config](https://www.npmjs.com/package/@prefecthq/eslint-config)
applied fixes with `npm run lint:fix`
fixed 1 not auto-fixable error manually (meta/ts string | undefined)

eslint config update and warnings fixed

---

RELEASE-NOTES.md

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.7.2/RELEASE-NOTES.md)

Add release notes for 2.7.2

---

docs/overrides/main.html

Update announcement bar for 2.7.2 release

---

docs/overrides/main.html

Update announcement bar for 2.7.3 release.
Links change, text continues to promote 2.7.2 features.

Update announcement bar for 2.7.3 release

---

setup.py

Minor change that updates setup.py to point at the main branch

Update setup.py link to correct repo

---

docs/concepts/deployments.md

Should be just a function, b/c not attached to a class.

Update language in Deployments concept page

---

docs/concepts/deployments.md

`prefect deployment` command docs were not updated which caused the `command not found` issue. To fix this I ran `prefect deployment --help` and pasted its contents in the docs.  Closes #7939.

Update `prefect deployment` command listing

---

src/prefect/blocks/abstract.py
tests/blocks/test_abstract.py

Adds the CredentialsBlock abstract interface.
Part of https://github.com/PrefectHQ/prefect/issues/7884

Add credentials abstract block

---

src/prefect/orion/models/flow_runs.py

Adds task run names to the `/graph` route for use by the UI in visualizations.

Enhancement: Add task run names to the `/graph` route

---

src/prefect/futures.py

Fix docstring examples in the `PrefectFuture`

---

src/prefect/cli/agent.py
src/prefect/cli/work_queue.py
src/prefect/client/orion.py

Clarify deprecation date for tag-based work queues.

Update tag-based work queue deprecation messages to include deprecation date

---

src/prefect/utilities/asyncutils.py

This attempts to reduce the effect of issues such as #7934 #7299 #7826 while we work on improving underlying patterns (such as in #7942)

Increase the default thread limit from 40 -> 250

---

docs/overrides/main.html

[preview](https://deploy-preview-7971--prefect-orion.netlify.app/)

Updated announcement bar for 2.7.4 release

---

RELEASE-NOTES.md

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.7.4/RELEASE-NOTES.md#release-274)

Add release notes for 2.7.4

---

docs/concepts/task-runners.md

Fixing task annotation in task runner docs

---

tests/cli/test_version.py

Add tests for the `prefect version` command.
Closes #6524 

Add tests for cli version output

---

orion-ui/package-lock.json
orion-ui/package.json

Update vite and vitejs/plugin-vue

---

orion-ui/package-lock.json
orion-ui/package.json
orion-ui/src/maps/index.ts
orion-ui/src/maps/uiSettings.ts

part 2 of this code review suggestion
https://github.com/PrefectHQ/prefect/pull/7965#discussion_r1057885854
using new `isNotNullish` type guard from orion-design instead of local function

replaced local guard with isNotNullish from orion-design

---

docs/collections/contribute.md

Originally from https://discourse.prefect.io/t/how-can-i-extend-a-block-class/2099/4

Add instructions for building custom blocks docs

---

src/prefect/orion/api/workers.py
tests/orion/api/test_workers.py

The update worker pool queue had a bug that cause it to always return 500. This PR fixes the bug and adds a test for coverage.

Fixes error in worker pool queue endpoint

---

.github/workflows/release.yaml

This is the manual process I'm doing to repair docs pull requests triggered by releases :)

Add rebase to docs release process

---

.github/workflows/remove-issue-labels.yaml

Add GitHub Actions Workflow to remove labels from closed issues

---

src/prefect/orion/collection_blocks_data.json

- Adds `BigQueryWarehouse` block to be registered by default
- Updates `GcpCredentials` to be registered with `SecretDict` field by default
[Best viewed without whitespace changes](https://github.com/PrefectHQ/prefect/pull/8009/files?diff=unified&w=1)

Updates prefect-gcp blocks for 0.2.1 release

---

src/prefect/orion/collection_blocks_data.json

`GcpCredentials` needs to be registered before other `prefect-gcp` blocks since they depend on it. This ensures the proper order.

Fixes collection blocks json ordering

---

src/prefect/orion/api/flow_runs.py
src/prefect/orion/models/flow_runs.py
src/prefect/orion/schemas/actions.py
tests/orion/api/test_flow_runs.py
tests/orion/models/test_flow_runs.py

Adds the ability to filter flow runs by the attributes of the corresponding worker pool and worker pool queue. Will be used by the UI when displaying flow runs for a given worker pool and worker pool queue.

Adds filtering to flow runs by worker pool and worker pool queue attributes

---

RELEASE-NOTES.md
docs/overrides/main.html

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes/RELEASE-NOTES.md)

Release notes for 2.7.5

---

src/prefect/cli/block.py
tests/cli/test_block.py

I think this will make it easier for users to get started with blocks, and users can simply alt click the link to get directed.
Cloud:
Local:

Link to blocks catalog upon registering blocks in CLI

---

docs/collections/usage.md
docs/concepts/blocks.md

Since we're now including all blocks at top level, drop the `.ecs` and `.credentials`.
Also move snippets to their proper sections and reference Block docs.

Fix up blocks docs

---

docs/collections/contribute.md

Spread awareness that users can also help enhance our collections!

Add a contributing features / bug fixes section to Collections docs

---

orion-ui/vite.config.ts

Fixed vue-router injection issues when linking packages locally

dedupe vue-router

---

docs/concepts/blocks.md

Shows how to use the new block document / schema migration built into `Block.save` / `Block.load`

add docs on migrating block documents

---

README.md

Add youtube badge

---

.github/CODEOWNERS

I am tired of requesting review explicitly  :)

Add Peyton and Serina as global code owners

---

docs/concepts/deployments.md

Doc had an incorrect example of `infra_override`. It was a list. It has been changed to a dict.
```diff
-  infra_overrides=["env.SOME_IMPORTANT_CONFIG=true"],
+  infra_overrides={
+        "env": {
+            "ENV_VAR": "value"
+       }
+    },
```

[Issue #456] Change example of `infra_override` in docs/concepts/deployment

---

.github/workflows/docker-builds.yaml

Fix for #7900 
Tested on `main` of my fork ref https://github.com/ddelange/prefect/actions/runs/3875949170/jobs/6609182214#step:7:120

Fix docker-builds.yaml templating syntax

---

.github/CODEOWNERS

Replacing individual contributors.

Add @PrefectHQ/open-source as codeowner

---

src/prefect/experimental/workers/base.py
tests/experimental/workers/test_base_worker.py

Fixes https://github.com/PrefectHQ/prefect/issues/8130

Removes cancellation of tasks when exiting worker context

---

src/prefect/engine.py
tests/test_tasks.py

Addresses https://github.com/PrefectHQ/prefect/issues/8124
Adds annotation support to `map` — we unwrap the annotation to get the value to check if it's an iterable then wrap the mapped values with the annotation again.
```python
from prefect import flow, task, allow_failure
@task
def fail_on_two(x):
if x == 2:
raise ValueError("Hi 2")
return x + 1
@task
def identity(x):
if isinstance(x, Exception):
return None
return x + 2
@flow
def map_with_allow_failure():
b = fail_on_two.map([1, 2, 3])
c = identity.map(allow_failure(b))
for future in c:
print(repr(future.wait()))
map_with_allow_failure(return_state=True)
```
```
13:06:32.553 | INFO    | prefect.engine - Created flow run 'faithful-wildebeest' for flow 'map-with-allow-failure'
13:06:32.674 | INFO    | Flow run …
```

Add support for `allow_failure` to mapped task arguments

---

src/prefect/experimental/workers/base.py
src/prefect/orion/schemas/actions.py
tests/experimental/workers/test_base_worker.py
tests/experimental/workers/test_process_worker.py
tests/fixtures/database.py
tests/orion/api/test_deployments.py
tests/orion/api/test_workers.py
tests/orion/schemas/test_core.py

Make review changes

---

docs/api-ref/overview.md
docs/api-ref/rest-api-reference.md
docs/ui/cloud.md
docs/ui/overview.md

Took this snippet from https://docs.prefect.io/api-ref/rest-api/ and additionally copied here because a user asked "Thoughts around making REST API endpoints available so users can configure workspaces and permissions without using the UI? e.g workspace creation, roles, service accounts"
I can understand why he missed it because if a user is already familiar with REST concepts, he may skip reading the overview and jump right into the API reference.

Add additional links to live Orion and Cloud REST API docs

---

.github/release.yml

I've been doing this manually. 
I've also added a corresponding `experimental` label.

Add experimental section to releases

---

mkdocs.yml

Found this: https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links

Add social links

---

src/prefect/filesystems.py
tests/test_filesystems.py

Closes https://github.com/PrefectHQ/prefect/issues/7664
Confirmed to work for the user here: https://github.com/PrefectHQ/prefect/issues/7664#issuecomment-1396589690
The GitHub storage block currently clones a repo from GitHub and then copies that repo into a directory. The default behavior is to copy the repo into a random directory, but a directory can also be specified on a process infrastructure block using `working_dir`. 
Using `working_dir` causes an issue when attempting to run a deployment multiple times, because a cloned repo includes `.git` files, which are read only. When shutil attempts to copy files into this directory, it raises a permission error when attempting to overwrite the git objects.
This pull request add a parameter `include_git_objects` to the block, which says …

Add option to filter git files with GitHub block

---

RELEASE-NOTES.md
docs/overrides/main.html

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-279/RELEASE-NOTES.md)

Add Release Notes for 2.7.9

---

orion-ui/package-lock.json
orion-ui/package.json
orion-ui/src/pages/FlowRun.vue
orion-ui/src/pages/TaskRun.vue

updates to latest orion-design which had breaking changes migrating away from JsonView and PythonView components.
this PR also updates to latest 
- prefect-design
- vue-composition

Latest orion design

---

docs/index.md

Fix reported broken link to automations page.
Along the way, fix some other working but malformed links.

Fix broken link and generally standardize links on home page

---

src/prefect/deployments.py

Changes docstring of `flow` parameter in `Deployments` to `flow_name` to match code behavior.

Updates deployments docstring to match behavior

---

docs/contributing/overview.md

Adds an example virtual environment setup to help beginners get an isolated environment.
Separates the blurb about running tests.
https://deploy-preview-8247--prefect-orion.netlify.app/contributing/overview/

Improve contributing documentation with venv instructions

---

src/prefect/orion/database/migrations/versions/postgresql/2023_01_25_152801_0a1250a5aa25_expand_work_queue_table.py
src/prefect/orion/database/migrations/versions/sqlite/2023_01_25_114348_b9bda9f142f1_expand_work_queue_table.py

- Adds unique constraints
- Adds indexes
- Adds downgrade
- Adds postrgresql migration
- Add default agent work pool creation
- Add migration of existing queues to default agent work pool

Migration enhancements

---

src/prefect/orion/database/migrations/versions/postgresql/2023_01_25_152801_0a1250a5aa25_expand_work_queue_table.py
src/prefect/orion/database/migrations/versions/sqlite/2023_01_25_114348_b9bda9f142f1_expand_work_queue_table.py

- Fixes errors in migration that arose from existing work queues
- Makes `type` column on `work_pool` table non-nullable

Fixes error in migration

---

src/prefect/cli/orion.py
src/prefect/settings.py
tests/cli/test_orion.py

Cleanup `PREFECT_ORION_API_KEEPALIVE_TIMEOUT` description and name

---

RELEASE-NOTES.md
docs/overrides/main.html

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.7.10/RELEASE-NOTES.md)

Add release notes for 2.7.10

---

RELEASE-NOTES.md

A very minor change to do something interesting instead of just pulling an image

Update release notes example to run a command

---

docs/recipes/contribute-recipes.md

Adds git commands to Recipes contribution page to make it easier for external Prefect users to add their own recipes. 
[Preview](https://deploy-preview-8283--prefect-orion.netlify.app/recipes/contribute-recipes/#steps-to-adding-your-recipe)
***
***

Add git commands to Prefect Recipes contribution page

---

docs/faq.md

Fix Prefect Cloud typo in FAQ

---

.github/workflows/issue-bot.yaml

I think [Issue bot is failing](https://github.com/PrefectHQ/prefect/actions/runs/4032274574) due to this issue: https://github.com/actions/runner/issues/866
This fix is intended to ensure the Issue bot action is successful.
Update: Static analysis failure is not limited to this PR. Similar [errors here in this issue ](https://github.com/sktime/sktime/issues/4162) opened this morning.

Update Issue bot

---

.github/workflows/issue-bot.yaml

Remove issue label `status:in-progress` and `status:accepted` when issue closed as completed.

Update issue label workflow

---

orion-ui/src/pages/Deployment.vue

This PR adds infra overrides tab object to Deployment page
Closes https://github.com/PrefectHQ/prefect/issues/8271

Add infra overrides tab to Deployments page

---

docs/.vuepress/config.js

Adds a `noindex` meta tag to site configuration

Add noindex meta tag

---

orion-ui/package-lock.json
orion-ui/package.json

This PR bumps the orion-design dependency to 1.2.12, in part so it has the latest Flow Run Timeline changes.

bump orion design to 1.2.12

---

src/prefect/orion/database/migrations/MIGRATION-NOTES.md
src/prefect/orion/database/migrations/versions/postgresql/2023_01_31_133052_2a88656f4a23_clean_up_work_queue_migration.py
src/prefect/orion/database/migrations/versions/sqlite/2023_01_31_132409_bfe42b7090d6_clean_up_work_queue_migration.py

Cleans up work queue migration by deleting the `work_pool_queue` table and makes the `work_pool_id` column on the `work_queue` table non-nullable.

Adds clean up migration

---

docs/collections/usage.md

Add tips for re-registering blocks from Prefect Collections

---

orion-ui/src/pages/Deployment.vue
orion-ui/src/pages/FlowRun.vue
orion-ui/src/pages/TaskRun.vue

This clean-up PR fixes few small CSS issues

Update CodeSnippet and fix odd issue with extra space on flowRun page

---

orion-ui/src/pages/WorkPoolQueue.vue

Update `prefect agent start --pool default-agent-pool --queue my-queue-name` to `prefect agent start --pool default-agent-pool --work-queue my-queue-name` 

Update poolQueue code banner and remove unused code

---

src/prefect/cli/deployment.py
src/prefect/client/orion.py
src/prefect/deployments.py
tests/cli/deployment/test_deployment_build.py
tests/cli/deployment/test_deployment_cli.py
tests/orion/api/test_deployments.py

Fixes behavior discovered during work pools testing.
- Adds error when attempting to apply a deployment to a work pool that hasn't been created yet.
- Creates queues in the correct work pool when applying a deployment for a queue that hasn't been created yet.

Adds work pool fixes for deployments CLI

---

RELEASE-NOTES.md
docs/overrides/main.html

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.7.12/RELEASE-NOTES.md#release-2712)

Add release notes for 2.7.12

---

orion-ui/src/pages/WorkPool.vue

In this PR 'Queue' was changed to 'Work Queue' on the workPool page

Update Queue name to Work Queue

---

src/prefect/cli/block.py
tests/cli/test_block.py

Don't show a link if the UI URL is empty.
Closes https://github.com/PrefectHQ/prefect-github/issues/43
`prefect register block -m prefect`

During blocks registration, hide link to blocks catalog if PREFECT_UI_URL is None

---

orion-ui/src/pages/WorkPool.vue

This PR fixes non-working filter

Update flowRunFilter on WorkPool page

---

docs/concepts/infrastructure.md

Updates infrastructure concept docs to reflect 
1. need for s3fs block in S3 storage example with infrastructure overrides
1. deployment.yaml changes seen when run in 2.7.12

Update Infrastructure to include extra-pip-package in example and updated deployment.yaml

---

src/prefect/orion/api/flow_runs.py
src/prefect/orion/api/run_history.py
src/prefect/orion/models/task_runs.py
tests/orion/api/test_run_history.py

Adds filters to flow run history endpoint to facilitate flow run filtering in the UI

Adds work pool and queue filters to flow runs history endpoint

---

README.md
docs/core/getting_started/quick-start.md

Remove outdated Orion references from v1 docs.

Remove Orion references

---

RELEASE-NOTES.md
docs/concepts/logs.md
src/prefect/cli/config.py
src/prefect/logging/handlers.py
src/prefect/settings.py
tests/cli/test_config.py
tests/conftest.py
tests/fixtures/logging.py
tests/test_logging.py

Part of #8454 
Updates logging settings as an example of how settings will change. Expands on utilities added in #8402 to improve the setting rename experience.
Adds `prefect config validate` to automatically migrate the current profile.
```python
from prefect.settings import PREFECT_LOGGING_ORION_ENABLED
print(PREFECT_LOGGING_ORION_ENABLED.value())
from prefect.settings import temporary_settings, PREFECT_LOGGING_TO_API_ENABLED
print(PREFECT_LOGGING_TO_API_ENABLED.value())
with temporary_settings({PREFECT_LOGGING_ORION_ENABLED: True}):
print(PREFECT_LOGGING_TO_API_ENABLED.value())
```
```
$ prefect config set PREFECT_LOGGING_ORION_ENABLED=False
$ prefect config validate
``` …

Rename `ORION` logging settings

---

orion-ui/package-lock.json
orion-ui/package.json

Bumps the orion-design dependency to the latest version.

bump orion-design to 1.2.23

---

RELEASE-NOTES.md

Amend release notes 2.8.0

---

RELEASE-NOTES.md

- [ x] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`

edits to to release notes on work pools

---

docs/concepts/filesystems.md

Fix minor typo in Filesystems

---

src/prefect/agent.py
src/prefect/cli/agent.py
tests/agent/test_agent_run_cancellation.py
tests/agent/test_agent_run_submission.py
tests/cli/test_agent.py

Rename `OrionAgent` to `PrefectAgent`

---

docs/api-ref/overview.md
docs/api-ref/prefect/cli/server.md
docs/api-ref/rest-api.md
docs/concepts/deployments.md
docs/concepts/work-pools.md

Part of #8454 
Fixes docs build errors and some missed references.

Fixups for Orion references in documentation

---

src/prefect/server/api/admin.py
src/prefect/server/api/block_capabilities.py
src/prefect/server/api/block_documents.py
src/prefect/server/api/block_schemas.py
src/prefect/server/api/block_types.py
src/prefect/server/api/concurrency_limits.py
src/prefect/server/api/deployments.py
src/prefect/server/api/flow_run_notification_policies.py
src/prefect/server/api/flow_run_states.py
src/prefect/server/api/flow_runs.py
src/prefect/server/api/flows.py
src/prefect/server/api/logs.py
src/prefect/server/api/root.py
src/prefect/server/api/saved_searches.py
src/prefect/server/api/task_run_states.py
src/prefect/server/api/task_runs.py
src/prefect/server/api/ui/flow_runs.py
src/prefect/server/api/work_queues.py
src/prefect/server/api/workers.py
src/prefect/server/utilities/server.py
tests/server/utilities/test_server.py

Rename `OrionRouter` to `PrefectRouter`

---

docs/overrides/partials/integrations/analytics/custom.html
mkdocs.yml

Enables custom analytics and adds Segment analytics.

Add custom analytics

---

src/prefect/engine.py
src/prefect/logging/handlers.py
src/prefect/logging/loggers.py
src/prefect/logging/logging.yml
tests/fixtures/logging.py
tests/test_logging.py

Rename `OrionHandler` to `APILogHandler`

---

docs/tutorials/deployments.md
docs/tutorials/orchestration.md
docs/ui/overview.md

This pull request updates the sample output on several docs pages to match the updated Prefect CLI output. 
Follows up on changes made in #8434.
Before: 
```
___ ___ ___ ___ ___ ___ _____    ___  ___ ___ ___  _  _
| _ \ _ \ __| __| __/ __|_   _|  / _ \| _ \_ _/ _ \| \| |
|  _/   / _|| _|| _| (__  | |   | (_) |   /| | (_) | .` |
|_| |_|_\___|_| |___\___| |_|    \___/|_|_\___\___/|_|\_|
```
After:
```
___ ___ ___ ___ ___ ___ _____ 
| _ \ _ \ __| __| __/ __|_   _|
|  _/   / _|| _|| _| (__  | |
|_| |_|_\___|_| |___\___| |_|
```
This matches the new output of `prefect server start`:
https://github.com/PrefectHQ/prefect/blob/f1cf1109e2db279f16f8257405c80482e21359c0/src/prefect/cli/server.py#L73-L76 …

Update welcome message in docs

---

docs/ui/automations.md

Update example: camel to snake case

---

docs/ui/automations.md

Adds a line in the docs for the new webhook action

Add webhooks to Automations  docs

---

tests/fixtures/logging.py

Update log handler reset fixture to `reset_api_log_handler`

---

src/prefect/experimental/workers/base.py
src/prefect/experimental/workers/process.py
tests/experimental/workers/test_base_worker.py

Adds metadata fields `_logo_url`, `_documentation_url`, and `_description` to `BaseWorker` to facilitate display of workers in the Prefect UI. Also added class methods to retrieve the metadata values along with `get_default_base_job_configuration` to generate and return the default base job configuration for a worker.
```python
>>> from prefect.experimental.workers.process import ProcessWorker
>>> ProcessWorker.get_description()
'Worker that executes flow runs within processes.'
>>> ProcessWorker.get_default_base_job_configuration()
{
'job_configuration':{
'command':'{{ command }}',
'stream_output':'{{ stream_output }}',
'working_dir':'{{ working_dir }}'
},
'variables':{
'properties':{
'command':{
'title':'Command',
'type':'array',
'items':{
'type':'string'
}
},
'stream_output':{ …
```

Adds metadata fields to `BaseWorker`

---

src/prefect/_internal/concurrency/runtime.py
tests/_internal/concurrency/test_runtime.py

Switches from an event to signal readiness to a future, allowing us to attach an exception. Otherwise, exceptions are hidden in the runtime thread and do not result in an exception in the main thread.

Add re-raise of exceptions during runtime startup

---

docs/index.md

Misc tweaks to landing page

---

.gitignore
ui/.vscode/css-data.json
ui/.vscode/extensions.json
ui/.vscode/settings.json
ui/.vscode/vue.code-snippets

Add back the vscode folder to the ui

---

docs/overrides/main.html

Update announce bar for 2.8.1

---

docs/api-ref/overview.md
docs/index.md

Adds note to docs landing page and API overview page noting Orion nomenclature change.

Add Orion nomenclature note

---

RELEASE-NOTES.md

I forgot to mention this previously.
I've also moved the full list of changes to the "Deprecated" section so it flows a little better.

Add note about `prefect config validate` to release notes

---

docs/concepts/logs.md

Closes https://github.com/PrefectHQ/prefect/issues/8512

Fix logging format override example

---

.github/workflows/issue-bot.yaml

Example failure at https://github.com/PrefectHQ/prefect/actions/runs/4237114120/jobs/7362702356

Fix issue bot `--remove-label` usage

---

scripts/test-with-postgres

The script for testing with postgres had an old URL that didn't reflect the changes that we recently made with the rename, so it wasn't working. This fixes the URL so that the script works again. 

Fix incorrect postgres URL in testing script

---

ui/package-lock.json
ui/package.json
ui/src/pages/Deployment.vue
ui/src/pages/FlowRun.vue
ui/src/pages/TaskRun.vue

this updates pages that were using the now deprecated CodeSnippet component to use the replacement CopyableWrapper component

Remove code snippet

---

docs/concepts/flows.md

The current doc doesn't mention that users can resume the flow run through the UI. This PR adds this utility to the doc. 

Docs: Add Resume Flow Run Through UI

---

ui/package-lock.json
ui/package.json
ui/src/pages/FlowRuns.vue

Fixes issues with selecting a date range filter on the flow runs page

Fix flow run filters date range not working properly

---

ui/package-lock.json
ui/package.json
ui/src/pages/AppRouterView.vue
ui/src/pages/FlowRuns.vue

pulls together changes from 
https://github.com/PrefectHQ/prefect-design/pull/665
https://github.com/PrefectHQ/prefect-ui-library/pull/1178
also
- changes app background color in light-mode
- applies similar style to transparent sticky header on flow runs list to match new bg color

Light and dark mode color and contrast enhancements

---

src/prefect/engine.py

Moves the function above the main block. 

Move _run_flow_hooks above the main block

---

src/prefect/engine.py

Fixes logging for task hooks to match flow hooks 

Make task hook logging match flow hook logging

---

RELEASE-NOTES.md
docs/overrides/main.html

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.8.3/RELEASE-NOTES.md)

Add release notes for 2.8.3

---

src/prefect/agent.py

Removes an unnecessary if statement that didn't affect the logical flow.

Removes unnecessary if statement

---

src/prefect/cli/root.py

I fixed small typo - word 'this' was repeated twice in help menu ```prefect --help``` 

Fix of a typo - removed repeated word

---

src/prefect/blocks/kubernetes.py
tests/blocks/test_kubernetes_block.py

Closes https://github.com/PrefectHQ/prefect/issues/8640

Add support for yaml config strings to `KubernetesClusterConfig`

---

netlify.toml
netlify/edge-functions/segment.ts

Add Netlify Edge function to proxy to Segment

---

src/prefect/_internal/concurrency/from_async.py
src/prefect/_internal/concurrency/from_sync.py
src/prefect/_internal/concurrency/supervisors.py
tests/_internal/concurrency/test_supervisors.py

Update `send_call` to `send_call_to_supervisor`

---

src/prefect/engine.py
src/prefect/utilities/callables.py

Closes https://github.com/PrefectHQ/prefect/issues/8665

Ensure flow parameters default values are present during deployment runs

---

ui/src/pages/Settings.vue

Closes https://github.com/PrefectHQ/prefect/issues/7016

Fix version misaligned on the settings page in the UI

---

tests/infrastructure/test_kubernetes_job.py

Closes https://github.com/PrefectHQ/prefect/issues/8678

Increase tolerance for `test_allows_configurable_timeouts_for_pod_and_job_watches`

---

ui/package-lock.json
ui/package.json

[Changelog](https://github.com/PrefectHQ/prefect-ui-library/blob/main/CHANGELOG.md#1112)

Chore: Bump prefect-ui-library 1.1.10 => 1.1.12

---

RELEASE-NOTES.md
docs/overrides/main.html

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.8.4/RELEASE-NOTES.md#release-284)

Add release notes for 2.8.4

---

netlify.toml

Should fix an issue where the deployment docs were throwing an error.

Chore: Update CSP script-src to include bundled mermaid script

---

tests/infrastructure/test_kubernetes_job.py

Closes https://github.com/PrefectHQ/prefect/issues/8720

Loosen assertion range on `test_allows_configurable_timeouts_for_pod_and_job_watches`

---

netlify.toml

Fixes some missing images in the docs

Buygfix: Add img.shield.io to allow list

---

src/prefect/_internal/concurrency/portals.py
src/prefect/_internal/concurrency/supervisors.py
tests/_internal/concurrency/test_api.py
tests/_internal/concurrency/test_supervisors.py

Cherry-picking fixes from https://github.com/PrefectHQ/prefect/pull/8702 onto #8717

Fix bugs in supervisors implementation

---

ui/src/pages/WorkPool.vue
ui/src/pages/WorkPoolQueue.vue

- Adds code banner to work pool page
- Updates work pool queue code banner to show worker start command when appropriate
- Adds workers table behind enable-workers feature flag

UI updates for workers beta

---

src/prefect/_internal/concurrency/calls.py
tests/_internal/concurrency/test_calls.py
tests/_internal/concurrency/test_waiters.py

Adds test coverage for calls and capturing base exceptions during waits

Add tests for base exceptions and calls

---

setup.cfg

See https://github.com/PrefectHQ/prefect/issues/8786

Ignore deprecation warning for starlette shutdown/startup hooks

---

.github/workflows/helm-chart-release.yaml

chore: trigger helm chart release upon release

---

src/prefect/experimental/cli/worker.py
src/prefect/experimental/workers/base.py
tests/agent/test_agent_run_submission.py
tests/experimental/cli/test_worker.py
tests/experimental/workers/test_base_worker.py
tests/fixtures/database.py
tests/server/api/test_deployments.py

Adds options to the `prefect worker start` CLI command to allow workers to only poll a subset of work queues in a work pool. 
Added options mirror the options available for the agent CLI:
- `--work-queue` specifies a specific work pool to pool and can be used multiple times in the same command
- `--match` specifies a work queue prefix to match and can be used multiple times in the same command
Start a worker to poll only one work queue:
```bash
prefect worker start --pool olympic --work-queue lane-1
```
Start a worker to poll two work queues:
```bash
prefect worker start --pool olympic -q lane-1 -q lane-2
```
Start a worker to poll all work queues matching a prefix:
```bash
prefect worker start --pool olympic --match lane
```
- If no issue exists and your change is not a small fix, please …

Add `--work-queue` option to worker CLI

---

docs/api-ref/prefect/blocks/webhook.md
mkdocs.yml

Adds / wires up docs on the webhook block

adding webhook block docs

---

src/prefect/experimental/cli/worker.py
src/prefect/experimental/workers/base.py
src/prefect/experimental/workers/process.py
src/prefect/settings.py
tests/experimental/workers/test_base_worker.py

Removing experimental feature where workers auto-apply deployments discovered in a per-determined storage location. Will be replaced by a better UX for deploying flows.

Remove workers' ability to auto-apply deployments

---

docs/concepts/task-runners.md
docs/tutorials/dask-ray-task-runners.md

Updates docs to reflect current Ray support for Python versions.

Update info on Ray's support for hardware and software

---

RELEASE-NOTES.md

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-2.8.6/RELEASE-NOTES.md#release-286)

Add release notes for 2.8.6

---

.github/workflows/helm-chart-release.yaml

fix: use the correct output in helm release workflow

---

ui/package-lock.json
ui/package.json
ui/src/pages/Deployment.vue

Follow up from https://github.com/PrefectHQ/nebula-ui/pull/2553 which was a cloud fix but this will keep things consistent in oss
Needs https://github.com/PrefectHQ/prefect-ui-library/pull/1231

Show all flow runs for deployments rather than just the last 7 days

---

.github/workflows/python-tests.yaml
setup.cfg

This drives me crazy and is not a metric we are using

Disable coverage display during local pytest runs by default

---

.github/codeql-config.yml
src/prefect/runtime/deployment.py
src/prefect/runtime/flow_run.py
tests/runtime/test_deployment.py
tests/runtime/test_flow_run.py

Adds more runtime attributes to address some user requests; note that I chose to call the start time field `scheduled_start_time` for v1 compatibility.  
I did not yet implement `image` access as there are some edge cases I realized that I want to think through (such as when an agent provides a default image instead of the infra block providing it).

More runtime attributes

---

src/prefect/agent.py

This PR updates agents to prepare their own default infrastructure in the case where the deployment does not have an infrastructure block configured.  I came across this while working on backwards compatibility issues with projects.
I believe I could also adjust this code to apply infra overrides, but wanted to break it down into smaller pieces for review.

Add preparation steps even to empty infra block setup

---

.github/workflows/docker-images.yaml

Disable new SLSA provenance setting in buildx

---

docs/ui/automations.md

updating custom trigger to include role

updating custom trigger to include role

---

ui/src/pages/Deployment.vue
ui/src/pages/Flow.vue
ui/src/pages/WorkPool.vue
ui/src/pages/WorkPoolQueue.vue
ui/src/pages/WorkQueue.vue

Updates everywhere we're displaying lists of flow runs to use the full history rather than just the last 7 days. 
Needs https://github.com/PrefectHQ/prefect-ui-library/pull/1245

Show the full run history in ui

---

ui/src/pages/FlowRun.vue

This PR adds a flow run results tab to the flow run page:
After enabling artifacts (`export PREFECT_EXPERIMENTAL_ENABLE_ARTIFACTS=1`), you can test this with the following flow:
```py
from random import randint, random
@task(persist_result=True)
def return_int()-> int:
return randint(0, 10)
@task(persist_result=True)
def return_str()-> str:
return "foo"
@task(persist_result=True)
def return_list()-> list:
return [1, 2, 3]
@task(persist_result=True)
def return_dict()-> dict:
return {"foo": "bar"}
@task(persist_result=True)
def return_bool()-> bool:
return random() > 0.5
@task(persist_result=True)
def return_none()-> None:
return None
@task(persist_result=True)
def return_tuple()-> tuple:
return (1, 2, 3)
@flow
def track_results():
int_result = return_int() …
```

Feature: Flow run results tab

---

src/prefect/settings.py
tests/_internal/compatibility/test_experimental.py
tests/events/test_events_worker.py
tests/server/test_app.py

Reverts PrefectHQ/prefect#8870

Revert "Enable events client experimental flag by default"

---

src/prefect/server/api/artifacts.py

To allow users to review their result artifacts in the UI without modifying their settings.

Allow artifacts to be read without experimental flag

---

src/prefect/server/api/artifacts.py

Fix read artifacts without experimental flag

---

RELEASE-NOTES.md

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.8.7/RELEASE-NOTES.md#release-287)

Release notes 2.8.7

---

.github/workflows/helm-chart-release.yaml

fix: use dot notation for helm release tag

---

README.md

fix broken concepts link

---

src/prefect/server/schemas/filters.py
tests/server/api/test_artifacts.py

Add ability to filter artifacts by type

---

src/prefect/serializers.py
tests/test_serializers.py

Otherwise, when your task fails we'll fail to persist the result and crash.
```python
from prefect.serializers import JSONSerializer
@flow(persist_result=True, result_serializer=JSONSerializer(), cache_result_in_memory=False)
def run_my_flow():
raise ValueError("test")
state = run_my_flow(return_state=True)
state.result()
```
```
❯ PREFECT_LOGGING_LEVEL=INFO python example.py                                                                                       
10:03:37.890 | INFO    | prefect.engine - Created flow run 'noisy-lion' for flow 'run-my-flow'
10:03:39.049 | ERROR   | Flow run 'noisy-lion' - Encountered exception during execution:
File "/Users/mz/dev/prefect/src/prefect/engine.py", line 673, in orchestrate_flow_run …
```

Add support to `JSONSerializer` for serialization of exceptions

---

ui/package-lock.json
ui/package.json
ui/src/components/SettingsCodeBlock.vue
ui/src/pages/FlowRun.vue
ui/tsconfig.json

Implementation of https://github.com/PrefectHQ/prefect-ui-library/pull/1264
Also added the validate:types npm task we use in other projects and fixed a bad import

Bump prefect-ui-library and implement breaking composition changes

---

docs/concepts/results.md

Add `UnpersistedResult` type to the docs

---

src/prefect/runtime/task_run.py
tests/runtime/test_task_run.py

Add `prefect.runtime.task_run.task_name`

---

docs/concepts/artifacts.md

Updates the docs to include valid markdown examples that can be properly rendered in the UI. 
Comments / feedback and ideas on the links section are particularly welcome - I expect there is a way we can add the time and formatting and still make it valid markdown.  But given we have a release coming an example that formats correctly feels more important. 
Previous markdown docs example rendered in the UI:
Updated version:
Previous link and updated link in the UI:

Small update to artifacts docs examples

---

docs/concepts/artifacts.md

Add artifact CLI to documentation

---

.github/workflows/stale.yml

Whoops failure at https://github.com/PrefectHQ/prefect/actions/runs/4566524822/workflow

Fix stale bot cron (every hour)

---

.github/workflows/helm-chart-release.yaml
netlify.toml

Also update nelify environment variable ref

chore: update github action secret reference

---

docs/concepts/deployments.md

As reported in #9004, the mermaid.js diagram isn't rendering very nicely. Text is getting cut off in some places, and isn't nicely centered within diagram elements elsewhere. See before and after screenshots below. 
This PR fixes the issue outlined in #9004 and updates styling in elsewhere to make the diagram more visually appealing. 
This comes at the cost of uglier diagram code due to embedded `div`s. On the other hand, embedding the `div`s makes it clear what style we're applying to each label and is simpler than re-theming Mermaid. Mermaid renders the chart in a shadow DOM, so we can't apply CSS to the chart from the docs CSS files. 
Closes #9004.
**Before**
**After** …

Fixed styling of deployments mermaid diagram

---

docs/concepts/database.md

Docs - Fix spelling on database page

---

docs/concepts/artifacts.md

Docs - Remove unnecessary imports from examples in artifacts page

---

src/prefect/server/api/artifacts.py
src/prefect/server/models/artifacts.py
tests/server/api/test_artifacts.py
tests/server/models/test_artifacts.py

OSS implementation of https://github.com/PrefectHQ/nebula/pull/4287

Add artifacts `/count` route

---

src/prefect/projects/steps/core.py

Allows project build, push, and pull steps to define required packages to run the step with a `requires` keyword. If the step runner is unable to import the function for a step, the packages in required will be installed and the runner will attempt to import the function again. Works will all formats that `pip install` accepts.
A step that requires a PyPI package:
```yaml
build:
- prefect_docker.projects.steps.build_docker_image:
requires: prefect-docker
image_name: repo-name/image-name
tag: dev
```
A step that requires package installable via a git repo:
```yaml
build:
- prefect_docker.projects.steps.build_docker_image:
requires: "git+httpsgithub.com/PrefectHQ/prefect-docker.git@main"
image_name: repo-name/image-name
tag: dev
```
A step that requires a package installable via a local …

Adds `requires` step keyword and auto installation

---

src/prefect/server/database/migrations/MIGRATION-NOTES.md
src/prefect/server/database/migrations/versions/postgresql/2023_04_04_132534_3bf47e3ce2dd_add_index_on_log.py
src/prefect/server/database/migrations/versions/sqlite/2023_04_04_115150_553920ec20e9_add_index_on_log.py
src/prefect/server/database/orm_models.py

Let me know if I should add some tests (and where) and/or migration.
Closes #8973 

Speed up the logs query

---

tests/events/test_events_instrument.py

Move more event test assertions by moving to proper place

---

src/prefect/projects/recipes/docker-gcs/prefect.yaml
src/prefect/projects/recipes/gcs/prefect.yaml

Recipes for new steps added in https://github.com/PrefectHQ/prefect-gcp/pull/167

Adds` gcs` and `docker-gcs` recipes

---

docs/ui/rate-limits.md

Include distinction between personal and organization orchestration rate limits

update rate limit docs

---

tests/client/test_base_client.py

Ensures we respect retry-after headers regardless of error code

Add test for retry-after header on 503 status code

---

ui/package-lock.json
ui/package.json
ui/src/pages/ArtifactKey.vue
ui/src/pages/FlowRun.vue

Adds an artifacts tab to the flow run page and updates the query we're using to fetch keyed artifacts. Bumps prefect-design and prefect-ui-library packages to latest. 
Related / Example here: https://github.com/PrefectHQ/prefect-ui-library/pull/1316

Enhancement: Add artifacts tab to flow run page

---

src/prefect/__init__.py
src/prefect/variables.py
tests/test_variables.py

Adds `Variables` to be used in and outside of flows.
You can access variables in 3 ways:
```python
from prefect import variables
@flow
async def my_flow():
variables.get("my_var")
variables["my_var"]
await variables.get("my_var")
```
closes: https://github.com/PrefectHQ/prefect/issues/9108

`Variables` module

---

src/prefect/__init__.py
src/prefect/cli/__init__.py
src/prefect/cli/variable.py
src/prefect/client/orchestration.py
src/prefect/server/api/__init__.py
src/prefect/server/api/server.py
src/prefect/server/api/variables.py
src/prefect/server/database/interface.py
src/prefect/server/database/migrations/MIGRATION-NOTES.md
src/prefect/server/database/migrations/versions/postgresql/2023_04_05_130406_43c94d4c7aa3_add_pull_steps_column_to_deployment.py
src/prefect/server/database/migrations/versions/postgresql/2023_04_05_134520_310dda75f561_add_variables.py
src/prefect/server/database/migrations/versions/sqlite/2023_04_05_120713_340f457b315f_add_column_to_deployments_for_pull_steps.py
src/prefect/server/database/migrations/versions/sqlite/2023_04_05_134301_3d46e23593d6_add_variables.py
src/prefect/server/database/orm_models.py
src/prefect/server/models/__init__.py
src/prefect/server/models/variables.py
src/prefect/server/schemas/actions.py
src/prefect/server/schemas/core.py
src/prefect/server/schemas/filters.py
src/prefect/server/schemas/sorting.py
src/prefect/variables.py
tests/cli/test_variable.py
tests/client/test_orion_client.py
tests/server/api/test_variables.py
tests/server/models/test_variables.py
tests/test_variables.py
ui/src/components/ContextSidebar.vue
ui/src/pages/Variables.vue
ui/src/router/index.ts

This pr is a staging pr for the `Variables` feature.
It contains the following prs (which were reviewed individually):
- https://github.com/PrefectHQ/prefect/pull/9057
- https://github.com/PrefectHQ/prefect/pull/9066
- https://github.com/PrefectHQ/prefect/pull/9068
- https://github.com/PrefectHQ/prefect/pull/9086
- https://github.com/PrefectHQ/prefect/pull/9104
- https://github.com/PrefectHQ/prefect/pull/9110

`Variables`

---

docs/concepts/storage.md

Concept->Storage docs didn't include Bitbucket storage

Adds bitbucket to supported Prefect flow code storage types

---

MANIFEST.in

The current MANIFEST only includes YAML files at the top level of the `recipes` directory.  This fixes it to look within subdirectories.

Include yaml files within subdirs

---

src/prefect/cli/project.py

Fixes the path logic within the CLI - the manifest file is fine.

Fix CLI path for recipes

---

RELEASE-NOTES.md

Add 2.10.1 Release Notes

---

flows/deployment_storage.py
src/prefect/deployments.py

Adds integration test to #9138

Add integration test for deployment with storage block

---

docs/api-ref/prefect/artifacts.md
mkdocs.yml

Adds artifacts to API ref docs

Adds artifacts to api-ref

---

src/prefect/server/api/artifacts.py
src/prefect/server/models/artifacts.py
tests/server/api/test_artifacts.py
tests/server/models/test_artifacts.py

OSS implementation of: https://github.com/PrefectHQ/nebula/pull/4321

Add deployment and flow filters to `/artifacts/filter` and `/artifacts/latest/filter` routes

---

docs/api-ref/prefect/cli/project.md
mkdocs.yml
src/prefect/cli/root.py
tests/cli/test_project.py

- Touches up some flags on the `prefect deploy` CLI command
- exposes `prefect project` CLI group in API reference docs
- removes ambiguous flags from `prefect deploy` command

Deploy touch ups

---

src/prefect/server/models/artifacts.py

Fix apply artifact collection filter

---

RELEASE-NOTES.md
docs/overrides/main.html

prepare 2.10.3 for release

---

src/prefect/cli/root.py
tests/cli/test_project.py

This PR allows for deployment.yaml files that contain only partial keys (or are empty!) - this allows users to edit these files freely without concern for breaking their deploy.
**cc:** @jamiezieziula 

Allow for partial deployment.yaml files

---

docs/concepts/work-pools.md

add polling interval info to agent and worker docs

---

.github/workflows/python-tests.yaml

Debugging like https://github.com/PrefectHQ/prefect/pull/9239

Pin pip version in python tests to 23.0.1

---

mkdocs.insiders.yml
mkdocs.yml

One caveat is that the "copy to clipboard" button works, but is still copying everything -- this block from the [Docker deployment guide](https://deploy-preview-9259--prefect-docs-preview.netlify.app/guides/deployment/docker/):
gets copied as:
```
$ prefect deployment build ./log_flow.py:log_flow -n log-flow-docker -sb s3/log-test -ib docker-container/log-tutorial -q test -o log-flow-docker-deployment.yaml
Found flow 'log-flow'
Successfully uploaded 4 files to s3://bucket-full-of-sunshine/flows/test
Deployment YAML created at
'/Users/terry/prefect-tutorial/log-flow-docker-deployment.yaml'.
```
I think there was some work to remove the `$` but looks like it [hasn't been merged yet](https://github.com/PrefectHQ/prefect/pull/9204), so this may be expected behavior
- If no issue exists and …

Add documentation edit button

---

src/prefect/workers/base.py
tests/events/instrumentation/test_events_workers_instrumentation.py

This includes some refactoring of the events methods on the base worker and updates worker flow run cancellation to emit an event when the cancellation is complete.
```json
{
"event": "prefect.worker.cancelled-flow-run",
"related": [
{
"prefect.resource.id": "prefect.work-pool.cd90d075-aade-4931-97d4-2af6fcb2fd4d",
"prefect.resource.name": "process-pool",
"prefect.resource.role": "work-pool"
},
{
"prefect.resource.id": "prefect.flow-run.2bf9d4a5-1df4-4207-8f6b-dd18931302a3",
"prefect.resource.name": "eta4-piscis-austrini-cluster",
"prefect.resource.role": "flow-run",
"prefect.infrastructure.identifier": "prefect.local:19242"
}
],
"resource": {
"prefect.version": "2.10.4+8.g8b09660c77",
"prefect.resource.id": "prefect.worker.process.my-worker",
"prefect.worker-type": "process", …
```

Emit cancelled-flow-run event when worker cancels a flow run

---

ui/package-lock.json
ui/package.json
ui/src/pages/FlowRun.vue

This PR bumps the `prefect-ui-library` dependency and makes the Flow Run Page full width.
When a flow hasn't started yet:
When a flow has started:

make flow run page full width

---

RELEASE-NOTES.md

Touchup release notes from last couple versions

---

RELEASE-NOTES.md

2.10.5 Release Notes

---

mkdocs.insiders.yml
mkdocs.yml

Remove duplicate features

---

docs/community/index.md
docs/concepts/artifacts.md
docs/concepts/logs.md

Make small docs fixes

---

docs/host/index.md

fix rendering of cloud feature list

---

ui/package-lock.json
ui/package.json
ui/src/pages/FlowRun.vue

This brings back the "Parent Flow Run" by bumping the `prefect-ui-library` dependency to latest and makes the Logs tab visible to pending flow runs again (pending flow runs can actually have logs in certain instances).
Resolves #9300 

bring back logs to flow run page

---

ui/package-lock.json
ui/package.json
ui/src/pages/FlowRun.vue

Reverts PrefectHQ/prefect#9309
This PR was merged with a bad `package-lock.json` file. Reverting so I can redo it with a clean one.

Revert "bring back logs to flow run page"

---

src/prefect/_internal/concurrency/services.py
src/prefect/_internal/concurrency/threads.py
tests/_internal/concurrency/test_services.py
tests/_internal/concurrency/test_threads.py

Closes https://github.com/PrefectHQ/prefect/issues/9275
See discussion in the linked issue for context on the bug.

Ensure services are drained on global loop shutdown

---

ui/src/pages/FlowRun.vue

This returns the "Logs" tab on the Flow Run page for pending flow runs, since they can actually have logs before the flow has begun.

show logs on pending flow run pages

---

src/prefect/_internal/concurrency/services.py

Helpful for understanding if service failures are important :)

Display number of pending items on service failure

---

.github/workflows/issue-bot.yaml

This is not as useful as I had hoped

Remove automation that assigns in-progress label on assignment

---

ui/package-lock.json
ui/package.json

Adds the vue-charts dependency to work with the `prefect-ui-library`'s peer dependency requirement, and the requirement that [this import statement](https://github.com/PrefectHQ/prefect/blob/main/ui/src/main.ts#L8) be satisfied.

add vue-charts dependency

---

ui/package-lock.json
ui/package.json
ui/src/components/FlowRunGraphs.vue
ui/src/pages/FlowRun.vue

This PR bumps the `prefect-ui-library` dependency and adds a component for handling the flow run graph and the accompanying selection panel on this level.

use decoupled timeline and panel on the flow run page

---

ui/package-lock.json
ui/package.json

Updates to latest prefect-ui-library and vue-charts. This gets vue-charts off of the magic 0 semver

UI: Update vue-charts

---

src/prefect/engine.py
tests/test_tasks.py

Closes https://github.com/PrefectHQ/prefect/issues/9340

Fix bug where tasks were not called when debug mode was enabled

---

ui/src/pages/TaskRun.vue

Adds an artifacts tab to the task run page, linking to the artifact generated by that task run (and the containing collection)

Feature: Add artifacts to task run page

---

RELEASE-NOTES.md

Add 2.10.6 release notes

---

.github/ISSUE_TEMPLATE/config.yml

When creating issues, direct people to report security issues via our Bug Bounty program, which includes a private mailing list.

Add a link to bug bounty program info

---

requirements-dev.txt

There was an ImportError raised during the build because Netlify forces Python 3.8 (no newer version is supported there):
```
6:54:15 AM: ImportError:
6:54:15 AM: IPython 8.13+ supports Python 3.9 and above, following NEP 29.
6:54:15 AM: IPython 8.0-8.12 supports Python 3.8 and above, following NEP 29.
6:54:15 AM: When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
6:54:15 AM: Python 3.3 and 3.4 were supported up to IPython 6.x.
6:54:15 AM: Python 3.5 was supported with IPython 7.0 to 7.9.
6:54:15 AM: Python 3.6 was supported with IPython up to 7.16.
6:54:15 AM: Python 3.7 was still supported with the 7.x branch.
6:54:15 AM: See IPython `README.rst` file for more information:
6:54:15 AM:     https://github.com/ipython/ipython/blob/main/README.rst
```
This …

Pin IPython to 8.12 when running with Python 3.8

---

docs/integrations/contribute.md

This fixes the 'Prefect Integration template' link so it points to https://github.com/PrefectHQ/prefect-collection-template#quickstart.  I'm guessing the prefect-collection-template repo will be renamed to prefect-integration-template at some point, so I left the name, but lemme know if I should change that too.
You can see an example of the broken link here: https://docs.prefect.io/latest/integrations/contribute/#generate-a-project

Fix 'Prefect Integration template' link

---

src/prefect/cli/deploy.py
tests/cli/test_deploy.py

Older versions of `deployment.yaml` are generated with `schedule: null`. This PR adds a guard against that and updates the tests to more accurately represent the default format of older versions of `deployment.yaml`.
Closes #9371 

Add guard against null schedule in `deployment.yaml`

---

src/prefect/projects/steps/core.py
tests/projects/test_steps.py

This PR adds support for asynchronous `build`, `push`, and `pull` project steps. Previously, project steps could only be synchronous.

Add support for async project steps

---

docs/concepts/index.md

Transpose all concepts to main concept page for nav convenience

add all concepts to landing page

---

src/prefect/server/api/ui/flow_runs.py

Adds a work_pool filter to the api/ui/flow_runs/history route.  This route is used for the flow runs scatter/dot chart on the flow runs page in the UI where we have added a work pool filter. 
Closes #8891 
https://www.loom.com/share/a2c4c68182c9425b9e34233eb9f7d4dd

Add work pools to the ui history flow run route

---

src/prefect/projects/recipes/docker-gcs/prefect.yaml
src/prefect/projects/recipes/docker-git/prefect.yaml
src/prefect/projects/recipes/docker-s3/prefect.yaml

…er-s3
Instead of `null`, now the provided values for `image_name` and `tag` for Docker builds carry through.
Closes #9423

Fix Project recipe image_name and tag templating in docker-git, docker-gcs, and docker-s3

---

src/prefect/cli/deployment.py

Adds additional storage blocks to cli deployment build help description and clarifies that some blocks need to be registered and installed.
Should help avoid confusion as shown in #9363.

Add storage blocks to cli `deployment build` help description 

---

docs/concepts/work-pools.md

This `Additional Resources` section is intended to address FAQs for Prefect Concepts. Ideally, we want these FAQs to live in our documentation as opposed to Discourse.

Add `Additional Resources` Section to Work Pools, Workers, & Agents page

---

RELEASE-NOTES.md

Add UI to RELEASE-NOTES.md

---

docs/concepts/index.md

update broken link in concepts index

---

netlify.toml
netlify/edge-functions/amplitude.ts

This adds a proxy that Amplitude can use to send analytics via our Netlify CDN. We do not yet have Amplitude installed, so this will not be active.

Add Amplitude proxy edge function

---

docs/overrides/main.html

Update announce bar for 2.10.7

---

tests/test_filesystems.py

Add test for trailing slash enforcement

---

docs/concepts/projects.md

Fixes `name` description in `deployment.yaml` reference

Fix `name` description in `deployment.yaml` reference

---

RELEASE-NOTES.md

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.10.8/RELEASE-NOTES.md#release-2108)

Add release notes for 2.10.8

---

docs/concepts/tasks.md

mitigate confusion around task-level vs. flow-level concurrency config

add tip about flow run level concurrency

---

.github/workflows/python-tests.yaml

feat: python test runners

---

RELEASE-NOTES.md

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.10.9/RELEASE-NOTES.md#release-2109)

Add release notes for 2.10.9

---

docs/api-ref/rest-api-reference.md
netlify.toml

Allow Redocly in Content-Security-Policy

---

docs/cloud/events.md

fix typo in events.md

---

RELEASE-NOTES.md

Fix typo in 2.10.9 RELEASE-NOTES.md

---

.github/workflows/docker-images.yaml

Avoid caching during image builds to ensure freshness at the cost of slower build times.

Remove image layer caching during builds

---

docs/concepts/work-pools.md

There are a few worker types missing from the Worker Types table (ACI, ECS, GCR). Added those and also hyperlinked to the respective integrations docs for each worker.

Add Additional Worker Types to Work Pools, Workers & Agents Concept Doc.md

---

docs/guides/dask-ray-task-runners.md

fix typo in dask/ray task runner docs

---

src/prefect/server/schemas/filters.py

Add docstrings for all schema filters

---

docs/concepts/tasks.md
docs/concepts/work-pools.md
docs/guides/deployment/developing-a-new-worker-type.md
src/prefect/workers/process.py

Fixes three broken links in the docs (1 of which is in a docstring) 

Fixes three broken links in the docs (1 of which is in a docstring) 

---

README.md
docs/concepts/flows.md
docs/concepts/projects.md

Fix readme typos

---

tests/software/test_conda.py

Supercedes https://github.com/PrefectHQ/prefect/pull/9589

Skip `test_unmocked_retrieval_succeeds` conda test

---

src/prefect/logging/handlers.py
tests/test_logging.py

Closes https://github.com/PrefectHQ/prefect/issues/9597

Fix deadlock when logging is overriden from an asynchronous context

---

flows/worker.py
src/prefect/cli/worker.py

Now that collection loading is deferred, we need to load collections before determining which worker class to start. Added an integration test to very that collection workers are correctly loaded.

Load collections prior to starting worker

---

RELEASE-NOTES.md

Add a few more items to the 2.10.10 release notes

---

flows/worker.py

Stream output during worker integration test subprocess calls

---

.gitignore
docs/contributing/overview.md

9638 add docs about how to build documentation locally

---

flows/worker.py
src/prefect/cli/work_pool.py

Remove check for 'prefect-agent' worker type in integration test

---

docs/cloud/connecting.md
docs/cloud/events.md
docs/cloud/organizations.md
docs/cloud/users/roles.md

Typo fixes

---

docs/tutorial/first-steps.md

Fix typo in first-steps.md

---

docs/concepts/artifacts.md

Docs: Add tip on artifact keys

---

docs/concepts/infrastructure.md

Changed the image parameter description from `tag` to `name`

Updated description of image parameter of DockerContainer

---

docs/api-ref/server/index.md
docs/concepts/variables.md
docs/host/index.md

change Prefect server capitalization

---

ui/package-lock.json
ui/package.json
ui/src/pages/WorkPoolCreate.vue

Adds new work pool creation wizard and bumps the prefect-ui-library version along with other required dependencies.

Adds work pool creation wizard

---

docs/getting-started/installation.md

Remove "Upgrading from Prefect Beta" section of Installation page.

Remove "Upgrading from Prefect Beta" section of Installation page

---

ui/package-lock.json
ui/package.json
ui/src/pages/FlowRunCreate.vue

Implementation of https://github.com/PrefectHQ/prefect-ui-library/pull/1447

Inconsistent flow run parameters when creating a new flow run or editing a deployment

---

src/prefect/server/services/cancellation_cleanup.py

Open source duplicate of https://github.com/PrefectHQ/nebula/pull/4726

Improve cancellation cleanup service iteration over subflow runs

---

src/prefect/cli/dev.py
src/prefect/cli/server.py
tests/cli/test_dev.py
tests/cli/test_server.py

Closes https://github.com/PrefectHQ/prefect/issues/9290

Fix bug where "uvicorn" could not be found when the server was started from an unloaded virtual environment

---

RELEASE-NOTES.md

Draft of release highlights

---

ui/src/pages/FlowRun.vue

Closes https://github.com/PrefectHQ/prefect/issues/9739

404 if flow run id is invalid or if flow run is missing

---

docs/concepts/tasks.md

Removes unused import in example.
Closes #9750

Removes unreferenced requests import in 'real-world example'

---

docs/guides/index.md

Add state change hooks to guides overview page

---

docs/tutorial/first-steps.md

Fixed 'dicionary' typo so that it says 'dictionary'.

Fix typo in flows and tasks tutorials section first-steps.md

---

docs/concepts/tasks.md

Update tasks.md to reference common params and link to all params

---

ui/src/components/ContextSidebar.vue

Re-adds the top-level deployment nav item

Chore: Add deployment nav item to back to context menu

---

src/prefect/settings.py

Creates an experimental flag for the workspace dashboard.

Create `ENABLE_WORKSPACE_DASHBOARD` experiment

---

ui/package-lock.json
ui/package.json
ui/src/components/ContextSidebar.vue
ui/src/maps/featureFlag.ts
ui/src/pages/Dashboard.vue
ui/src/router/index.ts
ui/src/types/flagResponse.ts

implementation of https://github.com/PrefectHQ/prefect-ui-library/pull/1461 and https://github.com/PrefectHQ/prefect-ui-library/pull/1462

Add `dashboard` feature flag and menu item

---

src/prefect/workers/base.py
tests/events/instrumentation/test_events_workers_instrumentation.py

Reverts https://github.com/PrefectHQ/prefect/pull/9702
We determined that we do not need these quite yet

chore: remove worker `poll.*` events

---

docs/concepts/logs.md

Add an example of using the `PREFECT_LOGGING_EXTRA_LOGGERS` setting.

Add extra loggers example

---

RELEASE-NOTES.md

[Preview](https://github.com/PrefectHQ/prefect/blob/release-2.10.12/RELEASE-NOTES.md#release-21012)

Add release notes for 2.10.12

---

src/prefect/engine.py

Adds missing underscores to name == main help string.

Fixes name equals main help string

---

docs/cloud/automations.md

Fixes broken link and Prefect server reference in automations.md

---

src/prefect/infrastructure/container.py

Fixes broken link to docker guide in API docs

---

.github/workflows/python-tests.yaml

chore: use regular test runners on merge

---

docs/api-ref/index.md

Add missing url in API docs

---

docs/cloud/automations.md

Changed flow.tags to flow_run.tags as discussed during onboarding call with Matt.

Update automations.md with flow_run.tags

---

RELEASE-NOTES.md

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-2.10.13/RELEASE-NOTES.md)

Add release notes for 2.10.13

---

docs/cloud/webhooks.md
src/prefect/cli/cloud/webhook.py
tests/cli/test_cloud.py

so we're consistent with other CLI command groups, like `workspace ls`
followup to #9874 
relates to https://github.com/PrefectHQ/nebula/issues/4817

chore: split up webhook get and ls commands

---

src/prefect/engine.py

Documents the latest and greatest behavior in the engine.
Preview at https://deploy-preview-9924--prefect-docs-preview.netlify.app/api-ref/prefect/engine/#prefect.engine--engine-process-overview

Add new documentation to the engine

---

docs/cloud/automations.md

Adds note to Automations docs explaining multiple `match_related` syntax.

Adds note explaining multiple match_related syntax

---

docs/guides/testing.md

updating tense to make the list consistent for testing.md

---

src/prefect/server/api/server.py
src/prefect/server/api/ui/__init__.py
src/prefect/server/api/ui/task_runs.py
tests/server/api/ui/test_task_runs.py

This ports the `/dashboard/counts` endpoint from Cloud to support the upcoming workspace dashboard work.
Closes #9902 

Port `/dashboard/counts` endpoint

---

src/prefect/cli/deployment.py
src/prefect/client/orchestration.py
src/prefect/events/schemas.py

This adds information about any related automations to the output of `prefect
deployment inspect`, only if the client is a Prefect Cloud client.  If there are
no automations, the list will be empty.  When using a self-hosted client, there
will be no `automations` key.
```
$ prefect deployment inspect logtastrophe/logtastrophe-triggered
{
'id': '91a8e6e7-8d3e-45e1-89fc-1eb1e270c333',
'created': '2023-06-13T21:09:38.908159+00:00',
'updated': '2023-06-13T21:09:38.906460+00:00',
'name': 'logtastrophe-triggered',
...
'automations': [
{
'name': 'logtastrophe-triggered__automation_1',
'description': '',
'enabled': True,
'trigger': {
'match': {},
'match_related': {},
'after': set(),
'expect': {'any.old.thing'},
'for_each': set(),
'posture': Posture.Reactive,
'threshold': 1,
'within': …
```

Adding any related automations to `prefect deployment inspect`

---

netlify.toml

tested that /ui/notifications now redirects.

Adds notifications page redirect to docs

---

ui/package-lock.json
ui/package.json
ui/src/pages/FlowRuns.vue
ui/src/pages/Flows.vue

bump prefect-ui-library

---

src/prefect/projects/steps/core.py
tests/projects/test_steps.py

As a result of #9860, some deployment steps will raise deprecation warnings if called via the old name or module. This PR updates the mechanism that runs deployment steps to surface these warnings to the user.
Example output:

Print deprecation warnings emitted by deployment steps

---

docs/concepts/deployments-ux.md
docs/tutorial/deployments-ux.md
src/prefect/deployments/recipes/azure/prefect.yaml
src/prefect/deployments/recipes/docker-azure/prefect.yaml
src/prefect/deployments/recipes/docker-gcs/prefect.yaml
src/prefect/deployments/recipes/docker-git/prefect.yaml
src/prefect/deployments/recipes/docker-s3/prefect.yaml
src/prefect/deployments/recipes/docker/prefect.yaml
src/prefect/deployments/recipes/gcs/prefect.yaml
src/prefect/deployments/recipes/git/prefect.yaml
src/prefect/deployments/recipes/local/prefect.yaml
src/prefect/deployments/steps/utility.py
tests/cli/test_project.py
tests/deployment/test_base.py

Updates recipes to use the new functionality of collections deployment steps.

Updates recipes to remove projects references

---

RELEASE-NOTES.md

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-2.10.14/RELEASE-NOTES.md
)

Add release notes for 2.10.14

---

RELEASE-NOTES.md

Add missing PR to release notes 2.10.14

---

RELEASE-NOTES.md

Fixes a small typo in the title of the deployments UX section. 

Fix typo in RELEASE-NOTES.md

---

src/prefect/deployments/steps/__init__.py
src/prefect/deployments/steps/pull.py
tests/deployment/test_steps.py

Updates import and body of `git_clone_project` to fix workflows that use `git_clone_project`.

Fixes use of deprecated `git_clone_project`

---

RELEASE-NOTES.md

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-2.10.15/RELEASE-NOTES.md)

Add release notes for 2.10.15

---

docs/tutorial/flows.md
docs/tutorial/tasks.md

WIP changes to flows and tasks section of tutorials

[WIP] Tutorial: flows and tasks

---

docs/cloud/index.md

Updating the events section & removed the TK image reference. Added hyperlink to events page and screenshot of events page.

Update events section for cloud docs index.md

---

netlify.toml

These redirects don't appear to be working on the docs site. Based on the other redirects, I think these need a `status = 301` to work.

Add status to redirects

---

docs/cloud/webhooks.md

For rotate use the rotate cli command
The docs say use `toggle` to rotate a webhook.  I think that should be `rotate`. 
@chrisguidry or @WillRaphaelson - for info/to check my correction is correct!

Fix typo in webhook docs

---

src/prefect/cli/work_queue.py
tests/cli/test_work_queues.py

closes https://github.com/PrefectHQ/prefect/issues/8626

Add option to specify work queue priority during creation from cli

---

src/prefect/cli/_prompts.py
src/prefect/cli/deploy.py
tests/cli/test_deploy.py

This PR refactors the logic in the `prefect deploy` command responsible for determining which deployment configurations to use when deploying flows and how CLI options are applied to existing deployment configurations. This PR aims to increase readability and make future changes to `prefect deploy` easier.
This PR makes **no changes to the tests** except a small tweak to an existing error message to ensure that all pre-existing functionality is maintained.
The key change in this PR is the introduction of two helper functions: `_pick_deploy_configs` and `_apply_cli_options_to_deploy_config`.
- `_pick_deploy_configs` encapsulates the logic for determining which deploy configs to use when deploying flows. This significantly reduces the complexity of the `deploy` command by making the choice …

Refactors `prefect deploy` dispatch

---

RELEASE-NOTES.md

[Rendered](https://github.com/PrefectHQ/prefect/blob/1b138a4324dea79d251be787778b8a7d3f1497f5/RELEASE-NOTES.md)

Release 2.10.16

---

docs/concepts/deployments-ux.md

Fix broken link in deployments UX page

---

docs/tutorial/deployments.md

Add question marks to headers and standardize spacing

Add question marks to headers and standardize spacing

---

src/prefect/client/schemas/schedules.py
src/prefect/server/schemas/schedules.py

This is a very minor change and should be excluded from release notes if possible.
This copies changes from prefect.client.schemas.CronSchedule to prefect.server.schemas.CronSchedule, and also fixes a minor typo (recieved -> received).
Related to: #10006, #10007

Synchronize changes to CronSchedule server schema

---

tests/cli/test_project.py

`test_project_init` covers the same ground.

Remove redundant deployment ux test

---

docs/tutorial/index.md

Small typo on tutorial index

---

RELEASE-NOTES.md

Add draft release notes for 2.10.17

---

docs/cloud/events.md

Including links to the Webhooks documentation from the Events documentation.

---

.github/CONTRIBUTING.md
.github/pull_request_template.md

* Add reference to contributor guidelines
* Add checklist item to configure redirects as needed

Update pull request template

---

docs/getting-started/installation.md

Remove duplicate line in installation.md

---

docs/tutorial/deployments.md

See rendered page preview [here](https://deploy-preview-10069--prefect-docs-preview.netlify.app/tutorial/deployments/).

Fix non-rendering graph and admonition in tutorial/deployments.md

---

docs/tutorial/deployments.md

Simply deployment description

---

src/prefect/cli/deploy.py
tests/cli/test_deploy.py

This adds support for deployment triggers to the `prefect deploy` command. Defining triggers in the prefect.yaml will result in automations being created in Prefect Cloud. A warning will be shown if you have triggers defined but are not using Cloud. 
Closes #10046 

Add support for deployment triggers to `prefect deploy`

---

docs/tutorial/flows.md

Replaces two instances of absolute links with relative links in the flows section of the tutorial.

Fixes tutorial links

---

docs/guides/debugging.md
docs/guides/index.md
docs/guides/troubleshooting.md
mkdocs.yml

This PR adds a new guide that covers common Prefect troubleshooting practices. These represent issues that come up often in conversations with users. The aim is not to be comprehensive, but rather to touch on the most common issues and give us a reference point to share with users. Assuming the PR is accepted, I imagine we'll want to build on this guide over time.

Adds troubleshooting guide to docs

---

ui/package-lock.json
ui/package.json

This PR bumps the UI library and design packages to latest. Changes include a fix for a crypto reference that was causing the UI to crash in unsecured deployments and various bugfixes and style updates.

Chore: library and design updates

---

docs/guides/index.md

fix ACI name in guides/index.md

---

src/prefect/deployments/recipes/docker-azure/prefect.yaml
src/prefect/deployments/recipes/docker-gcs/prefect.yaml
src/prefect/deployments/recipes/docker-git/prefect.yaml
src/prefect/deployments/recipes/docker-s3/prefect.yaml
src/prefect/deployments/recipes/docker/prefect.yaml

The Docker-based recipes currently set `push` on `build_docker_image` to `True`, but that field has been deprecated in favor of the `push_docker_image` step. This PR updates the Docker-based recipes to use the new `push_docker_image` step.
Closes https://github.com/PrefectHQ/prefect/issues/10089

Update Docker-based `prefect init` recipes to use `push_docker_image` step

---

src/prefect/deployments/base.py
tests/cli/test_deploy.py

Fixes incorrect saving of `push` and `pull` steps as `build` steps.

Fix saving of `pull` and `push` step deployment configuration

---

docs/concepts/settings.md
docs/guides/deployment/helm-worker.md

Several users and Slack mentioned that finding these values could be difficult - the context was in using a worker with Kubernetes Helm chart.

Show how to find Prefect Cloud Account ID and Workspace ID

---

RELEASE-NOTES.md

I've removed a bunch of trivial docs PRs
Corrects one header in a previous release.
@WillRaphaelson I've adding the highlight section for you to fill out.

Add 2.10.18 Release Notes

---

docs/concepts/blocks.md

This documents the change made in #9932 and closes #9785 

Add deleting blocks section to docs

---

src/prefect/blocks/core.py

Adds python code block to load function in blocks.
Closes #10095 

Adds code block to blocks core load function doc string

---

.github/workflows/windows-pull-request.yaml
.github/workflows/windows-tests.yaml

* Allow windows tests to be run manually via workflow_dispatch
* Run windows tests in pull requests where the workflow is modified, to allow us to test changes to the workflow
* Add Python 3.10 to the test matrix
* Add build concurrency limit settings to cancel in-progress builds on pull requests
* Fix a typo in package installation
Related to #6625

Fix Windows tests in CI

---

requirements.txt

Prefect is not yet compatible with Pydantic v2, and there are backward-incompatible changes requiring migration, so pin our requirements to v1 only for the time being.
Closes: #10143

Pin pydantic to v1 for now

---

src/prefect/deployments/steps/pull.py
tests/deployment/test_steps.py

Add credentials block support for `git_clone` step

---

docs/cloud/events.md

In the introduction at https://docs.prefect.io/2.10.18/cloud/events/, the link `event feed` will redirect to the page itself and not the actual `Event feed` section.
This makes the link redirect to the relevant section instead 😊

Correct link in events.md

---

docs/cloud/webhooks.md

remove disclaimer that ui is on the roadmap

---

RELEASE-NOTES.md

[Preview](https://github.com/PrefectHQ/prefect/blob/release-notes-2.10.19/RELEASE-NOTES.md#release-21019)

Add release notes 2.10.19

---

mkdocs.yml

fix indent in mkdocs.yml

---

RELEASE-NOTES.md

2.10.20 Release Notes

---

docs/getting-started/installation.md

The first item and the last item in the list are the same. The duplicate can be removed for better readability.

remove the duplicate listing

---

docs/cloud/automations.md

Link wasn't going anywhere.
Thanks for raising @prefectcboyd and pointing to docs @dylanbhughes.

Update link to API docs in automations.md

---

ui/src/components/ContextSidebar.vue
ui/src/maps/featureFlag.ts
ui/src/router/index.ts
ui/src/types/flagResponse.ts

This makes the Dashboard the root forward route, removes it's feature flag conditional and cleans up the frontend feature flag usage.

enable dashboard for general audience

---

ui/package-lock.json
ui/package.json
ui/src/components/FlowStats.vue
ui/src/pages/Dashboard.vue
ui/src/pages/Flow.vue

Adds stats to the Flow details page and moves details from the well to a tab:
(the graph's are only black like that on local)

add stats on flow details

---

src/prefect/workers/process.py

removing-worker-beta

---

tests/agent/test_agent_run_cancellation.py
tests/infrastructure/test_process.py
tests/test_flows.py

Trying to get our status badges to actually mean something - marking a few brittle tests as flaky.

Mark a few tests as flaky

---

RELEASE-NOTES.md

Add 2.11.1 release notes

---

tests/cli/test_start_agent.py

Flaky behavior seen here: https://github.com/PrefectHQ/prefect/actions/runs/5615654035/job/15216375002

Add flaky marker for another flaky test

---

src/prefect/context.py

Added a missing quotation mark in the docstring of `tags` context manager in `src.prefect.context`.

Add missing quotation mark in docstring

---

netlify.toml

Good catch on the needed redirect by Reuter.

Add redirect to quick start in netlify.toml

---

src/prefect/deployments/deployments.py

nit: `run_deployment` docstring rendering

---

docs/guides/push-work-pools.md
mkdocs.yml

Adds docs for adding an azure container instance push work pool.  I'm adding notes based on my experience setting up azure and would welcome a review/input from @prefectcboyd who I consider to be much more of an azure expert. It's likely that I go into a bit much detail on navigating the azure portal/UI. 
I run into an issue when serving the docs locally because my version of pymdown extensions doesn't like our addition of `pymdownx.tabbed`.  Taking out `pyndownx.tabbed`  from our config lets me serve the docs but the tabs we're using for the push work pools guide don't work. Equally, it seems our netlify build isn't working either.  So I'm leaving this as draft until we can properly check the deploy preview and make sure tabs are correctly displayed. 
Example - but the tabs aren't …

ACI push pool guide

---

RELEASE-NOTES.md

Draft release notes for 2.11.2

---

docs/cloud/cloud-quickstart.md
mkdocs.yml

I don't think we intended to remove the cloud quickstart from the docs all together. The page still exists. This PR puts it in the nav under Cloud. It also makes the video image render better by removing the TOC for that page.

Add cloud quickstart to nav menu and drop toc to make video fit

---

docs/concepts/deployments-ux.md
docs/concepts/deployments.md
docs/guides/deployment/push-work-pools.md

Fix deployments typos

---

docs/concepts/index.md
docs/guides/index.md
mkdocs.yml

Elevate Guides in nav menu and remove migration guide from guides nav section and index page.
@billpalombi, I didn't delete the migration page all together, just took it out of nav and index, please let me know if you'd prefer I delete.

Elevate Guides in nav and remove migration guide from nav 

---

.github/ISSUE_TEMPLATE/1_general_bug_report.yaml
.github/ISSUE_TEMPLATE/2_ui_bug_report.yaml
.github/ISSUE_TEMPLATE/config.yml
docs/cloud/index.md
docs/community/index.md
docs/guides/index.md
docs/index.md

* Update links to scheduling time with a Prefect Product Advocate to add UTM tags
* Update issue templates to indicate that community support does not carry an SLA, and remind users to file a case via support

Update notes about community support

---

ui/package-lock.json
ui/package.json
ui/src/pages/Dashboard.vue

Carrying @pleek91 's dashboard time span polling fix in, in the same manner as [he did in nebula](https://github.com/PrefectHQ/nebula-ui/pull/3122/files).

implement time span fix for the dashboard

---

docs/guides/deployment/storage-guide.md

Update the storage guide for Bitbucket to add x-token-auth:

---

docs/concepts/index.md

Fixes a small typo in the docs. 

Fix typo in artifacts docs

---

docs/tutorial/flows.md
docs/tutorial/index.md
docs/tutorial/tasks.md

This PR includes fixes to issues I spotted going through the prefect tutorial documentation 

Docs tutorial fixes

---

docs/cloud/connecting.md

This updates / includes the necessary URL's that need to be whitelisted in a restricted access environment.
* auth.workos.com
* ocsp.pki.goog/s/gts1d4/OxYEb8XcYmo
* app.prefect.cloud
* api.prefect.cloud

Update connecting.md to include whitelisting URLs

---

src/prefect/infrastructure/kubernetes.py
tests/infrastructure/test_kubernetes_job.py

Backports the fix for https://github.com/PrefectHQ/prefect-kubernetes/pull/85 to agents + k8s infrastructure

Handle spot instance eviction in Kubernetes Infrastructure Block

---

docs/contributing/overview.md

Remove Windows support experimental note from contributing docs page

---

docs/concepts/flows.md

fixing example viz flow

---

.github/workflows/docker-images.yaml

Hardcode docker workflow for a prod release

---

.github/workflows/docker-images.yaml

Reverts PrefectHQ/prefect#10439
If our jobs fail again in this way we can revisit the workflow logic and harden it a bit

Revert "Hardcode docker workflow for a prod release"

---

src/prefect/deployments/recipes/gcs/prefect.yaml

closes https://github.com/PrefectHQ/prefect/issues/10441

fix typo in gcs recipe

---

docs/concepts/flows.md

Update warning block to mention worker in title

---

docs/concepts/deployments.md

This PR clarifies the relationship between variables in the deployment process.

Clarify deployments variables

---

docs/guides/deployment/kubernetes.md

Splits a few commands over multiple lines for readability.

Update kubernetes guide for readability

---

docs/contributing/overview.md
docs/guides/host.md
docs/integrations/contribute.md

This PR fixes 4 small typos in the docs.
Links to typos in public docs site:
1. https://docs.prefect.io/2.11.4/guides/host/#:~:text=send%20email%20alerts%20from%20Prefect%27s%20serves%20based%20on%20automation%20triggers.
2. https://docs.prefect.io/2.11.4/contributing/overview/#:~:text=We%20us%20the%20mkdocs%2Dmaterial%20theme
3. https://docs.prefect.io/2.11.4/integrations/contribute/#:~:text=We%20welcome%20contributors!%20You%20can%20help%20contribute%20blocks%20and%20integrations%20by%20following%20these%20steps.%20We%20welcome%20contributors!%20You%20can%20help%20contribute%20blocks%20and%20integrations%20by%20following%20these%20steps.
4. https://docs.prefect.io/2.11.4/integrations/contribute/#:~:text=creating%20a%20integration%20to%20do%20so
- If no issue exists and your change is …

Fix a few typos in docs

---

docs/guides/deployment/storage-guide.md
src/prefect/client/schemas/objects.py
src/prefect/server/schemas/actions.py
src/prefect/server/schemas/core.py
tests/cli/test_deploy.py
tests/server/api/test_workers.py
tests/server/schemas/test_actions.py
tests/server/schemas/test_core.py

Closes https://github.com/PrefectHQ/prefect/issues/10458
We fixed a bug allowing misconfigured base job templates to be created for work pools. After fixing that bug, some users cannot read their work pools due to a misconfigured base job template. This PR moves validation to only work pool update and creation to unblock work pool reads. Users must fix their misconfigured base job templates to update a work pool with a misconfigured base job template.

Update base job template validation to only run on work pool update and creation

---

README.md

Update README header image

---

docs/guides/deployment/kubernetes.md

Resolves https://github.com/PrefectHQ/platform/issues/4486

Create GCP specific guide references for deploying a GKE cluster to host a worker

---

docs/concepts/agents.md
docs/concepts/deployments-block-based.md
docs/concepts/infrastructure.md

Fix typos in documentation admonitions

---

src/prefect/server/schemas/schedules.py
tests/server/schemas/test_schedules.py

Reverting this PR until I can verify that it's working as intended.

Revert "fix DST bug with `CronSchedule` (#10472)"

---

docs/guides/index.md

Fix broken moving data guide link

Fix broken moving data link

---

mkdocs.yml

- [ n/a] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

Add block and agent-based deployments back to left nav

---

docs/overrides/partials/header.html
docs/stylesheets/extra.css

Closes docs issue https://github.com/PrefectHQ/docs/issues/335
- [ n/a] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed
Colors and icon match prefect.io:
No hover:
Hover:

add cloud button link to header of docs

---

.github/workflows/integration-tests.yaml

Adds `2.11` to the integration test matrix

add 2.11 integration tests

---

ui/src/pages/Artifact.vue
ui/src/pages/ConcurrencyLimit.vue
ui/src/pages/Deployment.vue
ui/src/pages/Flow.vue
ui/src/pages/FlowRun.vue
ui/src/pages/TaskRun.vue
ui/src/pages/WorkPool.vue
ui/src/pages/WorkPoolQueue.vue

Updates all implementations of p-tabs to use a query param for the selected tab. This way tab state is preserved when refreshing the page and we could link to specific tabs if needed.

Add the selected tab in the url

---

docs/guides/settings.md
src/prefect/settings.py

This PR increases the default request timeout from 30s to 60s. When this timeout is set lower than or equal to to server side timeouts, it is possible for the server to be actively processing a request while the client raises a timeout.
Mitigates read errors as seen in these issues: 
- https://github.com/PrefectHQ/prefect/issues/10263
- https://github.com/PrefectHQ/prefect/issues/8084

Increase default request timeout

---

ui/src/pages/Deployment.vue

Removes the no work queue warning from the deployment page as it's less relevant now and is causing false toasts for deployments created by flow.serve()
@cicdw for info

Remove the no work queue warning from the deployment page

---

src/prefect/cli/flow.py
src/prefect/client/schemas/schedules.py
src/prefect/deployments/runner.py
tests/client/schemas/test_schedules.py

Updates `RunnerDeployment.construct_schedule` to no longer be a public method. Creates a new `construct_schedule` utility that previous consumers of `RunnerDeployment.construct_schedule` can use.

Refactors schedule creation for serve functionality

---

src/prefect/cli/flow.py
src/prefect/flows.py
src/prefect/runner.py
tests/test_runner.py

Adds a starting message to `serve()` to mirror the starting message in `Flow.serve()` and `prefect flow serve`. Prints a list of deployments being served, a sample `prefect deployment run` command with a placeholder, and a link to the deployments page in the Prefect UI if the Prefect UI URL is available.

Adds starting message to `serve()`

---

docs/overrides/main.html

Remove blank menu bar at top of docs

---

requirements.txt

per #10567 , we need to pin `anyio` to less than `4.0.0` to avoid breaking changes while a fix is developed

pin to anyio < 4

---

docs/api-ref/prefect/deployments/runner.md
docs/api-ref/prefect/runner.md
mkdocs.yml
src/prefect/deployments/runner.py
src/prefect/flows.py
src/prefect/runner.py

Put serve utilities into API reference

---

docs/guides/index.md

Of of these descriptions is not like the others.

Shorten push work pools description

---

docs/concepts/flows.md
docs/concepts/index.md

Adds a section to the Flows concept page on `.serve` - I also need to add to the other concept pages but wanted to break it down for review.

Add concept section for Flows

---

RELEASE-NOTES.md

[Preview](https://github.com/PrefectHQ/prefect/blob/release-2.12.0/RELEASE-NOTES.md)

Add release notes 2.12.0

---

src/prefect/events/clients.py
tests/events/test_cloud_events_client.py

We received a surprising report from a customer that they were seeing the
`AssertionError` indicating that we were trying to `_emit` an event, but the
websocket was `None`.  It's not clear from the available information how this
might happen, but I could reproduce it by emulating a failure to cleanly
disconnect during a reconnection attempt.  This leaves the websocket as `None`,
which would trigger the assertion failure.
This changes `_emit` so that we can perform an initial reconnection attempt if
the client finds itself without a websocket.

Recovering from a failure to cleanly disconnect a websocket in the Events client

---

ui/package-lock.json
ui/package.json

This reverts the graphs repo to v1. V2 was causing problems for the flow run timeline, issue [here](https://github.com/PrefectHQ/nebula/issues/5489).

revert graphs to v1

---

src/prefect/server/database/interface.py

Remove deprecated `OrionDBInterface`

---

src/prefect/client/orchestration.py

Remove deprecated `OrionClient`

---

src/prefect/agent.py

Remove deprecated `OrionAgent`

---

docs/cloud/users/api-keys.md

Remove link to nowhere in api-keys.md

---

docs/concepts/automations.md

fixing work pool schema link

---

docs/guides/deployment/kubernetes.md

Spotted by @serinamarie in a previous PR.
We now show the advanced instructions under the Advanced Settings note.

Chore: Fix Advanced Settings formatting for Kubernetes docs

---

src/prefect/runtime/flow_run.py
src/prefect/runtime/task_run.py
tests/runtime/test_flow_run.py
tests/runtime/test_task_run.py

Adds support for flow run / task run `run_count` to the runtime.
Closes https://github.com/PrefectHQ/prefect/issues/10633.
```python
@flow
def my_flow():
hello_world()
@task(persist_result=True, result_storage_key="{flow_run.id}_{flow_run.run_count}_{task_run.id}_{task_run.run_count}.json")
def hello_world(name: str = "world"):
return f"hello {name}"
my_flow()
```
```bash
In [7]: my_flow()
10:25:03.169 | INFO    | prefect.engine - Created flow run 'pompous-alpaca' for flow 'my-flow'
10:25:03.264 | INFO    | Flow run 'pompous-alpaca' - Created task run 'hello_world-0' for task 'hello_world'
10:25:03.265 | INFO    | Flow run 'pompous-alpaca' - Executing 'hello_world-0' immediately...
10:25:03.318 | INFO    | Task run 'hello_world-0' …
```

Add `prefect.runtime.flow_run.run_count` and `prefect.runtime.task_run.run_count`

---

.github/workflows/python-tests.yaml

* Increase threshold from 3 failures to 4 failures
* Add more metadata fields
* Add count of failing jobs to make notifications more reliable
Resolves: #10687

Update failure notifications

---

docs/cloud/index.md

Add error summaries to cloud index

Add error summaries to cloud index

---

tests/infrastructure/test_process.py

Closes #10704 
This test often flaked with `PermissionError: [Errno 1] Operation not permitted`
what seems important to test is that we attempt to call `os.kill` and that we raise `InfrastructureNotFound` when we can't find the PID.

fix flaky test `test_process_kill_no_matching_pid`

---

docs/concepts/events.md
docs/guides/variables.md

Fixes two broken links

---

src/prefect/cli/dev.py

Overview of the rationale for this fix is provided in issue https://github.com/PrefectHQ/prefect/issues/10389.
Closes https://github.com/PrefectHQ/prefect/issues/10389.

On UI build, make paths relative rather than absolute. 

---

docs/concepts/flows.md

Minor fix to add sentence capitalization to this section header, in line with other sections

Fix inconsistent capitalization

---

docs/tutorial/workers.md

Update workers tutorial to fix non-rendering diagram and link

---

.github/workflows/helm-chart-release.yaml

This 
* is a replacement for https://github.com/PrefectHQ/prefect-helm/pull/234
* resolves https://github.com/PrefectHQ/prefect-helm/issues/233
The versions must not be zero-padded since helm chart versions must be semantic versions and semantic versioning forbids zero-padding.
See https://github.com/PrefectHQ/prefect-helm/issues/233 for a more detailed description.

fix: do not zero-pad helm chart version

---

src/prefect/server/api/workers.py
src/prefect/server/models/workers.py
tests/server/api/test_workers.py
tests/server/models/test_workers.py

This PR adds `/count` routes for work pools

Add work pool counts

---

docs/guides/prefect-deploy.md

Adds documentation for: https://github.com/PrefectHQ/prefect/pull/10772

Add documentation for pattern matching in `prefect deploy`

---

docs/guides/deployment/storage-guide.md

Fix warning in deployment storage guide documentation

---

docs/tutorial/tasks.md

Small change in a variable name from a code snippet in the tutorial, in the tasks section.
Avoids the following error when trying the proposed code:
`NameError: name 'repo' is not defined`

Fix example in tasks concept documentation

---

ui/package-lock.json
ui/package.json
ui/src/pages/FlowRuns.vue

Implementation of https://github.com/PrefectHQ/prefect-ui-library/pull/1777 which removes the `useFlowRunsInfiniteScroll` composition. 
Needs https://github.com/PrefectHQ/prefect-ui-library/pull/1777

Implement useFlowRuns composition

---

docs/tutorial/deployments.md

Adds link to Docker guide in next steps section. Thanks to @taylor-curran for suggesting.

Add link to Docker guide in deployments.md

---

RELEASE-NOTES.md

[Preview](https://github.com/PrefectHQ/prefect/blob/release-notes-2.13.3/RELEASE-NOTES.md)

Release notes 2.13.3

---

src/prefect/client/schemas/actions.py
src/prefect/client/schemas/objects.py
src/prefect/server/database/migrations/versions/postgresql/2023_09_25_121806_8167af8df781_remove_flow_run_id_requirement_from_task_run.py
src/prefect/server/database/migrations/versions/sqlite/2023_09_25_121806_8167af8df781_remove_flow_run_id_requirement_from_task_run.py
src/prefect/server/database/orm_models.py
src/prefect/server/models/task_runs.py
src/prefect/server/orchestration/core_policy.py
src/prefect/server/orchestration/rules.py
src/prefect/server/schemas/actions.py
src/prefect/server/schemas/core.py
tests/server/api/test_task_runs.py

This PR lays out the backend work necessary to allow for task runs without a flow run.
It does not include any client-side changes to make autonomous task runs a first class concept.

Allow task runs without a flow run

---

docs/concepts/work-pools.md

Closes #10847
- [n/a ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

Add GCP Vertex AI worker to work-pools.md

---

src/prefect/settings.py
tests/test_settings.py

Closes https://github.com/PrefectHQ/prefect/issues/10754.
Tested with the UI accessed from a different domain/port than server's `PREFECT_SERVER_API_HOST`.
Before, `404`: API server not reachable as it uses `PREFECT_SERVER_API_HOST` which doesn't translate well from client-side (any results seen were `preflight` i.e. cached):
After, `200`: the API server is reachable:

Default PREFECT_UI_API_URL to relative path /api

---

flows/deployment_run.py
flows/deployment_storage.py
src/prefect/infrastructure/base.py
src/prefect/runner.py
src/prefect/workers/base.py
tests/infrastructure/test_base.py
tests/test_runner.py
tests/workers/test_base_worker.py
tests/workers/test_process_worker.py

The non-dash-delimited format for UUIDs produced by `uuid.uuid4().hex` does not pass validation in some instances, most notably when the `{id:uuid}` specifier is used on a FastAPI route. This causes flow run IDs fetched from the `prefect.runtime` module to sometimes contain this format without dashes. This PR updates all instances where `PREFECT__FLOW_RUN_ID` is set to use the dash-delimited format.
Closes #10851 

Update `PREFECT__FLOW_RUN_ID` environment variable to dash-delimited UUID format

---

docs/guides/deployment/storage-guide.md

Change docker guide link to point to worker tutorial since the docker guide no longer shows docker-based storage.

Change docker guide link to point to worker tutorial

---

docs/concepts/flows.md

Documentation for `flow.from_source`

---

RELEASE-NOTES.md

[rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.13.5/RELEASE-NOTES.md)

Release notes for 2.13.5

---

docs/api-ref/index.md
docs/cloud/index.md
docs/community/index.md
docs/concepts/index.md
docs/guides/index.md
docs/index.md
docs/integrations/index.md
docs/tutorial/index.md

Removes icons from side nav for improved readability - @brandonreid's suggestion.
Screenshot of navbar after.

Remove icons from side nav for improved readability

---

docs/stylesheets/extra.css

Apply CSS suggestions to improve docs style from @brandonreid. 
SS from local preview:

Update CSS for docs 

---

docs/concepts/flows.md

Add documentation for experimental enhanced cancellation

---

RELEASE-NOTES.md

Fix link in release notes for comparing changes between 2.13.5 and 2.13.6.

Docs: Update typo for 2.13.5-2.13.6 diff

---

docs/guides/using-the-client.md
mkdocs.yml

Fixes broken link, adjusts heading capitalization, and spells out small numbers to match style guide.

Using the client guide updates

---

docs/cloud/connecting.md

and replace with `api.prefect.cloud`

chore: update docs to remove `api-beta.` references

---

docs/tutorial/deployments.md

Capitalize `Docker` in tutorial

---

RELEASE-NOTES.md

Exactly what's on the tin!
Adding release notes for 2.13.7 release.

Adds release notes for 2.13.7

---

src/prefect/cli/worker.py
tests/cli/test_worker.py

Clarify CLI prompt message for missing integration library for worker

---

docs/tutorial/workers.md

Update work pools and workers tutorial to use `flow.deploy`

---

src/prefect/deployments/runner.py
tests/fixtures/database.py
tests/runner/test_runner.py

Previously, `deploy` would exit on the first failed deployment so that none of the later deployments would be applied. This PR adds logic to gather failed deployments and display the error to the user.
Example output from a `deploy` run that was partially successful:

Update `deploy` to gather and display errors for failed deployments

---

docs/guides/deployment/developing-a-new-worker-type.md

Standardize heading capitalization in developing-a-new-worker-type.md

---

docs/guides/docker.md

Update Docker guide to mention image builds with prefect.yaml and `flow.deploy`

---

docs/guides/deployment/kubernetes.md

Update Kubernetes guide to mention and link to Python `deploy` creation method

---

RELEASE-NOTES.md

Prepares release notes for 2.14.0 - the release of `prefect-client`. 

Release notes 2.14.0

---

.github/workflows/prefect-client-publish.yaml
.github/workflows/prefect-client.yaml
client/build_client.sh
client/client_flow.py

This PR makes two enhancements to our `prefect-client` builds:
1. Preserves the project `README.md` by only copying the `client/setup.py` file into the parent directory during builds
2. Uses a `prefect-client` specific project scoped token for publishing to PyPI

prefect client build updates

---

RELEASE-NOTES.md

Release notes for 2.14.1 -- I'm not including notes related to GH Actions since those aren't really user facing.

Release notes 2.14.1

---

RELEASE-NOTES.md

Release notes 2.14.2

---

tests/runner/test_runner.py

The  `test_runner_can_cancel_flow_runs` test is failing intermittently due to timing.  This marks the test as flaky.  Issue to address more fully (if needed) is in https://github.com/PrefectHQ/prefect/issues/11048
`

mark test_runner_can_cancel_flow_runs as flaky

---

src/prefect/client/schemas/objects.py
src/prefect/client/schemas/sorting.py
src/prefect/server/api/block_documents.py
src/prefect/server/database/migrations/versions/postgresql/2023_10_30_075026_cef24af2ec34_add_block_type_name_to_block_document.py
src/prefect/server/database/migrations/versions/sqlite/2023_10_30_075026_cef24af2ec34_add_block_type_name_to_block_document.py
src/prefect/server/database/migrations/versions/sqlite/2023_10_30_103720_22ef3915ccd8_index_and_backfill_block_type_name.py
src/prefect/server/database/orm_models.py
src/prefect/server/models/block_documents.py
src/prefect/server/schemas/core.py
src/prefect/server/schemas/sorting.py
tests/server/api/test_block_documents.py
tests/server/models/test_block_documents.py

This PR adds `block_type_name` to the block_document table, facilitating efficient sorting by block_type_name, name necessary for the UI.
Closes https://github.com/PrefectHQ/prefect/issues/6915

Allow sorting block documents by block_type_name, name

---

src/prefect/cli/dev.py

Fixes a bug inadvertantly introduced by https://github.com/PrefectHQ/prefect/pull/10390 that means that refreshing a page in the UI from a details page in the UI or trying to open the UI from a non-dashboard link opens only a blank page.  Resolves https://github.com/PrefectHQ/prefect/issues/10807
@danielhstahl - I'm afraid this reverts your PR - tagging you here as I want you to be aware that you may encounter issues in your JupyterHub build if you update to the next prefect version without manually setting PREFECT_UI_SERVE_BASE. 

Reset PREFECT_UI_SERVE_BASE to enable page refresh loading for non dashboard pages

---

docs/guides/deployment/push-work-pools.md

Update push-work-pools to mention concurrency

---

.github/workflows/prefect-client.yaml
.github/workflows/python-tests.yaml

This PR updates the "Verify prefect-client build" workflow trigger to run when there are changes to `requirements-client.txt`. This should help us verify dependency updates that dependabot submits.

ft: runs client build workflow on reqs.txt updates

---

ui/package-lock.json
ui/package.json

Updates UI packages

---

docs/guides/global-concurrency-limits.md

The introduction to the global concurrency docs made me think that they are only for limiting task run concurrency when in fact they can be used more globally.  This is a small change to make it more clear they can be used for limiting concurrency for flow runs and other operations. 
@bunchesofdonald - I'd love your review to make sure I am not misrepresenting anything here! 

Update global concurrency docs to be more global

---

src/prefect/server/api/block_documents.py
src/prefect/server/models/block_documents.py
tests/server/api/test_block_documents.py
tests/server/models/test_block_documents.py

This PR adds an API route to count block documents, necessary for UI pagination work in https://github.com/PrefectHQ/prefect/issues/6915

Count blocks

---

src/prefect/deployments/runner.py

Improve tag handling in `DeploymentImage` with `parse_image_tag`

---

docs/guides/deployment/push-work-pools.md

This is probably the easiest stumbling block to encounter, so adding a warning about image architecture.

Add warning to push pool guide

---

src/prefect/client/schemas/objects.py
src/prefect/deployments/runner.py
src/prefect/flows.py
tests/fixtures/database.py
tests/runner/test_runner.py

Ensure client avoids image builds for managed work pools

---

ui/package-lock.json
ui/package.json
ui/src/components/FlowRunGraphs.vue

We've re-written the flow run graph from scratch for maximum performance. Rendering of large graphs should be much more stable in v2 and we've added a few new features including a much requested dependency layout!
- Grid based dependency layouts
- Comparative duration layout
- Cached tasks appear on the graph
- Faster layouts
- Optimized api endpoint for fetching graph data
- Horizontal scale controls
Needs: https://github.com/PrefectHQ/prefect-ui-library/pull/1850

Improved flow run graph with new dependency layout

---

src/prefect/server/schemas/responses.py
src/prefect/settings.py
tests/_internal/compatibility/test_experimental.py
tests/server/test_app.py
ui/src/maps/featureFlag.ts
ui/src/types/flagResponse.ts
ui/src/utilities/permissions.ts

We added a feature flag to the UI for deployment status in https://github.com/PrefectHQ/prefect-ui-library/pull/1848. This PR updates the OSS UI to support this flag and defaults it to enabled so that deployment status continues to work in the UI as expected. This PR also increases the threshold for when a deployment is considered unhealthy to match the threshold in Cloud.

Add setting to ensure deployment status continues to display in the UI

---

tests/workers/test_base_worker.py

test failed on merge to main [here](https://github.com/PrefectHQ/prefect/actions/runs/6813545443/job/18528390019)

mark flaky worker test

---

src/prefect/runner/storage.py
tests/runner/test_storage.py

Closes https://github.com/PrefectHQ/prefect/issues/11135

Fix errors when using `GitRepository` with a private repo

---

.github/workflows/python-tests.yaml

Only run tests on a merge to main if Python, dependency files, or GHA workflows changed.

Only run tests for Python changes

---

docs/cloud/users/audit-log.md

Fix css class typo in audit-log.md

---

netlify.toml

Update mkdocs material pin

---

docs/guides/index.md
mkdocs.yml

Adds the recently no-longer-alpha Terraform Provider to guides and cleans up guides navigation.

Add Terraform Provider to guides and cleanup guides navigation

---

scripts/generate-release-notes.py

The output format for `gh auth status --show-token` seems to have changed so I updated the regex to pull the token automatically. This at least saved me some copy-pasting everytime I wanted to generate the notes.

Patches a few bugs in release notes script

---

docs/cloud/cloud-quickstart.md
docs/cloud/connecting.md

Adds information about GitHub to auth related cloud documentation.

Add github information to auth related cloud docs

---

docs/tutorial/workers.md

Small typo

---

ui/package-lock.json
ui/package.json

Update ui-library and vue-compositions

---

ui/package-lock.json
ui/package.json

Updates axios and ui-library to latest to get axios on a version without a security alert.

Update ui-library and axios

---

docs/tutorial/workers.md

Remove extraneous items and standardize terminal code formatting.

Update tutorial workers.md

---

ui/src/pages/FlowRun.vue

Removes an old watch that was used to make sure the flow run tab reset to logs when going to a subflow run from a run page. That watch is no longer needed but was setting the tab to 'logs' when a user was navigating away from the flow run page to the flow page.  
Previous behaviour:
https://github.com/PrefectHQ/nebula-ui/assets/40272060/ad46871a-7087-4dbd-b4e8-cebc110cfa51
With fix (also shows subflow run correctly setting to the logs tab):
https://github.com/PrefectHQ/nebula-ui/assets/40272060/d38731e4-0fc4-4cd0-904f-1c0b2675a0a6

Fix routing to the flow page from a flow run

---

scripts/generate-release-notes.py

This extends ability to generate script to the VSCode integrated terminal :)

Update token regex in release notes generation script for VSCode compatibility

---

src/prefect/deployments/runner.py
src/prefect/settings.py
tests/_internal/compatibility/test_experimental.py
tests/conftest.py
tests/events/instrumentation/test_events_workers_instrumentation.py
tests/infrastructure/test_base.py
tests/runner/test_runner.py
tests/server/test_app.py
tests/workers/test_base_worker.py

This PR updates the default settings to enable enhanced cancellation. This means agents and workers will start a runner in the flow run execution environment and the runner will be responsible for stopping cancelled flow runs.

Enable enhanced cancellation by default

---

RELEASE-NOTES.md

[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.14.5/RELEASE-NOTES.md)

Add release notes 2.14.5

---

ui/package-lock.json
ui/package.json
ui/src/pages/Deployment.vue
ui/src/pages/Flow.vue
ui/src/pages/WorkPool.vue
ui/src/pages/WorkPoolQueue.vue
ui/src/pages/WorkQueue.vue

OSS implementation of https://github.com/PrefectHQ/prefect-ui-library/pull/1881

Implement flow run filtered list and deployment table changes

---

docs/guides/deployment/daemonize.md
docs/guides/deployment/kubernetes.md
docs/guides/docker.md

Match title capitalization in several guides

---

ui/.vscode/settings.json
ui/package-lock.json
ui/package.json
ui/src/pages/FlowRun.vue

When viewing subflows of a flow run filtering by state was not working. Also the filters were not persisting to the url which meant changing tabs or refreshing the page would reset the filters.
Needs: PrefectHQ/prefect-ui-library#1882

Fix subflow filters not working and not persisting

---

.github/CODEOWNERS

Fixes an issue where I wasn't getting notifications on `/ui` PRs

Chore: Add @znicholasbrown to UI CODEOWNERS

---

mkdocs.yml

Fixes a change with mike 2.0 for docs versioning as a fallback.

Update mike for latest versioning in mkdocs.yml 

---

docs/guides/deployment/push-work-pools.md
docs/guides/deployment/serverless-workers.md

This PR clarifies some information around creating an ACI Push Work Pool.

Update Azure Container Instance guide to reflect current Azure Portal interface and Prefect UI

---

RELEASE-NOTES.md

Release notes for 2.14.7

---

docs/guides/deployment/serverless-workers.md

Fix broken docs link in serverless worker documentation

---

RELEASE-NOTES.md

Release notes for 2.14.8 - a fast follow to 2.14.7 to fix an issue with the GIthub actions workflow. 

Release notes for 2.14.8

---

docs/guides/index.md
mkdocs.yml

Makes the subheading encompass all its elements as discussed in https://github.com/PrefectHQ/prefect/pull/11256#issuecomment-1828818682
Thanks @serinamarie! 

Update guide category title to "work pools"

---

src/prefect/infrastructure/provisioners/__init__.py
src/prefect/infrastructure/provisioners/ecs.py
tests/infrastructure/provisioners/test_ecs.py

Adds the ability to configure an AWS account with all the necessary prerequisites to use a ECS push pool via the `--provision-infra` flag. 
Using the `--provision-infra` flag will trigger the CLI to configure the following resources:
- Create an IAM user
- Create an IAM policy granting access to the necessary resources in AWS to manage ECS tasks
- Assign the created policy to the created user
- Generate credentials for the user
- Save an `AwsCredentials` with the generated credentials
- Create an ECS cluster to run ECS tasks on
- Create a VPC to run ECS tasks in. VPC creation includes the necessary subnets, route table, security group, and internet gateway
After running `prefect work-pool create`, users can deploy and run flows in the created work pool without any additional …

Add provision infrastructure support for ECS push work pools

---

RELEASE-NOTES.md

2.14.9 release notes

---

docs/guides/deployment/serverless-workers.md

Add Google Cloud Run V2 option to Serverless guide

---

docs/concepts/work-pools.md

Improves discoverability. 
This is in response to a question in Community Slack.
- [n/a ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed

Add `work queues` tag to work pools concept page

---

src/prefect/cli/worker.py
src/prefect/client/orchestration.py
src/prefect/utilities/services.py

Adds additional logs to `critical_service_loop` to help with debugging an issue where a worker will silently stop polling for runs. Also increases the backoff to worker's loop services to increase their resiliency to network failures.

Adds additional debug logging to `critical_service_loop`

---

docs/cloud/users/teams.md

This PR makes a small update to the verbiage around Teams + SCIM + service accounts. @prefectcboyd was working with a client and suggested this bit could be clearer.

Clarify SCIM + service accounts handling

---

src/prefect/workers/utilities.py

Fixes flaky tests caused by in place dictionary modification

---

src/prefect/runner/server.py

modularize inject util

---

docs/guides/prefect-deploy.md
src/prefect/deployments/runner.py
src/prefect/settings.py
src/prefect/utilities/dockerutils.py
tests/docker/test_image_parsing.py
tests/runner/test_runner.py

Add a new setting, `PREFECT_DEFAULT_DOCKER_BUILD_NAMESPACE`, allowing users to define the default Docker namespace for the current profile. When building a Docker image, this setting will be used to tag the built image if a registry and/or organization is not provided.
Note: This will require an update to `prefect-docker` to allow this setting to be used with the YAML-based deployment API.
Set `PREFECT_DEFAULT_DOCKER_BUILD_NAMESPACE`:
```bash
perfect config set PREFECT_DEFAULT_DOCKER_BUILD_NAMESPACE="gcr.io/my-project"
```
Deploy a flow with an image pushed to the default registry:
```python
def my_flow(name: str = "world"):
print(f"Hello {name}! I'm a flow!")
my_flow.deploy(
name="my-deployment", …
```

Add setting to configure a default Docker namespace for image builds

---

docs/guides/upgrade-guide-agents-to-workers.md

Updates the 'Upgrade from agents to workers' guide to include references to `flow.deploy` and some of the new tooling to aid in migration. Includes examples of common patterns when using `Deployment.build_from_flow`.

Update agent upgrade guide to include `flow.deploy` and examples

---

docs/guides/moving-data.md

Update moving data guide 

---

docs/guides/deployment/push-work-pools.md
docs/guides/prefect-deploy.md
src/prefect/deployments/runner.py
src/prefect/infrastructure/provisioners/ecs.py
src/prefect/settings.py
src/prefect/utilities/dockerutils.py
tests/docker/test_image_parsing.py
tests/infrastructure/provisioners/test_ecs.py
tests/runner/test_runner.py

This PR adds an `ECRRepositoryResource` to the `ElasticContainerServicePushProvisioner` which creates an ECR repository for users to push flow images to when using their work pool. It also adds an `ExecutionRoleResource` to create an execution role granting ECS tasks access to ECR for image pulls.
Provisioning infrastructure will also set `PREFECT_DEFAULT_DOCKER_BUILD_NAMESPACE` to the registry URL of the created repository. As long as this is set, users will not need to provide the registry URL when building Docker images as part of their deployment process.
Note: Each ECR repository only supports one image name. This PR adds the ability to print next steps to guide the user through this. Users will need to create additional ECR repositories via the AWS UI or CLI if they want to use …

Add the ability to provision an ECR repository

---

src/prefect/client/orchestration.py
src/prefect/engine.py
src/prefect/server/api/flow_runs.py
tests/server/api/test_flow_runs.py
tests/test_engine.py

This is the OSS side of https://github.com/PrefectHQ/nebula/pull/6417. Adds run input validation and handling to resume flow runs.

Validate run input when resuming flow runs

---

ui/src/pages/Deployments.vue

Updates the deployments table to add run activity and separate out the deployment and flow name

Enhancement: Update the deployments table

---

ui/src/pages/Dashboard.vue

Just removes the max width from the input

Fix date range width on the dashboard

---

docs/guides/index.md
mkdocs.yml

To help differentiate Guides from other docs sections such as Concepts, this PR expands the name to "How-to Guides". 
This is based on a newer user's feedback.
This new naming is the same naming convention used in the [diataxis framework.](https://diataxis.fr/)

Change `Guides` title to` How-to Guides` in the docs

---

docs/guides/deployment/push-work-pools.md

Adds a section to the Push work pools guide on the provision-infra sub command 

---

docs/guides/deployment/push-work-pools.md
src/prefect/infrastructure/provisioners/ecs.py
tests/infrastructure/provisioners/test_ecs.py

Adds at missing `work_pool_name` argument to sample code associated with the ECS provisioner.

Adds missing `work_pool_name` argument to example code

---

docs/guides/managed-execution.md

Update search for managed-execution.md

---

docs/guides/deployment/push-work-pools.md

Adds minimum permissions required for ECS and ACI provisioners. The minimum required permissions for the Cloud Run provisioner is in https://github.com/PrefectHQ/prefect/pull/11399.

Add documentation for required permissions for ECS and ACI provisioners

---

docs/guides/deployment/push-work-pools.md

Adds line to infra provisioning prerequisites to upgrade to the latest CLI version

---

RELEASE-NOTES.md

2.14.11 release notes

---

src/prefect/infrastructure/provisioners/container_instance.py
tests/infrastructure/provisioners/test_container_instance.py

Fixes validation on custom identity names. We were restricting to alphanumeric only, but dashes and underscores are valid for identity names.
Fixes a bug where the role assignment for the created identity would fail due to latency on within Azure. An updated command mitigates this latency. From the `az` CLI help:
```
--assignee-principal-type     : Use with --assignee-object-id to avoid errors caused by
propagation latency in AAD Graph.  Allowed values:ForeignGroup,
Group, ServicePrincipal, User.
```

Fix prompt and role assignment in `ContainerInstanceProvisioner`

---

docs/guides/index.md
docs/guides/moving-data.md
mkdocs.yml

Based on conversation with @taylor-curran and @EmilRex. 

Rename moving data guide

---

docs/tutorial/workers.md

Graph [is not being rendered](https://docs.prefect.io/latest/tutorial/workers/) due to spacing. 

Fix workers graph rendering

---

ui/.vscode/settings.json
ui/package-lock.json
ui/package.json
ui/src/pages/Dashboard.vue

This PR, combined with some fixes from upstream dependencies, will allow the dashboard header to fluidly respond to the varying sizes of the tags and date range inputs and respond to the viewport width.

Fix: dashboard header to be responsive

---

docs/concepts/agents.md

Added a troubleshooting note #11459
Closes #11459 

Add troubleshooting instructions for agents.md re: Issue #11459

---

docs/concepts/flows.md

Tiny typo fix spotted while reading the docs. 

Fix typo in flows.md

---

docs/guides/managed-execution.md
docs/guides/prefect-deploy.md
docs/stylesheets/extra.css
src/prefect/workers/process.py

Minor updates to formatting and work pool docs to reflect recent changes

---

src/prefect/flows.py
tests/test_flows.py

Closes https://github.com/PrefectHQ/prefect/issues/11483

Fix error when deploying a remotely loaded flow with options

---

docs/concepts/tasks.md

Documentation follow-up to https://github.com/PrefectHQ/prefect/pull/10671
[Preview](https://deploy-preview-11490--prefect-docs-preview.netlify.app/concepts/tasks/#custom-retry-behavior)

Add documentation on conditional retries

---

docs/getting-started/quickstart.md

Fix Quickstart typo

---

RELEASE-NOTES.md

Adds human-in-the-loop details to the latest release notes.

Add human-in-the-loop notes

---

RELEASE-NOTES.md

Causing PRs to fail static analysis. Example here: https://github.com/PrefectHQ/prefect/actions/runs/7289869012/job/19865414193?pr=11500#step:5:30

Fix spelling error in release notes

---

src/prefect/flows.py
tests/test_flows.py

Closes #11513
```python
@flow
def my_flow():
print("hi")
my_flow.deploy(
name="has-a/slash",
work_pool_name="my-work-pool",
image="my_registry/my_image:my_image_tag",
build=False,
)
```
`ValueError: Invalid deployment name 'has-a/slash'. Deployment names cannot contain forward slashes.`

Fail `.deploy` if deployment name contains `/`

---

src/prefect/flows.py
tests/test_flows.py

Reverts PrefectHQ/prefect#11516

Revert "Fail `.deploy` if deployment name contains `/`"

---

docs/guides/creating-human-in-the-loop-workflows.md

Remove redundant word typo

---

docs/concepts/flows.md
src/prefect/engine.py

Add conditional pause example to flow documentation

---

ui/package-lock.json
ui/package.json

Updating both at once because the minimum version of prefect-design in ui-library was bumped.

Update prefect dependencies

---

.github/pull_request_template.md

Adds `maintenance` as a label prompt in PR template

Update PR template to include `maintenance` label

---

src/prefect/runner/runner.py

Another spot where we're seeing failing tests.

Use `_register_signal` utility in runner

---

RELEASE-NOTES.md

[Preview](https://github.com/PrefectHQ/prefect/blob/release-notes-2.14.13/RELEASE-NOTES.md)

Release notes 2.14.13

---

.gitignore
src/prefect/server/api/collections_data/views/aggregate-worker-metadata.json

Commit most recent version of worker metadata to repo

---

docs/concepts/automations.md

removing automations cancel warning

---

docs/guides/docker.md

Fix non-rendering link in Docker guide

---

docs/concepts/deployments.md
docs/concepts/flows.md

- Adds `run_deployment` to the deployment concept doc - hat tip for the need for more documentation to @abrookins 
- Fix link to the API docs for `run_deployment`
- Disambiguates work pools with and without workers in the deployment concept doc

Update deployment and flow concept docs

---

src/prefect/runner/submit.py

This PR adds overloads to `submit_to_runner` to more accurately type the return value. Now if the input `parameters` is a list, the return value will be correctly type checked as a list. If the input is a single dict, the return will be a single UUID. Currently, the return will always be a list or a UUID which can trip up the type checker's analysis and cause false positive.
Before: 
```console
local/autonotask.py:20: note: Revealed type is "Union[uuid.UUID, builtins.list[uuid.UUID]]"
local/autonotask.py:23: note: Revealed type is "Union[uuid.UUID, builtins.list[uuid.UUID]]"
```
After:
```console
local/autonotask.py:20: note: Revealed type is "uuid.UUID"
local/autonotask.py:23: note: Revealed type is "builtins.list[uuid.UUID]"
```
Sample code:
```python
from __future__ import annotations …
```

ft: adds overloads to submit_to_runner

---

src/prefect/runner/submit.py
tests/runner/test_submit.py

assert sync/async context works and restrict callable types

---

docs/concepts/automations.md

Additions and examples for custom triggers for automations.

Automation triggers examples

---

src/prefect/input/run_input.py

Add send/receive documentation to `run_input` module docstring

---

src/prefect/client/orchestration.py
src/prefect/client/schemas/actions.py
src/prefect/client/schemas/objects.py
tests/client/test_prefect_client.py

added functions to interact with the global concurrency limit api using a prefect client (similar to concurrency limit v1 api requests)
added tests for new methods
closes https://github.com/PrefectHQ/prefect/issues/11416
may be the first step before solving https://github.com/PrefectHQ/prefect/issues/10865
Sorry, maybe i am blind but i cannot find a way to add the "enhancement" label to this PR

Prefect client global concurrency limit functions / tests

---

docs/guides/deployment/storage-guide.md
docs/guides/index.md
mkdocs.yml

Fix storage guide links and reference

---

docs/guides/prefect-deploy.md

Fix typo in deploy guide

---

docs/guides/creating-human-in-the-loop-workflows.md

Fixes imports in tshirt example of human-in-the-loop guide.

Fix imports in tshirt example of human-in-the-loop guide

---

docs/guides/creating-human-in-the-loop-workflows.md

Found other spots to add `pause_flow_run`

Add more imports to creating-human-in-the-loop-workflows.md

---

src/prefect/deployments/runner.py
src/prefect/flows.py
tests/runner/test_runner.py

given reasonable user expectation that `.deploy` could be used with `Process` worker, be clear about our recommended alternative

raise helpful error message w .deploy

---

docs/concepts/automations.md

adding incident, metric, and deployment status info to automations docs

adding incident, metric, and deployment status info to automations docs

---

.github/workflows/integration-tests.yaml

Add 2.14 to integrations tests

---

docs/guides/prefect-deploy.md

The repeated line is a description of how to use private git repos

remove duplicate, dangling line in prefect-deploy.md

---

.github/workflows/stale.yml

Rename workflow that identifies stale PRs

---

docs/api-ref/prefect/flow_runs.md
mkdocs.yml
src/prefect/flow_runs.py
tests/test_flow_runs.py

Adds new `flow_runs` module to API reference docs and updates the signature of `wait_for_flow_run` to match the pattern of other functions in the library.

Add API reference documentation for `wait_for_flow_run`

---

docs/guides/deployment/push-work-pools.md
src/prefect/infrastructure/provisioners/__init__.py
src/prefect/infrastructure/provisioners/ecs.py
src/prefect/infrastructure/provisioners/modal.py
tests/infrastructure/provisioners/test_modal.py

Adds a `Provisioner` implementation to configure a Modal push work pool via the Prefect CLI. The provisioner will handle creating a `ModalCredentials` block and configuring the created work pool to use the new block. The provisioner will prompt the user to install `modal` if it is not present and will prompt the user to generate a new token if one is not found in the current Modal configuration.
This PR adds Modal push work pool configuration information to the serverless push work pools guide.

Add provisioner for Modal push work pools

---

RELEASE-NOTES.md

ft: add release notes for 2.14.16

---

tests/client/test_prefect_client.py
tests/input/test_run_input.py

Skip an egregiously flaky test and modify some others to reduce the problematic effects of timing.

Skip and change some flaky tests

---

docs/concepts/flows.md
docs/guides/index.md
mkdocs.yml

resolving links after moved page

resolving links after moved page

---

src/prefect/server/database/interface.py
src/prefect/server/database/migrations/MIGRATION-NOTES.md
src/prefect/server/database/migrations/versions/postgresql/2024_01_22_120615_8cf4d4933848_create_deployment_schedule_and_add_.py
src/prefect/server/database/migrations/versions/sqlite/2024_01_22_120214_265eb1a2da4c_create_deployment_schedule_and_add_.py
src/prefect/server/database/orm_models.py
src/prefect/server/models/deployments.py
src/prefect/server/schemas/actions.py
src/prefect/server/schemas/core.py
src/prefect/server/schemas/filters.py
tests/agent/test_agent_run_cancellation.py
tests/cli/test_project.py
tests/fixtures/database.py
tests/server/models/test_deployments.py

Implements the data modeling for enabling Deployments to have multiple schedules.
Note: This is merging into a feature branch which will then merge to main when the feature is ready.
Related to https://github.com/PrefectHQ/nebula/issues/6706

Implement data modeling for enabling Deployments to have multiple schedules.

---

src/prefect/server/database/interface.py
src/prefect/server/database/migrations/MIGRATION-NOTES.md
src/prefect/server/database/migrations/versions/postgresql/2024_01_22_120615_8cf4d4933848_create_deployment_schedule_and_add_.py
src/prefect/server/database/migrations/versions/sqlite/2024_01_22_120214_265eb1a2da4c_create_deployment_schedule_and_add_.py
src/prefect/server/database/orm_models.py
src/prefect/server/models/deployments.py
src/prefect/server/schemas/actions.py
src/prefect/server/schemas/core.py
src/prefect/server/schemas/filters.py
src/prefect/server/services/scheduler.py
tests/agent/test_agent_run_cancellation.py
tests/cli/test_project.py
tests/fixtures/database.py
tests/server/models/test_deployments.py
tests/server/services/test_scheduler.py

This updates scheduler to look at `Deployment.paused` and `DeploymentSchedules` for scheduling.
Note: This is merging into a feature branch which will then merge to main when the feature is ready.
Related to https://github.com/PrefectHQ/nebula/issues/6706

Update scheduler to look at `Deployment.paused` and `DeploymentSchedules` for scheduling.

---

docs/guides/automations.md

Update automations guide punctuation

---

src/prefect/server/api/collections_data/views/aggregate-worker-metadata.json

manually porting changes from [this PR](https://github.com/PrefectHQ/prefect-collection-registry/pull/343) until [this CI](https://github.com/PrefectHQ/prefect-collection-registry/actions/runs/7633068129) is fixed

update worker metadata view

---

.github/workflows/integration-tests.yaml
src/prefect/client/orchestration.py
src/prefect/client/schemas/actions.py
src/prefect/client/schemas/objects.py
src/prefect/client/schemas/responses.py
src/prefect/server/api/deployments.py
src/prefect/server/models/deployments.py
src/prefect/server/schemas/responses.py
tests/agent/test_agent_run_cancellation.py
tests/client/test_prefect_client.py
tests/server/api/test_deployment_schedules.py
tests/server/api/test_deployments.py
tests/server/models/test_deployments.py

This ports the deployment API changes to OSS.
Note: This is merging into a feature branch which will then merge to main when the feature is ready.
Related to https://github.com/PrefectHQ/nebula/issues/6706

Port deployment API changes to OSS

---

docs/concepts/automations.md

Clarifies that jinja syntax is available in automation actions beyond notification type actions.

Update automations concept doc for jinja templating

---

docs/cloud/incidents.md

Clarify language in incidents doc.

Clarify language in incidents doc intro

---

RELEASE-NOTES.md

add highlight for experimental flow submission to runner webserver

---

RELEASE-NOTES.md

2.14.17 Release Notes

---

docs/cloud/incidents.md

Picks up  @billpalombi's suggested change.

Update incidents docs language 

---

src/prefect/server/api/server.py
src/prefect/settings.py
tests/test_engine.py
tests/test_settings.py

This PR is one way to closes #11618.   The problem is that lists were not hashable which was described here: https://github.com/PrefectHQ/prefect/issues/11618#issuecomment-1887558096.   In scanning settings I didn't see any other settings which had this issue.  That being said, the note also points out that in the future this may change.  
In reviewing settings.py I noticed that environment variables are also cached, but using the text string representations to hash.  This is seen in get_setting_from_env.   Rather than going through and checking each variable and creating special hashing functions, it feels like converting to strings using to_environment_variables and hashing is a simpler solution.  
I also changed a test to verify the list actually flows through the code.
I haven't …

Fix environment variable not accepting lists

---

ui/src/pages/Flow.vue
ui/src/pages/WorkPool.vue

Add a list of related deployments on the Work Pool details page so that users can see all associated deployments with a Work Pool easily.
This also updates the Flow details page to use the `DeploymentsList` component instead of the `DeploymentsTable` component. 

Enhancement: add deployments to work pool details

---

docs/integrations/catalog/prefect-kv.yaml

Update KV integration docs link and author

---

docs/guides/creating-interactive-workflows.md

More interactive flows docs fixes

---

docs/guides/creating-interactive-workflows.md

fix terminal output

---

src/prefect/cli/flow.py
src/prefect/flows.py
src/prefect/runner/runner.py

When we print the output of a served flow/deployment, we present the user a link that will send them to the UI where they can interact with their served process. The link is unclickable and un-copy-pasteable today because the `rich`'s wrapping and `Panel` presentation don't mix well together. This PR removes the `Panel` on outputs that contain links and gets us a wrapped, clickable, copy-pasteable link.
Before:
```
╰─❯ python simple.py
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Your deployments are being served and polling for scheduled runs!                                              │
│                                                                                                                │
│ …
```

Make links in panels clickable

---

docs/guides/creating-interactive-workflows.md

Just a few docs nits, nothing big.

Some nits for interactive flow docs

---

RELEASE-NOTES.md

Release notes for 2.14.20

---

src/prefect/engine.py

it seems this was accidentally left here and is not needed

rm extra `WARNING` log in task runs

---

src/prefect/utilities/asyncutils.py

This PR adds logic to ignore an error if we aren't able to correctly add an event lop garbage collection reference.
Example run with this error https://github.com/PrefectHQ/prefect/actions/runs/7757198583/job/21156169937.

Handle key error in event loop gc

---

tests/test_flows.py

Attempting to address a flaky test. From what I can tell, the goal of this test is to ensure that the flow timeout doesn't wait for the flow to complete before timing out. The flow under test already does _something_ (writes a file) after sleeping (for far longer than the flow's timeout) and then the test asserts that that thing was never done. It also ensures that the flow failed w/ the appropriate timeout message. With these in mind, I don't think it's necessary to clock the flow also other than to provide a guarantee that a timeout of 0.1s ensures the flow invocation takes less than some time. Because this is a non-deterministic assertion and has been creating issues in the test suite for sometime now, this PR removes the timer-based assertions.
- If no issue exists and your change is …

Remove non-deterministic timing assertions from flaky test.

---

tests/public/tasks/test_task_timeouts.py

This PR makes task timeout tests more reliable by removing brittle timing related assertions.
Before these changes I could reliably get at least one of these tests to fail locally. After the changes, 3 runs succeeded in a row locally.

Make task timeout tests less flaky

---

tests/public/flows/test_flow_timeouts.py

Our prior versions of these tests depended on how fast the test runner was,
which led to a significant number of timing flakes here.  The changes here make
these tests deterministic (with `pytest-timeout` as a backstop).
Note: the tests have also changed to acknowledge that we can't currently
interrupt a long-running sleep within a flow.

Making the flow timeout tests deterministic

---

docs/guides/docker.md

Add clarity to Docker tutorial code snippet

---

requirements-dev.txt

This PR takes inspiration from other PRs where we've updated dev dependencies to make it clear lower versions of moto won't work anymore.

ft: be explicit about version reqs

---

tests/server/models/test_orm.py

These tests were expecting that they'd run in under a second, which we can't
always guarantee.  Instead, we'll make sure that lateness falls within the
bounds of the test run (however long that might be).

Make ORM model lateness tests tolerant to slow test runs

---

tests/test_flows.py

I ran all three tests several hundred times without a failure.

De-flaky `tests/test_flows.py`

---

tests/docker/test_image_builds.py

De-flaky `tests/docker/test_image_builds.py`

---

tests/server/api/test_block_documents.py

Remove `@pytest.mark.flaky` from `tests/server/api/test_block_documents.py`. Haven't been able to get this to flake locally via flake-finder and looking at the test, I'd be curious to see a trace from it actually flaking... 

deflake api/test_block_documents.py

---

tests/server/services/test_loop_service.py

This assertion was a little too tight on the timing.  What we want to know is
that the loop service will properly stop while it is sleeping for the next
interval (which is intentionally greatly exaggerated in this test).  Testing
that it was < 1s was too tight for CI

Addressing a timing flake in the loop service tests

---

requirements-dev.txt
src/prefect/testing/standard_test_suites/task_runners.py
tests/cli/test_start_agent.py
tests/cli/test_worker.py
tests/infrastructure/test_process.py
tests/packaging/test_docker_packager.py
tests/runner/test_runner.py
tests/server/api/test_run_history.py
tests/server/models/test_block_schemas.py
tests/server/models/test_concurrency_limits_v2.py
tests/utilities/test_services.py
tests/workers/test_base_worker.py

Removes  all `mark.flaky` decorators and `flaky` as a dependency.

Remove `flaky` and all `mark.flaky` decorators

---

tests/client/test_prefect_client.py

We can't guarantee this is in 1 second, we just want it to be in the past.

fix deployment flake

---

scripts/collections-manager

- add ability to open draft PRs
- skip `DELAY` if `--dry-run`

Tweak collection manager

---

docs/concepts/work-pools.md

Add small blurb to work pools concept doc

Add docs tip on work queue status

---

.github/workflows/python-tests.yaml
src/prefect/server/database/configurations.py

This also adds test legs for SQLAlchemy 1 so we catch issues like this quicker

Type safety in tests between SQLAlchemy 1 and 2

---

RELEASE-NOTES.md

Adds release notes for 2.14.21.

Release notes 2.14.21

---

scripts/collections-manager

merge em all
this will (correctly) no-op if any required status checks are failing or the PR is not approved (without the `--admin` flag, which we do not use here)

add `merge_latest_pr` to collections manager

---

.github/workflows/helm-chart-release.yaml

relates to https://github.com/PrefectHQ/prefect-helm/issues/297
in https://github.com/PrefectHQ/prefect-helm/pull/298, we update the helm chart's versioning schema to include a [pre-release append](https://semver.org/#spec-item-9).  this allows us to create distinct releases that land on the same day
in this repo, we'll change the trigger so that rather than creating a github release/tag in `prefect-helm`, we'll invoke the chart release workflow itself, where the chart version is computed.  this allows us to continue triggering a downstream chart release when `prefect` is released as well as continuing to allow manual chart releases
For …

chore: trigger prefect-helm release via `gh workflow run`

---

docs/concepts/flows.md

Clearer wording about concurrent subflows

---

mkdocs.yml
netlify.toml

Updates syntax.
Builds locally. 
QA'd manually.
Live preview:
https://deploy-preview-11969--prefect-docs-preview.netlify.app/

Updates mkdocs material to latest version 

---

RELEASE-NOTES.md

[RENDERED](https://github.com/PrefectHQ/prefect/blob/release-notes-2.15.0/RELEASE-NOTES.md)

Release notes for 2.15.0

---

docs/guides/big-data.md
docs/guides/ci-cd.md
docs/guides/deployment/serverless-workers.md
docs/guides/global-concurrency-limits.md
docs/guides/host.md
docs/guides/managed-execution.md
docs/guides/moving-data.md
docs/guides/runtime-context.md
docs/guides/state-change-hooks.md
docs/guides/upgrade-guide-agents-to-workers.md
docs/guides/using-the-client.md
docs/guides/webhooks.md

Improves docs formatting consistency and adds some minor content updates

---

src/prefect/deployments/runner.py
tests/runner/test_runner.py

Adds the ability to deploy to a process work pool using `flow.deploy` and `deploy`. Adds checks to ensure that an image isn't used when deploying to a process work pool, but some sort of storage is provided. Includes a message directing users towards `flow.serve` for local development.
Closes https://github.com/PrefectHQ/prefect/issues/11597

Allow deploying to process work pools with `flow.deploy`

---

.github/workflows/integration-tests.yaml
.github/workflows/python-tests.yaml

Adds Prefect 2.15 to the test matrix and removes an outdated Python 3.11 with conda on Docker exclusion and note.

Minor updates to CI tests

---

src/prefect/_vendor/starlette/testclient.py
src/prefect/blocks/notifications.py
tests/fixtures/api.py
tests/server/api/test_pagination.py
tests/server/utilities/test_server.py

Updates client usage to prevent deprecation warnings from `httpx`

Update `AsyncClient` instantiation to fix deprecation warnings

---

tests/docker/test_registry_pushes.py

This test could flake if the test took longer than 1 second to run, or the time
spilled over from one second to the next.  Freezing `pendulum.now` resolves it.

Corrects a timing-dependent test for pushing Docker images

---

ui/package-lock.json
ui/package.json

This PR simply bumps the `prefect-design` and `prefect-ui-library` dependencies to the latest version.

Chore: bump ui dependencies

---

docs/concepts/work-pools.md
docs/guides/prefect-deploy.md

Adds links to overriding job variables guide

---

src/prefect/settings.py
tests/_internal/compatibility/test_experimental.py
tests/server/test_app.py
ui/src/maps/featureFlag.ts
ui/src/types/flagResponse.ts
ui/src/utilities/permissions.ts

Adds an experimental flag for enabling/disabling the enhanced scheduling UI.

Add experimental flag for enhanced scheduling UI

---

requirements-client.txt
requirements.txt
src/prefect/_internal/concurrency/api.py
src/prefect/_internal/concurrency/calls.py
src/prefect/_internal/concurrency/threads.py
src/prefect/engine.py
src/prefect/task_engine.py
tests/conftest.py
tests/test_engine.py
tests/test_flows.py
tests/test_task_server.py
tests/test_tasks.py

This reverts commit 3d4281f989d84aca67f1d27e069826387e99ea8a.
Related to #12053

Revert "Run tasks on the main thread (#11930)"

---

src/prefect/client/orchestration.py
src/prefect/client/schemas/objects.py
src/prefect/deployments/deployments.py
tests/client/test_prefect_client.py
tests/test_deployments.py

Adds support for specifying multiple schedules in a deployment's YAML file.

Support multiple schedules in deployment YAML files

---

docs/concepts/deployments-block-based.md
docs/concepts/deployments.md
docs/concepts/infrastructure.md
docs/concepts/schedules.md
docs/tutorial/deployments.md

Update docs to include information about multiple schedules where appropriate

Update scheduling docs to include information about multiple schedules

---

RELEASE-NOTES.md

Draft of release notes for 2.16.0.

Add release notes for 2.16.0 release

---

src/prefect/settings.py

Closes https://github.com/orgs/PrefectHQ/projects/127/views/1?pane=issue&itemId=54190450
This PR adds a preliminary feature flag for gating access to the upcoming flow run infra overrides feature.

Add feature flag for flow run infra overrides

---

docs/getting-started/quickstart.md
docs/guides/deployment/overriding-job-variables.md
docs/tutorial/flows.md
docs/tutorial/work-pools.md
docs/tutorial/workers.md

Closes #12076
Makes minor updates for consistency in the tutorial and quickstart.
Adds Modal to list of push work pool types.
Clarifies where `httpx` comes from and what it is.

Updates to tutorial and getting started

---

src/prefect/server/api/deployments.py
tests/server/api/test_deployment_schedules.py

This is the OSS side of https://github.com/PrefectHQ/nebula/pull/7053
Related to https://github.com/PrefectHQ/nebula/issues/7047

Clear runs even if deployment is paused, when updating/deleting schedules

---

docs/guides/deployment/kubernetes.md

We had a question about K8s version compatibility, so adding here. cc: @gabcoyne 
Helm chart is tested as part of CD against K8s versions:  
- "1.26.0"
- "1.27.0"
- "1.28.0"
- "1.29.0"

Add minimum K8s version to guides -> kubernetes.md

---

docs/guides/webhooks.md

Closing div was missing a "/".
SS of local fix:

Fix formatting on webhooks page

---

src/prefect/cli/deployment.py

Fix a docstring that refers to `prefect deployment schedule set` instead of `prefect deployment schedule create`.

Fix a docstring

---

src/prefect/settings.py

This PR add the option to silence the `PREFECT_API_URL` warning
closes #10840

Silence PREFECT_API_URL warning 

---

docs/guides/deployment/daemonize.md
docs/guides/prefect-deploy.md
docs/guides/upgrade-guide-agents-to-workers.md

Closes #12119.
- [n/a ] This pull request includes redirect settings in `netlify.toml` for files that are removed or renamed.

Remove tab structure for three docs pages to improve navigation

---

docs/cloud/events.md
docs/guides/automations.md

Adds clarifications and style updates on the events page

---

docs/guides/docker.md

caught it while trying to make my damned docker images work

it's a spelling mistake

---

tests/fixtures/database.py
tests/server/__init__.py
tests/server/api/test_deployment_schedules.py

OSS side of https://github.com/PrefectHQ/nebula/pull/7099

Create `get_server_session` fixture and use it in `test_deployment_schedules.py`

---

.github/workflows/python-tests.yaml

trying to address some timeouts talking to the docker registry - it's not likely to help in all cases, but I'm trying to snuff out any upstream rate limits that might be causing cascading failures

chore: auth into dockerhub for python-tests

---

RELEASE-NOTES.md

patch release to get [this](https://github.com/PrefectHQ/prefect/pull/12151) out

prep release notes for `2.16.2`

---

docs/guides/host.md

I tested the PostgreSQL with Docker hosting instructions and found some opportunities to clarify them.

Update Prefect Server guide to clarify PostgreSQL Docker instructions

---

ui/package-lock.json
ui/package.json
ui/src/components/FlowRunGraphs.vue

Adds the states layer to flow run graph. Note that the layer will not show until the feature flag is enabled for viewing it.
https://github.com/PrefectHQ/prefect/assets/6776415/ded1886b-e24f-460a-beab-9869f3e11128

Enhancement: Add the flow run graph states layer and handle selection

---

docs/concepts/deployments.md

This page doesn't show in search for `run_deployment`, but it's the best page for that keyword search.

Add keyword for search to deployments concept doc

---

src/prefect/server/api/collections_data/views/aggregate-worker-metadata.json

after https://github.com/PrefectHQ/prefect-aws/pull/370, the worker metadata changed slightly
this updates the default template accordingly

update aggregate worker metadata view

---

README.md
client/INFO.md
client/README.md
client/build_client.sh

This PR adds a README that will get published to `prefect-client` on PyPI and properly describes the project. Our [current description on PyPI](https://pypi.org/project/prefect-client/) is not accurate and doesn't motivate the use case we had in mind. This PR makes that description more precise and includes a few examples of capabilities we include today. 
Let me know if there's anything I should add or call out to make this a useful doc!
Closes https://github.com/PrefectHQ/prefect/issues/12124

Add a `prefect-client` README

---

README.md

minor update to language in hero example

---

src/prefect/settings.py
tests/_internal/compatibility/test_experimental.py
tests/server/api/test_deployments.py
tests/server/test_app.py
tests/test_settings.py
ui/src/maps/featureFlag.ts
ui/src/types/flagResponse.ts
ui/src/utilities/permissions.ts

Removes the ENHANCED_SCHEDULING_UI flag and related UI code.
Related to https://github.com/PrefectHQ/nebula/issues/7115

Chore: Remove enhanced scheduling UI flag

---

ui/src/maps/featureFlag.ts
ui/src/pages/DeploymentEdit.vue
ui/src/pages/FlowRunCreate.vue
ui/src/types/flagResponse.ts

Enhanced deployment parameters ui improves support for handling default values, better ux for lists, and improved validation. 
Adds support for
- `Tuple` type parameters
- Lists ui (no longer restricted to json for lists)
- Use json or a workspace variable for any value
- Unified parameter validation (ui validation matches enforced parameter schemas on deployments)

Experimental enhanced deployment parameters UI

---

src/prefect/_internal/concurrency/services.py
src/prefect/_internal/concurrency/threads.py
tests/_internal/concurrency/test_services.py
tests/_internal/concurrency/test_threads.py

Attempts to resolve two memory leaks:
1. `QueueService` instances keep a reference to their asyncio tasks even after shutdown. The problem with this is that the task's context contains a reference to the `EngineContext` we use for a flow run, and _that_ contains references to every task call made during the flow run. As we process runs, these objects accumulate in memory without getting released. This change deletes the asynctio task after the `QueueService` stops, which fixes the leak.
2. `EventLoopThread` instances keep a reference to callbacks that should fire when the thread shuts down. The problem here is that these thread instances stick around and hold onto the calls, which accumulate in memory. After the thread shuts down and we run the callbacks, we don't need references to them, …

Fix two memory leaks

---

docs/guides/ci-cd.md

Adds an advanced example to the CI/CD guide featuring [this](https://github.com/kevingrismore/cicd-example-workspaces) repository.

Add advanced example to CI/CD guide

---

docs/integrations/catalog/prefect-soda-cloud.yaml

This is a super tiny PR to include [prefect-soda-cloud](https://alessandrolollo.github.io/prefect-soda-cloud/) in the integrations catalog 🚀

Added prefect-soda-cloud integration

---

src/prefect/utilities/schema_tools/validation.py
tests/utilities/schema_tools/test_validation.py

We can get multiple errors if we have a hydration error and then we attempt to validate it in some way like checking it's type (which will never pass). This makes sure that we only will surface the hydration error in those cases.

prioritize validation errors

---

RELEASE-NOTES.md

[Preview](https://github.com/PrefectHQ/prefect/blob/release-notes-2.16.3/RELEASE-NOTES.md)

Release notes 2.16.3

---

.github/workflows/python-tests.yaml

chore: revert docker login on python-tests

---

docs/concepts/work-pools.md

Fix formatting in concept -> work-pools.md

---

ui/package-lock.json
ui/package.json

🤖 Beep Boop 🤖 
Update @prefecthq/prefect-ui-library to version 2.6.32.
Release information can be found at https://github.com/prefecthq/prefect-ui-library/releases/tag/2.6.32.

Update @prefecthq/prefect-ui-library to version 2.6.32

---

docs/concepts/states.md

Add `on_running` state change hook to State -> Concepts docs

---

docs/guides/prefect-deploy.md

Fix some argument names in deploy guide

---

RELEASE-NOTES.md

Add a mention for custom flow run state UI handling in release notes.

---

docs/api-ref/server/models/csrf_token.md
mkdocs.yml
src/prefect/server/database/interface.py
src/prefect/server/database/migrations/MIGRATION-NOTES.md
src/prefect/server/database/migrations/versions/postgresql/2024_03_13_111215_7a653837d9ba_create_csrf_token_toble.py
src/prefect/server/database/migrations/versions/sqlite/2024_03_13_111316_bacc60edce16_create_csrf_token_toble.py
src/prefect/server/database/orm_models.py
src/prefect/server/models/__init__.py
src/prefect/server/models/csrf_token.py
src/prefect/server/schemas/core.py
src/prefect/settings.py
tests/server/models/test_csrf_token.py

Creates a `CsrfToken` model and associated utilities to store CSRF tokens associated with a client identifier. 
Closes #12271 

Create `CsrfToken` model and utilities

---

src/prefect/cli/__init__.py
src/prefect/cli/task_run.py

Ft 12250: Added prefect task-runs to cli

---

docs/api-ref/server/api/middleware.md
mkdocs.yml
src/prefect/server/api/__init__.py
src/prefect/server/api/middleware.py
src/prefect/server/api/server.py
src/prefect/server/models/csrf_token.py
tests/server/api/test_middleware.py
tests/server/models/test_csrf_token.py
tests/server/test_app.py

Creates and integrates the CsrfMiddleware into the server.
Closes #12298 

Integrate `CsrfMiddleware` into server

---

src/prefect/server/api/task_runs.py

I did some independent testing of this with FastAPI and an `asyncio.Queue` in a
simplified environment.  I found that when waiting for the next message on an
empty `asyncio.Queue`, the server will not notice that the client has
disconnected.
With a brief timeout on the `queue.get()`, the disconnects will be noticed and
the server can clean up that socket handler and anything related to it properly.

Correct a memory leak with the outbound task run websockets

---

ui/src/maps/featureFlag.ts
ui/src/pages/DeploymentEdit.vue
ui/src/pages/FlowRunCreate.vue
ui/src/types/flagResponse.ts

Removing the v1 deployment parameters code from oss so that in the next release enhanced deployment parameters are used by everyone.

Schemas: Remove references to v1 deployment parameters

---

src/prefect/server/api/deployments.py
src/prefect/server/api/flow_runs.py
src/prefect/server/api/ui/schemas.py
src/prefect/settings.py
tests/_internal/compatibility/test_experimental.py
tests/conftest.py
tests/server/api/ui/test_schemas.py
tests/server/test_app.py

This PR is graduating `enhanced-deployment-parameters` from an experiment to a fully fledged feature. It removes all condition checks on `experiment_enabled("enhanced_deployment_parameters")`. I have left the setting in place (`PREFECT_EXPERIMENTAL_ENABLE_ENHANCED_DEPLOYMENT_PARAMETERS`) which seems to be consistent with other finished experiments.

remove feature flagging around enhanced-deployment-experiment

---

ui/src/services/csrfTokenApi.ts

During testing I noticed that occasionally a request would be denied due to an invalid CSRF token. This seems to be the result of a race condition where the token is able to be refreshed while the change request is in-flight. To solve for this I updated the the `CsrfTokenApi` to retry failed requests, a single time, when they're due to invalid tokens.
Closes #12372

Update `CsrfTokenApi` to retry failed requests due to invalid tokens

---

docs/guides/settings.md

This adds the CSRF settings to our settings doc.

Add CSRF settings to common settings section in docs

---

RELEASE-NOTES.md

Add a line about appropriate settings for flow run graph layers.

---

ui/src/pages/Flow.vue

Feature : #11773 UI: Add checkboxes for runs for an indivdual flow to allow multi-selection/-deletion

---

docs/guides/settings.md

CSRF is defaulting to False for now

---

src/prefect/utilities/schema_tools/hydration.py
tests/utilities/schema_tools/test_hydration.py

part of closing: https://github.com/PrefectHQ/nebula/issues/6672
cloud pr here: https://github.com/PrefectHQ/nebula/pull/7304
Previously we would treat any __prefect_kind as a "terminal" node during hydration and not look deeper. This pr checks if the value is an object and if so will continue down the hydration chain. This lets us do things like parse workspace variables (strings) into ints or dicts.
```python
input = {
"param": {
"__prefect_kind": "json",
"value": {
"__prefect_kind": "workspace_variable",
"variable_name": "four_json_string",
},
},
}
output = hydrate(
input,
ctx=HydrationContext(
workspace_variables={"four_json_string": "4"},
),
)
```

nested hydration

---

RELEASE-NOTES.md

release notes for off cycle release to fix cli

release notes `2.16.6`

---

docs/guides/deployment/push-work-pools.md
docs/guides/deployment/serverless-workers.md

The links make it a bit easier for readers of the two guides to know where to go to learn about getting dependencies into a deployment that uses these.
Closes #11575

Add links to serverless and push serverless work pool guides for dependency management

---

src/prefect/client/schemas/actions.py
src/prefect/client/schemas/objects.py
src/prefect/server/api/concurrency_limits_v2.py
src/prefect/server/models/concurrency_limits_v2.py
tests/client/test_prefect_client.py

Fixes #12364 
Unit tests modified to reflect new type

fix(client/schema): correct Float type for `slot_decay_per_second` in client SDK

---

docs/guides/using-the-client.md

adding small client cancel flow runs example

---

src/prefect/_internal/pydantic/__init__.py
src/prefect/_internal/pydantic/_compat.py
tests/_internal/pydantic/test_model_validate_json.py

adds `model_validate_json` standalone function

Add `model_validate_json` to pydantic compat layer

---

docs/concepts/automations.md

Add change flow run state action to actions list

---

tests/runner/test_runner.py

Skip oft failing runner test 

---

src/prefect/_internal/schemas/validators.py
src/prefect/deployments/deployments.py

Part 1 of consolidating Pydantic field validation

Move `Deployment` Pydantic validation into internal `validators` module

---

src/prefect/_internal/pydantic/_flags.py

Lower the cognitive overhead when reading our Pydantic V2 flags

Add comment on our Pydantic V2 flags and deprecation logic

---

docs/cloud/users/service-accounts.md

adding rotate note and updating account role

adding rotate note and updating account role

---

src/prefect/_internal/schemas/validators.py
src/prefect/client/schemas/schedules.py
src/prefect/deployments/deployments.py
src/prefect/server/schemas/schedules.py
tests/server/schemas/test_schedules.py

Move `Schedule` Pydantic validation into internal validators module

---

docs/guides/deployment/push-work-pools.md

removing note around cluster and region in awscredblock

removing note around cluster and region in awscredblock

---

docs/guides/deployment/push-work-pools.md

adding back in region

---

.github/workflows/integration-tests.yaml
.github/workflows/python-tests.yaml

Adds a prefix to more easily find the cache values. Also correctly ids the setup python step so we output the version for the cache key

fix uv caching

---

src/prefect/_internal/schemas/validators.py
src/prefect/client/schemas/objects.py
src/prefect/server/schemas/actions.py
src/prefect/server/schemas/core.py
src/prefect/software/python.py
src/prefect/workers/base.py
src/prefect/workers/block.py
src/prefect/workers/process.py

Move validators for task run, infra block, and more 

---

docs/guides/index.md

Adds link to new shell command guide

add shell commands to guides index

---

requirements.txt
src/prefect/cli/_types.py
src/prefect/cli/_utilities.py
src/prefect/cli/deploy.py
src/prefect/cli/root.py

I'll leave it up for discussion whether we should upper bound pin the minor version, this is the second time they've released a minor version recently that's broken our CLI

fix another breaking `typer` change

---

src/prefect/client/schemas/objects.py
src/prefect/client/schemas/responses.py

remove `copy_model_fields` from client response schemas

---

docs/cloud/incidents.md
docs/cloud/index.md
docs/cloud/users/api-keys.md
docs/cloud/users/audit-log.md
docs/cloud/users/index.md
docs/cloud/users/object-access-control-lists.md
docs/cloud/users/roles.md
docs/cloud/users/service-accounts.md
docs/cloud/users/sso.md
docs/cloud/users/teams.md
docs/cloud/workspaces.md
docs/concepts/automations.md
docs/getting-started/installation.md
docs/guides/deployment/aci.md
docs/stylesheets/extra.css

Updates "Enterprise" to "Custom" on cloud plans and updates features.

Update cloud plan info

---

mkdocs.insiders.yml
mkdocs.yml
netlify.toml

Adds social cards back post Google Font changes.
[Mkdocs Material updated](https://github.com/squidfunk/mkdocs-material/releases/tag/9.5.16) how Google Fonts are loaded. 
Pins to this Mkdocs Material version.
Tested by building cards locally and building docs locally.

Integrates mkdocs material social plugin fix

---

src/prefect/client/schemas/actions.py

continuing #12475 
catching this straggler before I start the server schemas

remove straggler decorated client schema

---

netlify.toml

Updates pinned mkdocs material insiders for a potential bug fix
https://github.com/squidfunk/mkdocs-material/releases/tag/9.5.17
QA: Docs build fine locally.
Builds fine in live preview:

Update pinned mkdocs material insiders version

---

.github/workflows/npm_update_latest_prefect.yaml

This PR introduces a GHA secret called `PREFECT_CONTENTS_PR_RW` which allows a PR to be created via the Github Action workflow.  We are moving to this secret vs the default git perms as generally upstream triggered workflow PRs are unable to automatically run PR related tests, which we have observed previously.  Using a dedicated secret w/ the required permissions should resolve this issue.
- Relates: https://github.com/PrefectHQ/platform/issues/6439

chore: Add GHA secret to npm update job

---

mkdocs.insiders.yml
mkdocs.yml

Intermittently seeing docs preview builds fail with:
```Command was killed with SIGBUS (Bus error due to misaligned, non-existing address or paging error)```
The recent fix for mkdocs material treatment of Google Fonts for social cards is likely responsible, as we didn't see this with prior pinned mkdocs material versions and now Google Fonts are being downloaded.

Remove social cards to avoid flakiness in doc builds

---

src/prefect/engine.py
tests/test_tasks.py

After consulting with @cicdw, this PR removes a constraint that prohibits tasks from being called inside other tasks. Early testing shows no adverse consequence of this change, and nested tasks appear to behave and render correctly. The main motivation is that this constraint requires maintainers of frameworks that depend on Prefect to know exactly how their functions will be called, since any task-decorated function can not be called inside another task.
```python
@task
def child_task():
print("Hello from child")
@task
def parent_task():
print("Hello from parent")
child_task()
@flow
def nested_flow():
parent_task()
nested_flow()
``` …

Remove nested task constraint

---

src/prefect/server/schemas/actions.py

remove `copy_model_fields` from second chunk of server schemas

---

src/prefect/server/schemas/actions.py

continuing #12475 
stacked on https://github.com/PrefectHQ/prefect/pull/12572

Remove copy model fields pt9

---

docs/concepts/tasks.md

In #12548 the constraint against nested tasks was removed, so this doc's warning is outdated.

Remove outdated doc

---

docs/faq.md

One word typo fix for faq. There's also a broken link in previous section regarding migrating from Prefect 1 to 2.
> and our [Upgrade to Prefect 2](https://www.prefect.io/guide/blog/upgrade-to-prefect-2/) post for more information.

fix typo in faq

---

docs/faq.md

Update faq.md to remove broken link

---

RELEASE-NOTES.md
scripts/generate-release-notes.py

[Preview](https://github.com/PrefectHQ/prefect/blob/release-notes-2.16.9/RELEASE-NOTES.md)

Release notes 2.16.9

---

docs/concepts/schedules.md
docs/concepts/work-pools.md
docs/tutorial/deployments.md
docs/tutorial/work-pools.md
docs/tutorial/workers.md
mkdocs.yml

Found a few spots updates were needed and links were broken.

Minor doc fixes and updates

---

tests/events/server/conftest.py
tests/events/server/models/test_automations.py

This matches a test fixture in Prefect Cloud that was recently updated.

Syncing up with a Prefect Cloud test fixture change

---

src/prefect/_internal/pydantic/_base_model.py
src/prefect/_internal/pydantic/_compat.py
src/prefect/filesystems.py
src/prefect/pydantic/__init__.py
src/prefect/pydantic/main.py

expose `field_validator` in public compat layer

---

docs/guides/cli-shell.md

Adjusts some formatting and language for consistency with other pages.

Minor updates to cli-shell formatting

---

src/prefect/deployments/recipes/azure/prefect.yaml
src/prefect/deployments/recipes/docker-azure/prefect.yaml

Define `blob_storage` extra as requirement for Azure recipes

feat(deploy/recipe): define `blob_storage` extra as requirement for Azure recipes

---

requirements.txt
src/prefect/server/api/__init__.py
src/prefect/server/api/automations.py
src/prefect/server/api/clients.py
src/prefect/server/api/server.py
src/prefect/server/api/templates.py
src/prefect/server/events/filters.py
src/prefect/server/events/models/automations.py
src/prefect/server/utilities/user_templates.py
tests/events/server/conftest.py
tests/events/server/models/test_automations.py
tests/events/server/test_automations_api.py
tests/server/utilities/test_user_templates.py

This includes the CRUD API for both automations and for automation related
resources, as well as the template validation API.

Adding the automations CRUD API and test suite

---

docs/concepts/blocks.md

Closes #12426
Makes a note in the code example for the import needed if the user has Pydantic v2 installed. 
Will make sure to update in the future in a Prefect Pydantic V2 world. 

Update concepts->blocks example using SecretStr with Pydantic V2 
