tests/test_examples.py
Closes #811 by removing the tests which execute our examples directory.  The intent of this test is great, but ultimately it doesn't do more than make sure the flows _run_ (no assertions are made on flow / task state).  These examples will grow to include more tasks from the task library, which will make the dependency burden complex and excessive.  We want
```
pip install -e ".[dev]"
pytest .
```
to work cleanly.
=> Remove example runs

docs/generate_docs.py, docs/test_generate_docs.py, src/prefect/engine/signals.py, src/prefect/tasks/core/collections.py, src/prefect/tasks/core/operators.py
Reverses the change that automatically added "parent docs" to subclass documentation.
=> Clean up docs for auto-applied task classes

docs/.vuepress/style.styl
- matched bottom footer divider width to content width
- changed top header navigation font to 'arboria' to match the rest of our documentation headers
- resolved #786 by targeting `span.badge` instead of `.badge[data-v-numbers]`
=> documentation styling updates

CHANGELOG.md, src/prefect/core/task.py, tests/core/test_flow.py, tests/core/test_task.py, tests/engine/test_task_runner.py
Addresses an issue raise in #832 by automatically serializing non-serializeable parameters. Now the `Parameter` class will, by default, set `checkpoint` to False
This is feature more in tune with using Prefect Cloud (UI display) and is not needed for local development.
=> Set Parameter checkpoint to a False default

docs/guide/tutorials/advanced-mapping.md, docs/guide/tutorials/local-debugging.md
As raised by @alexisprince1994 the advanced mapping and local debugging tutorials had passed in `processes` to the Dask Executor instead of the proper argument `local_processes`
Closes #844
=> Change `processes` to `local_processes` in Dask Executor related docs

CHANGELOG.md, src/prefect/core/task.py, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/task_runner.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/test_task_runner.py
This PR turns checkpointing back on after #839; however, to prevent local bugs such as #832 task checkpointing now only occurs if the flow is running in Cloud (detected via context).
Checkpointing of parameters is semi-important for UI visibility; however, the JSON requirement of cloud parameters shouldn't affect core users executing flows locally.
=> Checkpointing updates

CHANGELOG.md, src/prefect/client/client.py, src/prefect/core/flow.py, tests/client/test_client.py
This PR adds an optional `build` kwarg to our deployment endpoints.  This makes it easier to build an environment manually and pass that to a Flow without having the Client attempt to rebuild it.  Probably makes #868 easier
This makes it easier for users to provide completely custom Docker images to their flow and avoid rebuilding the docker images.
=> Add optional build kwarg to client.deploy

CHANGELOG.md
Per request @ https://github.com/PrefectHQ/prefect/pull/871#issuecomment-478245424
=> Update Contributor name

CHANGELOG.md, src/prefect/client/secrets.py, tests/client/test_secrets.py, tests/engine/cloud/test_cloud_flows.py, tests/engine/test_flow_runner.py, tests/tasks/google/test_bigquery.py, tests/tasks/google/test_storage.py
This PR adds some auto-formatting inside `Secret.get` for local secrets only; in particular, `json.loads` will now attempt to be called on the value pulled from context.  Any errors this raises are ignored and the underlying value is returned.
This PR makes it much easier to handle complex secrets locally (such as `GOOGLE_APPLICATION_CREDENTIALS`).
=> Secrets upgrade

CHANGELOG.md, docs/guide/development/documentation.md, src/prefect/client/client.py, src/prefect/engine/cloud/task_runner.py, tests/engine/cloud/test_cloud_task_runner.py
This PR implements a new `client` method for extracting stored cached states, and additionally implements the necessary queries so that cached tasks will work across flow runs in Cloud.
=> Cloud Caching

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, src/prefect/engine/task_runner.py, tests/engine/test_task_runner.py
This PR adds Task loggers to context for easily creating custom logs during task runs.  This is easy enough when a custom Task class is created, but wasn't possible when using the `task` decorator.  Now a user simply has to pull the logger from context:
```python
@task
def my_logging_task():
logger = prefect.context.get("logger")
logger.info("Hey")
```
Closes #884
=> Add logger to context

docs/.vuepress/config.js, docs/api/0.5.0/utilities/notifications.md, docs/guide/PINs/PIN-4-Result-Objects.md, docs/guide/PINs/PIN-5-Combining-Tasks.md, docs/guide/PINs/PIN-6-Remove-Constant-Tasks.md, docs/guide/development/documentation.md, docs/guide/tutorials/visualization.md, package-lock.json, package.json, src/prefect/utilities/notifications.py
- Adds PIN 6, closes #748. Based on conversations, I marked it as "Accepted", but happy to revert to "Proposed" if I'm mistaken.
- Adds a utility for auto-generating sidebar children. It looks like VuePress has officially decided not to support this (https://github.com/vuejs/vuepress/issues/613). I've applied it to each section where alphabetical children are appropriate.
=> Add PIN 6 (and a utility for auto-generating docs sidebar)

CHANGELOG.md, src/prefect/tasks/core/collections.py, src/prefect/utilities/tasks.py, tests/tasks/test_core.py, tests/utilities/test_tasks.py
This PR fixes our `as_task` utility for auto-converting python objects to Prefect Tasks, specifically for callables and dictionaries.  Closes #894 
`as_task` is used internally to track _all_ task dependencies, including constants.  This utility was implicitly assuming that dictionaries were only keyed by strings and also would attempt to convert _all_ callables into `FunctionTask`s.  This isn't actually possible because python builtins cannot be inspected via `inspect.getfullargspec` and consequently users were seeing errors when passing these types of objects around in their Flow.
=> Fix as_task bug

CHANGELOG.md, docs/guide/core_concepts/configuration.md, src/prefect/cli/__init__.py, tests/cli/test_cli.py
closes #904 
Removes the cli command (and its tests) `prefect make user config` and updates docs and changelog accordingly
per discussion in #904, this feature was more trouble than it was worth.  Users should just create their own user configuration manually, and we don't need a utility for touching a functionally empty file.
=> removing cli command `prefect make user config`

.circleci/config.yml, README.md, codecov.yml, docs/generate_docs.py
This PR closes #902 via [codecov](https://codecov.io/gh) integration.
Notes:
- our hosted coverage reports can be found here: https://codecov.io/gh/PrefectHQ/prefect (see the "commits" section to see the reports by commits from this PR)
- this will allow us to display a badge of our awesome test coverage: [![codecov](https://codecov.io/gh/PrefectHQ/prefect/branch/master/graph/badge.svg)](https://codecov.io/gh/PrefectHQ/prefect) (unknown right now because we haven't uploaded reports from master yet)
- we can optionally turn off the codecov bot if we don't like it's comments
- we can use codecov to actually enforce coverage thresholds on PRs (see https://docs.codecov.io/docs/commit-status) (I didn't implement this yet because I want some feedback)
=> Add Codecov integration

CHANGELOG.md, src/prefect/core/flow.py, src/prefect/core/task.py, tests/core/test_flow.py
- Changes the validation argument of `Task.set_dependencies()` from a default of `True` to `None`, which will in turn pick up the value from `prefect.config` (unless provided explicitly)
- Closes #919, which was seeing runaway flow build times when dealing with many auto-generated `Constant` tasks, because each task was invoking flow validation due to the default parameter.
Thanks @Joselinejamy for identifying the issue!
=> Ensure validation isn't performed unless specified in config

CHANGELOG.md, src/prefect/client/secrets.py, tests/client/test_secrets.py
This PR raises an informative error if `Secret.get` is called from with a Flow building context. @dylanbhughes could you let me know what you think of this error message?
```python
ValueError: Secrets should only be retrieved during a Flow run, not while building a Flow.
```
Closes #927 and improves user experience by helping users employ best practices.
=> Raise ValueError if Secret.get is called from within flow context

CHANGELOG.md, src/prefect/core/flow.py, src/prefect/core/task.py, tests/core/test_task.py
Adds `key` and `mapped` keywords to both `Task.set_upstream` and `Task.set_downstream` for representing more interesting Task dependencies.
Ensures the imperative API has the same functionality / exposed features as the functional API.  Closes #823
=> Add two new keywords to task.set_upstream and task.set_downstream

CHANGELOG.md, docs/guide/tutorials/custom-logs.md, src/prefect/config.toml, src/prefect/engine/flow_runner.py, src/prefect/engine/task_runner.py, src/prefect/utilities/logging.py
This PR adds a "Deployment: Logging" tutorial for explaining how to interact with Prefect logs (Part 2 in a series on Deployment related information).
Is functionality really present if it isn't documented well? 🤔
=> Add Deployment Logging Tutorial

CHANGELOG.md, src/prefect/engine/state.py, src/prefect/serialization/state.py, tests/engine/test_state.py
This PR adds start times to queued states.
This could be useful for using queued states.
=> Add start time to queued states

setup.py
dask-kubernetes has the requirements set to `kubernetes>=4` however version `9.0.0` introduced some breaking changes https://github.com/dask/dask-kubernetes/issues/118 therefore we should install kubernetes before dask-kubernetes
To avoid running into deployment issues such as:
```
TypeError: delete_namespaced_pod() takes 3 positional arguments but 4 were given
at _cleanup_pods (/usr/local/lib/python3.6/site-packages/dask_kubernetes/core.py:510)
at __call__ (/usr/local/lib/python3.6/weakref.py:548)
at _exitfunc (/usr/local/lib/python3.6/weakref.py:624)
```
=> Change kubernetes requirements order

CHANGELOG.md, src/prefect/engine/state.py, tests/engine/test_state.py
This PR adds the is_submitted method for states.
This PR makes it easier to detect if a state is submitted.
=> Add is_submitted for states

CHANGELOG.md, docs/outline.toml, src/prefect/serialization/task.py, src/prefect/triggers.py, tests/serialization/test_tasks.py, tests/test_triggers.py
This PR implements two new triggers for specifying bounds on the number of failures or successes required for the task to run.  This is particularly useful for triggers on large collections of mapped tasks, where we might only care about a certain _level_ of failure rather than "all / none".
Closes #933 and allows for even more flexibility in workflow logic.
**cc:** @dylanbhughes
=> New triggers

CHANGELOG.md, docs/outline.toml, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/state.py, src/prefect/serialization/state.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/test_state.py
This PR introduces a new state (`ClientFailed`) for situations in which the Client fails to set a task run state.  This prevents downstream tasks with `all_failed` or `any_failed` triggers from accidentally running.
Closes #938 and fixes an edge case
=> ClientFailed State

CHANGELOG.md, src/prefect/engine/state.py, src/prefect/serialization/state.py, tests/engine/test_state.py, tests/serialization/test_states.py
- Allows `start_time` to be provided as an __init__ arg for Queued states. This makes the state more flexible (currently start time defaults to `now()`) and also simplifies serialization logic since no exception needs to be made for the field.
- Simplifies the combinatorially-growing `is_*()` checks in state unit tests
=> Add `start_time` as an init arg for Queued states

CHANGELOG.md, docs/outline.toml, src/prefect/environments/__init__.py, src/prefect/environments/execution/__init__.py, src/prefect/environments/execution/local.py, src/prefect/serialization/environment.py, tests/environments/execution/test_local_environment.py
This PR adds a simple implementation of a `LocalEnvironment` execution environment for running flows in storage via their runners.  This environment is currently intended only for local testing, but I could see it being useful in real scenarios as well.
I'd like to use this PR to discuss a few things:
- whether `get_runner` / `get_env_runner` should hook into `flow.run`, `FlowRunner(flow=flow).run()`, or whether they should both allow for an environment to toggle between the two
- whether `get_env_runner` should return something with a proper `run` _method_ vs. it's current return value (a callable)
Hopefully this PR clarifies …
=> Add LocalEnvironment

CHANGELOG.md, docs/outline.toml, src/prefect/environments/storage/__init__.py, src/prefect/environments/storage/bytes.py, src/prefect/serialization/storage.py, tests/environments/storage/test_bytes_storage.py, tests/serialization/test_storage.py
Back by popular demand, it's `Bytes` storage. 
For local testing, we needed something less ephemeral than `Memory` and still something that doesn't rely on file system storage.
=> Bytes storage

tests/engine/test_flow_runner.py
Attempt at closing #964 by removing a parallelism test which used `capsys` + prints.  This test also made local testing annoying because for _some_ reason (that I really don't understand), `pytest` would flood the terminal with these prints even though they should have been cleared from the buffer by the `capsys` fixture.  I'm guessing that multithreading had a role to play here.
=> Remove noisy print test that tested for parallelism

CHANGELOG.md, src/prefect/environments/storage/docker.py
Uses `self.flows.values()` instead of `keys()` since the flow path was moved to a value. Pip installs from the current master branch of Prefect until a new version is released which contains all new storage and environment changes
Avoids issues like:
```
Step 9/9 : RUN python /root/.prefect/healthcheck.py
---> Running in 203394a563b9
Beginning health check...
File "/root/.prefect/healthcheck.py", line 5, in <module>
with open(flow_file, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Test-Flow'
```
and
```
Step 9/9 : RUN python /root/.prefect/healthcheck.py
---> Running in …
```
=> Tweak Docker storage to handle healthcheck issues

CHANGELOG.md, src/prefect/cli/__init__.py
Adds an `execute-cloud-flow` CLI command
It didn't make sense to pump the storage and environment through the pipeline of execution and instead this allows us to run a small query to retrieve it at the time of execution
=> Add CLI command for executing a cloud flow

CHANGELOG.md, dev-requirements.txt, requirements.txt, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
Fixes docker storage to use slugified Flow names to prevent weird file copying behavior in the docker image. Closes #969 
Because people like @jlowin like to put emojis in flow names for some reason.  Btw this _does_ work with emojis, but I was too afraid to put an emoji in our codebase........
=> Flow Name fix for Docker Storage

CHANGELOG.md, src/prefect/environments/execution/cloud/environment.py, tests/environments/execution/test_cloud_environment.py
Changes the flow loading in the `run_flow` of the CloudEnvironment to use `cloudpickle.load`
Closes #977 
We need to be able to load the file in a way which matches how it is dumped https://github.com/PrefectHQ/prefect/blob/master/src/prefect/environments/storage/docker.py#L294
=> Change serialized flow loading to use cloudpickle

.circleci/config.yml
It's still happening: https://circleci.com/gh/PrefectHQ/prefect/18779
It looks like bleeding edge `pytest-cov` wasn't actually installed since the version was the same as the released version.
=> Uninstall pytest-cov prior to installing from git

src/prefect/environments/execution/cloud/environment.py, tests/environments/execution/test_cloud_environment.py
Updates the `CloudEnvironment` to pull the default flow runner class instead of always using a `FlowRunner`.  @joshmeek this is probably what was causing the version issue?
=> FlowRunner -> get_default_flow_runner_class

CHANGELOG.md, src/prefect/engine/executors/dask.py
This PR _immediately_ gathers futures created by `client.map` inside the `DaskExecutor`.  This prevents any strange behavior caused by mismatching clients w/ futures.
Closes #943
=> DaskExecutor map gathers immediately

.circleci/config.yml
Yet another attempt at closing #964 -- just don't track coverage in the 3.7 job.  We currently don't have any code paths that are unique to 3.7 so this shouldn't actually affect our coverage reports.
I have 0 proof that this is the cause of the issue, only a suspicion.
=> Remove coverage from 3.7

src/prefect/core/flow.py, tests/core/test_flow.py
Does the correct containment check when calling `flow.serialize` with `build=True`
For re-deploying flows in the same live session.
=> Add fix for calling serialize twice

CHANGELOG.md, src/prefect/engine/flow_runner.py, tests/engine/cloud/test_cloud_flow_runner.py, tests/engine/test_flow_runner.py
This PR explicitly calls state handlers in the event that an unexpected error occurs.
Rarely, there can be errors in `initialize_run` when a Flow was deployed incorrectly.  Previously, the run would end but the state wouldn't formally update in the system to `Failed`.  This ensures that the state change handlers are called in this scenario, and allows for a much smoother debugging experience.
=> Handle initialization errors

CHANGELOG.md, Dockerfile, docs/guide/development/release-checklist.md, src/prefect/core/flow.py, src/prefect/environments/storage/docker.py, tests/core/test_flow.py, tests/environments/storage/test_docker_storage.py
- adds a warning for building a flow's storage twice
- updates the `Dockerfile` to properly accept `GIT_POINTER` build arg (note: build args are reset after `FROM`)
- updates the release checklist to remind us to push a new tag to docker hub 
Improves UX for deploying flows; we were bit earlier by a flow which changed but wasn't added back to its storage because the storage class thought the flow was already present.  I am open to more aggressively removing the flow from storage and re-adding it back if anyone wants to push for that.
Also adds a warning if their are python version mismatches in `Docker` storage, closes #999
=> Random Docker nits

CHANGELOG.md, src/prefect/tasks/notifications/slack_task.py, tests/tasks/notifications/test_slack_task.py
This PR adds a new kwarg to `SlackTask` for customizing the name of the Prefect Secret which stores the webhook URL.
Turns out this is a very very popular task, and when multiple people in the same tenant want to redirect their messages to custom locations, this is necessary!  **cc:** @nanseay
=> Add webhook_secret to SlackTask

CHANGELOG.md, src/prefect/core/task.py, src/prefect/tasks/core/constants.py, src/prefect/tasks/core/function.py, tests/core/test_task.py
This PR introduces a new signature validator for the `__init__` method of custom `Task` subclasses.
As we saw in #1020 there are many situations in which the `Task` initialization kwargs might be reused by subclasses.  This can cause ambiguity + actual runtime errors, and relies on careful reviews to identify.  With the signature validator, a clear error message is raised at `Task` creation time to prevent the situation from occurring.
=> Init validator

CHANGELOG.md, src/prefect/utilities/logging.py
A mypy assert checked that a `client` attribute was a `Client` object, but unfortunately the `Client` class was imported in a scope that wasn't always available to the mypy assert.
The `Client` import needs to be deferred due to circular imports.
=> Fix bug caused by mis-scoped import

CHANGELOG.md, docs/outline.toml, src/prefect/schedules.py, src/prefect/serialization/schedule.py, tests/serialization/test_schedules.py, tests/test_schedules.py
This PR introduces a new schedule type: the `UnionSchedule`. This schedule is formed by simply combining an arbitrary number of other schedules in one, in the "natural" way.
This PR allows for complex schedule specification that wasn't possible before; for example: a single flow which runs at _both_ market open _and_ market close each day.
I propose that this PR closes #428
=> Introducing: Union schedule

src/prefect/cli/__init__.py, src/prefect/environments/execution/cloud/environment.py, src/prefect/environments/storage/docker.py, src/prefect/serialization/environment.py, tests/environments/execution/test_cloud_environment.py, tests/serialization/test_environments.py
Actually calls environment.setup inside the execute-cloud-flow CLI; this wasn't a bug per se, because previously the CloudEnvironment didn't have a non-trivial `setup` method, but now it does!
The final piece of the puzzle for fully automated private docker registry support.
=> Actuall call environment.setup in the execute-cloud-flow CLI

src/prefect/serialization/schedule.py
As a matter of best practice, we should use a fully qualified schema name to avoid collisions with any other ScheduleSchemas.
=> Use fully-qualified schedule schema for marshmallow

CHANGELOG.md, src/prefect/config.toml, src/prefect/configuration.py, tests/test_configuration.py
- Cleans up the configuration process to make it more streamlined and in line with how configs are being used today
- Removed some overengineered functionality around merging configurations
- Fixes an issue where user configs were loaded AFTER variable interpolation had taken place (Closes #1035)
=> Refactor configuration load / interpolation

CHANGELOG.md, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
This PR attempts to add a smart default for the Docker storage `prefect_version` based on the user's local version.
Closes #533
=> Default prefect version in Docker

docs/guide/core_concepts/configuration.md, src/prefect/config.toml, src/prefect/configuration.py, tests/test_configuration.py
- This PR removes a configuration key from the default config called `user_config_path`. This change has little impact because in practice, that value needed to be set via environment variable anyway (since setting it in a user config was useless unless the user config path was already set!). However, the redundant check for that value was creating issues with unit tests, since we set `PREFECT__USER_CONFIG_PATH=""` and the logic I implemented in #1037 loaded the config key if the env var was "None-ish". 
- tldr; no behavior changes but avoids a circular load that was caused by loading the config and checking a key that had to …
=> Remove user_config_path from config to avoid circular loads

CHANGELOG.md, src/prefect/client/secrets.py, tests/client/test_secrets.py, tests/engine/result_handlers/test_result_handlers.py, tests/serialization/test_result_handlers.py, tests/tasks/github/test_repos.py, tests/tasks/google/test_bigquery.py, tests/tasks/kubernetes/test_deployment.py, tests/tasks/kubernetes/test_job.py, tests/tasks/kubernetes/test_pod.py, tests/tasks/kubernetes/test_service.py, tests/utilities/test_notifications.py
This PR changes the behavior of secrets (notable _local_ secrets) to raise errors when they aren't found.
Raising an error does a few things:
- disambiguates between a `None` that is explicitly set as a secret value vs. a not-found secret
- provides an earlier, more explicit error when something involving secrets goes wrong (e.g., instead of AWS telling you your password is incorrect, Prefect tells you your AWS secret wasn't found)
- Closes #1043 
- makes the behavior of local vs deployed Flows consistent
=> Secrets now raise when not found

tests/serialization/test_tasks.py
This test has the same name as another test, so it shadows it. Updating so both are run.
=> Update shadowed unit test name

CHANGELOG.md, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
Closes #722 
Sometimes users want to build custom base images before adding their flows. This allows for it by skipping the pull step if user specifies `local_image=True`
=> Allow Local Images for Docker Storage

CHANGELOG.md, src/prefect/core/flow.py
Changes the order of the `visualize()` flow so that saving to a file is possible within a notebook.
IMO it's counterintuitive that `visualize(filename='blah')` does not save a file if running in a notebook. The current behavior does not match the docstring but I believe the updated behavior does, so I left the docstring as-is.
=> Allow saving graph from notebook

CHANGELOG.md, docs/guide/examples/imperative_docker.md, docs/outline.toml, examples/imperative_docker.py, src/prefect/tasks/docker/__init__.py, src/prefect/tasks/docker/containers.py, tests/tasks/docker/test_containers.py
This PR adds a new task to the task library, `WaitOnContainer`, which waits for a Docker container to finish its run.  The task optionally raises a `FAIL` signal if the container exits with a non-zero status code.
Additionally, closes #760 with an imperative API example which sets up a full Docker pipeline.
If a Flow interacts with docker, there are many instances in which certain tasks should only start if a docker container exits.  This "final" Docker task allows for complete Docker pipelines written in Prefect.
=> Add docker wait task

tests/test_schedules.py
Fixes two `UnionSchedule` tests that were failing during certain time windows.
Closes #1053
=> Fix poorly written schedule tests

CHANGELOG.md, src/prefect/engine/task_runner.py, tests/core/test_task_map.py, tests/engine/test_task_runner.py
This PR ensures that if a mapped task follows a task which is skipped, the mapped task skips itself and doesn't error out.  Previously, the upstream skipped state was indexed into (because the `check_upstream_skipped` pipeline step was run _after_ the `run_mapped_task` step).  I had to:
- Change the order of these pipeline steps so that upstream skips were handled better
- update the logic of `check_upstream_skipped` so that in the case of `c.map(b.map(a))`, where maybe _one_ mapped child of `b` skips, all of `c` does _not_ skip as well (only the individual child of `c` with an upstream skip should skip...)
Bug fix - closes …
=> FIX: Mapped skips

tests/test_schedules.py
Fixes the occasionally failing union-next-n-different-timezone test by ensuring `east.next(1)` is always the next scheduled time.
=> Finally fix union timezone test

requirements.txt
Closes #1073 by relaxing our `pendulum` requirement on the lower end to allow for `2.0.2`, which [is installable on Windows](https://github.com/sdispater/pendulum/issues/365).  Consequently, Windows users can work around the issue via 
```
pip install pendulum==2.0.2
pip install git+https://github.com/PrefectHQ/prefect.git@master#egg=prefect[viz]
``` 
(or whatever extras are desired).
Additionally, repins `marshmallow` as CLI tests began failing locally for me when I upgraded :/
=> Update requirements for easier workarounds on windows

requirements.txt
Part of the whole requirements cleanup; we don't explicitly depend on this package, and it's presence in our requirements is an artifact of an old `requests` issue.
=> Remove idna as a requirement

CHANGELOG.md, setup.cfg, src/prefect/engine/cache_validators.py, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/task_runner.py, tests/core/test_flow.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/test_cache_validators.py, tests/engine/test_task_runner.py
OK this is a doozy; caching with mapped tasks was not working in cloud because cache validators were comparing _safe results_ from the database with _raw inputs_ from the process; this has been updated to now convert safe results to real results prior to comparisons and then only compare _values_ of the results (so that the conclusion is independent of result handler)
Additionally, mapping was _not_ preserving the fully-hydrated "Result" object from upstream; instead, it was stripping out result handler info.  This has been fixed.
=> Map Caching in Cloud

src/prefect/cli/execute.py, tests/cli/test_execute.py
Raises a ValueError if the flow run id provided in context to `prefect execute cloud-flow` does not exist.
Error handling in the CLI makes a more pleasant experience
=> Add ValueError Handling in `execute cloud-flow`

CHANGELOG.md, src/prefect/core/flow.py, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/task_runner.py, tests/core/test_flow.py
This PR refactors mapped caching in the open source engine to look in `prefect.context` for candidate cached states.
This implementation closes #1082 and allows for mapped caches to exist independent of ordering; additionally, it allows for a cached mapped task to return results of differing lengths across runs, all while using a shared cache.
I'm satisfied with this implementation, but there are a few things I'd like to add / get some feedback on:
=> Context cache

requirements.txt, src/prefect/core/flow.py
Removes the xxhash dependency.
Unused dependencies should go bye bye
=> Remove unused xxhash dependency

src/prefect/environments/execution/cloud/worker_pod.yaml
Decreases the dask worker timeout to 60s (down from 600s)
If workers lose connection to the scheduler they don't need to sit around for 10 minutes and should just be killed quickly
=> Decrease dask worker timeout to 60s in CloudEnvironment

CHANGELOG.md, src/prefect/client/secrets.py, src/prefect/engine/result_handlers/gcs_result_handler.py, src/prefect/engine/result_handlers/s3_result_handler.py, src/prefect/serialization/result_handlers.py, tests/engine/result_handlers/test_result_handlers.py, tests/serialization/test_result_handlers.py
This PR allows for pulling credentials from custom-named Prefect Secrets in both the `GCSResultHandler` and `S3ResultHandler`.  In addition, it ensures that clients are not created during initialization / deserialization.
Improper deserialization was throwing errors on some Flows in Cloud. Having customizable secret names is important when multiple users want to access different resources within a tenant.
Closes #1098 
Closes #1112
=> ResultHandler fixes and upgrades

CHANGELOG.md, src/prefect/cli/execute.py
This PR pro-actively fails flow runs from the CLI entrypoint if loading the flow's storage or environment fails for any reason.
Allows for users to see / fix issues early on and prevents inherently corrupted flows from getting stuck in an infinite lazarus cycle.
=> Proactively fail flow runs if the storage / environment interface fails

src/prefect/cli/execute.py
Fixed the final typo caused by #1122 
I would write a test for this, but unfortunately it'll take me a bit because `set_temporary_config` / updating context for the CLI tests isn't as simple as it seems.  I've been unnsuccessfully trying to use the `env` keyword for the `CliRunner` but it doesn't seem to be working as I expect.  I've got an open issue #1124 to figure this out but I'd like to get this in to cleanup some old flow runs.
=> Now this is just embarrassing - fixed another typo

CHANGELOG.md, docs/guide/core_concepts/configuration.md, src/prefect/configuration.py, tests/test_configuration.py
- Adds two validation steps for configuration files:
1. makes sure config keys don't shadow methods of the `Config` object, which causes nasty errors if you try to interact with the object (for example, a config key called "keys" would shadow the `Config.keys()` method).
2. makes sure config keys are lowercase, because keys set by environment variables are always interpreted as lowercase, so upper case key's can't be set by env var.
=> Add validation for configuration files

src/prefect/configuration.py, tests/test_configuration.py
#1136 accidentally removed the ability to use local secrets, which are typically stored as all uppercase var names.  In fact, it removed the ability to set case sensitive keys in context, which is important.  This PR ensures that context is treated specially and not case-handled in any particular way.
=> Ensure context config can still be interpreted in a case-sensitive way

CHANGELOG.md, src/prefect/core/task.py, src/prefect/serialization/task.py, src/prefect/utilities/tasks.py, tests/core/test_flow.py, tests/core/test_task.py, tests/serialization/test_tasks.py, tests/utilities/test_tasks.py
This PR adds a new `auto_generated` property to all Tasks which is set only when using the `as_task` utility method. This property allows for convenient filtering of tasks when making graphql queries, in the UI, etc. etc.
Useful for filtering out "noise".
=> Add auto generated property to task

setup.cfg
Updates `setup.cfg` to identify `src/prefect` with `site-packages/prefect` so that the path names that are uploaded to codecov are correct.  I still don't know what changed to trigger this behavior, but here we are.
Closes #1132
=> Welcome back old friend

src/prefect/environments/execution/cloud/environment.py, src/prefect/serialization/environment.py, tests/environments/execution/test_cloud_environment.py, tests/serialization/test_environments.py
This PR ensures that the `CloudEnvironment` docker secret attribute is serialized correctly.  Note that I've set it to `None` if not using a private registry, so that when displayed in the UI it isn't misleading.
For users which require multiple docker secrets for multiple private registries, being able to customize the name is important.  Prior to this PR, serialization was not preserving the custom secret name.
=> Serialize secret name

src/prefect/environments/execution/cloud/environment.py, tests/environments/execution/test_cloud_environment.py
This PR explicitly calls `sys.exit` when the `CloudEnvironment` is done running its flow.  
We occasionally see kubernetes jobs in which the Flow is visibly complete (based on its state, logs, etc.) but the Dask Cluster remains alive in k8s.  It appears to happen more frequently for Python 3.7 jobs, and _appears_ to be caused by a hanging Python process that is stuck in some sort of garbage collection phase.  Explicitly calling `sys.exit` will hopefully trigger the appropriate resource cleanup and end these jobs so that the resource manager doesn't have to worry about cleaning them up.
=> Call sys.exit when cloud environment finishes running flow

CHANGELOG.md, src/prefect/engine/signals.py, tests/engine/test_signals.py
Ensures that the `result` kwarg can be passed to the underlying state associated with a Prefect signal. 
Closes #1163
=> Ensure results can be passed to Prefect Signals

CHANGELOG.md, src/prefect/environments/execution/cloud/job.yaml
Disable dask [work stealing](http://distributed.dask.org/en/latest/work-stealing.html) via env var config.
We saw a few situations in which a task future was resolved twice; because of our version lock system the task didn't actually _execute_ twice, but it did add some noise to the logs that we'd like to prevent.
=> Disable work stealing in Dask

src/prefect/environments/execution/cloud/job.yaml
I pattern matched with our other boolean configs, but Prefect's type casting is more generous than Dask's, so this setting needs to be properly cased.
=> Update dask config to False

CHANGELOG.md, src/prefect/utilities/notifications.py, tests/utilities/test_notifications.py
This PR changes the `slack_notifier` kwarg `webhook_url` to `webhook_secret`.  Now you must specify a secret name instead of the URL directly.  This:
- ensures consistency with other slack tasks
- encourages best practices with sensitive information
Closes #1075
=> slack_notifier pulls from secret

src/prefect/utilities/executors.py, tests/utilities/test_executors.py
For best practices, also calls `.join()` on the heartbeat timer thread after cancel.  It turns out that `.cancel()` doesn't guarantee that the thread itself is killed, but rather that the function the Timer is calling will not be called.  
I have a suspicion that this is at the heart of the various hanging processes we've seen in different situations (possibly even the hanging CircleCI jobs...).  I can't prove it, but we'll find out!
=> Call join on heartbeat timer to ensure thread is cleaned

docs/guide/tutorials/local-debugging.md
Tiny typo fix which was missed in #1160.
=> Typo fix in docs (right-hand side of assignment should be a tuple)

setup.py
In order to support Kubernetes 9.0.0 API changes we need dask-kubernetes to be on 0.8.0
=> Bump dask-kubernetes version to 0.8.0

CHANGELOG.md, src/prefect/engine/task_runner.py, tests/core/test_flow.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/test_task_runner.py
This PR fixes an issue that we recently observed in Prefect Cloud - if a Task is mapping over a large number of slow-running children, and one of those child tasks goes into immediate Retry, the asynchronously retrying Flow Run does not have access to the `Mapped` state and thus cannot regenerate its children appropriately. 
For large scale mapped Flows, retries need to work properly!
=> Long-running Mapped Retries

.circleci/config.yml, src/prefect/engine/flow_runner.py, src/prefect/engine/task_runner.py, tests/engine/cloud/test_cloud_flow_runner.py, tests/engine/test_flow_runner.py
This PR implements a minor optimization that prevents  a flow run `Running` state from being redundantly set twice.  In cloud, setting this state would increment all flow state versions and led to some annoying delays.
=> Don't redundantly set flow run state

CHANGELOG.md, src/prefect/core/flow.py, src/prefect/utilities/tasks.py, tests/core/test_flow.py, tests/tasks/test_core.py
This PR fixes an issue that arises when using the imperative API and binding a task with call arguments of type: dict, list, set, or a nested combination of the 3
Closes [#1211](https://github.com/PrefectHQ/prefect/issues/1211)
=> Fix collections automatical apply using the imperative API

CHANGELOG.md, src/prefect/engine/executors/dask.py, src/prefect/engine/task_runner.py, src/prefect/utilities/collections.py, tests/engine/executors/test_executors.py, tests/engine/test_task_runner.py
This PR implements the ability to tag tasks with `dask-resource:KEY=VALUE` for hooking into [Dask Worker Resources](https://distributed.dask.org/en/latest/resources.html).
This PR lets users create tasks with "task affinity" -> i.e., tasks with appropriate tags will _only_ be submitted to workers which claim to support those tags.  This allows certain tasks to run next to GPUs, other hardware, etc. in a very simple and lightweight fashion.
=> Dask task affinity!

CHANGELOG.md, src/prefect/config.toml, src/prefect/engine/cloud/task_runner.py, tests/engine/cloud/test_cloud_flow_runner.py, tests/engine/cloud/test_cloud_flows.py, tests/engine/cloud/test_cloud_task_runner.py
This PR implements "local retries" in the Cloud Task Runner.  Essentially, we found that tasks which request fast retries tend to eat up infrastructure in a way that just felt unnecessary.  This PR will retry tasks whose retry start time is <= 1 minute away by sleeping in the local process.  This prevents additional infrastructure spin ups.
=> Local retries

package.json, yarn.lock
These dependencies are only used to compile / host documentation in VuePress, but it's still good to keep them up-to-date.
=> Upgrade some JS package dependencies

docs/outline.toml
Fixes an issue wherein `unmapped` was listed as a function when in fact it is a class.  This messes up the auto-generated docs as can be seen here:
=> Fix documentation mistake

CHANGELOG.md, docs/outline.toml, src/prefect/environments/storage/__init__.py, src/prefect/environments/storage/local.py, src/prefect/serialization/storage.py, tests/environments/storage/test_local_storage.py, tests/serialization/test_storage.py
Renames `LocalStorage` to `Local` to better fit in with the storage naming pattern.
=> Rename LocalStorage -> Local

CHANGELOG.md, src/prefect/client/client.py, tests/client/test_client.py
This PR streamlines the process of logging in to Cloud and storing API tokens. Previously, `Client.login()` was a deprecated call that used old email/password auth. Now, `Client.login()` accepts an API token as its sole argument, and writes it to a known location. If the token is found in that location, it will be used automatically. 
This PR also removes token refresh behavior, as API tokens don't need refreshing.
=> Streamline Cloud login with API tokens

CHANGELOG.md, src/prefect/engine/flow_runner.py, src/prefect/engine/task_runner.py, src/prefect/utilities/logging.py, tests/core/test_task_map.py, tests/engine/test_flow_runner.py, tests/engine/test_task_runner.py, tests/utilities/test_logging.py
This PR fixes some issues we were seeing with logging in long-standing Dask clusters (namely, some logs didn't arrive).  In particular, this PR introduces the following behavior: whatever `prefect.context` is at _initialization_ time for the runners is guaranteed to be present during a run.  This ensures, in particular, that `flow_run_id` is always available for the logger.
=> Distributed logging

setup.py
`dask-kubernetes==0.8.0` is not compatible with newer versions of `distributed` -- @joshmeek I'll look to your guidance as to whether this requires any changes to the `CloudEnvironment` (which we should rename to `DaskKubernetesEnvironment` or something)
=> Loosen the dask-kubernetes pin to accomodate newest distributed versions

CHANGELOG.md, src/prefect/client/client.py, tests/client/test_client.py
Allows users to pass custom headers in `prefect.Client` calls.
Headers are often used to interact with remote servers, including assumptions of roles.
=> Allow passing custom headers through client

src/prefect/utilities/logging.py
The correct entry in the record dictionary is actually "levelname"; this was resulting in all Cloud logs arriving as "INFO" level.
=> Fix issue with all logs being shipped as INFO

docs/guide/core_concepts/results.md
It looks like CloudResultHandler was removed as the default in the 0.6.0 release. (See https://github.com/PrefectHQ/prefect/releases/tag/0.6.0 and https://github.com/PrefectHQ/prefect/pull/1198) Yet, the current documentation still refers to it as the default result handler.
As a healthcare company dealing with HIPAA/PHI data, it was scary to read this sentence (that I'm proposing to remove) in the docs: "As of this writing, the default handler that ships with a standard install of Prefect is the CloudResultHandler that writes data to a Prefect-managed Google Cloud Storage bucket." It caused me to worry that in testing Prefect Core locally we might have unwittingly shipped PHI data to a Google Cloud Storage bucket managed by Prefect.
Please describe …
=> Remove sentence saying CloudResultHandler is default

CHANGELOG.md, src/prefect/config.toml, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/task_runner.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/test_task_runner.py
This PR introduces a new config setting `flows.checkpointing` for turning on task checkpoints in local (non-cloud) execution.  The setting defaults to `False`, but when `True` Task result handlers will be called to "checkpoint" their results.
This PR has a few key advantages:
- allows for selective persistence of data
- allows users to more easily / naturally test their result handlers before deploying to Cloud
This will also make #892 easier to write
=> Checkpointing

CHANGELOG.md, docs/guide/core_concepts/configuration.md, src/prefect/configuration.py, tests/test_configuration.py
Previously, configuration keys were required to be lower-case. This was intended to prevent issues where case-insensitive environment variables were improperly interpolated. However it was overly-restrictive (see #1288). Now Prefect will allow mixed-case configs, and documents that environment variables can only be applied to lower-case keys.
Closes #1288
=> Allow mixed-case keys in configuration

tests/client/test_client.py, tests/client/test_secrets.py, tests/core/test_flow.py, tests/core/test_task.py, tests/engine/executors/test_executors.py, tests/engine/result_handlers/test_result_handlers.py, tests/engine/test_result.py, tests/environments/storage/test_bytes_storage.py, tests/environments/storage/test_docker_storage.py, tests/environments/storage/test_local_storage.py, tests/environments/storage/test_memory_storage.py, tests/flows/test_parameter.py, tests/serialization/test_edges.py, tests/serialization/test_result.py, tests/tasks/aws/test_s3.py, tests/tasks/github/test_issues.py, tests/tasks/github/test_prs.py, tests/tasks/github/test_repos.py, tests/tasks/google/test_bigquery.py, tests/tasks/google/test_gcs_upload_download.py, tests/tasks/postgres/test_postgres.py, tests/tasks/redis/test_redis_tasks.py, tests/tasks/spacy/test_spacy_tasks.py, tests/tasks/test_control_flow.py, tests/test_configuration.py, tests/test_triggers.py, tests/utilities/test_executors.py, tests/utilities/test_notifications.py, tests/utilities/test_tasks.py
This PR updates unit tests to replace this pattern:
```python
with pytest.raises(ValueError) as exc:
do_something()
assert "an error" in str(exc.value)
```
with:
```python
with pytest.raises(ValueError, match="an error"):
do_something()
```
=> Replace explicit asserts with pytest functions

src/prefect/cli/get.py
Minor typo fix in `get tasks` CLI command
Clarity of help texts
=> Fix typo in help text of get tasks CLI command

CHANGELOG.md, src/prefect/config.toml, src/prefect/core/flow.py, src/prefect/environments/storage/__init__.py, tests/core/test_flow.py, tests/environments/storage/test_defaults.py
Allows for a default storage class to be set in config, which will only be instantiated (with `**kwargs`) when `flow.deploy` is called.  Note that this _does_ introduce the possibility of some opaque error messages (e.g., deploying a Flow without knowing you need Docker and seeing something about a `registry_url` requirement). 
I still think this is a value add, but open to push back.
Allows for much faster deployment processes; for example, for lightweight flows the following is now valid:
```python
from prefect import Flow
Flow("lightweight").deploy("My Project", registry_url="prefecthq/example")
```
=> Default storage

src/prefect/core/flow.py, tests/core/test_flow.py
This PR adds quotes to `pip install 'prefect[viz]'` command in error msg in `visualize()` method.
Because most of developers wants to copy/paste command from error message and command without quotes will failed.
```
$ pip install prefect[viz]
zsh: no matches found: prefect[viz]
```
=> Add quotes into visualize ImportError error msg

CHANGELOG.md, src/prefect/engine/cloud/task_runner.py, tests/engine/cloud/test_cloud_task_runner.py
This PR makes an additional call to `get_task_run_info` whenever tasks have to retry locally.  Previously, prefect context was reset to its original state, meaning the task run version that was present in context was stale on the next run, preventing the retry from actually occurring in process (instead it occurred in a new run).  Note that local retries _were_ properly working for mapped tasks because of the additional call to `get_task_run_info` that mapped tasks always perform prior to a run.
It is much more efficient to retry in the same process for short duration retries.
=> Fix local retries in Cloud to always run in-process

CHANGELOG.md, docs/guide/PINs/PIN-11-Task-Loops.md, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/signals.py, src/prefect/engine/state.py, src/prefect/engine/task_runner.py, src/prefect/serialization/state.py, tests/core/test_flow.py, tests/engine/cloud/test_cloud_flow_runner.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/test_signals.py, tests/engine/test_state.py, tests/engine/test_task_runner.py, tests/serialization/test_states.py
This PR introduces "Task Looping" (first described in [PIN 11](https://docs.prefect.io/guide/PINs/PIN-11-Task-Loops.html)).  The implementation here will actually work in Cloud almost immediately (once the Cloud serializers are updated).
In order to make Looping work off-the-shelf, this PR:
- introduces a new `Looped` state which carries the `loop_count`
- introduces a new `LOOP` signal for triggering a loop
- places the appropriate data in context (loop count + loop result)
- re-uses our `cached_inputs` mechanism for conveying relevant data to retries
- allows for loops to begin at arbitrary points by setting the appropriate …
=> TASK LOOPING (in both Core and Cloud)

src/prefect/agent/kubernetes/agent.py, src/prefect/agent/kubernetes/resource_manager.py
The flow run id needed to be a label on the pods created by a job in order to be used by error reporting of the resource manager. Also added `HTTPError` handling to the resource manager because the entire process shouldn't halt if there is an error reporting conflict.
@TylerWanner
=> Add flow run id to pod labels and handle client errors in resource manager

CHANGELOG.md, src/prefect/engine/state.py, src/prefect/engine/task_runner.py, src/prefect/serialization/state.py, src/prefect/utilities/tasks.py, tests/engine/test_state.py, tests/engine/test_task_runner.py
Paused states can have fixed expirations
Closes #1342 and allows pauses to have pre-defined expirations.
=> Paused states subclass Scheduled

CHANGELOG.md, setup.cfg, src/prefect/environments/storage/_healthcheck.py, src/prefect/environments/storage/docker.py, tests/environments/storage/test_defaults.py, tests/environments/storage/test_docker_healthcheck.py
This PR introduces new and improved health checks on Flows which are being built into docker storage.  I also refactored this so the healthchecks live in their own file and could possibly be re-used in the future, in a non-Docker world.
I was becoming increasingly worried that users would see cryptic result handler errors in deployment when tasks attempted retries, caching, etc.  This prevents Flows with "bad" result handler configurations from being deployed to Cloud at all, pre-empting the situation to begin with and ensuring the correct behavior in deployment.
Closes #1372
=> Health checks

CHANGELOG.md, src/prefect/client/client.py, src/prefect/environments/storage/_healthcheck.py, tests/client/test_client.py, tests/environments/storage/test_docker_healthcheck.py
A user had a situation in which he modified attributes of a task in a way that Core would have prevented if the same arguments were provided at task initialization. Specifically: setting a `max_retries` value without a corresponding `retry_delay`. The user then deployed the flow to Cloud. All healthchecks passed, including serialization. However, Cloud (correctly, in this case) rejected the flow as invalid. 
The issue is that the serialization healthcheck is a *cloudpickle* serialization check, not a JSON serialization check. In this case, the Flow was indeed a valid Python object -- there was nothing Pythonically "wrong" with …
=> Add test to ensure flows can be deserialized prior to depoy

CHANGELOG.md, docs/outline.toml, setup.py, src/prefect/engine/result_handlers/__init__.py, src/prefect/engine/result_handlers/azure_result_handler.py, src/prefect/serialization/result_handlers.py, tests/engine/result_handlers/test_result_handlers.py, tests/serialization/test_result_handlers.py
Adds AzureResultHandler for for handling results to / from Azure Blob storage containers.
It helps users on the Azure platform to handle results.
=> Implement AzureResultHandler

CHANGELOG.md, src/prefect/core/flow.py, tests/core/test_flow.py, tests/engine/test_flow_runner.py
#1418 updated `flow.run()` to populate scheduled start time, but had a bug in that it didn't update across scheduled runs, as identified in #1428. This fixes that bug by moving the update line into the loop.
Closes #1428.
=> Ensure the flow.run() scheduled_start_time updates with each loop

docs/guide/core_concepts/states.md
From An Hoang in Slack:
> Just a little comment on the documentation. As an ESL person, when reading https://docs.prefect.io/guide/core_concepts/states.html#state-types section I got confused a bit between state and state types. I'd propose changing it to:
"There are three main state types: Pending, Running, and Finished. Flows and tasks typically progress through these three states types. At each stage of the execution pipeline, the current state type determines what actions are taken.
Sorry if this seems like nitpicking! I don't mean to :slightly_smiling_face:
The suggested corrections are valuable, and this PR goes one step further in trying to clarify state types!
=> Update state docs

CHANGELOG.md, docs/cloud/cloud_concepts/cli.md, src/prefect/cli/auth.py, tests/cli/test_auth.py
Closes #1417 
Adds new CLI commands for working with Prefect Cloud auth
Related to changes in #1423
e.g.
```
$ prefect auth login --token MY_TOKEN
Log in successful
$ prefect auth list-tenants
NAME                        SLUG                        ID
Test Person                 test-person                 816sghf2-4d51-4338-a333-1771gns7614d
test@prefect.io's Account   test-prefect-io-s-account   1971hs9f-e8ha-4a33-8c33-64512gds86g1 
$ prefect auth switch-tenants --slug test-person
Tenant switched
$ prefect auth list-tenants
NAME                        SLUG                        ID
Test Person                 test-person …
```
=> Add new CLI auth flow w/ tests and docs

CHANGELOG.md, docs/outline.toml, src/prefect/config.toml, src/prefect/engine/__init__.py, src/prefect/engine/executors/__init__.py, src/prefect/engine/executors/base.py, src/prefect/engine/executors/dask.py, src/prefect/engine/executors/sync.py, tests/conftest.py, tests/engine/executors/test_executors.py, tests/engine/test_defaults.py
This PR implements a new `LocalDaskExecutor` for running Flows with various dask schedulers.  In addition, now that this executor supersedes `SynchronousExecutor` (and is easier to type), we will be deprecating the `SynchronousExecutor`.
Closes #1336 and allows for more fine-tuning of how your workflows should be run.
=> New executor

CHANGELOG.md, src/prefect/engine/task_runner.py, tests/core/test_task_map.py, tests/engine/test_task_runner.py
Closes #1436 
It appears we were not unpacking upstream mapped states when checking if a task was ready to proceed.  This PR fixes that and adds multiple tests.
=> Fix map retries

docs/cloud/cloud_concepts/api.md
Adds a note to the Cloud API doc about the API URL
Currently the API URL isn't specified anywhere in the Cloud docs
=> Add API URL to Cloud docs

docs/cloud/first-steps.md
Flow runs and task runs on a remote environment that hasn't been configured with the appropriate PREFECT__ environment variables will fail without very specific information as to why. This note is intended to warn users of remote environments of the need to manually configure their environment with required and optional settings, e.g. for their Dask workers.
Documentation 
Users of Prefect Cloud with remote execution environments  may be confused by failed flow runs and task runs.
=> Add note about config for Remote Environments

CHANGELOG.md, src/prefect/agent/local/agent.py, src/prefect/environments/storage/docker.py
Updates paths related to Docker registries to _always_ be POSIX regardless of OS; with these minimal changes I was able to successfully run a Local Agent on a Windows 10 machine
=> Local agent windows

CHANGELOG.md, src/prefect/environments/execution/dask/job.yaml
```
(model) ➜  model git:(chicago) ✗ kl -f prefect-dask-job-1e0579da-5fde-4c6a-adfe-ce618147bcff-c2qgb
File "<string>", line 1, in <module>
ImportError: cannot import name 'CloudEnvironment' from 'prefect.environments' (/usr/local/lib/python3.7/site-packages/prefect/environments/__init__.py)
```
=> Fix missed rename of `CloudEnvironment`

docs/generate_docs.py, src/prefect/client/client.py, tests/agent/test_local_agent.py, tests/client/test_client_auth.py, tests/core/test_flow.py, tests/serialization/test_storage.py, tests/tasks/test_shell.py, tests/test_configuration.py, tests/test_formatting.py
This PR begins our path (😉) towards full Windows compatibility.  Much of the changes here are low-hanging fruit caused by casual path manipulation.  The only painful thing is that Windows doesn't like open temporary files being written to and then read from by a separate reader.
Prefect Core has been semi-stable for Windows users for a while, but recent onboards to Cloud have shown us that our Cloud + Windows compatibility isn't very robust.  We hope to change that for the next release.  As of this PR, there are about 30 failing tests remaining, many of which only require changes to the tests, not the code itself.
=> Windows compatibility: Phase 1

CHANGELOG.md, src/prefect/agent/agent.py, tests/agent/test_agent.py, tests/agent/test_k8s_agent.py, tests/agent/test_local_agent.py, tests/agent/test_nomad_agent.py, tests/cli/test_agent.py, tests/conftest.py
Adds an exception raise if no agent API token is provided
Closes #1454 
Helps avoid cases where an agent can deploy flows without providing an API token
=> Raise AuthorizationError on missing agent token

CHANGELOG.md, src/prefect/agent/kubernetes/deployment.yaml
Closes #1468 
`prefect agent install` w/ `--resource-manager` caused the imagePullSecrets to invalidate on an empty secret name. Moving it to the top of the spec appears to fix the issue:
```
➜ prefect agent install --resource-manager | kubectl apply --namespace=default -f -
deployment.apps/prefect-agent created
```
=> Move k8s agent deployment imagePullSecrets level

CHANGELOG.md, src/prefect/engine/task_runner.py, tests/engine/test_task_runner.py
This PR adds the Task logger in context within `initialize_run` instead of only during `get_task_run_state`.  This ensures that the Task logger is available during every single pipeline step, including during cache validation.
See #1509 for an excellent description of why having a properly populated context object is important.
Closes #1509
=> Place Task logger in context earlier

CHANGELOG.md, src/prefect/agent/kubernetes/agent.py, src/prefect/cli/agent.py, tests/agent/test_k8s_agent.py, tests/cli/test_agent.py
Closes #1468 by removing the `imagePullSecrets` block if not provided
Possible kubectl issues with the YAML can be avoided that were sometimes caused when the imagePullSecrets were blank
=> Remove imagePullSecrets on k8s agent install if not provided

CHANGELOG.md, src/prefect/agent/local/agent.py, src/prefect/environments/storage/docker.py, tests/agent/test_local_agent.py, tests/environments/storage/test_docker_storage.py
Closes #1498 by skipping the push step of a Docker build if no registry URL is set. Also skip pull step of Local Agent if flow's storage has no registry URL set.
We can now avoid the push/pull workarounds by simply providing `registry_url=""` to `flow.deploy()` (or `Docker()`)
=> On empty registry_url skip Docker Storage push and Local Agent pull

CHANGELOG.md, src/prefect/engine/task_runner.py, tests/engine/cloud/test_cloud_flow_runner.py, tests/engine/test_flow_runner.py
This PR ensures that the beginning / end logs of a task run are correctly associated with their task run IDs in Cloud.
It is annoying to visit an individual Task Run page and not see logs; the logs _were_ present on the Flow Run page, just not the individual pages.
=> Task run logs

tests/test_context.py
This PR adds an explicit test that Context objects are threadsafe and can be modified from multiple concurrent threads safely.
=> Add test that contexts are thread-safe

CHANGELOG.md, src/prefect/agent/agent.py, tests/agent/test_agent.py
Closes #1500 
Logs possible platform errors that may arise when deploying a flow run
e.g. using the Fargate agent with the name of a cluster that does not exist at time of deploy:
Makes some logs easier to see without having to go to the agent itself
=> Agent Platform Error Logs for Flow Runs

src/prefect/agent/agent.py, tests/agent/test_agent.py
Handles the situation where the error to be logged isn't dependent upon a flow run being deployed
```
During handling of the above exception, another exception occurred:
File "/usr/local/bin/prefect", line 10, in <module>
sys.exit(cli())
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File …
```
=> Handle agent error logging for no flow runs found

CHANGELOG.md, src/prefect/agent/agent.py, src/prefect/agent/fargate/agent.py, src/prefect/agent/kubernetes/agent.py, src/prefect/agent/local/agent.py, src/prefect/cli/agent.py, src/prefect/config.toml, tests/agent/test_agent.py, tests/cli/test_agent.py
Closes #1501 
Adds new agent log level config option
`prefect agent start --verbose/-v` to enable or `config.cloud.agent.level`
Allows for finer grained logging from the agent
=> Add Verbose Agent Logging Option

CHANGELOG.md, docs/core/task_library/azure.md, docs/outline.toml, src/prefect/tasks/azure/__init__.py, src/prefect/tasks/azure/blobstorage.py, tests/tasks/azure/__init__.py, tests/tasks/azure/test_blobstorage.py
Adds Azure Blob Storage tasks.
Azure Blob Storage users can upload and download stuff.
=> Add Azure Blob Storage tasks

CHANGELOG.md, src/prefect/client/client.py, src/prefect/utilities/exceptions.py, tests/client/test_client_auth.py
If users attempt to instantiate a Client with an invalid token and active tenant stored, the Client will (correctly) raise an error. However, because the error is raised during initialization it will not be possible to load the client object fully. This PR intercepts `AuthorizationErrors` when the Client is instantiated and clears the saved tenant id (but not the token, in case it is still valid). 
The use case:
- User logs in to a tenant with a token and saves those settings
- User is removed from the tenant, but the token remains valid
- User loads a new Client object; it should gracefully handle the invalid login attempt
=> Add check to gracefully handle failed login attempts

.circleci/config.yml, dev-requirements.txt, docs/.vuepress/config.js
This PR introduces Algolia search to our Documentation.  This superpowers our search bar!  This will allow me to also introduce "stop_urls" to prevent indexing of archived API documentation (I have to make a PR against another repo where our configuration lives to do this).
Will eventually address https://github.com/PrefectHQ/prefect/issues/1119 by removing archived docs from our search index
=> Add Algolia search to our docs

CHANGELOG.md, setup.cfg, src/prefect/engine/cloud/utilities.py, src/prefect/engine/state.py, src/prefect/engine/task_runner.py, src/prefect/serialization/state.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/cloud/test_utilities.py, tests/engine/test_state.py, tests/engine/test_task_runner.py
This PR adds `cached_inputs` to all `Failed` states.  When running in Cloud, Prefect will only call the input data's result handlers if _all_ are present, otherwise it will silently pass and not persist the upstream inputs.
This PR stores Failed state upstream inputs if possible, and passes if not.  This sets the stage for _manual_ retries in Prefect Cloud.  e.g., if my task failed very unexpectedly, I might want to rerun it manually.  Prior to this PR, if your task had upstream inputs that would _never_ work.  However, with this PR, as long as you set result handlers appropriately this situation will be possible with no …
=> Failed state inputs

CHANGELOG.md, src/prefect/tasks/kubernetes/deployment.py, src/prefect/tasks/kubernetes/job.py, src/prefect/tasks/kubernetes/pod.py, src/prefect/tasks/kubernetes/service.py, tests/tasks/kubernetes/test_deployment.py, tests/tasks/kubernetes/test_job.py, tests/tasks/kubernetes/test_pod.py, tests/tasks/kubernetes/test_service.py
QA'd the k8s tasks and found that the API secret was required, adjusted so it can be provided as None. This required tests to be updates slightly. Also added tests for each task's in/out of cluster configuration connections.
Secret was required and some connection options went untested
=> QA Kubernetes Tasks

CHANGELOG.md, src/prefect/engine/task_runner.py, tests/engine/test_task_runner.py, tests/utilities/test_debug.py
The `raise_on_exception` no longer re-raises Prefect Signals during execution.
This PR helps target the re-raises to "unexpected" errors, for a better debugging experience when using things like `switch` control flow tasks.
=> Raise on exception no longer raises for prefect signals

CHANGELOG.md, src/prefect/engine/state.py, src/prefect/engine/task_runner.py, tests/core/test_flow.py, tests/engine/test_state.py, tests/serialization/test_states.py
This PR persists `task_run_count` within the newly introduced `state.context` attribute for communicating the current run count across multiple state transitions (e.g., Retrying -> Paused -> Resume -> Running -> Failed -> Retrying -> etc.).   Note that this PR only attaches this data to `Scheduled` states, as attaching it to other states causes the run count to effectively "freeze" across runs.
Closes #1177
=> Persist task_run_count using state context

src/prefect/engine/state.py, src/prefect/serialization/state.py, tests/engine/test_state.py, tests/serialization/test_states.py
@cicdw I know you explicitly left this out in #1567 but I can quickly create situations in which information missing from context leads to inconsistencies, so I think all states should share the same base attributes (including Context). If necessary, we could take steps to populate metastate context from the wrapped state context, but I don't think it's warranted now.
For example, even though it's never done on purpose, setting a `Running` state to a `Submitted` state would fail to package tags.
=> Support context init kwarg for metastates

CHANGELOG.md, src/prefect/client/client.py, src/prefect/config.toml, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/state.py, tests/client/test_client.py, tests/engine/cloud/test_cloud_flow_runner.py, tests/engine/cloud/test_cloud_flows.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/test_state.py
This PR:
- adds two new methods to the Prefect Python Client for getting / setting task tag concurrency limits
- introduces logic for in-process retries of Queued states, which arise out of concurrency limits being hit in Prefect Cloud
- introduces a new config var for specifying how long Queued states should wait before retrying their run
- adds some new tests
Task Throttling / Concurrency Limiting is a very popular request, and will now be a first-class feature in Prefect Cloud.  Note to any Cloud users watching: this will not be made widely available until the next Cloud release.
=> Introducing: Task Tag throttling (in Prefect Cloud)

docs/core/concepts/results.md
This PR adds a sentence clarifying what "safe" means in the context of `safe_value`. It also removes double-spaces in between sentences by virtue of autoformatting-- let me know if the double-spacing was intentional.
Calling `safe_value` "safe" implies that there might be something unsafe about the rest of `Result`. While this is admittedly a small change, clarifying the context in which `safe_value` is safe could be helpful.
=> Clarify what safe means for safe_value

CHANGELOG.md, src/prefect/agent/kubernetes/agent.py, src/prefect/cli/agent.py, tests/agent/test_k8s_agent.py
Default's the generated agent k8s YAML to use a prefect docker image pinned to your local version
Consistency and to prevent redeploy issues on k8s if there is a new latest image built off of master
=> Pin prefecthq/prefect image version on agent deployment yaml

src/prefect/engine/cloud/task_runner.py, src/prefect/utilities/graphql.py, tests/utilities/test_graphql.py
This PR replaces the `CloudTaskRunner`'s recursive run calls with a while loop, so that tasks can remain queued / retrying for extended periods of time without running into recursion errors.  Also reintroduces the old `GraphQLResult` reprs because I personally really enjoyed those and used them often.
Closes #1575
=> Two tweaks - remove recursion and update GraphQLResult repr

CHANGELOG.md, src/prefect/engine/flow_runner.py, tests/engine/cloud/test_cloud_flow_runner.py, tests/engine/test_flow_runner.py, tests/tasks/test_control_flow.py
This PR greedily wraps Constant tasks in `Success` states to prevent their submission for "execution", thereby greatly reducing noise in logs and also time spent "running" the constants.
Closes #1527; working on this also exposed a large number of edge cases for Prefect Cloud that I will be investigating ASAP
**cc:** @bnaul
=> Don't submit constant tasks

src/prefect/tasks/control_flow/conditional.py
Closes #1565 by adding a simple docstring example to the `switch` task
=> Add switch task example docstring to task

CHANGELOG.md, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/result.py, src/prefect/engine/result_handlers/result_handler.py, src/prefect/engine/task_runner.py, src/prefect/serialization/result_handlers.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/result_handlers/test_result_handlers.py, tests/engine/test_result.py, tests/engine/test_task_runner.py, tests/serialization/test_result.py, tests/serialization/test_result_handlers.py
This PR seems small and weird, but it actually fixes a subtle issue: Cached / Retry / Failed states cache their inputs using the upstream task's result handler corresponding to each input.  The caching aspect worked just fine.  However, in future runs, if a Custom Result Handler (i.e., one which was user-written and not in the Prefect library) was used upstream, then whenever the state with `cached_inputs` was _deserialized_ from Cloud, the custom result handler was not present.  This PR always extracts the result handler from the upstream Task and uses it (if present) when hydrating cached inputs.  This required a few minor …
=> Custom result handler upgrades

CHANGELOG.md, src/prefect/cli/run.py, tests/cli/test_run.py
Adds a `--parameters` option to the `prefect run cloud` CLI command for flow run parameter specification. Takes in a json file of parameters to use.
I chose to go the route of providing a parameter file specification and am open to adding other methods if desired. This felt more natural.
Closes #1551 
Previously we were unable to specify parameters for this function
=> Add Parameter File Option to `run cloud` CLI command

CHANGELOG.md, src/prefect/engine/executors/dask.py
Reverts PrefectHQ/prefect#1589
This PR did not actually solve the bottleneck problem that I expected.  Hence I'd rather revert it and consider a more wholistic fix, instead of risking altering behavior.
=> Revert "Faster maps"

CHANGELOG.md, docs/outline.toml, src/prefect/environments/__init__.py, src/prefect/environments/execution/__init__.py, src/prefect/environments/execution/fargate/__init__.py, src/prefect/environments/execution/fargate/fargate_task.py, src/prefect/serialization/environment.py, tests/environments/__init__.py, tests/environments/execution/test_fargate_task_environment.py, tests/serialization/test_environments.py
Adds the `FargateTaskEnvironment`
Closes #1549 
Works in a similar way to the `KubernetesJobEnvironment` by allowing users to specify completely custom task definitions for their flow runs
=> Fargate Task Environment

CHANGELOG.md, docs/core/task_library/azureml.md, docs/outline.toml, setup.py, src/prefect/tasks/azureml/__init__.py, src/prefect/tasks/azureml/dataset.py, src/prefect/tasks/azureml/datastore.py, tests/tasks/azureml/__init__.py, tests/tasks/azureml/test_dataset.py, tests/tasks/azureml/test_datastore.py
It adds tasks to work with Azure Machine Learning Service, and more specifically Datasets and Datastores.
Helps Azure ML service users to register and update datastore and datasets from Prefect.
=> Implement Azure ML Service tasks

CHANGELOG.md, src/prefect/tasks/shell.py, tests/tasks/test_shell.py
This PR adds a new `return_all` flag to the `ShellTask` for optionally returning all lines of stdout; also updates the Changelog following the 0.6.6 release.
There are situations in which this is useful.
=> ShellTask Return all lines

CHANGELOG.md, src/prefect/core/flow.py, tests/core/test_flow.py
Flows which:
- run with `run_on_schedule=False`
- have a cached task
would error out with:
```
AttributeError: 'Context' object has no attribute 'caches'
```
because of the place that we set this key.  This PR moves that key-setting to a more universal location and adds a test.
For local development and testing!
=> Fix minor bug involving locally cached tasks and no schedule

CHANGELOG.md, docs/core/task_library/azure.md, src/prefect/engine/result_handlers/azure_result_handler.py, src/prefect/tasks/azure/__init__.py, src/prefect/tasks/azure/blobstorage.py, src/prefect/tasks/azureml/datastore.py, tests/engine/result_handlers/test_result_handlers.py, tests/tasks/azure/test_blobstorage.py, tests/tasks/azureml/test_datastore.py
Allows authentication to Azure Blob Storage using SAS tokens. This concerns `AzureResultHandler` as well as the tasks `BlobStorageDownload`, `BlobStorageUpload`, and `DatastoreRegisterBlobContainer`.
Allows Blob Storage users to authenticate more securely.
=> Allow authentication to Azure Blob Storage using SAS token

appveyor.yml
Adds an Appveyor job to our PRs.  This will test our most basic Windows functionality on Python 3.6.
Of course, we can always add to this by:
- including formatting tests
- installing _all_ extras to ensure Windows compatibility with the extended Task Library
- test against more Python versions
but this will get us started and in a good place to confidently ensure Windows compatibility. Closes #1576
=> Introducing: Appveyor jobs

CHANGELOG.md, docs/cloud/agent/fargate.md, src/prefect/agent/fargate/agent.py, tests/agent/test_fargate_agent.py
This PR adds in functionality to support temporary credentials and IAM role based credentials to the Fargate agent by introducing the aws_session_token per documentation found here: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
This is important because using the existing state of the agent does not allow you to use temporary credentials. Also, it should never be required to supply access keys when using a library inside of AWS compute.
=> Enhancement Fargate Agent - temporary credentials 

CHANGELOG.md, appveyor.yml, docs/core/concepts/configuration.md, src/prefect/client/secrets.py, src/prefect/configuration.py, tests/client/test_secrets.py, tests/test_configuration.py
This PR ensures that secrets set through environment variable retain their casing when placed in Context.
Closes #1601 - using ephemeral environment variables for setting local secrets provides slightly better security than hardcoding them into config, and also feels more natural.  Previously, secret names would also get lower-cased, preventing many system secrets from being set this way (e.g., `SLACK_WEBHOOK_URL`, etc.)
=> Special case secrets in environment

CHANGELOG.md, src/prefect/tasks/control_flow/conditional.py, tests/tasks/test_control_flow.py
This PR updates the `merge` task to do an `isinstance` check instead of a direct comparison; this allows for the merge task to work with objects that don't have a robust `__bool__` method such as pandas dataframes and numpy arrays.
We should strive to be agnostic to what types of objects tasks return
=> Fix issue with merge task and comparisons

CHANGELOG.md, docs/cloud/agent/fargate.md, src/prefect/agent/fargate/agent.py, tests/agent/test_fargate_agent.py
- [x ] adds new tests (if appropriate)
- [x ] updates `CHANGELOG.md` (if appropriate)
This PR makes a few changes to the Fargate Agent. The first change is that it allows subnets and security groups to be set based on environment variables. The second change is that it adds two AWS configuration options to the Fargate Agent: `task_role_arn` and `execution_role_arn`.
This PR is important because Fargate requires the task definition to have execution role ARN to support ECR images. These …
=> Fargate Agent configuration options enhancements

CHANGELOG.md, src/prefect/agent/agent.py, src/prefect/agent/fargate/agent.py, src/prefect/agent/kubernetes/agent.py, src/prefect/agent/local/agent.py, src/prefect/agent/nomad/agent.py, src/prefect/cli/agent.py, src/prefect/config.toml, tests/agent/test_agent.py, tests/agent/test_fargate_agent.py, tests/agent/test_k8s_agent.py, tests/agent/test_local_agent.py, tests/agent/test_nomad_agent.py, tests/cli/test_agent.py
Closes #1611 
Adds a `name` init arg to agents that can also be set through the `AGENT_NAME` environment variable
Being able to name agents is a great tiny feature to have for division of work and clarity.
=> Add Optional "Name" to Agents

CHANGELOG.md, docs/core/task_library/azure.md, docs/outline.toml, setup.py, src/prefect/tasks/azure/__init__.py, src/prefect/tasks/azure/cosmosdb.py, tests/tasks/azure/__init__.py, tests/tasks/azure/test_blobstorage.py, tests/tasks/azure/test_cosmosdb.py
Add Azure Cosmos DB tasks.
Helps Azure Cosmos DB users create and query data as part of their Flows.
=> Cosmosdb tasks

CHANGELOG.md, src/prefect/client/client.py
This PR adds the `delete_task_tag_limit` method to the client. 
As it stands, we have methods to get and update task tag limits via the client, but not to delete them. It's a bit add to make users use GraphQL for this one case in particular, so adding the method to the client streamlines UX.
=> Add the ability to delete task tag limits

CHANGELOG.md, src/prefect/agent/fargate/agent.py, tests/agent/test_fargate_agent.py
Updates the fargate agent to handle non-specified ARNs and relaxes the logger warning if not specified
Closes #1625 
Closes #1624 
UX
=> Default fargate ARNs to empty string and relax logger warning

src/prefect/agent/local/agent.py
This PR upgrades a few local agent logs to INFO.  As we move towards complete self-service onboards and use the local agent as a learning opportunity,  I want to make sure the default settings for this agent are maximally helpful.   In this case, users will now see what the agent is doing more transparently, without having to update their Prefect user config to `DEBUG` logging level.
=> Upgrade some local agent logs to info

docs/.vuepress/config.js, docs/cloud/concepts/flow_runs.md, docs/cloud/flow-deploy.md, docs/cloud/the-basics.md, src/prefect/tasks/shell.py, tests/tasks/test_shell.py
Adds documentation on building an running a Cloud Flow locally and deploying it to Cloud.  Also slightly reorganizes the Cloud docs to a more natural order.
Closes #1594
=> Add documentation on a full flow deploy to Cloud

.circleci/config.yml, CHANGELOG.md, Dockerfile, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
- Reduces the docker image size from ~900MB to ~490MB by leveraging the `python:*-slim` images (addressing #1638 ).
- Introduces a prefect docker image for each supported python version (3.5, 3.6, and 3.7) which are built on each tagged master commit.
This cuts down the time it takes to pull down the prefect image for the first time, thus getting users to their first flow faster.
=> Reduce docker image size

CHANGELOG.md, src/prefect/agent/agent.py, src/prefect/environments/execution/base.py, src/prefect/environments/execution/dask/k8s.py, src/prefect/environments/execution/fargate/fargate_task.py, src/prefect/environments/execution/k8s/job.py, src/prefect/environments/execution/local.py, src/prefect/environments/execution/remote.py, src/prefect/environments/storage/_healthcheck.py, src/prefect/environments/storage/docker.py, tests/environments/execution/test_base_environment.py, tests/environments/execution/test_dask_k8s_environment.py, tests/environments/execution/test_fargate_task_environment.py, tests/environments/execution/test_k8s_job_environment.py, tests/environments/execution/test_local_environment.py, tests/environments/execution/test_remote_environment.py, tests/environments/storage/test_docker_healthcheck.py, tests/environments/storage/test_docker_storage.py
Adds a new healthcheck for environment specific dependencies. These are exposed through the `.dependencies` property on environments
Closes #1623 
This allows us to remove some required dependencies from the docker storage build step and is a great notifier for users of certain environments
=> Environment Dependency Healthcheck

CHANGELOG.md, src/prefect/client/secrets.py, tests/client/test_secrets.py
This PR fixes an issue we've seen where secrets set from e.g., the UI are sometimes preserved as strings when they should be interpreted as JSON documents.
Makes the full life cycle of secrets more polished.
=> Attempt to parse cloud secrets as JSON first

CHANGELOG.md, src/prefect/cli/agent.py, tests/agent/test_agent.py
Ensures that agent configuration settings are respected regardless of whether `--verbose` was passed or not
Env vars can be easier than CLI flags
=> Agent log fix

CHANGELOG.md, src/prefect/client/client.py
Updates the Client requests to have a default timeout of 30 seconds
Without providing a timeout it has the potential to hang indefinitely
=> Add default 30s timeout to client requests

CHANGELOG.md, docs/core/task_library/google.md, src/prefect/tasks/airtable/__init__.py, src/prefect/tasks/airtable/airtable.py, src/prefect/tasks/dropbox/__init__.py, src/prefect/tasks/dropbox/dropbox.py, src/prefect/tasks/github/__init__.py, src/prefect/tasks/github/issues.py, src/prefect/tasks/github/prs.py, src/prefect/tasks/github/repos.py, src/prefect/tasks/google/__init__.py, src/prefect/tasks/google/bigquery.py, src/prefect/tasks/google/storage.py, src/prefect/tasks/twitter/__init__.py, src/prefect/tasks/twitter/twitter.py, tests/tasks/airtable/test_airtable.py, tests/tasks/dropbox/test_dropbox.py, tests/tasks/github/test_issues.py, tests/tasks/github/test_prs.py, tests/tasks/github/test_repos.py, tests/tasks/google/test_bigquery.py, tests/tasks/google/test_gcs_copy.py, tests/tasks/google/test_gcs_upload_download.py, tests/tasks/twitter/test_twitter.py
Closes #1669 by adding support for passing values directly to various task library tasks.
This PR attempts to maintain all prior behavior, just raising a `warning` if the secret name is passed instead of a value.
In addition, it's a little noisy because it coincides with the release of a new version of `black`
=> Add support for directly-passing secrets to task library tasks

CHANGELOG.md, docs/cloud/deployment.md, src/prefect/core/flow.py, tests/core/test_flow.py
This PR introduces a `save` / `load` interface to Flows for a smoother deployment experience.
Some users were annoyed with `cloudpickle`'s behavior if you create a Flow in a file called "my_flow.py" and then imported that flow inside "my_deploy.py" like `from my_flow import flow`, deploy health checks would fail.  This is because `cloudpickle` sees your flow's logic as living inside a module called "my_flow".  
Using the new `save / load` interface allows users to save their flow at build time, so that cloudpickle correctly manages the imports.
=> Flow save / load

CHANGELOG.md, src/prefect/agent/fargate/agent.py, tests/agent/test_fargate_agent.py
Updates the Fargate Agent boto3 access kwargs to default to `None`
Properly parses env vars that may be in forms such as lists and dicts
Not providing certain access kwargs was failing on initialization of the boto3 client and not properly parsing certain env vars was rendering them useless
=> Adjust Fargate Agent defaults and env var parsing

CHANGELOG.md, src/prefect/environments/execution/fargate/fargate_task.py, tests/environments/execution/test_fargate_task_environment.py
Adds the option to specify an `aws_session_token` for the FargateTaskEnvironment
This is useful when in an IAM / ARN setup
=> Add `aws_session_token` kwarg to FargateTaskEnvironment

CHANGELOG.md, src/prefect/client/client.py, tests/client/test_client.py, tests/client/test_client_auth.py
This PR adds an informative header to all Cloud client requests: `X-PREFECT-CORE-VERSION=<version>`
=> Add version header to all client requests

CHANGELOG.md, src/prefect/core/flow.py, src/prefect/environments/storage/docker.py, src/prefect/environments/storage/local.py, tests/core/test_flow.py, tests/environments/storage/test_docker_storage.py, tests/serialization/test_storage.py
This PR improves upon the save / load interface for flows by:
- introducing a sensible default save location which just happens to coincide with the save location inside Docker storage objects ;) 
- introducing a sensible inference pattern on load so that absolute paths, flow names, and slug-ified flow names are all acceptable inputs 
- uses the save / load interface inside Local storage
=> Improvements to Flow save / load interface

CHANGELOG.md, src/prefect/core/flow.py, src/prefect/environments/storage/local.py, tests/core/test_flow.py
This PR auto-labels flow environments with a slugified flow name whenever `Local` storage is used.
Using local storage greatly restricts what types of agents can run the work - this PR pre-emptively helps with that.
=> Local storage labels

CHANGELOG.md, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
Currently no prefect installation is attempted if you are providing your own image. This change attempts to install prefect if it is not already installed, regardless of the base image. This closes #1698 .
This makes deploying a flow easier --provide an image with what you need to run whats contained within a task, prefect will bring what it needs to run.
=> Always attempt to install prefect in base image

CHANGELOG.md, Dockerfile
Removes the default python version from the dockerfile. This should always be explicitly provided by CircleCI (or the user for manual builds)
This ensures the proper images are built and tagged, preventing unexpected image contents.
=> Remove default version for Python in Docker builds

src/prefect/tasks/database/__init__.py
Small warning for an issue that could arise in some distros of Linux where python was compiled without sqllite3
=> Add warning for missing sqlite3 dependency for sqlite tasks

CHANGELOG.md, src/prefect/utilities/context.py, tests/test_context.py
This PR raises an informative error whenever `context` is pickled.  Closes #1710 
Users are tempted to use context like:
```python
from prefect import context
@task
def my_fn():
logger = context['logger']
```
and submit such tasks to dask.  This is problematic, because if we freeze context (which is what this import pattern effectively does), we lose all the dynamic information that is placed into context by the various runners.  
Consequently, users should _always_ access context as an attribute of the top-level module so that dynamically added keys will be available.
This PR raises an informative error for how to access …
=> Raise informative error whenever context is pickled

docs/cloud/concepts/graphql.md
Example doesn't run, this appears to fix it.
As a side note: for someone pretty unfamiliar with GraphQL (<--), even with these docs it's pretty intimidating to try to figure out what kinds of things could be done through the API :)
=> Fix GraphQL doc typo

CHANGELOG.md, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
=> Fix issue with user config path being overwritten in docker storage

CHANGELOG.md, src/prefect/environments/execution/dask/k8s.py, src/prefect/environments/execution/k8s/job.py, tests/environments/execution/test_dask_k8s_environment.py, tests/environments/execution/test_k8s_job_environment.py
Adds an `identifier_label` property to the Dask Kubernetes Environment and Kubernetes Job Environment.
The `identifier_label` was not being recreated on each run due to the way environments are stored on the Flow now
=> Add identifier_label property to relevant environments

CHANGELOG.md, src/prefect/utilities/executors.py, tests/utilities/test_executors.py, tests/utilities/test_logging.py
This PR introduces two new `ERROR` logs for heartbeats in the event that a failure or thread death occurs.
There are situations involving dask worker clients that appear to cause either a GIL deadlock or thread death, resulting in Zombied task / flow runs.  While we haven't isolated the root cause yet, the absence / presence of these logs would help in debugging this and any future heartbeat related issues.
=> Add informative error logs if heartbeat thread fails or dies

CHANGELOG.md, src/prefect/agent/agent.py
For most local agents, especially during testing, users tend to use CTRL+C or some other keyboard interrupt signal to kill a running agent.  This PR adds a graceful shutdown mode for all agents when a keyboard interrupt is passed.  It prints agent is shutting down and waits for the final loop to process.
Better user experience.
=> Graceful agent shutdowns

CHANGELOG.md, src/prefect/agent/local/agent.py, tests/agent/test_local_agent.py
This PR proactively fails flow runs from the local docker agent if there are issues with the Flow's storage, including an image pull error.
Previously we simply logged the error and waited for Lazarus to come along and reschedule the flow, which typically just results in the flow run eventually failing after some time.  Users expect an image pull error to immediately translate to a flow run failure.  Closes #1395
=> Proactively fail flow runs if there is an issue with flows storage

CHANGELOG.md, src/prefect/tasks/control_flow/conditional.py, tests/tasks/test_control_flow.py
Currently `merge(a, b)` randomly returns either `a` or `b` if both tasks have results. However, the docs say:
> The merge will return the first real result it encounters, or None.
which to me implies that the result in that case should be `a`. The randomness comes from the fact that task results come from edges, which are stored as a set, which have non-deterministic ordering.
@cicdw mentioned this is maybe not the original intended use of `merge`, but to me it feels valid and the docs definitely suggest that this should work. Also less randomness in results when re-running some flows seems desirable.
=> Respect order of inputs in merge

CHANGELOG.md, docs/cloud/agent/fargate.md, setup.py, src/prefect/cli/agent.py, tests/cli/test_agent.py
Closes #1734 
`prefect agent start` now accepts kwargs. This is useful for users when providing the configuration options for the Fargate Agent.
e.g. 
```bash
$ prefect agent start fargate cpu=$CPU memory=$MEMORY networkConfiguration=$NETWORK_CONFIGURATION
```
Having to provide kwargs in the boto3 camel casing convention could potentially lead to conflicts in environment variable names when using external tooling (e.g. Terraform) to deploy the Agent. 
Instead of having to do:
```bash
$ export memory=512
$ prefect agent start fargate
```
There is now the option to use custom names:
```bash
$ export AGENT_MEMORY=512
$ prefect …
```
=> `agent start` CLI command now allows for kwargs

setup.py
In #1737 the `google-cloud-storage` was pinned to below `1.23.0` due to some conflicts with `google-cloud-bigquery`
https://github.com/googleapis/google-cloud-python/pull/9788
=> Relax google storage dependency bounds

CHANGELOG.md, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
This PR exposes a new `dockerfile` keyword argument for users to provide a custom dockerfile for flow docker storage. 
Allows for better more efficient control of Docker images for flows instead of having to first build a base image.
=> Allow users to provide a Dockerfile instead of a base image

requirements.txt
It seems that some python packages install older versions of `urllib3` that are incompatible with our Python client.  This PR bounds `urllib3` from below in our `requirements.txt` so that users don't have to go on a bug hunt!
=> Bound urllib3 below due to an issue in older versions

CHANGELOG.md, docs/cloud/execution/fargate_task_environment.md, docs/cloud/execution/k8s_job_environment.md, src/prefect/environments/execution/dask/job.yaml, src/prefect/environments/execution/fargate/fargate_task.py, src/prefect/environments/execution/k8s/job.py, tests/environments/execution/test_fargate_task_environment.py, tests/environments/execution/test_k8s_job_environment.py
Updated the commands for a few environments which were calling `run_flow` on a new Environment object
If a new Environment object is created on each run then some of the information stored on the environment won't persist. This is mainly an issue in specifying things like `min_workers` and `max_workers` on the `DaskKubernetesEnvironment`.
=> Update Environment `run_flow` call to use Flow's original Environment

CHANGELOG.md, docs/core/concepts/persistence.md, src/prefect/cli/run.py, tests/cli/test_run.py
Adds the option to specify a `--run-name / -rn` for a Cloud Flow run.
e.g. `prefect cloud run -n Flow -p Project --run-name NAME` will create a flow run named `NAME`
Extra option that needed to be exposed from the CLI :)
=> Add run_name option to cloud run CLI command

CHANGELOG.md, src/prefect/environments/execution/dask/k8s.py, tests/environments/execution/test_dask_k8s_environment.py
Adds a kwarg for `work_stealing` to the Dask Kubernetes Environment. Previously this _always_ defaulted to 'False'
There are some cases in which users want to enable work stealing.
=> Allow for dask work stealing to be toggles in Dask Kubernetes Environment

CHANGELOG.md, src/prefect/environments/execution/dask/k8s.py, tests/environments/execution/test_dask_k8s_environment.py
Similar to the default scheduler name, providing a custom scheduler spec will be given a unique name corresponding to the `identifier_label`
This ensures that multiple flow runs can share the same scheduler spec and exist simultaneously without conflicting job names
=> Set unique scheduler name for DaskKubernetesEnvironment

CHANGELOG.md, src/prefect/engine/executors/dask.py, tests/engine/executors/test_executors.py
Mapping using the `LocalDaskExecutor` w/ _scheduler='processes'_ was causing the multithreading error `'daemonic processes are not allowed to have children'`. This updates the executor to raise a more informative error.
`'daemonic processes are not allowed to have children'` is pretty vague and this now raises and error which offers a solution.
=> Raise informative error for mapping over processes w/ LocalDaskExecutor

docs/.vuepress/config.js, docs/cloud/other-considerations.md, docs/cloud/the-basics.md, docs/cloud/upandrunning.md, docs/core/welcome/community.md
- Adds some basic info about Prefect Cloud and links to info about Prefect and Prefect Core in the first page of the Prefect Cloud Docs.  
- Moves the current content of "the basics" to a new page called "other things to consider" as it's not really the basics and as a new user it contained information that was slightly confusing/superfluous to what I needed to get up and running. 
- Although most users come through Prefect Core, if a user is interested in Prefect Cloud and goes straight to the Prefect Cloud section of the docs, we should give them some sort of introduction and make them feel that getting started is simple.
=> Makes Cloud first-page in docs more user friendly

CHANGELOG.md, src/prefect/core/flow.py, tests/core/test_flow.py
This PR fixes an issue with visualizing mapped flows whose mapped task is in a non-mapped state.
Closes #1765
=> Visualization Fix

CHANGELOG.md, src/prefect/core/flow.py, tests/core/test_flow.py, tests/engine/cloud/test_cloud_task_runner.py
This PR fixes an issue caused by the latest refactor to how Prefect handles constants: in short, now that constants are stored as a flow attribute we need to also transfer these over when calling `flow.update`.
Fixes an issue raised by a user in Slack.
=> Fix issue with flow.update not transferring constants

CHANGELOG.md, src/prefect/utilities/executors.py, tests/core/test_flow.py, tests/engine/test_task_runner.py, tests/utilities/test_executors.py
This PR revisits our old timeout code with some smarter detection of when each handler is the appropriate choice.  In particular, this PR returns to the hard enforcement of timeouts in most situations, except for those where the task was submitted to run in a daemonic subprocess (in which case we don't have a good way of "managing" the run and killing it).  In this event, I added a helpful warning and I recommend any users to use a state handler which detects the `TimedOut` state and takes any necessary action (which will vary from use case to use case).
Soft timeout enforcement was unexpected.
Closes #1145 
Closes #1686 …
=> Better timeouts

tests/conftest.py
This is an attempt at solving for the non-deterministic appveyor job failure which isn't an actual test failure but rather a failure during Dask cleanup.
=> Attempt to close the client gracefully in test fixtures

CHANGELOG.md, src/prefect/environments/storage/__init__.py, src/prefect/environments/storage/gcs.py, src/prefect/serialization/storage.py, src/prefect/utilities/exceptions.py, tests/environments/storage/test_gcs_storage.py, tests/serialization/test_storage.py
Adds a new storage option for Google Cloud Storage.
This allows the user to delegate flow storage to a remote backend.
=> Add Google Cloud Storage backend

src/prefect/client/client.py, tests/client/test_client.py, tests/environments/storage/test_gcs_storage.py
Quick fix to readd `client.deploy` w/ a deprecation warning
=> Reimplement client.deploy w/ deprecation warning

CHANGELOG.md, docs/cloud/agent/kubernetes.md, docs/cloud/agent/local.md, docs/cloud/tutorial/k8s.md, src/prefect/agent/kubernetes/agent.py, src/prefect/agent/kubernetes/rbac.yaml, src/prefect/cli/agent.py, tests/agent/test_k8s_agent.py, tests/cli/test_agent.py
Adds a `--rbac` flag to the `prefect agent install kubernetes` command for a default RBAC configuration. Also updated the documentation with the proper Role and RoleBinding YAML.
Closes #1487 
This makes it easier and more clear on the RBAC required to use the Kubernetes Agent
=> Kubernetes Agent install default RBAC option

src/prefect/agent/docker/agent.py, tests/agent/test_docker_agent.py
After #1815 there was one missing place where the Flow Run name was not specified on the Docker Agent
=> Add flow run name to env vars set by Docker Agent

CHANGELOG.md, src/prefect/agent/kubernetes/agent.py, src/prefect/cli/agent.py, tests/agent/test_k8s_agent.py, tests/cli/test_agent.py
Adds a `--latest` flag for the `prefect agent install kubernetes` command to use the latest Prefect image
Adds the option to use the most recent image if desired
=> Add `--latest` flag for Kubernetes Agent CLI install command

CHANGELOG.md, src/prefect/utilities/logging.py, tests/engine/cloud/test_cloud_flow_runner.py, tests/utilities/test_logging.py
This PR ensures that a single bad non-JSON serializable log doesn't prevent further logs from arriving in Cloud.
A user was attempting to log bytes from a subprocess, and all logs stopped arriving in Cloud (because bytes aren't JSON serializable).  This is undesirable behavior, and as many logs as possible should be getting through.
=> Make logging to Cloud more robust in the face of a bad log

setup.py
Bumps the upper bound of the kubernetes optional dependency. I tested deployments with newer versions and all went well 👍 
Closes #1493
=> Bump kubernetes upper bound to 11.0.0b2

CHANGELOG.md, src/prefect/core/task.py, tests/core/test_task.py, tests/utilities/test_configuration.py
This PR enforces the provision of a `max_retries` argument if `retry_delay` is specified for a task.
If a user is specifying a retry delay, they're probably expecting their task to retry. The current default behavior of setting max retries to 0 if not provided isn't sensible.
=> Enforce max_retries if retry_delay specified

tests/utilities/test_executors.py
These fail occasionally and tests should provide a strong signal, not a noisy one.
=> Relax two brittle tests

CHANGELOG.md, src/prefect/schedules/clocks.py, tests/schedules/test_clocks.py
IntervalClock should allow any interval greater than 0.
60 seconds was an arbitrary time period. Some applications can use short intervals.
=> Allow intervals less than 60 seconds

src/prefect/schedules/clocks.py, src/prefect/serialization/schedule.py, tests/schedules/test_clocks.py, tests/serialization/test_schedules.py
Follows up on https://github.com/PrefectHQ/prefect/pull/1880 with some doc / serialization changes to ensure Prefect Cloud requirements are unchanged.
=> Validate interval clocks for cloud deployment

CHANGELOG.md, src/prefect/engine/result_handlers/s3_result_handler.py, src/prefect/tasks/aws/s3.py, tests/engine/result_handlers/test_result_handlers.py, tests/serialization/test_result_handlers.py, tests/tasks/aws/test_s3.py
This PR changes how all S3 hooks authenticate with AWS; in particular, it removes the requirement that users store their AWS credentials in a Prefect Cloud Secret and allows for the standard boto3 auth chain.  Note that this resulted in a breaking change - S3 tasks and handlers that relied on the default value for `aws_credentials_secret` will need to explicitly provide it.
Gives users control over how the authenticate with AWS and allows for a more natural authentication strategy, especially when running Flows in AWS.
=> AWS Auth changes

docs/cloud/concepts/flows.md
This PR updates cloud docs for flow settings to reflect the fact that version locking is now opt-in.
It's important to have up-to-date and accurate docs.
=> Update docs to reflect that version locking is opt-in

CHANGELOG.md, requirements.txt, src/prefect/core/flow.py, src/prefect/engine/result.py, src/prefect/engine/result_handlers/result_handler.py, src/prefect/engine/task_runner.py, src/prefect/tasks/control_flow/conditional.py, src/prefect/tasks/control_flow/filter.py, tests/core/test_task_map.py, tests/engine/cloud/test_utilities.py, tests/engine/result_handlers/test_result_handlers.py, tests/engine/test_result.py, tests/engine/test_state.py, tests/serialization/test_result_handlers.py
This PR alters the behavior of both the base `ResultHandler` class as well as the `NoResult` sentinel object.  In particular, `ResultHandler` now returns `None` for both read and write, and `NoResult` returns `None` as its "value".  
This PR is another step towards greedy persistence of results; in particular, we will ultimately never checkpoint / persist tasks which return `None`, and this change simplifies our logic in that space.
=> NoResult returns None

CHANGELOG.md, src/prefect/client/client.py, src/prefect/config.toml, src/prefect/core/task.py, src/prefect/engine/cloud/utilities.py, src/prefect/engine/task_runner.py, src/prefect/environments/storage/_healthcheck.py, tests/client/test_client.py, tests/core/test_task.py, tests/engine/cloud/test_utilities.py, tests/engine/test_task_runner.py, tests/environments/storage/test_docker_healthcheck.py
**NOTE**: PR'ing into #1898 
This PR:
- reverts checkpointing behavior _essentially_ to its defaults, with one change: if checkpointing is turned on (which occurs in Core with an env var setting and in Cloud always), any task with a result handler will be checkpointed
- updates cached inputs to gracefully pass in the absence of a result handler
- removes the strict requirement that _all_ Flows have result handlers in favor of a warning
=> Relax result handler requirement

src/prefect/engine/executors/dask.py
Fix error of unsupported operand "+" with string and int
- [ x] updates `CHANGELOG.md` (if appropriate) Not sure if needed?
I was getting errors that the operand "+" cannot be used with an int and str. So I reformated the string using `format` in place of "+".
It fixes an error I was getting.
=> Format Key String

src/prefect/agent/agent.py, src/prefect/agent/docker/agent.py, tests/agent/test_docker_agent.py
#1918 and #1921 had conflicting changes which was not apparent due to implied base class behavior that had changed. Without this PR the Docker agent will fail to exit after the allotted reconnect attempts have expired.
=> Fix merge issue from #1918 and #1921

CHANGELOG.md, src/prefect/agent/fargate/agent.py, tests/agent/test_fargate_agent.py
The Fargate Agent checks values read in through environment variables to see if they need to be taken literally. For example:
```bash
export networkConfiguration="{'awsvpcConfiguration':{'assignPublicIp':'DISABLED','subnets':['my_subnet'],'securityGroups':['sg-12345']}}"
```
Will be interpreted as a dictionary (as it should be). Previously any kwargs passed in to the `FargateAgent` object itself were not subjected to this literal eval. This was an issue because the CLI `prefect agent start fargate` accepts strings and passes them directly to the `FargateAgent`. Therefore the parse step needed to occur on those kwargs to check …
=> Parse Fargate Agent kwargs as literal

CHANGELOG.md, src/prefect/agent/agent.py, src/prefect/agent/docker/agent.py, src/prefect/agent/local/agent.py, src/prefect/cli/agent.py, tests/agent/test_docker_agent.py, tests/cli/test_agent.py
Adds the `show_flow_logs` agent option to the `DockerAgent`, forwarding all subprocess flow logs to the agent's standard output.
=> Add show_flow_logs to the Docker agent

.circleci/config.yml
Follow up of #1939 
@wagoodman The build fails if no `CIRCLE_TAG` is set
=> Remove CIRCLE_TAG for master build image step

CHANGELOG.md, src/prefect/core/flow.py, tests/core/test_flow.py
=> Fix issue with result handler default persisting after storage change

tests/core/test_flow.py, tests/engine/test_task_runner.py
Currently the timeout tests fail sporadically in CircleCI. These changes are to reduce the brittleness of the Task timeout tests. 
Closes #1947
=> Decrease brittleness of timeout tests 

CHANGELOG.md, src/prefect/agent/agent.py, tests/agent/test_agent.py
This PR does two things:
- puts Flow Runs in submitted states _prior_ to deploying them; this ensures that jobs / resources aren't created for Flow Runs which have already been submitted by other agents.  Putting them in Submitted _first_ allows Cloud to version lock appropriately
- in the event that placing the Flow Run into a Submitted state fails, we no longer attempt to mark the flow run failed; instead we log the error and continue on our way
Closes #1956
=> Slight refactor of how agents deploy and submit flow runs for execution

CHANGELOG.md, src/prefect/environments/execution/fargate/fargate_task.py, tests/environments/execution/test_fargate_task_environment.py
Bug fix where proper auth token was not being passed to the task ran in the FargateTaskEnvironment's execute step
Bug fixes are important :P
=> Pass proper auth token to FargateTaskEnvironment execute tasks

CHANGELOG.md, src/prefect/utilities/logging.py, tests/utilities/test_logging.py
Adds a step to the CloudHandler to attempt to log possible logger errors to Cloud for visibility. For example if the payload is too large or something non-json serializable is attempted the error will be raised in the flow process but not elevated for visibility.
Example logger issue being elevated as a cloud log:
Closes #1943 
Improves user visibility into otherwise hidden logger exceptions.
=> Attempt to ship logger errors via the CloudHandler

CHANGELOG.md, src/prefect/agent/kubernetes/agent.py, tests/agent/test_k8s_agent.py
Previously providing an `image_pull_secrets` to the Kubernetes agent install did not automatically use them for the jobs created by the agent.
This reduces user need to manually update the yaml outputted by the install command.
=> Populate prefect job imagePullSecrets if provided

CHANGELOG.md, src/prefect/environments/storage/s3.py, src/prefect/serialization/storage.py, tests/environments/storage/test_s3_storage.py
Add a `client_options` optional dict parameter to `prefect.environments.storage.s3.S3` for passing additional parameters when instantiating the `boto3` client; also serialize it as `JSONCompatible` in `prefect.serialization.storage.S3Schema`.
Passing additional parameters to the `boto3` client (like `endpoint_url` and `use_ssl`) allows storing and fetching Flows from any S3-compatible service, for example a local Minio cluster or alternative services ([list of S3-compatible and competing services on Wikipedia](https://en.wikipedia.org/wiki/Amazon_S3#S3_API_and_competing_services)).
=> S3 storage: accept additional boto3 kwargs

src/prefect/agent/fargate/agent.py, src/prefect/agent/kubernetes/agent.py
Local and Docker agents already log this at the `INFO` level. Informative to track runs that are being deployed and witness activity.
=> Update "deploying flow" log level in k8s and fargate agents

CHANGELOG.md, docs/cloud/concepts/flow_runs.md, src/prefect/client/client.py, tests/client/test_client.py
This PR exposes and documents `version_group_id` as an input to `create_flow_run`.  This input provides a stable API for running flows from a version group.
Closes #1987
=> Add version_group_id

CHANGELOG.md, src/prefect/agent/fargate/agent.py, tests/agent/test_fargate_agent.py
Moving task_definition_name from class attribute to dict value, which is explicitly passed into fargate agent class methods.
This fixes a new bug with Fargate Agent when task revisions are enabled caused by the new ThreadPool based agent process.  Previously because the loop over flow runs was synchronous we could house the task definition name as an agent class attribute.  Now that the loop as async when there are more than 1 flows runs collected by the agent, the second flow run overrides the task definition name set by the first flow.
=> change to fargate agent to fix bug related to agent process threadpool

CHANGELOG.md, src/prefect/core/task.py, src/prefect/engine/task_runner.py, tests/core/test_task.py
Adds a better exception around unsubscriptable mapped arguments, both within a Flow context and at runtime. Until there is a large mapping refactor, this only addresses the message raised by #1821 .
Brings forth mapping argument Type issues as early as possible.
=> Add early check for mapping argument type errors

requirements.txt
Until https://github.com/dask/distributed/pull/3494 is merged let's pin msgpack `<1.0.0` to fix failing tests
=> Pin msgpack distributed dependency

CHANGELOG.md, src/prefect/tasks/kubernetes/deployment.py, src/prefect/tasks/kubernetes/job.py, src/prefect/tasks/kubernetes/pod.py, src/prefect/tasks/kubernetes/service.py
There is a bug in the DeleteNamespacedJob K8s task. in the api_client delete_namespaced_job call, api_client is used instead of client.
Fixed it here
=> Bugfix: DeleteNamespacedJob K8s task

CHANGELOG.md, src/prefect/tasks/kubernetes/deployment.py, src/prefect/tasks/kubernetes/job.py, src/prefect/tasks/kubernetes/pod.py, src/prefect/tasks/kubernetes/service.py
Currently in delete K8s resource task (e.g. `DeleteNamespacedJob`), the propagation policy cannot be passed. This might lead to orphans.
Now we have the options to pass kwargs (e.g. {"propagation_policy": "...", "grace_period_seconds": "..."}) to the `V1DeleteOptions` object.
This would allow to better control the delete options, for instance garbage collection mechanism (propagation_policy).
=> ADD KWARGS TO `V1DeleteOptions`

.circleci/config.yml
Fix the Twine repository setting (allow the default of `pypi`)
=> Remove TWINE_REPOSITORY env var in CI

CHANGELOG.md, docs/core/concepts/logging.md, src/prefect/core/task.py, src/prefect/engine/task_runner.py, src/prefect/utilities/logging.py, tests/core/test_task.py, tests/core/test_task_map.py, tests/engine/test_task_runner.py, tests/utilities/test_logging.py
Closes #2040 
By default tasks now have a `log_stdout=True` kwarg which can be toggled based on whether or not to send stdout messages as Prefect logs.
Example:
```python
@task
def me():
print("@@@")
f = Flow('test', tasks=[me])
```
As we have seen, logging stdout is commonly a new user assumption when it comes to using Prefect / Prefect Cloud. Having to pull the logger from context is not that intuitive to new users:
```python
from prefect import context
logger = context.get('logger')
logger.info('@@@')
```
=> Add optional stdout logging in tasks

CHANGELOG.md, src/prefect/utilities/serialization.py, tests/utilities/test_serialization.py
This PR ensures that serialization and deserialization do not mutate their payloads, but create and manipulate (shallow) copies instead.
Closes #2098
=> Don't mutate data during serialization

CHANGELOG.md, src/prefect/engine/task_runner.py
Fix retrieval of `task.log_stdout` by making it a `getattr` to preserve compatibility between patch release versions
=> Fix task runner pipeline retrieving of log_stdout attribute

.github/ISSUE_TEMPLATE/bug_report.md
Updates the github bug template to make note of the `prefect diagnostics` command line option to retrieve environment information
=> Add note about using prefect diagnostics to bug template

src/prefect/agent/agent.py, src/prefect/agent/kubernetes/agent.py, src/prefect/client/client.py, src/prefect/engine/result_handlers/azure_result_handler.py, src/prefect/engine/result_handlers/gcs_result_handler.py, src/prefect/engine/result_handlers/s3_result_handler.py, src/prefect/schedules/clocks.py, tests/cli/test_run.py
Fix click test assertion to account for click v7.1 error formatting change. Also fixes select mypy issues due to mypy rule updates.
=> Change Click error test assertions to be agnostic to Click version

docs/core/PINs/PIN-16-Results-and-Targets.md
Closes #2131. Adds a PIN describing the goals of an internal roadmap project sophisticating the Result interface.
We want to be able to support several use cases related to Prefect knowing about where file targets exist, including tracking task artifacts, file dependencies to determine state, and persisting the cache for core only users outside of the in memory cache. We believe this PINs suggested API …
=> Closes #2131 Add PIN for Result update for targets

CHANGELOG.md, src/prefect/engine/result_handlers/s3_result_handler.py, tests/engine/result_handlers/test_result_handlers.py
Instantiates a new boto session (and thus boto client) if we think we are in a new thread. Closes #2108 which has a lot of context for this. In the end (see commit history for the history) I went with memoizing the boto client not on the result handler instance as before, but in `prefect.context`. Anecdotally, initializing at every call to `S3ResultHandler.client` a la 0852c2c made the [dask example flow](https://docs.prefect.io/core/advanced_tutorials/dask-cluster.html#an-example-flow) twice as slow with two local dask workers using `--nprocs 1 --nthreads 3`.
Tasks on multithreaded executors can now use the S3ResultHandler …
=> Closes #2108. New boto session for each thread

CHANGELOG.md, src/prefect/utilities/serialization.py, tests/conftest.py, tests/core/test_flow.py, tests/serialization/test_flows.py, tests/utilities/test_serialization.py
This PR fixes an issue in which some deserialization logic accidentally mutated the state of the original serialized payload. 
This bug prevented some specific types of Schedules from being registered with Prefect Cloud.
**cc:** @znicholasbrown
=> Fix Stateful Function Reference deserialization logic

CHANGELOG.md, src/prefect/client/client.py, src/prefect/serialization/schedule.py, tests/client/test_client.py, tests/serialization/test_schedules.py
This PR does two independent things:
- fixes an issue with the `DateClock` serializer (this isn't a widely used clock but it still should work)
- allows users to have required parameters whose default values come entirely from their Flow's clocks
This PR improves the user experience for scheduling changing parameter defaults over time while still having a required parameter.
=> Scheduled Required Parameters Fix

docs/core/getting_started/installation.md
Adds a note to the Installation doc about Prefect Docker images. The breakdown of Docker image tags is present on the DockerHub README https://hub.docker.com/r/prefecthq/prefect
Closes #2085
=> Add note about using Prefect Docker images to installation doc

CHANGELOG.md, src/prefect/agent/agent.py, src/prefect/agent/docker/agent.py, src/prefect/agent/fargate/agent.py, src/prefect/agent/kubernetes/agent.py, src/prefect/agent/local/agent.py, src/prefect/cli/agent.py, tests/agent/test_agent.py, tests/agent/test_docker_agent.py, tests/agent/test_fargate_agent.py, tests/agent/test_k8s_agent.py, tests/agent/test_local_agent.py, tests/cli/test_agent.py
Closes #2037 
Adds a `--max-polls` flag to the `prefect agent start` CLI command and a `max_polls` kwarg to all agents. This option allows users to specify the amount of times they want the agent to poll Cloud looking for flow runs. This is great for one-off and testing scenarios because the agents no longer exist as infinitely running loops.
Opens the door for short-lived agents that is beneficial for areas such as testing and serverless platforms.
=> Add maximum polling option to agents

CHANGELOG.md, src/prefect/agent/agent.py, src/prefect/agent/kubernetes/resource_manager.py, src/prefect/agent/local/agent.py, src/prefect/client/client.py, src/prefect/core/flow.py, src/prefect/utilities/logging.py, tests/agent/test_agent.py, tests/agent/test_docker_agent.py, tests/agent/test_fargate_agent.py, tests/agent/test_k8s_agent.py, tests/agent/test_local_agent.py, tests/cli/test_create.py, tests/cli/test_run.py, tests/client/test_client.py, tests/conftest.py, tests/engine/cloud/test_cloud_flow_runner.py, tests/engine/test_flow_runner.py, tests/utilities/test_logging.py
This PR does some major house cleaning to:
- remove `Client.deploy` and `flow.deploy`
- remove `Client.write_run_log`
- converts ~_most_ (but not all)~ all of our camelCased GraphQL calls to snake_cased calls
Note that we should manually test many of the changes here to make sure a breaking change doesn't sneak in accidentally.
- Closes #2183 
- Closes #2184 
- Closes #2181
=> camelCase -> snake_case

CHANGELOG.md, src/prefect/utilities/executors.py, tests/utilities/test_executors.py
This PR fixes a new issue that crops up in local development situations wherein certain Cloud environment / configuration variables are not present causing the background heartbeat process to fail to start.
Local dev is important.
=> Fix issue with None values in heartbeat subprocess environment

CHANGELOG.md, src/prefect/cli/run.py, tests/cli/test_run.py
By querying for a flow run state in the `run cloud --logs` option after the initial log query it allowed for a potential condition where the state was retrieved before all of the batch logs had arrived.
So possible tracebacks aren't missing in failed runs
cc @bnaul
=> Query for state on flow run logs query for run CLI command

src/prefect/client/client.py, src/prefect/config.toml, tests/cli/test_run.py
This will output the proper UI link when registering and running flows.
Register:
```
Flow: http://localhost:8080/flow/a262196f-8bd3-4183-bfe9-4e6cb83f04d8
```
Run:
```
Flow Run: http://localhost:8080/flow-run/fdffb511-17dc-499d-b3f6-bda59a77ee49
```
=> Use server UI endpoint when backend is server

CHANGELOG.md, src/prefect/engine/result_handlers/s3_result_handler.py, tests/engine/result_handlers/test_result_handlers.py
Closes #2204 
There was a possibility where a thread contained a `boto3client` in context however did not have the `_client` attribute set. This updates the `client` property to check if `_client` is set before returning.
Fix the potential failures that could arise from using the `S3ResultHandler`.
=> Fix retrieval of unset S3ResultHandler attribute

.circleci/config.yml, CHANGELOG.md
adds a circle orb to docker publish prefect server images
versioned images published to docker hub for open use on each merge to master
=> add docker publish jobs for server images

CHANGELOG.md, src/prefect/engine/result_handlers/s3_result_handler.py
Closes #2232 
There is still a chance where the s3 result handler `_client` attribute does not exist and this uses the hasattr function for that case.
=> Update s3 result handler to check for _client attribute before retrieval

tests/client/test_client_auth.py, tests/engine/cloud/test_cloud_flow_runner.py
Import LOOP so that line 536 will not raise NameError at runtime.
Related to #1199
[flake8](http://flake8.pycqa.org) testing of https://github.com/PrefectHQ/prefect on Python 3.8.1
$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./tests/client/test_client_auth.py:342:16: F632 use ==/!= to compare str, bytes, and int literals
assert client._access_token is "ACCESS_TOKEN"
^
./tests/client/test_client_auth.py:343:16: F632 use ==/!= to compare str, bytes, and int literals
assert client._refresh_token is "REFRESH_TOKEN"
^
./tests/engine/cloud/test_cloud_flow_runner.py:536:19: F821 undefined name 'LOOP'
raise LOOP(result=prefect.context.get("task_loop_result", 0) + x)
^
2     F632 use ==/!= to compare str, bytes, and int literals
1     F821 undefined name 'LOOP'
3 …
```
=> Undefined name: from prefect.engine.signals import LOOP

CHANGELOG.md, src/prefect/cli/docker-compose.yml, src/prefect/cli/server.py, src/prefect/config.toml, tests/cli/test_server.py, tests/core/test_flow.py
Open PR up for discussion if this is how we want optional port allocations to work when running `prefect server start`. This allows ports from the server services to be binded to different ports on the host machine. For this to work I had to add `__HOST_PORT` options to some of the services in `config.toml`. I'm guessing this is due to some hardcoded ports that these services use inside their containers. (e.g. overwriting `config.server.hasura.port` broke communication inside the containers when they ran)
This implementation allows us to set ports through CLI `--postgres-port` or environment variables …
=> Update `prefect server start` command to specify and disable port mappings

server/setup.py
This PR places an upper bound on `graphql-core`. 
A recent release of `graphql-core` broke some server dependencies-- this should pin them back up.
=> Bound graphql-core

server/Changelog.md, server/services/postgres/alembic/versions/2020-03-30T160456_fix_log_default_timestamp.py
This PR changes the default value in the `log` table from a static timestamp to `clock_timestamp()` to be in sync with the other `timestamp` default values.
This PR is important to make sure that default values aren't given an old static timestamp that would result in inaccurate data.
=> change default log timestamp to clock timestamp from static timestamp

CHANGELOG.md, src/prefect/tasks/cloud/flow_run.py, tests/conftest.py, tests/tasks/cloud/test_flow_run.py
This updates the `FlowRunTask` in the task library to make the project name optional for running this task against Prefect Core's server.
Previous attempts to use this task against Prefect Core's server would raise a schema error due to the project name.
=> Make project name optional for FlowRunTask

CHANGELOG.md, src/prefect/cli/describe.py, tests/cli/test_describe.py
Closes #1813
Adds a new `--output/-o` option to `prefect describe` CLI commands. Currently only supports `json` but could be expanded in the future to support other options if requested.
Allows for more programmatic use of the describe CLI commands.
=> Add `--output` option to describe CLI commands for JSON output

CHANGELOG.md, src/prefect/client/client.py, src/prefect/config.toml, src/prefect/utilities/logging.py, tests/utilities/test_logging.py
This PR introduces a new "diagnostic" mode for analyzing all requests made to Prefect Cloud.  To turn this mode on for your flows either:
- set `PREFECT__CLOUD__DIAGNOSTICS=true` locally and run a local agent
- start your agent with `prefect agent start -e PREFECT__CLOUD__DIAGNOSTICS=true` so that all flows submitted through that agent have diagnostics on
- set the corresponding value to `true` in your user `config.toml`
Every request made to Cloud will then be timed and logged.
Some users experience slow downs when running flows on Cloud and this PR adds a tool to help them self diagnose where there issue might be.
Some …
=> Diagnostic mode

src/prefect/utilities/collections.py, tests/engine/test_state.py, tests/engine/test_task_runner.py, tests/serialization/test_states.py
Accessing `collections.Iterable` raises a deprecation warning, but `collections.abc.Iterable` does not.
=> Suppress deprecation warning for collections module

CHANGELOG.md, src/prefect/agent/local/agent.py, tests/agent/test_local_agent.py
When not using `show_flow_logs` the LocalAgent subprocesses were previously holding on to logs in a `PIPE` which on longer runs could cause the subprocess to deadlock if too many logs were buffered. Since these logs are not used it makes more sense to send them to `subprocess.DEVNULL` (**note:** logs are still sent to the Prefect API when in use).
Also updates the LocalAgent heartbeat to no longer attempt to log the stdout on an unexpected error since stderr is already by default redirected to stdout if an error were to occur.
I believe there is a chance this is related to #2270 
Prevent subprocesses from filling up with logs
=> Fix LocalAgent subprocess using PIPE to buffer logs

CHANGELOG.md, src/prefect/utilities/executors.py
Related to #2293, a "just in case" for forwarding stdout to `DEVNULL` instead of `PIPE`. This PR makes the change in the heartbeat subprocess since the output was never used in a meaningful way and only gathered on error. (status code is still reported)
=> Forward heartbeat utility output to subprocess.DEVNULL instead of subprocess.PIPE

CHANGELOG.md, server/src/prefect_server/cli/dev.py, server/src/prefect_server/cli/services.py
- Convert ui_path when read from environment variable into a Path object.
- Use config file's host and port for hasura and apollo when starting services with `dev services`.
Fixes some config interpolation that wasn't happening when running services independently/not with docker.
Needed to dev on Apollo from Prefect Core; Apollo services could not build Apollo schema or healthcheck Apollo when running from dev services without it. Also needed to be …
=> Fix some interpolation of config in Prefect server dev commands

CHANGELOG.md, src/prefect/core/task.py, src/prefect/engine/task_runner.py, src/prefect/triggers.py, tests/test_triggers.py
Addresses #2298 by refactoring trigger signatures from a set of states to a dictionary of edges and states.
**Breaking change** so being merged into the 0.11.0 release branch
This will allow for more customized triggers in the future
=> Update trigger signatures to accept a dictionary of [Edge, State]

src/prefect/engine/result/base.py, src/prefect/engine/results/__init__.py, src/prefect/engine/results/constant_result.py, src/prefect/engine/results/gcs_result.py, src/prefect/engine/results/json_result.py, src/prefect/engine/results/prefect_result.py, src/prefect/engine/results/s3_result.py, tests/engine/result/test_base.py, tests/engine/results/test_gcs_result.py, tests/engine/results/test_results.py, tests/engine/results/test_s3_result.py
This PR hardens the new PIN-16 `Result` interface to better match our intended way of using it.  Additionally, this PR introduces a new `JSONResult` type for interacting with data which can safely be stored directly in the database.
There are a few ways this PR could be improved:
I wanted to open the PR for any comments before addressing the two points above.
=> Hardening the Result interface

server/Changelog.md, server/docker/docker-compose.yml, server/src/prefect_server/cli/dev.py
cli option for building (and using) local images from source using docker-compose
prefect-server dev build
enables local work on prefect-server using docker-compose
`prefect-server dev build [--version foo]`
`prefect-server dev up --no-pull [--version foo]`
=> add capability to build server from source

CHANGELOG.md, docs/outline.toml, src/prefect/tasks/secrets/__init__.py, src/prefect/tasks/secrets/base.py, src/prefect/tasks/secrets/env_var.py, tests/tasks/secrets/test_base.py, tests/tasks/secrets/test_env_var.py
This PR does a few things:
- renames our secret tasks for clarity
- allows for new secret names to be passed at runtime
- removes `env_var` as a distinct option from `EnvVarSecret`
This PR was originally motivated by our work on Results (additional PR for `SecretResult` incoming), and I went ahead and changed the names as well as this has been a common source of confusion.
=> Minor secrets refactor

CHANGELOG.md, src/prefect/tasks/core/operators.py
Previously conditional operators also cast their result to `bool`. This
relaxes that constraint. Note that `Not` still returns bool, since
this is required in Python by `__bool__` (which `not x` calls).
Fixes #2271.
=> Relax bool cast on operators

CHANGELOG.md, tests/cli/test_run.py, tests/client/test_client.py, tests/conftest.py
Closes #2319 
Since the client no longer determines if you are using Core's server or Cloud based on the `cloud.api` host and instead by `backend` this has to be added to the test fixtures.
Fix failing tests
=> Fix test fixtures by setting backend setting

CHANGELOG.md, src/prefect/tasks/control_flow/conditional.py, tests/tasks/test_control_flow.py
This modifies `ifelse` and `switch` to return a task for the branch that
was run. Previously users had to explicitly use `merge` to achieve the
same behavior.
Fixes #1735.
=> Control flow tasks return executed branch

CHANGELOG.md, src/prefect/engine/result_handlers/azure_result_handler.py, tests/engine/result_handlers/test_result_handlers.py
Closes #2316 
This PR fixes the Azure result handler's use of an empty Prefect Secret over a provided connection string (either directly or through env var). A provided connection string should take precedence over looking for a Prefect Secret.
Previously the Prefect Secret was always used unless specified as `None`.
=> Fix AzureResultHandler choosing an empty Secret over provided connection string

docs/orchestration/tutorial/k8s.md
The link pointed to `cloud`, not `orchestration`.
=> Fix broken link in k8s agent docs

CHANGELOG.md, docs/orchestration/concepts/api.md, docs/orchestration/concepts/cli.md, docs/orchestration/concepts/tokens.md, src/prefect/cli/auth.py, tests/cli/test_auth.py
Closes #2336 
The `create_api_token` mutation, when converted to snake casing convention in a recent release, switched over to using `scope` instead of `role` when creating a token.
Fixing a broken CLI command
=> Fix `auth create-token` CLI command

CHANGELOG.md, src/prefect/config.toml, src/prefect/utilities/logging.py, tests/utilities/test_logging.py
This PR exposes `config.logging.datefmt` as a configurable setting on Prefect loggers.
Community requested 🚀 (also might help support logging data dog integrations)
=> Better logging config

CHANGELOG.md, src/prefect/agent/docker/agent.py, tests/agent/test_docker_agent.py
Previously these would accumulate as the agent ran things. We now set
them to autoremove on completion.
Fixes #2344.
=> Auto-remove completed docker containers

CHANGELOG.md, src/prefect/cli/server.py, tests/cli/test_server.py
Changes yaml `load` and `dump` to `safe_load` and `safe_dump` in the server start CLI command.
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
=> Use YAML safe command versions in server start CLI command

src/prefect/environments/storage/s3.py, src/prefect/utilities/aws.py, tests/engine/results/test_s3_result.py, tests/environments/storage/test_s3_storage.py, tests/serialization/test_storage.py, tests/tasks/aws/test_lambda.py, tests/tasks/aws/test_s3.py, tests/tasks/aws/test_step_function.py
This PR will address https://github.com/PrefectHQ/prefect/issues/2272 once it's released with 0.11.0.  
In particular:
- adds `SESSION_TOKEN` as a possible key for AWS credentials stored in secrets
- removes the credentials kwargs on S3 Storage.  Storage classes are _always_ deserialized from Cloud and as such, cannot access non-serialized attributes so these kwargs were non-functional
=> Minor AWS creds refactor

server/contrib/README.md, src/prefect/contrib/README.md, tests/contrib/README.md
Closes #2333. Adds in a `contrib` folder with a basic readme for `/src/prefect` (and an analogous spot for `/tests/`) and another one in `/server/`. For the latter, I imagine we might split this more over time depending what type of contributions really go into server (for example, a contrib folder specifically for UI in `/server/services/ui/src`) but this felt like a safe starting point there while we …
=> Closes #2333. Add contrib directories and READMEs for prefect core and server

src/prefect/tasks/control_flow/conditional.py
The code and docstrings were correct, but the type annotations weren't.
=> Fix return type annotations for switch & ifelse

docs/orchestration/execution/remote_dask_environment.md
Minor fix to docs for `RemoteDaskEnvironment` code example with TLS.
Change URL scheme from `tcp` to `tls` for TLS example.
Users who copy and paste from this example might be confused if it doesn't work with the code provided.
=> Fix URL scheme for TLS to actually be tls

CHANGELOG.md, src/prefect/environments/execution/fargate/fargate_task.py, src/prefect/environments/execution/k8s/job.py, tests/environments/execution/test_fargate_task_environment.py, tests/environments/execution/test_k8s_job_environment.py
Closes #2258 
This allows optional executor kwargs to be set on these environments where previously it was not possible to pass arguments to the executors they used.
=> Add executor_kwargs to KubernetesJobEnvironment and FargateTaskEnvironment

CHANGELOG.md, src/prefect/tasks/docker/images.py, tests/tasks/docker/test_containers.py, tests/tasks/docker/test_images.py
At the moment, only a subset of the Docker API is supported by Prefect's [Docker tasks](https://github.com/PrefectHQ/prefect/tree/master/src/prefect/tasks/docker).
Nothing too fancy, I simply added some code to the current tasks (respectively `CreateContainer`, `ListContainers` and `ListImages`) in order to allow the following optional arguments when calling the `run` method:
* `volumes` ;
* `filters`.
I invite you to refer to the [documentation](https://docker-py.readthedocs.io/en/stable/index.html) in case you're not familiar with Docker-related concepts.
I plan to use Prefect at my workplace to manage Docker-based ETL jobs (heavily relying on disk I/O), but the lack of support for Docker volumes and list filtering is sadly a no-go.
=> Support for Docker volumes and list filtering

CHANGELOG.md, src/prefect/cli/server.py, src/prefect/environments/execution/dask/remote.py, src/prefect/serialization/environment.py, tests/cli/test_server.py, tests/serialization/test_environments.py
Closes #2369 
Closes #2375 
Now the RemoteDaskEnvironment won't show up as a CustomEnvironment and the image tag selection based on Prefect version is good for local development.
=> Add serializer for RemoteDaskEnvironment and add server start image version logic

CHANGELOG.md, src/prefect/agent/docker/agent.py, src/prefect/cli/agent.py, tests/agent/test_docker_agent.py, tests/cli/test_agent.py
Adds a flag to disable the auto host mounting for Linux. Closes #2361 
In certain Docker setups (notably some Docker-in-Docker), there is no `docker0` interface present inside the container so this step of auto-attaching the internal docker daemon fails.
=> Add flag for toggling Docker interface check on Linux

CHANGELOG.md, src/prefect/cli/server.py
Fixes a bug where the `version` kwarg on the `server start` CLI command wasn't being respected on tagged releases.
=> Fix server start image version not using version kwarg

CHANGELOG.md, src/prefect/utilities/logging.py, tests/utilities/test_logging.py
This PR pops `args` out of the logs record dictionary to prevent them from being sent to Cloud (under the `info` payload).  `args` are _typically_ used to format log messages and otherwise not needed for log visibility / inspection in Cloud.
Closes #2407 and helps ensure users don't need to change their logging code when running in Prefect.
=> Pop args out of log messages to prevent shipping non-JSON objects

CHANGELOG.md, src/prefect/tasks/control_flow/conditional.py, tests/tasks/test_control_flow.py
This PR prevents the creation of a task whenever the `false_task` is `None`.  This is a minor optimization that allows for a cleaner DAG when the intent is just using a basic "if".
Minor UX improvement.
**cc:** @jcrist / @znicholasbrown
=> Dont spuriously create None task when using ifelse

CHANGELOG.md, src/prefect/tasks/core/collections.py, tests/tasks/test_core.py
This PR closes https://github.com/PrefectHQ/prefect/issues/2451, which identified a bug in which ordered Prefect collections implicitly relied on string (lexical) ordering rather than numerical ordering. Since collections maintain a dictionary keyed by `arg_{n}`, where n is the sort order, lexical ordering would result in `arg_0, arg_1, arg_10, arg_11, arg_2, arg_3, ...` for a list of 12 items. This PR adds an explicit key function to the sort of `collections.List` and `collections.Tuple` which extracts the integer part of the key name for numerical sorting.
=> Ensure that ordered collections maintain numerical order for > 10 items

CHANGELOG.md, server/services/ui/shell_scripts/start_server.sh
A small fix that handle undefined PREFECT_SERVER__GRAPHQL_URL env var.
=> fix start_server.sh when PREFECT_SERVER__GRAPHQL_URL undefined

CHANGELOG.md, src/prefect/config.toml, src/prefect/core/flow.py, src/prefect/core/task.py, src/prefect/engine/task_runner.py, src/prefect/utilities/logging.py, tests/core/test_flow.py, tests/core/test_task.py, tests/engine/cloud/test_cloud_flow_runner.py, tests/engine/test_flow_runner.py, tests/engine/test_task_runner.py, tests/tasks/test_shell.py, tests/utilities/test_logging.py
This PR:
- reverts a piece of https://github.com/PrefectHQ/prefect/pull/1355 to use logger names that are derived from task / flow names without prepending additional (and usually redundant) info
- adds a new `logging.log_attributes` config option for injecting custom context variables into log records (can be used for formatting)
Reduces clutter + closes #2462
=> Logging updates

CHANGELOG.md, src/prefect/agent/kubernetes/resource_manager.py
Calls `.isoformat()` prior to passing a log timestamp in the k8s resource manager.
Was preventing the resource manager from doing its job.  Closes #2474
=> Isoformat timestamps before passing them to log writer

CHANGELOG.md, src/prefect/agent/local/agent.py, tests/agent/test_local_agent.py
Previously this would loop over a list of processes, and *attempt* to
remove completed processes with `processes.pop`. Due to a bug though,
this would remove the incorrect process. We now use a set of processes,
which provides `O(1)` access to remove (more efficient than `O(n)`), and
removes the correct process.
Fixes #2419, see https://github.com/PrefectHQ/prefect/pull/2464#discussion_r419463181
=> Fix bug in local agent process cleanup loop

CHANGELOG.md, src/prefect/agent/kubernetes/agent.py, src/prefect/agent/kubernetes/deployment.yaml, src/prefect/cli/agent.py, tests/agent/test_k8s_agent.py, tests/cli/test_agent.py
Adds a toggle for `config.backend` when installing the k8s agent.
When using the k8s agent against Core's server would cause an issue where a token was expected because it didn't know it wasn't communicating with cloud.
=> Add backend toggle to k8s agent install

src/prefect/engine/result/base.py, src/prefect/engine/results/local_result.py, src/prefect/serialization/result.py, src/prefect/serialization/state.py, tests/engine/result/test_base.py, tests/engine/results/test_gcs_result.py, tests/engine/results/test_results.py, tests/serialization/test_result.py, tests/serialization/test_results.py, tests/serialization/test_states.py
This PR breaks some of the work from #2391 into it's own, independent PR for easier review.  This PR introduces new serializers for all the new-style result classes.
Serializers are the language by which Core and Prefect backends communicate; because the backend will need to support older versions of Core still running with old result handlers we need to be very mindful of how these serializers work.  You'll notice this implementation layers _on top_ of the serializers but doesn't change anything related to Result Handlers or SafeResult objects.
=> Results serializers

CHANGELOG.md, src/prefect/utilities/serialization.py, tests/utilities/test_serialization.py
Prefect's serialization scheme relies on callable objects having fully
qualified names, a property that is only true (for the most part) for
true functions in importable modules. We now raise a better error
message when trying to use other callables in these locations.
Fixes #2432
=> Give a better error when trying to serialize a non-function

src/prefect/utilities/aws.py, tests/tasks/aws/test_lambda.py, tests/tasks/aws/test_s3.py, tests/tasks/aws/test_step_function.py, tests/utilities/test_aws.py
In release 0.11.0 there is a new utility function to create boto3 clients that honors the new rules regarding Secret authentication (`utilities.get_boto_client`). This PR fixes a typo in its docstring, and moves tests that were being repeated unevenly in AWS related tasks that had to do with the utility function to a single version of those tests only on the utility function. In doing so I decreased code coverage since the repetitive version of those tests were falsely inflating the test coverage for AWS related tasks's `run` methods, so I threw in a few basic unittests that test …
=> Change some tests around given the new boto3 utility function in 0.11.0

src/prefect/core/flow.py, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/flow_runner.py, src/prefect/engine/task_runner.py, src/prefect/serialization/state.py, tests/engine/test_state.py, tests/serialization/test_states.py, tests/utilities/test_logging.py
This PR fixes two issues identified in integration testing:
- an incredibly rare situation in which `flow.run()` runs on an infinite loop
- state serializers for `cached_inputs` losing information
There is still one large outstanding issue we need to address: how to handle `cached_inputs` for mapped children.  For standard situations, task outputs are checkpointed and can be safely / directly stored as a cached input to downstream tasks that request caching, retries, etc.  However, with mapping specifically, the actual input to the task is an altered version of the upstream output (in particular it's an indexed item from the …
=> Fixes from integration testing

src/prefect/environments/__init__.py
Just adding DaskCloudProvider to the top level `__init__` for environments.
So people can import DaskCloudProviderEnvironment like they do the rest of the environments (and [how it is suggested to do so in the Prefect docs](https://docs.prefect.io/orchestration/execution/dask_cloud_provider_environment.html#examples))
=> Make DaskCloudProviderEnvironment importable from `prefect.environments`

CHANGELOG.md, src/prefect/agent/kubernetes/deployment.yaml
The health check server can't listen on localhost in kubernetes.
=> Fix agent kubernetes liveness probe

src/prefect/engine/cloud/task_runner.py, src/prefect/engine/task_runner.py
The last piece of the PIN 16 puzzle!
Left to do:
- raise an error if `{filename}` not a part of the result template for mapped tasks
- improve documentation
- go through tests to begin using `Result` classes instead of `ResultHandler`s
All of that can be done in other PRs
=> Fix issue with mapped caching and looped retries

CHANGELOG.md, server/src/prefect_server/api/states.py, server/tests/api/test_runs.py, server/tests/api/test_states.py, server/tests/fixtures/database_fixtures.py, server/tests/graphql/test_states.py
This PR brings a new behavior from Prefect Cloud to server: task runs can not enter a running state if the flow run isn't running. The enables a "cancellation lite" semantic.
=> [Server] Prevent tasks from entering a running state if flow run is not running

CHANGELOG.md, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
Take in DOCKER_HOST env var with precedence over base_url parameter in docs
closes #2157 
Allows for docker-in-docker/ remote docker daemon setup at buildtime
=> take docker daemon url in docker storage from DOCKER_HOST env var

src/prefect/serialization/result.py, tests/serialization/test_results.py
Adds a serializer for custom results
So users can write their own result handlers and orchestrate them with a backend
=> Add serializer for custom Results

CHANGELOG.md, src/prefect/tasks/notifications/slack_task.py
This PR change allows **slack_task** to accept a dictionary for the message parameter to build a specially-strctured JSON Block. It would give users flexibility to send a text or a JSON block. The original slack_task only accepted message as a plain text by setting `json = {"text":message}`.
Users would able to customize and their own slack message with a structured JSON block. Here is the documentation of [Slack Block](https://api.slack.com/block-kit/building) which provides better formatting, layouts and visualization. In our case, we used slack block kit to send informative alert message when the flow is done
=> Allow slack_task to accept a dictionary as a specially-strctured JSON 

src/prefect/engine/cloud/task_runner.py, tests/engine/cloud/test_cloud_flow_runner.py, tests/engine/cloud/test_cloud_flows.py
This PR introduces a max 10 minutes wait for "in-process" retries when running against a Prefect backend.  Previously this limit was 1 minute.
Slightly better UX in some edge case situations.
**cc:** @jlowin
=> Relax in-process retries to 10 minutes

CHANGELOG.md, src/prefect/core/flow.py, src/prefect/core/task.py, src/prefect/tasks/control_flow/case.py, tests/tasks/test_control_flow.py
Previously this only worked with the functional api.
Fixes #2538.
=> Support using `case` with the imperative api

CHANGELOG.md, src/prefect/environments/execution/k8s/job.py, tests/environments/execution/test_k8s_job_environment.py
Adds option to use a unique name for each job created with the Kubernetes Job Environment by adding on the first eight characters from the flow run id.
Previously it would not be possible to run two runs of the same flow at the same time using this environment due to k8s naming collisions.
=> Add unique name option to Kubernetes Job Environment

CHANGELOG.md
Just a quick update because there was a dupe in the 0.11.0 changelog (you can see the still existing one in the diff 3 bullet points down)
Correct changelog.
=> Fix 0.11.0 changelog from duplicate entry

CHANGELOG.md, src/prefect/configuration.py, tests/test_configuration.py
This PR introduces a better implementation for parsing config values that will handle secrets passed in through env var in a much more natural way.
Mainly for secrets, but also for configuration consistency.  Closes #2536
=> Try to parse all config values using literal_eval

docs/core/tutorial/06-parallel-execution.md
This PR proposes fixing mis-aligned parentheses in the Dask example at https://docs.prefect.io/core/tutorial/06-parallel-execution.html to match style in the rest of the documentation.
This PR is a minor change to improve the consistency and readability of the documentation. In its current form, at first glance I thought that there was a `)` missing and this was distracting while reading the documentation.
=> [docs] fix indentation for parentheses in Dask example

docs/core/advanced_tutorials/task-guide.md, docs/core/advanced_tutorials/visualization.md, docs/core/idioms/parallel.md, docs/orchestration/faq/dataflow.md, src/prefect/agent/agent.py
This PR suggests fixes for a few small typos noticed in the documentation.
This is a minor fix to remove typos that may distract readers of the documentation.
=> [docs] fix typos in docs

server/tests/database/test_hasura.py, tests/agent/test_fargate_agent.py, tests/cli/test_auth.py, tests/cli/test_execute.py, tests/client/test_client_auth.py, tests/core/test_flow.py, tests/engine/test_flow_runner.py, tests/tasks/azureml/test_datastore.py, tests/tasks/dropbox/test_dropbox.py
Thanks for this awesome project! I've been getting familiar with `prefect` this week, and wanted to contribute back where I could. I noticed you aren't running `flake8` in this project, so I ran that over the codebase to see if there were any issues that could be fixed.
I saw one pattern that I think it would be helpful to address...duplicated tests.
If you run this command from the root of the repo
```shell
flake8 | grep -E "F811 .*unused .*test_"
```
you'll see the following:
```text
./tests/engine/test_flow_runner.py:1187:1: F811 redefinition of unused 'test_parameters_can_be_set_in_context_if_none_passed' from line 1160
./tests/engine/test_flow_runner.py:1194:1: F811 redefinition of unused …
```
=> [ci] fix masked tests

CHANGELOG.md, src/prefect/agent/agent.py, src/prefect/agent/local/agent.py
Now that #2558 allows for providing a more rich set of env vars via config we were attempting to double parse `config.cloud.agent.labels`. 
Closes #2569
=> Handle possible malformed evals in agent labels parsing

CHANGELOG.md, src/prefect/environments/execution/dask/remote.py, tests/environments/execution/test_remote_dask_environment.py
This is a minor change to fix the type of the optional Dask Security parameter in RemoteDaskEnvironment for those using TLS.
Change the type of the security parameter from `Type[Security]` to `Security`.
Without this change, those using TLS with Dask will get an annoying and incorrect type error.
=> Fix type for Dask Security in RemoteDaskEnvironment

CHANGELOG.md, src/prefect/engine/task_runner.py, tests/engine/test_task_runner.py, tests/utilities/test_logging.py
Introduced in 0.11.0, if users set `log_stdout=True` on a task that returns non-trivial data, that data was not stored on the task run state and consequently was not checkpointed / passed to downstream tasks.  
Dataflow is critical functionality in prefect
=> Fix log_stdout

CHANGELOG.md, src/prefect/core/flow.py, tests/core/test_flow.py
The `Flow` context manager works by explicitly placing and removing itself into context on enter and exit, in order to make sure it works across various nesting levels. However, this replicates (better-tested) functionality in the `prefect.context` class itself, so it is preferable to reuse `prefect.context` as a context manager rather than as a manually-manipulated object. 
Specifically, while entering a `with Flow:` block modifies the active `prefect.context`, it is NOT equivalent to entering a new `with prefect.context():` block. This can lead to surprising behaviors. For example, modifying context from inside a `with Flow` …
=> Reuse prefect.context for flow context

CHANGELOG.md, docs/orchestration/agents/fargate.md, src/prefect/agent/fargate/agent.py, tests/agent/test_fargate_agent.py
It's not currently possible to enable AWS logging for Flow Runs launched with the Fargate Agent. This is a small change to allow `logConfiguration` in `containerDefinitions`, which enables logging, e.g. with AWS CloudWatch.
Adds the ability to include `logConfiguration` inside `containerDefinitions`.
The Fargate Agent can be complex to configure, especially when using it with an environment like `DaskCloudProviderEnvironment`. Being able to examine logs for Flow runs can help with debugging configuration issues. Some users may also wish to capture and store logs for Flow runs in AWS CloudWatch.
=> Allow log configuration in Fargate Agent

docs/orchestration/concepts/cli.md
I noticed today that there is a `TODO` comment visible in the docs at https://docs.prefect.io/orchestration/concepts/cli.html#interacting-with-the-cli. This PR hides it.
This is a minor change to remove a comment meant only for contributors from the user-facing documentation.
=> [docs] hide TODO from CLI docs

CHANGELOG.md, src/prefect/engine/results/s3_result.py, tests/engine/results/test_s3_result.py
Closes #2585 
Was able to reproduced using code below and fixed with handling proper ErrorCode
Code used:
```python
from prefect.engine.results import S3Result
@task(target="{task_name}-{today}")
def extract():
return [1, 2, 3]
@task(target="{task_name}-{today}")
def transform(data):
return [i * 10 for i in data]
@task
def load(data):
print("Here's your data: {}".format(data))
with Flow("ETL", result=S3Result(bucket="MY_BUCKET")) as flow:
e = extract()
t = transform(e)
l = load(t)
flow.run()
```
Results in S3:
=> Fix S3Result exists not catching ErrorCode

docs/orchestration/execution/overview.md
Reading through https://docs.prefect.io/orchestration/execution/overview.html#environments this morning, I noticed what I think is a grammatical error.
> ...should be run e.g., which executor to and whether there are any..
I think this was supposed to be:
> ...should be run e.g., which executor to [use] and whether there are any...
This PR proposes that fix to that sentence.
This is a minor fix to a grammatical error that makes one sentence in the Environments overview ambiguous.
=> [docs] fix grammatical error in Environments overview

src/prefect/agent/agent.py, src/prefect/agent/local/agent.py, src/prefect/configuration.py, src/prefect/environments/execution/dask/k8s.py, src/prefect/environments/execution/fargate/fargate_task.py, src/prefect/environments/execution/k8s/job.py, src/prefect/utilities/logging.py, tests/agent/test_agent.py, tests/environments/execution/__init__.py, tests/environments/execution/test_dask_cloud_provider.py, tests/environments/execution/test_dask_k8s_environment.py, tests/utilities/test_logging.py
This PR clarifies and finalizes the work of #2558 and #2570 with one well-placed `literal_eval`.  In particular, it ensures that any string values within a user's Prefect config are parsed / converted to the corresponding Python objects.  This is particularly useful for nested structures such as lists of strings (`extra_loggers`, secrets, etc.)
For easier debugging of our config values and consistency of typing.
=> Isolated ast.literal_eval for consistency and clarity

CHANGELOG.md, src/prefect/agent/agent.py, tests/agent/test_agent.py, tests/cli/test_agent.py
Closes #2587 
By moving the registration step to `start` all agents will be initialized with whatever necessary information (such as default label)
=> Fix LocalAgent registration with default labels

CHANGELOG.md, src/prefect/core/flow.py, src/prefect/core/task.py, tests/core/test_flow.py
A common stumbling block for new users is that they instantiate a `Task` class without realizing it hasn't been added to their flow. This is especially easy with `Parameters`:
```python
with Flow('example') as flow:
x = Parameter('x')
flow.run(x=5) # error, unexpected parameter
```
This PR adds a warning when users create tasks that don't get added to the flow:
```
UserWarning: Tasks were created but not added to the flow: 
{<Parameter: x>}. This can occur when `Task` classes, 
including `Parameters`, are instantiated inside a `with flow:` 
block but not added to the flow either explicitly or as the 
input to another task. For …
```
=> Add warning if tasks are created in flow context but not added to the flow

CHANGELOG.md, src/prefect/core/task.py, tests/core/test_task.py
When tasks are copied, which happens often in the functional API via `Task.bind()`, their attributes are carried over to the new copy. In addition, users have the opportunity to set new attributes via the `task_args` kwarg. However, any initialization logic that takes place in `Task.__init__()` based on the values of those attributes is unavailable to the copy method. This leads to inconsistencies like the one described in #2588. In the issue described in #2588, the task `Result` is modified based on the presence of a `target` attribute. When copying the task, that step doesn't take place.
Closes #2588
We want to ensure …
=> Ensure target locations are updated when tasks are copied

CHANGELOG.md, src/prefect/core/flow.py, tests/core/test_flow.py
Due to recent literal eval changes, running an agent off of `flow.run_agent` broke in some ways because it uses the labels found on the flow's environment which is a `set` instead of a `list` to enforce uniqueness.
=> Cast environment labels to list when calling run_agent from flow

src/prefect/core/flow.py, tests/core/test_flow.py
#2584 added a very convenient warning whenever tasks are initialized within a Flow context but not added to `flow.tasks`.  `Constant` tasks are a special type of task that are created whenever constants are referenced within a Task call -- one way in which they are special is that they are _not_ tracked by the `Flow` but instead are stored directly on the `Task` object.  This was causing the new warning to incorrectly be issued anytime a Constant was created under the hood.
Prevent confusing users.
**cc:** @kingsleyb
=> Dont issue warning for constant tasks

src/prefect/cli/server.py
If specific ports aren't specified then they are read from config. In config they are strings but literal eval converts them to integers. Docker compose wants _all_ strings and no integers so we have to cast these back to strings. Otherwise we get this error:
```
File "/Users/josh/Desktop/code/prefect/src/prefect/cli/server.py", line 308, in start
["docker-compose", "pull"], cwd=compose_dir_path, env=env
File "/Users/josh/miniconda3/envs/prefect/lib/python3.7/subprocess.py", line 342, in check_call
retcode = call(*popenargs, **kwargs)
File "/Users/josh/miniconda3/envs/prefect/lib/python3.7/subprocess.py", line 323, in call
with Popen(*popenargs, **kwargs) as p:
File "/Users/josh/miniconda3/envs/prefect/lib/python3.7/subprocess.py", line 775, in __init__ …
```
=> Recast server service ports to strings

CHANGELOG.md
Follow up on #2311. Pending changelog entries are now stored in the `changes/` folder, not in an unreleased section.
=> Drop unreleased section from changelog

changes/issue2568.yaml, src/prefect/__init__.py
This is common enough that we should elevate it to the toplevel
namespace.
Fixes #2568.
=> Add `case` to toplevel `prefect` namespace

changes/issue2604.yaml, src/prefect/core/flow.py, tests/tasks/test_control_flow.py
Previously adding a parameter to a flow under a `case` statement would
error if the parameter hadn't been already used (since all new tasks
under the case statment had the case set as an upstream task, and
parameters can't have upstream tasks). This fixes that.
Fixes #2604.
=> Fix parameter first usage with case

changes/pr2573.yaml, server/.dockerignore, server/Dockerfile
This PR proposes two small changes to reduce the built size of the `server/` docker image:
* clearing the `apt` cache with `rm -rf /var/lib/apt/lists/*`
* adding testing code, cache files, and documentation to that image's `.dockerignore`
If I understand correctly, the [server Dockerfile](https://github.com/PrefectHQ/prefect/blob/master/server/Dockerfile) is used to build an image that others might pull to run the Prefect Core server themselves. Cutting the size of that container reduces the amount of data that has to be transmitted to pull that image, which should make those pulls faster and less expensive.
The changes in this PR reduce the size of the built image by 2MB, tested with:
```shell
docker build \
-t prefect-server \
--no-cache \ …
```
=> cut built size of server/ container

changes/pr-2617.yaml, src/prefect/core/flow.py, src/prefect/engine/state.py, src/prefect/engine/task_runner.py, src/prefect/environments/execution/local.py, tests/core/test_flow.py, tests/engine/test_state.py, tests/engine/test_task_runner.py, tests/environments/execution/test_local_environment.py
Closes #2615
`Paused` states are a subclass of `Scheduled` states, since they imply a run in a future and allow for predetermined pauses ("Pause this task for 5 minutes"). However, they currently default to a `start_time` 10 years in the future as a "hack" to simulate "pausing". While examining an error described in #2615, I began exploring whether that was even necessary - why can't a `Paused` state just have `start_time=None`, reflecting that it's likely to run in the future but at an indeterminate time?
It turns out there is only a small set of changes that had to be made to embrace this possibility, and I strongly prefer …
=> Pause states have no "start_time"

changes/pr2630.yaml, docs/orchestration/execution/dask_cloud_provider_environment.md, docs/orchestration/execution/dask_k8s_environment.md, docs/orchestration/execution/fargate_task_environment.md, docs/orchestration/execution/k8s_job_environment.md, src/prefect/environments/execution/dask/k8s.py
Deprecates kwargs used in the setup step of this environment and updates documentation.
This method uses an outdated secret access methodology that we do not recommend. Instead users should opt for directly adding `imagePullSecrets` to their worker and scheduler yaml.
=> Deprecate private_registry and docker_secret options on DaskKubernetesEnvironment

changes/issue2623.yaml, src/prefect/engine/results/s3_result.py
Closes #2623 
We don't need to attempt to load the data at all. Only need to check existence. This call will succeed if it exists otherwise it will raise the `NoSuchKey` error that is handled.
=> Remove attempt to load data in S3Result exists function

changes/issue2626.yaml, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
Closes #2626 
Now a TLS config can be passed directly to Docker storage (https://docker-py.readthedocs.io/en/stable/tls.html#docker.tls.TLSConfig). This is very useful for CI related processes that build flows
=> Add TLS configuration option to Docker storage

changes/issue2618.yaml, src/prefect/agent/local/agent.py, tests/agent/test_local_agent.py
Closes #2618 
Uses the host IP when running LocalAgent inside of a docker container that is using the host network
Would lead to agents attempting to pull runs from other containers due to this constant hostname
=> Use host IP for `hostname` label in cases where `LocalAgent` is in container using host network

changes/issue1588.yaml, src/prefect/agent/kubernetes/agent.py, src/prefect/agent/kubernetes/resource_manager.py, src/prefect/environments/execution/dask/k8s.py, src/prefect/environments/execution/k8s/job.py, tests/agent/test_k8s_agent.py, tests/environments/execution/test_dask_k8s_environment.py, tests/environments/execution/test_k8s_job_environment.py
A few fixes to the k8s agent resource manager
- No longer delete pods explicitly. Deleting a job deletes any directly associated pods, which is all the resource manager should be concerned with. Previously this also had the fun behavior of deleting any non-running pod in a namespace (including pods that were pending or not associated with prefect).
- Only manage jobs that have a `prefect.io/identifier` label. Previously this managed all jobs in a namespace, including those not associated with prefect.
- Update our k8s labels to use a `prefect.io/` prefix, following kubernetes best practices.
Fixes #1588.
=> A few cleanups to the k8s agent resource manager

CHANGELOG.md, changes/pr2651.yaml, src/prefect/config.toml
This PR removes an old reference to `graphql/alpha` endpoint in favor of `graphql`. Requests to `graphql/alpha` will still work.
=> Remove reference to `graphql/alpha`

changes/pr2682.yaml, docs/core/tutorial/07-next-steps.md
closes #2682 
This PR fixes an incorrectly specified import of `LocalResult` in the docs.
This PR fixes an issue with the docs, so now users can properly follow along.
=> fix incorrect localresult import in docs

changes/issue-2677.yaml, src/prefect/core/flow.py, src/prefect/core/task.py, tests/core/test_flow.py
#2677 identified that the warning about unused tasks fired spuriously when tasks were defined inside the flow context. This is because the task is defined (which adds it to the task tracker) then copied, and the copy is added to the flow. The original, unused task triggers the warning.
To solve this, we relax the "new task tracker" slightly to reflect "unused tasks", and the act of copying a task counts as "using" it. This way, tasks defined inline are able to trigger the warning unless 1) added to the flow or 2) copied. This still covers all cases that originally motivated the warning, while being less intrusive to users who …
=> Don't warn on tasks defined inline and copied

changes/issue-2661.yaml, src/prefect/utilities/gcp.py, tests/tasks/gcp/test_gcs_upload_download.py
Moves google package specific imports into their respective utility function calls.
Closes #2661  **cc:** @dylanbhughes
=> Move google submodule specific imports

changes/pr2685.yaml, src/prefect/engine/results/local_result.py, tests/engine/results/test_results.py
This PR handles the `ValueError` that can sometimes be raised when instantiating a `LocalResult` on Windows with a drive other than `C:/`
Windows compatibility.  Closes #2683
=> Fix windows path check

changes/pr2671.yaml, src/prefect/cli/get.py, tests/cli/test_get.py
Adds the option to query for logs based on flow run ID. Previously only querying based on name would return the most recent run of that name. Now it can be more granular.
Also adds the ID to the output of get `flows` and `flow-runs` for more programmatic use.
CLI `get` usability
=> Add use of ID field to `get` CLI commands

changes/pr2667.yaml, docs/core/advanced_tutorials/advanced-mapping.md, docs/core/advanced_tutorials/dask-cluster.md, docs/core/advanced_tutorials/local-debugging.md, docs/test_generate_docs.py, src/prefect/config.toml, src/prefect/engine/executors/dask.py, src/prefect/utilities/importtools.py, tests/conftest.py, tests/engine/executors/test_executors.py, tests/utilities/test_importtools.py
This adds support for creating a temporary dask cluster from within a `DaskExecutor`. The cluster class and kwargs can be configured by the `cluster_class` and `cluster_kwargs` keyword arguments. By default, the class is `distributed.LocalCluster`, creating a temporary local cluster.
This also deprecates a few existing arguments:
- Deprecates `local_processes` kwarg to `DaskExecutor`, in favor of `cluster_kwargs={"processes": local_processes}`
- Deprecates `address="local"` in favor of `address=None`.
- Deprecates automatic forwarding of `kwargs` to `Client` in `DaskExecutor`, in favor of `cluster_kwargs` and `client_kwargs`.
Address part of #2508
=> Support creating temporary clusters within DaskExecutor

changes/pr2602.yaml, src/prefect/core/task.py, src/prefect/tasks/core/function.py, tests/core/test_task.py, tests/tasks/test_core.py
This is possibly too much magic.
It does two things:
- On tasks created with `@task`, the docstring is now the original
function docstring. The `__call__` and `__class__` docstrings are
still the same.
- All tasks dynamically generate a `__signature__` attribute, which
provides nicer tab completion and signature inspection when calling a
task directly (e.g. `mytask(param, other_param=1)`).
Mostly putting this up for discussion, the implementation can be cleaned
up for sure.
Fixes #2551.
=> Dynamic `__doc__`/`__signature__` on tasks

changes/pr2668.yaml, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
Closes #2654 
Instead of adding options over time this takes a similar approach to the Fargate related services and allows for setting any kwargs which are then forwarded to the docker client during the build step.
=> Add option to set build kwargs on Docker storage

changes/issue-2693.yaml, src/prefect/core/flow.py
This PR adds a manual approval step for tasks which enter a Paused state locally.
Example:
```python
from prefect.triggers import manual_only
@task
def return_1():
return 1
@task(trigger=manual_only)
def add(x):
return x + 1
with Flow("pause") as flow:
res = add(return_1)
flow_state = flow.run()
```
```...
[2020-06-02 01:47:57] 514-- INFO - prefect.FlowRunner | Flow run RUNNING: terminal tasks are incomplete.
<Task: add> is currently Paused; enter 'y' to resume:
>> y
[2020-06-02 01:47:59] 223-- INFO - prefect.FlowRunner | Beginning Flow run for 'pause'
...
```
Closes #2693 **cc:** @znicholasbrown
=> Ability to Resume paused tasks when running locally

changes/pr2691.yaml, src/prefect/cli/server.py, tests/cli/test_server.py
There is an extra_hosts addition that is added during `prefect server start` when running on Linux. This was added in #2328 however I don't think it is needed for the server as it does not need to communicate outside of its own network anyway. The PR was intended to add this option to containers created by the docker agent but it also added it to the server containers.
Removing this change as it was causing issues on some platforms when running Docker in a rootless setup. The error that commonly arose was: `invalid IP address in add-host: ""`
Link to slack thread: https://prefect-community.slack.com/archives/CL09KU1K7/p159067323 …
=> Fix running server on Ubuntu using a rootless Docker setup

docs/core/concepts/persistence.md
Fix some leftover references to `result_handler` kwarg in our docs. On a reread also felt like we needed another sentence in here about the 'time travel' desgination for cache_key.
Not confuse new users re: result handlers!
Closes #2702
=> Closes #2702. Fix mistakes re: result/result_handler in persistence docs

changes/pr2705.yaml, src/prefect/client/client.py
This PR updates the client to retry a request if it receives an `API_ERROR` code from the API. 
The client currently retries when it receives one of a few 500 codes. By detecting API_ERROR codes in the response, we can handle errors even when the GraphQL server returns a 200. The meat of this change is in lines 333-348, but I pulled some of the request logic into its own method to try and DRY the implementation.
Closes #2692 .
=> Handle API_ERROR codes

.circleci/config.yml, server/setup.py
In #2706 I removed `psycopg2` from the Server dependencies, which appeared to be fine. However, it was only fine because Server tests included Prefect with "all extras", including psycopg2. 
This PR adds psycopg2 back to the dependencies and adjusts server tests to remove all extra installs, so server is tested with "base" Prefect only.
=> Add psycopg2 back to Server dependencies; adjust unit tests to remove "extras"

changes/pr2718.yaml, server/src/prefect_server/api/states.py, server/src/prefect_server/graphql/states.py, server/tests/api/test_states.py
This PR updates the signature of the state setting pipeline to return a mapping indicating the status of the update operation. Previously, the only options were returning `None`, which meant success, and raising a `ValueError`, which indicated failure.
This PR allows alternative options, such as indicating that instead of the desired state, the state got set to `Queued`. This PR enables both tasks and flows an avenue to enter the `Queued` status, which is a prerequisite for server successfully implementing concurrency limiting.
=> update set run state signature for extensibility

changes/pr2698.yaml, src/prefect/engine/flow_runner.py, src/prefect/engine/result/base.py, src/prefect/engine/results/local_result.py, src/prefect/engine/task_runner.py, tests/core/test_flow.py, tests/engine/results/test_results.py, tests/engine/test_flow_runner.py, tests/engine/test_task_runner.py
This PR does a few things:
- stores the full absolute path to the result location for `LocalResult` (note that this change _should_ have no bearing on implementation, but instead makes sure the full path is visible in the UI)
- makes sure that `prefect.context.parameters` now also includes unprovided parameter defaults (previously this dictionary only included parameters that were explicitly passed)
- passes flow `parameters`, task `inputs` _and_ `context` to `result.write(**kwargs)` call for richer templating possibilities
- allows for users to (optionally) provide a callable location for their `Result` locations which will …
=> Result location updates

docs/.vuepress/public/state_inheritance_diagram.svg, src/prefect/engine/state.py
Updates colors for states to match those used in the UI
This may be the UI overstepping the mark but colors for states in the docs and in flow.vizualize no longer match the colors for states in the UI.  (Started with cancelled a while back and we just updated paused and resume, mainly because we didn't want paused to look too much like cancelled.)  This PR would bring them all back in line.
=> update colors to match UI

docs/core/advanced_tutorials/dask-cluster.md, docs/orchestration/concepts/flows.md
Move the warning about dask worker stealing to under the docs on version locking, since it is only relevant in that case.
People deploying on Dask are probably reading our deployment tutorial first, but are unsure if enabling worker stealing (which they are likely prefer to optimize their Dask cluster later) is the source of any other issues they might have.
=> Move worker stealing warning in docs

changes/pr2653.yaml, src/prefect/config.toml, src/prefect/environments/storage/azure.py, src/prefect/environments/storage/base.py, src/prefect/environments/storage/docker.py, src/prefect/environments/storage/gcs.py, src/prefect/environments/storage/local.py, src/prefect/environments/storage/s3.py, src/prefect/serialization/storage.py, tests/environments/storage/test_base_storage.py, tests/environments/storage/test_local_storage.py, tests/serialization/test_storage.py
closes #2653 
This PR includes a flag on `LocalStorage` which will disable including hostname as the default label. By default, the `add_hostname_label` flag defaults to `True`, maintaining backwards compatibility.
See issue.
=> add flag to include hostname on local storage

changes/pr2657.yaml, docs/orchestration/execution/dask_k8s_environment.md, src/prefect/environments/execution/dask/k8s.py, tests/environments/execution/test_dask_k8s_environment.py
It is now easier to directly specify the name of an `imagePullSecret` to be used for the scheduler and worker pods. *Note* this is only for the quick configuration options and has no effect on custom specs.
This is a point of confusion and sometimes users do not want to provide custom worker & scheduler specs.
=> Add direct option to set imagePullSecrets on DaskKubernetesEnvironment

changes/pr2725.yaml, src/prefect/client/client.py, src/prefect/engine/cloud/flow_runner.py, tests/client/test_client.py, tests/engine/cloud/test_cloud_flow_runner.py, tests/engine/cloud/test_cloud_flows.py
closes #2724 
This PR will update the `Client.set_flow_run_state` signature to return the new `State`, as opposed to `None`.
This PR allows future extensibility by allowing logic to be placed between receiving a response from Cloud and the cloud flow runner reacting to it.
=> update set_flow_run_state signature for flow meta state future use

changes/issue2726.yaml, src/prefect/core/flow.py, tests/core/test_flow.py
Closes #2726 
Cleans up the intermediate source file that is kept around when visualizing the flow
=> Fix flow.visualize cleanup of source files when using filename

src/prefect/client/client.py, src/prefect/core/flow.py, src/prefect/environments/storage/docker.py, tests/client/test_client.py, tests/core/test_flow.py
If a registry or name are not provided to Docker storage then the value of `storage.name` will raise an error if the storage has not been built yet (we add a random name/tag on build if not set). This moves the place where the `storage.name` is appended to the `environment.metadata` to _after_ the build.
=> Fix env metadata not having access to name of Docker storage

changes/pr2738.yaml, src/prefect/serialization/state.py, tests/serialization/test_states.py, tests/serialization/test_states_shadow_schema.py
Uses a fully-qualified path to the Marshmallow schema for States in order to avoid conflicts with any user-registered schemas by the same name (since Marshmallow doesn't know how to disambiguate)
See for example https://prefect-community.slack.com/archives/CL09KU1K7/p1591564929493200?thread_ts=1591186834.311100&cid=CL09KU1K7
=> Use fully-qualified path to avoid conflicts with other registered schemas

.circleci/config.yml, Dockerfile, changes/pr2745.yaml, docs/core/getting_started/installation.md
Adds an `all_extras` `prefecthq/prefect` image to be built on releases of Prefect.
When doing something like:
```python
f.storage = S3(bucket="my-flows", secrets=["AWS_CREDENTIALS"])
f.environment = RemoteEnvironment(metadata={"image": "image/name:here"})
```
The `image` needs to have the dependencies present for the selected `storage` (in this case, prefect's `aws` extras). This adds an image with `all_extras` and it acts as a self contained image with even more packages baked in. In this case you can use the entire task library without ever having to build an image for deployment.
(edited)
-----
Original text: 
> When doing …
=> Add new CI step for a prefect image with all_extras installed

docs/orchestration/agents/overview.md
This PR fixes a small issue in [the Agent documentation](https://docs.prefect.io/orchestration/agents/overview.html), where `DockerAgent` is not imported correctly in sample Python code.
This fixes an inaccuracy in the documentation, which should prevent that inaccuracy from slowing users down as they learn about Prefect agents.
Currently, the docs have this pattern
```python
from prefect.agent import DockerAgent
```
which results in this error on `prefect` 0.11.5
> Traceback (most recent call last):
ImportError: cannot import name 'DockerAgent' from 'prefect.agent' …
=> [docs] fix import in Agent docs

docs/orchestration/agents/local.md, docs/orchestration/concepts/cli.md, docs/orchestration/concepts/flows.md, docs/orchestration/concepts/projects.md, docs/orchestration/tutorial/docker.md, docs/orchestration/tutorial/first.md, docs/orchestration/tutorial/multiple.md, src/prefect/cli/create.py, src/prefect/tasks/prefect/flow_run.py
This is a follow-up to #2776 . Working through the [First Flow docs](https://docs.prefect.io/orchestration/tutorial/first.html#register-flow-with-the-prefect-api), I came across this language:
> Prefect Cloud allows users to organize flows into projects. In this case we are using the default Hello, World! Project.
> `flow.register(project_name="Hello, World!")>
The use of the word "default" made me think that I could call that code as-is and that it would attach my flow to a project `Hello, World` that is created automatically when you create a Prefect Cloud account.
But that is not what happened:
> Traceback (most recent call last):
File "/home/jlamb/miniconda3/lib/python3.7/site-packages/prefect/core/flow.py", …
=> [docs] standardize example project name

changes/pr2773.yaml, src/prefect/engine/state.py, tests/engine/test_state.py
Currently, states with no message have a repr like this, which isn't helpful:
```python
s = Success()
repr(s)
```
This PR cleans it up a little when `message is None`:
```python
s = Success()
repr(s)
s2 = Success(message='hi')
repr(s)
```
=> Improve state `__repr__`

docs/orchestration/concepts/flows.md, docs/orchestration/tutorial/docker.md, docs/orchestration/tutorial/first.md, docs/orchestration/tutorial/multiple.md
This PR changes the language in `orchestration/` docs to make it clear that `project_name` is required when registering a flow with Prefect Cloud.
Thanks for the AWESOME documentation! It's made it really easy to work with Prefect. Following the example from https://docs.prefect.io/orchestration/tutorial/first.html#write-flow, I tried to register the example flow code there with Prefect Cloud (I already have Cloud setup and an agent configured).
```python
import prefect
@task
def hello_task():
logger = prefect.context.get("logger")
logger.info("Hello, Cloud!")
flow = Flow("hello-flow", tasks=[hello_task])
flow.register()
```
On `flow.register()`, I got this error:
> Traceback (most recent call last):
File …
=> [docs] make it clearer that project is required with Prefect Cloud

.pylintrc, server/src/prefect_server/utilities/names.py, src/prefect/utilities/serialization.py
^ as the title states, it removes references to "whitelist" and "blacklist" wherever possible. There are two notable places where this wasn't possible (as far as I can tell): the `method_whitelist` kwarg for **urllib3** and the **VSCode** > `extension-pkg-whitelist`, for `pylint`.
Language is important.
=> Remove references to "whitelist" and "blacklist" wherever possible

changes/pr2758.yaml, docs/outline.toml, src/prefect/__init__.py, src/prefect/core/__init__.py, src/prefect/core/flow.py, src/prefect/core/parameter.py, src/prefect/core/task.py, src/prefect/serialization/flow.py, src/prefect/serialization/task.py, tests/core/test_flow.py, tests/core/test_parameter.py, tests/flows/test_parameter.py
As I work with Parameters to increase their "first-class-ness", including extensions of #2755, I'm becoming acutely aware of the awkwardness of accessing them from `core/task.py`. This PR moves them to a more appropriate home, `core/parameter.py`. It makes no other changes to behavior or code.
I believe this is not a user-facing change as we have always encouraged accessing them at the top-level (in fact, our own code only referenced `task.Parameter` three times), but I've added a backwards-compatible access nonetheless.
So this remains the recommended access:
```python
from prefect import Parameter
```
But these are also …
=> Move parameters to standalone module

changes/pr2782.yaml, src/prefect/tasks/database/sqlite.py, tests/tasks/test_sqlite.py
Support for using the `db` argument at run time in `SQLiteQuery` and `SQLiteScript` has been added. It is directly related to this issue: https://github.com/PrefectHQ/prefect/issues/2405
Due to the fact that we can provide `db` arugment for the`run` method, we can also start parameterizing this argument in `Flow` using `Parameter`.
=> Add support for db argument at run time in the SQLiteQuery and SQLiteScript

changes/pr2768.yaml, docs/orchestration/agents/fargate.md, src/prefect/agent/fargate/agent.py, tests/agent/test_fargate_agent.py
This PR adds a function to the fargate agent for validating the configuration that it was provided. For example something like this could happen:
```python
agent = FargateAgent(
aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
region_name="us-east-1",
cpu="1024",
memory="8192",
executionRoleArn="my_arn...",
containerDefinitions=[
{
"logConfiguration": {
"logDriver": "awslogs",
"options": {
"awslogs-region": "us-east-1",
"awslogs-group": "my_group",
"awslogs-stream-prefix": "prefect",
},
},
}
],
networkConfiguration={
"awsvpcConfiguration": {
"assignPublicIp": "ENABLED", …
```
=> Add config validation utility to Fargate Agent

changes/pr2780.yaml, src/prefect/environments/execution/dask/k8s.py, src/prefect/environments/execution/k8s/job.py
This PR correctly uses the `PrefectSecret` interface for retrieving secrets declared on Storage when running with the k8s / dask k8s environments.
Bug fix.
=> Fix how storage secrets are populated within k8s and dask k8s environments

changes/pr2783.yaml, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/flow_runner.py
This pr fixes a minor bug that resulted from #2707. `CloudTaskRunner.run()` begins by instantiating a default context as `context = context or {}`, and the passed context has a default of None. Since no `context` was being passed to this method, [this call](https://github.com/PrefectHQ/prefect/blob/d52cc24981a43ea12b7c6d10c6280aa24aa3efc0/src/prefect/engine/cloud/task_runner.py#L325) would fail when attempting an in-process retry since context was empty.
=> Fix context passing for Cloud

changes/pr2744.yaml, src/prefect/agent/kubernetes/agent.py, src/prefect/agent/kubernetes/deployment.yaml, src/prefect/agent/kubernetes/job_spec.yaml, src/prefect/cli/agent.py, tests/agent/test_k8s_agent.py, tests/cli/test_agent.py
Closes #2547 
Closes #2721 
Closes #2633 
You can now set imagePullPolicy and ServiceAccount name on jobs created by the k8s agent. Also adds the option to set `--api` on `prefect agent start` (previously was only on `install`)
=> Some minor agent enhancements

changes/pr2769.yaml, src/prefect/core/task.py, src/prefect/engine/task_runner.py, tests/engine/test_task_runner.py
This PR allows for task targets to be both strings and callables. This is similar to how result locations can also be both. e.g.:
```python
@task(target=lambda **kwargs: "{task_name}-88")
def get_data():
"""test"""
return "data"
@task
def print_data(data):
print(data)
with Flow("using-targets", result=LocalResult(), ) as flow:
data = get_data()
print_data(data)
flow.run()
```
```
[2020-06-11 21:50:17] DEBUG - prefect.LocalResult | Starting to upload result to get_data-88...
[2020-06-11 21:50:17] DEBUG - prefect.LocalResult | Finished uploading result to /Users/josh/.prefect/results/get_data-88...
...
[2020-06-11 21:50:19] DEBUG …
```
=> Allow for task targets to be callables

changes/pr2794.yaml, src/prefect/agent/kubernetes/resource_manager.py
Previously we'd do a full list in each loop of `clean_resources`. Under
heavy load, this may return a large list, which can use more resources
than desired. We now use the paginated api, listing in sets of 20.
We also explicitly set `propagationPolicy="Foreground"` when deleting
jobs to ensure that child objects are also deleted and not orphaned.
AFAIK this shouldn't be necessary, but for some reason is on my local
kubernetes install (1.15.5). No harm is done by setting it though.
=> Use pagination in k8s resource manager

docs/orchestration/execution/storage_options.md
Congrats on release 0.12.0! I'm very excited about non-docker storage options for `KubernetesAgent` agents (#2666). I was reading through the documentation introduced in that PR, and found one sentence that was confusing. This looks like it was two separate sentences that were spliced together:
> Due to the cloud storage options have sensible defaults for labels make sure the agent's labels match the desired labels for the flows' storage objects.
This PR proposes clarifying that language.
This PR might improve users' understanding of how to use non-docker storage with `KubernetesAgent`.
=> [docs] clarify language on non-docker storage for KubernetesAgent

changes/pr2669.yaml, src/prefect/config.toml
This reverts commit 29f5094c71208a94b572ac53ec79ac1e34690cb1.
stop referring to /alpha subpath behind /graphql
the "official" prefect cloud api path
=> Revert "Revert "Remove reference to `graphql/alpha`""

changes/pr2817.yaml, src/prefect/engine/executors/dask.py, tests/engine/executors/test_executors.py
With the changes from depth-first execution and the executor refactor, the `DaskExecutor` could be simpler in implementation. We delete some code that's no longer needed.
=> Simplify dask executor implementation

changes/pr2811.yaml, src/prefect/tasks/notifications/email_task.py, tests/tasks/notifications/test_email_task.py
MIME type `text/html` has been set as the default option for `EmailTask`. This was done in accordance with what was mentioned in the issue: https://github.com/PrefectHQ/prefect/issues/2487
Minor changes:
* start using `ssl.create_default_context`, which provides much better default options for sending emails - https://docs.python.org/3/library/ssl.html#ssl.create_default_context 
* adding **error handling** when specifying unsupported `smtp_type`
We are increasing the possibilities offered by EmailTask. From now on it will be able to start sending emails with correctly rendered HTML code.
```
email = EmailTask(
subject='Hello …
```
=> Add support for HTML content in the EmailTask

changes/issue2815.yaml, src/prefect/engine/cloud/task_runner.py
Eliminates redundant, repeated debug logging re: _can't use cache because no candidate Cached states were valid_
Redundant logging message make remainder of logging harder to use.
=> Quiet "no valid cached states" logging

changes/pr2819.yaml, src/prefect/engine/executors/dask.py, tests/engine/executors/test_executors.py
- Fixes `LocalDaskExecutor` to only compute once. Previously this would recompute tasks, sometimes many many times (the comment saying "twice" was being optimistic).
- Adds support for setting task names in the `LocalDaskExecutor`.
Also a few misc cleanups.
=> Cleanup `LocalDaskExecutor`

docs/orchestration/concepts/cloud_hooks.md
Simple change to update a GQL command in the docs that is not valid GraphQL - the JSON payload must be passed as a literal JSON string or variable.
=> Update docs to use JSON literal

changes/pr2828.yaml, src/prefect/client/client.py, tests/client/test_client.py
This field should be populated by default in order to ensure flows are deployable without extra configuration
Could remove some potential hidden frictions for new users
=> Set default env metadata image

changes/pr2831.yaml, src/prefect/engine/executors/dask.py, src/prefect/engine/flow_runner.py, tests/engine/executors/test_executors.py, tests/engine/test_flow_runner.py
Dask infers if different tasks do similar things with some custom
key-name splitting heuristics (it's *mostly* splitting by `-`, but not
entirely). The previous key names generated by mapped tasks didn't play
nice with this heuristic, resulting in the dask UI not grouping tasks
appropriately. This fixes that.
Fixes #2821
=> Generate better dask task key names

src/prefect/environments/storage/docker.py
The documentation for `prefect.environments.storage.docker.Docker.create_dockerfile_object()` says that `directory` is optional, but it's currently required. This PR fixes the the documentation to match the code.
This resolves a minor inconsistency in the documentation that might lead users to make a mistake the first time they use `create_dockerfile_object()`.
=> [docs] fix doc on Docker.create_dockerfile_object()

changes/pr2839.yaml, server/src/prefect_server/graphql/states.py, server/tests/graphql/test_states.py
This PR changes the `set_flow_run_states` and `set_task_run_states` mutations to return the status from the underlying function call.
This PR is important for implementing `Queued` statuses for both flows and tasks, as it forwards the signals back to core.
=> Update graphql responses with underlying api response statuses

changes/pr2838.yaml, src/prefect/client/client.py
In `client.register()`, the client checks if the flow is using `Docker` storage and, if so, gets the image from that storage and puts it on `flow.environment.metadata["image"]`. This PR proposes ~doing that *before* capturing the serialized flow with `flow.serialize()`.~ updating `serialized_flow` after doing that.
This will help users avoid a mistake that I just made, which took a bit of time to debug.
I've been using `KubernetesAgent` and `KubernetesJobEnvironment`, and experimenting with different types of storage. From a previous attempt that was using `S3` storage, I had an image set in the environment's `metadata` left over in my `KubernetesJobEnvironmnet` code:
```python
env = KubernetesJobEnvironment(
job_spec_file="prefect-flow-run.yaml",
metadata={
"image": …
```
=> make sure `environment` and serialized flow in client.register() match

changes/pr2849.yaml, docs/orchestration/execution/fargate_task_environment.md, docs/orchestration/execution/k8s_job_environment.md, src/prefect/environments/execution/__init__.py, src/prefect/environments/execution/base.py, src/prefect/environments/execution/dask/job.yaml, src/prefect/environments/execution/dask/k8s.py, src/prefect/environments/execution/fargate/fargate_task.py, src/prefect/environments/execution/k8s/job.py, src/prefect/environments/execution/local.py, tests/environments/execution/test_base_environment.py, tests/environments/execution/test_dask_k8s_environment.py, tests/environments/execution/test_fargate_task_environment.py, tests/environments/execution/test_k8s_job_environment.py
*created from [this conversation in Prefect Community Slack](https://prefect-community.slack.com/archives/CL09KU1K7/p1592925843192100)*
This PR proposes changing the behavior of `Environment.run_flow()`. Today, if you call this method on an instance of `Environment` or any child class of it, `run_flow()` will use the executor in `self.executor` if that attribute has been set.
https://github.com/PrefectHQ/prefect/blob/191f429cdb1c48cde1b2636e2fa04e24f94dfb79/src/prefect/environments/execution/base.py#L133-L135
That strategy means that despite the changes from #2805 , it is not currently possible to use `KubernetesJobEnvironment` and `DaskExecutor` together. That is because flows that use `KubernetesJobEnvironment` end up being run with `KubernetesJobEnvironment().run_flow()` …
=> respect executor from environment

changes/issue2875.yaml, src/prefect/agent/fargate/agent.py, tests/agent/test_fargate_agent.py
Closes #2875 
The eval parses the contents of containerDefinitions but an extra eval needs to be added to parse the containerDefinitions prior if it is provided as a string through the CLI
=> Fix Fargate agent not parsing containerDefinitions if provided as string

changes/issue2878.yaml, src/prefect/agent/fargate/agent.py, tests/agent/test_fargate_agent.py
Closes #2878 
boto3 has some kwargs for `containerDefinitions` that don't have to be provided however if an empty value is set for them at all (`[]` or `{}`) then it requires them to be populated.
=> Fix Fargate agent providing empty parameters if not set

changes/pr2893.yaml, src/prefect/engine/cloud/task_runner.py, tests/engine/cloud/test_cloud_task_runner.py
Updates `cloud/task_runner.py` to send a heartbeat on each iteration of the retry loop.
This is a step towards making a backend API aware of when a task run is still out there retrying or queued and that it should not be readded to the work queue.
=> Update task runner to send heartbeat on each iteration of a retry loop

src/prefect/cli/auth.py
The -r (scope) option does not exist in version 0.12.2
-s must be used to specify the scope of the token (role is not used anymore)
The -r (scope) option does not exist in version 0.12.2
-s must be used to specify the scope of the token (role is not used anymore)
CLI help is currently wrong and command does not work:
```
$ prefect auth create-token -n my-runner-token -r RUNNER
Usage: prefect auth create-token [OPTIONS]
Try 'prefect auth create-token -h' for help.
Error: no such option: -r
```
Current documentation is as follow:
```
$ prefect auth create-token -h
Usage: prefect auth create-token [OPTIONS]
Create a Prefect Cloud …
```
=> UPDATED runner create-token command in CLI help

docs/orchestration/tutorial/configure.md
The -r (scope) option does not exist in version 0.12.2
-s must be used to specify the scope of the token (should be changed in the command line help as well)
The -r (scope) option does not exist in version 0.12.2
-s must be used to specify the scope of the token (should be changed in the command line help as well)
Documentation is currently wrong and command does not work:
```
$ prefect auth create-token -n my-runner-token -r RUNNER
Usage: prefect auth create-token [OPTIONS]
Try 'prefect auth create-token -h' for help.
Error: no such option: -r
```
=> UPDATED runner create-token command in docs

changes/pr2906.yaml, src/prefect/schedules/clocks.py, tests/schedules/test_clocks.py
This PR fixes an edge case involving interval clocks with short intervals and DST-observing start dates far in the past.
Scheduling should be robust!
**cc:** @zdhughes / @jlowin this fixes the issue we were poking at earlier today
=> Fix edge case in Interval Clocks

requirements.txt
This PR bumps the version ceiling for `cloudpickle` to 1.6, since version 1.5.0 was released yesterday. See #2910 for more background and discussion.
This PR makes it possible to install the version of `prefect` that is currently on `master` if you have the latest released version of `cloudpickle` installed, so that users don't hit the situation where their versions of `prefect` and `cloudpickle` are incompatible.
In my opinion this version ceiling should be removed completely, but I think for now at least bumping it to 1.6 would fix the immediate issue.
=> bump cloudpickle version ceiling to 2.0

changes/pr2914.yaml, src/prefect/agent/agent.py, src/prefect/client/client.py, tests/agent/test_agent.py
This is following the conversion in [2908](https://github.com/PrefectHQ/prefect/discussions/2908), to reduce the latency in executing the flow runs by agent process due to loop intervals.
The PR implements a poke handler to wake up agent process and start processing the flow runs.
The current loop interval adds a sort of limitation when prefect needs to be invoked in realtime scenarios. The poke handler implemented in this PR provides a way for users to trigger the flow execution without waiting for loop interval to complete.
=> Added poke handler to notify agent process of available flow runs

docs/orchestration/agents/local.md
Adds a note to the docs recommending using an init process like `tini`
when running the local agent inside a docker container.
Fixes #2418.
=> Recommend `tini` when running local agent in docker

changes/pr2920.yaml, requirements.txt, src/prefect/engine/executors/base.py, src/prefect/engine/executors/dask.py, tests/engine/executors/test_executors.py
Previously when the `executor.start()` contextmanager would exit early (say on an interrupt or error), there might be background work still happening, since the executor wouldn't wait for or cancel the remaining submitted tasks.
We now attempt to cancel all pending work running on the executor, and wait for tasks that haven't completed in cases where we can't efficiently/robustly cancel them. This ensures that when `executor.start()` exits, no tasks will continue to progress.
- For a `DaskExecutor` with a temporary cluster, we shutdown the cluster, so no lingering work can persist.
- For a `DaskExecutor` with an external cluster (specified with an `address`) or an `inproc` cluster (using local threads only), we stop all pending tasks and wait for all running tasks to finish.
- For a …
=> Executor leaves no background work upon exiting `start` contextmanager

changes/issue1262.yaml, src/prefect/utilities/debug.py
This fixes an issue where if the user is running a Python that is not
the default Python on their $PATH then is_serializable fails because
it invokes a subprocess running a different Python (the system
default). This would occur if e.g. the user is running the executable
from a virtual env without first activating the virtual environment.
N.B. I haven't added a test specifically for this fix because the amount of test engineering you'd have to do around running multiple Pythons is almost certainly not worth the trouble.
It resolves an old and probably uncommon issue, #1262 , so "important" is a bit much. But you may find it …
=> Same Python exe for is_serializable subprocess

changes/pr2934.yaml, src/prefect/cli/describe.py, tests/cli/test_describe.py
Previously the default format for `prefect describe` was to print the
python object. This is similar to json, but not actually json. There's
not a good reason to not use json, so we default to json formatting, and
also add yaml as an option. We also pretty-print the json to make it
easier to read.
Fixes #2926.
=> Improve output format in prefect describe cli

.circleci/config.yml, update_changelog.py
A few improvements to the changelog script
- Drop unused sections, instead of inserting `- None` lines.
- Add `lint` subcommand for validating changelog entries
- Add the linting to the CI run
=> Changelog script improvements

changes/pr2916.yaml, docs/outline.toml, src/prefect/tasks/kubernetes/__init__.py, src/prefect/tasks/kubernetes/job.py, tests/tasks/kubernetes/test_job.py
In this PR, I created the `RunNamespacedJob` task according to what was given in this issue: https://github.com/PrefectHQ/prefect/issues/2281
Generally, the flow looks like this: first, a task is created on the Kubernetes cluster as specified in the `body` argument. Then, in five-second intervals, the Kubernetes API is asked about the status of a given job, if the job has been successfully completed, then all of its rescuers are removed from the cluster: both job and corresponding pods. If the job on Kubernetes failed, the resources are not cleaned so that the user can find out the cause of the failure.
Design decisions:
* …
=> Implement RunNamespacedJob task for Kubernetes 

changes/pr2935.yaml, src/prefect/engine/signals.py, src/prefect/tasks/prefect/flow_run.py, tests/engine/test_signals.py, tests/tasks/prefect/test_flow_run.py
This PR adds a new `wait` kwarg to `FlowRunTask` which will wait until the triggered flow run completes, and reflect the corresponding state back in this task.  Note that an idempotency key is used so that retries, etc. work robustly without triggering new flow runs.
This task can now be used to create flow-to-flow dependencies
=> Mirror flow run state within task

docs/core/concepts/results.md
After attempting to setup result storage on my local machine and failing, got some answers from @cicdw in Slack which I think should be added / updated on the `concepts/results.md` documentation.
Specific slack conversation reference: [here](https://prefect-community.slack.com/archives/CL09KU1K7/p1594417008008500)
Shortened:
> Hey Jackson - if you’re running this locally you additionally need to set the environment variable `PREFECT__FLOWS__CHECKPOINTING=true` to “turn on” the feature (it is enabled by default against a backend but toggleable for local runs for testing >purposes)
Better docs means people don't ask the same question as me later on :tada:
=> Add tip about enabling checkpointing and change the task definition

changes/issue2656.yaml, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/state.py, src/prefect/utilities/tasks.py, tests/engine/test_state.py
This PR fixes a very specific situation, where if a Mapped pipeline doesn't complete due to zombie tasks, _and_ if there is a "reducer" task downstream of the mapped task, on the next run of that pipeline the reducer task will receive incomplete data.  Ultimately this was caused by the task runners not properly re-loading mapped children state results.
Closes https://github.com/PrefectHQ/prefect/issues/2656
=> Fix zombie maps

changes/pr2950.yaml, src/prefect/environments/execution/k8s/job.py, tests/environments/execution/test_k8s_job_environment.py, tests/serialization/test_environments.py
This PR is my attempt to implement this suggestion: https://github.com/PrefectHQ/prefect/issues/2829#issuecomment-652544616.
It splits `KubernetesJobEnvironment._populate_job_spec_yaml()` into two methods:
* `._populate_build_time_job_spec_details()`: fill in bits of the job spec that can be known at build time when  `KubernetesJobEnvironment` is initialized
* `_populate_run_time_job_spec_detailis()`: fill in details of the job spec that can only be determined at run time of a flow (like the `flow_run_id` and prefect-specific  environment variables)
Right now, all prefect customization of the user-provided job spec happens at run time. This means that it isn't possible to change the `args`  and `command` for the container that runs `prefect.environments.execution.load_and_run_flow()`. …
=> move some job_spec details for KubernetesJobEnvironment to build time

server/src/prefect_server/cli/dev.py
Closes #2809. A while ago I changed the name of this function for clarity (https://github.com/PrefectHQ/prefect/pull/2299#pullrequestreview-390186444) but missed updating it in this spot in the dev CLI commands.
build image CLI utility for server dev doesn't work without it, and it's a flake8 error too!
=> Closes #2809. Fix flake8 error in server dev CLI code

changes/pr2965.yaml, src/prefect/engine/state.py, tests/engine/test_state.py
This PR fixes an issue where Metastates could compound and eventually hit recursion errors when serialized / deserialized.
This situation actually can arise in task tag concurrency limit, when the limit takes a long time to hit, see discussion here: https://github.com/PrefectHQ/prefect/issues/2884
=> Fix metastate recursion

changes/pr2961.yaml, src/prefect/tasks/dbt/dbt.py, src/prefect/tasks/shell.py, tests/tasks/test_shell.py
Adds a `log_stderr` boolean kwarg to ShellTask and DbtShellTask for logging the full output in the case of a non-zero exit code.
User encountered a case where an error in their DbtShellTask didn't output the full traceback
=> Add option to log the output from stderr in the case of non-zero exit codes in ShellTask

changes/pr2973.yaml, src/prefect/environments/execution/dask/job.yaml, src/prefect/environments/execution/dask/k8s.py, src/prefect/environments/execution/dask/worker_pod.yaml, tests/environments/execution/test_dask_k8s_environment.py
This PR:
- removes blocked handlers from the dask k8s environment spec (stale code essentially)
- changes the default value of work stealing to `True`
Turning work stealing off hampers the dask scheduler's ability to distribute work, and was originally turned off to avoid bad UX with version locking.  Might help #2958
=> Remove stale env vars on dask k8s and update work stealing default

changes/issue2069.yaml, docs/outline.toml, src/prefect/tasks/aws/__init__.py, src/prefect/tasks/aws/secrets_manager.py, tests/tasks/aws/test_secrets_manager.py
Adds a task that enables secrets to be retrieved from AWS secrets manager.
This feature has been demanded by several users (see [issue 2069](https://github.com/PrefectHQ/prefect/issues/2069)).
closes #2069
=> added task AWSSecretsManager and tests

changes/pr2977.yaml, src/prefect/engine/cloud/task_runner.py
This PR sends regular heartbeats (every 30 seconds) to the backend API while waiting to Retry / Dequeue a task run.
This allows Cloud to know that a process is out in the world waiting to rerun this task run, so that we can prevent flooding agents with unnecessary / redundant work.
=> Send regular heartbeats while waiting to retry /dequeue

setup.py
It simply introduces a `py.typed` file and includes in the `setuptools` configuration. This follows from [PEP-0561](https://www.python.org/dev/peps/pep-0561/).
This lets type checkers (like `mypy`) use the type hints present in the library.
The current behavior with the package:
```bash
$ mypy -c 'import prefect; reveal_type(prefect.Flow("test"))'
<string>:1: error: Skipping analyzing 'prefect': found module but no type hints or library stubs
<string>:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
<string>:1: note: Revealed type is 'Any'
Found 1 error in 1 file (checked 1 source file)
``` …
=> Add py.typed to allow type hints to pass into userland

changes/issue1345.yaml, src/prefect/tasks/postgres/postgres.py, tests/tasks/postgres/test_postgres.py
This PR removes `password` as a possible kwarg in the initialization of the postgres tasks in the task library in favor of providing the password at runtime via a Secret task type. 
Closes https://github.com/PrefectHQ/prefect/issues/1345
Prefect should encourage best practices, and having this initialization kwarg meant that passwords would be baked into where ever the Flow was stored.
=> Remove password from init method of postgres tasks

changes/pr2995.yaml, src/prefect/core/parameter.py, tests/core/test_parameter.py
This allows creating a parameter with a default of `None` without explicitly setting `required=False`. I find this more intuitive to use - any value can be passed to `default` to create an optional `Parameter`, `None` is no longer special-cased.
=> Support passing in explicit `default=None` to Parameter

docs/core/idioms/idioms.md, docs/core/idioms/resource-manager.md
Adds an idiom on using the `resource_manager` api, with an example using a temporary dask cluster.
=> Add idiom on resource-manager api

changes/pr2980.yaml, setup.py, src/prefect/tasks/dbt/dbt.py, tests/tasks/dbt/__init__.py, tests/tasks/dbt/test_dbt.py
First off, adds `return` that I think just got missed in the original dbtshelltask. Otherwise the stdout from dbt being run in the shell is not retrieved as the return value of the task, against what is says in its docstrings and the intention of ShellTask itself and presumably its derivatives. This was brought up in this slack thread: https://prefect-community.slack.com/archives/CL09KU1K7/p1594912760250100
While writing tests I realized that the super method was also failing to forward …
=> Some cleanups to dbtshelltask

src/prefect/tasks/prefect/flow_run.py, tests/tasks/prefect/test_flow_run.py
Adds in another change to FlowRunTask to the mega PR that allows people to send NEW context through to the newly generated flow run (closes #2941). I made this a PR to the mega PR to show what I wanted to add but it can go in separately too.
At least one person from the community is avoiding FlowRunTask and calling the client directly to be able to expose this, so this way they can use our official task instead!
=> add option to send in new context to new flow run from FlowRunTask

changes/pr3009.yaml, src/prefect/engine/executors/dask.py
In certain configurations (systems where a distributed scheduler may be addressable via multiple IPs, and somehow multiple get used due), unpickling a `distributed.Variable` can do the wrong thing and create a new `Client` each time, potentially exhausting file descriptors.
This fixes that by avoiding pickling the `Variable` - instead we recreate it on usage. This is no more expensive than before, but in *the bad case* is much less expensive.
This bad behavior was introduced in version 0.12.3, and affects users using external dask clusters (i.e. an explicit `address` is passed to `DaskExecutor`), and not every user may run into it (I was able to reproduce on a dockerized system but not locally, the actual buggy code has to do with differences in address resolution for the scheduler - I …
=> Avoid `distributed.Variable` pickle usage

changes/pr3012.yaml, src/prefect/client/client.py, src/prefect/config.toml
This PR adds a `retry_on_api_error` flag to the client. Wasn't 100% sure of a clean way to test this, but happy to add tests if it's appropriate.
This allows us to opt out of retrying nonatomic mutations, as discussed in #3004.
=> Add flag for API error retries

changes/pr3018.yaml, setup.py
`dbt` pins all its dependencies, and doesn't generally play well with
others when used as a library. Their extreme dependency pinning was
causing complications with other dependencies (e.g. conflicts with
versions of `google-cloud-bigquery`). Since most users will have `dbt`
installed as a CLI, and prefect only uses it as a CLI, we remove the
package from our immediate dependencies.
=> Remove `dbt` extra

changes/pr3026.yaml, src/prefect/agent/docker/agent.py, tests/agent/test_docker_agent.py
Adds an option for Docker Agent to only pull from registries specified in the `reg_allow_list`
To ensure that if someone where to get access to your Prefect Account they would not be able to run their own images.
=> Add option to limit Docker Agent to only pull images from some registries.

changes/pr3029.yaml, src/prefect/environments/storage/docker.py
The success of building the the Docker Storage is determined if an image with the name exists running the build. This PR changes it to requiring to match on both name and tag to ensure uniqueness. See issue #3015 for more details.
This ensures that the build report that it failed when it is the case.
=> Use fullname and tag when Docker Storage determines if build was successful

changes/pr3031.yaml, src/prefect/environments/execution/fargate/fargate_task.py, tests/environments/execution/test_fargate_task_environment.py
This PR adds a validation step in the `FargateTaskEnvironment` setup to verify the given task definition. 
It attempts to give a very helpful `ValueError` to point out the exact inconsistency.
For instance, if you update the image and cpu in your `FargateTaskEnvironment` you'll be greeted with:
```
ValueError: The given taskDefinition does not match the existing taskDefinition {family}.
Detail:
containerDefinition.0.image -> Given: test/image:newtag, Expected: test/image:tag
cpu -> Given: 1024, Expected: 512
If the given configuration is desired, deregister the existing
taskDefinition and re-run the flow. Alternatively, you can …
```
=> Update FargateTaskEnvironment to throw if task definition is inconsistent with existing task definition

changes/issue3027.yaml, src/prefect/environments/storage/azure.py, src/prefect/environments/storage/docker.py, src/prefect/environments/storage/gcs.py, src/prefect/environments/storage/github.py, src/prefect/environments/storage/local.py, src/prefect/environments/storage/s3.py, tests/environments/storage/test_azure_storage.py, tests/environments/storage/test_docker_storage.py, tests/environments/storage/test_gcs_storage.py, tests/environments/storage/test_github_storage.py, tests/environments/storage/test_local_storage.py, tests/environments/storage/test_s3_storage.py
These changes will allow a user to initialize an S3 Storage object with a bucket name and object key, then call `get_flow()` without any args to retrieve that object from S3. Previously, a call to `add_flow()` would need to have been made to add entries to `self.flows()` and `self._flows()`, or the dictionaries would have to be set by the user. If this was not done `get_flow()` would raise an exception. 
Simplifies process of downloading a Flow from S3 Storage.
=> Issue 3027 remove storage objects check get flows

src/prefect/tasks/azureml/dataset.py, src/prefect/tasks/great_expectations/checkpoints.py, src/prefect/utilities/notifications/jira_notification.py
In the interest of contributing back, I ran `pylint src/prefect` tonight. It turned up a bunch of things, many of which are subjective style / formatting things.
This PR addresses one of the issues found which could actually lead to user-facing bugs:
> W0102: Dangerous default value {} as argument (dangerous-default-value)
This PR proposes changing those cases to avoid the use of a dangerous default that could lead to issues.
This PR removes a possible cause of future bugs. Dictionary defaults are dangerous because the default values are initialized one time when the module is loaded, and then all successive function calls access the same dictionary.
```python
import uuid
def print_stuff(x = dict()):
x[str(uuid.uuid4())] = "hello"
return x
```
=> remove uses of dictionary as default

changes/pr3042.yaml, src/prefect/agent/local/agent.py, src/prefect/cli/agent.py, tests/agent/test_local_agent.py
This PR attempts to prevent the situation where an agent has duplicate labels.
While testing #3000 , I noticed something surprising...it's possible for duplicates to exist in an agent's set of labels:
For example:
```shell
prefect agent start \
-t ${PREFECT_RUNNER_TOKEN} \
--label 'i-am-duplicated' \
--label 'i-am-duplicated' \
--label 'i-am-duplicated'
```
I'm not sure if this would cause any problems today, but I could see it causing these types of problems:
* breaking code that allows wildcards for matching flows to agents, but throws an error if more than one label is matched
* breaking code that queries for agents by label and cannot handle duplicates
* slightly hurting the experience in the Prefect Cloud UI if duplicate labels are enough to push other labels into the collapsed `+n` …
=> prevent assignment of duplicate labels to agents

docs/core/development/documentation.md
We use `npm` everywhere else, and `yarn` doesn't give us anything extra. Simplifies the developer experience a bit.
Fixes #1422.
=> Switch to npm from yarn for developer docs

changes/pr3044.yaml, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
https://github.com/PrefectHQ/prefect/pull/2390 introduced a change so that on Windows, Dockerfile contained absolute paths which prevents docker build from working when using wsl backend or ssh (see https://github.com/PrefectHQ/prefect/issues/3023).
The fix here is to use relative paths in Dockerfile (i.e. revert to behavior before https://github.com/PrefectHQ/prefect/pull/2390) but pass absolute path of Dockerfile to `client.build`.
For previous attempt at addressing this problem, see the discussion here: https://github.com/PrefectHQ/prefect/pull/3035
=> Revert back to using relative paths in generated Dockerfile on Windows

.gitignore
This PR adds the following things to `.gitignore`:
* Jupyter notebooks (`.ipynb`)
* objects from compiling C/C++ code (`.a`, `.dll`,  `.dylib`, `.o`)
* Windows executables (`.exe`, `.msi`)
While working on #3000 , I was developing in a Jupyter notebook. I found that `.ipynb` notebooks are not currently ignored in this repo. I think that they should be, since this repo currently does not have any notebooks in it.
The C/C++ stuff and Windows executables are other things I noticed missing and that I expect should not be checked into this project.
=> ignore Jupyter notebooks in .gitignore

changes/pr3085.yaml, src/prefect/engine/task_runner.py, tests/engine/test_task_runner.py
Previously the global checkpointing config was determined by looking at
`prefect.config.flows.checkpointing`, which required configuring this
value on all dask workers for things to work properly.  We now use
`prefect.context.config.flows.checkpointing`, which will match the value
configured for the flow runner alone, better matching user expectations.
Fixes #3071.
=> Determine checkpointing from context.config

changes/issue3006.yaml, src/prefect/tasks/prefect/flow_run.py, tests/tasks/prefect/test_flow_run.py
Closes #3006 
Recent server changes allow for idempotency key now when running a flow and also now requires the specification of a project name
=> Allow idempotency key in FlowRunTask when using server backend

CHANGELOG.md, changes/issue3051.yml, update_changelog.py
This change update was left off of the `0.13.0` changelog due to it being a `.yml` instead of a `.yaml` so I updated the changelog script to accept both of these formats. I also manually updated the release notes and changelog to account for the missing entry.
=> Update changelog generation to handle .yml files

changes/issue3086.yml, docs/outline.toml, src/prefect/tasks/gcp/bigquery.py
Return `google.cloud.bigquery.job.LoadJob` object in `BigQueryLoadGoogleCloudStorage` and `BigQueryLoadFile` tasks.  It also adds BigQueryLoadFile to the API reference as it was missing.
This is actually what the docstring suggested, but it wasn't implemented.  The LoadJob object allows you to inspect important information pertaining to the load including output_rows (number of rows written to BigQuery table) and errors which are useful for debugging.
Closes #3086
=> Issue 3086 bq load file return load job

changes/pr3127.yaml, requirements.txt, src/prefect/engine/executors/dask.py, tests/engine/executors/test_executors.py
Previously we added a dask scheduler plugin to cache tasks submitted
multiple times through the `LocalDaskExecutor`. This fixed several
issues with the `LocalDaskExecutor` running tasks twice, but fails in
certain cases when running with `scheduler="processes"`. Dask's
multiprocessing scheduler runs a task-fusion optimization pass, which
doesn't play well with our scheduler plugin. Task fusion results in
tasks embedded inside other tasks, which prevents the plugin from
finding and removing tasks submitted twice.
Unfortunately the multiprocessing scheduler doesn't expose the option to
disable the call to `fuse` in a way that can be disabled locally, so for
now we disable task fusion globally when using the multiprocessing
scheduler. Since user code will run in external processes in this …
=> Run tasks at most once with Dask multiprocessing

changes/pr3113.yaml, src/prefect/agent/agent.py, src/prefect/agent/docker/agent.py, src/prefect/agent/fargate/agent.py, src/prefect/agent/kubernetes/agent.py, src/prefect/agent/kubernetes/job_spec.yaml, src/prefect/agent/local/agent.py, src/prefect/utilities/agent.py, tests/agent/test_docker_agent.py, tests/agent/test_fargate_agent.py, tests/agent/test_k8s_agent.py, tests/agent/test_local_agent.py, tests/utilities/test_agent.py
Adds an agent utility for determining the flow run execution command based on the version of the flow. For core_version < `0.13.0` it will use `execute cloud-flow` and for versions >= `0.13.0` it will use `execute flow-run`.
Maintain backwards compatibility while also respecting the deprecation of commands
=> Determine flow run command based on flow version

changes/pr3129.yaml, src/prefect/agent/kubernetes/job_spec.yaml
A while ago we switched to using `prefect.io/` labels for jobs created by the kubernetes agent and these UUID labels are no longer needed.
Remove some unnecessary labels from the flow run job manifest
=> Remove extra UUID labels from jobs created by the kubernetes agent

changes/pr3136.yml, src/prefect/utilities/notifications/notifications.py
backend_info toggle (default=true) enables or disables supplementing
the notification with urls from prefect server/cloud. Message formatter
queries the graphql for a flow/task url only if backend_info=True.
Fixes #2930 and #3133 
=> Added backend_info toggle for slack_notifier

changes/pr3146.yaml, src/prefect/environments/storage/_healthcheck.py, tests/environments/storage/test_docker_healthcheck.py
Updates the healthcheck script to raise a warning instead of an exception when upstream tasks do not have a result type set and things like retries/caching are used.
There is potential for things like retries to happen in the same process if their delay is short enough and in that case the result wouldn't be necessary.
=> Healthcheck raise Warning instead of Exception when result types are not present

changes/issue3151.yaml, src/prefect/client/client.py
This PR updates error handling in `Client._request` to handle situations in which the `requests` module defaults to using `simplejson` instead of json.
Without some dynamic error handling here, `Client._request` will raise `simplejson.errors.JSONDecoderError` instead of handling the exception and providing useful feedback to the user.
=> Make client robust to simple json

README.md
It appears as if the API which powered the badge prior is now down (https://github.com/crflynn/pypistats.org/issues/29). If we want we could switch to this badge for the meantime
=> Update pypi stats badge in README

changes/pr3168.yaml, src/prefect/client/client.py, src/prefect/environments/storage/webhook.py
This PR fixes a bug when querying for cached states that match a given task id and cache key. The old logic was this:
```python
"where": {
"state": {"_eq": "Cached"},	                
"_or": [	
{	
"_and": [	
{"cache_key": {"_eq": cache_key}},	### NOTE THIS LINE
{"cache_key": {"_is_null": False}},	
]	
},	
{"task_id": {"_eq": task_id}},	
],	
"state_timestamp": {"_gte": created_after.isoformat()},
```
When Hasura receives an equality of `null`, it [ignores it](https://hasura.io/docs/1.0/graphql/manual/queries/query-filters.html#evaluation-of-null-values-in-comparision-expressions). This means that if `cache_key=None`, the …
=> Fix bug with retrieving cached states when cache_key is None

src/prefect/core/flow.py
- [x ] adds new tests (if appropriate): 
no new tests were added however I tested locally like below in example.py: 
``` 
#--------------------------------------------------------------
#imports
#--------------------------------------------------------------
#global imports
import prefect
from prefect import Flow, Parameter, task
from prefect.tasks.shell import  ShellTask
from prefect.engine.executors import DaskExecutor
#--------------------------------------------------------------
#--------------------------------------------------------------
#Props: max_retries=3, retry_delay=datetime.timedelta(minutes=10)
@task(log_stdout=True)
def plus_one(x):
"""A task that adds 1 to a number"""
print("asdf")
return x + 1
@task(log_stdout=True)
def …
```
=> flow.py: add ability to modify flow_run_id in `flow.run()`

src/prefect/cli/describe.py, tests/cli/test_describe.py
Removes a query for run heartbeat to align with proposed changes in https://github.com/PrefectHQ/cloud/pull/2620 / https://github.com/PrefectHQ/cloud/pull/2621
=> Remove heartbeat from graphql

src/prefect/client/client.py
This PR makes the API error backoff a little more conservative.
Previously the retry happened so quickly it's not clear that it had any benefit.  This should extend the longest sleep to around 8 seconds which is a decent amount of time for things to change.
=> Update API error retry delay to be a little more conservative

changes/issue3142.yaml, src/prefect/agent/kubernetes/agent.py, tests/agent/test_k8s_agent.py
Closes #3142 
We can safely remove the `imagePullSecrets` field from the prefect job if not set. Previously it was set to `""` which could cause issues if container authentication is set at a higher level.
Ensure deployments operate properly on AKS
=> Remove imagePullSecrets from prefect k8s job if not set

changes/issue2988.yaml, src/prefect/environments/execution/dask/k8s.py, tests/environments/execution/test_dask_k8s_environment.py
Closes #2988 
Adds a new kwarg to the DaskKubernetesEnvironment `log_k8s_errors` which can be used to toggle the use of the `kubernetes` extra logger.
Could lead to logging unintended information so we should make this opt-in
=> Make kubernetes extra logger in DaskKubernetesEnvironment optional

src/prefect/agent/kubernetes/agent.py
Fixes a misspelled method name in the documentation for `KubernetesAgent`.
Fixes a misspelled method name in the documentation for `KubernetesAgent`
This PR eliminates a typo that would have led to a false negative grepping through the code or searching on the docs. Sorry, pretty sure this is a typo I introduced :grimacing: 
This PR:
=> [docs] fix misspelled method name in KubernetesAgent docs

CHANGELOG.md, changes/pr3173.yaml, src/prefect/tasks/docker/containers.py, src/prefect/tasks/docker/images.py, tests/tasks/docker/test_containers.py, tests/tasks/docker/test_images.py
A couple of small edits in the `prefect.tasks.docker` package. Basically, I just:
* Added the `extra_docker_kwargs` parameter to every Docker-related `Task` class in order to pass in arbitrary keyword arguments to Docker API calls (as in the current `prefect.tasks.docker.containers.CreateContainer` task). This allows for use of the newer possibilities of the [Docker API client](https://docker-py.readthedocs.io/en/stable/api.html#low-level-api) without having to adapt the corresponding `Task` class.
* Rewrote some of the log messages to make them more accurate and homogeneous towards the rest of the project.
* Fixed an issue in the way the current `extra_docker_kwargs` parameter is handled in `prefect.tasks.docker.containers.CreateContainer`. The current class uses the instance variable …
=> Add support for `host_config` and arbitrary keyword arguments in Docker tasks

changes/pr3177.yaml, src/prefect/utilities/agent.py, tests/utilities/test_agent.py
In #3113 , agents were changed to choose a different flow run command based on the current version of Prefect Core managing the flow. That PR added a default for `core_version` for the cases where `{"core_version": null}` exists on the response. However, if `core_version` is not present on the response at all, you get this hard-to-understand error:
```text
item = 'core_version'
def __getattr__(self, item):
try:
try:
value = self.__getitem__(item, _ignore_default=True)
except KeyError:
value = object.__getattribute__(self, item)
except AttributeError as err:
if item == '__getstate__':
raise BoxKeyError(item) from None
if item == '_box_config':
raise BoxError('_box_config key must exist') from None
if self._box_config['conversion_box']:
safe_key = self._safe_attr(item)
if safe_key in …
```
=> fix access to core_version in get_flow_run_command()

docs/orchestration/concepts/flow_runs.md
Gives an example GQL mutation for adding parameters to the create_flow_run mutation. (As requested in the community slack - https://prefect-community.slack.com/archives/CL09KU1K7/p1597772567101100)
Adds an example graphql create_flow_run mutation with parameters 
The JSON for parameters can be complicated so it's helpful to have a reference
This PR:
=> Show parameters example in create_flow_run gql

changes/pr3186.yaml, src/prefect/agent/agent.py
Fix the `--api` option for the agent CLI commands not being respected
Passes the set API endpoint to the agent's client
Fix broken CLI option
This PR:
=> Fix agent CLI api flag not being respected on start

changes/pr3166.yaml
@Ashton-Sidhu since the Databricks task spanned two PRs with multiple contributors weighing in I am appending @VincentTNR and @d80tb7 to the changelog update 🙂
=> Update PR #3166 entry

.circleci/config.yml, changes/pr3204.yaml, src/prefect/cli/server.py, tests/cli/test_server.py
This PR introduces our new versioning scheme for Core / Server and the UI.  In particular:
- both the [server repo](https://github.com/PrefectHQ/server) and the [ui repo](https://github.com/PrefectHQ/ui) cut releases based on calendar versioning; each time this occurs, a new `latest` tag is pushed to the respective docker hub repositories (along with the true image tag)
- whenever Core cuts a new version / release, it will pull whatever is the `latest` release of both Server and the UI and retag those images with `core-X.X.X` corresponding to the current Core version being released
This ensures compatibility with all images and prevents the use of `latest` which has some associated risks.
`prefect server start` will now use smart defaults for server image versions / tags based on the …
=> Server versions

changes/pr3150.yaml, src/prefect/cli/docker-compose.yml
This PR makes use of server's `post-start.sh` to have the apollo service properly wait for the graphql service to be running and healthy.
This PR depends on https://github.com/PrefectHQ/server/pull/41
In its current form we will commonly see an error when running `prefect server start` that looks like:
```
apollo_1    |
apollo_1    | > @ serve /apollo
apollo_1    | > node dist/index.js
apollo_1    |
apollo_1    | Building schema...
apollo_1    | { FetchError: request to http://graphql:4201/graphql/ failed, reason: connect ECONNREFUSED 172.31.0.4:4201
apollo_1    |     at ClientRequest.<anonymous> …
```
=> Update apollo service in docker compose to wait for graphql service

changes/pr3212.yaml, src/prefect/engine/state.py, tests/engine/test_state.py
This PR adds two new kwargs to `State.children` and `State.parents`:
- `include_self`: a boolean specifying whether to include the class on which the method is called
- `names_only`: a boolean specifying whether to return a list of string names instead of the classes themselves
Reduces duplication of this logic all over the place.
This PR:
=> Improved helper methods

pytest.ini
Color pytest ouptut logs to make it easier to identify test failures.
Add `pytest.ini` to configure pytest to enable the `--color` option by default.
Before:
After:
This PR:
=> Color pytest ouptut logs

changes/pr3216.yaml, src/prefect/engine/task_runner.py, tests/engine/test_task_runner.py
It appeared that when using task targets, in the event that a target was found we would log the templated target string instead of the resolved location.  This PR fixes that.
**NOTE:** It seems that our tests still somehow are not independent from user configuration.  Some of my tests were failing because of my user configuration file - not sure if it's my IDE setup or something else.
This PR:
=> Fix state message when using targets

changes/pr3210.yaml, src/prefect/agent/kubernetes/agent.py, src/prefect/agent/kubernetes/job_spec.yaml, tests/agent/test_k8s_agent.py
This PR adds the option to give let KubernetesAgent mount volumes in the k8 jobs.
Adds the two options `volume_mounts `and `volumes` to `KubernetesAgent  `
Allows for mount volume which has many use-cases. One is #3184 but this PR allows for much broader use.
This PR:
=> Added option to mount volumes with KubernetesAgent

pytest.ini
I'm not too familiar with `pytest.ini` but the presence of this file causes a lot of my tests to fail because they are no longer independent of my local environment cc @jcrist @cicdw
=> Revert "Color pytest ouptut logs"

changes/pr3046.yaml, src/prefect/agent/kubernetes/agent.py
Add an extra configurable `YAML_TEMPLATE` argument to the `KubernetesAgent` to allow overwriting of the template job spec.
Due to environmental setup of our k8s cluster I found myself needing to alter the podspec run in ways not exposed by current environment variables, and it didn't seem sensible to add new environment variables for every change I'd want to make to the template. This approach allows me to build a custom container with a specialized yaml spec.
=> allow customization of the yaml template

changes/pr3230.yaml, src/prefect/core/flow.py, tests/core/test_flow.py
Although an edge can be omitted from the graph if source task is a constant, the target task should still be included in the graph. As it is a single edge graph from constant to task will contain no tasks if "add_edge()" is used to build it, but it should contain at least the target task.
This PR:
=> Optimizing constants out of graph still add downstream

docs/core/faq.md
Fixes a broken link to create a flow run in the FAQ. It now matches the other links that refer to orchestration docs -- seems easiest to confirm that it is correct once netlify runs. Is there somewhere that local docs build instructions are given?
Tested working at https://deploy-preview-3236--prefect-docs.netlify.app/core/faq.html#how-does-the-prefect-scheduler-work
- Updates the link in `core/faq.md` to refer to `/orchestration/concepts`
None of these are applicable, seems unworthy of a changelog entry.
This PR:
=> Fix `create_flow_run` link in core faq

changes/issue3233.yaml, src/prefect/engine/state.py, src/prefect/engine/task_runner.py, tests/engine/test_state.py, tests/engine/test_task_runner.py, tests/serialization/test_states.py
This PR uses the already defined (but unused) `n_map_states` attribute on `Mapped` states to store the expected width of a mapped pipeline.  Will allow us to address point 1 in #3233 
This PR refactors the already implemented but unused `n_map_states` attribute in a way that is backwards compatible with our serializer logic so will work off-the-shelf with no changes to Server / Cloud.
For displaying more information about mapped pipelines in the UI.
This PR:
=> n_map_states

changes/pr3248.yaml, pr.py, src/prefect/tasks/core/function.py, tests/tasks/core/test_core.py
Expand `FunctionTask` AttributeError Message to prompt user to check if they have called a `FunctionTask` within a function that should have been decorated with `prefect.task`
- Expands `FunctionTask` AttributeError Message
- Adds a test for `FunctionTask` being called with an unknown attribute
Currently when a complete eejit such as myself forgets to decorate a function called in a `prefect.Flow` with `prefect.task` and passes another `prefect.task` to this function as an argument in this flow; the error message could nudge future me towards a quicker fix.  
In my case this forgetfulness resulted in a `pandas.DataFrame` function argument being interpreted as a `prefect.task` due to this missing decorator with the resulting error message:
Example:
```python
import pandas as pd
from …
```
=> Expand FunctionTask AttributeError Message

changes/pr3251.yaml, src/prefect/agent/kubernetes/agent.py, tests/agent/test_k8s_agent.py
See #3250 for a summary.
Makes `identifier` optional in `KuebrnetesAgent.replace_job_spec_yaml()` to avoid breaking older code that is using that method directly.
This PR fixes a small regression introduced in 0.13.5 which could break older code that directly calls `KubernetesAgent.replace_job_spec_yaml()`.
Instead of removing the `identifier` argument in this PR, I opted to give it a default value. If I just removed it, code written in v 0.13.5 which passes `identifier` would break in the next release.
This PR:
=> make identifier optional in KubernetesAgent.replace_job_spec_yaml() (fixes #3250)

changes/pr3247.yaml, docs/outline.toml, src/prefect/contrib/tasks/databricks/__init__.py, src/prefect/contrib/tasks/databricks/databricks_submitjob.py, tests/contrib/tasks/databricks/test_databricks.py
Porting over the DatabricksRunNow operator from Airflow as a Prefect Task giving 100% Databricks coverage from Airflow to Prefect.
This will add the DatabricksRunNow task to Prefect allowing user to trigger jobs on Databricks as a Prefect task.
Further enhances the 3rd party ETL suite and now has full coverage of Databricks tasks to Airflow
This PR:
=> Add DatabricksRunNow Task

src/prefect/contrib/tasks/databricks/databricks_hook.py, src/prefect/contrib/tasks/databricks/databricks_submitjob.py, src/prefect/engine/executors/dask.py, src/prefect/tasks/control_flow/case.py
I noticed some of our API docs looked off - turns out we had some RST-like backticks floating around.
Just updates a few doc strings to replace double backticks with single.
This PR:
=> Fix RST formatted strings in docstrings

changes/pr3271.yaml, src/prefect/cli/server.py
Change `https://localhost` to `http://localhost` in the welcome message because HTTPS doesn't work on port 8080, see #3270.
Change https://localhost to http://localhost in the local server welcome message
1. It could not connect to localhost by copy-paste the URL in the welcome message in the browser.
2. Prefect Docs says `http://localhost:8080` instead of `https`
I think none of the checklist items is necessary for this change. Let me know if I missed anything.
This PR:
=> Change https://localhost to http in welcome message

changes/pr3268.yaml, src/prefect/utilities/graphql.py, tests/utilities/test_graphql.py
Hi!
Was looking to make my first open source contribution and saw #1788 unpicked.
This PR implements the suggested aesthetic enhancement while writing GraqphQL in Python
Currently, if a dictionary key is True, it is ignored and the key alone is used as a field name.
Adding support for Ellipsis `...` to have the same behavior
```
python
{'query':{
'books': {
'id': True,
'name': True,
'author': {
'id',
'name',
}
}
}}
```
is equivalent to -
```
python
{'query':{
'books': [
'id',
'name',
{'author': {
'id',
'name',
}}
]
}}
```
This PR will enable the developer to write the following syntax in Python
```
python
{'query':{
'books': {
'id': True,
'name': ...,
'author': {
'id',
'name',
}
}
}}
```
and receive the same converted query as before -
```
python
{'query':{
'books': [
'id',
'name', …
```
=> Ellipsis Support for GraphQL DSL

changes/pr3282.yaml, docs/outline.toml, src/prefect/tasks/aws/__init__.py, src/prefect/tasks/aws/s3.py, tests/tasks/aws/test_s3.py
This PR adds a new task to the S3 task library, allowing for the listing of keys for a given prefix in some S3 bucket.
Adds an `S3List` class to the `prefect/tasks/aws/s3.py` file, along with a corresponding test.
This is a pretty simple addition, but I often find myself reaching for this functionality when using S3. It seemed relevant enough to add to the core task library.
This PR:
=> Add S3List task

changes/pr3275.yaml, src/prefect/tasks/aws/lambda_function.py, src/prefect/tasks/aws/s3.py, src/prefect/tasks/aws/secrets_manager.py, src/prefect/tasks/aws/step_function.py
kwargs are added to the run method of the secrets manager task to enable the user to specify e.g. `region_name` in the boto client.
It seems like there were previously no other functioning methods to specifying `AWS_DEFAULT_REGION`. This provides a general solution to such problems.
This PR:
I only added the kwargs as Args within the AWS secrets manager
=> add boto_kwargs to init method of aws_tasks

changes/pr3296.yaml, src/prefect/cli/docker-compose.yml
A user called out that the verbose logs are noisy - even in Cloud, we haven't found these logs to be particularly informative.
Sets Hasura log level to "warn"
This PR:
=> Quiet the hasura logs by setting log level to warn

changes/pr3293.yaml, src/prefect/core/flow.py, src/prefect/utilities/tasks.py, tests/tasks/test_control_flow.py, tests/utilities/test_tasks.py
A few assorted control-flow bug fixes:
- Support case blocks that create a new constant in them. These would
work before, but due to how the `FlowRunner` special-cases `Constant`
execution, they would never be skipped, leading to downstream tasks
not being skipped. A different fix would be to remove this special-
casing in the `FlowRunner`, as it can still lead to odd behavior in
certain edge cases. For example:
```python
from prefect import Flow, case, Parameter
from prefect.utilities.tasks import as_task
from prefect.tasks.control_flow import merge
with Flow("this still fails") as flow:
cond = Parameter("cond")
flow.add_task(cond)
with case(cond, True):
val1 = as_task("if true")
with case(cond, False):
val2 = as_task("if false")
branch = merge(val1, val2)
state = flow.run(cond=False) …
```
=> A few control-flow fixups

src/prefect/cli/docker-compose.yml, src/prefect/cli/server.py, src/prefect/config.toml
Updates the variable passed by `docker-compose.yml` to the UI container from `graphql_url` => `apollo_url`.  
Changes `docker-compose.yml`, the default `config.toml`, and `server.py` with the above.
This improves the clarity of which service the UI is connecting to; the UI does not connect to the GraphQL container but DOES connect to the Apollo container.
This PR:
This is a tandem PR with https://github.com/PrefectHQ/ui/pull/219, which will mean the UI will now respect the injected url.
=> UI runtime variable graphql_url => apollo_url

changes/issue3259.yaml, src/prefect/tasks/aws/s3.py, tests/tasks/aws/test_s3.py
Adds a `compression` argument to `S3Upload` and `S3Download`, initially referenced in [3259](https://github.com/PrefectHQ/prefect/issues/3259)
- Adds an optional `compression` argument to `S3Upload`, compressing data upon upload. Currently supports only gzip.
- Adds an optional `compression` argument to `S3Download`, decompressing data upon download. Currently supports only gzip.
Frequently, users will want to save on upload time / bucket space by compressing data, and this streamlines the process. Likewise, when downloading compressed data for immediate use, this allows the user to skip the intermediate step of decompression.
This PR:
=> Add compression argument to S3Upload and S3Download

src/prefect/contrib/tasks/mysql/mysql.py
This PR fixes logging in MySQL tasks, which could lead to misleading error logs that obscure the true cause of errors being logged.
I found these with `pylint`. You can find them by running the following:
```shell
pylint src/prefect/ | grep logging-too-many-args
```
This PR changes cases like this: `logging.debug("error: ", e)` to `logging.debug("error: %s", e)`.
The missing formatting strings in the logging statements changed by this PR will result in confusing logs when they're triggered. Consider the following
**without format string**
```python
import logging
try:
{}["a"]
except Exception as e:
logging.error("Fetch Error: ", e)
```
```text
--- Logging error ---
File "<stdin>", line 2, in <module>
KeyError: 'a'
During handling of the above exception, …
```
=> fix logging in MySQL tasks

docs/core/task_library/github.md
The current URLs for the GitHub tasks don't seem to work properly. This PR fixes them.
- Fix `prefect-tasks-github-prs-createbranch-` in the URL fragment.
This PR:
=> Fix GitHub task URL fragments

changes/issue3258.yaml, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/runner.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/test_task_runner.py
This PR fixes an issue where Prefect signals raised within Task state handlers were incorrectly interpreted as exceptions - note that this bug was only present when running against a backend.
This PR fixes that and will make it much easier to do, e.g., ad-hoc / custom retries from within state handler logic.
Closes #3258 
This PR:
=> Fix issue w/ state handler signals

changes/pr3317.yaml, src/prefect/engine/executors/dask.py
Currently `distributed` hardocodes a default value for connect timeouts to `get_client`. Until this is fixed upstream, we explicitly pull in the value from dask's config and pass it in programmatically. This config value (`distributed.comm.timeouts.connect`) can be increased if needed to allow for longer connect times.
See https://prefect-community.slack.com/archives/CL09KU1K7/p1600165695297200 for more info.
=> Pass `timeout` to `get_client` in `DaskExecutor`

changes/issue3306.yaml, src/prefect/client/client.py, src/prefect/client/secrets.py
Adds explicit exception chaining so that exception stack traces are a bit easier to comprehend. See #3306 for a lot more detail and background discussion on this.
Uses explicit exception chaining like `raise RuntimeError("whatever") from exc` in all the places in `src/prefect/client/*` that are missing it.
You can confirm that they were all caught by running the following from the root of the repo:
```shell
pylint src/prefect/client | grep raise-missing-from
```
This pull request will make some of `prefect`'s stack traces a bit easier to understand, to improve the user experience in debugging.
=> use explicit exception chaining in client

changes/issue3034.yaml, src/prefect/engine/result/base.py, src/prefect/engine/results/azure_result.py, src/prefect/engine/results/constant_result.py, src/prefect/engine/results/gcs_result.py, src/prefect/engine/results/local_result.py, src/prefect/engine/results/prefect_result.py, src/prefect/engine/results/result_handler_result.py, src/prefect/engine/results/s3_result.py, src/prefect/engine/results/secret_result.py, tests/engine/test_task_runner.py
Once we began templating using task keyword argument names as well, we introduced a minor bug where any task with an argument named "value" would fail at runtime; this was caused by our Result classes all using `value` as the kwarg name for `result.write`, and so the two kwargs were competing. 
This PR updates the internally used kwarg name to `value_` to prevent overshadowing user kwargs.
Closes #3034 
This PR:
=> Use value_

changes/issue3246.yaml, src/prefect/engine/task_runner.py, tests/engine/test_task_runner.py
This PR fixes a subtle issue with mapped pipelines: for a Flow that has a `Result` configured, restarting a mapped pipeline will do what you think.  In particular, it can pull the result it is supposed to map over and regenerate the correct width pipeline.  Each child task will learn its Task Run ID from Cloud along with its state, and everything will proceed.  
If you _don't_ have a `Result` configured (e.g., your pipeline doesn't exchange data and state dependencies are all you care about), restarting the mapped pipeline wouldn't quite work as you expect - specifically, because there was no data persisted, Core couldn't regenerate the correct number of child tasks that then ping the API, etc.  So, each mapped task would proceed as if it had 0 children to spawn and your Flow would …
=> Fix for restarting some mapped pipelines

tests/tasks/aws/test_s3.py
Fixes a broken test for the S3Upload class. See [3329](https://github.com/PrefectHQ/prefect/issues/3329).
I guess `gzip` uses the current timestamp when compressing data -- looks like `compress` offers an `mtime` argument to override this, but I think the better option would be to just decompress the result and compare it with the original bytes, rather than comparing compressed data.
Good to not have a test that sometimes breaks!
This PR:
=> Fix S3 gzip compression test

changes/pr3296.yaml, changes/pr3299.yaml, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
This will allow user to copy whole directories into the built docker image with only a single COPY command
Docker's COPY command can accept a directory path just as easily as it can accept a file path, but shutil.copy2 (the function Prefect currently used to prepare the file to be copied) fails if given a path to a directory. Therefore a check has been added which first checks if the user specified path is a file and, if it is, shutil.copy2 is still used. On the other hand, if a directory path is provided then shutil.copytree is used.
Aligns the capabilities of Docker's COPY command with Prefect's image build workflow
This PR:
- No suitable test to update
=> Allow copying of directories into Docker image

changes/pr3339.yaml, src/prefect/agent/docker/agent.py, tests/agent/test_docker_agent.py
When running on platforms using `spawn` as the default multiprocessing
context (windows, and osx for python >= 3.8), all arguments to
`multiprocessing.Process` need to be pickleable.
Fixes #3288.
=> Fix DockerAgent with show_flow_logs

docs/orchestration/tutorial/docker.md
The `Docker(registry_url=...)` example in the documentation "[Flow with Docker](https://docs.prefect.io/orchestration/tutorial/docker.html#pushing-to-a-registry)" does not work.
I needed to delete "docker.io/" to get it working.
Documentation changes only.
Without modification, I got the following error:
```
[2020-09-17 22:55:41] INFO - prefect.Docker | Building the flow's Docker storage...
Step 1/9 : FROM prefecthq/prefect:0.13.7-python3.8
...
Successfully built dbe32999e1ce
Successfully tagged k24d/myflow:2020-09-17t22-55-39-290448-00-00
...
ValueError: Your docker image failed to build!  Your flow might have failed one of its deployment health checks - please ensure that all necessary files and dependencies have been included.
```
This PR:
=> Update docker.md registry_url examples

changes/pr3338.yaml, src/prefect/core/flow.py, src/prefect/engine/flow_runner.py, tests/engine/test_flow_runner.py
(*Split off of #3333*)
This moves the `executor` configuration to the `Flow` itself, rather than on the "environment". This is nice, as it improves parity between `flow.register()` and `flow.run()`, where the same configured executor is used. Several users have been confused in the past about why `flow.run()` doesn't use the configuration in the `environment`.
Another benefit here is that Flows always have to be loaded (usually unpickled), but environments are sometimes unpickled and sometimes loaded from json from cloud (on the agent). This distinction between a fully loaded environment and a half-loaded environment (that might be missing some pickled components) is confusing, removing the need for a half-loaded environment is a goal of #3333. Moving one more piece of pickled state off …
=> Support configuring executor on the flow

changes/issue3319.yaml, src/prefect/core/flow.py, tests/core/test_flow.py
Fixes issue where we were not copying the `.constants` attribute (which is a dictionary referencing tasks).
Closes #3319
This PR:
=> Fix constant copies

docs/orchestration/concepts/services.md
Removed invalid references to cloud in services doc (fixes #3303)
This PR:
=> updated services doc to remove invalid references to cloud

changes/pr3346.yaml, src/prefect/core/task.py, src/prefect/tasks/core/resource_manager.py, src/prefect/utilities/tasks.py, tests/core/test_task.py
- Fix `__signature__` of `Task` types to work on both the class and on
instances.
- Fix `task` decorator to support type checking. mypy doesn't like
decorators that accept optional arguments, to handle this we have to
add additional annotations.
- *Almost* fix `resource_manager` decorator to support type checking.
This is annoying, mypy assumes (incorrectly) that the output of a
class decorator is always an instance of the class, even if the
decorator type signature says otherwise.
Fixes #3056.
Related to, but doesn't fix #3191.
=> A few mypy fixups

docs/core/concepts/results.md
`result` is an argument to `@task`, not the function.
=> Fix typo in docs/concepts/results.md [ci skip]

changes/pr3352.yaml, src/prefect/core/flow.py, tests/core/test_flow.py
Python assert statements may be dropped dropped by the compiler if running with `-O`/`PYTHONOTIMIZE=1`. As such, they shouldn't be used for control flow, as they might not be executed.
Fixes a bug in `flow.visualize()` where no output would be generated if asserts are optimized out.
Also fixes the `flow.visualize` tests to properly use `pytest.skipif`, rather than xfailing them unconditionally (which makes them useless as tests).
Fixes #2918.
=> Dont use asserts for control flow

changes/pr3354.yaml, docs/orchestration/execution/dask_cloud_provider_environment.md, src/prefect/environments/execution/dask/cloud_provider.py
While reading the docs at https://docs.prefect.io/orchestration/execution/dask_cloud_provider_environment.html tonight, I found what I believe is a typo in a log message from `DaskCloudProviderEnvironment`
Changes `sheduler` to `scheduler` in a log message in `DaskCloudProviderEnvironment`.
This is a minor PR fix that might improve the experience searching the docs.
=> fix typo in DaskCloudProviderEnvironment logs

src/prefect/environments/execution/dask/k8s.py
Following issue #3334, update the documentation of `DaskKubernetesEnvironment` for two arguments:
- image_pull_secret
- work_stealing
The documentation explains that those arguments are not applied to your custom `scheduler` and `worker` spec files, if provided.
Update the documentation
I add to read the source code to understand that those two arguments were not applied to my custom spec files.
This PR:
- ~~[x] adds new tests (if appropriate)~~
- ~~[x] adds a change file in the `changes/` directory (if appropriate)~~
=> Add documentation for DaskKubernetesEnvironment close #3334

changes/pr3344.yaml, src/prefect/agent/kubernetes/agent.py
For errors with the connection (connection dropped, timeouts, etc...) we
can retry submitting jobs a few times. If a previous submission
succeeded (the job was created) but then errored to the client
additional submission attempts will return a 409 error, which we now
interpret as a success. This should help when deployed in setups with
network issues.
For now we retry a max of 3 times, with a fixed 1 second delay between
each attempt.
Still needs tests.
Fixes #3278.
=> KubernetesAgent retries on connection errors

changes/pr3342.yaml, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
Allows advanced docker build users to inject custom build commands at the end of the generated DockerFile (but before health checks)
Adds the argument ```final_build_commands``` to the Docker storage class. This is either "None" or is a list of strings. In the case of the latter, these strings, which are assumed to be Docker build commands, are added to the end of the generated DockerFile
Permits more flexibility to Docker building, and allows for more advanced usages that are not currently possible. E.g. copying a local python module first via a COPY statement, and then installing that module within the image
=> Docker final build commands

changes/pr3364.yaml, src/prefect/core/flow.py, tests/core/test_flow.py
When running using Server, it is possible to  set `flow_run_name`, which is currently not
possible when doing local runs. This change allows the user to specify  `flow_run_name` when
calling run, in the same way as it is currently done for `flow_run_id`.
This change allows the user to specify  `flow_run_name` when doing local runs in the same way as it is currently done for `flow_run_id`.
This PR adds an option of specifying `flow_run_name` when running prefect locally in the same way that 
specifying flow_run_id  is possible. This allows the flow_run_name to be settable and not necessarily auto-generated.   
Allowing the user to set the flow_run_name for local runs is important because it brings closer prefect functionality when running locally and when using server. It also allows the …
=> Expose flow_run_name to .run() method for local runs

tests/core/test_flow.py
This test is failing regularly for some unknown reason (presumably related to Circle running slow?).  Hopefully extending this time will prevent it from failing as often.
=> Extend time on test to see if that robustifies it

changes/issue3306.yaml, src/prefect/core/flow.py, src/prefect/core/task.py, src/prefect/engine/cloud/flow_runner.py, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/runner.py, src/prefect/engine/serializers.py, src/prefect/engine/task_runner.py
Adds explicit exception chaining so that exception stack traces are a bit easier to comprehend. See #3306 for a lot more detail and background discussion on this.
*note*: Issue body is copied from #3320, created by @jameslamb.
Uses explicit exception chaining like `raise RuntimeError("whatever") from exc` in all the places in `src/prefect/core/*` and `src/prefect/engine/*` that are missing it.
You can confirm that they were all caught by running the following from the root of the repo:
```
python -m pylint src/prefect/core --disable=all --enable=W0707
python -m pylint src/prefect/engine --disable=all --enable=W0707
```
I have intentionally left out - `src/prefect/engine/serializers.py:84` since that usage seems valid as it is to me.
This pull …
=> use explicit exception chaining in core and engine

changes/issue2510.yaml, src/prefect/schedules/clocks.py, tests/schedules/test_clocks.py, tests/schedules/test_schedules.py
This PR extends the scheduling logic to account for clocks that emit the exact same time but different parameter sets.  In particular, because we do a sort / unique filter on clock events, this ended up being as simple as adjusting the `__eq__` logic for ClockEvents!
Closes #2510
**NOTE**: For anyone following this, this will not be compatible with Server or Cloud until this change makes it way into the Server / Cloud deployments.  If you are running Server, you'll need to upgrade the version of Prefect within your images or wait until the next release and swap out your images.  
For Cloud users, this change will be automatically available when the next release of Core goes live next week
This PR:
=> Parameter scheduling

src/prefect/cli/server.py
`prefect server start --help` shows the following help text:
```
--hasura-port       TEXT    Port used to serve Hasura, defaults to '3001'
--graphql-port      TEXT    Port used to serve the GraphQL API, defaults to '4001'
```
However, these default values are different from the actual default values defined in `prefect/config.toml`:
```
[server.graphql]
host = "0.0.0.0"
port = "4201"
host_port = "4201"
...
[server.hasura]
host = "localhost"
port = "3000"
host_port = "3000"
```
This PR fixes the help string.
The current help string is confusing.
This PR:
=> Update the default port numbers in the help string

changes/pr3393.yaml, src/prefect/tasks/prefect/flow_run.py, tests/tasks/prefect/test_flow_run.py
Add an option of specifying run_name when using FlowRunTask 
It changes FlowRunTask by adding an optional parameter that allows setting run_name
It is important, because having an option to set the name for your flow is beneficial for people that rely on flow names for tracking the flows. Having an option to set the flow name, allows more flexibility. 
This PR:
=> Add option to specify run_name for FlowRUnTask

docs/outline.toml, src/prefect/run_configs/__init__.py, src/prefect/run_configs/kubernetes.py, src/prefect/serialization/run_config.py, tests/agent/test_k8s_agent.py, tests/run_configs/test_kubernetes.py, tests/serialization/test_run_configs.py, tests/utilities/test_agent.py
Allows for more consistent naming across `RunConfig` objects. Future implementations will then be `DockerRun`/`LocalRun`/`FargateRun`.
=> Rename KubernetesJob to KubernetesRun

changes/pr1111.yaml, src/prefect/client/client.py, tests/client/test_client.py
Updates the error text to use the CLI function instead of the Client call when directing users to create the project.
This PR:
=> Update error message when registering to non-existant project

changes/issue2100.yaml, src/prefect/client/client.py, src/prefect/core/task.py, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/task_runner.py, tests/client/test_client.py, tests/core/test_task.py, tests/engine/cloud/test_cloud_task_runner.py
This PR supersedes #2974
Closes #2100 
With the recent introduction of the `set_task_run_name` mutation in the GraphQL API we can now use this to set the name of task runs dynamically at run time. This means that a code snippet like this:
```python
@task
def get_values():
return ['a', 's', 'd', 'f']
@task(log_stdout=True, task_run_name=lambda **kwargs: f"{kwargs['v']}")
def p(v):
print(v)
with Flow("task_run_names") as flow:
vals = get_values()
p.map(vals)
```
Will automatically name all of the mapped tasks based on their inputs `a`, `s`, `d`, `f` instead of the index!
Adds a new kwarg called `task_run_name` to the Task class that can now take in a string or callable to update the task run name at runtime.
Lots of users have requested this!
This PR:
=> Add option to template task run name at runtime when using backend API

changes/pr3423.yaml, src/prefect/agent/fargate/agent.py
Starting the fargate agent through the CLI could lead to issues in parsing of the cpu and memory values. This is due to the fact that boto3 required these values to be strings however natively they appear as integers. e.g.:
```
["prefect", "agent", "start", "fargate", "cpu=256", "memory=1024"]
```
Normally we exclude the literal parsing of these values because they are expected to be strings however we need to special case when they are actually provided as integers.
This fix will unblock some users attempting to do this however the new RunConfig pattern will completely resolve and simplify all of the Fargate agent parsing so much.
This PR:
=> Fix Fargate Agent not handling int provided cpu and memory

.circleci/config.yml
(email from CircleCI)
```
Hi there,
On November 1st, Docker Hub will begin limiting anonymous image pulls. We want to make sure you know how you might be impacted and what you can do to avoid interruptions to your workflow.
Adding Docker authentication to your pipeline config is the easiest way to avoid any service disruptions. If you use the Docker executor or pull Docker images when using the machine executor on CircleCI, we encourage you to authenticate. Because the anonymous API rate limits are based on IP addresses, they will impact CircleCI cloud customers. Authenticated users get higher per-user rate limits, regardless of IP.
We are currently working on a partnership with Docker to minimize the impact of this change for our users and will share more details as we get them.
For more …
```
=> Add docker auth to CI image pulls

changes/pr3431.yml, docs/outline.toml, src/prefect/client/client.py, src/prefect/tasks/prefect/__init__.py, src/prefect/tasks/prefect/flow_run_rename.py, tests/client/test_client.py, tests/tasks/prefect/test_flow_run_rename.py
Adds a `FlowRunRename` task for renaming running flows
Update the `prefect` task module to allow users to rename a currently running flow.
Expands the `prefect` task module in a useful way, as specified in #3285
This PR:
=> Add FlowRunRename task 

netlify.toml
A few users have called out that this link is now broken (and it's used on `prefect.io` and other various places).  This redirects to an existing page with similar content.
=> Add redirect for old task library landing page

changes/pr3426.yaml, examples/task_library/mysql/mysql_flow.py, src/prefect/tasks/mysql/mysql.py
Fixes #3318 MySQL tasks erroring on attempting to enter a context manager with a connection object. Also adds an example flow that was used to reproduce the issue and validate the fix.
- Updated code to open a context with a cursor and not a connection. PyMySQL's connection object isn't meant to be used as a context manager to fix #3318.
- A few other changes included in this as enhancements or additional bug fixes
- `port` was not used as part of creating a connection with PyMYSQL despite being part of the init kwargs
- made `query` a *required* argument instead of a keyword argument (I'm not sure but maybe this goes against prefect's design practices - feel free to correct me if so)
- updated default port to `3306`, which is the most common mysql port by being the default one out of the …
=> Fix MySQL Tasks and add mysql example

changes/pr3404.yaml, src/prefect/tasks/snowflake/snowflake.py
The snowflake connector will only accept user name and password as an authentication method.  We use key pair authentication for our snowflake connectors.
https://docs.snowflake.com/en/user-guide/python-connector-example.html#using-key-pair-authentication
The PR makes the password optional and adds an additional optional bytes object of the keypair. 
Many snowflakes users use keypair authentication.  Without that feature, I would have to maintain my own snowflake task going forward.  I would much rather use code maintained by the community.
This PR:
- [x ] adds a change file in the `changes/` directory (if appropriate)
=> allow for a keypair and not just user:password

CHANGELOG.md, changes/issue2100.yaml, changes/issue3306.yaml, changes/pr1111.yaml, changes/pr3333.yaml, changes/pr3351.yaml, changes/pr3385.yaml, changes/pr3404.yaml, changes/pr3423.yaml, changes/pr3426.yaml, changes/pr3429.yaml, changes/pr3431.yml, docs/.vuepress/config.js
Released on October 6, 2020.
- Add option to template task run name at runtime when using backend API - [#2100](https://github.com/PrefectHQ/prefect/issues/2100)
- Add `set_task_run_name` Client function - [#2100](https://github.com/PrefectHQ/prefect/issues/2100)
- Use 'from' to explicitly chain exceptions - [#3306](https://github.com/PrefectHQ/prefect/pull/3306)
- Update error message when registering flow to non-existant project - [#3418](https://github.com/PrefectHQ/prefect/pull/3418)
- Add `flow.run_config`, an *experimental* design for configuring deployed flows - [#3333](https://github.com/PrefectHQ/prefect/pull/3333)
- Allow python path in Local storage - [#3351](https://github.com/PrefectHQ/prefect/pull/3351)
- Enable agent registration for server users - …
=> Prep for release of 0.13.10

changes/pr3452.yaml, src/prefect/environments/execution/fargate/fargate_task.py
Fixed validation of containerDefinitions' environment
For containerDefinitions' `environment`, the validation now uses `sorted` since `environment` is a list of dict.
This PR fixes the validation phase for the task definition `environment`, which otherwise fails if the existing `environment` and the flow's `environments` have dicts in different order
This PR:
=> Fixed validation for containerDefinitions environment

src/prefect/agent/kubernetes/job_template.yaml
Previously the default job template when using `KubernetesRun` added a
cpu request and limit of `100m`. This is rather low for any cpu
intensive task, and would likely need to be adjusted by the end user.
Unfortunately, by setting both a limit and request, if the user
increases the request they also have to increase the limit (request
cannot exceed limit).
This PR drops the limit/request in favor of the k8s defaults.
- With no namespace configuration, a pod without resource
requests/limits will have no limit on cpu usage on a node, but will
also not reserve any cpu usage (the request is small, the limit is
infinite).
- An admin can configure default requests/limits for a namespace. If
configured, these defaults will be used.
For most jobs, a lack of a limit should be fine - without effort …
=> Remove default cpu requests/limits for flows using KubernetesRun

src/prefect/agent/kubernetes/agent.py, tests/agent/test_k8s_agent.py
When using the new `KubernetesRun` config, we don't set the logging
level by default in the k8s agent. This makes it easier for users to
configure the logging level, as the agent doesn't always override it.
We only apply this change to flows using the `KubernetesRun` run
conifiguration as it's new and experimental. Users using other config
mechansisms may be relying on the existing behavior.
=> Don't set log level in k8s agent w/ KubernetesRun

changes/pr3467.yaml, src/prefect/core/flow.py, tests/core/test_flow.py
Previously this would raise an error due to pickle failing. We could
have fixed it so pickle worked, but I'd argue that the flow context
should always exit before registering the flow (we do correctness checks
for the user on flow context exit). We now raise a nicer error message.
Reported via slack: https://prefect-community.slack.com/archives/C014Z8DPDSR/p1602257752136900
=> Better error for `flow.register` in flow context

src/prefect/core/task.py
Remove incorrect docstrings noting they were.
=> The `cache_*` args in `Task` aren't deprecated

src/prefect/triggers.py
Updates the docs because the args for `some_successful` and `some_failed` stated that percentages were triggerd by numbers <0 instead of <1
Minor change to docstrings
Reduce confusion!
This PR:
=> Docs bugfix

changes/pr3474.yaml, src/prefect/engine/cloud/flow_runner.py
This doesn't actually interrupt long running calls like `time.sleep`,
better to use `signal.pthread_kill` everywhere. Long running system
blocking calls like `time.sleep` are unlikely, but still possible,
especially for users trying things out.
Fixes #3424 (partially).
=> Don't use `signal.raise` when cancelling tasks

changes/issue3280.yaml, src/prefect/tasks/dbt/dbt.py
Documentation did not specify that an empty dictionary was required for DbtKwargs to function properly in the dbt task. This change creates an empty dict when none is given.
Default behavior in dbt task as requested in #3280 
Improves user experience with dbt task.
This PR:
=> fixing default DbtKwargs arg to default to empty dict

changes/issue3306.yaml, src/prefect/tasks/spacy/__init__.py, src/prefect/tasks/spacy/spacy_tasks.py
Adds explicit exception chaining so that exception stack traces are a bit easier to comprehend. See #3306 for a lot more detail and background discussion on this.
note: Issue body is copied from #3320, created by @jameslamb.
Uses explicit exception chaining like raise `RuntimeError("whatever") from exc` in all the places in src/prefect/tasks/spacy/* that are missing it.
You can confirm that they were all caught by running the following from the root of the repo:
```
python -m pylint src/prefect/tasks/spacy --disable=all --enable=W0707
```
This pull request will make some of `prefect`'s stack traces a bit easier to understand, to improve the user experience in debugging.
This PR:
=> explicit exception chaining for spacy tasks

changes/issue3231.yaml, src/prefect/environments/execution/dask/k8s.py, tests/environments/execution/test_dask_k8s_environment.py
The log attributes used to be hard enforced and I think this setting was a relic of that. When providing custom specs for the worker and scheduler in the `DaskKubernetesEnvironment` it should not be overwriting the user provided values for anything log related. These values were being set to whatever the default value was on the pod that was executing the environment. This led to undesirable behavior because it was unclear that needing to set things like `PREFECT__LOGGING__LEVEL` on the Agent was propagating the change down to the scheduler and workers.
Closes #3231 
Removes the hardcoded log settings on user provided scheduler and worker specs
Allows users to set log level, log to cloud, and extra loggers on their custom specs for the DaskKubernetesEnvironment
This PR:
=> Fix DaskKubernetesEnvironment overwriting log attributes for custom specs

changes/pr3483.yaml, src/prefect/client/client.py, src/prefect/schedules/clocks.py, src/prefect/serialization/schedule.py, tests/schedules/test_clocks.py, tests/serialization/test_schedules.py
This PR exposes the ability to emit per-clock flow run labels, in addition to exposing `labels` on `Client.create_flow_run`.  This will enable the ability for users to schedule Flows to run simultaneously in different places / through different agents, and moreover will allow users to create ad-hoc runs with unique label sets as needed.
This is a new feature that enables a pattern that wasn't possible before; *please note* this will not be available in Cloud / Server until the scheduler logic has been updated and released!  We will try to have this released prior to the next release of Core 👍 
This PR:
=> Clock labels

changes/pr3482.yaml, docs/core/idioms/file-based.md, src/prefect/cli/register.py, src/prefect/environments/storage/base.py, src/prefect/environments/storage/gcs.py, src/prefect/environments/storage/s3.py, tests/environments/storage/test_gcs_storage.py, tests/environments/storage/test_s3_storage.py
It is the expected behavior for some users that when they call
```bash
prefect register flow -f my_flow.py -p Project
```
That this will also upload their flow to their desired storage location in S3 and GCS. While this was previously true with pickle-based storage we did not perform the automatic upload for these cloud storage options and this PR adds that.
Adds a `script_path` kwarg to the S3 and GCS storage classes to be used in tandem with `store_as_script`. The value can either be set manually in a script:
```python
flow.storage = S3(
bucket="my-flow-bucket",
stored_as_script=True,
script_path="my_flow.py"  # Local file that you want uploaded to the bucket
)
```
or it will pull the value of the flow file when calling the `register flow` CLI command from context.
Enables some expected …
=> Enable upload for file based storage when using S3 and GCS

src/prefect/schedules/clocks.py, tests/schedules/test_clocks.py, tests/serialization/test_schedules.py
Minor adjustment from #3483 that allows for `None` to be set as the labels.  This allows us to distinguish between labels that were user-provided (e.g., `[]`) vs. no labels provided.
=> Allow for None as labels attribute of clocks

changes/pr3500.yaml, src/prefect/client/client.py, tests/client/test_client.py
When registering a flow it shows a URL linking to the flow in the UI:
```
Flow URL: https://cloud.prefect.io/my-tenant/flow/45fa712c-a5b1-4be7-82ec-55b01071d032
└── ID: 45fa712c-a5b1-4be7-82ec-55b01071d032
└── Project: Demo
└── Labels: ['Josh.local']
```
However navigating to the Flow ID redirects the user to the flow group page so by outputting the flow group ID instead we can avoid the redirect
```
Flow URL: https://cloud.prefect.io/my-tenant/flow/43be177a-c791-48f3-a156-f26dc0b7f62a
└── ID: 45fa712c-a5b1-4be7-82ec-55b01071d032
└── Project: Demo
└── Labels: ['Josh.local']
```
Updates the output of the flow registration to use the flow group ID in the URL
Avoids an unnecessary redirect to the flow group page
This PR:
=> Output Flow Group ID for registration URL instead of Flow ID

changes/issue3165.yaml, src/prefect/agent/agent.py, tests/agent/test_agent.py
`get_runs_in_queue` will return flow runs in order however when we do the additional query to get flow run information order is not guaranteed. This updates that function to sort the flow runs after returned from the query
Closes #3165 
Adds `sorted` call on flow run information query in the agent deployment process, ordered by `scheduled_start_time`
It is ideal to have work run in the order it is scheduled under circumstances (such as) where agents go down and come back online
This PR:
=> Submit flow runs based on order of scheduled start time

changes/pr3514.yaml, src/prefect/environments/execution/fargate/fargate_task.py, tests/environments/execution/test_fargate_task_environment.py
Expands and fixes upon #3451
Properly fixes previous FargateTaskEnvironment task definition validation around `Environment` by refactoring the comparisons.
Expands the validation to include ARNs as well (you can reference them by name when created  but the name gets converted to the ARN form in the taskDefinition in AWS and will clash in validation later). To play it safe, I also went through the AWS documentation and reformat the fields that could possibly be re-ordered by AWS incase users are using task definitions with more than one container.
Tests are included to verify the implementation.
Essentially, the data structure storing environment variables is a hashmap that isn't ordered, so each `describe_task_definition` call can potentially return the environment variables out of order, …
=> Fix Fargate task definition environment and role validation

changes/pr3511.yaml, src/prefect/utilities/executors.py, tests/conftest.py, tests/core/test_flow.py
The value retrieval in the `multiprocessing_timeout` was using a locally defined helper function
which could not be serialized by the native Python pickler resulting in an error running tasks with
a timeout while using a process based scheduler.
```python
from prefect.engine.executors import LocalDaskExecutor
from random import randint
@task
def foo(x):
return [randint(0, i) for i in range(x)]
@task(timeout=10)
def bar(y):
return y * 2
with Flow("foobar") as flow:
y = foo(10)
z = bar.map(y) 
state = flow.run(executor=LocalDaskExecutor())
```
Results in the error `AttributeError: Can't pickle local object 'multiprocessing_timeout.<locals>.retrieve_value'`
Also fixes a timeout issue with function pickling similar to …
=> Fix multiprocessing timeout

changes/pr3521.yaml, src/prefect/agent/agent.py, src/prefect/agent/kubernetes/agent.py, tests/agent/test_agent.py
Previously an error in the heartbeat thread would silently kill the
thread. We now catch and log them, and continue looping.
This fixes a bug where a non-api error (e.g. a socket error) in the k8s
agent resource manager would kill the resource manager.
This PR:
=> Catch & log errors in heartbeat thread

changes/pr3522.yaml, src/prefect/tasks/notifications/slack_task.py
Specify the `webhook_secret` of the `SlackTask` on runtime.
This PR changes the `SlackTask.run` method by adding the `webhook_secret` argument.
User will have the ability to provide the slack `webhook_secret` dynamically based previous tasks.
This PR:
=> specify slack webhook_secret on runtime

docs/core/advanced_tutorials/slack-notifications.md
Add information about storing SLACK_WEBHOOK_URL as a Prefect Secret for production usage. 
Documentation change
Currently the docs suggest that it's not possible to securely store the slack webhook url. However, I tested it and it seems that when you pass the SLACK_WEBHOOK_URL secret, the slack_notifier correctly picks this up.
=> Info about storing SLACK_WEBHOOK_URL as a secret

src/prefect/engine/task_runner.py, tests/engine/test_task_runner.py
The task runner logs were mixed lower/upper case. Log calls exceeded the `black` line limits
- All "Task {name}: ..." logs capitalize the first word
- Lines are below the 88 char black line limit
- Consistent and pretty UI
This PR:
- ~[ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate~)
=> Use consistent capitalization for task runner logs

src/prefect/tasks/gcp/storage.py
Fix for PR 3508 (https://github.com/PrefectHQ/prefect/pull/3508).  
Sorry, I realised I made a mistake there and should have wrapped data in BytesIO so it is delivered as a binary stream.
I have hopefully sorted my local testing setup so this won't happen for future PRs :)
* Imports io library to gcs tasks file
* Uses io.BytesIO to deliver the bytes data as a binary stream to the upload_from_file function.
* Make the GCSUpload with bytes more functional.
This PR:
=> Fix for bytes GCSUpload 

changes/pr3537.yaml, docs/outline.toml, src/prefect/agent/docker/agent.py, src/prefect/run_configs/__init__.py, src/prefect/run_configs/docker.py, src/prefect/serialization/run_config.py, tests/agent/test_docker_agent.py, tests/run_configs/test_docker.py, tests/serialization/test_run_configs.py
Adds a `DockerRun` run config type for use with the `DockerAgent`. Currently this exposes:
- `image`: the docker image to use
- `env`: environment variables to set in the container
I opted out of exposing other config options (`volumes`, `network` ...) for now, as I'm not certain these options would differ that much between flows. We can always add things later if needed.
Also cleans up the docker-agent tests a bit to make better use of fixtures (deleting a couple hundred lines of duplicated test code).
This PR:
=> Add `DockerRun` run-config

changes/pr3256.yaml, docs/outline.toml, src/prefect/engine/task_runner.py, src/prefect/utilities/compatability.py, src/prefect/utilities/compatibility.py, src/prefect/utilities/executors.py, tests/engine/test_task_runner.py, tests/utilities/test_executors.py
Resolves issues on Linux with the `multiprocessing_timeout_handler` which is used during `LocalDaskExecutor(scheduler="threads")` calls. Execution was hanging during execution of mapped tasks and appears to be an issue with the `fork` process implementation in Python and I'm not sure it's worth trying to hunt down.
Cleans up timeout handling in general.
Closes #3506 
- Refactors the timeout handlers in `prefect.utilities.executors`
- Uses `spawn` instead of `fork` to create a process based timeout handler
- Unifies timeout handler interfaces
- Adds logging to timeout handlers
- Adds `prefect.utilities.compatibility` with `nullcontext`
- Fixes a bug with multiprocess timeout handling and the threaded scheduler
- Improves readability and inspectability of timeout handling
This PR:
=> Fix multiprocess based timeout handler on linux

src/prefect/utilities/executors.py, tests/utilities/test_executors.py
A few quick fixups for #3526.
- Use the logger for the task in the subprocess-based timeout
- Quiet log level
- Fix one test where timeout was == to execution time.
=> A few fixups for timeout handling

changes/pr3540.yaml, src/prefect/utilities/serialization.py, tests/utilities/test_serialization.py
When using Prefect with Cloud/Server, custom functions aren't supported
for fields in schedules (e.g. filters), as these functions are run as
part of Cloud/Server's infrastructure. Previously if a user tried to use
a custom function here, registering the flow would raise an opaque
"invalid function" error message, we now provide a more helpful message.
Fixes #3495.
This PR:
=> Raise better error for invalid functions used with cloud

changes/pr3549.yaml, src/prefect/utilities/serialization.py, tests/utilities/test_serialization.py
When using Prefect Cloud/Server, `Parameter` defaults have to be JSON
serializable. Previously registering a flow with JSON incompatible
Parameter defaults would error with an opaque `"Value is not
JSON-compatible"` error. We now raise a better error message providing
some context. This has come up in the community slack a few times.
=> Better error for JSON incompatible parameter defaults

changes/pr3551.yaml, src/prefect/agent/local/agent.py, tests/agent/test_local_agent.py
Adds support for windows python path creation by using `os.pathsep`
Closes #3544 
- Uses `os.pathsep` instead of `:` to build the python path
Fixes a bug on Windows.
This PR:
=> Fix LocalAgent PYTHONPATH construction on Windows

tests/conftest.py, tests/utilities/test_executors.py
Hard to know if this is effective without a few tests runs
- Reduce resource usage for dask clusters, to hopefully fix issues on resource constrained CI systems
- Fixup some of the timeout tests to hopefully be less flaky on Circle CI. Note that the changes shouldn't make the tests take any longer (the longer timeouts are for tests that should never timeout).
=> Fix a few flaky tests

changes/issue3562.yaml, src/prefect/tasks/azure/blobstorage.py
azure-blob-storage library used to have a BlockBlobService class but it was changed to BlobServiceClient, so i changed the Task to create the blob_service using the new class
Instead of using `BlockBlobService` I used `BlobServiceClient.from_connection_string(conn_str=azure_credentials)`
Today when using the azure tasks the task fails because `BlockBlobService` does not exists
This PR:
=> fix(azure): need to use BlobServiceClient with the new version

changes/issue3378.yaml, src/prefect/engine/cloud/task_runner.py, tests/engine/cloud/test_cloud_task_runner.py
Currently, if the data that is referenced by a `Cached` state is deleted by an external process but that state is still considered valid, Prefect will throw an error and fail the task run that is checking against the cached state.  This is undesirable, as a failure to load cached data is equivalent to the cache being invalid and we should treat it as such.
This PR captures errors to load cached data and logs them, but allows the pipeline to continue on.
Much clearer UX and fixes the currently undesirable behavior.
Closes #3378 
This PR:
=> Cache load enhancement

src/prefect/engine/results/local_result.py
This PR comes out of a discussion in Prefect Community Slack today: https://prefect-community.slack.com/archives/CL09KU1K7/p1603751503170700.
Updates the documentation for `LocalResult` to describe what "local" means when you are using a remote executor.
This PR clarifies something in the `LocalResult` documentation that I think can be confusing in hybrid execution cases. 
@bhperry and I were trying to use `LocalResult`  to get the result of a flow run today and were surprised when it worked differently than we'd expected
This PR:
=> [docs] clarify how LocalResult works with a remote executor

changes/pr3573.yaml, src/prefect/tasks/prefect/flow_run.py, tests/tasks/prefect/test_flow_run.py
New `scheduled_start_time` parameter of FlowRunTask allows to schedule Flows at an arbitrary time.
This PR adds an extra argument to `FlowRunTask`.
Adds an option to schedule flow runs in the future, currently, they are always scheduled to run immediately.
This PR:
=> Add scheduled start time to FlowRunTask

changes/pr3589.yaml, src/prefect/cli/create.py
`prefect create project` would not display helpful information on failure to determine the cause.
- Adds a `click.echo` statement to display the stringified exception
Before
```
❯ prefect create project "idempotency"                              
Error creating project
```
After
```
❯ prefect create project "idempotency"
ClientError: Malformed response received from Cloud - please ensure that you have an API token properly configured.
Error creating project
```
```
❯ prefect create project "idempotency"
AuthorizationError: [{'path': ['create_project'], 'message': 'AuthenticationError: Forbidden', 'extensions': {'code': 'UNAUTHENTICATED'}}]
Error creating project
```
--> This last one could be displayed better but this is really a matter of improving our string representation of the …
=> Display error details when `create project` fails

changes/pr3574.yaml, src/prefect/tasks/mysql/mysql.py, tests/tasks/mysql/test_mysql.py
Add support for the Pymysql `DictCursor` class in `MySQLFetch`.
This PR adds an extra `cursor_type` argument to `MySQLFetch`, for which the user can define `"cursor"`, `"dict_cursor"`, or leave blank. A new conditional has also been added to the task's `run` method to choose the corresponding cursor class which is then set in `pymysql.connect`.
There are cases where it's useful to have column names as part of the mysql fetch response, especially in the context of task mapping where downstream tasks behave or build new queries according to the particular column / values inputted. In such a case, without the dict cursor, downstream tasks must be aware of the schema or simply have hardcoded the index value of the column being observed.
This PR:
=> add cursor_type param to task, unit test

tests/environments/execution/test_dask_k8s_environment.py, tests/schedules/test_schedules.py
While working on #3596 , I saw that a handful of tests on `DaskKubernetesEnvironment` looked like they were accidentally missing an `assert`.
This PR fixes those and other tests in `tests/`, so that they'll fail when they should.
Added `assert` to a few comparisons in `tests/` that looked like they were intended to be test cases that fail if `False`.
The changes in this PR ensure that tests that fail do so loudly, so that problematic changes to the code they cover don't accidentally get merged.
This PR:
After noticing this working on #3596 , I searched for other cases with `pylint`:
```shell
pylint tests/ | grep expression-not-assigned
```
<details><summary>pylint logs with duplicates removed (click me)</summary>
```text
I searched for these with the following comand:
```shell …
=> run accidentally-skipped tests

docs/core/concepts/secrets.md
Wasn't sure what scopes we needed for a github access token, so I checked in chat and am updating the doc
Adds more info on scoping GitHub access token
clarity!
This PR:
=> update secrets doc to state scopes needed for github access token

changes/pr3585.yaml, docs/generate_docs.py, docs/outline.toml, docs/test_generate_docs.py, src/prefect/agent/__init__.py, src/prefect/agent/agent.py, src/prefect/agent/ecs/__init__.py, src/prefect/agent/ecs/agent.py, src/prefect/agent/ecs/task_definition.yaml, src/prefect/cli/agent.py, src/prefect/run_configs/__init__.py, src/prefect/run_configs/ecs.py, src/prefect/serialization/run_config.py, tests/agent/test_ecs_agent.py, tests/cli/test_agent.py, tests/run_configs/test_ecs.py, tests/serialization/test_run_configs.py
This PR adds `RunConfig` support for flows running on ECS. It adds:
- A new `ECSRun` run config, for configuring flow runs on ECS
- A new `ECSAgent` for running `ECSRun` based flows
- A new CLI option `prefect agent ecs start` for starting the ECS agent
A new agent was used rather than modifying the existing fargate agent, as:
- The configuration options we wanted to expose at the agent level were completely different than those the fargate agent currently exposes. Maintaining backwards compatibility while transitioning to the new model would be difficult.
- Since the agent can deploy on either fargate or ec2, the "ECS" prefix makes more sense than the "fargate" prefix
Note that the ECS agent uses a `prefect agent <name> start` pattern instead of `prefect agent start <name>`. We plan to …
=> Add ECS run config and agent

changes/pr3607.yaml, src/prefect/config.toml, src/prefect/utilities/logging.py
This PR makes logging timestamp format and behavior easier to understand and better aligned with default Python behavior. This PR is an update to #3600, incorporating feedback received.
1. Adds UTC offset (%z) to the default logging.datefmt setting.
2. Removes override of `logging.Formatter.converter` so that `time.localtime` is used instead of `time.gmtime`.
The UTC offset adds useful, explicit information to log records. The logging.display_tz attribute may be appreciated by some users, particularly for local development and testing, since UTC is sometimes difficult for humans to think in.
Removing the `logging.Formatter.converter` override will lead to more expected behavior locally, and will not change cloud logging functionality.
This PR:
Closes #3556.
=> Log Record UTC Offset & Converter

changes/pr3590.yaml, docs/orchestration/tutorial/first.md, src/prefect/client/client.py, src/prefect/core/flow.py, tests/client/test_client.py, tests/core/test_flow.py
Adds idempotency keys to flow registration exposing the API in https://github.com/PrefectHQ/server/pull/116 to allow sequential registration calls for the same flow without actually re-registering.
- Adds `idempotency_key: str = None` to `flow.register` and `client.register` 
- Adds `flow.serialized_hash()` to return a stringified hash of the serialized flow
- Adds a brief description [to the docs here](https://deploy-preview-3590--prefect-docs.netlify.app/orchestration/tutorial/first.html#register-flow-with-the-prefect-api)
- Users register flows repeatedly with automation and do not want to needlessly bump versions
```python
> from prefect import Flow
> with Flow("empty") as flow:
>     pass
> flow.register(project_name="idempotency")
Result check: OK
Flow URL: …
```
=> Add idempotency key to flow registration

README.md, changes/pr3610.yaml, docs/core/getting_started/first-steps.md, docs/core/getting_started/installation.md, docs/generate_docs.py, docs/orchestration/agents/docker.md, docs/orchestration/agents/fargate.md, docs/orchestration/agents/kubernetes.md, docs/orchestration/agents/local.md, docs/orchestration/agents/overview.md, docs/orchestration/concepts/tokens.md, docs/orchestration/execution/storage_options.md, docs/orchestration/recipes/third_party_auth.md, docs/orchestration/tutorial/docker.md, docs/orchestration/tutorial/k8s.md, docs/orchestration/tutorial/multiple.md, docs/outline.toml, src/prefect/agent/docker/agent.py, src/prefect/agent/fargate/agent.py, src/prefect/agent/kubernetes/agent.py, src/prefect/agent/kubernetes/deployment.yaml, src/prefect/agent/local/agent.py, src/prefect/agent/local/supervisord.conf, src/prefect/cli/agent.py, tests/agent/test_local_agent.py, tests/cli/test_agent.py
- Deprecates `prefect agent start <kind>` in favor of `prefect agent <kind> start`
- Deprecates `prefect agent install <kind>` in favor of `prefect agent <kind> install`
- Updates the documentation to use the new commands only
- Adds the new agent commands to the api docs
- Updates the test suite to provide better coverage of the agent CLI
- Fix a few bugs in the agent CLI
---
=> Restructure prefect agent cli

src/prefect/engine/task_runner.py
Updated debug message to make the state of an already mapped task a little more clear. 
An example scenario where the original message was confusing is using pause resume functionality. After you resume a paused task, the task runner checks the state of the prior tasks. Log messages are then written for these already run tasks. These messages were a little confusing as to what was was actually happening, so this change is just to add a little more clarification to show that the tasks are not being run again. 
This PR:
=> Update to mapped task debug message

docs/orchestration/execution/dask_cloud_provider_environment.md
Updates the documentation on using `dask-cloudprovider` for a `DaskExecutor`. That project now supports Azure, and has an open PR for GCP.
Updates the documentation on using `dask-cloudprovider` for a `DaskExecutor`. That project now supports Azure (https://github.com/dask/dask-cloudprovider/pull/67), and has an open PR for GCP (https://github.com/dask/dask-cloudprovider/pull/131).
This PR updates a note in the document that is currently inaccurate (says that Azure support is "coming soon" in `dask-cloudprovider`). It also mentions that support for GCP is coming soon.
This update allows users to answer the question "how can I get started with Prefect + Dask on `<major cloud provider>`.
This PR comes from this Prefect community slack conversation: Coming from this thread in prefect slack: …
=> [docs] add Azure, GCP to dask-cloudprovider docs

docs/orchestration/recipes/k8s_dask.md
Signed-off-by: Henry Tseng <info@heycanvas.com>
A quick spelling fix for prefect executors package.  Import should be pluralized here.  
Updated documentation to reflect correct package name.  
Documentation is always important esp for cut-and-pasting hello world examples.  
This PR:
=> Fix spelling mistake in documentation for executors package import

docs/core/concepts/persistence.md
Task's kwarg name is `checkpoint`, not `checkpointing`.
Documentation only.
Documentation only.
This PR:
=> Fix kwarg `checkpoint` in the doc

changes/issue3515.yaml, src/prefect/agent/agent.py, src/prefect/cli/auth.py, src/prefect/client/client.py, tests/client/test_client_auth.py
close #3515
Developpers using prefect server needs sometimes to attach_headers to the
queries in order to communicate with the server (e.g Basic Auth).
However, the first call to the server happened inside the constructor with the
tenant_id initialization. Since the headers couldn't been attached it results to failures.
This commit fix this issue.
Server protected with BasicAuth
```python
client = Client()
headers = {'Authorization': "Basic {}".format(PREFECT__SERVER__BASIC_AUTH)}
client.attach_headers(headers)
```
After the commit will have this:
```python
client = Client() # No errors
headers = {'Authorization': "Basic {}".format(PREFECT__SERVER__BASIC_AUTH)}
client.attach_headers(headers)
client.graphql({"query": {"tenant": {"id"}}})
```
1. ~tenant initialization is performed during …
=> [client] close #3515 Introduce the property active_tenant_id which handles the tenant initialization

changes/issue3605.yaml, src/prefect/core/task.py, src/prefect/engine/cloud/task_runner.py, tests/engine/cloud/test_cloud_task_runner.py
Solve the issue [#3605](https://github.com/PrefectHQ/prefect/issues/3605) related to collision of names for task_run and name of variables in prefect.context.
Keep user defined arguments for task_run_name. Add the prefect context values only for the task arguments with different names. 
Avoids name collision between task_run_name and prefect.context variables.
This PR:
=> Fix set task run name

changes/pr3627.yaml, src/prefect/engine/task_runner.py, tests/engine/test_task_runner.py
Following the work in #3622 , this PR updates _all_ templating logic to follow the same precedence: parameters, then context, then inputs.
Updates the handling of conflicting keys when templating results.
Match user expectations better.
This PR:
=> Update ordering on all formatting kwargs for templated objects

changes/issue3638.yaml, src/prefect/environments/storage/github.py, src/prefect/serialization/storage.py, tests/environments/storage/test_github_storage.py
Closes #3638 
Adds a `ref` kwarg to github storage at initialization and when calling `get_flow`
This now matches the functionality currently present in GitLab storage and allows users to grab flows from other branches
This PR:
=> Add ref option to GitHub storage for specifying branches

changes/pr3641.yaml, src/prefect/tasks/secrets/base.py, src/prefect/tasks/secrets/env_var.py, tests/tasks/secrets/test_base.py, tests/tasks/secrets/test_env_var.py
Previously `PrefectSecret` and `EnvVarSecret` tasks required a default
name set, even if that name was always overridden at runtime. We now
relax that constraint so a user can init a secret task without a name
and only provide the name at runtime later.
=> Secret names not required to init tasks

changes/pr3624.yaml, src/prefect/client/client.py
Does not add idempotency_key to the create_flow mutation inputs unless it is set
- Updates the dict of inputs for the create_flow mutation call in Client.register conditionally
Fixes the breaking change introduced by adding idempotency keys
This PR:
=> Only send the idempotency_key during registration if set

changes/pr3637.yaml, src/prefect/tasks/kubernetes/deployment.py, src/prefect/utilities/kubernetes.py, tests/utilities/test_kubernetes.py
Fixes https://github.com/PrefectHQ/prefect/issues/3636
This PR updates the kubernetes tasks & utilities for deployments to AppsV1Api, which is required for newer cluster versions of kubernetes.  
Refer https://github.com/PrefectHQ/prefect/issues/3636
This PR:
=> Update deployments extension to AppsV1Api

changes/pr3630.yaml, src/prefect/cli/create.py, src/prefect/client/client.py, tests/cli/test_create.py, tests/client/test_client.py
Change `Client.create_project` and `prefect create project`to skip creating the project if it already exists, returning/printing as if the project had been created
- Change `Client.create_project` such that if the project to be created already exists, then it has no net effect and the id of the existing project is returned.
- Change `prefect create project` to regard an attempt to create a project that already exists as successful, skipping the creation of the project.
Enables users to easily automate project creation (e.g., at startup in an ECS task) while continuing to receive errors unrelated to the project having been previously created. This meshes nicely with the introduction of the idempotency key for `flow.register` and `flow.serialized_hash()` in 0.13.14.
This PR:
=> Skip project creation if the project already exists

tests/utilities/test_logging.py
This test was failing for me locally because of a discrepancy between the current day in PST vs UTC.  I believe this is related to https://github.com/PrefectHQ/prefect/pull/3607
=> Fix logging datetime test

changes/issue3603.yaml, src/prefect/configuration.py, tests/test_configuration.py
Removes the need to escape backslashes when parsing environment variables. See also #3603
Makes usage of JSON configs as environment variables easier by respecting the original backslashes. 
This PR:
=> Parse env vars with newlines, without requiring escaping \

CHANGELOG.md
=> Fix link to wrong PR in changelog

src/prefect/cli/docker-compose.yml, src/prefect/cli/server.py
Passes `PREFECT_CORE_VERSION` during `prefect server start` for https://github.com/PrefectHQ/server/pull/126
- Passes PREFECT_CORE_VERSION to docker-compose
- Adds PREFECT_CORE_VERSION to the server container env
Allow core version display in the UI
This PR:
Manually verified that this value populates when running `prefect server start`
I do not think a changes/ entry is meaningful here.
=> Pass PREFECT_CORE_VERSION to Server

changes/issue3655.yaml, src/prefect/core/flow.py, tests/core/test_flow.py
Changes `Flow.replace` so that it doesn't set reference tasks on a flow that didn't already have reference tasks set.
This PR modifies `Flow.replace` by adding an `if` statement to check whether `Flow._reference_tasks` is set before it updates reference tasks by replacing the old task with the new task.
This is discussed in https://github.com/PrefectHQ/prefect/issues/3655
Briefly, the current behavior of `Flow.replace` does not make intuitive sense since it freezes the reference tasks of a flow that didn't have frozen reference tasks.
This PR:
=> Stopped Flow.replace from setting unset reference tasks

changes/pr3654.yaml, src/prefect/core/flow.py, tests/core/test_flow.py
Fixes a bug where runs of `serialized_hash` could give different values in new Python processes due to dict key order.
Was missed in the initial testing because
- The flow used in manual new python process testing had no tasks and that's where the items are very likely to be in a different order
- New python process testing was deemed not worth automating / adding to the codebase
Thanks @jnoynaert for the report and example!
Closes #3653 
- Adds `sort_keys=True` to the json.dumps call
- Add test coverage for serializing in new processes
Serialized hash should not depend on order
This PR:
=> Sort json keys before hashing in `flow.serialized_hash`

src/prefect/cli/agent.py
Currently if you run `prefect agent install kubernetes ... | kubectl apply -f -` you get a fairly confusing error:
```
error: error parsing STDIN: error converting YAML to JSON: yaml: found character that cannot start any token
```
The reason is that `Warning: `prefect agent install kubernetes` is deprecated, use `prefect agent kubernetes install` instead`  shows up at the beginning of the stdout block and gets piped through to `kubectl apply`. Writing to stderr instead seems more appropriate here.
=> Write agent command line warnings to stderr

src/prefect/agent/agent.py, src/prefect/engine/flow_runner.py, src/prefect/utilities/notifications/jira_notification.py, src/prefect/utilities/notifications/notifications.py, tests/core/test_flow.py, tests/core/test_task_map.py, tests/core/test_task_operators.py, tests/engine/cloud/test_cloud_flows.py, tests/environments/storage/test_docker_storage.py, tests/schedules/test_clocks.py, tests/schedules/test_schedules.py, tests/serialization/test_schedules.py, tests/tasks/azureml/test_datastore.py, tests/tasks/docker/test_images.py
Changes unnecessary list comprehensions within `any`/`all` calls to generators which will exit early on failure.
I noticed this in #3121 
Speeds up failure and success cases, best practice, 20 second regex to do :)
This PR:
=> Use generators instead of list-comprehensions for any/all

changes/pr3681.yaml, src/prefect/agent/ecs/agent.py, src/prefect/run_configs/ecs.py, src/prefect/serialization/run_config.py, tests/agent/test_ecs_agent.py, tests/run_configs/test_ecs.py, tests/serialization/test_run_configs.py
Adds support for manually specifying a `task_definition_arn` to use in an `ECSRun` run config.
Fixes #3659.
This PR:
=> Add `task_definition_arn` to `ECSRun`

changes/pr3679.yml, src/prefect/environments/storage/local.py
Related to https://github.com/PrefectHQ/prefect/discussions/3678
There is a potential race condition between `os.path.exists` and `os.makedirs`.
`os.makedirs` provides the `exist_ok` flag and already handles race condition case when other thread may
have created the directory between the exists check and the makedirs
call. See
https://github.com/python/cpython/blob/48b069a003ba6c684a9ba78493fbbec5e89f10b8/Lib/os.py#L214-L218
Replaces `os.path.exists` by `exist_ok` flag.
I faced this issue when writing tests for a custom agent that used local storage. More details in https://github.com/PrefectHQ/prefect/discussions/3678
Workaround is to use `validate=False` and create the directory before instantiating the local storage class.
This PR:
=> Use exist_ok flag in os.makedirs to avoid race condition

changes/pr3672.yaml, setup.py, tests/environments/execution/test_dask_cloud_provider.py
The import path changed to local-only (instead of top-level) in the
latest release. Local imports are backwards compatible, so this should
work for all versions.
=> Fix dask-cloudprovider tests

changes/pr3689.yaml, src/prefect/engine/flow_runner.py, src/prefect/tasks/core/resource_manager.py, tests/tasks/core/test_resource_manager.py
Tasks created by a resourcemanager shouldn't be cached by default (since
they contain references to inherently transient resources). As such,
when restarting a flow from failed, we usually always want to rerun all
required resource tasks, even if they succeeded in a previous run. Users
can still opt-out of rerunning be enabling checkpointing for their
resource tasks, but by default checkpointing is off.
This provides a nicer behavior in the case of failures. For example, say
a flow creates a temporary Dask cluster using a resource manager, then
runs tasks `A`, `B` and `C` relying on that cluster. If task `B` fails,
the cluster will be nicely shutdown, with all resource-manager tasks
succeeding. If the user then restarts the flow from failed, we want to
recreate the dask cluster resource …
=> Always rerun resource-manager tasks on flow-run restart

changes/pr3649.yaml, src/prefect/tasks/shell.py, tests/tasks/test_shell.py
Adds some better handling of output to `ShellTask`
Closes #3614
Closes #3584 
- Adds the output result to the `FAIL` signal state for inspection on failure cases
- Adds notes about inconsistencies / handling that need to be fixed but are breaking changes
- Adds `stream_output` to log printed lines as they come independent of return settings
- The `ShellTask` is a bit neglected and was hard to inspect in failure cases.
- Setup for future `ShellCommand` but fixes pressing problems
This PR:
=> Add `stream_output` and a result on failure to `ShellTask`

changes/pr3692.yaml, src/prefect/client/client.py, src/prefect/tasks/prefect/flow_run.py, tests/client/test_client.py, tests/tasks/prefect/test_flow_run.py
Now that there is an artifact API for creating things like links we can take advantage of it in some places like the task library. This serves as an initial addition where we can create a link artifact for the `StartFlowRun` task that links to the created flow run in the UI.
Adds a new kwarg `create_link_artifact` to the `StartFlowRun` task. When set to `True` this will post a link artifact that looks something like `https://cloud.prefect.io/my-tenant-slug/flow-run/424242-ca-94611-111-55` (or localhost for server users).
This PR:
=> Add kwarg for creating link artifact in StartFlowRun task

changes/issue3695.yaml, src/prefect/core/task.py, tests/core/test_task.py
Returns `self` from imperative task dependency calls so they can be changed
Closes #3695 
- Changes return types of `set_upstream`, `set_downstream`, and `set_dependencies` from `None` to `Task`
- Returns `self` from all the above
This PR:
=> Allow chaining of imperative task dependency calls

changes/pr3693.yaml, src/prefect/environments/storage/docker.py
Fixes missing display of docker error messages during image build. On docker-py version 4.3.1 and Docker version 19.03.13, build 4484c46d9d the message for a syntax error in the dockerfile was in a format we did not check for. This gave me a `ValueError` suggesting a healthcheck had failed when really there was a dockerfile syntax error that was hidden.
- Adds a check for "message" in the docker build output parsing
Helps debug bad Docker storage setups
This PR:
=> Fix display of docker errors during storage build

changes/pr3691.yaml, docs/generate_docs.py, docs/test_generate_docs.py, src/prefect/core/task.py, tests/core/test_task.py
A common user mistake when usint class-based tasks is to pass dependent
tasks as arguments to the task constructor, rather than when calling the
task (or using methods like `.map`/`.bind`/`.set_dependencies`). We now
raise a nice warning in this case. We don't error outright in case the
user actually intended this (although my guess is this case is rare).
Also cleans up a few linting errors in the `test_task.py` file.
This PR:
=> Nice warning if passing task to Task constructor

changes/pr3697.yaml, docs/core/concepts/tasks.md, src/prefect/core/task.py, tests/core/test_task.py
Adds support for annotating tasks that return multiple results, allowing
for result-unpacking. This is a convenience to avoid explicitly
indexing out tasks.
If `nout` isn't provided, it's inferred from the task return type (if
possible), falling back to `None`.
Tasks that have a non-None `nout` are iterable, so they can be used in
result unpacking or iteration, since Prefect knows how long they are. By
default (`nout=None`) tasks are still non-iterable, keeping the expected
behavior.
This makes the following work:
```python
from prefect import Flow, task
@task(nout=2)
def inc_and_dec(x):
return x + 1, x - 1
@task
def double_and_triple(x : int) -> tuple[int, int]:
return x * 2, x * 3
with Flow("example"):
inc, dec = inc_and_dec(1)
double, triple = double_and_triple(inc)
```
This PR:
=> Nicer support for tasks return multiple results

changes/pr3702.yaml, tests/tasks/test_shell.py
Sometimes log output tests fail due to a mixture of irrelevant logs.
For example:
- [jobs/104977](https://app.circleci.com/pipelines/github/PrefectHQ/prefect/6862/workflows/962381e4-a5f0-4df0-95a8-16971e5d8ac0/jobs/104977)
- [jobs/104730](https://app.circleci.com/pipelines/github/PrefectHQ/prefect/6833/workflows/40f1c93a-aead-434c-9cef-8617ab8bda82/jobs/104730)
I'm not sure, but sometimes `caplog` captures errors from agent.
```Python
[2020-11-20 20:48:01,644] ERROR - agent | Error while managing existing k8s jobs
File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 170, in _new_conn
(self._dns_host, self.port), self.timeout, **extra_kw
File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 96, in …
```
=> Fix log filtering in tests

changes/pr3701.yaml, docs/core/getting_started/next-steps.md
The example code in [docs/core/getting_started/next-step.md](https://github.com/PrefectHQ/prefect/blob/master/docs/core/getting_started/next-steps.md) does not work.
```python
@task
def create_cluster():
cluster = create_spark_cluster()
return cluster
@task
def run_spark_job(cluster):
submit_job(cluster)
@task
def tear_down_cluster(cluster):
tear_down(cluster)
with Flow("Spark") as flow:
cluster = create_cluster()
submitted = run_spark_job(cluster)
tear_down_cluster(cluster)
tear_down_cluster.set_upstream(submitted)
```
Calling `set_upstream` method of a task itself, instead of a return value, makes an unintended copy of the task.
And this code raises TypeError: `TypeError: tear_down_cluster() missing 1 required positional argument: 'cluster'`
This is a DAG …
=> Fix docs core/getting_started/next-steps.md

changes/pr3682.yaml, src/prefect/core/flow.py, src/prefect/serialization/environment.py, src/prefect/serialization/flow.py, src/prefect/serialization/run_config.py, src/prefect/serialization/task.py, src/prefect/utilities/serialization.py, tests/core/test_flow.py, tests/serialization/test_environments.py, tests/serialization/test_flows.py, tests/serialization/test_run_configs.py, tests/serialization/test_tasks.py, tests/utilities/test_serialization.py
Much to my shame, `serialized_hash` was still not creating a consistent output. I've now expanded the test cases further and fixed the ordering issues that I thought would be fully resolved in #3654 
Alternate implemntation in #3683 abandoned because of typo anagrams.
- Adds helpers for `FlowSchema` that sorts tasks and parameters
- `FlowSchema` helpers for reference tasks and parameters return sorted lists instead of sets
- Adds note about serialized_hash not necessarily changing when the code does
- Adds `SortedList` derivative of `marshmallow.fields.List`
- Sorts lists for labels in `run_configs` and `environments`
Fixes additional bugs with `serialized_hash`
This PR:
=> Serialize task, edges, etc. in deterministic order

changes/pr3714.yaml, src/prefect/tasks/postgres/postgres.py
Refactor execute query code for `PostgresExecute`, `PostgresExecuteMany`, and `PostgresFetch` tasks.
- Instead of nesting `with` statements, use a single `with` statement with two items.
- Instead of nested repeating `conn.close()` in both try and except blocks and explicitly listing exception types, use the finally block.
- Avoid an unnecessary indentation level with no loss of readability.
- Avoid unnecessarily listing exception types only to re-raise the exception when the finally block is perfect for the aim of ensuring the connection is always closed.
This PR:
(Note that neither new tests nor docstring update is applicable.)
=> Refactor execute query code for postgres tasks
