README.md, docs/guide/getting_started/installation.md
If you weren't tired of these yet...
=> More documentation updates

docs/README.md, docs/generate_docs.py
- Closes #815 by replacing a markdown link with an `<a>` tag
- Fixes a broken link on the docs home page by replacing a router link with an `<a>` tag
👎 404s
=> Fix two link-related issues

CHANGELOG.md, docs/.vuepress/config.js, docs/guide/examples/daily_github_stats_to_airtable.md, docs/guide/task_library/github.md, docs/outline.toml, examples/daily_github_stats_to_airtable.py, src/prefect/tasks/github/__init__.py, src/prefect/tasks/github/repos.py
This PR introduces a new GitHub task for retrieving information about a repository; main use case is presumably for tracking repo engagement over time!
More tasks!  Also adds an example use case for #760
=> GitHub stats

docs/guide/tutorials/advanced-mapping.md, src/prefect/core/flow.py, tests/core/test_flow.py
- Flow.run() was incorrectly raising if non-required parameters were not provided; this PR addresses that issue.
- also updates the advanced mapping tutorial
=> Fix issue with flow.run raising for non-required params

CHANGELOG.md
=> Update changelog for 0.5.0

docs/.vuepress/config.js, docs/guide/README.md, docs/guide/welcome/design.md
=> Tweak titles in docs

docs/.vuepress/config.js, docs/guide/comparisons/airflow.md
This comparison is a little dated, but is a helpful guide.
=> Enable comparison

docs/generate_docs.py
The link was to `/prefect-coverage/index.html` and should have been just `/prefect-coverage/`
=> Fix link to test coverage

MANIFEST.in
=> Add requirements files to MANIFEST.in

README.md
This PR fixes a misspelling of "Prefect" in the readme.
=> Fix Prefect misspelling in readme

docs/guide/PINs/PIN-3-Agent-Environment.md, docs/guide/PINs/README.md
Primarily, adds PIN-5 to the table of contents, while touching up some typos and adding a "status" to the overview document.
=> PIN cleanup

docs/guide/getting_started/first-steps.md
Language tweaks in the tutorial, for clarity
=> Clarify description of task inputs

CHANGELOG.md, src/prefect/tasks/core/collections.py, tests/core/test_flow_local_ids.py, tests/engine/cloud/test_cloud_flows.py, tests/engine/test_task_runner.py, tests/serialization/test_edges.py, tests/serialization/test_states.py, tests/test_configuration.py
Closes #848 
Mostly touches int/string comparisons in `tests/` and adds a single `import prefect` to the collections tasks
As raised by @cclauss in #848 these flake8 issues should be resolved. (even if they are mostly tests)
=> Adjust Small flake8 Issues Raised

docs/guide/getting_started/first-steps.md
This pull request changes the typo in the documentation pages
To be more understandable to readers
=> typo in docs

CHANGELOG.md, requirements.txt, src/prefect/environments/docker.py, src/prefect/environments/kubernetes/dask/job.yaml, src/prefect/environments/kubernetes/dask/worker_pod.yaml
This PR:
- removes an unnecessary docker line that could cause certain base images to fail
- updates our requirement of `dask.distributed` to 1.26.1 so we can take advantage of some enhanced security features in deployment
Small, but important changes!
=> Bump distributed version up

CHANGELOG.md, docs/outline.toml, src/prefect/engine/result_handlers/__init__.py, src/prefect/engine/result_handlers/gcs_result_handler.py, src/prefect/engine/result_handlers/s3_result_handler.py, src/prefect/serialization/result_handlers.py, tests/engine/result_handlers/test_result_handlers.py, tests/serialization/test_result_handlers.py
This PR:
- adds a new `S3ResultHandler` for landing files in S3
- fixes the `GCSResultHandler` so that it is pickleable (this is important because it's a Task attribute and Tasks are pickled when shipped to a dask worker in deployment)
Result Handlers are a crucial ingredient to Cloud deployments
=> Result handler upgrades

docs/guide/development/documentation.md
adds clarification for pip install for nonessential tasks
closes #880
=> clarifying pip dependencies for doc gen/ preview

docs/.vuepress/config.js, docs/guide/development/documentation.md, docs/guide/development/release-checklist.md
Adds:
- a blurb on how to API version the docs
- a release checklist document (more for reference than anything else, as most people won't have the necessary permissions to execute these steps)
Document _all the things!_ Closes #890
=> Release notes

CHANGELOG.md, docs/guide/task_library/google.md, docs/outline.toml, src/prefect/tasks/google/__init__.py, src/prefect/tasks/google/bigquery.py, tests/tasks/google/test_bigquery.py
This PR adds a new task to the task library for creating a BigQuery table, which skips if the table already exists.
Useful for creating fully reproducible workflows!
=> BigQuery Create Table Task

CHANGELOG.md, examples/feature_engineering.py
Adds an example Flow that tackles reasonably intricate feature engineering, and passes those features into an unsupervised learning model. Starts from scratch with a URL string indicating the location of a raw (zipped) dataset, and finishes with 2 principle components in a Numpy array.
Currently Prefect's examples/ directory doesn't contain any applications in machine learning; I believe this is a great use-case for the platform to be explored. I believe this example also identifies a few pain points from the perspective of a machine learning engineer, as may be noted by the utilities and workarounds I had to employ in the process. Hopefully this sparks some discussion on ways Prefect can be geared …
=> Add example of feature engineering and machine learning

.github/PULL_REQUEST_TEMPLATE.md, docs/guide/examples/state_handler_logging.md, examples/state_handler_logging.py
- Adds an example using a state handler (#760 ) which also demo's logging run duration
- Updates PR template (**cc:** @jlowin )
=> Add example which uses state handlers to log durations

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, docs/.vuepress/config.js, docs/guide/welcome/code_of_conduct.md, docs/guide/welcome/community.md
- Adds a code of conduct to the repo top-level and also the docs, complying with open-source best practice and also promoting visibility within our own "Welcome" section
- Adds CONTRIBUTING.md, following open-source best practice, which links to our complete contributing documentation
- Fostering a positive development environment
=> Add Prefect's Code of Conduct

docs/guide/PINs/PIN-6-Remove-Constant-Tasks.md
Declines PIN 6 following points raised in #915
=> Decline PIN 6

docs/guide/tutorials/README.md, docs/guide/tutorials/dask-cluster.md
Adds a tutorial on deploying a Prefect Flow to a Dask cluster.
Addresses one of the more common questions we've received.
=> Add tutorial on deploying a Flow to a Dask cluster

setup.cfg, src/prefect/core/flow.py, src/prefect/core/task.py, tests/core/test_edge.py, tests/core/test_flow.py, tests/core/test_task_operators.py, tests/engine/test_flow_runner.py, tests/engine/test_task_runner.py, tests/tasks/test_core.py, tests/utilities/test_collections.py
- Adds unit tests for various branches revealed to be uncovered (via new coverage reports)
=> Add minor unit tests for areas revealed to be uncovered

docs/guide/welcome/community.md, netlify.toml
Tentatively addresses #930 (I won't close until I've verified post-deploy)
=> Update netlify redirect settings and fix contributing issue link

CHANGELOG.md, codecov.yml, src/prefect/client/client.py, src/prefect/core/flow.py, tests/client/test_client.py
Simplification in light of recent Cloud change.
=> Convert set_schedule_active to set_schedule_inactive

CHANGELOG.md, docs/outline.toml, src/prefect/tasks/notifications/__init__.py, src/prefect/tasks/notifications/slack_task.py, tests/tasks/notifications/test_slack_task.py
Adds a Slack notification task for sending slack message via the official Prefect Slack App.
User request.  Closes #932
=> Slack Task

CHANGELOG.md
=> Update changelog for a release

tests/environments/storage/test_docker_storage.py, tests/tasks/github/test_issues.py, tests/tasks/github/test_repos.py
Adds some low-hanging tests. A couple for Docker storage and tests for tasks `OpenGitHubIssue` and `GetRepoInfo`
Properly tested code is good
=> Add Missing Tests

.circleci/config.yml, Dockerfile
Auto-builds Docker image prefecthq/prefect:latest and pushes to Docker on every merge to master (minimal implementation of #700)
Added graphviz (won't work atm) and kubernetes deps to the Dockerfile and created build-args for python version and prefect git ref
Gives us a starting place for CI on the Prefect Core docker image
=> CI building docker image

src/prefect/cli/__init__.py
Quick addition to pump the flow location through the execution process @cicdw
=> Add flow_location to `execute_environment` CLI function

CHANGELOG.md, src/prefect/config.toml, src/prefect/core/flow.py, src/prefect/environments/execution/base.py, src/prefect/environments/execution/cloud/environment.py, src/prefect/environments/execution/cloud/job.yaml, src/prefect/environments/execution/local.py, src/prefect/environments/storage/__init__.py, src/prefect/environments/storage/base.py, src/prefect/environments/storage/bytes.py, src/prefect/environments/storage/memory.py, tests/core/test_flow.py, tests/environments/execution/test_local_environment.py, tests/environments/storage/test_bytes_storage.py, tests/environments/storage/test_docker_storage.py, tests/environments/storage/test_memory_storage.py, tests/serialization/test_storage.py
As discussed offline with @joshmeek and @jlowin this PR further polishes the interface between storage and environments.  Additionally, it introduces a config setting for affecting whether `flow.run` runs on schedule or not.
=> Env polish

.circleci/config.yml
Another attempt to fix #964 
Idea comes from this issue: https://github.com/pytest-dev/pytest-cov/issues/261
=> Install bleeding edge pytest-cov to fix hang issues

CHANGELOG.md, src/prefect/engine/task_runner.py, src/prefect/triggers.py, tests/engine/test_task_runner.py, tests/test_triggers.py
This PR removes the optimization which bypassed trigger functions within the Task Runner, allowing them each individually to determine their behavior when passed an empty set.
Closes #667 and allows for `manual_only` tasks to be root tasks of a Flow!
=> Trigger fix

src/prefect/tasks/airflow/airflow.py, src/prefect/tasks/google/bigquery.py, src/prefect/tasks/google/storage.py
Just adds a few helpful debug logs to some tasks in our task library.
Began as an attempt to look into #920 but realized I didn't know what to add, so I'm just PR'ing the few updates I did make.
=> Add a few debug logs to some tasks in the task library

CHANGELOG.md, src/prefect/client/client.py, src/prefect/core/flow.py
=> Deploy fix

src/prefect/client/client.py, src/prefect/utilities/graphql.py, tests/client/test_client.py, tests/utilities/test_graphql.py
This PR switches LZMA encryption to gzip encryption.
CircleCI and LZMA don't play well together. Gzip appears to work well with CircleCI, and it's arguably more universal.
=> Switch from LZMA to gzip

.circleci/config.yml, CHANGELOG.md, docs/guide/examples/flow_state_handler_viz.md, docs/guide/welcome/why_not_airflow.md, examples/flow_state_handler_viz.py, src/prefect/core/flow.py, tests/core/test_flow.py, tests/utilities/test_serialization.py
This PR introduces a new `filename` keyword for saving the output of `flow.visualize` to a known file location.  Also adds an example (#760 ) of how to use the keyword for storing the visualization with each new state change.
Closes #1001 
**cc:** @gane5h for the example of how to use a flow state handler for storing the visualization automatically.
=> Flow.vizualiation() save

CHANGELOG.md, docs/outline.toml, src/prefect/environments/storage/__init__.py, src/prefect/environments/storage/bytes.py, src/prefect/environments/storage/local.py, src/prefect/serialization/storage.py, tests/environments/storage/test_local_storage.py, tests/serialization/test_storage.py
Adds a new `Storage` class for storing flows in your local filesystem.  Finishes out most of the "natural" storage options for now.
Adds a useful permanent storage option for open source users.
=> Local storage

CHANGELOG.md, docs/guide/task_library/github.md, docs/outline.toml, src/prefect/tasks/github/__init__.py, src/prefect/tasks/github/repos.py, tests/tasks/github/test_repos.py
This PR adds a new task to the task library for creating new github branches.
I need this task for a release cycle that I am automating 😝
=> Github CreateBranch Task

CHANGELOG.md, src/prefect/environments/execution/cloud/environment.py, tests/environments/execution/test_cloud_environment.py
This PR adds a `flowrunid` label to our Cloud environment jobs / pods whose value is the `flow_run_id` found in context.
This PR will allow us to more quickly identify k8s jobs / pods with their associated flow runs in deployment, for a faster debugging experience.
=> Add more labels

docs/guide/examples/flow_state_handler_viz.md
=> Add title to the flow visualization state handler example

CHANGELOG.md, docs/outline.toml, src/prefect/tasks/aws/__init__.py, src/prefect/tasks/aws/lambda_function.py, tests/tasks/aws/test_lambda.py
This PR adds four new tasks to the task library for interaction with AWS Lambda. Operations include create, delete, invoke, and list.
Basic tests have been created for all operations, and all operations have been tested locally with live credentials.
Closes [#1009](https://github.com/PrefectHQ/prefect/issues/1009)
=> Add AWS Lambda Tasks

docs/guide/development/overview.md, docs/guide/task_library/aws.md
- Adds a short blurb on our dev workflow (fork + branch) 
- Exposes the new Lambda tasks in our manually curated [Task Library docs](https://docs.prefect.io/guide/task_library/aws.html)
Better docs = better YOU
=> Random adjustments to docs

CHANGELOG.md, src/prefect/core/task.py, src/prefect/tasks/core/constants.py, src/prefect/tasks/core/function.py, tests/core/test_task.py
Reverts PrefectHQ/prefect#1024
Decided offline that this was overly eager and prevents certain patterns that users might need.
=> Revert "Init validator"

CHANGELOG.md, src/prefect/environments/execution/cloud/environment.py, src/prefect/serialization/environment.py, tests/serialization/test_environments.py
This PR tentatively adds the ability for Cloud users to pull Flow images from private docker registries.
Security!
=> Private docker registries

src/prefect/environments/execution/cloud/environment.py
Makes value list instead of dict
So it works
=> Update CloudEnvironment job yaml imagePullSecrets to list

src/prefect/environments/execution/cloud/environment.py
Correctly creates the k8s secret for private docker registries
@joshmeek you can edit this PR body to include this section ;)
=> Correctly create the k8s docker secret

CHANGELOG.md, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
This PR checks docker output for errors and raises them as `InterruptedError`s accordingly.
Improves user experience by making it clear when things go wrong.  Raising errors early and often!
=> Improve docker UX via error-raising

docs/guide/PINs/PIN-8-Listener-Flows.md, docs/guide/PINs/README.md
=> PIN-8: Event-Driven / Listener flows

.circleci/config.yml
=> Update test reporting for GitHub checks API

CHANGELOG.md, docs/guide/task_library/postgres.md, docs/outline.toml, setup.py, src/prefect/tasks/postgres/__init__.py, src/prefect/tasks/postgres/postgres.py, tests/tasks/postgres/__init__.py, tests/tasks/postgres/test_postgres.py
This PR adds two new tasks for interacting with Postgres databases, `PostgresExecute` and `PostgresFetch`, which execute and fetch results of a SQL query.
Basic tests have been added for both tasks. Functionality has been tested locally with a live Postgres instance.
Closes [#1022](https://github.com/PrefectHQ/prefect/issues/1022).
=> Add Postgres tasks

CHANGELOG.md, docs/guide/task_library/redis.md, docs/outline.toml, setup.py, src/prefect/tasks/redis/__init__.py, src/prefect/tasks/redis/redis_tasks.py, tests/tasks/redis/__init__.py, tests/tasks/redis/test_redis_tasks.py
This PR adds three new tasks for communicating with Redis - `RedisSet`, `RedisGet`, and `RedisExecute`. 
Basic tests have been added for both tasks. Functionality has been tested locally with a live Redis instance.
Closes [#1021](https://github.com/PrefectHQ/prefect/issues/1021)
=> Add Redis tasks

CHANGELOG.md, src/prefect/core/flow.py
- Removes duplicated computation in dict comprehension
- Enables `any` short-circuiting
- Eliminates nested for loop
- Small tweaks to the codebase
- First contribution experience for a new contributor ;)
=> Refactor Map Caching Changes

CHANGELOG.md, requirements.txt
This PR relaxes some if the max pins on the dependencies
Currently installing `prefect` into an existing environment requires downgrading a number of dependencies.
=> Relax dependency pinning

src/prefect/utilities/logging.py
=> Add a log when the system exits, for more DEBUGGING POWER

src/prefect/environments/execution/cloud/environment.py
This PR adds some logging to the Cloud Environment for easier debugging in production.  Additionally, exposes a new keyword argument for specifying a custom name for your Prefect Secret containing your docker registry credentials.
=> Cloud Environment logs

CHANGELOG.md, docs/guide/task_library/aws.md, docs/outline.toml, src/prefect/tasks/aws/__init__.py, src/prefect/tasks/aws/step_function.py, tests/tasks/aws/test_step_function.py
This PR adds one new task for triggering an AWS Step Function workflow, `StepActivate`.
Closes [#1012](https://github.com/PrefectHQ/prefect/issues/1012)
=> Add AWS Step Function Activation Task

src/prefect/environments/execution/cloud/environment.py
Adds more logs to the cloud environment.
Logs are extra important
=> Add more debugging logs to cloud environment

src/prefect/cli/execute.py
=> Grab first element in flow run list on execute cli command

dev-requirements.txt, requirements.txt
Closes #1065 
The leaner the required base environment, the better.
=> Move mypy to a dev requirement where it belongs

src/prefect/environments/execution/cloud/job.yaml, src/prefect/environments/execution/cloud/worker_pod.yaml
Adds CPU requests and limits to the cloud environment job and workers.
Resource contention
=> Add CPU requests and limits to cloud environment

requirements.txt, tests/conftest.py
Removes the `cryptography` dependency since it isn't being used.
Thinner installs, the cryptography library also doesn't work on alpine images due to gcc requirement.
=> Remove cryptography dependency

README.md
Adds a badge for monthly PyPi downloads and total docker hub pulls.
=> Add two download badges to README

src/prefect/cli/execute.py, tests/cli/test_execute.py
There's definitely more work to be done, but this PR simply adds a few CLI tests for `prefect execute cloud-flow`.
Closes #1124
=> Better cli tests

docs/generate_docs.py, docs/guide/getting_started/installation.md, src/prefect/tasks/postgres/postgres.py
- fixes an issue wherein locally hosting docs had some errors
- adds extras packages
- removes the prefect version from the auto-generated footer, because Netlify was somehow not registering new git tags so the version looked wonky
=> Very minor doc tweaks

docs/guide/task_library/README.md
=> Fix broken link to api docs

docs/guide/getting_started/first-steps.md
=> Fix wrong kwarg in docs example for imperative API

.circleci/config.yml
Poking around trying to understand why codecov stopped working...
=> Bump pytest version

src/prefect/utilities/logging.py
This was not as helpful as I originally anticipated and is causing some weird looking logs in production.  Vote to remove
=> Remove atexit log

CHANGELOG.md, src/prefect/serialization/flow.py, src/prefect/serialization/result_handlers.py, src/prefect/serialization/schedule.py, src/prefect/serialization/state.py, src/prefect/serialization/storage.py, src/prefect/serialization/task.py, src/prefect/utilities/serialization.py
Adds `**kwargs` to all methods decorated my marshmallow decorators.
Fixes a breaking change caused by the recently released `marhsmallow 3.0.0rc7`.
=> Add kwargs to all marshmallow decorated methods

README.md, docs/guide/getting_started/installation.md
Fixed typo in installation doc. Had `-pre` instead of `--pre`
Closes #1158 
For proper installation instructions
=> Fix --pre typo in installation doc

docs/guide/tutorials/local-debugging.md, docs/guide/tutorials/visualization.md
=> Fix two doc typos

CHANGELOG.md, src/prefect/core/flow.py, tests/core/test_flow.py
Fixes issue with `flow.update` not preserving mapped edges properly.
Closes #1164
=> Fix flow update

.circleci/config.yml
Attempt to delay the upload of codecov reports until the end.  Closes #1102 
Implementation inspired by @zangell44's  in https://github.com/PrefectHQ/prefect/pull/1104
=> Attempt to persist reports to disk and upload them all at once

src/prefect/environments/execution/cloud/job.yaml, src/prefect/environments/execution/cloud/worker_pod.yaml
Temporary adjustment to allow for debugging support in deployed flows
=> Cloud Env privilege for debugging

setup.py
Related to fixing hanging issue that was outlined in https://github.com/kubernetes-client/python/issues/411
=> Bump bounds of kubernetes requirement

src/prefect/environments/execution/cloud/job.yaml, src/prefect/environments/execution/cloud/worker_pod.yaml
Reverts PrefectHQ/prefect#1174
Flow debugging attempts were successful 👍
=> Revert "Cloud Env privilege for debugging"

CHANGELOG.md, src/prefect/client/client.py, tests/client/test_client.py
This PR explicitly casts parameters and context to raw python dictionaries when queried from Cloud. 
Closes #1186
=> Parameter JSON fix

README.md, docs/guide/welcome/community.md
=> Add public Slack channel to docs

src/prefect/environments/execution/cloud/job.yaml, src/prefect/environments/execution/cloud/worker_pod.yaml
=> Remove result handler from CloudEnvironment job and worker yaml

tests/engine/cloud/test_cloud_flows.py
=> Fix cloud flow test

CHANGELOG.md, src/prefect/cli/run.py
Adds `--logs/-l` to `prefect run cloud` command for live streaming logs. (alternatively logs can be retrieved through `prefect get logs`)
Live log streaming is a nice CLI feature to have
=> Added log streaming to run CLI command

src/prefect/utilities/context.py
=> Update documentation for context to include other relevant values

docs/guide/tutorials/dask-cluster.md, src/prefect/config.toml, src/prefect/engine/executors/__init__.py, src/prefect/engine/executors/sync.py
This PR:
- adds a few notes about executor usage
- adds a warning box for Dask work stealing in our Dask tutorial
=> Dask Work Stealing

CHANGELOG.md, src/prefect/tasks/docker/images.py, tests/tasks/docker/test_images.py
Fixes issue with docker build image task not running to completion; also makes the return value much friendlier per @TylerWanner 's feedback.
Closes #1243
=> Fix issue with docker build image not running

dev-requirements.txt, requirements.txt
Compatibility operators don't appear to play nicely with dependabot
=> Remove compatibility operators

CHANGELOG.md, src/prefect/engine/cloud/task_runner.py, src/prefect/engine/runner.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/test_task_runner.py
Closes #1326 
Better logs = better debugging experience
=> Add error log for exceptions raised in state handlers with tests

README.md
=> Add new unlimited slack invite link to README

CHANGELOG.md, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
Fixes bug we saw in our exercise.
=> Fix issue with Docker storage not respecting user-provided image names

MANIFEST.in, src/prefect/agent/kubernetes/deployment.yaml, src/prefect/agent/kubernetes/resource_manager.py
Minor tweaks for a working kubernetes agent (yaml file including and resource manager config)
=> Minor K8s Agent Tweaks

.circleci/config.yml, docs/cloud/cloud_concepts/lazarus-process.md
This PR documents adds Cloud's Lazarus process as a cloud concept in the documentation. It also pins the miniconda image pulled for `test-airflow` in response to broken tests caused by the latest miniconda image.
It's important to be transparent and keep folks informed about how their flows are interacting with the system.
=> Document the Lazarus process

src/prefect/cli/agent.py
Minor docstring tweaks for `agent` cli commands
`install` wasn't visible before on the help output
=> Clean up agent CLI docstrings

src/prefect/cli/auth.py, tests/cli/test_auth.py
Minor tweak to access preexisting auth token (if it exists) for `auth login` CLI command
Also closes #1385
If would fail if there was no token :)
=> Update stability of login CLI command

docs/guide/examples/task_looping.md, examples/task_looping.py, src/prefect/utilities/context.py, tests/core/test_flow.py
Adds some documentation related to Looping + a test.
Closes #1361
=> Some Loop docs

docs/cloud/agent/kubernetes.md, docs/cloud/agent/local.md, docs/cloud/upandrunning.md
=> Rename RUNNER token type in doc to proper name

src/prefect/config.toml, src/prefect/environments/storage/local.py
Accidentally left out of the rebased #1423
=> Add home_dir to config

docs/cloud/cloud_concepts/debug.md, docs/cloud/faq.md, docs/guide/core_concepts/schedules.md
Closes #1292, updates some FAQs and debug sections.
=> More doc tweaks

.gitignore
Add new pip directory that is created on installs
=> Add pip-wheel-metadata to .gitignore

CHANGELOG.md, docs/cloud/cloud_concepts/zombie-killer.md, src/prefect/environments/execution/base.py, src/prefect/environments/execution/dask/k8s.py, src/prefect/environments/execution/local.py, src/prefect/environments/execution/remote.py, src/prefect/serialization/environment.py, tests/environments/execution/test_base_environment.py, tests/environments/execution/test_dask_k8s_environment.py, tests/environments/execution/test_local_environment.py, tests/environments/execution/test_remote_environment.py, tests/serialization/test_environments.py
This PR introduces a `labels` kwarg to all environments for specifying environment labels.  These labels are also serialized and communicated to Cloud. 
Closes #1438 - this PR is the first step in enabling first-class support for multi-environment agents.  Currently listed as an "Enhancement" in the Changelog, the actual corresponding Agent change will elevate this to a "Feature".
=> Add Environment Labels

docs/cloud/faq.md, docs/guide/tutorials/dask-cluster.md
=> FAQ + Dask blurb

CHANGELOG.md, src/prefect/environments/storage/docker.py
Uses `-U` to override base image's prefect version (if present).
**cc:** @bnaul
=> Docker prefect version

CHANGELOG.md, src/prefect/utilities/debug.py, tests/client/test_client_auth.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/executors/test_executors.py, tests/tasks/test_shell.py, tests/tasks/test_sqlite.py, tests/utilities/test_debug.py, tests/utilities/test_executors.py
This PR gets us to a place where all of our core tests pass on Windows.  The next step is for me to manually QA Flow deployments to Cloud and address any remaining issues I find in the process.
For supporting Windows compatibility.
=> Windows compatibility: Phase 2

CHANGELOG.md, src/prefect/client/client.py, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
This PR makes the final polishing touches on Core so that Flows can now be built, tested, deployed to Cloud, and even run on Windows machines through Local Agents.
Prepares Core for onboarding Windows users!
=> Windows compatibility: endgame

docs/guide/core_concepts/execution.md, src/prefect/tasks/core/constants.py, src/prefect/triggers.py
Addresses #1467.  Also adds a blurb about Constant tasks.
=> More trigger docs + constant docs

CHANGELOG.md, src/prefect/agent/agent.py, src/prefect/agent/kubernetes/agent.py, src/prefect/agent/kubernetes/deployment.yaml, tests/agent/test_agent.py, tests/agent/test_k8s_agent.py
=> Kubernetes Agent Liveness Probe

docs/cloud/cloud_concepts/secrets.md, src/prefect/client/secrets.py
Updates some secrets documentation to reflect that Secrets can be set directly in context; also updates the example code to use `setdefault` as the `secrets` key is not guaranteed to exist.
**cc:** @rabernat
=> Clarify some secrets documentation

docs/core/development/documentation.md, src/prefect/triggers.py
Fixes a typo in the Triggers docs and adds a new section in the documentation guidelines about Class capitalization.
No typos :)
=> Triggers typo fix

docs/.vuepress/enhanceApp.js
=> Add route redirects for old docs links

src/prefect/utilities/configuration.py, src/prefect/utilities/context.py
=> Add references to config in context

src/prefect/client/client.py, tests/client/test_client_auth.py
Closes #1483 
I didn't update the changelog because this is just a simple internal implementation detail change that keeps Core up-to-date with Cloud's latest API
=> expiresIn -> expiresAt

docs/cloud/concepts/secrets.md, docs/cloud/first-steps.md, src/prefect/client/secrets.py
Adds some tips about `.toml` config files to the secrets pages and fixes a typo.
To avoid some painful and hard to trace errors when setting up secrets (also to make our typing teachers happy)
=> Secrets addition

src/prefect/engine/result_handlers/__init__.py
=> Add example to the result handler API documentation

CHANGELOG.md
=> Update CHANGELOG ordering

CHANGELOG.md, src/prefect/serialization/environment.py, src/prefect/utilities/logging.py, tests/serialization/test_environments.py, tests/tasks/test_shell.py, tests/utilities/test_logging.py
This PR fixes the serialization schema for DaskK8s custom specs, and adds support for serializing custom user-written environments.
Users can now create their own custom environments for deploying Flows in Cloud (once the Cloud serializers have been updated).
=> Serialize all environments

docs/.vuepress/config.js, docs/cloud/agent/fargate.md, docs/outline.toml, src/prefect/agent/agent.py, src/prefect/agent/fargate/agent.py, src/prefect/agent/kubernetes/agent.py, src/prefect/agent/local/agent.py
Adds a doc for the Fargate Agent and now the Agent API docs are available
=> Fargate Agent Doc and Agent API Docs

README.md, docs/.vuepress/config.js, docs/core/concepts/execution.md, docs/core/concepts/persistence.md
- separates out "persistence" from execution for easier discoverability
- adds a few relevant comments on data persistence
- adds a section on Checkpointing, which was entirely absent before
- updates README to include a blurb about Cloud compatibility on the master branch
=> Add documentation for checkpointing

src/prefect/engine/state.py, src/prefect/engine/task_runner.py, src/prefect/serialization/state.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/test_state.py, tests/engine/test_task_runner.py, tests/serialization/test_states.py
This PR introduces a concept of "state context" on all states.  Currently only `Running` states have their context updated to include Task tags.
This simple idea will power many of our features that are about to be introduced.  
**NOTE:** This PR will prevent any deploys to Prefect Cloud until another release is made!
=> State context

tests/cli/test_execute.py, tests/cli/test_run.py
Some minor CLI tests for run and execute
=> Minor CLI Test Additions

src/prefect/engine/state.py, src/prefect/engine/task_runner.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/test_state.py, tests/engine/test_task_runner.py, tests/serialization/test_states.py
Adds task tags to _all_ state contexts at initialization.
Allows us to communicate a much richer set of data to Cloud, enabling certain features ;)
=> Add task tags to all state contexts

src/prefect/engine/signals.py, src/prefect/engine/state.py, src/prefect/serialization/state.py, tests/engine/test_state.py, tests/serialization/test_states.py
This PR introduces a `context` kwarg to `State.__init__` for all states.
Exposes an easier interface for passing around execution context information.
=> State Context init

src/prefect/environments/execution/dask/k8s.py, src/prefect/environments/execution/k8s/job.py
=> Tweak docstring formatting

CHANGELOG.md, src/prefect/engine/executors/dask.py
This PR enhances our integration with Dask when performing large mapped work.  In particular, we were observing that large mapped pipelines would hang for extended periods of time prior to any work being performed.  It turns out that our TaskRunner class (which is very heavy as it includes references to the underlying Task, context, etc.) was being serialized many times and causing a significant slow down in performance.  This PR flips the perspective so that the function payload itself is considered "data" and scattered to all the workers first.  This should drastically speed up performance of mapped pipelines, in particular …
=> Faster maps

docs/core/task_library/aws.md
=> Fix AWS links in docs

CHANGELOG.md, src/prefect/core/flow.py, tests/core/test_flow.py
Many users have asked us what to do when they try `flow.visualize()` without graphviz installed.  This PR adds a (hopefully) more informative error message for this situation.
Better UX.
=> Better exception message

CHANGELOG.md, src/prefect/tasks/docker/containers.py, src/prefect/tasks/docker/images.py, tests/tasks/docker/test_containers.py, tests/tasks/docker/test_images.py
This PR allows for better debug logging of docker tasks.
Debug logs help debug errors
=> Improved Docker Tasks' Logging

docs/api/0.6.6/schedules/schedules.md, src/prefect/schedules/schedules.py
A typo in our docs
It's not really, it's just a typo fix
=> NS schedules typo

docs/cloud/concepts/concurrency-limiting.md
Fix small typo in GraphQL query
Docs
Existing query fails with `400 Client Error: Bad Request for url: https://api.prefect.io/graphql/alpha`
=> Minor fix for Task Tag Limit GraphQL Query

CHANGELOG.md, docs/index.md
- Adds an "Ask for help" button on the welcome page which takes (if clicked) takes a user to the prefect.io/support page
- Helps users find the support page
=> adds an ask for help button (with link to website support page) to the docs

docs/core/PINs/PIN-12-Environment-Callbacks.md
Minor PIN 12 doc header fix to include PIN number
=> Update PIN 12 doc header

CHANGELOG.md, src/prefect/tasks/shell.py
if the command returns no lines `line` is undefined
=> line is undefined

docs/cloud/flow-deploy.md
It changes `your` to `you` in the introductory paragraph of `Prefect Cloud: Deploying a Flow`.
It fixes a typo in the docs so the sentence can be grammatically correct.
=> Fix typo in flow-deploy.md

src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
Allows flow docker builds to be derived from the tip of Prefect core master branch. 
This allows users to use the latest features from master with little to no effort.
=> Allow flow builds from the master Prefect core branch

docs/cloud/faq.md, docs/core/concepts/execution.md
=> Add backfill FAQ and improved linking

docs/.vuepress/config.js, docs/cloud/deployment.md
Adds a document on deployment considerations when moving from Core -> Cloud.  I still want to include more intricate examples than https://docs.prefect.io/cloud/flow-deploy.html but this hopefully outlines in a little more detail how things work.
=> Deploy gotchas

docs/.vuepress/config.js, docs/generate_docs.py
=> Link directly to codecov coverage report from the sidebar

docs/cloud/README.md, docs/core/README.md, docs/core/welcome/what_is_prefect.md, src/prefect/engine/cache_validators.py, tests/client/test_client_auth.py, tests/core/test_task_map.py, tests/engine/cloud/test_cloud_flow_runner.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/cloud/test_utilities.py, tests/engine/test_flow_runner.py, tests/engine/test_task_runner.py, tests/environments/storage/test_docker_storage.py
=> Update references to Prefect Cloud

docs/cloud/agent/fargate.md, docs/cloud/agent/kubernetes.md, docs/cloud/agent/local.md, docs/cloud/agent/overview.md, docs/cloud/concepts/execution.md
Updates agent documentation to make labels more visible
Some of the label functionality wasn't explained enough and this needs to be added for clarity
=> Add more documentation around using Environment Labels w/ Agents

src/prefect/agent/agent.py
Very minor change to have an Agent output its labels when starting.
When configuring multiple agents with Environment Labels, it's very helpful to confirm what labels the Agent was started with.
=> Output labels on startup

CHANGELOG.md, src/prefect/agent/kubernetes/agent.py, tests/agent/test_k8s_agent.py
Closes #1697 
Our docker image tagging format changed
=> Add python version for new image tags to k8s agent deployment yaml

docs/cloud/agent/fargate.md
Fargate Agent documentation addition for clarity. Adds list of accepted kwargs and description of environment variable parsing
=> Add kwargs and environment variable casing example to Fargate Agent doc

src/prefect/client/client.py, tests/client/test_client_auth.py
This was bugging me, no functional difference
=> Update local settings path to property

docs/core/PINs/PIN-13-Universal-Deploy.md
=> Add PIN 13 to public docs

README.md, docs/README.md, docs/api/0.6.4/README.md, docs/api/0.6.5/README.md, docs/api/0.6.6/README.md, docs/api/0.6.7/README.md, docs/api/0.7.0/README.md, docs/api/0.7.1/README.md, docs/api/0.7.2/README.md, docs/core/welcome/community.md, docs/index.md
Update Slack link with new link
=> Update Slack link

CHANGELOG.md, src/prefect/utilities/executors.py, src/prefect/utilities/logging.py, tests/utilities/test_executors.py, tests/utilities/test_logging.py
This PR revisits the logging of heartbeat thread failures and improves our ability to detect exceptions raised in the heartbeat thread.  We `try / except` inside the `_heartbeat` method but there is still the possibility that the thread dies or ceases running, and this PR ensures that this event will get logged.
Improved debugging power - if a task run is marked as zombie we will have better visibility into whether the thread died or there was a deadlock.
=> Better heartbeat thread management

CHANGELOG.md, src/prefect/engine/state.py, tests/engine/test_state.py
Adds new `children()` and `parents()` convenience methods on states for easily navigating the state hierarchy.
This pattern comes up a lot in either inferring all subclasses that should trigger events, creating visualizations, etc. so this consolidates the logic into one place.
=> State inspection methods

docs/cloud/agent/docker.md, docs/cloud/agent/fargate.md, docs/cloud/agent/local.md, docs/cloud/concepts/cli.md, docs/cloud/concepts/concurrency-limiting.md, docs/cloud/concepts/flows.md, docs/cloud/concepts/projects.md, docs/cloud/deployment.md, docs/cloud/execution/dask_k8s_environment.md, docs/cloud/execution/overview.md, docs/cloud/execution/remote_environment.md, docs/cloud/faq.md, docs/cloud/flow-deploy.md, docs/cloud/recipes/configuring_storage.md, docs/cloud/recipes/multi_flow_storage.md, docs/cloud/the-basics.md, docs/cloud/upandrunning.md, src/prefect/agent/local/agent.py, src/prefect/cli/run.py, src/prefect/client/client.py, src/prefect/core/flow.py, src/prefect/environments/storage/local.py, src/prefect/utilities/debug.py, tests/cli/test_agent.py, tests/client/test_client.py, tests/core/test_flow.py
This is a change being merged into the `deploy-2.2` branch and this PR is for checking purposed before it's merged.
Renames `deploy` to `register` and updates references of it. cc @cicdw
=> Deploy -> Register

docs/core/concepts/mapping.md, docs/core/concepts/notifications.md
This PR simply implements minor typo fixes in the documentation.
This PR is of small importance, but no one ever regrets a typo fix (probably).
=> Minor typo fixes in the documentation

docs/cloud/agent/overview.md, docs/cloud/execution/overview.md
This PR tightens up the wording in our docs related to Cloud execution and the Agent. 
While minor, any improvement to readability is a good thing.
=> Refine wording in Cloud and Agent docs

src/prefect/environments/storage/s3.py, tests/environments/storage/test_s3_storage.py
Handles client errors that may arise when uploading and downloading flows from S3. Adds a helpful graceful logging error message
If an S3 storage object tries to download a file which does not exist or upload to a bucket that does not exist a botocore `ClientError` will be raised.
=> Handle possible ClientErrors in S3 storage

docs/.vuepress/styles/index.styl
- Updates the argument list bullet padding
- Overrides the code-copy button class height (to remove space at the end of code blocks)
Styling :) 
Arg lists:
**Before**:
**After**:
Codeblocks:
**Before**:
**After**:
=> Fix padding issues

MANIFEST.in
Fixes our broken [feedstock](https://github.com/conda-forge/prefect-feedstock/pull/25)
=> Add new test requirements file to manifest

CHANGELOG.md, docs/cloud/agent/overview.md, src/prefect/agent/agent.py, src/prefect/agent/docker/agent.py, src/prefect/agent/fargate/agent.py, src/prefect/agent/kubernetes/agent.py, src/prefect/agent/local/agent.py, src/prefect/agent/nomad/agent.py, tests/agent/test_agent.py, tests/agent/test_docker_agent.py, tests/agent/test_fargate_agent.py, tests/agent/test_k8s_agent.py, tests/agent/test_local_agent.py, tests/agent/test_nomad_agent.py
Refactors the main agent process.
Previously:
The agent deployed _before_ submitting. It also deployed and submitted over entire list of found flow runs at once which means if there was an error in deploying a single one of those flow runs then they would all fail to be deployed / submitted.
Now:
The process now iterates over flow runs individually which allows for new functionality! Marking as submitted happens _after_ the deployment takes place. Deployment returns some information about the infra created (e.g. k8s job name, process ID, etc...) which is then passed into the message for the `Submitted` state. If any error is …
=> Agent Process Enhancements

docs/cloud/concepts/flows.md
This PR updates broken links in `flows.md` and documents how to set flow settings.
There is a very real demand for these flow settings, but they're not particularly useful without docs explaining how to use them and what they do.
=> Update flow docs for Cloud

appveyor.yml
Now that the pytest logger issue may be fixed we can readd windows tests w/ appveyor
=> Add appveyor build step

docs/cloud/concepts/flows.md
- [x ] adds new tests (if appropriate)
- [x ] updates `CHANGELOG.md` (if appropriate)
It fixes some graphql queries which returned errors when I tried them.
So that the graphql examples in the docs work.
=> Update graphql in flows.md

README.md
Adds a link to the blog to the REAME
Our README is often the first place people come to learn about Prefect and we should point them to all the resources at their disposal.
=> add a link to The Prefect Blog to the README

CHANGELOG.md, src/prefect/agent/agent.py, src/prefect/agent/docker/agent.py, src/prefect/agent/fargate/agent.py, src/prefect/agent/kubernetes/agent.py, src/prefect/agent/local/agent.py, src/prefect/agent/nomad/agent.py, src/prefect/cli/agent.py, tests/agent/test_agent.py, tests/agent/test_docker_agent.py, tests/agent/test_fargate_agent.py, tests/agent/test_k8s_agent.py, tests/agent/test_local_agent.py, tests/agent/test_nomad_agent.py, tests/cli/test_agent.py
This PR introduces new initialization kwargs on all Agents for easily setting environment variables on all submitted flow runs.
This allows users to set environment variables on all flow runs submitted through an agent, which allows for easier and more secure authentication in some situations.  Closes #1878
=> Agent environment variables

.github/CODEOWNERS
=> Add Alex as a code owner

CHANGELOG.md, src/prefect/core/flow.py, tests/core/test_flow.py
Fixes `flow.visualize` in the case when flow state is provided and there is a reduce task.
Closes #1793
=> Fix flow.visualize for reduce tasks

docs/cloud/dataflow.md, docs/cloud/execution/storage_options.md, docs/core/concepts/persistence.md
Updates some places in the docs to mention default result handlers and the fact that checkpointing is now enabled by default.
Should they mention future plans? i.e. #1910
=> Update documentation about results and checkpointing

docs/cloud/recipes/k8s_dask.md, docs/core/tutorials/dask-cluster.md
This PR updates some Dask deployment-related docs. Nothing big, just a few things I found during a naive runthrough.
Just tidying up.
=> Update Dask deployment docs

.circleci/config.yml
The build of a `master` tagged image is successful. This PR updates the _Test image_ step to ensure it uses the recently built `master` image for the test 👍
=> Test master build image against recently tagged local image

.circleci/config.yml, appveyor.yml
Adding verbosity to the pytest output such that when a case fails as much information can be gleaned as possible to troubleshoot.
=> Add detailed output in CircleCI pytest runs

src/prefect/agent/agent.py, tests/agent/test_agent.py
Fixes a race condition in the agent logic where the set of flow runs that are currently being submitted may be modified while still reasoning about which flow runs should not be kicked off next. The fix keeps a copy of the set in question at the top of the function does performs this logic at a time before the query occurs.
Intended to be merged into the branch of #1960
=> Ensure flow run submission checks are performed with static data

CHANGELOG.md, src/prefect/agent/fargate/agent.py, tests/agent/test_fargate_agent.py
=> Handle possible Fargate agent SyntaxError from kwarg parse

tests/environments/storage/test_docker_storage.py
=> Fix two docker tests that failed on tagged commits

docs/cloud/concepts/scheduled-flows.md, docs/core/concepts/schedules.md
=> Schedule doc additions

src/prefect/utilities/executors.py
This PR fixes an issue from #1973 that prevented heartbeats from firing on static Dask Clusters.  We can't expect (and shouldn't expect) users to configure their dask workers' environment to have all the correct Prefect settings.  In #1973 I submitted heartbeats to fire in a subprocess, which uses its ambient environment for an auth token, but because none was present tasks would get marked as zombies if they ran for more than ~3 minutes.   This PR fixes that by extracting both the auth token and API url (for internal use) from config and explicitly setting them on the subprocess's environment.  I tested this on a static …
=> Pass API and Auth down to heartbeat subprocess

docs/core/tutorials/local-debugging.md, docs/outline.toml
Closes https://github.com/PrefectHQ/prefect/issues/1999
=> Remove stale references to SynchronousExecutor

CHANGELOG.md, docs/cloud/concepts/zombie-killer.md
Fixes the [docs page](https://docs.prefect.io/cloud/concepts/zombie-killer.html) on the minimum heartbeat age required for Zombie Killer to mark task runs and parent objects as Failed, matching the behavior explained in the [Flow settings docs page](https://docs.prefect.io/cloud/concepts/flows.html#disable-heartbeats).
Fixes inconsistencies in the docs making Prefect Cloud easier to understand.
=> Fix Cloud docs on Zombie Killer

.gitignore, docs/core/tutorial/01-etl-before-prefect.md, docs/core/tutorial/02-etl-flow.md, docs/core/tutorial/04-handling-failure.md, docs/core/tutorial/05-running-on-a-schedule.md, examples/tutorial/04_handle_failures.py, examples/tutorial/aircraftlib/analysis.py, examples/tutorial/aircraftlib/database.py, examples/tutorial/aircraftlib/openflights.py, examples/tutorial/aircraftlib/opensky.py
This PR applies some minor cleanup to the tutorial.
I'm new to prefect, so read through it, using PyCharm which points out typos in the editor.
The changes in the 04 and 05 docs MD files are to match what is in the corresponding Python example files.
=> Minor cleanup in tutorial

docs/core/faq/faq.md
=> Fix broken link to Cloud dataflow FAQ

CHANGELOG.md, docs/cloud/execution/fargate_task_environment.md, docs/cloud/execution/k8s_job_environment.md, src/prefect/client/client.py, src/prefect/config.toml, src/prefect/environments/execution/dask/job.yaml, src/prefect/environments/execution/dask/k8s.py, src/prefect/environments/execution/dask/worker_pod.yaml, src/prefect/environments/execution/fargate/fargate_task.py, src/prefect/environments/execution/k8s/job.py, tests/cli/test_auth.py, tests/cli/test_create.py, tests/cli/test_describe.py, tests/cli/test_execute.py, tests/cli/test_get.py, tests/cli/test_heartbeat.py, tests/cli/test_run.py, tests/client/test_client.py, tests/client/test_client_auth.py, tests/engine/cloud/test_cloud_flow_runner.py, tests/engine/cloud/test_cloud_flows.py, tests/environments/execution/test_dask_k8s_environment.py, tests/environments/execution/test_fargate_task_environment.py, tests/environments/execution/test_k8s_job_environment.py
This PR reverts the API endpoint update to its old `api.prefect.io/graphql/alpha` endpoint.
=> Revert "Point client toward api.prefect.io"

package-lock.json, package.json
Updates Vuepress plugin that handles code block copying.
The update contains some improvements that impact usability on Safari, Edge, and Internet Explorer.
=> Updates vuepress plugin

docs/cloud/concepts/flows.md
Fixes a broken link to the Zombie Killer in the Cloud concept docs.
Cause broken links are bad 😺
=> Fix zombie killer link in cloud flow docs

docs/core/development/documentation.md
Adds detail to the documentation style guide about when to capitalize a Prefect concept like "flow" or "task"
=> Add detail to capitalization docs

CONTRIBUTING.md
Fix broken links on our CONTRIBUTING.md that were pointing to an old organizational scheme for the docs.
Contributors could get lost looking for our guidelines from the standard github interface and bounce.
=> Fix broken links on CONTRIBUTING.md

docs/core/getting_started/why-not-airflow.md
This paragraph got left behind in #2106
=> Add notes about UI

docs/cloud/concepts/flows.md
This PR updates the docs to reflect the new flow settings mutations.
Up-to-date and accurate docs are important.
=> Update docs with new flow setting mutations

docs/outline.toml, src/prefect/schedules/filters.py, tests/core/test_flow.py, tests/engine/test_flow_runner.py
Noticed there was room for clarity in two of the schedule filters docstrings.
=> Add some clarification on two time filters docs

docs/core/community.md
Adds a new section to the community page of the docs for us to keep track of community extensions outside of prefect core.
We don't have a place to store these right now, and though this isn't super high up in terms of discoverability, this gives us a place to link to if people are curious. As/if it gets bigger we might promote it to the README a la [webpack](https://github.com/webpack/webpack#plugins) …
=> Update community page with plugin section 

CHANGELOG.md, src/prefect/cli/run.py, src/prefect/client/client.py, src/prefect/utilities/notifications/notifications.py, tests/client/test_client.py
This PR adds title links to relevant pages in the Cloud UI to Slack notification messages when executing in a Cloud context.
The name of the state is now a link: 
Closes #2112 
**cc:** @bnaul
=> Slack notification upgrade

docs/core/concepts/flows.md
=> Fix typo in flow concept doc

CHANGELOG.md, docs/api/0.7.3/client/secrets.md, docs/api/0.8.1/client/secrets.md, docs/cloud/concepts/api.md, docs/cloud/concepts/flow_runs.md, docs/cloud/concepts/flows.md, docs/cloud/concepts/projects.md, docs/cloud/concepts/secrets.md, docs/cloud/concepts/task-concurrency-limiting.md, docs/cloud/concepts/tokens.md, docs/cloud/tutorial/first.md, docs/core/faq.md, src/prefect/agent/agent.py, src/prefect/cli/auth.py, src/prefect/client/client.py, src/prefect/client/secrets.py, tests/agent/test_agent.py, tests/cli/test_auth.py, tests/cli/test_heartbeat.py, tests/client/test_client.py, tests/client/test_client_auth.py, tests/client/test_secrets.py, tests/tasks/secrets/test_base.py
This PR updates docs and remaining API calls in the codebase to use snake_casing. 
Consistency is key.
=> Finish converting to snake case API calls

src/prefect/client/client.py
When registering a flow, only look up the project (and throw an error) if pointing at [Prefect Cloud](https://cloud.prefect.io)
So that we can register flows with no projects.
=> Projects are optional

README.md, docs/README.md, docs/index.md
Our "Hello World" tutorial is a little sparse and doesn't really illustrate any Prefect features. This adds `Parameters` and dataflow.
=> Update tutorial to include parameters and dataflow

README.md, docs/orchestration/README.md
In README and Orchestration landing page
=> Mention single CLI command

docs/.vuepress/enhanceApp.js, netlify.toml
It seems the vuepress redirects were not working
=> Fix cloud -> orchestration redirects

LICENSE
=> Update license path

CHANGELOG.md, README.md, docs/core/getting_started/installation.md, docs/orchestration/README.md, docs/orchestration/tutorial/configure.md, server/README.md, src/prefect/cli/docker-compose.yml, src/prefect/cli/server.py, src/prefect/config.toml
This PR adds a new server start command for spinning up all backend infra for serving the UI
Open sourcing the UI 🎉
=> Add server start cmd

.gitignore, server/services/ui/.env
This missing file was breaking our UI docker images
=> Add .env file to tracked repo for docker builds

CHANGELOG.md, src/prefect/cli/run.py
Returns Flow Run ID from CLI run methods
Allows CLI methods to be used for programmatic use to start flows on Prefect Cloud. Flow Run ID is needed to check status after a run completes
=> Return Flow Run ID in CLI run methods

CHANGELOG.md, src/prefect/engine/result_handlers/s3_result_handler.py, tests/engine/result_handlers/test_result_handlers.py
This PR changes the behavior of S3ResultHandler to allow it to function with S3 Compatible Object Stores.
https://github.com/PrefectHQ/prefect/issues/2240
Allow broader re-use of the S3ResultHandler with S3 Compatible Object Stores
=> S3 boto kwargs

docs/core/concepts/schedules.md
=> Fix schedule timezone example in concept doc

src/prefect/environments/execution/k8s/job.py
=> clear up some verbiage

CHANGELOG.md, docs/outline.toml, src/prefect/tasks/docker/__init__.py, src/prefect/tasks/docker/containers.py, tests/tasks/docker/test_containers.py
Adds a task for removing a docker Container
After running a container, it's likely that it needs to be removed.
=> Adds tasks.docker.containers.RemoveContainer

README.md, docs/core/getting_started/installation.md, docs/orchestration/README.md, server/README.md
=> Update server start references to mention docker and docker compose

docs/core/getting_started/first-steps.md
=> Fix links in first steps core doc

CHANGELOG.md, server/src/prefect_server/api/flows.py, server/tests/api/test_flows.py, src/prefect/client/client.py, tests/client/test_client.py
This PR fixes an issue server-side with registering flows that have required parameters which are scheduled.  This fix was previously implemented Client-side.
Closes #2296
=> Fix flow parameter registration

src/prefect/engine/results/__init__.py, src/prefect/engine/results/constant_result.py, src/prefect/engine/results/secret_result.py, tests/engine/results/test_results.py
Adds a new SecretResult type for handling sensitive data that tasks might return - depends on #2302 
PIN 16 work
=> Secret result

docs/orchestration/execution/storage_options.md
It was noted in Slack that these code snippets didn't work.
Closes #2317
=> Fix storage code snippets

server/services/apollo/src/index.js
This feels noisy and unnecessary for the Server setup
=> Turn off apollo tracing from server

src/prefect/engine/results/__init__.py, src/prefect/engine/results/azure_result.py, src/prefect/engine/results/gcs_result.py, tests/engine/results/test_azure_result.py, tests/engine/results/test_gcs_result.py, tests/engine/results/test_s3_result.py
Adds AzureResult.  Needs:
If anyone is listening, feel free to commit directly to my branch ;)
=> Add azure result

CHANGELOG.md, src/prefect/agent/docker/agent.py, src/prefect/cli/server.py, src/prefect/utilities/docker_util.py, tests/cli/test_server.py, tests/conftest.py
Attempt to fix issues with prefect-server / agent running on linux, described in https://github.com/PrefectHQ/prefect/issues/2324
This is a temporary fix until https://github.com/moby/moby/pull/40007 is released
=> Add extra_hosts to linux docker commands

CHANGELOG.md, server/docker/docker-compose.yml, server/services/ui/Dockerfile, server/services/ui/shell_scripts/start_server.sh, server/src/prefect_server/cli/dev.py, server/src/prefect_server/config.toml, src/prefect/cli/docker-compose.yml, src/prefect/cli/server.py, src/prefect/config.toml
Allows the GraphQL endpoint in the UI to be configured via `config.toml`
It allows remote deployment of Prefect Server to include a working UI. 
Resolves: #2237
=> Ui graphql endpoint

.circleci/config.yml, server/MANIFEST.in
Enables unit tests for the server & UI in circleci
=> Add server tests

docs/orchestration/tutorial/docker.md
=> cloud -> orchestration reference

CHANGELOG.md, src/prefect/agent/agent.py, tests/agent/test_agent.py
Enhances the `agent_connect` function to check for API connectivity
Could help surface connection issues early on. Also more prominently shows which API endpoint you are connected to
=> Adjust agent connect output and check for API connection

CHANGELOG.md, src/prefect/tasks/control_flow/conditional.py, tests/tasks/test_control_flow.py
Reverts PrefectHQ/prefect#2310
=> Revert "Control flow tasks return executed branch"

docs/core/getting_started/first-steps.md
Makes the toggle more clear :)
=> Add note to first steps about local backend configuration CLI command

src/prefect/cli/get.py, tests/cli/test_get.py
Mostly a test update to handle the Core server vs Cloud differences in projects when using the `get` CLI commands. Closes #2226
=> Adjust CLI tests for get commands to account for projects

CHANGELOG.md, src/prefect/client/client.py
=> Update graphql type for refreshing tokens

src/prefect/core/flow.py, src/prefect/core/task.py, src/prefect/engine/runner.py
Use collections.abc for ABC import. Fixes #2412
=> Import ABC from collections.abc for Python 3 compatibility

src/prefect/core/task.py, src/prefect/engine/result/base.py, src/prefect/engine/results/azure_result.py, src/prefect/engine/results/constant_result.py, src/prefect/engine/results/gcs_result.py, src/prefect/engine/results/local_result.py, src/prefect/engine/results/prefect_result.py, src/prefect/engine/results/s3_result.py, src/prefect/engine/task_runner.py, src/prefect/utilities/tasks.py, tests/engine/test_task_runner.py
**Note**:
Being merged into the `results-wiring` branch. Not fully done with tests but want some feedback on this check. (the couple target tests so far pass but there may be others that will fail due to the base branch)
- is the check in the correct place of the runner pipeline
- how should we handle a target being specified but no result (right now it just returns the original state)
- if we're putting it in a cached state how should we handle the cache duration aspect
=> Add task target kwarg and add check to task runner pipeline

src/prefect/engine/cloud/task_runner.py, src/prefect/engine/result/base.py, src/prefect/engine/results/local_result.py, src/prefect/engine/task_runner.py, tests/core/test_flow.py, tests/engine/cloud/test_cloud_task_runner.py, tests/engine/result/test_base.py, tests/engine/results/test_results.py
- improves `target` logic
- fixes `LocalResult` writing to unknown directories
- handles `load_results` failures better
=> Minor enhancements

.circleci/config.yml, appveyor.yml
This PR:
- excludes the `master` branch from being tested on Appveyor
- adds `PREFECT_VERSION` build arg to our master docker build (I have no clue how this was working previously)
Prevents red failures on our master build status.
=> Add prefect version to docker build for master image

.circleci/config.yml
=> Use circle SHA for master image builds

test-requirements.txt
=> [WIP] Attempt to fix codecov's incorrect coverage stats

src/prefect/core/flow.py, src/prefect/engine/task_runner.py, tests/engine/test_task_runner.py
=> Correctly respect targets and caching

test-requirements.txt
Reverts PrefectHQ/prefect#2532
=> Revert "Update pytest-xdist requirement from <1.32.0,>=1.23 to >=1.23,<1.33.0"

docs/core/advanced_tutorials/using-results.md, docs/core/concepts/persistence.md, docs/core/concepts/results.md, src/prefect/core/task.py
Fleshing out Result documentation more!
=> Result doc additions

CHANGELOG.md, docs/orchestration/recipes/deployment.md, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py, tests/serialization/test_storage.py
Closes #2025 
Allows flows to be written to Docker storage without requiring root permissions.
=> Write flows in Docker storage to /opt directory

src/prefect/environments/storage/_healthcheck.py, tests/environments/storage/test_docker_healthcheck.py
Was causing some deployments off master to fail
=> Fix issue with healthcheck on flows with no results

docs/core/concepts/tasks.md
Adds a note describing the behavior of `task_args` when using the `@task` decorator, which isn't well documented.
=> Add note on passing arguments via `task_args`

tests/agent/test_agent.py, tests/tasks/docker/test_containers.py
This PR fixes two tests that consistently failed on my machine.  Clearly some mocked state is being shared across tests but I couldn't ultimately track down the root cause.  Instead I adjusted the two tests accordingly.
Tests should run smoothly across many environments / setups / machines
=> Fix two tests that consistently failed on my machine

CHANGELOG.md, server/services/ui/src/graphql/Dashboard/hello.gql, server/services/ui/src/pages/Dashboard/ApiHealthcheck-Tile.vue, server/services/ui/src/pages/Dashboard/Dashboard.vue, server/services/ui/tests/unit/pages/__snapshots__/Dashboard.spec.js.snap, server/services/ui/tests/unit/pages/graphqlMocks.js
Closes #2395. Adds a new tile that showcases the status of the `hello` query to Apollo to determine if we are connected to the API layer, and what the current API endpoint is configured as.
So people will be less confused about whether their UI is connected correctly :)
=> Closes #2395. Adds API healthcheck

docs/orchestration/recipes/k8s_docker_sidecar.md
Relevant slack discussion: https://prefect-community.slack.com/archives/CL09KU1K7/p1589909387169700
=> Fix dind-daemon yaml in docker sidecar recipe doc

docs/core/PINs/PIN-07-Storage-Execution.md, docs/core/PINs/PIN-09-CLI.md, docs/core/PINs/PIN-10-Schedules.md, docs/core/PINs/PIN-14-Listener-Flows-2.md
Updates PIN language to standardize on "Accepted" (instead of where we sometimes used "Approved") and specifies that PIN 14 is "Paused".
Mostly to clarify the state of the event driven PIN.
=> update pin language

changes/pr2620.yaml, src/prefect/client/secrets.py
Adds more informative error message whenever a secret doesn't exist in Cloud.
Better UX
=> Secret message

src/prefect/_siginfo.py, src/prefect/engine/task_runner.py
This PR removes two instances of local variables that are initialized or unused. Most cases `flake8` turns up for that issue in this project are false positives, but I think these two can be safely removed.
This is minor cleanup to remove code that is unused. It will have no user-facing impact but removes two unnecessary lines that take time (however small) to run.
=> remove unused local variables

src/prefect/config.toml
Reverts PrefectHQ/prefect#2651
=> Revert "Remove reference to `graphql/alpha`"

CHANGELOG.md, docs/.vuepress/config.js
This release was a quick revert of a change from `0.11.3`
=> 0.11.4 Changelog and API Docs

docs/core/tutorial/06-parallel-execution.md
Updates docs
Dead link corrected
=> Updated dask local cluster url.

changes/issue2676.yaml, server/docker/docker-compose.yml
Closes #2676
This volume mount isn't needed since as local dev builds shouldn't attempt to persist data
=> Remove volume mount from dev infrastructure Docker compose

server/setup.py, server/src/prefect_server/configuration.py, server/src/prefect_server/database/orm.py, server/src/prefect_server/services/graphql/server.py, server/src/prefect_server/utilities/__init__.py, server/src/prefect_server/utilities/graphql.py, server/src/prefect_server/utilities/http.py, server/tests/database/test_hasura.py, server/tests/graphql/conftest.py, server/tests/graphql/test_server.py
This PR bumps server dependencies that have fallen a bit behind. The only one that requires changes to code is httpx, which adopted a new API in v 0.13.
=> Bump Server dependencies

docs/core/idioms/idioms.md, docs/core/idioms/notifications.md
Small idiom addition for notification types. I could expand on this more however a lot of notification based concepts are already present in the docs. This is more of a small way to tie them together.
=> Add idiom for notifications

src/prefect/tasks/prefect/flow_run.py
This PR updates some of the language around `FlowRunTask`, hopefully making it clearer that it can be used with Prefect Core's server or Prefect Cloud. Closes #2497.
We've had some questions about this, and it never hurts to disambiguate.
=> Update FlowRunTask docs

docs/orchestration/agents/local.md
=> Update local.md to fix code typo

changes/pr2736.yaml, src/prefect/engine/executors/base.py, src/prefect/engine/executors/dask.py, src/prefect/engine/executors/local.py, src/prefect/engine/flow_runner.py, tests/engine/executors/test_executors.py
A user brought to my attention last night that our dask resource tags were not being respected; it appears that we pulled tags from context but those are not present at `executor.submit` time.  Instead of relying on implicit `context` keys this PR adds an `executor_kwargs` keyword to `submit` that allows the explicit passing of info.
Fixes bug.
=> Dask resources

docs/orchestration/execution/storage_options.md
Relies on #2745 for warning at the end of this doc
=> Add example to storage doc of credentials secret and add warning about dependencies

README.md, docs/index.md
The PR adds a link to the Prefect Server Feedback Survey to the docs and README.
No changelog entry necessary for this one.
We want to gather as much feedback as possible. This PR helps spread the word!
=> Add survey

.circleci/config.yml, changes/issue2801.yaml
=> Fix all_extras tag in CI job

docs/core/development/sprints.md
Changing up the sprints page to not mention in person events lolol and link to meetup for event listings.
It's easier to update the meetup page with the sprint schedule, and we are likely not meeting in person any time soon.
=> update sprints page re digital events, meetup link

changes/issue2822.yaml, docs/orchestration/agents/fargate.md, src/prefect/agent/fargate/agent.py, tests/agent/test_fargate_agent.py
=> Add repositoryCredentials to Fargate agent containerDefinitions

changes/pr2832.yaml, src/prefect/client/client.py, src/prefect/tasks/prefect/flow_run.py
- Closes #2810 
- Fixes a bug with `FlowRunTask` when running against a local server deployment
Bug fixes.
=> Two small bug fixes

docs/.vuepress/config.js, docs/.vuepress/enhanceApp.js, package-lock.json, package.json
Removes the `vuepress-plugin-smooth-scrolling` plugin and re-implements smooth scrolling with some custom logic. This'll reduce the bundle size and fix an issue where anchor scrolling wasn't working on the first load of the page. 
Fixes a bug, reduces bundle size.
=> Docs fixes pt 2

src/prefect/agent/fargate/agent.py, tests/agent/test_fargate_agent.py
This is a continuation of #2825 (still in master) and closes #2822
=> Add repositoryCredentials to updated containerDefinitions

.github/ISSUE_TEMPLATE/1. bug_report.md, .github/ISSUE_TEMPLATE/2. enhancement-of-an-existing-feature.md, .github/ISSUE_TEMPLATE/config.yml
(Sorry for noise, I don't know how to preview these changes except live)
1. The quote "We demand rigidly defined areas of doubt and uncertainty" will seem weirdly antagonistic to anyone not (deeply) familiar with H2G2
2. Align use of double-quotes
3. Align capitalization
=> Update quotes in issue chooser

docs/core/faq.md, docs/core/getting_started/why-not-airflow.md
Very minor change to update URLs to the preferred landing page for Cloud
=> Update links in docs to canonical download page

docs/orchestration/README.md
=> Fix 404 link in docs

docs/orchestration/agents/docker.md
=> Fix typo in documentation: dockerly -> locally

src/prefect/core/flow.py, src/prefect/engine/flow_runner.py, tests/engine/test_flow_runner.py
=> Only set task ID in flow dot run

changes/pr2940.yaml, src/prefect/environments/execution/fargate/fargate_task.py
When using this environment with core's server there is no auth token present so this access needs to be updated
=> Fix FargateTaskEnvironment token retrieval for runs using core server

docs/orchestration/tutorial/configure.md
If a user has previously used server, they need to switch their backend to cloud but there's no specific instruction for that in the tutorial. This adds in a small, cloud specific reminder. 
Helps new users who are following the tutorial
Inspired by this support interaction: https://prefect-community.slack.com/archives/CL09KU1K7/p1594380088460600
=> Add specific prefect backend cloud instruction

src/prefect/utilities/tasks.py
=> fix apply_map doc string formatting

docs/orchestration/concepts/flows.md
Updates the set schedule graphql mutations example in the docs
The example previously given is deprecated and was causing confusion - e.g see https://prefect-community.slack.com/archives/CL09KU1K7/p1594964464271000
=> Update schedule toggle mutations in docs

src/prefect/agent/kubernetes/agent.py
This PR proposes updates to the documentation on how to customize the behavior of `KubernetesAgent`. I have been working with `KubernetesAgent` a lot recently, and it took me a while to figure out how to customize the job that the agent creates.
Today, the template for the flow run job, created by `KubernetesAgent.replace_job_spec_yaml()`, can be changed by setting environment variables on the agent, For example, you can set `IMAGE_PULL_SECRETS` to add a secret to every job that it uses to pull images from a non-public registry.
Each of these environment variables is mirrored by a keyword argument in `KubernetesAgent.generate_deployment_yaml()`, but in my case I ran that method one time at the …
=> [docs] clarify docs on customizing jobs via KubernetesAgent

src/prefect/engine/results/__init__.py
Fixes a broken link in the docstring to advanced tutorial using results.
=> broken link in docs fo using results advanced tutorial

docs/orchestration/execution/storage_options.md
=> Add github to list of storage without default results

CHANGELOG.md, changes/issue3002.yaml, changes/issue3027.yaml, changes/pr2898.yaml, changes/pr3012.yaml, changes/pr3018.yaml, changes/pr3026.yaml, changes/pr3029.yaml, changes/pr3031.yaml, changes/pr3042.yaml, docs/.vuepress/config.js
=> Update docs / changelog for release

src/prefect/engine/cloud/flow_runner.py, tests/engine/cloud/test_cloud_flow_runner.py
Since `prefect.context` is a thread local, we need to ensure it's
properly copied into the background cancellation checking thread, since
logging relies on some parameters in the context. This wasn't caught
before since logging wasn't enabled. We fix this to copy the context
over to the background thread, and add a test to check that logging
calls all have the context available.
=> Ensure full context is available in cancel-checking thread

docs/core/advanced_tutorials/dask-cluster.md
Relates to #2094. Updates the Dask deployment tutorial with some references to content on the Dask blog that is useful for people going to the next step of deploying Dask from Prefect.
Make it easier to find resources for Prefect people who are setting up Dask for the first time.
=> Relates #2094. Update dask docs with linkouts to new related dask blog content

docs/orchestration/server/telemetry.md
- N/A adds new tests (if appropriate)
- N/A add a changelog entry in the `changes/` directory (if appropriate)
- N/A updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)
This PR updates our documentation for Server II.
So that users have the up-to-date information.
=> Update telemetry documentation for Server II

README.md, docs/.vuepress/config.js, docs/README.md, docs/generate_docs.py, docs/index.md
Updates the Prefect logo with the latest brand mark
=> Update Prefect logo

package-lock.json, package.json
`npm run docs:dev` was not hot reloading due to an issue in another dependency
=> Pin watchpack to fix doc hot reloading

docs/.vuepress/config.js, docs/orchestration/README.md, docs/orchestration/server/deploy-local.md, docs/orchestration/server/deploy.md, docs/orchestration/server/overview.md
=> Add server overview and tweak current docs

changes/pr3000.yaml
Changes the changelog entry for #3000 from `enhancement`  to `feature`.
Sorry! Re-reading https://github.com/PrefectHQ/prefect/blob/master/changes/README.md, I think that on #3000 I should have called that change a `feature` instead of an `enhancement`. This PR proposes a change that will make the next release's changelog slightly more accurate.
=> update Webhook change entry

docs/orchestration/server/deploy-local.md, docs/orchestration/server/overview.md, src/prefect/cli/server.py
A bit of proofreading of the new server docs.
=> Small server docs edits

README.md
Add links to Server / UI repos
=> Update README.md with links to new repos

docs/orchestration/server/deploy-local.md
This method mentioned previously is no longer supported https://github.com/PrefectHQ/ui/issues/99
=> Update server UI doc

docs/core/development/overview.md, docs/core/development/tests.md
This PR expands the development and testing docs
=> Expand development docs

docs/orchestration/agents/kubernetes.md, src/prefect/environments/storage/docker.py
=> Update kubernetes agent CLI output in documentation

Dockerfile, changes/pr3215.yaml
* Reduce overall size of final docker image by using layer less layers.
* Added default UTF-8 locale to system.
* Avoid having pip cache by using --no-install-cache
* Added comments to Dockerfile
* Shouldn't affect CI process since build arguments were left the same
* Overall image size of latest tag uncompressed was reduced from **425 MB** to **326 MB** a decrease of **23%**
* Added default locale UTF-8
* Remove **git** after installing Prefect.
* Reduce RUN layer to just 1 from 4.
* Reduce network usage when downloading image.
* Reduce storage usage when using Prefect Docker Image.
This PR:
- [-] adds new tests (if appropriate)
- [-] adds a change file in the `changes/` directory (if appropriate)
- [-] updates docstrings for any new functions or function arguments, including …
=> Dockerfile Refactoring and Improvements

docs/.vuepress/public/state_inheritance_diagram.svg, src/prefect/engine/state.py
Update cancelling color in docs to match the UI and differentiate between cancelled and cancelling
Maintain consistency with the UI, where it's important for users to be able to see the difference between cancelling and cancelled. 
This PR:
=> Cancelling color update

.circleci/config.yml, CHANGELOG.md, changes/pr3046.yaml, changes/pr3150.yaml, changes/pr3166.yaml, changes/pr3186.yaml, changes/pr3204.yaml, changes/pr3210.yaml, changes/pr3212.yaml, changes/pr3215.yaml, changes/pr3216.yaml, docs/.vuepress/config.js
In preparation for an 0.13.4 release
=> Update changelog + docs refs

changes/issue3239.yaml, src/prefect/agent/kubernetes/agent.py, tests/agent/test_k8s_agent.py
Fixes an issue wherein the K8s agent install manifest was incorrectly translating the `--env-vars` flags to environment variables.
Closes #3239 
Important feature, especially for auth / config related things.
This PR:
=> Fix env vars

README.md, docs/api/0.12.6/README.md
Remove links to old Server feedback survey
This PR:
=> Remove old feedback survey links

docs/core/advanced_tutorials/custom-logs.md
As pointed out in https://github.com/PrefectHQ/prefect/discussions/3252#discussioncomment-60752
=> Update logging docs

changes/pr3265.yaml, src/prefect/utilities/diagnostics.py
Added backend information to the prefect diagnostics Cli 
This PR:
=> Add backend to diagnostics

src/prefect/engine/cloud/flow_runner.py
This particular log was being generated every 30 seconds or so for flow runs with DEBUG logging level and was crowding up the logs views.  It _is_ useful when the flow run is no longer in a running state, so I've updated the logic accordingly.
This PR:
=> Make a regular flow runner heartbeat log a little less verbose

changes/pr3279.yaml, src/prefect/core/task.py
=> fix typo, Maginc -> Magic

changes/issue3256.yaml, src/prefect/__init__.py, src/prefect/utilities/logging.py
Adds logger to global context to remove friction on running task unit tests
This PR:
=> Add logger to global context

changes/pr3269.yaml, docs/core/task_library/github.md, docs/generate_docs.py, docs/outline.toml, docs/test_generate_docs.py, src/prefect/tasks/github/__init__.py, src/prefect/tasks/github/comments.py, tests/tasks/github/test_comments.py
Add a new task to create a comment on the specified github issue.
This PR:
=> Add a new task to create a github issue comment

CHANGELOG.md
=> Fix bad URL in changelog

docs/orchestration/server/deploy-local.md
Updates the docs with the changes from #3301 
^^^
Keeps the docs up to date and answers a common question in support threads.
This PR:
=> Update the local-deploy docs to include UI  Apollo endpoint setting

src/prefect/cli/run.py
=> Add example of passing parameters through CLI

changes/issue3306.yaml, src/prefect/tasks/gcp/__init__.py
My first open-source pull request. I fixed the from listing problem in the `src/prefect/tasks/gcp` file
Changes the syntax to pass pylint in the `src/prefect/tasks/gcp` file
for more details, see #3306
Linting is important to ensure code syntax is standard
Okay
This PR:
=> Corrected use from explicitly

docs/orchestration/ui/flow.md
Adds a brief explanation of flow group settings and flow group labels as they are set in the UI. 
Updates the UI flow page to include a brief description of flow group settings
We use flow group settings in the UI and the way they interact with flow settings needs explanation. 
This PR:
=> [WIP] - Add brief explanation of flow group settings

.github/ISSUE_TEMPLATE/config.yml, README.md, docs/README.md, docs/api/0.10.7/README.md, docs/api/0.11.5/README.md, docs/api/0.12.6/README.md, docs/core/community.md, docs/core/development/overview.md, docs/core/development/sprints.md, docs/index.md
I realized we are still using the old Slack invites in a few places
This PR:
=> Update slack links

changes/issue3347.yaml, src/prefect/cli/run.py, tests/cli/test_run.py
Allows for passing context values from CLI when creating a new flow run.
Closes #3347 
This PR:
=> Context via CLI

docs/outline.toml, src/prefect/environments/storage/__init__.py, src/prefect/environments/storage/base.py, src/prefect/environments/storage/webhook.py
=> Clean up old storage docs and add missing Storage base class and Webhook storage

dev-requirements.txt, test-requirements.txt, tests/engine/test_task_runner.py
Removes unnecessary upper bounds on many of our dependencies
=> Unbound test requirements

docs/core/task_library/contributing.md
small edit on code example 
This PR:
=> correction on import Flow

changes/pr3387.yaml, docs/outline.toml, src/prefect/tasks/monday/__init__.py, src/prefect/tasks/monday/monday.py
Adding first task to task library for monday.com that allows you create an item in a board. More tasks to come. 
This PR:
=> Monday task library

docs/orchestration/execution/fargate_task_environment.md
One more small fix to this doc
=> Add task definition to fargate task environment doc

docs/core/getting_started/installation.md
Update getting started in Prefect Core.
* Slightly reorders installation block
* Moves the mention of Prefect Cloud into a tip block
* Unifies formatting of configuration and server start
* Adds mention of Azure extensions, joining GCP and AWS
Smoother getting started docs are always good to have.
This PR:
*none of these checkboxes are appropriate for this change
=> Update getting started in Prefect Core

changes/issue3306.yaml, src/prefect/tasks/databricks/databricks_hook.py
Use explicit exception chaining for Databricks hook (more background in #3306)
Explicit exception chaining (i.e `raise PrefectError(...) from e`)
Improve stack trace when debugging errors
This PR:
=> explicit exception chaining for databricks hook

docs/orchestration/faq/config.md, package-lock.json
Add Server configuration info to the docs
Adds a configuration options section to the Server FAQ section
We've seen several questions about configuration and the correct configuration options/environment variables for Server in the community slack.  There was also a question about connecting to a pre-exisiting postgres db and I couldn't see a great place to add that info.  This section adds a link to the prefect repo config.toml and gives info about how to set a different API endpoint and how to run Prefect with a pre-exisiting postgres database. It also links to the more detailed explanation about configuration in the Core docs (which are relevant to server but not so easy to find if one is looking for something server specific.)
Ideally when we do a docs refactor, we can create one …
=> Config docs

docs/core/getting_started/installation.md
A quick formatting fix for my previous PR #3437  VuePress looks like it wants the `::: tip :::` block to have the closing marker on a new line.
Simply updates the tag around the tip.
Formatting. Here's how the previous PR looks
This PR:
=> Formatting fix for tip block

src/prefect/engine/task_runner.py, src/prefect/environments/execution/fargate/fargate_task.py
New release of mypy is causing some linting errors.
=> Fixes for new mypy release

changes/issue3306.yaml, src/prefect/tasks/postgres/postgres.py
Use explicit exception chaining for Databricks hook (more background in #3306)
Bare raising exceptions
Improve stack trace when debugging errors
This PR:
=> Bare raising exceptions on postgres task

changes/storage-log.yaml, src/prefect/environments/storage/local.py
When helping a user debug, I realized that the new import path logic for Local Storage can cause misleading errors whenever a user uses pickle-based storage + the file doesn't exist in the Agent's environment.  In particular, our storage logic first checks if the location is a known path, and if not, it tries to treat the location as an import string.  This causes the ultimate error to be a `ModuleNotFound` error, which looks confusing.
This is a minimal change to add a helpful log, but I'm open to other ideas for how to avoid the spurious import attempt!
Adds a log + traceback that explicitly says what the issue was, and re-raises the error for the Agent CLI command to capture.
To help users self debug.
This PR:
=> Informative error

src/prefect/schedules/clocks.py
This was failing for me locally on the most recent mypy build
=> Ignore new mypy type error

changes/pr3481.yaml, docs/outline.toml, src/prefect/tasks/core/operators.py, tests/core/test_task_operators.py
Helper task that retrieves a specific attribute of an upstream task's result.
-
Allows one to extract deeply nested attributes of objects instead of passing potentially large structures (such as configuration) to downstream tasks.
This PR:
=> Add GetAttr task

changes/issue3306.yaml, src/prefect/tasks/aws/__init__.py
References this issue: https://github.com/PrefectHQ/prefect/issues/3306
Adds explicit exception chaining to AWS
This PR:
=> explicit exception to AWS task

tests/client/test_client.py
=> Small client test fix

changes/issue3517.yaml, changes/pr3517.yaml, src/prefect/cli/describe.py, src/prefect/cli/get.py, tests/cli/test_describe.py, tests/cli/test_get.py
=> Fix get flow-runs and describe flow-runs CLI commands querying of removed duration field

tests/conftest.py
Always display debug logs during pytest runs
- Changes the log level for the `prefect` logger during pytest runs
Eases inspection of issues during test failures
This PR:
-- I do not think any of these are relevant, please let me know if a changes entry is required for this
=> Display debug level logs during pytest runs

docs/orchestration/server/telemetry.md
Fixes #3547. Updates the server telemetry config setting in docs.
Telemetry configuration in docs.
Incorrect setting in docs.
This PR:
=> Fix server telemetry configuration section

docs/core/concepts/tasks.md
=> Fix typo in tasks concept doc

CHANGELOG.md, changes/issue3378.yaml, changes/issue3562.yaml, changes/pr3546.yaml, changes/pr3563.yaml, changes/pr3564.yaml, changes/pr3573.yaml, docs/.vuepress/config.js
=> Cut changelog and docs in prep for release

docs/orchestration/agents/overview.md
Adds a small section to the Agent overview process docs to describe how agents are tracked. 
This PR adds a tip to the docs. 
It clarified how agents are tracked in Prefect Server and Cloud.
This PR:
=> Add a section to the Agent process docs on agent tracking

changes/pr3602.yaml, src/prefect/tasks/twitter/__init__.py
* Added from on each raised exception for `src/prefect/tasks/twitter`.
* This PR is part of Hacktoberfest.
* Changes based on https://github.com/PrefectHQ/prefect/issues/3306 for `src/prefect/tasks/twitter` .
This PR:
=> Added FROM to explicitly chain exceptions in src/prefect/tasks/twitter

changes/pr3615.yaml, src/prefect/client/client.py
Many users experience 400 status codes when issuing client requests to the Prefect API.  This is _almost_ always caused by a bad GraphQL request (schema mismatch, bad type, etc.) and would be much easier to debug if the GraphQL was displayed.  This also allows users to copy / paste the GraphQL when we support.
Captures 400 status codes and expands the error message.
Easier debugging experience.
This PR:
=> Better GraphQL error message

changes/pr3599.yaml, docs/outline.toml, setup.py, src/prefect/tasks/jupyter/__init__.py, src/prefect/tasks/jupyter/jupyter.py, tests/tasks/jupyter/__init__.py, tests/tasks/jupyter/sample_notebook.ipynb, tests/tasks/jupyter/test_jupyter.py
A prefect task for running jupyter notebooks
Added a new task `tasks.jupyter.ExecuteNotebook`
I use it myself for generating a visual report at the end of a prefect flow run. Got some positive feedback on it in the prefect slack workspace and decided to add it to prefect task library.
This PR:
=> added `tasks.jupyter.ExecuteNotebook`

changes/issue3619.yaml, src/prefect/engine/task_runner.py, tests/engine/test_task_runner.py
This PR checkpoints _all_ iterations of a looped task, not just the final one.
Closes #3619 
This PR:
=> Quick fix for checkpointing looped results

.circleci/config.yml, changes/pr3411.yaml, docs/core/getting_started/installation.md, src/prefect/engine/executors/dask.py, tests/conftest.py
Just wanted to see whether our tests would pass off-the-shelf for Python 3.9!  If so, I'll add a "feature" changelog entry, and if not I'll investigate further.
Keeps us up-to-date.
This PR:
=> Add python 3.9 circle job - let's see how this goes

changes/pr3672.yaml, src/prefect/tasks/docker/images.py, tests/tasks/docker/test_images.py
Closes #920 by adding logging to Docker tasks (PullImage and BuildImage).
Adds debug logs for PullImage and BuildImage Docker tasks.
Outputs the logs and explicitly describes what's going on during execution of the tasks.
This PR:
=> Logging docker task

tests/artifacts/test_artifacts.py, tests/client/test_client.py, tests/engine/results/test_s3_result.py, tests/environments/storage/test_base_storage.py, tests/environments/storage/test_docker_storage.py, tests/tasks/docker/test_containers.py, tests/tasks/docker/test_images.py
I have used identity check for comparison with True.
In many Tests, I noticed the usage of `==` for comparison which doesn't seem to be a very good practice. I have made use of `is` instead to do the identity check.
It improves the readability of the Code and improves the Code Quality by a small margin.
This PR:
=> Using identity check for comparison with True

changes/pr3694.yaml, src/prefect/environments/storage/docker.py, tests/environments/storage/test_docker_storage.py
Automatically quote passed dockerfile environment variables so that something like
```python
{"MY_ENV_VAR": "Hello world!"}
```
does not result in a syntax error when written to the dockerfile
- Adds quotes around relevant environment variable declarations using their repr format
- Fixes indentation for dockerfile environment variables
- Cleanup of dockerfile building, especially formatting
- Less likely to encounter an unexpected error when using env variables
- A bit clearer file formatting if you need to inspect the dockerfile
This PR:
=> Cleanup docker storage dockerfile formatting

changes/pr3795.yaml, docs/outline.toml, src/prefect/tasks/postgres/__init__.py, src/prefect/tasks/postgres/postgres.py, tests/tasks/postgres/test_postgres.py
Add a new postgres task PostgresExecuteMany.
Added a new Task subclass called PostgresExecuteMany which makes multiple queries against a Postgres database given a list of tuples.
Makes writing Tasks that push lists of rows into a db much cleaner and faster.
This PR:
=> Add postgres execute many

changes/pr3730.yaml, src/prefect/client/client.py, tests/client/test_client.py
This PR refactors the Core client to call some new API routes (newly present in both Server and Cloud APIs).  These routes were created for performance reasons, and in addition should cut the volume of API calls in half when performing mapping.
Changes the GraphQL calls being made by the Core Client - no functional difference though.
Performance and scale
This PR:
=> New API calls

src/prefect/core/task.py
Fixes small misspelling in a warning.
=> [ci skip] Fix minor misspelling

.circleci/config.yml, Dockerfile, setup.py
Attempting to fix an install issue we are seeing on the 3.6 circle jobs
=> Drop dask_cloudprovider from install in testing CI jobs and pin pip version

tests/client/test_client.py
Fix failing test.
Add missing import.
This PR:
=> Fix requests import in tests/client/test_client.py

docs/index.md
Resolves an issue where home page links were sometimes not working because the router link wasn't wrapped correctly. 
Reverses the router link wrapping for the Core and Orchestration buttons on the index page.
Resolves: #2866
cc @jcrist 
This PR:
=> Fix issue with home page links not working all the time

changes/pr3755.yaml, src/prefect/environments/storage/docker.py
Moves docker storage environment variables up in the generated Dockerfile so they can be used downstream
Allows the environment variables to be used in the commands
Closes https://github.com/PrefectHQ/prefect/issues/3640
This PR:
=> Move docker storage env declaration up

docs/core/tutorial/07-next-steps.md
Update link to the task library in the Core tutorial documentation in this section: https://docs.prefect.io/core/tutorial/07-next-steps.html#ready-made-task-library
One link! Brought to our attention via an Intercom inquiry.
So new users going through the documentation can access the Task Library conveniently!
But mostly, so I don't have to hear the complaints of Intercom people!
This PR:
=> Update Core Tutorial link to Task Library

docs/orchestration/tutorial/flow_config.md
update link in the tutorial doc
This PR:
=> fix broken link in tutorial

docs/orchestration/ui/flow-run.md
Fix the link to task-run page.
Add a hyphen to the link 
Fix the link to another page.
This PR:
=> Fix the link to the task-run page

.circleci/config.yml
=> Remove extras build arg from core image building CI job

src/prefect/serialization/environment.py, tests/serialization/test_environments.py
In testing in our dev environment I realized that new (0.14.0) agents won't be able to submit flows with `RemoteEnvironment`s configured, but it appears that many users are still (incorrectly) using these.  This patch doesn't re-introduce them, but rather ensures they can be safely deserialized into `CustomEnvironment`s.  This does not affect their functionality because environments are ultimately extracted off the flow object itself, but helps smooth the transition a little.
Adds the ability to deserialize Remote Environments into base Environment classes.
Smoother user experience / avoids unnecessary complications with 0.14.0.
This PR:
=> Compatibility Patch for new agents

changes/pr3818.yaml, src/prefect/cli/__init__.py
Echoing prefect config file as JSON to be able to parse it with jq in the terminal
This PR:
=> Echoing config as json

changes/pr3829.yaml, changes/pr3832.yaml, src/prefect/agent/kubernetes/agent.py, src/prefect/cli/execute.py, src/prefect/storage/bitbucket.py, src/prefect/utilities/git.py
Sends a log if an error is raised during the execute flow-run command so the error can also be visible in the logs and not just the state message. (cc @kingsleyb)
Updates the name of k8s infrastructure logs raised by the k8s agent for filtering purposes.
Also updates a couple random docstrings.
This PR:
=> Couple small flow run log updates

src/prefect/storage/gitlab.py
Minor change to documentation for registering a flow
This corrects the syntax for the command to register a flow
When using the existing syntax, the current command yields an error:
```bash 
$ prefect register -f flow.py
```
```
Usage: prefect register [OPTIONS] COMMAND [ARGS]...
Try 'prefect register -h' for help.
```
This PR:
=> fixes minor typo in GitLab Storage docs

changes/pr3842.yaml, src/prefect/engine/cloud/task_runner.py, tests/engine/cloud/test_cloud_task_runner.py
These can spawn large numbers of subprocesses for large flows, and are ultimately unnecessary as the flow run heartbeat is sufficient for detecting and alerting on issues.  Both Server and Cloud have been updated to account for this change.
Removes task run heartbeats
Expected performance improvement.
This PR:
=> Remove task run heartbeats

src/prefect/engine/result/__init__.py, src/prefect/engine/result/base.py, src/prefect/engine/state.py, src/prefect/serialization/result.py, src/prefect/utilities/executors.py, tests/core/test_task_map.py, tests/engine/result/test_base.py, tests/engine/test_state.py, tests/engine/test_task_runner.py, tests/serialization/test_states.py
For backwards compatibility of serialized states
=> Reintroduce Noresult

docs/orchestration/flow_config/storage.md
mention `GitLab` instead of `GitHub`  in `GitLab` section of `storage.md`
simple copy/paste docs fix
/
This PR:
=> update GitLab reference in storage.md

docs/core/getting_started/installation.md
=> Clarify docker image included dependencies in installation doc

docs/outline.toml
Some useful filters are currently not documented - adds them to our API docs
=> Add missing filters to API docs

src/prefect/utilities/context.py
=> Add resume context var to context API doc

src/prefect/tasks/asana/asana_task.py
Tiny change to make the Asana task return details
Adds a return to the Asana task so that users can access details of the new Asana ToDo
Small change but means you can use the details of the new Asana ToDo - useful if you want to notify others about the new item
I haven't added a changes file since it's a tiny update but let me know if you'd rather I add one. 
This PR:
=> make the Task Library Asana task return

changes/pr3991.yaml, docs/outline.toml, src/prefect/tasks/kubernetes/__init__.py, src/prefect/tasks/kubernetes/pod.py
Add a Kubernetes task for running exec commands inside pods to the task library
This PR:
=> Kubernetes exec task

changes/pr4015.yaml, src/prefect/agent/ecs/agent.py, src/prefect/cli/agent.py, src/prefect/run_configs/ecs.py, src/prefect/serialization/run_config.py, tests/agent/test_ecs_agent.py, tests/cli/test_agent.py, tests/run_configs/test_ecs.py, tests/serialization/test_run_configs.py
Add execution role parameter at the run config and agent level for ECS run config.
Add execution_role_arn parameter.
Grant AWS ECS agent permissions through execution role to call AWS API (for example, auth/pull images from ECR).
This PR:
=> Add task execution role

changes/4025.yaml, docs/outline.toml, src/prefect/tasks/gcp/__init__.py, src/prefect/tasks/gcp/storage.py, src/prefect/tasks/google/__init__.py
Creates a new GCS task in the task library for checking the existence of an object in a GCS bucket, optionally waiting for it to exist
This PR:
=> add task for GCSBlobExists to check for a GCS blob in a bucket

src/prefect/tasks/gcp/storage.py
Provide option to fail GCSBlobExists task if blob does not in fact exist (after wait_seconds)
I chose to go with True as default but I could see it either way.  Let me know if I should change to False
This PR:
=> optionally fail GCSBlobExists if not found

changes/pr4044.yaml, docs/outline.toml, setup.py, src/prefect/tasks/exasol/__init__.py, src/prefect/tasks/exasol/exasol.py, tests/tasks/exasol/__init__.py, tests/tasks/exasol/test_exasol.py
Adds task support for [Exasol](https://www.exasol.com/) database based on the [pyexasol](https://github.com/badoo/pyexasol) library.
This adds the four new tasks to communicate with an Exasol database:
- ExasolFetch
- ExasolExecute
- ExasolImportFromIterable
- ExasolExportToFile
Adds missing Exasol support
This PR:
=> EXASOL TASKS

setup.py
=> Drop upper bound on dask-cloudprovider versioning

src/prefect/tasks/gcp/bigquery.py
adds functionality that makes failures in the BigQueryLoadGoogleCloudStorage more digestible for users
catch, log, and raise fail for exceptions in BigQueryLoadGoogleCloudStorage task
without this, it's hard to see into failures
This PR:
=> catch, log, and raise fail for exceptions in BigQueryLoadGoogleCloudStorage task

src/prefect/engine/cache_validators.py, src/prefect/engine/task_runner.py, src/prefect/environments/execution/dask/cloud_provider.py, src/prefect/tasks/jira/jira_service_desk.py, src/prefect/tasks/jira/jira_task.py, src/prefect/tasks/notifications/pushbullet_task.py, src/prefect/utilities/notifications/__init__.py, src/prefect/utilities/notifications/jira_notification.py, tests/tasks/jira/test_jira_service_desk.py, tests/tasks/jira/test_jira_task.py, tests/tasks/notifications/test_pushbullet.py, tests/utilities/notifications/test_jira_notification.py
Delay importing some optional dependencies to speedup import time. Drops
`import prefect` time from 1.2 s to 0.34 s on my machine.
=> Speedup imports

docs/orchestration/concepts/secrets.md
Rewrites the cloud secrets doc to clarify a few points:
- How to set secrets both locally and in cloud
- How to forward local secrets from an agent to deployed flow runs
- Best practices for accessing secrets in tasks and other components of
prefect
=> Rewrite the cloud secrets doc

changes/task-fivetran-v1.yaml, src/prefect/tasks/fivetran/__init__.py, src/prefect/tasks/fivetran/fivetran.py
Initial release of the FivetranSyncTask, to manage your [Fivetran](https://fivetran.com) connector sync process.
Adds a `fivetran` folder (package) to `tasks`
Adds a FivetranSyncTask, starts and monitors a Fivetran connector job. 
This is Fivetran's first effort at integrating our APIs directly into a scheduling tool. We are very much looking to see if this helps with more complicated use cases that involved loading data through Fivetran. 
This PR:
Tests have not actually been added yet. We would love to work with the team on the best way to test this new Task.
=> Initial release of the FivetranSyncTask, to manage your Fivetran connector sync process.

changes/pr4121.yaml, src/prefect/tasks/control_flow/filter.py, tests/tasks/test_control_flow.py
This adds the ability to log the result of the FilterTask by a logging function.
Adds a additional parameter `log_func` to the `FilterTask` class.
E.g. if you pass in a list of file names and filter them, it's not clear at runtime what the result is. With this change its possible to log the result if needed.
This PR:
=> FilterTask Logging

docs/orchestration/tutorial/overview.md
I don't see a hamburger menu and the user menu to access this setting is on the top right, not top left for me.
This PR:
- [x ] adds new tests (if appropriate)
- [x ] adds a change file in the `changes/` directory (if appropriate)
=> fix create token instructions

docs/.vuepress/config.js, docs/orchestration/flow_config/docker.md, docs/orchestration/flow_config/executors.md, docs/orchestration/flow_config/overview.md, docs/orchestration/flow_config/run_configs.md
Adds a new docs page on docker images and prefect. Covers dependency requirements, different options for building images, and some recommendations on which option to choose.
=> Add new docs page on docker images

changes/pr4183.yaml, src/prefect/core/task.py, tests/core/test_task_operators.py
Finishing up https://github.com/PrefectHQ/prefect/pull/4183 (I would have pushed to the branch, but they have permissions disabled for that).
Supersedes https://github.com/PrefectHQ/prefect/pull/4183.
=> Improve indexed task naming

changes/pr4202.yaml, docs/outline.toml, src/prefect/tasks/files/__init__.py, src/prefect/tasks/files/compression.py, src/prefect/tasks/files/operations.py, tests/tasks/files/test_operations.py
This introduces two new tasks to the `files` section.
Adds the tasks `Copy` and `Remove` 
Doesn't exists...
This PR:
=> Copy and Remove

docs/core/concepts/logging.md
Add a note about logging.
Doc enhancement.
Doc enhancement.
This PR:
- [-] adds new tests (if appropriate)
- [-] adds a change file in the `changes/` directory (if appropriate)
- [-] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)
=> Add a note about pickling context

README.md, docs/core/getting_started/installation.md
Removes a stale README badge and replaces what I believe to be a misleading command with a warning box for how to interact with our docker images.  Open to other wording suggestions here.
To try and prevent users from running docker in docker and the inevitable complications that arise from that.
This PR:
=> Minor doc tweaks

docs/core/tutorial/06-parallel-execution.md
The text implies that you can just add the DaskExecutor without conditionalizing main(). The sample program does the conditionalization but it isn't evident in the web tutorial.
If you feel its too much information then just reject this PR.
This PR:
=> Wrap script in __name__=="__main__"

changes/pr4238.yaml, src/prefect/tasks/aws/s3.py, tests/tasks/aws/test_s3.py
see https://github.com/PrefectHQ/prefect/discussions/4226
This PR:
=> Add raw parameter to S3Download

src/prefect/cli/auth.py
remove reference to -r flag in create-token cli
This PR:
- [ - ] adds new tests (if appropriate)
- [ - ] adds a change file in the `changes/` directory (if appropriate)
- [ - ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)
=> remove outdated reference in CLI help

src/prefect/agent/agent.py, src/prefect/utilities/executors.py
Fix typing error in code comments
This PR:
=> Fix typing error

changes/pr4360.yaml, src/prefect/tasks/shell.py
Fixes documentation issue, which seems like it comes from the ordering of `Example` and `Raises` blocks.
Docs!
This PR:
=> Fix shell task docs

CHANGELOG.md
Minor fixup since I didn't know how to do a release properly here
=> Update changelog to have version number headers instead of dates

changes/pr4418.yaml, docs/orchestration/flow_config/storage.md, docs/outline.toml, requirements.txt, src/prefect/serialization/storage.py, src/prefect/storage/__init__.py, src/prefect/storage/git.py, src/prefect/utilities/git.py, tests/storage/test_git_storage.py, tests/utilities/test_git.py
This PR adds a generalized git storage class to Prefect.
- Adds a new `Git` storage class which uses a pure python git implemenation
- Adds a new `TemporaryGitRepo` utility, allowing us to temporary clone and cleanup a repository
These changes will
- Allow users to use Deploy Tokens and other ssh based git auth if they wish
- Allow us to become less reliant on third party libraries
- Allow users to pull info from non-python files at run time (python modules are another beast)
These changes address
- https://github.com/PrefectHQ/prefect/issues/4376
- https://github.com/PrefectHQ/prefect/issues/4328
These changes WILL NOT
- Allow users to import Python modules from the repo when cloning
```python
import prefect
from prefect.storage import Git
storage = …
```
=> Add full repo storage

requirements.txt, setup.py, src/prefect/utilities/git.py, tests/storage/test_git_storage.py, tests/utilities/test_git.py
This PR moves `dulwich` to an orchestration extra associated with "git".
This PR:
=> Move dulwich to extras

docs/orchestration/tutorial/overview.md
Updates API Key guidance
Removes login with personal API key and advises how to store it instead in the set up section of the tutorial in the docs. 
Key to ease of use and getting started
This PR:
=> Update api key guidance

docs/api/0.13.19/utilities/edges.md
Small typo fixed in the name of a function
This PR:
=> Fixed #4488 - Mistake in flatten() example

changes/pr4470.yaml, docs/orchestration/concepts/flows.md, src/prefect/__init__.py, src/prefect/hello_world.py, tests/test_hello_world.py
This adds a very basic hello world flow to the Prefect module itself. I use a hello world flow _all the time_ to test things and I think it's super reasonable to provide one immediately to the user. I think this is the _only_ example we should inline in this way. This allows onboarding to look like:
```
❯ prefect register --project default --module prefect.hello_world
Collecting flows...
Processing 'prefect.hello_world':
Building `Module` storage...
Registering 'hello-world'... Done
└── ID: bfc72a71-8732-4c74-a119-e4a3b1309f00
└── Version: 5
======================== 1 registered ========================
❯ prefect run --module prefect.hello_world -p name \"Marvin\" --watch
Looking up flow... Done
Creating run for flow 'hello-world'... Done
└── Name: mauve-piculet
└── UUID: …
```
=> Add `hello world` flow to prefect module for very fast onboarding

docs/core/idioms/conditional.md, docs/core/idioms/resource-manager.md, docs/core/tutorial/04-handling-failure.md, docs/orchestration/recipes/k8s_docker_sidecar.md
Update some task library links which are broken
Closes #4477
This PR:
=> update broken task library links

docs/orchestration/server/deploy-local.md
Update to reflect small changes to UI button placement
Small updates to the server page 
Updates to reflect new plan names and the position of the backend switcher
So users can find the backend
This PR:
=> Reflect UI changes

changes/pr4547.yaml, src/prefect/agent/agent.py, tests/agent/test_agent.py
If the agent cannot connect to Cloud, there are no logs indicating what it is doing during startup. This PR adds some basic logs and wraps the exception to explain the failure case.
This may be irrelevant with API Key changes.. ?
- Adds debug level logs to `_setup_api_connection` during auth token verification
Allows easier debugging of agent startup failure
Closes https://github.com/PrefectHQ/prefect/issues/4546
This PR:
=> Add debug logs during agent auth verification

docs/orchestration/agents/overview.md
Add info about agent config id
Adds information about agent configs and automations and  where to add
Helps users understand how and where to use agent configs and notifications
This PR:
=> Add agent config info

docs/.vuepress/config.js, docs/orchestration/concepts/automations.md
Add automation action message configuration options
Updates automations docs
Helps users understand how to customize automation notifications
This PR:
=> Add action message configuration options

docs/api/0.13.19/tasks/great_expectations.md, src/prefect/tasks/great_expectations/__init__.py
fix broken link to Great Expectations docs
The link
Broken links are suboptimal.
This PR:
- [n/a ] adds new tests (if appropriate)
- [n/a] adds a change file in the `changes/` directory (if appropriate)
=> fix broken link to Great Expectations docs

CHANGELOG.md, changes/pr4499.yaml, changes/pr4584.yaml, changes/pr4587.yaml, changes/pr4593.yaml, changes/pr4602.yaml, changes/pr4605.yaml, docs/.vuepress/config.js
- Add interface for backend key-value metadata store - [#4499](https://github.com/PrefectHQ/prefect/pull/4499)
- Keep intermediate docker layers when using Docker Storage to improve caching - [#4584](https://github.com/PrefectHQ/prefect/pull/4584)
- Fix possible race condition in `LocalResult` directory creation - [#4587](https://github.com/PrefectHQ/prefect/pull/4587)
- Use absolute paths when registering flows in `prefect register` - [#4593](https://github.com/PrefectHQ/prefect/pull/4593)
- Propagate storage labels (e.g. hostname label on `Local` storage) when registering flows with `prefect register` - [#4593](https://github.com/PrefectHQ/prefect/pull/4593)
- Fix small-flow parallelism issues with multiprocess `LocalDaskExecutor` - …
=> Release 0.14.21

.circleci/config.yml
I tried to install typeshed packages in #4638 but could not get it to work....
=> Pin mypy to 0.8 to fix typeshed errors

requirements.txt, src/prefect/backend/flow.py
This just cleans up some little details for the `FlowView` class before release. See commits for details. No behavior is changed.
=> Cleanup `FlowView`

src/prefect/backend/flow_run.py, tests/backend/test_flow_run.py
Fixes agent query compatibility with Server and does not show agent warnings if the flow is in a submitted state
=> Some agent warning fixups

src/prefect/backend/flow_run.py, src/prefect/client/client.py, tests/client/test_client.py
- Fix current tenant url retrieval -- this was using old API token logic
- Fix bug where the wrong agent information is displayed in warning -- the last agent queried was being referenced instead of the relevant healthy/unhealthy agent
=> Some 0.15.0 bug fixes

changes/pr4721.yaml, docs/orchestration/rbac/overview.md
This PR documents helper queries for role based access controls.
Adds documentation for querying role and membership information in the context of RBAC.
Docs!
This PR:
=> Add rbac helper queries to docs

docs/orchestration/server/overview.md
Fixed typo
Fixed typo
Fixed typo
=> Fixed typo

CHANGELOG.md, changes/pr4721.yaml, changes/pr4744.yaml, changes/pr4751.yaml, changes/pr4758.yaml, changes/pr4759.yaml, docs/.vuepress/config.js
- Add documentation for querying role and membership info - [#4721](https://github.com/PrefectHQ/prefect/pull/4721)
- Checkpoint task results when `SUCCESS` is raised - [#4744](https://github.com/PrefectHQ/prefect/pull/4744)
- Fix loading of `PREFECT__CLOUD__API_KEY` environment variable when starting agents - [#4751](https://github.com/PrefectHQ/prefect/pull/4751)
- Fix bug where the tenant could not be inferred during flow runs while using token auth - [#4758](https://github.com/PrefectHQ/prefect/pull/4758)
- Fix bug where an agent using token auth could clear the tenant from disk - [#4759](https://github.com/PrefectHQ/prefect/pull/4759)
=> Release 0.15.1

docs/core/concepts/schedules.md
the cron link in this section of the docs seems to be broken  #4660
Fixes the broken link
It is important as it fixes 404 link
This PR:
=> Fix  broken cron schedule link in Schedule Docs

src/prefect/utilities/executors.py
Fix leaving defunct heartbeat processes in system process list.
* `run_with_heartbeat` waits on the heartbeat process after its kill
* Long running agents can leave hundreds of defunct heartbeat processes in the system process list.
This PR:
=> Fix defunct heartbeat process

CHANGELOG.md, changes/issue4770.yaml, changes/issue4773.yaml, changes/pr4752.yaml, changes/pr4767.yaml, changes/pr4774.yaml, tests/cli/test_build_register.py
- Adds tests for #4752 
- Adds changes entry for #4656 
- Adds changes entry for #4733
=> Minor fixups before 0.15.2

CHANGELOG.md, changes/ge_task.yaml, changes/pr4801.yaml, changes/pr4802.yaml, docs/.vuepress/config.js
- Add new `evaluation_parameters` parameter to `RunGreatExpectationsValidation` task - [#4798](https://github.com/PrefectHQ/prefect/pull/4798)
- Fix `create_flow_run` compatibility with auth tokens - [#4801](https://github.com/PrefectHQ/prefect/pull/4801)
- Fix auto-quoting for strings that begin with numeric characters - [#4802](https://github.com/PrefectHQ/prefect/pull/4802)
- [Michal Zawadzki](https://github.com/trymzet)
=> Release 0.15.3

src/prefect/engine/cloud/task_runner.py
Just a small typo in a doc string
Fixes the doc string
Not really
This PR:
=> Looks like it is 10 minutes not 1

src/prefect/utilities/notifications/notifications.py
Update the docstring to reflect that the Flow class requires a 'name' argument.
Update the docstring in the notifications.py file to show the correct use of the example.
The code as exists does not run successfully.
This PR:
- [ X] adds new tests (if appropriate).
- [ X] adds a change file in the `changes/` directory (if appropriate)
- [ X] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)
=> The Flow class requires a name

docs/generate_docs.py, package.json
Resolves #4846 
Adds a newline to certain class signatures to make sure the markdown parser renders them correctly. Also fixes an issue where subheadings were interpolating invalid anchors (beginning with `-` characters).
Also fixes an issue where empty anchor tags were causing the page to scroll to top when passed `#`
Before:
After:
This PR:
=> Fix issues with certain class signatures being displayed incorrectly

src/prefect/client/client.py
Fixes #4852 by putting the rate limiting logic in the correct place within `_send_request`.
=> Refactor rate limiting code to the correct method call

src/prefect/tasks/gcp/secretmanager.py, src/prefect/tasks/gcp/storage.py
fix broken links and spelling in GCP docs
fix broken links and spelling in GCP docs
Improves user experience
This PR:
- [ na] adds new tests (if appropriate)
- [ na] adds a change file in the `changes/` directory (if appropriate)
- [na ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)
=> fix broken links and spelling in GCP docs

changes/pr4887.yaml, docs/core/about_prefect/thinking-prefectly.md
Fix broken link to local server/UI deployment docs
Changes a link in docs/core/about_prefect/thinking-prefectly.md
Broken link led to a 404
This PR:
=> Fix broken link to local server/UI deployment docs

docs/core/advanced_tutorials/task-guide.md
Updated import statement in documentation.
Resolves #4889
* Updates the import statement in one of the examples on the task guide.
* When copying the example it didn't work out of the box for me. After looking through the source I realised the problem, wanted to save others the trouble.
This PR:
=> updates import statement for unmapped in task guide

changes/pr4900.yaml, src/prefect/utilities/logging.py
Updates the log size batching limits to match reality - this will prevent us from attempting to send batches that the backend won't accept, ensuring against log loss (ha).
This PR:
=> Update log limit to match backend logic

src/prefect/storage/gitlab.py
This PR, I think, fixes a typo in #4828 
Ping @matmiad @madkinsz
=> Gitlab storage typo

changes/pr4724.yaml, docs/orchestration/concepts/api_keys.md
In the process of reviewing this issue, I saw that there were some unneeded empty lines in the code block. Removed said lines.
Readability of the /docs/orchestration/concepts/api_keys.md file, under the Using API Keys section, within the code block.
Cleanup of sloppy example text that would likely be replicated by an end user unnecessarily.
This PR:
=> Issue 4724

docs/api/0.12.6/utilities/edges.md, docs/api/0.13.19/utilities/edges.md, docs/api/0.14.22/utilities/edges.md, src/prefect/utilities/edges.py
changed some minor doc errors in the code
This PR:
- [v] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)
=> Fix Edges docs

docs/orchestration/agents/kubernetes.md, docs/orchestration/concepts/api_keys.md, docs/orchestration/flow-runs/concurrency-limits.md, docs/orchestration/server/overview.md
Clean up some references to API keys in docs
This PR:
=> update some references to tokens

src/prefect/engine/serializers.py
=> fix mismatched words in docstring

docs/core/concepts/mapping.md, docs/core/concepts/persistence.md, docs/orchestration/execution/storage_options.md
There were a few typos and wrong hyperlinks in the docs.
This PR will fix the typos and the wrong hyperlink.
The wrong hyperlink redirects the user to the incorrect section on the page.
Fixing typos is self-explanatory.
This PR:
=> Fix typos and hyperlinks

docs/orchestration/getting-started/set-up.md
=> Fix link to Prefect Server docs

changes/pr4955.yaml, docs/orchestration/execution/storage_options.md, src/prefect/engine/results/azure_result.py, src/prefect/serialization/storage.py, src/prefect/storage/azure.py, tests/engine/results/test_azure_result.py, tests/serialization/test_storage.py, tests/storage/test_azure_storage.py, tests/tasks/jupyter/sample_notebook.ipynb
Set a connection string as a secret or env variable `AZURE_STORAGE_CONNECTION_STRING` for Azure storage. 
`AzureStorage(connection_string=..)` to `AzureStorage(connection_string_secret=<secret_name>)`.
Closes #4941 and #4447
This PR:
=> Update Azure storage connection string

changes/pr5022.yaml, docs/orchestration/server/deploy-local.md
The addition of --expose flag in Server documentation.
=> Adding documentation to PR #4821

docs/api/0.14.22/storage.md, docs/core/tutorial/07-next-steps.md
Some small requested doc fixups
addresses #5021
addresses #5010
=> Fix broken doc link

docs/core/getting_started/install.md, docs/orchestration/README.md, docs/orchestration/getting-started/basic-core-flow.md, docs/orchestration/getting-started/quick-start.md, docs/orchestration/getting-started/registering-and-running-a-flow.md, docs/orchestration/getting-started/set-up.md
Docs changes directing first time users to Prefect Cloud, and providing more clear differentiation between optimal Prefect Cloud and Prefect Core server use cases.
Edits to the following source documents:
docs/orchestration/README.md
docs/orchestration/getting-started/basic-core-flow.md
docs/orchestration/getting-started/quick-start.md
docs/orchestration/getting-started/registering-and-running-a-flow.md
docs/orchestration/getting-started/set-up.md
Affects the following published pages:
https://docs.prefect.io/orchestration/
https://docs.prefect.io/orchestration/getting-started/quick-start.html
https://docs.prefect.io/orchestration/getting-started/basic-core-flow.html
https://docs.prefect.io/orchestration/getting-started/set-up.html …
=> Docs: Orchestration orchestration cloud examples

docs/core/PINs/PIN-05-Combining-Tasks.md
Fix formatting in documentation code.
Not really important, just the code being misaligned, but trivial issue, probably really low priority :+1: 
This PR:
Thanks!
=> Fix formatting

docs/orchestration/server/architecture.md
Hi!
Fixed a typo found while browsing the docs, and clicked "Edit this page"! 
`inteface` -> `interface`
`inteface` -> `interface`
This PR:
=> fix: typo in architecture docs

CHANGELOG.md, changes/pr4901.yaml, changes/pr4980.yaml, changes/pr4989.yml, changes/pr5066.yaml, changes/pr5077.yml, changes/pr5084.yaml, changes/pr5085.yml, changes/pr5094.yaml, changes/pr5103.yaml, changes/pr5116.yaml, changes/pr5117.yaml, docs/.vuepress/config.js
- Add support for rich iCal style scheduling via RRules - [#4901](https://github.com/PrefectHQ/prefect/pull/4901)
- Add Google Cloud Vertex agent and run configuration - [#4989](https://github.com/PrefectHQ/prefect/pull/4989)
- Allow `Azure` flow storage to overwrite existing blobs - [#5103](https://github.com/PrefectHQ/prefect/pull/5103)
- Provide option to specify a dockerignore when using Docker storage - [#4980](https://github.com/PrefectHQ/prefect/pull/4980)
- Add keep-alive connections for kubernetes client API connections - [#5066](https://github.com/PrefectHQ/prefect/pull/5066)
- Add `idempotency_key` to `create_flow_run` task - [#5125](https://github.com/PrefectHQ/prefect/pull/5125)
- Add `raise_final_state` to `wait_for_flow_run` task to reflect child flow run state - …
=> Release 0.15.8

src/prefect/agent/docker/agent.py
Documentation for resolving the issue at https://github.com/PrefectHQ/prefect/issues/4963
=> Document connecting to local server using `--network`

docs/orchestration/README.md
Remove outdated Cloud tier benefits from docs.
Removes outdated information from https://docs.prefect.io/orchestration/
Incorrect number or users and task runs.
This PR:
=> Remove outdated cloud tier information.

src/prefect/run_configs/ecs.py
document environment var overwrite in ECSRun; see [discussion on slack](https://prefect-community.slack.com/archives/CL09KU1K7/p1637703686216800?thread_ts=1637627432.120600&cid=CL09KU1K7) 
Just some docs 😄 
Cause docs are important 💯 
This PR:
=> document environment var overwrite in ECSRun

docs/concepts/settings.md
Seems it is just a typo
This PR:
=> seems it is missed prefix

docs/.vuepress/styles/index.styl, docs/generate_docs.py, docs/outline.toml
Changes verbiage of partnership integration to verified tasks since not all verified tasks will be the result of an official partnership.
This PR:
- ~~[ ] adds new tests (if appropriate)~~
- ~~[ ] adds a change file in the `changes/` directory (if appropriate)~~
=> Changes partnership integration callout to verified task callout

setup.py
Pin `mistune` to < 2 to avoid breaking changes. The breaking changes affect `nbconvert` which is a `jupyter` extra.
Gets unit tests passing for the task library.
This PR:
- ~~[ ] adds new tests (if appropriate)~~
- ~~[ ] adds a change file in the `changes/` directory (if appropriate)~~
- ~~[ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)~~
=> Pins version of mistune to prevent version conflict

docs/core/concepts/tasks.md
propogate -> propagate
This PR:
=> typo fix propogate -> propagate

changes/pr5232.yaml, docs/orchestration/agents/local.md, docs/orchestration/concepts/flows.md
Adding a section to clarify that local agents are not intended to be used as a queue.
=> Multiple local agents with the same label

docs/orchestration/server/deploy-local.md
Updates instructions for where to find the **Connecting your infrastructure** section of the UI in the docs. 
Resolves https://github.com/PrefectHQ/prefect/issues/5251
- Updates the server section of the docs in response to https://github.com/PrefectHQ/prefect/issues/5251
Helps users find the right section of the UI. 
This PR:
=> Update Server Getting Started docs

docs/orchestration/flow_config/overview.md
Fixes broken link from Flow Configuration overview to Flow Runs overview.
https://docs.prefect.io/orchestration/flow_config/overview.html#next-steps
to 
https://docs.prefect.io/orchestration/flow-runs/overview.html
Fixes 404
This PR:
=> Fix broken link to flow runs documentation.

docs/orchestration/server/overview.md
This PR fixes the typo in server overview docs as mentioned in #5222 
Change `Ultimatey` to `Ultimately`
Closes #5222 
This PR:
~- [ ] adds new tests (if appropriate)~
~- [ ] adds a change file in the `changes/` directory (if appropriate)~
~- [ ] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)~
=> docs: fix typo in server overview

docs/core/concepts/persistence.md, docs/core/concepts/schedules.md, docs/core/tutorial/07-next-steps.md
Note this should be merged into 1.0rc branch
Fixes broken internal links in documentation.
- docs/core/concepts/persistence.md
- docs/core/concepts/schedules.md
- docs/core/tutorial/07-next-steps.md
Fixes 404
This PR:
=> Docs: Fix broken links in 1.0rc

src/prefect/tasks/snowflake/snowflake.py, tests/tasks/snowflake/test_snowflake.py
Adds application identifier to both Snowflake tasks so that task usage can be observed via the Snowflake Partner Network Portal.
Adds application identifier with format `Prefect_{task_name}` to Snowflake tasks 
Necessary step for joining the Snowflake Partner Network
This PR:
=> Adds application identifier to Snowflake connection in Snowflake tasks

changes/pr_5260.yaml, src/prefect/tasks/airbyte/airbyte.py, tests/tasks/airbyte/test_airbyte.py
=> Make `AirbyteConnectionTask`'s optional params optional

changes/pr5313.yaml, src/prefect/cli/docker-compose.yml
Upgrades hasura to `2.0.9` matching the upgrade in [prefect server ](https://github.com/PrefectHQ/server/pull/328)
Upgrades hasura from `1.3.3` -> `2.0.9`
Prefect was a major version behind on Hasura and this helps keep up to date.
This PR:
=> upgrade hasura version for prefect server

CHANGELOG.md, changes/pr5016.yml, changes/pr5173.yaml, changes/pr5231.yaml, changes/pr5256.yaml, changes/pr5265.yaml, changes/pr5273.yaml, changes/pr5276.yaml, changes/pr5278.yaml, changes/pr5280.yaml, changes/pr5292.yaml, changes/pr5303.yaml, changes/pr5310.yaml, changes/pr5313.yaml, changes/pr5314.yaml, changes/pr_5260.yaml, docs/.vuepress/config.js
- Allow passing timedeltas to `create_flow_run` to schedule subflows at runtime - [#5303](https://github.com/PrefectHQ/prefect/pull/5303)
- Upgrade Prefect Server Hasura image to 2.0.9 - [#5173](https://github.com/PrefectHQ/prefect/pull/5313)
- Allow client retries on failed requests to Prefect Server - [#5292](https://github.com/PrefectHQ/prefect/pull/5292)
- Add authentication parameter for Snowflake query tasks - [#5173](https://github.com/PrefectHQ/prefect/pull/5173)
- Add Mixpanel tasks - [#5276](https://github.com/PrefectHQ/prefect/pull/5276)
- Add Zendesk Tickets Incremental Export task - [#5278](https://github.com/PrefectHQ/prefect/pull/5278)
- Add Cube.js Query task - [#5280](https://github.com/PrefectHQ/prefect/pull/5280)
- Add Monte Carlo lineage tasks - …
=> Release 0.15.12

docs/orchestration/getting-started/set-up.md
=> Fixed the typo

CHANGELOG.md, changes/pr5316.yaml, changes/pr5335.yml, changes/pr5355.yaml, changes/pr5362.yml
- Ensure that maximum log payload sizes are not exceeded - [#5316](https://github.com/PrefectHQ/prefect/pull/5316)
- Upgrade Hasura to v2.1.1 which includes support for Apple M1 - [#5335](https://github.com/PrefectHQ/prefect/pull/5335)
- Fix bug where logout was required before logging in with a new key if the new key does not have access to the old tenant - [#5355](https://github.com/PrefectHQ/prefect/pull/5355)
- Fix bug where the Airbyte sync job failure would not be reflected in the task state - [#5362](https://github.com/PrefectHQ/prefect/pull/5362)
=> Release 0.15.13

docs/core/concepts/schedules.md, docs/core/task_library/contributing.md, docs/orchestration/concepts/services.md
Minor fixes including:
- Remove broken tweet display, which seems no longer relevant due to current display context of the tweet (and is not rendering anyway) in [Contributing](https://docs.prefect.io/core/task_library/contributing.html)
- Remove unused import from [Date clocks](https://docs.prefect.io/core/concepts/schedules.html#date-clocks) example.
- Clarify running state in [Lazarus](https://docs.prefect.io/orchestration/concepts/services.html#how-does-it-work-3) docs.
See above.
This PR:
=> Docs: Misc minor doc fixes.

src/prefect/client/client.py, src/prefect/tasks/core/operators.py, src/prefect/tasks/spacy/spacy_tasks.py, tests/core/test_flow.py, tests/engine/cloud/test_cloud_flow_runner.py
Fixes CI failures due to style changes in the latest black version
=> Format with latest black version

.github/ISSUE_TEMPLATE/config.yml, README.md, changes/pr5396.yaml, docs/.vuepress/config.js, docs/README.md, docs/api/0.13.19/README.md, docs/api/0.14.22/README.md, docs/core/community.md, docs/core/development/overview.md, docs/index.md
Adding Discourse links to the READMEs and community pages.
=> Adding Discourse links

README.md
Copy-paste mistake when updating URLs in the docs.
=> Fix a broken docs URL in the README.md

docs/orchestration/flow-runs/setting-states.md
Broken link in docs
Fix broken link: 
`/orchestration/ui/flowrun` >>> `/orchestration/ui/flow-run`
This PR:
=> Fix broken link

RELEASE-NOTES.md
=> Add release notes for 2.0a11

changes/issue5438.yaml, docs/outline.toml, src/prefect/tasks/databricks/__init__.py, src/prefect/tasks/databricks/databricks_get_job_id.py, src/prefect/tasks/databricks/databricks_hook.py, tests/tasks/databricks/test_databricks.py
Creates a new task in databricks_get_job_id.py to fetch the job_id given a job name. This makes it lot easier in developing databricks related flows that all relies on knowing the job_id beforehand.
- Updates DatabricksHook with new api endpoint for listing jobs
- New task to fetch job ids given a job name
- Associated tests for the new task
Simplifies flows that invoke databricks as suggested by dbx documentation here: https://dbx.readthedocs.io/en/latest/orchestration.html
Solves the issue #5438 
This PR:
=> Adds new databricks get job ID task

changes/issue4084.yaml, src/prefect/client/client.py, src/prefect/tasks/core/operators.py, src/prefect/tasks/spacy/spacy_tasks.py, src/prefect/utilities/executors.py, tests/core/test_flow.py, tests/core/test_task_map.py, tests/engine/cloud/test_cloud_flow_runner.py
Add support for flatten() when processing results that contain no flattenable value.
This PR:
=> Add support for flatten() when processing results that contain no flattenable value

docs/index.md
Add a notice about 1.0 release and link to upgrade to 1.0 guide.
This PR:
=> Docs: Add 1.0 blub with link to upgrade guide

changes/pr5515.yaml, docs/orchestration/agents/kubernetes.md
Fix the `conda install` command for the Kubernetes python client.
Resolves https://github.com/PrefectHQ/prefect/issues/5424
Not sure if you need the change file in the `changes/` directory, but I created one anyway.
@madkinsz please let me know if any dependencies should be added/updated in the [conda-forge feedstock](https://github.com/conda-forge/prefect-feedstock/blob/master/recipe/meta.yaml).
Corrects the name of the Kubernetes python client conda package in the "[Kubernetes Agent](https://github.com/PrefectHQ/prefect/blame/master/docs/orchestration/agents/kubernetes.md#L28)" documentation.
Helps ensure that conda users install the correct Kubernetes python client package.
This PR:
~- [ ] adds new tests (if appropriate)~
~- [ ] updates docstrings for any new functions or function …
=> Fix conda install command with correct python-kubernetes package

setup.py
=> Update `python_requires` in setup to 3.7

src/prefect/tasks/dbt/dbt_cloud_utils.py, tests/executors/test_executors.py, tests/tasks/dbt/test_dbt.py
Adds user-agent header to dbt Cloud requests to track usage of dbt Cloud tasks. This is an ask from dbt as part of Prefect's partnership with dbt.
This PR:
=> Adds user-agent header to dbt Cloud requests

dev-requirements.txt, setup.py, tests/tasks/jupyter/sample_notebook.ipynb
Fixes the CI breaking maybe
python3 -> python
CI is breaking
This PR:
=> Maybe fix CI

changes/pr5632.yaml, setup.py, src/prefect/tasks/azureml/__init__.py
azureml has many dependency issues, and no need to install for use with blob storage or cosmos db. Also, https://docs.prefect.io/api/latest/#task-library lists them separately
Separates out the azureml-sdk into its own key
Someone encountered this https://prefect-community.slack.com/archives/C014Z8DPDSR/p1648828182848839 and also me too
This PR:
=> Separate azureml requirements

docs/orchestration/concepts/automations.md
Clarify Flow SLA Failure automation behavior applies to runs that have not entered a Submitted or Running state.
Clarifies behavior. Closes https://github.com/PrefectHQ/cloud/issues/3939
This PR:
=> Clarify automation behavior

changes/pr5643.yaml, src/prefect/client/client.py
Fixes a bug where logging in for the first time would throw an error.
See bug report here https://github.com/PrefectHQ/cloud/issues/3951
When first logging in, several attempts are made to find a tenant id. Several of these checks can return `''` instead of `None`, which leads to the error message detailed in the bug report.
https://github.com/PrefectHQ/prefect/blob/master/src/prefect/client/client.py#L139
This PR:
=> Handle empty string as tenant id

CHANGELOG.md, changes/pr4356.yaml, changes/pr5518.yaml, changes/pr5541.yaml, changes/pr5554.yaml, changes/pr5588.yaml, changes/pr5612.yaml, changes/pr5618.yaml, changes/pr5631.yaml, changes/pr5632.yaml, changes/pr5634.yaml, changes/pr5643.yaml, docs/.vuepress/config.js
- Add `retry_on` to allow tasks to retry on a subset of exception types - [#5634](https://github.com/PrefectHQ/prefect/pull/5634)
- Add ability to add capacity provider for ECS flow runs - [#4356](https://github.com/PrefectHQ/prefect/issues/4356)
- Add support for default values to `DateTimeParameter` - [#5519](https://github.com/PrefectHQ/prefect/pull/5519)
- Calling `flow.run` within a flow definition context will raise a `RuntimeError` - [#5588](https://github.com/PrefectHQ/prefect/pull/5588)
- Add support for service principal and managed identities for storage on Azure - [#5612](https://github.com/PrefectHQ/prefect/pull/5612)
- The `azureml-sdk` dependency has been moved from the `azure` extra into `azureml` - [#5632](https://github.com/PrefectHQ/prefect/pull/5632)
- Add task to …
=> Release 1.2.0

changes/pr5615.yml, requirements.txt, src/prefect/cli/__init__.py
click commands can be wrapped in a repl sub-command where we can start a repl to access all other commands. This should persist session and also supports auto-complete along with storing history.
* Add [click-repl](https://github.com/click-contrib/click-repl) as requirement
* Add repl command to start repl
https://user-images.githubusercontent.com/3972343/160831507-2d24edb1-7044-4476-af0b-e45e92dc0a9c.mp4
```
prefect repl
Welcome to Prefect REPL
version : 1.1.0+10.g7d958a5e7.dirty
> get projects
NAME    FLOW COUNT    AGE             DESCRIPTION
Sample  1             45 minutes ago
> get flows -p Sample
NAME         VERSION    AGE             ID                                    PROJECT NAME
Hello world  1          45 minutes ago  1aded56d-c6c2-4939-a247-cdc59d23de47  Sample
> run --id …
```
=> Add REPL mode for cli.

changes/pr5672.yaml, docs/outline.toml, src/prefect/tasks/hightouch/__init__.py, src/prefect/tasks/hightouch/hightouch_tasks.py, src/prefect/tasks/hightouch/hightouch_utils.py, tests/tasks/hightouch/test_hightouch_tasks.py
This PR introduces the ability trigger sync runs on Hightouch.
Now users can trigger Hightouch Syncs with a native Prefect task.
This PR:
=> Add hightouch tasks

docs/tutorials/testing.md
Following up from [this slack thread](https://prefect-community.slack.com/archives/CL09KU1K7/p1650416317687919), this should explain how to unit test tasks, in addition to flows.
Open question: should I explain more why someone may want to use `.fn()`, or is it pretty clear?
Adds a bit more to the Testing section.
To help folks know the options for their unit tests. It took me a while to realize that you didn't need a `flow` for unit tests. They were adding some runtime to our test suite, when the functions themselves were pretty simple!
This PR:
=> Docs: Testing tasks as well as flows

docs/generate_docs.py, src/prefect/cli/server.py, src/prefect/storage/bitbucket.py, src/prefect/utilities/storage.py
=> Missing `f` prefix on f-strings fix

docs/orchestration/rbac/overview.md
Adding information to rbac/overview.md doc about Enterprise only feature Audit Logs.
Adding information to rbac/overview.md doc.
Adding documentation.
This PR:
=> Adding information about Audit Logs

CHANGELOG.md, changes/issue5076.yaml, changes/issue5669.yaml, changes/pr0000.yaml, changes/pr5615.yml, changes/pr5637.yaml, changes/pr5657.yaml, changes/pr5662.yaml, changes/pr5672.yaml, changes/pr5674.yml, changes/pr5705.yml, changes/pr5716.yaml, docs/.vuepress/config.js
- Add ability to set a `max_duration` timeout in `wait_for_flow_run` task - [#5669](https://github.com/PrefectHQ/prefect/issues/5669)
- Add pipe support for `EdgeAnnotation` types, e.g. `map` - [#5674](https://github.com/PrefectHQ/prefect/pull/5674)
- Add 'gs' as a valid filesystem schema for reading specifications - [#5705](https://github.com/PrefectHQ/prefect/pull/5705)
- Add REPL mode for CLI - [#5615](https://github.com/PrefectHQ/prefect/pull/5615)
- Fix bug where settings the backend to "server" would not prevent client from requesting secrets from the API - [#5637](https://github.com/PrefectHQ/prefect/pull/5637)
- Fix docker-in-docker issue in `DockerAgent` on Windows - [#5657](https://github.com/PrefectHQ/prefect/pull/5657)
- Fix graphviz syntax error when visualizing a flow with a …
=> Release 1.2.1

src/prefect/utilities/tasks.py
`retries` I think is outdated; it's now named `max_retries` and add retry_delay because it's required if max_retries > 0
Update docstring example 
Reflects latest version
This PR:
=> Update tasks max_retries docstring example

docs/core/faq.md
Removes outdated discussion of Docker dependencies for Prefect Cloud.
Preview: [FAQ](https://deploy-preview-5799--prefect-docs.netlify.app/core/faq.html#what-are-the-requirements-of-prefect-cloud)
https://docs.prefect.io/core/faq.html#what-are-the-requirements-of-prefect-cloud
Old information was incorrect and confusing to users.
This PR:
=> Docs: Remove discussion of Docker dependencies in FAQ

docs/concepts/task-runners.md
Fixes a minor typo in v2 documentation that leads to an import error.
Minor Prefect v2 documentation update
I'm trying out Prefect v2 and tried copy & pasting this example. Took me a minute to figure out what was up :)
This PR:
=> Fix documentation typo

changes/pr5794.yaml, src/prefect/tasks/airbyte/airbyte.py
Configure logging output for `AirbyteConnectionTask`
This setup is equivalent to that of the `ShellTask` (for consistency). Logging output of the responses are modified. 
Depending on what you sync, Airbyte might log a lot of information. On each _job_status, logging of the sync is retrieved as well -> causing a lot of output.
This PR:
=> feat(AirbyteConnectionTask): configure logging output

CHANGELOG.md, changes/pr5724.yaml, changes/pr5728.yaml, changes/pr5740.yaml, changes/pr5748.yaml, changes/pr5770.yaml, changes/pr5778.yaml, changes/pr5785.yaml, changes/pr5789.yaml, changes/pr5794.yaml, changes/pr5795.yaml, changes/pr5797.yaml, changes/pr5804.yaml, changes/pr5825.yaml, docs/.vuepress/config.js
- Add inference of Docker network mode for "host" and "none" networks - [#5748](https://github.com/PrefectHQ/prefect/pull/5748)
- Add Python 3.10 support - [#5770](https://github.com/PrefectHQ/prefect/pull/5770)
- Raise error on task initialiation when positional-only parameters are present in function signature - [#5789](https://github.com/PrefectHQ/prefect/pull/5789)
- Add flag to prevent printing ASCII welcome message [5619](https://github.com/PrefectHQ/prefect/issues/5619)
- Allow the Prefect client to retry connections for HTTP targets - [#5825](https://github.com/PrefectHQ/prefect/pull/5825)
- Adds SFTP server tasks `SftpUpload` and `SftpDownload` [#1234](https://github.com/PrefectHQ/prefect/pull/5740)
- Configure logging output for `AirbyteConnectionTask` - …
=> Release 1.2.2

docs/concepts/flows.md
I added a missing colon to a code example in docs/concepts/flow.md 
I added a missing colon to a code example in docs/concepts/flow.md 
Not super important in the big scheme of things. 
This PR:
- [ NA] adds new tests (if appropriate)
- [ NA] adds a change file in the `changes/` directory (if appropriate)
- [ NA] updates docstrings for any new functions or function arguments, including `docs/outline.toml` for API reference docs (if appropriate)
=> added a missing colon to a code example in docs/concepts/flow.md

docs/concepts/tasks.md
=> docs: Fix small typo

changes/pr5921.yaml, docs/outline.toml, setup.py, src/prefect/tasks/azure/__init__.py, src/prefect/tasks/azure/datafactory.py, tests/tasks/azure/test_datafactory.py
Adds datafactory tasks.
This PR:
=> Add datafactory tasks

changes/issue5971.yaml, src/prefect/tasks/sftp/__init__.py
Fixed imports in [sftp-task](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/sftp/__init__.py)
Closes #5971
=> Fixed sftp-task imports

README.md
Adds a warning to the README for the forthcoming Prefect 2 default change.
=> Add Prefect 2 warning to README

README.md, docs/index.md
Fixes link to migration guide in 2.0 docs
Updates link to: https://docs.prefect.io/migration-guide/
- README.md
- index.md
Fix broken doc link
This PR:
=> Docs: Fix link to migration guide

src/prefect/testing/utilities.py
=> Ignore prefect api url in test harness

.gitignore, docs/concepts/infrastructure.md, docs/index.md, docs/tutorials/deployments.md, docs/ui/cloud-getting-started.md, netlify.toml, src/prefect/cli/deployment.py, src/prefect/deployments.py
Roll up docs updates from 2022-07-28
=> Docs updates 220728

src/prefect/orion/models/logs.py
When large log batches arrive at the API, they may exceed what we can INSERT in
a single statement, which is limited to 32,767 parameters (and will also have
some textual query size limit as well).  This splits the logs into chunks that
we know will be beneath those limits.
Observed in Prefect Cloud: https://github.com/PrefectHQ/nebula/issues/1247
=> Split up the insert of logs into smaller chunks.

src/prefect/filesystems.py
=> Update `from_path` and skip upload on same path

.github/ISSUE_TEMPLATE/bug_report.yaml
This PR closes https://github.com/PrefectHQ/prefect/issues/6116 by removing a leftover `TODO` from the bug fix template. 
I checked the dif to make sure that I did not remove any other important text.
- Please make sure that your QA steps are both …
=> Remove leftover TODO from bug report template

RELEASE-NOTES.md
Adds release notes for v2.0.1
- Please make sure that your QA steps are both thorough and easy to reproduce by someobdy with limited knowledge of the feature that you are submitting
=> Add release notes for 2.0.1

src/prefect/client.py
Our collections test are flaky, and there have been reports about timeouts; wanted to see if this fixes things, or at least reduces the frequency.
I think the issue stems from us creating a tad too many threads, and it takes longer than the usual 5 seconds timeout for cleanup, so this extends it to 30 seconds.
The prefect-aws Github tests often flake due to this timeout error, and this happens similarly in many other collections. I created https://github.com/PrefectHQ/prefect-aws/pull/51 pulling from this branch `prefect @ git+https://github.com/PrefectHQ/prefect@elongate_timeout`, and adding random comments each time the tests complete to check if it still flakes.
So far, I have 6 successful github runs and 0 flakes after pulling from this branch.
To see if it worked elsewhere, I tried …
=> Make timeout longer

orion-ui/package-lock.json, orion-ui/package.json, orion-ui/src/pages/NotificationCreate.vue, orion-ui/src/pages/WorkQueueCreate.vue
This PR is a follow up of https://github.com/PrefectHQ/orion-design/pull/455 for orion
**Happy …
=> Orion-design bump and Submit buttons update

MANIFEST.in, requirements.txt, src/prefect/.prefectignore, src/prefect/cli/deployment.py, src/prefect/filesystems.py, src/prefect/settings.py, src/prefect/utilities/filesystem.py, tests/utilities/test_filesystem.py
This PR introduces the concept of a `.prefectignore` file when building deployments; in short, this file allows users to specify files to ignore when uploading to their chosen storage that mirrors exactly [the syntax of `.gitignore` files](https://git-scm.com/docs/gitignore).  
If no `.prefectignore` file is found, the default file is written to the present working directory to ensure some sanity when uploading.
After this, I will begin following up with more tests and documentation PRs to support the new deployment story and code.
Tested locally and against S3 with variations in the file / no defaults / etc.
- If no issue …
=> Deployment .prefectignore files

tests/tasks/transform/test_transform_tasks.py
Fixes Transform task library tests and closes #6150 
The change is limited to only test files, so there should be no change in functionality for users.
- Please make sure that your QA steps are both thorough and easy to reproduce by someobdy with …
=> Fixes errors in Transform task library tests

RELEASE-NOTES.md, docs/concepts/flows.md, docs/concepts/task-runners.md, docs/tutorials/dask-ray-task-runners.md, docs/tutorials/first-steps.md
I'll likely tackle the addition of flow retries in a separate pull request.
=> Improvements to the flow concept page

docs/core/getting_started/install.md
Updates installation instructions for v1 after v2 GA.
Replaces https://github.com/PrefectHQ/prefect/pull/6047
=> Update install instructions

changes/pr6035.yaml, src/prefect/tasks/powershell/powershell.py, src/prefect/tasks/shell.py, tests/tasks/test_shell.py
This PR adds Powershell as a valid input shell for ShellTask. https://github.com/PrefectHQ/prefect/issues/3375
Powershell is unable to read the temp file while it's open in another process (`with tempfile.NamedTemporaryFile(prefix="prefect-") as tmp:`).
So the solution is to update the file with the helper script and command, add a `ps1` suffix, and close it. 
Only then we run the temp script with powershell, and finally unlink (delete) the file.
For reference, see this [stackoverflow answer](https://stackoverflow.com/a/5344603) 
This PR:
=> [Enhancement] Powershell as shell input to ShellTask

src/prefect/orion/api/deployments.py, tests/orion/api/test_deployments.py
Users have commonly run into an error building a deployment against one workspace/database and applying it against another.
This PR adds a detailed error message from the server, rather than responding with a generic 409 conflict message.
Tests.
- …
=> Add error messages for missing deployment blocks

src/prefect/orion/database/migrations/MIGRATION-NOTES.md, src/prefect/orion/database/migrations/versions/postgresql/2022_08_01_211251_97e212ea6545_add_deployment_version.py, src/prefect/orion/database/migrations/versions/sqlite/2022_08_01_211039_24bb2e4a195c_add_deployment_version.py, src/prefect/orion/database/orm_models.py, src/prefect/orion/schemas/actions.py, src/prefect/orion/schemas/core.py, tests/orion/api/test_deployments.py
Adds a nullable `version` to deployment.
Added test cases for relevant API calls. @cicdw is working on the client side changes.
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the …
=> Add version to deployments

docs/concepts/infrastructure.md, src/prefect/infrastructure/docker.py, src/prefect/infrastructure/kubernetes.py, src/prefect/infrastructure/process.py
Updates to Infrastructure docs and docstrings.
Affects:
- [Infrastructure](https://deploy-preview-6118--prefect-orion.netlify.app/concepts/infrastructure/) concepts docs
- [Infrastructure](https://deploy-preview-6118--prefect-orion.netlify.app/api-ref/prefect/infrastructure/) API docstrings
Previewed locally.
- If no issue exists, …
=> Docs: Infra docstrings cleanup and examples

changes/pr6021.yaml, src/prefect/tasks/azure/datafactory.py, tests/tasks/azure/test_datafactory.py
https://github.com/PrefectHQ/prefect/issues/6019
This PR:
=> Fixes default polling interval

changes/pr6018.yaml, setup.py
In https://github.com/PrefectHQ/prefect/pull/5921 azure-mgmt-datafactory was mistakenly added to orchestration_extras. This moves it to the proper extras
https://github.com/PrefectHQ/prefect/pull/5921/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R31-R36
Thanks to @prefectcboyd for discovering this and raising this issue
setup.py orchestra_extras -> extras
Proper requirements added
This PR:
=> Move reqs to proper location

src/prefect/blocks/notifications.py, tests/blocks/test_notifications.py
Fixes https://github.com/PrefectHQ/prefect/issues/6165
Ran
```
from prefect import flow, task, get_run_logger
from prefect.blocks.notifications import SlackWebhook
@task(name = "SlackNotif")
def test_notif():
slack_webhook_block = SlackWebhook.load("slack-demo-notification")
slack_webhook_block.notify("Hello from Prefect!")
@flow(name="Testing")
def basic_flow():
test_notif()
basic_flow()
```
in notebook with changes
- Please reference the related …
=> Add sync compatible on SlackWebhook

src/prefect/cli/deployment.py, src/prefect/client.py, src/prefect/deployments.py, tests/test_client.py
Wires up deployment versions to the client on the heels of #6170
=> Deployment version

CHANGELOG.md, changes/pr5819.yaml, changes/pr5979.yaml, changes/pr6018.yaml, changes/pr6021.yaml, changes/pr6035.yaml, docs/.vuepress/config.js
- Allow custom job name for Kubernetes flow runsto be set in job template - [#5819](https://github.com/PrefectHQ/prefect/pull/5819)
- Adds container parameter to `ReadNamespacedPodLogs` - [#5979](https://github.com/PrefectHQ/prefect/pull/5979)
- Add `PowershellTask` for running commands with Microsoft Powershell - [#6035](https://github.com/PrefectHQ/prefect/pull/6035)
- Move `azure-mgmt-datafactory` requirement to 'extras', instead of 'orchestration_extras' - [#6018](https://github.com/PrefectHQ/prefect/pull/6018)
- Fix default initialization of `polling_interval` in `azure.datafactory.PipelineRun` - [#6021](https://github.com/PrefectHQ/prefect/pull/6021)
- [Alvaro Duran Tovar](https://github.com/hermesdt)
- [Chinmay Bhat](https://github.com/chinmay-bhat)
=> Release 1.3.0

src/prefect/testing/cli.py, tests/cli/example-project/README.md, tests/cli/example-project/flows/hello.py, tests/cli/test_deployment_build.py
I created some tech debt last week that I want to revisit by adding tests for critical path behavior of the deployment build / apply CLI commands.  This PR introduces a basic setup for those tests that I wanted to get reviewed before I go too far.
=> Deployment CLI tests

docs/concepts/flows.md, docs/concepts/tasks.md, docs/tutorials/flow-task-config.md
Corrects or adds examples and docs that descriptions for flows and tasks may be provided as docstrings _within_ the flow or task function definition.
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with …
=> Docs: Fix or elaborate flow and task description format

RELEASE-NOTES.md
=> first draft 2.0.2 release notes

src/prefect/orion/schemas/filters.py
Add `or_` operator to flow and task run state filters. This allows queries by "state_name OR state_type".
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are …
=> Add or_ filters to flow,task run state

docs/concepts/deployments.md, docs/concepts/settings.md, docs/concepts/work-queues.md, docs/ui/cloud-getting-started.md
Fix API URL examples in docs.
Add some notes about configuring API URL where it's needed (deployments and agents).
Add a specific section in the settings docs.
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody …
=> Docs: Fix api url examples, expand notes

RELEASE-NOTES.md
adding release notes line on azure storage blocks
Missed this earlier, it can go out with the next release.
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are …
=> adding release notes line on azure storage blocks

orion-ui/package-lock.json, orion-ui/package.json
We haven't used this deprecated library in a while. Finally getting around to removing it.
=> Chore: Remove @prefecthq/miter-design

orion-ui/package-lock.json, orion-ui/package.json, orion-ui/src/pages/WorkQueueEdit.vue
https://github.com/PrefectHQ/orion-design/pull/469
=> Supplementary updates for headings consistency change

docs/concepts/infrastructure.md
=> Improvements to Docker image section of infrastructure docs

docs/concepts/deployments.md
Adds block identifiers to the docs
=> Add block identifiers to the docs

src/prefect/orion/api/dependencies.py, src/prefect/orion/api/deployments.py, src/prefect/orion/database/configurations.py, src/prefect/orion/database/query_components.py, src/prefect/orion/models/flow_runs.py, src/prefect/orion/services/late_runs.py
As we're working toward being able to check our types, I've started in Prefect
Cloud.  There are a few mistypings here (mostly the AsyncEngine/AsyncSession)
that are required to get Prefect Cloud passing checks.
My goal here is not to get all of `prefect` passing, as that will require a
larger effort.
Unit tests are passing, and these changes pass mypy in Prefect Cloud.
- Please reference the related issue by including "closes `<link to issue>`" in …
=> A targeted set of type annotation corrections

src/prefect/client.py, tests/test_client.py
Adds `tags` support to `update_flow_run`. Closes #6220 
- Test suite
- Manually updated a flow via `update_flow_runs` and verified that they appeared in the DB and UI.
- Please make sure that your QA steps are both thorough and easy to reproduce by …
=> Add support for updating `tags` to `update_flow_run`

.github/workflows/python-tests.yaml
We run pytest with extra-verbosity turned on, which results in huge amounts of logging output in CI builds -- all passing tests appear, etc. With failing builds, this extra output makes finding details about _what_ failed difficult.
Fixes #6242 
I waited to see what kind of output this workflow showed for CI builds on this branch.
- If …
=> Run pytest without verbose mode turned on

docs/concepts/task-runners.md
The callout box for the submit method on tasks wasn't rendering right. This fixes it.
**Happy …
=> fixing the callout box

docs/concepts/deployments.md, docs/concepts/filesystems.md
Adds docs showing how to install remote file system dependencies within Docker images
=> Add docs showing how to install remote file system dependencies

docs/concepts/deployments.md, docs/concepts/flows.md, docs/concepts/states.md, docs/tutorials/execution.md
- Add `.prefectignore` to the docs, which is introduced in 2.0.2
- Fix highlighting in `concepts/states`
- Link to `concepts/states` from `concepts/flows/#final-state-determination` to make sure users understand different states before reading the section
- Add some information about `.submit` in the Getting Started section
- If no …
=> Docs: add .prefectignore to deployment

src/prefect/cli/deployment.py
Allows for multiple paths to be specified and removes the non-working default (**cc:** @zangell44 )
=> Allow for multiple deployment YAML paths in apply CLI

docs/concepts/tasks.md, docs/tutorials/flow-task-config.md
Adds notes to Tasks concept and task configuration tutorial regarding persisted location of task results.
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are …
=> Docs: Task result location notes

RELEASE-NOTES.md
=> Create release notes for 2.0.3

src/prefect/blocks/core.py, src/prefect/orion/models/block_schemas.py, tests/orion/models/test_block_schemas.py
Reverts PrefectHQ/prefect#6158
=> Revert "Adds support for `BaseModel` fields in blocks"

.github/workflows/write-changelog.yaml, src/prefect/cli/dev.py
Testing autogenerating changelog entry on merge to a branch
=> feat: Changelog entry workflow (testing)

.github/workflows/write-changelog.yaml, src/prefect/cli/dev.py
=> feat: Changelog entry workflow (still testing!)

docs/tutorials/flow-task-config.md
When simply copy/pasting the example, it does not run because of this missing import
Adding "import os" on top of the existing example.
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge …
=> Fix missing import in example of flow version using git commit sha

.github/workflows/write-changelog.yaml, src/prefect/cli/dev.py
=> feat: Changelog entry workflow (yet another test!)

src/prefect/engine.py
Additional information is needed to debug cases like https://github.com/PrefectHQ/prefect/issues/6086
=> Add debug level log for task run rehydration

orion-ui/package-lock.json, orion-ui/package.json, orion-ui/src/App.vue, orion-ui/src/pages/FlowRunCreate.vue, orion-ui/src/router/index.ts, orion-ui/src/router/routes.ts
This PR introduces a new page for creating adhoc flow runs from any deployment. It extends existing run functionality with 2 options on "Run", "Now with defaults" and "Custom". Clicking "Now with defaults" will create a new run from all defaults set on the deployment, while clicking "Custom" will navigate to a new page where parameters, start time, name, and more can be configured. 
Kick off some runs!
- Please reference the related issue by including …
=> Feature: Custom flow runs

src/prefect/engine.py
Improves out of date documentation for state/result tracking.
=> Fix documentation for `link_state_to_result`

docs/concepts/flows.md
The location of the note should be right after Final State Determination instead of before the subsection Raise an exception. 
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the …
=> Docs: change the location of the note

src/prefect/engine.py, tests/test_flows.py
Closes https://github.com/PrefectHQ/prefect/issues/6322
=> Attach exception to timeout states

tests/orion/models/test_block_documents.py
Adds a unit test for blocks with a field typed as `List[SecretStr]`
=> Add test for list of secrets

RELEASE-NOTES.md
=> Add Anna's fixes that I missed

src/prefect/orion/models/task_runs.py
Similar to the problem described in #6352, we need to perform an implicit idempotency check when creating task runs. This is because every task run attempts to create itself prior to running, and we don't want to introduce a duplicate. This PR modifies the logic to reduce the opportunity for race condition; for a full description of how that can arise, see #6352.
=> Improve task run idempotency checks

src/prefect/orion/models/flow_runs.py
Flow run idempotency is checked with an inequality comparison of the `created` time of the run to the time at the start of the API call. This works in almost all practical cases, but is subject to two failure modes:
- a race condition in which two runs are inserted concurrently. Both calls measure the time at their start and attempt to insert the run. If call A measures its start time, then call B measures its start time, then call A's run is created, then call B's run is created, then both call A and call B will conclude that **it** was the call that actually inserted the run.
- an implicit dependency on SQLAlchemy's python default for the `created` column, which uses `pendulum.now()` to populate the time _when the ORM model is instantiated_. If that behavior were ever changed or removed …
=> Reduce opportunity for race condition in flow run idempotency check

RELEASE-NOTES.md, src/prefect/cli/dev.py
=> feat: Zach testing

.github/release.yml
Much simpler way of generating release notes using GitHub's built in format.
Changes are categorized using labels and listed with a configurable header.
You can also ignore by label or author. I've left the defaults as an example.
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
- Please reference the related issue by including "closes `<link to issue>`" in this Pull Request's summary section. …
=> Configure release notes

docs/contributing/overview.md
Copies 'Code of Conduct' from v1 docs to contributing overview. Closes #6316 
- Previewed markdown output in my local environment.
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of …
=> Add code of conduct to contributing overview

docs/concepts/deployments.md
Remove manifest from the doc about deployment under the concept. I kept everything else the same since the options of deployment might change soon. 
- [x ] A documentation / typographical error fix
- Please make sure that your QA steps are both …
=> Docs: remove manifest from deployment concept

docs/concepts/infrastructure.md
Add a note to Infrastructure recommending that using a docker image with a specific version is a good practice for production.
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the …
=> Docs: Add docker image recommendation

src/prefect/infrastructure/docker.py
The Docker logo is a little wonky right now:
I created a new image that's square and that seemed to fix it:
I also added an image to the `DockerContainer` block.
- Please make sure that your QA steps are both thorough and easy to reproduce by …
=> Updates Docker logo

docs/ui/cloud.md
Remove beta restriction note on users and workspaces. 
Add note and link to Cloud plans.
**Happy …
=> Docs: Update the cloud workspace options

src/prefect/blocks/core.py, src/prefect/orion/models/block_schemas.py, tests/blocks/checksums.json, tests/orion/models/test_block_schemas.py
Reintroduces changes first made in #6158. Now that block schema creation is idempotent due to changes #6301, we can safely reintroduce these changes without the issue described in #6265.
The checksums for `docker-container` and `kubernetes-job` are updated because they both contain a `BaseModel` field that is now correctly included in the block schema `fields`.
Adds the ability to embed `BaseModel` subclasses as fields within blocks. This fixes an issue with the `ImagePullPolicy` field on the `KubernetesJob` block not being saved in the block schema. To resolve, non-block definitions in the generated OpenAPI spec are saved in the `fields` column, while definitions for fields that are block continue to be stored in the `block_schema_references` table.
Closes …
=> Adds support for `BaseModel` fields in blocks

README.md, docs/getting-started/installation.md
Adds badges like 
There's also a contributors badge, but not sure whether or not to add 
`[![Contributors](https://img.shields.io/github/contributors/prefecthq/prefect)](https://github.com/prefecthq/prefect/graphs/contributors)`
https://img.shields.io/github/contributors/prefecthq/prefect
- If no issue exists, please create a feature …
=> Adds badges to readme

.github/ISSUE_TEMPLATE/1_general_bug_report.yaml, .github/ISSUE_TEMPLATE/2_ui_bug_report.yaml, .github/ISSUE_TEMPLATE/3_feature_enhancement.yaml, .github/ISSUE_TEMPLATE/config.yml
There's a lot of text on this page, even if you already know what you're looking for. Small icons help break it up and make each section more readily identifiable.
=> Add icons for each template option

docs/concepts/storage.md
Small wording fix in storage docs
Changed 'inherit' to 'inherent' to make the sentence in question read correctly.
I previewed the Markdown to ensure it render correctly.
- Please make sure that your QA steps are both thorough and easy to reproduce …
=> Update wording in storage docs

src/prefect/cli/deployment.py, src/prefect/deployments.py, tests/cli/test_deployment_build.py, tests/fixtures/client.py, tests/test_deployments.py
This PR enhances the recent deployment work to include:
- `build_from_flow` is now a class method instead of a class method to reduce the number of calls necessary
- fixes two minor bugs in which server-side descriptions and versions were overwritten incorrectly 
- begins establishing some basic testing patterns for deployments
Used locally, wrote tests.
- Please reference the related issue by including "closes `<link to issue>`" in this Pull …
=> Build Method to classmethod

.github/ISSUE_TEMPLATE/config.yml
Following conversation with @csreuter
=> Update issues template to reflect rubber duck program

mkdocs.yml
Two minor flags following discussion with @tpdorsey :
- search auto-suggestions
- search highlights
=> Enhance docs search

orion-ui/tests/notifications.spec.ts, orion-ui/tests/utilities/utilities.ts
Fixes the previously broken create notification test. Fixed in a way that didn't require PRs to other repositories. Eventually this will be improved.
=> Chore: Fix broken integration test

docs/ui/cloud-getting-started.md
Small documentation update to make API key creation instructions match current cloud UI.
The account icon no longer has a **Settings** option. Instead, you just click on your account name to load your profile. This change updates the docs to match what the user needs to do in the UI. 
* Previewed the Markdown to ensure it renders correctly
* Verified that the updated instructions match the Prefect cloud UI
- Please reference the related issue by …
=> Update API key creation instructions

src/prefect/orion/database/migrations/versions/postgresql/2022_08_07_134410_77eb737fc759_add_work_queue_name_to_runs.py
Fixes line that was erroneously commented out in migration
=> Uncomment migration line

src/prefect/orion/models/flow_run_notification_policies.py, src/prefect/orion/models/flow_runs.py, src/prefect/orion/models/flows.py, src/prefect/orion/models/work_queues.py, tests/orion/models/test_flow_runs.py, tests/orion/models/test_flows.py, tests/orion/models/test_work_queues.py
This PR removes some old, explicit type checks in certain update routes.
=> Remove explicit type validation

docs/concepts/deployments.md
Add Python `Deployment` section and examples to Deployments docs.
=> Docs: Add Python deployment examples

docs/concepts/deployments.md
Fix deployment Python examples.
=> Docs: fix deployment Python examples

src/prefect/engine.py
Fixes log added in #6307 when the task is run on a remote worker.
Related to bug noted in #6401 
This is hard to reproduce, a task run needs to double-execute on a remote worker.
- Please make sure that your QA steps are both thorough and easy to …
=> Fix log on abort when the flow run context is not available

src/prefect/agent.py, tests/test_agent.py
Refers to out of date "flow runner" concept.
=> Fix error message in `submit_run`

mkdocs.yml
Fixes edit URL so the edit icon takes users to the correct GitHub page.
=> Docs: Correct GitHub edit URL

.github/workflows/release.yaml
Instead of just opening a pull request, the release automation will merge the pull request. This will not occur if there are merge conflicts. Previously, if a maintainer squash merged the pull request the history of the `docs-deploy` branch would diverge from `main` resulting in failure of this workflow on the next release.
- If no …
=> Automatically publish documentation on release

docs/concepts/work-queues.md
Remove references to 2.0.5 because release's name was changed to 2.1.0
More work could be done here, this just fixes the references to 2.0.5
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited …
=> Docs: work-queues.md to remove references to 2.0.5

orion-ui/package-lock.json, orion-ui/package.json, orion-ui/src/components/FlowRunsFilter.vue, orion-ui/src/pages/FlowRuns.vue
orion side that mirrors https://github.com/PrefectHQ/nebula-ui/pull/1522
* pulls filter component out of `FlowRuns.vue`
* uses new `useFlowRunFilterFromRoute` from orion-design
=> Chore: using new orion-design flow-run-filter composition

orion-ui/src/components/FlowRunsFilter.vue
updated orion-ui to match nebula-ui's approach to changing flow runs filter on different screen sizes
=> Feature: using media queries from nebula

docs/concepts/deployments.md
- Update deployment API and command to reflect changes in 2.1.1
- Reorganize the structure
- Use `-q` instead of `-t` to reflect the recommended way to build a deployment
- Please make sure that your QA steps are both thorough and easy to reproduce …
=> Docs: Update deployment concepts to reflect changes in 2.1.1

docs/concepts/blocks.md
Fixes several typos in blocks concepts doc.
- [ x] A documentation / typographical error fix …
=> Docs: fix typos in blocks.md

docs/collections/overview.md
fix typos in readme
- [ x] A documentation / typographical error fix
=> fix typos in README

src/prefect/deployments.py, tests/test_deployments.py
Helps ensure issues with typos, etc. are caught early with `build_from_flow` which accepts arbitrary kwarg inputs.
Wrote test.
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the …
=> Disallow extra attribute initialization on Deployments

src/prefect/cli/deployment.py
To avoid confusing users, raises informative error if both infra and a specific infra block are simultaneously provided.
- Please make sure that your QA steps are both thorough and easy to reproduce by somebody with limited knowledge of the feature …
=> Raise informative error if two infra configs provided

src/prefect/client.py, src/prefect/engine.py, src/prefect/orion/orchestration/core_policy.py, src/prefect/orion/schemas/core.py, tests/orion/api/test_task_runs.py, tests/orion/models/test_task_run_states.py, tests/orion/orchestration/test_core_policy.py, tests/orion/schemas/test_core.py, tests/test_client.py, tests/test_engine.py
All clients from `2.1.1` and before will break by making these properties now optional.
Instead of making the properties optional, we have marked them as deprecated and introduced two new properties.
For consistency, the updates have also been applied to `TaskRunPolicy`.
- If no issue exists, please create a feature enhancement issue …
=> Revert breaking schema change

RELEASE-NOTES.md
=> Add release notes for 2.2.0

docs/contributing/overview.md, scripts/precommit-versions.py
Adds `autoflake8` to `precommit-versions.py` and the contributing guidelines
Ran `pip install $(./scripts/precommit-versions.py)` and ensured `autoflake8` was installed.
- Please make sure that your QA steps are both thorough and easy to reproduce …
=> Clean up autoflake8 usage outside of pre-commit

src/prefect/engine.py
If we are already in a client context, we should avoid creating new clients as it puts additional strain on the database when using the ephemeral server. We perform this optimization for task runs, but not for child flow runs. 
This should help address issues like https://prefect-community.slack.com/archives/CL09KU1K7/p1661212292649449 where the database is locked when running multiple subflows.
- Please reference the related issue by including …
=> Use the parent flow run client for child flow runs if available

src/prefect/deployments.py, src/prefect/filesystems.py, tests/test_deployments.py
This PR introduces block capability validation onto the client-side `Deployment` object to capture errors earlier; in doing so, this PR also refactors filesystem blocks into more granular capabilities at both the path and directory level.  This should be sufficient to support both read-only storage options as well as result configuration needs at the individual file level.
Closes #6487 
Wrote targeted tests.
- Please reference the related issue by …
=> Block validation on deployments

scripts/entrypoint.sh
Previously, this incorrectly noted that the image was a "development" image. The ASCII art has been updated to "Prefect" instead of "Orion" to match current branding and image usage.
```
❯ ./scripts/entrypoint.sh
___ ___ ___ ___ ___ ___ _____ 
| _ \ _ \ __| __| __/ __|_   _|
|  _/   / _|| _|| _| (__  | |  
|_| |_|_\___|_| |___\___| |_|  
$ 
```
Previously:
```
❯ ./scripts/entrypoint.sh
____  _____  _____ ____  _   _
/ __ \|  __ \|_   _/ __ \| \ | |
| |  | | |__) | | || |  | |  \| |
| |  | |  _  /  | || |  | |     |
| |__| | | \ \ _| || |__| | |\  |
\____/|_|  \_\_____\____/|_| \_|
Thanks for using Prefect!!!
This is a development docker image for Prefect Orion.
$
``` …
=> Update the Prefect entrypoint display

mkdocs.yml
Very minor change - removes a duplicate key in mkdocs.yaml
=> Remove duplicate key in mkdocs.yaml

.github/workflows/python-tests.yaml
Pretty much what is says on the tin ;)
=> Including the layer caching configuration from #6578 during python tests.

src/prefect/deployments.py
Deployment docstring shows `flow_name` as a parameter. Correct param is `flow` and examples in the same docstring reflect that. This change fixes the docstring so it is now `flow`.
- [ x] This pull request includes a `bug`, `feature`, `enhancement`, `docs`, or `maintenance` label categorizing the change.
=> correct docstring param name for flow in Deployment

src/prefect/utilities/asyncutils.py, tests/utilities/test_asyncutils.py
The recently added check (https://github.com/PrefectHQ/prefect/pull/6565) for an async caller will fail when using task groups since AnyIO uses internal methods that are not async to create the coroutine
```python
@sync_compatible
async def foo(task_status=None):
if task_status:
task_status.started()
async with anyio.create_task_group() as tg:
await tg.start(foo)
foo()
```
=> Fix edge case in `sync_compatible` detection when using AnyIO task groups

docs/ui/flow-runs.md, docs/ui/organizations.md
Add documentation for flow run retention policy.
Affects:
- Cloud > Organizations
- UI > Flow Runs
=> Docs: Add flow run retention policy

docs/core/README.md, docs/core/development/overview.md, docs/core/getting_started/quick-start.md, docs/core/tutorial/01-etl-before-prefect.md, docs/core/tutorial/02-etl-flow.md, docs/core/tutorial/03-parameterized-flow.md, docs/core/tutorial/04-handling-failure.md, docs/core/tutorial/05-running-on-a-schedule.md, docs/core/tutorial/06-parallel-execution.md, docs/core/tutorial/07-next-steps.md
Updates the ETL tutorial and related pages to:
- Include correct branch installation step
- Add notes suggesting new users should consider starting with Prefect 2
=> Update ETL tutorial installation

src/prefect/logging/loggers.py
Closes #6606 by improving the documentation for `get_logger`.
=> Improve internal `get_logger` docstring

RELEASE-NOTES.md
[View rendered notes](https://github.com/PrefectHQ/prefect/blob/release-notes-2.3/RELEASE-NOTES.md#230)
=> Add release notes for 2.3.0

.github/pull_request_template.md, .github/release.yml
Updates use of the `bug` label for pull requests to `fix` which is nice for not feeling like a PR introduces a bug.
=> Update `bug` label to `fix`

RELEASE-NOTES.md
We should probably not merge the release notes until right before release as it turns out I like to futz.
=> Minor touchups to release notes for v2.3.0

docs/concepts/deployments.md
Fixes a typo: `indentifier` -> `identifier`
An example of the correct spelling from elsewhere in the docs is the sentence: `You can provide storage and infrastructure block identifiers`
=> Fix typo in deployments.md

.github/workflows/release.yaml
Closes https://github.com/PrefectHQ/prefect/issues/6630 by changing from `master` to `release/v1`
- ~[ ] This pull request includes tests or only affects documentation.~
- Cannot be tested until next release
=> Update pin for gh-action-pypi-publish action

Dockerfile
Now that we support Git storage of flows (#6517) it seems reasonable for us to include `git` in our base image.
Closes https://github.com/PrefectHQ/prefect/issues/6649
```bash
$ prefect dev build-image
$ docker run prefecthq/prefect:dev-python3.8 git --version                                                                                                                  
git version 2.30.2
```
=> Add `git` to the Prefect image

RELEASE-NOTES.md
[View rendered notes](https://github.com/PrefectHQ/prefect/blob/release-notes-2.3.1/RELEASE-NOTES.md#231)
=> Add release notes for 2.3.1

orion-ui/package-lock.json, orion-ui/package.json, orion-ui/src/App.vue, orion-ui/src/services/healthApi.ts, orion-ui/src/utilities/api.ts
This PR adds error display to UI when backend is unreachable 
Closes https://github.com/PrefectHQ/prefect/issues/6442
=> Add error display to UI when backend is unreachable

README.md
removes contrib count badge
- [ x] This pull request includes a `fix`, `feature`, `enhancement`, `docs`, or `maintenance` label categorizing the change.
=> Remove contributors badge from README

src/prefect/orion/models/deployments.py
Closes [#6663](https://github.com/PrefectHQ/prefect/issues/6663)
When building and reapplying after changing parameters of a flow, the parameters in the Orion UI are not changed. 
Fixed by adding 'parameter_openapi_schema' to include for insertion in Orion database.
```
@flow
def test_flow(name):
print("Hello, {} and {}!".format(name))
```
```
prefect deployment build -n ghtest -q prod --apply test-flow.py:test_flow
```
```
@flow
def test_flow(name, name2):
print("Hello, {} and {}!".format(name, name2))
```
```
prefect deployment build -n ghtest -q prod --apply test-flow.py:test_flow
```
No change
After adding ```parameter_openapi_schema```: …
=> Add parameter_openapi_schema to inject database

docs/concepts/schedules.md
Improve docs Schedules concept page to show new common ways of creating schedules.
=> Docs: Update schedules.md for deployments from cli and python file

docs/collections/catalog/prefect-fugue.yaml
Adds entry for new `prefect-fugue` collection to the collections catalog.
Examples can be seen in the [prefect-fugue docs](https://fugue-project.github.io/prefect-fugue/)
=> Adds prefect-fugue to collections catalog

docs/concepts/deployments.md, docs/getting-started/installation.md, docs/index.md, docs/tutorials/deployments.md, docs/tutorials/storage.md, mkdocs.yml
This PR expands our deployment docs to cover:
- sharing blocks between deployments
- python-based definitions
- infra overrides and path specification
- multi-file projects
=> Expanded Deployment docs

CHANGELOG.md, changes/6412.yml, changes/6572.yaml, changes/pr5671.yaml, changes/pr6028.yaml, changes/pr6375.yaml, changes/pr6573.yml
- Fix bug where flows with emoji characters pass `flow.validate()`, but fail to extract from file - [#6375](https://github.com/PrefectHQ/prefect/pull/6375)
- Fix `FlowRunView` task run query errors when all task runs in the flwo run are cached - [#6572](https://github.com/PrefectHQ/prefect/pull/6572)
- Update `FlowRunView` to avoid retrieval of cached static tasks during `latest` calls - [#6572](https://github.com/PrefectHQ/prefect/pull/6572)
- Update `FlowRunView` to be robust to multithreaded usage - [#6572](https://github.com/PrefectHQ/prefect/pull/6572)
- Add state handler to log to Snowflake - [#5671](https://github.com/PrefectHQ/prefect/pull/5671)
- Fix default idempotency token for `DatabricksSubmitMultitaskRun` - [#6412](https://github.com/PrefectHQ/prefect/pull/6412)
- Fix custom …
=> Release 1.3.1

docs/concepts/flows.md, docs/concepts/task-runners.md, docs/tutorials/deployments.md, docs/tutorials/docker.md, docs/tutorials/flow-task-config.md, docs/tutorials/storage.md, docs/ui/cloud-getting-started.md, docs/ui/flow-runs.md, src/prefect/cli/deployment.py, src/prefect/orion/models/concurrency_limits.py, src/prefect/utilities/services.py, tests/cli/test_deployment_cli.py
Revisions to task runner concepts documentation and tutorial to clarify "default task runner" language. In response to user community questions indicating confusion about when a task runner is invoked for task execution.
Additional minor fixes including:
- Remove "the the" typos in docs and docstrings
- Remove unnecessary heading from tutorial
- Fix heading levels in tutorial
- Move some admonitions to more appropriate locations to avoid confusion
=> Task runner documentation fixes and clarifications

docs/faq.md, docs/getting-started/installation.md
Add notes regarding Windows and Linux installation:
- Specify minimum Python 3.8 version for Windows
- Add notes regarding Windows and Linux support to FAQ
- Minor doc formatting and organization fixes
=> Add notes for Windows and Linux installation

netlify.toml
Fixes the work begun in #6728 -- see #6784 for an example of build failure.
=> Fall back to base mkdocs config file not insiders file

src/prefect/executors/dask.py
Closes https://github.com/PrefectHQ/prefect/issues/6776
=> Fix bug where `scheduler_comm.close_rpc()` was not awaited

tests/infrastructure/test_docker_container.py, tests/infrastructure/test_kubernetes_job.py
Fixes failures on `main` e.g. https://github.com/PrefectHQ/prefect/actions/runs/3039755553/jobs/4895326998
=> Fix infrastructure tests after out-of-date merge

orion-ui/package-lock.json, orion-ui/package.json
Updates orion design to the latest version.  Changes include:
- fixes to state badges
- created date/time in the flows table
- export the radar page header
=> Update orion design and related packages

docs/concepts/deployments.md, docs/concepts/filesystems.md, docs/concepts/storage.md, mkdocs.yml, src/prefect/filesystems.py
Updates Storage and Filesystems documentation
- Adds notes about installing libraries used by some filesystems
- Adds missing GitHub and SMB docs
- Fixes docstring formatting
- Minor fixes and reorganization
=> Enhancements to Storage and Filesystems documentation

docs/concepts/infrastructure.md
=> Add `ECSTask` block to infrastructure documentation

RELEASE-NOTES.md
[Rendered](https://github.com/PrefectHQ/prefect/blob/release-2.4.0/RELEASE-NOTES.md#release-240)
=> Add release notes for 2.4.0

mkdocs.yml
Storage tutorial dropped from navigation. This restores it.
=> Add storage tutorial to nav

orion-ui/src/App.vue, orion-ui/src/pages/AppRouterView.vue, orion-ui/src/pages/RouterView.vue
Part of a multi step effort to replace our current ui api services with a much simpler and more flexible approach. 
Related to https://github.com/PrefectHQ/orion-design/pull/545
=> UI: Provide new api service for orion-design

docs/index.md
We originally thought that use of ConcurrentTaskRunner with submit would be a common early use case. My sense based on Community Slack and questions elsewhere is that this is not the case. I think we're best off cutting this example and getting folks to Getting Started sooner. We could also simplify the side-bar menu for the main docs page with this change.
=> Remove simple concurrency example

docs/recipes/recipes.md
=> Improvements to Prefect Recipes page

docs/tutorials/docker.md
=> Fix typos in Docker tutorial

src/prefect/blocks/core.py
=> Fix import in block core module

docs/concepts/blocks.md
I was looking for how to register a block in orion and skipped over this because the title said "in Prefect Cloud".  This small change makes it clearer that you can also register a block for the orion ui.
=> Switch header for registering blocks

requirements-dev.txt
Adds `cairosvg` to ensure successful site build.
I'm not sure why this was not being picked up when installing Material for Mkdocs Insiders. Perhaps worth more investigation.
=> Add cairosvg to requirements

docs/contributing/overview.md
Adds a note and link to further information for users wanting to run the Prefect UI locally.
Closes https://github.com/PrefectHQ/prefect/issues/5288
=> Add tip and link to building UI for local development

CHANGELOG.md, docs/.vuepress/config.js
- Add `get_latest` to `TaskRunView` — [#6749](https://github.com/PrefectHQ/prefect/pull/6749)
- Update agents to allow logs to be disabled with `PREFECT__CLOUD__SEND_FLOW_RUN_LOGS` — [#6833](https://github.com/PrefectHQ/prefect/pull/6833)
- Fix bug where `scheduler_comm.close_rpc()` was not awaited in `DaskExecutor` — [#6793](https://github.com/PrefectHQ/prefect/pull/6793) 
- Fix bug where the Prefect diagnostics logger could duplicate output — [#6832](https://github.com/PrefectHQ/prefect/pull/6832) 
-  Add validation for node type id and instance pool id in Databricks `NewCluster` — [#6853](https://github.com/PrefectHQ/prefect/pull/6853)
=> Release 1.4.0

docs/getting-started/installation.md, docs/getting-started/overview.md, mkdocs.yml
- Change getting started overview into quick start
- New Advanced Tutorials section
=> Reorganize tutorials and quick start

docs/concepts/work-queues.md
Removed duplicated agents documentation content. Minor edits to text.
=> Remove duplicated sections from work queue and agents docs

RELEASE-NOTES.md
[Rendered](https://github.com/PrefectHQ/prefect/blob/release-2.4.1/RELEASE-NOTES.md#release-241)
=> Add release notes for 2.4.1

docs/concepts/schedules.md
Removes a line stating that tz cannot be set via CLI. That limitation was removed in 2.4.0
=> Update docs regarding schedules and the CLI

docs/index.md
Minor doc formatting improvement on index page. 
=> Remove single subheading example from main index page

.github/workflows/integration-tests.yml, .github/workflows/ui-tests.yml
Updates `Integration tests` to only run on changes to Python or UI files in pull requests (basically skipping on docs pull requests).
Cleans up some of the names in preparation for introducing integration tests that are not UI related.
- ~[ ] This pull request includes tests or only affects documentation.~
=> Clean up integration tests workflow

.github/workflows/integration-tests.yml, flows/hello_world.py, flows/secret_block.py, scripts/run-integration-flows.py, scripts/wait-for-server.py
- Adds `/flows` for writing flows to use in integration tests
- Extends the `Integration tests` workflow to test client/server compatibility by running flows
Runs all of the flows in `/flows` with the current client and an old server version running in a Docker container.
Runs all of the flows in `/flows` with an old client version running in a Docker container with the current server (flows are mounted into the image).
Client not compatible with old server https://github.com/PrefectHQ/prefect/actions/runs/3130522985/jobs/5080857103
Server not compatible with old client https://github.com/PrefectHQ/prefect/actions/runs/3130522985/jobs/5080857344
Compatible https://github.com/PrefectHQ/prefect/actions/runs/3130522985/jobs/5080857524
- If no issue exists and your change is not a small fix, …
=> Add backwards compatibility integration tests

.pre-commit-config.yaml, src/prefect/blocks/core.py, src/prefect/docker.py, src/prefect/infrastructure/docker.py, src/prefect/infrastructure/kubernetes.py, src/prefect/orion/database/migrations/versions/postgresql/2022_07_25_214717_4ff2f2bf81f4_adds_block_type_slug.py, src/prefect/orion/database/migrations/versions/sqlite/2022_07_25_142515_f335f9633eec_adds_block_type_slug.py, src/prefect/packaging/docker.py, src/prefect/utilities/slugify.py, tests/docker/test_registry_pushes.py, tests/orion/api/test_block_types.py, tests/utilities/test_slugify.py
Having `unicode-slugify` installed in the same environment breaks Prefect.
Work around this by using a more explicit import.
Closes #6945.
=> Ensure python-slugify is always used

src/prefect/orion/database/interface.py, src/prefect/orion/database/query_components.py, src/prefect/orion/models/configuration.py, tests/orion/models/test_configuration.py
Resolves a bug with configuration caching introduced in #6959
=> Fix configuration caching

src/prefect/orion/models/__init__.py
=> Add block registration to models init

.github/ISSUE_TEMPLATE/4_maintenance_ticket.yaml
Adds an issue template for maintenance tasks e.g. fix a flaky test, add integration tests, etc.
I did not go through the trouble of hosting this one on another repository to demo. We can adjust afterwards if necessary.
Following creation of this, I'm going to create the issue: "Add deployment / agent coverage for compatibility tests"
=> Add issue template for maintenance

.github/ISSUE_TEMPLATE/1_general_bug_report.yaml, .github/ISSUE_TEMPLATE/2_ui_bug_report.yaml
Updates the version / error sections of issue templates to automatically render rather than including code fences for the user to place content in. The users often place content outside of it — I edit user's issues to move content into the fences as intended ~2x a day.
Also updates guidance on the version section to strongly encourage the user of the builtin command. We're often not receiving complete information here.
https://github.com/PrefectHQ/prefect/issues/7002 is a great example of both of these problems (I blame the template, not the users!)
I tested over in a personal repository: https://github.com/madkinsz/prefect-gh-test/issues/new?assignees=&labels=status%3Aneeds-triage%2Cbug&template=1_general_bug_report.yaml
- ~[ ] This pull request references any related issue by including …
=> Improve rendering of errors/versions in issue templates

tests/cli/test_block.py, tests/orion/api/test_block_schemas.py, tests/orion/api/test_block_types.py
These tests should be updated in the very near future to match expected behavior
=> Disable block protection tests to fix CI on main

orion-ui/src/main.ts
I have no idea why this doesn't break the build, but this should have been done alongside https://github.com/PrefectHQ/prefect/pull/7035
=> UI: remove pinia plugin from main

src/prefect/serializers.py, tests/test_serializers.py
Deep serialization makes less sense for results and was not thread/async safe as implemented
=> Remove deep serialization from `PickleSerializer` and add tests

docs/concepts/deployments.md, src/prefect/cli/deployment.py
=> Clarify that path can be used to point to a local subdirectory

src/prefect/orion/api/server.py, tests/orion/api/test_server.py
Adds exception handling to block auto-registration to avoid crashing the server during start up in situations like the one discovered in https://github.com/PrefectHQ/prefect-helm/pull/63.
=> Adds exception handling to block auto-registration

src/prefect/blocks/kubernetes.py, src/prefect/blocks/notifications.py, src/prefect/blocks/system.py
Renames `Args` to `Attributes` in docstrings to better adhere to the [google styled docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
This is one of the reasons why griffe raises warnings.
=> Convert args to attributes

docs/recipes/catalog/ecs-infra-block.yaml, docs/recipes/catalog/prefect-azure.yaml
- Fix broken link in Azure agent recipe
- Add Serverless workflows with ECSTask block recipe
=> Add ECSTask block tutorial to recipes

flows/flow_retries.py, flows/task_retries.py
Adds additional test coverage for backwards compatibility.
=> Add flow and task retries to integration tests

RELEASE-NOTES.md, scripts/generate-release-notes.py
[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.5.0/RELEASE-NOTES.md#release-250)
=> Add release notes for 2.5.0

docs/faq.md, docs/getting-started/installation.md
Adds a note regarding support for and configuration of proxies to installation docs and FAQ
=> Add documentation for support of proxies

docs/ui/organizations.md
Minor revisions to Organizations docs based on feedback from the team.
=> Revisions to Organization docs

.github/workflows/integration-tests.yaml, src/prefect/blocks/core.py, src/prefect/cli/block.py, src/prefect/client/orion.py, src/prefect/exceptions.py, src/prefect/orion/api/block_schemas.py, src/prefect/orion/api/block_types.py, tests/blocks/test_core.py, tests/cli/test_block.py, tests/orion/api/test_block_schemas.py, tests/orion/api/test_block_types.py
Block protection has caused some issues with basic block functionality when it gets turned on. When a block is registered, the client attempts to update a block type and create a new block schema if necessary, both actions that are prevented on protected blocks by the current implementation. Neither block types updates nor block schema creations are destructive actions, and we can safely allow users to perform these actions on protected blocks.
This PR removes block protection from the block type update and block schema create API routes. Block type deletion and block schema deletion routes maintain the protection logic. I've also removed the API version check for block protection so that protected block types and protected block schemas are protected from all clients.
This code would …
=> Updates block protection to only prevent deletion

docs/api-ref/prefect/settings.md, docs/faq.md, mkdocs.yml, src/prefect/engine.py, src/prefect/settings.py
Adds attribute docstrings to settings, ensuring that they appear correctly in rendered API documentation.
Minor formatting corrections to settings assignments.
Update mkdocstrings options.
Closes https://github.com/PrefectHQ/prefect/issues/6549
=> Update docstrings to render settings in API reference

src/prefect/cli/deployment.py, tests/cli/test_deployment_cli.py, tests/fixtures/database.py
Adds `--params <json>` and `--param <name>=<value>` to `prefect deployment run`. `--param` may be specified multiple times. `--params -` may be passed to read parameters from stdin allowing a file to be piped to the command.
Closes https://github.com/PrefectHQ/prefect/issues/6840
```     
❯ echo '{"z": 3}' | prefect deployment run hello/test --param x=1 --param y=2 --params -
Creating flow run for deployment 'hello/test'...
Created flow run 'annoying-koel'.
└── UUID: 8bfc27b4-0f35-47dc-b3d9-72151ff4317e
└── Parameters: {'z': 3, 'x': 1, 'y': 2}
└── URL: <no dashboard available>
❯ prefect deployment run hello/test --param z='["item", "item", "item"]'            
Creating flow run for deployment 'hello/test'...
Created flow run 'blazing-leech'.
└── UUID: efd41a94-92a4-4ac4-a801-3f28dd53d4c1 …
```
=> Add `--param` / `--params` to `prefect deployment run`

RELEASE-NOTES.md
[Rendered](https://github.com/PrefectHQ/prefect/blob/release-2.6.0/RELEASE-NOTES.md#release-260)
=> Release notes for 2.6.0

docs/index.md
Discourse discussion of choosing between Prefect 1 and 2 had been deleted, resulting in a broken link in the docs. Rewrote reference and updated links accordingly.
- [s] This pull request includes a label categorizing the change e.g. `fix`, `feature`, `enhancement`
=> Update link reference for version 1/2 discussion

src/prefect/utilities/importtools.py
The docs reference the wrong function name. This fixes it.
NA
=> Update the docs for from_qualified_name

docs/getting-started/overview.md, docs/index.md, mkdocs.yml
- Moves index.md into Getting Started navigation, emphasizing how to get started as the first thing users see in the docs.
- Minor edits to support navigating readers to appropriate getting started topics.
=> Reorganize top-level navigation to highlight Getting Started

RELEASE-NOTES.md
[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.6.2/RELEASE-NOTES.md)
=> Add release notes for 2.6.2

docs/overrides/main.html
As an experiment, changes the announce bar to announce the release, with link to release notes.
=> Add 2.6.2 release notes link to announcement bar

scripts/run-integration-flows.py
Integration tests could pass by not actually running any files. This guards against that.
If running from an installed version:
```
❯ python ./scripts/run-integration-flows.py
No Python files found at /opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/lib/python3.8/flows
```
=> Exit with non-zero code if integration tests do not run any files

docs/overrides/main.html
Bump version in announce bar from 2.6.2 to 2.6.3
=> Bump version

docs/concepts/filesystems.md
Change the parameter `basepath` to `bucket_path` for S3 and GCS.
closes #6251
=> Docs: change basepath to bucket_path for s3 and gcs

docs/overrides/main.html
Update announce bar for 2.6.4 release
=> Update announce bar for 2.6.4 release

RELEASE-NOTES.md
[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.6.4/RELEASE-NOTES.md#release-264)
=> Add release notes for 2.6.4

.github/workflows/release.yaml
We can add this again once it is done being a blocker for our releases
=> Remove Test PyPI entirely

docs/collections/catalog/prefect-docker.yaml
Adds `prefect-docker` to catalog. No logo added because it exists already https://github.com/PrefectHQ/prefect/blob/main/docs/img/collections/docker.png
=> Add prefect docker to catalog

docs/concepts/infrastructure.md
The experimental tag was removed from the `prefect-aws` docs. This PR removes it from the core library docs to reflect that change.
=> Removes experimental tag from ECSTask block

orion-ui/.vscode/settings.json, orion-ui/package-lock.json, orion-ui/package.json
We've removed all pinia code from the ui. Safe to remove it as a dependency now.
=> UI: Remove pinia as a dependency

orion-ui/.vscode/settings.json, orion-ui/package-lock.json, orion-ui/package.json, orion-ui/src/main.ts, orion-ui/src/pages/Settings.vue, orion-ui/src/utilities/colorMode.ts
[this change](https://github.com/PrefectHQ/orion-design/pull/727) to orion-design changed the way we interact with color-mode.
This PR, applies that change to orion-ui
=> UI: updated and fix breaking color change

docs/concepts/results.md
=> Fix typo in Results documentation

orion-ui/src/utilities/permissions.ts, src/prefect/client/orion.py
Removes the check for feature flag env
=> Remove UI canary flag permission check

orion-ui/package-lock.json, orion-ui/package.json
Bumps orion design to include flow retry button. 
=> Add flow retry button 

RELEASE-NOTES.md
[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.6.5/RELEASE-NOTES.md#release-265)
=> Generate release notes for 2.6.5

src/prefect/storage/docker.py
Fix broken link to Docker API docs from `build_kwargs` in V1 [Docker Storage](https://docs-v1.prefect.io/api/latest/storage.html#docker).
=> Fix broken link to Docker documentation from Storage API docs

setup.py
Fix a typo introduced in https://github.com/PrefectHQ/prefect/pull/5357. 
- `kubernetes >= 9.0.0a1.0` [is not valid](https://pypi.org/project/kubernetes/9.0.0a1.0/)
- `kubernetes >= 9.0.0a1` [is valid](https://pypi.org/project/kubernetes/9.0.0a1/)
Discovered while using [dependabot](https://github.com/dependabot) as it is failing with `Could not parse version constraint: >=9.0.0a1.0` 
=> Fix non existing kubernetes version.

docs/contributing/versioning.md, mkdocs.yml
Adds documentation around versioning scheme, deprecation, and compatibility guarantees.
See it in the preview: https://deploy-preview-7353--prefect-orion.netlify.app/contributing/versioning/
=> Add versioning documentation

docs/overrides/main.html
Updates announce bar for 2.6.6 release.
=> Update announce banner for 2.6.6

docs/concepts/schedules.md
The last sentence in `schedules.md` says "remote" when it should say "remove". This PR changes exactly one letter in `schedules.md` to correct the typo.
=> Fixed typo in schedules.md

src/prefect/cli/block.py, src/prefect/cli/cloud.py, src/prefect/cli/deployment.py, src/prefect/cli/orion_utils.py, src/prefect/cli/root.py, src/prefect/client/cloud.py, src/prefect/logging/configuration.py, src/prefect/settings.py, tests/cli/test_deployment_cli.py, tests/cli/test_version.py, tests/test_settings.py
Changes `PREFECT_CLOUD_URL` to `PREFECT_CLOUD_API_URL` and adds `PREFECT_UI_URL` and `PREFECT_CLOUD_UI_URL`  to consolidate inference of UI URLs. 
`PREFECT_CLOUD_URL` is marked as deprecated and has backwards compatibility support.
`PREFECT_UI_URL` infers its value from `PREFECT_API_URL` by default, but can be set explicitly. For example, if you want to test against a UI preview on netlify.
`PREFECT_CLOUD_UI_URL` infers its value from `PREFECT_CLOUD_API_URL` by default, but can be set explicitly.
When using Cloud, the `PREFECT_UI_URL` is workspace scoped. The `PREFECT_CLOUD_UI_URL` is not.
When using the open source server, `PREFECT_CLOUD_UI_URL` will still point to Cloud. This is important for login e.g. #7334 
Required for #7334 
Helps with issues like …
=> Create setting for UI URL and clarify Cloud API URL

src/prefect/agent.py, src/prefect/infrastructure/base.py, tests/infrastructure/test_base.py, tests/test_agent.py
Currently, infrastructure is given labels for flow run metadata. However, in cases like https://github.com/PrefectHQ/prefect-aws/issues/148 it is useful for the infrastructure to have additional metadata like the deployment and flow names.
This adds optional `deployment` and `flow` parameters to `Infrastructure.prepare_for_flow_run` which will then be used to add the labels:
- `prefect.io/deployment-name`
- `prefect.io/deployment-updated`
- `prefect.io/flow-name`
These can be used by infrastructure blocks to configure namespaces. For example, the `ECSTask` block will use the deployment and flow names for the "family" name to avoid rate limits. Right now, we're using "prefect" for the family name.
The full list of labels for an example deployment is now:
```python
{ …
```
=> Add deployment and flow metadata to infrastructure labels

docs/ui/sso.md
Adds minimal documentation for new SCIM/Directory Sync SSO feature.
=> Add documentation for Directory Sync

RELEASE-NOTES.md
Add release notes for version 2.6.7.
Preview at https://github.com/PrefectHQ/prefect/blob/release-notes-2-6-7/RELEASE-NOTES.md
=> Add release notes for 2.6.7

docs/ui/workspaces.md
Remove outdated language about limits on workspaces. ht Joey for bringing this to my attention.
Also minor fixes for typos.
=> Remove outdated workspaces limit language

src/prefect/flows.py
Name and verison are optional, typing now reflects this.
=> Fixed flow types by making name and version arguments optional

docs/concepts/tasks.md
Replace the `concurrency-limit read` command with the `prefect concurrency-limit inspect` command.
Closes #7541
=> Docs: Add inspect to concurrency-limit in concept

RELEASE-NOTES.md
[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.6.8/RELEASE-NOTES.md)
=> Add release notes for 2.6.8

docs/overrides/main.html
=> Update announce bar for 2.6.8

src/prefect/settings.py, tests/test_settings.py
Closes https://github.com/PrefectHQ/prefect/issues/7591
```
PREFECT_LOGGING_LEVEL="debug" python example.py
```
=> Add automatic upper-casing of string log level settings

docs/concepts/infrastructure.md
A user requested clarification in docs https://github.com/PrefectHQ/prefect-aws/issues/156 
=> Add docs about CPU and memory allocation on agent deploying ECS infrastructure blocks

requirements.txt, src/prefect/cli/cloud.py, src/prefect/cli/root.py, src/prefect/client/cloud.py, src/prefect/client/schemas.py, src/prefect/logging/configuration.py, src/prefect/settings.py, src/prefect/utilities/compat.py, tests/cli/test_cloud.py, tests/cli/test_profile.py, tests/conftest.py
This is a tracking pull request for changes to the CLI login experience.
- #6999 
- #7334
=> Tracking: Improvements to the Cloud login experience

docs/overrides/main.html
Updates announce bar for 2.6.9
=> Update announce bar for 2.6.9

RELEASE-NOTES.md
[Rendered](https://github.com/PrefectHQ/prefect/blob/release-notes-2.6.9/RELEASE-NOTES.md#release-269)
=> Add release notes for 2.6.9

src/prefect/cli/flow_run.py, src/prefect/client/orion.py, tests/cli/test_flow_run.py, tests/client/test_orion_client.py
This pull request adds the command `prefect flow-run cancel <run_id>`. 
This CLI command will change the `state.StateType` of a given flow run to `CANCELLED` and the state name to `Cancelling` if possible, and otherwise will exit with error saying that it could not be cancelled. If it could not cancel, it will provide the reason from the abort status. 
There is also a change in the orion client, which changes `set_flow_run_state` to raise `ObjectNotFound` if we get a 404. This brings it in-line with the behavior of the rest of the functions in the orion client. A test has been added for this.
=> Add flow run cancel command

src/prefect/cli/cloud.py, tests/cli/test_cloud.py
This matches our verbiage in the UI.
=> Update login to prompt for "API key" instead of "authentication key"

orion-ui/package-lock.json, orion-ui/package.json, orion-ui/src/pages/FlowRun.vue
Part of https://github.com/PrefectHQ/prefect/pull/7666
This PR makes Cancel button available for feature/flow-run-cancellation
=> Add cancel button to the flow run page in the UI

docs/concepts/deployments.md, docs/concepts/filesystems.md, docs/concepts/storage.md, src/prefect/cli/deployment.py
=> Add GitLab storage block docs to deployment CLI

docs/concepts/infrastructure.md
I think we left them out before.
=> Mention Cloud Run and Container Instance

src/prefect/task_runners.py
As seen in https://github.com/PrefectHQ/prefect/actions/runs/3490782632/jobs/5843551732
If `Future.wait` is called before the task is finished submitting, the concurrent task runner will throw a key error.
=> Fix bug where result event is missing when wait is called before submission completes

tests/test_engine.py
Example failure at https://github.com/PrefectHQ/prefect/actions/runs/3589607088/jobs/6042202580
=> Fix flaky pause test

orion-ui/package-lock.json, orion-ui/package.json
=> Bump @prefecthq/orion-design from 1.1.20 to 1.1.21

src/prefect/utilities/asyncutils.py
I'm working on threadsafe async events in the engine reliability raft and have learned some magic. Here, I use an async event in a threadsafe way which should improve performance as we are no longer running a busy loop on the event loop. We only run tasks in interruptible threads when timeouts are set right now, but to support #7150 we will want sync tasks to be cancellable by default.
=> Update `run_sync_in_interruptible_worker_thread` to use an event
